### ISSUE TITLE
`$VIRTUAL_ENV` not available in pipenv's virtualenv

### ISSUE THREAD

**Issue by carmenbianca** [pypa/pipenv#1116]
Given the following file:

```
import os

print(os.environ.get('VIRTUAL_ENV'))
```

`pipenv run python test.py` will result in printing `None`.

I discovered this bug while trying to install `venvgit2` inside of pipenv, which relies on having `$VIRTUAL_ENV` available inside of its setup.py.

##### Describe your environment

1. OS Type: Debian Stretch
1. Python version: Python 3.5.3
1. Pipenv version: pipenv, version 8.3.2

##### Expected result

`$VIRTUAL_ENV` is present when running scripts from pipenv.

`venvgit2` correctly installs.

##### Actual result

`$VIRTUAL_ENV` is not present.

##### Steps to replicate

Already provided.

**Comment by frankier** [comment]
(Duplicate of https://github.com/pypa/pipenv/issues/829 )
