### ISSUE TITLE
pipenv update for dev dep adds it to regular package

### ISSUE THREAD

**Issue by iddan** [pypa/pipenv#1122]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

##### Describe your environment

1. OS Type: macOS
1. Python version: 3.6
1. Pipenv version: 8.3.2

##### Expected result
To only update version of the package at the dev packages section of the pipfile

Describe what you expected.

##### Actual result

Also added it to dev packages

##### Verbose Log

```bash
Iddans-MBP-4:fptools iddan$ pipenv update pydocs --verbose
Uninstalling pydocs…

Cannot uninstall requirement pydocs, not installed

Installing -e git+https://github.com/kang-health/pydocs.git#egg=pydocs…
Obtaining pydocs from git+https://github.com/kang-health/pydocs.git#egg=pydocs
  Updating /Users/iddan/.local/share/virtualenvs/fptools-2BevdbXl/src/pydocs clone
Requirement already satisfied: click in /Users/iddan/.local/share/virtualenvs/fptools-2BevdbXl/lib/python3.6/site-packages (from pydocs)
Installing collected packages: pydocs
  Running setup.py develop for pydocs
Successfully installed pydocs

Adding -e git+https://github.com/kang-health/pydocs.git#egg=pydocs to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (06359d)!
```

##### Steps to replicate

1. Install a package as dev package
2. Update it

**Comment by sobolevn** [comment]
Yeap, that's happened to me too. 

As a workaround I had to 1. remove from `pipfile` 2. delete 3. reinstall

**Comment by sobolevn** [comment]
@kennethreitz could you please clarify: is this issue invalid or is it fixed now? Thanks!
