### ISSUE TITLE
Idempotent pipenv?

### ISSUE THREAD

**Issue by tehranian** [pypa/pipenv#1139]
Greetings and thank you for this sweet tool, Kenneth! 

I have a question as I try to integrate `pipenv` into our `make` environment... Is there a way to make `pipenv` act w/idempotence?

Ex: With our current setup, we know that `venv/bin/activate` depends on `setup.py`, `requirements.txt`, etc, and we have a well-constructed Makefile such that if those files have not been updated, then re-creating the virtualenv is a no-op (`make: Nothing to be done for 'venv'.`). The virtual environment will only get constructed if `venv/bin/activate` does not exist, or if any of those course files are newer.

I can't seem to figure out how to get `pipenv` to behave this way. ie. Don't do anything if the virtualenv is already in-line with `Pipfile.lock`. `pipenv install` takes a good amount of time to return, and `pipenv update` does a purge before reinstalling everything.

##### Describe your environment

1. MacOS Sierra
1. Python 3.6.3
1. `pipenv, version 8.3.2`

##### Expected result

A super-fast command, where pipenv can check what is in `Pipfile.lock` and compare with the existing virtualenv.

##### Actual result

I don't know of a way to do this.

##### Steps to replicate

Run `pipenv install` repeatedly. If it's a big project each invocation can take some time.

**Comment by tilgovi** [comment]
It might be sufficient, for the described purpose, if `pipenv --venv` could output the location where the venv _would be_ irrespective of whether it exists.

**Comment by cs01** [comment]
+1 for this feature.  I also need a way for my makefiles to have idempotent behavior, as do many others.  I created a similar issue and proposed an implementation (see below). 

Kenneth said he'd like to add the feature but for now it was only a "cool idea to ponder".  I would argue its a required feature for a tool like this.  Perhaps now that it's part of PyPA it can be reconsidered.  

https://github.com/pypa/pipenv/issues/1080

**Comment by techalchemy** [comment]
@tehranian we have a command that does a check but not quite what you want: `pipenv update —dry-run` which I’m assuming you are referring to when you mention the slow update command. Per @cs01 there was discussion of adding this as a part of `pipenv check`, but it just hasn’t been done yet.

**Comment by kennethreitz** [comment]
let's add it!

**Comment by kennethreitz** [comment]
we can communicate if it actually exists or not with exit codes

**Comment by cjw296** [comment]
I wonder how close this comes to my use case for [picky](http://picky.readthedocs.io/en/0.9.1/)?

Asked differently: how would the lock file become out of sync with the venv?

**Comment by andyshinn** [comment]
I couldn't find any way to just "check that `Pipfile.lock` and what is in the virtualenv match". Is this closed because there is now some way to do this or because it is a "won't fix" item?
