### ISSUE TITLE
How about a subcommand to vendor packages?

### ISSUE THREAD

**Issue by HolgerPeters** [pypa/pipenv#1143]
Occasionally I want to vendor packages, so with a `requirements.txt` based workflow, I would have executed  `pip download -r requirements.txt -d vendor`. As far as I can tell, pipenv doesn't have an subcommand to do this. It would be great to have such an option.

Also, in addition it would be cool to choose whether to vendor development packages, or whether to not vendor them.

**Comment by rajasimon** [comment]
Not just for `download` I'm using `install` to manually include the package source code in my project. 

    pip install -r vendor.txt -t vendor/  --upgrade

It will be great pipenv support these features.

**Comment by kennethreitz** [comment]
no, this is not trivial in python

**Comment by HolgerPeters** [comment]
Do I understand this correctly? `pip download` of pinned `sdists` is non-trivial? I wouldn't have thought so, but then, I am not very familiar with pip/setuptools internals.

**Comment by kennethreitz** [comment]
it's more about import styles, absolute vs relative.

**Comment by HolgerPeters** [comment]
Ok.

I found that I can use to solve the issue I had when I opened this ticket.  Maybe useful for people who stumble over this issue when googling for something similar.

```
% pipenv lock -r > foo.txt
% pip download -d vendor -r foo.txt
```
