### ISSUE TITLE
Feature Request: Remove hash from command line prompt after running 'pipenv shell'

### ISSUE THREAD

**Issue by joaqo** [pypa/pipenv#1157]
Hey guys, just started using pipenv and I'm loving it. The only thing that I would like to  change is that when I run `pipenv shell` pipenv automatically adds the environment name along with its hash to my command line prompt. It would be great if we could opt out from having the hash being shown there, as I think it is very unnecessary information,  and makes me shell uglier.

Thanks for the awesome project!

**Comment by kennethreitz** [comment]
thanks for the feedback
