### ISSUE TITLE
`pipenv install aioredis` suggests `redis`

### ISSUE THREAD

**Issue by dfee** [pypa/pipenv#1174]
1. Mac OS 10.13
2. python 3.6
3. pipenv, version 8.2.6

Why does this happen?

![image](https://user-images.githubusercontent.com/262602/33699333-5971de16-dac7-11e7-8119-9b2543df6aaf.png)

**Comment by nateprewitt** [comment]
@kennethreitz I think the threshold on this may need some tweaking again. How did we handle it for Django* packages?

**Comment by kennethreitz** [comment]
this may be acceptable.

**Comment by dfee** [comment]
Obviously, I missed the boat on participating in the conversation about the suggestions feature. However, my gut is that suggestions could be useful in preventing installation of malicious packages (perhaps someone published a `jango` instead of `django` -- blacklisting). Or, perhaps it could be more `apt` like in that it could list all matching packages (perhaps a `search` click command?). Or, maybe it could check the weighting on pypi to see if something is ranked?

However, `aioredis` is different enough from `redis` (it's even ranked with weight 9 on pypi under a search for `aioredis` - where `redis` doesn't even pop up) that I think your suggestion algorithm could be more harmful than helpful.

**Comment by dfee** [comment]
Just wanted to come back and comment now that I'm on a fresh project. The auto-suggest is atrocious.

**Comment by kennethreitz** [comment]
@dfee if you'd like to help improve it (e.g. check pypi weight), i'm all for it!

**Comment by dfee** [comment]
@kennethreitz at face value, that would seem to make sense. But you did comment a month ago that you were satisfied with the algorithm and immediately closed the ticket: https://github.com/pypa/pipenv/issues/1174#issuecomment-349971983
