### ISSUE TITLE
Can't update pipenv  from 8.3.2 to 9.0 on Windows 8/Python 3.6

### ISSUE THREAD

**Issue by pvergain** [pypa/pipenv#1175]
C:\Tmp>pipenv --update

Courtesy Notice: Pipenv 9.0.0 is now available. Automatically upgrading!
Collecting pipenv
  Downloading pipenv-9.0.0.tar.gz (3.9MB)
    100% |████████████████████████████████| 3.9MB 2.2MB/s
Requirement already up-to-date: virtualenv in c:\python36\lib\site-packages (from pipenv)
Collecting pew>=0.1.26 (from pipenv)
  Downloading pew-1.1.1-py2.py3-none-any.whl
Requirement already up-to-date: pip>=9.0.1 in c:\python36\lib\site-packages (from pipenv)
Requirement already up-to-date: requests>2.18.0 in c:\python36\lib\site-packages (from pipenv)
Requirement already up-to-date: flake8>=3.0.0 in c:\python36\lib\site-packages (from pipenv)
Requirement already up-to-date: urllib3>=1.21.1 in c:\python36\lib\site-packages (from pipenv)
Requirement already up-to-date: virtualenv-clone>=0.2.5 in c:\python36\lib\site-packages (from pew>=0.1.26->pipenv)
Requirement already up-to-date: psutil==5.3.1; sys_platform == "win32" in c:\python36\lib\site-packages (from pew>=0.1.26->pipenv)
Collecting setuptools>=17.1 (from pew>=0.1.26->pipenv)
  Downloading setuptools-38.2.4-py2.py3-none-any.whl (489kB)
    100% |████████████████████████████████| 491kB 3.3MB/s
Requirement already up-to-date: idna<2.7,>=2.5 in c:\python36\lib\site-packages (from requests>2.18.0->pipenv)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in c:\python36\lib\site-packages (from requests>2.18.0->pipenv)
Requirement already up-to-date: certifi>=2017.4.17 in c:\python36\lib\site-packages (from requests>2.18.0->pipenv)
Requirement already up-to-date: pyflakes<1.7.0,>=1.5.0 in c:\python36\lib\site-packages (from flake8>=3.0.0->pipenv)
Requirement already up-to-date: pycodestyle<2.4.0,>=2.0.0 in c:\python36\lib\site-packages (from flake8>=3.0.0->pipenv)
Requirement already up-to-date: mccabe<0.7.0,>=0.6.0 in c:\python36\lib\site-packages (from flake8>=3.0.0->pipenv)
Installing collected packages: setuptools, pew, pipenv
  Found existing installation: setuptools 36.6.0
    Uninstalling setuptools-36.6.0:
      Successfully uninstalled setuptools-36.6.0
  Rolling back uninstall of setuptools
Exception:
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\pipenv\patched\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python36\lib\site-packages\pipenv\patched\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\python36\lib\site-packages\pipenv\patched\pip\req\req_set.py", line 814, in install
    **kwargs
  File "c:\python36\lib\site-packages\pipenv\patched\pip\req\req_install.py", line 850, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\python36\lib\site-packages\pipenv\patched\pip\req\req_install.py", line 1063, in move_wheel_files
    isolated=self.isolated,
  File "c:\python36\lib\site-packages\pipenv\patched\pip\wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "c:\python36\lib\site-packages\pipenv\patched\pip\locations.py", line 142, in distutils_scheme
    i = d.get_command_obj('install', create=True)
  File "c:\python36\lib\distutils\dist.py", line 846, in get_command_obj
    klass = self.get_command_class(command)
  File "c:\python36\lib\site-packages\setuptools\dist.py", line 576, in get_command_class
    self.cmdclass[command] = cmdclass = ep.load()
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2409, in load
    return self.resolve()
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'setuptools.command'
Pipenv updated to 9.0.0!

C:\Tmp>pipenv --version
pipenv, version 8.3.2

C:\Tmp>python
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by nateprewitt** [comment]
@pvergain I believe you're going to need to run `pip install -U setuptools` to get around this. I'm not sure why we uninstall setuptools when upgrading but that is likely to cause problems. We'll take a look into trying to prevent this problem.

**Comment by pvergain** [comment]
Hi @nateprewitt !

To resolve the problem I've simply uninstalled pipenv  and successfully reinstalled it.
So it is not a big problem for windows users.
Thanks.
Have a nice day !
----------------------------<-----------------------------------------
pip uninstall pipenv
   ....
  c:\python36\lib\site-packages\pipenv\vendor\yarg\exceptions.py
  c:\python36\lib\site-packages\pipenv\vendor\yarg\package.py
  c:\python36\lib\site-packages\pipenv\vendor\yarg\parse.py
  c:\python36\lib\site-packages\pipenv\vendor\yarg\release.py
  c:\python36\scripts\pipenv-script.py
  c:\python36\scripts\pipenv.exe
Proceed (y/n)? y
  Successfully uninstalled pipenv-8.3.2

C:\Tmp>pip install pipenv
Collecting pipenv
Requirement already satisfied: virtualenv in c:\python36\lib\site-packages (from pipenv)
Requirement already satisfied: pew>=0.1.26 in c:\python36\lib\site-packages (from pipenv)
Requirement already satisfied: requests>2.18.0 in c:\python36\lib\site-packages (from pipenv)
Requirement already satisfied: flake8>=3.0.0 in c:\python36\lib\site-packages (from pipenv)
Requirement already satisfied: urllib3>=1.21.1 in c:\python36\lib\site-packages (from pipenv)
Requirement already satisfied: pip>=9.0.1 in c:\python36\lib\site-packages (from pipenv)
Requirement already satisfied: psutil==5.3.1; sys_platform == "win32" in c:\python36\lib\site-packages (from pew>=0.1.26->pipenv)
Requirement already satisfied: setuptools>=17.1 in c:\python36\lib\site-packages (from pew>=0.1.26->pipenv)
Requirement already satisfied: virtualenv-clone>=0.2.5 in c:\python36\lib\site-packages (from pew>=0.1.26->pipenv)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python36\lib\site-packages (from requests>2.18.0->pipenv)
Requirement already satisfied: idna<2.7,>=2.5 in c:\python36\lib\site-packages (from requests>2.18.0->pipenv)
Requirement already satisfied: certifi>=2017.4.17 in c:\python36\lib\site-packages (from requests>2.18.0->pipenv)
Requirement already satisfied: pyflakes<1.7.0,>=1.5.0 in c:\python36\lib\site-packages (from flake8>=3.0.0->pipenv)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in c:\python36\lib\site-packages (from flake8>=3.0.0->pipenv)
Requirement already satisfied: pycodestyle<2.4.0,>=2.0.0 in c:\python36\lib\site-packages (from flake8>=3.0.0->pipenv)
Installing collected packages: pipenv
Successfully installed pipenv-9.0.0

C:\Tmp>pipenv --version
pipenv, version 9.0.0

---------------------------------->---------------------------------------
