### ISSUE TITLE
Provide a way to force ignore a mismatch when locking

### ISSUE THREAD

**Issue by mjtamlyn** [pypa/pipenv#1176]
It would be great to be able to force an ignore of a mismatch in package dependencies. At present you can't lock a configuration which has has a mismatch, even if the code works properly.

##### Describe your environment

1. OS Type: OSX
1. Python version: 3.6.3
1. Pipenv version: 9.0

##### Expected result

I would like to be able to run `pipenv lock --ignore-mismatch` to create a lockfile which ignores a mismatch generated in version dependencies. Some unhelpful packages include a maximum version in their `install_requires`, even though the version they're preventing you from working with doesn't exist yet.

##### Example

[django-babel](https://github.com/python-babel/django-babel/blob/0.6.1/setup.py#L27) specifies a requirement for `Django<1.12`. The code works absolutely fine with Django 2.0, so this restriction is not relevant. At present the following sequence of commands will fail, and there's no way I can find to generate a lock file to solve it.

```
pipenv install django-babel
pipenv install "Django>=2.0"
```

**Comment by mjtamlyn** [comment]
Er, did you mean to close this with no feedback?

**Comment by kennethreitz** [comment]
out of scope, at the moment. will revisit, for sure.

**Comment by kennethreitz** [comment]
e.g. it's def on our radar

**Comment by mjtamlyn** [comment]
Thanks!

**Comment by nicolaspanel** [comment]
@kennethreitz I'm facing the same issue and it is very annoying. 
Have you been able to propose a work around ?
I didn't found any mention of this on the doc

**Comment by nicolaspanel** [comment]
@mjtamlyn have you found a workaround ?

**Comment by techalchemy** [comment]
@nicolaspanel one simple workaround you can use is to put the dependency you want to override in your `[dev-packages]` and the thing you want to override it in `[packages]`.

FYI tagging kenneth is not a very effective way to get help, but if you need more help you should say more about your situation
