### ISSUE TITLE
Add --debug option

### ISSUE THREAD

**Issue by chimeno** [pypa/pipenv#1181]
Add a ``--debug`` option to pipenv, in order to show useful information of how and where it is installed, also it can include the output of ``--where``, ``--py``, ``--env``, ...etc.

This is something I've first seen in the [httpie](https://httpie.org/doc#python-version) and found it very valuable.

**Comment by Zaab1t** [comment]
If it prints os, python version, pip version and full tracebacks, it would already improve bug reports. We can always add debug logging later as fit.

Will implement this if you say go :)
