### ISSUE TITLE
exit vs deactivate

### ISSUE THREAD

**Issue by sobolevn** [pypa/pipenv#1188]
A proper way to exit from the `pipenv shell` is by `exit` command.
But I am used to `deactivate` through all these years.

And whenever I accidentally use `deactivate` I have to close my terminal window and reopen it again.

Is there a way to fix this somehow?
Maybe some way to recover from the wrong command?
Or disallow `deactivate`?

**Comment by uranusjr** [comment]
I believe you can still `exit` after accidentally using `deactivate`, can you not? I do like the idea of overwriting `deactivate` to say something like “Hey, you might want to use `exit` instead”, like what Python does when you enter `exit` without the parentheses.

**Comment by kennethreitz** [comment]
no

**Comment by sobolevn** [comment]
@uranusjr thanks for your advice! That's a good workaround.

@kennethreitz what's your vision of this problem? Should users just get used to it?

**Comment by kennethreitz** [comment]
@sobolevn basically yes :)
