### ISSUE TITLE
When to add initial flags to subsequent calls

### ISSUE THREAD

**Issue by uda** [pypa/pipenv#1194]
I opened a PR #1193 because I tried to update a project's dependencies using the --clear flag, but that flag isn't currently passed to the subsequent `do_lock` function, and is only used on dry-run calls. While digging, I noticed that the verbose flag isn't passed as well.

So this issue's purpose is to ask, what flags should be "passed around" and when?

**Comment by kennethreitz** [comment]
fixed in master
