### ISSUE TITLE
pipenv --system --deploy installs development packages

### ISSUE THREAD

**Issue by iknite** [pypa/pipenv#1207]
##### Environment

OS Type:` docker python:3.6 (debian/jessie)`
Python version: `Python 3.6.3` 
Pipenv version: `pipenv, version 9.0.0`

Test repository: https://github.com/iknite/pipenv-system-develop

##### Expected result

Docker should be able to build the image since pyenchant doesn't need to be downloaded/executed.
Pyenchant It's a dev-package sub depencency of `sphinxcontrib-spelling` 

##### Actual result

Can't build, a detailed log can be found here:
https://hub.docker.com/r/bbvalabsci/patton/builds/bznbtcjbawc73awzdknw8ih/

(there is more depencies than the isolated git repository, but the result it's the same.)

##### Steps to replicate

```bash
issue_repo=/tmp/pipenv-system-develop-issue && \
git clone https://github.com/iknite/pipenv-system-develop $issue_repo && \
cd $issue_repo && \
docker build .
```

**Comment by nateprewitt** [comment]
Thanks for the raising this issue, @iknite. This is a known issue introduced in 9.0 and we have a fix merged from #1183 which will address this in the next patch release.
