### ISSUE TITLE
docs.pipenv.org is gone

### ISSUE THREAD

**Issue by glyph** [pypa/pipenv#1209]
![untitled](https://user-images.githubusercontent.com/716529/34021911-1e56c5d2-e0f1-11e7-9ee6-3eff44810175.png)

**Comment by nateprewitt** [comment]
Thanks for catching this, @glyph! This is probably a side effect of migrating to the pypa org.

We'll take a look into getting them back up asap.

**Comment by nateprewitt** [comment]
Alright, they're back up. Thanks again!

**Comment by kennethreitz** [comment]
✨🍰✨
