### ISSUE TITLE
flake8 check does not respect projects python version

### ISSUE THREAD

**Issue by Nothing4You** [pypa/pipenv#1212]
`pipenv check --style` appears to run the syntax check depending on its own python version instead of respecting the python version specified in the projects Pipfile.

##### Describe your environment

1. OS Type: Debian 9
1. Python version: `$ python3 -V`: `Python 3.5.3`
1. Pipenv version: `$ pipenv --version`: `pipenv, version 9.0.1`

##### Expected result

No errors.

##### Actual result

```
/home/user/myenv/testfile.py:2:18: E999 SyntaxError: invalid syntax
```

##### Steps to replicate

`pipenv check --style testfile.py`

testfile.py
```py
bar = 'baz'
print(f'foo {bar}')
```

Pipfile
```ini
[[source]]
verify_ssl = true
url = "https://pypi.python.org/simple"
name = "pypi"
[requires]
python_version = "3.6"
[dev-packages]
[packages]
```

**Comment by kennethreitz** [comment]
yes, it is far from perfect.

**Comment by uranusjr** [comment]
AFAIK PyFlakes relies on the Python itself is installed in to analyse the code (with `ast`), and therefore is only capable of linting that exact Python version. There is really no way around this but to install a seperate Flake8 copy inside the project’s virtualenv, and use it (`pipenv run flake8 .`) instead.

Maybe this command can be tweaked to detect whether Flake8 is available in the project’s virtualenv, and use it if possible?

**Comment by kennethreitz** [comment]
I'd be more apt to remove the flake8 checking myself.

**Comment by uranusjr** [comment]
That would be even better.

**Comment by taion** [comment]
It would be great to remove the Flake8 integration. In addition to the integration not working quite right, I also find it quite odd to see Flake8 end up in my production environments via Pipenv.

**Comment by jeremytiki** [comment]
So what would the desired outcome be to fix this ticket?

Should `--style` be removed altogether or is there a better alternative syntax checker to use instead?

**Comment by Nothing4You** [comment]
Since it doesn't work properly and that doesn't seem to be an issue easily solved I'd also prefer removal, if at some point there will be a better solution that could be implemented if people agree on it, however, imo it shouldn't be left in a broken state.

**Comment by uranusjr** [comment]
This is being worked on in #1394.
