### ISSUE TITLE
pipenv install -r' not work

### ISSUE THREAD

**Issue by jaeeonjin** [pypa/pipenv#1215]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

##### Describe your environment
1. OS Type : window 10
2. Python version: 3.5.1
3. Pipenv version: 9.0.1

##### Expected result
**I expected Pipfile.lock updated!!!!!!!!**

##### Actual result
**But I could not get any results. Even if I wait for one hour, the work does not proceed.**

<pre>
PS D:\project\django\myproject> pipenv install -r .\requirements\local.txt<br>
Requirements file provided! Importing into Pipfile…<br>
Pipfile.lock (c23e27) out of date, updating to (47d60b)…<.
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
</pre>

**Pipfile**
<pre>
[[source]]

url = "https://pypi.python.org/simple"
name = "pypi"
verify_ssl = true

[dev-packages]

[packages]

django = "==1.10.8"
django-environ = "==0.4.4"
django-crispy-forms = "==1.7.0"
django-model-utils = "==3.0.0"
pillow = "==4.3.0"
"argon2-cffi" = "==16.3.0"
django-allauth = "==0.34.0"
awesome-slugify = "==1.6.5"
pytz = "==2017.3"
django-redis = "==4.8.0"
redis = ">=2.10.5"
coverage = "==4.4.2"
django-coverage-plugin = "==1.5.0"
sphinx = "==1.6.5"
django-extensions = "==1.9.8"
werkzeug = "==0.13"
django-test-plus = "==1.0.21"
factory-boy = "==2.9.2"
django-debug-toolbar = "==1.9.1"
ipdb = "==0.10.3"
pytest-django = "==3.1.2"
pytest-sugar = "==0.9.0"
</pre>

**base.txt**
<pre>
`# Wheel 0.25+ needed to install certain packages on CPython 3.5+
# like Pillow and psycopg2
# See http://bitly.com/wheel-building-fails-CPython-35
# Verified bug on Python 3.5.1
wheel==0.30.0

# Bleeding edge Django
django==1.10.8 # pyup: >=1.10,<1.11

# Configuration
django-environ==0.4.4

# Forms
django-crispy-forms==1.7.0

# Models
django-model-utils==3.0.0

# Images
Pillow==4.3.0

# Password storage
argon2-cffi==16.3.0

# For user registration, either via email or social
# Well-built with regular release cycles!
django-allauth==0.34.0

# On Windows, you must download/install psycopg2 manually
# from http://www.lfd.uci.edu/~gohlke/pythonlibs/#psycopg

# Unicode slugification
awesome-slugify==1.6.5

# Time zones support
pytz==2017.3

# Redis support
django-redis==4.8.0
redis>=2.10.5

# Your custom requirements go here
</pre>

**local.txt**
<pre>
`# Local development dependencies go here
-r base.txt

coverage==4.4.2
django-coverage-plugin==1.5.0

Sphinx==1.6.5
django-extensions==1.9.8
Werkzeug==0.13
django-test-plus==1.0.21
factory-boy==2.9.2

django-debug-toolbar==1.9.1

# improved REPL
ipdb==0.10.3

pytest-django==3.1.2
pytest-sugar==0.9.0
</pre>

**Comment by kennethreitz** [comment]
we don't support cascading requirements files.
