### ISSUE TITLE
/tmp/pipenv-*-requirement.txt files not cleaned up.

### ISSUE THREAD

**Issue by nguyening** [pypa/pipenv#1217]
This /may/ be related to #142, but the commit that resolved that issue doesn't seem to apply in this case. I run a frequent periodic job that creates a new virtualenv each time, which leads to these files eating up inodes.

Is there some flag or env-var I can set to have these cleaned up? Or some way for me to specify a directory where they can be placed?

I think what I'm looking for is here:

https://github.com/pypa/pipenv/blob/546b39900dcaa17924dc91a290f972ef747ad930/pipenv/utils.py#L464-L465

Which eventually gets called by `utils.resolve_deps`. `tempfile.mkstemp`'s docs state that 
> Caller is responsible for deleting the file when done with it.

##### Describe your environment

1. OS Type
```
$ head -n3 /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
```

1. Python version: `$ python -V`
```
$ python -V
Python 2.7.6
```

1. Pipenv version: `$ pipenv --version`
```
$ pipenv --version
pipenv, version 9.0.1
```

##### Expected result

Temporary files created by `pipenv` are cleaned up after `pipenv install`/`upgrade`.

##### Actual result

```
$ pipenv install pytest
Creating a virtualenv for this project…
⠋New python executable in /home/rnguyen/.local/share/virtualenvs/rnguyen-2uvVmHXa/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/rnguyen/.local/share/virtualenvs/rnguyen-2uvVmHXa
Creating a Pipfile for this project…
Installing pytest…
Collecting pytest
  Using cached pytest-3.3.1-py2.py3-none-any.whl
Collecting six>=1.10.0 (from pytest)
  Using cached six-1.11.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./.local/share/virtualenvs/rnguyen-2uvVmHXa/lib/python2.7/site-packages (from pytest)
Collecting attrs>=17.2.0 (from pytest)
  Using cached attrs-17.3.0-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest)
  Using cached py-1.5.2-py2.py3-none-any.whl
Collecting funcsigs; python_version < "3.0" (from pytest)
  Using cached funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pluggy<0.7,>=0.5 (from pytest)
Installing collected packages: six, attrs, py, funcsigs, pluggy, pytest
Successfully installed attrs-17.3.0 funcsigs-1.0.2 pluggy-0.6.0 py-1.5.2 pytest-3.3.1 six-1.11.0

Adding pytest to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (547f9b)!
$ ls /tmp/pipenv*
/tmp/pipenv-NMk6h4-requirement.txt
```

##### Steps to replicate

Given above.

**Comment by smkent** [comment]
@kennethreitz Is there a reason this was closed? This issue is still present as of the current release version (v10.1.2).
.

**Comment by techalchemy** [comment]
We are aware of it and working on it in other issues

**Comment by nguyening** [comment]
Could I get a link to watch? My search-foo is weak @techalchemy
