### ISSUE TITLE
Unclear message when Pipfile.lock is missing

### ISSUE THREAD

**Issue by jacebrowning** [pypa/pipenv#1224]
The messaging around missing `Pipfile.lock` seems to have regressed.

##### Describe your environment

1. macOS
1. Python 3.6.2
1. pipenv 9.0.1

##### Expected result

I expected to see a message indicating that a `Pipfile.lock` was being generated for me because it was missing. I believe this is a regression in 9.x.

##### Actual result

```
$ pipenv install --dev
Pipfile.lock () out of date, updating to (8ae34d)…
```

##### Steps to replicate

1. Delete `Pipfile.lock`
2. Run `pipenv install`

**Comment by uranusjr** [comment]
I tried but couldn’t reproduce this on either my macOS or Windows environment (with 3.6.3). 🙁

Pipenv 9.0.1 correctly show

```
Pipenv.lock not found, creating…
```

**Comment by techalchemy** [comment]
@jacebrowning I actually can't replicate this either, and that's with a fresh pipenv install from PyPI and switching down to python 3.6.2 as well.  What are your locale settings? Which pieces are homebrew installed? Or to try the simple route which just occurred to me after typing some other stuff up, what is the output of `pipenv --where`? Maybe there is a Pipfile or a lockfile somewhere above your working directory

```console
 ◰³ tempenv-728c297066e8d  /t/test2  ls
Pipfile
 ◰³ tempenv-728c297066e8d  /t/test2  python --version
Python 3.6.2
 ◰³ tempenv-728c297066e8d  /t/test2  pipenv --version
pipenv, version 9.0.1
 ◰³ tempenv-728c297066e8d  /t/test2  pip freeze | grep pipenv
pipenv==9.0.1
```

### Install

```console
 ◰³ tempenv-728c297066e8d  /t/test2  pipenv install --python=3.6.2 --dev
Creating a virtualenv for this project…
Using /home/hawk/.pyenv/versions/3.6.2/bin/python3.6m to create virtualenv…
⠋Running virtualenv with interpreter /home/hawk/.pyenv/versions/3.6.2/bin/python3.6m
Using base prefix '/home/hawk/.pyenv/versions/3.6.2'
New python executable in /home/hawk/.local/share/virtualenvs/test2-h6PFdzq5/bin/python3.6m
Also creating executable in /home/hawk/.local/share/virtualenvs/test2-h6PFdzq5/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/hawk/.local/share/virtualenvs/test2-h6PFdzq5
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (ef08e8)!
Installing dependencies from Pipfile.lock (ef08e8)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 21/21 — 00:00:10
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

### Delete lockfile and reinstall

```console
 ◰³ tempenv-728c297066e8d  /t/test2  rm -rf Pipfile.lock
 ◰³ tempenv-728c297066e8d  /t/test2  pipenv install --dev
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (ef08e8)!
Installing dependencies from Pipfile.lock (ef08e8)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 21/21 — 00:00:03
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

**Comment by jacebrowning** [comment]
My apologies. I could've sworn I was seeing this in a reproducible manner, because I was seeing this message in several of our projects, but it turns out this is simply an artifact of the way we are generating projects.

In order to force a generated project to lock dependencies on first install, we're using:
 `{"_meta": {"hash": {"sha256": ""}}}`
as a placeholder `Pipfile.lock`.

**Comment by techalchemy** [comment]
No worries, thanks for the update!
