### ISSUE TITLE
Add something like npm watch in pipenv.

### ISSUE THREAD

**Issue by RatanShreshtha** [pypa/pipenv#1227]
It is just my suggestion to add watch feature in pipenv that resembles npm watch, npm watch makes you able to run some scripts whenever you save for files after a change.

One of the use cases of this feature might be to run all your unit tests whenever you make changes to your files, thus giving you instant feedback about your changes.

And another use case could be to run static code analysis on your codebase whenever you make changes to your files.

I have been using pipenv for a while and I think this is a good feature for pipenv.

**Comment by lwm** [comment]
Would be great! Can we bundle pytest and use https://github.com/tarpas/pytest-testmon 🙃

**Comment by RatanShreshtha** [comment]
@lwm  I don't get your point please explain it a little bit in details.

**Comment by mimischi** [comment]
@RatanShreshtha I think his point was that the package `pytest-testmon` already does what you're asking for. It's probably not in the scope of responsibilities of `pipenv` to do that.

**Comment by Zaab1t** [comment]
Hello. I have started developing something like this. It is still in such an early stage, that it doesnt even have a name yet. If you are interested, contributors are very welcome. I have not worked with `npm watch`, so there might be features I have not even thought of.

The project can be found at https://github.com/Zaab1t/workout-playlist.

Hopefully all interaction with the module can be done through its `interact` function, which I hope will be so flexible that it can also be used in https://github.com/ofek/hatch and other projects alike.

**Comment by uranusjr** [comment]
Now that #1433 is in I think this can be closed. The behaviour can be better handled with a standalone command and a user entry in the `scripts` section.
