### ISSUE TITLE
No hashes for VCS or tarball dependencies

### ISSUE THREAD

**Issue by theunraveler** [pypa/pipenv#1231]
Hello.

I'm not sure if this is a limitation of `pipenv` or `pip` itself, but when generating a `requirements.txt` file via `pipenv lock -r`, both VCS and tarball dependencies do not contain a `--hash` parameter, which means that I cannot install from the file on systems that don't support `pipenv` yet (like Elastic Beanstalk).

Here's my example `Pipfile`:

```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

six = "*"
pyeti = {git = "https://github.com/cehdeti/pyeti.git", editable = true}


[requires]

python_version = "3.4"
```

And here is the resulting `requirements.txt`:

```
six==1.11.0 --hash=sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb  --hash=sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9
-e git+https://github.com/cehdeti/pyeti.git@c829508895fb2f39281aad784993cf2a89d526dd#egg=pyeti
```

And here's the error that `pip` throws when I attempt to install from `requirements.txt`:

```
...
Obtaining pyeti from git+https://github.com/cehdeti/pyeti.git@187f9e6b92d46a08dc974573b1bdf41ff0308702#egg=pyeti (from -r /opt/python/ondeck/app/requirements.txt (line 60))
  The editable requirement pyeti from git+https://github.com/cehdeti/pyeti.git@187f9e6b92d46a08dc974573b1bdf41ff0308702#egg=pyeti (from -r /opt/python/ondeck/app/requirements.txt (l
ine 60)) cannot be installed when requiring hashes, because there is no single file to hash.
  2017-12-20 19:15:08,059 ERROR    Error installing dependencies: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit st
atus 1
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 22, in main
      install_dependencies()
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 18, in install_dependencies
      check_call('%s install -r %s' % (os.path.join(APP_VIRTUAL_ENV, 'bin', 'pip'), requirements_file), shell=True)
    File "/usr/lib64/python2.7/subprocess.py", line 541, in check_call
      raise CalledProcessError(retcode, cmd)
  CalledProcessError: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1 (Executor::NonZeroExitStatus)
```

I tried the same thing but with a `.tar.gz` file from GitHub and without the `editable` attribute, but ran into the same issue.

Thanks, and please let me know if you'd like me to clarify anything or provide any additional info.

##### Describe your environment

1. MacOS 10.13.2
1. Python version: `3.6.4`
1. Pipenv version: `8.3.2` (also tried with `9.0.1`, same issue)

##### Expected result

All of the dependencies in the generated `requirements.txt` have a `--hash` parameter, or there should be a flag to leave off `--hash` parameters entirely.

##### Actual result

VCS and tarball dependencies do not have a `--hash` parameter.

**Comment by theunraveler** [comment]
Related: https://github.com/pypa/pip/issues/4344

**Comment by bbarker** [comment]
This appears to be a problem for us as well

**Comment by charlax** [comment]
It was unclear to me if closed meant fixed, and I can confirm it is fixed with version 11.9.0. The hashes are not included at all in the generated `requirements.txt`.

**Comment by bbarker** [comment]
@charlax do you mean 'not fixed with version 11.9.0'?

**Comment by charlax** [comment]
Sorry, I should have clarified "hash are not included" and "not working with Elastic Beanstalk". I'm not sure what you're doing differently, but with the current `pipenv` version the `requirements.txt` generated from a `Pipfile` that included an editable dependency works fine for me on Elastic Beanstalk.

So, (1) the hashes are not included at all now (2) but it does work with Elastic Beanstalk.

Here's what the generated `requirements.txt` kind of look like (most lines omitted for brevity). Note the absence of hashes for all dependencies (not only the editable ones).

```
-e git+https://github.com/kennethreitz/records@f2c5307d76e7909e7b0476e0b004590486ebdf37#egg=records
aiofiles==0.3.2
alembic==0.9.8
...
```

**Comment by techalchemy** [comment]
@charlax correct. This is the fix. We don’t hash vcs deps because it’s not possible. That means their dependencies also can’t be hashed
