### ISSUE TITLE
Package editable instalation fail

### ISSUE THREAD

**Issue by uetoyo** [pypa/pipenv#1239]
When I use `pipenv install --dev` then pipenv cannot install package in editable mode for the first time.

##### Describe your environment

1. OS Type: Ubuntu
1. Python version: 3:6
1. Pipenv version: 8.2.6

##### Expected result

No error message is reported.

##### Actual result

```Installing dependencies from Pipfile.lock (096e63)…
An error occurred while installing -e .! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 32/32 — 00:00:17
Installing initially–failed dependencies…
Success installing -e .!▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:00
```

##### Steps to replicate
```
pipenv install --dev
```

**Comment by techalchemy** [comment]
Hi @uetoyo thanks for the report. You didn’t actually experience a bug, so I’m going to close this issue. 

To clarify, pipenv installs dependencies in parallel and sometimes this causes odd race conditions. It is built into pipenv to retry failed installs sequentially, which it did, and which was successful. That’s why you don’t have any actual errors and you have an exit code of 0. 

I would also recommend upgrading pipenv. Version 8.2.6 is somewhat out of date
