### ISSUE TITLE
Running the tests leaves a bunch of virtualenvs lying around

### ISSUE THREAD

**Issue by OddBloke** [pypa/pipenv#1243]
When I run the pipenv tests (using `pipenv run pytest -n 8 tests`), I end up with a bunch of virtualenvs left:

```
$ ls -d ~/.virtualenvs/pipenv[^-]* | wc -l
42
```

which take up a fair bit of space:

```
$ du -h -c ~/.virtualenvs/pipenv[^-]* | tail -n1
1.2G	total
```

##### Describe your environment

1. OS Type: Ubuntu 17.10
1. Python version: 3.6.3
1. Pipenv version: dev

##### Expected result

No Virtualenv Left Behind

##### Actual result

Virtualenv Left Behind

##### Steps to replicate

`pipenv run pytest -n 8 tests`

**Comment by OddBloke** [comment]
I'll take a few minutes to dig in to this.

**Comment by techalchemy** [comment]
Yep, I have actually no idea why that happens but I just wrote a cleanup script that uses invoke (if you have it installed):

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from invoke import task, run
from pathlib import Path
import os
import shutil

@task
def cleanup(ctx):
    venv_dir = os.environ.get('WORKON_HOME', '~/.local/share/virtualenvs/')
    base_path = Path(venv_dir).expanduser()
    if base_path.exists():
        folders = base_path.glob('pipenv*project*')
        for folder in folders:
            print('Removing folder: {0}'.format(folder))
            shutil.rmtree(folder)
```

And then from the commandline:
```console
 ~/git  inv cleanup
Removing folder: /home/hawk/.local/share/virtualenvs/pipenvk0bp3lvxproject-dLJfX5dR
Removing folder: /home/hawk/.local/share/virtualenvs/pipenv57d8rjpdproject-AglnS1JN
Removing folder: /home/hawk/.local/share/virtualenvs/pipenva23j4y_1project-L5db6JOr
Removing folder: /home/hawk/.local/share/virtualenvs/pipenv57vcn6d4project-u0WaH-W2
Removing folder: /home/hawk/.local/share/virtualenvs/pipenvtq3c5n60project-j3pb2Xs9
```

**Comment by ncoghlan** [comment]
The brute-force shell based version:

    rm -rf ~/.local/share/virtualenvs/pipenv*project-*

**Comment by ncoghlan** [comment]
@kennethreitz Even with `test_legacy` gone, I'm still seeing the test suite leave these directories behind.

**Comment by techalchemy** [comment]
@ncoghlan I meant to add a provision to my temporary file cleanup to also clean up virtualenvs created during testing, but I must have forgotten.  I think I might have tried setting `$WORKON_HOME` initially but now that I have backported python 3's `TemporaryDirectory` + vendored a backport of `weakref.finalize` we might have more success cleaning up temporary directories with these resources.

Since that might get messy due to process restrictions / the open file handle issues on windows we've touched on in a few other places, we might want to just pass this to a subprocess call on windows and let the OS handle it.

**Comment by uranusjr** [comment]
By the way, I noticed the other day the tests also generate a `.env` file in the project. I’m not sure if it’s still generated now, but if it is that’s another thing to get rid of (by setting the working directory, I imagine?) when going through these changes.

**Comment by kennethreitz** [comment]
not anymore
