### ISSUE TITLE
Deploy to heroku pipenv project

### ISSUE THREAD

**Issue by anuj9196** [pypa/pipenv#1246]
- [x] Question

I have created a Django project with virtual environment created with pipenv.

Now I want to deploy this to heroku and as per heroku it required a `requirements.txt` file.

How can I generate the `requirements.txt` usingin `pipenv`.

I tried `pipenv freeze > requirements.txt`

I gives
```
Error: No such command "freeze".
```

**Comment by uranusjr** [comment]
To freeze into a `requirements.txt` you can use `pipenv lock --requirements`. Use `pipenv lock --help` to learn more.

But [Heroku provides native support to Pipenv](https://github.com/heroku/heroku-buildpack-python), so it can read directly from `Pipfile.lock`. You don’t need that `requirements.txt`.

**Comment by uranusjr** [comment]
I just realised they have updated their [Getting Started on Heroku with Python](https://devcenter.heroku.com/articles/getting-started-with-python#introduction) guide to use Pipenv. This could be more useful walking you through what you need to provide for a Pipenv-based Heroku project.

I wonder whether it is an oversight they didn’t update the [Python on Heroku entry page](https://www.heroku.com/python) as well. The screencast still shows an example using Virtualenv and Pip directly. /cc @kennethreitz

**Comment by anuj9196** [comment]
How can I move the project to any other local directory and setup a fresh virtual environment there using `Pipenv.lock` file?

**Comment by uranusjr** [comment]
Move both `Pipfile` and `Pipfile.lock` to any directory, and run `pipenv install` (or `pipenv install --dev` depending on what you want). A new virtualenv will be created. (Also you can `pipenv --rm` in the old directory before you move to delete the old virtualenv.)

**Comment by anuj9196** [comment]
Thanks

**Comment by spookyUnknownUser** [comment]
Seems like both pages on heroku don't use pipenv now 🤔

**Comment by newtfrank** [comment]
You can also run pipenv run pip freeze > requirements.txt to create the requirements file

**Comment by abumalick** [comment]
if you have a pipenv file in your repository heroku will install the packages from it.

![image](https://user-images.githubusercontent.com/8377185/61723242-4ef7c280-ad5b-11e9-9f98-143070a67115.png)

**Comment by philgyford** [comment]
FWIW, I opened a ticket at Heroku to ask about pipenv support, given that it's no longer in their docs. They said they have no plans to remove support for it (and they use it on many of their internal tools). The docs should be updated at some (unspecified) point.
