### ISSUE TITLE
Homebrew install method

### ISSUE THREAD

**Issue by richardcooper** [pypa/pipenv#1248]
Commit 76e5faa1f176fc7dbac7b686e90d76016af96afd deleted the homebrew install instructions from the docs. May I ask why?

I would like to see these instructions reinstated. (I have been maintaining the homebrew formula for pipenv, so I'm biased) 

However, if the decision to not document homebrew based installation stands, then there are a few other mentions in the docs and README which need cleaning up. Including a link on https://docs.pipenv.org which currently 404s.

**Comment by erinxocon** [comment]
Question @richardcooper did we ever get the recipe for homebrew to rely on homebrews cpython3 and not apples distribution of python3?  I believe that was why the instructions were removed.

**Comment by richardcooper** [comment]
@erinxocon. Yes. The patch which you were working on to use homebrew's cpython3 landed a couple of weeks ago.

There's still a question of why pipenv cares about relative v's absolute paths but we're using absolute paths as a workaround for now.

**Comment by richardcooper** [comment]
@erinxocon @kennethreitz

Have you decided about how you would like to proceed with Homebrew?

I was about to send a PR to homebrew to update their pipenv formula to v9.0.3 when I saw https://github.com/Homebrew/homebrew-core/issues/22429 and decided to hold off.

I am happy to continue to maintain the pipenv homebrew formula for the foreseeable future, or leave that task to a member of the core pipenv team. Whichever you prefer. However, I would like to see homebrew reinstated as an officially recommended way to install pipenv.

**Comment by kennethreitz** [comment]
@richardcooper we'd love for you to maintain the forumla for us.

**Comment by richardcooper** [comment]
Added #1495 to reinstate the homebrew docs
