### ISSUE TITLE
virtualenv path is re-used for new project of new directory

### ISSUE THREAD

**Issue by Dowwie** [pypa/pipenv#1252]
The virtualenv name suffix is insufficiently random.  A removed directory that is re-created will obtain "ownership" of the virtualenv that was created for the prior project of the same directory.

##### Describe your environment

Debian 9
Python 3.6
Pipenv 9.0.1

##### Expected result

A sufficiently randomized virtualenv suffix for every virtualenv created

##### Steps to replicate

mkdir something
cd something
pipenv install requests

```
Creating a virtualenv for this project…
⠋Using base prefix '/usr/local'
New python executable in /home/dowwie/.local/share/virtualenvs/somethin-6_rmC2iw/bin/python3.6
Also creating executable in /home/dowwie/.local/share/virtualenvs/somethin-6_rmC2iw/bin/python
Installing setuptools, pip, wheel...done.
```
cd ..
rm -rf something
mkdir something
cd something
pipenv install requests

```
Creating a Pipfile for this project…
Installing requests…
Requirement already satisfied: requests in /home/dowwie/.local/share/virtualenvs/somethin-6_rmC2iw/lib/python3.6/site-packages
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/dowwie/.local/share/virtualenvs/somethin-6_rmC2iw/lib/python3.6/site-packages (from requests)
Requirement already satisfied: idna<2.7,>=2.5 in /home/dowwie/.local/share/virtualenvs/somethin-6_rmC2iw/lib/python3.6/site-packages (from requests)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/dowwie/.local/share/virtualenvs/somethin-6_rmC2iw/lib/python3.6/site-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in /home/dowwie/.local/share/virtualenvs/somethin-6_rmC2iw/lib/python3.6/site-packages (from requests)
```

**Comment by uranusjr** [comment]
Well, the suffix isn’t random, but computed from the absolute path to the project. Since your two projects are at the same location, the suffix is destined to clash. I’m not sure this is an issue Pipenv focuses to resolve, however, since you can easily fix this by `pipenv --rm` (since you don’t want the old virtualenv anyway).

(One possible fix to this is to take the root directory’s `os.stat` into account, but that might not work well with version control tools removing/re-creating a directory between revision switches.)

**Comment by Dowwie** [comment]
@uranusjr  Thanks for the fast response.  ```pipenv --rm``` does help.  Maybe documenting this behavior might be all the is needed.

**Comment by techalchemy** [comment]
@Dowwie thanks for the report. This behavior is built into pipenv and is an intentional design, so I don’t think it’s going to change. I’m going to go ahead and close this out, but let us know if you encounter any issues!
