### ISSUE TITLE
Same directory maps to two venv hash value

### ISSUE THREAD

**Issue by eyc88** [pypa/pipenv#1256]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

##### Describe your environment

1. OS Type MacOSx High Sierra
1. Python version: `$ python -V` Python 3.6.4
1. Pipenv version: `$ pipenv --version` pipenv, version 9.0.1
##### Expected result

I created a virtual environment when I first "pipenv run python", which resulted in a virtual environment called "/Users/username/.local/share/virtualenvs/directory_name-w7QgSO1E"

Later on, I run "pipenv run python" in the exact same directory, and I expected the virtual env with directory_name-w7QgSO1E to be launched.  However, that did not happen, instead, a new virtual environment called "directory_name-A5OeF-2g" has been created!

What's even more shocking is the fact that, when I run "pipenv run python" even later, a new version of "directory_name-A5OeF-2g" is created, overwriting the old one.  Do you have any idea what is going on?

This behavior comes at random -- in other words, I can't specify the steps to create this problem.  However, it happened to me just at the second day of using pipenv, so I guess it should not be something that rarely occurs.

Additional question:  From Issue 796 (How does pipenv know the virtualenv for current project ?) I learnt that the postfix of the virtual environment is a hash of the absolute path.  Is there anyway to access the hash function so I can check which hash is the correct one?

**Comment by uranusjr** [comment]
The hash is computed with SHA256. You can find the implementation here: https://github.com/pypa/pipenv/blob/master/pipenv/project.py#L134

I’m wondering if this is related to the default macOS disk format being case-insensitive-but-preserving. Can you provide the actual absolute path to the project, so I can try if the two hashes can be produced by different casing?

**Comment by eyc88** [comment]
@uranusjr 
1.  I "pipenv run python" in two different directory whose names are the same but different case.  I confirmed that two hashes can produce different casing (Since macOSx is case-insensitive, I need to delete one directory before I can create the other).
2.  However, the problem does not lie in casing.  The reason is simply because I have moved the directory into a folder.  So it is quite reasonable that the hash is different.
3.  When I move the directory and "pipenv run python", I noticed that (a) a new virtual environment is created with nothing inside (b) the old Pipfile does not reflect the fact that the new virtual environment is empty.  Namely, the old Pipfile is not deleted. (c) When I install new packages in the new environment, the new package only *appends* to the Pipfile.  In other words, if the old environment has package "A", "B", and "C", and the new environment has package "D", one will end up with a Pipfile that has "A", "B", "C" and "D" while only "D" installed.  Simply put, there is a syncing issue between the Pipfile and the virtual environment.
4.  I have a few suggestions:  (a) When "pipenv run python" is executed, pipenv should automatically check if the new virtual environment is identical to the one specified in the working directory.  If not, it should be rebuild according to the Pipfile in the working directory.  (b) That being said, I think there should be another copy of Pipfile (or something equivalent) that resides in the virtual environment directory to facilitate the comparison.  --  Just my two cents.
5.  The problem that "pipenv run python" will create a brand new virtual environment, overwriting the old one -- is still a mystery to me.  Although it only occurred once.
6.  (out of my own curiosity) Would you please kindly point to me that in the code:
hash = hashlib.sha256(self.pipfile_location.encode()).digest()[:6]
encoded_hash = base64.urlsafe_b64encode(hash).decode()
what is "self.pipfile_location" when the absolute path is "/Users/user_a/directory_b"?  I tried running the code with the string "/Users/user_a/directory_b" (which is the string resulting from running pwd in the working directory) but it is not returning the string I see from pipenv.  Is there any pre-processing to the absolute path?

**Comment by felipemfp** [comment]
When you move the directory, run: `pipenv install`

**Comment by eyc88** [comment]
Sure.  However, I feel if the default behavior of "pipenv install A" is to install A and append A to the Pipfile, pipenv should verify that all packages in the Pipfile are already installed -- Just my two cents -- or there is an inconsistency between the environment and the Pipfile.

**Comment by felipemfp** [comment]
I think it's up to the user. But a warning like "These packages aren't installed: foo; bar;" would be nice.

**Comment by ernstki** [comment]
> The hash is computed with SHA256. You can find the implementation here: https://github.com/pypa/pipenv/blob/master/pipenv/project.py#L134

Things have changed since 2018, and if you're looking for this code _now_, it's in `pipenv/utils/venv_locator.py`:

https://github.com/pypa/pipenv/blob/3f1b272abd51d7d7ab7f5935bb6b25da86e93e8b/pipenv/utils/venv_locator.py#L196-L200

Here's a one-liner that makes it a bit clearer, should work on a typical Mac/BSD/Linux system:

```bash
printf $PWD/Pipfile | openssl dgst -sha256 -binary | cut -c1-6 | base64 | cut -c1-8
```
