### ISSUE TITLE
pipenv client can't report some errors when importing requirements

### ISSUE THREAD

**Issue by dereksantibanez** [pypa/pipenv#1261]
`pipenv install` suffers an exception when trying to report on failures to import a requirements.txt.

This is under python3.

For example, to reproduce, under python3.6:

```
$ cat req.txt
-e thing

$ pipenv install -r req.txt
Requirements file provided! Importing into Pipfile…
Traceback (most recent call last):
  ...<snip>...
  File "/Users/dsantibanez/Library/Python/3.6/lib/python/site-packages/pipenv/cli.py", line 1813, in install
    if error and e:
UnboundLocalError: local variable 'e' referenced before assignment
```

This is because some pipenv cli `except` clauses are shadowing a variable, and their `finally` is expecting to be able to use that variable.

https://github.com/pypa/pipenv/blob/50ad7746eebb397e97d9403456921743d2ffb3bb/pipenv/cli.py#L1795
https://github.com/pypa/pipenv/blob/50ad7746eebb397e97d9403456921743d2ffb3bb/pipenv/cli.py#L1799
https://github.com/pypa/pipenv/blob/50ad7746eebb397e97d9403456921743d2ffb3bb/pipenv/cli.py#L1804
https://github.com/pypa/pipenv/blob/50ad7746eebb397e97d9403456921743d2ffb3bb/pipenv/cli.py#L1813

By line 1813, `e` is out of scope.

**Comment by nateprewitt** [comment]
Thanks for catching this @dereksantibanez. I've pushed up 68d1a29 which should have this addressed in the next release.
