### ISSUE TITLE
Doesn't install and run properly under Windows 10 with non-English locale and username

### ISSUE THREAD

**Issue by reflechant** [pypa/pipenv#1265]
#####
My environment:
Windows 10 64-bit with latest updates
Python 3.6.4
Pipenv 9.0.1

##### Expected result
I expect pipenv to run from command line properly

##### Actual result
`C:\Users\Рома>pipenv --verbose
  File "C:\Users\Рома\AppData\Local\Programs\Python\Python36\Scripts\pipenv-script.py", line 1
SyntaxError: Non-UTF-8 code starting with '\xf0' in file C:\Users\Рома\AppData\Local\Programs\Python\Python36\Scripts\pipenv-script.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`
It works if run with `python -m pipenv` though
NOTE: I attached the pipenv-script.py inside a ZIP archive
[pipenv-script.zip](https://github.com/pypa/pipenv/files/1601357/pipenv-script.zip)

##### Steps to replicate
1) Install pipenv under Windows 10 with **non-English** locale and username (in order to do it you need to first update to pip10 with easy_install https://github.com/pypa/pip/archive/master.zip as pip9.0.1 itself is _unusable under non-English locale_)
2) Open Windows 10 console, type `pipenv` and press Enter

NOTE: using git bash doesn't help in any way.

P.S. The error is trivial and looks like it's not in pipenv itself but in install scripts. Maybe it's distutils, maybe it's pip, maybe it's Python for Windows. In such a case please, tell me where to report the issue or report to the corresponding project developers.

**Comment by habnabit** [comment]
This is not a pipenv problem. `easy_install` is writing a broken `pipenv-script.py`. About to file an issue against [setuptools](/pypa/setuptools) for it.

**Comment by jaraco** [comment]
Easy_install is generally deprecated in favor of `pip install`. What happens if you uninstall pipenv and re-install it using pip?

**Comment by reflechant** [comment]
@jaraco i installed pipenv using pip10.0.0dev which i installed using easy_install.

**Comment by jaraco** [comment]
Easy_install is generally deprecated in favor of pip install. What happens if you uninstall pipenv and re-install it using pip?

**Comment by jaraco** [comment]
If you installed pipenv via pip, then the `pipenv` script is installed by `pip` and `distlib`, so setuptools isn't implicated.

**Comment by habnabit** [comment]
@jaraco so far I haven't found any evidence that this was installed using anything but setuptools/easy_install, considering the `EASY-INSTALL-ENTRY-SCRIPT` banner.

**Comment by jaraco** [comment]
Here's what the script in that zip contains:

```
#!c:\users\ðîìà\appdata\local\programs\python\python36\python.exe
# EASY-INSTALL-ENTRY-SCRIPT: 'pipenv==9.0.1','console_scripts','pipenv'
__requires__ = 'pipenv==9.0.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('pipenv==9.0.1', 'console_scripts', 'pipenv')()
    )
```

Indeed, that script looks to have been generated by easy_install, which is surprising considering

> i installed pipenv using pip10.0.0dev

I would not have expected any version of pip to use easy_install to build scripts. I'll see if I can verify.

**Comment by jaraco** [comment]
So to my surprise, I do see the EASY-INSTALL-ENTRY-SCRIPT in the script even when installing with pip 9.0.1. So easy_install _is_ apparently implicated.

**Comment by jaraco** [comment]
Aha. I think I may have figured out my confusion. It seems pip installs the scripts using distlib only when it's installing from wheels, but when installing from source, it invokes setuptools (which internally uses easy_install). So you likely would not have encountered this issue if pipenv provided wheels for its distribution.

Can you confirm that - what happens if you:

```
pip uninstall pipenv
pip install wheel
pip wheel pipenv --no-deps
pip install ./pipenv-*.whl
```

**Comment by reflechant** [comment]
Being installed that way (with pip9.0.1) pipenv works just ok.
