### ISSUE TITLE
Why "Compatibility with **three** virtualenvs"?

### ISSUE THREAD

**Issue by guettli** [pypa/pipenv#1267]
On https://docs.pipenv.org/ I read

> The use of Python 3 is highly preferred over Python 2, when installing Pipenv. Compatibility with **three** virtualenvs is greatly improved when using Python 3 as the installation target.

I don't understand the word "three" here. Is this a typo?

**Comment by uranusjr** [comment]
I think it means *virtualenvs created with `pipenv --three`*.
