### ISSUE TITLE
Downloading incorrect hashes from PyPI

### ISSUE THREAD

**Issue by malramsay64** [pypa/pipenv#1272]
I am not sure whether this is more of an issue with Pipenv or the package I am trying to install, but I figure the chances are high other packages could have similar issues.

The package in question [numpy-quaternion](https://pypi.python.org/pypi/numpy-quaternion) has two 'versions' on PyPI, (note the extra zero in the second)
- `numpy-quaternion 2017.11.26.19.0.13`     (wheels)
- `numpy-quaternion 2017.11.26.19.00.13`   (source)
The wheels are under the first version number while the source is under the second.

When installing by pipenv the sha256 of the source is included in the pipenv file, as confirmed by manually downloading and hashing, despite having the single zero version number in both the install specification and the Pipenv.lock file.

When running the check for the hash, which I am doing by copying the Pipfile and Pipfile.lock to different directories or machines the wheel is downloaded and so fails the hash comparison.

I am able to work around the problem by manually adding the hashes of the wheels to the Pipfile.lock.

##### Describe your environment

1. macOS, Fedora 26, CentOS 7.4
1. Python version: 3.6.4
1. Pipenv version: 9.0.1

##### Expected result

Installation

##### Actual result

```
THESE PACKAGES DO NOT MATCH THE HASHES FROM Pipfile.lock!. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    numpy-quaternion==2017.11.26.19.0.13 from https://pypi.python.org/packages/53/e7/d397c3cc6cf3f11d04dfbf89303d4622b5613f1387869ba8e5fb3fca4f6b/numpy_quaternion-2017.11.26.19.0.13-cp36-cp36m-macosx_10_7_x86_64.whl#md5=59f1b4a136bd1063d591d52a0fa3075e (from -r /var/folders/j8/26018yc51bx86z2k50nj8m9m0000gn/T/pipenv-2c1b0yxh-requirement.txt (line 1)):
        Expected sha256 3e3cad8e769934628fae9beefdb19418db9519d9b8a8c5eee7c78778fc492988
             Got        3612c26c4e0a1c16019f6bc80fbfe48ea4318d16d00d2c1d5a0b800e7526334d

```
##### Steps to replicate
```
pipenv install numpy-quaternion==2017.11.26.19.0.13
```
Copy/move Pipfile and Pipfile.lock to new directory/machine to create new virtualenv
```
pipenv install
```

Modified Pipenv.lock for python 3.6 Linux/macOS
```
{
    "_meta": {
        "hash": {
            "sha256": "4961af33ad7fde467ea9ac9781b297deee3cd07d27e9726f34aae7c82d969f72"
        },
        "host-environment-markers": {
            "implementation_name": "cpython",
            "implementation_version": "3.6.4",
            "os_name": "posix",
            "platform_machine": "x86_64",
            "platform_python_implementation": "CPython",
            "platform_release": "17.3.0",
            "platform_system": "Darwin",
            "platform_version": "Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64",
            "python_full_version": "3.6.4",
            "python_version": "3.6",
            "sys_platform": "darwin"
        },
        "pipfile-spec": 6,
        "requires": {},
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "numpy-quaternion": {
            "hashes": [
                "sha256:3612c26c4e0a1c16019f6bc80fbfe48ea4318d16d00d2c1d5a0b800e7526334d",
                "sha256:057446053be4ce72a951f919740c83a7c9fb5f2ffac22b2018a2e81a21ad2b72"
            ],
            "version": "==2017.11.26.19.0.13"
        }
    },
    "develop": {}
}
```

**Comment by Zaab1t** [comment]
I found that this was introduced between https://github.com/pypa/pipenv/compare/v8.3.2...v9.0.1.

**Comment by kennethreitz** [comment]
Closing, hoping it'll come up again if this truly an issue.
