### ISSUE TITLE
Relative Path for Packages using Command Line

### ISSUE THREAD

**Issue by EmmanuelObo** [pypa/pipenv#1276]
Is there a way to move certain packages into the project's directory? Because packages that use the CLI require different path structures than the one initialized in the code. Here is an example of when I was trying to use Flask-Migrate. 

For example:

`from myapp import app`

Works fine when I'm running the app.
But when I run a flask-migrate command I get:

`ModuleNotFoundError: No module named 'myapp'`

Then I have to change it to a relative path for it to work:

`from .myapp import app`

Is there a workaround for this?

**Comment by techalchemy** [comment]
Hi @EmmanuelObo thanks for opening this issue.  It doesn't appear to be related to pipenv, but I'd recommend checking out information about module search paths in python to resolve this issue.  I'm going to go ahead and close this, good luck resolving your problem
