### ISSUE TITLE
Could not fetch URL https://pypi.python.org/simple/requests/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available

### ISSUE THREAD

**Issue by vaisakh92** [pypa/pipenv#1280]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

##### Describe your environment

1. OS Type Ubuntu 16.04.3 LTS
1. Python version: `$ python -3.6.4
1. Pipenv version: `$ pipenv  version 9.0.1

##### Expected result
pipenv install 
installation of all the dependencies..

Describe what you expected.

##### Actual result
pipenv install
Installing dependencies from Pipfile.lock (615159)…
An error occurred while installing requests==2.18.4! Will try again.
An error occurred while installing flask==0.12.2! Will try again.
An error occurred while installing urllib3==1.22! Will try again.
An error occurred while installing markupsafe==1.0! Will try again.
An error occurred while installing chardet==3.0.4! Will try again.
An error occurred while installing werkzeug==0.12.2! Will try again.
An error occurred while installing jinja2==2.9.6! Will try again.
An error occurred while installing itsdangerous==0.24! Will try again.
An error occurred while installing certifi==2017.7.27.1! Will try again.
An error occurred while installing idna==2.6! Will try again.
An error occurred while installing click==6.7! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 11/11 — 00:00:09
Installing initially–failed dependencies…
Collecting requests==2.18.4 ▉▉▉▉▉▉▉▉▉ 0/11 — 00:00:00
  Could not fetch URL https://pypi.python.org/simple/requests/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping

pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
  Could not find a version that satisfies the requirement requests==2.18.4 (from -r /tmp/pipenv-jndFEa-requirement.txt (line 1)) (from versions: )
No matching distribution found for requests==2.18.4 (from -r /tmp/pipenv-jndFEa-requirement.txt (line 1))

  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/11 — 00:00:02

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

**Comment by kennethreitz** [comment]
this is a problem with your python installation.

**Comment by brainwane** [comment]
Transport Layer Security, or TLS, is part of how we make sure connections between your computer and PyPI are private and secure. It's a cryptographic protocol that's had several versions over time. 

You need to be connecting to PyPI with a TLS support library. The specific steps you need to take will depend on your operating system version, where your installation of Python originated (python.org, your OS vendor, or an intermediate distributor), and the installed versions of Python, `setuptools`, `pipenv`, and  `pip`. For help, please go to <a href="https://webchat.freenode.net/?channels=%23pypa" target="_blank" rel="noopener">the #pypa IRC channel on Freenode</a>, file an issue at <a href="https://github.com/pypa/packaging-problems/issues" target="_blank" rel="noopener">pypa/packaging-problems/issues</a>, or <a href="https://www.python.org/community/lists/" target="_blank" rel="noopener">post to the python-help mailing list</a>, including your OS and installation details and the output of <tt>pip install -vvv upgrade pip</tt>.
