### ISSUE TITLE
Cannot create lockfile when using PIP_EXTRA_INDEX_URL

### ISSUE THREAD

**Issue by alexbecker** [pypa/pipenv#1285]
The extra index is definitely available, as the desired package is installed when running `pipenv install --skip-lock`. However, I cannot generate a lockfile by running `pipenv install` or `pipenv lock`. This was not true earlier today and I have not updated `pipenv` or anything else relevant to my knowledge.

##### Describe your environment

1. OS Type: Ubuntu 16.04
1. Python version: 3.6.3
1. Pipenv version: 9.0.1

##### Expected result

Lockfile is generated when running `pipenv lock`.

##### Actual result

```
$ pipenv lock --clear --verbose
Locking [dev-packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1                           
Current constraints:

Finding the best candidates:

Finding secondary dependencies:
------------------------------------------------------------
Result of round 1: stable, done
Locking [packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1                           
Current constraints:
  get-app-root-path

Finding the best candidates:
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches get-app-root-path
Tried: (no version found at all)
Please check your version specifier and version number. See PEP440 for more information.
Using pip: -i https://pypi.python.org/simple

                          ROUND 1                           
Current constraints:
  get-app-root-path

Finding the best candidates:
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches get-app-root-path
Tried: (no version found at all)
Please check your version specifier and version number. See PEP440 for more information.
```

##### Steps to replicate

Unfortunately I can't provide replication since the extra index requires credentials I cannot distribute publicly. But my steps are as follows:

```
$ pipenv shell
$ pipenv lock --clear --verbose
```

The toy project contains only two files:
.env:
```
PIP_EXTRA_INDEX_URL=https://[elided]@packagecloud.io/[elided]/pypi/simple
```
Pipfile:
```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

get-app-root-path = "*"


[requires]

python_version = "3.6"
```

**Comment by alexbecker** [comment]
Using `/usr/bin/python3.6 -m pipenv lock` works.

Best I can tell, `pipenv lock` is ignoring `PIP_EXTRA_INDEX_URL`, given the line `Using pip: -i https://pypi.python.org/simple` in the verbose output. Why this differs between the module and the executable is beyond me.

**Comment by kennethreitz** [comment]
this is a known issue.

**Comment by alexbecker** [comment]
Glad to hear the maintainers are aware of this. Is there a canonical issue tracking this that I can follow? Is a fix targeted for the next release? Is there a recommended workaround, or if not can I expect my workaround of using `/usr/bin/python3.6 -m pipenv lock` to continue working?

**Comment by kennethreitz** [comment]
currently, the pipfile/lockfile are to be deterministic, and the total source of truth.

**Comment by alexbecker** [comment]
@kennethreitz To clarify, you are saying that pipenv *should not be expected to respect any environment variables*? Why does it pretend to then?

**Comment by kennethreitz** [comment]
not PIP_INDEX_URL.
