### ISSUE TITLE
Provide argument which specifies the subname of the virtual environment folder instead of automatic hashname

### ISSUE THREAD

**Issue by rishatsharafiev** [pypa/pipenv#1292]
Hello.
It's my proposal. Assume that we in folder `~/dev/project/dummy`. let's create virtual environment with command and argument `pipenv shell --name=subname`. It should create path `~/.local/share/virtualenvs/dummy-subname`. Else it just uses old mechanism.
Thank you.

**Comment by cjw296** [comment]
@rishatsharafiev - any chance you could close this as it looks do be a dupe of #1049?

**Comment by rishatsharafiev** [comment]
@cjw296  that's great, thank you.
