### ISSUE TITLE
Will pipenv have an better shortname in the future?

### ISSUE THREAD

**Issue by yech1990** [pypa/pipenv#1294]
`pipenv` is not easy to type. I usally get typo when use this command. And It is not easy to pronounce either.

It mix two type of naming scheme, `pip` in short for `Python Package Index` and `env` is the prefix of `Environment`. 

Dose anyone think `pipe` or `pie` is a better shortname?

**Comment by nateprewitt** [comment]
Hey @yech1990, thanks for opening a dialogue on this. If you’re having difficulties typing the name `pipenv` in your terminal, you may consider using an`alias` to map it to something you find easier.

As for the projects name, I think we’re pretty happy with what we’ve chosen and don’t have any plans on changing that in the immediate future.
