### ISSUE TITLE
use with Continuous Integration (Heroku CI specifically)

### ISSUE THREAD

**Issue by dbinetti** [pypa/pipenv#1295]
(Checked Issues and Documentation First -- couldn't find anything)

What is the best practice for using `pipenv` with Continuous Integration systems (specifically, with Heroku CI)?  Currently I have testing dependencies in my `dev-packages` but that doesn't load when using Heroku CI, so I have to include all dev stuff in my default (ie, production.) list.  Is there a [test] header?  Some other practice?

**Comment by kennethreitz** [comment]
Open an issue with the Heroku buildpack. We’ll get this fixed.
