### ISSUE TITLE
Package names are not always normalised properly (e.g. when containing full stops)

### ISSUE THREAD

**Issue by anowlcalledjosh** [pypa/pipenv#1302]
If you try to `pipenv install` packages with names that are technically equivalent but look different, Pipenv doesn't always realise that the two names are equivalent, and creates a duplicate entry in the Pipfile.

##### Describe your environment

1. OS Type: Ubuntu 16.04
1. Python version: 3.6.3
1. Pipenv version: 9.0.1

##### Expected result

Normalisation should behave the same as other Python packaging software (Pip, PyPI, setuptools...) and be consistent with the Python documentation. For example, from the [Python Packaging User Guide](https://packaging.python.org/tutorials/distributing-packages/#name):

> Comparison of project names is case insensitive and treats arbitrarily-long runs of underscores, hyphens, and/or periods as equal.

##### Actual result

Pipenv doesn't consider full stops `.` equivalent to underscores or hyphens, and adjacent hyphens/underscores/full stops aren't reduced to a single hyphen.

##### Steps to replicate

```
$ pipenv install flask-marshmallow
$ pipenv install Flask_-.MARSHMALLOW
$ cat Pipfile
...
[packages]

flask-marshmallow = "*"
"flask--.marshmallow" = "*"
...
```

It looks like there's a [`safe_name` function](https://setuptools.readthedocs.io/en/latest/pkg_resources.html) in pkg_resources that might do the required normalisation? I don't know if that's the correct thing to use.

**Comment by kennethreitz** [comment]
pull requests accepted!

**Comment by marksteward** [comment]
In case anyone comes along and implements a fix, this also currently means `pipenv install prometheus_client` results in the unnecessary prompt "Did you mean prometheus-client?".

**Comment by kennethreitz** [comment]
we removed this in master

**Comment by nazmulhasan85** [comment]
@kenneth-reitz  when to plan a release with this fix?
