### ISSUE TITLE
Incorrect install output text

### ISSUE THREAD

**Issue by revolter** [pypa/pipenv#1304]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

##### Describe your environment

1. OS Type: macOS 10.13.2 (17C88)
1. Python version: 3.6.4
1. Pipenv version: 9.0.1

##### Expected result

Describe what you expected.

I think that the `./s` should not be there.

##### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

```
Adding boto3 to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
./sUpdated Pipfile.lock (aebaf3)!
```

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

Run `pipenv install boto3`

**Comment by XiaxuanTanKolmostar** [comment]
same problem

```shell
$ pipenv install boto3
...
TypeError: can't pickle zipimport.zipimporter objects

**Comment by uranusjr** [comment]
@XiaxuanTanKolmostar Your issue is completely unrelated to OP’s.

@revolter Pipenv uses [blindspin](https://github.com/kennethreitz/blindspin) to display progress during installation, and this seems like a wrongly-rencered spinner. What is the encoding and language setup of your console?

**Comment by revolter** [comment]
```sh
> echo $LC_CTYPE
UTF-8
> echo $LANG
en_US.UTF-8
```

@uranusjr, Is this what you needed? If not, please tell me how can I find it.

**Comment by uranusjr** [comment]
@revolter It is, and it looks right. I’m stumped :(

**Comment by revolter** [comment]
Ran the command again:

```
Adding boto3 to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (aebaf3)!
```

So I think is that kind of what the heck happened bug. Feel free to close it until it happens again.
