### ISSUE TITLE
New command for `pipenv run python script.py`

### ISSUE THREAD

**Issue by apnewberry** [pypa/pipenv#1306]
Loving pipenv so far! 

Pipenv has a number of helpful commands like `graph`, `install`, and `run`. I'm not sure what the right command name would be, but I wish I could run `pipenv python script.py` instead of `pipenv run python script.py`. 

I realize I could alias it, but it would be quite nice to have it come standard.

**Comment by kennethreitz** [comment]
run is fine :)
