### ISSUE TITLE
--deploy only checks for Pipfile/Pipfile.lock consistency (ignoring setup.py dependencies)

### ISSUE THREAD

**Issue by argaen** [pypa/pipenv#1309]
Having a Pipfile as:

```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]

"e1839a8" = {path = ".", editable = true}

[dev-packages]

"e1839a8" = {path = ".", editable = true, extras=["dev"]}
```

After the Pipfile.lock file is generated, if we modify dependencies in `setup.py` and do a `pipenv install --deploy` it happily installs the dependencies without noticing the dependencies in the source have changed.

The reason is because the `pipfile.hash` [property](https://github.com/pypa/pipfile/blob/master/pipfile/api.py#L96,L99
) checks only for Pipfile contents but, in our case our dependencies are defined in `setup.py`.

For us, expected result would be the command failing because dependencies in `setup.py` and `Pipfile.lock` don't match.

For reference, part of the code where `--deploy` option is implemented: https://github.com/pypa/pipenv/blob/f5b482453f545fee58e3a4322bd9e7759db85f9f/pipenv/cli.py#L1270

Haven't found any issue related so sorry in advance if this is already documented/discussed somewhere

**Comment by kennethreitz** [comment]
this isn't bound to change, there's only so much we can do here.
