### ISSUE TITLE
pipenv install seems to not be installing entrypoints when run in tox

### ISSUE THREAD

**Issue by nicain** [pypa/pipenv#1312]
##### Describe your environment

Ubuntu
python 27, 35, 36
pipenv 9.0.3

##### Expected result

For some reason, all my tests that check for installation of the entrypoints defined in my setup.py file are failing, because the entrypoints aren't getting isntalled.  The package is installed, however.  This seems to be a consequence of upgrading from 9.0.1

**Comment by nicain** [comment]
@kennethreitz can you please document the reason that this issue is now closed?  Has the issue been resolved with a commit or PR?  Or is pipenv not responsible for installing entry-points (this seemed to be the case in 9.0.1)? Or wontfix?

**Comment by uranusjr** [comment]
@nicain What you encountered is eerily similar to an incompatibility issue I faced when working on berdario/pew#173. Can you provide more information on how your environment is set up? For example, how you install those Python versions, how you install Pipenv and Tox (an their dependencies), and how you setup Tox to discover available Python versions.
