### ISSUE TITLE
how to use pipenv with cv2 

### ISSUE THREAD

**Issue by jwz-ecust** [pypa/pipenv#1313]
I install OpenCV by `brew install opencv`. To import cv2, copy the cv2.so from opencv lib to my python sitepackages. When I use pipenv, how do I install the cv2?

## environment

- MacOS Sierra
- Python3.6
- pipenv, version 9.0.1

**Comment by uranusjr** [comment]
```
$ brew install opencv
$ pipenv --python 3.6
$ pipenv install numpy
$ ln -s "$(brew --prefix)"/lib/python3.6/site-packages/cv2*.so "$(pipenv --venv)"/lib/python3.6/site-packages
$ pipenv run python -c "import cv2; print(cv2.__version__)"
3.4.0
```

And I’ll mention #1305 because the issue tracker is not the place for usage questions.

**Comment by jwz-ecust** [comment]
@uranusjr  thanks!

**Comment by laxmikantG** [comment]
How to install on windows?

**Comment by uranusjr** [comment]
Follow the official documentation, but replace `C:\Python27` with whatever `pipenv --venv` outputs.
