### ISSUE TITLE
pipenv does not create Pipfile and Pipfile.lock if they exist in parent directories

### ISSUE THREAD

**Issue by tejasbubane** [pypa/pipenv#1317]
##### Describe your environment

1. OS Type - OSX - Darwin Kernel Version 16.7.0
1. Python version: `$ python -V` - Python 2.7.10
1. Pipenv version: `$ pipenv --version` - pipenv, version 9.0.3

##### Steps to replicate:

```
cd ~/
pipenv install <any-package>
mkdir hello
cd hello
pipenv install <any-package>
```

##### Expected result

`Pipfile` and `Pipfile.lock` should be created in the current directory (`~/hello` in the above example)

##### Actual result

If `Pipfile` exist in home (parent) directory, no `Pipfile` or `Pipfile.lock` is created in current directory. `pipenv` keeps adding packages to the parent Pipfile (in home directory in above example). And `pipenv --where` returns home directory path.

**Comment by uranusjr** [comment]
This is deliberate, and normally is what people want. Say you’re developing a package with a `tools` directory, and it would be strange if you can’t run scripts inside the subdirectory. The Pipfile should work for all directories inside that project.

You can create a Pipfile manually inside `hello` to get the behaviour you want.

**Comment by tejasbubane** [comment]
I don't program in python and in fact I came across `pipenv` today itself while working on a project. So my opinions might not be right. But I was expecting the tool to create `Pipfile` in current directory if it does not exist. I was not aware that I had accidentally ran `pipenv` in home directory and that a `Pipfile` exists there - kept wondering why `Pipfile` was not created in my project directory even though all commands succeed.

You are right that this might be an issue while running commands in subdirectories. Wonder if it would make sense to lookup the source-control root directory and generate the file there rather than using home? And if source-control not present, use default home path?

Again this is just an opinion, please feel free to close the issue if this is deliberate and desired behaviour.

**Comment by uranusjr** [comment]
While I don’t think the current behaviour is wrong, your experience might show a related issue: it is too easy for people to accidentally create a Pipfile. Currently there’s no explicit command required to create a Pipfile; almost all commands will create it automatically. I can recall several times I ran `pipenv <something>` in the wrong directory and had to ctrl-c immediately before it create a Pipfile (and virtualenv) for my `/etc`. There might be an enhancement worth considering.

(p.s. I am not one of the project maintainers; I’ll just leave this here for them to triage on.)

**Comment by techalchemy** [comment]
@uranusjr thanks again as always for your ongoing help, it really means a great deal

@tejasbubane you can set the environment variable `PIPENV_MAX_DEPTH` if you don't like pipenv recursing up your directory tree

**Comment by halloleo** [comment]
Another, newer way to do it is to set the env variable  `PIPENV_NO_INHERIT`. Then Pipenv won't look in the parent directory.

**Comment by sid-kap** [comment]
I just ran into this issue as well (apparently there was a Pipfile in the parent directory but I didn't realize). 
Can we add a debug message when this happens, something like `(using /path/to/Pipfile)`?

**Comment by uranusjr** [comment]
@sid-kap It has been added recently and will be in the next release :)

**Comment by Hezeh** [comment]
You can as well run 
_pipenv --rm 
 _rm Pipfil*_ 
The command deletes the virtualenv and then  the Pipfile.

**Comment by gprotasio** [comment]
> Another, newer way to do it is to set the env variable `PIPENV_NO_INHERIT`. Then Pipenv won't look in the parent directory.

Thanks! @halloleo

**Comment by jorgeav527** [comment]
first I cd into the dir them I create the python version I want to use `pipenv --python 3.x.x` them I activate the shell `pipenv shell` and confirm the actual env is in the correct folder. Last I start installing all de devs I need
