### ISSUE TITLE
Is there a way to install to custom-packages in Pipfile?

### ISSUE THREAD

**Issue by sbeleidy** [pypa/pipenv#1318]
My understanding is that Pipfile supports the ability to install many categories of packages with the default being `[packages]` and `[dev-packages]`. Is there a way using pipenv to install to a custom group and install all of the packages under a custom group?

Example implementation if this is not already implemented could be:

`pipenv install requests --custom test` to install the requests package under `[test-packages]`
`pipenv install --custom test` to install all packages under `[test-packages]`

**Comment by uranusjr** [comment]
Based on several previous discussions, the answer seems to be no. The workaround would be using good-old requirements.txt files.

**Comment by kennethreitz** [comment]
the spec is open to adding that later, but it's not on the table at this time.

**Comment by gsemet** [comment]
would be really useful indeed to support custom packages.
