### ISSUE TITLE
Catalog PRs post-9.0.1

### ISSUE THREAD

**Issue by nateprewitt** [pypa/pipenv#1324]
It looks like 9.0.3 erased all commits post-9.0.1 which means we’ve lost some relevant PRs. We need to go back through our PR list and determine which ones we need to get added back. Preferably a maintainer can just cherrypick them onto master.

I’ll assign this to myself, but if someone else wants to pick this up, please feel free to do so.

**Comment by cclauss** [comment]
Please add #1298 back in.

**Comment by techalchemy** [comment]
Just waiting on #1372 here (needs your final signoff maybe)

**Comment by nateprewitt** [comment]
Resolved via #1372.
