### ISSUE TITLE
Separate testing dependencies from development dependencies

### ISSUE THREAD

**Issue by thedrow** [pypa/pipenv#1327]
We need another section to specify test only dependencies so that during CI we won't have to install all the development tools as well.
UX-wise we have two options:
The first option is that `pipenv install --dev` will install both development and test dependencies.
To avoid installing test dependencies we can introduce `pipenv install --dev --no-test`.
The second option is to mandate the user to specify `--dev --test` if they want to install both development and test dependencies.

**Comment by kennethreitz** [comment]
`--dev` is intended to include both test and development dependencies. this is not an oversight, it is an intentional design decision.

**Comment by thedrow** [comment]
Can I ask what's the rationale behind this design decision?

**Comment by uranusjr** [comment]
@thedrow This has been discussed (and explained) multiple times in the past. #335 is one example, and there is a tracking issue in the upstream Pipfile spec project pypa/pipfile#99.
