### ISSUE TITLE
`pipenv shell` fails when `zsh` tries to autoupdate

### ISSUE THREAD

**Issue by sobolevn** [pypa/pipenv#1330]
I am using `zsh` with `oh-my-zsh` as my main shell.
Everything worked fine, but today I have noticed this strange behavior:

```
» pipenv shell
Spawning environment shell (/usr/local/bin/zsh). Use 'exit' to leave.
[Oh My Zsh] Would you like to check for updates? [Y/n]: source /Users/sobolev/.virtualenvs/test_project-c7lHFdaF/bin/activate

» pipenv shell
Shell for UNKNOWN_VIRTUAL_ENVIRONMENT already activated.
No action taken to avoid nested environments.
```

So, what happened:
1. I tried to activate a existing `pipenv shell`
2. My `oh-my-zsh` script tried to check for updates
3. I had to close my terminal and reopen it to make everything work again

##### Describe your environment

1. OS Type: macos
1. Python version: `3.6.4`
1. Pipenv version: `9.0.1`
1. `zsh --version`: `zsh 5.3.1 (x86_64-apple-darwin15.6.0)`

##### Steps to replicate

I guess, it would be hard to replicate.

**Comment by kennethreitz** [comment]
this is an ohmyzsh problem.
