### ISSUE TITLE
Place to list editor integrations?

### ISSUE THREAD

**Issue by pwalsh** [pypa/pipenv#1332]
As Pipenv becomes more widespread, it would be useful to be able to discover code editor and IDE integrations from the Pipenv documentation site. I am currently aware of my own Pipenv integration for [Emacs](https://github.com/pwalsh/pipenv.el), and the [Sublime Text](https://github.com/kennethreitz/pipenv-sublime) integration by @kennethreitz . I am sure there are others.

**Comment by kennethreitz** [comment]
Let's add it to the docs!

**Comment by Senpos** [comment]
Also, there is a [ticket](https://youtrack.jetbrains.com/issue/PY-26492) about adding `pipenv` support into PyCharm. If it is possible, can you place link to that ticket somewhere too? I think, so many PyCharm users would love to have this integration, but probably, they don't know how to affect PyCharm team into creating it.

**Comment by kennethreitz** [comment]
Love that idea!

**Comment by pwalsh** [comment]
@kennethreitz happy to do a PR to the docs, but some guidance on where such a section should go would be helpful. Thanks!

**Comment by jayfk** [comment]
I've just added (experimental) support for `pipenv` to [pyup.io](https://pyup.io) 👏 

There are still some minor caveats but overall, it should be good to go: https://github.com/pyupio/pyup/issues/197#issuecomment-360391226

**Comment by brettcannon** [comment]
FYI we are tracking VS Code support at https://github.com/Microsoft/vscode-python/issues/404

**Comment by pwalsh** [comment]
Is this closed because it is no longer deemed relevant/useful to the community of users?

**Comment by kennethreitz** [comment]
just cleaning house, prs accepted!

**Comment by kennethreitz** [comment]
https://docs.pipenv.org/advanced/#community-integrations
