### ISSUE TITLE
Would it be good to be able to activate a pipenv by providing a path to a Pipenv file?

### ISSUE THREAD

**Issue by mbrochh** [pypa/pipenv#1335]
Having used virtualenvwrapper for eternity, I find it really hard to wrap my head around the fact that I can't just activate a pipenv from any folder in my filesystem. I have to be in the folder where the Pipenv file is, then I can use `pipenv shell`.

You could say that I can simply source the `activate` script in the `.virtualenvs` folder, but for example in Ansible scripts where I do the initial server provisioning, it is really inconventient that I don't know the name of the virtualenv because it has that hash value in the name. I will always know the path to my Pipenv file, though, so if I could do something like `pipenv shell|run --path=/path/to/Pipenv` then I would not need to know the name of the virtualenv any more.

Am I overthinking this? Is something similar already in place?

**Comment by kennethreitz** [comment]
we have an environment variable you can set currently, actually.

https://github.com/pypa/pipenv/blob/master/pipenv/environments.py#L26
