### ISSUE TITLE
There is no way to set per-environment indexes

### ISSUE THREAD

**Issue by Ignas** [pypa/pipenv#1336]
We have different pip mirror urls (both public and private) depending on environments. Our private mirror is password protected. It would be nice to be able to provide global source configuration, without having to commit urls into all of the repositories, and also avoid having to store passwords in the repo (or enter them every time you are updating dependencies).

Pip does that via `.pip/pip.conf` file, where you can have `[global]` section with your per-environment configuration which makes work that Ops have to do a lot easier.

This also would be useful in environments where one wants to prevent global pypi from being used (to avoid depending on resources external to the datacenter in the build process), without modifying code being built/installed.

**Comment by kennethreitz** [comment]
Builds are to be deterministic, from the Pipfile.

**Comment by Ignas** [comment]
I would think that determinism is ensured by having hashes in the Pipfile, not by having same source for the tarball each time. Sources can disappear or go down. Do you consider Debian build system to be non-deterministic because `debian/control` file does not hardcode the apt repository to download build dependencies from?
