### ISSUE TITLE
calling pipfile from make

### ISSUE THREAD

**Issue by gvoysey** [pypa/pipenv#1338]
(my apologies if this is actually a `make` problem or user error)

Project structure:
```
.
├── my_project
│   ├── __init__.py
│   ├── __main__.py
│   └── _version.py
├── Makefile
├── requirements.txt
├── MANIFEST.in
├── Pipfile
├── Pipfile.lock
├── README.md
├── setup.py
└── deploy
    └── Pipfile
├── version.txt
├── WARNING
└── wheels
    └── my_project-0.9.2.post1-py3-none-any.whl
```

I have a make target in `Makefile` as follows:
```
package:
	@cd ./deploy		
	@pipenv run pex -r ../requirements.txt -f ../wheels my_project -c my_project -o my_project.pex
	@mv my_project.pex ../
	@cd ..
```

`deploy` contains its own Pipfile with `pex` and `requests` installed. (and indeed can/wants to be outside of this project entirely -- just a clean venv for deployment and packaging)

so the intent is: go here, make me a bundle, move it, get out. 

##### Describe your environment

1. OS Type 
  Ubuntu 16.04 64-bit
1. Python version: `$ python -V`
 3.6.3 (pyenv)
1. Pipenv version: `$ pipenv --version`
9.0.3
##### Expected result

pex builds me a file and puts it in the project root.

##### Actual result

`Error: the command pex could not be found within PATH.`

**Comment by kennethreitz** [comment]
i think you're going to have to play around with make some more :)

**Comment by gvoysey** [comment]
yup!  i'm an idiot.
