### ISSUE TITLE
Consider removing flake8 support

### ISSUE THREAD

**Issue by kennethreitz** [pypa/pipenv#1340]
the less code, the better!

**Comment by sobolevn** [comment]
@kennethreitz is it on the roadmap?
If so, I would be happy to submit a PR.

**Comment by nateprewitt** [comment]
@sobolevn yes, we'll be happy to review a PR removing this feature.

**Comment by sobolevn** [comment]
I am on it.

**Comment by s0undt3ch** [comment]
It struck me as odd too that linting was part of the project.
