### ISSUE TITLE
pipenv shell change my zsh environment

### ISSUE THREAD

**Issue by readyou** [pypa/pipenv#1359]
when I run: pipenv shell, then I get a pure shell environment

##### Describe your environment

1. OS Type MAC OS
1. Python version: 3.6
1. Pipenv version: 9.0.1

##### Expected result
like virtualenv, just change python environment, but not change os environment

##### Actual result
change both
![](http://cf.alioss.shuidihuzhu.com/img/ck/20180126/121b1ab1-c3d5-4826-84e1-3f50cf8f957d)

**Comment by uranusjr** [comment]
`pipenv shell` creates a new subshell because it is considered too hacky to change/restore the current shell environment. The subshell should inherit your current shell’s environment though. What exactly is not working for you? I don’t see anything unusual with the screenshot you attached. The prompt seems to be customised, and your custom alias seems to work.

**Comment by readyou** [comment]
My custom alias do not work after I run 'pipenv shell'

zsh: command not found: gst

**Comment by techalchemy** [comment]
@readyou this has to do with configuring you shell and whether your aliases are in `zshrc` or not. The subshell pipenv creates is not a login shell so if your aliases are loaded in `zprofile` they will be ignored. 

Thanks for reporting, I’m going to close this one for now as it was a design decision to spawn subshells.

**Comment by nitrocode** [comment]
Ugh. I just ran into this issue too. Is the workaround to move all plugins config and everything from `.zshrc` to `.zprofile` to get my shell environment to look and work correctly after a `pipenv shell` ?

**Comment by techalchemy** [comment]
@nitrocode if you want things to load in `pipenv shell`, they go in `.zshrc`.  Things that should only get set one time (like environment variables) go in `.zprofile`

**Comment by readyou** [comment]
I set the aliases in .bash_profile and then sourced by .zshrc. It worked in item2, but not work after pipenv shell.

**Comment by Colaplusice** [comment]
I cp .zshrc to .zprofile .And it works in terminal.
But when i use Pycharm integrate terminal. It doesn't works. I lost my zsh config in Pipenv subshell until i run commands "source ~/.zshrc".
Can you tell me how to fix it.

**Comment by uranusjr** [comment]
@Colaplusice You will need to ask for support from PyCharm, I’m afraid.

**Comment by JuliGonzalez** [comment]
> I cp .zshrc to .zprofile .And it works in terminal.
> But when i use Pycharm integrate terminal. It doesn't works. I lost my zsh config in Pipenv subshell until i run commands "source ~/.zshrc".
> Can you tell me how to fix it.

Did you fix it?
Having the same issue using Pycharm terminal.

**Comment by pozgo** [comment]
Still the same with Pycharm 
The only know solution is:

`source ~/.zshrc`

**Comment by jake-aft** [comment]
I am having this issue starting today after upgrading ohmyzsh not from pycharm, but from iterm2 when launching a pipenv shell. Everything is in my .zshrc.
