### ISSUE TITLE
Platform version is parsed incorrectly on Ubuntu

### ISSUE THREAD

**Issue by thedrow** [pypa/pipenv#1370]
It seems that Platform version is parsed incorrectly and includes the current date and time on Ubuntu at the very least.

##### Describe your environment

1. OS Type: Ubuntu 17.10
1. Python version:  3.6.4
1. Pipenv version: 9.0.1

##### Expected result

Platform version should be "Ubuntu".

##### Actual result

Pipfile.lock contains the following:

```json
{
  // ...
  "platform_version": "#34-Ubuntu SMP Fri Jan 19 16:34:46 UTC 2018",
  // ...
}
```

##### Steps to replicate

Create a pipfile on Ubuntu and install it, creating the lock.

**Comment by techalchemy** [comment]
Thanks for the report. We are aware of issues with marker parsing and will have a fix shortly

**Comment by nateprewitt** [comment]
@thedrow this would appear to be a bug in the standard library `platform` module. All we're doing is writing the value it returns to us as seen [here](https://github.com/pypa/pipenv/blob/ad7229b7548b900727e0596f6812fa783bcc6870/pipenv/pep508checker.py#L35).

I don't know if there's much we can do for pipenv in this case. Can you run the script below and see if the returned value is the same? If it is, you may consider trying to find the issue on the [cpython bug tracker](https://bugs.python.org/) and filing a bug if it isn't recorded. I'm going to close this out for now unless we have a repro that's specific to pipenv. Thanks for the report!

```python
import platform
print(platform.version())
```

**Comment by thedrow** [comment]
This is indeed a problem with CPython. Thanks!
