### ISSUE TITLE
'pipenv shell' fails if /bin/sh is not bash (depends on 'source')

### ISSUE THREAD

**Issue by paulchakravarti** [pypa/pipenv#1371]
##### Describe your environment

1. FreeBSD 11.1-RELEASE-p4 
1. Python version: Python 3.6.4
1. Pipenv version: pipenv, version 9.0.3

##### Expected result

pipenv should not assume /bin/sh is bash

##### Actual result

```
$ pipenv shell
pipenv shell
Spawning environment shell (/bin/sh). Use 'exit' to leave.
[paulc@dev6] /usr/home/paulc $ source /home/paulc/.local/share/virtualenvs/paulc-fQQTQRg4/bin/activate
source /home/paulc/.local/share/virtualenvs/paulc-fQQTQRg4/bin/activate
/bin/sh: source: not found
```

The following patch solves this (bash also supports .)

```
--- cli.py.old	2018-01-28 16:18:27.232506000 +0000
+++ cli.py	2018-01-28 16:18:53.234899000 +0000
@@ -1185,7 +1185,7 @@
     venv_location = project.virtualenv_location.replace(' ', r'\ ')
 
     if source:
-        return 'source {0}/bin/activate{1}'.format(venv_location, suffix)
+        return '. {0}/bin/activate{1}'.format(venv_location, suffix)
     else:
         return '{0}/bin/activate'.format(venv_location)
```

**Comment by racarr01** [comment]
FreeBSD 14.1
Python 3.11.11
Pipenv pipenv, version 2024.4.0
packages  installed from FreeBSD 'latest repository

Identical error occurs when executing pipenv at login shell:

    racarr@lazyacres:~ $ pipenv shell
    Launching subshell in virtual environment...
    racarr@lazyacres:~ $  source /home/racarr/.local/share/virtualenvs/racarr-K63DNGtK/bin/activate
    source /home/racarr/.local/share/virtualenvs/racarr-K63DNGtK/bin/activate
   /bin/sh: source: not found
