### ISSUE TITLE
Estimated time color should not be set to black

### ISSUE THREAD

**Issue by Pawamoy** [pypa/pipenv#1374]
If the terminal background is dark, then the estimated time is difficult to see. See the attached screenshot.

![screenshot - 01292018 - 07 34 50 pm](https://user-images.githubusercontent.com/3999221/35527594-8dccabe4-052b-11e8-98c1-c7c223aec5c6.png)

##### Versions

1. OS Type: Linux, Debian, BunsenLabs
1. Python version: 3.6.4
1. Pipenv version: 9.0.3

##### Expected result

Leave the color as default? Or also set the color background to make sure the text is visible. Terminal emulators usually support the **reverse** sequence: `\033[;7m`.

##### Actual result

Estimated time text might not be visible.

##### Steps to replicate

`pipenv install`

**Comment by uranusjr** [comment]
#660

**Comment by Pawamoy** [comment]
Alright, duplicate, closing, thanks.
