### ISSUE TITLE
Large number of dependencies causes crash

### ISSUE THREAD

**Issue by OniOni** [pypa/pipenv#1376]
When trying to pipenv lock on project with (too) many dependencies (>300), pipenv crashes.

##### Describe your environment
1. osx
1. Python version: `3.6`
1. Pipenv version: `9.0.3`

##### Expected result
pipenv creates lock file.

##### Actual result
pipenv crashes with:
```
OSError: [Errno 24] Too many open files: '/var/folders/4h/s6ttpgkd1d1ddm85n3n5kw4w0000gn/T/pipenv-m5smono2-requirement.txt'
```

##### Steps to replicate
- Pifple with over 253 dependencies.
- Run any command that would produce the lock file (eg: `pipenv lock`)

First reported here: https://github.com/pypa/pipenv/pull/1375
Should be fixed by: https://github.com/pypa/pipenv/pull/1364

**Comment by kennethreitz** [comment]
this should now be fixed, hopefully
