### ISSUE TITLE
How do I uninstall pipenv?

### ISSUE THREAD

**Issue by palash25** [pypa/pipenv#1377]
I installed pipenv using `pip install --user pipenv`. After installing pipenv I was not able to create virtualenvs using `virtualenv venv`. I would like to uninstall it now but I can't find it in the docs how to uninstall it.

##### Environment

1. OS Type: Ubuntu 16.04
1. Python version: 3.6.1
1. Pipenv version: 9.0.3

**Comment by BallisticPain** [comment]
@palash25 basically didn't include a body to your question... didn't answer any of the prompts in the template body that was provided for you. Do you honestly expect someone to answer you in a fashion that would be helpful?

**Comment by nateprewitt** [comment]
@paladh25, does `pip uninstall —user pipenv` not work?

**Comment by palash25** [comment]
done thanks

**Comment by Ishaan-Adarsh** [comment]
> @palash25, does `pip uninstall pipenv` not work?

I used `python -m pip uninstall pipenv` and it worked.

**Comment by quinnzaballa** [comment]
THANKS

**Comment by p8ul** [comment]
I used `brew uninstall pipenv`

**Comment by AliEslah** [comment]
sudo apt uninstall pipenv

**Comment by Dav-Merva** [comment]
sudo apt remove pipenv

**Comment by biswasbiplob** [comment]
if installed with uv
`uv tool uninstall pipenv`
