### ISSUE TITLE
Local files hashes are not included in Pipfile.lock or in pipenv lock -r output

### ISSUE THREAD

**Issue by ElliotJH** [pypa/pipenv#1378]
I would like to be able to add a local wheel file to my Pipfile, and be able to emit a requirements.txt that can be installed with `pip install -r`. 

Right now, the Pipfile.lock does not include hashes for local files which means the emitted requirements.txt can't be used as if any hashes are provided all dependencies need hashes.

##### Describe your environment

1. MacOS
1. Python version: Python 3.6.4
1. Pipenv version: pipenv, version 9.0.3

##### Expected result

Hashes included for local wheel files in Pipfile.lock and in `pipenv lock -r` output.

##### Actual result

No hashes included.

##### Steps to replicate

```
pipenv install path/to/some_wheel-py3-none-any.whl
```

Lock file does not include hashes for some_wheel.

**Comment by ElliotJH** [comment]
Happy to be guided in how to fix it myself or to be told this is expected behavior. Thanks for the great project.

**Comment by owenstranathan** [comment]
This is a lot like [#988](https://github.com/pypa/pipenv/issues/988)

**Comment by kennethreitz** [comment]
hashes are currently derived from PyPi. You'd have to add code to calculate the hashes from locally available packages.

**Comment by techalchemy** [comment]
It is doable in theory, I believe the process is discussed in #1255 for using local repositories with pip tools

**Comment by kennethreitz** [comment]
closing for #1255
