### ISSUE TITLE
Control where virtualenv is created

### ISSUE THREAD

**Issue by caliph007** [pypa/pipenv#1385]
For deploying in production it would be really helpful to have tighter control on the location where the virtual env gets created.

Just fyi a transscript from my last deploy:
```
[server.com] run: export PIPENV_VENV_IN_PROJECT=true
[server.com] run: pipenv --three
[server.com] out: Creating a virtualenv for this project…
[server.com] out: Using /usr/bin/python3 to create virtualenv…
[server.com] out: ⠋Running virtualenv with interpreter /usr/bin/python3
[server.com] out: Using base prefix '/usr'
[server.com] out: New python executable in /home/ubuntu/.local/share/virtualenvs/application-qO5bWt8a/bin/python3
[server.com] out: Also creating executable in /home/ubuntu/.local/share/virtualenvs/application-qO5bWt8a/bin/python
[server.com] out: Installing setuptools, pkg_resources, pip, wheel...done.
[server.com] out:
[server.com] out: Virtualenv location: /home/ubuntu/.local/share/virtualenvs/application-qO5bWt8a

```
Why is pipenv disrespecting the environment variable PIPENV_VENV_IN_PROJECT ?

**Comment by techalchemy** [comment]
@caliph007 if you are using docker you will need to use proper docker commands to build your environment, as `export` will not accomplish this. In addition you will also need to pass `WORKDIR`. See [this link](https://docs.docker.com/engine/reference/builder/#env) for more information or [our example Dockerfile](https://github.com/pypa/pipenv/blob/master/Dockerfile) for a slightly different example.  Beyond that, if you are still having issues we will need your dockerfile
