### ISSUE TITLE
Extraneous Content in Pipfile.lock

### ISSUE THREAD

**Issue by orokusaki** [pypa/pipenv#1387]
It seems the opinion of the community is pretty unanimous:

### NOBODY WANTS LOCAL DEV OS JUNK IN `Pipfile.lock`

See #753

I don't know too many people that use Mac OS in production, so many people using Heroku or similar tools will have to deal with their app being in a perpetual [fugue state](https://en.wikipedia.org/wiki/Fugue_state).

I haven't yelled on GitHub before... but I also haven't come across a thread on an open source project where **everyone** wanted to remove a pretty bad feature from something and then the core maintainer popped in and said:

> going to remain, for now.

Then locked the thread to avoid hearing any other opinions on the matter (outside of the DPRK, we have an "Unsubscribe" button on the right side of the thread when we don't want the chatter).

**Comment by sbdchd** [comment]
After a brief search the `"host-environment-markers"` section of the `Pipfile.lock` doesn't seem to be used for anything.

https://github.com/pypa/pipenv/search?utf8=✓&q=host-environment-markers&type=

**Comment by uranusjr** [comment]
@sbdchd As mentioned in previous issues, it serves as debugging information.

**Comment by sbdchd** [comment]
@uranusjr I think a better way to get debug info would be a command for debugging. Something like the `brew config`.

e.g.
```
❯ brew config
HOMEBREW_VERSION: 1.5.2-15-gd558ec0
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: d558ec09332c74927dfb9182b19e11c5a73d8b52
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9d5797627cb6fcd5c52fb7dd9f32e85964eeacf5
Core tap last commit: 9 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_66
macOS: 10.12.6-x86_64
Xcode: N/A
CLT: 9.2.0.0.1.1510905681
X11: 2.7.8 => /opt/X11
```
