### ISSUE TITLE
Add a pipenv wheel command

### ISSUE THREAD

**Issue by thedrow** [pypa/pipenv#1392]
pipenv should have a command to build wheels out of a Pipfile.lock.
Right now we have to install everything and do:
```
$(pipenv --venv)/bin/pip wheel --wheel-dir=/tmp/wheelhouse $($(pipenv --venv)/bin/pip freeze)
```
which is not obvious and requires installation into a virtual environment.

**Comment by kennethreitz** [comment]
i think a pipenv extension would be more appropriate for this

**Comment by thedrow** [comment]
Is there an extension mechanism I can work with?

**Comment by tucked** [comment]
This would be handy!

@thedrow's workaround is helpful (I hadn't even made it that far!), but I think it bypasses hash-checking?
