### ISSUE TITLE
Failed package installation causes Pipfile.lock to be deleted

### ISSUE THREAD

**Issue by maw** [pypa/pipenv#1400]
[First of all, this might really be two issues in one. Apologies if so.]

If I use pipenv to install django==2.0.2 and subsequently try to install django-registration, then:

a) django-registration isn't installed.  A fragment of the error message is: "Could not find a version that matches django!=1.9.*,<2.0,==2.0.2,>=1.8"; among the versions tried is 2.0.2 (listed twice). My read of this is that it should be installable.

b) Pipfile.lock is deleted.

##### Describe your environment

1. OS Type: Ubuntu 16.04
1. Python version: Python 3.5.2 (also reproduced with a pyenv-managed 3.6.1)
1. Pipenv version: pipenv, version 9.0.3

##### Expected result

a) django-registration should be installed successfully

b) if django-registration can't be installed (I could well be misreading the error message), then Pipfile.lock shouldn't removed, and should probably remain as-is.

##### Actual result

a) django-registration not installed

b) Pipfile.lock deleted

I put a very verbose session in https://gist.github.com/maw/83f72224cf574f85fbad108e0d622124. Starting from a base OS image is probably overkill, but I've run into some issues involving pyenv. I don't think they're at play here, but I felt it better to eliminate that variable anyway.  The shorter version is in the next section.

##### Steps to replicate

```
mkdir tacos
cd tacos
pipenv install django==2.0.2
ls
pipenv install django-registration
ls
```

**Comment by maw** [comment]
According to its docs, django-registration doesn't support django 2. If so, it's legit for it to not have been installed, but the error message is confusing. And deleting the lock file seems definitely wrong.

**Comment by kennethreitz** [comment]
wontfix
