### ISSUE TITLE
pipenv suggests to install unrelated package

### ISSUE THREAD

**Issue by arthurk** [pypa/pipenv#1403]
When trying to install `schedule` pipenv suggests `azure-mgmt-scheduler` instead, even thought the package `schedule` exists on pypi (https://pypi.python.org/pypi/schedule).

```
$ pipenv install schedule
Did you mean azure-mgmt-scheduler? [Y/n]: 
```
##### Describe your environment

1. OS Type: MacOS 10.13.2
1. Python version: 3.6.4
1. Pipenv version: 9.0.3

##### Expected result

I expect it to install the specified package and not suggest another one.

**Comment by aaronang** [comment]
I can confirm this bug. Note though that if you answer `n`, it will install the desired package.

**Comment by kennethreitz** [comment]
i'm opening a PR to remove this functionality
