### ISSUE TITLE
`pipenv run` should support `-h` and `--help`

### ISSUE THREAD

**Issue by nodakai** [pypa/pipenv#1405]
##### Describe your environment

pipenv, version 9.0.3

##### Expected result

Pipenv should print a help text explaining how to use the `pipenv run` sub-command. This should be done regardless of whether `pipenv run` accepts a complex family of options which is worth a help text or not, in order to make it consistent with other Pipenv sub-commands which all accepts `-h` / `--help`.

##### Actual result

```
$ pipenv run -h
Creating a virtualenv for this project…
⠋Using base prefix '/usr'
New python executable in /home/ec2-user/.local/share/virtualenvs/a-EouiYCWm/bin/python3
Also creating executable in /home/ec2-user/.local/share/virtualenvs/a-EouiYCWm/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/ec2-user/.local/share/virtualenvs/a-EouiYCWm
Creating a Pipfile for this project…
Error: the command -h could not be found within PATH.
```

##### Steps to replicate

See above

**Comment by jrbourbeau** [comment]
It looks like `pipenv run --help` was disabled in #940. Although, there wasn't a specific reason given for disabling it. 

I agree with @nodakai that it's a little strange the other `pipenv` commands (e.g. `open`, `lock`, `shell`, etc.) have a help message displayed with `--help` / `-h`, but the `run` command doesn't.

**Comment by kennethreitz** [comment]
run passes everything to what you're trying to run...
