### ISSUE TITLE
Can't see current dir

### ISSUE THREAD

**Issue by lightninglu10** [pypa/pipenv#1410]
##### Describe your environment

1. MacOS
1. Python version: 3.6
1. Pipenv version: 9.0.3

Hey guys, I really love pipenv, but it's so annoying that my dir is obstructed! 

![screen shot 2018-02-08 at 5 54 50 pm](https://user-images.githubusercontent.com/2453737/36007852-2ee0a7a4-0cf9-11e8-9d94-78749ff80d4a.png)

I have the name of the virtualenv, but I don't know what current dir I'm in. Is there anyway to see the current dir?

**Comment by uranusjr** [comment]
You need to set up your shell properly with `.bashrc`. https://github.com/pypa/pipenv/issues/844#issuecomment-355536640

**Comment by lightninglu10** [comment]
Oh, is there a link to the proper docs?

**Comment by uranusjr** [comment]
Not AFAIK, unfortunately. (Pull request accepted!) You can read more into this topic (not specific to Pipenv) here: http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html
