### ISSUE TITLE
Pipenv completes on Windows and hangs on Raspberry Pi

### ISSUE THREAD

**Issue by hargikas** [pypa/pipenv#1413]
I have a problem with pipenv, when building in different platforms (machine). As you can see in the uploaded [Pipfile.zip](https://github.com/pypa/pipenv/files/1713222/Pipfile.zip) I have specified some packages to be install in the virtual enviroment. The [imageio](http://imageio.github.io/) package doesn't support the raspberry pi yet. 

I tried to exclude it in Pipfile using:
`imageio = {version = "*", platform_machine = "!= 'armv7l'"}` 

Even with that directive if I try to install to my raspberry pi, the pipenv hangs!!!

##### Describe your environment

1. Raspbian: Linux *** 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
1. Python version: `Python 3.5.3`
1. Pipenv version: `pipenv, version 9.0.1`

##### Expected result

I expected to install all the packages except the imageio package.

##### Actual result

I hangs! Some how it misses some packages and hangs around numpy package! I tried to get the logs here: 
[pipenv_log.zip](https://github.com/pypa/pipenv/files/1713234/pipenv_log.zip)

Any Ideas?

**Comment by kennethreitz** [comment]
it's compiling from source, mostly likely, which will take a long time. You'll have to configure pipenv to set a longer timeout than 60s for package installation.
