### ISSUE TITLE
Update internal dotenv (or make it a dependency)

### ISSUE THREAD

**Issue by kylegibson** [pypa/pipenv#1418]
Variables in a `.env` file that have single-quoted spaces are not loaded into the environment. If double quotes are used, then the variables are loaded into the environment.

##### Describe your environment

1. ubuntu 17.10
1. Python version: `$ python -V` - 3.6.4
1. Pipenv version: `$ pipenv --version` - 9.0.3

##### Expected result

All variables in `.env` would be loaded

##### Actual result

Variables in `.env` that are single-quoted and contain spaces are not loaded

##### Steps to replicate

1. Given the following `.env` file:

```
FOO='Hello World'
BAR='Test'
BAZ="Hello World"
```

2. Running `pipenv shell`
3. `FOO` will not be set in the environment.
4. This happens because the `FOO` line doesn't match the regex used (`'^\s*(\w*)\s*=\s*("[^"]*"|[^\s]*)\s*$'`) in the parsing algorithm. 

##### Additional information

I tracked this issue down by stepping through the dotenv loading code used by pipenv. When I found this line of code, I learned that only double quotes would allow spaces:

https://github.com/pypa/pipenv/blob/master/pipenv/patched/dotenv/main.py#L100

This parsing algorithm diverges a bit from the official dotenv logic:

https://github.com/theskumar/python-dotenv/blob/master/dotenv/main.py#L98

**Comment by kennethreitz** [comment]
pull requests accepted!
