### ISSUE TITLE
Automatically detect broken virtualenvs

### ISSUE THREAD

**Issue by dmerejkowsky** [pypa/pipenv#1419]
On many linux distros, after upgrading from e.g python3.5 to python3.6, all the vritualenvs created with python3.5 suddenly become usable.

The errors vary across distributions, but a simple workaround is simply to re-create the vritualenvs by hand:

```bash
$ cd /path/to/venv/created/with/3.5
$ virtualenv .
```

It would be nice if `pipenv` could help in this case, maybe by having a `pipenv recreate` or just a `pipenv clean` command.

Thoughts ?

**Comment by kennethreitz** [comment]
the current solution is `pipenv --rm` followed by `pipenv install`. I like that workflow, except I'd like to make it so we automatically detect when the virtualenv is corrupt and do the rm for you.

**Comment by dmerejkowsky** [comment]
> the current solution is pipenv --rm followed by pipenv install

That's fine with me :) I somehow missed the `--rm` option from the help message.

I don't know if detecting corrupted virtualenvs is easy, but it's worth trying. 

Thanks.
