### ISSUE TITLE
local requirement makes generated requirements.txt invalid

### ISSUE THREAD

**Issue by ipmb** [pypa/pipenv#1424]
Not sure there's anything to be done in pipenv for this beyond maybe some documentation, but starting with an issue since it feels related to #1417.

If you include a local dependency in your `Pipfile`, `-e .` for example. `pip lock --requirements` will generate a requirements list that is not installable by `pip`. Trying to install it results in the error:

```
The editable requirement file:///path/to/your/project (from -r requirements.txt (line 27)) cannot be installed when requiring hashes, because there is no single file to hash.
```

The workaround is to manually remove `-e .` from the requirements and install the two separately `pip install -r reqiurements.txt && pip install --no-deps -e .`.

##### Describe your environment

1. MacOS
1. Python 3.6.3
1. pipenv, version 9.0.3

##### Expected result

`pipenv lock --requirements` produces requirements that can be installed by `pip`

##### Actual result

`pip` fails to install when a local dependency is included with the error above.

##### Steps to replicate

From a local Python project with at least one dependency:

```
pipenv install -e .
pipenv lock --requirements > requirements.txt
# From an active virtualenv
pip install -r requirements.txt
```

**Comment by kennethreitz** [comment]
Hmm, looks like we'll have to remove those from the output.

**Comment by kennethreitz** [comment]
solution in https://github.com/pypa/pipenv/commit/9f41427a678e816538cec891f2e655e05a7eaad3 is to comment out these lines.
