### ISSUE TITLE
Errors when locking after system installs in Docker

### ISSUE THREAD

**Issue by jsatt** [pypa/pipenv#1428]
I've been running into what seemed to be an intermittent issue for several weeks now and have finally been able to narrow it down to a repeatable test case. 

When trying to install a new package system wide, with no virtualenv for the root user, and specific package present in the Pipfile, the install process will complete and the lock process will fail. `pylint`, `pylint-django`, `nose-watch` and `arrow` are some of the packages in the my Pipfile that seem to be involved.

### Versions:
I'm running in Docker specifically, but I suspect a fresh Linux install would probably result in the same.
Python 2.7 and 3.6
pipenv - 9.0.3
pip - 9.0.1
pew - 1.1.2
virtualenv - 15.1.0

### Steps:
1. In a Docker container (Dockerfile below)(`docker run -ti -u root <<image>> bash`)
1. run `pipenv install --system django` (but it's the same with any package)
1. Results in
    ```
    Installing six…
    Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages

    Adding six to Pipfile's [packages]…
    Locking [dev-packages] dependencies…
    CRITICAL:pip.utils:Error [Errno 2] No such file or directory while executing command python setup.py egg_info
    <<< rest of traceback below >>>
    ```
1. run any command that creates a virtualenv, such as `pipenv run ls`
1. run `pipenv install --system six`
1. This completes successfully,
    ```
    Installing six…
    Requirement already satisfied: six in /usr/local/lib/python2.7/site-packages

    Adding six to Pipfile's [packages]…
    Locking [dev-packages] dependencies…
    Locking [packages] dependencies…
    Updated Pipfile.lock (0a3864)!
    ```
1. `rm -r /root/.virtualenvs/app-MuJj66st/`
1. now `pipenv install --system six` reverts to previous error

Dockerfile
```
FROM python:2.7
RUN pip install pipenv
RUN mkdir /srv/app
WORKDIR /srv/app
COPY Pipfile* ./
RUN pipenv install --deploy --system
```

Pipfile
```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[dev-packages]
pylint = "*"


[packages]
six = '*'
```

Full Traceback
```
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 1934, in install
    do_lock(system=system, pre=pre)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 1041, in do_lock
    pre=pre
  File "/usr/local/lib/python2.7/site-packages/pipenv/utils.py", line 545, in resolve_deps
    resolved_tree = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/usr/local/lib/python2.7/site-packages/pipenv/utils.py", line 507, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 278, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/pip/utils/__init__.py", line 667, in call_subprocess
    cwd=cwd, env=env)
  File "/usr/local/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

### Workaround
For know I'm running `pipenv install --system --nolock <<pkg>>`, then `pipenv lock` to get the package installed and successfully regenerate the lockfile.

**Comment by techalchemy** [comment]
Can you try with this Dockerfile:

```Dockerfile
FROM python:2.7
RUN set -ex && pip install pipenv --upgrade
RUN set -ex && mkdir -p /srv/app
WORKDIR /srv/app
ONBUILD COPY Pipfile Pipfile
ONBUILD COPY Pipfile.lock Pipfile.lock
ONBUILD RUN set -ex && pipenv install --deploy --system
```

and this Pipfile:

```ini
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

six = "*"

[dev-packages]

pylint = "*"

```

**Comment by jsatt** [comment]
Because of the ONBUILD commands, running it with that Dockerfile directly doesn't actually copy my Pipfiles in or install the packages defined in the file, and therefore doesn't meet the state listed above as causing the problem.

Dropping the ONBUILD and doing those commands immediately or extending that image in another Dockerfile still results in the error above.

**Comment by techalchemy** [comment]
@jsatt I think you'd have to build the container separately from running it in order to have it copy, but I just read your report more carefully (sorry about that) -- are you saying that the container actually runs fine and it's not until you run a shell inside it and try to use pipenv that things break?

**Comment by jsatt** [comment]
@techalchemy, right. We're using the same Dockerfile for development, test and production. The images always build and run just fine. It's during development, when adding new packages that we need to run the `pipenv install` command from the repeat steps and when we see the error.

It's because the image builds and run fine that I suspect it's not limited to Docker, but I haven't had a chance to setup a Linux system that I can quickly try it out on. Will get those results as soon as I can.

**Comment by techalchemy** [comment]
@jsatt can you provide the (scrubbed if necessary) output of `env` from the docker shell? Specifically looking for locale settings (`LC_LANG` or `LC_ALL`) -- if they aren't set to `en_US.UTF-8` or `C.UTF-8` you should try setting them and see if that resolves it

**Comment by jsatt** [comment]
I can confirm it's not limited to Docker. I was able to recreate the error in a fresh Ubuntu install.

1. Fresh install
2. copy the Pipfile from above and lock
3 . `sudo su` to become root (`sudo` still uses the non-root user's venvs so it doesn't have the error)
4. `apt install python-pip`
5. `pip install --system pipenv` (installs 9.0.3)
6. `pipenv install --system --deploy`
7. `pipenv install --system django`
8. same error as above

**Comment by techalchemy** [comment]
Hm what if you `python -m pip install --upgrade pip` after you install it with the package manager first and make sure `/usr/local/*` precedes `/usr/*` on your path?

**Comment by techalchemy** [comment]
Hm I'm not actually sure if locking woks with `--system`, come to think of it. This may be intended to be paired with `--deploy`, i.e. an already-resolved lockfile

**Comment by jsatt** [comment]
Here's the env output from the from linux install that's seeing the error. setting those two variables explicitly makes no difference.

```
LESSCLOSE=/usr/bin/lesspipe %s %s
LANG=en_US.UTF-8
SUDO_GID=1000
USERNAME=root
SUDO_COMMAND=/bin/su
USER=root
PWD=/home/jsatt
HOME=/root
LC_CTYPE=en_US.UTF-8
SUDO_USER=jsatt
SUDO_UID=1000
MAIL=/var/mail/root
SHELL=/bin/bash
TERM=xterm-256color
SHLVL=1
LOGNAME=root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
LESSOPEN=| /usr/bin/lesspipe %s
_=/usr/bin/env
```

**Comment by techalchemy** [comment]
Okay, I mean, you can try setting `LC_ALL` but I don't think it will help -- I am pretty sure we discussed what is supposed to happen in this case at some point in the past, I'll have to dig that up and experiment tomorrow a bit... I have a feeling dependency resolution and `--system` may not play nicely

**Comment by jsatt** [comment]
I can kind of see some reasons why it wouldn't want it to work with `--system`, but I also think this is going to continue to be a use case as people migrate more to both pipenv and Docker for development (the docs explicitly mention using `--system` with Docker).

If that's the case, it seems like it could be useful to either
* display a message at the end on a install with `--system` (when the lock would happen) explaining the need to lock separately
* automatically create a temp or "cache" venv (assuming a useable one doesn't already exist) for use with `--system` so that it works as expected.

**Comment by kennethreitz** [comment]
--system is intended to install a Pipfile, not individual packages. maybe we should enforce that.

**Comment by jsatt** [comment]
@kennethreitz, @techalchemy, I think in this day, using Docker for development is becoming quite common and the very nature of Docker encourages system level installation as opposed to virtualenvs, as indicated in your own documentation. In such a development environment, how is the developer intended to add a new package to the Pipfile, install that package at the system level with all other installed packages and update the lockfile for committing later? To completely restrict the developer, as commit 52ea1d4 does, requires the user to do each of these steps separately and manually, quickly chipping away at pipenv's usefulness to the project at all.

If there is another workflow you intend developers to use in this sort of environment I think it'd be great to have it documented somewhere, but if not, I think we should try to figure out a workflow that works better in what is likely to be a more common environment as pipenv continues to gain adoption.

**Comment by jsatt** [comment]
And with today's release my project is now unable to add new dependencies because of this new commit. At least there was a workaround before.

@kennethreitz, I'm seriously curious what workflow you expect to be used for projects like what I've described above that you so quickly shut down this workflow.

**Comment by kennethreitz** [comment]
Pipenv is designed to manipulate virtualenvs and Pipfiles, as well as (optionally) installing a Pipfile into a "system" Python. These are your constraints.

**Comment by splatEric** [comment]
If we can't manipulate the libraries at the system level then it doesn't really work with Docker. Certainly not the way we're using Docker anyway. So I think that might end our efforts to work with pipenv

**Comment by kennethreitz** [comment]
Pipenv and pip are very friendly tools to use together.

**Comment by jtratner** [comment]
@kennethreitz - if I put up a proposed “standard Docker workflow” are you
cool with adding it to the docs? (Any suggestions on what that would be,
heh?)

From my perspective, I actually came to pipenv because I was eager to use
it as a sane way to manage requirements.txt in Docker and conda
environments - I think there’s a lot to offer there (even if you’re
installing a couple particularly difficult to manage scientific packages
with conda)
