### ISSUE TITLE
Unable to parse --no-binary when installing psycopg2

### ISSUE THREAD

**Issue by dfee** [pypa/pipenv#1430]
Unable to install psycopg2 with option `--no-binary`. Might be related to this issue? https://github.com/pypa/pipenv/issues/870

##### Describe your environment

1. OS Type: Mac OS 10.13.3
1. Python version: Python 2.7.10
1. Pipenv version: pipenv, version 9.0.3

##### Expected result
Describe what you expected.
`pipenv install "--no-binary psycopg2 psycopg2"` --> `pip install --no-binary psycopg2 psycopg2`

##### Actual result
$ pipenv install "--no-binary psycopg2 psycopg2" --verbose
Installing --no-binary psycopg2 psycopg2…
⠋Installing '--no-binary psycopg2 psycopg2'
WARNING: Invalid requirement, parse error at "'--no-bin'"
ABORTING INSTALL... You will have to reinstall any packages that failed to install.
You may have to manually run pipenv lock when you are finished.

##### Steps to replicate
$ pipenv --three
$ pipenv install "--no-binary psycopg2 psycopg2"

**Comment by techalchemy** [comment]
@dfee this doesn't get dropped through to pip and it's not a valid pipenv argument.  Pipenv doesn't just function as a wrapper around pip, it is a separate tool and has separate options-- you will have to set it as an environment variable:

`export PIP_NO_BINARY=1 && pipenv install psycopg2`

**Comment by rca** [comment]
@techalchemy setting `PIP_NO_BINARY=':all:'` works for me, setting the value to `ALL` _does not_.

**Comment by techalchemy** [comment]
yeah sorry, my fault for the typo there -- edited my comment also in case people dont scroll down

thanks for posting the update!

**Comment by xarg** [comment]
I just tried this and `PIP_NO_BINARY=':all:'` installs ALL packages as non-binary. Is there a way to install just the psycopg2 package from source?

**Comment by techalchemy** [comment]
Replace `:all:` with `psycopg2`

**Comment by xarg** [comment]
Thanks @techalchemy just saw your comment on https://github.com/pypa/pipenv/issues/1450:

`PIP_NO_BINARY=psycopg2 pipenv install`

seems to work
