### ISSUE TITLE
[ENH] pipenv search?

### ISSUE THREAD

**Issue by achillesrasquinha** [pypa/pipenv#1436]

**Comment by kennethreitz** [comment]
no plans for any new commands at this time

**Comment by fonfon** [comment]
If I understand correct, `pipenv` is at large parts aimed to replace the usage of `pip` for developers. But without a search functionality, users will always have to fall back to using pip.

The first two sentences of the README.md of this project state:

> Pipenv: Python Development Workflow for Humans
> 
> Pipenv is a tool that aims to bring the best of all packaging worlds (bundler, composer, npm, cargo, yarn, etc.) to the Python world.

Why should python users have to deal with two different tools for packaging tasks, whereas with tools like npm or yarn only one tool is needed?
