### ISSUE TITLE
pipenv run: Install packages automatically

### ISSUE THREAD

**Issue by dbrgn** [pypa/pipenv#1443]
##### Current Behavior

When running `pipenv run` in a directory that does not have a virtualenv yet, that virtualenv is automatically generated. But the packages are not installed.

##### Expected Behavior

When a virtualenv is not yet initialized for a project, I would expect the `pipenv run` command to either do nothing, or to create both the virtualenv *and* install the dependencies.

Maybe there are edge cases I haven't thought of yet though?

##### Describe your environment

1. OS Type: Linux
1. Python version: `3.6.4`
1. Pipenv version: `9.0.3`

**Comment by techalchemy** [comment]
Thanks for the recommendation -- we used to do this and I believe we opted to stop. The discussion is likely in an old issue or PR which revolved around changes to the behavior of `pipenv run`

closing for now, thanks for the suggestion!

**Comment by dbrgn** [comment]
Thanks for clarification. I searched for "pipenv run" in the closed issues and the search turned up 396 results, so I didn't manage to find one where this was discussed 🙂

**Comment by code-tree** [comment]
I'm also very confused by this behaviour. If you could give a link to the mentioned issue that would be great, as I don't think this should remain as is.
