### ISSUE TITLE
Pipenv workflow for private authenticated package indexes like Artifactory

### ISSUE THREAD

**Issue by natedub** [pypa/pipenv#1444]
Hi there, I'm looking to switch from plain old pip to pipenv but I'm having trouble finding a comparable workflow for private package indexes that require HTTP Basic Auth specified in the index URL.

With plain old pip (9.0.1), it's quite easy to point to a package index with basic auth using `~/.pip/pip.conf` or `$VIRTUAL_ENV/pip.conf`:
```
[global]
index-url = https://MY_USERNAME:MY_PASSWORD@some.artifactory.mycorp.com/artifactory/api/pypi/python/simple
```

Because of the basic auth in the URL, it's actually beneficial that this is kept separate from our dependencies. We track our requirements in git; meanwhile the creds are kept in an untracked config file that varies for each member of our team (since they'll all have their own personal creds).

Can pipenv support a workflow like this?

FWIW I tried removing the `[[sources]]` section in hopes that it would fall back to `pip.conf`, but no such luck. At least for us, this would be quite amenable as every package is expected to be pulled from our single private index anyway.

Thanks!

##### Describe your environment

1. OSX 10.12
1. Python version: 3.6.2
1. Pipenv version: 9.0.3

**Comment by kennethreitz** [comment]
this is currently unsupported

**Comment by natedub** [comment]
Any interest in supporting this in the future? I'd be willing to contribute if we can come to some agreement on how it would work.

**Comment by tyler-8** [comment]
+1'd OP as this has become something very needed for those of us in more secured environments where an internal "proxy" `pip` (like Artifactory) is the only way to get external pip packages.

**Comment by techalchemy** [comment]
This was already in #1769 and updated in #1809 and #2015 @natedub @tyler-8

**Comment by tyler-8** [comment]
Thanks @techalchemy - I see the way to accomplish this now. https://docs.pipenv.org/advanced/#specifying-package-indexes
