### ISSUE TITLE
Allow pipenv to respect an external configuration to change the default pip mirror

### ISSUE THREAD

**Issue by ninrod** [pypa/pipenv#1451]
@kennethreitz, I have a simple use case that directly if affected by #1040 and #856

I have a project that uses pipenv. I write this project both at home and at work. 
At home, I have no problem, everything works. At work, I have to use the internal pipy index. 

As the Pipfile is commited and pushed to git, I cannot keep changing it as I hop from home to work. 
I would like to have an external configuration that signals to pip that I have to use another index. 

putting this mirror config inside the Pipfile does not work. 

So allow pipenv to use a global configuration, external to the project, to overwrite the default pipy index.

**Comment by kennethreitz** [comment]
closing as we have many existing issues that reflect this
