### ISSUE TITLE
Can not install the package without activating the pipenv shell?

### ISSUE THREAD

**Issue by sbluemin** [pypa/pipenv#1454]
Hi!
I am currently using the Fabric to configure the continuous deploy.
However, there is a problem because can not control the new shell created by "pipenv shell".
Below is the deployment scenario script I tried.

`$ pipenv shell pipenv install && exit`

How do I install the package and auto exit the spawned shell?
Thank you!

**Comment by ScarletMcLearn** [comment]
As the documentations state, you can use "pipenv install --dev" to install your package. it will automatically create a seperate environment. 

if you want to install something globally, use pip to install it.

"pipenv shell" will start the virtualenv shell.

can press ctrl+D to return.

https://pypi.python.org/pypi/pipenv
