### ISSUE TITLE
local editable version still in use after `pipenv uninstall '<hash>'` 

### ISSUE THREAD

**Issue by manihamidi** [pypa/pipenv#1460]
Be sure to check the existing issues, both open and closed.

* You have the latest version of a dependency that's on an index like PyPI installed using `pipenv install dep`. 
* You `import dep`, and check `dep.__file__` and it returns something along the lines of `'/users/<user>/.virtualenvs/madness-HMebEsp1/Lib/site-packages/dep'`, which is good. 
* You want to use `dep` with some custom features, so you clone it onto your disk and use `pipenv install -e /path/to/local/dep` to play with it. 
* You `import dep` and `dep.__file__`  and you get `path/to/local/dep/dep/__init__.py` which makes you happy. The Pipefile now has: `"8c9b980" = {path = "path/to/local/dep", editable = true}` added to it.
* You want to revert back to using the PyPI version because your gave up on your feature, so you uninstall it using `pipenv uninstall '<hash>'` , where <hash> is `8c9b980`. 
* You `import dep` and `dep.__file__`  and you STILL get `path/to/local/dep/dep/__init__.py`, even though `"8c9b980" = {path = "path/to/local/dep", editable = true}` has been removed from the Pipefiles. This makes you sad :disappointed:. 

... or should it? is this by design? Am I missing something about how these editable installs are supposed to be used?
 
##### Describe your environment

1. OS Type windows
1. Python version: `$ python -V` 2.7.12
1. Pipenv version: `$ pipenv --version`  9.0.3

##### Expected result

to see `dep.__file__` return something like `'/users/<user>/.virtualenvs/madness-HMebEsp1/Lib/site-packages/dep` just like it did before the local editable version was installed. 

##### Actual result

see above. 

##### Steps to replicate

see above.

**Comment by techalchemy** [comment]
You need to run `pipenv uninstall <packagename>` per the name of the package defined in the `setup.py` file, just like if you had installed it with pip -- When you install from VCS in the future you can just `pipenv install -e file:///path/to/project#egg=packagename` and it will get installed as `packagename` instead of some hash.  Note that adding `#egg` to a file uri will only work starting with pipenv 9.1.0

Thanks for using pipenv :tada:

**Comment by manihamidi** [comment]
Awesome! thank you very much :handshake:. Upgrading to 9.1.0 right away!
