### ISSUE TITLE
I miss `pip show`

### ISSUE THREAD

**Issue by dradetsky** [pypa/pipenv#1462]
I've recently started using pipenv. I like it, but I miss having `pip show` around. Doing `pip shell ; pip show PKG_NAME` makes me unhappy.

I've started a branch to add this command, although it occurs to me to ask whether this is considered a bad feature to add for some reason, such as because there's another canonical way to get this info that I didn't know about or something.

My WIP PR is #1461. I do plan to make it less crappy, although not before hearing that the basic idea is welcome.

##### Describe your environment

1. Arch Linux
1. Python version: `3.6.4`
1. Pipenv version: `9.0.3`

**Comment by dradetsky** [comment]
For example, I would 

- add a `more_packages` arg to the click cmd, after figuring out how that works, and get info for multiple arguments at once.
- steal more ideas from `pip_install` to make the implementation of `pip_show` more robust.
- add some documentation of the command in various places (advice in re where to find all these places would be totes awesome; is there anything besides `format_help` and `docs/`?)

**Comment by uranusjr** [comment]
You can `pipenv run pip show PACKAGE`. I’m personally -1 to this.

**Comment by dradetsky** [comment]
-1 to using `pipenv run` or -1 to what i'm proposing?

fwiw, I didn't actually know that the `pipenv run ...` solution existed; maybe the answer is a PR which adds "using pip stuff" to dox

**Comment by uranusjr** [comment]
I’m -1 to `pipenv show`, to more generally, any top-level subcommand that is essentially a shortcut to `pipenv run`.

**Comment by uranusjr** [comment]
(Sorry for the extra comment, I submitted too early.)

You’re not the first, and certainly won’t be the last trying to coming up with suggestions due to unawareness to `pipenv run`, and this (to me) shows that the documentation probably needs some re-writing. The `run` subcommand is not present in the Usages section of README, and is only mentioned in a relatively obscure place. Restructuring the documentation a little might be useful. Would it be a possibility @kennethreitz?

**Comment by dradetsky** [comment]
I think I agree with both your -1 and the proposition that the dox need work.

**Comment by ncoghlan** [comment]
+1 for explicitly calling out `pipenv run pip <subcommand>` for getting package level info out of an environment with first running `pipenv shell`. As @uranusjr notes, we don't want to be in the business of shadowing all of `pip`'s subcommands in `pipenv`.
