### ISSUE TITLE
pipenv not on Docker hub anymore

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [pypa/pipenv#1468]
I am using the pipenv Docker image (https://hub.docker.com/r/kennethreitz/pipenv/) to deploy images from it. Unfortunately, since it moved to pypa it hasn't been updated.

##### Describe your environment

1. OS Type: Mac OS High Sierra 10.13.3 (17D47)
1. Python version: 2.7.10
1. Pipenv version: 9.0.3

##### Expected result

I expected the Docker image continue to be updated on pushes to master on this repo or to transition to a new place on Docker hub.

##### Actual result

The old images are not updated and the current Dockerfile as on the `master` branch in this repository is not on Docker hub.

##### Steps to replicate

```Dockerfile
FROM kennethreitz/pipfile
```

gives me an outdated version and I can't make a pull request to fix things because the file is not synced with Docker hub any more.

**Comment by kennethreitz** [comment]
updated

**Comment by Leonidas-from-XIV** [comment]
Thanks a lot!
