### ISSUE TITLE
pipenv shell not working with PIPENV_VENV_IN_PROJECT

### ISSUE THREAD

**Issue by nfvs** [pypa/pipenv#1476]
`pipenv shell` does not seem to work when used with `PIPENV_VENV_IN_PROJECT`

##### Describe your environment

1. MacOS
1. python 3.6.4
1. pipenv 9.1.0

##### Expected result

Pipenv to start a shell using the `.venv` virtualenv.

##### Actual result

Pipenv does not recognize `.venv`

##### Steps to replicate

```
~/Perforce/gitp4/myproject master* ⇡
❯ PIPENV_VENV_IN_PROJECT=true pipenv install --three
Virtualenv already exists!
Removing existing virtualenv…
Creating a virtualenv for this project…
Using /Users/nsantos/.pyenv/versions/3.6.4/bin/python3 to create virtualenv…
⠋Running virtualenv with interpreter /Users/nsantos/.pyenv/versions/3.6.4/bin/python3
Using base prefix '/Users/nsantos/.pyenv/versions/3.6.4'
New python executable in /Users/nsantos/Perforce/gitp4/myproject/.venv/bin/python3
Also creating executable in /Users/nsantos/Perforce/gitp4/myproject/.venv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/nsantos/Perforce/gitp4/myproject/.venv
Installing dependencies from Pipfile.lock (745261)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 46/46 — 00:00:11
Ignoring futures: markers 'python_version == "2.6" or python_version == "2.7"' don't match your environment

~/Perforce/gitp4/myproject master* ⇡ 20s
❯ pipenv shell
Shell for UNKNOWN_VIRTUAL_ENVIRONMENT already activated.
No action taken to avoid nested environments.
```

**Comment by nfvs** [comment]
Seems like the problem is that the venv was created with `PIPENV_VENV_IN_PROJECT`, while `pipenv shell` was not; running `PIPENV_VENV_IN_PROJECT=true pipenv shell` fixes it.

Perhaps pipenv could check the current directory for a `.venv` folder and activate that if found, regardless of the value of `PIPENV_VENV_IN_PROJECT`, but I understand that might not be desirable and might interfere with existing not-created-with-pipenv virtual envs. If so, feel free to close.

**Comment by uranusjr** [comment]
See also #902 and issues referencing it for the design decision, related discussion, and proposed alternatives.

**Comment by timur-gilauri** [comment]
I still facing this issue

**Comment by techalchemy** [comment]
@timur-gilauri you will need to provide substantially more detail. Please file a new issue.
