### ISSUE TITLE
pipenv local install fails without -e

### ISSUE THREAD

**Issue by cdwilson** [pypa/pipenv#1477]
##### Describe your environment

1. OS Type: macOS 10.13.3 (17D102)
1. Python version: Python 3.6.4
1. Pipenv version: pipenv, version 9.1.0

##### Expected result

I expected that running `pipenv install .` would give:

```
[packages]

"e1839a8" = {path = "."}

(or "e1839a8" = {path = ".", editable = false}, not sure which is correct)
```

In addition, I would expect that:

`pipenv install . --dev` would give:

```
[dev-packages]

"e1839a8" = {path = "."}

(or "e1839a8" = {path = ".", editable = false}, not sure which is correct)
```

##### Actual result

_pipenv does not install the local package at all._

However, trying to do the same thing with pip works:

```
$ pipenv shell
$ pip install .
Processing /path/myproject
Installing collected packages: myproject
  Running setup.py install for myproject ... done
Successfully installed myproject-0.1.2
```

Editable installs work as expected:

`pipenv install -e .` gives:

```
[packages]

"e1839a8" = {path = ".", editable = true}
```

`pipenv install -e . --dev` gives:

```
[dev-packages]

"e1839a8" = {path = ".", editable = true}
```

##### Steps to replicate

1. `cd /python/app/source`
2. `pipenv install .` or `pipenv install . --dev`

**Comment by kennethreitz** [comment]
i would not recommend installing a package that way, ever. you should always use -e.

**Comment by cdwilson** [comment]
@kennethreitz from https://pip.pypa.io/en/stable/reference/pip_install/

> Instead of `python setup.py develop`, use...
> 
>     pip install --no-deps -e .
> 
> Instead of `python setup.py install`, use...
> 
>     pip install --no-deps .
> 

Are there benefits to deploying a package in production as editable?  (I understand that for development, it makes sense to use `-e .`, but don't quite understand the use case for production)

**Comment by kennethreitz** [comment]
yes, the code will never get updated unless the version number changes.

**Comment by kennethreitz** [comment]
because it's "already installed"
