### ISSUE TITLE
Installing dev-packages leads to multiple versions of dependencies

### ISSUE THREAD

**Issue by jsma** [pypa/pipenv#1482]
##### Describe your environment

1. OS Type: macOS High Sierra
1. Python version: Python 3.6.3 (via pyenv)
1. Pipenv version: pipenv, version 10.0.0

##### Expected result

The [packages] and [dev-packages] sections of the Pipfile do not appear to be explicitly documented anywhere. From random comments I've seen on other issues and elsewhere, my understanding is that [dev-requirements] is the replacement for a requirements-dev.txt. A common pattern with pip is to only add packages used in a development/testing environment in requirements-dev.txt and then include the line ``--requirement=requirements.txt``, so that ``pip install -r requirements-dev.txt`` will collect the full list of packages to install before resolving dependencies.

If I pin ``Django==1.11.10`` in [packages] but then add e.g. django-debug-toolbar which has its own looser Django requirements in [dev-packages], I expect that ``pipenv install --dev`` will install django-debug-toolbar, but detect that I've locked Django to 1.11.10 in [packages] and only install that version.

##### Actual result

Pipenv appears to install the correct version of Django but then for some reason decides to also install ``Django==2.0.2``, presumably because it sees django-debug-toolbar's looser ``'Django>=1.11'``.

##### Steps to replicate

Here is the simplest Pipfile to reproduce:

    [[source]]

    url = "https://pypi.python.org/simple"
    verify_ssl = true
    name = "pypi"

    [packages]

    django = "==1.11.10"

    [dev-packages]

    django-debug-toolbar = "*"

Here are the steps to reproduce:

    $ mkdir pipenvtest && cd pipenvtest
    $ pipenv install --dev --verbose
    Creating a virtualenv for this project…
    ⠋Using base prefix '/Users/someone/.pyenv/versions/3.6.3'
    New python executable in /Users/someone/.local/share/virtualenvs/pipenvtest-878QcYLX/bin/python
    Installing setuptools, pip, wheel...done.

    Virtualenv location: /Users/someone/.local/share/virtualenvs/pipenvtest-878QcYLX
    Installing dependencies from Pipfile.lock (d5557d)…
    Installing 'django==1.11.10 --hash=sha256:ac4c797a328a5ac8777ad61bcd00da279773455cc78b4058de2a9842a0eb6ee8  --hash=sha256:22383567385a9c406d8a5ce080a2694c82c6b733e157922197e8b393bb3aacd9'
    $ "/Users/someone/.local/share/virtualenvs/pipenvtest-878QcYLX/bin/pip" install   --verbose --no-deps  -r /var/folders/4n/rrlwfns50yq8bk2r0bs96fdw0000gn/T/pipenv-oo9puy8g-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w
    Installing 'pytz==2018.3 --hash=sha256:ed6509d9af298b7995d69a440e2822288f2eca1681b8cce37673dbb10091e5fe  --hash=sha256:f93ddcdd6342f94cea379c73cddb5724e0d6d0a1c91c9bdef364dc0368ba4fda  --hash=sha256:61242a9abc626379574a166dc0e96a66cd7c3b27fc10868003fa210be4bff1c9  --hash=sha256:ba18e6a243b3625513d85239b3e49055a2f0318466e0b8a92b8fb8ca7ccdf55f  --hash=sha256:07edfc3d4d2705a20a6e99d97f0c4b61c800b8232dc1c04d87e8554f130148dd  --hash=sha256:3a47ff71597f821cd84a162e71593004286e5be07a340fd462f0d33a760782b5  --hash=sha256:5bd55c744e6feaa4d599a6cbd8228b4f8f9ba96de2c38d56f08e534b3c9edf0d  --hash=sha256:887ab5e5b32e4d0c86efddd3d055c1f363cbaa583beb8da5e22d2fa2f64d51ef  --hash=sha256:410bcd1d6409026fbaa65d9ed33bf6dd8b1e94a499e32168acfc7b332e4095c0'
    $ "/Users/someone/.local/share/virtualenvs/pipenvtest-878QcYLX/bin/pip" install   --verbose --no-deps  -r /var/folders/4n/rrlwfns50yq8bk2r0bs96fdw0000gn/T/pipenv-y9o613k7-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w
    Installing 'django==2.0.2 --hash=sha256:7c8ff92285406fb349e765e9ade685eec7271d6f5c3f918e495a74768b765c99  --hash=sha256:dc3b61d054f1bced64628c62025d480f655303aea9f408e5996c339a543b45f0'
    $ "/Users/someone/.local/share/virtualenvs/pipenvtest-878QcYLX/bin/pip" install   --verbose --no-deps  -r /var/folders/4n/rrlwfns50yq8bk2r0bs96fdw0000gn/T/pipenv-wltwmmjs-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w
    Installing 'django-debug-toolbar==1.9.1 --hash=sha256:4af2a4e1e932dadbda197b18585962d4fc20172b4e5a479490bc659fe998864d  --hash=sha256:d9ea75659f76d8f1e3eb8f390b47fc5bad0908d949c34a8a3c4c87978eb40a0f'
    $ "/Users/someone/.local/share/virtualenvs/pipenvtest-878QcYLX/bin/pip" install   --verbose --no-deps  -r /var/folders/4n/rrlwfns50yq8bk2r0bs96fdw0000gn/T/pipenv-73tz4ib0-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w
    Installing 'pytz==2018.3 --hash=sha256:ed6509d9af298b7995d69a440e2822288f2eca1681b8cce37673dbb10091e5fe  --hash=sha256:f93ddcdd6342f94cea379c73cddb5724e0d6d0a1c91c9bdef364dc0368ba4fda  --hash=sha256:61242a9abc626379574a166dc0e96a66cd7c3b27fc10868003fa210be4bff1c9  --hash=sha256:ba18e6a243b3625513d85239b3e49055a2f0318466e0b8a92b8fb8ca7ccdf55f  --hash=sha256:07edfc3d4d2705a20a6e99d97f0c4b61c800b8232dc1c04d87e8554f130148dd  --hash=sha256:3a47ff71597f821cd84a162e71593004286e5be07a340fd462f0d33a760782b5  --hash=sha256:5bd55c744e6feaa4d599a6cbd8228b4f8f9ba96de2c38d56f08e534b3c9edf0d  --hash=sha256:887ab5e5b32e4d0c86efddd3d055c1f363cbaa583beb8da5e22d2fa2f64d51ef  --hash=sha256:410bcd1d6409026fbaa65d9ed33bf6dd8b1e94a499e32168acfc7b332e4095c0'
    $ "/Users/someone/.local/share/virtualenvs/pipenvtest-878QcYLX/bin/pip" install   --verbose --no-deps  -r /var/folders/4n/rrlwfns50yq8bk2r0bs96fdw0000gn/T/pipenv-cdi6zc49-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w
    Installing 'sqlparse==0.2.4 --hash=sha256:d9cf190f51cbb26da0412247dfe4fb5f4098edb73db84e02f9fc21fdca31fed4  --hash=sha256:ce028444cfab83be538752a2ffdb56bc417b7784ff35bb9a3062413717807dec'
    $ "/Users/someone/.local/share/virtualenvs/pipenvtest-878QcYLX/bin/pip" install   --verbose --no-deps  -r /var/folders/4n/rrlwfns50yq8bk2r0bs96fdw0000gn/T/pipenv-wouu0lw0-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w
    Collecting django==1.11.10 (from -r /var/folders/4n/rrlwfns50yq8bk2r0bs96fdw0000gn/T/pipenv-oo9puy8g-requirement.txt (line 1))
      1 location(s) to search for versions of django:

    ...snip, but here the correct version is installed...

      Using version 1.11.10 (newest of versions: 1.11.10)
      Looking up "https://pypi.python.org/packages/32/44/a9afb2b7dd641d89341a2126020bbda9201d270e23e4ffe2601eeaaabcfd/Django-1.11.10-py2.py3-none-any.whl" in the cache
      Current age based on date: 4492
      Freshness lifetime from max-age: 31557600
      The response is "fresh", returning cached response
      31557600 > 4492
      Using cached Django-1.11.10-py2.py3-none-any.whl
      Downloading from URL https://pypi.python.org/packages/32/44/a9afb2b7dd641d89341a2126020bbda9201d270e23e4ffe2601eeaaabcfd/Django-1.11.10-py2.py3-none-any.whl#md5=dc59370ed297d818fe90b873fb22c901 (from https://pypi.python.org/simple/django/)
    Installing collected packages: django

      changing mode of /Users/john-scott/.local/share/virtualenvs/pipenvtest-878QcYLX/bin/django-admin to 755
    Successfully installed django-2.0.2
    Cleaning up...

    Collecting pytz==2018.3 (from -r /var/folders/4n/rrlwfns50yq8bk2r0bs96fdw0000gn/T/

    ...snip hundreds of lines listing out every known version of pytz...

      Using version 2018.3 (newest of versions: 2018.3)
      Looking up "https://pypi.python.org/packages/3c/80/32e98784a8647880dedf1f6bf8e2c91b195fe18fdecc6767dcf5104598d6/pytz-2018.3-py2.py3-none-any.whl" in the cache
      Current age based on date: 4499
      Freshness lifetime from max-age: 31557600
      The response is "fresh", returning cached response
      31557600 > 4499
      Using cached pytz-2018.3-py2.py3-none-any.whl
      Downloading from URL https://pypi.python.org/packages/3c/80/32e98784a8647880dedf1f6bf8e2c91b195fe18fdecc6767dcf5104598d6/pytz-2018.3-py2.py3-none-any.whl#md5=a32aa7e834a17d5b14d099924870485c (from https://pypi.python.org/simple/pytz/)
    Installing collected packages: pytz

    Successfully installed pytz-2018.3
    Cleaning up...

    Collecting django==2.0.2 (from -r /var/folders/4n/rrlwfns50yq8bk2r0bs96fdw0000gn/T/pipenv-wltwmmjs-requirement.txt (line 1))
      1 location(s) to search for versions of django:

    ...snip list of all versions of Django, but now it's installing the wrong version...

      Using version 2.0.2 (newest of versions: 2.0.2)
      Looking up "https://pypi.python.org/packages/48/b1/4e4875dabd9603c89ca753313fd13f429426e4a80a0264603a30d56e0338/Django-2.0.2-py3-none-any.whl" in the cache
      Current age based on date: 4502
      Freshness lifetime from max-age: 31557600
      The response is "fresh", returning cached response
      31557600 > 4502
      Using cached Django-2.0.2-py3-none-any.whl
      Downloading from URL https://pypi.python.org/packages/48/b1/4e4875dabd9603c89ca753313fd13f429426e4a80a0264603a30d56e0338/Django-2.0.2-py3-none-any.whl#md5=36d3f5a7f230296c040b11344f48ffce (from https://pypi.python.org/simple/django/) (requires-python:>=3.4)
    Installing collected packages: django

      changing mode of /Users/john-scott/.local/share/virtualenvs/pipenvtest-878QcYLX/bin/django-admin to 755
    Successfully installed django-2.0.2
    Cleaning up...

    Collecting django-debug-toolbar==1.9.1 (from -r /var/folders/4n/rrlwfns50yq8bk2r0bs96fdw0000gn/T/pipenv-73tz4ib0-requirement.txt (line 1))
      1 location(s) to search for versions of django-debug-toolbar:

    ...snip, django-debug-toolbar gets installed, pytz gets reinstalled, and then it finishes with installing the final dependency of sqlparse...

      Using version 0.2.4 (newest of versions: 0.2.4)
      Looking up "https://pypi.python.org/packages/65/85/20bdd72f4537cf2c4d5d005368d502b2f464ede22982e724a82c86268eda/sqlparse-0.2.4-py2.py3-none-any.whl" in the cache
      Current age based on date: 4503
      Freshness lifetime from max-age: 31557600
      The response is "fresh", returning cached response
      31557600 > 4503
      Using cached sqlparse-0.2.4-py2.py3-none-any.whl
      Downloading from URL https://pypi.python.org/packages/65/85/20bdd72f4537cf2c4d5d005368d502b2f464ede22982e724a82c86268eda/sqlparse-0.2.4-py2.py3-none-any.whl#md5=f6206be02d016858fe59a6e62db3a469 (from https://pypi.python.org/simple/sqlparse/)
    Installing collected packages: sqlparse

      changing mode of /Users/someone/.local/share/virtualenvs/pipenvtest-878QcYLX/bin/sqlformat to 755
    Successfully installed sqlparse-0.2.4
    Cleaning up...

      🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 6/6 — 00:00:08
    To activate this project's virtualenv, run the following:
     $ pipenv shell

Once it completes, check the django version:

    iMac:pipenvtest$ pipenv shell
    Spawning environment shell (/usr/local/bin/bash). Use 'exit' to leave.
    . /Users/someone/.local/share/virtualenvs/pipenvtest-878QcYLX/bin/activate
    iMac:pipenvtest$ . /Users/someone/.local/share/virtualenvs/pipenvtest-878QcYLX/bin/activate
    (pipenvtest-878QcYLX) iMac:pipenvtest$ python
    Python 3.6.3 (default, Jan  8 2018, 22:37:25)
    [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import django
    >>> django.get_version()
    '2.0.2'

The only way I can get pipenv to only install the correct version of Django, is to duplicate the Django pinned requirement under [dev-packages].

**Comment by kennethreitz** [comment]
closing, as this is a known issue

**Comment by Hellzed** [comment]
@kennethreitz I can't find the original known issue you mentioned, and I'm not reproducing this behaviour after taking the steps the OP mentioned.
Was this fixed?
