### ISSUE TITLE
hello I would like to collaborate with your project by serving as a translator to Spanish which is my native language could translate the readme and contribute

### ISSUE THREAD

**Issue by UlisesTJ** [pypa/pipenv#1483]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

##### Describe your environment

1. OS Type
1. Python version: `$ python -V`
1. Pipenv version: `$ pipenv --version`

##### Expected result

Describe what you expected.

##### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

**Comment by knz** [comment]
@UlisesTJ https://github.com/cockroachdb/cockroach/issues/23038#issuecomment-368220870
