### ISSUE TITLE
Freeze + download commands

### ISSUE THREAD

**Issue by tomasbedrich** [pypa/pipenv#1488]
It may be handful to proxy some other pip commands to work with pipenv.

##### Expected result

Resolve and freeze all dependencies from Pipfile to "requirements.txt format".

```
$ pipenv freeze --dev
requests==2.18.4
```

##### Current workaround

Requires installation before freezing.

```
$ pipenv install --dev
$ pipenv run pip freeze
requests==2.18.4
```

##### Expected result

Resolve and download all packages from Pipfile to some destination directory.

```
$ pipenv download --dev -d ./dest
```

##### Current workaround

Requires installation and freezing before downloading.

```
$ pipenv install --dev
$ pipenv run pip freeze > requirements.txt
$ pipenv run pip download -d ./dest -r requirements.txt
```

**Comment by kennethreitz** [comment]
just use pip

**Comment by tomasbedrich** [comment]
What do you think about a need to install all the packages just to generate a freeze list? Such list can be generated only based on Pipfile(.lock) for sure.

**Comment by uranusjr** [comment]
Is `pipenv lock --requirements` not enough?

**Comment by tomasbedrich** [comment]
I am convinced, that it would be possible to somehow isolate the Pipenv from the system and user packages just for running single command without a need to create a virtualenv.

But of course I also understand, that it would be tremendous amount of work with little benefit.

So thank you for now, `pipenv lock --requirements` is not perfect, but good enough. 👍

**Comment by techalchemy** [comment]
@tomasbedrich how would you propose resolving a dependency graph deterministically for a single package without a virtualenv to isolate it?

**Comment by kennethreitz** [comment]
@techalchemy "So thank you for now, pipenv lock --requirements is not perfect, but good enough. 👍"

**Comment by techalchemy** [comment]
Yeah just curious if there is a way I haven’t considered
