### ISSUE TITLE
Dependencies are not update to Pipfile.lock when package format is file

### ISSUE THREAD

**Issue by jxltom** [pypa/pipenv#1498]
When package format is file such as ```flask-admin = {file = "https://github.com/flask-admin/flask-admin/archive/2c2c98e.zip"}```, it's dependency can not be updated to ```Pipfile.lock``` correctly. For above example, wtform is obvious a dependendy of flask-admin and one can also check it by ```pipenv graph```, but it is not pinned in ```Pipfile.lock``` and then it won't be installed by ```pipenv install```.

##### Describe your environment

1. Ubuntu 16.04
1. Python version: `$ python -V`: 2.7.12
1. Pipenv version: `$ pipenv --version`: 10.1.0

**Comment by kennethreitz** [comment]
it must be editable.

**Comment by jxltom** [comment]
But it looks like file mode does not support ```editable = true```.

```pipenv install``` will raise ```pip.exceptions.InstallationError: https://github.com/flask-admin/flask-admin/archive/2c2c98e.zip should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+```

I didn't find a detailed document about approprate VCS file format.

**Comment by jxltom** [comment]
OK. I found correct format should be ```flask-admin = {git= "https://github.com/flask-admin/flask-admin.git@2c2c98e", editable = true}```

**Comment by techalchemy** [comment]
Yes the pip-tools resolver doesn't currently resolve remote URLs unfortunately
