### ISSUE TITLE
"pipenv install --user"

### ISSUE THREAD

**Issue by gsemet** [pypa/pipenv#1500]
Hello

Can we imagine a "--user" option for "pipenv install", that would allow a content of a Pipfile/Lock to be installed into the ~/.local directory of the user? Pip provides this option, and is used by pipenv to update itself.
I should not be the "normal" way of using pipenv, but since there is a "--system" that install on the system (requiring sudo permission), a similar "--user" can be useful.

I am looking for this option especially for embedded the application inside a docker image, most of a time it is fine to recreate a virtualenv inside the docker (it is still better than using "--system" even from inside a docker), but sometimes we want the application directly callable by the docker user.

thanks

**Comment by kennethreitz** [comment]
i think this would complicate things.

**Comment by gsemet** [comment]
For the moment, I replace this behavior with the following snippet in my Docker file:
```
RUN pipenv install --dev \
    &&  pipenv run pipenv_to_requirements \
    &&  pip install --user requirements.txt
```

**Comment by uranusjr** [comment]
@gsemet But why? I thought one of the main virtue of using Docker is you get a whole clean system for yourself, and don’t need to worry about system/user distinction in the first place, is it not?

**Comment by gsemet** [comment]
My use case is when replacing requirements.txt for jupyter notebook docker. I need to install python package to current user only (because of npm dependencies).

But I think it is a legit need, even inside a docker image, changing the system python package can lead to unwanted issues

**Comment by uranusjr** [comment]
Wouldn’t a virtualenv be better, thinking along that line? It’s even more isolated than `--user`.

**Comment by gsemet** [comment]
sure, that's why i said "I should not be the "normal" way". But for jupyter we typically install several kernels (anaconda's environment or virtualenv) in the image so user choose which one.

The option ``--user`` is available for ``pip``, and is heavily used by pipenv itself. It is legit to understand similar situation might occur to programs packaged by pipenv themselve.
