### ISSUE TITLE
Support passing through find_links option to pip

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [pypa/pipenv#1501]
I want to install package which take ages and lots of RAM to compile from source from wheels instead. I was able to build the wheel just fine on a different machine with the same system.

##### Describe your environment

1. OS Type: Docker
2. Python version: `3.6.4` 
1. Pipenv version: `9.1.0`

##### Expected result

I expected it to take the `find_links` option from my `Pipfile` and pass it to `pip` when calling `pip install`

##### Actual result

It does not pass this option, thus `pip` starting to build, taking forever and failing with an out of memory error eventually.

##### Steps to replicate

Add `find_links = "wheelhouse/"` to your `Pipfile` `[[source]]` section.

**Comment by kennethreitz** [comment]
this seems like a good idea.

**Comment by techalchemy** [comment]
The advice we have been giving to people who raise this issue (this has been raised in a bunch of other places) is to use the environment variable `PIP_FIND_LINKS` to configure this, ideally in the future we can pull this from the pip config (but if Kenneth likes this in the sources section that seems like a good idea as well)

**Comment by jtratner** [comment]
One potential issue: does `find_links` work with [hash checking](https://pip.pypa.io/en/stable/reference/pip_install/#hash-checking-mode) mode in pip?

**Comment by Leonidas-from-XIV** [comment]
@jtratner It does, but unfortunately the `Pipfile.lock` uses the SHA256 of the source tarball not the wheel. When manually editing it to the SHA256 of the wheel it installs it just fine.

@techalchemy Whou, that's an excellent suggestion. It works! The only problem I have now is that `pipenv lock` is understandably not aware of the wheel and records the hash of the source tarball in the `Pipfile.lock` instead of the wheel.

**Comment by techalchemy** [comment]
@Leonidas-from-XIV @jtratner I believe the real solution we will want to use is to always first generate a hash of the actual installation file we are using and add that as a main comparison point in some way

/cc @nateprewitt
