### ISSUE TITLE
All requirements are commented out after `pipenv lock -r`

### ISSUE THREAD

**Issue by MarcDufresne** [pypa/pipenv#1503]
Since the update to 10.X all our `requirements.txt` files get commented out because of this specific piece of code: https://github.com/pypa/pipenv/blob/master/pipenv/core.py#L802

It wants the dependencies to include `--hash` but generating the lock file does not populate the hashes. And in our situation we can't use hashes because our team is a mix of different linux distros and macOS, so hashes are useless.

I suggest adding a flag to the `lock` command to ignore the `'--hash' not in dep[0]` requirement.

Something like:

```python
if '--hash' not in dep[0] and not ignore_pip_hash_mode:
```

##### Describe your environment

1. OS version: macOS 10.13, Ubuntu 16.04, Arch Linux x86_64 Linux 4.15.5-1-ARCH
1. Python version: 3.6.3, 3.6.4
1. Pipenv version: v10.1.0

##### Expected result

Normal requirement file, with no requirement being commented out.

```
alembic==0.9.7
arrow==0.12.1
mako==1.0.7
markupsafe==1.0
munch==2.2.0
pymysql==0.7.11
python-dateutil==2.6.1
python-editor==1.0.3
pyyaml==3.12
six==1.11.0
sqlalchemy==1.1.15
ujson==1.35
```

##### Actual result

Commented out requirements

```
# alembic==0.9.7
# arrow==0.12.1
# mako==1.0.7
# markupsafe==1.0
# munch==2.2.0
# pymysql==0.7.11
# python-dateutil==2.6.1
# python-editor==1.0.3
# pyyaml==3.12
# six==1.11.0
# sqlalchemy==1.1.15
# ujson==1.35
```

##### Steps to replicate

Pipfile:
```
[[source]]
url = "https://our.custom.devpi.com/simple"
verify_ssl = true

[requires]
python_version = "3.6"

[packages]
alembic = ">=0.9,<0.10"
arrow = ">=0.12.0"
Munch = "*"
PyYAML = ">=3.12,<4"
sqlalchemy = ">=1.1,<1.2"
ujson = "*"
PyMySQL = ">=0.7,<0.8"

[dev-packages]
pytest = ">=3.0,<3.1"
pytest-cov = ">=2.4,<2.5"
flake8 = "*"
yapf = "*"
```

Commands:
```bash
$ pipenv lock -r
```

This works fine on 9.0.3, but not on 10.1.0. 
We started seeing the issue on 9.1.0 where only `six` would get commented out.

We've noticed that the issue does not happen (hashes get populated in the lock file) when using `https://pypi.python.org/simple` as a source url, but we have closed source packages that we can't make public so we have to use our own devpi server. And AFAIK hashes don't work across different OSes, so we'd still have an issue, albeit a different one.

**Comment by kennethreitz** [comment]
projects without hashes are commented out

**Comment by MarcDufresne** [comment]
> projects without hashes are commented out

Yes, that's the issue... 🤔

**Comment by kennethreitz** [comment]
this is a feature, not a bug, currently.

**Comment by jtratner** [comment]
@kennethreitz - I just hit this trying to generate a requirements.txt for comparison with my existing one while trying to convert to pipenv. 

Looks like this can happen if you use an internal PyPI that doesn't append hashes to URLs (in which case `pipenv install` has no hashes).  My googling is failing on when/how this was added to PyPI and how the "PyPI API" might be supposed to work.

Any pointers on how this was added to PyPI or specs on the hashing?

**Comment by techalchemy** [comment]
@jtratner we pull hashes from the `PyPIRepository` object from pip-tools (which basically proxies it to pip)  and from the json api as a fallback.  For another repository to work it would have to provide hashes, and, realistically, we would want to do our own hashing as well.

**Comment by jtratner** [comment]
@techalchemy - thanks - that's a really helpful pointer! I'll go poke around there :)

**Comment by jtratner** [comment]
Dug up some more info: devpi is a popular tool to run custom indexes/mirrors (e.g. Counsyl uses it internallly). devpi generates hashes - `https://m.devpi.net/devpi-travis/devpi_devpi_client-4.0.1/+f/962/034168a6d9448/devpi-client-4.0.1.tar.gz#sha256=962034168a6d9448d777eaab35f87658dcafa593807591e0dee16fb70acd79f8`.

And I confirmed that `pip install -r requirements.txt --require-hashes` works correctly against a devpi server (installing if correct and failing if the hash does not match).

This makes me think it'll be not-too-hard to get this to work for custom mirrors. Will try to put together a PR :)

**Comment by techalchemy** [comment]
I don’t think these are actually read from the URL though — hopefully this will save you some time since I know myself, Kenneth and Vincent probably have a collective 60 hours on this — hashes come from the PyPIRepository object which is also used for private urls, this prefers the xmlrpc lookup method for packages and metadata and uses the json api as a fallback, this is necessary because we include all possible hashes when locking. The url only includes the hash of the one being downloaded.

**Comment by jtratner** [comment]
@techalchemy - empirically, I got it to work here - https://github.com/pypa/pipenv/pull/1504

**Comment by techalchemy** [comment]
Oh nice that’s clever. Not a complete fix but something workable anyway
