### ISSUE TITLE
Pipenv doesn't install development packages

### ISSUE THREAD

**Issue by wvxvw** [pypa/pipenv#1511]
##### Describe your environment

1. OS Type
1. Python version: far too many
1. Pipenv version: 8.3.2

##### Expected result

Install development packages

##### Actual result

Nothing is installed

##### Steps to replicate

``` sh
$ cat ./Pipfile | grep -B5 -A5 pytest
[dev]
"autopep8" = "*"
"flake8" = "*"
ipython = "*"
pylint = "*"
pytest = "*"
yapf = "*"


[requires]
python_version = '3.6'
```

``` sh
$ pipenv install --dev
Installing dependencies from Pipfile.lock (287b16)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

``` sh
find $(pipenv --venv)/lib/python$(grep python_version ./Pipfile | grep -Po '[0-9.]+')/site-packages -name pytest
# produces no output
```

``` sh
$ find $(pipenv --venv)/lib/python$(grep python_version ./Pipfile | grep -Po '[0-9.]+')/site-packages -name setuptools
/home/$USER/.local/share/virtualenvs/piller-_Obv8KIK/lib/python3.6/site-packages/setuptools
```

PS. I have no idea what 2/2 refers to in the `pipenv install` output. There's absolutely nothing in Pipfile that is a two, it's either more or less, but not exactly equal to two.  When I run with `--verbose`, there's no mention of development packages in output.  Same story for `pipenv update`.  `Pipfile.lock` contains no mention of development packages.

**Comment by wvxvw** [comment]
Note that modifying the section `[dev]` to `[dev-packages]` does solve this problem.  I cannot find the documentation, but I believe this was the way to specify development packages some time ago (like a few months at least?)

**Comment by rhymes** [comment]
@wvxvw don't know, it has been dev-packages for a while. But anyhow you should let "pipenv" write your Pipfile for you.

**Comment by kennethreitz** [comment]
it's always been `[dev-packages]`. Part of the Pipfile standard.
