### ISSUE TITLE
How to update packages

### ISSUE THREAD

**Issue by rhymes** [pypa/pipenv#1515]
Now that `pipenv update` it's gone, I'm not really sure how can I update packages locally.

##### Describe your environment

1. MacOSX 10.13
1. Python version: 3.6.4
1. Pipenv version: 10.0.0

##### Expected result

```shell
$ pipenv run pip list --outdated
Package       Version Latest Type
------------- ------- ------ -----
boto3         1.5.35  1.6.1  wheel
botocore      1.8.49  1.9.1  wheel
flake8-quotes 0.13.1  0.14.0 sdist
SQLAlchemy    1.1.17  1.2.4  sdist
tqdm          4.19.5  4.19.6 wheel

$ pipenv sync --dev
[...]

$ pipenv run pip list --outdated
Nothing outdated
```

##### Actual result

I also tried with `pipenv install --dev` but I'm not really sure how to update packages.

The content of my Pipfile is something like this:

```ini
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

"psycopg2" = "*"

[dev-packages]

pytest = "*"

[requires]

python_full_version = "3.6.4"
```

with all other packages listed as "*"

**Comment by kennethreitz** [comment]
$ pipenv lock
    $ pipenv sync

**Comment by techalchemy** [comment]
Now also `pipenv update` once again!
