### ISSUE TITLE
`pipenv --venv` doesn't work for non-pipenv venv without Pipfile

### ISSUE THREAD

**Issue by jtdoepke** [pypa/pipenv#1518]
While using a not-created-by-pipenv virtualenv, running `pipenv --venv` when a Pipfile is not present does not print a path to the current virtualenv.

##### Describe your environment

1. OS Type: Fedora 27 (4.15.4-300.fc27.x86_64)
1. Python version: pipenv installed with Python 3.6.4. Tested with virtualenvs from Python 3.6.4 and 2.7.14.
1. Pipenv version: 10.1.2

##### Expected result

A path to the current virtualenv.

##### Actual result

```
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
No virtualenv has been created for this project yet!
```

##### Steps to replicate

```
$ mkdir venv_test
$ cd venv_test
$ virtualenv venv
$ . venv/bin/activate
$ pipenv --venv
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
No virtualenv has been created for this project yet!

$ touch Pipfile
$ pipenv --venv
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
/home/jtdoepke/Development/venv_test/venv
```

**Comment by uranusjr** [comment]
The Pipfile is required to associate the project to the virtualenv.

**Comment by jtdoepke** [comment]
Not the behavior I intuitively expected. Perhaps some clearer documentation?

**Comment by uranusjr** [comment]
Sure, just submit a pull request.
