### ISSUE TITLE
Let `pipenv shell` work when $SHELL is just an executable name, not a path

### ISSUE THREAD

**Issue by fictionic** [pypa/pipenv#1520]
Originally I had `export SHELL=zsh`, and I experienced no shell-opening-related problems with any software. Then I got the error
```
pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: /path/to/my/project/zsh
```
when running `pipenv shell`. Of course this was fixed by changing my startup files to `export SHELL=/usr/bin/zsh`, but I find it odd that this is the first time this has caused a problem. ArchWiki does say that $SHELL should be "the path to your prefered shell", so I'm not arguing that pipenv has a *bug* per se, but that it should be more accommodating of people whose configuration is not perfect.

##### Describe your environment

1. Arch Linux
1. Python version: 3.6.4
1. Pipenv version: 10.0.1

##### Expected result

`pipenv shell` should work.

##### Actual result

I get the error reproduced above.

##### Steps to replicate

```
$ export SHELL=bash # or whatever you have installed
$ pipenv --three
$ pipenv shell
```

Thanks!

**Comment by fictionic** [comment]
Mind giving an explanation?

**Comment by uranusjr** [comment]
As you said, it is not a Pipenv problem. You *should* configure your `$SHELL` correctly. Masking this error might be the easy way out right now, but is just asking for trouble in the long run. At least it is relatively easy for the user to find out as things are right now.

**Comment by fictionic** [comment]
Fair enough. But why is it asking for trouble? This is literally the first time in years I've run into any problems with my `$SHELL` set this way.

**Comment by uranusjr** [comment]
I was talking about supressing errors in general, not particularly about this instance.
