### ISSUE TITLE
Misleading message for "pipenv --venv" without correct PATH on FreeBSD

### ISSUE THREAD

**Issue by aidik** [pypa/pipenv#1525]
Running `/usr/local/bin/pipenv --venv` without actually exporting the correct PATH variable produces inconclusive and misleading message: **_"No virtualenv has been created for this project yet!"_** 

This snippet
```
export LC_ALL="en_US.UTF-8"
echo $(/usr/local/bin/pipenv --venv)
export PATH=/usr/local/sbin:/usr/local/bin:/root/bin:$PATH
echo $(/usr/local/bin/pipenv --venv)
```
 would produce following
```
No virtualenv has been created for this project yet!

/.local/share/virtualenvs/myapp-dU9nX2_T
```

##### Describe your environment

1. FreeBSD 11.1-RELEASE-p4
1. Python 3.6.4
1. pipenv, version 10.1.2

##### Expected result
Somewhat more conclusive message. For example:
`Warning: it looks like XYZ is not in your PATH. We cannot continue until this is resolved.`

##### Actual result

The inconclusive message:
`No virtualenv has been created for this project yet!`

##### Steps to replicate
Please see the snippet above.

**Comment by kennethreitz** [comment]
that is where your project would be if it was created.

**Comment by aidik** [comment]
But the project does indeed exist. 

The issue lays elsewhere. If you look at the snippet

The second line produces `No virtualenv has been created for this project yet!`
while the fourth line after the correct path to python is added to the PATH variable produces the expected result.

So the issue is that the message produced by the second line is misleading, the problem is not the non-existence of the project and/or of the vitualenv.

Please give my original post one more read. Thank you in advance.

**Comment by techalchemy** [comment]
So the actual description of your problem is that when `pew`, `pipenv`, `virtualenv` and such are not on your path, pipenv can’t find your environments? That’s not surprising. FYI as we triage many issues it is much easier if you make it clear what exactly you think should be happening vs what is happening, simply providing output usually is just confusing. 

In this case it seems like the only issue might be around error messaging?

**Comment by aidik** [comment]
**@techalchemy, yes the problem is that I would imagine the error message to reflect the issue.** 

Of course, I'm not surprised that `pipenv` is not working without a proper path. It is completely logical. 

Sorry about not being clear in my original post, I will try to explain and illustrate it better next time there is an issue.


Thank you.

**Comment by aidik** [comment]
@kennethreitz would you please reconsider opening of this issue? I understand that a nicer error message might not be the top of your priorities, but it is definitely not something deserving immediate dismissal.

**Comment by uranusjr** [comment]
@aidik Would you be interested in submitting a pull request? I believe it may be much easier to get your point across with code and a test case that demonstrates the improvement.
