### ISSUE TITLE
Unable to activate new virtualenv

### ISSUE THREAD

**Issue by jamesstidard** [pypa/pipenv#1527]
Hi,

I've got little experience with pipenv, though I believe I'm getting some unexpected behaviour.

I'm using `macOS 10.13.3 (17D102)` and I used brew to install `pipenv`. I also have `pyenv` installed also via `brew`. The version informations are also in the attach screenshot.

I'm trying to make a new project and activate it's virtual environment in the shell. However, I'm unable to and get a UNKNOWN_VIRTUAL_ENVIROMENT message. See screenshot.

Am I missing some additional configuration?

<img width="1351" alt="screen shot 2018-03-02 at 14 47 26" src="https://user-images.githubusercontent.com/1797906/36904667-34d13926-1e29-11e8-822e-548cb086a072.png">

Thanks

**Comment by kennethreitz** [comment]
something is setting 'VIRTUAL_ENV' environment variable

**Comment by jamesstidard** [comment]
@kennethreitz strange, it seems to resolve itself and VIRTUAL_ENV also appears unset - so could have been the problem. Anyway, thanks.

**Comment by techalchemy** [comment]
Can you provide the output of `env`, specifically looking for `SHELL`, `LC_ALL`, `VIRTUAL_ENV`, and all pipenv or pyenvv specific settings

**Comment by jamesstidard** [comment]
@techalchemy Only have `SHELL` set from my scan. But here's the complete list

```bash
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.JYLoov7PjZ/Render
COLORFGBG=15;0
COLORTERM=truecolor
COMMAND_MODE=unix2003
DISPLAY=/private/tmp/com.apple.launchd.E4VVswKRcQ/org.macosforge.xquartz:0
HOME=/Users/james
ITERM_PROFILE=Default
ITERM_SESSION_ID=w0t0p0:DF367973-E070-4F84-9BE5-930255A8B432
LANG=en_GB.UTF-8
LOGNAME=james
PATH=/Users/james/.pyenv/shims:/Users/james/.local/bin/:/Users/james/.fastlane/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin
PIPSI_HOME=/Users/james/.local/share/virtualenvs/
PWD=/Users/james
PYENV_SHELL=fish
SECURITYSESSIONID=186a7
SHELL=/usr/local/bin/fish
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.bzKj5oQeat/Listeners
TERM=xterm-256color
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.1.5
TERM_SESSION_ID=w0t0p0:DF367973-E070-4F84-9BE5-930255A8B432
TMPDIR=/var/folders/0p/ljj7lrds2gb6tpg5gjpnhbbr0000gn/T/
USER=james
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
__CF_USER_TEXT_ENCODING=0x0:0:0
```
