### ISSUE TITLE
Hash order is not deterministic

### ISSUE THREAD

**Issue by hynek** [pypa/pipenv#1529]
The order of hashes in both Pipfile.lock and --requirements output is not deterministic: every `pipenv update` shuffles them around which makes running an update and checking for changes pointless.

##### Describe your environment

1. OS Type macOS High Sierra
1. Python version: `$ python -V` 3.6.4
1. Pipenv version: `$ pipenv --version` 10.1.2

NB I’m using devpi as a PyPI mirror.

##### Expected result

The hashes should be in a stable order. Easiest would be to just sort them alphabetically.

##### Actual result
 
The order changes with every run.

##### Steps to replicate

Install a bunch of packages, run update. Watch hashes permutate.

**Comment by kennethreitz** [comment]
thanks for the excellent suggestion!

**Comment by kennethreitz** [comment]
11.0.2 released, which contains this
