### ISSUE TITLE
package install ends with temp files not deleted

### ISSUE THREAD

**Issue by apiraino** [pypa/pipenv#1530]
When `pipenv install` finishes installing packages there are leftovers in `/tmp/pipenv-xxxxx-requirement.txt` (one per package installed).

##### Describe your environment

1. `Linux 4.13.0-36-generic #40-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux`
2. Python version: tested with 2.7.14 and 3.6.4
3. Pipenv version: 10.1.2

##### Expected result

no tmp files left

##### Actual result

many tmp files in /tmp 

##### Steps to replicate

just install any package

The issue is caused IMO by running pipenv concurrently, the tmp file cannot be immediately deleted [at this point](https://github.com/pypa/pipenv/blob/5ba8c9cf2484d257c21ded9eeca7f981bc911d0a/pipenv/core.py#L1465). 

I think we can add a small cleanup task similar to `pipenv.utils.rmtree()` at `pipenv/core.py +890` when we're sure that the job is finished.
A couple of options for this:

1) `pipenv.core.pip_install()` returns also a list of files that has used but not deleted. Our cleanup task takes it as input and does the cleanup at the very end of `pipenv.core.do_install_dependencies()` before returning.

2) Or  one can amend the `project.Project` adding the temp dir where the requirement files are created so the cleanup task can be executed with something like `rmtree(project.tmp_requirements_location)`.

Any thoughts on this issue?

If you agree with the proposed solution, I can submit a patch for evaluation. 

Thanks!

**Comment by kennethreitz** [comment]
known issue ;)

**Comment by kennethreitz** [comment]
Closing for #1538
