### ISSUE TITLE
pipenv fails if there's a "&" in path

### ISSUE THREAD

**Issue by xNathan** [pypa/pipenv#1543]
I failed to create a virtual environment using pipenv if there's a  "&" in path.

It seems pipenv doesn't proper process special symbols in path.

##### Describe your environment

1. macOS 10.13.3
1. Python version: `Python 3.6.4 :: Anaconda custom (64-bit)
1. Pipenv version: `pipenv 11.0.2`

##### Expected result

Create virtualenv and Pipfile.

##### Actual result
```bash
$ pipenv install
Creating a virtualenv for this project…
⠋Using base prefix '/Users/nathan/anaconda3'
New python executable in /Users/nathan/.local/share/virtualenvs/A&B-9-zczMNG/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/nathan/.local/share/virtualenvs/A&B-9-zczMNG
Creating a Pipfile for this project…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
 directory
/bin/sh: B-9-zczMNG/bin/python: No such file or directory
```

##### Steps to replicate
```bash
$ mkdir "~/foo&bar"
$ cd "~/foo&bar"
$ pipenv install
```

**Comment by techalchemy** [comment]
Based on the messages it looks to me like pipenv actually had no trouble _creating_ the virtualenv, but some later command during the locking process broke. Can you check whether the virtualenv directory exists?

**Comment by kennethreitz** [comment]
delegator woes. i'll close this as won'tfix for now.

**Comment by xNathan** [comment]
I tried again, the virtualenv directory exists.
But fails when creating `Pipfile.lock`.

And I can't activate virtualenv using `pipenv shell`
This is output:
```bash
~/foo&bar ❯❯❯  pipenv shell
Spawning environment shell (/usr/local/bin/zsh). Use 'exit' to leave.
. /Users/nathan/.local/share/virtualenvs/foo&bar-LOHawtln/bin/activate
~/foo&bar ❯❯❯ . /Users/nathan/.local/share/virtualenvs/foo&bar-LOHawtln/bin/activate
[1] 76221
.: no such file or directory: /Users/nathan/.local/share/virtualenvs/foo
[1]  + 76221 exit 127   . /Users/nathan/.local/share/virtualenvs/foo
zsh: command not found: bar-LOHawtln/bin/activate
```
