### ISSUE TITLE
[Feature request] Make pipenv NOT care what env i'm currently in.

### ISSUE THREAD

**Issue by pycampers** [pypa/pipenv#1549]
Usually, I use a separate virtualenv as a replacement for my global / system python, (anaconda using pyenv), for quick testing stuff and running python based utils (like `fuck`, `sass` and some other one's i've made for myself.)

This means that i'm always in a virtualenv by default. 

But this also means that if i try to use pipenv anywhere in my machine, i can't (untill i deactivate my 
"pyenv global venv")

To be specific, this is what i'm talking about

```
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
```

**Comment by kennethreitz** [comment]
use the path to the binary directly

**Comment by pycampers** [comment]
UPDATE

That happened because i was using a pyenv virtualenv

When i used 3.6.4 as the global, everything works as advertised!

**Comment by uranusjr** [comment]
May I ask the reason what you’re using the pyenv virtualenv for?

**Comment by pycampers** [comment]
It was leftover as a result of transition from pyenv to pipenv.

The virtualenv was for anaconda, which I used to use as my global python
(Pyenv creates a virtualenv for it).

Anaconda was great for quick tests and small scripts since it already
included the common packages used by the community.

Unfortunately, pipenv doesn't do anaconda
https://github.com/pypa/pipenv/issues/1635
