### ISSUE TITLE
Failure to parse ipywidgets extras_require

### ISSUE THREAD

**Issue by intrinseca** [pypa/pipenv#1552]
It seems that pipenv is getting confused by the requirements in ipywidgets (https://github.com/jupyter-widgets/ipywidgets/blob/master/setup.py).

```
extras_require = setuptools_args['extras_require'] = {
    ':python_version<"3.3"' : ['ipython>=4.0.0,<6.0.0'],
    ':python_version>="3.3"': ['ipython>=4.0.0'],
    'test:python_version=="2.7"': ['mock'],
    'test': ['nose'],
}
```

It declares a conflict between IPython > 6.0.0 and ipywidgets even though my environment is Python 3.6.

##### Describe your environment

1. OS Type: Windows Server 2012 (though I expect I could reproduce on Windows 10 x64)
1. Python version: Python 3.6.4
1. Pipenv version: version 11.0.2

##### Expected result

pipenv allows IPython > 6.0.0 to be installed as Python is >= 3.3.

##### Actual result

Incidentally, I had to add `print(c.out)` to `utils.venv_resolve_deps` to get it to print the output from the venv rather than just eating it, so I could work out which packages were going wrong. 

```
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches ipython<6.0.0,>6.0.0,>=4.0.0
Tried: 0.10, 0.10.1, 0.10.1, 0.10.2, 0.10.2, 0.11, 0.11, 0.12, 0.12, 0.12.1, 0.12.1, 0.13, 0.13, 0.13.1, 0.13.1, 0.13.2,
 0.13.2, 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.2.1, 1.2.1, 2.0.0, 2.0.0, 2.0.0, 2.1.0, 2.1.0, 2.1.0, 2.2.0, 2.2.0,
 2.2.0, 2.3.0, 2.3.0, 2.3.0, 2.3.1, 2.3.1, 2.3.1, 2.4.0, 2.4.0, 2.4.0, 2.4.1, 2.4.1, 2.4.1, 3.0.0, 3.0.0, 3.0.0, 3.1.0,
3.1.0, 3.1.0, 3.2.0, 3.2.0, 3.2.0, 3.2.1, 3.2.1, 3.2.1, 3.2.2, 3.2.2, 3.2.2, 3.2.3, 3.2.3, 3.2.3, 4.0.0b1, 4.0.0b1, 4.0.
0b1, 4.0.0, 4.0.0, 4.0.0, 4.0.1, 4.0.1, 4.0.1, 4.0.2, 4.0.2, 4.0.2, 4.0.3, 4.0.3, 4.0.3, 4.1.0rc1, 4.1.0rc1, 4.1.0rc1, 4
.1.0rc2, 4.1.0rc2, 4.1.0rc2, 4.1.0, 4.1.0, 4.1.0, 4.1.1, 4.1.1, 4.1.1, 4.1.2, 4.1.2, 4.1.2, 4.2.0, 4.2.0, 4.2.0, 4.2.1,
4.2.1, 4.2.1, 5.0.0b1, 5.0.0b1, 5.0.0b1, 5.0.0b2, 5.0.0b2, 5.0.0b2, 5.0.0b3, 5.0.0b3, 5.0.0b3, 5.0.0b4, 5.0.0b4, 5.0.0b4
, 5.0.0rc1, 5.0.0rc1, 5.0.0rc1, 5.0.0, 5.0.0, 5.0.0, 5.1.0, 5.1.0, 5.1.0, 5.2.0, 5.2.0, 5.2.1, 5.2.1, 5.2.2, 5.2.2, 5.3.
0, 5.3.0, 5.4.0, 5.4.0, 5.4.1, 5.4.1, 5.5.0, 5.5.0, 6.0.0rc1, 6.0.0rc1, 6.0.0, 6.0.0, 6.1.0, 6.1.0, 6.2.0, 6.2.0, 6.2.1,
 6.2.1
```

##### Steps to replicate

In a clean directory:

```
pipenv install ipywidgets IPython>6.0.0
pipenv lock
```

**Comment by david-gang** [comment]
I think this is connected to the following comment: https://github.com/pypa/pipenv/issues/1547#issuecomment-370515641
The suspected problem is that the markers are  not evaluated in all cases, therefore it takes both of them

**Comment by intrinseca** [comment]
I went digging a bit more - the markers are maintained until the requirements are grouped together here:

https://github.com/pypa/pipenv/blob/31c8f0d89600216043308bb8d344f52b38224a36/pipenv/patched/piptools/resolver.py#L204

_group_constraints:
https://github.com/pypa/pipenv/blob/31c8f0d89600216043308bb8d344f52b38224a36/pipenv/patched/piptools/resolver.py#L155-L161

I think the comment about losing information has come true! Does your fix in #1547 cause non-matching markers to be dropped at that early stage, such that they don't make it to be dropped (incorrectly) when grouped?

**Comment by david-gang** [comment]
Hi @intrinseca,
It works like a charm.
I had to use the command:
> python  pipenv/resolver.py google-cloud-datastore --verbose

When i ran the command 
> pipenv install google-cloud-datastore

it ran the python from the virtualenv instead of the local github code.

What i need to do now is to add an unit test but i can't figure how to do this. I see that there is a big pypi folders with subfolders tar.gz files. Do you know how an unit test of this would look like? But essentially this is a possible solution

**Comment by david-gang** [comment]
Hi @intrinseca ,
Update: I fixed it in a more upstream place:
https://github.com/pypa/pipenv/pull/1564
You could just fetch my pr and see if this fixes your problem

**Comment by techalchemy** [comment]
@david-gang thanks for submitting those! @kennethreitz just set up our local copy of pypi for testing purposes and is probably most qualified to answer this question

**Comment by kennethreitz** [comment]
Can you provide your pipfile?

**Comment by intrinseca** [comment]
It's just the default that gets created by `pipenv install ipywidgets IPython>6.0.0`

```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

ipywidgets = "*"
ipython = ">6.0.0"


[dev-packages]



[requires]

python_version = "3.6"

```

**Comment by david-gang** [comment]
I think it is the same issue as #1547 . It is the same platform specific dictionary form which isn't supported.
