### ISSUE TITLE
Unable to resolve .dev package versions since updating to 11.0.2

### ISSUE THREAD

**Issue by seslattery** [pypa/pipenv#1560]
##### Describe your environment

1. Docker container: FROM python:2.7-slim-stretch (Debian Linux)
1. Python version: 2.7.14
1. Pipenv version: 11.0.2 (10.1.2)

##### Expected result

The Pipfile line in this case is:
internal-package-name = "*"
I had a working Pipfile and Pipfile.lock on 10.1.2, with an internal pypi to grab a package with the following possible versions available: "1.0.0.dev1, 1.0.0.dev1, 1.0.0.dev2, 1.0.0.dev2, 1.0.0.dev3, 1.0.0.dev3, 1.0.0.dev4, 1.0.0.dev4, 1.0.0.dev5, 1.0.0.dev5, 1.0.0.dev6, 1.0.0.dev6" . 

On 10.1.2 this installs just fine, and everything worked as expected.

##### Actual result

When I updated to 11.0.2 today, I received the following error when trying various combinations of installs:

Pipfile.lock (370d05) out of date, updating to (5a3b50)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches internal-package-name
Tried: 1.0.0.dev1, 1.0.0.dev1, 1.0.0.dev2, 1.0.0.dev2, 1.0.0.dev3, 1.0.0.dev3, 1.0.0.dev4, 1.0.0.dev4, 1.0.0.dev5, 1.0.0.dev5, 1.0.0.dev6, 1.0.0.dev6

##### Steps to replicate

Not sure how to replicate because it's an internal pypi server, but I can make a simple Dockerfile and Pipfile if I can find another project with .dev only versions.  Let me know what other information I can provide to help.

**Comment by dhensen** [comment]
I have a similar issue:

```
$ pipenv install web3
Installing web3…
...
...
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches eth-keys<0.2.0,>=0.1.0b3
Tried: 0.1.0b1, 0.1.0b1, 0.1.0b2, 0.1.0b2, 0.1.0b3, 0.1.0b3, 0.1.0b4, 0.1.0b4, 0.2.0b1, 0.2.0b1, 0.2.0b2, 0.2.0b2, 0.2.0b3, 0.2.0b3
```

I think `0.1.0b4` should be the next version that matches the constraints. I have not checked the pipenv sources to see how these versions are parsed and I don't know the version schemes well enough to know if `0.1.0b3` is a valid format for which an ordering has been determined.

**Comment by dhensen** [comment]
Oh I see there are more issues like this which involve private registries. We too are using a private registry.

**Comment by techalchemy** [comment]
You need to have `allow_prereleases` in your pipfile, so in a section called `[pipenv]` like this:

```ini
[pipenv]

allow_prereleases = true
```

**Comment by seslattery** [comment]
Thank you! That seems to have resolved it.  I didn't see that in documentation anywhere, should I open a doco issue for it?  and if so, where's the right place to do that?
