### ISSUE TITLE
No module named 'Queue'

### ISSUE THREAD

**Issue by DanMcInerney** [pypa/pipenv#1571]
pipenv install --three leads to an error: 

root@kali:/home# pipenv install
Locking [dev-packages] dependencies���
python2.7/dist-packages/pipenv/resolver.py", line 11, in <module>
    import pipenv.utils
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/__init__.py", line 17, in <module>
    from .cli import cli
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/cli.py", line 10, in <module>
    import delegator
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/delegator.py", line 8, in <module>
    from pexpect.popen_spawn import PopenSpawn
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pexpect/popen_spawn.py", line 14, in <module>
    from Queue import Queue, Empty  # Python 2
ModuleNotFoundError: No module named 'Queue'

What's odd is if I open the python2 interpreter then that import statement is fine. The python3 import statement in that file is also fine in the python3 interpreter. Additionally, using the python3 interpreter from the created virtualenv also doesn't have a problem importing Queue, Empty from queue.

pipenv install --two works fine but this is a Python3 script.

##### Describe your environment

1. Kali Rolling
1. Python version: 2.7.14+
1. Pipenv version: 11.0.2

##### Expected result

I expect pipenv install to install all the libraries in the Pipfile.

##### Actual result

Pipenv errors out on seemingly all its commands like pipenv install and pipenv clean.

##### Steps to replicate

Run pipenv install.

Pipefile:

[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true

[packages]

netaddr = "*"
pexpect = "*"
asyncio = "*"
python-libnmap = "*"
netifaces = "*"
requests = "*"
termcolor = "*"
libtmux = "*"

**Comment by DanMcInerney** [comment]
Even weirder, if I pipenv install --two it works. If I then pipenv install --three and agree to delete the old virtualenv via pipenv prompt, it works. Wtf.

**Comment by DanMcInerney** [comment]
Any idea why this would occur?

**Comment by lancelote** [comment]
Had the same error, `pipenv` was installed with `pip install --user pipenv` with system Python 2 and called under Python 3 virtual environment. Reinstalling with `pip3` fixed the problem for me.

**Comment by DanMcInerney** [comment]
I get this error when I delete the icebreaker folder and reclone it.
Pavel's probably right about it being messed up pip and/or virtualenv
installs but I notice it goes away if you do pipenv install --two then do
pipenv install --three.

>
