### ISSUE TITLE
First character in terminal output is displaced sometimes

### ISSUE THREAD

**Issue by anlutro** [pypa/pipenv#1577]
I'm on Debian Stretch, using `rxvt-unicode` as my terminal.

In certain situations, the first character of a line gets displaced - it ends up at the far right of my terminal, on the previous line. Look at the right edge of this screenshot:

![2018-03-07-110130_958x1059_scrot](https://user-images.githubusercontent.com/163093/37086080-fb7793e2-21f6-11e8-87c5-b036bc398414.png)

**Comment by kennethreitz** [comment]
we're aware

**Comment by kojiromike** [comment]
Ref #1574 so people searching for that issue can find this one.
