### ISSUE TITLE
Fail on branching

### ISSUE THREAD

**Issue by junquera** [pypa/pipenv#1581]
##### Describe your environment

A git repository in any system.

##### Expected result

Updating project dependencies in different branches should result in a functional file when merging.

##### Actual result

When I change dependencies in different git branches, It fails when merging due to the signature of the file.

There could be a third file as backup of all the dependencies and use it to *restore* the project after merge.

##### Steps to replicate

In a commit with pipenv, branch it, change a dependency in one of the branches and merge.

**Comment by kennethreitz** [comment]
there's already an issue open for this

**Comment by joshfriend** [comment]
@junquera I think he's talking about #1389, but cant say for sure since no link was provided
