### ISSUE TITLE
Feature Request:  Exit from virtualenv shell after removing virtualenv (when virtualenv is active)

### ISSUE THREAD

**Issue by DanAtShenTech** [pypa/pipenv#1594]
After executing `pipenv --rm` from within an activated virtualenv, the prompt still shows as (virtualenv).......  Seems like the final step should be to exit from the virtualenv and bring the user back to a regular prompt since the virtualenv has now been deleted.

**Comment by kennethreitz** [comment]
nothing we can do about that
