### ISSUE TITLE
ImportError: cannot import name '_psutil_windows'

### ISSUE THREAD

**Issue by sdementen** [pypa/pipenv#1600]
Issue on windows on 11.1.3 via appveyor (see logs on
https://ci.appveyor.com/project/sdementen/piecash/build/1.0.372/job/uogfacdy8m9y902x#L151)

**Comment by kennethreitz** [comment]
#1587. Please check existing issues before opening new ones.

**Comment by techalchemy** [comment]
Fixed & released
