### ISSUE TITLE
pipenv shell failing due to SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by arcan25** [pypa/pipenv#1601]
When trying to run pipenv shell it fail to do so with error message below:
pipenv shell --verbose
  File "<string>", line 1
    c:\python27\python.exe -c "from pew.pew import prevent_path_errors; prevent_path_errors()"
     ^
SyntaxError: invalid syntax

##### Environment

1. Windows 7
2. Python 2.7.14
3. pipenv, version 11.1.4

##### Steps to replicate

just try to run pipenv shell.

**Comment by kennethreitz** [comment]
uh

**Comment by kennethreitz** [comment]
can you send a screenshot?

**Comment by arcan25** [comment]
Here you go
![image](https://user-images.githubusercontent.com/33428164/37153801-e5b5eec2-22ab-11e8-964e-85eaaf593aa6.png)

**Comment by kennethreitz** [comment]
reproduced, but with a different error

**Comment by kennethreitz** [comment]
@techalchemy's on it.

**Comment by techalchemy** [comment]
@arcan25 fix is available, you can `pip install -e git+https://github.com/pypa/pipenv.git@bugfix/pew-shells-windows#egg=pipenv` and try it out

**Comment by purEnergy** [comment]
I tried using the command that @arcan25 provided, but I get a fatal error.

Obtaining pipenv from git+https://github.com/pypa/pipenv.git@bugfix/pew-shells-windows#egg=pipenv
  Updating c:\users\v-maeile\documents\src\onebmctest\onebmctest\src\pipenv clone (to bugfix/pew-shells-windows)
  Could not find a tag or branch 'bugfix/pew-shells-windows', assuming commit.
fatal: ambiguous argument 'bugfix/pew-shells-windows': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Command "git reset --hard -q bugfix/pew-shells-windows" failed with error code 128 in C:\Users\v-maeile\Documents\src\On
eBMCTest\OneBMCTest\src\pipenv
