### ISSUE TITLE
Feature Request: Add custom groups

### ISSUE THREAD

**Issue by 7wonders** [pypa/pipenv#1612]
I see that today the different install groups default and develop are hardcoded. Is there a plan to have custom groups? For example, the very common pipeline dev, stage, production could be handled nicely:

```
[packages]
# default packages here
[dev-packages]
# dev packages here
[stage-packages]
# stage packages here
[production-packages]
# production packages here
[somethingelse-packages]
# something else packages here
```

**Comment by kennethreitz** [comment]
nope.

**Comment by 7wonders** [comment]
Would it be a welcome addition or is it a plain old nope?

**Comment by uranusjr** [comment]
This has been raised several times. Not going to happen

**Comment by kennethreitz** [comment]
the spec leaves room for this intentionally, and it is also intentionally not supported :)
