### ISSUE TITLE
pipenv shell creates new virtualenv

### ISSUE THREAD

**Issue by hobbsd** [pypa/pipenv#1613]
I forgot to cd to my project dir before running `pipenv shell`, and it created a new virtualenv.

##### Describe your environment

Windows 10
Python 3.6.4
Pipenv version: 11.1.5

##### Expected result

I would expect `pipenv shell` to fail when there is no virtualenv to start a shell for. I didn't see anything in the docs about the shell command creating a virtualenv and Pipfile.

##### Actual result

A virtualenv was created and then a Pipfile and then pipenv crashed with a SyntaxError (but I see there's already an issue for that).

##### Steps to replicate

Run `pipenv shell` in a directory with no Pipfile.

**Comment by techalchemy** [comment]
I _think_ we might have decided this was intended, but I can't quite remember. If you can confirm whether this happened in 9.0.1 or earlier it would be helpful

**Comment by hobbsd** [comment]
I just tried 9.0.1, and it also created a new virtualenv.

**Comment by kennethreitz** [comment]
this is intended behavior

**Comment by microbit-carlos** [comment]
Could there be an option/flag to not create the virtualenv and exit with an error code?

**Comment by uranusjr** [comment]
I feel a PEEP proposing an environment variable disabling auto virtual environment creation *in general* (on just for `shell`) could be appropriate.
