### ISSUE TITLE
Support `py` as an acceptable Python intpreter

### ISSUE THREAD

**Issue by brettcannon** [pypa/pipenv#1620]
On Windows, Python is not put on `PATH` by default. Instead the `py` command is made available which operates somewhat like `pipenv --three` where a single command handles executing different Python versions. It would be great if pipenv picked up on `py` -- or Python versions installed by reading the Windows registry -- instead of only looking for `python` on `PATH`.

**Comment by kennethreitz** [comment]
Someone had a working proposal in progress for this at some point, but it got lost in the shuffle. 

the tl;dr is basically — it heavily complicates our codebase, and ideally the "proper" way to install Pythons currently is to add them to your PATH. 

That's the answer we're going with *for now*. If you're open to contributing elegant PEP 397 support to our codebase in a way that doesn't totally overhaul what we're already doing, I'm open to it.

**Comment by brettcannon** [comment]
And I totally understand and I realize that Windows is totally bucking the trend compared to UNIX and thus proper support is a cost that has to be weighed.

Looping in @zooba in case he has interest in this. I also wonder if this would be easier if `py` had a `--path` or something to emit the path to the interpreter so that something equivalent in PowerShell to ```py -3 -m pipenv --version `py -3 --path` ``` would work.

**Comment by kennethreitz** [comment]
that'd be wonderful.

**Comment by techalchemy** [comment]
@uranusjr and @ncoghlan were working on this as far as I knew, one of them will remember which PR we had

**Comment by uranusjr** [comment]
#1150 and #1259. My approach is not really using py.exe, but reimplements the whole PEP 514 logic, which is probably too radical.

Re-thinking this right now it is probably doable with just one more subprocess call in Pipenv. Instead of using the executable’s path directly, we can do something like this ([in `ensure_python`](https://github.com/pypa/pipenv/blob/2dc06d4/pipenv/core.py#L550):

```python
path_to_python = …
path_to_python = subprocess.check_output([path_to_python, '-c', 'import sys; print(sys.executable)']).strip()
return path_to_python
```

to make sure we’re getting the path of the real executable (`python.exe`) instead of the shim (`py.exe`).

**Comment by zooba** [comment]
As the PEP 514 author, I don't think it's too radical :)

See https://github.com/zooba/pep514tools if you want code that is free-as-in-MIT which you are welcome to simply take and vendor/reuse. I'm not really maintaining it, but only because nobody is using it and asking for changes.

**Comment by techalchemy** [comment]
@zooba those seem kinda nice :+1: I am not sure if we can trust the source though, we should really just reinvent the wheel (or .whl maybe? lame puns anyone?)

**Comment by uranusjr** [comment]
The PEP 514 logic is really straightforward and difficult to get wrong, after all. Really good job designing it 😃 Incorporating it into Pipenv would require some structural change (the current implementation assumes the executable is somewhere in PATH), which is what I meant by radical.
