### ISSUE TITLE
pipenv shell under windows throws SyntaxError: unexpected character after line continuation character

### ISSUE THREAD

**Issue by infogeek** [pypa/pipenv#1630]
I installed pipenv on windows and did a pipenv install which worked but pipenv shell throws this error E:\temp\temp>pipenv shell
  File "<string>", line 1
    c:\users\infogeek\appdata\local\programs\python\python36\python.exe -c "from pew.pew import prevent_path_errors; prevent_path_errors()"
                                                                                                                                       ^
SyntaxError: unexpected character after line continuation character

Windows 10
Python 3.6.3
pipenv 11.1.5

**Comment by kennethreitz** [comment]
try 11.1.6 :)

**Comment by infogeek** [comment]
Cheers! btw up key doesn't work in CMD under pipenv shell but i think you know about it already.

**Comment by kennethreitz** [comment]
correct, thanks for the report!
