### ISSUE TITLE
pip==9.0.1 fails to correctly install pipenv==11.1.6, but works with pipenv==11.1.5

### ISSUE THREAD

**Issue by zyv** [pypa/pipenv#1631]
The latest release of pipenv (11.1.6) somehow cannot be installed correctly by pip on the official python:3.6 Docker image, because it doesn't pull in virtualenv as a dependency, even though it still seems to be present in `setup.py`.

##### Describe your environment

1. OS Type

Official Python 3.6 Docker image from Docker Hub:

```
$ docker run -it --rm python:3.6 /bin/bash

root@655cf1e07441:/# pip --version
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)
```
1. Python version: `$ python -V`
```
root@655cf1e07441:/# python -V
Python 3.6.4
```
1. Pipenv version: `$ pipenv --version`
N/A
##### Expected result

`virtualenv` dependency is installed.

##### Actual result

`virtualenv` dependency is **not** installed.

##### Steps to replicate

```
$ docker run -it --rm python:3.6 /bin/bash

root@655cf1e07441:/# pip install pipenv==11.1.6
Collecting pipenv
  Downloading pipenv-11.1.6.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 514kB/s 
Requirement already satisfied: setuptools>=36.2.1virtualenv in /usr/local/lib/python3.6/site-packages (from pipenv)
Collecting virtualenv-clone>=0.2.5 (from pipenv)
  Downloading virtualenv_clone-0.3.0-py2.py3-none-any.whl
Building wheels for collected packages: pipenv
  Running setup.py bdist_wheel for pipenv ... done
  Stored in directory: /root/.cache/pip/wheels/ee/bb/e2/3c8a67b115b7fe036ffa6ba776b5bcc692c35fa958a6d8507c
Successfully built pipenv
Installing collected packages: virtualenv-clone, pipenv
Successfully installed pipenv-11.1.6 virtualenv-clone-0.3.0

root@655cf1e07441:/# virtualenv
bash: virtualenv: command not found
```

```
root@655cf1e07441:/# pip install pipenv==11.1.5
Collecting pipenv==11.1.5
  Downloading pipenv-11.1.5.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 464kB/s 
Collecting virtualenv (from pipenv==11.1.5)
  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 1.1MB/s 
Requirement already satisfied: virtualenv-clone>=0.2.5 in /usr/local/lib/python3.6/site-packages (from pipenv==11.1.5)
Building wheels for collected packages: pipenv
  Running setup.py bdist_wheel for pipenv ... done
  Stored in directory: /root/.cache/pip/wheels/0a/c4/18/93d03dc61aa0e86ad82a01ab6e082e9a30db943c58fac80ef7
Successfully built pipenv
Installing collected packages: virtualenv, pipenv
  Found existing installation: pipenv 11.1.6
    Uninstalling pipenv-11.1.6:
      Successfully uninstalled pipenv-11.1.6
Successfully installed pipenv-11.1.5 virtualenv-15.1.0

root@655cf1e07441:/# virtualenv
You must provide a DEST_DIR
Usage: virtualenv [OPTIONS] DEST_DIR
```

**Comment by kennethreitz** [comment]
oh man, the bug behind this is hilarious.

11.1.7 released, which fixes this. very sorry for the inconvenience.

**Comment by kennethreitz** [comment]
https://github.com/pypa/pipenv/commit/ea4b5893e48ec41de933fe73aba9f04b1a44593b

**Comment by kennethreitz** [comment]
our ci doesn't use a clean venv for each build (to speed things up), so it didn't catch this

**Comment by zyv** [comment]
Thank you very much for working on pipenv in general and quick reaction to this issue in particular! However, I hope you would consider extending CI / test coverage to make pipenv releases more robust. 

Pipenv has quickly become an indispensable tool in our workflow, and it's great to see that it's being developed at a high pace and released often, but this particular breakage has cost us about 3 person-hours, and we were certainly not the only ones to see all of our CI builds go red. The sudden disappearance of `update` command and its subsequent comeback last week has also cost us many hours of confusion. I really wish for a smoother experience with such an important part of Python infrastructure...

**Comment by kennethreitz** [comment]
yew — we will do what we can :)

gotta learn lessons the hard way, unfortunately.

**Comment by kennethreitz** [comment]
p.s. you should pin versions if you're depending on us in infrastructure — this is why version numbers exist!

**Comment by zyv** [comment]
@kennethreitz thank you, I appreciate your advice regarding pinning, however, is there any official guideline as to which version should I rely upon?

We use Heroku to deploy our Django apps (surprise, surprise!) and we need to be using the same version as Heroku uses. So far I understood that Heroku is always using the latest one. This is why I unpinned `pipenv`, because I had problems debugging weird differences between our local Docker infra and Heroku production infra all the time :(

**Comment by kennethreitz** [comment]
Heroku is now pinning pipenv. It is currently on v11.7.2.

**Comment by zyv** [comment]
Awesome, thank you! Could you please tell if there if some way to get notified when the version changes? Or all I can do is to stick `pipenv --version` in release script and change the logs regularly?

**Comment by kennethreitz** [comment]
check the buildpack changelog, or that :)
