### ISSUE TITLE
pipenv install that worked on 9.0.3 fails on 11.1.5

### ISSUE THREAD

**Issue by jmcs** [pypa/pipenv#1632]
I use pipenv install as part of a CI pipeline. When I updated pipenv version used in the pipeline pipenv install stopped working.

##### Describe your environment

1. OS Type: Linux
1. Python version: `$ python -V`: 3.6.4
1. Pipenv version: `$ pipenv --version` 11.1.5

##### Expected result

Updating pipenv shouldn't make installation stop working. 

##### Actual result

pipenv doesn't install all the dependencies because they have wrong python_requires, for example:

```Ignoring pluggy: markers 'python_version == ">=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*"' don't match your environment```

Please note that despite the version in python_requires all this packages were working before.

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

Pipfile:

```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

uwsgi = "*"
connexion = "*"
stups-tokens = "*"
requests = "*"
"dogpile.cache" = "*"
ecological = "*"


[dev-packages]

httpie = "*"
httpie-zign = "*"
stups-pierone = "*"
pylint = "*"
mypy = "*"
sphinx = "*"
sphinx-rtd-theme = "*"
pytest = "*"
pytest-cov = "*"


[requires]

python_version = "3.6"
```

Command: ``pipenv install --dev --deploy``

**Comment by kennethreitz** [comment]
this is a feature, not a bug.

**Comment by fahdk** [comment]
It seems as though `python_version == ">=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*"` shoud work with Python 3.6. I am having the same issue with djangorestframework. Why is this a feature? Is the `python_version` value incorrect? I read it as "compatible with Python 2.7 and up but not compatible with Python 3.0, 3.1, 3.2 and 3.3".

**Comment by semitable** [comment]
I am having the same issue with djangorestframework. It says: Ignoring djangorestframework: markers 'python_version == ">=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*"' don't match your environment.
Nevertheless, I am certainly using python 3.6
Also  ">=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*" means that 3.4, 3.5, 3.6 ARE supported so that is not the issue!
