### ISSUE TITLE
Failed Install for version 11.1.6

### ISSUE THREAD

**Issue by epicserve** [pypa/pipenv#1633]
During a deployment, pipenv didn't install. The following is the output with information that isn't relevant redacted:

```
Updating requirements...
[■■■■■■■■■■■■■■■■] run: /usr/local/virtualenvs/■■■■■/bin/pip install pipenv
[■■■■■■■■■■■■■■■■] out: Collecting pipenv
[■■■■■■■■■■■■■■■■] out:   Using cached pipenv-11.1.6.tar.gz
[■■■■■■■■■■■■■■■■] out:     Complete output from command python setup.py egg_info:
[■■■■■■■■■■■■■■■■] out:     error in pipenv setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
[■■■■■■■■■■■■■■■■] out:
[■■■■■■■■■■■■■■■■] out:     ----------------------------------------
[■■■■■■■■■■■■■■■■] out: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-glgvssan/pipenv/
[■■■■■■■■■■■■■■■■] out:

Fatal error: run() received nonzero return code 1 while executing!

Requested: /usr/local/virtualenvs/■■■■■/bin/pip install pipenv
Executed: /bin/bash -l -c "cd /srv/sites/■■■■■/pears >/dev/null && /usr/local/virtualenvs/■■■■■/bin/pip install pipenv"
```

##### Describe your environment

OS: Ubuntu 16.04.3 LTS
Python version: 3.5.2
Pipenv version: 11.1.4

##### Expected result

I expected pipenv to install without an error.

##### Actual result

Pipenv didn't install.

##### Steps to replicate

I'm guessing you could replicate it by running `pip install pipenv` in a python virtualenv on a similar environment.

**Comment by kennethreitz** [comment]
11.1.7 is released, which should fix this.

**Comment by epicserve** [comment]
@kennethreitz,

I verified that it worked. Thank you sir!

![giphy](https://user-images.githubusercontent.com/191620/37210453-5bfaad9e-236e-11e8-8dfc-09a6bcab7f88.gif)

**Comment by techalchemy** [comment]
Definitely not my fault guys. I didn’t do it.

**Comment by epicserve** [comment]
@techalchemy,

Hehe. You shouldn't have said anything. I would have never known. :)
