### ISSUE TITLE
Pipenv does not find pipfile in upper directory

### ISSUE THREAD

**Issue by mattvend** [pypa/pipenv#1634]
Pipenv virtualenv created for a project, at the top of my project are a pipfile and pipfile.lock files.
When executing pipenv commands in sub directory (3 levels below), a new virtual env gets created.

I thought it would not be the case and pipenv would use the one at the top

##### Describe your environment

1. OS Type: Windows 10
1. Python version: `$ python -V` Python 3.6.1 :: Anaconda 4.4.0 (64-bit)
1. Pipenv version: `$ pipenv --version` pipenv, version 11.1.6

##### Expected result

I expect no new environment to be created

##### Actual result

Passing the option --verbose to pipenv does not work

##### Steps to replicate

- created a virtualenv with pipenv, and a pipfile
- create some subdirs
- in the subdir, execute pipenv --shell
It creates a new env instead of using the one at the top.
Please note that sometimes it works, sometimes not.

Top Pipfile
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]

"pyqt5" = "*"
pyedflib = "*"
psutil = "*"

[dev-packages]

[requires]

python_version = "3.6"

**Comment by kennethreitz** [comment]
We only check 3 levels above. This is configurable by setting the `PIPENV_MAX_DEPTH` environment varialbe.

**Comment by mattvend** [comment]
How can I pass it to pipenv then ?

**Comment by mattvend** [comment]
Ok, I defined the variable ang finally got pipenv finding the venv.

Nevertheless, while in my sub dir, while typing pipenv shell, the shell started correctly but 3 level above, next to the venv, not in the current directory. It is a bit annoying.

I cd back to my script, then tried to run it. The script complained about not being able to import packages as absolute import. It looks like something is not functioning correctly regarding absolute and relative paths in this situation.

**Comment by techalchemy** [comment]
`set PIPENV_MAX_DEPTH=5` or whatever.

**Comment by techalchemy** [comment]
Pipenv will always drop you at your project root when you launch a subshell. As for absolute imports, you’ll want to consult the python docs on why you’re getting that error

**Comment by mattvend** [comment]
Thanks ! I already figured out the env variable.

Out of curiosity, PIPENV_MAX_DEPTH=2 or 3 by default, why such a low number by default ? what is the reasoning ? 

Nevertheless, I would prefer that pipenv, by design, while in a shell and typing pipenv shell leaves you at your current location.

For the wrong absolute imports, this is probably something else.

**Comment by kennethreitz** [comment]
you're the first person who's raised any concern over the default so far, so i think we've picked a good sane default :)

**Comment by kennethreitz** [comment]
I'll see about adding an env var to not chdir when invoking shell

**Comment by rrthomas** [comment]
That would be good; I've just run into this. It's nice to be able to use `pipenv run` without `pipenv run sh -c "cd foo && actual-cmd"`

**Comment by keysmusician** [comment]
> you're the first person who's raised any concern over the default so far, so i think we've picked a good sane default :)

Perhaps my experience is another outlier, but I thought creating a subshell was default behavior for about 6 months now because using the project root environment almost never worked for me (though I do seem to recall from documentation that it was supposed to). I find the default max depth surprising and incredibly annoying, but didn't realize I could do anything about it.
