### ISSUE TITLE
pipenv install for requirement.txt is failing

### ISSUE THREAD

**Issue by arcan25** [pypa/pipenv#1638]
Issue:
running pipenv install in directory where requirement.txt file already exist is failing.

##### Environment

1. Windows 7
2. Python version: 2.7.14
1. Pipenv version: 11.1.7

##### Expected result

should have install all the packages
##### Actual result

C:\My\TE\flask example\flask-bookshelf>pipenv install
requirements.txt found, instead of Pipfile! Converting.
Warning: Your Pipfile now contains pinned versions, if your requirements.txt did.
We recommend updating your Pipfile to specify the "*" version, instead.
Pipfile.lock not found, creating.
Locking [dev-packages] dependencies.
Locking [packages] dependencies.

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches Flask==0.10.1,>=0.10,>=0.11,>=0.9

Tried: 0.1, 0.2, 0.3, 0.3.1, 0.4, 0.5, 0.5.1, 0.5.2, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.9, 0.10, 0.10.1, 0.11, 0.11, 0.11.1, 0.11.1, 0.12, 0.12, 0.12.1, 0.12.1, 0.12.2, 0.12.2

c:\python27\lib\site-packages\pipenv\utils.py:1152: ResourceWarning: Implicitly cleaning up <TemporaryDirectory 'c:\\users\\xxxxxx\\appdata\\local\\tem
p\\pipenv-xaecsz-requirements'>
  warnings.warn(warn_message, ResourceWarning)

C:\My\TE\flask example\flask-bookshelf>

##### Steps to replicate

try to run pipenv install

[requirements.txt](https://github.com/pypa/pipenv/files/1797763/requirements.txt)
[Pipfile.txt](https://github.com/pypa/pipenv/files/1797767/Pipfile.txt)

ps: pipfile temporary converted to txt file.

**Comment by kennethreitz** [comment]
try again with v11.1.8 please :)

**Comment by arcan25** [comment]
hi, did try but same result,

What i did:
removed whole project directory to have fresh start, removed .virtualenvs folder from appdata of user.

still the same result as above with version 11.1.8

**Comment by kennethreitz** [comment]
"Flask==0.10.1,>=0.10,>=0.11,>=0.9"

one of your dependencies says it needs flask > 0.11, so this is an un-resolvable dependency graph

**Comment by kennethreitz** [comment]
pip doesn't have this problem because it doesn't resolve a dependency graph — it's just first come first serve

**Comment by arcan25** [comment]
Ohh, i see. I did try with pip and it worked so didn’t thought about pip. But pipenv is outsmart that thing which is great! apologies for wasting your time.

Just a feture request: is it possible to have some message showing conflicts of requirements.

**Comment by kennethreitz** [comment]
Easier said than done :)

**Comment by techalchemy** [comment]
@arcan25 the best bet for that is to run `pipenv install --skip-lock` and then `pipenv graph` to investigate
