### ISSUE TITLE
An alternative to keeping pipenv up-to-date with python versions manually

### ISSUE THREAD

**Issue by raiderrobert** [pypa/pipenv#1644]
On this line right here, there's a mapping dictionary: https://github.com/pypa/pipenv/blob/master/pipenv/core.py#L503

However, since it's using pyenv, maybe we should adopt an approach closer to this: https://github.com/concordusapps/pyenv-implict

**Comment by kennethreitz** [comment]
$ pipenv --rm
    $ pipenv install

not too hard :)

**Comment by kennethreitz** [comment]
oh i see what you're saying.

this isn't an issue for us right now. but, thanks for the suggestion!
