### ISSUE TITLE
~

### ISSUE THREAD

**Issue by ridwankazi** [pypa/pipenv#1647]
Be sure to check the existing issues (both open and closed!).

Describe the issue briefly here.

Please run `$ python -m pipenv.help`, and paste the results here.

If you're on MacOS, just run the following:

    $ python -m pipenv.help | pbcopy

------------

##### Expected result

Describe what you expected.

##### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

**Comment by techalchemy** [comment]
@ridwankazi you are suposed to paste the results. You also still have to describe the issue you encountered.
