### ISSUE TITLE
Surprising `pipenv install` behaviour regarding the lockfile

### ISSUE THREAD

**Issue by skorokithakis** [pypa/pipenv#1649]
I'm afraid I the `pipenv.help` command couldn't find pipenv, so I couldn't run it. I'm running v10.1.2, and I was very surprised to see that `pipenv install` does *not* use the lockfile by default! This led to a crash where my package could not be installed, as `pipenv install` on the end user's machine tried to upgrade the lockfile and broke. `pipenv install --ignore-pipfile` worked fine, but it was extremely surprising to me that this wasn't the default.

Basically, I consider `pipenv install` without any arguments to be a distribution-time command, ie it will be run when I want to distribute my package and install all the requirements. I would expect this to use the lockfile, if available.

I realize that `pipenv install <somepackage>` is a development-time command, breaking symmetry, but the way I imagined things working regarding the lockfile was that a command like `pipenv install <package>` would change both `Pipfile` and `Pipfile.lock`, a command like `pipenv lock` or `pipenv upgrade` would upgrade packages in the lockfile, and a command like `pipenv install` would use that lockfile to install packages.

I think many people will be bitten by the surprising default behavior of `pipenv install` to not only *not* use the lockfile, but to upgrade it as well, and the main problem is that nobody will realize what's happening until stuff blows up.

If you won't consider changing `pipenv install` to use the lockfile, maybe a separate command could be added.

I just now realized that `pipenv sync` is close to what I want, but it seems to be an alias for `pipenv install --keep-outdated`. Does that mean that *new* versions of the packages will be installed, but the lockfile won't be changed? That's what "Keep out–dated dependencies from being updated in Pipfile.lock." seems to imply, ie that it will install the new dependencies but won't touch the lockfile. Also, `pipenv sync` doesn't seem to use the Pipenv file if a lockfile does not exist.

To sum up, I am concerned that the commands are, at least, not documented well enough/a bit unclear. What is the recommended way, currently, of using the lockfile if it exists, or the Pipfile otherwise?

**Comment by skorokithakis** [comment]
Another problem of the `sync` command is that it doesn't work with `--system`, making it unsuitable for Dockerized deployments. Basically, the most useful thing is a command that would run `pipenv install --ignore-pipfile` if a lockfile exists, or `pipenv install` otherwise.

**Comment by kennethreitz** [comment]
... that’s what install does.

What makes you think otherwise?

**Comment by kennethreitz** [comment]
But only if the lockfile is up-to-date.

**Comment by kennethreitz** [comment]
Then, in that instance, it re-locks before installing... from the lockfile.

**Comment by skorokithakis** [comment]
That's kind of the problem, what do you mean "if it's up to date"? I don't want to lock my dependencies when developing, push that to dev, test and push to production, only to find that there's a new, incompatible version of some package, and the production server arbitrarily decided to install that one.

Basically, if there's a lockfile, and pipenv deletes it, creates a new one and then installs from that, there's basically no lockfile. What's the use of a lockfile if it's only used when it's not needed?

**Comment by kennethreitz** [comment]
You want install --deploy

**Comment by skorokithakis** [comment]
No, I don't want it to abort. Consider this scenario: I developed, tested, froze all my dependencies, etc. Now, a month later, when all the red tape has been cleared, I want to deploy what I tested, with all the dependencies I used when testing, etc to production. I don't want pipenv to upgrade anything, I don't want it to fail if there are new packages: I want it to install the *exact versions*, to the byte, of what's in the lockfile.

**Comment by kennethreitz** [comment]
A lockfile contains the hash of the pipfile that generated it. If the hashes don’t match, it’s invalid, and needs to be re-created as soon as possible.

**Comment by kennethreitz** [comment]
E.g. a lockfile is a cached result of a pipfile. They change together.

**Comment by skorokithakis** [comment]
Oh, is that what you mean by "out of date"? If so, I agree. I hadn't touched the Pipfile, though. Maybe I'm mistaken (and I don't have my scrollback buffer to paste any more), but what I saw happen was that `pipenv` updated my lockfile even though I hadn't touched the Pipfile.

For my clarification, is `pipenv install` ever supposed to change the lockfile based on the versions of the packages on PyPI? Or will it always use the lockfile if the Pipfile hash matches?

**Comment by kennethreitz** [comment]
A bare pipenv install will always use the pipfile.lock, if the hashes match.

**Comment by skorokithakis** [comment]
Ah, thanks. Then I'm either mistaken (most likely) or there's a pipenv bug. I'll close this issue and open another one with more information if I manage to reproduce my earlier experience. Sorry for the hassle and thanks for the clarification.

**Comment by kennethreitz** [comment]
Thanks for the due dilligence!
