### ISSUE TITLE
Pipenv is failing to install packages, due to an unexpected keyword argument 'absorb' in patched

### ISSUE THREAD

**Issue by LegoStormtroopr** [pypa/pipenv#1658]
##### Expected result

Pipenv 11.3.2 can install stuff.

##### Actual result

```
Locking [dev-packages] dependencies…
   has_changed, best_matches = self._resolve_one_round()
  File "/tmp/tox/dj1.11-test-linux-db-sqlite-search-elastic/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/tmp/tox/dj1.11-test-linux-db-sqlite-search-elastic/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 297, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/tmp/tox/dj1.11-test-linux-db-sqlite-search-elastic/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/repositories/pypi.py", line 171, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/tmp/tox/dj1.11-test-linux-db-sqlite-search-elastic/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/repositories/pypi.py", line 206, in get_legacy_dependencies
    result = reqset._prepare_file(self.finder, ireq, ignore_requires_python=True)
  File "/tmp/tox/dj1.11-test-linux-db-sqlite-search-elastic/lib/python3.6/site-packages/pipenv/../pipenv/patched/pip/req/req_set.py", line 699, in _prepare_file
    self.requires_python = check_dist_requires_python(dist, absorb=False)
TypeError: check_dist_requires_python() got an unexpected keyword argument 'absorb'
```

##### Install packages

```Django==2.0.3,django-haystack==2.8.0,django-haystack-elasticsearch==0.1.0,elasticsearch==5.5.2,pipenv==11.3.2,pytz==2018.3,urllib3==1.22,virtualenv==15.1.0,virtualenv-clone==0.3.0```

##### Steps to replicate

`pipenv install`

**Comment by logicx24** [comment]
Yup, I'm having the same issue. It's happening on every package I've tried.

**Comment by bryanhelmig** [comment]
Downgrading to 11.0.2 ala `pip3 install pipenv==11.0.2` worked for me. I just picked the release before the flurry of a dozen or more releases uploaded in the last few days and it worked.

**Comment by kennethreitz** [comment]
working on it actively — hoping to do a "stability" release as soon as possible (but not rushing it)

**Comment by techalchemy** [comment]
@kennethreitz we can publish a prerelease version of 11.3.3 by tagging it 11.3.3b1 or something

**Comment by kennethreitz** [comment]
anything's better than what we have now.

**Comment by sant527** [comment]
I also got the same issue. pipenv-11.3.2, Presently downgraded to 11.3.0

**Comment by techalchemy** [comment]
Installing from master should also work

**Comment by kennethreitz** [comment]
11.3.3 released. sorry again for the failure here

**Comment by LegoStormtroopr** [comment]
@kennethreitz Thanks again for being so responsive. I just want to say thanks for all of your work with in python community, `pipenv` is an amazing product. Its such an advancement on what was around before, and in such a short time that a few hiccups are bound to happen.

Thanks again for building this!

**Comment by benatkin** [comment]
if you're having trouble with this in 2019, upgrade pipenv to the latest version, and be sure to do it outside of a pipenv shell - I hit both this and https://github.com/pypa/pipenv/issues/2871 The three steps I needed to take:

1. `exit` to exit out of the pipenv shell I was in
2. `pip install pipenv -U` to upgrade pipenv
3. `pipenv shell` to start a new shell

Now `pipenv install` should run without errors!
