### ISSUE TITLE
pipenv update

### ISSUE THREAD

**Issue by hynek** [pypa/pipenv#1669]
So the good news is: `pipenv lock; pipenv sync` seems to work now. However…since the docs don’t really tell *what* `pipenv update` is supposed to do, but 11.5.0 changed it quite dramatically:

```
$ pipenv update --dev
Usage: pipenv update [OPTIONS] [MORE_PACKAGES]... PACKAGE

Error: Missing argument "package".
```

Wat? :)

It used to be:

```
pipenv update --clear
Running $ pipenv lock then $ pipenv sync.
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (ba2c3e)!
Installing dependencies from Pipfile.lock (ba2c3e)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 55/55 — 00:00:06
To activate this project's virtualenv, run the following:
 $ pipenv shell
All dependencies are now up-to-date!
```

It would be great if someone could document what those commands are supposed to do, at this point I’m just guessing. :|. One-liner is fine.

**Comment by kennethreitz** [comment]
gah!

**Comment by kennethreitz** [comment]
we haven't gotten around to writing integration tests for the new commands yet – it's on my short todo list.

**Comment by kennethreitz** [comment]
v11.5.1 released.

**Comment by hynek** [comment]
“Our CI consists of Travis, Jenkins, and Hynek.” 😂

**Comment by kennethreitz** [comment]
"eventual consistency"
