### ISSUE TITLE
Invalid marker error when installing on v11.4.0

### ISSUE THREAD

**Issue by ryanwilsonperkin** [pypa/pipenv#1670]
I believe this is an extension of https://github.com/pypa/pipenv/issues/1617
The last version that works produces the desired behaviour is `pipenv==11.1.3`.

I'm getting a `pip._vendor.packaging.markers.InvalidMarker` exception when running `pipenv install` and installing the `responses` package.

It is worth noting that the `responses` package includes the following [in their setup.py](https://github.com/getsentry/responses/blob/master/setup.py#L38-L41) and that this may be an improper packaging issue.
```python
extras_require = {
    ':python_version in "2.6, 2.7, 3.2"': ['mock'],
    'tests': tests_require,
}
```

Result of running `$ python -m pipenv.help`:
<details>
Pipenv version: `'11.4.0'`

Pipenv location: `'/usr/local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python2.7'`

Other Python installations in `PATH`:

  - `2.6`: `/usr/bin/python2.6`
  - `2.6`: `/usr/bin/python2.6`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`

  - `2.7.13`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.13`: `/usr/local/bin/python2`
  - `3.6.4`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '15.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 15.6.0: Mon Nov 13 21:58:35 PST 2017; root:xnu-3248.72.11~1/RELEASE_X86_64',
 'python_full_version': '2.7.13',
 'python_version': '2.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_PROGRAM_VERSION`
  - `LOGNAME`
  - `USER`
  - `NVM_DIR`
  - `HOME`
  - `PATH`
  - `PYTHONUNBUFFERED`
  - `DISPLAY`
  - `TERM_PROGRAM`
  - `LANG`
  - `TERM`
  - `Apple_PubSub_Socket_Render`
  - `COLORFGBG`
  - `SHLVL`
  - `SECURITYSESSIONID`
  - `XPC_FLAGS`
  - `ITERM_SESSION_ID`
  - `EDITOR`
  - `TERM_SESSION_ID`
  - `XPC_SERVICE_NAME`
  - `SSH_AUTH_SOCK`
  - `SHELL`
  - `ITERM_PROFILE`
  - `PIP_PYTHON_PATH`
  - `TMPDIR`
  - `__CF_USER_TEXT_ENCODING`
  - `PWD`
  - `COLORTERM`
</details>

------------

##### Expected result

Installation of `responses` package.

##### Actual result

```
$ pipenv install --verbose
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1
Current constraints:

Finding the best candidates:

Finding secondary dependencies:
------------------------------------------------------------
Result of round 1: stable, done

Locking [packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1
Current constraints:
  responses

Finding the best candidates:
  found candidate responses==0.8.1 (constraint was <any>)

Finding secondary dependencies:
  responses==0.8.1          requires cookies, mock; python_version in "2.6, 2.7, 3.2", requests>=2.0, six

INFO:pip._vendor.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): pypi.fury.io
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pipenv/resolver.py", line 66, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/pipenv/resolver.py", line 54, in main
    results = resolve(packages, pre=do_pre, sources=project.sources, verbose=is_verbose, clear=do_clear)
  File "/usr/local/lib/python2.7/site-packages/pipenv/resolver.py", line 52, in resolve
    return pipenv.utils.resolve_deps(packages, which, project=project, pre=pre, sources=sources, clear=clear, verbose=verbose)
  File "/usr/local/lib/python2.7/site-packages/pipenv/../pipenv/utils.py", line 398, in resolve_deps
    resolved_tree, resolver = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/usr/local/lib/python2.7/site-packages/pipenv/../pipenv/utils.py", line 328, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python2.7/site-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/site-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python2.7/site-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 325, in _iter_dependencies
    yield InstallRequirement.from_line(dependency_string, constraint=ireq.constraint)
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/notpip/req/req_install.py", line 181, in from_line
    markers = Marker(markers)
  File "/usr/local/lib/python2.7/site-packages/pipenv/../pipenv/../pip/_vendor/packaging/markers.py", line 282, in __init__
    raise InvalidMarker(err_str)
pip._vendor.packaging.markers.InvalidMarker: Invalid marker: u'python_version in "2.6', parse error at u'"2.6'

/usr/local/lib/python2.7/site-packages/pipenv/utils.py:1156: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/var/folders/k_/yfvkl0_n2y9_t7xr9gd16r740000gn/T/pipenv-vN8Ju3-requirements'>
  warnings.warn(warn_message, ResourceWarning)
```

##### Steps to replicate
`pipenv install` with the following `Pipfile`:

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
responses = "*"
```

**Comment by kennethreitz** [comment]
i have yet to see anyone use that syntax before. I'll have to investigate if this is a bug on our end or theirs.

**Comment by kennethreitz** [comment]
I suspect theirs, but I admit that's finger-pointing :)

**Comment by kennethreitz** [comment]
I don't think this is valid syntax.

**Comment by kennethreitz** [comment]
yeah, pip may not error out on this, but it also doesn't honor it.

**Comment by kennethreitz** [comment]
11.5.2 released, which fixes this.

**Comment by kennethreitz** [comment]
Sorry about the :bug:!

**Comment by ryanwilsonperkin** [comment]
No sweat @kennethreitz, thanks for the quick fix! I'm migrating a couple of large projects over to pipenv so I'll report anything else that I run into 🙂

**Comment by techalchemy** [comment]
@kennethreitz I think that implies we are also now officially supporting the `:python_version:` syntax for extras?

**Comment by kennethreitz** [comment]
just put a fallback mechanism in place, our custom parsing, if it fails, take it as-is.
