### ISSUE TITLE
document tox-pipenv

### ISSUE THREAD

**Issue by kennethreitz** [pypa/pipenv#1671]
https://github.com/tonybaloney/tox-pipenv

**Comment by tonybaloney** [comment]
See important related issue about owning organization of the plugin (I want to move it to Tox) https://github.com/tox-dev/tox/issues/771

**Comment by tonybaloney** [comment]
This is now https://github.com/tox-dev/tox-pipenv

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by tapaswenipathak** [comment]
Hi folks: I see a line https://github.com/pypa/pipenv/blob/master/docs/advanced.rst, can the ticket be closed?

**Comment by frostming** [comment]
I think yes.
