### ISSUE TITLE
pipenv 11.5.2 does not install

### ISSUE THREAD

**Issue by Moritz90** [pypa/pipenv#1678]
> bash-4.1$ pip --version
pip 1.5.6 from /opt/rh/python27/root/usr/lib/python2.7/site-packages (python 2.7)
bash-4.1$ pip install --user 'pipenv >=11,<12'
Downloading/unpacking pipenv>=11,<12
  Downloading pipenv-11.5.2.tar.gz (3.9MB): 3.9MB downloaded
  Running setup.py (path:/tmp/pip-build-rGYiv3/pipenv/setup.py) egg_info for package pipenv
    error in pipenv setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in pipenv setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

I've rolled back to pipenv 11.1.0 for now, which is the last version I tested successfully.

------------

##### Expected result

pipenv installs on old systems with Python 2.7.

##### Actual result

pipenv does not install.

##### Steps to replicate

See above. (System: RHEL 6, Python 2.7 installed from the software collections repository)

**Comment by kennethreitz** [comment]
upgrade setuptools

**Comment by Moritz90** [comment]
Thanks, I should have figured this out myself... Sorry for the noise.
