### ISSUE TITLE
Is there a way to install the current version of APSW?

### ISSUE THREAD

**Issue by cLupus** [pypa/pipenv#1680]
##### Expected result

Install a python package from source; e.g. [APSW](https://github.com/rogerbinns/apsw), which _cannot_ be installed through PyPi (currently).

##### Actual result

Trying to install via 'vanilla' `pipenv` gives a _really_ old version (3.9 I think, as opposed to the current; 3.22).

**Comment by kennethreitz** [comment]
uh, https://pypi.python.org/pypi/apsw/

**Comment by jtratner** [comment]
Can always use a git source if pypi really doesn’t work

**Comment by kennethreitz** [comment]
Sorry for the terseness :)

**Comment by cLupus** [comment]
My apologies for not being clearer;
The author of APSW has [said](https://rogerbinns.github.io/apsw/download.html#easy-install-pip-pypi) APSW is _not_ available in PyPi, and that the version that is there is not his, and is of lower quality. The recommended way of installing it is by compiling it from source.
My question then becomes; is there a way to give a URL, and then tell `pipenv` which steps it should take?

**Comment by kennethreitz** [comment]
you can use git ;)

**Comment by kennethreitz** [comment]
$ pipenv install -e git+<git url here>

**Comment by vildan-valeev** [comment]
> My apologies for not being clearer;
> The author of APSW has [said](https://rogerbinns.github.io/apsw/download.html#easy-install-pip-pypi) APSW is _not_ available in PyPi, and that the version that is there is not his, and is of lower quality. The recommended way of installing it is by compiling it from source.
> My question then becomes; is there a way to give a URL, and then tell `pipenv` which steps it should take?

https://rogerbinns.github.io/apsw/download.html#i-really-want-to-use-pip

pip install --user https://github.com/rogerbinns/apsw/releases/download/3.32.2-r1/apsw-3.32.2-r1.zip \
--global-option=fetch --global-option=--version --global-option=3.32.2 --global-option=--all \
--global-option=build --global-option=--enable-all-extensions
