### ISSUE TITLE
Pipenv doesn't resolve local wheel deps. 

### ISSUE THREAD

**Issue by chngtrn** [pypa/pipenv#1683]
When installing a .whl package that we built using `pipenv install package.whl` it doesn't install the dependencies in package.whl.

These are the required packages in package.whl setup.py file:
`install_requires=[
        'requests==2.18.4',
        'PySocks==1.6.7',
        'nose==1.3.7',
        'redis==2.10.6',
        'Sphinx==1.6.4',
        'twine==1.9.1',
    ]
`

Step to replicate:
`pipenv install /path/to/package.whl`  # Doesn't install dependencies
`pip install /path/to/package.whl`        # Does install package.whl dependencies

**Comment by kennethreitz** [comment]
can you try again with latest?

**Comment by kennethreitz** [comment]
cannot reproduce with latest

**Comment by chngtrn** [comment]
Why you close it so sudden? I wouldn't post it as a problem if I'm having the problem. I'll gather the info and show you.

**Comment by kennethreitz** [comment]
make sure you're using the latest version!

**Comment by chngtrn** [comment]
Sorry I might have reported the step to reproduct wrong.

What happened is that if it's a fresh new environment and I do `pipenv install` so it'll import my `requirements.txt` and the `requirements.txt` contains a local `.whl` file it only installs that `.whl` package, not its dependencies. I had to manually do a `pipenv install package.whl` for it to install the `.whl` dependencies.

**Comment by kennethreitz** [comment]
ah, I see. 

I'll see if we can improve this, but I make no promises.

**Comment by techalchemy** [comment]
@chngtrn if you install the `requirements.txt` and then `pipenv update` does it capture the dependencies?

**Comment by kennethreitz** [comment]
@techalchemy pipenv lock doesn't capture the deps at all. this is fine if we document it. but, it's a caveat, currently.

**Comment by chngtrn** [comment]
OK. I'll deal with it then. Thanks for everything and this great project.
