### ISSUE TITLE
Support aliasses like 'workon', 'cdsitepackages', 'cdproject', 'cdvirtualenv'

### ISSUE THREAD

**Issue by dwt** [pypa/pipenv#1684]
I'm trying to switch from virtualenvwrapper to pipenv, and find I really miss the aliasses. I know I can use them together, but I find that I would really like to leave virtualenvwrapper behind (for various reasons).

What I'm missing most is support for `workon`, `cdsitepackages`, `cdproject`. Is there any chance these can be included as subcommands in pipenv? To be more precise, I think `cdsitepackages`, `cdproject` could/ should still be aliasses once you have `pipenv shell` . But especially workon is something im dearly missing.

**Comment by festinuz** [comment]
I cant find the issue number, but i remember that it was discussed before and rejected(?). 

I don't know the current state of @kennethreitz regardless this, but IMO you can just write some dirty hacks for that functionality - `workon` would be hardest unless you host all your projects in a dedicated directory like `~/Projects`, in which case it sounds easy to implement.

**Comment by kennethreitz** [comment]
exactly

**Comment by kennethreitz** [comment]
out of scope, for now

**Comment by uranusjr** [comment]
You can still use virtualenvwrapper if you like. A virtualenv is a virtualenv, it won’t care if it’s created by Pipenv, as long as it’s in `WORKON_HOME`. You can write a wrapper around it to find the correct virtualenv name for you, too. The logic is already in Pipenv.

**Comment by dwt** [comment]
I think the thing that would make implementing workon the easiest is that pipenv (like virtualenvwrapper) records the project directory in a .project file in virtualenv. That way the metadata is there to do something like this.

Would you guys be willing to accept a pull request like that?

**Comment by techalchemy** [comment]
I think that’s pretty unlikely right now. We are not looking to add more maintenance overhead
