### ISSUE TITLE
Issue getting pipenv to run in a python3 script.

### ISSUE THREAD

**Issue by JHowell45** [pypa/pipenv#1685]
Hi I'm currently having issues getting python3 to recognise my Pipenv virtualenv.

I have created a simple scripts for executing tests within `pipenv` along the lines of `pipenv run pytest ...`. The scripts is packaged into a click application using a `setup.py` file and installed by running `pip3 install -e .` in the click applications directory. However when I try to run this application `script test` it fails saying:
```
Creating a virtualenv for this project…
Using /usr/local/Cellar/python/3.6.4_4/bin/python3.6 (3.6.4) to create virtualenv…
⠋/usr/local/opt/python/bin/python3.6: Error while finding module specification for 'pipenv.pew' (ModuleNotFoundError: No module named 'pipenv')
```
which it shouldn't as a pipenv environment already exists. I have noticed that when running the following:
`python -c "from subprocess import call; call(['pipenv', '--venv'])"`
`python3 -c "from subprocess import call; call(['pipenv', '--venv'])"`
python shows the virtualenv, but python3 fails saying `No virtualenv has been created for this project yet!`
Any help would be greatfully appreciated!

The click applciation is along the lines of:
```
import click
from subprocess import call

@click.group()
def cli:
  pass

@click.command()
def test():
  call(['pipenv', 'run', 'pytest', ...])
```
The script is called using: `script test`

**Comment by kennethreitz** [comment]
I don't think we support what you're trying to do

**Comment by JHowell45** [comment]
The code is being called similarly to how it would if it was executed from a bash file, I guess my issue is more as to why `python` is able to recognise the pipenv environment and `python3` is not. Surely both of those instances should be able to recognise the Pipenv environments. I even tried building the environment using the specific `python3` version I have by calling `pipenv --python /path/to/python3`.

**Comment by kennethreitz** [comment]
you need to have pipenv installed properly in each python environment to be able to invoke it that way

**Comment by JHowell45** [comment]
ok thanks, I currently have it installed using Homebrew, though I guess I should install it in `python3` also.

**Comment by JHowell45** [comment]
urgh I'm such a doofus. Cheers, yh i uninstalled the Homebrew version of `pipenv` and installed it into `python3` the virtualenvs are now accessible for both versions of python. 

My script now also works!
