### ISSUE TITLE
Allow Pipfile to consume environment variables

### ISSUE THREAD

**Issue by dvf** [pypa/pipenv#1688]
It would be awesome if `Pipfile` could be parsed to allow for environment variables.

While it's great that `pipenv` supports private indexes, it's annoying if those indexes require credentials—it's bad practice to store them in source control:

```
[[source]]

url = "https://{{ MY_USERNAME }}:{{ MY_PASSWORD }}@my_custom_repo.jfrog.io/simple"
verify_ssl = true
name = "pypi"
```

Happy to contribute a PR for this if this gets some thumbs.

**Comment by kennethreitz** [comment]
:+1:

**Comment by gsemet** [comment]
@kennethreitz what do you think about making this section able to inherits values from a global setting file, such as /etc/pipenv.conf (a-la /etc/pip.conf), so all Pipfile within a private organisation can use the same internal repository (nexus, artifactory, other,...)

**Comment by kennethreitz** [comment]
no

**Comment by techalchemy** [comment]
@gsemet I believe pipfiles will use sources specified in your pip.conf now though

**Comment by kennethreitz** [comment]
When we create a pipfile for you, it will be populated with sources from pip.conf.

**Comment by gsemet** [comment]
not sure, we use our internal nexus cache in pip.conf:
```
$ cat /etc/pip.conf
[global]
trusted-host = nexus.mycompagny.fr
index = http://nexus.mycompagny.fr/repository/pypi/pypi
index-url = http://nexus.mycompagny.fr/repository/pypi/simple
```

when executing pip install on its own, it uses this server.

when creating a pipfile:
```
$ pipenv install request
...
$ cat Pipfile                                                                                                                                                                                              
[[source]]
name = "pypi"
verify_ssl = true
url = "https://pypi.python.org/simple"
...```

**Comment by kennethreitz** [comment]
we pick up user pip conf i think, not global pip conf.

**Comment by kennethreitz** [comment]
here's the code: https://github.com/pypa/pipenv/blob/master/pipenv/project.py#L419

**Comment by dvf** [comment]
That sounds potentially dangerous if you’re storing credentials in pip.conf. 

@kennethreitz, I was reading another issue where you referred to the Pipfile as the source of truth. I think this is a great idea and should stay that way.

**Comment by kennethreitz** [comment]
we could detect high-entropy strings automatically (or just urlparse).

**Comment by kennethreitz** [comment]
@dvf pipfile is def the source of truth.

**Comment by kennethreitz** [comment]
i think environment variable injection is a good idea though

**Comment by kennethreitz** [comment]
url = "https://:$PYPI_USERNAME:$PYPI_PASSWORD@pypi.python.org/simple"

**Comment by kennethreitz** [comment]
or just `https://:$PYPI_CREDS@pypi.python.org/simple`

**Comment by kennethreitz** [comment]
We raise an error if `PYPI_CREDS` isn't in `os.environ`.

**Comment by dvf** [comment]
If we only check `PYPI_CREDS`, we're assuming that a user would only have a single source defined in their `Pipfile`. I think we should allow for any environment variable—similar to how Docker allows you to use [Environment Variables in Compose files](https://docs.docker.com/compose/environment-variables/).

- `Pipfile` is the ultimate source of truth
- Any value can contain an environment variable, but nothing else

**Comment by kennethreitz** [comment]
Of course we'd support any.

**Comment by kennethreitz** [comment]
i'm just using that as an example

**Comment by dvf** [comment]
Oh gotcha 👍 

Do you have any ideas about how you see this being implemented?

**Comment by jtratner** [comment]
@kennethreitz - env variable expansion is something I'd be happy to implement unless somebody else wants to (prob have time next weekend), but also happy to leave to other ambitious and/or helpful folks

**Comment by dvf** [comment]
@jtratner I was going to take a stab at it. Feel free to leave some suggestions in advance though.

**Comment by jtratner** [comment]
oh go for it @dvf :)

**Comment by techalchemy** [comment]
Resolved by #1769 and #1809

**Comment by njgrisafi** [comment]
It would be nice if we can have environment variables loaded throughout the entire Pipfile. E.g.
```
[dev-packages]
my-package = {path="${PATH_TO_REPO}", editable = true}
```

**Comment by andyneff** [comment]
@njgrisafi The reason this does not work appears to be due to https://github.com/pypa/pipenv/blob/8aa9283fda2e8cc532f517969f5f3e1969e8d4a2/pipenv/project.py#L519 using tomlkit instead of `pipfile.api.PipfileParser`

However, this gets further complicated by the fact that the `path` is copied into the `Pipfile.lock`. The way inject currently works, it that it injects the values at parse time, which means by the time you get to writing the lock file, it will write the value of the the environment variable, not the `${FOO}` syntax. :(

I agree, this feature working on path would be very much desired for me too. I want to run a Pipfile in and out of a docker container, but currently implementation limits this.

**Comment by iuriguilherme** [comment]
So where are the docs?
