### ISSUE TITLE
--pre per–package

### ISSUE THREAD

**Issue by gsemet** [pypa/pipenv#1696]
This is a follow up on #1677.

`pipenv lock` doesn't work because I need a preversion of a single package. `pipenv lock --pre` does work but might add other, unwanted preversion in dependencies.

I would like to propose my help in implementing this feature: if one package needs to be frozen to a preversion (and only one), allow the dependency finding to pick this one even without the `--pre` parameter.

The `--pre` parameter which the preversion search for **all** packages, and sometimes we only want one package

**Comment by kennethreitz** [comment]
This would be nice, but is not feasible (as far as I know) with the way our current resolver code works. It's either "all or nothing".

**Comment by techalchemy** [comment]
But if you know you want a specific package to be prerelease then you probably know what version, so (once we get the strict pinning bug sorted) you should be able to just pin the prerelease

**Comment by kennethreitz** [comment]
+1, closing for that solution, for now. Our resolver just doesn't allow this yet.

**Comment by kennethreitz** [comment]
Thanks for the suggestion, though!

**Comment by gsemet** [comment]
Hello @techalchemy If you reread my bug, this pinning of the release does **not** work if there are 2 dependencies, where one says "a==1.0" and the other says "a>=1.0", of course when the resolution if obvious.
When **all** packages says it wish "a==1.0", yes, pinning works.

**Comment by kennethreitz** [comment]
please see #1687

**Comment by gsemet** [comment]
indeed, same issue

**Comment by tribals** [comment]
Well, I think, if the problem in resolver, there is need to replace it.

**Comment by tribals** [comment]
And not reject any issues just with "our resolver can't do that".
