### ISSUE TITLE
Pipenv tries to install dependency of package which was excluded by marker

### ISSUE THREAD

**Issue by anentropic** [pypa/pipenv#1705]
pipenv-11.6.1

I have in my Pipfile:

```
[dev-packages]
mypy = {version = "*", markers = "python_version >= '3.4'"}
```

When I run `pipenv install --dev` against Python 2.7 I get the following error:

```
Ignoring mypy: markers 'python_version >= "3.4"' don't match your environment
An error occurred while installing typed-ast==1.1.0! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 48/48 — 00:00:53
```

`typed-ast` is not listed in my Pipfile. If I run `pipenv graph` it shows that `mypy` is the only package which depends on `typed-ast`:

```
mypy==0.570
  - typed-ast [required: >=1.1.0,<1.2.0, installed: 1.1.0]
```

So it seems that pipenv is trying to install `typed-ast` due to `mypy` being in my Pipfile, despite the fact that the markers for mypy correctly caused pipenv to skip installing mypy itself.

I am struggling generally with the workflow for using pipenv on a library which needs to be tested against multiple python versions. The lock-file seems not helpful in this case.

**Comment by kennethreitz** [comment]
we don't cascade markers to their dependencies. if you want conditionals for sub-deps, you also need to include them in your Pipfile.

**Comment by anentropic** [comment]
this doesn't make much sense to me, just seems like a bug

**Comment by kennethreitz** [comment]
You're asking for a lot — this stuff is much easier said than done :)

**Comment by anentropic** [comment]
Sorry, I appreciate that :)  I assumed since it already had to deal with a dependency graph...
