### ISSUE TITLE
Trouble when `$ pipenv install`

### ISSUE THREAD

**Issue by koddr** [pypa/pipenv#1707]
I have trouble when `$ pipenv install`:

```bash
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
er exception occurred:

Traceback (most recent call last):
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/resolver.py", line 66, in <module>
    main()
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/resolver.py", line 54, in main
    results = resolve(packages, pre=do_pre, sources=project.sources, verbose=is_verbose, clear=do_clear)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/resolver.py", line 52, in resolve
    return pipenv.utils.resolve_deps(packages, which, project=project, pre=pre, sources=sources, clear=clear, verbose=verbose)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 429, in resolve_deps
    r = requests.get('https://pypi.org/pypi/{0}/json'.format(name), timeout=10)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/../pipenv/vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/../pipenv/vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/../pipenv/vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/../pipenv/vendor/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 2] No such file or directory
```

My `$ python -m pipenv.help` is:

Pipenv version: `'11.6.2'`

Pipenv location: `'/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv'`

Python location: `'/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m`
  - `3.6`: `/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/bin/python3.6`
  - `3.6`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `3.6.4`: `/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `3.6.4`: `/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/bin/python3`
  - `3.6.1`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3`
  - `3.6.1`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.4.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST '
                     '2017; root:xnu-4570.41.2~1/RELEASE_X86_64',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `ANDROID_HOME`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `VIRTUAL_ENV`
  - `PATH`
  - `PWD`
  - `JAVA_HOME`
  - `XPC_FLAGS`
  - `PS1`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `HOME`
  - `LOGNAME`
  - `LC_CTYPE`
  - `TOOLBOX_VERSION`
  - `BASH_FUNC_generate_command_executed_sequence%%`
  - `_`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/bin:/usr/local/share/npm/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/gettext/bin:/usr/local/share/npm/bin`
  - `SHELL`: `/bin/zsh`
  - `PWD`: `/Users/vikkyshostak/PyCharmProjects/django_visatorus`
  - `VIRTUAL_ENV`: `/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG`

---------------------------

Contents of `Pipfile` ('/Users/vikkyshostak/PyCharmProjects/django_visatorus/Pipfile'):

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

django = "*"
django-rest-framework = "*"
markdown = "*"
gunicorn = "*"
django-hijack = "*"
django-hijack-admin = "*"
celery = {extras = ["redis"]}
django-admin-interface = "*"
"psycopg2-binary" = "*"
weasyprint = "*"
django-modeltranslation = {git = "https://github.com/deschler/django-modeltranslation.git"}


[dev-packages]

django-debug-toolbar = "*"
pytest-django = "*"

```

I downgrade to pipenv `11.5.3` and everything is okay! What's wrong?

**Comment by kennethreitz** [comment]
11.6.3 should fix this.

**Comment by kennethreitz** [comment]
I take that back.

**Comment by kennethreitz** [comment]
workaround: pip install certifi

**Comment by kennethreitz** [comment]
yes — try 11.6.3
