### ISSUE TITLE
pipenv install can fail on dev dependencies

### ISSUE THREAD

**Issue by gzzo** [pypa/pipenv#1711]
Since `pipenv install` tries to lock when the lockfile is out of date, the command can fail trying to lock dev dependencies when `--dev` was not specified.

<details>
Pipenv version: `'11.6.3'`

Pipenv location: `'/usr/local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.6`: `/usr/bin/python2.6`
  - `2.6`: `/usr/bin/python2.6`
  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`

  - `3.6.4`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `3.6.4`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '16.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT '
                     '2017; root:xnu-3789.70.16~2/RELEASE_X86_64',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_SESSION_ID`
  - `SSH_AUTH_SOCK`
  - `Apple_PubSub_Socket_Render`
  - `COLORFGBG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `LANG`
  - `PWD`
  - `SHELL`
  - `TERM_PROGRAM_VERSION`
  - `TERM_PROGRAM`
  - `PATH`
  - `COLORTERM`
  - `TERM`
  - `HOME`
  - `TMPDIR`
  - `USER`
  - `XPC_SERVICE_NAME`
  - `LOGNAME`
  - `__CF_USER_TEXT_ENCODING`
  - `ITERM_SESSION_ID`
  - `SHLVL`
  - `OLDPWD`
  - `ZSH`
  - `PAGER`
  - `LESS`
  - `LC_CTYPE`
  - `LSCOLORS`
  - `AWS_ACCESS_KEY_ID`
  - `AWS_SECRET_ACCESS_KEY`
  - `GOPATH`
  - `CLUSTER_NAME`
  - `KOPS_STATE_STORE`
  - `NVM_DIR`
  - `NVM_CD_FLAGS`
  - `NVM_BIN`
  - `_`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/guido/.nvm/versions/node/v8.9.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/guido/go/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/guido/demo`

---------------------------

Contents of `Pipfile` ('/Users/guido/demo/Pipfile'):

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]
"boto3" = "*"


[dev-packages]
"c367f39" = {path = "/does/not/exist"}


[requires]

python_version = "3.6"

```
</details>
------------

##### Expected result

I would dev dependencies to not interfere with `pipenv install`

##### Actual result

```
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
q_install.py", line 82, in __init__
    req = Requirement(req)
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/vendor/pip9/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip9._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'/does/no'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pipenv/resolver.py", line 66, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/pipenv/resolver.py", line 54, in main
    results = resolve(packages, pre=do_pre, sources=project.sources, verbose=is_verbose, clear=do_clear)
  File "/usr/local/lib/python3.6/site-packages/pipenv/resolver.py", line 52, in resolve
    return pipenv.utils.resolve_deps(packages, which, project=project, pre=pre, sources=sources, clear=clear, verbose=verbose)
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 397, in resolve_deps
    resolved_tree, resolver = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 290, in actually_resolve_reps
    constraint = [c for c in req.parse_requirements(t, session=pip_requests)][0]
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 290, in <listcomp>
    constraint = [c for c in req.parse_requirements(t, session=pip_requests)][0]
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/vendor/pip9/req/req_file.py", line 93, in parse_requirements
    for req in req_iter:
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/vendor/pip9/req/req_file.py", line 158, in process_line
    isolated=isolated, options=req_options, wheel_cache=wheel_cache
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/vendor/pip9/req/req_install.py", line 235, in from_line
    wheel_cache=wheel_cache, constraint=constraint)
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/vendor/pip9/req/req_install.py", line 91, in __init__
    "Invalid requirement: '%s'\n%s" % (req, add_msg))
pip9.exceptions.InstallationError: Invalid requirement: '/does/not/exist'
It looks like a path. Does it exist ?
```

##### Steps to replicate

The Pipfile I provided is enough to reproduce with `pipenv install`

**Comment by kennethreitz** [comment]
Without a Pipfile, we cannot reproduce.

**Comment by gzzo** [comment]
@kennethreitz the Pipfile is in the output of pipenv.help, in the details section.

**Comment by kennethreitz** [comment]
oh i missed that, sorry :)

**Comment by kennethreitz** [comment]
this is expected behavior.
