### ISSUE TITLE
Pipenv isn't installing a several versions

### ISSUE THREAD

**Issue by epicserve** [pypa/pipenv#1712]
We use fabric to create new instances of our web application and it installs pipenv inside a virtualenv and that doesn't seem to be working on several different versions of pipenv. I wasn't able to install the following versions: 11.6.4, 11.6.3, 11.6.2, 11.6.1, 11.6.0, 11.5.3, 11.5.0, 11.4.0, 11.3.0, 11.2.0. However, I was able to install 11.1.0 and once I install 11.1.0, I can install any of the other versions that didn't install before.

The error that you get is, "error in pipenv setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers"

This also might be related to issue #1633

##### Environment

Pipenv version: `'11.6.4'`

Pipenv location: `'/home/■■■■■■/temp/lib/python3.5/site-packages/pipenv'`

Python location: `'/home/■■■■■■/temp/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/home/■■■■■■/temp/bin/python3.5`
  - `3.5`: `/usr/bin/python3.5`

  - `3.5.2`: `/home/■■■■■■/temp/bin/python`
  - `2.7.12`: `/usr/bin/python`
  - `2.7.12`: `/usr/bin/python2`
  - `3.5.2`: `/home/■■■■■■/temp/bin/python3`
  - `3.5.2`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.5.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.4.0-116-generic',
 'platform_system': 'Linux',
 'platform_version': '#140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018',
 'python_full_version': '3.5.2',
 'python_version': '3.5',
 'sys_platform': 'linux'}
```

System environment variables:

  - `HOME`
  - `PWD`
  - `SHELL`
  - `LC_CTYPE`
  - `XDG_RUNTIME_DIR`
  - `SSH_CLIENT`
  - `LOGNAME`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `LESSCLOSE`
  - `LESSOPEN`
  - `MAIL`
  - `SSH_CONNECTION`
  - `OLDPWD`
  - `LS_COLORS`
  - `PYTHONUNBUFFERED`
  - `LANG`
  - `PIP_PYTHON_PATH`
  - `_`
  - `PS1`
  - `VIRTUAL_ENV`
  - `SHLVL`
  - `PATH`
  - `SSH_TTY`
  - `XDG_SESSION_ID`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/■■■■■■/temp/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/oeie-scripts/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/■■■■■■/temp`
  - `VIRTUAL_ENV`: [`/home/■■■■■■/temp`](url)

##### Expected result

That pipenv would install without errors.

##### Steps to replicate

```
$ virtualenv --python=`which python3` temp
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in temp/bin/python3
Also creating executable in temp/bin/python
Installing setuptools, pip...done.
$ cd temp/
$ source bin/activate
$ pip install pipenv
Downloading/unpacking pipenv
  Downloading pipenv-11.6.4.tar.gz (5.0MB): 5.0MB downloaded
  Running setup.py (path:/home/brento/temp/build/pipenv/setup.py) egg_info for package pipenv
    error in pipenv setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in pipenv setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/brento/temp/build/pipenv
Storing debug log for failure in /home/brento/.pip/pip.log
```

**Comment by kennethreitz** [comment]
please update setuptools.

**Comment by epicserve** [comment]
@kennethreitz,

I added `pip install -U setuptools pip` to my fabfile and it's working now. Is that the best way to handle it?

**Comment by kennethreitz** [comment]
i believe so
