### ISSUE TITLE
Rate-limiting releases

### ISSUE THREAD

**Issue by amancevice** [pypa/pipenv#1720]
I am a big fan of this project. I am working on getting my team to switch over to use it.

However, I worry that the pace of development seems to be a little out of control. I opened a PR to Homebrew to upgrade to 11.6.4 because 11.6.1 was completely broken for me and by the time I submitted it pipenv is already at 11.6.9!

Today may be an exceptionally patch-filled day, but a more slow-paced approach to planning/releasing features would be very welcomed by the humble user, I think.

**Comment by kennethreitz** [comment]
it's actually the opposite — we're trying to make smaller, incremental changes in smaller releases so things break less often.

**Comment by kennethreitz** [comment]
We're already in talks to with homebrew to switch the formula style to one like aws-cli uses.

**Comment by amancevice** [comment]
Incremental changes sound good, but stability is best. Is there any reason not release incremental changes to a beta channel or something?

Everyone releases bugs, myself included, so I'm sympathetic -- I don't think I've ever released a `.0` release for more than a day before finding some stupid bug -- but nearly half (4/9) releases on the `11.6` family are simply marked "Bugfixes." That tells me something may be wrong in testing.

**Comment by kennethreitz** [comment]
Someone reports a bug, we fix it, we roll out a release.

Most projects take weeks to do these things. We take hours.

**Comment by kennethreitz** [comment]
You also have to keep in mind the surface area we're covering — PPA, Linux Distros, Windows users, Heroku, etc.

**Comment by kennethreitz** [comment]
If we were just a simple library it would be easy to not ship releases often.

I hope to get into a lax schedule soon.

**Comment by amancevice** [comment]
Don't get me wrong: the pipenv project is great! Fast turnaround on patching reported bugs is great! Covering a huge surface area is hard!

If there was a beta channel, I'd probably be on it so I could help the project along in my own small way. But it's not super fun to tell your coworkers to try out this new & exciting tool and than have them come back to you and say "it's broke, I'm not gonna use this," either.

**Comment by kennethreitz** [comment]
hence the releases :)

**Comment by techalchemy** [comment]
We are making large improvements to dependency resolution across platform and python versions. That code is quite intricate and we have been stepping through releases as users in all types of environments find bugs that we can’t. 

If you have a problem with updating often, feel free to keep using broken versions. 9.0.3 works, mostly, just please don’t file any issues about it. 

If you think you can assist with making our tests cover those cases we currently don’t catch, pull requests are always welcome :)

**Comment by amancevice** [comment]
I guess we're just three different people :)

Thanks for the discourse. I'll open a PR for the first bug I find.

**Comment by gsemet** [comment]
Hello. Like pipfile.lock freeze dependencies, I usually freeze the pip/pipenv in my projects (I use Makefile for that). Not full version pinning, but with comparison operator (`pip install --user pipenv>9.0 pip>=9`), that allows to temporarily disable update when upstream projet has an impacting change (`pip install --user pipenv>9.0,<11 pip>=9`). Typically the time a cleaner solution is found to integrate this new change.

Rapidily changing project is very good for the general picture, but it is completely acceptable for projet to add their own control process on top of that. At least ensure it has the option to upgrade or not.
