### ISSUE TITLE
pipenv 11.6.2 breaks installing from private PyPIs

### ISSUE THREAD

**Issue by alexbecker** [pypa/pipenv#1723]
Running `pipenv install --ignore-pipfile` breaks with the message `WARNING: Invalid requirement, parse error at "'--extra-'"`. Latest working version is 11.6.1, confirmed broken at both 11.6.2 and 11.6.9.

##### Expected result

Packages installed normally.

##### Actual result

```
$ pipenv install --ignore-pipfile --verbose
Creating a virtualenv for this project…
Using /usr/local/bin/python (3.6.4) to create virtualenv…
Already using interpreter /usr/local/bin/python
Using base prefix '/usr/local'
New python executable in /root/.local/share/virtualenvs/app-4PlAip0Q/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /root/.local/share/virtualenvs/app-4PlAip0Q
Creating a Pipfile for this project…
Installing dependencies from Pipfile.lock (5e019a)…
Installing 'my-private-package==5.1.1  --extra-index-url https://packagecloud.io/pypi/simple'
WARNING: Invalid requirement, parse error at "'--extra-'"
ABORTING INSTALL... You will have to reinstall any packages that failed to install.
```

##### Steps to replicate

Use the following Pipfile.lock:

```
{
    "_meta": {
        "hash": {
            "sha256": "7c7b3a5dbc4c43dd9b9ef5182ea9baa5d5b584ace52a4887f83c8112fd5e019a"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            },
            {
                "name": "packagecloud",
                "url": "https://packagecloud.io/pypi/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "my-private-package": {
            "hashes": [],
            "version": "==5.1.1"
        }
    },
    "develop": {}
}
```

Here `my-private-package` must be a package that (presumably) exists on the private package index but not PyPI. Obviously this will fail since I made up the credentials and package name, but it fails first with the error noted above, and with correct package and credentials still fails.

**Comment by kennethreitz** [comment]
Please provide your Pipfile.

**Comment by alexbecker** [comment]
@kennethreitz Is the Pipfile possibly relevant when running `pipenv install --ignore-pipfile`?? If so this should be clearly documented.

**Comment by kennethreitz** [comment]
No, I need it to replicate your issue.

**Comment by kennethreitz** [comment]
It'll save me time.

**Comment by alexbecker** [comment]
Unfortunately I cannot create a `Pipfile` that will generate that `Pipfile.lock` without using a real package and real extra index URL, which contains a credential.

Debugging, it looks like if I add a hash to the `Pipfile.lock` then this works, or at least fails with a different error since the hash is wrong. Is there no backwards-compatibility guarantee for the `Pipfile.lock`, e.g. if generated with `pipenv` version X.Y.Z it is not guaranteed to work with X.Y.Z+1?

**Comment by techalchemy** [comment]
@alexbecker if you want help troubleshooting your issue you need to give us a reproducible set of installation material, abstract questions about our versioning is not going to get you anywhere. No, we do not intentionally put bugs in our software, we also can't remove them without relevant diagnostic information

**Comment by alexbecker** [comment]
@techalchemy I gave you the `Pipfile.lock`, you can run `pipenv install --ignore-pipfile` with that lockfile and you will see the issue. The only way this could not be a bug is if you're declaring that `Pipfile.lock` to be invalid.

I *can* set up a new private package index, with no secret information, to make a `Pipfile` which you can use to reproduce that, but before I go through that effort I'd like to know whether this is something you would fix, rather than just tell me not to use a `Pipfile.lock` with new versions of `pipenv`.

**Comment by kennethreitz** [comment]
We have our own private indexes we can use. Just wanted your pipfile to save us typing.

**Comment by kennethreitz** [comment]
anyway, we fixed this earlier today. please try later releases.

**Comment by kennethreitz** [comment]
i believe.

**Comment by alexbecker** [comment]
@kennethreitz As I stated in the issue, I tried with `11.6.9` and it failed. I do not see any later releases.

Meanwhile, re-generating the `Pipfile.lock` with pipenv `11.6.9` includes the hashes and installing that `Pipfile.lock` works. So release `11.6.2` breaks backwards compatibility of `Pipfile.lock`, but I do not know whether you want to maintain backwards compatibility or make any sort of announcement about it.

**Comment by kennethreitz** [comment]
you just said 11.6.9 failed, and then said it worked. 

no backwards compatibility was broken — we removed non-deterministic unnecessary metadata from the lockfile.

**Comment by alexbecker** [comment]
@kennethreitz The `Pipfile.lock` I posted--which was generated with some previous version of `pipenv`--fails with 11.6.9.

If I use `pipenv` 11.6.9 to generate my `Pipfile.lock`, then **that** `Pipfile.lock` works.

**Comment by kennethreitz** [comment]
okay, so please re-lock.

**Comment by kennethreitz** [comment]
We aren't magicians :)
