### ISSUE TITLE
Support verification of GnuPG signed packages

### ISSUE THREAD

**Issue by ovalseven8** [pypa/pipenv#1735]
You can upload packages to PyPI and sign the distributions using GnuPG with `twine` (https://packaging.python.org/tutorials/distributing-packages/#upload-your-distributions).

My recommendation for `pipenv` is that you can (optionally) add a GnuPG key to the piplock file for packages. The update or installation process will then only work if the packages has been signed with the correct GnuPG key.

While I agree that `pipenv` should not add too many features and focus on being relatively lighweight and functional, I think this is an important issue because of security. Manually veryfing signatures is not the way to go.

**Comment by kennethreitz** [comment]
thanks for the recommendations.

**Comment by ovalseven8** [comment]
I'd at least know some reason why this has been closed several seconds after I created the issue.

**Comment by kennethreitz** [comment]
Our issue tracker is for outstanding issues, not new ideas. This was the right place to put it it, and thank you for taking the time to raise it with us —

Your issue has been noted carefully, and will be considered in the future.

**Comment by ovalseven8** [comment]
Thank you for the clarification! :+1: 

Is there some other issue tracker for ideas/features where things are discussed? So I could track progess. :smile:

**Comment by kennethreitz** [comment]
Can you add it to our wiki?

**Comment by ovalseven8** [comment]
Well, I do not have any permissions to do so. But anyway, keep up the good work and perhaps this feature lands on pipenv someday! :)

**Comment by kennethreitz** [comment]
i added it :)
