### ISSUE TITLE
Problem with stackless version of interpreter of python

### ISSUE THREAD

**Issue by mmasztalerczuk** [pypa/pipenv#1740]
This is more question, sorry for that but I can't find any information about support for stackless version of python.
Is stackless is supported by _pipenv_? I don't have any problem with _stackless_ version of python interpreter (_pyenv_ is working fine), but when I'm trying to configure project by _pipenv_ with _stackless_ as interpreter something is going wrong.

```
 mariusz@hal:~/stack$ pipenv --python stackless-3.5.4
 Warning: Python stackless-3.5.4 was not found on your system…
 Would you like us to install CPython stackless-3.5.4 with pyenv? [Y/n]: 
 Installing CPython stackless-3.5.4 with pyenv (this may take a few minutes)…
 ⠋
 Warning: The Python you just installed is not available on your PATH, apparently.
 mariusz@hal:~/stack$ pyenv versions
   system
   3.4.0
   3.6.0
   pypy3.5-5.10.0
 * stackless-3.5.4 (set by /home/mariusz/.pyenv/version)
   stackless-dev
 mariusz@hal:~/stack$ python
 Python 3.5.4 Stackless 3.1b3 060516 (default, Mar 14 2018, 16:02:19) 
 [GCC 7.2.0] on linux
 Type "help", "copyright", "credits" or "license" for more information.
```

When I trying to use pypy everything is fine - `pipenv --python pypy`

**Comment by kennethreitz** [comment]
we have no explicit support for this — we target cpython interpreters.

**Comment by uranusjr** [comment]
FWIW you can use `pipenv --python <full absolute path to the actual python interpreter>`. Pipenv should function (although unsupported) as long as it works reasonably like CPython.

**Comment by mmasztalerczuk** [comment]
Are you interested in PR with adding support for syntax like`pipenv --python stackless-3.5.4` or `pipenv --python pypy3.5-5.10.0` ? Yesterday I was reading source code of pipenv and after small changes, I was able to create correctly working environment with a stackless interpreter. 
I think that I can add support for most of pyenv interpreters.

**Comment by uranusjr** [comment]
@mmasztalerczuk Maybe share the changes first? It might not be desired to add extra maintenance burden, but if it’s a more general “make Pipenv do things more correctly” kind of change it may be accepted.

**Comment by mmasztalerczuk** [comment]
Ok. I will prepare PR to review :) Thanks :)

**Comment by techalchemy** [comment]
@mmasztalerczuk before you invest too much effort be aware that we have a re implementation of our python finders in the pipeline. Same basic premise for pyenv so I imagine we can use whatever approach you implement

**Comment by kennethreitz** [comment]
FYI it’s not likely to be accepted. I don’t want to encourage stackless use, and you can already specify it with —python.
