### ISSUE TITLE
`pipenv install` does not detect dependencies in setup.cfg

### ISSUE THREAD

**Issue by jleclanche** [pypa/pipenv#1746]
`pipenv, version 11.0.7`

I have the following project:
* https://github.com/HearthSim/twitch-hdt-ebs/tree/7cb8315eb2740e520ac74b0dc93ab252a8199f69

I ran `pipenv install` at the root.

Now with most projects, pipenv detects `requirements.txt`. But before pipenv, I was using setup.cfg to define dependencies as it's less icky than requirements.txt and I can do `pip install .`.

##### Expected result

pipenv should have detected the dependencies in setup.cfg install_requires

##### Actual result

An empty venv and pipfile were created.

**Comment by uranusjr** [comment]
Pipenv reads dependencies from Pipfile, which does not take setup.py (and by extension setup.cfg) into account, because they serve different purposes. [Read the docs.](https://docs.pipenv.org/advanced/#pipfile-vs-setup-py)

**Comment by jleclanche** [comment]
@uranusjr but pipenv does read dependencies from `requirements.txt` on first install.

**Comment by uranusjr** [comment]
requirements.txt and setup.py serve different purposes. Pipfile replaces common usages of requirements.txt, but not setup.py. [Further reading.](https://caremad.io/posts/2013/07/setup-vs-requirement/)

**Comment by kennethreitz** [comment]
$ pipenv install -e .

**Comment by jleclanche** [comment]
@kennethreitz Thanks, that makes sense.

**Comment by internetofjames** [comment]
Not sure if this is cause to reopen the ticket, but @kennethreitz 's answer of `pipenv install -e .` only works for projects with a `setup.py` file.

I'd love to see support for `setup.cfg` declared dependencies in the same way.

**Comment by ringerc** [comment]
It appears that `setup.cfg` is now handled by `pipenv install -e`, but it does not appear to understand the `options.extras_require` `setuptools` option.

The required incantation appears to be

```
pipenv install -e '.[test,debug]'
```

for example, assuming `extras_require` contains `test` and `debug` groups. This will result in a `Pipfile` entry like

```
[packages]
mylocalpkg = {editable = true, extras = ["debug", "test"], path = "."}
```
