### ISSUE TITLE
Up arrow doesn't work in pipenv shell

### ISSUE THREAD

**Issue by ethanhs** [pypa/pipenv#1759]
When I spawn `pipenv shell` I loose all the pretty colors and I can no longer use command prompt history :(

<details><summary>$ python -m pipenv.help output</summary>
Pipenv version: `'11.8.0'`

Pipenv location: `'C:\\Python36\\lib\\site-packages\\pipenv'`

Python location: `'C:\\Python36\\python.exe'`

Other Python installations in `PATH`:

  - `2.7`: `C:\Python27\python.exe`
  - `3.6`: `C:\Python36\python.exe`
  - `3.7`: `C:\Python37\python.exe`

  - `3.6.4`: `C:\Python36\python.exe`
  - `2.7.14`: `C:\Python27\python.exe`
  - `3.7.0`: `C:\Python37\python.exe`
  - `3.7.0`: `C:\Windows\py.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17618',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'win32'}
```

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: <snip>
---------------------------
Contents of `Pipfile` ('C:\\Users\\ethanhs\\Documents\\halibut\\Pipfile'):

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]



[dev-packages]



[requires]

python_version = "3.6"

```
------------

##### Expected result

I'd expect the colors to remain and for command history to work.

##### Actual result

The colors are lost, and the up key to fill in previous commands doesn't work. (even after entering a few in the new prompt).

##### Steps to replicate

Just `pipenv shell`.

--------------

I believe the color loss happens because a new shell is spawned.

**Comment by uranusjr** [comment]
Known and not top priority. Happy to accept related contributions but currently out of scope of the core team.

**Comment by ethanhs** [comment]
Okay, I'm glad its known. I didn't see a bug about it, but perhaps I missed it.

**Comment by uranusjr** [comment]
Yeah the issue tracker is difficult to comprehend. GitHub’s search feature is very, very bad.

**Comment by mojimi** [comment]
This, specifically in visual studio code.

**Comment by LakshitF** [comment]
Still not fixed?
