### ISSUE TITLE
False positive UnsupportedPythonVersion Error while installing from a virtual environment

### ISSUE THREAD

**Issue by v1k45** [pypa/pipenv#1764]
While installing a package which requires a specific version of python3 to work, pipenv seems to raise a false positive unsupported error if pipenv is installed on python2 system.

More details here: https://github.com/aio-libs/aiohttp/issues/2843

**Comment by uranusjr** [comment]
You Pipenv version is *way* too old. The runtime detection has been significantly improved since then. Please upgrade.
