### ISSUE TITLE
pipenv uses deprecated pypi.python.org

### ISSUE THREAD

**Issue by jaraco** [pypa/pipenv#1765]
pypi.python.org is deprecated in favor of pypi.org. Most tools have updated and the default is to use https://pypi.org/ as the default repository. A [quick search](https://github.com/pypa/pipenv/search?utf8=%E2%9C%93&q=%22pypi.python.org%22&type=Code) reveals 33 cases where pipenv uses pypi.python.org. It should probably instead use pypi.org instead.

**Comment by jaraco** [comment]
Aha. Looks like this issue is being addressed in #1668.

**Comment by kennethreitz** [comment]
pypi.org will be released later this month
