### ISSUE TITLE
Excilipt tell  the project home?

### ISSUE THREAD

**Issue by SuJiKiNen** [pypa/pipenv#1780]
when create a virtualenv with pipenv,it print following the info.
`Creating a virtualenv for this project…`
I think tell project home would more helpful,

I have a case where I create a virtualenv with pipenv in upper level accidently,
took me over half an hour figure out why pipenv didn't working in currently dir

**Comment by jtratner** [comment]
Does either setting PIPENV_VENV_IN_PROJECT=1 or “pipenv --venv” cover what
you’re describing?

**Comment by kennethreitz** [comment]
$ PIPENV_PIPFILE=/path/to/Pipfile pipenv …
