### ISSUE TITLE
pipenv install -> ModuleNotFoundError: No module named 'chardet'

### ISSUE THREAD

**Issue by ZhukovGreen** [pypa/pipenv#1781]
Running pipenv install inside empty dir gives:
```sh
$ pipenv install
Creating a virtualenv for this project…
Using /usr/bin/python3 (3.6.3) to create virtualenv…
⠋Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/user/.local/share/virtualenvs/temp-3Hlnl3pp/bin/python3
Also creating executable in /home/user/.local/share/virtualenvs/temp-3Hlnl3pp/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/user/.local/share/virtualenvs/temp-3Hlnl3pp
Creating a Pipfile for this project…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
python3.6/dist-packages/pipenv/../pipenv/core.py", line 21, in <module>
    import requests
  File "/usr/local/lib/python3.6/dist-packages/pipenv/../pipenv/../requests/__init__.py", line 44, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'
```

##### Expected result

No error message

##### Actual result

```sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py", line 75, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py", line 30, in main
    import pipenv.core
  File "/usr/local/lib/python3.6/dist-packages/pipenv/../pipenv/core.py", line 21, in <module>
    import requests
  File "/usr/local/lib/python3.6/dist-packages/pipenv/../pipenv/../requests/__init__.py", line 44, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'
```

##### Steps to replicate

Inside new dir `pipenv install`

Please run `$ python -m pipenv.help`, and paste the results here.

<details><summary>$ python -m pipenv.help output</summary>
Pipenv version: `'11.8.0'`

Pipenv location: `'/usr/local/lib/python3.6/dist-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.14`: `/usr/bin/python`
  - `2.7.14`: `/usr/bin/python2`
  - `3.6.3`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.13.0-37-generic',
 'platform_system': 'Linux',
 'platform_version': '#42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018',
 'python_full_version': '3.6.3',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `COLORFGBG`
  - `COLORTERM`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DEFAULTS_PATH`
  - `DESKTOP_SESSION`
  - `DISPLAY`
  - `GDMSESSION`
  - `GDM_LANG`
  - `HOME`
  - `KONSOLE_DBUS_SERVICE`
  - `KONSOLE_DBUS_SESSION`
  - `KONSOLE_DBUS_WINDOW`
  - `KONSOLE_PROFILE_NAME`
  - `LANG`
  - `LANGUAGE`
  - `LC_ADDRESS`
  - `LC_IDENTIFICATION`
  - `LC_MEASUREMENT`
  - `LC_MONETARY`
  - `LC_NAME`
  - `LC_NUMERIC`
  - `LC_PAPER`
  - `LC_TELEPHONE`
  - `LC_TIME`
  - `LOGNAME`
  - `MANDATORY_PATH`
  - `PAPERSIZE`
  - `PATH`
  - `PROFILEHOME`
  - `PWD`
  - `SHELL`
  - `SHELL_SESSION_ID`
  - `SHLVL`
  - `SSH_AGENT_PID`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `USER`
  - `WINDOWID`
  - `XAUTHORITY`
  - `XDG_CONFIG_DIRS`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_DATA_DIRS`
  - `XDG_GREETER_DATA_DIR`
  - `XDG_RUNTIME_DIR`
  - `XDG_SEAT`
  - `XDG_SEAT_PATH`
  - `XDG_SESSION_DESKTOP`
  - `XDG_SESSION_ID`
  - `XDG_SESSION_PATH`
  - `XDG_SESSION_TYPE`
  - `XDG_VTNR`
  - `OLDPWD`
  - `ZSH`
  - `PAGER`
  - `LESS`
  - `LC_CTYPE`
  - `LSCOLORS`
  - `LS_COLORS`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `ZSH_TMUX_TERM`
  - `_ZSH_TMUX_FIXED_CONFIG`
  - `EDITOR`
  - `_`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/zhukovgreen/bin:/usr/local/bin:/home/zhukovgreen/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `EDITOR`: `nvim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/zhukovgreen/temp`

---------------------------

Contents of `Pipfile` ('/home/zhukovgreen/temp/Pipfile'):

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]



[dev-packages]



[requires]

python_version = "3.6"

```

**Comment by kennethreitz** [comment]
cannot reproduce

**Comment by ZhukovGreen** [comment]
This somehow linked with the way I installed the pipenv. If I installing the pipenv with `pip install --user pipenv`, then no issues

**Comment by LucianLiu6** [comment]
I update the pipenv by `pip3 install -U pipenv` and solve the problem...  
Before update, my pipenv version was `11.9.0`, and now it is `pipenv, version 2018.05.18`

**Comment by djangorobert** [comment]
if you use windows7 make sure to open command prompt with administrator then run commands.
