### ISSUE TITLE
Pipenv has unversioned dependency of Pipfile

### ISSUE THREAD

**Issue by dvf** [pypa/pipenv#1789]
The [vendor](https://github.com/pypa/pipenv/tree/master/pipenv/vendor) folder contains a copy of [pipfile](https://github.com/pypa/pipfile).

But it looks like the [pipfile](https://github.com/pypa/pipfile) repo is outdated, for example https://github.com/pypa/pipfile/blob/master/pipfile/api.py#L129-L141 doesn't appear in the `vendor` folder version.

This makes things difficult:
- Any commit to `vendor/pipfile` needs to be mirrored in the other repository
- Tests seem to reside in the `pipenv` repository, and not the `pipfile` repository

Is there any reason why we don't just reference [pipfile](https://github.com/pypa/pipfile) as a dependency in `pipenv`?

**Comment by kennethreitz** [comment]
pipfile isn't finalized yet.
