### ISSUE TITLE
SSL Error when locking

### ISSUE THREAD

**Issue by gerdek** [pypa/pipenv#1800]
read and tried proposed solutions in #1717 but to no avail, running pipenv 11.8.3.

When attempting to run `pipenv lock` or any command dependent on `pipenv lock` (pipenv install etc) I am getting an SSLError `requests.exceptions.SSLError: [Errno 2] No such file or directory`. 

Following instructions listed in #1717:
```
c:\code\relevant_assets (master -> origin)
λ cd c:\Users\gerritd\AppData\Roaming\Python\Python36\site-packages\
λ c:\Python27\python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pipenv
>>> from pipenv.vendor.pip9._vendor.requests.certs import where
>>> print(where())
pipenv\vendor\pip9\_vendor\requests\cacert.pem
```

Output of python -m pipenv.help output:

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.8.3'`

Pipenv location: `'c:\\Users\\gerritd\\AppData\\Roaming\\Python\\Python36\\site-packages\\pipenv'`

Python location: `'C:\\Users\\gerritd\\AppData\\Local\\Continuum\\anaconda3\\python.exe'`

Other Python installations in `PATH`:

  - `3.6`: `C:\Users\gerritd\AppData\Local\Continuum\anaconda3\python.exe`

  - `3.6.4`: `C:\Users\gerritd\AppData\Local\Continuum\anaconda3\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.15063',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALIASES`
  - `ALLUSERSPROFILE`
  - `ANSICON`
  - `ANSICON_DEF`
  - `APPDATA`
  - `ARCHITECTURE`
  - `CMDER_ROOT`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `CONEMUANSI`
  - `CONEMUANSILOG`
  - `CONEMUARGS`
  - `CONEMUARGS2`
  - `CONEMUBACKHWND`
  - `CONEMUBASEDIR`
  - `CONEMUBASEDIRSHORT`
  - `CONEMUBUILD`
  - `CONEMUCFGDIR`
  - `CONEMUCONFIG`
  - `CONEMUDIR`
  - `CONEMUDRAWHWND`
  - `CONEMUDRIVE`
  - `CONEMUHOOKS`
  - `CONEMUHWND`
  - `CONEMUPALETTE`
  - `CONEMUPID`
  - `CONEMUSERVERPID`
  - `CONEMUTASK`
  - `CONEMUWORKDIR`
  - `CONEMUWORKDRIVE`
  - `GIT_INSTALL_ROOT`
  - `HOME`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PLINK_PROTOCOL`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PTI_HOST`
  - `PUBLIC`
  - `SESSIONNAME`
  - `SNFILESERVER`
  - `SNOW_AGENT`
  - `SVN_SSH`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TERM`
  - `TMP`
  - `UATDATA`
  - `USER-ALIASES`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VERBOSE-OUTPUT`
  - `WINDIR`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `C:\Users\gerritd\AppData\Local\Continuum\anaconda3\Library\bin;C:\Users\gerritd\Portable\cmder\bin;C:\Users\gerritd\Portable\cmder\vendor\git-for-windows\cmd;C:\Users\gerritd\Portable\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Users\gerritd\Portable\cmder\vendor\conemu-maximus5;C:\Users\gerritd\Portable\cmder\vendor\conemu-maximus5\ConEmu;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Enterprise Vault\EVClient\;C:\Users\gerritd\AppData\Roaming\Python\Python36\Scripts;C:\Users\gerritd\AppData\Local\Continuum\anaconda3;C:\Users\gerritd\AppData\Local\Continuum\anaconda3\Scripts;;C:\Users\gerritd\Portable\cmder\vendor\git-for-windows\usr\bin;C:\Users\gerritd\Portable\cmder\vendor\git-for-windows\usr\share\vim\vim74;C:\Users\gerritd\Portable\cmder\`

---------------------------

</details>

------------

##### Expected result
successful completion of `pipenv lock`

##### Actual result
pipenv lock --verbose

<details><summary>$ pipenv lock --verbose</summary>
Locking [dev-packages] dependencies…
Using pip: -i https://pypi.python.org/simple

ROUND 1
Current constraints:
  pytest

Finding the best candidates:
  found candidate pytest==3.4.2 (constraint was <any>)

Finding secondary dependencies:
  pytest==3.4.2             requires attrs>=17.2.0, colorama; sys_platform == "win32"; sys_platform == "win32", pluggy<0.7,>=0.5, py>=1.5.0, setuptools, six>=1.10.0

New dependencies found in this round:
  adding ['attrs', '>=17.2.0', '[]']
  adding ['colorama', '', '[]']
  adding ['pluggy', '<0.7,>=0.5', '[]']
  adding ['py', '>=1.5.0', '[]']
  adding ['six', '>=1.10.0', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  attrs>=17.2.0
  colorama
  pluggy<0.7,>=0.5
  py>=1.5.0
  pytest
  six>=1.10.0

Finding the best candidates:
  found candidate attrs==17.4.0 (constraint was >=17.2.0)
  found candidate colorama==0.3.9 (constraint was <any>)
  found candidate pluggy==0.6.0 (constraint was >=0.5,<0.7)
  found candidate py==1.5.2 (constraint was >=1.5.0)
  found candidate pytest==3.4.2 (constraint was <any>)
  found candidate six==1.11.0 (constraint was >=1.10.0)

Finding secondary dependencies:
  pytest==3.4.2             requires attrs>=17.2.0, colorama; sys_platform == "win32"; sys_platform == "win32", pluggy<0.7,>=0.5, py>=1.5.0, setuptools, six>=1.10.0
  pluggy==0.6.0             requires -
  six==1.11.0               requires -
  py==1.5.2                 requires -
  attrs==17.4.0             requires -
------------------------------------------------------------
Result of round 2: stable, done

INFO:notpip.req.req_set:Collecting colorama==0.3.9
INFO:pip9.download:File was already downloaded c:\users\gerritd\appdata\local\pipenv\pipenv\cache\wheels\colorama-0.3.9-py2.py3-none-any.whl
Traceback (most recent call last):
  File "C:\Users\gerritd\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\requests\packages\urllib3\util\ssl_.py", line 295, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gerritd\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Users\gerritd\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "C:\Users\gerritd\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "C:\Users\gerritd\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "C:\Users\gerritd\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\requests\packages\urllib3\connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "C:\Users\gerritd\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\requests\packages\urllib3\util\ssl_.py", line 297, in ssl_wrap_socket
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\\Users\\gerritd\\AppData\\Roaming\\Python\\Python36\\site-packages\\pipenv\\resolver.py", line 82, in <module>
    main()
  File "C:\\Users\\gerritd\\AppData\\Roaming\\Python\\Python36\\site-packages\\pipenv\\resolver.py", line 71, in main
    clear=do_clear,
  File "C:\\Users\\gerritd\\AppData\\Roaming\\Python\\Python36\\site-packages\\pipenv\\resolver.py", line 63, in resolve
    verbose=verbose,
  File "C:\Users\gerritd\AppData\Roaming\Python\Python36\site-packages\pipenv\utils.py", line 470, in resolve_deps
    timeout=10,
  File "C:\Users\gerritd\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\requests\sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\gerritd\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\gerritd\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\gerritd\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\requests\adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 2] No such file or directory

---------------------------

</details>

------------

##### Steps to replicate
Pipfile: 
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]

numpy = "*"
scipy = "*"
numba = "*"
execnet = "*"

[dev-packages]

pytest = "*"

[requires]

python_version = "3.6"

---------------------

**Comment by gerdek** [comment]
Am on windows, and the path as it stands is not a valid windows path.

There is such a file though at `C:\Users\gerritd\AppData\Roaming\Python\Python36\site-packages\pipenv\vendor\pip9\_vendor\requests` which is probably the target.

**Comment by kennethreitz** [comment]
that actually is a valid path on windows :)

**Comment by DanMcInerney** [comment]
Having same issue. I looked into it and the file /usr/local/lib/python3.6/dist-packages/pipenv/vendor/requests/packages/urllib3/util/ssl_.py is looking for the pem from the variable ca_certs and sets that variable to /usr/local/lib/python3.6/dist-packages/pipenv/vendor/requests/cacert.pem which doesn't exist. 


```
Python 3.6.5rc1 (default, Mar 14 2018, 06:54:23) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pipenv.vendor.pip9._vendor.requests.certs import where
>>> print(where())
/etc/ssl/certs/ca-certificates.crt
```

**Comment by gerdek** [comment]
Confirming that this works in the unreleased version currently on the master branch.

**Comment by morenoh149** [comment]
so it's the inverse, for me I uninstalled via brew and reinstalled

**Comment by Mahdi-Hosseinali** [comment]
I'm using ubuntu:20.04 docker and following the [pypi page](https://pypi.org/project/pipenv/), I use `apt-get install pipenv` in my dockerfile. When I tty a bash into the docker and try to install a new library or even update the lock file, I'm getting this error. `pipenv --version` returns `11.9.0` which [seems to belong](https://launchpad.net/ubuntu/+source/pipenv/11.9.0-1) to 2018!
