### ISSUE TITLE
Mac brew installed pipenv doesn't appear to use default/global pyenv's python.

### ISSUE THREAD

**Issue by flamingbear** [pypa/pipenv#1827]
_Note:  After looking at a lot of the answers, I half expect to be told my paths are wrong, but I'd be interested in how that should be fixed as well._

```
 $ echo $PATH
/Users/savoie/.pyenv/shims:/Users/savoie/.pyenv/bin:/Users/savoie/.rbenv/shims:/Users/savoie/.rbenv/bin:/Users/savoie/.nvm/versions/node/v8.9.0/bin:/usr/local/bin:/Users/savoie/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```
Be sure to check the existing issues (both open and closed!). ✅ 

Describe the issue briefly here.

When I start a new project with no Pipfile or Pipfile.lock in a directory, pipenv is using an included python 3.6 to create my virtual environment.

Please run `$ python -m pipenv.help`, and paste the results here.

I'm using brew installed pipenv so the output is: 
`/Users/savoie/.pyenv/versions/2.7.14/bin/python: No module named pipenv`

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.9.0'`

Pipenv location: `'pipenv'`

Python location: `'/Users/savoie/.pyenv/versions/2.7.14/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/Users/savoie/.pyenv/versions/2.7.14/bin/python2.7`
  - `2.7`: `/Users/savoie/.pyenv/versions/2.7.14/bin/python2.7`
  - `2.7`: `/Users/savoie/.pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/Users/savoie/.pyenv/shims/python3.5`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/Users/savoie/.pyenv/shims/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `2.7.14`: `/Users/savoie/.pyenv/versions/2.7.14/bin/python`
  - `2.7.14`: `/Users/savoie/.pyenv/shims/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.14`: `/Users/savoie/.pyenv/versions/2.7.14/bin/python2`
  - `2.7.14`: `/Users/savoie/.pyenv/shims/python2`
  - `None`: `/Users/savoie/.pyenv/shims/python3`
  - `3.6.4`: `/usr/local/bin/python3`
  - `3.6.4`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.4.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64',
 'python_full_version': '2.7.14',
 'python_version': '2.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `GIT_PS1_SHOWDIRTYSTATE`
  - `NVM_CD_FLAGS`
  - `TERM_PROGRAM_VERSION`
  - `PYENV_DIR`
  - `LOGNAME`
  - `USER`
  - `NVM_DIR`
  - `HOME`
  - `PATH`
  - `PYTHONUNBUFFERED`
  - `DISPLAY`
  - `TERM_PROGRAM`
  - `LANG`
  - `NVM_BIN`
  - `TERM`
  - `SHELL`
  - `COLORFGBG`
  - `PYENV_SHELL`
  - `GIT_PS1_SHOWSTASHSTATE`
  - `SHLVL`
  - `ITERM_SESSION_ID`
  - `XPC_FLAGS`
  - `CLICOLORS`
  - `GIT_PS1_SHOWUPSTREAM`
  - `RBENV_SHELL`
  - `PYENV_VERSION`
  - `EDITOR`
  - `GIT_PS1_SHOWCOLORHINTS`
  - `TERM_SESSION_ID`
  - `XPC_SERVICE_NAME`
  - `SSH_AUTH_SOCK`
  - `IDL_STARTUP`
  - `Apple_PubSub_Socket_Render`
  - `PIP_PYTHON_PATH`
  - `BUILD`
  - `ITERM_PROFILE`
  - `LC_ALL`
  - `PYTHONDONTWRITEBYTECODE`
  - `TMPDIR`
  - `PYENV_HOOK_PATH`
  - `EMACS_HOME`
  - `PYENV_ROOT`
  - `__CF_USER_TEXT_ENCODING`
  - `PWD`
  - `COLORTERM`
  - `GIT_EDITOR`

```
Traceback (most recent call last):
  File "/Users/savoie/.pyenv/versions/2.7.14/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/savoie/.pyenv/versions/2.7.14/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/Cellar/pipenv/11.9.0/libexec/lib/python3.6/site-packages/pipenv/help.py", line 90, in <module>
    main()
  File "/usr/local/Cellar/pipenv/11.9.0/libexec/lib/python3.6/site-packages/pipenv/help.py", line 49, in main
    print(u'Pipenv–specific environment variables:')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 6: ordinal not in range(128)
```

------------

##### Expected result

I expect that when I do a `pipenv install package`, I would get a virutal environment build using my default python.

##### Actual result

The included python 3.6 is used as the default python and the resulting Pipfile also has 3.6 in the requires.

Resulting Pipfile
```
 $ cat Pipfile
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = "*"

[dev-packages]

[requires]
python_version = "3.6"
```
##### Steps to replicate

```sh
$ pyenv version
2.7.14 (set by /Users/savoie/.pyenv/version)
savoie@nsidc-msavoie ~/tmp/pipenvtests/wat
 $ python --version
Python 2.7.14
savoie@nsidc-msavoie ~/tmp/pipenvtests/wat
 $ pipenv install requests
Creating a virtualenv for this project…
Using /usr/local/Cellar/pipenv/11.9.0/libexec/bin/python3.6 (3.6.4) to create virtualenv…
⠋Already using interpreter /usr/local/Cellar/pipenv/11.9.0/libexec/bin/python3.6
Using real prefix '/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/savoie/.local/share/virtualenvs/wat-Knii1XaF/bin/python3.6
Also creating executable in /Users/savoie/.local/share/virtualenvs/wat-Knii1XaF/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/savoie/.local/share/virtualenvs/wat-Knii1XaF
Creating a Pipfile for this project…
```

**Comment by uranusjr** [comment]
First of all, your PATH is fine. :p

Pipenv by default uses *the Python it is installed against* to create the virtualenv, not the first one in your PATH (as you might expect). In your case it is using Homebrew’s `python3` executable (I would expect).

To change the default and make it use your pyenv’s default Python, set the environment variable `PIPENV_PYTHON` to `$HOME/.pyenv/shims/python`.
