### ISSUE TITLE
Can't specify miniconda python on commandline when installing packages. (mac brew)

### ISSUE THREAD

**Issue by flamingbear** [pypa/pipenv#1828]
Be sure to check the existing issues (both open and closed!). ✅ 

I'd like to use a pyenv installed version of miniconda as my virtualenv python. 
ala: `pipenv --python miniconda3-4.3.30 `

Please run `$ python -m pipenv.help`, and paste the results here.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.9.0'`

Pipenv location: `'/usr/local/Cellar/pipenv/11.9.0/libexec/lib/python3.6/site-packages/pipenv'`

Python location: `'/Users/savoie/.pyenv/versions/miniconda3-4.3.30/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/Users/savoie/.pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/Users/savoie/.pyenv/shims/python3.5`
  - `3.6`: `/Users/savoie/.pyenv/versions/miniconda3-4.3.30/bin/python3.6m`
  - `3.6`: `/Users/savoie/.pyenv/versions/miniconda3-4.3.30/bin/python3.6`
  - `3.6`: `/Users/savoie/.pyenv/shims/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `3.6.3`: `/Users/savoie/.pyenv/versions/miniconda3-4.3.30/bin/python`
  - `3.6.3`: `/Users/savoie/.pyenv/shims/python`
  - `2.7.10`: `/usr/bin/python`
  - `None`: `/Users/savoie/.pyenv/shims/python2`
  - `3.6.3`: `/Users/savoie/.pyenv/versions/miniconda3-4.3.30/bin/python3`
  - `3.6.3`: `/Users/savoie/.pyenv/shims/python3`
  - `3.6.4`: `/usr/local/bin/python3`
  - `3.6.4`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.4.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST '
                     '2017; root:xnu-4570.41.2~1/RELEASE_X86_64',
 'python_full_version': '3.6.3',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `GIT_PS1_SHOWDIRTYSTATE`
  - `TERM_PROGRAM`
  - `NVM_CD_FLAGS`
  - `PYENV_ROOT`
  - `SHELL`
  - `TERM`
  - `IDL_STARTUP`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `GIT_PS1_SHOWCOLORHINTS`
  - `PYENV_VERSION`
  - `LC_ALL`
  - `GIT_EDITOR`
  - `USER`
  - `NVM_DIR`
  - `SSH_AUTH_SOCK`
  - `CLICOLORS`
  - `PYENV_DIR`
  - `__CF_USER_TEXT_ENCODING`
  - `PATH`
  - `BUILD`
  - `PWD`
  - `EMACS_HOME`
  - `EDITOR`
  - `LANG`
  - `ITERM_PROFILE`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `RBENV_SHELL`
  - `XPC_SERVICE_NAME`
  - `COLORFGBG`
  - `HOME`
  - `SHLVL`
  - `PYENV_SHELL`
  - `GIT_PS1_SHOWSTASHSTATE`
  - `ITERM_SESSION_ID`
  - `LOGNAME`
  - `GIT_PS1_SHOWUPSTREAM`
  - `NVM_BIN`
  - `DISPLAY`
  - `COLORTERM`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/savoie/.pyenv/versions/miniconda3-4.3.30/bin:/Users/savoie/.pyenv/libexec:/Users/savoie/.pyenv/plugins/python-build/bin:/Users/savoie/.pyenv/shims:/Users/savoie/.pyenv/bin:/Users/savoie/.rbenv/shims:/Users/savoie/.rbenv/bin:/Users/savoie/.nvm/versions/node/v8.9.0/bin:/usr/local/bin:/Users/savoie/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `emacsclient`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/usr/local/Cellar/pipenv/11.9.0/libexec/lib/python3.6/site-packages`

---------------------------

</details>

------------

##### Expected result

I expect that I would get an virtual environment build that matches the specified python.
for example when I ask for a 2.7 python.

```
 $ pipenv --python 2.7
Creating a virtualenv for this project…
Using /Users/savoie/.pyenv/versions/2.7.14/bin/python2.7 (2.7.14) to create virtualenv…
⠋Running virtualenv with interpreter /Users/savoie/.pyenv/versions/2.7.14/bin/python2.7
New python executable in /Users/savoie/.local/share/virtualenvs/condatest-kJNOufxs/bin/python2.7
Also creating executable in /Users/savoie/.local/share/virtualenvs/condatest-kJNOufxs/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/savoie/.local/share/virtualenvs/condatest-kJNOufxs
```

##### Actual result

Actual result, is that it can't find the installed miniconda python, asks if I would like to install it, and then says it can't find it on my path.

```
$ pipenv --python miniconda3-4.3.30
Warning: Python miniconda3-4.3.30 was not found on your system…
Would you like us to install CPython miniconda3-4.3.30 with pyenv? [Y/n]: Y
Installing CPython miniconda3-4.3.30 with pyenv (this may take a few minutes)…
⠋
Warning: The Python you just installed is not available on your PATH, apparently.
savoie@nsidc-msavoie ~/tmp/pipenvtests/condatest
```

##### Steps to replicate

See above, but install miniconda3-4.30 into you pyenv first.

**Comment by jtratner** [comment]
Does `pyenv local miniconda3-4.3.30` work? (And then just typing python
after that ends you up with miniconda3 interpreter?)

**Comment by uranusjr** [comment]
`--python` only supports CPython version numbers. For anything else you’ll need to pass the full path to the executable. Or use the combination of `pyenv local` (or `pyenv global`) and #1827 to delegate the interpreter selection to pyenv’s shims.

**Comment by flamingbear** [comment]
Thanks @uranusjr those were both fast and helpful answers.
