### ISSUE TITLE
Minimum requirements from pipenv

### ISSUE THREAD

**Issue by etano** [pypa/pipenv#1831]
Is it possible to get the minimum requirements of a pipenv project?

I know we can generate a requirements.txt, but it will always fix the requirements to what is currently installed.

Instead I want the absolute minimum versions of every library necessary, given the pipenv graph.

**Comment by techalchemy** [comment]
Hi @etano thanks for the report -- no, that is not currently possible and I suspect @ncoghlan would have some words to say about this particular issue

**Comment by etano** [comment]
In the meantime, I made a dumb script to do it:

`def min_version(x):
    if '>' in x:
        gi = re.search('>', x)
        x = x[gi.end():]
        ni = re.search('\d', x)
        x = x[ni.start():]
        x = x.split(',')[0]
        return x
    else:
        return '0'

def compare_versions(a, b):
    min_a = min_version(a)
    min_b = min_version(b)
    min_a = [int(x) for x in min_a.split('.')]
    min_b = [int(x) for x in min_b.split('.')]
    return min_b > min_a

requirements = {}
for line in graph_txt.split('\n'):
    if "[" not in line:
        ci = re.search('>|=|<', line)
        package = line[:ci.start()]
        version = line[ci.start():]
    else:
        line = line.split()
        package = line[1]
        version = line[3][:-1]
    if version == 'Any':
        version = ''
    package = package.lower()
    if package in requirements:
        old_version = requirements[package]
        if compare_versions(old_version, version):
            requirements[package] = version
    else:
        requirements[package] = version
for package, version in sorted(requirements.iteritems()):
    print package+version.replace('==', '>=')`

You just put the output of `pipenv graph` into graph_txt.

**Comment by techalchemy** [comment]
@etano is this meant to be the best compatible version from the dependency graph? I'm not sure what your goal is from this

**Comment by etano** [comment]
The goal is the get the minimum version required of every dependency, while still satisfying the dependency graph.

**Comment by techalchemy** [comment]
@etano can I ask why you want the minimum?

**Comment by etano** [comment]
It's to avoid upgrading dependencies when we don't have to.

We have lots of packages with shared dependencies, and if we don't have to upgrade those dependencies every time we update a package, it is preferred.

**Comment by techalchemy** [comment]
From https://docs.pipenv.org/#cmdoption-pipenv-install-keep-outdated

**--keep-outdated**
   _Keep out–dated dependencies from being updated in Pipfile.lock._

**--selective-upgrade**
   _Update specified packages._

**Comment by ncoghlan** [comment]
This definitely sounds like the use case that `pipenv lock --keep-outdated` is intended to cover, assuming that you have an existing `Pipenv.lock` that sets your baseline requirements. (However, see https://github.com/pypa/pipenv/issues/966#issuecomment-374559333 for an issue report on `--selective-upgrade` misbehaving in at least some cases).

Not contributing to OWASP A9 (folks running outdated known-vulnerable components) is a design goal for `pipenv` though, so I'd consider deliberately backdating a version snapshot to be out of scope, and am hence closing this (`--keep-outdated` covers the part of the requested functionality that's in scope, while #966 remains open to cover any current implementation bugs in that feature).

Note that if someone really wanted to provide the "lock the minimum compatible versions" as a third party project, a likely workable approach would be:

1. Generate a `requirements.txt` or `Pipfile` with fully pinned versions for the oldest versions that meet the version constraints (`pipenv` can convert `requirements.txt` to `Pipfile`, so it doesn't really matter which format gets generated)
2. Use `pipenv lock` to generate an initial `Pipfile.lock` from that
3. Replace the fully pinned `Pipfile` with your actual `Pipfile`
4. Use `pipenv lock --keep-outdated` from that baseline

I don't think that would be a good idea, but I figured I'd mention the possibility for completeness :)

**Comment by etano** [comment]
Fair enough, thanks!

**Comment by atzannes** [comment]
@etano if you're building a library you should probably be providing requirements through the `setup.py` file, not `requirements.txt`
https://caremad.io/posts/2013/07/setup-vs-requirement/
