### ISSUE TITLE
Built-in Sphinx documentation search index broken (also, search link hard to find)

### ISSUE THREAD

**Issue by WoLpH** [pypa/pipenv#1839]
First of all it's pretty hard to find the search at all in the docs (would be useful in the sidebar) but there is a link at the bottom of the docs homepage: https://docs.pipenv.org/

Which points to this page: https://docs.pipenv.org/search/

Actually searching for something like this: https://docs.pipenv.org/search/?q=test
Results in links like these which only result in 404s: https://docs.pipenv.org/en/latest/advanced?highlight=test

The problem seems to be that the search index uses the standard readthedocs urls containing the versions (`/en/latest/`) instead of using the root. I'm not entirely sure if this bug is restricted to this project's configuration or if it's an upstream bug.

**Comment by frostming** [comment]
The search part seems problematic and is hidden by JS hack.

So it is intentional. Maybe @kennethreitz has some words for it.

**Comment by techalchemy** [comment]
This is fixed

**Comment by WoLpH** [comment]
Are you sure? I've tried a minute ago and it still looks broken to me.

**Comment by techalchemy** [comment]
Searching works fine. Are you complaining about our style sheet?

**Comment by WoLpH** [comment]
Have you actually tried the search and read the original question fully?

All of the search results end up in non-existing (404) pages.

**Comment by RickDB** [comment]
Search result pages all have 404's here as well.

**Comment by techalchemy** [comment]
Ah ok, I didn’t click any of the resulting links. Considering we have it hidden to begin with I’m not that surprised. Not sure what would be required to fix

**Comment by WoLpH** [comment]
I've done some testing by setting up another project on readthedocs with the docs at the root domain and that appears to function fine: http://pipenv-searchable.readthedocs.io/search.html?q=test

So for some reason the search index for this project is broken. Perhaps someone can press the "wipe" button at readthedocs to fix it?

![image](https://user-images.githubusercontent.com/270571/38368879-c652bc08-38e6-11e8-91df-889b8a971650.png)

**Comment by techalchemy** [comment]
@WoLpH I’ll find out who has access and see if I can get it taken care of. Thanks for looking into it!

**Comment by ashnur** [comment]
@techalchemy are you sure? because I just tried, and it didn't work.

**Comment by ashnur** [comment]
Would be really nice if the docs were usable. But they are not. It's more like an essay about how great the authors feel about themselves. If at least one could search in this very popular and ultimately awesome project's documentation, that might salvage the situation somewhat, but when the response to an issue is "it's fixed" because there are no proper tests, I can understand why the situation is as it is. BTW, 51 days since this issue was raised. How come in almost 2 months, this was ignored? Don't you think it's kind of important? Are there even bigger issues with the project that take away time? Or there are no one dedicated working on this project, it's abandoned?

**Comment by gsemet** [comment]
document search is handled by readthedocs and sphinx. It basically uses a full text search with js script that is known to work poorly, but still do the job on very simple words. For more complex use case, alternatives such as https://www.algolia.com/ that does provide a community edition.

**Comment by techalchemy** [comment]
@ashnur kindly take your negativity and go elsewhere. If you have nothing productive to contribute we are not interested in your feedback. Please see the code of conduct and see yourself out. 

The reason search is hidden is because RTD doesn’t support SSL for custom domains and the docs are hosted at python.org as well. You are welcome to go fix this for them, but until then there will continue to be no movement.

**Comment by WoLpH** [comment]
@techalchemy the python.org hosted (I'm assuming you mean through pypi) documentation is deprecated and cannot be updated anymore, if that's the issue I would suggest dropping it

**Comment by techalchemy** [comment]
I don’t. I mean readthedocs.

**Comment by WoLpH** [comment]
Perhaps I misunderstood, can you clarify this statement?

> the docs are hosted at python.org as well

**Comment by techalchemy** [comment]
Oh yeah. Typo. Thanks— I mean readthedocs and _pipenv.org_ which my phone might have autocorrected or I might have subconsciously typed. Been at pycon all weekend

**Comment by brainwane** [comment]
Now that the documentation has moved to https://pipenv.pypa.io/ could people check whether the problem persists? If it still does, then I think Dan & Ernest (purposely not @-mentioning right now) would need to address it.

**Comment by WoLpH** [comment]
@brainwane  It still seems partially broken. Just look at this result: https://pipenv.pypa.io/en/latest/search/?q=requirements
The "Pipenv features" link results in a 404

**Comment by WoLpH** [comment]
Also, I think the "Algolia" search can be disabled now. While that search isn't bad, the built-in Sphinx search is often more useful when it comes to searching code in my experience

**Comment by brainwane** [comment]
@WoLpH Thanks.

I've made PR #4166 to temporarily remove the link to that search till we can fix the index.

@techalchemy can you poke at the settings at http://readthedocs.org/projects/pipenv and see if you can wipe and rebuild the index, or, barring that, the entire site?

**Comment by pradyunsg** [comment]
I've just looked through https://pipenv.pypa.io/en/latest/search/?q=requirements, and it seems to be working fine now.

Reverting https://github.com/pypa/pipenv/pull/3703, to use the basic Sphinx search would be a good fix.

**Comment by pradyunsg** [comment]
> Reverting #3703

I stand corrected -- even that works just fine for me now. :)

**Comment by brainwane** [comment]
I'd love for a maintainer to review #4166.

**Comment by oz123** [comment]
This PR is already merged. Closing the issue.
