### ISSUE TITLE
Support multiple environments 

### ISSUE THREAD

**Issue by peterdemin** [pypa/pipenv#1841]
Hi Kenneth! Check this tool I built: https://github.com/peterdemin/pip-compile-multi
Do you think PipEnv can/should have it's functionality?
I know PipEnv supports separation of dev and prod requirements, but in my projects I have more, like docs, linters, tests and so on.
I also need compatibility with Python 2.7 and 3.4 and can't use 3.6+. 
Here are good examples of such projects:
https://github.com/zulip/zulip/
https://github.com/ansible/awx

**Comment by techalchemy** [comment]
Thanks for the suggestion

This has been discussed in a number of other issues and is out of scope currently, but you should know that we use pip-tools (heavily hacked at this point) to do most of our dependency resolution & have the maintainer on our team.  Your project is well documented and it's clear you care about this stuff -- if you want to have an impact, we have plenty of opportunities for improvement (especially around the resolver)

We aren't likely to implement more kinds of requirements, but are interested in things like flattening the dependency graph to resolve conflicts (we don't currently do this really)

Hope to see you back :) but closing this for now
