### ISSUE TITLE
possible docker build issue

### ISSUE THREAD

**Issue by don-swept** [pypa/pipenv#1859]
In your [Dockerfile](https://github.com/pypa/pipenv/blob/master/Dockerfile) you have `RUN apt update` and `RUN apt install ...` in separate lines. This is not recommended, since docker's caching can cause old versions of your packages to get installed.

From the [docs](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run):
> Always combine RUN apt-get update with apt-get install in the same RUN statement. For example:
> ```
>    RUN apt-get update && apt-get install -y \
>        package-bar \
>        package-baz \
>        package-foo
> ```
> Using apt-get update alone in a RUN statement causes caching issues and subsequent apt-get install instructions fail.

**Comment by techalchemy** [comment]
Ooh I didn’t realize we are using apt instead of apt get to begin with. That’s fascinating about the caching issues, do you have any idea as to why? Would be happy to accept a PR

**Comment by don-swept** [comment]
i think the basic idea is that the result of each line is cached, so if you have a cached `apt update` from last week, and then add some new packages to the `apt install` line,  you might get the versions from an older apt repository. probably not a crucial thing here, but i'll put up a PR. also, as you mentioned, `apt-get` might be better for scripts -- you get a warning about it when you run `docker build`

**Comment by don-swept** [comment]
well, the build blew up! the docker build works fine locally. maybe it's because there are 0 code changes, so most of the tests aren't running...
