### ISSUE TITLE
Creating a virtualenv fails on Windows when user name starts with a dollar character

### ISSUE THREAD

**Issue by philosophicles** [pypa/pipenv#1868]
Pipenv seems to be unable to create a virtualenv on Windows when the current user's username starts with a dollar character: `$johndoe` in the results below.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.9.0'`

Pipenv location: `'C:\\Program Files\\Python36\\lib\\site-packages\\pipenv'`

Python location: `'C:\\Program Files\\Python36\\python.exe'`

Other Python installations in `PATH`:

  - `3.6`: `C:\Program Files\Python36\python.exe`

  - `3.6.4`: `C:\Program Files\Python36\python.exe`
  - `3.6.4`: `C:\Windows\py.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
'implementation_version': '3.6.4',
'os_name': 'nt',
'platform_machine': 'AMD64',
'platform_python_implementation': 'CPython',
'platform_release': '10',
'platform_system': 'Windows',
'platform_version': '10.0.14393',
'python_full_version': '3.6.4',
'python_version': '3.6',
'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `UATDATA`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `WINDIR`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\$johndoe\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin`

---------------------------

Contents of `Pipfile` ('C:\\!DRSYSTEM\\Scripts\\project_folder\\Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = "*"

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('C:\\!DRSYSTEM\\Scripts\\project_folder\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "33a0ec7c8e3bae6f62dd618f847de92ece20e2bd4efb496927e2524b9c7b8df8"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "certifi": {
            "hashes": [
                "sha256:14131608ad2fd56836d33a71ee60fa1c82bc9d2c8d98b7bdbc631fe1b3cd1296",
                "sha256:edbc3f203427eef571f79a7692bb160a2b0f7ccaa31953e99bd17e307cf63f7d"
            ],
            "version": "==2018.1.18"
        },
        "chardet": {
            "hashes": [
                "sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae",
                "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691"
            ],
            "version": "==3.0.4"
        },
        "idna": {
            "hashes": [
                "sha256:2c6a5de3089009e3da7c5dde64a141dbc8551d5b7f6cf4ed7c2568d0cc520a8f",
                "sha256:8c7309c718f94b3a625cb648ace320157ad16ff131ae0af362c9f21b80ef6ec4"
            ],
            "version": "==2.6"
        },
        "requests": {
            "hashes": [
                "sha256:6a1b267aa90cac58ac3a765d067950e7dbbf75b1da07e895d1f594193a40a38b",
                "sha256:9c443e7324ba5b85070c4a818ade28bfabedf16ea10206da1132edaa6dda237e"
            ],
            "index": "pypi",
            "version": "==2.18.4"
        },
        "urllib3": {
            "hashes": [
                "sha256:06330f386d6e4b195fbfc736b297f58c5a892e4440e54d294d7004e3a9bbea1b",
                "sha256:cc44da8e1145637334317feebd728bd869a35285b93cbb4cca2577da7e62db4f"
            ],
            "version": "==1.22"
        }
    },
    "develop": {}
}

```
</details>

------------

##### Expected result

Running `pipenv install` in a project folder should create a virtualenv for that project, as well as setting up Pipfile etc.

##### Actual result

Pipfile and Pipfile.lock are created as expect. Creating the virtualenv fails. I didn't actually notice this properly until I came to run `pipenv shell` which found no existing virtualenv, so tried again to create a virtualenv, and failed.

I've changed the actual `project_folder` and username `$johndoe` for privacy/security reasons but the username was still prefixed with a dollar character `$` followed by only lowercase a-z characters. The project folder was a mix of lowercase a-z characters and a space.

```
c:\!DRSYSTEM\Scripts\project_folder>pipenv shell
Creating a virtualenv for this project…
Using C:\Program Files\Python36\python.exe (3.6.4) to create virtualenv…
Running virtualenv with interpreter C:\Program Files\Python36\python.exe
Using base prefix 'C:\\Program Files\\Python36'
New python executable in C:\Users\$johndoe\.virtualenvs\project_folder--vi7V_1k\Scripts\python.exe
Installing setuptools, pip, wheel...
  Complete output from command C:\Users\$johndoe\.vir...k\Scripts\python.exe - setuptools pip wheel:
  Collecting setuptools
Collecting pip
Collecting wheel
Installing collected packages: setuptools, pip, wheel
Exception:
Traceback (most recent call last):
  File "C:\Program Files\Python36\Lib\distutils\util.py", line 202, in subst_vars
    return re.sub(r'\$([a-zA-Z_][a-zA-Z_0-9]*)', _subst, s)
  File "C:\Users\$johndoe\.virtualenvs\project_folder--vi7V_1k\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Program Files\Python36\Lib\distutils\util.py", line 199, in _subst
    return os.environ[var_name]
  File "C:\Users\$johndoe\.virtualenvs\project_folder--vi7V_1k\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'johndoe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\virtualenv_support\pip-9.0.3-py2.py3-none-any.whl\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\virtualenv_support\pip-9.0.3-py2.py3-none-any.whl\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files\python36\lib\site-packages\virtualenv_support\pip-9.0.3-py2.py3-none-any.whl\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files\python36\lib\site-packages\virtualenv_support\pip-9.0.3-py2.py3-none-any.whl\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\program files\python36\lib\site-packages\virtualenv_support\pip-9.0.3-py2.py3-none-any.whl\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "c:\program files\python36\lib\site-packages\virtualenv_support\pip-9.0.3-py2.py3-none-any.whl\pip\wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "c:\program files\python36\lib\site-packages\virtualenv_support\pip-9.0.3-py2.py3-none-any.whl\pip\locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "C:\Program Files\Python36\Lib\distutils\command\install.py", line 307, in finalize_options
    self.expand_basedirs()
  File "C:\Program Files\Python36\Lib\distutils\command\install.py", line 475, in expand_basedirs
    self._expand_attrs(['install_base', 'install_platbase', 'root'])
  File "C:\Program Files\Python36\Lib\distutils\command\install.py", line 469, in _expand_attrs
    val = subst_vars(val, self.config_vars)
  File "C:\Program Files\Python36\Lib\distutils\util.py", line 204, in subst_vars
    raise ValueError("invalid variable '$%s'" % var)
ValueError: invalid variable '$'johndoe''
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\virtualenv.py", line 2349, in <module>
    main()
  File "c:\program files\python36\lib\site-packages\virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "c:\program files\python36\lib\site-packages\virtualenv.py", line 953, in create_environment
    download=download,
  File "c:\program files\python36\lib\site-packages\virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "c:\program files\python36\lib\site-packages\virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\$johndoe\.vir...k\Scripts\python.exe - setuptools pip wheel failed with error code 2

Virtualenv location:
ERROR: Environment 'project_folder--vi7V_1k' does not exist. Create it with 'pew new project_folder--vi7V_1k'.

c:\!DRSYSTEM\Scripts\project_folder>
```

##### Steps to replicate

1. On Windows, create a user account that starts with a dollar character `$` and log in as that user.
1. Create a new folder somewhere on C: drive for your python development project. (Not necessarily within user folder, it seems.)
1. Open cmd.exe with Administrator privileges, `cd` to the project folder.
1. Run `pipenv install`, or `pipenv shell`, or any command that should check for an existing virtualenv and create if it doesn't already exist.

Repeat with another Windows user account that is identical except for the leading `$` character: pipenv works as expected.

**Comment by uranusjr** [comment]
Does bare virtualenv works? Judging from the traceback it is not Pipenv failing, but virtualenv. Try running this command in the user folder and see what happens:

```
> "C:\Program Files\Python36\python.exe" -m virtualenv anything
```

**Comment by philosophicles** [comment]
Apologies, you are completely right. virtualenv produces fundamentally the same error. I'll go raise it to that project.

**Comment by philosophicles** [comment]
For the benefit of any future visitors to this issue, please note it turns out that `virtualenv` seems to have problems with practically any characters other than [A-Za-z0-9], at the time of writing. 

For example, see:
https://github.com/pypa/virtualenv/issues/457
https://github.com/pypa/virtualenv/issues/994
