### ISSUE TITLE
Pipenv misbehaves when installing local packages from Pipfile when .egg directories aren't present

### ISSUE THREAD

**Issue by LegoStormtroopr** [pypa/pipenv#1873]
Unable to correct install packages that are defined locally.
Using pipenv 11.8.3 to target Heroku, so upgrading is hard.

I'm trying to build an application that has quite a few components, and want a Pipfile at the root which installs a bunch of packages that are in a subdirectory, each with a `setup.py`. I'm doing this in editable mode, so I can do development work.

The initial `pipenv install -e ./some-local-package` works fine, but inserts a `.egg` directory, which is ignore by git when committing. If another developer tries to check this code out, without the egg and just runs `pipenv install` or `pipenv lock` pipenv crashes, especially if the lock file (which changes a lot in dev) isn't present.

So if the `.egg` directories are removed (which aren't in source control), pipenv locks fail with an intuitive message.

**So what am I doing wrong?**

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.8.3'`

Pipenv location: `'/usr/local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/bin/python27'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.12`: `/usr/bin/python`
  - `2.7.12`: `/usr/bin/python2`
  - `3.6.2`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.9.70-25.242.amzn1.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Wed Jan 3 05:36:22 UTC 2018',
 'python_full_version': '2.7.12',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `PROMPT_COMMAND`
  - `rvm_version`
  - `NVM_CD_FLAGS`
  - `C9_HOSTNAME`
  - `AWS_PATH`
  - `rvm_path`
  - `PYTHONDONTWRITEBYTECODE`
  - `LESSOPEN`
  - `RUBY_VERSION`
  - `SSH_CLIENT`
  - `CVS_RSH`
  - `LOGNAME`
  - `USER`
  - `NVM_DIR`
  - `HOME`
  - `PATH`
  - `PYTHONUNBUFFERED`
  - `NODE_PATH`
  - `PORT`
  - `SSH_CONNECTION`
  - `LANG`
  - `GEM_PATH`
  - `TERM`
  - `SHELL`
  - `TMUX_PANE`
  - `EC2_AMITOOL_HOME`
  - `LESS_TERMCAP_me`
  - `LESS_TERMCAP_md`
  - `LESS_TERMCAP_mb`
  - `HISTSIZE`
  - `NVM_BIN`
  - `NVM_PATH`
  - `EDITOR`
  - `MANPATH`
  - `IP`
  - `HGUSER`
  - `AWS_ELB_HOME`
  - `JAVA_HOME`
  - `EC2_HOME`
  - `HISTFILESIZE`
  - `rvm_bin_path`
  - `LESS_TERMCAP_se`
  - `rvm_prefix`
  - `C9_PROJECT`
  - `C9_USER`
  - `IRBRC`
  - `TMUX`
  - `_system_type`
  - `MY_RUBY_HOME`
  - `AWS_AUTO_SCALING_HOME`
  - `_system_name`
  - `PIP_PYTHON_PATH`
  - `_`
  - `C9_PID`
  - `LESS_TERMCAP_ue`
  - `_system_arch`
  - `NVM_IOJS_ORG_MIRROR`
  - `AWS_CLOUDWATCH_HOME`
  - `OLDPWD`
  - `HOSTNAME`
  - `GEM_HOME`
  - `HISTCONTROL`
  - `SHLVL`
  - `PWD`
  - `LESS_TERMCAP_us`
  - `ISOUTPUTPANE`
  - `_system_version`
  - `MAIL`
  - `LS_COLORS`
  - `C9_PORT`
  - `PYTHON_INSTALL_LAYOUT`
  - `NVM_NODEJS_ORG_MIRROR`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/ec2-user/.nvm/versions/node/v6.12.3/bin:/usr/local/rvm/gems/ruby-2.4.1/bin:/usr/local/rvm/gems/ruby-2.4.1@global/bin:/usr/local/rvm/rubies/ruby-2.4.1/bin:/usr/local/bin:/bin:/usr/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/opt/aws/bin:/usr/local/rvm/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: ``
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/ec2-user/environment/git/aristotle-cloud/dev`

---------------------------

Contents of `Pipfile` ('/home/ec2-user/environment/git/aristotle-cloud/dev/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
aristotle-metadata-registry = {editable = true, path = "../../aristotle-metadata-registry/python/aristotle-metadata-registry/"}

[requires]
python_version = "3.6"

```

</details>

------------

##### Expected result

A lock file is generated

##### Actual result

```
Creating a virtualenv for this project…
Using /usr/local/bin/python3.6m (3.6.4) to create virtualenv…
Running virtualenv with interpreter /usr/local/bin/python3.6m
Using base prefix '/usr/local'
New python executable in /root/.local/share/virtualenvs/dev-mLGR0Vyd/bin/python3.6m
Also creating executable in /root/.local/share/virtualenvs/dev-mLGR0Vyd/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /root/.local/share/virtualenvs/dev-mLGR0Vyd
Locking [dev-packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1                           
Current constraints:

Finding the best candidates:

Finding secondary dependencies:
------------------------------------------------------------
Result of round 1: stable, done

Locking [packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1                           
Current constraints:
  file:///usr/src/app/aristotle-metadata-registry/python/aristotle-metadata-registry

Finding the best candidates:
  found candidate -e file:///usr/src/app/aristotle-metadata-registry/python/aristotle-metadata-registry (constraint was <any>)

Finding secondary dependencies:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pipenv/resolver.py", line 82, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/pipenv/resolver.py", line 71, in main
    clear=do_clear,
  File "/usr/local/lib/python3.6/site-packages/pipenv/resolver.py", line 63, in resolve
    verbose=verbose,
  File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 425, in resolve_deps
    pre,
  File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 336, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 275, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 174, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 193, in get_legacy_dependencies
    dist = ireq.get_dist()
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pip9/req/req_install.py", line 1069, in get_dist
    egg_info = self.egg_info_path('').rstrip('/')
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pip9/req/req_install.py", line 515, in egg_info_path
    'No files/directories in %s (from %s)' % (base, filename)
pip9.exceptions.InstallationError: No files/directories in /usr/src/app/aristotle-metadata-registry/python/aristotle-metadata-registry (from )
```

##### Steps to replicate

```
mkdir tmp && cd tmp
git clone https://github.com/aristotle-mdr/aristotle-metadata-registry
pipenv install -e ./aristotle-metadata-registry/python/aristotle-metadata-registry
rm ./aristotle-metadata-registry/python/aristotle-metadata-registry/aristotle_metadata_registry.egg-info -rf
rm Pipfile.lock
pipenv --rm && pipenv install
ls ./aristotle-metadata-registry/python/aristotle-metadata-registry/
```

**Comment by frostming** [comment]
This happens when pipenv tries locking the dependencies. I never caught this because `Pipfile.lock` is usually in version control.

**Comment by uranusjr** [comment]
`pipenv install` would work, however. Whatever install does specially to an editable package, lock should probably do it as well.

**Comment by techalchemy** [comment]
This is fixed in master I believe ? Can someone check?

**Comment by frostming** [comment]
@uranusjr because resolver needs egg info and install creates that. However bare `lock` will fail, on master.

**Comment by frostming** [comment]
Yes `pipenv install` works with master branch

**Comment by techalchemy** [comment]
`pipenv install` from a pipfile using an egg directory was fixed in #1812 and #1815. As far as if you are starting from no environment with a copy of a lockfile, I’m not really sure of the use case for running `pipenv lock` without installing first. Thanks for the report, closing for now!

**Comment by LegoStormtroopr** [comment]
Thanks for the response!
I'll see if I can submit a PR for Heroku to upgrade too.

**Comment by techalchemy** [comment]
@LegoStormtroopr haven't cut a release yet -- just got testing infrastructure working

**Comment by LegoStormtroopr** [comment]
I just want to jump back to @techalchemy 's question:
> I’m not really sure of the use case for running pipenv lock without installing first

The reason I see this happening is that often I'll create my own pipenv files or edit them after they've been created - which given that they are text files, I'm guessing is ok. So

If you don't have a lock file, doing a `pipenv install` with just a Pipfile will force it to try and lock it, and when nothing has been previously installed, it fails.

**Comment by techalchemy** [comment]
@LegoStormtroopr having had an opportunity to mull this over I’m much more certain about this now anyway. It seems valid to me, we could hide the internals if necessary

**Comment by gsemet** [comment]
looks like it can happen without corrupted lock file (see the PR gsemet/pipenv-to-requirements#4)
