### ISSUE TITLE
Pipenv and coverage don't play nice

### ISSUE THREAD

**Issue by Galithil** [pypa/pipenv#1876]
I am trying to run the tests from a Django projects on circleci and get information on code coverage, via coverage.py. 
The Django documentation recommends using pipenv (https://github.com/CircleCI-Public/circleci-demo-python-django/blob/master/.circleci/config.yml#L32). 
When using pipenv, the coverage file is empty, while coverage works fine without pipenv. this behaviour is identical on MacOS, using anaconda's python.

Results of  `python -m pipenv.help` : https://pastebin.com/0j8pnQRR

Command being run : 
`pipenv run "coverage run --timid --source='/Users/Me/PycharmProjects/LimsDashboard/lims_dashboard' manage.py test lims_dashboard.tests.PlasmaPoolingControllerTest.test_print"`

Result : 
`Coverage.py warning: Module '/Users/Me/PycharmProjects/LimsDashboard/lims_dashboard' was never imported. (module-not-imported)
Coverage.py warning: No data was collected. (no-data-collected)`

I tried changing the source to  '.' and to '$(pipenv --venv)' , but to no avail. 

Printing out the module's file path within the tests returns 
`/Users/Me/PycharmProjects/LimsDashboard/lims_dashboard/__init__.pyc`

Does anyone have an idea as to where to look in order to make this work ?

Thanks,

Denis

**Comment by techalchemy** [comment]
I actually don’t have any insight on this, although I know plenty of people are using coverage with pipenv. One issue may be that your module context isn’t set correctly when you run this way and you can fix this with `pipenv run python -m coverage ...` -  you also don’t need the quotes surrounding the command as far as I’m aware. Beyond that you’ll have to consult the coverage folks or the python irc channel over on freenode
