### ISSUE TITLE
Installing dependencies but not app

### ISSUE THREAD

**Issue by remram44** [pypa/pipenv#1879]
My current setup uses a requirements.txt which lists all my dependencies (and transitive dependencies), which I basically generate from pip-tools. To deploy my app, I do `pip install -r requirements.txt` then `pip install -e .`, to install the dependencies and the app, respectively.

What is great with this system is that it works correctly with Docker, caching the dependencies and keeping my builds very fast:
```
# This part will be cached, only reinstalling if I change the requirements
ADD requirements.txt ./
RUN pip install -r requirements.txt

# This part runs every time I change any of the app's code, but is fast because dependencies are installed
ADD setup.py app ./
RUN pip install -e .
```

I am not sure how to get this working with pipenv. If I `install -e ./`, my app appears in `Pipfile`, and there's no way for me to install only the dependencies. If I don't put my app in Pipfile, I need to copy all the dependencies from `setup.py` to `Pipfile`.

That makes the build for anyone using Docker hundreds of time slower, and is a huge barrier to Docker users moving to pipenv.

------------

##### Expected result

Being able to use `Pipfile` in my Docker build.

##### Actual result

Build is made very slow by the fact I can't cache installation of the dependencies.

##### Steps to replicate

This fails because `.` is not copied yet (it might even try to grab the app from Git):
```
ADD Pipfile Pipfile.lock ./
RUN pipenv install
```

------------

I am not sure what's a good fix for this, or if it's high profile enough for pipenv devs to address. A way to install dependencies but not the app would solve this. A way to have `Pipfile.lock` list the dependencies from `setup.py` without having it list the app would be another way.

Anyone else using pipenv to build applications deployed via Docker?

**Comment by frostming** [comment]
Put them in different sections, you can do this by:(starting from a clean env)
### Install dependencies:
```
$ pipenv install
```
It will automatically discover `requirements.txt` and add the contents to `[packages]` section of `Pipfile`
### Install app:
```
$ pipenv install --dev -e .
```
It will add app path to `[dev-packages]` section.

**Comment by remram44** [comment]
Running `pipenv install .` as part of the build has no advantage over using pip, and doesn't fix the problem: the first `pipenv install` won't install the dependencies unless I list them all in `Pipfile` in addition to `setup.py` 🤔 I am not sure what `--dev` brings me in that context.

Still, thanks for taking a look! I'm very interested in hearing how people are using pipenv for production themselves.

**Comment by jtratner** [comment]
Yes, you’re right there’s not a good way around this at the moment, except
that you could use pipenv to generate a requirements.txt that you then
install into your Docker image.

**Comment by uranusjr** [comment]
Why *not* app, however? Are there any particular limitations, or is it only aesthetic consideration?

**Comment by jtratner** [comment]
Actually the suggestion to put it in [dev] would work really well! (As long
as the dependency closure is compatible with dev when you only install prod
packages)

**Comment by uranusjr** [comment]
Also this is because the goal of Pipfile (the standard) is to be eventually integrated into pip, and enables you to just use it like a requirements.txt like `pip install -p Pipfile` (something like this). There is no good way to do it with Pipenv atm, but it is relatively easy to write a pip wrapper to perform the conversion yourself. (I’ve said this a couple of times, and have made a tool I never took time to package properly, but I’m a little surprised nobody actually did it at this point.)

**Comment by techalchemy** [comment]
Wait I’m super confused about why this conversation isn’t addressing how we actually recommend people lock dependencies and deploy via docker...

You can do your exact workflow with pipenv, except `pipenv install -e .`, then add the lockfile to your container and `pipenv install —deploy`

**Comment by techalchemy** [comment]
It’s quite fast because your dependencies are resolved and pinned already in the lockfile, I guess I’m not sure why you’d add them one by one to the Pipfile... that makes no sense at all

**Comment by remram44** [comment]
If you don't do `pipenv install -e .`, then the dependencies of your app (from setup.py) don't get added to `Pipfile.lock` (unless you copy them from `setup.py` to `Pipfile`, which you can do, but then you have to remember to keep all that in sync)

@techalchemy: I don't think resolving dependencies is what takes the bulk of installation time. Some projects will have a lot of dependencies, some of which will take a long time to download, some of which will be compiled from source, and having to re-install the same dependencies on every Docker build is inefficient (and unnecessary).

Yes it seems that the current best option is to copy dependencies from `setup.py` to `Pipfile` (and remember to always keep them in sync), not put `-e .` in there, and do `pipenv install --deploy` then `pip install -e .`

**Comment by jtratner** [comment]
Key problem is that it totally breaks layer caching - because you have to
add your (frequently changing) code into the container *first*, before
installing requirements - which then repeatedly busts the cache.

**Comment by techalchemy** [comment]
@remram44 resolving dependencies _is_ what takes a long time. Locking is precisely the thing that is slow, just try my suggestion and see the difference.  Locking in docker containers is well documented as being incredibly slow, and the more dependencies you put in your Pipfile the slower it will be.

**Comment by remram44** [comment]
Nevertheless, doing compilation and no resolution is way slower than no compilation or resolution. If Docker can't cache, this takes (tens of) minutes instead of a fraction of a second.

**Comment by choliver** [comment]
Maybe I'm not understanding something, but why can't you do `pipenv install -e .` ahead of time (i.e. so that everything's tracked in `Pipfile.lock`), and then have your Dockerfile as something like:

```
ADD Pipfile Pipfile.lock setup.py ./
RUN pipenv install --deploy
ADD app ./
...
```

That way Docker caching still works, so long as you don't change your deps.

**Comment by techalchemy** [comment]
Right, the approach described above is the correct one. Closing this

**Comment by remram44** [comment]
This works if you could install the app with only the `setup.py` and none of its code.
```
Obtaining file:///usr/src/app
    running egg_info
    writing myapp.egg-info/PKG-INFO
    writing dependency_links to myapp.egg-info/dependency_links.txt
    writing entry points to myapp.egg-info/entry_points.txt
    writing top-level names to myapp.egg-info/top_level.txt
    error: package directory 'myapp' does not exist
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /usr/src/app/
```

**Comment by tsiq-oliverc** [comment]
@remram44 That's because setuptools needs somewhere to put the `egg-info`, I think?  Can you just add `RUN mkdir app` to your Dockerfile?

**Comment by remram44** [comment]
It's simply because it is listed in setup.py's `packages=[]`. And it would be way worse for programs using `find_packages()`, since you can't discover packages that are not there.

This is a terrible solution, but I respect your choice to close this issue and end the conversation. Apologies if this wasn't the right place. We will have to continue using `pip-freeze` and `requirements.txt` until a better solution appear.

**Comment by techalchemy** [comment]
@remram44 how is this a terrible solution? Lock the dependency graph locally. Then remove your own package from the lockfile. Then copy your lockfile. 

I can’t follow any aspect of your use case that would make this not work for you. Can you provide some output demonstrating exactly what you’re trying to do and why this doesn’t accomplish that?

**Comment by remram44** [comment]
> Lock the dependency graph locally. Then remove your own package from the lockfile. Then copy your lockfile.

This would work, I guess. Will `pipenv install --deploy` not complain that the `Pipfile.lock` is not up-to-date with `Pipfile`?

Is there an automatic way to remove the app from the lockfile? It seems to appear twice (once as `.` and once as Git reference)

**Comment by techalchemy** [comment]
@remram44 you can just delete the Pipfile entirely or (my suggestion) never copy it to Docker. Then the lockfile can’t be out of date.  However you can also use `pipenv install —ignore-pipfile`

Appearing twice is a bug I probably introduced at some point last release (sorry!) but we will have a new release out soon that will fix this
