### ISSUE TITLE
Misusage of `resolve_deps` function?

### ISSUE THREAD

**Issue by alexsavio** [pypa/pipenv#1880]
There is something wrong with the call to `resolve_deps` here: https://github.com/pypa/pipenv/blob/master/pipenv/resolver.py#L56

Please, check the function definition here: https://github.com/pypa/pipenv/blob/master/pipenv/utils.py#L394
I am not sure what is the fix though and can't propose a change.

Thank you!

**Comment by techalchemy** [comment]
@alexsavio telling us there is something wrong is not going to help us troubleshoot or assess. Can you please provide context? What bug did you encounter?

**Comment by alexsavio** [comment]
If you read the code I point to...there is a missing parameter in the function call.

**Comment by frostming** [comment]
@alexsavio The function call looks correct to me. What parameter is missing?

**Comment by techalchemy** [comment]
There is no missing parameter in the function call and unless there is some behavior that is wrong, this is not an issue. Closing unless there is an issue to report.

**Comment by alexsavio** [comment]
Sorry for the misunderstanding. You're right, the function call is correct, the inconsistency in the function call misled me, because of the error I get with the latest pipenv release.
```
❯ pipenv install --dev
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
in
    clear=do_clear,
          └ False
  File "/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py", line 63, in resolve
    verbose=verbose,
    │       └ False
    └ False
TypeError: resolve_deps() missing 1 required positional argument: 'which_pip'
```
I have been using pipenv with the same setup without a problem since version 9.xx, I got this update last night and can't figure out what is the issue now.


Here is the output from my setup:
```
❯ python3 -m pipenv.help
<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.9.0'`

Pipenv location: `'/usr/local/lib/python3.6/dist-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`
  - `3.6`: `/opt/bin/python3.6`
  - `3.6`: `/home/alexandre/anaconda3/bin/python3.6`
  - `3.7`: `/usr/bin/python3.7m`
  - `3.7`: `/usr/bin/python3.7`

  - `2.7.14`: `/usr/bin/python`
  - `3.6.4`: `/home/alexandre/anaconda3/bin/python`
  - `2.7.14`: `/usr/bin/python2`
  - `3.6.3`: `/usr/bin/python3`
  - `3.6.4`: `/opt/bin/python3`
  - `3.6.4`: `/home/alexandre/anaconda3/bin/python3`
```

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.13.0-37-generic',
 'platform_system': 'Linux',
 'platform_version': '#42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018',
 'python_full_version': '3.6.3',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `CLUTTER_IM_MODULE`
  - `CONDA_SHLVL`
  - `LD_LIBRARY_PATH`
  - `LS_COLORS`
  - `_fzf_orig_completion_cat`
  - `LC_MEASUREMENT`
  - `FSLWISH`
  - `FSLDIR`
  - `_fzf_orig_completion_gunzip`
  - `LESSCLOSE`
  - `LC_PAPER`
  - `LC_MONETARY`
  - `XDG_MENU_PREFIX`
  - `POSSUMDIR`
  - `LANG`
  - `SOFT`
  - `DISPLAY`
  - `GNOME_SHELL_SESSION_MODE`
  - `_fzf_orig_completion_uniq`
  - `EDITOR`
  - `FSLMACHINELIST`
  - `_fzf_orig_completion_cd`
  - `FSLBROWSER`
  - `_fzf_orig_completion_cp`
  - `_fzf_orig_completion_git`
  - `COLORTERM`
  - `_fzf_orig_completion_view`
  - `USERNAME`
  - `JAVA_HOME`
  - `_fzf_orig_completion_sort`
  - `J2SDKDIR`
  - `XDG_VTNR`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `GIT_HOSTING`
  - `_fzf_orig_completion_bunzip2`
  - `GIT_EDITOR`
  - `SSH_AUTH_SOCK`
  - `_fzf_orig_completion_grep`
  - `SPM_DIR`
  - `FSLTCLSH`
  - `MANDATORY_PATH`
  - `FSLREMOTECALL`
  - `_fzf_orig_completion_vi`
  - `LC_NAME`
  - `XDG_SESSION_ID`
  - `DERBY_HOME`
  - `USER`
  - `DESKTOP_SESSION`
  - `GIT_PYTHON_TRACE`
  - `_fzf_orig_completion_vim`
  - `QT4_IM_MODULE`
  - `TEXTDOMAINDIR`
  - `_fzf_orig_completion_less`
  - `_fzf_orig_completion_telnet`
  - `DEFAULTS_PATH`
  - `PWD`
  - `HOME`
  - `JOURNAL_STREAM`
  - `TEXTDOMAIN`
  - `CMAKE_PREFIX_PATH`
  - `J2REDIR`
  - `SSH_AGENT_PID`
  - `_fzf_orig_completion_head`
  - `QT_ACCESSIBILITY`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `FSLLOCKDIR`
  - `_fzf_orig_completion_unzip`
  - `CAMINO_PATH`
  - `XDG_SESSION_DESKTOP`
  - `_fzf_orig_completion_awk`
  - `TILIX_ID`
  - `LC_ADDRESS`
  - `_fzf_orig_completion_diff`
  - `_fzf_orig_completion_mv`
  - `LC_NUMERIC`
  - `FORCE_SPMMCR`
  - `_fzf_orig_completion_ftp`
  - `_fzf_orig_completion_tee`
  - `GTK_MODULES`
  - `PAPERSIZE`
  - `WINDOWPATH`
  - `_fzf_orig_completion_emacs`
  - `TERM`
  - `VTE_VERSION`
  - `SHELL`
  - `MCR_DIR`
  - `_fzf_orig_completion_gvim`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `IM_CONFIG_PHASE`
  - `XDG_CURRENT_DESKTOP`
  - `ANTSPATH`
  - `_fzf_orig_completion_tail`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `CUDA_VISIBLE_DEVICES`
  - `SHLVL`
  - `XDG_SEAT`
  - `LANGUAGE`
  - `_fzf_orig_completion_du`
  - `LC_TELEPHONE`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `XDG_CONFIG_DIRS`
  - `PATH`
  - `LC_IDENTIFICATION`
  - `_fzf_orig_completion_ls`
  - `_fzf_orig_completion_ld`
  - `FSLOUTPUTTYPE`
  - `_fzf_orig_completion_ln`
  - `_fzf_orig_completion_sed`
  - `SPMMCRCMD`
  - `FSLMULTIFILEQUIT`
  - `_fzf_orig_completion_rmdir`
  - `_fzf_orig_completion_wc`
  - `SESSION_MANAGER`
  - `_fzf_orig_completion_rm`
  - `LESSOPEN`
  - `GTK_IM_MODULE`
  - `LC_TIME`
  - `_`
  - `OLDPWD`
  - `CVSEDITOR`
  - `SVN_EDITOR`
  - `LSCOLORS`
  - `CORRECT_IGNORE`
  - `CORRECT_IGNORE_FILE`
  - `WORDCHARS`
  - `HISTFILE`
  - `HISTSIZE`
  - `SAVEHIST`
  - `FZF_DEFAULT_OPTS`
  - `LISTMAX`
  - `INTERACTIVE_FILTER`
  - `DOTPATH`
  - `ZPLUG_LOADFILE`
  - `ZPLUG_ROOT`
  - `PERIOD`
  - `FPATH`
  - `ZPLUG_HOME`
  - `ZPLUG_THREADS`
  - `ZPLUG_PROTOCOL`
  - `ZPLUG_FILTER`
  - `ZPLUG_USE_CACHE`
  - `ZPLUG_ERROR_LOG`
  - `ZPLUG_BIN`
  - `ZPLUG_CACHE_DIR`
  - `ZPLUG_REPOS`
  - `_ZPLUG_VERSION`
  - `_ZPLUG_URL`
  - `_ZPLUG_OHMYZSH`
  - `_ZPLUG_PREZTO`
  - `_ZPLUG_AWKPATH`
  - `_ZPLUG_CONFIG_SUBSHELL`
  - `GIT_FZF`
  - `SOFT_PATH`
  - `MP_EDITOR`
  - `ZSH_HISTORY_FILE`
  - `ZSH_HISTORY_FILTER`
  - `ZSH_HISTORY_KEYBIND_GET_BY_DIR`
  - `ZSH_HISTORY_KEYBIND_GET_ALL`
  - `ZSH_HISTORY_KEYBIND_SCREEN`
  - `ZSH_HISTORY_KEYBIND_ARROW_UP`
  - `ZSH_HISTORY_KEYBIND_ARROW_DOWN`
  - `PIP_CONFIG_FILE`
  - `INTEL_HOME`
  - `BETTER_EXCEPTIONS`
  - `FSLPARALLEL`
  - `AFNI_PATH`
  - `MANPATH`
  - `SPM_ARCH`
  - `ZSH`
  - `ZSH_CACHE_DIR`
  - `PROMPT_EOL_MARK`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `DIRENV_DIR`
  - `DIRENV_DIFF`
  - `ZSH_COMMAND_TIME`
  - `DIRENV_WATCHES`
  - `PIPENV_VENV_IN_PROJECT`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `./.venv`

Debug–specific environment variables:

  - `PATH`: `/usr/lib/fsl/5.0:./node_modules/.bin:/home/alexandre/.zplug/repos/zplug/zplug/bin:/home/alexandre/bin:/usr/local/bin:/home/alexandre/.zplug/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/opt/bin:/home/alexandre/abin:/home/alexandre/software/camino/bin:/home/alexandre/software/matlab_runtime/v93/bin:/home/alexandre/software/ants/build/bin:/home/alexandre/.fzf/bin:/home/alexandre/bin:/snap/bin:/home/alexandre/anaconda3/bin:/opt/intel/bin:/home/alexandre/abin:/home/alexandre/software/ants/build/bin:/home/alexandre/software/camino/bin:/home/alexandre/software/matlab_runtime/v93/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `/usr/bin/vim`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/alexandre/projects/hansel`


---------------------------

Contents of `Pipfile` ('/home/alexandre/projects/hansel/Pipfile'):

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[dev-packages]

pytest = "*"
pytest-cov = "*"
pdbpp = "*"
pytest-xdist = "*"
better-exceptions = "*"
"flake8" = "*"
bumpversion = "*"
coveralls = "*"
pandas = "*"
rstcheck = "*"


[packages]

click = "*"

```

</details>
