### ISSUE TITLE
Delete Pipfile.lock as late as possible

### ISSUE THREAD

**Issue by tsiq-oliver** [pypa/pipenv#1888]
When updating Pipfile.lock, the old version is deleted before anything happens.  If the update process fails (maybe because one Ctrl+C's it because of a mistake, or it's [taking too long][3], or [it crashes][4], etc.), then one is left with no lockfile.

Could the behaviour be changed so that the [lockfile deletion][1] is performed **immediately** before the [serialisation of the new content][2]?  (FWIW, I'd be happy to attempt a PR for this.)

I guess two rationales for the current behaviour:

1. Your `Pipfile.lock` should be in Git.  Yes, but it still sucks if you're doing a sequence of new package installs/etc. and haven't committed your work.
2. The update of the `Pipfile.lock` should be consistent with the current state of the virtualenv.  I'd buy that, but the current behaviour (no lockfile) doesn't strike me as better :wink:.

[1]: https://github.com/pypa/pipenv/blob/master/pipenv/core.py#L1026
[2]: https://github.com/pypa/pipenv/blob/master/pipenv/core.py#L1173
[3]: https://github.com/pypa/pipenv/issues/1785
[4]: https://github.com/pypa/pipenv/issues/1837

------------

##### Steps to replicate

1. Start with an existing Pipenv environment (i.e. you have a working `Pipfile`/`Pipfile.lock`).
2. Run `pipenv install <any_dep_that_takes_a_long_time>`.
3. Hit Ctrl+C before it's finished.

**Comment by uranusjr** [comment]
Pull requests are welcomed :)

**Comment by tsiq-oliverc** [comment]
@uranusjr - Good :)  I'll do so once maintainers agree the proposed change wouldn't break some intentional behaviour.

**Comment by techalchemy** [comment]
@tsiq-oliverc I would say that the lockfile should _never_ be updated with the current state of the environment. We never arbitrarily update lockfiles _ever_. If you activate your environment and pip install some stuff, you didn’t use pipenv dependency management and it could badly break resolution. We can’t be responsible for managing this

However, if you want to write a PR that renames the old lockfile at the start of the process and swaps it back on exceptions or deletes it on success that would make sense to me

**Comment by tsiq-oliverc** [comment]
@techalchemy - Sorry, to clarify, what I mean is this:

I could imagine that the current behaviour is intentional, as it would avoid situations where there's an outdated lockfile.  Imagine `pipenv` is installing/updating some package (`A`), but it crashes (or is killed) **before** updating the lockfile.  Then the lockfile would say one thing (old or no version of `A`), but the actual contents of the environment would be different.

Nevertheless, if you guys are happy for me to go with the "atomic" replacement approach then I'll get to that this week, hopefully!

**Comment by uranusjr** [comment]
+1 from me on the atomic file replacing part. I’ve always disliked how Pipenv deletes the lockfile and then fails to lock, personally. Nothing wrong technically, but is a bit expectected from a UX perspective.

**Comment by techalchemy** [comment]
Yeah that is what I had in mind.

**Comment by uranusjr** [comment]
This reminds me Armin has a [battle-tested `atomic_open` snippet](https://github.com/lektor/lektor/blob/05a541120e6f6add0d5d9d30d0585166f838594c/lektor/utils.py#L451) we might be able to steal.

**Comment by wichert** [comment]
This would be really helpful for us. I am currently in a location where the network is very slow, and I keep seeing developers hit a download timeout, not noticing Pipfile.lock disappeared, running` pipenv install` again and then noticing all kinds of unexpected upgrades happened.
