### ISSUE TITLE
Missing `pipenv help` subcommand

### ISSUE THREAD

**Issue by maxalbert** [pypa/pipenv#1894]
Apologies if this has been suggested before, but I couldn't find it in the existing issues.

Given that pipenv supports subcommands such as `pipenv run`, `pipenv install`, ..., the first thing I try when I'm unsure about something is `pipenv help`. However, this results in an error ('No such command "help".') It always takes a few second to realise that `pipenv -h` will do the trick but it is a little confusing and results in a mental context switch from the task at hand that would be nice to avoid.

I know that @kennethreitz said in [another issue](https://github.com/pypa/pipenv/issues/485) that he wants to keep the list of commands as small as possible, but the `help` command is arguably one of the most fundamental ones and it is surprising to a user that `pipenv help` doesn't work while something like `pipenv install` does.

Suggestion:

- Add `pipenv help` (equivalent to `pipenv -h`)
- Add `pipenv help <subcommand>` (equivalent to `pipenv <subcommand> -h`), for instance: `pipenv help run`

**Comment by frostming** [comment]
I know help subcommand is very common for listing all available subcommands and printing usage for specific subcommand, however, on the other hand,  `--help` is **click**'s convention to do that, and it is also intuitive.

There should be one way and only one way to do one thing(from Zen of Python). What do you think?

**Comment by maxalbert** [comment]
I guess the question is what the _obvious_ way to do it is. ;)

Personally, I think consistency helps a lot. This is why from a user's perspective I'd expect the existence of a help subcommand, since the other core functionality in pipenv is also provided via subcommands.

I agree that the `--help` approach is also very common (esp. among older Unix tools, although the subcommand approach seems to be gaining more traction recently). So in order to follow the ["principle of least astonishment"](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) for the largest user base it would be great to support both - especially since it should add virtually no implementation overhead because the help subcommand is just an alias for `--help`.

Anyway, no big deal either way. Just thought I'd make the suggestion because it seems like an easy thing to support with little to no downside.

**Comment by techalchemy** [comment]
I think this seems like a decent suggestion but is very, very low priority and we have a lot on our plates right now, closing for the moment but thanks for the input!
