### ISSUE TITLE
Editable install with `Pipenv install -e .` is not editable

### ISSUE THREAD

**Issue by brandonvin** [pypa/pipenv#1898]
<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.9.0'`

Pipenv location: `'/usr/local/lib/python3.5/dist-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.12`: `/usr/bin/python`
  - `2.7.12`: `/usr/bin/python2`
  - `3.5.2`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.5.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.4.0-79-generic',
 'platform_system': 'Linux',
 'platform_version': '#100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017',
 'python_full_version': '3.5.2',
 'python_version': '3.5',
 'sys_platform': 'linux'}
```

System environment variables:

  - `USER`
  - `LS_COLORS`
  - `JAVA_HOME`
  - `PATH`
  - `SPARK_CONF_DIR`
  - `PYTHONDONTWRITEBYTECODE`
  - `HOME`
  - `LESSOPEN`
  - `SHELL`
  - `HISTCONTROL`
  - `PS1`
  - `HADOOP_HOME`
  - `LESSCLOSE`
  - `J2SDKDIR`
  - `LANGUAGE`
  - `MAIL`
  - `HADOOP_CONF_DIR`
  - `RBENV_SHELL`
  - `LANG`
  - `LOGNAME`
  - `MYPYPATH`
  - `TERM`
  - `DERBY_HOME`
  - `J2REDIR`
  - `PIP_PYTHON_PATH`
  - `HIVE_HOME`
  - `SPARK_HOME`
  - `PYTHONPATH`
  - `HISTTIMEFORMAT`
  - `SHLVL`
  - `PWD`
  - `YARN_CONF_DIR`
  - `CMF_CONF_DIR`
  - `_`
  - `SSH_TTY`
  - `HIVE_CONF_DIR`
  - `SSH_CLIENT`
  - `SSH_CONNECTION`
  - `PYTHONUNBUFFERED`
  - `PYSPARK_PYTHON`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/bvincent/hadoop/bin:/home/bvincent/hive/bin:/home/bvincent/spark/bin:/home/bvincent/.local/bin:/home/bvincent/.chefdk/gem/ruby/2.1.0/bin:/opt/chefdk/bin:/home/bvincent/.rbenv/plugins/ruby-build/bin:/home/bvincent/.rbenv/shims:/home/bvincent/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/go/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/bvincent`

---------------------------

</details>

------------

##### Expected result

The install uses a symlink so that my code can be edited and re-run without re-installing.

##### Actual result

* A duplicate of my code appeared in the virtualenv's `src` directory. It is *not* a symlink.

* The Pipfile.lock contains a reference to a specific commit of my code's Git repository, which implies that a separate copy is cloned.
```
...
"mypackage": {
    "editable": true,
    "git": "git@github.com:myorg/my-package.git",
    "ref": "a30098a534d2ccb41sb907db3ef2a8c0cda2460c"
},
...
```

##### Steps to replicate

Note that there are 2 other packages in my Pipfile that are also editable installs from Git.

```
git clone git@github.com:myorg/my-package.git
cd my-package
pipenv install -e .
# Edit mypackage/__main__.py with text editor...
diff mypackage/__main__.py $(pipenv --venv)/src/mypackage/__main__.py
```
There is a diff. And running the code using `pipenv run python -m mypackage` uses the copy located in the virtualenv, not the repository where I executed `pipenv install -e .`.

**Comment by NateV** [comment]
I think I'm seeing this too. It seems like changes to files in the venv are reflected (although not actually written into the venv files), but new files are not added into the venv src directory. pytest is not finding new modules, and I think this is why.

**Comment by techalchemy** [comment]
There is a bug in the release which duplicates local editable installs in the lockfile - one as a vcs ref, one as a `path`. As a temporary workaround you can delete the vcs entry manually and run `pipenv sync`

**Comment by hanchang** [comment]
Since this issue is closed, is it a safe assumption that this is a "won't fix", i.e. if someone submits a pull request to address the issue, would it be reviewed and potentially accepted for release?

If a fix is welcome, would it make sense to keep this issue open in case someone wants to work on it?

Thanks in advance for all the effort put into pipenv!
