### ISSUE TITLE
support for --py returning pythonw.exe on windows

### ISSUE THREAD

**Issue by sdementen** [pypa/pipenv#1905]
Should we add a --pyw flag to return pythonw.exe path on windows ?
use case: I need to retrieve the pythonw.exe path programmatically to initialise a configuration file. If I use python.exe in this case, there is the shell window that appears. I could use --venv and add /Scripts/pythonw.exe but it looks hackish (vs the --pyw solution).
I am ready to do a PR if worthwile

**Comment by uranusjr** [comment]
+1 for me if this option only works on Windows. On other systems it should report a standard error message (no such option), or a custom one (only works on Windows).

**Comment by uranusjr** [comment]
On second though I’m probably +0. The path can be obtained with less hack with `pipenv run where pythonw.exe`

**Comment by techalchemy** [comment]
@uranusjr @sdementen does this get picked up by the normal pep 514 compliant finder at all? Like `py -3w` or some equivalent syntax?

**Comment by uranusjr** [comment]
@techalchemy There is a `pyw.exe`, but `pipenv run` does not set `VIRTUAL_ENV` so it cannot pick up the correct executable. Inside the subshell, `pyw` points to `pythonw` in the virtualenv.

**Comment by sdementen** [comment]
@uranusjr , yes, I want to get the pythonw of an environment created by pipenv to configure xlwings (see http://docs.xlwings.org/en/stable/addin.html#workbook-directory-config-config-file if interested )

**Comment by uranusjr** [comment]
@techalchemy pyw (and py) does not consider the PATH environ, only registry and VIRTUAL_ENV.

**Comment by techalchemy** [comment]
Closing then for now, this seems super specific
