### ISSUE TITLE
Pipenv lock failing on py3.6 due to py2 dependency

### ISSUE THREAD

**Issue by j-walker23** [pypa/pipenv#1912]
I'm opening up a new issue to hopefully further the conversation from another closed issue https://github.com/pypa/pipenv/issues/1579.

`pipenv` author mentioned when closing the issue above that the issue was with the `setup.py` for the `futures` package.
I opened the issue at https://github.com/agronholm/pythonfutures/issues/76 and they are willing to help but we need more info on this side.

Specifically an answer/help to my question here https://github.com/pypa/pipenv/issues/1579#issuecomment-377013055.

Pipenv and the lock file are amazing so any help getting this resolved will be greatly appreciated!

**Comment by techalchemy** [comment]
Can you give me an example file that causes you this problem?

**Comment by j-walker23** [comment]
No problem. There are also a couple examples in the linked issue https://github.com/pypa/pipenv/issues/1579.

The simplest one causing the issue for me is
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
google-cloud-core = "*"

[dev-packages]

[requires]
python_version = "3.6"
```

**Comment by techalchemy** [comment]
Thanks, will check this out in the morning if someone doesn't get to it first.  Could be fixed in master though, if you dont mind checking

**Comment by j-walker23** [comment]
Awesome thanks! 

I definitely don't mind checking master. I did a `brew install` for my setup. Whats the best way to test master?

**Comment by techalchemy** [comment]
You can technically just make a fresh virtualenv and then `pip install -e git+https://github.com/pypa/pipenv.git@master#egg=pipenv` inside the virtualenv, then `export PIPENV_IGNORE_VIRTUALENVS=1` and pipenv will behave as normal but use the virtualenv install

**Comment by j-walker23** [comment]
Perfect, will try now.

**Comment by j-walker23** [comment]
![screen shot 2018-04-05 at 1 59 29 am](https://user-images.githubusercontent.com/2018885/38353882-13e9c988-3875-11e8-9388-719129466220.png)

Very cool! Looks like it is. Whats the release schedule look like so i can know when to get it on my prod vms?

**Comment by techalchemy** [comment]
Release is out, thanks for your patience

**Comment by j-walker23** [comment]
Thank you! This shit is awesome.
