### ISSUE TITLE
pipenv issue template encourages leaking index credentials

### ISSUE THREAD

**Issue by wichert** [pypa/pipenv#1913]
The issue template for this project says:

> Please run `$ python -m pipenv.help`, and paste the results here.

If you run this from a package that uses a private package repository this will result in your private index URL **including credentials** to be included (multiple times) in the issue. Needless to say that is a very bad thing to happen.

**Comment by techalchemy** [comment]
Pipenv allows environment variables and if you dont like that approach you should keep it in your `~/.config/pip/pip.conf` and use the index alias.

We don't encourage leaking credentials, please adopt good practices.
