### ISSUE TITLE
Pipenv lock failing on py2.7 on egg pkgs

### ISSUE THREAD

**Issue by denever** [pypa/pipenv#1915]
Trying to lock a Pipfile with egg pkgs `netaddr==0.7.12` or `odfpy==1.3.6` fails.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.9.0'`

Pipenv location: `'/home/denever/miniconda2/lib/python2.7/site-packages/pipenv'`

Python location: `'/home/denever/miniconda2/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/home/denever/miniconda2/bin/python2.7`
  - `2.7`: `/home/denever/miniconda2/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.14`: `/home/denever/miniconda2/bin/python`
  - `2.7.14`: `/usr/bin/python`
  - `2.7.14`: `/home/denever/miniconda2/bin/python2`
  - `2.7.14`: `/usr/bin/python2`
  - `3.6.3`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.13.0-38-generic',
 'platform_system': 'Linux',
 'platform_version': '#43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018',
 'python_full_version': '2.7.14',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `QT4_IM_MODULE`
  - `GJS_DEBUG_OUTPUT`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_SESSION_TYPE`
  - `QT_IM_MODULE`
  - `LOGNAME`
  - `USER`
  - `PATH`
  - `XDG_VTNR`
  - `HOME`
  - `PYTHONUNBUFFERED`
  - `PS1`
  - `DISPLAY`
  - `LANG`
  - `CONDA_SHLVL`
  - `SHELL`
  - `JOURNAL_STREAM`
  - `SESSION_MANAGER`
  - `XDG_DATA_DIRS`
  - `WAYLAND_DISPLAY`
  - `GNOME_DESKTOP_SESSION_ID`
  - `CLUTTER_IM_MODULE`
  - `TEXTDOMAIN`
  - `XMODIFIERS`
  - `USERNAME`
  - `XDG_SESSION_DESKTOP`
  - `XDG_RUNTIME_DIR`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `VTE_VERSION`
  - `GDMSESSION`
  - `IM_CONFIG_PHASE`
  - `TEXTDOMAINDIR`
  - `GNOME_SHELL_SESSION_MODE`
  - `XDG_CONFIG_DIRS`
  - `PIP_PYTHON_PATH`
  - `LESSOPEN`
  - `XDG_SESSION_ID`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `_`
  - `GTK_IM_MODULE`
  - `DESKTOP_SESSION`
  - `LESSCLOSE`
  - `OLDPWD`
  - `SHLVL`
  - `PWD`
  - `COLORTERM`
  - `XDG_MENU_PREFIX`
  - `LS_COLORS`
  - `GJS_DEBUG_TOPICS`
  - `XDG_SEAT`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/denever/miniconda2/bin:/home/denever/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `it_IT.UTF-8`
  - `PWD`: `/home/denever/workvir/pipenvfail`

---------------------------

Contents of `Pipfile` ('/home/denever/workvir/pipenvfail/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
netaddr = "==0.7.12"

[requires]
python_version = "2.7"

```

</details>

------------

##### Expected result

Locking succeed creating a Pipfile.lock

##### Actual result
INFO:notpip.req.req_set:Collecting netaddr==0.7.12
INFO:pip9.download:File was already downloaded /home/denever/.cache/pipenv/pkgs/netaddr-0.7.12-py2.7.egg
INFO:pip9.utils:Complete output from command python setup.py egg_info:
INFO:pip9.utils:Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '/tmp/tmpBWtmo0build/netaddr/setup.py'

Full log: [here](https://github.com/pypa/pipenv/files/1879070/cerr.log)
##### Steps to replicate

`pipenv install -v netaddr==0.7.12`

**Comment by uranusjr** [comment]
This is fixed in master, IIRC. There is a duplicate somewhere in the issue tracker.
