### ISSUE TITLE
Change the blue text color to something more readable

### ISSUE THREAD

**Issue by garyking** [pypa/pipenv#1923]
Is it possible to change the blue text color to something more readable?

Here's how it looks for me right now; the only way I can read it is if I highlight the text. I'm sure most people are also using a black background color, like me?

![pipenv screenshot](https://user-images.githubusercontent.com/343940/38392525-cc5c84c6-38f5-11e8-8ff3-5f7f1b9d495e.png)

**Comment by s0undt3ch** [comment]
I'm facing the same issue, got it fixed? I need to change my shell color theme?

**Comment by garyking** [comment]
Yeah I just changed the color in my own shell.

**Comment by garyking** [comment]
I'm going to re-open this issue, because I just reset my terminal theme to test colors in another script, and I realized that most people would be using the default colors. So most of them would also have difficulty reading blue text on a black background.

**Comment by techalchemy** [comment]
Hey @garyking, thanks for the feedback --

We are not currently open to changing the colors (per Kenneth) but we are taking note of usability 
complaints on the topic which may influence a future change of heart.  I'm going to keep this closed for now since it's currently a no-action but I will make note of it

**Comment by Joss** [comment]
The blue color is completely unreadable in Windows terminal.
![2018-06-12_03h42_12](https://user-images.githubusercontent.com/9437720/41263932-a9e88b4c-6df2-11e8-9578-f32a32d37ea4.png)

**Comment by nachopro** [comment]
Hi, I'm a newcomer to pipenv and I faced the same issue :(

<a href="https://i.imgur.com/AxvxSUz.png">
  <img src="https://imgur.com/AxvxSUzl.png" />
</a>

**Comment by techalchemy** [comment]
I hear you, I really do.  I will make note of this and bring it up internally

**Comment by mmanhertz** [comment]
Any news on this? It's annoying in black background terminals, but I actually use windows powershell quite regularly... (to those unfamiliar: it has blue background)

**Comment by stardust85** [comment]
I love pipenv, but the blue color in 2018.7.x is really a fail! Please revert to something readable.

**Comment by stardust85** [comment]
I found a workaround for ubuntu: If you use gnome-terminal, it uses white background instead of black. Or change your color scheme. Sub-optimal, but better than unreadable pipenv.

**Comment by uranusjr** [comment]
IIRC white background has more problems displaying Pipenv output. Or it had, maybe it was improved but I forgot. I am curious though, what information do you find important to declare the current scheme as unreadable. I have never needed to read any output of `pipenv install` and it semi-hiding the text actually makes me more comfortable than running `pip install`, where I get immersed by a lot of not-really-useful output.

**Comment by hblanks** [comment]
It really is illegible on a standard black background terminal.

Given the other colors available, and the importance of any python program being accessible, perhaps we could use some color other than blue?

**Comment by jdeyton** [comment]
Hilariously, if you highlight the text in powershell, at least in mine, it becomes an equally unreadable yellow on white.

For other latecomers like me, you can work around this by setting the PIPENV_COLORBLIND env var to 1.
