### ISSUE TITLE
Detecting virtualenv location in windows is unreliable when using powershell.

### ISSUE THREAD

**Issue by mteiste** [pypa/pipenv#1925]
PS C:\Users\N N> cd work
PS C:\Users\N N\work> pipenv --venv
No virtualenv has been created for this project yet!
PS C:\Users\N N\work> cd ..
PS C:\Users\N N> cd .\Work\
PS C:\Users\N N\Work> pipenv --venv
C:\Users\N N\.virtualenvs\Work-DPz4PjCb
PS C:\Users\N N\Work>

Seems to work fine when using cmd.exe as the shell. Not a big thing, but slightly annoying.

**Comment by techalchemy** [comment]
@mteiste thanks for the report, this may be fixed with #1922 when merged, but not sure
