### ISSUE TITLE
[Question]Is package version numbering in pipfile get changed?

### ISSUE THREAD

**Issue by arcan25** [pypa/pipenv#1926]
It is come my attention that by default if i install some package with pipenv install some-package, in a pipfile it automatically mark version as a *. But about month ago that wasn't the case, if i install package it take's version number by default and record it in pipfile.

Is there something change internally or am i doing something wrong?

for example if you look below, upto wtforms it was marking the version number by default but after few updates for pipenv, about month ago, pipenv stop doing so. now when i install the packages it marks * as a version number , and all the * packages gets updated automatically which i never wanted for my production environment.
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
alembic = "==0.9.7"
"beautifulsoup4" = "==4.6.0"
certifi = "==2018.1.18"
chardet = "==3.0.4"
click = "==6.7"
colorama = "==0.3.9"
comtypes = "==1.1.4"
docopt = "==0.6.2"
dominate = "==2.3.1"
flask = "==0.12.2"
flask-cors = "==3.0.3"
flask-login = "==0.4.1"
flask-migrate = "==2.1.1"
flask-sqlalchemy = "==2.3.2"
flask-wtf = "==0.14.2"
gevent = "==1.2.2"
greenlet = "==0.4.13"
idna = "==2.6"
itsdangerous = "==0.24"
jedi = "==0.11.1"
"jinja2" = "==2.10"
mako = "==1.0.7"
markupsafe = "==1.0"
mysql-connector-python = "==8.0.6"
parso = "==0.1.1"
prompt-toolkit = "==1.0.15"
ptpython = "==0.41"
pygments = "==2.2.0"
"pypiwin32" = "==219"
python-dateutil = "==2.6.1"
python-editor = "==1.0.3"
"pywin32" = "==222"
requests = "==2.18.4"
sqlalchemy = "==1.2.2"
"urllib3" = "==1.22"
visitor = "==0.1.3"
wcwidth = "==0.1.7"
werkzeug = "==0.14.1"
wtforms = "==2.1"
openpyxl = "*"
flask-assets = "*"
jsmin = "*"
cssmin = "*"
cachecontrol = {extras = ["filecache"]}
msgpack = "*"
flask-admin = "*"
flask-compress = "*"
cssutils = "*"
flask-debugtoolbar = "*"
flask-principal = "*"
flask-user = "*"
flask-testing = "*"
python-dotenv = "*"
flask-restful = "*"

[pipenv]
keep_outdated = true
```

**Comment by techalchemy** [comment]
Pipenv has always default-installed packages unpinned unless you import them from a pinned requirements file or install them pinned yourself.
