### ISSUE TITLE
Error with 'pipenv shell -c'

### ISSUE THREAD

**Issue by kbd** [pypa/pipenv#1931]
I tried running `pipenv shell -c` as recommended [here](https://docs.pipenv.org/diagnose/#shell-does-not-show-the-virtualenvs-name-in-prompt) and got the following error:

```
⚡ ~/proj/temp/pipenvtest$ pipenv shell -c
Spawning environment shell (/usr/local/bin/zsh). Use 'exit' to leave.
. /Users/kbd/.local/share/virtualenvs/pipenvtest-4itLjI3S/bin/activate
-c
⚡ ~/proj/temp/pipenvtest$ . /Users/kbd/.local/share/virtualenvs/pipenvtest-4itLjI3S/bin/activate
(pipenvtest-4itLjI3S) ⚡ ~/proj/temp/pipenvtest$ -c
zsh: command not found: -c
```

It seems to pass anything after `shell` to the shell inside the virtualenv (which is what [this code](https://github.com/pypa/pipenv/blob/8a67a21d61a2383253fe0dd5e7a8d79d51d30d2d/pipenv/core.py#L2166) seems to do), but `-c` isn't being handled?

**Comment by techalchemy** [comment]
Yes, it spawns a subshell, and then it passes the arguments you supply as a command to execute in the new subshell.   As it says in your error message in your log here, `-c` is not a command as far as I'm aware. This is not passed as an argument to `$SHELL`.

**Comment by kbd** [comment]
So what you're saying is it's doing what the code tells it to do, but then [your documentation](https://docs.pipenv.org/diagnose/#shell-does-not-show-the-virtualenvs-name-in-prompt) is wrong.

> ☤ shell does not show the virtualenv’s name in prompt
>This is intentional. You can do it yourself with either shell plugins, or clever PS1 configuration. If you really want it back, use
>
>pipenv shell -c

What am I missing here?

**Comment by uranusjr** [comment]
The whole thing is upside down because `pipenv shell` changed its behaviour a while ago. It *does* show your virtualenv’s name by default now, and you should pass `--fancy` for it to *not* show it. I guess the whole section should be removed now.

**Comment by kbd** [comment]
> Yeah I was messing around with this yesterday and I couldn’t really figure out what we are even doing now. Like what is the advantage of `fancy`?

FWIW the only docs on https://docs.pipenv.org/ about `--fancy` say:

> `--fancy`
> Run in shell in fancy mode (for elegantly configured shells).

Which seems almost intentionally unhelpful. I only had *any* idea what it does thanks to [this ticket](https://github.com/pypa/pipenv/issues/815).

> But no matter what I do I actually can’t use it with fish or zsh because...

It works for me, so I'll show what it does here for reference. Without `--fancy` I get:

```bash
⚡ ~/proj/temp/pipenvtest$ pipenv shell
Spawning environment shell (/usr/local/bin/zsh). Use 'exit' to leave.
. /Users/kbd/.local/share/virtualenvs/pipenvtest-4itLjI3S/bin/activate
⚡ ~/proj/temp/pipenvtest$ . /Users/kbd/.local/share/virtualenvs/pipenvtest-4itLjI3S/bin/activate
(pipenvtest-4itLjI3S) ⚡~/proj/temp/pipenvtest$
```

With `--fancy` I get:

```bash
⚡ ~/proj/temp/pipenvtest$ pipenv shell --fancy
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
⚡ ~/proj/temp/pipenvtest$
```

So the only behavior difference I see is that it doesn't modify my prompt (and I prefer things not messing with my prompt). In absence of checking the code (or finding the aforementioned ticket), I had no idea `--fancy` uses an entirely different mechanism of loading the virtualenv.

In case it helps anyone, I'll post [how I added my support for pipenv to my own prompt](https://github.com/kbd/setup/commit/a491fc357871755bcd48c17a71f06f5efbcfa05b). I added `export PIPENV_SHELL_FANCY=1` to my environment and the following function to my prompt:

```bash
_prompt_venv() {
    # example environment variable set in a venv:
    # VIRTUAL_ENV=/Users/kbd/.local/share/virtualenvs/pipenvtest-vxNzUMMM
    if [[ -n $VIRTUAL_ENV ]]; then
        local venv_id=$(basename "$VIRTUAL_ENV" | rev | cut -d- -f1 | rev)
        echo -n "[v:$venv_id]"
    fi
}
```

After that, my prompt looks like:

```bash
⚡ ~/proj/temp/pipenvtest$ pipenv shell
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
⚡ [v:4itLjI3S]~/proj/temp/pipenvtest$
```

Regarding `$VIRTUAL_ENV`, I didn't see that documented anywhere by Pipenv, I just had to go spelunking through my `env` to see what was defined when I entered the virtualenv. It'd be nice if this was documented somewhere.

Anyway, thanks very much for looking into this, y'all.

**Comment by uranusjr** [comment]
@kbd `$VIRTUAL_ENV` is an environment variable set by virtualenv to indicate the currently activated environment. Pipenv does not really use it (except for detecting nested environments, but that is using virtualenv’s behaviour anyway), but set it to be compatible with plain virtualenv usages.

**Comment by kbd** [comment]
> Pipenv does not really use it...

It puts its tag prominently in your prompt with no mention of how to get at it if you want to be `--fancy`.

**Comment by uranusjr** [comment]
@kbd Er, no, the prompt thing comes from the activate script, which can be different from what `$VIRTUAL_ENV` gives you. Pipenv does not use `$VIRTUAL_ENV` for that.

**Comment by kbd** [comment]
> the prompt thing comes from the activate script, which can be different from what $VIRTUAL_ENV gives you.

So, even worse. You see why this could use a line of documentation somewhere.

**Comment by techalchemy** [comment]
Pipenv is not virtualenv and doesn't claim to be, I believe we explicitly say in our documentation that we don't behave exactly like virtualenv.  However, every tool that attempts to 'activate' virtualenvs _**MUST**_ set the `VIRTUAL_ENV` variable or much of the python tooling wont' operate correctly.  The fact that some shell themes take that and put it in your prompt really has nothing to do with us.

**Comment by techalchemy** [comment]
Also our documentation is under no obligation to explain every technical detail of the inner workings of pipenv, if you need to know what lines of code it runs to simulate a virtualenv activation you should read them

**Comment by techalchemy** [comment]
Closing, will address with documentation
