### ISSUE TITLE
pipenv lock -r should allow for exporting dev and regular depencies as a unified requirements.txt

### ISSUE THREAD

**Issue by irconan** [pypa/pipenv#1932]
I'm using pipenv to generate a requirements.txt for later install
Ideally I want to output all of the dependencies (regular and development) together as opposed to outputting the development dependencies on their own.

**Comment by techalchemy** [comment]
Thanks for the input! This isn't really a standard practice and you can just pipe them both into the same file, it's definitely not a priority feature to implement

Closing for now
