### ISSUE TITLE
Keys in Pipfile shouldn't be quoted, even when they contain numbers

### ISSUE THREAD

**Issue by anowlcalledjosh** [pypa/pipenv#1933]
Per the TOML spec, bare (unquoted) keys can contain ASCII alphanumerics, underscores and dashes – since these are the only characters allowed in Python package names (at least on PyPI), Pipfile shouldn't need to contain any quoted keys.

I tried to check if this was a pytoml or contoml issue; I couldn't get either of them to generate quoted keys with only alphanumerics, so I guess this is an issue with Pipenv? I'll admit I didn't do much testing, so I could be wrong.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.9.0'`

Pipenv location: `'/home/josh/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv'`

Python location: `'/home/josh/.local/venvs/pipenv/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.12`: `/usr/bin/python`
  - `2.7.12`: `/usr/bin/python2`
  - `3.5.2`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.13.0-38-generic',
 'platform_system': 'Linux',
 'platform_version': '#43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018',
 'python_full_version': '3.6.3',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `CLUTTER_IM_MODULE`
  - `PIPENV_VENV_IN_PROJECT`
  - `NVM_DIR`
  - `LS_COLORS`
  - `GNOME_KEYRING_PID`
  - `GIT_PS1_SHOWUNTRACKEDFILES`
  - `XDG_CONFIG_HOME`
  - `LESSCLOSE`
  - `LANG`
  - `GDM_LANG`
  - `LESS`
  - `DISPLAY`
  - `PYENV_ROOT`
  - `OLDPWD`
  - `EDITOR`
  - `COMPIZ_CONFIG_PROFILE`
  - `GPG_TTY`
  - `GTK2_MODULES`
  - `PIPENV_SHELL_FANCY`
  - `UPSTART_INSTANCE`
  - `DEBFULLNAME`
  - `XDG_VTNR`
  - `RIPGREP_CONFIG_PATH`
  - `SSH_AUTH_SOCK`
  - `MANDATORY_PATH`
  - `SESSIONTYPE`
  - `TMUX_PLUGIN_MANAGER_PATH`
  - `XDG_SESSION_ID`
  - `XDG_GREETER_DATA_DIR`
  - `USER`
  - `DESKTOP_SESSION`
  - `JOB`
  - `QT4_IM_MODULE`
  - `GOPATH`
  - `DEFAULTS_PATH`
  - `QT_QPA_PLATFORMTHEME`
  - `PWD`
  - `HOME`
  - `MANPAGER`
  - `GIT_PS1_SHOWDIRTYSTATE`
  - `SSH_AGENT_PID`
  - `QT_ACCESSIBILITY`
  - `TMUX`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `UPSTART_SESSION`
  - `XDG_SESSION_DESKTOP`
  - `GIT_PS1_SHOWUPSTREAM`
  - `GTK_MODULES`
  - `UPSTART_EVENTS`
  - `VISUAL`
  - `SHELL`
  - `TERM`
  - `VTE_VERSION`
  - `GNOME_KEYRING_CONTROL`
  - `XDG_SEAT_PATH`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `IM_CONFIG_PHASE`
  - `GIT_PS1_SHOWSTASHSTATE`
  - `INSTANCE`
  - `XDG_CURRENT_DESKTOP`
  - `GPG_AGENT_INFO`
  - `QT_LINUX_ACCESSIBILITY_ALWAYS_ON`
  - `TMUX_VERSION`
  - `TMUX_PANE`
  - `SHLVL`
  - `XDG_SEAT`
  - `LANGUAGE`
  - `WINDOWID`
  - `DEBEMAIL`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `XDG_CACHE_HOME`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `UPSTART_JOB`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `XDG_DATA_HOME`
  - `XDG_SESSION_PATH`
  - `XDG_CONFIG_DIRS`
  - `PATH`
  - `PS1`
  - `MYPYPATH`
  - `LESSOPEN`
  - `GTK_IM_MODULE`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`
 - `PIPENV_SHELL_FANCY`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/josh/go/bin:/home/josh/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/josh/.cargo/bin:/home/josh/.cabal/bin:/home/josh/bin:/home/josh/.local/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `vim`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/josh`

---------------------------

</details>

------------

##### Expected result

Pipenv should generate beautiful Pipfiles that look like this, with no quotes (as far as possible):

```toml
[dev-packages]
flake8 = "*"
twine = "*"
check-manifest = "*"
pyroma = "*"
flake8-bugbear = "*"
```

##### Actual result

Any keys with numbers in are quoted, even though they are allowed to be unquoted.

```toml
[dev-packages]
mypy = "*"
"flake8" = "*"
twine = "*"
check-manifest = "*"
pyroma = "*"
"flake8-bugbear" = "*"
```

##### Steps to replicate

```
pipenv install flake8
```

**Comment by techalchemy** [comment]
@anowlcalledjosh I'm pretty sure this is a patch in our toml version, is this causing any problems?  You may have to dig through commit histories to find out why this was patched

@frostming is a bit of a toml expert I believe so maybe he can speak to this a bit

**Comment by anowlcalledjosh** [comment]
@techalchemy ah, that would explain why I couldn't get either pytoml or contoml to generate quoted keys.

It looks like e0b35b2b1c6a8a7699a0a19307ad52d246616a32 might cause this? No idea what it was fixing though.

**Comment by uranusjr** [comment]
This has no technical consequences, but there is an aesthetic one. It also does not conform with general TOML styling AFAIK, so I’d be happy if this can be changed.

**Comment by techalchemy** [comment]
where do we stand on this, then? While pytoml/contoml doesnt't generate keys this way natively, they can certainly parse this, right?

Also, aren't these two things equivalent?

```ini
[dev-packages]
flake8-bugbear
```

and 

```toml
[dev-packages."flake8-bugbear"]
```

The latter of which would allow quotes?  I'm going to close this since I don't think we're likely to do much with it anyway, but I'm still curious about whether this violates the spec or not

See also #2062

**Comment by uranusjr** [comment]
From I understand the quotes shouldn’t have a functional difference. Non-quoted keys are simply a (preferred) shorthand.
