### ISSUE TITLE
Question: Detecting conditional dependencies managed by python code and not markers

### ISSUE THREAD

**Issue by vlcinsky** [pypa/pipenv#1934]
`pipenv` can create `Pipenv.lock` containing hashes for all available package formats. This allows the same package be safely installed in multiple execution environments such as Linux or Windows where compiled versions of C-based packages are likely to differ.

`Pipfile.lock` also contains markers, so if some of installed libraries used markers to declare conditional dependencies (e.g. only for python version 2.x), it will be present in `Pipfile.lock` and all things are great.

Problem: Some `setup.py` code I have seen is building list of dependencies `install_requires` dynamically using pure python code and not using markers.

Question: Is `pipenv` able to detect python code defined conditional list of dependencies (not using markers) and reflect it properly in `Pipfile.lock`?

I can imagine how complex such task could be and complete implementation is probably impossible.

If such scenarios exists (and I would assume they exist), it would be great to describe these limitations in documentation and also to recommend best practice to package authors to refrain from pure code created list of dependencies and use exclusively markers.

**Comment by vlcinsky** [comment]
Examples of such code defined dependencies:

[enum34](https://github.com/certik/enum34/blob/master/setup.py#L6):
```
if sys.version_info[:2] < (2, 7):
    required = ['ordereddict']
else:
required = []
```

**Comment by jtratner** [comment]
This is why locking is so slow in pipenv and lockfiles are only 100%
guaranteed to be correct for a specific Python version :-/

I think it’s pretty clear that markers are the blessed path going forward
(and it’d be great to open a PR on enum34 to change their setup.py going
forward), but I’m not totally familiar with the official story on packaging.

Google has a BigQuery database of the contents / file paths of open source
projects. Would be an interesting undertaking to detect dynamic
requirements in open source python projects.

**Comment by techalchemy** [comment]
Yep, lockfiles are built by actually executing setup.py

For the record that is a bug with `enum34` and someone should go PR an upstream patch so their setup.py can do this correctly

**Comment by techalchemy** [comment]
To @jtratner's point I dream someday we could aggregate this stuff, but it would still be non-deterministic under the current system so kinda hard to say how that would work

**Comment by techalchemy** [comment]
@vlcinsky I assume we answered the question here, although the limitations could definitely be documented.  Closing for now but definitely receptive to documentation
