### ISSUE TITLE
links instead of copies?

### ISSUE THREAD

**Issue by nbecker** [pypa/pipenv#1938]
Just trying out pyenv.  Looks nice, but it appears to install packages into virtualenv using copies, even though I already have the same packages installed in ~/.local/lib/python3.6/site-packages. I'd prefer links, which I believe is what anaconda does.

Tested on Linux Fedora 27 python 3.6

**Comment by uranusjr** [comment]
Pipenv uses virtualenv, and this is what it does. Please file this to pypa/virtualenv instead.
