### ISSUE TITLE
pipenv does not work in a pipenv shell

### ISSUE THREAD

**Issue by jkleint** [pypa/pipenv#1945]
First, thanks for pipenv -- it's a great step forward in Python package management.  I'd like to roll it out for my team, but a few snags are preventing me.

I'd like to be able to run `pipenv shell` and have it work like a virtualenv; specifically, when I run `pipenv xxx` in that shell, from any directory, even outside the project directory, I expected it to operate on that virtualenv.  But alas.

Create a new empty pipenv:
```
$ mkdir proj
$ cd proj
$ pipenv install
Creating a virtualenv for this project…
Using /usr/bin/python (2.7.14) to create virtualenv…
⠋Already using interpreter /usr/bin/python
New python executable in /home/me/.venv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/me/.venv/proj-9zRXrcHj
Creating a Pipfile for this project…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (b44f36)!                                                                                              Installing dependencies from Pipfile.lock (b44f36)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

Activate that environment:
```
$ pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave.
$ . /home/me/.venv/proj-9zRXrcHj/bin/activate
```

Leave the project directory:
```
(proj-9zRXrcHj) $ cd ..
```

...And things fall apart:
```
(proj-9zRXrcHj) $ pipenv graph
Warning: Unable to display currently–installed dependency graph information here. Please run within a Pipenv project.
```

I expected that to work.

```
(proj-9zRXrcHj) $ pipenv install requests
Creating a virtualenv for this project…
^C
```

I expected that to install to the existing virtual environment (/home/me/.venv/proj-9zRXrcHj) instead of create a new one.

And I can't even provide debugging info, because pipenv does not install itself in the virtualenv:

```
(proj-9zRXrcHj) $ python -m pipenv.help
/home/me/.venv/proj-9zRXrcHj/bin/python: No module named pipenv
```

It's pipenv 11.9.0 on Redhat 7 with Python 2.7.14.

**Comment by techalchemy** [comment]
Pipenv is a project-oriented dependency manager. Other people like to be able to safely move into a new project and create it while still being in a pipenv shell, which has been a requirement in the past -- we've had a few other issues on this in the past and this is a design decision

**Comment by jtratner** [comment]
It *will* work in all subdirectories of the project however.
