### ISSUE TITLE
Can we make `pipenv` available inside `pipenv shell` automatically?

### ISSUE THREAD

**Issue by devxpy** [pypa/pipenv#1948]
I have `fish`'s `pipenv` plugin installed, which automatically activates `pipenv shell` when i cd in to the directory

but this means i have to type `exit` or install pipenv inside my virtualenv if i want to install a new package using pipenv inside `pipenv shell`

Is there any good way to overcome this wired pattern?

**Comment by uranusjr** [comment]
`pipenv install` should work inside a subshell spawn by `pipenv shell` just like in the parent shell. What happened for you?

**Comment by techalchemy** [comment]
As far as I know you can still use pipenv inside a pipenv shell unless your fish config is messed up, I do this all the time.  Closing for now, let us know (with a reproducible example) if there is some problem with the functionality here

**Comment by devxpy** [comment]
@techalchemy , thanks for the explanation, it works now, for some reason..
