### ISSUE TITLE
Pipenv doesn't handle empty values in .env well

### ISSUE THREAD

**Issue by Flimm** [pypa/pipenv#1966]
##### Expected result

I have a `.env` file with these contents:

```
FOO_ONE=
FOO_TWO=
```

I expect these two environment variables to be created with empty values when running `pipenv run`:

```
$ pipenv run env | grep -i foo
Loading .env environment variables…
FOO_ONE=
FOO_TWO=
```

The reason I expect this is because that's the way `source .env` works in Bash, and that's also the way [`python-dotenv`](https://pypi.python.org/pypi/python-dotenv) works.

##### Actual result

```
$ pipenv run env | grep -i foo
Loading .env environment variables…
FOO_ONE=FOO_TWO=
```

The actual result was that the environment variable `FOO_ONE` was set to `FOO_TWO=`, and the environment variable `FOO_TWO` was not created.

##### Debugging information

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.9.0'`

Pipenv location: `'/usr/local/Cellar/pipenv/11.9.0_1/libexec/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/11.9.0_1/libexec/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`

  - `2.7.14`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.14`: `/usr/local/bin/python2`
  - `3.6.5`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST '
                     '2018; root:xnu-4570.51.1~1/RELEASE_X86_64',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_PROGRAM`
  - `TERM`
  - `SHELL`
  - `CLICOLOR`
  - `HISTSIZE`
  - `COPYFILE_DISABLE`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `OLDPWD`
  - `TERM_SESSION_ID`
  - `HISTFILESIZE`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `PATH`
  - `PWD`
  - `EDITOR`
  - `LANG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `ITERM_ORIG_PS1`
  - `PS1`
  - `HISTCONTROL`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `ITERM_PREV_PS1`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `GOPATH`
  - `DISPLAY`
  - `COLORTERM`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:...`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `vim`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/flimm/git/bla2`

---------------------------

Contents of `Pipfile` ('/Users/flimm/git/bla2/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.6"

```

</details>

**Comment by uranusjr** [comment]
Upgrade. 11.10.0 works.

**Comment by Flimm** [comment]
Thank you.
