### ISSUE TITLE
install with '"e1839a8" = {path = ".", editable = true}' in Pipfile refuse to install other dependencies

### ISSUE THREAD

**Issue by AndreasPresthammer** [pypa/pipenv#1984]
Given that you have a Pipfile with other dependencies and a '"e1839a8" = {path = ".", editable = true}' section created using `pipenv install -e .`. `pip install --skip-lock` will ONLY install the _self_ and not any of the other dependencies specified in the `[packages]` section.

This only fails in latest 11.10.0 version. Version 11.9.0 is working fine. This MAY only be a problem when you run with `--skip-lock`, but I haven't verified that, since #1906 is blocking me from using lock file.

If I install with debug flag it works fine: `pipenv install -d --skip-lock`

```
Executing command: pipenv --rm ; pipenv install --skip-lock -v

Removing virtualenv (/home/andreas/.virtualenvs/my-project-UpnTMLUq)…
Creating a virtualenv for this project…
Using /usr/bin/python3.6m (3.6.3) to create virtualenv…
⠋Running virtualenv with interpreter /usr/bin/python3.6m
Using base prefix '/usr'
New python executable in /home/andreas/.virtualenvs/my-project-UpnTMLUq/bin/python3.6m
Also creating executable in /home/andreas/.virtualenvs/my-project-UpnTMLUq/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/andreas/.virtualenvs/my-project-UpnTMLUq
Installing -e .…
⠙Installing '-e .'
$ "/home/andreas/.virtualenvs/my-project-UpnTMLUq/bin/pip" install   --verbose    -e "." -i https://pypi.python.org/simple --exists-action w
Obtaining file:///home/andreas/code/my-project
  Running setup.py (path:/home/andreas/code/my-project/setup.py) egg_info for package from file:///home/andreas/code/my-project
    Running command python setup.py egg_info
    running egg_info
    writing company.my_project.egg-info/PKG-INFO
    writing dependency_links to company.my_project.egg-info/dependency_links.txt
    writing top-level names to company.my_project.egg-info/top_level.txt
    reading manifest file 'company.my_project.egg-info/SOURCES.txt'
    writing manifest file 'company.my_project.egg-info/SOURCES.txt'
  Source in /home/andreas/code/my-project has version 0.1, which satisfies requirement company.my-project==0.1 from file:///home/andreas/code/my-project
Installing collected packages: company.my-project
  Running setup.py develop for company.my-project
    Running command /home/andreas/.virtualenvs/my-project-UpnTMLUq/bin/python3.6m -c "import setuptools, tokenize;__file__='/home/andreas/code/my-project/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps
    running develop
    running egg_info
    writing company.my_project.egg-info/PKG-INFO
    writing dependency_links to company.my_project.egg-info/dependency_links.txt
    writing top-level names to company.my_project.egg-info/top_level.txt
    reading manifest file 'company.my_project.egg-info/SOURCES.txt'
    writing manifest file 'company.my_project.egg-info/SOURCES.txt'
    running build_ext
    Creating /home/andreas/.virtualenvs/my-project-UpnTMLUq/lib/python3.6/site-packages/company.my-project.egg-link (link to .)
    Adding company.my-project 0.1 to easy-install.pth file

    Installed /home/andreas/code/my-project
Successfully installed company.my-project
Cleaning up...

Adding -e . to Pipfile's [packages]…
/usr/local/lib/python2.7/dist-packages/pipenv/utils.py:1258: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-VYzejO-requirements'>
  warnings.warn(warn_message, ResourceWarning)
```

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.0'`

Pipenv location: `'/usr/local/lib/python2.7/dist-packages/pipenv'`

Python location: `'/usr/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.12`: `/usr/bin/python`
  - `2.7.12`: `/usr/bin/python2`
  - `3.5.2`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.4.0-119-generic',
 'platform_system': 'Linux',
 'platform_version': '#143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018',
 'python_full_version': '2.7.12',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `LC_NUMERIC`
  - `MANDATORY_PATH`
  - `CONSCRIPT_OPTS`
  - `_LXSESSION_PID`
  - `XDG_GREETER_DATA_DIR`
  - `SPARK_HOME`
  - `PROJECT_HOME`
  - `LC_CTYPE`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_CURRENT_DESKTOP`
  - `LC_PAPER`
  - `LOGNAME`
  - `XDG_SEAT`
  - `PATH`
  - `XDG_VTNR`
  - `QT_PLATFORM_PLUGIN`
  - `PYTHONUNBUFFERED`
  - `VIRTUALENVWRAPPER_SCRIPT`
  - `ZSH`
  - `DISPLAY`
  - `XDG_SESSION_DESKTOP`
  - `LANG`
  - `company_CFG_DIR`
  - `TERM`
  - `SHELL`
  - `XDG_SESSION_PATH`
  - `XAUTHORITY`
  - `LANGUAGE`
  - `SHLVL`
  - `QT_QPA_PLATFORMTHEME`
  - `TERMINATOR_UUID`
  - `PIP_REQUIRE_VIRTUALENV`
  - `WINDOWID`
  - `_`
  - `SSH_AGENT_PID`
  - `HOME`
  - `LC_MONETARY`
  - `XDG_CONFIG_HOME`
  - `SAL_USE_VCLPLUGIN`
  - `CONSCRIPT_HOME`
  - `XDG_RUNTIME_DIR`
  - `WORKON_HOME`
  - `VIRTUALENVWRAPPER_PROJECT_FILENAME`
  - `LC_ADDRESS`
  - `SSH_AUTH_SOCK`
  - `VIRTUALENV_PYTHON`
  - `GDMSESSION`
  - `VIRTUALENVWRAPPER_WORKON_CD`
  - `company_CFG_HOME`
  - `IBUS_DISABLE_SNOOPER`
  - `XDG_SEAT_PATH`
  - `PIP_PYTHON_PATH`
  - `XDG_SESSION_ID`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `ORBIT_SOCKETDIR`
  - `VIRTUALENVWRAPPER_HOOK_DIR`
  - `LC_IDENTIFICATION`
  - `DESKTOP_SESSION`
  - `LSCOLORS`
  - `XDG_CONFIG_DIRS`
  - `DEFAULTS_PATH`
  - `XDG_SESSION_TYPE`
  - `OLDPWD`
  - `LS_COLORS`
  - `GDM_LANG`
  - `LC_TELEPHONE`
  - `LC_MEASUREMENT`
  - `PWD`
  - `COLORTERM`
  - `LC_NAME`
  - `XDG_MENU_PREFIX`
  - `LC_TIME`
  - `LESS`
  - `PAGER`
  - `XDG_DATA_DIRS`
  - `USER`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/andreas/.conscript/bin:/opt/spark-2.2.1/bin:/opt/flink/bin:/home/andreas/activator-dist-1.3.12/bin:/home/andreas/bin:/home/andreas/bin:/home/andreas/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/andreas/code/my-project`

---------------------------

Contents of `Pipfile` ('/home/andreas/code/my-project/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
pytest = "==3.3.2"
asynctest = "*"
aiopubsub = "==1.0.0"

[packages]
aio-pika = "==1.8.1"
deepdiff = "==3.3.0"
pika = "*"
async_timeout = "*"
async_generator = "*"
spacy = "*"
"e1839a8" = {path = ".", editable = true}

[requires]
python_version = "3.6"

```

</details>

**Comment by techalchemy** [comment]
Closing in favor of #1973 / #1974
