### ISSUE TITLE
mercury CI is always failing

### ISSUE THREAD

**Issue by hroncok** [pypa/pipenv#1990]
I've open several pull requests during past couple of days. yet the mercury CI is still failing with "0 tests run, 0 skipped, 0 failed."

**Comment by techalchemy** [comment]
Yeah, it's an extra CI build server in Kenneth's living room.  I'm pretty sure there's some extra process that happens and I'm not totally clear on why it's failing, but you can click through to see the test results (they are actually all good, usually)
