### ISSUE TITLE
pipenv install -e break with pip10

### ISSUE THREAD

**Issue by gsemet** [pypa/pipenv#1999]
I have the following error on pipenv (latest version) now pip has updated to pip10:
```
Installing -e ./deps/mysubmod…

Error:  An error occurred while installing -e ./deps/mysubmod!
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
ImportError: cannot import name 'main'
```

I have this same issue when I try to use `pip` or `pip3` directly on my system.

Using `python3 -m pip` instead of `pip` solve this issue, but this needs to be fixed inside the pipenv code.

System Ubuntu 16.04
pip: 10
pipenv 11.10
inside a docker image (so env is clean)

**Comment by techalchemy** [comment]
your path is preferring `/usr/local/bin/pip` as a binary which is not up to date.  Please `sudo python3 -m pip install --upgrade pip`

**Comment by techalchemy** [comment]
I have a fix incoming
