### ISSUE TITLE
pipenv doesnt work with pip 10

### ISSUE THREAD

**Issue by kakulukia** [pypa/pipenv#2009]
pkg_resources.DistributionNotFound: The 'pip>=9.0.1' distribution was not found and is required by pipenv
$ pip --version
pip 10.0.0 from .../python3.6/site-packages/pip (python 3.6)

**Comment by uranusjr** [comment]
Please provide detailed information. I cannot reproduce anything with information this scarce. Follow the issue template at least.

**Comment by uranusjr** [comment]
Do you mean you have Pip 10 globally, or in the virtualenv? If it’s global (my guess), try force-reinstalling pip with the `--ignore-installed` option. `pkg_resources` can be confused if the installation is not completely successful.

Also you might want to make sure pip and Pipenv are actually installed to the same Python (I can’t tell from the `...` part).

**Comment by kakulukia** [comment]
Okay, somehow the pip upgrade totally broke pipenv. After manually removing all pipenv stuff from my disc and installing pipenv again it works.

Weird!

**Comment by uranusjr** [comment]
@afs2015 The image not found error indicates your virtualenv is broken (likely because you create it from Homebrew Python and a `brew upgrade` and/or `brew clean` broke it). You need to recreate it.

Also, don’t create virtualenvs against Homebrew Python. They break.

**Comment by afs2015** [comment]
@uranusjr Thanks! Recreating the virtualenv did the trick. I'll avoid creating virtualenvs against Homebrew Python in the future.
