### ISSUE TITLE
Clean unused arguments/options of `pipenv sync`

### ISSUE THREAD

**Issue by frostming** [pypa/pipenv#2010]
There exist many arguments & options unused in `pipenv sync`/`do_sync`, which need to be cleaned up. But before doing that, I'd like to list them below to see whether they should be axed or preserved for future features.

- [x] `install`. Actually `install` command passed in, not used. **To be removed**
- [x] `dry_run`. Perhaps we should add this feature, listing the packages not updated or installed. **To be implemented**
- [x] `bare`  **Remain**
- [x] `dont_upgrade`. Same as `keep_outdated`? Need to redesign the current logic, **To be removed**
- [x] `user`. I don't know what does it mean.  **To be removed**
- [x] `clear`. Not used, dependency resolution isn't performed in sync.  **To be removed**
- [x] `unused`  **To be removed**

**Comment by techalchemy** [comment]
@frostming are you hoping to establish the issues here or are you planning to move forward cleaning this up? /cc @ncoghlan

**Comment by frostming** [comment]
I will get to it in a couple of days.

**Comment by techalchemy** [comment]
No rush just wasn’t sure if you were looking for more dialog or identifying issues or outlining your plan

**Comment by frostming** [comment]
It will be good if you guys take a look at the plan, any advice is appreciated.

**Comment by frostming** [comment]
Close in honor of #2211
