### ISSUE TITLE
Error when call Pipenv == 11.10 on Windows

### ISSUE THREAD

**Issue by FlavioCestari** [pypa/pipenv#2017]
When I call "pipenv" at the Windows command prompt I get the an error.
This problem and others occurs only with the new PIP version 10.0.0!

> Please run `$ python -m pipenv.help`, and paste the results here.
```
C:\Users\cestarfl>python -m pipenv.help
<details><summary>$ python -m pipenv.help output</summary>
Pipenv version: `'11.10.0'`
Pipenv location: `'C:\\Program Files\\Python36\\lib\\site-packages\\pipenv'`
Python location: `'C:\\Program Files\\Python36\\python.exe'`
Other Python installations in `PATH`:
  - `3.6`: `C:\Program Files\Python36\python.exe`
  - `3.6.5`: `C:\Program Files\Python36\python.exe`
  - `3.6.5`: `C:\Windows\py.exe`

PEP 508 Information:
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '7',
 'platform_system': 'Windows',
 'platform_version': '6.1.7601',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'win32'}
```

------------

##### Expected result

Show Pipenv Help, like: "python -m pipenv"

##### Actual result

```
C:\Users\cestarfl>pipenv
Fatal error in launcher: Unable to create process using '""c:\program files\python36\python.exe"  "C:\Program Files\Python36\Scripts\pipenv.exe" '
```
PS: Pay attention to the double quotation marks before the python path.

##### Steps to replicate

Just type "pipenv" + [ENTER].

**Comment by techalchemy** [comment]
@FlavioCestari  see https://github.com/pypa/pip/issues/5223 -- this is a problem with pip10 on windows 7x64 using `cmd.exe` and will be fixed in pip 10.0.1 which should be released soon

In the meantime, you can fix it by running `python -m pip install pip==9.0.3`
