### ISSUE TITLE
The cousin of pipenv shell doesn't activate env

### ISSUE THREAD

**Issue by Chris-May** [pypa/pipenv#2023]
I somehow doubt this is an issue with `pipenv`, as it works as expected on the Windows7 machine at work. But on my OSX 10.12.6, with `pyenv`-installed pythons and homebrew-installed `pipenv`, issues arise:

I create a .venv with `pipenv` and run `pipenv shell`, but the virtual environment doesn't activate... `python` and `pip` are still the global commands.

I could use some help figuring what I did wrong.

------------
Please run `$ python -m pipenv.help`, and paste the results here.
```
/usr/bin/python: No module named pipenv
```
(This is output after `pipenv shell`)

------------

##### Expected result

Running `pipenv shell` should let you run `python` and `pip` being the commands from within the environment.

##### Actual result

`python` and `pip` use the global commands.

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

```
~ » mkdir temp
~ » cd temp
temp » pipenv --python 3.6
Creating a virtualenv for this project…
Using /usr/local/bin/python3.6m (3.6.5) to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python3.6m
Using base prefix '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/chrisdev/temp/.venv/bin/python3.6
Also creating executable in /Users/chrisdev/temp/.venv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/chrisdev/temp/.venv
Creating a Pipfile for this project…
temp » pipenv shell
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
temp » python --version
Python 2.7.10
temp » python3 --version
Python 3.6.5
temp » pipenv --py
/Users/chrisdev/temp/.venv/bin/python
temp » which python3
/usr/local/bin/python3
temp » which python
/usr/bin/python
temp » echo $PATH
/usr/local/opt/sqlite/bin:.:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin
temp » which pip
/usr/local/bin/pip
temp » echo $VIRTUAL_ENV
/Users/chrisdev/temp/.venv
```

**Comment by techalchemy** [comment]
I think the answer is taht you have `python` on your path in only one place: `/usr/bin`, and `/usr/local/bin` only has `python3` -- I know nothing about homebrew installations (I recommend searching closed issues here because they come up a lot) but I would recommend adding `~/.local/bin` as a directory and then running `ln -s /usr/local/bin/python3 ~/.local/bin/python` and then setting up your `~/.profile` or whatever to do `export PATH=~/.local/bin:$PATH` although in bash i think you need to type out the full expansion of `~`

**Comment by Chris-May** [comment]
Thanks, Dan. Sadly, I have no `~/.local/bin`. All I have in `~/.local` is `~/.local/share`. But I'm looking in to see what else is going on. Thank you for your help.

FWIW, this is what I get when I run `python -m pipenv.help`:
<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.0'`

Pipenv location: `'/Users/chrisdev/foo/.venv/lib/python3.6/site-packages/pipenv'`

Python location: `'/Users/chrisdev/foo/.venv/bin/python'`

Other Python installations in `PATH`:

  - `2.6`: `/usr/bin/python2.6`
  - `2.6`: `/usr/bin/python2.6`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/chrisdev/foo/.venv/lib/python3.6/site-packages/pipenv/help.py", line 89, in <module>
    main()
  File "/Users/chrisdev/foo/.venv/lib/python3.6/site-packages/pipenv/help.py", line 24, in main
    found = find_python_in_path(python_v)
  File "/Users/chrisdev/foo/.venv/lib/python3.6/site-packages/pipenv/core.py", line 355, in find_python_in_path
    version = python_version(p)
  File "/Users/chrisdev/foo/.venv/lib/python3.6/site-packages/pipenv/utils.py", line 218, in python_version
    return u'{major}.{minor}.{micro}'.format(**version)
TypeError: format() argument after ** must be a mapping, not NoneType
</details>

**Comment by techalchemy** [comment]
@Chris-May no I understood that already I am telling you to create that directory and run the command I provided.

**Comment by Chris-May** [comment]
Sorry, Dan. I was way too tired when I read your comment. I'll jump on that when I get back to that computer. Thanks again for helping out!

**Comment by Chris-May** [comment]
I'm sorry, Dan. Something tells me I messed something up with this user. It's still not working.
```
» pipenv --python 3.5
Creating a virtualenv for this project…
Using /Users/chrisdev/.pyenv/versions/3.5.2/bin/python3.5m (3.5.2) to create virtualenv…
⠋Running virtualenv with interpreter /Users/chrisdev/.pyenv/versions/3.5.2/bin/python3.5m
Using base prefix '/Users/chrisdev/.pyenv/versions/3.5.2'
New python executable in /Users/chrisdev/temp/.venv/bin/python3.5m
Also creating executable in /Users/chrisdev/temp/.venv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/chrisdev/temp/.venv
Creating a Pipfile for this project…
temp » python --version
Python 3.6.5
temp » pipenv shell
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
temp » python --version
Python 3.6.5
temp » pipenv --py
/Users/chrisdev/temp/.venv/bin/python
temp » .venv/bin/python --version
Python 3.5.2
```

```
» echo $PATH
/Users/chrisdev/.local/bin:/Users/chrisdev/.pyenv/shims:/usr/local/opt/sqlite/bin:.:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/bin
```

**Comment by techalchemy** [comment]
So do you have pipenv installed with homebrew? Can you give us the output of `pipenv --version` and `which pipenv`

**Comment by Chris-May** [comment]
Sure thing! Sorry for the delay.
```
» pipenv --version
pipenv, version 11.10.0
» which pipenv
/usr/local/bin/pipenv
```

**Comment by techalchemy** [comment]
Ah you have pyenv but that’s not where pipenv is! Can you get rid of that version of pipenv somehow and install it via the pyenv python? Sorry I know almost nothing about Mac but I’m guessing that will fix everything

**Comment by Chris-May** [comment]
AH! Thank you so very much!!! I would never have figured all of this out without you!!!

**Comment by Chris-May** [comment]
Turns out it's still not working. But I started a new user and it worked good there.
It's so weird. My default python is system (though it's managed by pyenv), but it somehow doesn't have pip. (Which I'm pretty sure it should)

**Comment by techalchemy** [comment]
Is this seriously the case? I'm not sure if that's impressive or disturbing... at least you can't `sudo pip install...` and have things wind up in your system folders

**Comment by Chris-May** [comment]
I'm sorry, I'm still missing something, so I'm opening this again, looking for help.
I found that homebrew's python2 was the first python on my path, and removed that thinking I was home free. But still, I can't solve this riddle.

`pyenv global` is set to `system`.

```
» pipenv --python 3.5
Creating a virtualenv for this project…
Using /Users/chrisdev/.pyenv/versions/3.5.2/bin/python3.5m (3.5.2) to create virtualenv…
⠋Running virtualenv with interpreter /Users/chrisdev/.pyenv/versions/3.5.2/bin/python3.5m
Using base prefix '/Users/chrisdev/.pyenv/versions/3.5.2'
New python executable in /Users/chrisdev/foo/.venv/bin/python3.5m
Also creating executable in /Users/chrisdev/foo/.venv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/chrisdev/foo/.venv
Creating a Pipfile for this project…
foo » pipenv install requests
Installing requests…
Collecting requests
 ...
Installing collected packages: idna, certifi, chardet, urllib3, requests
Successfully installed certifi-2018.4.16 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22

Adding requests to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (0b4483)!
Installing dependencies from Pipfile.lock (0b4483)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 5/5 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell
» pipenv shell
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
» python --version
Python 2.7.14
» echo $PATH
/Users/chrisdev/.pyenv/shims:/Users/chrisdev/.pyenv/bin:/usr/local/opt/sqlite/bin:.:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/.local/bin
»
```


<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.1'`

Pipenv location: `'/usr/local/Cellar/pipenv/11.10.1/libexec/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/11.10.1/libexec/bin/python'`

Other Python installations in `PATH`:

  - `2.6`: `/usr/bin/python2.6`
  - `2.6`: `/usr/bin/python2.6`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/Users/chrisdev/.pyenv/shims/python3.5`
  - `3.6`: `/Users/chrisdev/.pyenv/shims/python3.6m`
  - `3.6`: `./python3.6`
  - `3.6`: `/Users/chrisdev/.pyenv/shims/python3.6`
  - `3.6`: `./python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `3.6.5`: `./python`
  - `3.6.5`: `/Users/chrisdev/.pyenv/shims/python`
  - `3.6.5`: `./python`
  - `2.7.14`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `3.6.5`: `/usr/local/opt/python/libexec/bin/python`
  - `2.7.14`: `/usr/local/bin/python2`
  - `3.6.5`: `./python3`
  - `3.6.5`: `/Users/chrisdev/.pyenv/shims/python3`
  - `3.6.5`: `./python3`
  - `3.6.5`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '16.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST '
                     '2018; root:xnu-3789.73.11~1/RELEASE_X86_64',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `TERM`
  - `SHELL`
  - `PIPENV_VENV_IN_PROJECT`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `PYENV_VERSION`
  - `ZSH`
  - `USER`
  - `COMMAND_MODE`
  - `SSH_AUTH_SOCK`
  - `PYENV_DIR`
  - `__CF_USER_TEXT_ENCODING`
  - `PAGER`
  - `LSCOLORS`
  - `PATH`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `PYENV_SHELL`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `PIPENV_SHELL_FANCY`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `LC_CTYPE`
  - `SECURITYSESSIONID`
  - `COLORTERM`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `True`
 - `PIPENV_SHELL_FANCY`: `True`

Debug–specific environment variables:

  - `PATH`: `.:/usr/local/Cellar/pyenv/1.2.3/libexec:/Users/chrisdev/.pyenv/shims:/Users/chrisdev/.pyenv/bin:/usr/local/opt/sqlite/bin:.:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/.local/bin:/usr/local/opt/python/libexec/bin`
  - `SHELL`: `/usr/local/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/usr/local/Cellar/pipenv/11.10.1/libexec/bin`


---------------------------

</details>

**Comment by Chris-May** [comment]
As I was driving to work, I was wondering if this has anything to do with `pyenv`... It seems it shouldn't, but I've seen other issues about "`pipenv` not respecting `pyenv`'s `global` python.

I was hoping that having `pyenv global` set to `system` would more or less mean that it would be doing no active managing of python. (Which makes sense to me since 2.7.14 id homebrew's python2.)

And I don't think I can set `pyenv local` to `.venv/bin/python`.

Really, I guess it comes down to something seems quite off with my user.

**Comment by techalchemy** [comment]
Stop using your system python. Don’t set pyenv global to system. Don’t set your path to point at system python. It doesn’t matter _how_, but if you tell your machine to point at your systems broken, non-pipenv-installed python then you can’t use pipenv

**Comment by Chris-May** [comment]
I'm sorry @techalchemy. I wasn't aware I was doing this wrong from reading the docs w/r/t installing pipenv via homebrew.

**Comment by techalchemy** [comment]
@Chris-May yeah we need to fix those, that's all on us and not on you, we deal with a ton of issues related to homebrew but I have no idea who maintains the pipenv release there or how it works or anything, I don't use or have access to a mac myself

**Comment by Chris-May** [comment]
@techalchemy I can only imagine how much you have to go through supporting this tool.

Going through this experience, I now "get it"... or so I think... It now makes sense why I was having that issue, but I would never had guessed (nor realized from reading other issues) that I would need homebrew's python central to my workflow.

Thanks for all your help!!

For anyone reading this far, to resolve my own issue, I removed the brew-installed pipenv and `pip install pipenv` on my system python (which is actually homebrew's `python@2`). Now it works like a charm.
