### ISSUE TITLE
Pipenv install fails with traceback on Ubuntu 16.04.4

### ISSUE THREAD

**Issue by Chris-May** [pypa/pipenv#2025]
I am converting an already-running django project on an Ubuntu server over to `pipenv`. I converted my `requirements.txt` file over to `Pipfile` and `Pipfile.lock` on my local system, and it's running fine. When I ssh into the server, pull down my code, and run `pipenv install`, the system can hang for over 30 minutes (usually I stop the VM after a few minutes).

Please run `$ python -m pipenv.help`, and paste the results here.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.0'`

Pipenv location: `'/home/innovationuser/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv'`

Python location: `'/home/innovationuser/.pyenv/versions/3.6.4/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
Traceback (most recent call last):
  File "/home/innovationuser/.pyenv/versions/3.6.4/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/innovationuser/.pyenv/versions/3.6.4/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/innovationuser/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/help.py", line 89, in <module>
    main()
  File "/home/innovationuser/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/help.py", line 24, in main
    found = find_python_in_path(python_v)
  File "/home/innovationuser/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/core.py", line 355, in find_python_in_path
    version = python_version(p)
  File "/home/innovationuser/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/utils.py", line 218, in python_version
    return u'{major}.{minor}.{micro}'.format(**version)
TypeError: format() argument after ** must be a mapping, not NoneType

</details>

------------

##### Expected result

Create a new .venv with dependencies.

##### Actual result

Hangs the server for 30+ minutes with what seems to be pegged disk read bytes (nearly 200MB/min) (minimal network activity and <10% CPU usage). 

The console returned this: https://pastebin.com/Rn5v7T01

I piped `pipenv install` into a log file and got this: https://pastebin.com/GUsEA11b

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

```
> pipfile install
```

###### Pipfile:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"Fabric3" = "*"
wagalytics = "*"
wagtail = "*"
wagtailfontawesome = "*"
wagtailmenus = "*"
django-debugtools = "*"

[dev-packages]

[requires]
python_version = "3.5.2"
```

**Comment by techalchemy** [comment]
@Chris-May I think you generated at least part of this pipfile by hand, because `python_version` is only ever allowed to be a short version (e.g. `3.5` in this case) -- we have better messaging in the coming point release but this is likely part of the problem.

**Comment by techalchemy** [comment]
As for the other bug we have already pushed a fix and will have a release out very soon, just need to rerun tests now that pip 10.0.1 is out

**Comment by Chris-May** [comment]
Awesome! Thanks!
