### ISSUE TITLE
Determining double requirement sources

### ISSUE THREAD

**Issue by jamesstidard** [pypa/pipenv#2027]
I have a project which is currently getting a Double requirement failure. My Pipfile contains a `numpy = "*"` entry and a number of dependancies listed will also have sub depednaancies of numpy. There are quire a few dependancies in this project so I was wondering if there is an easier was of checking which packages are causing the conflict - without manually inspecting all of their `setup.py`'s.

The errpr I get at the moment looks like:

``` bash
Double requirement given: numpy==1.12.1 from https://files.pythonhosted.org/packages/02/64/c6c1c24ff4dbcd789fcfdb782e343ac23c074f6b8b03e818ff60eb0f937f/numpy-1.12.1-cp34-cp34m-manylinux1_x86_64.whl#sha256=4eac5f2f624c5e7eecbdb51395ff39a099c48cab607a158f16f288c6fe39a2b3 (already in numpy==1.9.3 from https://files.pythonhosted.org/packages/fc/1b/a1717502572587c724858862fd9b98a66105f3a3443225bda9a1bd16ee14/numpy-1.9.3-cp34-cp34m-manylinux1_x86_64.whl#sha256=bff36563f9d6a06a81ae232f49d2946c84c05e391a7dff057496033c79507860, name='numpy')
```

**Comment by techalchemy** [comment]
I think this must be new as of pip 10. Just try running `pipenv lock` first

**Comment by jamesstidard** [comment]
I've have narrowed this down to an issue with python 3.4 and `pandas>=0.21.0` and opened a ticket [over there](https://github.com/pandas-dev/pandas/issues/20764).

Thanks
