### ISSUE TITLE
pipenv, serialized objects, reproducibile workflow

### ISSUE THREAD

**Issue by LukeMathWalker** [pypa/pipenv#2028]
Good morning!

After having spent the last three or four days reviewing all possible tools to manage Python environments and dependencies I have finally come to pipenv: it seems to be in a good position to solve my problem but I have a final dilemma to solve.

We have three repos - a library and two applications.
The library is used by the first application to train a machine learning model, which is then serialized using `joblib`.
The second application is meant to serve the model behind a RESTful API - to do so it needs to be able to reproduce the exact environment used by the first application to train the model, otherwise it might fail to deserialize it or the resulting behaviour might differ. 

The first (dirty) solution that I have come up with is:
- merge the two applications in a single repository; 
- merge their `Pipfile`s;
- install the merged `Pipfile`;
- train+serialize the model;
- commit the resulting `Pipfile.lock` to git; 
- fetch the commit with the `Pipfile.lock` used to train the model and install all dependencies from the frozen `Pipfile.lock` when I have to serve the model.

This is of course suboptimal: the two applications serve different purposes, and I am installing a lot of unnecessary dependencies at training time (when I don't need Flask, etc.).

Is there a way to let my second application depend on my first application in order to install everything as specified in first application `Pipfile.lock` plus the missing libraries required to do the serving job?

**Comment by techalchemy** [comment]
Yes of course! But, only if it is a proper python package — that is, you have configured it with a `setup.py`. If you have, you can just `pipenv install -e ../some/other/place` and it will be taken care of

**Comment by techalchemy** [comment]
Pipenv installs what’s in your pipfile or lockfile. If there’s a lockfile it will look no further unless there is a difference between what it has as the hash of your pipfile and what it gets when it hashes your pipfile.

You don’t need to pin versions in `setup.py` because this stuff is all resolved in the lockfile and pinned there.  As long as you have a lockfile pipenv won’t look at this (unless your lockfile is out of date and you don’t pass `—deploy` or `—ignore-pipfile`)

**Comment by techalchemy** [comment]
If that leaves some things unclear I can help clear them up, I realize the specific details are probably incredibly important for your use case

**Comment by LukeMathWalker** [comment]
This is not what seems to be happening...?
Just for the sake of testing, I added a dependency in `Pipfile` which is not in `setup.py` (i.e. `Flask`).
When I do 
```
pipenv install -e ../ApplicationA
```
from ApplicationB's folder there is no trace of Flask in the resulting `Pipfile.lock` while `Flask` is in ApplicationA's `Pipfile.lock`.

**Comment by techalchemy** [comment]
Like I said before, pipenv does not look at other lockfiles besides the current project lockfile. It looks only at setup.py. If you have an application install dependency for application A (a top level install dependency, you don’t have to pin a specific version), you put it in the `setup.py` `install_requires` section. Pipenv looks _only_ at the current project pipfile and lockfile. It will _never_ introspect pipfiles or lockfiles outside of the current project

Think of it like this:
**Pipenv**: tool for writing and developing and deploying stuff. Software developers use it to recreate dev and testing and prod environments precisely. Has strict boundaries at the project border, is never read or interpreted anywhere besides local to the current project. Not merged with other pipfiles or dependency graphs. 

**Setup file**: application management — tool for distributing or installing an application, used to instruct another environment or user how to install your application. Is resolved by pipenv, pip, etc.

**Comment by LukeMathWalker** [comment]
Got it. Then I am back to the initial problem: how do I ensure that I can deserialize and use `model.pkl` in ApplicationB if it was generated by ApplicationA and I can't trust the environment I obtain by listing ApplicationA in ApplicationB's `Pipfile` as a requirement unless I pin down the versions of all packages in ApplicationA's `setup.py`?

That's why I wanted to "depend" on ApplicationA's `Pipfile.lock`.

**Comment by techalchemy** [comment]
@LukeMathWalker so to understand your workflow a bit better:

1. You run Application A and generate a lockfile and a model
2. You then go to application B and deserialize the model generated separately at some other time by application A?

This seems like a flow problem.  Why not just put the unpinned dependencies of Application A in the setup file, install Application A in Application B's Pipfile, and then inside Application B run Application A to build the model in the first place? Then at some later time you can do the rest of whatever it is you need to do.

```console
ApplicationB $ pipenv install ../ApplicationA
...
ApplilcationB $ pipenv run ApplicationA train_model
ApplicationB $ pipenv run ApplicationA deserialize_model trained_model.pkl
```

If this doesn't make sense, it would be really helpful to have a similar example as to why these workflows don't fit what you're trying to do (I'm not in the ML space at all so I'm not totally sure on this) -- it's possible we're talking past each other, it's possible that there's an existing workflow that would make sense for you to use, or it's possible that you are using these tools in a way that we didn't plan for.  Lets figure it out :)

**Comment by LukeMathWalker** [comment]
The flow you suggest might actually work for my use-case! My bad for not having thought about it in the first place ^^"

The only drawback I see for this workflow in the ML area is if we were to have multiple serving services for the same model.
This workflow would require us to retrain the model N times if we have N serving services - undesirable, considering that training if very often a quite expensive process. It would be nice, in that case, to have a way to simply "add stuff on top of an existing `Pipfile.lock`" if there exists a way to make the new packages compatible with the ones frozen in `Pipfile.lock`, which is what I was trying to do in the first place.

**Comment by techalchemy** [comment]
adding stuff on top of a lockfile sounds pretty much like packaging to me in which case you'd want a `setup.py` -- sometimes you want to pin those dependencies.
