### ISSUE TITLE
pipenv --system --ignore-pipfile still updates the lockfile

### ISSUE THREAD

**Issue by bitdivision** [pypa/pipenv#2032]
When using the `--system` flag, the `--ignore-pipfile` flag does not work.
------------

##### Expected result

I expected the packages from the lockfile to be installed, and the lockfile not to be updated.

##### Actual result
```
Pipfile.lock (895be3) out of date, updating to (5038ce)…
```
##### Steps to replicate

`pipfile --system --ignore-pipfile` prints `Pipfile.lock (895be3) out of date, updating to (5038ce)…`, where `pipfile --ignore-pipfile` does not.

**Comment by techalchemy** [comment]
`—system` is not compatible with most other flags. Pipenv requires an isolated environment to do resolution. The flag that does what you want in combination is `—system —deploy`. Please see the docs for more info. We have improved error messaging in the next release.

**Comment by bitdivision** [comment]
@techalchemy - That's what I tried originally, however I still see:

```Pipfile.lock (895be3) out of date, updating to (5038ce)…
Locking [dev-packages] dependencies```

in the output when running `pipenv install --system --deploy`

**Comment by techalchemy** [comment]
Oh ... that might be a bug with the current release then. I think we fixed this in #2006 but feel free to confirm by installing pipenv from master. Hoping to cut a release today

**Comment by bitdivision** [comment]
I have indeed confirmed that this is fixed in master.

Thanks

**Comment by bitdivision** [comment]
@techalchemy Not sure if I should make another issue for this, but is there any chance that `--system --ignore-pipfile` will be supported in future?

The use case here is that in CI, we don't want to fail if the lock file is out of date, but we also don't want to wait for pipenv to update it (which takes a very long time).

**Comment by techalchemy** [comment]
@bitdivision this behavior should be implicit if you `pip install —upgrade —pre pipenv` (releasing tomorrow if we don’t hit major issues)
