### ISSUE TITLE
Suggestion: [optional-packages] and [suggested-packages]

### ISSUE THREAD

**Issue by adaliszk** [pypa/pipenv#2036]
I've recently found this tool and it completely changed my workflow, I feel like I have a proper NPN or  PHP's composer for Python with virtualenv management built it. I've really liked that you can specify optional and suggested packages in composer and I wish to suggest that functionality for this really great tool:

The optional packages usually don't require for the project to run or develop but they could enhance the experience mostly for development but some cases to the environment as well. A good example could be: `django-debug-toolbar`, `ipython`, the optional packages for `djangorestframework`. I'm sure there is more but I just only used django in my first 6 month so far :smile: 

Suggested packages are a subtype of the optional packages, they just a hook to make a note after you firstly installed the project from the really important options.

Both options behave just like the `[dev-packages]` but with a different flag.

Thoughts, Ideas, Opinions are welcomed!

**Comment by glenfant** [comment]
Great idea, I need this too for a couple of projects. Example for adding an optional package in a "faster" optional group:

pipenv install --opt-group=faster ujson

Installing standard packages and "faster" optional packages in a fresh environment (after git clone) :

pipenv install --opt-groups=faster,other_group

**Comment by techalchemy** [comment]
Thanks for the suggestion! We’ve discussed expanding the Pipfile in the past but I believe we currently want to hold firm to the two sections for simplicity and to guard against feature creep.

Feel free to file this against the Pipfile repository, though they move much slower and aren’t likely to change the spec there either

**Comment by techalchemy** [comment]
Closing for now. We may revisit in the future
