### ISSUE TITLE
Are there plans to bundle pipenv with a future release of Python?

### ISSUE THREAD

**Issue by johnthagen** [pypa/pipenv#2039]
`pipenv` is a fabulous tool, something Python's been missing for years. Are there any plans to bundle `pipenv` with future releases of Python 3 similar to how `pip` is bundled? This would make using `pipenv` that much easier for users and also reinforce that this is the official tool for the job.

Is `pipenv` still relatively unstable, and that is part of the reason not to bundle?

It would be great to have `pipenv` always available similar to how Rust comes with `cargo` out of the box.

**Comment by uranusjr** [comment]
This is not for us to decide. Draft a PEP and or raise a discussion on [python-dev](https://mail.python.org/mailman/listinfo/python-dev) instead.

**Comment by techalchemy** [comment]
@johnthagen to elaborate a bit further, and I believe @ncoghlan has addressed this also, this is a great idea but pipenv is very new and python really only ships with things that are very stable.  We are a part of the ecosystem and we are working collaboratively with the entire PyPA as much as possible, we have a core dev on the team (if you are going to draft a PEP he would be the person to work with as the primary BDFL delegate on packaging issues usually)

To answer your question -- are there any plans? No, there are no concrete plans for this, although I guess it's probably a good long term goal.  We are not anywhere near there at this point (they only _just_ started bundling pip), so we are more focused on building the tool

**Comment by ncoghlan** [comment]
@techalchemy Describing "4 years ago" as "just" is a postitively stdlib-esque perception of the passage of time ;) (Not that I disagree, it's just a different perspective on time scales from the one that drives a lot of developer tooling)

As for whether we'll ever bundle `pipenv` with the stdlib there's actually two answers to that based on timeline:

1. Right now, the answer is "No", for simple reasons of maturity - both `pipenv` and the `Pipfile` and `Pipfile.lock` formats are still very new, and we'd want all of them to be clearly stable before promoting them from "recommended in a packaging.python.org tutorial" to "installed by default with the reference interpreter".
2. Longer term, exactly what we do will depend in part on the exact form that `pip`'s native `Pipfile` and `Pipfile.lock` support ends up taking (see https://github.com/pypa/pipfile/issues/108 for more on that), and also on whether or not we can get the `pip install pipenv` UX to the "it just works" level (see https://github.com/pypa/python-packaging-user-guide/issues/396 and https://github.com/pypa/python-packaging-user-guide/issues/394 for some discussion of the problems both with getting installed scripts to work reliably in general, as well as with the reasons why `pipenv` isn't a full replacement for direct use of `pip`)

**Comment by johnthagen** [comment]
Thank you @uranusjr, @techalchemy, and @ncoghlan for the detailed explanations!
