### ISSUE TITLE
Dependencies for locally installed distributions are not being taken into account

### ISSUE THREAD

**Issue by mvaled** [pypa/pipenv#2040]
Installing locally defined distributions doesn't properly process (and lock) their dependencies.  Steps to reproduce:

1. Create a new project `penv2_bug`

2. Create `penv2_bug/foo/setup.py`, with content:

```python
from setuptools import setup

setup(
    name='foo',
    version='1.0',
    py_modules=['foo'],
    install_requires=[
        'xoutil>=1.8,<2.0',
    ]
)
```

3. Create the module `foo.py` with some content.

4. Run `pipenv install ./foo`.

The generated Pipfile.lock does not contain the resolved dependency for 'xoutil', but something like:

```json
{
    "_meta": {
        "hash": {
            "sha256": "314553368cd3db718a99e462140b44582aa76eda0d250c13ec9a9df36b8eae5f"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "2cac671": {
            "path": "./foo"
        }
    },
    "develop": {}
}
```

The Pipfile shows:

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"2cac671" = {path = "./foo"}

[requires]
python_version = "3.6"

[dev-packages]
```

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.0'`

Pipenv location: `'/home/manu/.local/lib/python3.5/site-packages/pipenv'`

Python location: `'/home/manu/.pyenv/versions/3.5.5/bin/python3.5'`

Other Python installations in `PATH`:

  - `2.7`: `/home/manu/.pyenv/shims/python2.7`
  - `2.7`: `/home/manu/.pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/home/manu/.pyenv/versions/3.5.5/bin/python3.5m`
  - `3.5`: `/home/manu/.pyenv/versions/3.5.5/bin/python3.5`
  - `3.5`: `/home/manu/.pyenv/shims/python3.5`
  - `3.6`: `/home/manu/.pyenv/shims/python3.6m`
  - `3.6`: `/home/manu/.pyenv/shims/python3.6`
  - `3.6`: `/usr/bin/python3.6`

  - `3.5.5`: `/home/manu/.pyenv/versions/3.5.5/bin/python`
  - `3.5.5`: `/home/manu/.pyenv/shims/python`
  - `2.7.15`: `/usr/bin/python`
  - `2.7.15`: `/home/manu/.pyenv/shims/python2`
  - `2.7.15`: `/usr/bin/python2`
  - `3.5.5`: `/home/manu/.pyenv/versions/3.5.5/bin/python3`
  - `3.5.5`: `/home/manu/.pyenv/shims/python3`
  - `3.6.5`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.5.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-15-generic',
 'platform_system': 'Linux',
 'platform_version': '#16-Ubuntu SMP Wed Apr 4 13:58:14 UTC 2018',
 'python_full_version': '3.5.5',
 'python_version': '3.5',
 'sys_platform': 'linux'}
```

System environment variables:

  - `PYENV_HOOK_PATH`
  - `XDG_VTNR`
  - `LC_NUMERIC`
  - `LC_IDENTIFICATION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `DISPLAY`
  - `LC_MEASUREMENT`
  - `IM_CONFIG_PHASE`
  - `TERM`
  - `LC_ADDRESS`
  - `PIP_PYTHON_PATH`
  - `QT4_IM_MODULE`
  - `PYENV_VIRTUALENV_INIT`
  - `PYENV_VERSION`
  - `DESKTOP_AUTOSTART_ID`
  - `LC_PAPER`
  - `PYENV_ROOT`
  - `AGDA_STDLIB`
  - `XDG_MENU_PREFIX`
  - `GNOME_TERMINAL_SCREEN`
  - `XAUTHORITY`
  - `PYENV_DIR`
  - `SSH_AGENT_PID`
  - `QT_IM_MODULE`
  - `XDG_SEAT`
  - `VTE_VERSION`
  - `TEXTDOMAIN`
  - `GDMSESSION`
  - `WINDOWPATH`
  - `GOBIN`
  - `LANG`
  - `LOGNAME`
  - `PATH`
  - `COLORTERM`
  - `GOROOT`
  - `DESKTOP_SESSION`
  - `LC_TELEPHONE`
  - `GNOME_TERMINAL_SERVICE`
  - `LESSOPEN`
  - `CLUTTER_IM_MODULE`
  - `XMODIFIERS`
  - `GTK_IM_MODULE`
  - `GTK_MODULES`
  - `USER`
  - `XDG_DATA_DIRS`
  - `XDG_SESSION_DESKTOP`
  - `XDG_SESSION_ID`
  - `LC_MONETARY`
  - `S_COLORS`
  - `DEFAULTS_PATH`
  - `SSH_AUTH_SOCK`
  - `PYTHONUNBUFFERED`
  - `MANDATORY_PATH`
  - `LC_TIME`
  - `XDG_RUNTIME_DIR`
  - `PYENV_SHELL`
  - `USERNAME`
  - `SHLVL`
  - `XDG_SESSION_TYPE`
  - `OLDPWD`
  - `LC_NAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_CURRENT_DESKTOP`
  - `GNOME_SHELL_SESSION_MODE`
  - `LESSCLOSE`
  - `PYTHONDONTWRITEBYTECODE`
  - `TEXTDOMAINDIR`
  - `SESSION_MANAGER`
  - `XDG_CONFIG_DIRS`
  - `LS_COLORS`
  - `SHELL`
  - `QT_ACCESSIBILITY`
  - `PWD`
  - `HOME`
  - `GPG_AGENT_INFO`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/manu/.pyenv/versions/3.5.5/bin:/home/manu/.pyenv/libexec:/home/manu/.pyenv/plugins/python-build/bin:/home/manu/.pyenv/plugins/pyenv-virtualenv/bin:/opt/cabal/2.2/bin:/home/manu/.cabal/bin:/home/manu/.pyenv/plugins/pyenv-virtualenv/shims:/home/manu/.pyenv/shims:/home/manu/.pyenv/bin:/home/manu/.local/bin:/home/manu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/manu/.local/bin:/home/manu/bin:/home/manu/.local/go/bin:/home/manu/.npm-packages/bin:/home/manu/.rvm/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/manu/tmp/pipenv-demostration`

---------------------------

Contents of `Pipfile` ('/home/manu/tmp/pipenv-demostration/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"2cac671" = {path = "./foo"}

[requires]
python_version = "3.6"

[dev-packages]

```

Contents of `Pipfile.lock` ('/home/manu/tmp/pipenv-demostration/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "314553368cd3db718a99e462140b44582aa76eda0d250c13ec9a9df36b8eae5f"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "2cac671": {
            "path": "./foo"
        }
    },
    "develop": {}
}

```
</details>

**Comment by techalchemy** [comment]
These need to be installed in editable mode, it even tells you that when you run `pipenv install ./foo` -- run `pipenv install -e ./foo` instead.

**Comment by mvaled** [comment]
Hi @techalchemy 

I think that should be noted in the docs, though.  

Being editable should only mean that 'foo' won't be *copied* to the site-packages (or dist-packages) and it will be egg-linked instead.  It should not affect the dependencies, IMO.

**Comment by techalchemy** [comment]
> Being editable should only mean that 'foo' won't be copied to the site-packages (or dist-packages) and it will be egg-linked instead. It should not affect the dependencies, IMO.

Unfortunately pipenv isn't responsible for the entire packaging ecosystem, we interface with pip to do installation and we are bound by the constraints set there in terms of handling dependency and conflict resolution.  If you don't like the terminology they established I recommend opening a discussion over there, we are certainly open to changing to accommodate any new nomenclature and I'm sure they would be willing to have this conversation as well.  Since you mention what you think it _should_ mean I'll just leave it at this because this really isn't our call.  You're asking for a change to python packaging conventions which needs to go to start with pip I think.

Since we just interface with pip, you should see the documentation here: https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs

> It should not affect the dependencies, IMO.

But it does. Unless you install something in editable mode, we can't resolve the dependencies.  This isn't a decision we made, it's just a statement of facts about the situation.

**Comment by mvaled** [comment]
I'm not ranting.  I just think it should be noted in the docs to help reduce the likelihood others do the same mistake I did.  

I've just created a [commit](https://github.com/mvaled/pipenv/commit/2c72a789eeb4debdcecbf3fdc14520b12d7e39d7) to make a PR for the docs.  Do you think that'd be ok?

**Comment by techalchemy** [comment]
Sure thing, I''ll give it a look -- always interested in improvements to the documentation

**Comment by pecigonzalo** [comment]
@techalchemy I know this is closed and the explanation seems reasonable, I was just wondering if there was any change on this, as while `pipenv install ../package` does not install local deps without the `-e`, `pipenv graph` does show them, so they deps are resolved.
Are there any changes?
