### ISSUE TITLE
Support for multiple environment files?

### ISSUE THREAD

**Issue by kevbo** [pypa/pipenv#2050]
This is a feature request, not a bug, so I'm not using the template. I searched the open/closed issues for mention of this, but couldn't find anything. If this request already exists, I apologize.

I would like for pipenv to support multiple environment files, a la [Honcho](https://github.com/nickstenning/honcho) and [Foreman](http://ddollar.github.io/foreman/). For many workflows I'm aware of, it's beneficial to have a default `.env` file checked in to the repository, along with `.env.local` files on developer machines, with secrets and such. Based on my reading of the docs (and no further digging, sorry), pipenv doesn't seem to support this. Could it?

**Comment by techalchemy** [comment]
We sort of support this => https://docs.pipenv.org/advanced/#automatic-loading-of-env

`PIPENV_DOTENV_LOCATION`

There isn't much else we can do as far as I can tell, hope this helps!
