### ISSUE TITLE
pipenv install is missing an equivalent to pip's --index-url=

### ISSUE THREAD

**Issue by triplepoint** [pypa/pipenv#2051]
Pipfile allows for defining multiple package sources, by providing multiple named [[source]] sections.

However there's no command line way to add a new package from a specific source.

It would be convenient to be able to call something like:
```
pipenv install some-private-repo-project --index-url=https://my.repo.lan/simple
```

And have the resulting Pipfile contain:
```
[[source]]
url = "https://my.repo.lan/simple"
verify_ssl = true
name = "my-repo-lan"

[dev-packages]

[packages]
some-private-repo-project = {version="*",  index="my-repo-lan"}

[requires]
python_version = "2.7"
```

I've confirmed that you can create a requirements.txt file of the form:
```
--index-url https://my.repo.lan/simple
some-private-repo-project
```

and import it with:
```
pipenv install -r requirements.txt
```

and get behavior similar to the desired result, though the index isn't explicitly set on the target package.  

But it would be convenient to not have to construct that intermediate requirements.txt file first.

**Comment by uranusjr** [comment]
#1980
