### ISSUE TITLE
Add PIPENV_SKIP_LOCK to disable locking

### ISSUE THREAD

**Issue by giuscri** [pypa/pipenv#2058]
Locking can be very slow on some machines - for example, I always run pipenv with the `--skip-lock` option.

It would be useful to control that behaviour from an environment variable.

**Comment by techalchemy** [comment]
It is literally slow only the first run now due to hash caching. This isn’t something I think we want to support or encourage since you are skipping all of the functionality of the tool

**Comment by techalchemy** [comment]
We might want to revisit this (see #2200)

**Comment by pirate** [comment]
> It is literally slow only the first run now due to hash caching.

FWIW This is definitely not true in my experience, aytime add a new package locking takes a bunch of extra time.  I only lock before pushing to master in preparation for deploys, 90% of my runs during development I have to add `--skip-lock`.
