### ISSUE TITLE
pipenv --update fails with SemVer violation

### ISSUE THREAD

**Issue by GPHemsley** [pypa/pipenv#2063]
Running `pipenv --update` (with pipenv 9.0.0) fails with an error like the following:

```
ValueError: 11.10.1.dev5 is not valid SemVer string
```

This is presumably due to the release of dev versions of v11.10.1 over the last few days. Multiple runs of the command will fail on different dev versions. (I believe the problem is that, according to [SemVer spec item 9](https://semver.org/#spec-item-9), pre-release data should be separated by a hyphen, not a dot; thus the above version should be `11.10.1-dev.5`.)

**Comment by techalchemy** [comment]
The core issue is actually that this command sucks, which is why it hasn't existed since the `9.0` release series. Use pip to upgrade.

**Comment by techalchemy** [comment]
Also, see https://www.python.org/dev/peps/pep-0440/#developmental-releases

**Comment by GPHemsley** [comment]
SemVer and PEP 440 are inherently incompatible, so I don't know that you need to blame it on the command. :smile:

**Comment by techalchemy** [comment]
Lol. Well I meant that the command should work irrespective of any semver compatibilities, we shouldn't have been doing a semver check there anyway. So I'm just glad that we axed it

**Comment by NBR-hugh** [comment]
Sorry,I'm still confused.Thanks for any help.

- macOS High Sierra
- Macbook Pro (Early 2015)

## My Error:

```
~ pipenv --update 
...
 File "/usr/local/Cellar/pipenv/11.8.0/libexec/lib/python3.6/site-packages/pipenv/vendor/semver.py", line 50, in parse
    raise ValueError('%s is not valid SemVer string' % version)
ValueError: 11.10.1.dev1 is not valid SemVer string
```

## My understanding: 

- > https://www.python.org/dev/peps/pep-0440/#developmental-releases
    - `X.Y.devN` is the valid SemVer string
    - `11.10.1.dev1` is false

- > it hasn't existed since the 9.0 release series. Use pip to upgrade.
    + I don't know how to upgrade pipenv by pip
    + I use `brew upgrade pyenv` 
        ```
        ➜  ~ pipenv --version
        pipenv, version 11.8.0
        ```
    + but the `pipenv --update ` is still not working.
        * the same error.

- So...
    + May I make any mistake?

**Comment by techalchemy** [comment]
This command doesn’t work. We deleted it from pipenv. Please upgrade using pip, the same way you installed pipenv in the first place

**Comment by NBR-hugh** [comment]
Thanks.
BTW,This command was not deleted from the help info,which may need adjust.
```
Options:
  --update         Update Pipenv & pip to latest.
  --where          Output project home information.
  --venv           Output virtualenv information.
  --py             Output Python interpreter information.
  --envs           Output Environment Variable options.
  --rm             Remove the virtualenv.
  --bare           Minimal output.
  --completion     Output completion (to be eval'd).
  --man            Display manpage.
  --three / --two  Use Python 3/2 when creating virtualenv.
  --python TEXT    Specify which version of Python virtualenv should use.
  --site-packages  Enable site-packages for the virtualenv.
  --version        Show the version and exit.
  -h, --help       Show this message and exit.
```

**Comment by uranusjr** [comment]
@NBR-hugh Pull requests welcomed!
