### ISSUE TITLE
Can't install anything

### ISSUE THREAD

**Issue by helio-correia** [pypa/pipenv#2071]
Hi guys, I am frustrating with this, after trying everything and read everything, I write this issue. 
I'm on a mac, and can't install anything with pipenv. The site pypi.org rarely open, with I try to install anything gives me errors like that, even with pip I add errors like that but after there if i try to do the same command like 15 times I can install the package.

Can you guys help me out. Thanks

```
pipenv install requests
Installing requests…
Looking in indexes: https://pypi.python.org/simple
Collecting requests

Error:  An error occurred while installing requests!
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/requests/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/requests/
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/requests/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/requests/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/requests/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/requests/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/requests/
  Could not find a version that satisfies the requirement requests (from versions: )
No matching distribution found for requests
```

**Comment by techalchemy** [comment]
can you fill out the full issue template including `python -m pipenv.help`

**Comment by uranusjr** [comment]
This looks like what I get when my Internet connection is down.

**Comment by helio-correia** [comment]
I've installed with homebrew and running the `python -m pipenv.help it gives me the error (/usr/bin/python: No module named pipenv). It sounds like internet problem but I have internet and today I try in another internet and it works. I don't know it's strange and frustrating.

**Comment by uranusjr** [comment]
Well if it works with another Internet access, it’s an environment problem, and there’s nothing much we can do. You probably want to talk to your Internet Service Provider about this situation, especially if you can’t connect to pypi.org consistently.

**Comment by helio-correia** [comment]
I did this in this morning, they reporting the problem, hope that resolves that

**Comment by shatax** [comment]
Collecting pipenv
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/pipenv/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/pipenv/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/pipenv/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/pipenv/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))': /simple/pipenv/
  Could not find a version that satisfies the requirement pipenv (from versions: )
No matching distribution found for pipenv

I keep on getting that on my mac terminal. It is the same even when I try to install a package using pipenv it self

**Comment by frostming** [comment]
@shatax That is basically because pypi.org(or any PyPI mirror being used) is not reachable in your environment, can you check that?

**Comment by shatax** [comment]
That is true. It is not reachable. Does that have to do with my internet connection?
