### ISSUE TITLE
Bogus dependency error during package installation

### ISSUE THREAD

**Issue by rr-** [pypa/pipenv#2079]
<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.1'`

Pipenv location: `'/home/rr-/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `3.6.5`: `/usr/bin/python`
  - `2.7.14`: `/usr/bin/python2`
  - `3.6.5`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.15-1-ARCH',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Sat Mar 31 23:59:25 UTC 2018',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `COLORFGBG`
  - `COLORTERM`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DISPLAY`
  - `EDITOR`
  - `FZF_DEFAULT_COMMAND`
  - `FZF_DEFAULT_OPTS`
  - `GTK_IM_MODULE`
  - `GTK_MODULES`
  - `HISTFILE`
  - `HISTORY_IGNORE`
  - `HISTSIZE`
  - `HOME`
  - `INCLUDE_PATH`
  - `INVOCATION_ID`
  - `JOURNAL_STREAM`
  - `LANG`
  - `LD_LIBRARY_PATH`
  - `LOGNAME`
  - `LS_COLORS`
  - `MAIL`
  - `OLDPWD`
  - `PATH`
  - `PKG_CONFIG_PATH`
  - `PWD`
  - `QT_IM_MODULE`
  - `SAVEHIST`
  - `SHELL`
  - `SHLVL`
  - `SXHKD_SHELL`
  - `TERM`
  - `TMUX`
  - `TMUX_PANE`
  - `TMUX_PLUGIN_MANAGER_PATH`
  - `USER`
  - `WINDOWID`
  - `WINDOWPATH`
  - `XAUTHORITY`
  - `XDG_RUNTIME_DIR`
  - `XDG_SEAT`
  - `XDG_SESSION_ID`
  - `XDG_VTNR`
  - `XMODIFIERS`
  - `_`
  - `active_window_bk`
  - `active_window_fg`
  - `bell_window_bk`
  - `bell_window_fg`
  - `inactive_window_bk`
  - `inactive_window_fg`
  - `is_irssi`
  - `is_vim`
  - `message_bk`
  - `status_bk`
  - `PYTHONPATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/rr-/.local/bin/:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/rr-/.fzf/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `nvim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/rr-/test`

---------------------------

Contents of `Pipfile` ('/home/rr-/test/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
ffms = "*"

[dev-packages]

[requires]
python_version = "3.6"

```

</details>

------------

##### Expected result

I'm able to install `ffms`.

##### Actual result

I'm unable to install `ffms` because `pipenv` says there's conflict in dependencies. But it has only one dependency, `numpy`…

I'm able to install `ffms` just fine via `pip`.

##### Steps to replicate

```console
rr-@localhost:~$ mkdir test
rr-@localhost:~$ cd test
rr-@localhost:~/test$ pipenv install ffms
Creating a virtualenv for this project…
Using /usr/bin/python (3.6.5) to create virtualenv…
⠋Already using interpreter /usr/bin/python
Using base prefix '/usr'
New python executable in /home/rr-/.local/share/virtualenvs/test-yU0AATTd/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/rr-/.local/share/virtualenvs/test-yU0AATTd
Creating a Pipfile for this project…
Installing ffms…
Collecting ffms
Collecting numpy (from ffms)
  Using cached https://files.pythonhosted.org/packages/6e/dc/92c0f670e7b986829fc92c4c0208edb9d72908149da38ecda50d816ea057/numpy-1.14.2-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy, ffms
Successfully installed ffms-0.3a2 numpy-1.14.2

Adding ffms to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.Hint: try $ pipenv lock --pre if it is a pre-release dependency
Could not find a version that matches ffms
Tried: 0.3a2
There are incompatible versions in the resolved dependencies.

rr-@localhost:~/test$ pipenv install --skip-lock
Installing dependencies from Pipfile…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell
rr-@localhost:~/test$ pipenv graph
ffms==0.3a2
  - numpy [required: Any, installed: 1.14.2]
```

**Comment by uranusjr** [comment]
You probably need —pre

**Comment by rr-** [comment]
Thanks, that fixes it (thought I don't know why).

**Comment by techalchemy** [comment]
`3a2` for example is an alpha release which means it is a ‘pre-release’ or not yet fully released aka still being developed so you are forced to pass an extra argument to prove you accept the risk
