### ISSUE TITLE
pipenv-only TLS issue on macOS

### ISSUE THREAD

**Issue by ldgabbay** [pypa/pipenv#2087]
`pipenv` is failing due to TLS issues on a new High Sierra 10.13.4 system with python 2.7.14 from python.org's pkg installed. I have updated pip to support the latest TLS.

FYI someone mentioned this issue before but closed their issue because it "resolved itself" without explanation.

```
$ pip --version
pip 10.0.1 from /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip (python 2.7)

$ python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 0.9.8zh 14 Jan 2016
```

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.1'`

Pipenv location: `'/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pipenv'`

Python location: `'/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python'`

Other Python installations in `PATH`:

  - `2.7`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7`
  - `2.7`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7`
  - `2.7`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7`
  - `2.7`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7`
  - `2.7`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7`
  - `2.7`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`

  - `2.7.14`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python`
  - `2.7.14`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python`
  - `2.7.14`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python`
  - `2.7.14`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python`
  - `2.7.14`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python`
  - `2.7.14`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.14`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2`
  - `2.7.14`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2`
  - `2.7.14`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2`
  - `2.7.14`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2`
  - `2.7.14`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2`
  - `2.7.14`: `/usr/local/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64',
 'python_full_version': '2.7.14',
 'python_version': '2.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PYTHONIOENCODING`
  - `TERM_PROGRAM_VERSION`
  - `PLAYERGLOBAL_HOME`
  - `SCALA_HOME`
  - `LOGNAME`
  - `USER`
  - `HOME`
  - `PS2`
  - `PATH`
  - `PS1`
  - `PS4`
  - `TERM_PROGRAM`
  - `LANG`
  - `TERM`
  - `SHELL`
  - `COLORFGBG`
  - `SHLVL`
  - `XPC_FLAGS`
  - `HISTSIZE`
  - `ITERM_SESSION_ID`
  - `_`
  - `MANPATH`
  - `JBOSS_HOME`
  - `M2_HOME`
  - `HISTFILESIZE`
  - `TERM_SESSION_ID`
  - `XPC_SERVICE_NAME`
  - `SSH_AUTH_SOCK`
  - `DYLD_LIBRARY_PATH`
  - `Apple_PubSub_Socket_Render`
  - `PYTHONDONTWRITEBYTECODE`
  - `ITERM_PROFILE`
  - `PIP_PYTHON_PATH`
  - `TMPDIR`
  - `ANT_HOME`
  - `LC_COLLATE`
  - `__CF_USER_TEXT_ENCODING`
  - `PWD`
  - `COLORTERM`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/rick/notes/scripts:/Users/rick/bin::/opt/make/4.2.1/bin:/Users/rick/Library/Python/3.6/bin:/Users/rick/Library/Python/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/openssh/7.6p1/bin:/opt/rar/5.2.1/bin:/opt/redis/3.2.8/bin:/opt/node/6.10.0/bin:/Users/rick/.npm-packages/bin:/opt/mongodb/2.4.10/bin:/opt/ffmpeg/3.4-evermeet:/opt/ImageMagick/6.8.8/bin:/opt/apache/flex-sdk/4.14.0/bin:/opt/jq/1.5/bin:/opt/elasticsearch/1.4.3/bin:/opt/kibana/4.1.2/bin:/opt/postgresql/9.6.2/bin:/opt/ruby/2.5.1/bin:/opt/aria2/1.31.0/bin:/opt/phantomjs/2.1.1/bin:/opt/git-lfs/1.5.5/bin:/opt/google-cloud-sdk/143.0.1/bin:/opt/pandoc/1.19.2.1/bin:/opt/autotools/bin:/opt/openssl/1.0.2m/bin:/opt/icu/58.2/bin:/opt/fop/2.2/fop:/opt/wxWidgets/3.0.3/bin:/opt/erlang/20.2/bin:/opt/yaws/1.99/bin:/opt/apache/ant/1.9.4/bin:/opt/maven/3.3.3/bin:/opt/spark/1.2.0/bin:/opt/sbt/0.13.7/bin:/opt/mysql/5.7.17/bin:/opt/xz/5.2.3/bin:/opt/watchman/4.7.0/bin:/opt/pv/1.6.0/bin:/opt/sassc/3.4.2/bin:/opt/cpdf/2.2/bin:/Applications/CMake.app/Contents/bin:/opt/cmark/0.28.3/bin:/opt/cmark-gfm/0.28.0.gfm.11/bin:/opt/p7zip/16.02/bin:/opt/heroku/20170629/bin:/opt/monero/0.11.1.0:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/rick`

---------------------------

</details>

------------

##### Expected result

```
$ pipenv install -r requirements.txt
Creating a virtualenv for this project…
Using /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python (2.7.14) to create virtualenv…
⠋Already using interpreter /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
New python executable in /Users/rick/.local/share/virtualenvs/voice-quickstart-server-python-zVwW_i1A/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/rick/.local/share/virtualenvs/voice-quickstart-server-python-zVwW_i1A
Creating a Pipfile for this project…
Requirements file provided! Importing into Pipfile…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
... sunshine and rainbows ...
Done.
```

##### Actual result

```
$ pipenv install -r requirements.txt
Creating a virtualenv for this project…
Using /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python (2.7.14) to create virtualenv…
⠋Already using interpreter /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
New python executable in /Users/rick/.local/share/virtualenvs/voice-quickstart-server-python-zVwW_i1A/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/rick/.local/share/virtualenvs/voice-quickstart-server-python-zVwW_i1A
Creating a Pipfile for this project…
Requirements file provided! Importing into Pipfile…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/rick/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/rick/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/itsdangerous/json (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)'),))

/Users/rick/Library/Python/2.7/lib/python/site-packages/pipenv/utils.py:1288: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/var/folders/7x/pfyb8v_j13bdvsj9rrgftq8w0000gn/T/pipenv-L14PsE-requirements'>
  warnings.warn(warn_message, ResourceWarning)
```

##### Steps to replicate

* new macOS High Sierra 10.13.4
* install Python 2.7.14 from python.org here: https://www.python.org/ftp/python/2.7.14/python-2.7.14-macosx10.6.pkg
* update `pip` with `curl https://bootstrap.pypa.io/get-pip.py -O; sudo python get-pip.py`
* go into project with this `requirements.txt` file:
```
Flask==0.10.1
Jinja2==2.7.3
MarkupSafe==0.23
Werkzeug==0.9.6
httplib2==0.9
itsdangerous==0.24
six==1.*
twilio==6.10.0
wsgiref==0.1.2
nose
requests
pyjwt
```
* run `pipenv install -r requirements.txt`

--------------

**Comment by uranusjr** [comment]
Wild guess, did you upgrade the pip inside the virtualenv?

**Comment by techalchemy** [comment]
Yeah you can’t just update the system one unfortunately

**Comment by ldgabbay** [comment]
@uranusjr no, pip was installed globally

@techalchemy as i mentioned, python TLS is upgraded, as you can see in the logs. Like I said, I can use pip and virtualenv with no issues. Only pipenv has problems.

Also, pipenv is up to date:

```
$ pip list | grep pipenv
pipenv                 11.10.1
```

**Comment by techalchemy** [comment]
@ldgabbay it is not part of the issue.

From your logs:

> Using /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python (2.7.14)
> **/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/requests/sessions.py", line 508, in request**

I could be mistaken, but these look quite different, and that suggests to me that you may have _installed_ the latest version of python, but you didn't actually upgrade things in your system python or you have artifacts of an installation of pipenv from before you did the new install.  At least that's what I can guess, knowing basically nothing about mac or its python ecosystem.  Can you uninstall that pipenv version and let us know if that fixes?  I.e. `/Library/Python/2.7/bin/python -m pip uninstall pipenv` (explicitly, and provide the output please)

**Comment by ldgabbay** [comment]
Thanks for looking into this. So, even though it printed `/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/requests/sessions.py` there is actually no such file, not even . There is, however, such a file under the home directory, `~/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/requests/sessions.py`. This was installed by `pip install --user pipenv`.

As `/Library/Python/2.7/bin/python` does not exist, I followed your instructions as closely as possible here:

```
$ /Library/Python/2.7/bin/python
-bash: /Library/Python/2.7/bin/python: No such file or directory

$ find /Library/Python
/Library/Python
/Library/Python/2.7
/Library/Python/2.7/site-packages
/Library/Python/2.7/site-packages/vboxapi-1.0-py2.7.egg-info
/Library/Python/2.7/site-packages/README
/Library/Python/2.7/site-packages/vboxapi
/Library/Python/2.7/site-packages/vboxapi/__init__.py
/Library/Python/2.7/site-packages/vboxapi/VirtualBox_constants.py
/Library/Python/2.7/site-packages/vboxapi/VirtualBox_constants.pyc
/Library/Python/2.7/site-packages/vboxapi/__init__.pyc
/Library/Python/2.7/site-packages/Extras.pth

$ which python
/Library/Frameworks/Python.framework/Versions/2.7/bin/python

$ /Library/Frameworks/Python.framework/Versions/2.7/bin/python -m pip uninstall pipenv
Uninstalling pipenv-11.10.1:
  Would remove:
    /Users/rick/Library/Python/2.7/bin/pewtwo
    /Users/rick/Library/Python/2.7/bin/pipenv
    /Users/rick/Library/Python/2.7/bin/pipenv-resolver
    /Users/rick/Library/Python/2.7/lib/python/site-packages/pipenv-11.10.1.dist-info/*
    /Users/rick/Library/Python/2.7/lib/python/site-packages/pipenv/*
    /Users/rick/Library/Python/2.7/lib/python/site-packages/tasks/*
    /Users/rick/Library/Python/2.7/lib/python/site-packages/tests/integration/*
    /Users/rick/Library/Python/2.7/lib/python/site-packages/tests/unit/*
Proceed (y/n)? y
  Successfully uninstalled pipenv-11.10.1

$ which pipenv

$
```

**Comment by techalchemy** [comment]
What if you run the same thing again? The uninstall commad

**Comment by ldgabbay** [comment]
```
$ /Library/Frameworks/Python.framework/Versions/2.7/bin/python -m pip uninstall pipenv
Skipping pipenv as it is not installed.
```

**Comment by ldgabbay** [comment]
Same problem with fresh compiled python 2.7.15 with latest openssl. (reinstalled pipenv)

```
$ python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.1.0h  27 Mar 2018

$ pipenv install -r requirements.txt
Creating a Pipfile for this project…
Requirements file provided! Importing into Pipfile…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
/lib/python2.7/site-packages/pipenv/vendor/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/rick/.local/lib/python2.7/site-packages/pipenv/vendor/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/rick/.local/lib/python2.7/site-packages/pipenv/vendor/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/pyopenssl/json (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)'),))

/Users/rick/.local/lib/python2.7/site-packages/pipenv/utils.py:1288: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/var/folders/7x/pfyb8v_j13bdvsj9rrgftq8w0000gn/T/pipenv-j5Eq9c-requirements'>
  warnings.warn(warn_message, ResourceWarning)
```


<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.1'`

Pipenv location: `'/Users/rick/.local/lib/python2.7/site-packages/pipenv'`

Python location: `'/opt/python/2.7.15/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/opt/python/2.7.15/bin/python2.7`
  - `2.7`: `/opt/python/2.7.15/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m`
  - `3.6`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `2.7.15`: `/opt/python/2.7.15/bin/python`
  - `2.7.14`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.15`: `/opt/python/2.7.15/bin/python2`
  - `2.7.14`: `/usr/local/bin/python2`
  - `3.6.5`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3`
  - `3.6.5`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64',
 'python_full_version': '2.7.15',
 'python_version': '2.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PYTHONIOENCODING`
  - `TERM_PROGRAM_VERSION`
  - `PLAYERGLOBAL_HOME`
  - `SCALA_HOME`
  - `LOGNAME`
  - `USER`
  - `HOME`
  - `PS2`
  - `PATH`
  - `PS1`
  - `PS4`
  - `TERM_PROGRAM`
  - `LANG`
  - `TERM`
  - `SHELL`
  - `COLORFGBG`
  - `SHLVL`
  - `XPC_FLAGS`
  - `HISTSIZE`
  - `ITERM_SESSION_ID`
  - `_`
  - `MANPATH`
  - `JBOSS_HOME`
  - `M2_HOME`
  - `HISTFILESIZE`
  - `TERM_SESSION_ID`
  - `XPC_SERVICE_NAME`
  - `SSH_AUTH_SOCK`
  - `DYLD_LIBRARY_PATH`
  - `Apple_PubSub_Socket_Render`
  - `PYTHONDONTWRITEBYTECODE`
  - `ITERM_PROFILE`
  - `PIP_PYTHON_PATH`
  - `TMPDIR`
  - `ANT_HOME`
  - `LC_COLLATE`
  - `__CF_USER_TEXT_ENCODING`
  - `PWD`
  - `COLORTERM`
  - `OLDPWD`

Pipenv–specific environment variables:


Debug–specific environment variables:

  - `PATH`: `/Users/rick/notes/scripts:/Users/rick/bin::/opt/make/4.2.1/bin:/Users/rick/.local/bin:/opt/python/2.7.15/bin:/Users/rick/Library/Python/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/opt/openssh/7.6p1/bin:/opt/rar/5.2.1/bin:/opt/redis/3.2.8/bin:/opt/node/8.11.1/bin:/Users/rick/.npm-packages/bin:/opt/ffmpeg/3.4-evermeet:/opt/ImageMagick/6.8.8/bin:/opt/apache/flex-sdk/4.14.0/bin:/opt/jq/1.5/bin:/opt/elasticsearch/1.4.3/bin:/opt/kibana/4.1.2/bin:/opt/postgresql/9.6.2/bin:/opt/ruby/2.5.1/bin:/opt/aria2/1.31.0/bin:/opt/phantomjs/2.1.1/bin:/opt/git-lfs/1.5.5/bin:/opt/google-cloud-sdk/143.0.1/bin:/opt/pandoc/1.19.2.1/bin:/opt/autotools/bin:/opt/openssl/1.1.0h/bin:/opt/icu/58.2/bin:/opt/fop/2.2/fop:/opt/wxWidgets/3.0.3/bin:/opt/erlang/20.2/bin:/opt/yaws/1.99/bin:/opt/apache/ant/1.9.4/bin:/opt/maven/3.3.3/bin:/opt/spark/1.2.0/bin:/opt/sbt/0.13.7/bin:/opt/mysql/5.7.17/bin:/opt/xz/5.2.3/bin:/opt/watchman/4.7.0/bin:/opt/pv/1.6.0/bin:/opt/sassc/3.4.2/bin:/opt/cpdf/2.2/bin:/Applications/CMake.app/Contents/bin:/opt/cmark/0.28.3/bin:/opt/cmark-gfm/0.28.0.gfm.11/bin:/opt/p7zip/16.02/bin:/opt/heroku/20170629/bin:/opt/monero/0.11.1.0:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/rick/dev/bond/twilio/voice-quickstart-server-python`


---------------------------

Contents of `Pipfile` ('/Users/rick/Desktop/bond/dev/twilio/voice-quickstart-server-python/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
"httplib2" = "==0.9"
itsdangerous = "==0.24"
six = "==1.*"
twilio = "==6.10.0"
wsgiref = "==0.1.2"
nose = "*"
requests = "*"
Flask = "==0.10.1"
"Jinja2" = "==2.7.3"
MarkupSafe = "==0.23"
Werkzeug = "==0.9.6"
PyJWT = "*"

[requires]
python_version = "2.7"

```

</details>

**Comment by nitrocode** [comment]
I see the same issue on centos 7 with pipenv 11.10.1

**Comment by techalchemy** [comment]
@ldgabbay sorry I meant to send this earlier when I closed this — I am looking at the path the warning is coming from. You are installing new versions over and over again. Yet your system installation is the broken one. You can’t simply install over it with a new python. Pipenv doesn’t touch `ssl.c`. This is related to your system python and you need to fix it by upgrading requests and certifi by following the instructions and using _the absolute path to your native system python installation_. Sorry you’re running up against this but we can’t give you much more to go on. Closing for now

**Comment by techalchemy** [comment]
@nitrocode would need logs, probably need to upgrade your system ssl libraries

**Comment by mikexstudios** [comment]
I ran into a somewhat similar issue (pipenv with python 2.7) and resolved it by:

1. Activate the virtualenv: `pipenv shell`

2. Upgrade pip inside that virtualenv (which is the version of pip that pipenv will use): `pip install -U pip`

3. Exit the virtualenv: `exit`. Then pipenv works as expected without the TLS error.

**Comment by GregOwen** [comment]
For anyone running into this issue, I was able to fix the problem and successfully use `pipenv install` after doing the following:
1. Uninstall pipenv
1. `brew install python2 python3`
1. `ls /usr/bin/python*` (or wherever your system Python is installed)
1. For each binary in the result of the above `ls` command, find the corresponding binary that Brew installed (`/usr/local/bin/python*` for me) and perform `ln -sf /path/to/brew/binary /path/to/system/binary` for each one (this will overwrite the system binary)

I hope this helps!

**Comment by uranusjr** [comment]
I wouldn’t advise people to overwrite system binaries (who knows what can happen), but essentially, [don’t use the system Python](https://twitter.com/callmewuest/status/987917349322940416). If you use Homebrew, Pipenv is available with `brew install pipenv`.

**Comment by foreverfighter** [comment]
Uninstalling and reinstalling with `brew install pipenv` worked for me. Thanks!
