### ISSUE TITLE
`python -m pipenv.help` fails on Travis CI

### ISSUE THREAD

**Issue by melinath** [pypa/pipenv#2089]
`python -m pipenv.help` fails on Travis CI due to a unicode encode error.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.1'`

Pipenv location: `'/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pipenv'`

Python location: `'/home/travis/virtualenv/python2.7.14/bin/python'`

Other Python installations in `PATH`:
  - `2.7`: `/home/travis/virtualenv/python2.7.14/bin/python2.7`
  - `2.7`: `/home/travis/virtualenv/python2.7.14/bin/python2.7`
  - `2.7`: `/opt/pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.4`: `/usr/bin/python3.4m`
  - `3.4`: `/usr/bin/python3.4`
  - `3.6`: `/opt/pyenv/shims/python3.6`
  - `2.7.14`: `/home/travis/virtualenv/python2.7.14/bin/python`
  - `2.7.14`: `/opt/pyenv/shims/python`
  - `2.7.6`: `/usr/bin/python`
  - `2.7.14`: `/home/travis/virtualenv/python2.7.14/bin/python2`
  - `2.7.14`: `/opt/pyenv/shims/python2`
  - `2.7.6`: `/usr/bin/python2`
  - `3.4.3`: `/opt/pyenv/shims/python3`
  - `3.4.3`: `/usr/bin/python3`
PEP 508 Information:
```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.14.12-041412-generic',
 'platform_system': 'Linux',
 'platform_version': '#201801051649 SMP Fri Jan 5 16:50:54 UTC 2018',
 'python_full_version': '2.7.14',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```
System environment variables:
  - `TRAVIS_UID`
  - `rvm_version`
  - `PYTHONDONTWRITEBYTECODE`
  - `TRAVIS`
  - `_JAVA_OPTIONS`
  - `PIPENV_IGNORE_VIRTUALENVS`
  - `TRAVIS_STACK_LANGUAGES`
  - `JRUBY_OPTS`
  - `VIRTUAL_ENV`
  - `SHELL`
  - `TRAVIS_PULL_REQUEST_BRANCH`
  - `PYENV_SHELL`
  - `TRAVIS_BRANCH`
  - `TRAVIS_PULL_REQUEST_SLUG`
  - `HISTSIZE`
  - `NVM_BIN`
  - `RBENV_SHELL`
  - `MANPATH`
  - `JAVA_HOME`
  - `_system_type`
  - `TRAVIS_SECURE_ENV_VARS`
  - `MY_RUBY_HOME`
  - `STRIPE_TEST_ORGANIZATION_PUBLISHABLE_KEY`
  - `RUBY_VERSION`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `HOSTNAME`
  - `DATABASE_URL`
  - `_system_version`
  - `TRAVIS_COMMIT_RANGE`
  - `GOPATH`
  - `CONTINUOUS_INTEGRATION`
  - `GOROOT`
  - `rvm_path`
  - `TRAVIS_REPO_SLUG`
  - `USER`
  - `PS1`
  - `PS4`
  - `container`
  - `STRIPE_TEST_APPLICATION_ID`
  - `SHLVL`
  - `TRAVIS_PULL_REQUEST_SHA`
  - `MERB_ENV`
  - `JDK_SWITCHER_DEFAULT`
  - `STRIPE_TEST_PUBLISHABLE_KEY`
  - `GIT_ASKPASS`
  - `TRAVIS_FILTERED`
  - `GEM_PATH`
  - `HAS_ANTARES_THREE_LITTLE_FRONZIES_BADGE`
  - `TRAVIS_EVENT_TYPE`
  - `DWOLLA_TEST_USER_ACCESS_TOKEN`
  - `PIP_PYTHON_PATH`
  - `DWOLLA_TEST_USER_USER_ID`
  - `DWOLLA_TEST_ORGANIZATION_ACCESS_TOKEN`
  - `TRAVIS_TAG`
  - `DWOLLA_TEST_APPLICATION_KEY`
  - `TRAVIS_BUILD_NUMBER`
  - `PYENV_ROOT`
  - `TRAVIS_STACK_FEATURES`
  - `_system_name`
  - `DWOLLA_TEST_ORGANIZATION_REFRESH_TOKEN`
  - `TRAVIS_SUDO`
  - `MIX_ARCHIVES`
  - `TRAVIS_BUILD_ID`
  - `NVM_DIR`
  - `TRAVIS_STACK_NAME`
  - `HOME`
  - `TRAVIS_PULL_REQUEST`
  - `LANG`
  - `TRAVIS_COMMIT`
  - `_`
  - `TRAVIS_STACK_JOB_BOARD_REGISTER`
  - `_system_arch`
  - `MYSQL_UNIX_PORT`
  - `CI`
  - `rvm_prefix`
  - `DEBIAN_FRONTEND`
  - `TRAVIS_PRE_CHEF_BOOTSTRAP_TIME`
  - `TRAVIS_COMMIT_MESSAGE`
  - `IRBRC`
  - `TRAVIS_STACK_TIMESTAMP`
  - `CASHER_DIR`
  - `STRIPE_TEST_ORGANIZATION_USER_ID`
  - `TRAVIS_STACK_NODE_ATTRIBUTES`
  - `RACK_ENV`
  - `PERLBREW_HOME`
  - `GEM_HOME`
  - `HAS_JOSH_K_SEAL_OF_APPROVAL`
  - `PYTHON_CFLAGS`
  - `COMPOSER_NO_INTERACTION`
  - `DWOLLA_TEST_USER_REFRESH_TOKEN`
  - `NVM_CD_FLAGS`
  - `TRAVIS_BUILD_STAGE_NAME`
  - `PERLBREW_BASHRC_VERSION`
  - `PATH`
  - `DWOLLA_TEST_USER_PIN`
  - `TRAVIS_ALLOW_FAILURE`
  - `TERM`
  - `TZ`
  - `STRIPE_TEST_ORGANIZATION_ACCESS_TOKEN`
  - `MALLOC_ARENA_MAX`
  - `HISTFILESIZE`
  - `TRAVIS_OSX_IMAGE`
  - `rvm_bin_path`
  - `STRIPE_TEST_SECRET_KEY`
  - `RAILS_ENV`
  - `PERLBREW_ROOT`
  - `TRAVIS_JOB_NUMBER`
  - `PYTHON_CONFIGURE_OPTS`
  - `DWOLLA_TEST_APPLICATION_SECRET`
  - `DWOLLA_TEST_ORGANIZATION_USER_ID`
  - `DWOLLA_TEST_ORGANIZATION_PIN`
  - `LC_ALL`
  - `TRAVIS_JOB_ID`
  - `TRAVIS_PYTHON_VERSION`
  - `PAGER`
  - `OLDPWD`
  - `TRAVIS_LANGUAGE`
  - `TRAVIS_BUILD_DIR`
  - `HISTCONTROL`
  - `PWD`
  - `TRAVIS_OS_NAME`
  - `ELIXIR_VERSION`
  - `rvm_pretty_print_flag`
Traceback (most recent call last):
  File "/opt/python/2.7.14/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/python/2.7.14/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pipenv/help.py", line 89, in <module>
    main()
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pipenv/help.py", line 48, in main
    print(u'Pipenv–specific environment variables:')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 6: ordinal not in range(128)
The command "python -m pipenv.help" failed and exited with 1 during .
Your build has been stopped.
</details>

------------

##### Expected result

I would expect that I get normal output.

##### Actual result

Fails with a UnicodeEncodeError (see output above)

##### Steps to replicate

Set up travis-ci with python 2.7 and pipenv 1.11.1 and run `python -m pipenv.help`.

Build that fails this way: https://travis-ci.org/dancerfly/django-brambling/builds/372773845

**Comment by techalchemy** [comment]
Set your locale variables in any environment you run python on.

```yaml
env:
  global:
    - PYTHONIOENCODING='utf-8'
```

**Comment by techalchemy** [comment]
er also `LC_ALL=en_US.utf-8`
