### ISSUE TITLE
Incorrect `Pipenv.lock` with CVS based dependencies

### ISSUE THREAD

**Issue by gabhijit** [pypa/pipenv#2096]
Hi All

I am having an issue with `pipenv lock` when I have dependencies that come from a CVS. This might be related to #1690 but not exactly identical.

Start with a clean slate - no `Pipfile`, no `requirements.txt` file and no `Pipfile.lock` and no `virtualenv`

1. start with `pipenv install` - emptyish  Pipfile and Pipefile.lock created - as expected.
2. Add the git based dependency in the Pipfile (See below in steps to reproduce)
3. Again do a `pipenv install ` - CVS Dependency is properly added to Pipfile.lock, but second order dependencies are not added to Pipfile.lock while they get installed properly. 

Consequently - `pipenv lock -r` also does not capture other dependencies. 

My initial guess was - there might be some issue with my packages, but I am able to produce it with `requests==2.18.4` as well. 

#### Results of running python -m pipenv.help

<summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.1'`

Pipenv location: `'/home/gabhijit/.local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`

  - `2.7.12`: `/usr/bin/python`
  - `2.7.12`: `/usr/bin/python2`
  - `3.5.2`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.13.0-36-generic',
 'platform_system': 'Linux',
 'platform_version': '#40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018',
 'python_full_version': '2.7.12',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```
<snipped lot of environment variables details - don't think they are relevant>

------------

##### Expected result

All the dependencies of a CVS package should be also captured in Pipfile.lock

##### Actual result

Dependencies do not get captured - 
```
$ cat Pipfile.lock 
{
    "_meta": {
        "hash": {
            "sha256": "633566f25d3ae239154bfaddfea35abb2737c60bf8a609820ceab9d224c6f932"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "2.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "requests": {
            "git": "https://github.com/requests/requests.git",
            "ref": "v2.18.4"
        }
    },
    "develop": {}
}
```

##### Steps to replicate
```
$ pipenv --rm
$ rm -rf Pipfile Pipefile.lock requirements.txt
$ pipenv install

# Add dependency to Pipfile, the Pipfile looks like 
$ cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
requests = { git = "https://github.com/requests/requests.git", ref="v2.18.4" }

[requires]
python_version = "2.7"

$ pipenv install --verbose

```

**Comment by techalchemy** [comment]
As it tells you when you do this from the command line, VCS dependencies need to be installed in editable mode in order to be resolved properly.
