### ISSUE TITLE
Dependencies miss index

### ISSUE THREAD

**Issue by apollo13** [pypa/pipenv#2099]
Dependencies do not have an index set in `Pipfile.lock`

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.1'`

Pipenv location: `'/home/florian/.local/venvs/pipenv/lib/python3.5/site-packages/pipenv'`

Python location: `'/home/florian/.local/venvs/pipenv/bin/python'`

Other Python installations in `PATH`:

  - `2.5`: `/usr/local/bin/python2.5`
  - `2.5`: `/usr/local/bin/python2.5`
  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.15`: `/usr/bin/python`
  - `2.7.15`: `/usr/bin/python2`
  - `3.6.5`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.5.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-3-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 4.15.17-1 (2018-04-19)',
 'python_full_version': '3.5.4',
 'python_version': '3.5',
 'sys_platform': 'linux'}
```

System environment variables:

  - `XDG_VTNR`
  - `LC_MONETARY`
  - `GDMSESSION`
  - `EDITOR`
  - `XDG_SESSION_ID`
  - `VTE_VERSION`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `COLORTERM`
  - `GTK_MODULES`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `XDG_SESSION_TYPE`
  - `LC_CTYPE`
  - `XDG_DATA_DIRS`
  - `GJS_DEBUG_OUTPUT`
  - `USER`
  - `PAGER`
  - `PROJECT_HOME`
  - `SSH_AUTH_SOCK`
  - `SHELL`
  - `LC_TIME`
  - `TERMINATOR_DBUS_PATH`
  - `XDG_SESSION_COOKIE`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_SESSION_DESKTOP`
  - `LANG`
  - `WINDOWPATH`
  - `OLDPWD`
  - `XDG_SEAT`
  - `SSH_AGENT_PID`
  - `PYTHONDONTWRITEBYTECODE`
  - `_`
  - `QT_ACCESSIBILITY`
  - `DISPLAY`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `TERMINATOR_UUID`
  - `GJS_DEBUG_TOPICS`
  - `LSCOLORS`
  - `PEX_INHERIT_PATH`
  - `LESS`
  - `XDG_MENU_PREFIX`
  - `LC_MEASUREMENT`
  - `S_COLORS`
  - `ZSH`
  - `ANSIBLE_NOCOWS`
  - `LC_PAPER`
  - `LS_COLORS`
  - `DESKTOP_SESSION`
  - `SESSION_MANAGER`
  - `PWD`
  - `LOGNAME`
  - `QT_SELECT`
  - `TERMINATOR_DBUS_NAME`
  - `HOME`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `LC_NUMERIC`
  - `ELECTRON_TRASH`
  - `GDM_LANG`
  - `SHLVL`
  - `GPG_AGENT_INFO`
  - `PIP_PYTHON_PATH`
  - `USERNAME`
  - `GNOME_DESKTOP_SESSION_ID`
  - `TERM`
  - `PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/florian/.yarn/bin:/usr/local/heroku/bin:/home/florian/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
  - `SHELL`: `/usr/bin/zsh`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.utf8`
  - `PWD`: `/home/florian/.local/venvs/pipenv`

---------------------------

</details>

##### Expected result

`Pipfile.lock` should contain an `index` key for every package.

##### Actual result

This is what `Pipfile.lock` looks like after `pipenv install Django`:
```
{
    "_meta": {
        "hash": {
            "sha256": "68309cd71a258c30a39567fce09a09ad5c4ff0bdc85b6fba22b47598c985c883"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "django": {
            "hashes": [
                "sha256:2d8b9eed8815f172a8e898678ae4289a5e9176bc08295676eff4228dd638ea61",
                "sha256:d81a1652963c81488e709729a80b510394050e312f386037f26b54912a3a10d0"
            ],
            "index": "pypi",
            "version": "==2.0.4"
        },
        "pytz": {
            "hashes": [
                "sha256:65ae0c8101309c45772196b21b74c46b2e5d11b6275c45d251b150d5da334555",
                "sha256:c06425302f2cf668f1bba7a0a03f3c1d34d4ebeef2c72003da308b3947c7f749"
            ],
            "version": "==2018.4"
        }
    },
    "develop": {}
}
```

Which index did `pytz` come from?

##### Steps to replicate

Run `pipenv install Django` in an empty pipfile and look for the `index` key for `pytz` in the lockfile.

**Comment by techalchemy** [comment]
Hi, thanks for reporting this. Did you notice something wrong while using pipenv? Was there a bug or an issue you came across?

For context, this is not a required key and currently its presence depends on 1) whether you have multiple indexes specified and it came from a non-primary index, or 2) it was resolved via the fallback resolver and not a cached lookup or a json query (I might have the last one backwards). Given that you have only once source specified, suffice to say it came from pypi.

**Comment by apollo13** [comment]
Hi, yeah I noticed it while reporting #2098 and thought I'd open a bugreport in case it was an oversight. Thanks for clearing that up!

That said, it is still weird that Django would have the index set, since it clearly also can come only from `pypi` ;)

**Comment by techalchemy** [comment]
Yeah there is a reason but it was an unintentional side effect or something like that
