### ISSUE TITLE
scripts commands does not interpret shell variables

### ISSUE THREAD

**Issue by bmamouri** [pypa/pipenv#2105]
The **[scripts]** section of the Pipfile does not support shell env variables. For example, all the following commands fails to run correctly:

```
[scripts]
generate_key = "python generate_key.py ~"
generate_key = "python generate_key.py $HOME"
generate_key = "python generate_key.py ${HOME}"
```

------------

##### Expected result

If the absolute path is specified, the script works perfectly:
```
[scripts]
generate_key = "python generate_key.py /Users/user"
```

##### Actual result

pipenv should interpret the variables (e.g. \~, $HOME) and replace them accordingly. For example, if you run `echo ~` or `echo "$HOME"` in the shell you will get your user directory not the literal strings (~ or $HOME).

**Comment by techalchemy** [comment]
This is not an advertised or implemented feature of scripts and I’m kind of hesitant to make any changes to that code as its somewhat complex for what we probably should be handling as a dependency management tool. This section is meant as a convenience wrapper around simple `pipenv run` commands and accomplishing that across platforms is already a challenge. @uranusjr implemented most of this so he might have a better sense

**Comment by uranusjr** [comment]
I agree, this would become messy pretty quickly. We don’t want to implement a task runner, especially considering cross-platform, or even just cross-shell support. Once we go into this rabbit hole we’ll soon find ourselves implementing a half-hearted mini-DSL receiving bug reports because it misses some obscure feature.

It’d be better to rely on a more specialised tool with well-defined syntax, e.g. GNU make (if you don’t care about Windows) or [Invoke](http://www.pyinvoke.org). With Invoke you’d do it like this:

```toml
# Pipfile
[dev-packages]
invoke = "*"   # Install with "pipenv install invoke --dev"

[scripts]
generate_key = "invoke generate_key"
```

```python
# tasks.py

import os
import shlex

import invoke

@invoke.task()
def generate_key(ctx):
    ctx.run('python generate_key.py {}'.format(shlex.quote(os.path.expanduser('~'))))
```

**Comment by bmamouri** [comment]
@techalchemy: npm supports the feature

@uranusjr: I don't understand why we cannot use something as simple as this:

```
import subprocess
print(subprocess.check_output('echo $HOME', shell=True))
```

We don't really need to implement a fully fledged task runner. But if we have support for scripts, it is a reasonable expectation to be able to use env variables in them.

**Comment by uranusjr** [comment]
@bmamouri First of all, Python focuses a lot on cross-platform support and team collaboration. This would not work if you’re on Windows, or even on a non-Bourne-derived shell (the syntax is different). Secondly, we avoid subprocess if possible for efficiency reasons, and use the os.exec series to swap out the process. This makes environment variable support much more difficult. There are more reasons, but these two are the most important in my opinion.

**Comment by techalchemy** [comment]
Also, npm does it is not a persuasive argument - we have to maintain the features we add.
