### ISSUE TITLE
When a virtualenv is already active, `pipenv shell` suggests using `pew new`

### ISSUE THREAD

**Issue by gtalarico** [pypa/pipenv#2114]
### To Reproduce:
1. Activate a virtual env using virtualenv or virtualenvwrapper
2. Go to a folder with no Pipenv/pipfile
3. `$ pipenv shell` 

### Result:

Raises
```
ERROR: Environment 'folder-1AY1GkYk' does not exist. Create it with 'pew new folder-1AY1GkYk'.
```
![image](https://user-images.githubusercontent.com/9513968/39495126-0c0c4cfc-4d67-11e8-9f3a-13de2073a1b0.png)

### Expected
An error about a virtualenv already being active. Perhaps similar to the error shown when using 
`$ pipenv --three`, which issues a courtesy warning:
'Pipenv found itself running within a virtual environment ... '
![image](https://user-images.githubusercontent.com/9513968/39495138-1af05be6-4d67-11e8-86bb-acf32a49980c.png)

### Note

While I understand pipenv can't always play nice with every possible virtual env configurations it might find itself one, standard virtualenv is still widely used and until I can migrate all projects I still find myself jumping between the two and making these types of mistakes often. Hopefuly I am not the only one : )

These courtesy messages are incredibly helpful and can save users and maintainers troubleshooting time

**Comment by techalchemy** [comment]
Lol! This is particularly hilarious because we don’t have a hard dependency on pew but instead bundle a patched version and call it `pewtwo`. Thanks for the report!

**Comment by uranusjr** [comment]
I don’t get this error on macOS, so maybe this is a Windows-only thing. Or maybe it is already resolved? (I can’t reproduce in either 11.10.4 and 2018.05.18.)

**Comment by gtalarico** [comment]
I can no longer reproduce this either. I would close it for now.

Seems strange that pipenv does not complain about an active venv, but I guess you can consider this user error (double activation of 2 different venv managers)

``` console
D:\Dropbox\shared\dev\repos
λ workon test

D:\Dropbox\shared\dev\repos\test
(test) λ pipenv shell

Launching subshell in virtual environment. Type 'exit' to return.
Be aware that this environment will be nested on top of 'test'

D:\Dropbox\shared\dev\repos\test
(test) λ cd ..\airtable\

D:\Dropbox\shared\dev\repos\airtable (master -> origin)
(test) λ pipenv shell

Launching subshell in virtual environment. Type 'exit' to return.
Be aware that this environment will be nested on top of 'test'

D:\Dropbox\shared\dev\repos\airtable (master -> origin)
(test) λ which python
/c/Users/gtalarico/.env/airtable-HCXp4XFS/Scripts/python
```

**Comment by uranusjr** [comment]
Well, running shell inside an already activated virtualenv doesn’t generally cause harm, since all you really get is duplicated entries in `PATH`; they will still find you the correct executables anyway. I can understand it not objecting.

One less issue to fix ∠( 'ω')／
