### ISSUE TITLE
Pipenv Shell raises error if shell's path contains space

### ISSUE THREAD

**Issue by gtalarico** [pypa/pipenv#2115]
This might be a windows only issue - Pipenv version 11.10.1
I am using cmder console

##### Steps to replicate
1. `set PIPENV_SHELL="c:\path_with space\enclosed\inquotes\shell"
2. `pipenv shell`

##### Expected result
Pipenv Shell is activated with the desired shell

##### Actual result
Pipenv Shell is activated with the default shell (cmd.exe)
> 'c:\path_with' is not regognized as an internal or external command

I use a portable cmder that is in a folder location that has spaces in its path.
To use Pipenv with cmder, I need to set `PIPENV_SHELL` to cmder's `init.bat` file
This files if there is a space in the folder path.

#### Work Around
Moving cmder's `init.bat` to a location with no spaces fixes it

![image](https://user-images.githubusercontent.com/9513968/39496845-4fccd9e6-4d6e-11e8-9efd-5a510420cc1e.png)

**Comment by uranusjr** [comment]
Probably needs to quote it here. https://github.com/pypa/pipenv/blob/master/pipenv/core.py#L2179
