### ISSUE TITLE
Feature: Add active environment name to PROMPT env var (Windows Support)

### ISSUE THREAD

**Issue by gtalarico** [pypa/pipenv#2116]
On unix/fish, when a shell is started using `pipenv shell`, the `$VIRTUAL_ENV` variable can be used to provide a visual indicator on the shell. For Example, if the users prompt is ` (~/folder)  $`
once the shell is activated using `pipenv shell` the prompt becomes:
` (~/folder) (pipenvfolder-1234) $`
or similar. This currently works well with zsh/fish, etc and in general in the unix world is fairly easy to customize prompt.

On windows however, `%PROMPT% variable is used instead, and the variable is used by both cmd.exe and cmder console to add the virtual environment to the user's prompt.

Upon activating an environment, the environment's name is prepended to the `$PROMPT` var.
As far as I know, this is not customizable on cmd.exe, and is not easily customizable with cmder neither.

### cmd.exe behavior with virtualenv / virtualenv-wrapper
Active Environment is shown on prompt

![image](https://user-images.githubusercontent.com/9513968/39497845-16d6f64e-4d73-11e8-88c8-603a3c08457b.png)

### cmder behavior with virtualenv  / virtualenv-wrapper
Active Environment is shown on prompt

![image](https://user-images.githubusercontent.com/9513968/39497992-b03a709a-4d73-11e8-91cf-e825f7124a30.png)

### cmd and cmder with pipenv shell - No prompt indicator
Environment IS NOT shown anywhere on the prompt

![image](https://user-images.githubusercontent.com/9513968/39498041-f412e612-4d73-11e8-8892-54bc396bb2b2.png)

![image](https://user-images.githubusercontent.com/9513968/39498029-e8ae26a6-4d73-11e8-9e41-d2eaf806bd13.png)

# Proposed solution

For the pipenv environment to be shown by default on the built-in cmd.exe and other windows-friendly consoles,  pipenv could prepend the shell environment name to the PROMPT variable in the same way virtualenv does.

Virtualenv stores that old prompt in `_OLD_VIRTUAL_PROMPT` so it can restore the original on deactivate, but pipenv would not need that since the process is destroyed.

### Working example on cmd.exe
![image](https://user-images.githubusercontent.com/9513968/39498612-1264961c-4d77-11e8-9cf3-205b1e0e36f6.png)

### Working example on cmder
![image](https://user-images.githubusercontent.com/9513968/39498523-9a008fdc-4d76-11e8-8e70-b2870d280fa1.png)

I would be happy to work on a PR if the proposal is accepted.

PS: Pipenv environment works perfectly out of the box on my fish shell
![image](https://user-images.githubusercontent.com/9513968/39498805-49465020-4d78-11e8-93a5-92ec4518ce9a.png)

**Comment by uranusjr** [comment]
I agree with this (it’s an oversight Windows support is not added). Work on it! You might not need to mess with environment variables yourself, but can leverage existing scripts to do it. The activation is done in [`core.activate_virtualenv`](https://github.com/pypa/pipenv/blob/master/pipenv/core.py#L1190); try adding cases for cmd and Powershell first and see if that’s enough.

**Comment by gtalarico** [comment]
Sounds good. I will see what I can do.

In the meantime, I have a really simple and practical workaround, which is to add
`export PROMPT="(pipenv-projectname)$P$G"`  to the project's `.env` file so the prompt is set when the pipenv shell is loaded

![image](https://user-images.githubusercontent.com/9513968/39505922-83758826-4da3-11e8-9a28-32fb15a06017.png)

**Comment by uranusjr** [comment]
I actually wrote some Lua to do this in Cmder :p I don’t have my Windows machine around now, but can probably add a page to wiki about this.

**Comment by techalchemy** [comment]
FYI we have discussed this in the past and rejected it because cross platform support is hard, but if you can come up with something we’d review

**Comment by gtalarico** [comment]
Can you guys point me to the discussion so I don't make the same mistake and propose the same thing :)

Do we not use the same activate script from virtualenvs bat to activate on windows? 
Here is how the windows specific prompt is handled on embedded virtualenv
https://github.com/pypa/virtualenv/blob/263283be88061b965ead9ebff47c37021d7d3f62/virtualenv_embedded/activate.bat#L12

**Comment by uranusjr** [comment]
The catch is that you cannot assume CMD (there’s Powershell, and as you know Fish etc. also work), and contrary to POSIX, shell detection on Windows is much more difficult.

**Comment by uranusjr** [comment]
This should be fixed with the above PR merge. (Please correct me if I’m wrong.)
