### ISSUE TITLE
I'm getting an error when trying to run "pipenv install" on Windows 7,project folder  included Pipfile.lock and Pipfile

### ISSUE THREAD

**Issue by qipahia** [pypa/pipenv#2117]
I'm getting an error when trying to run "pipenv install":
D:\Venv\ScienceCalculate_PY365_env>pipenv install

1 windows 7 x64 Pro
2 Python version: Python 3.6.5
3 Pipenv version: 11.10.1
4 In ScienceCalculate_PY365_env project folder，which  included Pipfile.lock and Pipfile files.

[Expected result]
install Python 3.6 and all packages.

[Actual result]
D:\Venv\ScienceCalculate_PY365_env>pipenv install
Warning: Python 3.6 was not found on your system…
You can specify specific versions of Python with:
  $ pipenv --python path\to\python

**Comment by uranusjr** [comment]
And since Pyenv does not support Windows, auto Python installation is not available on Windows.

**Comment by qipahia** [comment]
I have installed python 3.6.5 in my windows 7 pro OS.
but:
D:\Venv\ScienceCalculate_PY365_env>pipenv install
Warning: Python 3.6 was not found on your system…
You can specify specific versions of Python with:
$ pipenv --python path\to\python

Then,I uninstall python 3.6.5 and install python 3.5.4.
The above situation is still the same.

Pipenv doesn‘t automatically recognize python 3.6.5 or 3.5.4 or... witch installed in my win7 OS.

**Comment by qipahia** [comment]
In my Win10x64 and Windows server 2016，pipenv works very well.

**Comment by uranusjr** [comment]
Does `pipenv install --python path\to\python.exe` work? Can you share debug information on your machine(s)? The issue template was presented when you create a new issue for a reason, and with you not filling any of it, there’s very little we can do to help because we know so little about your environment.

**Comment by techalchemy** [comment]
Not added to the `PATH` variable. If only the 3 series was installed it’s just accessible via the pep 514 finder.

**Comment by techalchemy** [comment]
Just a guess given no help output, no pipfile, no provided command

**Comment by qipahia** [comment]
I have modified the PATH variable,before "pipenv install".

Thanks，uranusjr，your command solved my problem.
