### ISSUE TITLE
Non-editable install from vcs does not work

### ISSUE THREAD

**Issue by caspervdw** [pypa/pipenv#2121]
I would like to install a package from Github in non-editable mode, mainly to not pull in dependencies. When I set `editable = false` in the `Pipfile`, and run `pipenv install`, the package is installed editable anyway, and dependencies are pulled in.

My pipenv version is 11.10.1

------------

##### Expected result

Using Pipfile:

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
slicerator = {git = "https://github.com/soft-matter/slicerator.git", editable = false, ref = "master"}

[requires]
python_version = "2.7"
```

I expect a non editable install of `slicerator`, without dependencies.

##### Actual result

```
 ROUND 1                           
Current constraints:
  slicerator from git+https://github.com/soft-matter/slicerator.git@master#egg=slicerator

Finding the best candidates:
  found candidate -e git+https://github.com/soft-matter/slicerator.git@master#egg=slicerator (constraint was <any>)

Finding secondary dependencies:

New dependencies found in this round:
  adding [u'six', '', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  six
  slicerator from git+https://github.com/soft-matter/slicerator.git@master#egg=slicerator

Finding the best candidates:
  found candidate six==1.11.0 (constraint was <any>)
  found candidate -e git+https://github.com/soft-matter/slicerator.git@master#egg=slicerator (constraint was <any>)

Finding secondary dependencies:
  six==1.11.0               requires -
------------------------------------------------------------
Result of round 2: stable, done

Updated Pipfile.lock (89400d)!
```

Resulting lockfile:

```
{
    "_meta": {
        "hash": {
            "sha256": "c7173951bea190534637732bfe1da99d65f79ac699656354358940dd1289400d"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "2.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        },
        "slicerator": {
            "editable": false,
            "git": "https://github.com/soft-matter/slicerator.git",
            "ref": "master"
        }
    },
    "develop": {}
}
```

##### Steps to replicate

Use the Pipfile above, then `pipenv install`.

This issue is part of #2068 I raised earlier.

**Comment by techalchemy** [comment]
Erm so. Dependencies are _always_ installed. Editable just dictates how thoroughly the traversal is done and whether they land in your lockfile. It would be kind of pointless if you could install something and it didn’t include dependencies. Pip forces you to explicitly pass `--no-deps` for that

**Comment by caspervdw** [comment]
@techalchemy  In the docs it is stated that sub-dependencies are not resolved if you set editable to false:

["Sub-dependencies are not added to the Pipfile.lock if you leave the -e option out."](
https://docs.pipenv.org/basics/#editable-dependencies-e-g-e)
["If editable is not true, sub–dependencies will not be resolved."](https://docs.pipenv.org/basics/#a-note-about-vcs-dependencies)

Instead, `pip` is called with `-e`, sub-dependencies (here: `six`) are resolved, and they end in the lockfile.

As far as I can see, there is no difference currently between `editable = true` and `editable = false`?

**Comment by techalchemy** [comment]
@caspervdw I see. There is possibly no difference between `editable = true` and `editable = false` but I have never seen this used this way. If you exclude the `editable` key entirely (because it’s presence is what toggles the flag for pip, we just need to assign a value to it) it works as described. I say this often, but this is among the reasons to let pipenv build your pipfiles.

**Comment by techalchemy** [comment]
Also to improve our documentation and handling of these kinds of cases of course. This is a pretty dumb bug to have, and I can see why you would toggle it to false

**Comment by techalchemy** [comment]
Omg. Definitely a bug. This part of our codebase sucks. I probably introduced this last time I touched it.  Will have a look. Thanks for the report!

**Comment by caspervdw** [comment]
Happy to help! Thanks for the fast responses. Maybe good to reopen the issue?
