### ISSUE TITLE
virtualenv name contains full python path if PIPENV_PYTHON is a path

### ISSUE THREAD

**Issue by SethMMorton** [pypa/pipenv#2124]
##### Expected result

When using `pipenv install`  with the `PIPENV_PYTHON` environment variable set to the full path of an existing python installation, I would expect the resulting virtualenv path to be named similarly to if the `--python` command-line option were used.

##### Actual result

The virtual environment name contains the full path to that existing python installation, and thus has a rather deep hierarchy.  I do not believe this actually has any negative effects for me beyond unnecessary directories, but I'm not sure if it is the intended behavior - my guess is that `PIPENV_PYTHON` is appended to the virtualenv name for the cases where a user set the value to a python version (e.g. `3.6`) and not for a full path.

##### Steps to replicate

Using the `--python` option with a full python path gives the virtualenv name that I would expect (`demo-Qnml4myH`).

```bash
 % cd demo                                                                                                                                                                                       
 % pipenv install --python /home/me/Miniconda/3.6.3/bin/python
Creating a virtualenv for this project…
Using /home/me/Miniconda/3.6.3/bin/python (3.6.3) to create virtualenv…
⠋Running virtualenv with interpreter /home/me/Miniconda/3.6.3/bin/python
Using base prefix '/home/me/Miniconda/3.6.3'
New python executable in /home/me/.local/share/virtualenvs/demo-Qnml4myH/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/me/.local/share/virtualenvs/demo-Qnml4myH
Creating a Pipfile for this project…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (ca72e7)!
Installing dependencies from Pipfile.lock (ca72e7)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell                                                                                                                                                                                          
```
Using `PIPENV_PYTHON` instead of `--python` gives a virtualenv name that itself is a hierarchical path (`demo2-Ap4OScU9-/home/me/Miniconda/3.6.3/bin/python/bin/python`)

```bash
 % cd ../demo2                                                                                                                                                                                  
 % export PIPENV_PYTHON=/home/me/Miniconda/3.6.3/bin/python
 % pipenv install                                                    
Creating a virtualenv for this project…
Using /home/me/Miniconda/3.6.3/bin/python (3.6.3) to create virtualenv…
⠋Running virtualenv with interpreter /home/me/Miniconda/3.6.3/bin/python
Using base prefix '/home/me/Miniconda/3.6.3'
New python executable in /home/me/.local/share/virtualenvs/demo2-Ap4OScU9-/home/me/Miniconda/3.6.3/bin/python/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/me/.local/share/virtualenvs/demo2-Ap4OScU9-/home/me/Miniconda/3.6.3/bin/python
Creating a Pipfile for this project…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (ca72e7)!
Installing dependencies from Pipfile.lock (ca72e7)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell

```

**Comment by techalchemy** [comment]
Lol.  I'm amazed this variable even works, last tiem I used it it didnt :) i think we only use it for CI sometimes...

**Comment by uranusjr** [comment]
@SethMMorton The intended usage is not to specify the full path, but only a version number (e.g. `3.6`), but I guess there’s no reason it can’t be used for full paths. I would say it’s fine to implement some simple logic to shorten the path. Would you be interested in working on a pull request? All the logic would be in `pipenv.project.Project.virtualenv_name`.

**Comment by techalchemy** [comment]
I think the main point is we still want to derive a deterministic hash of the location. This was meant as a helper similar to toxenv I’m not sure it makes sense to complicate it unless you simply take a path and parse the version from that.

**Comment by SethMMorton** [comment]
Given that `pipenv --python /path/to/python` does not attempt to append the python path to the virtual environment name, I wonder if a reasonable solution would to check only append the value of `PYTHON_PIPENV` to the virtual environment name if `os.path.isfile` (or `os.path.exists`) is `False`. To me this would at least be consistent behavior.

**Comment by techalchemy** [comment]
This isn’t even a documented variable, much less part of the normal defined api or behavior. Expecting it to behave consistently would be a bit odd because the explicit purpose of this environment variable is to append things to the environment name for CI usage. 

Basically this isn’t designed to behave like other commands— it’s whole purpose is to behave the way it does. If you want to have it point at a specific python why not use the `--python` argument which exists for this and use the environment variable to append something to the name?

**Comment by SethMMorton** [comment]
@techalchemy As mentioned in [my earlier comment](https://github.com/pypa/pipenv/issues/2124#issuecomment-386374447), I am trying to use functionality from the [direnv](https://github.com/direnv/direnv) project that calls `pipenv` but does not provide a hook to directly use the `--python` command-line argument.

Using `pipenv` version 11.0.1, when I use the `--envs` command-line argument, I get the following output (comment added by me):

```
$ pipenv --envs
The following environment variables can be set, to do various things:

  - PIPENV_SHELL_FANCY
  - PIPENV_PYTHON                       # <====  HERE
  - PIPENV_VENV_IN_PROJECT
  - PIPENV_TEST_INDEX
  - PIPENV_COLORBLIND
  - PIPENV_NOSPIN
  - PIPENV_MAX_ROUNDS
  - PIPENV_PIPFILE
  - PIPENV_DEFAULT_PYTHON_VERSION
  - PIPENV_DONT_LOAD_ENV
  - PIPENV_YES
  - PIPENV_MAX_SUBPROCESS
  - PIPENV_MAX_DEPTH
  - PIPENV_NO_INHERIT
  - PIPENV_VIRTUALENV
  - PIPENV_USE_SYSTEM
  - PIPENV_USE_HASHES
  - PIPENV_SKIP_VALIDATION
  - PIPENV_DOTENV_LOCATION
  - PIPENV_HIDE_EMOJIS
  - PIPENV_TIMEOUT
  - PIPENV_INSTALL_TIMEOUT
  - PIPENV_DONT_USE_PYENV
  - PIPENV_SHELL
  - PIPENV_CACHE_DIR

You can learn more at:
   http://docs.pipenv.org/advanced/#configuration-with-environment-variables
```

It is true that the variable is not listed in the list at http://docs.pipenv.org/advanced/#configuration-with-environment-variables, but the fact that it shows up with `--envs` made be believe it was "sanctioned" in some way for non-internal use.

**Comment by SethMMorton** [comment]
I am going to self-close this issue.  It seems that this is a "for-internal-use-only" variable that accidentally made its way into a user-facing list.  For my part I will try to replicate the functionality in another way. Thank you for your time.

**Comment by techalchemy** [comment]
@SethMMorton it's meant to be set only as an appended python version to modify the normal virtualenv name.  If you want it to behave differently (e.g. to parse the version from a full path) that's going to be a low-priority enhancement most likely, we never intended to do anything fancy with this

**Comment by SethMMorton** [comment]
No... closing the issue was my signal that I do not want it to behave differently.
