### ISSUE TITLE
Virtualenv's site.py

### ISSUE THREAD

**Issue by matejcik** [pypa/pipenv#2139]
pipenv seems to use virtualenv internally.
There are several known problems with virtualenv using its own `site.py` as opposed to Python's one, see https://github.com/pypa/virtualenv/issues/355
In particular this means that Python 3 tab completion is not enabled by default.

A simple workaround (unsure how simple really) would be to use python's `venv` module in Python 3

**Comment by techalchemy** [comment]
Please review the previous discussions on this topic. We use virtualenvs for compatibility reasons.
