### ISSUE TITLE
requirements.txt lists old version of pathlib2

### ISSUE THREAD

**Issue by jhgit** [pypa/pipenv#2140]
pipenv lists pathlib2==2.1.0 as a requirement (for python2.7).  More recent versions of pathlib2 are newer than 2.1.0 have been released.  If you have a newer version installed, pipenv throws an error.

Does pipenv really only work with pathlib2 2.1.0?

Please run `$ python -m pipenv.help`, and paste the results here.

==========================
<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.1'`

Pipenv location: `'pipenv'`

Python location: `'/usr/local/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `3.5`: `/usr/local/bin/python3.5m`
  - `3.5`: `/usr/local/bin/python3.5`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`

  - `2.7.14`: `/usr/local/bin/python`
  - `2.7.14`: `/usr/local/bin/python2`
  - `3.5.5`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'amd64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10.4-STABLE',
 'platform_system': 'FreeBSD',
 'platform_version': 'FreeBSD 10.4-STABLE #2 r327488M: Thu Jan  4 15:09:54 MST 2018     me@build:/usr/obj/usr/src/sys/MYKERN',
 'python_full_version': '2.7.14',
 'python_version': '2.7',
 'sys_platform': 'freebsd10'}
```

System environment variables:

  - `PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/pipenv/help.py", line 89, in <module>
    main()
  File "/tmp/pipenv/help.py", line 48, in main
    print(u'Pipenv–specific environment variables:')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 6: ordinal not in range(128)

=======================

------------

##### Expected result

I was expecting pipenv to work with a recent pathlib2

##### Actual result

pkg_resources.DistributionNotFound: The 'pathlib2==2.1.0' distribution was not found and is required by pipenv

##### Steps to replicate

Install a pathlib2 newer than 2.1.0 (released in 2015).
Install pipenv 10.11.0 or .1
Run pipenv & observe requirements exception failure.

**Comment by uranusjr** [comment]
I take you mean the `install_requires` field in setup.py. Honestly I have no idea.

**Comment by techalchemy** [comment]
The answer is yes and no— we had a lot of issues when I unpinned this due to a hard dependency of any newer version on `scandir`. If we have this vendored properly it shouldn’t matter

**Comment by lorengordon** [comment]
See #2153 for at least one issue caused by newer versions of pathlib2...

**Comment by techalchemy** [comment]
Yep, just dropped it completely from setup.py and switched everything to our vendored version
