### ISSUE TITLE
psycopg2 module not found error

### ISSUE THREAD

**Issue by dmckim1977** [pypa/pipenv#2144]
When making migrations on a new django 2 project it is saying psycopg2 is improperly configured or not found. 

```
"raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'"
```

psycopg2 is installed globally and in the environment django is installed in. 

From pipenv graph:

```
Django==2.0.5
  - pytz [required: Any, installed: 2018.4]
psycopg2==2.7.4
```

This is from outside the env:

```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
>>>
```

psycopg2 is installed but for some reason django is not seeing it when trying to makemigrations or migrating. 

This is from the settings.py file:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'mysite',
        'USER': 'username',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '',
    }
}
```

**Comment by uranusjr** [comment]
Please fill out the issue template, and provide a procedure for us to reproduce. There is basically no way to debug this with so little information.

**Comment by dmckim1977** [comment]
I thought I did as best I could anyway. 

I ran python -m pipenv.help and I didn't give me anything. 

I uninstalled pipenv and reinstalled and still had the issue. I also upgraded to pip 10, reinstalled pipenv and now it works.
