### ISSUE TITLE
Error installing pipenv on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by gtalarico** [pypa/pipenv#2162]
Trying to install pipenv on Ubuntu > [WSL](http://wsl-guide.org/en/latest/)
Followed [instructions](https://docs.pipenv.org/#install-pipenv-today) from docs:
```
$ sudo apt install software-properties-common python-software-properties
[ OK ]
$ sudo add-apt-repository ppa:pypa/ppa
[ OK ]
$ sudo apt update
...
```

`sudo apt update` fails with the message below:
```
Err:5 http://ppa.launchpad.net/pypa/ppa/ubuntu xenial Release
404  Not Found
```

Since it failed to update the repo, installs also fails:
```
$ sudo apt install pipenv
E: Unable to locate package pipenv
```

I am not very familiar with ubuntu's packaging repositories,
but are missing a release compatible with WSL ubuntu flavor (xenial) ?

```lsb_release -a```

```No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

**Comment by uranusjr** [comment]
#2059. Not specific to WSL, the PPA simply does not contain a Xenial build. I recommend installing with `pip install --user` (or pipsi).
