### ISSUE TITLE
pipenv install --python path/to/specific doesn't seem to work right

### ISSUE THREAD

**Issue by twig** [pypa/pipenv#2166]
**Describe the issue briefly here.**

My system version of python is 2.7.6.
I've got python 2.7.15 compiled locally and wish to use it for the virtualenv as below

> pipenv install --python ~/python/compiled/2.7.15/bin/python2.7
> pipenv shell
> python --version

The virtualenv creation process seems to work fine, but when I start `pipenv shell`, it seems to be using python 2.7.6

**Please run `$ python -m pipenv.help`, and paste the results here.**

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.4'`

Pipenv location: `'/usr/local/lib/python2.7/dist-packages/pipenv'`

Python location: `'/usr/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.4`: `/usr/bin/python3.4m`
  - `3.4`: `/usr/bin/python3.4`

  - `2.7.6`: `/usr/bin/python`
  - `2.7.6`: `/usr/bin/python2`
  - `3.4.0`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '3.16.0-30-generic',
 'platform_system': 'Linux',
 'platform_version': '#40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015',
 'python_full_version': '2.7.6',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `PYTHONDONTWRITEBYTECODE`
  - `LESSOPEN`
  - `SSH_CLIENT`
  - `LOGNAME`
  - `USER`
  - `HOME`
  - `PATH`
  - `PS1`
  - `SSH_AGENT_PID`
  - `LANG`
  - `TERM`
  - `SHELL`
  - `LANGUAGE`
  - `SHLVL`
  - `_VIRTUALENVWRAPPER_API`
  - `WORKON_HOME`
  - `SSH_AUTH_SOCK`
  - `XDG_RUNTIME_DIR`
  - `COMP_WORDBREAKS`
  - `PIP_PYTHON_PATH`
  - `XDG_SESSION_ID`
  - `_`
  - `VIRTUALENVWRAPPER_PROJECT_FILENAME`
  - `SSH_CONNECTION`
  - `LESSCLOSE`
  - `VIRTUALENVWRAPPER_HOOK_DIR`
  - `SSH_TTY`
  - `OLDPWD`
  - `VIRTUALENVWRAPPER_SCRIPT`
  - `PWD`
  - `MAIL`
  - `LS_COLORS`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/twig/bin:/home/twig/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/share/elasticsearch/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_AU.UTF-8`
  - `PWD`: `/home/twig/src/OpenLearningEngine`

---------------------------

Contents of `Pipfile` ('/home/twig/src/OpenLearningEngine/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]

[requires]
python_version = "2.7"

```

Contents of `Pipfile.lock` ('/home/twig/src/OpenLearningEngine/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "ae4bdd7d4157baab65ae9d0e8389a6011e6b640995372c45ec81fa5d1ddfae9f"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "2.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

------------

##### Expected result

Expected "python --version" to print out `2.7.15`

##### Actual result

Output was `2.7.6`

##### Steps to replicate

* rm -rf Pipfile Pipfile.lock ~/.virtualenvs/TestProject-nEJHdvQJ
* pipenv install --python ~/python/compiled/2.7.15/bin/python2.7
* pipenv shell
* python --version

Here are the logs as I typed the commands.

```
twig@nix:~/src/TestProject$ rm -rf Pipfile Pipfile.lock ~/.virtualenvs/TestProject-nEJHdvQJ
twig@nix:~/src/TestProject$ pipenv install --python ~/python/compiled/2.7.15/bin/python2.7
Creating a virtualenv for this project…
Using /home/twig/python/compiled/2.7.15/bin/python2.7 (2.7.15) to create virtualenv…
⠋Running virtualenv with interpreter /home/twig/python/compiled/2.7.15/bin/python2.7
New python executable in /home/twig/.virtualenvs/TestProject-nEJHdvQJ/bin/python2.7
Also creating executable in /home/twig/.virtualenvs/TestProject-nEJHdvQJ/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/twig/.virtualenvs/TestProject-nEJHdvQJ
Creating a Pipfile for this project…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (dfae9f)!
Installing dependencies from Pipfile.lock (dfae9f)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell


twig@nix:~/src/TestProject$ pipenv shell
Loading .env environment variables…
Spawning environment shell (/bin/bash). Use 'exit' to leave.
. /home/twig/.virtualenvs/TestProject-nEJHdvQJ/bin/activate


(TestProject-nEJHdvQJ) twig@nix:~/src/TestProject$ python --version
Python 2.7.6


(TestProject-nEJHdvQJ) twig@nix:~/src/TestProject$ whereis python
python: /usr/bin/python /usr/bin/python2.7 /usr/bin/python3.4m /usr/bin/python3.4 /usr/bin/python2.7-config /etc/python /etc/python2.7 /etc/python3.4 /usr/lib/python2.7 /usr/lib/python3.4 /usr/bin/X11/python /usr/bin/X11/python2.7 /usr/bin/X11/python3.4m /usr/bin/X11/python3.4 /usr/bin/X11/python2.7-config /usr/local/lib/python2.7 /usr/local/lib/python3.4 /usr/include/python2.7 /usr/share/python /usr/share/man/man1/python.1.gz
```

**Comment by techalchemy** [comment]
use the full path -- also this is really meant to be done when you already have a pipfile etc., creating an environment of nothing is not really the role of pipenv.

**Comment by twig-openlearning** [comment]
Hey @techalchemy , I tried again with the full path and it still produces the same result.

Is there something I have misunderstood with how pipenv differs to using virtualenv normally?

```
twig@nix:~/src/staging$ pipenv install --python /home/twig/python/compiled/2.7.15/bin/python
Creating a virtualenv for this project…
Using /home/twig/python/compiled/2.7.15/bin/python (2.7.15) to create virtualenv…
⠋Running virtualenv with interpreter /home/twig/python/compiled/2.7.15/bin/python
New python executable in /home/twig/.virtualenvs/staging-yabiGdb7/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/twig/.virtualenvs/staging-yabiGdb7
Installing dependencies from Pipfile.lock (aa66ed)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 7/7 — 00:00:17
To activate this project's virtualenv, run the following:
 $ pipenv shell

twig@nix:~/src/staging$ pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave.
. /home/twig/.virtualenvs/staging-yabiGdb7/bin/activate

twig@nix:~/src/staging$ python --version
Python 2.7.6
```

**Comment by twig** [comment]
Spoke to @uranusjr regarding the issues and it turns out to be a [script](https://stackoverflow.com/a/13034313/253704) causing shell issues with pipenv.

Leaving this here for reference in case anyone else runs into this issue.

**Comment by lulullamozagamboa** [comment]
> Habló a@uranusjrcon respecto a los problemas y resulta ser un [script](https://stackoverflow.com/a/13034313/253704) en .bashrc que causa problemas de shell con pipenv.
> 
> Dejo esto aquí como referencia en caso de que alguien más se encuentre con este problema.

hola  ramita me ayudas a solucionar tengo el mismo problema
