### ISSUE TITLE
pipenv --two fails with PIPENV_VENV_IN_PROJECT

### ISSUE THREAD

**Issue by skurfer** [pypa/pipenv#2174]
With `PIPENV_VENV_IN_PROJECT` true, `pipenv --two` tries to use Python 3 and fails to create a virtual environment.

Note that if you installed using Homebrew, you need to run `/usr/local/Cellar/pipenv/11.10.4/libexec/bin/python -m pipenv.help`

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.4'`

Pipenv location: `'/usr/local/Cellar/pipenv/11.10.4/libexec/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/11.10.4/libexec/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/Users/rob/Developer/Python/Environments/tools2/bin/python2.7`
  - `2.7`: `/Users/rob/Developer/Python/Environments/tools2/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.6`: `/Users/rob/Developer/Python/Environments/tools/bin/python3.6`
  - `3.6`: `/Users/rob/Developer/Python/Environments/tools/bin/python3.6`

  - `3.6.5`: `/usr/local/opt/python/libexec/bin/python`
  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `3.6.5`: `/usr/local/opt/python/libexec/bin/python`
  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `3.6.5`: `/Users/rob/Developer/Python/Environments/tools/bin/python`
  - `2.7.15`: `/Users/rob/Developer/Python/Environments/tools2/bin/python`
  - `3.6.5`: `/Users/rob/Developer/Python/Environments/tools/bin/python`
  - `2.7.15`: `/Users/rob/Developer/Python/Environments/tools2/bin/python`
  - `2.7.15`: `/usr/local/bin/python2`
  - `2.7.15`: `/usr/local/bin/python2`
  - `2.7.15`: `/usr/local/bin/python2`
  - `2.7.15`: `/Users/rob/Developer/Python/Environments/tools2/bin/python2`
  - `2.7.15`: `/Users/rob/Developer/Python/Environments/tools2/bin/python2`
  - `3.6.5`: `/usr/local/bin/python3`
  - `3.6.5`: `/usr/local/bin/python3`
  - `3.6.5`: `/usr/local/bin/python3`
  - `3.6.5`: `/Users/rob/Developer/Python/Environments/tools/bin/python3`
  - `3.6.5`: `/Users/rob/Developer/Python/Environments/tools/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT '
                     '2018; root:xnu-4570.51.2~1/RELEASE_X86_64',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TMPDIR`
  - `XPC_FLAGS`
  - `Apple_PubSub_Socket_Render`
  - `TERM`
  - `SSH_AUTH_SOCK`
  - `DISPLAY`
  - `SECURITYSESSIONID`
  - `XPC_SERVICE_NAME`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `SHELL`
  - `HOME`
  - `LOGNAME`
  - `USER`
  - `PATH`
  - `SHLVL`
  - `PWD`
  - `OLDPWD`
  - `PAGER`
  - `EDITOR`
  - `DISABLE_UNTRACKED_FILES_DIRTY`
  - `HISTFILE`
  - `HISTSIZE`
  - `SAVEHIST`
  - `LESS`
  - `RSYNC_RSH`
  - `GREP_COLOR`
  - `LSCOLORS`
  - `FZF_TMUX`
  - `FZF_TMUX_HEIGHT`
  - `FZF_DEFAULT_OPTS`
  - `KRB5_CONFIG`
  - `WORKON_HOME`
  - `PROJECT_HOME`
  - `PYENV_ROOT`
  - `PY2`
  - `LC_CTYPE`
  - `EVENT_NOKQUEUE`
  - `LESSEDIT`
  - `JAVA_HOME`
  - `VIRTUALENVWRAPPER_PROJECT_FILENAME`
  - `VIRTUALENVWRAPPER_WORKON_CD`
  - `VIRTUALENVWRAPPER_SCRIPT`
  - `VIRTUALENVWRAPPER_HOOK_DIR`
  - `ZSH_TMUX_TERM`
  - `_ZSH_TMUX_FIXED_CONFIG`
  - `LANG`
  - `REPORTTIME`
  - `_`
  - `__CF_USER_TEXT_ENCODING`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/rob/Developer/Python/Environments/tools/bin:/Users/rob/Developer/Python/Environments/tools2/bin:/Users/rob/bin:.:/Users/rob/Developer/Python/Environments/tools/bin:/Users/rob/Developer/Python/Environments/tools2/bin:/Users/rob/bin:.`
  - `SHELL`: `/usr/local/bin/zsh`
  - `EDITOR`: `mate_wait`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/rob`

---------------------------

</details>
------------

##### Expected result

With `PIPENV_VENV_IN_PROJECT` undefined, `pipenv --two` does what I expect:

  1. Creates a Pipfile with `python_version = "2.7"`
  2. Creates a new virtual environment using Python 2 in `$WORKON_HOME`

##### Actual result

If I enable `PIPENV_VENV_IN_PROJECT` and run `pipenv --two`:

  1. A Pipfile is created with `python_version = "3.6"`
  2. No virtual environment is created at `.venv`
  3. If I run `pipenv shell`, it attempts to create a virtual environment in `.venv` using Python 3, but that and everything after fails.

##### Steps to replicate

<details>
<summary>sample shell commands and output</summary>

Note that `python` on my system (outside of any virtualenv) refers to 3.6.

```
❯ echo $PIPENV_VENV_IN_PROJECT


❯ mkdir project

❯ cd project 

❯ pipenv --two
Creating a virtualenv for this project…
Using /usr/local/bin/python2 (2.7.15) to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python2
New python executable in /Users/rob/Developer/Python/Environments/project-az5PATU3/bin/python2.7
Also creating executable in /Users/rob/Developer/Python/Environments/project-az5PATU3/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/rob/Developer/Python/Environments/project-az5PATU3
Creating a Pipfile for this project…
pipenv --two  4.28s user 1.27s system 55% cpu 10.063 total

❯ ls -la
total 8
drwxr-xr-x   3 rob  staff    96 May 10 13:38 .
drwxr-xr-x+ 91 rob  staff  2912 May 10 13:39 ..
-rw-r--r--   1 rob  staff   138 May 10 13:39 Pipfile

❯ pipenv shell
Spawning environment shell (/usr/local/bin/zsh). Use 'exit' to leave.
. /Users/rob/Developer/Python/Environments/project-az5PATU3/bin/activate

❯ . /Users/rob/Developer/Python/Environments/project-az5PATU3/bin/activate
(project-az5PATU3) 
❯ python --version
Python 2.7.15
(project-az5PATU3) 
❯ exit

❯ rm Pipfile; rmvirtualenv project-az5PATU3 
Removing project-az5PATU3…
```

```
❯ export PIPENV_VENV_IN_PROJECT=1

❯ pipenv --two
Creating a virtualenv for this project…
Using /usr/local/bin/python2 (2.7.15) to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python2
The PYTHONDONTWRITEBYTECODE environment variable is not compatible with setuptools. Either use --distribute or unset PYTHONDONTWRITEBYTECODE.

Virtualenv location: /Users/rob/project/.venv
Creating a Pipfile for this project…

❯ ls -la
total 8
drwxr-xr-x   3 rob  staff    96 May 10 13:40 .
drwxr-xr-x+ 91 rob  staff  2912 May 10 13:40 ..
-rw-r--r--   1 rob  staff   138 May 10 13:40 Pipfile

❯ pipenv shell
Creating a virtualenv for this project…
Using /usr/local/bin/python3.6m (3.6.5) to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python3.6m
New python executable in /Users/rob/project/.venv/bin/python3.6
Also creating executable in /Users/rob/project/.venv/bin/python
Failed to import the site module
Traceback (most recent call last):
  File "/Users/rob/project/.venv/bin/../lib/python3.6/site.py", line 67, in <module>
    import os
  File "/Users/rob/project/.venv/bin/../lib/python3.6/os.py", line 652, in <module>
    from _collections_abc import MutableMapping
ModuleNotFoundError: No module named '_collections_abc'
ERROR: The executable /Users/rob/project/.venv/bin/python3.6 is not functioning
ERROR: It thinks sys.prefix is '/Users/rob/project' (should be '/Users/rob/project/.venv')
ERROR: virtualenv is not compatible with this system or executable

Virtualenv location: /Users/rob/project/.venv
Spawning environment shell (/usr/local/bin/zsh). Use 'exit' to leave.
. /Users/rob/project/.venv/bin/activate

❯ . /Users/rob/project/.venv/bin/activate
.: no such file or directory: /Users/rob/project/.venv/bin/activate
✗ 127
❯ ls -la
total 8
drwxr-xr-x   4 rob  staff   128 May 10 13:41 .
drwxr-xr-x+ 91 rob  staff  2912 May 10 13:41 ..
drwxr-xr-x   6 rob  staff   192 May 10 13:41 .venv
-rw-r--r--   1 rob  staff   138 May 10 13:40 Pipfile
```
</details>

A work-around is to manually run `virtualenv -p python2 .venv` _before_ running any `pipenv` commands.

**Comment by uranusjr** [comment]
`python` is Python 2 from Homebrew (not the same as `python2`). This sounds too much like a configuration problem I really need a clean, producible environment to work on.
