### ISSUE TITLE
VCS packages should be locked with their exact commit

### ISSUE THREAD

**Issue by OrangeDog** [pypa/pipenv#2180]
Not sure how hard this is, but it would fill a current hole in the locking mechanism.

All of these Pipfile entries are locked as-is:
```
package = {git = "ssh://git@bitbucket.org/user/repo.git"}
package = {ref="master", git = "ssh://git@bitbucket.org/user/repo.git"}
package = {ref="v1.0", git = "ssh://git@bitbucket.org/user/repo.git"}
package = {ref="dd9e921", git = "ssh://git@bitbucket.org/user/repo.git"}
```
```
"package": {
    "git": "ssh://git@bitbucket.org/user/repo.git",
    "ref": "master"
}
```

Instead, to ensure the target is actually fixed, the ref should be resolved to its current target when locking.
```
"package": {
    "git": "ssh://git@bitbucket.org/user/repo.git",
    "ref": "dd9e921f0fa31c50ffb7bff91c5c9c6d552f1b3a",
    "version": "==1.0.2"
}
```
The hashes can then also be included.

**Comment by OrangeDog** [comment]
It also doesn't lock things installed via dependency_links, but that's a separate issue (though they are deprecated, there is no alternative solution that I know of).

**Comment by techalchemy** [comment]
@OrangeDog I was actually just looking at that, no need for a separate issue.  I have like 80% of a solution.  Locking the actual refs is working but you can see the WIP branch here: https://github.com/pypa/pipenv/commit/ea6f02da95a7835dda059b082ce649fcb0159af3

**Comment by OrangeDog** [comment]
@techalchemy I just tested 2018.6.25 and it still doesn't appear to lock the `install_requires` of VCS packages (though they are still installed). You want that separate issue now?
