### ISSUE TITLE
.env file having \ does not work properly

### ISSUE THREAD

**Issue by dhruvinsh** [pypa/pipenv#2182]
as pipenv automatically load environment variable form .env file, a variable containing  backward slash '\' does not end up properly,
For example,
.env file with
`test=hi\hello`

and in python,
```
import os
print os.getenv('test') 
print repr(os.getenv('test')
```
Output is something like:
```
hi\\hello
hi\\\\hello
```
pipenv: 11.10.1
windows: 10
python: 2.7.14

**Comment by uranusjr** [comment]
This is provided by python-dotenv. You’d want to report there first, and when they update we can pull in the changes.
