### ISSUE TITLE
Why I can create only one virtualenv

### ISSUE THREAD

**Issue by jarrekk** [pypa/pipenv#2185]
Hey, I installed `pipenv` with `brew install pipenv`, the version of Python and pipenv are:

- Python: 3.6.5
- pipenv: 2018.5.18

But now I can only create one virtualenv with python:3.6.5, no matter where I am:

```
~
•100% ➜ cd hello

~/hello
•100% ➜ pipenv --three
Creating a virtualenv for this project…
Using /usr/local/bin/python3 (3.6.5) to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/jack/.local/share/virtualenvs/jack-JNXsLa7q/bin/python3.6
Also creating executable in /Users/jack/.local/share/virtualenvs/jack-JNXsLa7q/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/jack/.local/share/virtualenvs/jack-JNXsLa7q

~/hello took 8s
•100% ➜ pipenv --rm
Removing virtualenv (/Users/jack/.local/share/virtualenvs/jack-JNXsLa7q)…

~/hello
•100% ➜ cd ../world

~/world
•100% ➜ pipenv --three
Creating a virtualenv for this project…
Using /usr/local/bin/python3 (3.6.5) to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/jack/.local/share/virtualenvs/jack-JNXsLa7q/bin/python3.6
Also creating executable in /Users/jack/.local/share/virtualenvs/jack-JNXsLa7q/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/jack/.local/share/virtualenvs/jack-JNXsLa7q

~/world took 7s
•100% ➜ cd ;pwd
/Users/jack
```

The two projects' virtualenv path are the same: `/Users/jack/.local/share/virtualenvs/jack-JNXsLa7q`.

IMO, the Python virtualenv should be located at:

- /Users/jack/.local/share/virtualenvs/**hello**-JNXsLa7q 
- /Users/jack/.local/share/virtualenvs/**world**-JNXsLa7q 

based on the video instructor at https://docs.pipenv.org/

But they all use the home folder's name, so the `Pipfile` is located at `/Users/jack`.

Look forward for your help & reply. :)

**Comment by gsemet** [comment]
you probably have a pipfile in your home folder. Pipenv looks for the first pipfile in one of the parent folder

**Comment by jarrekk** [comment]
@gsemet thanks! This is the root cause, I have gone through the document and didn't find any about this, is it better to add this to the document or remove this feature?

**Comment by uranusjr** [comment]
It’s probably not a good idea to remove it altogether (because it is expected in some cases), but maybe it would be a good idea to have a way to tell Pipenv “I want my project *here*, do not care about parent directories at all”.

**Comment by uranusjr** [comment]
Discussion in #2188.
