### ISSUE TITLE
find virtualenvs with deleted folder?

### ISSUE THREAD

**Issue by AlJohri** [pypa/pipenv#2187]
hi there, quick Q. my hard drive is filling up and I wondering if you could suggest a command to run to delete "unused virtualenvs" (virtualenvs with renamed or deleted folders).

if the hash at the end of the venv name is reversible, I could use it to `stat` the project directory to make sure it still exists? wondering if you've tried something like this before.

<img width="568" alt="screen shot 2018-05-13 at 2 33 51 pm" src="https://user-images.githubusercontent.com/2790092/39970511-afe5f45c-56ba-11e8-8b17-9faa4edfb428.png">

closest issue I found was https://github.com/pypa/pipenv/issues/202

**Comment by uranusjr** [comment]
I don’t think the hashes are reversible (MD5 IIRC), so you’ll have to brute-force, unfortunately. If you come up with paths to test, this is how you test if the virtualenv name matches:

```python
from pipenv.core import project
print(project.virtualenv_name)
```

This would improve after #1861 is merged, or if you use Pipes or Pew to associate the project and virtualenv.
