### ISSUE TITLE
Exception in resolver

### ISSUE THREAD

**Issue by gsemet** [pypa/pipenv#2190]
Found during a pipenv update [against this commit](https://github.com/Guake/guake/commit/43971f12ee177f8afc0277141f7b82f5ea5dd07c) using pipenv 2018.05.18:
```
$ pipenv lock
Locking [dev-packages] dependencies…
al/lib/python3.5/site-packages/pipenv/resolver.py", line 71, in main
    sources=project.pipfile_sources,
AttributeError: 'Project' object has no attribute 'pipfile_sources'
```

Revert back to pipenv-11.10.4 did not fixed the issue.
Fixed by reverting to pipenv-11.10.1

I install pipenv using:
```
pip3 install --user --upgrade 'pipenv==11.10.2'
```

Summary:
- 2018.05.18 : failed
- 11.10.4: failed
- 11.10.3: failed
- 11.10.2: failed
- 11.10.1: work
- 11.10.0: work

Going back and forth from 11.10.1 to 11.10.2 reproduce this issue, so their have been a change in 11.10.2 that break the pipfile parser.

Maybe it would worth a try to define a "unstable" release channel of pipenv, to avoid breaking change like that that might impact everybody. Are we supposed to use "latest" pipenv or freeze the version of pipenv used in a project? At least early adopters can test these change and general public only get well tested pipenv packages.

**Comment by uranusjr** [comment]
I saw this somewhere else before (in SMS chat IIRC), and the ultimate problem is you might have multiple copies of Pipenv in your system, and it gets confused which one to use. `pipfile_sources` was addedd relatively recently, so if it (mistakenly) tries to import the wrong (older) copy, it will break. I’d suggest looking through your `sys.path` to find extraneous Pipenv installations, and remove all of them except the one you actually want to use.

Please reopen this if this does not work.
