### ISSUE TITLE
Add an intuitive way to use Pipenv without a home directory to facilitate use in deployment scenarios

### ISSUE THREAD

**Issue by brandonvin** [pypa/pipenv#2195]
## The problem
I attempted to automate deployment of some Python code that uses Pipenv to isolate itself and lock its dependencies. The automation is in the form of a Chef cookbook. I ran into frustration while executing the command `pipenv install --deploy` due to the fact that Pipenv makes liberal use of the current value of `HOME` and assumes that whatever is in `HOME` is readable and writeable by the executing user. However, my Chef cookbook executes commands as an unprivileged user, in a very clean environment where typical environment variables such as `HOME` are not set (unless hacks are used). The usage of an unprivileged user and clean environment are engineering standards set by the organization I work for.

## The temporary workaround
I was able to get the deployment process to work in a way that avoids touching the home directory, by using environment variables such as `PIPENV_VENV_IN_PROJECT` and `PIPENV_CACHE_DIR`. It could also conceivably work to spoof the `HOME` variable with some non-home directory.

## The solution I'd like
Assumptions about the current user's home directory and environment variables should be documented explicitly, with the mindset that Pipenv is a tool that will be used in automation frameworks where these things are not guaranteed.

It would be ideal to avoid environment variable trickery and create a clean, streamlined deployment process. Pipenv could allow running in a mode that abandons all assumptions about the current user's home directory. This could be in the form of a command-line flag, such as `--no-home-directory` (just for example).

## Alternatives I've considered
An alternative solution is to change the way that we approach deployments at my organization, or to make a special case for this application. I have spoken with other people in my organization about setting the home directory to be readable and writeable for this particular cookbook, to avoid kludges and workarounds while still considering security.

**Comment by uranusjr** [comment]
Also I’m wondering how pip would have worked in this situation. If you need to tweak `PIP_CACHE_DIR` it means even using pip directly is problematic.

**Comment by uranusjr** [comment]
One more question (sorry for comment spamming): What commands exactly are you using for deployment, and what breaks exactly when you *don’t* specify `PIPENV_CACHE_DIR`? I don’t think it should even be used at all in this situation…

**Comment by techalchemy** [comment]
@brandonvin typically we would suggest using `--system`.  If we can't find a home directory I think a sensible default would be `.venv`.

**Comment by reinout** [comment]
@brandonvin, you mention "environment variable trickery". Would a config file (as suggested in #2778) already help? A config file can be added to version control and there you could configure all the settings you need.

**Comment by brandonvin** [comment]
@reinout Yes, I think that proposal would cover my use case. I would add the environment variables to the configuration file, instead of setting them in the shell created by Chef.

**Comment by matteius** [comment]
I think we have this now in the docs:  https://pipenv.pypa.io/en/latest/basics/#pipenv-and-docker-containers

I also have a PR out that needs more work that would allow better usage of the `--system` flag.  

I am closing this specific issue out as stale -- please continue to report new issues and feature requests and we can keep the conversations focused on how things are working today and what we can improve for tomorrow.
