### ISSUE TITLE
Pipfile for 'base'/'root' python env

### ISSUE THREAD

**Issue by mb-georgetown** [pypa/pipenv#2204]
Hi,

I am trying to sort out how to get Pipenv to fit into my workflow.  I am coming from a conda managed environment, so you'd have a "base" virtualenv that was the default python environment, but it is distinct from the system python.  I previously installed various python tools into that base, when I wanted them available throughout my system.  I'd then create specific virtual environments on a per project basis.

I can easily fit pipenv into the per project part of my workflow, but I'm still trying to figure out how to create the same "base" environment.  I am currently using a Pipfile in my home directory and that seems to be a reasonable way to get the benefits of pipenv and have this general python environment.

The one issue I've seen is that if I happen to be in a directory with a Pipfile, pipenv defaults to updating the Pipfile for the current directory vs. the one for the "base" environment.   

Is there a better to get the workflow I'm looking for?  Any thoughts or suggestions would be appreciated.

Thanks!

**Comment by uranusjr** [comment]
You probably wouldn’t like the answer, and someone else can probably solve this, but I would strongly suggest you to stick with Conda instead. Conda environments are their own kind of beasts, and are not at all similar to Python’s “traditional” virtual envrionments. Pipenv, at least at its current state and without any Conda specialists supporting it, simply cannot handle something like this.

**Comment by mb-georgetown** [comment]
Fair enough.  Thanks for the note.  Is it expected behavior for pipenv to use the current directory Pipfile, even if it's in the shell of a different pipenv virtual environment?

**Comment by uranusjr** [comment]
It depends on the surrounding environment’s implementation. Currently it detects whether an environment is set (`VIRTUAL_ENV`) and points to a valid virtual environment. This works for virtualenv (the package, not the concept) and venv (the Python 3.4+ builtin module), but not necessarily others. I don’t know enough about eg pyenv and Conda virtualenv to tell either way. You can certainly customise your environment to trick Pipenv into using it (by setting the right environment variables and providing the right commands), but we only actively maintain compatibility with virtualenv.
