### ISSUE TITLE
Run in Pipfile

### ISSUE THREAD

**Issue by danieldaeschle** [pypa/pipenv#2217]
It would be nice to declare run in Pipfile like:

```
...
run= main.py
...
```
and run it like: `pipenv run`
instead of `pipenv run main.py`

**Comment by frostming** [comment]
Your statements are not true. Given the Pipfile like following:
```toml
...
[scripts]
run = main.py
```
The correct way to run this is `pipenv run run`(in case you really want your command named `run`). This has the same effect as running command `main.py` in your virtualenv.

**Comment by danieldaeschle** [comment]
Oh, very nice. I didn't find that in documentation. Is it there?
