### ISSUE TITLE
Configuration file to set internal pypi

### ISSUE THREAD

**Issue by gsemet** [pypa/pipenv#2223]
Hi

As a company policy, and also because it is a good security and traceability practices, for both security and fastness (we have a poor proxy), to always use our internal pypi network.

Is it possible to populate a default file on each PC in our network or through an environment variable, to change the default pypi server pipenv will use each time pipenv will create a Pipfile.

Of course we also need to disable the ssl security. Basically, everything that it in the [[source]] section could come from an /etc/pipenvrc file.
I can contribute to that, in my mind I would mimick how pip.conf is handled by pip (the different system-wide paths under windows, Linux or Mac, user path), if your agree on this feature.

Today i need to tell user to edit the Pipfile manually after bootstrapping a project with pipenv. But they will do mistakes,and they also expect it to work seamlessly on their workstation as it already does for pip or npm. 

Thanks for your feedback on this feature

**Comment by uranusjr** [comment]
Would #2075 cover your use case?

**Comment by gsemet** [comment]
Yes this is the same need !
I however feel the discussion goes in a direction far too complex. I close this ticket and contribute in the other one
