### ISSUE TITLE
Pipenv Shell clears all colors for existing shell [Windows]

### ISSUE THREAD

**Issue by gtalarico** [pypa/pipenv#2226]
##### Actual result
After shell activation, existing terminal colors are lost.
New colors will show as expected; only colors in the parent shell are lost.

##### Expected result
After shell activation, parent shell colors are maintained

##### Steps to replicate

* On windows, using cmder or cmd.exe:
* Print any command that shows color (eg. on cmder, `ls`)
* use `pipenv shell`
* (See gifs below)

#### Comments
Looks like the actual shell activation happens [here](https://github.com/pypa/pipenv/blob/0eb95ecbfc79e9e0ead59387a81ffacaf805ae98/pipenv/patched/pew/_utils.py#L47)

I tried adding `stdout=sys.stdout` to the `f` call as suggested [here](https://stackoverflow.com/questions/42589584/ansi-color-lost-when-using-python-subprocess?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa#comment72401619_42589699)) but it did not fix. (I think that's already default `check_call` args anyway...)

If anyone has any guess of what might be the cause I would be happy to look further into it and prepare a PR.

###### Cmder

![pipenv-colors](https://user-images.githubusercontent.com/9513968/40282063-44515470-5c37-11e8-8acd-88861770fa36.gif)

###### Cmd.exe

![pipenv-cmd](https://user-images.githubusercontent.com/9513968/40282228-31c3ea04-5c3a-11e8-88ab-aeb1e9fe48dd.gif)

**Comment by uranusjr** [comment]
Unfortunately that’s how Windows shelling works, at least afaict, and there’s nothing we can do here… Anyone please feel free to reopen if you know some technical details I don’t and can provide insights on how this can be done.
