### ISSUE TITLE
setting up pipenv environment in django application on apache server

### ISSUE THREAD

**Issue by anuj9196** [pypa/pipenv#2240]
I understand this is not right place to ask for help but I really need help with this

I need help with setting up `Django 2.0` application on `apache` server. 

Here is the link to Stackoverflow with details of what I have done till in to setup it. But, It seems the virtual environment is not activating or being called.

https://stackoverflow.com/q/50464727/3719167

**Comment by uranusjr** [comment]
Closing since you now get the exposure you’re looking for. Further discussion can happen on StackOverflow.
