### ISSUE TITLE
Pipenv install fails if path to .venv contains a space

### ISSUE THREAD

**Issue by ibrewster** [pypa/pipenv#2243]
I saw what appeared to be a similar issue, but only about the path to the shell containing a space.

Running pipenv install fails if the path to the venv directory contains a space. For example:

```
Error:  An error occurred while installing flask!
/bin/sh: /Volumes/Promise6TB/Development/contract manager/.venv/bin/pip: "/Volumes/Promise6TB/Development/contract: bad interpreter: No such file or directory
```

Note how the "path" to the interpreter stops at the space - obviously the path isn't being escaped properly.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`

Pipenv location: `'/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv'`

Python location: `'/Library/Frameworks/Python.framework/Versions/3.6/bin/python3'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m`
  - `3.6`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6`
  - `3.6`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6`
  - `3.6`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `2.7.14`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.14`: `/usr/local/bin/python2`
  - `3.6.3`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3`
  - `3.6.3`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3`
  - `3.6.3`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3`
  - `3.6.3`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT '
                     '2018; root:xnu-4570.51.2~1/RELEASE_X86_64',
 'python_full_version': '3.6.3',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `rvm_bin_path`
  - `TERM_PROGRAM`
  - `GEM_HOME`
  - `SHELL`
  - `TERM`
  - `IRBRC`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `OLDPWD`
  - `MY_RUBY_HOME`
  - `TERM_SESSION_ID`
  - `USER`
  - `__array_start`
  - `rvm_path`
  - `SSH_AUTH_SOCK`
  - `escape_flag`
  - `rvm_prefix`
  - `PATH`
  - `ANDROIDAPI`
  - `PWD`
  - `LANG`
  - `ANDROIDNDK`
  - `_second`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `rvm_version`
  - `SHLVL`
  - `HOME`
  - `ANDROIDSDK`
  - `_first`
  - `LOGNAME`
  - `GEM_PATH`
  - `ANDROIDNDKVER`
  - `DISPLAY`
  - `RUBY_VERSION`
  - `SECURITYSESSIONID`
  - `_`
  - `__CF_USER_TEXT_ENCODING`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Users/israel/.buildozer/android/platform/android-ndk-r9c:/Users/israel/.buildozer/android/platform/android-sdk-21/platform-tools:/Users/israel/.buildozer/android/platform/android-sdk-21/tools:/Users/israel/.rvm/gems/ruby-1.9.3-p194/bin:/Users/israel/.rvm/gems/ruby-1.9.3-p194@global/bin:/Users/israel/.rvm/rubies/ruby-1.9.3-p194/bin:/Users/israel/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/israel/Development/contract manager`

---------------------------

Contents of `Pipfile` ('/Volumes/Promise6TB/Development/contract manager/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "*"

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/Volumes/Promise6TB/Development/contract manager/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "8ec50e78e90ad609e540d41d1ed90f3fb880ffbdf6049b0a6b2f1a00158a3288"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "click": {
            "hashes": [
                "sha256:29f99fc6125fbc931b758dc053b3114e55c77a6e4c6c3a2674a2dc986016381d",
                "sha256:f15516df478d5a56180fbf80e68f206010e6d160fc39fa508b65e035fd75130b"
            ],
            "version": "==6.7"
        },
        "flask": {
            "hashes": [
                "sha256:2271c0070dbcb5275fad4a82e29f23ab92682dc45f9dfbc22c02ba9b9322ce48",
                "sha256:a080b744b7e345ccfcbc77954861cb05b3c63786e93f2b3875e0913d44b43f05"
            ],
            "index": "pypi",
            "version": "==1.0.2"
        },
        "itsdangerous": {
            "hashes": [
                "sha256:cbb3fcf8d3e33df861709ecaf89d9e6629cff0a217bc2848f1b41cd30d360519"
            ],
            "version": "==0.24"
        },
        "jinja2": {
            "hashes": [
                "sha256:74c935a1b8bb9a3947c50a54766a969d4846290e1e788ea44c1392163723c3bd",
                "sha256:f84be1bb0040caca4cea721fcbbbbd61f9be9464ca236387158b0feea01914a4"
            ],
            "version": "==2.10"
        },
        "markupsafe": {
            "hashes": [
                "sha256:a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665"
            ],
            "version": "==1.0"
        },
        "werkzeug": {
            "hashes": [
                "sha256:c3fd7a7d41976d9f44db327260e263132466836cef6f91512889ed60ad26557c",
                "sha256:d5da73735293558eb1651ee2fddc4d0dedcfa06538b8813a2e20011583c9e49b"
            ],
            "version": "==0.14.1"
        }
    },
    "develop": {}
}

```
</details>
------------

##### Expected result

Spaces should be properly escaped, and install should work

##### Actual result

The error above

##### Steps to replicate

Just create a .venv folder in a directory containing a space, and try running.

**Comment by kennethreitz** [comment]
i cannot replicate this on my machine.

**Comment by kennethreitz** [comment]
will be re-opened by someone else if it continues to be an issue ;)
