### ISSUE TITLE
Installs package successfully, but fails to resolve when importing

### ISSUE THREAD

**Issue by codeblooded** [pypa/pipenv#2245]
I'm attempting to install the latest version of **click** from PyPI using `pipenv install click`. I have activated my virtual environment using `pipenv shell` before installation. It successfully installs and adds the dependency to my Pipfile, like-so:

```toml
[packages]
click = "*"
```

And, I have navigated to the virtual environment's site-packages directory and confirmed click is there. However, when I run a script which calls `import click` in my virtual environment, I get the following error:

```
Traceback (most recent call last):
  File "bin/index.py", line 3, in <module>
    import click
ImportError: No module named 'click'
```

Please run `$ python -m pipenv.help`, and paste the results here.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`

Pipenv location: `'/usr/local/lib/python3.4/dist-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.4`: `/home/USER_MASKED/.local/share/virtualenvs/PROJ-kf829eji/bin/python3.4m`
  - `3.4`: `/home/USER_MASKED/.local/share/virtualenvs/PROJ-kf829eji/bin/python3.4`
  - `3.4`: `/usr/bin/python3.4`

  - `3.4.3`: `/home/USER_MASKED/.local/share/virtualenvs/PROJ-kf829eji/bin/python`
  - `2.7.6`: `/usr/bin/python`
  - `2.7.6`: `/usr/bin/python2`
  - `3.4.3`: `/home/USER_MASKED/.local/share/virtualenvs/PROJ-kf829eji/bin/python3`
  - `3.4.3`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.4.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '3.13.0-149-generic',
 'platform_system': 'Linux',
 'platform_version': '#199-Ubuntu SMP Thu May 17 10:12:50 UTC 2018',
 'python_full_version': '3.4.3',
 'python_version': '3.4',
 'sys_platform': 'linux'}
```

System environment variables:

  - `GNOME_KEYRING_CONTROL`
  - `https_proxy`
  - `JOB`
  - `SESSION`
  - `PATH`
  - `SHELL`
  - `XDG_GREETER_DATA_DIR`
  - `LESSOPEN`
  - `XDG_SESSION_PATH`
  - `LS_COLORS`
  - `LOGNAME`
  - `DESKTOP_SESSION`
  - `GPG_AGENT_INFO`
  - `GNOME_DESKTOP_SESSION_ID`
  - `QT4_IM_MODULE`
  - `PYTHONDONTWRITEBYTECODE`
  - `WINDOWID`
  - `USER`
  - `SESSIONTYPE`
  - `COLORTERM`
  - `EDITOR`
  - `SESSION_MANAGER`
  - `IM_CONFIG_PHASE`
  - `HOME`
  - `QT_IM_MODULE`
  - `LESSCLOSE`
  - `PIPENV_ACTIVE`
  - `DISPLAY`
  - `VTE_VERSION`
  - `XMODIFIERS`
  - `MANDATORY_PATH`
  - `SELINUX_INIT`
  - `ftp_proxy`
  - `XDG_RUNTIME_DIR`
  - `COMPIZ_CONFIG_PROFILE`
  - `no_proxy`
  - `XDG_DATA_DIRS`
  - `VIRTUAL_ENV`
  - `XDG_SESSION_ID`
  - `GDMSESSION`
  - `DEFAULTS_PATH`
  - `QT_QPA_PLATFORMTHEME`
  - `XDG_CONFIG_DIRS`
  - `COMPIZ_BIN_PATH`
  - `PWD`
  - `PS1`
  - `SSH_AUTH_SOCK`
  - `_`
  - `XAUTHORITY`
  - `GTK_MODULES`
  - `LANG`
  - `SHLVL`
  - `http_proxy`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `CLUTTER_IM_MODULE`
  - `TERM`
  - `XDG_SEAT_PATH`
  - `GNOME_KEYRING_PID`
  - `XDG_VTNR`
  - `TEXTDOMAIN`
  - `XDG_CURRENT_DESKTOP`
  - `PIP_PYTHON_PATH`
  - `GDM_LANG`
  - `GTK_IM_MODULE`
  - `TEXTDOMAINDIR`
  - `LANGUAGE`
  - `XDG_SEAT`
  - `XDG_MENU_PREFIX`
  - `INSTANCE`
  - `UPSTART_SESSION`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/USER_MASKED/.local/share/virtualenvs/PROJ-kf829eji/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/USER_MASKED/PROJ`
  - `VIRTUAL_ENV`: `/home/USER_MASKED/.local/share/virtualenvs/PROJ-kf829eji`

---------------------------

Contents of `Pipfile` ('/home/USER_MASKED/PROJ/Pipfile'):

```toml
[[source]]
verify_ssl = true
url = "https://pypi.org/simple"
name = "pypi"

[dev-packages]
pytest = ">=3.5,<3.6"

[packages]
xlsxwriter = ">1.0,<2.0"
click = "*"

[requires]
python_version = "3.4"
```

Contents of `Pipfile.lock` ('/home/USER_MASKED/proj/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "704b17c89342e2fcd8cb67a412c5d3613c4893ed7a7b39bc08fc388c8c3f3262"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.4"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "click": {
            "hashes": [
                "sha256:29f99fc6125fbc931b758dc053b3114e55c77a6e4c6c3a2674a2dc986016381d",
                "sha256:f15516df478d5a56180fbf80e68f206010e6d160fc39fa508b65e035fd75130b"
            ],
            "index": "pypi",
            "version": "==6.7"
        },
        "xlsxwriter": {
            "hashes": [
                "sha256:05005a069da3fcadeb20ff9384d92e548096faf9ede9d6a538403fa8e0aae1f0",
                "sha256:bd4661c04a68621cb2ebc07c38b8b2e98e30bf213a16e1cf3675b61e26ca9bf2"
            ],
            "index": "pypi",
            "version": "==1.0.5"
        }
    },
    "develop": {
        "attrs": {
            "hashes": [
                "sha256:4b90b09eeeb9b88c35bc642cbac057e45a5fd85367b985bd2809c62b7b939265",
                "sha256:e0d0eb91441a3b53dab4d9b743eafc1ac44476296a2053b6ca3af0b139faf87b"
            ],
            "version": "==18.1.0"
        },
        "more-itertools": {
            "hashes": [
                "sha256:0dd8f72eeab0d2c3bd489025bb2f6a1b8342f9b198f6fc37b52d15cfa4531fea",
                "sha256:11a625025954c20145b37ff6309cd54e39ca94f72f6bb9576d1195db6fa2442e",
                "sha256:c9ce7eccdcb901a2c75d326ea134e0886abfbea5f93e91cc95de9507c0816c44"
            ],
            "version": "==4.1.0"
        },
        "pluggy": {
            "hashes": [
                "sha256:7f8ae7f5bdf75671a718d2daf0a64b7885f74510bcd98b1a0bb420eb9a9d0cff",
                "sha256:d345c8fe681115900d6da8d048ba67c25df42973bda370783cd58826442dcd7c",
                "sha256:e160a7fcf25762bb60efc7e171d4497ff1d8d2d75a3d0df7a21b76821ecbf5c5"
            ],
            "version": "==0.6.0"
        },
        "py": {
            "hashes": [
                "sha256:29c9fab495d7528e80ba1e343b958684f4ace687327e6f789a94bf3d1915f881",
                "sha256:983f77f3331356039fdd792e9220b7b8ee1aa6bd2b25f567a963ff1de5a64f6a"
            ],
            "version": "==1.5.3"
        },
        "pytest": {
            "hashes": [
                "sha256:54713b26c97538db6ff0703a12b19aeaeb60b5e599de542e7fca0ec83b9038e8",
                "sha256:829230122facf05a5f81a6d4dfe6454a04978ea3746853b2b84567ecf8e5c526"
            ],
            "index": "pypi",
            "version": "==3.5.1"
        },
        "six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        }
    }
}

```
</details>

##### Expected result

The package to be imported successfully.

##### Actual result

I cannot dump the verbose logs, because I'm in a configured corporate environment. However, nothing should be out of the usual.

##### Steps to replicate

1. Create a project with the above Pipfile and Pipfile.lock
2. Create pipenv and install dependencies
3. Create the following script:
```python
#!/usr/bin/env python

import click

@click.command()
def index():
    """
    Start command
    """
    return

if __name__ == '__main__':
    index()
```
4. Run the script.

## Things I've tried...

- Deleting the virtualenv and recreating it (same issue)

**Comment by dhruvinsh** [comment]
Hi, i did try to replicate but, it did work for me,
without any hassle, there were 2 way i was able to run the code. for me the code in test.py file
i did `pipenv install click`
1. `pipenv run pyhton test.py`
2. `pipenv shell` ---> and then in activated environment run it with `python test.py`

**Comment by lemuelmidas** [comment]
Like the OP above recommended, try and it will work out
