### ISSUE TITLE
Better documentation layout.

### ISSUE THREAD

**Issue by halicki** [pypa/pipenv#2252]
**Is your feature request related to a problem? Please describe.**
I was frustrated while starting to work with `pipenv` by the documentation structure. Until I figured out how to navigate `pipenv` docs I felt like child in a fog. I felt lost in the amount of the information. Couldn't find things that I needed.

Here are some things that bothers me while working with `pipenv` docs:
* Sidebar is bloated and mostly has links to other projects, not focusing on the main topic: providing info about how does `pipenv` work.
* Sidebar doesn't have a full Table of Contents - only current page contents is on sidebar Table of Contents
* Installation instructions not in Table of Contents.
* Pages are to big, for example: [advanced](https://docs.pipenv.org/advanced/) that's a lot of stuff in here.
* Full description of CLI usage is on title page.

**Describe the solution you'd like**
Just negate things I mentioned above and I'll be happy :D But just for the record:
* Sidebar is free of distractions.
* Sidebar concisely list's Table Of Contents with current page contents unfold.
* Single source of true for Table Of Contents.
* CLI usage help has its own separate page.

**Additional context**
I would like to bring other project documentation here: [Mitogen](https://mitogen.readthedocs.io/en/latest/). Its sidebar is so helpful - contains full TOC - it's so easy to navigate. This is what we should pursue.

**Comment by kennethreitz** [comment]
If you'd like to contribute, feel free to open a pull request! Most docs changes are accepted!
