### ISSUE TITLE
python -m pipenv.help with a pipe doesn't work on python 2.7

### ISSUE THREAD

**Issue by benjaminjkraft** [pypa/pipenv#2253]
I believe the issue is just that printing unicode doesn't work right in python 2.7 if output is redirected.  I get this error:

```
$ python -m pipenv.help | xsel -b
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/benkraft/.virtualenv/khan27/lib/python2.7/site-packages/pipenv/help.py", line 89, in <module>
    main()
  File "/home/benkraft/.virtualenv/khan27/lib/python2.7/site-packages/pipenv/help.py", line 48, in main
    print(u'Pipenv–specific environment variables:')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 6: ordinal not in range(128)
```

##### Expected result

The full pipenv help output should go to my clipboard

##### Actual result

I only get the following, which ends after environment variables, plus the error posted above (to stderr):

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`

Pipenv location: `'/home/benkraft/.virtualenv/khan27/local/lib/python2.7/site-packages/pipenv'`

Python location: `'/home/benkraft/.virtualenv/khan27/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/home/benkraft/.virtualenv/khan27/bin/python2.7`
  - `2.7`: `/home/benkraft/.virtualenv/khan27/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`
  - `3.6`: `/usr/bin/python3.6`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.14`: `/home/benkraft/.virtualenv/khan27/bin/python`
  - `2.7.14`: `/home/benkraft/src/pyenv/shims/python`
  - `2.7.14`: `/home/benkraft/src/pyenv/shims/python`
  - `2.7.15`: `/usr/bin/python`
  - `2.7.15`: `/usr/bin/python`
  - `2.7.15`: `/usr/bin/python`
  - `2.7.14`: `/home/benkraft/.virtualenv/khan27/bin/python2`
  - `2.7.15`: `/usr/bin/python2`
  - `2.7.15`: `/usr/bin/python2`
  - `2.7.15`: `/usr/bin/python2`
  - `3.6.5`: `/usr/bin/python3`
  - `3.6.5`: `/usr/bin/python3`
  - `3.6.5`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-20-generic',
 'platform_system': 'Linux',
 'platform_version': '#21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018',
 'python_full_version': '2.7.14',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `USERNAME`
  - `QT_QPA_PLATFORMTHEME`
  - `GOPATH`
  - `QT4_IM_MODULE`
  - `GIT_AUTHOR_EMAIL`
  - `PYENV_SHELL`
  - `LESSOPEN`
  - `WINDOWPATH`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_SESSION_TYPE`
  - `QT_IM_MODULE`
  - `LOGNAME`
  - `USER`
  - `PATH`
  - `HOME`
  - `PS1`
  - `DISPLAY`
  - `LANG`
  - `MANAGERPID`
  - `SHELL`
  - `XAUTHORITY`
  - `JOURNAL_STREAM`
  - `SESSION_MANAGER`
  - `XDG_DATA_DIRS`
  - `KHAN`
  - `MANDATORY_PATH`
  - `WINDOW`
  - `TERM`
  - `GNOME_DESKTOP_SESSION_ID`
  - `CLUTTER_IM_MODULE`
  - `TEXTDOMAIN`
  - `GNOME_TERMINAL_SERVICE`
  - `EDITOR`
  - `DESKTOP_AUTOSTART_ID`
  - `XMODIFIERS`
  - `AUTOJUMP_SOURCED`
  - `INVOCATION_ID`
  - `GTK2_MODULES`
  - `XDG_SESSION_DESKTOP`
  - `SSH_AUTH_SOCK`
  - `XDG_RUNTIME_DIR`
  - `GTK_IM_MODULE`
  - `COMP_WORDBREAKS`
  - `VIRTUAL_ENV`
  - `ATHENA_USER`
  - `VTE_VERSION`
  - `GDMSESSION`
  - `IM_CONFIG_PHASE`
  - `TEXTDOMAINDIR`
  - `AUTOJUMP_ERROR_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `QT_ACCESSIBILITY`
  - `XDG_CONFIG_DIRS`
  - `PIP_PYTHON_PATH`
  - `GPG_TTY`
  - `STY`
  - `_`
  - `GTK_MODULES`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `TERMCAP`
  - `DESKTOP_SESSION`
  - `GPG_AGENT_INFO`
  - `LESSCLOSE`
  - `DEFAULTS_PATH`
  - `OLDPWD`
  - `GPGKEY`
  - `PYENV_ROOT`
  - `SHLVL`
  - `PWD`
  - `GIT_COMMITTER_EMAIL`
  - `SSH_AGENT_LAUNCHER`
  - `COLORTERM`
  - `XDG_MENU_PREFIX`
  - `GNOME_SESSION_XDG_SESSION_PATH`
  - `LS_COLORS`
  - `GNOME_TERMINAL_SCREEN`

</details>

**Comment by techalchemy** [comment]
You need to set your locale settings in your shell configuration, add `export LC_ALL=C.UTF-8` or `en_US.UTF-8` or whatever is appropriate and conveys a unicode locale

**Comment by Julian** [comment]
@techalchemy that doesn't fix this -- I've got `LC_ALL` set (to en_US.UTF-8), but this still blows up. It shouldn't be trying to print unicode to stdout/err on Py2.
