### ISSUE TITLE
Echo virtualenv name

### ISSUE THREAD

**Issue by campanelli-resonon** [pypa/pipenv#2259]
**Is your feature request related to a problem? Please describe.**

pipenv "hides" the virtualenv path and name, which leads to confusion and disorientation. Knowing this helps set up PyCharm IDE or simply activating the virutalenv directly from a command line.

**Describe the solution you'd like**

- When creating the virtualenv, echo the path to the virtualenv to the console.
- Have a pipenv command that echoes the full virtualenv path.
- Have `pipenv shell` prefix the virtualenv name in the shell's command prompt the same way as if one were to activate the virtualenv directly. (I am using Windows here.)

**Describe alternatives you've considered**

- In general, I have found it less confusing to work directly in the virtualenv rather than using `pipenv shell`, partly because the virtualenv prefix on the command prompt tells reassures me of my current Python environment.

**Additional context**
N/A

**Comment by uranusjr** [comment]
The third is already done (Windows support in master and will be out in the next release). The second is `pipenv --venv`. I agree with the first; pull request is welcomed :)

**Comment by uranusjr** [comment]
Wait, this is already done.

```
$ pipenv --three
Creating a virtualenv for this project…
Pipfile: /Users/uranusjr/Downloads/foo/Pipfile
Using /Users/uranusjr/Library/PythonUp/bin/python3 (3.6.5) to create virtualenv…
⠋Running virtualenv with interpreter /Users/uranusjr/Library/PythonUp/bin/python3
Using base prefix '/Users/uranusjr/Library/PythonUp/versions/3.6'
New python executable in /Users/uranusjr/Downloads/foo/.venv/bin/python3
Also creating executable in /Users/uranusjr/Downloads/foo/.venv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/uranusjr/Downloads/foo/.venv
Creating a Pipfile for this project…
```

**Comment by campanelli-resonon** [comment]
@uranusjr Very sorry that I missed that venv path in the output and --venv in the options. Thanks so much for your team's work on this welcome Python tool!
