### ISSUE TITLE
Implement help command

### ISSUE THREAD

**Issue by ashemedai** [pypa/pipenv#2264]
**Is your feature request related to a problem? Please describe.**
Given how `pipenv` uses a verb command interface, it feels wrong that to get a help/command summary you need to invoke it with `--help` instead of `pipenv help`.

**Describe the solution you'd like**
Enable `pipenv help` to work. Can be shared with the `--help` output. This maps better in terms of usability.

If okay, I can put a PR together for this.

**Comment by uranusjr** [comment]
I don’t really follow your reasoning on why `--help` is wrong, to be honest. `--help` feels as correct as `help` to me.

**Comment by techalchemy** [comment]
Thanks for the feedback and for explaining the reasoning with it, that definitely helps us understand where you're coming from -- overall I'd say I see an argument for why it could behave this way, but at the same time I don't think we are getting a lot of feedback for this right now.  That's not to say it shouldn't happen, but I don't think now is the time for these kinds of API changes.  Right now we are aiming for stability and correcting some functionality and performance issues. 

I'm going to close this for now, but we may revisit it in the future.  Thanks again for your input

**Comment by ashemedai** [comment]
@techalchemy Thanks for the feedback. It was something I raised based on internal feedback from users at the company I work for.
