### ISSUE TITLE
Raise error in the shell environment of pipenv in wsl

### ISSUE THREAD

**Issue by kingname** [pypa/pipenv#2265]
```
$ python3 -m pipenv.help
<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`

Pipenv location: `'/home/kingname/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.12`: `/usr/bin/python`
  - `2.7.12`: `/usr/bin/python2`
  - `3.6.5`: `/usr/bin/python3`

PEP 508 Information:

{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.4.0-43-Microsoft',
 'platform_system': 'Linux',
 'platform_version': '#1-Microsoft Wed Dec 31 14:42:53 PST 2014',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

------------

##### Expected result

show `command not find` instead of raise python error.

##### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.
![image](https://user-images.githubusercontent.com/5440523/40537043-74d3de62-6040-11e8-97d1-8e4b61f203ea.png)

##### Steps to replicate

do it in Ububtu subsystem of Windows 10

**Comment by uranusjr** [comment]
My guess is asdf stands for something particular in your environment. Pipenv does emit *command not found* error if it can’t find a command, but asdf seems to be actually found.

**Comment by techalchemy** [comment]
The command was found in this case. It is a pyenv dependency. https://github.com/tuvistavie/asdf-python

**Comment by techalchemy** [comment]
Can you provide the error message of that happening? The above error is an import error related to a missing system dependency required for the package `asdf`

**Comment by kingname** [comment]
![image](https://user-images.githubusercontent.com/5440523/40593082-5bbde35e-6258-11e8-9ab3-0f51debad768.png)

![image](https://user-images.githubusercontent.com/5440523/40593090-6a578ed8-6258-11e8-830f-aca921e21130.png)

![image](https://user-images.githubusercontent.com/5440523/40593109-83e764b8-6258-11e8-82e0-a18606af5278.png)

**Comment by uranusjr** [comment]
Something is going quite wrong with your Python environment :| Pipenv is indeed related to the exceptions, but it’s caused by an underlying misconfiguration in your system somewhere.

This problem looks similar, but for apt-get instead of Pipenv (both are built with Python, however!). You might want to try the accepted solution and see if it solves your problem.
https://askubuntu.com/questions/720416/no-module-named-gdbm

**Comment by kingname** [comment]
problem solved, just to ` sudo apt-get install python3.6-gdbm`

**Comment by uranusjr** [comment]
I changed the title to make this more searchable, in case others need this in the future.
