### ISSUE TITLE
Install and uninstall at the same time

### ISSUE THREAD

**Issue by kootenpv** [pypa/pipenv#2270]
**Is your feature request related to a problem? Please describe.**

The problem is that it is always slow to do an install/uninstall with the graph resolving.

**Describe the solution you'd like**

If I want to uninstall and install something at the same time that would help.
Possible solution: also allow `-i` and `-u` syntax for adding package to install and uninstall.

    pipenv install something -u somethingelse

**Describe alternatives you've considered**
Help speeding up the graph resolving.

**Comment by uranusjr** [comment]
I’d recommend doing this manually.

1. Write TOML by hand
2. `pipenv lock`
3. `pipenv sync` (add `--dev` if needed)

It almost always works, unless you have a local package (I actually think this is a bug, but that is another issue).

**Comment by kootenpv** [comment]
@uranusjr That sounds like the way to do it

**Comment by techalchemy** [comment]
@kootenpv you can also `pipenv install --skip-lock` and then `pipenv uninstall` will re-lock I believe
