### ISSUE TITLE
sys_platform does not seem to work on windows

### ISSUE THREAD

**Issue by arrrggghhh** [pypa/pipenv#2271]
Be sure to check the existing issues (both open and closed!).

Describe the issue briefly here.
`sys_platform` marker in Pipfile seems not to be working as expected.
Please run `$ python -m pipenv.help`, and paste the results here.
<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`

Pipenv location: `'C:\\Users\\z\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pipenv'`

Python location: `'C:\\Users\\z\\AppData\\Local\\Programs\\Python\\Python36\\python.exe'`

Other Python installations in `PATH`:

  - `3.5`: `C:\Users\z\AppData\Local\Programs\Python\Python35-32\python.exe`
  - `3.6`: `C:\Users\z\AppData\Local\Programs\Python\Python36\python.exe`

  - `3.6.5`: `C:\Users\z\AppData\Local\Programs\Python\Python36\python.exe`
  - `3.5.4`: `C:\Users\z\AppData\Local\Programs\Python\Python35-32\python.exe`
  - `3.6.5`: `C:\Windows\py.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17134',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `ANSICON`
  - `ANSICON_DEF`
  - `APPDATA`
  - `ASL.LOG`
  - `CHOCOLATEYINSTALL`
  - `CHOCOLATEYLASTPATHUPDATE`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `CONEMUANSI`
  - `CONEMUANSILOG`
  - `CONEMUARGS`
  - `CONEMUARGS2`
  - `CONEMUBACKHWND`
  - `CONEMUBASEDIR`
  - `CONEMUBUILD`
  - `CONEMUCONFIG`
  - `CONEMUDIR`
  - `CONEMUDRAWHWND`
  - `CONEMUDRIVE`
  - `CONEMUHOOKS`
  - `CONEMUHWND`
  - `CONEMUPALETTE`
  - `CONEMUPID`
  - `CONEMUSERVERPID`
  - `CONEMUWORKDIR`
  - `CONEMUWORKDRIVE`
  - `DESKTOP`
  - `DJANGO_SETTINGS_MODULE`
  - `DRIVERDATA`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `JD2_HOME`
  - `LESS`
  - `LESSCHARSET`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PORTABLES`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `SESSIONNAME`
  - `SURVEYBOT`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VBOX_MSI_INSTALL_PATH`
  - `WINDIR`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `C:\Users\z\email\configs\conemu_portable\ConEmu\Scripts;C:\Users\z\email\configs\conemu_portable;C:\Users\z\email\configs\conemu_portable\ConEmu;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Git\cmd;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\PuTTY_o\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;c:\users\z\appdata\local\programs\python\python36\Scripts;C:\Users\z\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\z\AppData\Local\Programs\Python\Python36\;C:\Users\z\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\z\AppData\Local\Programs\Python\Python36-32\;C:\Users\z\AppData\Roaming\WinRAR\Rar.exe;C:\Users\z\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\z\AppData\Local\Programs\Python\Python35-32\;C:\Users\z\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\z\AppData\Local\portables;C:\Users\z\AppData\Local\portables\ctags58;C:\Users\z\AppData\Local\portables\curl\bin;C:\Users\z\AppData\Local\portables\rclone;C:\Program Files\Git\usr\bin\;C:\Program Files\Bandizip\;C:\Users\z\AppData\Roaming\npm;C:\Users\z\AppData\Roaming\sqlite3;C:\Program Files\Git\usr\bin\;C:\Users\z\AppData\Roaming\sqlite3`

---------------------------

Contents of `Pipfile` ('C:\\Users\\z\\Desktop\\pipenvtest\\Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
uWSGI = {version = "==2.0.15", sys_platform = "== 'linux'"}

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('C:\\Users\\z\\Desktop\\pipenvtest\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "415dfdcb118dd9bdfef17671cb7dcd78dbd69b6ae7d4f39e8b44e71d60ca72e7"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>
If you're on MacOS, just run the following:

    $ python -m pipenv.help | pbcopy

------------

##### Expected result

uWSGI not being installed since it had run on windows.

##### Actual result

```
PS C:\Users\z\Desktop\pipenvtest> pipenv install --verbose
Pipfile.lock (ca72e7) out of date, updating to (3dd806)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
repository.get_dependencies(ireq):
  File "c:\users\z\appdata\local\programs\python\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 202, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "c:\users\z\appdata\local\programs\python\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 256, in get_legacy_dependencies
    result = reqset._prepare_file(self.finder, ireq, ignore_requires_python=True)
  File "c:\users\z\appdata\local\programs\python\python36\lib\site-packages\pipenv\patched\notpip\req\req_set.py", line 644, in _prepare_file
    abstract_dist.prep_for_dist()
  File "c:\users\z\appdata\local\programs\python\python36\lib\site-packages\pipenv\patched\notpip\req\req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "c:\users\z\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\pip9\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\users\z\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\pip9\utils\__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip9.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\z\AppData\Local\Temp\tmp91q1edfxbuild\uWSGI\
```
##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).
powersehll on Windows 10
1. `pipenv install`
2. edit `Pipfile` to add `uWSGI = {version = "==2.0.15", sys_platform = "== 'linux'"}`
3. `pipenv install`

**Comment by uranusjr** [comment]
`sys_platform` (and other markers) “work” on installation time, so they can prevent the system from installing incompatible packages. Those incompatible packages, however, still need to be resolved during locking, so we can generate a platform-agnostic lockfile. In other words, we need `egg_info` to work, even on incompatible platforms. (And a well-behaved package *should* have it working.) This is really a problem in the package you try to install (uWSGI). There’s not much Pipenv can do here :(
