### ISSUE TITLE
Please make "install env folder under current project folder" as a  directory instead of using local varibles

### ISSUE THREAD

**Issue by xufangda** [pypa/pipenv#2272]
**Describe the solution you'd like**
I assume most people are migrated from virtualenv to pipenv. I think these people's habit is building up their env under the project folder. 

So I suggest could you please create a new directory for building up env under current folder, such as **"pipenv -local install"** instead of using local variable to control it..

Additionally, people need to learn some packages simultaneously when they write their own code. So restore env folder in a system folder is not quite convenient. 

Thank you for making this fantastic tool. 
Thanks a lot for considering this issue. 
Best regards

**Comment by techalchemy** [comment]
closing in favor of #2086, thanks for the suggestion :)
