### ISSUE TITLE
Handling of unusual version strings (eg. containing 'dev')

### ISSUE THREAD

**Issue by pmosakowski** [pypa/pipenv#2294]
Install process fails when the version string is not in the typical x.y.z format. To be exact the installation succeeds but the Pipfile and Pipfile.lock are not getting updated.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`

Pipenv location: `'/usr/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`
  - `3.6`: `/bin/python3.6`

  - `3.6.5`: `/usr/bin/python`
  - `3.6.5`: `/bin/python`
  - `2.7.15`: `/usr/bin/python2`
  - `2.7.15`: `/bin/python2`
  - `3.6.5`: `/usr/bin/python3`
  - `3.6.5`: `/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.14.32-1-lts',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Sun Apr 1 11:41:45 CEST 2018',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `XDG_CONFIG_HOME`
  - `LANG`
  - `GDM_LANG`
  - `DISPLAY`
  - `EDITOR`
  - `COLORTERM`
  - `MOZ_PLUGIN_PATH`
  - `_CFLAGS`
  - `XDG_VTNR`
  - `SSH_AUTH_SOCK`
  - `SOUND_FILE`
  - `RAX_SSO`
  - `XDG_SESSION_ID`
  - `XDG_GREETER_DATA_DIR`
  - `USER`
  - `DESKTOP_SESSION`
  - `PWD`
  - `HOME`
  - `LESSHISTFILE`
  - `SSH_AGENT_PID`
  - `_LDFLAGS`
  - `LIBVIRT_DEFAULT_URI`
  - `TMUX`
  - `XDG_SESSION_TYPE`
  - `HISTFILE`
  - `XDG_SESSION_DESKTOP`
  - `VIRSH_DEFAULT_CONNECT_URI`
  - `CARGO_HOME`
  - `DESKTOP_STARTUP_ID`
  - `MAIL`
  - `LYNX_CFG`
  - `HOSTALIASES`
  - `TERM`
  - `SHELL`
  - `XDG_SEAT_PATH`
  - `XDG_CURRENT_DESKTOP`
  - `_CC`
  - `WINEARCH`
  - `TMUX_PANE`
  - `XDG_SEAT`
  - `SHLVL`
  - `COLORFGBG`
  - `WINDOWID`
  - `GDMSESSION`
  - `_JAVA_AWT_WM_NONREPARENTING`
  - `XDG_CACHE_HOME`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `XDG_DATA_HOME`
  - `RAX_DEFAULT_DC`
  - `XDG_SESSION_PATH`
  - `PATH`
  - `WINEPREFIX`
  - `_`
  - `OLDPWD`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/pawe9833/bin:/home/shared/programming/vm-scripts:/home/shared/programming/dcops:/home/shared/programming/dellsku:/home/shared/programming/ooblib:/home/shared/programming/smclp-query:/home/pawe9833/.local/bin/:/home/pawe9833/bin:/home/shared/programming/vm-scripts:/home/pawe9833/node_modules/.bin/:/opt/cisco/anyconnect/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/pawe9833/bin:/home/shared/programming/vm-scripts:/home/shared/programming/dcops:/home/shared/programming/dellsku:/home/shared/programming/ooblib:/home/shared/programming/smclp-query:/home/pawe9833/.local/bin/:/home/pawe9833/bin:/home/shared/programming/vm-scripts:/home/pawe9833/node_modules/.bin/:/opt/cisco/anyconnect/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `vim`
  - `LANG`: `en_GB.utf8`
  - `PWD`: `/home/pawe9833/tmp/demo`

---------------------------

Contents of `Pipfile` ('/home/pawe9833/tmp/demo/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = "*"
beeware = "*"

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/home/pawe9833/tmp/demo/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "8739d581819011fea34feca8cc077062d6bdfee39c7b37a8ed48c5e0a8b14837"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "certifi": {
            "hashes": [
                "sha256:13e698f54293db9f89122b0581843a782ad0934a4fe0172d2a980ba77fc61bb7",
                "sha256:9fa520c1bacfb634fa7af20a76bcbd3d5fb390481724c597da32c719a7dca4b0"
            ],
            "version": "==2018.4.16"
        },
        "chardet": {
            "hashes": [
                "sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae",
                "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691"
            ],
            "version": "==3.0.4"
        },
        "idna": {
            "hashes": [
                "sha256:2c6a5de3089009e3da7c5dde64a141dbc8551d5b7f6cf4ed7c2568d0cc520a8f",
                "sha256:8c7309c718f94b3a625cb648ace320157ad16ff131ae0af362c9f21b80ef6ec4"
            ],
            "version": "==2.6"
        },
        "requests": {
            "hashes": [
                "sha256:6a1b267aa90cac58ac3a765d067950e7dbbf75b1da07e895d1f594193a40a38b",
                "sha256:9c443e7324ba5b85070c4a818ade28bfabedf16ea10206da1132edaa6dda237e"
            ],
            "index": "pypi",
            "version": "==2.18.4"
        },
        "urllib3": {
            "hashes": [
                "sha256:06330f386d6e4b195fbfc736b297f58c5a892e4440e54d294d7004e3a9bbea1b",
                "sha256:cc44da8e1145637334317feebd728bd869a35285b93cbb4cca2577da7e62db4f"
            ],
            "version": "==1.22"
        }
    },
    "develop": {}
}

```
</details>

------------

##### Expected result

'pipenv install beeware' installs the requested packages

##### Actual result

The process fails with:

<details><summary>truncated 'pipenv install beeware' output</summary>

```
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches toga>=0.3.0.dev2
Tried: 0.1.0, 0.1.0, 0.1.1, 0.1.1, 0.1.2, 0.1.2, 0.2.0.dev1, 0.2.0.dev1, 0.2.0, 0.2.0, 0.2.1, 0.2.1, 0.2.2, 0.2.2, 0.2.3, 0.2.3, 0.2.4, 0.2.4, 0.2.5, 0.2.5, 0.2.6, 0.2.6, 0.2.7, 0.2.7, 0.2.8, 0.2.8, 0.2.9, 0.2.9, 0.2.10, 0.2.10, 0.2.11, 0.2.11, 0.2.12, 0.2.12, 0.2.13, 0.2.13, 0.2.14, 0.2.14, 0.2.15, 0.2.15, 0.3.0.dev1, 0.3.0.dev1, 0.3.0.dev2, 0.3.0.dev2, 0.3.0.dev3, 0.3.0.dev3, 0.3.0.dev4, 0.3.0.dev4, 0.3.0.dev5, 0.3.0.dev5, 0.3.0.dev6, 0.3.0.dev6, 0.3.0.dev7, 0.3.0.dev7, 0.3.0.dev8, 0.3.0.dev8
There are incompatible versions in the resolved dependencies.
```
</details>
<br/>
As you can see above the exact version (and newer versions too are available). The 'toga' and 'beeware' packages end up being installed though:
<br/><br/>
<details><summary>'pipenv graph' output</summary>

```
beeware==0.1.1
  - briefcase [required: Any, installed: 0.2.4]
    - boto3 [required: >=1.4.4, installed: 1.7.31]
      - botocore [required: >=1.10.31,<1.11.0, installed: 1.10.31]
        - docutils [required: >=0.10, installed: 0.14]
        - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.3]
        - python-dateutil [required: <3.0.0,>=2.1, installed: 2.7.3]
          - six [required: >=1.5, installed: 1.11.0]
      - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.3]
      - s3transfer [required: >=0.1.10,<0.2.0, installed: 0.1.13]
        - botocore [required: <2.0.0,>=1.3.0, installed: 1.10.31]
          - docutils [required: >=0.10, installed: 0.14]
          - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.3]
          - python-dateutil [required: <3.0.0,>=2.1, installed: 2.7.3]
            - six [required: >=1.5, installed: 1.11.0]
    - cookiecutter [required: >=1.0, installed: 1.6.0]
      - binaryornot [required: >=0.2.0, installed: 0.4.4]
        - chardet [required: >=3.0.2, installed: 3.0.4]
      - click [required: >=5.0, installed: 6.7]
      - future [required: >=0.15.2, installed: 0.16.0]
      - jinja2 [required: >=2.7, installed: 2.10]
        - MarkupSafe [required: >=0.23, installed: 1.0]
      - jinja2-time [required: >=0.1.0, installed: 0.2.0]
        - arrow [required: Any, installed: 0.12.1]
          - python-dateutil [required: Any, installed: 2.7.3]
            - six [required: >=1.5, installed: 1.11.0]
        - jinja2 [required: Any, installed: 2.10]
          - MarkupSafe [required: >=0.23, installed: 1.0]
      - poyo [required: >=0.1.0, installed: 0.4.1]
      - requests [required: >=2.18.0, installed: 2.18.4]
        - certifi [required: >=2017.4.17, installed: 2018.4.16]
        - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
        - idna [required: >=2.5,<2.7, installed: 2.6]
        - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
      - whichcraft [required: >=0.4.0, installed: 0.4.1]
    - pip [required: >=10.0, installed: 10.0.1]
    - requests [required: <3.0, installed: 2.18.4]
      - certifi [required: >=2017.4.17, installed: 2018.4.16]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.7, installed: 2.6]
      - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
    - setuptools [required: >=39.0.1, installed: 39.2.0]
    - voc [required: >=0.1.1, installed: 0.1.5]
  - toga [required: >=0.3.0.dev2, installed: 0.3.0.dev8]
    - toga-gtk [required: ==0.3.0.dev8, installed: 0.3.0.dev8]
      - gbulb [required: >=0.5.3, installed: 0.5.3]
      - toga-core [required: ==0.3.0.dev8, installed: 0.3.0.dev8]
        - travertino [required: >=0.1.0, installed: 0.1.2]
```
</details>
<br/>
<details><summary>python REPL output</summary>

```
$ pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave.
$ python
Python 3.6.5 (default, May 11 2018, 04:00:52)
[GCC 8.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import toga
>>> import beeware
>>> dir(beeware)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', 'argparse', 'build_project', 'main', 'new_project', 'run_project', 'subprocess', 'sys']
>>>
```

</details>

##### Steps to replicate

run 'pipenv install beeware' in an empty directory

**Comment by techalchemy** [comment]
>   Hint: try $ pipenv lock --pre if it is a pre-release dependency.
> Could not find a version that matches toga>=0.3.0.dev2

Per the text it tells you in the error message, `pipenv install --pre beeware`
