### ISSUE TITLE
PIPENV_VENV_IN_PROJECT in .env file ignored during initial pipenv shell command

### ISSUE THREAD

**Issue by rgacote** [pypa/pipenv#2313]
Put the following line into the local .env file: 
    `export PIPENV_VENV_IN_PROJECT=1`

Running `pipenv shell` creates a .venv in `~/.local...`, not the `.venv` directory as expected. 
Running `pipenv sync` then creates the local `.venv` file, but the Python interpreter is not there. 

I've done some debugging and found that when running the initial shell command, the `os.environ` commands in `environment.py` are run prior to `core.load_dot_env`. The Python globals containing the environment variables are not reloaded after the `.env` file is loaded.

Is there a reason the .env file is not loaded earlier?

**Comment by uranusjr** [comment]
`.env` is only read for `shell` and `run`. This is a design decision made early on, and likely won’t be changed without substential reasoning and convicing arguments (I know because I failed before). Sorry about this.

**Comment by rgacote** [comment]
Thanks. The confusing thing here for a user is that I _did_ run shell. Granted, it was for creating the virtualenv vs. using it. Still, it was the shell command.

**Comment by uranusjr** [comment]
I wasn’t clear—it is only read *for the shell* (in `shell`) or *for the command you run* (in `run`). Virtual environment creation is not part of the shell, so it does not consult `.env` for configuration.

**Comment by rgacote** [comment]
Understood, and thanks for the response.

**Comment by techalchemy** [comment]
Have a look at tools like `direnv` if you want this to operate like this as well
