### ISSUE TITLE
pipenv basic tutorial should link to valid values of python_version

### ISSUE THREAD

**Issue by Julian** [pypa/pipenv#2318]
Reading [the basic usage tutorial](https://docs.pipenv.org/basics/) through for the first time mentions `python_version`, but doesn't link to what the acceptable values are for that option.

Concretely, since my project uses PyPy, I put `pypy` in there, which appears to "work" in the sense that the virtualenv was created using PyPy when then running `pipenv install`, but I had to guess whether that was actually a thing.

**Comment by techalchemy** [comment]
PyPy isn't actually a valid python version that can be enforced afaik.  But this is a good point, I probably implemented a bunch of this and I actually have no idea what is valid here.

**Comment by Julian** [comment]
To be clear -- is the `python_version` here just referring to the PEP 508 thing called python_version?

**Comment by Julian** [comment]
Yeah OK, from looking at what module parses that value, which is literally called `pep508parser`, I guess that's a "yes" :)

**Comment by uranusjr** [comment]
That is correct!
