### ISSUE TITLE
Where does the shell completion for pipenv in fish come from?

### ISSUE THREAD

**Issue by ksonj** [pypa/pipenv#2327]
I am trying to disable tab completion for pipenv in fish, because filenames and paths are not completed when I do e.g. `pipenv run py.test tests/test_<TAB>`.
I suspect that it might have to do with [this line](https://github.com/pypa/pipenv/blob/442564450f26feb996a850462da8e66ade096525/pipenv/vendor/click_completion.py#L21) specifically the `-f` flag to the `complete`-command.

However I can't figure out how the completion for pipenv is activated in the first place. There is no such configuration in my fish-config. Manually executing `complete --command pipenv --erase` disables completion for pipenv, but putting that in `$XDG_CONFIG/fish/config.fish` does not help. Somehow the completion is overridden again.

Could someone either give me hint as to why the completion of filenames and paths does not work for pipenv (is that actually intended or a bug?) or alternatively point out to me how the completion is activated at all, so I can go and disable it?

**Comment by uranusjr** [comment]
Did you install the [plugin](https://github.com/fisherman/pipenv)? Pipenv does not do anything special to your shell (unless you tell it to, by adding `pipenv --completion` or something similar somewhere), but there are integrations to it, and maybe you accidentally left one active.

**Comment by ksonj** [comment]
Hm, not that I recall... I've never used or installed fisherman. Also, I grepped for `pipenv` in ~/.config/fish` and found no matches. The same goes for ~/.local/share/fish`.

**Comment by uranusjr** [comment]
That is strange… I am sure we don’t do anything fancy to your shell by default. You’ll need to do some deep debugging I guess, there’s nothing I can offer. Sorry :/

**Comment by ksonj** [comment]
Alright, thanks anyway. Could you just very quickly tell me whether completion of filenames after e.g. `pipenv run` is disabled on purpose? Or is this also some config mishap on my side?

**Comment by uranusjr** [comment]
I don’t know TBH (I don’t use Fish and don’t contribute to that part of the code at all), but my guess based on other parts would be this is probably nothing wrong on your side, just not supported in the implementation.
