### ISSUE TITLE
pipenv does not pick up the virtualenv-3 script

### ISSUE THREAD

**Issue by ijanos** [pypa/pipenv#2332]
On Fedora linux the python3 version of the virtualenv script is called `virtualenv-3` and pipenv does not find it.

```
$ pipenv install
Creating a virtualenv for this project…
Using /usr/bin/python3.6m (3.6.5) to create virtualenv…
⠋Warning: it looks like virtualenv is not in your PATH. We cannot continue until this is resolved.
$ pip3 install virtualenv
Requirement already satisfied: virtualenv in /usr/lib/python3.6/site-packages
$ virtualenv
-bash: virtualenv: command not found
$ virtualenv-3 --version
16.0.0

```

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`

Pipenv location: `'/usr/local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Other Python installations in `PATH`:

  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `3.6.5`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.16.13-300.fc28.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Wed May 30 14:31:00 UTC 2018',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LS_COLORS`
  - `SSH_CONNECTION`
  - `LANG`
  - `HISTCONTROL`
  - `HOSTNAME`
  - `XDG_SESSION_ID`
  - `USER`
  - `SELINUX_ROLE_REQUESTED`
  - `PWD`
  - `HOME`
  - `SSH_CLIENT`
  - `TMUX`
  - `SELINUX_LEVEL_REQUESTED`
  - `SSH_TTY`
  - `MAIL`
  - `TERM`
  - `SHELL`
  - `SELINUX_USE_CURRENT_RANGE`
  - `TMUX_PANE`
  - `SHLVL`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `PATH`
  - `HISTSIZE`
  - `LESSOPEN`
  - `_`
  - `OLDPWD`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/fedora/.local/bin:/home/fedora/bin:/home/fedora/.local/bin:/home/fedora/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/srv/my_app`

</details>

**Comment by uranusjr** [comment]
We are switching to using virtualenv via `[sys.executable, '-m', 'virtualenv']` in the next version, thus solving this problem automatically. Thanks for the report, sorry for the trouble, and check back later for the new version!

**Comment by ijanos** [comment]
Awesome, thanks! 

Meanwhile, do you have a workaround other than creating a symlink?

**Comment by uranusjr** [comment]
Unfortunately no, symlink is likely your best bet.
