### ISSUE TITLE
1) pipenv from python 3.6.5 wants python 3.5 to make venv 2) it makes it in wrong dir

### ISSUE THREAD

**Issue by lesatdgl** [pypa/pipenv#2333]
Be sure to check the existing issues (both open and closed!).

Describe the issue briefly here.

Please run `$ python -m pipenv.help`, and paste the results here.

(xenial)les@localhost:~/.local/share/virtualenvs$ python3.6 -m pipenv.help
<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`

Pipenv location: `'/home/les/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.12`: `/usr/bin/python`
  - `2.7.12`: `/usr/bin/python2`
  - `3.5.2`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '3.14.0',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Tue May 29 21:59:41 PDT 2018',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SSH_AGENT_PID`
  - `XMETHOD`
  - `GPG_AGENT_INFO`
  - `VTE_VERSION`
  - `TERM`
  - `SHELL`
  - `XDG_MENU_PREFIX`
  - `QT_LINUX_ACCESSIBILITY_ALWAYS_ON`
  - `GJS_DEBUG_OUTPUT`
  - `WINDOWID`
  - `OLDPWD`
  - `GNOME_KEYRING_CONTROL`
  - `GJS_DEBUG_TOPICS`
  - `GTK_MODULES`
  - `XDG_SESSION_CLASS`
  - `USER`
  - `LS_COLORS`
  - `QT_ACCESSIBILITY`
  - `SSH_AUTH_SOCK`
  - `SESSION_MANAGER`
  - `DEFAULTS_PATH`
  - `XDG_CONFIG_DIRS`
  - `PATH`
  - `MAIL`
  - `DESKTOP_SESSION`
  - `XDG_SESSION_TYPE`
  - `PWD`
  - `LANG`
  - `MANDATORY_PATH`
  - `HOME`
  - `SHLVL`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LOGNAME`
  - `XDG_DATA_DIRS`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `LESSOPEN`
  - `WINDOWPATH`
  - `DISPLAY`
  - `XDG_CURRENT_DESKTOP`
  - `LESSCLOSE`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/les/.local/share/umake/bin:/home/les/bin:/home/les/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/les/.local/share/virtualenvs`

---------------------------

</details>

------------

##### Expected result

new venv in dir ~/dgl-home/dgl-env
##### Actual result

(xenial)les@localhost:~/dgl-home/dgl-env$ sudo python3.6 -m pipenv --python 3.6.5 --site-packages
Creating a virtualenv for this project…
Using /usr/bin/python3.6m (3.6.5) to create virtualenv…
⠋Running virtualenv with interpreter /usr/bin/python3.6m
Using base prefix '/usr'
New python executable in /home/les/.local/share/virtualenvs/les--CUxPr5c/bin/python3.6m
Also creating executable in /home/les/.local/share/virtualenvs/les--CUxPr5c/bin/python
Installing setuptools, pip, wheel...done.

Making site-packages available…
Virtualenv location: /home/les/.local/share/virtualenvs/les--CUxPr5c
Warning: Your Pipfile requires python_version 3.5, but you are using 3.6.5 (/home/les/.local/share/v/l/bin/python).
  $ pipenv check will surely fail.
(xenial)les@localhost:~/dgl-home/dgl-env$ 
.

##### Steps to replicate

simply the command, as above

-- It's necessary to use the python3.6 -m pipenv... because python 3.5 is part of ubuntu xenial and there's (AFAIK) no way to get rid of it

**Comment by techalchemy** [comment]
I don't really see a problem other than that your pipfile itself says it requires python 3.5

>  Warning: Your Pipfile requires python_version 3.5, but you are using 3.6.5 (/home/les/.local/share/v/l/bin/python).

Just edit your pipfile and change it to `3.6`

Also you shouldn't really ever  need to use sudo to make a virtualenv, why do you need root privileges to make a virtualenv in your own home directory?  This is just going to lead to a seriously broken installation down the road.

Regarding the python/python3.6 situation: `ln -s $(which python3,6) "${HOME}/.local/bin/python" && ln -s $(which pip3.6)  "${HOME}/.local/bin/pip"` and then make sure `~/.local/bin` is on your $PATH and configured to be put at the front of your path in your ~/.bashrc -- `echo "export PATH=$HOME/.local/bin:$PATH" >> ~/.bashrc`

then you will have symlinked `python` and `pip` to your local bin so that when you run them on your personal account they will point at 3.6

**Comment by lesatdgl** [comment]
Thanks, I understand and appreciate the effort
However, 
les:~$ ls /home/les/.local/share/v/l/bin/python
ls: cannot access '/home/les/.local/share/v/l/bin/python': No such file or directory

I did: 
les:~$ find /home -name Pipfile
/home/les/.local/share/Trash/files/save-from-env/sls-projects/wchb/Pipfile
/home/les/Pipfile
/home/les/pelican-env/Pipfile
/home/les/dgl-home/dgl-env/sls-projects/wchb/Pipfile

I cleaned all all this trash

And then - to answer question about needing sudo:
les:~$ cd dgl-home/dgl-env
les:dgl-env$ cd dgl-home/dgl-env
bash: cd: dgl-home/dgl-env: No such file or directory
les:dgl-env$ pipenv --venv
No virtualenv has been created for this project yet!
les:dgl-env$ pipenv --python 3.6.5 --site-packages
Creating a virtualenv for this project…
Using /usr/bin/python3.6m (3.6.5) to create virtualenv…
⠋Running virtualenv with interpreter /usr/bin/python3.6m
Using base prefix '/usr'
Traceback (most recent call last):
  File "/home/les/.local/lib/python3.6/site-packages/virtualenv.py", line 2343, in <module>
    main()
  File "/home/les/.local/lib/python3.6/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/home/les/.local/lib/python3.6/site-packages/virtualenv.py", line 927, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/home/les/.local/lib/python3.6/site-packages/virtualenv.py", line 1112, in install_python
    mkdir(lib_dir)
  File "/home/les/.local/lib/python3.6/site-packages/virtualenv.py", line 324, in mkdir
    os.makedirs(path)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/les/.local/share/virtualenvs/dgl-env-nWAMFiVe'
Error while trying to remove the /home/les/.local/share/virtualenvs/dgl-env-nWAMFiVe env: 
No such file or directory

Making site-packages available…
Virtualenv location: 
Traceback (most recent call last):
  File "/home/les/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/les/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/les/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/les/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/home/les/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/les/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/les/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/les/.local/lib/python3.6/site-packages/pipenv/cli.py", line 270, in cli
    three=three, python=python, warn=True, site_packages=site_packages
  File "/home/les/.local/lib/python3.6/site-packages/pipenv/core.py", line 625, in ensure_project
    path_to_python = which('python') or which('py')
  File "/home/les/.local/lib/python3.6/site-packages/pipenv/core.py", line 128, in which
    p = os.sep.join([location] + ['bin/{0}'.format(command)])
TypeError: sequence item 0: expected str instance, NoneType found
les:dgl-env$ pipenv --venv
No virtualenv has been created for this project yet!
les:dgl-env$ 

I then did:
les:dgl-env$ sudo pipenv --python 3.6.5 --site-packages
[sudo] password for les: 
sudo: pipenv: command not found
les:dgl-env$ sudo python3.6 -m pipenv --python 3.6.5 --site-packages
Creating a virtualenv for this project…
Using /usr/bin/python3.6m (3.6.5) to create virtualenv…
⠋Running virtualenv with interpreter /usr/bin/python3.6m
Using base prefix '/usr'
New python executable in /home/les/.local/share/virtualenvs/dgl-env-nWAMFiVe/bin/python3.6m
Also creating executable in /home/les/.local/share/virtualenvs/dgl-env-nWAMFiVe/bin/python
Installing setuptools, pip, wheel...done.

Making site-packages available…
Virtualenv location: /home/les/.local/share/virtualenvs/dgl-env-nWAMFiVe
les:dgl-env$ 

Thanks for your help - not sure how, but it appears that the Pipfile laying around was the issue
