### ISSUE TITLE
Allow pre-release for specific packages only

### ISSUE THREAD

**Issue by jaroel** [pypa/pipenv#2334]
I'd like to be able to install one specific package with a pre-release, but not the rest.
I can currently set `allow_prereleases = true`, but I'll have to pin every other package to a stable version range.

I'd rather have pipenv to prefer stable releases, but allow me to set any version for a package.

For example, I'd like to use the `black` package with version `18.6b2`.
I do not want the pre-releases for pylint-django, or any other dependency as they do not work at the moment.

This one doesn't work, but I'd like it to :)
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]
black = "18.6b2"
pylint-django = "*"

[requires]
python_version = "3.6"

[pipenv]
allow_prereleases = false
```

This one does work. Note the `pylint` and `astroid` pinning.
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]
pylint = "==1.*"
black = "*"
pylint-django = "*"
mypy = "*"
astroid = "==1.*"

[requires]
python_version = "3.6"

[pipenv]
allow_prereleases = true

```

**Comment by gsemet** [comment]
Similar to #1760.

**Comment by uranusjr** [comment]
Closing this to centralise the discussion.
