### ISSUE TITLE
can not create nested pipenv of different python version

### ISSUE THREAD

**Issue by kaldown** [pypa/pipenv#2339]
for instance assume the next path:

```
/projects/
-- some_porject/
(pipenv --python 3)
-- Pipfile
-- Pipfile.lock
-- py3file.py
-- sub_dir/
--|-- sub_sub_dir/
--|--|--py2file.py
--|--|-- ^^^^^ can not do (pipenv --python 2.7)
```

it thinks I want use python3. But I'm not!

pipenv, version 11.10.4
debian 9
python 3.5

thanks

**Comment by uranusjr** [comment]
Sounds like another instance of #2188. I would be really happy if it can be approved :(

Your current alternative is to create `Pipfile` in `sub_sub_dir` yourself. Once you have `sub_sub_dir/Pipfile` created (even if it is empty!), you can run `pipenv --python 2.7` as expected.
