### ISSUE TITLE
Talking About Pipenv!

### ISSUE THREAD

**Issue by 54oqF** [pypa/pipenv#2341]
**Is your feature request related to a problem? Please describe.**
>_"Okay, good to know. Is there any public place where that discussion and future ones can be viewed?"_
https://github.com/pypa/pipenv/issues/2191#issuecomment-391479745

**Describe the solution you'd like**
Would it be possible to get some extra reporting on decisions that are likely to impact people like this? I'm really not bothered by the versionning system change but it was a bit disappointing neither /releases or `HISTORY.txt` have anything notable about the change. `HISTORY` just had a single line of `- Switch to calver for versioning.` and I had to search the issue tracker to find the perfectly valid reasoning. 

pipenv is becoming increasingly important to _my_ projects so a bit more overt transparency would be appreciated even if _my_ projects aren't part of pipenv :wink: 

**Describe alternatives you've considered**
Slap a bit more information in `HISTORY.txt` when there is something worth talking about. Sure, "worth" is a very subjective concept but there is no reason why `HISTORY.txt` can't be ~rewritten~ updated if people later notice that there was something important to talk about.

Actually, /releases and `HISTORY.txt` are just the first places I would check. Even slapping in a link to a blog post somewhere is fine.

**Comment by techalchemy** [comment]
hey @54oqF I'm going to be updating /releases more regularly going forward, and history.txt has been kept mostly up to date since roughly january.  As for the Calver decision, well, we didn't have great messaging, it was done at a table at pycon while we were discussing the merits of it

**Comment by 54oqF** [comment]
Thanks for the response. I guess my point is more you guys gave a good tl;dr of the merits of this change in that issue and maybe making a few notes on the outcome of stuff like this would be
