### ISSUE TITLE
Requirement name not detected when installing from local git repo, despite specification

### ISSUE THREAD

**Issue by 0az** [pypa/pipenv#2344]
Pipenv fails with `pip9.exceptions.InstallationError: Could not detect requirement name` when installing from a package in a local git repo, despite specifying the name with `#egg=`

Pipenv installed via pip. Also tested on Pipenv master.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`

Pipenv location: `'/usr/local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.6`: `/usr/bin/python2.6`
  - `2.6`: `/usr/bin/python2.6`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.15`: `/usr/local/bin/python2`
  - `2.7.15`: `/usr/local/bin/python2`
  - `3.6.5`: `/usr/local/bin/python3`
  - `3.6.5`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '14.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT '
                     '2017; root:xnu-2782.70.3~1/RELEASE_X86_64',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `XDG_CONFIG_HOME`
  - `LANG`
  - `XPC_FLAGS`
  - `DISPLAY`
  - `TERM_SESSION_ID`
  - `COMMAND_MODE`
  - `EDITOR`
  - `COLORTERM`
  - `__CF_USER_TEXT_ENCODING`
  - `ITERM_SESSION_ID`
  - `NPM_CONFIG_USERCONFIG`
  - `SSH_AUTH_SOCK`
  - `HOMEBREW_CASK_OPTS`
  - `USER`
  - `PWD`
  - `HOME`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `Apple_PubSub_Socket_Render`
  - `ITERM_PROFILE`
  - `TMPDIR`
  - `XPC_SERVICE_NAME`
  - `TERM`
  - `SHELL`
  - `SECURITYSESSIONID`
  - `SHLVL`
  - `COLORFGBG`
  - `NPM_CONFIG_CACHE`
  - `XDG_CACHE_HOME`
  - `LOGNAME`
  - `XDG_RUNTIME_DIR`
  - `NPM_CONFIG_TMP`
  - `XDG_DATA_HOME`
  - `PATH`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/azhou/bin:/usr/local/opt/gettext/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS`
  - `SHELL`: `/usr/local/bin/bash`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/azhou/Documents/workspace/test/test-project`

---------------------------

Contents of `Pipfile` ('/Users/azhou/Documents/workspace/test/test-project/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
six = {path = "git+file:///Users/azhou/Documents/workspace/test/six/.git", editable = true}

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/Users/azhou/Documents/workspace/test/test-project/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "415dfdcb118dd9bdfef17671cb7dcd78dbd69b6ae7d4f39e8b44e71d60ca72e7"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

------------

##### Expected result

Package installs from local git branch successfully.

##### Actual result

`pipenv install` fails with pip9.exceptions.InstallationError.

Tested with six. `--verbose` log at https://gist.github.com/0az/8215fb5a578f47446ff5b1e813a2762b due to length. 

```
Installing -e git+file:///Users/azhou/Documents/workspace/test/six/.git#egg=six…
Obtaining six from git+file:///Users/azhou/Documents/workspace/test/six/.git#egg=six
  Updating /Users/azhou/.local/share/virtualenvs/test-project-kYOvgE9a/src/six clone
Installing collected packages: six
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Running setup.py develop for six
Successfully installed six

Adding -e git+file:///Users/azhou/Documents/workspace/test/six/.git#egg=six to Pipfile's [packages]…
Pipfile.lock (ca72e7) out of date, updating to (1ab3f3)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
penv/utils.py", line 332, in actually_resolve_reps
    dep[len('-e '):]
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pip9/req/req_install.py", line 144, in from_editable
    editable_req, default_vcs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pip9/req/req_install.py", line 1197, in parse_editable
    "Could not detect requirement name, please specify one with #egg="
pip9.exceptions.InstallationError: Could not detect requirement name, please specify one with #egg=
…

```

##### Steps to replicate

1. Clone a python package with a `setup.py` (six) into a local repo (`$sixdir`)
2. Create empty Pipenv with `pipenv install`
3. Install six using `pipenv install -e git+file://$sixdir/.git#egg=six`

**Comment by techalchemy** [comment]
a git repository is not a valid requirement, your requirement needs to point at a directory with a setup.py in it

**Comment by uranusjr** [comment]
Also—the error message has been improved in master (will be released in the next version). I’m hitting another bug right now with `#egg=`, and can’t confirm if the user experience is improved there.

**Comment by 0az** [comment]
@tealalchemy

I tested it with the benjaminp/six repo, which does have a setup.py. I should probably make that clear.

**Comment by uranusjr** [comment]
I believe this is under investigation.
