### ISSUE TITLE
Projects version dependency not honoured 

### ISSUE THREAD

**Issue by jamesstidard** [pypa/pipenv#2347]
I've switched to using `pipenv` in most projects but got some, what I found to be, unexpected behaviour. I have one project that depends on another and both track their dependencies with `pipenv`. 

The first project (A) had a dependency on numpy = "*" in its Pipfile and in its Pipfile.lock it was using 1.14.

The second project (B) has a dependency on numpy = "==1.13.3" as well as the first project A.

When doing a `pip install` in project B I would always get numpy 1.14, even when explicity calling `pipenv install numpy==1.13.3`. 

Is this expected behaviour? My understanding of python dependencies is that the dependant specifies source (e.g. pypi.org) and versions.

Also the `setup.py` in project A just has `numpy` as a dependency listed (no version requirement).

**Comment by uranusjr** [comment]
I don’t quite get your setup with your description. Would it be possible if you set up a simple repository on GitHub so I can clone and test directly?

**Comment by jamesstidard** [comment]
@uranusjr yeah, I can do that this evening. I was just wanting to confirm that this sounds suspect before I put the time in to reproduce.

**Comment by jamesstidard** [comment]
I tried making a minimal reproduction of what I believed was happening and it worked as expected. There must be something else going on. Will reopen when I determine the cause if relevant to pipenv and not a mistake somewhere else.
