### ISSUE TITLE
pipenv install with environment variable fails.

### ISSUE THREAD

**Issue by coulonxyz** [pypa/pipenv#2351]
Hi,

I try to use a environment variable in my Pipfile but it raises an error each time.
This seems to be an known issue "https://github.com/pypa/pipenv/issues/1906" but it supposed to be resolved.

I tried to pass the variable directly when running pipenv install (FURYTOKEN=1234 pipenv install) and I also have it declared (echo ${FURY_TOKEN} works).

My Pipfile:
```
[[source]]
url = "https://repo.fury.io/${FURY_TOKEN}/prettyfuntherapy/"
verify_ssl = true
name = "fury"
```

<summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`

Pipenv location: `'/usr/local/lib/python2.7/dist-packages/pipenv'`

Python location: `'/usr/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.15`: `/usr/bin/python`
  - `2.7.15`: `/usr/bin/python2`
  - `3.6.5`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-22-generic',
 'platform_system': 'Linux',
 'platform_version': '#24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018',
 'python_full_version': '2.7.15rc1',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `LESS`
  - `LC_CTYPE`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_SESSION_TYPE`
  - `AWS_ACCESS_ID`
  - `LC_PAPER`
  - `SNAP_REVISION`
  - `SHELL`
  - `XDG_DATA_DIRS`
  - `MANDATORY_PATH`
  - `QT_ACCESSIBILITY`
  - `TEXTDOMAIN`
  - `XMODIFIERS`
  - `XDG_RUNTIME_DIR`
  - `LC_ADDRESS`
  - `SNAP_NAME`
  - `APPLICATION_NAME`
  - `XDG_SESSION_ID`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DESKTOP_SESSION`
  - `SNAP_COMMON`
  - `SNAP_REEXEC`
  - `SNAP`
  - `XDG_MENU_PREFIX`
  - `LS_COLORS`
  - `LC_NUMERIC`
  - `SNAP_LIBRARY_PATH`
  - `GNOME_DESKTOP_SESSION_ID`
  - `XDG_CURRENT_DESKTOP`
  - `AWS_PROFILE`
  - `USER`
  - `DIRENV_DIFF`
  - `XDG_VTNR`
  - `PS1`
  - `XAUTHORITY`
  - `SESSION_MANAGER`
  - `LC_MEASUREMENT`
  - `CLUTTER_IM_MODULE`
  - `GPG_AGENT_INFO`
  - `LANG`
  - `GDMSESSION`
  - `LC_NAME`
  - `PIP_PYTHON_PATH`
  - `ZDOTDIR`
  - `_`
  - `LC_IDENTIFICATION`
  - `XDG_CONFIG_DIRS`
  - `LC_TIME`
  - `PAGER`
  - `DIRENV_DIR`
  - `QT4_IM_MODULE`
  - `GJS_DEBUG_OUTPUT`
  - `HOME`
  - `DISPLAY`
  - `BAMF_DESKTOP_FILE_HINT`
  - `XDG_SESSION_DESKTOP`
  - `LC_MONETARY`
  - `SNAP_DATA`
  - `SNAP_VERSION`
  - `SNAP_USER_DATA`
  - `USERNAME`
  - `GTK_IM_MODULE`
  - `S3_BUCKET`
  - `SNAP_CONTEXT`
  - `DEFAULTS_PATH`
  - `QT_IM_MODULE`
  - `LOGNAME`
  - `XDG_SEAT`
  - `PATH`
  - `ZSH`
  - `SNAP_ARCH`
  - `SSH_AGENT_PID`
  - `AWS_SECRET_KEY`
  - `TERM`
  - `APPLICATION_ENVIRONMENT`
  - `FURY_TOKEN`
  - `WINDOWPATH`
  - `IM_CONFIG_PHASE`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `SNAP_USER_COMMON`
  - `SNAP_COOKIE`
  - `SSH_AUTH_SOCK`
  - `TEXTDOMAINDIR`
  - `GNOME_SHELL_SESSION_MODE`
  - `LSCOLORS`
  - `OLDPWD`
  - `LC_TELEPHONE`
  - `SHLVL`
  - `PWD`
  - `DIRENV_WATCHES`
  - `JABBA_HOME`
  - `GJS_DEBUG_TOPICS`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/jcoulon/.local/bin:/home/jcoulon/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/jcoulon/PycharmProjects/test-ci`

---------------------------

Contents of `Pipfile` ('/home/jcoulon/PycharmProjects/test-ci/Pipfile'):

```toml
[[source]]
url = "https://repo.fury.io/${FURY_TOKEN}/prettyfuntherapy/"
verify_ssl = true
name = "fury"

[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
ddt = "*"
nose = "*"
awsebcli = "*"

[packages]
numpy = "==1.14.4"
flask = "==1.0.2"
pandas = "*"
py-pft-utils  = { version = "*",  editable = true, index = "fury" }

[requires]
python_version = "3.6"

```

</details>

------------

##### Expected result
I expect my private to install without issue.

##### Actual result
and the error:
```
pipenv install       
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
elf.finder.find_all_candidates(req_name)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/index.py", line 456, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/index.py", line 606, in _get_pages
    page = self._get_page(location)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/index.py", line 723, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/index.py", line 832, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pip9/_vendor/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pip9/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pip9/_vendor/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pip9/_vendor/requests/sessions.py", line 625, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pip9/_vendor/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pip9/download.py", line 181, in handle_401
    username = six.moves.input("User for %s: " % parsed.netloc)
EOFError: EOF when reading a line

/usr/local/lib/python2.7/dist-packages/pipenv/_compat.py:86: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-doFZ54-requirements'>
  warnings.warn(warn_message, ResourceWarning)

```

##### Steps to replicate
use a var env in your Pipfile and run pipenv install

**Comment by uranusjr** [comment]
I’d assume the env var replacement acautlly works, given the error raised is 401, not 404. Does `install` work if you expand the actual value of `FURY_TOKEN` into Pipfile?

**Comment by maximegregoire** [comment]
I run into the same issue with a similar setup. Same `File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pip9/download.py", line 181, in handle_401
    username = six.moves.input("User for %s: " % parsed.netloc)` message.

If I expand the variable in the `Pipfile` it works (but is not desirable as I would not want to commit the credentials)

**Comment by coulonxyz** [comment]
Hi, 
I works fine this morning. It was probably an issue with gem fury. 
It would explain the 401.

sorry for wasting your time.
Julien
