### ISSUE TITLE
Provide better logging for “run”

### ISSUE THREAD

**Issue by uranusjr** [pypa/pipenv#2367]
This is more like a TODO item for myself. Ref #2335.

* Add an environment variable to control verbosity. Probably consolidate this with `--verbose`? But `run` cannot have a `--verbose` flag now (unless we improve parsing).
* Show more information when the flag is set, e.g. what command will be run.

**Comment by sinscary** [comment]
@uranusjr Can I work on this?

**Comment by sinscary** [comment]
Thank you :)

**Comment by uranusjr** [comment]
Alright I’ve merged that, you should be able to use `PIPENV_VERBOSITY` to control this.

**Comment by sinscary** [comment]
@uranusjr I wonder what other information we can show other than which command is about to run if `--verbose/-v` flag is set.

**Comment by frostming** [comment]
This request has been implemented in d47604892a915ddf0b2a130dadaf01376442ae6a, so close it now.
