### ISSUE TITLE
python/pip/pipenv doesn't work after pipenv shell

### ISSUE THREAD

**Issue by sungukryu** [pypa/pipenv#2372]
It seems that pipenv links to python inside pipenv which doesn't exist...
I've been through all the '/.local/ ' permission denied and now this...
installing pipenv is so exhausting and frustrating ...

```
~/workspace/xxx$ which python
/Users/xxx/anaconda3/bin/python
 ~/workspace/xxx$ pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave. ~/workspace/xxx$ . /Users/xxx/.local/share/virtualenvs/xx-XXXX/bin/activate
(xxx-XXXX) ~/workspace/xxx$ which python
/Users/xxx/.local/share/virtualenvs/kospo_coal-XXXX/bin/python
(xxx-XXXX) ~/workspace/xxx$ python
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fffa8bf3380 (most recent call first):
Abort trap: 6
```

**Comment by uranusjr** [comment]
Does it work if you launch the Python directly? i.e.

```
$ ~/.local/share/virtualenvs/kospo_coal-XXXX/bin/python
```

**Comment by sungukryu** [comment]
@uranusjr Thanks for the response.
Yes, it didn't work either.
I kind of solved the problem by `pip uninstall pipenv` and then reinstalling it with brew.
But permission denied happened again and I just did `chmod 777 -R`
I will run pipenv for my personal laptop and thus I believe this doesn't cause any big security issues.

**Comment by uranusjr** [comment]
I can’t really comment on your environment without much information. Does re-installing solves the problem? You may also need to rebuild the virtualenv with

```
$ cd <your project>
$ pipenv --rm
$ pipenv install # Other arguments to initialise the environment.
```

**Comment by techalchemy** [comment]
closing due to lack of info
