### ISSUE TITLE
Pipenv should support platform markers in pipenv install and pipenv install -r

### ISSUE THREAD

**Issue by yoni1** [pypa/pipenv#2375]
`pipenv install "nsenter ; platform_system=='Linux'"`
should do the same as `pip install "..."`, and it should put this in your Pipfile:
`nsenter = { version = "*", markers = "platform_system=='Linux'" }`
The same should be supported when importing a requirements.txt using `pipenv install -r`.

**Comment by uranusjr** [comment]
Hmm, this sounds reasonable. Any opinions @techalchemy? (since I imagine this would require support in requirementslib)

**Comment by techalchemy** [comment]
It does....

**Comment by techalchemy** [comment]
Or it should. If it doesn’t, file a bug version of this

**Comment by yoni1** [comment]
Ok, it didn't work for me earlier today when I tried. I'm going to investigate it a bit more and figure out if I did it wrong or if it just doesn't work, and then I'll open a bug issue.

**Comment by yoni1** [comment]
Opened bug report #2378.
