### ISSUE TITLE
Incorrect python_version identified

### ISSUE THREAD

**Issue by temi4** [pypa/pipenv#2382]
<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`

Pipenv location: `'/usr/local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/local/opt/python@2/bin/python2.7'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`

  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.15`: `/usr/local/bin/python2`
  - `3.6.0`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64',
 'python_full_version': '2.7.15',
 'python_version': '2.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PYTHONDONTWRITEBYTECODE`
  - `LOGNAME`
  - `USER`
  - `PATH`
  - `HOME`
  - `TERM_PROGRAM`
  - `LANG`
  - `TERM`
  - `Apple_PubSub_Socket_Render`
  - `SHLVL`
  - `SECURITYSESSIONID`
  - `XPC_FLAGS`
  - `TMPDIR`
  - `TERM_SESSION_ID`
  - `XPC_SERVICE_NAME`
  - `SSH_AUTH_SOCK`
  - `SHELL`
  - `TERM_PROGRAM_VERSION`
  - `PIP_PYTHON_PATH`
  - `_`
  - `__CF_USER_TEXT_ENCODING`
  - `PWD`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `ru_RU.UTF-8`
  - `PWD`: `/Users/temi4/www/nodejs/jsprav`

---------------------------

</details>

I am install 
```
django-rest-elasticsearch==0.4.1
  - Django [required: >=1.8, installed: 2.0.6]
    - pytz [required: Any, installed: 2018.4]
  - djangorestframework [required: >=3.2.0, installed: 3.8.2]
  - elasticsearch-dsl [required: <7.0.0,>=5.0.0, installed: 6.1.0]
    - elasticsearch [required: <7.0.0,>=6.0.0, installed: 6.2.0]
      - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
    - ipaddress [required: Any, installed: 1.0]
    - python-dateutil [required: Any, installed: 2.7.3]
      - six [required: >=1.5, installed: 1.11.0]
    - six [required: Any, installed: 1.11.0]
  - pytest-runner [required: Any, installed: 4.2]
  - six [required: >=1.11.0, installed: 1.11.0]
```

Use "ipaddress" https://pypi.org/project/ipaddress/ - support python 3.3+

Error:
Installing dependencies from Pipfile.lock (783c0f)…
Ignoring ipaddress: markers 'python_version == "2.7"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
Ignoring enum34: markers 'python_version < "3"' don't match your environment
Looking in indexes: https://pypi.python.org/simple

**Comment by techalchemy** [comment]
Sorry for the issue, I believe this is resolved on the master branch already.  Will be releasing today or tomorrow, let me know if you still experience this after that
