### ISSUE TITLE
Pipenv error unclear when attempting system install as non-root in docker

### ISSUE THREAD

**Issue by AGeekInside** [pypa/pipenv#2387]
I am attempting to install in a Docker container, and I was getting this error:

Step 6/10 : RUN pipenv install --system --deploy
Warning: --system is intended to be used for pre-existing Pipfile installation, not installation of specific packages. Aborting.
The command '/bin/sh -c pipenv install --system --deploy' returned a non-zero code: 1

The error message make think there was an issue with my Pipfile.lock.  I rebuilt the lock file, and it did not help.  

I was able to resolve the issue by changing my user to root and not attempting to do it in the root directoyr.  

Please run `$ python -m k.help`, and paste the results here.

If you're on MacOS, just run the following:

    $ python -m pipenv.help | pbcopy

------------

##### Expected result

I expected an error message to tell me that I did not have permissions or something to that effect.

I'd be happy to work on a pull request to help with this, if it is something that would be useful.

**Comment by techalchemy** [comment]
This error is known and already fixed in master -- will be releasaed shortly. Sorry for the inconvenience.  Ref: #2301 #2181 #2178 #2183 #2091 #2219 #2273
