### ISSUE TITLE
Define git branch for package from environment variable?

### ISSUE THREAD

**Issue by typhoon2099** [pypa/pipenv#2391]
It it possible to define an environment variable to be used to determine the branch that should be checked out for a git repo used as a module? I have been trying to edit my Pipfile to include this but I'm not having any success. Here's an example error message:

```
pip9.exceptions.InstallationError: Command "git checkout -q ${PIPENV_ENVIRONMENT}" failed with error code 1 in /tmp/pip-1kIzTE-export
```

The reason that I'm doing this is that I have two deployments (staging and master) and would like the packages that are pulled in to use the same branch as the repo that is pulling them in (so the master branch would pull in master packages and the staging branch would pull in staging packages).

**Comment by uranusjr** [comment]
merging into #2317

**Comment by notEvil** [comment]
second @typhoon2099 
specifying targets (branch, ref or even version) dynamically simplifies version and dependency management a lot.
It was possible to use environment variables in packages section up until v2018.05.18 but was dropped thereafter as it seems. Even though I understand why, it would have been very nice :)
