### ISSUE TITLE
Pipenv cannot update to newer version of packages

### ISSUE THREAD

**Issue by shivawu** [pypa/pipenv#2393]
This is similar to #2165 even though I'm not sure if they're exactly the same.

Describe the issue briefly here.

`pipenv update <pkg>` does not update the lock file and fails to install the newer version of package.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`

Pipenv location: `'/usr/local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`

  - `2.7.10`: `/usr/bin/python`
  - `3.6.5`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT '
                     '2018; root:xnu-4570.61.1~1/RELEASE_X86_64',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `Apple_PubSub_Socket_Render`
  - `COLORFGBG`
  - `COLORTERM`
  - `COMMAND_MODE`
  - `EDITOR`
  - `HOME`
  - `ITERM_PROFILE`
  - `ITERM_SESSION_ID`
  - `JAVA_HOME`
  - `LANG`
  - `LC_ALL`
  - `LC_CTYPE`
  - `LOGNAME`
  - `OMF_CONFIG`
  - `OMF_PATH`
  - `PATH`
  - `PWD`
  - `SECURITYSESSIONID`
  - `SHELL`
  - `SHLVL`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `TMPDIR`
  - `USER`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `__CF_USER_TEXT_ENCODING`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/wucy/.fastlane/bin:/Users/wucy/.cargo/bin:/usr/local/opt/fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
  - `SHELL`: `/usr/local/bin/fish`
  - `EDITOR`: `vim`
  - `LANG`: `zh_CN.UTF-8`
  - `PWD`: `/Users/wucy`

---------------------------

</details>

------------

##### Expected result

It should update the package

##### Actual result

It did not

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

1. Create an empty folder and cd into it
2. `pipenv --python 3.6` to create a Pipfile
3. `pipenv install black==18.5b0`
4. Edit Pipfile to say `black = "*"`
5. Run `pipenv lock --keep-outdated --pre`, `keep-outdated` preserves the 18.5b0 in the lock file while 18.6b2 is the latest version
6. Run `pipenv update black`, see that `pip` installs `black==18.6b2` into the virtualenv and then `pipenv` install `18.5b0` back from Pipfile.lock since it did not update the lock file

**Comment by techalchemy** [comment]
keep outdated keeps everything in your lockfile at outdated versions.  It is not meant to do selective upgrades.  That is what `--selective-upgrade` is for, and that one works on master

**Comment by shivawu** [comment]
Step 1-5 is the way to repro what I have in my project, and step 6 shows the problem. I have `black = "*"` in my Pipfile and it chooses 18.5b0 weeks ago, and now it has a newer version, I want to upgrade to that version.

**Comment by techalchemy** [comment]
Ah gotcha, thanks for the clarification that makes a lot more sense. Yeah I think I merged the fix for this about 2-3 days ago. Thanks for the report!
