### ISSUE TITLE
Recreating virtualenv when python_version changes instead of warning

### ISSUE THREAD

**Issue by mrh1997** [pypa/pipenv#2395]
When the "python_version" in a Pipfile changes  I get [warnings](https://github.com/pypa/pipenv/blob/d213e7c3d88a50b75d586b9e2541f36e19e9cce1/pipenv/core.py#L638) but i manually have to run ``pipenv install --python X.X``.

My understanding of the idea of pipenv is, that running ``pipenv update`` will sync my virtualenv with my Pipfile (without need for manual interaction). Thus: why is this not the case for changing the python version.

**Comment by uranusjr** [comment]
Ultimately the virtualenv itself (what `python_version` controls) is different from the packages installed in it (what `[packages]` and `[dev-packages]` control). The abstraction leaks in this situation.

Maybe it can be a good idea if we offer the user to tear down and rebuild the virtualenv in this case. This needs some discussion.

**Comment by mrh1997** [comment]
When creating a virtualenv the first time with pipenv (i.e. with ``pipenv update``) the python version to use will be retrieved automaticially from the Pipfile.

Of course you are the expert. But as a pipenv-layman I would expect an operation to give me the same environment as when destroying the virtualenv and recreating it. And I am pretty sure that I am not the only one who is intuitively expecting "update" to do exactly that job...

**Comment by uranusjr** [comment]
I understand the expectation, and that is completely reasonable; I’m just not sure if this expectation is shared in the general community. Re-creating the environment is destructive, and we’d need to be more careful.

**Comment by mrh1997** [comment]
My understanding of pipenv is, that virtualenvs are simply artefacts generated from the Pipfile / Pipfile.lock.
Thus deleting the virtualenv should not be critical as long as I have the Pipfile.lock.

Of course this is not true, if you expect the user to manually modify virtualenvs by running ``pip``.
But shouldn't that be a anti-pattern on pipenv?!?

**Comment by uranusjr** [comment]
It is an anti-pattern (I’d even say it’s anti-pattern to virtual environment usages in general), but people still depend on the behaviour, and sometimes it is even a useful hack. Like it is also an anti-pattern to install packages with managing it with Pipfile (`pipenv run pip install`), but we still allow that for the occasional edge cases, only inteerfere when the user explicit wants us to (`pipenv clean`). It’s probably a good idea to follow the same pattern here, i.e. don’t actively overwrite (only showing errors), but provide a clear path to encourage it (with a command option, for example).

**Comment by kennethreitz** [comment]
i like the current implementation
