### ISSUE TITLE
Add ability to pass arguments to the safety library when running pipenv check

### ISSUE THREAD

**Issue by jarshwah** [pypa/pipenv#2407]
There's a particular CVE that is being raised for our project when running `pipenv check` that we'd like to ignore. The safety library provides the `--ignore` argument for this purpose, but the `check` command doesn't seem to support passing args down to the safety library.

**Describe the solution you'd like**

I'd like some method for passing arguments down to the safety library, though I don't know what UI would be best. It could involve copying args that safety supports onto check. Or an argument on check like `safety-args` that'll group a string under a single argument to be expanded and passed down.

Another solution could be environment variables `SAFETY_IGNORE` for example, but the underlying library does not support that as a variable, so it'd have to be collected and passed down anyway.

**Describe alternatives you've considered**

Running safety directly and bypassing pipenv check, but that's not a nice alternative.

**Comment by erinxocon** [comment]
Hi @jarshwah thanks for using pipenv!

@techalchemy @uranusjr can we just pass args down to the safety lib?

**Comment by uranusjr** [comment]
Was about to comment the same thing in the other issue :) We’d probably add a link to Safety’s documentation so users know what they can pass.

**Comment by techalchemy** [comment]
closing, this made it into the release
