### ISSUE TITLE
pipenv update --outdated ignores certain options

### ISSUE THREAD

**Issue by alexgmin** [pypa/pipenv#2413]
##### Expected result

Doing  `pipenv update --outdated -v --pre --clear` should take into account the verbose, pre and clear options

##### Actual result

Since those parameters are no sent to the internal method do_outdated https://github.com/pypa/pipenv/blob/eb2a7c18c63943de945dc018e6891f4e58aa7518/pipenv/cli.py#L826 which then doesn't send them to do_lock https://github.com/pypa/pipenv/blob/eb2a7c18c63943de945dc018e6891f4e58aa7518/pipenv/core.py#L1722 they are ignored.

##### Steps to replicate
`pipenv update --outdated -v` should have a different output than `pipenv update --outdated` 

Also, outside of the scope of this bug, but maybe `pipenv update --outdated` would make more sense as `pipenv outdated`, since other options of the `update` command like `--sequential` don't make much sense in the context of listing outdated dependencies.

**Comment by techalchemy** [comment]
This all seems right at a glance, this feature was kind of rushed and not revisited. The next project (starting as of the release we just pushed) is to refactor all of this stuff. Thanks for compiling this info!

**Comment by petobens** [comment]
Hi! I have a question which is related to this issue (thus I'm not opening a new one). As far as I see both `pipenv update --outdated` and `pipenv update --dry-run` print a list of outdated packages:
```
> pipenv update --outdated
✔ Success!
Package 'scikit-learn' out-of-date: '==0.20.0' installed, '==0.20.1' available.
Package 'matplotlib' out-of-date: '==3.0.1' installed, '==3.0.2' available.
```
but do not actually update those packages. Now if run `pipenv update` those packages are updated but nothing is printed to the console about the packages that were actually updated: 
```
> pipenv update
Running $ pipenv lock then $ pipenv sync.
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (797843)!
Installing dependencies from Pipfile.lock (797843)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 13/13 — 00:00:04
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!
```
Using `pipenv update --verbose` on the other hand prints a massive log. So my question is: is it possible to run something like `pipenv update --show-outdated` that both prints a message about outdated packages being updated and actually updates them? Thanks in advance for the help!
