### ISSUE TITLE
pipenv update fails on 2018.6.25

### ISSUE THREAD

**Issue by gsemet** [pypa/pipenv#2420]
pipenv 2018.6.25:

```
$ pipenv update
../.local/lib/python3.5/site-packages/pipenv/vendor/requests/__init__.py:83: 
Running $ pipenv lock then $ pipenv sync.
Locking [dev-packages] dependencies...
ite-packages/pipenv/resolver.py", line 37, in main
    from pipenv.utils import create_mirror_source, resolve_deps, replace_pypi_sources
ImportError: cannot import name 'create_mirror_source'
```

Works with: pipenv-2018.5.18

**Comment by erinxocon** [comment]
Hi @gsemet, I'm looking into this issue now.  Can you fill out the issue template by running the command `python -m pipenv.help`?  It would greatly aid in troubleshooting.

**Comment by techalchemy** [comment]
Stop breaking stuff!!! :) 

Is that the right pipenv? Seems like multiple versions

**Comment by erinxocon** [comment]
@gsemet @techalchemy I can't reproduce this issue at this point in time.  If you could post the help diagnostic info that would be great.

**Comment by uranusjr** [comment]
Indeed seems like you have multiple instances installed and one (the new version) tries to import the other (the old version). `create_mirror_source` is added in the latest release.

**Comment by gsemet** [comment]
Hi. I have removed long time ago all reference to pipenv, so the one in ~/.local/bin is the only one.

I cannot reproduce anymore, going back and forth with `pipenv-2018.5.18` works, so now it seems the upgrade is fine. It did failed in some of our CI pipelines, however that annoy me more.

You can close it if this is no more reproducible

**Comment by uranusjr** [comment]
For CI, it might help to `pip uninstall -y pipenv` and install it again. Maybe it is trying to import from the old bytecode, even after the source update… I vaguely remember there is an environment variable to fix that as well.

**Comment by techalchemy** [comment]
`PYTHONDONTWRITEBYTECODE=1`

**Comment by gsemet** [comment]
Reproduced today. I had another pipenv on python2 in .local. Removed by `pip uninstall -y pipenv`. I use `pip3 install pipenv`.

So there can be contamination between module imports somehow, from the python3 pipenv, it somehow include a module from python2 dist-packages, which should not happen
