### ISSUE TITLE
ModuleNotFoundError: No module named 'XXXXX'.  version 2018.6.25

### ISSUE THREAD

**Issue by ikosenn** [pypa/pipenv#2421]
After updating to version: 2018.6.25. I get the error as shown in the image attached. `facematic` is the package name in setup.py. I get the error while running the command `pipenv install -e .`

![screen shot 2018-06-26 at 02 56 04](https://user-images.githubusercontent.com/5145715/41904689-e3225cde-78ed-11e8-8eb4-ea6160f0b0d0.png)
##### Steps to replicate
1. Get a python package
2. Run `pipenv install -e .`

**Comment by ikosenn** [comment]
On a different package. This time I used the command `pipenv install --dev`

![screen shot 2018-06-26 at 03 10 01](https://user-images.githubusercontent.com/5145715/41904923-83def98e-78ee-11e8-9fd3-60e6bd869387.png)

**Comment by ofirarias** [comment]
I've had the same error after upgrading to v2018.6.25.

**Comment by erinxocon** [comment]
In addition to the setup.py can we see the directory structure?

**Comment by seglberg** [comment]
I'm having the exact same issue:

```python
ModuleNotFoundError: No module named 'versioneer'
```

See https://gist.github.com/seglberg/97c47832d2997d47b345c189fbb1aad4

**Comment by erinxocon** [comment]
@seglberg is your repo public and something I could pull down for testing?  I can't seem to replicate the issue.

**Comment by seglberg** [comment]
No, it is private. I can create a sample repository that reproduces the error. Hang tight.

**Comment by uranusjr** [comment]
I would first point out it is against best practice to import your library in its `setup.py`. It creates a chicken-egg problem—Usually the user cannot import dependencies before your package is installed, but without running `setup.py` pip cannot resolve dependencies for the user.

I would recommend adopting on of the top solutions mentioned in the [Python Packaging User Guide](https://packaging.python.org/guides/single-sourcing-package-version/).

**Comment by erinxocon** [comment]
@uranusjr good catch

**Comment by uranusjr** [comment]
Ah, I see, sorry for the misunderstanding. Indeed this seems to be a path issue. Also we should probably be more resilient when reading the package name.

**Comment by seglberg** [comment]
If I modify my setup.py:

```python
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.append(HERE)
import versioneer
```

So definitely a path issue.

**Comment by techalchemy** [comment]
Thanks for the reports all, fix will be out shortly

**Comment by jeremyarr** [comment]
Well done for getting a fix in the master out so quickly.
