### ISSUE TITLE
Package dependencies not being included in Pipfile.lock

### ISSUE THREAD

**Issue by fairbanksg** [pypa/pipenv#2423]
I am seeing problems with package dependencies being included in the Pipfile.lock.
For example, a clean install of pyramid installs all of pyramid's dependencies, but none of them end up in the lock file.

<details><summary>pipenv install pyramid</summary>

```
Creating a Pipfile for this project...
Installing pyramid...
Collecting pyramid
  Using cached https://files.pythonhosted.org/packages/85/c7/0a14873ef7bbb6d30e38678334d5b5faee1ccae2f5a59f093d104a3cc5ee/pyramid-1.9.2-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./.venv/lib/python2.7/site-packages (from pyramid) (39.2.0)
Collecting translationstring>=0.4 (from pyramid)
  Using cached https://files.pythonhosted.org/packages/26/e7/9dcf5bcd32b3ad16db542845ad129c06927821ded434ae88f458e6190626/translationstring-1.3-py2.py3-none-any.whl
Collecting plaster (from pyramid)
  Using cached https://files.pythonhosted.org/packages/61/29/3ac8a5d03b2d9e6b876385066676472ba4acf93677acfc7360b035503d49/plaster-1.0-py2.py3-none-any.whl
Collecting WebOb>=1.7.0 (from pyramid)
  Using cached https://files.pythonhosted.org/packages/d2/df/9b3b374ea2a82b875a90d1fdcf2c4a652d48f0d1e7c2d1034d636551d4d2/WebOb-1.8.2-py2.py3-none-any.whl
Collecting plaster-pastedeploy (from pyramid)
  Using cached https://files.pythonhosted.org/packages/81/25/b537cb592ca52b8b8f0f445dd3b1b6fd7e31a8c26bb295b1327be554bd9c/plaster_pastedeploy-0.5-py2.py3-none-any.whl
Collecting zope.deprecation>=3.5.0 (from pyramid)
  Using cached https://files.pythonhosted.org/packages/ee/33/625098914ec59b3006adf2cdf44a721e9671f4836af9eeb8cbe14e485954/zope.deprecation-4.3.0-py2.py3-none-any.whl
Collecting hupper (from pyramid)
  Using cached https://files.pythonhosted.org/packages/2f/ba/a4f257c5a7ede042c9cab15571c351de204015c6869a83c5249215fb3e5a/hupper-1.3-py2.py3-none-any.whl
Collecting venusian>=1.0a3 (from pyramid)
  Using cached https://files.pythonhosted.org/packages/2f/c2/3d122e19287ed7d73f03821cef87e53673f27d41cae54ee3a46e92b147e2/venusian-1.1.0-py2.py3-none-any.whl
Collecting repoze.lru>=0.4 (from pyramid)
Collecting PasteDeploy>=1.5.0 (from pyramid)
  Using cached https://files.pythonhosted.org/packages/31/28/51201a54aeecbd02eff767d17050b302f6fd98fdfecb4e3f4c9301ba6ef8/PasteDeploy-1.5.2-py2.py3-none-any.whl
Collecting zope.interface>=3.8.0 (from pyramid)
Installing collected packages: translationstring, plaster, WebOb, PasteDeploy, plaster-pastedeploy, zope.deprecation, hupper, venusian, repoze.lru, zope.interface, pyramid
Successfully installed PasteDeploy-1.5.2 WebOb-1.8.2 hupper-1.3 plaster-1.0 plaster-pastedeploy-0.5 pyramid-1.9.2 repoze.lru-0.7 translationstring-1.3 venusian-1.1.0 zope.deprecation-4.3.0 zope.interface-4.5.0

```

</details>

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.6.25'`

Pipenv location: `'/Users/greg/.pyenv/versions/2.7.12/lib/python2.7/site-packages/pipenv'`

Python location: `'/Users/greg/.pyenv/versions/2.7.12/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/Users/greg/.pyenv/versions/2.7.12/bin/python2.7`
  - `2.7`: `/Users/greg/.pyenv/versions/2.7.12/bin/python2.7`
  - `2.7`: `/Users/greg/.pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/Users/greg/.pyenv/shims/python3.6m`
  - `3.6`: `/Users/greg/.pyenv/shims/python3.6`

  - `2.7.12`: `/Users/greg/.pyenv/versions/2.7.12/bin/python`
  - `2.7.12`: `/Users/greg/.pyenv/shims/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.12`: `/Users/greg/.pyenv/versions/2.7.12/bin/python2`
  - `2.7.12`: `/Users/greg/.pyenv/shims/python2`
  - `3.6.5`: `/Users/greg/.pyenv/shims/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64',
 'python_full_version': '2.7.12',
 'python_version': '2.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `GOPATH`
  - `LESS`
  - `GOROOT`
  - `TERM_PROGRAM_VERSION`
  - `PYENV_DIR`
  - `LOGNAME`
  - `USER`
  - `HOME`
  - `PATH`
  - `PYENV_VIRTUALENV_INIT`
  - `TERM_PROGRAM`
  - `LANG`
  - `__CF_USER_TEXT_ENCODING`
  - `TERM`
  - `SHELL`
  - `PYENV_SHELL`
  - `SHLVL`
  - `LESS_TERMCAP_me`
  - `LESS_TERMCAP_md`
  - `LESS_TERMCAP_mb`
  - `PIPENV_VENV_IN_PROJECT`
  - `DISPLAY`
  - `RBENV_SHELL`
  - `PYENV_VERSION`
  - `EDITOR`
  - `GREP_COLOR`
  - `TERM_SESSION_ID`
  - `XPC_SERVICE_NAME`
  - `SSH_AUTH_SOCK`
  - `VISUAL`
  - `Apple_PubSub_Socket_Render`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `LESS_TERMCAP_so`
  - `TMPDIR`
  - `BROWSER`
  - `LESS_TERMCAP_ue`
  - `LSCOLORS`
  - `PYENV_HOOK_PATH`
  - `PYENV_ROOT`
  - `LESS_TERMCAP_se`
  - `PWD`
  - `LESS_TERMCAP_us`
  - `GREP_OPTIONS`
  - `XPC_FLAGS`
  - `LS_COLORS`
  - `PAGER`
  - `NODENV_SHELL`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/greg/.pyenv/versions/2.7.12/bin:/usr/local/Cellar/pyenv/1.2.4/libexec:/Users/greg/google-cloud-sdk/bin:/Users/greg/.nodenv/shims:/Users/greg/.rbenv/shims:/usr/local/Cellar/pyenv-virtualenv/1.1.3/shims:/Users/greg/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/greg/dev/go/bin:/usr/local/opt/go/libexec/bin:/Users/greg/.cargo/bin:/Users/greg/.local/bin`
  - `SHELL`: `/usr/local/bin/zsh`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/greg/dev/pipenv-pyramid-bug`

---------------------------

Contents of `Pipfile` ('/Users/greg/dev/pipenv-pyramid-bug/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
pyramid = "*"

[requires]
python_version = "2.7"

```

Contents of `Pipfile.lock` ('/Users/greg/dev/pipenv-pyramid-bug/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "7948528dcb191b1442624a7442babfa38767375e9d1d3d7de5d88adc5aa035a9"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "2.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "pyramid": {
            "hashes": [
                "sha256:600f12e0d11211a55c2da970120af33214f77607ed45caba6af6c891afeaa771",
                "sha256:cf89a48cb899291639686bf3d4a883b39e496151fa4871fb83cc1a3200d5b925"
            ],
            "index": "pypi",
            "version": "==1.9.2"
        }
    },
    "develop": {}
}

```
</details>

------------

##### Expected result

Pyramid dependencies to be in the lock file.

##### Actual result

Only Pyramid itself is included in the lock file, none of its dependencies.

##### Steps to replicate

- `pipenv install pyramid`

**Comment by fairbanksg** [comment]
I have the latest version of virtualenv (16.0.0).

Here is everything I have installed:

```
Package          Version  
---------------- ---------
certifi          2018.4.16
pip              10.0.1   
pipenv           2018.6.25
setuptools       39.2.0   
virtualenv       16.0.0   
virtualenv-clone 0.3.0    
wheel            0.31.1
```

**Comment by fairbanksg** [comment]
I tried this again with python 3.6.5, and I got the dependencies in the lock file as expected. So I guess this only applies with python 2.7.

**Comment by erinxocon** [comment]
@fairbanksg I can confirm that this worked for me in a venv of 3.6.5, I'm trying it with 2.7.15 right now to see if I can replicate it.

**Comment by fairbanksg** [comment]
I decided to delete both my pip and pipenv caches, and now my lock file is correct in python 2.7.

**Comment by erinxocon** [comment]
Perhaps this is a 2.7.12 bug?  I get the correct deps in 2.7.15.

**Comment by erinxocon** [comment]
Ahh ok, Thanks for the update.  Perhaps @techalchemy can shed some light on the why the cache would be doing that.  For now I'm going to close the issue.  Thanks for using pipenv!

**Comment by fairbanksg** [comment]
Thanks for the quick response, glad it turned out not to be a bug.

**Comment by erinxocon** [comment]
Every now and then I do have to clear my cache, but it's usually in relation to testing.

**Comment by fairbanksg** [comment]
I was testing the master branch last week because of some bug fixes. Could that have contributed to this?

**Comment by erinxocon** [comment]
Could be.  @techalchemy or @uranusjr?  Could that be the issue?

**Comment by uranusjr** [comment]
It could, but not likely…

**Comment by techalchemy** [comment]
Hmmm I'm going to close this again for now unless we can get a reproducible test case

Sorry for the trouble!
