### ISSUE TITLE
Invoke vendoring script on CI

### ISSUE THREAD

**Issue by hroncok** [pypa/pipenv#2428]
**Is your feature request related to a problem? Please describe.**

*I'm always frustrated when* I try to update the vendoring script but I'm hit by unrelated issues.

**Describe the solution you'd like**

This could be solved by having the vendoring script being run as part of the Continues Integration (Travis CI e.g. has daily cron as well).

**Describe alternatives you've considered**

Prove that the vendoring script is always reproducible.

**Additional context**

https://github.com/pypa/pipenv/issues/2426#issuecomment-400444068

**Comment by techalchemy** [comment]
I am +1 on this as well, have been meaning to do this but yeah, it's on the list. You know how it is. I have to test it before every release and it's always basically what you experienced.

**Comment by hroncok** [comment]
I don't see Travis CI enabled. Would a PR with this be accepted?

**Comment by erinxocon** [comment]
@hroncok We use buildkite for unix testing, and VSTS for windows testing.  We'll have to figure out how to integrate them on those platforms.

**Comment by techalchemy** [comment]
I just pr'ed it (we also use appveyor currently)

We really need to sort out how to make buildkite publicly visible...

**Comment by uranusjr** [comment]
For the vendoring process itself, would it a good idea to use a bot? I know there’re already mentions of this idea, we can use it to make sure a PR provides news fragments, and (if needed) generate patch files.

**Comment by techalchemy** [comment]
I’d love that. Would need to get time to set this up
