### ISSUE TITLE
Pipenv install local packages created with short hash

### ISSUE THREAD

**Issue by jpaulodit** [pypa/pipenv#2448]
When I install a local package with pipenv, the entry in the Pipfile and the lock file is a short hash instead of the package name. Is there a reason why that happens? And is there anyway to make it use the package name instead?

The issue with that is uninstalling with package name leaves the Pipfile and lock file unchanged. The hash entry remains.

I am installing from local because the package is in a monorepo, and did not want to create it as a package in pypi.

**Comment by uranusjr** [comment]
A hash is generated when Pipenv can not detect the package name. Recent version of Pipenv improves the detection logic, and it should work in most cases.  What version of Pipenv are you using? Can you provide a reproducible example so we can investigate why the detection fails?

Please try to provide as much information as possible when posting an issue. It helps immensely for us to know what the situation is, and prevent needless boilerplate exchange that slows down the process.

**Comment by techalchemy** [comment]
This is a known feature. You can have pipenv use its name by using the latest version of pipenv and adding the package's name to its `setup.py`.

**Comment by brennie** [comment]
I'm still running into this. I'm using pipenv 2018.7.1
