### ISSUE TITLE
TypeError: mkdir() got an unexpected keyword argument 'exist_ok' with Pipenv on Python 3.4

### ISSUE THREAD

**Issue by adhh852** [pypa/pipenv#2451]
Be sure to check the existing issues (both open and closed!).

Describe the issue briefly here.
Run: $ pipenv install requests
Got Error:

Creating a virtualenv for this project...
Pipfile: /home/ec2-user/test3/Pipfile
Using /usr/bin/python34 (3.4.8) to create virtualenv...
⠋Already using interpreter /usr/bin/python34
Using base prefix '/usr'
New python executable in /home/ec2-user/.local/share/virtualenvs/test3-wCjdD5kk/bin/python34
Also creating executable in /home/ec2-user/.local/share/virtualenvs/test3-wCjdD5kk/bin/python
Installing setuptools, pip, wheel...done.
Setting project for test3-wCjdD5kk to /home/ec2-user/test3

Virtualenv location: /home/ec2-user/.local/share/virtualenvs/test3-wCjdD5kk
Creating a Pipfile for this project...
Installing requests...
Collecting requests
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
Collecting idna<2.8,>=2.5 (from requests)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17 (from requests)
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
Collecting urllib3<1.24,>=1.21.1 (from requests)
  Downloading https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl (133kB)
Installing collected packages: idna, chardet, certifi, urllib3, requests
Successfully installed certifi-2018.4.16 chardet-3.0.4 idna-2.7 requests-2.19.1 urllib3-1.23

Adding requests to Pipfile's [packages]...
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.4/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/pipenv/cli.py", line 416, in install
    selective_upgrade=selective_upgrade,
  File "/usr/local/lib/python3.4/site-packages/pipenv/core.py", line 2074, in do_install
    skip_lock=skip_lock
  File "/usr/local/lib/python3.4/site-packages/pipenv/core.py", line 1346, in do_init
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.4/site-packages/pipenv/core.py", line 1098, in do_lock
    dev=settings['dev']
  File "/usr/local/lib/python3.4/site-packages/pipenv/utils.py", line 1177, in get_vcs_deps
    src_dir.mkdir(mode=0o775, exist_ok=True)
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'

Please run `$ python -m pipenv.help`, and paste the results here.

If you're on MacOS, just run the following:

    $ python -m pipenv.help | pbcopy

------------

##### Expected result

Describe what you expected.

##### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

**Comment by techalchemy** [comment]
This is already reported, please check the existing issues including the closed ones

Note that we don't actually build against python 3.4 and you should consider upgrading to python 3.6

**Comment by jfunction** [comment]
@techalchemy I don't mean to sound complainy, but I didn't see anything about incompatibility with python 3.4? Is this information out there somewhere? For example, see Requires section of https://pypi.org/project/pipenv/2018.7.1/ - should that not be changed? Same with the badge at the top of https://pipenv.readthedocs.io/en/latest/ and here at https://github.com/pypa/pipenv

**Comment by jfunction** [comment]
Ok so it seems that [6.25](https://github.com/pypa/pipenv/blob/v2018.6.25/pipenv/utils.py#L1177) and [7.1](https://github.com/pypa/pipenv/blob/v2018.7.1/pipenv/utils.py#L1181) which both officially support 3.4 but use the `exist_ok` parameter, which was [not in python 3.4](https://docs.python.org/3.4/library/pathlib.html#pathlib.Path.mkdir) but [is in python 3.5](https://docs.python.org/3.5/library/pathlib.html#pathlib.Path.mkdir)

I'm not sure what the best recourse would be in this situation but I could suggest maybe wrapping it in try catch and swallowing the possible `FileExistsError`? What should I do; create a PR? reopen the issue? fly away?

**Comment by jfunction** [comment]
The try except solution worked for me on 3.4; pipenv is updating my lockfile now :)

**Comment by uranusjr** [comment]
I think we have already amended that by switching to `pathlib2` on 3.4. You might want to check is the master branch still has this problem.

**Comment by jfunction** [comment]
Confirmed, the next version of pipenv should not see this error. It fixes 2530 too, so I eagerly await the release :)
Thank you.
