### ISSUE TITLE
Double output from pip when using --verbose

### ISSUE THREAD

**Issue by Tenzer** [pypa/pipenv#2475]
As mentioned in #2458, when I'm running `pipenv install --verbose` in a folder which currently doesn't have a virtual environment, and where 'redis' is the only package specified in `Pipfile` and `Pipfile.lock`, I get the output from the `pip` command twice, in both yellow and blue, as shown in this screenshot (I had to make it quite small to fit it on one screen):
![screen shot 2018-06-28 at 11 57 32](https://user-images.githubusercontent.com/68696/42098492-fc34c5fa-7bb2-11e8-95f9-2116f6eb0b46.png)

This is presumably because the `pip` output contains the word "Ignoring" and me specifying `--verbose`. Both triggers the printing of the output, as per this code:
https://github.com/pypa/pipenv/blob/8691c7168bc12711d0b3ae07d0d45967f4afc28a/pipenv/core.py#L727-L730

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.6.26.dev0'`

Pipenv location: `'/Users/jeppe/git/pipenv/pipenv'`

Python location: `'/Users/jeppe/.virtualenvs/pipenv/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/Users/jeppe/.virtualenvs/pipenv/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `3.6.5`: `/Users/jeppe/.virtualenvs/pipenv/bin/python`
  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `3.6.5`: `/usr/local/opt/python/libexec/bin/python`
  - `2.7.15`: `/usr/local/bin/python2`
  - `3.6.5`: `/Users/jeppe/.virtualenvs/pipenv/bin/python3`
  - `3.6.5`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT '
                     '2018; root:xnu-4570.61.1~1/RELEASE_X86_64',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `VIRTUALENVWRAPPER_SCRIPT`
  - `VIRTUALENVWRAPPER_PROJECT_FILENAME`
  - `TERM_PROGRAM`
  - `NVM_CD_FLAGS`
  - `TERM`
  - `SHELL`
  - `CLICOLOR`
  - `HISTSIZE`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `OLDPWD`
  - `TERM_SESSION_ID`
  - `PIPENV_IGNORE_VIRTUALENVS`
  - `HISTFILESIZE`
  - `NVM_DIR`
  - `USER`
  - `COMMAND_MODE`
  - `HOMEBREW_NO_ANALYTICS`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `VIRTUAL_ENV`
  - `WORKON_HOME`
  - `VIRTUALENVWRAPPER_PYTHON`
  - `PATH`
  - `VIRTUALENVWRAPPER_HOOK_DIR`
  - `PWD`
  - `HOMEBREW_GITHUB_API_TOKEN`
  - `EDITOR`
  - `LANG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `PS1`
  - `PYTHONDONTWRITEBYTECODE`
  - `HISTCONTROL`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `GOPATH`
  - `NVM_BIN`
  - `VIRTUALENVWRAPPER_WORKON_CD`
  - `DISPLAY`
  - `SECURITYSESSIONID`
  - `COLORTERM`
  - `_`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

 - `PIPENV_IGNORE_VIRTUALENVS`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/jeppe/.virtualenvs/pipenv/bin:/Users/jeppe/.nvm/versions/node/v8.11.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/jeppe/go/bin:/Users/jeppe/.bin:/usr/local/sbin:/usr/local/opt/python/libexec/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `nano`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/jeppe/git/pipenv-test2`
  - `VIRTUAL_ENV`: `/Users/jeppe/.virtualenvs/pipenv`

---------------------------

Contents of `Pipfile` ('/Users/jeppe/git/pipenv-test2/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
redis = "*"

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/Users/jeppe/git/pipenv-test2/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "7b0f0dbd6c2f0d16c422460053203c035d6fbd716beda24eb8bfd3ba7dab7b2e"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "redis": {
            "hashes": [
                "sha256:8a1900a9f2a0a44ecf6e8b5eb3e967a9909dfed219ad66df094f27f7d6f330fb",
                "sha256:a22ca993cea2962dbb588f9f30d0015ac4afcc45bee27d3978c0dbe9e97c6c0f"
            ],
            "index": "pypi",
            "version": "==2.10.6"
        }
    },
    "develop": {}
}

```
</details>

------------

##### Expected result

The output should only be printed once, probably in yellow since I guess that output is intended to be a bit of a warning, even though it's not that clear from a user perspective why it's printed, unless you look at the source code.

##### Actual result

The output from `pip` is printed twice, first in yellow and then in blue.

##### Steps to replicate

Place the following content inside `Pipfile` in a folder and run `pipenv install --verbose`:
```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
redis = "*"

[dev-packages]

[requires]
python_version = "3.6"
```
Note: This will only work if you get lines such as "Ignoring unknown cache-control directive" in the output from `pip`. I'm getting it on macOS.

**Comment by techalchemy** [comment]
Oh this makes sense now. So you’re saying the verbose flag will include those messages too. But honestly the fileter there is not meant to display ignored cache control directives but ignored packages.  Technically we would want to just exclude ignored cache control directives in the first case I think.
