### ISSUE TITLE
Install deps from git in docker container

### ISSUE THREAD

**Issue by ben-prezola** [pypa/pipenv#2476]
I have a private git repository which I have in my Pipfile and it is marked as `editable = true`.
I can install this locally in my virtual environment no problem.

I am using Docker and inside my Dockerfile I run:
`pipenv install --system --deploy`

This installs my library into a `src/` directory in the working directory. I don't know why it's doing that but is there something I am missing or is there a way to specify `site-packages`.

**Comment by techalchemy** [comment]
Pip also does this. You can set the environment variable `PIP_SRC` to change it.

**Comment by ben-prezola** [comment]
Thank you 👍
