### ISSUE TITLE
Add pipenv --support instead of python -m pipenv.help

### ISSUE THREAD

**Issue by erinxocon** [pypa/pipenv#2477]
When homebrew is used to install python, the debug help command doesn't work.  
`pipenv --support` will now be the flag to invoke when getting diagnostic information.

**Comment by techalchemy** [comment]
i'm guessing we want to keep `.help` too and just leave it as a thin wrapper around the new command

**Comment by erinxocon** [comment]
`pipenv --support` and `python -m pipenv.help` are both supported now with `pipenv --support` being preferred.
