### ISSUE TITLE
apt-get always printing SyntaxError: 'yield' inside async function

### ISSUE THREAD

**Issue by rcalvert** [pypa/pipenv#2481]
Note: pipenv _does_ work.  This is only a minor nuisance.   

I get the below message every time I run apt-get.  Whether related to python or not... 

```
Setting up pipenv (11.10.1-1) ...
  File "/usr/lib/python3/dist-packages/pipenv/vendor/jinja2/asyncfilters.py", line 24
    yield item
             ^
SyntaxError: 'yield' inside async function

  File "/usr/lib/python3/dist-packages/pipenv/vendor/jinja2/asyncsupport.py", line 35
    yield event
              ^
SyntaxError: 'yield' inside async function

dpkg: error processing package pipenv (--configure):
 subprocess installed post-installation script returned error exit status 1
```

A very shallow look into this yielded https://github.com/pallets/jinja/issues/643 

Oh, and this is on Windows WSL mode runningUbuntu Xenial

**Comment by uranusjr** [comment]
Where do you get the APT source? I don’t think there are official distributions, and we don’t provide PPA for Xenial either.

**Comment by techalchemy** [comment]
pipenv 11.10 is super old btw.  I might as well just build this myself

**Comment by rcalvert** [comment]
The steps I followed to install it were 

```bash
$ sudo apt install software-properties-common python-software-properties
$ sudo add-apt-repository ppa:pypa/ppa
$ sudo apt update
$ sudo apt install pipenv
```

Per https://docs.pipenv.org/

The source is showing as:

```bash
$ apt-cache policy pipenv
pipenv:
  Installed: 11.10.1-1
  Candidate: 11.10.1-1
  Version table:
 *** 11.10.1-1 500
        500 http://ppa.launchpad.net/pypa/ppa/ubuntu artful/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by uranusjr** [comment]
That is an Artful PPA, not Xenial. Don’t mix that. Install from pip instead.
