### ISSUE TITLE
Configure environment to make virtualenv as isolated as possible

### ISSUE THREAD

**Issue by braco** [pypa/pipenv#2493]
------------

##### Issue description

```
$ PIPENV_VENV_IN_PROJECT=1 pipenv install
```
```
$ rm -rf .venv/lib
```
```
$ PIPENV_VENV_IN_PROJECT=1 pipenv run python test.py
```

I would think this would throw an error, but instead it seems to just read from the system libraries instead of .venv. Is this by design?

-------------

```
$ pipenv --support
Error: no such option: --support
$ pipenv --version
pipenv, version 2018.6.25
```

**Comment by techalchemy** [comment]
In what way does this default to system python? You haven’t deleted the virtualenv or the python binary inside it. You only deleted a folder of libraries which may or may not be relevant to whatever you ran in your example. Python still would work fine. Also, the `--support` flag was added in the release that came out yesterday. 

What is your goal here? We don’t build in protections to stop you from selectively deleting things out of your virtualenv. The things you deleted don’t prevent the tasks you attempted. I’m not sure there’s anything else we can really say on this.

**Comment by braco** [comment]
Sorry, wasn't clear: the libraries inside _are_ required by test.py, and when some key topmost directories are corrupt/deleted from .venv, there are no errors thrown. I guess you're saying that's expected?

For more detail, an error is thrown if deeper files are corrupted, but not the uppermost directory/ies.

My expectation was that .venv was self-contained, and corruption to key files in this folder would break the script.

Is there any way to say ".venv is the only library path, not the first path in an array of search locations"?

**Comment by braco** [comment]
```
mkdir test && cd test
PIPENV_VENV_IN_PROJECT=1 pipenv install requests
echo "import requests" >> test.py
PIPENV_VENV_IN_PROJECT=1 pipenv run test.py
```
The above works as expected

Let's remove .venv/lib and run again
```
rm -rf .venv/lib
PIPENV_VENV_IN_PROJECT=1 pipenv run test.py
```

No errors? Let's remove the system package and try again

```
pip uninstall requests
PIPENV_VENV_IN_PROJECT=1 pipenv run test.py
```

Errors as expected
> Traceback (most recent call last):
>   File "test.py", line 1, in <module>
>     import requests
> ImportError: No module named requests

Let's setup again and delete the requests library inside .venv:

```
rm -rf .venv
PIPENV_VENV_IN_PROJECT=1 pipenv install requests
rm -rf .venv/lib/python2.7/site-packages/requests
PIPENV_VENV_IN_PROJECT=1 pipenv run test.py
```

> Traceback (most recent call last):
>   File "test.py", line 1, in <module>
>     import requests
> ImportError: No module named requests

**Comment by uranusjr** [comment]
I assume you’re using Windows? By default `.py` files are associated to the py launcher, which finds a system Python, not a virtualenv Python. I think there is a workaround, but generally you want to do `pipenv run python test.py` instead.

**Comment by braco** [comment]
Not following, this is what I'm running on MacOS:

> PIPENV_VENV_IN_PROJECT=1 pipenv run test.py

But the issue is about the inconsistency between `.venv/lib` not existing (default to system in this case) and `.venv/lib/python2.7/*` not existing (error)

**Comment by uranusjr** [comment]
No, it’s about you are using an incorrect invocation style.

On macOS (and Windows, but that is not relevant in your case), files have a “default association”. If you open a file without specifying an executable, it is run with a default one specified by the system. If you install Python with an official installer from python.org, it sets the association automatically.

This means that when you invoke `pipenv run test.py` without specifying an interpreter, the file will always be executed by the default associated executable, which is always a system-wide Python, never the virtual environment Python. To get the interpreter inside the environment, you should write `pipenv run python test.py`. With your commands, the virtual environment is never taken into consideration.

**Comment by uranusjr** [comment]
(Original comment deleted—I see it is a typo, not a different invocation style.)

There is no such fallback, however. This is likely related to how virtualenv works internally, and we can do very little about it if that is the case. You may want to investigate using bare virtualenvs, and file the issue to [pypa/virtualenv](https://github.com/pypa/virtualenv).

I’m keeping this in my backlog to investigate later with a Mac. Will reopen if I find anything unusual about Pipenv itself (instead of virtualenv).

**Comment by braco** [comment]
Will do, thank you

**Comment by uranusjr** [comment]
I did some digging and this is indeed a problem caused by virtualenv’s design. virtualenv uses [`site.py`](https://github.com/pypa/virtualenv/blob/6f424ca/virtualenv_embedded/site.py) to hook into Python’s startup sequence and perform customisation.

Python is hard-wired to detect `../lib/pythonX.Y/site.py` when it starts up. If a `site.py` does not exist on the call side (i.e. in the virtual environment), it automatically uses the default `site.py` instead. This is how the interpreter is designed. So unfortunately there is no way to fix this, even in virtualenv.

**Comment by braco** [comment]
Nice investigatory work, @uranusjr, thanks!

Looks like this might work to clear sys.path?

`PYTHONHOME=/foo PYTHONPATH=/foo python`

**Comment by uranusjr** [comment]
Setting `PYTHONHOME` sounds like a good idea. IIRC virtualenv’s activate script also sets it. Maybe we should do the same. Will need to dig deeper.

**Comment by matteius** [comment]
A lot has changed since this issue report was opened.  Please open a new report if there is a modern issue to address.
