### ISSUE TITLE
index_indicators check needs improvement.

### ISSUE THREAD

**Issue by jpaulodit** [pypa/pipenv#2494]
##### Issue description

When installing local package, the logical check on this line does not work correctly when package name has `-i` in it.

https://github.com/pypa/pipenv/blob/29eb73aa7f1abc2bef077cd967df21a8719f4b66/pipenv/core.py#L1873

##### Actual result

Pipenv tries installing a package called `-e`

##### Steps to replicate

Suppose you have a local python package named like `marathon-python-internal`

> pipenv install -e ../packages/marathon-python-lnternal/

This results in the code flow falling inside the IF condition vs some other package name that doesn't have the string `-i` in them eg

> pipenv install -e ../packages/funniest/

```
pipenv, version 2018.7.1
```

**Comment by techalchemy** [comment]
hmmm yes, that is a problem.

**Comment by mlouielu** [comment]
Some points I want to know:

1. pipenv install -i https://foo.bar

In pipenv, it will include source in Pipfile and https://foo.bar

2. pipenv install -i https://foo -i https://bar

It will only include source in Pipfile and https://bar

3. pipenv install -i https://foo --extra-index-url https://bar

It should include source in Pipfile, and https://foo, and https://bar

Is that right @techalchemy ?
