### ISSUE TITLE
Bash script on wiki will misbehave with spaces in pathnames

### ISSUE THREAD

**Issue by anowlcalledjosh** [pypa/pipenv#2497]
The automatic `pipenv shell` script for Bash on the wiki will not work properly if the path to a virtualenv contains a space, or if a project name contains a space.

The `workon` function should have quotes around the paths, like so:

```bash
workon() {
    if [ $# -eq 0 ]
    then
        source "$(pipenv --venv)/bin/activate"
    else
        source "~/.virtualenvs/$1/bin/activate"
    fi
}
```

Arguably, all the uses of `cd ...` should also be `cd ... || return 1`, so that the functions stop if they can't access a directory.

I would fix this myself, but it looks like only people marked as collaborators on GitHub can edit the wiki.

**Comment by uranusjr** [comment]
Fixed! Thanks for the report.
