### ISSUE TITLE
Installing tornado from Pipfile{,.lock} losts singledispatch dependency in Python 2.7

### ISSUE THREAD

**Issue by hexchain** [pypa/pipenv#2498]
##### Issue description

In Python 2.7, installing from Pipfile{,lock} containing `tornado` does not install its `singledispatch` dependency.

##### Expected result

`singledispatch` is installed.

##### Actual result

`singledispatch` is not installed and `tornado` is unusable.

##### Steps to replicate

1. Create a `Pipfile` according to detailed info below.
2. Run `pipenv install --two`
3. ```
   $ pipenv run python
   Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
   [GCC 6.3.0 20170516] on linux2
   Type "help", "copyright", "credits" or "license" for more information.
   >>> import tornado
   >>> import tornado.web
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/home/thc/.local/share/virtualenvs/test-50RnJwkM/local/lib/python2.7/site-packages/tornado/web.py", line 86, in <module>
       from tornado import gen
     File "/home/thc/.local/share/virtualenvs/test-50RnJwkM/local/lib/python2.7/site-packages/tornado/gen.py", line 112, in <module>
       from singledispatch import singledispatch  # backport
   ImportError: No module named singledispatch
   >>> 
   ```

---------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/home/thc/.local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`

  - `2.7.13`: `/usr/bin/python`
  - `2.7.13`: `/usr/bin/python2`
  - `3.5.3`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.9.0-6-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07)',
 'python_full_version': '2.7.13',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `LANG`
  - `TERM`
  - `SSH_CONNECTION`
  - `XDG_RUNTIME_DIR`
  - `SHLVL`
  - `SSH_TTY`
  - `OLDPWD`
  - `SSH_CLIENT`
  - `PYTHONDONTWRITEBYTECODE`
  - `PATH`
  - `PWD`
  - `SHELL`
  - `LOGNAME`
  - `EDITOR`
  - `MAIL`
  - `HOME`
  - `PIP_PYTHON_PATH`
  - `LS_COLORS`
  - `XDG_SESSION_ID`
  - `_`
  - `USER`

Pipenv–specific environment variables:


Debug–specific environment variables:

  - `PATH`: `/home/thc/.local/bin:/home/thc/.local/bin:/data/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/node/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/thc/test`


---------------------------

Contents of `Pipfile` ('/home/thc/test/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
tornado = "*"

[requires]
python_version = "2.7"

```

Contents of `Pipfile.lock` ('/home/thc/test/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "cfe1c3b4f6ee7b1f69b28e485f82072c4c262e38d17aca29d1333eaca13e16d3"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "2.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "tornado": {
            "hashes": [
                "sha256:1b83d5c10550f2653380b4c77331d6f8850f287c4f67d7ce1e1c639d9222fbc7",
                "sha256:408d129e9d13d3c55aa73f8084aa97d5f90ed84132e38d6932e63a67d5bec563",
                "sha256:88ce0282cce70df9045e515f578c78f1ebc35dcabe1d70f800c3583ebda7f5f5",
                "sha256:ba9fbb249ac5390bff8a1d6aa4b844fd400701069bda7d2e380dfe2217895101",
                "sha256:c050089173c2e9272244bccfb6a8615fb9e53b79420a5551acfa76094ecc3111"
            ],
            "index": "pypi",
            "version": "==5.0.2"
        }
    },
    "develop": {}
}

```
</details>

**Comment by uranusjr** [comment]
Tornado needs to update their [setup.py](https://github.com/tornadoweb/tornado/blob/v5.1.0b1/setup.py#L126) to use [PEP 508 environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers). Please file an issue for them to fix this. There is not much we can do.
