### ISSUE TITLE
pipenv run doesn't update Pipfile or Pipfile.lock

### ISSUE THREAD

**Issue by themagicmountain** [pypa/pipenv#2506]
In a working directory I run,
``
pipenv run pip install rlp==0.6.0
`` 
When I then run
``
pip lock
`` 

Pipfile.lock isn't updated with the lower version number version, and running ``pip sync`` takes me back to the broken, newer version. 

I would like to be able to force override of requirements -- currently I am just generating a requirements.txt with ``pip lock -r`` but my feeling is there should be a more graceful way of doing this. 

Possibly if the lower level pip commands were also reflected in pipenv?

**Comment by techalchemy** [comment]
`pipenv run` will run any command you give it inside your virtualenv. This is not an official api for installing things and we don’t check if you are handing stuff to pip and bypassing pipenv (which you may want to do sometimes). If you want to put something in your pipfile, use `pipenv install <packagename>`
