### ISSUE TITLE
Get mirror from pip.conf

### ISSUE THREAD

**Issue by KeatingSmith** [pypa/pipenv#2517]
if pip.conf is exists, pipenv can use default mirror from it.

And setting env ` PIPENV_PYPI_MIRROR ` is not working.

So, it`s urgent need for a feature: `pipenv can set mirror`

 priority of mirror is : --pypy-mirror > PIPENV_PYPI_MIRROR > pip.conf > default

**Comment by uranusjr** [comment]
I wish this request were not so urgent you didn’t even have the time to follow the issue template and search the issue tracker.

https://github.com/pypa/pipenv/issues?utf8=%E2%9C%93&q=is%3Aissue+%22pip.conf%22

**Comment by techalchemy** [comment]
Yeah so I’m not sure...was this a bug report or a feature request or just a random set of demands?
