### ISSUE TITLE
Is there a way to disable / suppress pipenv's "Courtesy Notice" about virtual environments?

### ISSUE THREAD

**Issue by trianta2** [pypa/pipenv#2527]
Each time I invoke `pipenv` I see:

> Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead.

Can this be globally suppressed?

**Comment by uranusjr** [comment]
No, there is not.

**Comment by uranusjr** [comment]
That said, maybe we can treat an empty `PIPENV_IGNORE_VIRTUALENVS` as the suppressor.

* `PIPENV_IGNORE_VIRTUALENVS` absent—show the message.
* `PIPENV_IGNORE_VIRTUALENVS` set to empty string—suppress the message, but use the environment.
* `PIPENV_IGNORE_VIRTUALENVS` is not empty—create a nested virtualenv.

**Comment by trianta2** [comment]
Does `PIPENV_IGNORE_VIRTUALENVS=0` have any significance? If pipenv was told to not ignore virtual envs, then that should mean I want to use my existing virtual env, and the courtesy notice should be ignored.

**Comment by techalchemy** [comment]
We have an environment variable to suppress output but we don't use it much. We can add this to the refactor

**Comment by max-arnold** [comment]
My current workaround:

`pipenv lock --requirements 2> >(grep -v "Courtesy Notice" >&2) > requirements.txt`

**Comment by uranusjr** [comment]
@max-arnold You found a bug! `lock -r` should output to stdout (it does when you’re not in a virtualenv), but for some reason outputs to stderr when you are inside. You shouldn’t need more than `pipenv lock --requirements > requirements.txt`. We will fix that. Sorry for the annoyance.

**Comment by max-arnold** [comment]
@uranusjr Fancy grep and redirections are used to filter`Courtesy Notice` while preserving stderr/stdout separation and exit codes.

**Comment by Abbyboing** [comment]
Where should I set this?

> PIPENV_VERBOSITY=-1

A bit new to programming so unable to find the proper solution.
