### ISSUE TITLE
Pipenv not 'picking up' Pyenv's Python version?

### ISSUE THREAD

**Issue by khpeek** [pypa/pipenv#2532]
As described in [this StackOverflow question](https://stackoverflow.com/questions/51201018/pipenv-not-recognizing-pyenv-version), I'm trying to use `pipenv` together with [`pyenv`](https://github.com/pyenv/pyenv) to specify a certain version of Python. However, when I run `pipenv shell`, it runs with my system version of Python and not the one I specified using the [`pyenv local`](https://github.com/pyenv/pyenv/blob/master/COMMANDS.md#pyenv-local) command.

Are `pipenv` and `pyenv` not compatible with each other?

**Comment by erinxocon** [comment]
Hi @khpeek!  Thanks for choosing to use pipenv.  I'm guessing that this is a PATH issue.  Pipenv should be able to use pyenv no problem.  Could you please open a new issue that and follow the issue template so I can get a better idea of where your pipenv installation is at.
