### ISSUE TITLE
pipenv lock stores commit hash

### ISSUE THREAD

**Issue by notEvil** [pypa/pipenv#2552]
##### Issue description

For git urls, `pipenv lock` stores commit hash instead of git ref to Pipfile.lock. `pipenv lock -r` then creates invalid lines.

##### Expected result

-i https://pypi.org/simple
git+https://github.com/dfunckt/django-rules@master#egg=django-rules

##### Actual result

-i https://pypi.org/simple
git+https://github.com/dfunckt/django-rules@ec0d0905240cd1e4d79724fd53f7fd461023a3bf#egg=django-rules

##### Steps to replicate

pipenv install "git+https://github.com/dfunckt/django-rules@master#egg=django-rules"
pipenv lock -r

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/home/arappold/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.12`: `/usr/bin/python`
  - `2.7.12`: `/usr/bin/python2`
  - `3.5.2`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-24-generic',
 'platform_system': 'Linux',
 'platform_version': '#26~16.04.1-Ubuntu SMP Fri Jun 15 14:35:08 UTC 2018',
 'python_full_version': '3.6.6',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `DBUS_SESSION_BUS_ADDRESS`
  - `DEFAULTS_PATH`
  - `DESKTOP_AUTOSTART_ID`
  - `DESKTOP_SESSION`
  - `DISPLAY`
  - `GDMSESSION`
  - `GDM_LANG`
  - `GNOME_DESKTOP_SESSION_ID`
  - `GPG_AGENT_INFO`
  - `GTK_MODULES`
  - `GTK_OVERLAY_SCROLLING`
  - `HOME`
  - `LANG`
  - `LANGUAGE`
  - `LC_ADDRESS`
  - `LC_IDENTIFICATION`
  - `LC_MEASUREMENT`
  - `LC_MONETARY`
  - `LC_NAME`
  - `LC_NUMERIC`
  - `LC_PAPER`
  - `LC_TELEPHONE`
  - `LOGNAME`
  - `LS_COLORS`
  - `MANDATORY_PATH`
  - `PATH`
  - `PWD`
  - `QT_ACCESSIBILITY`
  - `QT_LINUX_ACCESSIBILITY_ALWAYS_ON`
  - `QT_QPA_PLATFORMTHEME`
  - `QT_STYLE_OVERRIDE`
  - `SESSION_MANAGER`
  - `SHELL`
  - `SHLVL`
  - `SSH_AGENT_PID`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `USER`
  - `VTE_VERSION`
  - `WINDOWID`
  - `XAUTHORITY`
  - `XDG_CONFIG_DIRS`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_DATA_DIRS`
  - `XDG_GREETER_DATA_DIR`
  - `XDG_RUNTIME_DIR`
  - `XDG_SEAT`
  - `XDG_SEAT_PATH`
  - `XDG_SESSION_DESKTOP`
  - `XDG_SESSION_ID`
  - `XDG_SESSION_PATH`
  - `XDG_SESSION_TYPE`
  - `XDG_VTNR`
  - `__fish_bin_dir`
  - `__fish_datadir`
  - `__fish_help_dir`
  - `__fish_sysconfdir`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/arappold/bin:/home/arappold/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
  - `SHELL`: `/usr/bin/fish`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/arappold/git/cloud-backend-alice/scripts/pipenv`

---------------------------

Contents of `Pipfile` ('/home/arappold/git/cloud-backend-alice/scripts/pipenv/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django-rules = {ref = "master", git = "https://github.com/dfunckt/django-rules"}

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/home/arappold/git/cloud-backend-alice/scripts/pipenv/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "25313a7f522107a2f58a0d613208fa8b7656223bbf63ea143001d52250a789bb"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "django-rules": {
            "git": "https://github.com/dfunckt/django-rules",
            "ref": "ec0d0905240cd1e4d79724fd53f7fd461023a3bf"
        }
    },
    "develop": {}
}

```
</details>

**Comment by uranusjr** [comment]
It is not invalid. Did you try actually use the output? It totally works (except the `egg=django-rules` part because that package is not actually called django-rules).

**Comment by uranusjr** [comment]
Also see #2180 for explaination why this is done. The difference between branch and commit is similar to abstract and concrete versions—The locked result should contain commit info instead of branch so subsequent installations can reproduce the locked environment exactly.

I vaguely remember there is an issue about `--outdated` should report outdated branch-commit results, but I can’t find it now. @techalchemy do you remember?

**Comment by notEvil** [comment]
Sorry! I agree. I might be a little frustrated by multiple issues stacking up.
The issue must then be in serverless-python-requirements (nodejs package).

**Comment by uranusjr** [comment]
No worrys. Please do report any potential issues when you find them! 🌌
