### ISSUE TITLE
install doesn't honor .env

### ISSUE THREAD

**Issue by caulagi** [pypa/pipenv#2562]
##### Issue description

`pipenv install` doesn't use `PIPENV_PIPFILE` when specified in `.env`. However,  install uses `PIPENV_PIPFILE` when it is defined as a normal shell variable.

##### Expected result

`pipenv install` doesn't create new Pipfile

##### Actual result

```bash
$ cd /tmp/test
$ find .
.
./.env
./requirements
./requirements/Pipfile
./requirements/Pipfile.lock

$ cat .env
PIPENV_PIPFILE=${PWD}/requirements/Pipfile

$ pipenv install
Creating a Pipfile for this project...
Pipfile.lock not found, creating...

$ export PIPENV_PIPFILE=/tmp/test/requirements/Pipfile

$ pipenv install
Creating a virtualenv for this project...
Pipfile: /tmp/test/requirements/Pipfile
```

##### Steps to replicate

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.7.1/libexec/bin/python3.7'`

Other Python installations in `PATH`:

  - `2.6`: `/usr/bin/python2.6`
  - `2.6`: `/usr/bin/python2.6`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.7`: `/usr/local/bin/python3.7m`
  - `3.7`: `/usr/local/bin/python3.7`

  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.15`: `/usr/local/bin/python2`
  - `3.7.0`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '16.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST '
                     '2018; root:xnu-3789.73.11~1/RELEASE_X86_64',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `GREP_COLOR`
  - `NNTPSERVER`
  - `LESS_TERMCAP_mb`
  - `TERM_PROGRAM`
  - `NODEUP_BUCKET`
  - `LESS_TERMCAP_md`
  - `LESS_TERMCAP_me`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `CLUSTER_NAME`
  - `LESS_TERMCAP_ue`
  - `TERM_SESSION_ID`
  - `LC_ALL`
  - `USER`
  - `LS_COLORS`
  - `GREP_COLORS`
  - `COMMAND_MODE`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `LSCOLORS`
  - `LESS_TERMCAP_us`
  - `_`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `CLOUDSDK_PYTHON`
  - `XPC_FLAGS`
  - `HOST_IP`
  - `XPC_SERVICE_NAME`
  - `GPG_TTY`
  - `KOPS_STATE_STORE`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `IMAGE`
  - `ITERM_SESSION_ID`
  - `LOGNAME`
  - `LESS_TERMCAP_so`
  - `LC_CTYPE`
  - `FZF_DEFAULT_COMMAND`
  - `WEECHAT_HOME`
  - `GOPATH`
  - `SECURITYSESSIONID`
  - `LESS_TERMCAP_se`
  - `COLORTERM`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.7.1/libexec/tools:/Users/pradipcaulagi/.yarn/bin:/Users/pradipcaulagi/.config/yarn/global/node_modules/.bin:/Users/pradipcaulagi/go/bin:/Users/pradipcaulagi/Downloads/google-cloud-sdk/bin:/Users/pradipcaulagi/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Applications/Wireshark.app/Contents/MacOS`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/tmp/test`

---------------------------

Contents of `Pipfile` ('/private/tmp/test/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/private/tmp/test/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "7e7ef69da7248742e869378f8421880cf8f0017f96d94d086813baa518a65489"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

**Comment by uranusjr** [comment]
No it does not, ahdn that is by design. `.env` is only evaluated by `run` and `shell`. The documentation has some suggestion on this issue:

https://docs.pipenv.org/advanced/#configuration-with-environment-variables

**Comment by caulagi** [comment]
@uranusjr thanks! I has missed direnv. However, it seems confusing to use .env for some sub-commands but .envrc for others. Just out of curiosity, why are environment variables via .env not support for all sub-commands?

**Comment by techalchemy** [comment]
`.env` files are loaded by pipenv only for the purpose of and in the context of running your code inside your virtualenv (e.g. running an application in a virtualenv).  This is a context switch at which time pipenv is modifying your environment in other ways (which python you use, your path search location, etc) and therefore it also may alter the context of your environment variables.  We have had a few extensive discussions on this in past issues, feel free to search for those if you'd like to know more.
