### ISSUE TITLE
ImportError: No module named req_install

### ISSUE THREAD

**Issue by yu-liang-kono** [pypa/pipenv#2565]
##### Issue description
Fail to execute `pipenv install`. No Pipfile.lock is created. I tried `v2018.7.1` and `v2018.6.25`, both of them don't work. But `v2018.05.18` works, it's weird.

- pipenv `v2018.6.25`
- pip `10.0.1`
- python `2.7.6`

##### Actual result

```shell
> pipenv install --verbose
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
using sources: [{u'url': u'https://pypi.org/simple', u'verify_ssl': True, u'name': u'pypi'}]

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 87, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 76, in main
    system=system,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 63, in resolve
    allow_global=system,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 402, in resolve_deps
    req_dir=req_dir
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 232, in actually_resolve_deps
    from .vendor.requirementslib import Requirement
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/__init__.py", line 6, in <module>
    from .models import Requirement, Lockfile, Pipfile
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/models/__init__.py", line 8, in <module>
    from .requirements import Requirement
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/models/requirements.py", line 14, in <module>
    from .markers import PipenvMarkers
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/models/markers.py", line 6, in <module>
    from .utils import validate_markers, filter_none
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/models/utils.py", line 7, in <module>
    from .._compat import Link
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/_compat.py", line 41, in <module>
    InstallRequirement = do_import("req.req_install", "InstallRequirement")
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/_compat.py", line 35, in do_import
    _tmp = importlib.import_module(pip9)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named req_install
/usr/local/lib/python2.7/dist-packages/pipenv/_compat.py:113: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-j_DPd2-requirements'>
  warnings.warn(warn_message, ResourceWarning)

/usr/local/lib/python2.7/dist-packages/pipenv/_compat.py:113: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-jPQFk0-requirements'>
  warnings.warn(warn_message, ResourceWarning)
```

##### Steps to replicate
My Pipfile:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
ujson = "==1.35"
bottle = "==0.11.6"
pymongo = "==2.8.0"
mongoengine = "==0.8.7"
"html2text" = "==3.200.3"
requests = {version = "==2.13.0", extras = ["security"]}
gmail = "==0.5"
lxml = "==4.1.0"
"beautifulsoup4" = "==4.3.2"
imgutil = ">=0.1.2"
celery = "==3.1.25"
flower = "==0.9.1"
facebook-sdk = "==2.0.0"
"pbkdf2" = "==1.3"
interactor = "==0.1.2"
retrying = "==1.3.3"
futures = "==3.1.1"
libthumbor = "==1.3.2"
"boto3" = "==1.4.4"
humanize = "==0.5.1"
"html5lib" = "==0.9999999"
contexttimer = "==0.3.3"
filetype = "==1.0.0"
Pillow = "==2.7.0"
Fabric = "==1.8.1"
"Jinja2" = "==2.7.3"
youtube_dl = "==2018.7.4"
autolink_py = "==0.2.0"

[requires]
python_version = "2.7"
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/usr/local/lib/python2.7/dist-packages/pipenv'`

Python location: `'/usr/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.4`: `/usr/bin/python3.4m`
  - `3.4`: `/usr/bin/python3.4`

  - `2.7.6`: `/usr/bin/python`
  - `2.7.6`: `/usr/bin/python2`
  - `3.4.3`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '3.13.0-151-generic',
 'platform_system': 'Linux',
 'platform_version': '#201-Ubuntu SMP Wed May 30 14:22:13 UTC 2018',
 'python_full_version': '2.7.6',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `GOPATH`
  - `WINDOWID`
  - `LS_COLORS`
  - `LC_NUMERIC`
  - `GNOME_DESKTOP_SESSION_ID`
  - `WINDOWPATH`
  - `XDG_CURRENT_DESKTOP`
  - `__fish_bin_dir`
  - `XDG_VTNR`
  - `QT_IM_MODULE`
  - `LOGNAME`
  - `USER`
  - `GNOME_KEYRING_CONTROL`
  - `LC_PAPER`
  - `HOME`
  - `DISPLAY`
  - `PATH`
  - `LANG`
  - `TERM`
  - `SHELL`
  - `QT_QPA_PLATFORMTHEME`
  - `SESSION_MANAGER`
  - `LC_MEASUREMENT`
  - `MANDATORY_PATH`
  - `CLUTTER_IM_MODULE`
  - `TEXTDOMAIN`
  - `QT4_IM_MODULE`
  - `COMPIZ_CONFIG_PROFILE`
  - `SESSION`
  - `__fish_sysconfdir`
  - `SESSIONTYPE`
  - `IM_CONFIG_PHASE`
  - `GPG_AGENT_INFO`
  - `LC_MONETARY`
  - `USERNAME`
  - `SHLVL`
  - `SSH_AUTH_SOCK`
  - `__fish_help_dir`
  - `XDG_RUNTIME_DIR`
  - `LC_IDENTIFICATION`
  - `LC_ADDRESS`
  - `SELINUX_INIT`
  - `COMPIZ_BIN_PATH`
  - `DESKTOP_SESSION`
  - `J2SDKDIR`
  - `GDMSESSION`
  - `XMODIFIERS`
  - `TEXTDOMAINDIR`
  - `PYTHONDONTWRITEBYTECODE`
  - `GNOME_KEYRING_PID`
  - `PIP_PYTHON_PATH`
  - `XDG_SESSION_ID`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `GTK_MODULES`
  - `GTK_IM_MODULE`
  - `DERBY_HOME`
  - `JAVA_HOME`
  - `XDG_CONFIG_DIRS`
  - `DEFAULTS_PATH`
  - `VTE_VERSION`
  - `XDG_SEAT`
  - `__fish_datadir`
  - `GDM_LANG`
  - `LC_TELEPHONE`
  - `XAUTHORITY`
  - `INSTANCE`
  - `PWD`
  - `JOB`
  - `COLORTERM`
  - `LC_NAME`
  - `XDG_MENU_PREFIX`
  - `LC_TIME`
  - `J2REDIR`
  - `XDG_DATA_DIRS`
  - `UPSTART_SESSION`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/go/bin:/home/user/.autojump/bin:/home/user/.ndenv/shims:/home/user/.ndenv/bin:/home/user/projects/go_workspace/bin:/home/user/.rbenv/shims:/home/user/.rbenv/bin:/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin`
  - `SHELL`: `/usr/bin/fish`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/user/projects/test_pipenv`

---------------------------

Contents of `Pipfile` ('/home/user/projects/test_pipenv/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
ujson = "==1.35"
bottle = "==0.11.6"
pymongo = "==2.8.0"
mongoengine = "==0.8.7"
"html2text" = "==3.200.3"
requests = {version = "==2.13.0", extras = ["security"]}
gmail = "==0.5"
lxml = "==4.1.0"
"beautifulsoup4" = "==4.3.2"
imgutil = ">=0.1.2"
celery = "==3.1.25"
flower = "==0.9.1"
facebook-sdk = "==2.0.0"
"pbkdf2" = "==1.3"
interactor = "==0.1.2"
retrying = "==1.3.3"
futures = "==3.1.1"
libthumbor = "==1.3.2"
"boto3" = "==1.4.4"
humanize = "==0.5.1"
"html5lib" = "==0.9999999"
contexttimer = "==0.3.3"
filetype = "==1.0.0"
Pillow = "==2.7.0"
Fabric = "==1.8.1"
"Jinja2" = "==2.7.3"
youtube_dl = "==2018.7.4"
autolink_py = "==0.2.0"

[requires]
python_version = "2.7"

```

</details>

**Comment by erinxocon** [comment]
Hi @yu-liang-kono, thanks for using pipenv!  I'm happy to help ou debug this issue.  I am trying to replicate it on my machine, however I am unable too.  I'm wondering if there is a discrepancy from python 2.7.6 to 2.7.15.  There is something wrong with the pipfile, specifically the package entry for amqp.   Here is my output from trying to lock the pipfile you provided.  Is it possible for you to upgrade the version of python you are using?  

```
Creating a virtualenv for this project…
Pipfile: R:\pipenv-test\Pipfile
Using C:\Python27\python.exe (2.7.15) to create virtualenv…
Running virtualenv with interpreter C:\Python27\python.exe
New python executable in C:\Users\erin\.virtualenvs\pipenv-test-8FQ5-y6V\Scripts\python.exe
Installing setuptools, pip, wheel...done.

Virtualenv location: C:\Users\erin\.virtualenvs\pipenv-test-8FQ5-y6V
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches amqp<2.0,<3.0,>=1.4.9,>=2.1.4

Tried: 0.9.1, 0.9.2, 0.9.3, 0.9.4, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.2.0,
1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.3, 1.4.4, 1.4.4, 1.4.5, 1.4.5, 1.4.6, 1.4.6, 1.4.7, 1.4.8, 1.4.8, 1.4.9, 1.4.9, 2.0.0, 2.0.0, 2.0.1, 2.0.2, 2.0.2, 2.0.3, 2.0.3, 2.1.0, 2.1.0, 2.1.1, 2.1.1, 2.1.2, 2.1.2, 2.1.3, 2.1.3, 2.1.4, 2.1.4, 2.2.0, 2.2.0, 2.2.1, 2.2.1, 2.2.2, 2.2.2, 2.3.0, 2.3.0, 2.3.1, 2.3.1, 2.3.2, 2.3.2

There are incompatible versions in the resolved dependencies.
```

**Comment by uranusjr** [comment]
Hi! Would you be able to provide what versions of setuptools and pip are installed on your machine? I mean the version installed alongside your Pipenv, i.e. inside `/usr`, not the one inside the virtual environment.

I also wonder what particular reason makes you stay on 2.7.6 without upgrading. It is strongly recommended that you bring your system up-to-date if possible.

**Comment by yu-liang-kono** [comment]
Hi, @uranusjr, thanks for helping out. My pip version is `10.0.1`, and my setuptools version is `38.2.4`. I'm pretty sure `pip._internal.req.req_install` exists in my `/usr/local/lib/python2.7/dist-packages` folder, it is importable in my python interpreter. To debug, I put a `pdb.set_trace` statement into `/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/_compat.py`, and step through the code, but cannot reproduce the importing error. :(

There is no particular reason that I stay in `2.7.6`. I was working on a system using python around 2014. The main version was `2.7.6` then. I got my hands on pipenv few days ago and try to use it to replace my requirements.txt and virtualenv. I'll give `2.7.15` a shot if possible.

**Comment by uranusjr** [comment]
If you cannot upgrade the system Python, I would suggest installing Pipenv to a Python 3 installation instead. Pipenv has much fewer problems on Python 3.

**Comment by techalchemy** [comment]
closing for now, we don't really support 2.7.6
