### ISSUE TITLE
Using Update for a Dev Package will add it to Default List in Pipfile

### ISSUE THREAD

**Issue by FlavioCestari** [pypa/pipenv#2566]
##### Issue description

When using `$ pipenv update` or `$ pipenv update <pkg>` to a dev package will add it in the default package list of PipFile.

##### Expected result

Keep updated dev package only in the `[dev-packages]` Pipfile list.

##### Actual result

 Updated dev package is kept in the `[dev-packages]` and add too in `[packages]` list.

##### Steps to replicate

> Pipfile
> ...
> [packages]
> requests = "*"
> [dev-packages]
> pytest = "*"

 `$ pipenv update` or `$ pipenv update pytest`

 > Result Pipfile
> ...
> [packages]
> requests = "*"
> pytest = "*"
> [dev-packages]
> pytest = "*"
>

-------------------------------------------------------------------------------

 Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

 If you're on Windows, run the following:
    > pipenv --support | clip

> Error: no such option: --support

#### Environment

- Python version: Python 3.6.5
- Pipenv version: pipenv, version 2018.05.18

**Comment by uranusjr** [comment]
Does this happen with the latest release, 2018.7.1?

**Comment by FlavioCestari** [comment]
No, after **Pipenv** upgrade it was resolved. Thanks.
Sorry for forgetting to do this update, my bad.

**Comment by uranusjr** [comment]
🎈
