### ISSUE TITLE
pipenv install doesn't install the package itself

### ISSUE THREAD

**Issue by Julian** [pypa/pipenv#2569]
There are a ton of issues mentioning `pipenv install`, so this one might already be present, or for some reason intentional, so apologies in advance if so.

##### Issue description

`pipenv install` doesn't actually install the package itself (just its dependencies).

##### Expected result

It should install the package itself as well.

##### Actual result

It doesn't.

##### Steps to replicate

Run `pipenv install`, then `pipenv run python -m pip list`, and the package isn't installed in the virtualenv.

**Comment by uranusjr** [comment]
No Pipfile, no way to answer.

**Comment by Julian** [comment]
.. no way to answer what? That's a pretty swift closing.

**Comment by uranusjr** [comment]
… no way to answer why your package is not installed? Why should it be installed?
