### ISSUE TITLE
Handle conditional install_requires wrongly

### ISSUE THREAD

**Issue by Sraw** [pypa/pipenv#2573]
##### Issue description

Handle conditional `install_requires` wrongly.

Given a `setup.py` snippet:

```
setup(
    ...
    install_requires={
        'futures; python_version == "2.7"'
    }
)
```

`pipenv install package` in Python3 env cannot rightly ignore this requirement but installs `futures==3.1.1` which is the last version for Python3.

pipenv, version 2018.7.1

##### Expected result

`futures` doesn't get installed and listed in `Pipfile.lock` at all.

##### Actual result

`futures==3.1.1` gets installed and listed in `Pipfile.lock`.

##### Steps to replicate

`pipenv install azure-cosmosdb-table` in Python3.

**Comment by uranusjr** [comment]
Unfortunately the wheel distribution of `azure-cosmosdb-table` on PyPI does not specify its `install_requires` like you mentioned. To prove this, [download the wheel from PyPI](https://pypi.org/project/azure-cosmosdb-table/#files), crack it up (it is essentially a ZIP), and look inside `azure_cosmosdb_table-1.0.4.dist-info/METADATA`:

```
Metadata-Version: 2.1
Name: azure-cosmosdb-table
Version: 1.0.4
Summary: Microsoft Azure CosmosDB Table Client Library for Python
Home-page: https://github.com/Azure/azure-cosmosdb-python
Author: Microsoft Corporation
Author-email: ascl@microsoft.com
License: Apache License 2.0
Platform: UNKNOWN
Classifier: Development Status :: 4 - Beta
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 2
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.3
Classifier: Programming Language :: Python :: 3.4
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
Classifier: License :: OSI Approved :: Apache Software License
Requires-Dist: azure-common (>=1.1.5)
Requires-Dist: azure-storage-common (~=1.1)
Requires-Dist: cryptography
Requires-Dist: python-dateutil
Requires-Dist: requests
Requires-Dist: futures
Requires-Dist: azure-cosmosdb-nspkg (>=2.0.0)

[snipped]
```

It specifies `futures` without markers.

Wheels are always preferred to sdists since they provide a more declarative information format, and is much safer to inspect.

Please report this to `azure-cosmosdb-table` for its maintainers to fix. There is little Pipenv can do.

**Comment by Sraw** [comment]
OK, I have confirmed this. Sorry for disturbing you.

**Comment by uranusjr** [comment]
I’m always happy to help out this kind of problems. Hopefully with every issue I find we get one step closer to a perfect Python packaging world 🙂

**Comment by techalchemy** [comment]
In the meantime you can put futures with the marker directly into your pipfile and it will take precedence

**Comment by uda** [comment]
I encountered this issue as well. I tried to install `pytest-sanic==0.1.15`, which requires `aiohttp`, which in turn requires `idna-ssl>=1.0` if python version is less than 3.7.

but, `idna-ssl` was not installed using pipenv. I checked the wheel's `METADATA` it has `Requires-Dist: idna-ssl (>=1.0) ; python_version < "3.7"`.

I have en environment using python 3.6.8, pipenv 2018.11.26.
