### ISSUE TITLE
Pipenv does not pull new ref from git when Pipfile is updated

### ISSUE THREAD

**Issue by arielnmz** [pypa/pipenv#2576]
##### Issue description

I am using a small lib that I pull from git using its tag, this is how the entry looks in the Pipfile:

`my_lib = {git = "ssh://git@bitbucket.org/user/my_lib.git", ref = "v0.2.0"}`

I did some changes and pushed a new tag, so I updated my Pipfile accordingly

`my_lib = {git = "ssh://git@bitbucket.org/user/my_lib.git", ref = "v0.2.1"}`

I then locked dependencies:

`pipenv lock`

This is how the lib entry looks in the Pipenv.lock:

```
"nopal-framework-django": {
    "git": "ssh://git@bitbucket.org/user/my_lib.git",
    "ref": "v0.2.1"
},
```

And sync'ed packages:

`$ pipenv sync`

##### Expected result

I expect the correct tag to be pulled

##### Actual result

As the title suggests the package is not being installed correctly, as the graph shows otherwise:

`$ pipenv graph`

```
my-lib==0.2.0
  - django [required: Any, installed: 2.0.7]
    - pytz [required: Any, installed: 2018.5]
  - djangorestframework [required: Any, installed: 3.8.2]
```

##### Steps to replicate

I tried this on two different environments with the same Pipfile and package

1. Create a new Pipfile
2. Add a git entry
3. Lock and sync
4. Change the ref in the Pipfile
5. Lock and sync again
6. Graph still shows the old package

One way around this is to just remove the package and reinstall it with the desired ref

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

`Error: no such option: --support`

**Comment by erinxocon** [comment]
Hi @arielnmz!  If the `--support` command is not um well supported..that means you have an old version of pipenv!  Can you upgrade your installation of pipenv and see if that fixes your issue?  The currently released version of pipenv is 2018.7.1.  I am going to close this issue.  If you are still experiencing this in the latest version of pipenv open a new issue and paste the output of `pipenv --support`!  Cheers 🌈🍰🌈

**Comment by erinxocon** [comment]
`pip install pipenv --upgrade` or `pip3` depending on your installation.

**Comment by arielnmz** [comment]
It's been a while but I'm back. Im on pipenv version `pipenv, version 2018.7.1` and the problem persists. It only seems to happen when the non-editable flag is enabled.

This is what happens without the editable -e flag:

```
Installing git+ssh://git@bitbucket.org/user/my_lib.git@v0.2.1#egg=my_lib...
Warning: You installed a VCS dependency in non-editable mode. This will work fine, but sub-dependencies will not be resolved by $ pipenv lock.
To enable this sub-dependency functionality, specify that this dependency is editable. 
Requirement already satisfied: my_lib from git+ssh://git@bitbucket.org/user/my_lib.git@v0.2.1#egg=my_lib in /home/user/.local/share/virtualenvs/my-venv-kjsj2d-h/lib/python3.6/site-packages (0.2.0)
```

And this is with the editable flag:

```
Installing -e git+ssh://git@bitbucket.org/user/my_lib.git@v0.2.1#egg=my_lib...
Obtaining my_lib from git+ssh://git@bitbucket.org/user/my_lib.git@v0.2.1#egg=my_lib
Updating /home/user/.local/share/virtualenvs/my-venv-kjsj2d-h/src/my-lib clone (to revision v0.2.1)
```

And I get the correct version this time. Why does a non-editable package detect the dependency as 'already satisfied'?

**Comment by techalchemy** [comment]
non-editable installations don't resolve dependencies at all; it simply takes whatever you  say is the url and installs it using pip.  By default pip won't upgrade a package it has installed already (by name) unless you tell it to upgrade

**Comment by arielnmz** [comment]
@techalchemy Ok, I get that dependencies aren't being resolved for non-editable installations (it even throws I warning to stdout about that) but why? Also, this makes more sense to me:

> By default pip won't upgrade a package it has installed already (by name) unless you tell it to upgrade

If you change the ref. it's clear that you need something different, even the hash in the lockfile changes, isn't that enough information to "know" a package needs to be pulled again? What is the reasoning behind not pulling it when the hash in the lock changes, unless it's editable?
