### ISSUE TITLE
BrokenPipeError when piping `pipenv graph` output to some commands

### ISSUE THREAD

**Issue by xiaket** [pypa/pipenv#2594]
##### Issue description

When I send the output of `pipenv graph` to some other command via a pipe, it will write some exception to stderr.

##### Expected result

```
{~}pipenv graph | head -n 1
somepackage==1.0.248
```
##### Actual result

```
{~}pipenv graph | head -n 1
somepackage==1.0.248
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

I don't believe this is related to my local setup, so I added only the more relevant output of `pipenv --support`:

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/usr/local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.7'`

Other Python installations in `PATH`:

  - `2.6`: `/usr/bin/python2.6`
  - `2.6`: `/usr/bin/python2.6`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.7`: `/usr/local/bin/python3.7m`
  - `3.7`: `/usr/local/bin/python3.7`

  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.15`: `/usr/local/bin/python2`
  - `3.7.0`: `/usr/local/bin/python3`

If this is not the case, I would love to provide the full output.

**Comment by xiaket** [comment]
I think it is related to a bug in Click here: https://github.com/pallets/click/pull/626

It was fixed in 2016 and I believe I'm using the latest version of Click:

```
{~}python3 -c "import click; print(click.__version__)"
6.7
{~}python2 -c "import click; print(click.__version__)"
6.7
```

**Comment by uranusjr** [comment]
I don’t think it is the same error. You might want to report this to Clic :( Please do raise an issue here for us to update if you get any news from the Click team. Thanks!
