### ISSUE TITLE
Where pyc and __pycache__ goes?

### ISSUE THREAD

**Issue by nachopro** [pypa/pipenv#2601]
Hi All! I'm a 2 weeks old pipenv (v2018.7.1) user.

I see that my projects does not have any `.pyc` file (py2.7) nor `__pycache__` folder (py3.7) anymore.
I searched about this "bug" or "feature" but I found nothing about it.

This is a feature of pipenv run / pipenv shell ?

Thank you!

**Comment by techalchemy** [comment]
We disable these at runtime when using pipenv for several reasons, this is neither a bug nor a feature but an intended behavior which prevents bugs.
