### ISSUE TITLE
Consider adding "pipenv outdated" as an alias for "pipenv update --outdated"

### ISSUE THREAD

**Issue by K900** [pypa/pipenv#2624]
Pipenv doesn't support `outdated` as a separate subcommand, making the functionality sort of hard to reach. [Yarn](https://yarnpkg.com/lang/en/docs/cli/outdated/), [npm](https://docs.npmjs.com/cli/outdated), [Composer](https://getcomposer.org/doc/03-cli.md#outdated), [RubyGems](https://guides.rubygems.org/command-reference/#gem-outdated), [Bundler](https://bundler.io/v1.16/bundle_outdated.html) and Cargo (via a [third party plugin](https://github.com/kbknapp/cargo-outdated)) all support `$package_manager outdated` directly. It would be nice for Pipenv to be consistent here, as many people working on full stack projects probably have muscle memory for it (I know I do :) ).

**Comment by techalchemy** [comment]
This is a good suggestion and a good reason. I'll triage it with Kenneth and see what he thinks

**Comment by uranusjr** [comment]
Probably worth considering whether we should keep `update --outdated`, or remove it in favour of `outdated` (maybe through a deprecation cycle).

**Comment by charlax** [comment]
What would be nice too would be to take inspiration from `yarn`'s `outdated` command, which uses a color code (for semver updates) and includes as link to the project (super useful to check the changelog):

```
% yarn outdated
yarn outdated v1.17.3
info Color legend :
 "<red>"    : Major Update backward-incompatible updates
 "<yellow>" : Minor Update backward-compatible features
 "<green>"  : Patch Update backward-compatible bug fixes
Package                Current Wanted Latest Package Type    URL
@babel/core            7.5.0   7.5.4  7.5.4  devDependencies https://babeljs.io/
```

**Comment by matteius** [comment]
Noting here that this issue is rather old at this point, but also there is a recent issue with an open PR that seems to be fulfilling a very similar ask to this by adding an out dated check.  https://github.com/pypa/pipenv/issues/4893

Perhaps we should close this issue and rally behind the open PR?
