### ISSUE TITLE
Should `pipenv install -i` suppress `--pypi_mirror`

### ISSUE THREAD

**Issue by mlouielu** [pypa/pipenv#2636]
##### Issue description

Should `pipenv install -i` suppress `--pypi_mirror`

When using `pip install -i https://foo six` it will suppress default pypi URL
```
➜  p pip install -i https://foo six
Looking in indexes: https://foo
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (1.11.0)
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

But at `pipenv install -i https://foo six`, it will also using pypi_mirror:

```
➜  p pipenv install -i https://foo six
Installing six…
Looking in indexes: https://foo, https://pypi.org/simple
Requirement already satisfied: six in /home/louie/.local/share/virtualenvs/p-iGimN7tB/lib/python3.6/site-packages (1.11.0)

Adding six to Pipfile's [packages]…
Pipfile.lock (3cae52) out of date, updating to (d8ade3)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (d8ade3)!
Installing dependencies from Pipfile.lock (d8ade3)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:00
```
Do this behavior need to changed?

##### Expected result

As pip, or remain the same.

##### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

##### Steps to replicate

```
$ pipenv install -i https://foo six
```

-------------------------------------------------------------------------------

**Comment by uranusjr** [comment]
I would say no, if you want to replace PyPI specifically, use `--pypi-mirror`; if you use `-i`, it adds an additional mirror alongside PyPI. This covers all common use cases.

**Comment by mlouielu** [comment]
So in pipenv, the result of `-i` and `--extra-index-url` should have the same, but `--extra-index-url` allow multiple input, `-i` will only use the last input, right?

**Comment by techalchemy** [comment]
No. Also see #2494. Please don’t open multiple of the same issue (ref: #2637)
