### ISSUE TITLE
Install with index didn't write the index in Pipfile, causing lock failed

### ISSUE THREAD

**Issue by mlouielu** [pypa/pipenv#2638]
##### Issue description

Install with index didn't write the index in Pipfile

Package like `pybase` only exist in testpypi, when install like this:

```
$ pipenv install pybase -i https://test.pypi.org/simple
```

it will not record the index from the URL in Pipfile.

---

Also, when using source name, it will record the wrong index in Pipfile.lock

##### Expected result

Record index in Pipfile, record correct index in Pipfile.lock

##### Actual result

Didn't record index in Pipfile, causing locking failed (when the source isn't inside the Pipfile)
When the source is in Pipfile, Pipfile.lock will record incorrect index.

##### Steps to replicate

1. URL index failed when locking

```
$ pipenv install pybase -i https://test.pypi.org
```

2. Name index causing Pipfile.lock incorrect index

Pipfile
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://test.pypi.org/simple"
verify_ssl = true
name = "testpypi"

[packages]

[dev-packages]

[requires]
python_version = "3.6"
```

lock
```
$ pipenv lock
```

Check Pipfile.lock
```
...
    "default": {
        "pybase": {
            "hashes": [
                "sha256:34b4f89a8"
            ],
            "index": "pypi",
            "version": "==3"
        }
    },
...
```

**Comment by kennethreitz** [comment]
that isn't supposed to work.
