### ISSUE TITLE
pipenv init subcommand

### ISSUE THREAD

**Issue by dankeder** [pypa/pipenv#2642]
##### Is your feature request related to a problem? Please describe.

When I run `pipenv install <somepackage>` in a directory where the Pipfile doesn't exist yet pipenv automatically creates the `Pipfile`. While this is convenient, sometimes I accidentally run it in a wrong directory. After that happens I have to manually remove both Pipenv & Pipenv.lock.

##### Describe the solution you'd like

To prevent the mistakes like the one described above, I propose this:

1. Introduce a pipenv subcommand `init`:

```
pipenv init     # Create the initial Pipfile and/or Pipfile.lock in the current directory
pipenv install <somepackage>     # Install packages as usual
```

2. Modify the subcommand `inistall` so that it doesn't create Pipfile automatically; if the command is issued and Pipfile doesn't exist in the current directory or in one of the parent directories, print a message and exit. The message may contain a hint that the user should first run `pipenv init`.

Also, there are other well-known tools that work in a similar fashion, for example `git` or `vagrant`.

**Comment by uranusjr** [comment]
Duplicate to #426 #2188.

For the record I am in favour of this feature, but as the issue template says, *be sure to check the existing issues*.

**Comment by dankeder** [comment]
Sorry about that, I checked (really) but my search query didn't yield these two issues... I guess I'll try harder next time. Thanks!

**Comment by uranusjr** [comment]
@dankeder Pro tip: GitHub search is terrible, use Google instead :p (use something like _pipenv github <your keywords>_)
