### ISSUE TITLE
Advanced Usage of Pipenv: sys_platform should not be win32

### ISSUE THREAD

**Issue by thernstig** [pypa/pipenv#2654]
##### Issue description

https://docs.pipenv.org/advanced/#specifying-basically-anything describes the following usage to install pywinusb on Windows systems:
```sh
[packages]
requests = "*"
pywinusb = {version = "*", sys_platform = "== 'win32'"}
```

However, the text refers to [PEP 508](https://www.python.org/dev/peps/pep-0508/) which does not have win32 as a sys_platform. According to [PEP 496](https://www.python.org/dev/peps/pep-0496/) it reads:

> After this PEP was initially drafted, PEP 508 was developed and submitted to fully specify the dependency declaration syntax, including environment markers. As a result, this PEP ended up being rejected in favor of the more comprehensive PEP 508.

As such, shouldn't PEP 508 also be used in the code example?

##### Expected result
I expected the code example to read:

```sh
[packages]
requests = "*"
pywinusb = {version = "*", platform_system= "== 'Windows'"}
```

Note that I understand that `sys_platform = "== 'win32'` works, but it was confusing not finding win32 in the PEP 508 documentation.

##### Actual result

n/a

##### Steps to replicate

n/a

**Comment by techalchemy** [comment]
The pep only lists sample values, it is not exhaustive. `sys_platform` is listed and the function call is `sys.platform()` as the pep outlines.
