### ISSUE TITLE
Should I commit pipfile.lock to my Python package repo?

### ISSUE THREAD

**Issue by kwill** [pypa/pipenv#2657]
Note: `https://kenneth-reitz.uservoice.com/forums/913660-general` says "This site is not currently active" and I think this query is too speculative for StackOverflow, so I've posted the query here. (If there's an official answer, then it stops being speculative ;D )

From the (excellent) documentation, the semantics of a pipenv's pipfile is a loosely-versioned list of the dependencies for the package. The pipfile.lock is an environment-specific list of the exact dependencies installed.

So, my hunch is that I *must* commit my pipfile to my package repo (otherwise how will you know what the dependencies are?) but I *must not* commit my pipfile.lock (what if I use GNU/Linux and you use Windows). Is this correct?

**Comment by uranusjr** [comment]
It would be best if you commit Pipfile.lock if you can. Python is a cross-platform language, and the platform difference is not a problem most of the time, if all your dependencies are cross-platform. There are, unfortunately, definitely packages in the wild that does not work well in a cross-platform context, so you don’t _have_ to commit Pipfile.lock—feel free to leave it out if it gives you problems.
