### ISSUE TITLE
Do I still need setup.py for *application* uploads to PyPI?

### ISSUE THREAD

**Issue by kwill** [pypa/pipenv#2658]
Note: `https://kenneth-reitz.uservoice.com/forums/913660-general` says "This site is not currently active" and I think this query is too speculative for StackOverflow, so I've posted the query here. (If there's an official answer, then it stops being speculative ;D )

From the (excellent) documentation, setup.py is really intended for Python libraries, packages that are imported by other packages. Obviously if I am building a Python library and uploading it to PyPI, I must create a `setup.py`. (In addition to my existing `pipfile` as required for `pipenv`.)

If I am building a local application, the documentation explains I don't need `setup.py` -- only `pipfile`.

But what if I am building an application and uploading it to PyPI? For example, so that a user can `pip install --user myapp` and then launch `myapp`. Do I still need `setup.py` in this case, or will the `pip install` succeed with just a `pipfile`?

**Comment by uranusjr** [comment]
If you want to upload to PyPI (i.e. make your code installable with pip), you need to package your application as a library. Pipenv does not care about that, and it’s up to you to handle how you want to do it.

*Also note that you don’t necessarily need a setup.py to package code as a Python library, but that is out of the scope of this conversation, and Pipenv does not care either way.
