### ISSUE TITLE
clonevirtualenv

### ISSUE THREAD

**Issue by apple-han** [pypa/pipenv#2659]
**AVOID POSTING ISSUES UNDER THIS CATEGORY.**

If you're requesting a new feature or leaving feedback, please use this forum instead:

    https://kenneth-reitz.uservoice.com/forums/913660-general

If Pipenv is not functioning as you would like it to, consider filing either a bug report, or a feature request instead.

Please refer to [StackOverflow tag](https://stackoverflow.com/questions/tagged/pipenv) for more information.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip
Collecting clonevirtualenv
  Could not find a version that satisfies the requirement clonevirtualenv (from versions: )
No matching distribution found for clonevirtualenv

why? ThankYou

**Comment by uranusjr** [comment]
Because [clonevirtualenv](https://pypi.org/search/?q=clonevirtualenv) is not a valid package. You’re probably looking for [virtualenv-clone](https://pypi.org/project/virtualenv-clone/).
