### ISSUE TITLE
Issue Resolving Dependencys with graphql-core

### ISSUE THREAD

**Issue by stvnksslr** [pypa/pipenv#2663]
##### Issue description

Issue seems to revolve around resolving dependencys between these three libraries which according to there stated setup.py's should be compatible and install without issue with pip at these versions (i know that doesnt exactly mean there isnt an issue with the packages themselves potentially)

My assumption is something is weird with the graphql-core library and 1.1.0/1.1 is not being picked up correctly for some reason?

Thank you for any time you spend looking into this!

##### Expected result

pipenv install django==1.9 graphql-core==1.1 graphene==1.4 graphene-django==1.3

should lead to the packages 
graphql-core==1.1 
graphene==1.4 
graphene-django==1.3

installing with the expected versions
##### Actual result

`pipenv install`

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches graphql-core<3,==1.1,>=1.1,>=2.1 (from -r /var/folders/91/9f8xmgn15zn1k6sk9wnkhwj40000gn/T/pipenv-3_28mw_m-requirements/pipenv-skbqntbp-constraints.txt (line 3))
Tried: 0.4.9, 0.4.11, 0.4.12, 0.4.12.1, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 0.4.18, 0.5, 0.5.1, 0.5.2, 0.5.3, 1.0, 1.0.1, 1.1, 2.0, 2.0, 2.1, 2.1
Skipped pre-versions: 0.1a0, 0.1a1, 0.1a2, 0.1a3, 0.1a4, 0.4.7b0, 0.4.7b1, 0.4.7b2, 0.5b1, 0.5b2, 0.5b3, 1.0.dev20160814231515, 1.0.dev20160822075425, 1.0.dev20160823054952, 1.0.dev20160909030348, 1.0.dev20160909040033, 1.0.dev20160920065529, 1.2.dev20170724044604, 2.0.dev20170801041408, 2.0.dev20170801041408, 2.0.dev20170801051721, 2.0.dev20170801051721, 2.0.dev20171009101843, 2.0.dev20171009101843, 2.1rc0, 2.1rc0, 2.1rc1, 2.1rc1, 2.1rc2, 2.1rc2, 2.1rc3, 2.1rc3
There are incompatible versions in the resolved dependencies.

####### For reference setup.py's of applicable versions
https://github.com/graphql-python/graphql-core/blob/v1.1.0/setup.py
https://github.com/graphql-python/graphene-django/blob/v1.3/setup.py
https://github.com/graphql-python/graphene/blob/v1.4.0/setup.py

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

1. copy pipfile from below
2. pipenv install

Pipfile
``` 
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "==1.9"
graphql-core = "==1.1"
graphene = "==1.4"
graphene-django = "==1.3"

[dev-packages]

[requires]
python_version = "3.5"
```

pipenv install --skip-lock results
`Pipenv graph`
```
graphene-django==1.3
  - Django [required: >=1.6.0, installed: 1.9]
  - graphene [required: >=1.4, installed: 1.4]
    - graphql-core [required: >=1.1, installed: 1.1]
      - promise [required: >=2.0, installed: 2.1]
        - six [required: Any, installed: 1.11.0]
        - typing [required: Any, installed: 3.6.4]
      - six [required: >=1.10.0, installed: 1.11.0]
    - graphql-relay [required: >=0.4.5, installed: 0.4.5]
      - graphql-core [required: >=0.5.0, installed: 1.1]
        - promise [required: >=2.0, installed: 2.1]
          - six [required: Any, installed: 1.11.0]
          - typing [required: Any, installed: 3.6.4]
        - six [required: >=1.10.0, installed: 1.11.0]
      - promise [required: >=0.4.0, installed: 2.1]
        - six [required: Any, installed: 1.11.0]
        - typing [required: Any, installed: 3.6.4]
      - six [required: >=1.10.0, installed: 1.11.0]
    - promise [required: >=2.0, installed: 2.1]
      - six [required: Any, installed: 1.11.0]
      - typing [required: Any, installed: 3.6.4]
    - six [required: >=1.10.0, installed: 1.11.0]
  - iso8601 [required: Any, installed: 0.1.12]
  - singledispatch [required: >=3.4.0.3, installed: 3.4.0.3]
    - six [required: Any, installed: 1.11.0]
  - six [required: >=1.10.0, installed: 1.11.0]
```

`pip freeze`
```
Django==1.9
graphene==1.4
graphene-django==1.3
graphql-core==1.1
graphql-relay==0.4.5
iso8601==0.1.12
promise==2.1
pytz==2018.5
singledispatch==3.4.0.3
six==1.11.0
typing==3.6.4
```

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.7.1/libexec/bin/python3.7'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/Users/skessler/.virtualenvs/test-3wH9OC5G/bin/python3.5m`
  - `3.5`: `/Users/skessler/.virtualenvs/test-3wH9OC5G/bin/python3.5`
  - `3.5`: `/Users/skessler/.pyenv/shims/python3.5`
  - `3.6`: `/Users/skessler/.pyenv/shims/python3.6`
  - `3.7`: `/usr/local/bin/python3.7m`
  - `3.7`: `/usr/local/bin/python3.7`

  - `3.5.2`: `/Users/skessler/.virtualenvs/test-3wH9OC5G/bin/python`
  - `None`: `/Users/skessler/.pyenv/shims/python`
  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.15`: `/usr/local/bin/python2`
  - `3.5.2`: `/Users/skessler/.virtualenvs/test-3wH9OC5G/bin/python3`
  - `None`: `/Users/skessler/.pyenv/shims/python3`
  - `3.7.0`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT '
                     '2018; root:xnu-4570.71.2~1/RELEASE_X86_64',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `TERM`
  - `SHELL`
  - `PIP_PYTHON_PATH`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `VIRTUAL_ENV`
  - `WORKON_HOME`
  - `PIPENV_ACTIVE`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `PYTHONDONTWRITEBYTECODE`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `PYENV_SHELL`
  - `HOME`
  - `COLORFGBG`
  - `ITERM_SESSION_ID`
  - `LOGNAME`
  - `_OLD_VIRTUAL_PATH`
  - `GOPATH`
  - `COLORTERM`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.7.1/libexec/tools:/Users/skessler/.virtualenvs/test-3wH9OC5G/bin:/usr/local/sbin:/usr/local/opt/libxml2/bin:/usr/local/opt/node@8/bin:/usr/local/Cellar/pipenv/2018.7.1/libexec/tools:/Users/skessler/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet`
  - `SHELL`: `/usr/local/bin/fish`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/skessler/Projects/personal-projects/test`
  - `VIRTUAL_ENV`: `/Users/skessler/.virtualenvs/test-3wH9OC5G`

---------------------------

Contents of `Pipfile` ('/Users/skessler/Projects/personal-projects/test/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "==1.9"
graphql-core = "==1.1"
graphene = "==1.4"
graphene-django = "==1.3"

[dev-packages]

[requires]
python_version = "3.5"

```

Contents of `Pipfile.lock` ('/Users/skessler/Projects/personal-projects/test/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "df91154c60515926ce2aed220ecaa6bc606a754b291bc72a06482e64a7b677fa"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.5"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "django": {
            "hashes": [
                "sha256:05fe4b19a8778d4b48bbf1f4dfca3106881fea7982664553e7f7f861606f7c66",
                "sha256:e66d58bfeed3a5eb44f2af6d5f1b6a85d656c4180ebba63b692e58d29db2a716"
            ],
            "index": "pypi",
            "version": "==1.9"
        }
    },
    "develop": {}
}

```
</details>

**Comment by uranusjr** [comment]
Merging into #2596.
