### ISSUE TITLE
Tab completion / readline broken

### ISSUE THREAD

**Issue by herrmit** [pypa/pipenv#2664]
I am a happy newbie with pipenv but used virtualenv / venv in the past. 

##### Issue description

My pipenv is version 2018.7.1 on a mac with HighSierra. 

Tab completion seems to be broken.

##### Expected result

If I use either Python without a virtualenv or a virtualenv created with `python -m venv`, then the completion  works as expected:

```
>>> p
pass       pow(       print(     property(
```

##### Actual result

After calling `pipenv shell` and `python` at the prompt (>>> ) I enter p<TAB> and the TAB  is inserted literally. No completion :-(

With `import readline` I get:
ImportError: dlopen(/Users/herrmann/.local/share/virtualenvs/temp-pipenv-try-aoQVVn0z/lib/python3.6/readline.so, 2): no suitable image found.

The above mention readline.so is a symbolic link to `/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/readline/readline.py`

##### Steps to replicate

In a new directory install just a virtualenv with  Python 3.6:

$ pipenv install
$ pipenv shell
(...) $ python

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/Volumes/Home+BUP/NeueHeimat/herrmann/Library/Python/3.6/lib/python/site-packages/pipenv'`

Python location: `'/opt/local/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.7`: `/opt/local/bin/python2.7`
  - `2.7`: `/opt/local/bin/python2.7`
  - `2.7`: `/opt/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/opt/local/bin/python3.5m`
  - `3.5`: `/opt/local/bin/python3.5`
  - `3.5`: `/opt/local/bin/python3.5`
  - `3.6`: `/opt/local/bin/python3.6m`
  - `3.6`: `/Volumes/Home+BUP/NeueHeimat/herrmann/.local/share/virtualenvs/temp-pipenv-try-aoQVVn0z/bin/python3.6`
  - `3.6`: `/opt/local/bin/python3.6`
  - `3.6`: `/opt/local/bin/python3.6`

  - `3.6.6`: `/Volumes/Home+BUP/NeueHeimat/herrmann/.local/share/virtualenvs/temp-pipenv-try-aoQVVn0z/bin/python`
  - `3.6.6`: `/opt/local/bin/python`
  - `3.6.6`: `/opt/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.15`: `/opt/local/bin/python2`
  - `2.7.15`: `/opt/local/bin/python2`
  - `3.6.6`: `/Volumes/Home+BUP/NeueHeimat/herrmann/.local/share/virtualenvs/temp-pipenv-try-aoQVVn0z/bin/python3`
  - `3.6.6`: `/opt/local/bin/python3`
  - `3.6.6`: `/opt/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.3.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST '
                     '2017; root:xnu-4570.31.3~1/RELEASE_X86_64',
 'python_full_version': '3.6.6',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `Apple_PubSub_Socket_Render`
  - `COLORFGBG`
  - `COLORTERM`
  - `COMMAND_MODE`
  - `HOME`
  - `ITERM_PROFILE`
  - `ITERM_SESSION_ID`
  - `LANG`
  - `LC_ALL`
  - `LC_CTYPE`
  - `LOGNAME`
  - `LSCOLORS`
  - `PATH`
  - `PIPENV_ACTIVE`
  - `PIP_PYTHON_PATH`
  - `PWD`
  - `PYTHONDONTWRITEBYTECODE`
  - `SECURITYSESSIONID`
  - `SHELL`
  - `SHLVL`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `TMPDIR`
  - `USER`
  - `VIRTUAL_ENV`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `_OLD_FISH_PROMPT_OVERRIDE`
  - `_OLD_VIRTUAL_PATH`
  - `__CF_USER_TEXT_ENCODING`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/Volumes/Home+BUP/NeueHeimat/herrmann/.local/share/virtualenvs/temp-pipenv-try-aoQVVn0z/bin:.:/Volumes/Home+BUP/NeueHeimat/herrmann/Library/Python/3.6/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:.:/Volumes/Home+BUP/NeueHeimat/herrmann/Library/Python/3.6/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
  - `SHELL`: `/opt/local/bin/fish`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Volumes/Home+BUP/NeueHeimat/herrmann/Documents/Mybox/1_Projekte/1_10_swdev/Python-Projekte/temp-pipenv-try`
  - `VIRTUAL_ENV`: `/Volumes/Home+BUP/NeueHeimat/herrmann/.local/share/virtualenvs/temp-pipenv-try-aoQVVn0z`

---------------------------

Contents of `Pipfile` ('/Volumes/Home+BUP/NeueHeimat/herrmann/Documents/Mybox/1_Projekte/1_10_swdev/Python-Projekte/temp-pipenv-try/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/Volumes/Home+BUP/NeueHeimat/herrmann/Documents/Mybox/1_Projekte/1_10_swdev/Python-Projekte/temp-pipenv-try/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "415dfdcb118dd9bdfef17671cb7dcd78dbd69b6ae7d4f39e8b44e71d60ca72e7"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

**Comment by uranusjr** [comment]
Does an environment created by virtualenv work correctly? I am inclined to think this is a problem on virtualenv’s part (Pipenv simply depends on it).

**Comment by herrmit** [comment]
Just tried virtualenv-3.6. And indeed it also does not work :-(

Isn't `python -m venv` recommended over virtualenv ?

**Comment by uranusjr** [comment]
Yes but nobody has yet to successfully implement venv support (and remember we need to support Python 2.7 so dropping virtualenv is not an option).

I’m closing this since the issue really belongs to virtualenv. Also Pipenv actually works with manually created venv environments, you just need to create it yourself at the correct location.

**Comment by herrmit** [comment]
@uranusjr Thanks for your help
