### ISSUE TITLE
Any news on when the next release will be on pypi? (ref. #2514)

### ISSUE THREAD

**Issue by thebjorn** [pypa/pipenv#2669]
I'm just testing out pipenv after watching ActiveState's Managing Dependencies and Runtime Security.

I verified the license and supported versions before watching the rest of the deminar, and saw that your builds are passing and you support 2.7.  

I immediately ran into #2514, which was a bit of a disappointment. The subprocess module doesn't have a `.run()` method except in very new Pythons, so this must mean that you don't really support 2.7 or at the very least that you don't run tests on it (the simplest of travis tests would have caught this, no?)  If you don't intend to support 2.7 you should remove it from your README and setup.py files so other people in my situation don't need to waste so much time.

I'm sure I could try this again with a 3.x version of Python (although that would be a non-starter for our general dev-environment), but these kinds of errors makes it impossible for us to use pipenv in a production setting even if it looks very promising. 

I'm in a very small organization, but even we really do need a commitment to cross platform and cross version support in these kinds of tools. Having a breaking issue on a supported platform for almost a month (with a fix in git for almost as long) sends a pretty clear signal..?

**Comment by uranusjr** [comment]
We do plan to release soon™, but can’t make guarantees because life :)

**Comment by uranusjr** [comment]
Closing since there really is no way to answer this more specifically, and we don’t need an issue to track the release. (There is a [project](https://github.com/pypa/pipenv/projects/7) you can track, however.)
