### ISSUE TITLE
'WindowsPath' object has no attribute 'expanduser'

### ISSUE THREAD

**Issue by Yezhengliang** [pypa/pipenv#2672]
my system is win10, i  cd my project dir and use "pipenv --three",find one error"AttributeError: 'WindowsPath' object has no attribute 'expanduser'",please help me,thank you

**Comment by uranusjr** [comment]
Hi, could you provide a more complete traceback, and fill out the issue template? Debugging with such scarce information is like finding a needle in a haystack. It would help immensely if you provide as comprehensive information as possible.

**Comment by techalchemy** [comment]
Update pipenv and if you still have trouble see if you have pathlib2 installed in your environment (`pip freeze` and check for pathlib2)

If you have pathlib2 and it is older than version 2.3.0 then you can run `pip install --upgrade pathlib2` to update the one in your environment.

Additionally make sure pipenv is up to date.  Also please consider using pipenv with python 3.
