### ISSUE TITLE
guide: add example to install from git branch or tag

### ISSUE THREAD

**Issue by glensc** [pypa/pipenv#2685]
##### Is your feature request related to a problem? Please describe.

https://realpython.com/pipenv-guide/#example-usage

please add here example how to add package from git branch "develop" or tag "1.0.0". it is not obvious for persons who started to use pipenv and not familiar with python ecosystem.

**Comment by techalchemy** [comment]
We don't control that website, unfortunately, but if it's not become clear to you yet you can do this from the command line with `pipenv install -e git+https://github.com/user/repo.git@1.0.0#egg=project_name`

**Comment by glensc** [comment]
appending `@1.0.0` is not self-obvious. that's why example needed.

i tried `&ref=develop`, but eventually just used `vim` on `Pipfile` to specify `ref`.

**Comment by glensc** [comment]
such examples could be present in this project `README.md` as well.

**Comment by akefeli** [comment]
Also it took me a while to figure out you needed to escape & in the url for subdirectory.
This doesn't work:
pipenv install -e git@github.com:some/repo.git#egg=foo&subdirectory=python
This works:
pipenv install -e git@github.com:some/repo.git#egg=foo**\**&subdirectory=python

Is this even documented somewhere?

**Comment by glensc** [comment]
you need to escape `&` for shell. so these are equivalent:

```
pipenv install -e "git@github.com:some/repo.git#egg=foo&subdirectory=python"
pipenv install -e 'git@github.com:some/repo.git#egg=foo&subdirectory=python'
pipenv install -e git@github.com:some/repo.git#egg=foo\&subdirectory=python
```

https://www.tldp.org/LDP/abs/html/special-chars.html

**Comment by akefeli** [comment]
@glensc you are right, for some reason I thought same command was working with pip but not with pipenv, I must be using quotes with pip

**Comment by techalchemy** [comment]
I think we are all set on this front now (merged #2702) -- thanks for opening the issue and thanks for the helpful back and forth all!

**Comment by kushan-gunasekera** [comment]
This is how I solved it,

`pipenv install -e git+https://github.com/some_user/some_package.git#egg=some_package`

**Comment by hivemall** [comment]
How to checkout a tag and install from https://github.com/ccxt/ccxt, yet its a js/php/py repo with python subfolder?

**Comment by coltonbh** [comment]
If you want to install via ssh (say, for a private repo), you'll need to modify the GitHub ssh url as follows:
```
    git@github.com:coltonbh/my-package.git (fetch)
                  ^ change this to a '/' character
```

Correct:
`git@github.com/coltonbh/my-package.git (fetch)`

And the install looks like:

`pipenv install -e "git+ssh://git@github.com/coltonbh/my-package.git@branch123#egg=mypgk"`


Otherwise you'll get a very long install process followed by the cryptic error: 

```pipenv.patched.notpip._internal.exceptions.InstallationError: Command "git clone -q ssh://git@github.com:coltonbh/my-package.git /var/folders/w2/rkn1bm3d3ndclys0f81clbfw0000gn/T/requirementslib5mkvyj4m/mypgk" failed with error code 128 in None
```
