### ISSUE TITLE
Tried to install my fork of Flask-Users, but got .dist-info directory not found

### ISSUE THREAD

**Issue by ferrarijessie** [pypa/pipenv#2686]
Hi!

I've made a translation update to the package Flask-Users on my company fork and when I try to install it with pipenv, this is what I get:

Here's the command I'm using:
```shell
>pipenv install https://github.com/pricez/Flask-User/archive/0.6-pt_BR.zip
```
Here's the pipenv output:
```shell
An error occurred while installing https://github.com/pricez/Flask-User/archive/0.6-pt_BR.zip#egg=e25cbd6! Will try again.
  ================================ 1/1 - 00:00:06
Installing initially failed dependencies...
Collecting e25cbd6 from https://github.com/pricez/Flask-User/archive/0.6-pt_BR.zip#egg=e25cbd6 
Installing collected packages: e25cbd6

Exception:
Traceback (most recent call last):
  File ".venv\lib\site-packages\pip\_internal\basecommand.py", line 141, in main
    status = self.run(options, args)
  File ".venv\lib\site-packages\pip\_internal\commands\install.py", line 347, in run
    use_user_site=options.use_user_site,
  File ".venv\lib\site-packages\pip\_internal\req\__init__.py", line 49, in install_given_reqs
    **kwargs
  File ".venv\lib\site-packages\pip\_internal\req\req_install.py", line 941, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File ".venv\lib\site-packages\pip\_internal\req\req_install.py", line 526, in move_wheel_files
    warn_script_location=warn_script_location,
  File ".venv\lib\site-packages\pip\_internal\wheel.py", line 326, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: e25cbd6 .dist-info directory not found

     ================================ 0/1 - 00:00:06
 ```

But it works fine with pip:

Command:
```shell
>pip install https://github.com/pricez/Flask-User/archive/0.6-pt_BR.zip
```
Output:
```shell
Building wheels for collected packages: Flask-User
  Running setup.py bdist_wheel for Flask-User ... done
  Stored in directory: AppData\Local\pip\Cache\wheels\04\23\57\1f5c7e57b6def3583f0d26b618dfa0514c876f7ace26f02aee
Successfully built Flask-User
```

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'\\AppData\\Roaming\\Python\\Python37\\site-packages\\pipenv'`

Python location: `'c:\\program files\\python37\\python.exe'`

Other Python installations in `PATH`:

  - `3.6`: `C:\Program Files\Python36\python.exe`
  - `3.7`: `C:\Program Files\Python37\python.exe`

  - `3.7.0`: `C:\Program Files\Python37\python.exe`
  - `3.6.6`: `C:\Program Files\Python36\python.exe`
  - `3.7.0`: `C:\Windows\py.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17134',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `USERDOMAIN_ROAMINGPROFILE`
  - `PATH`
  - `LOCALAPPDATA`
  - `PROCESSOR_LEVEL`
  - `USERDOMAIN`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `LOGONSERVER`
  - `PROMPT`
  - `SESSIONNAME`
  - `ALLUSERSPROFILE`
  - `PROCESSOR_ARCHITECTURE`
  - `PSMODULEPATH`
  - `SYSTEMDRIVE`
  - `ASL.LOG`
  - `ONEDRIVE`
  - `APPDATA`
  - `USERNAME`
  - `PROGRAMFILES(X86)`
  - `COMMONPROGRAMFILES`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `PATHEXT`
  - `DRIVERDATA`
  - `OS`
  - `COMPUTERNAME`
  - `PIPENV_VENV_IN_PROJECT`
  - `PROCESSOR_REVISION`
  - `COMMONPROGRAMW6432`
  - `COMSPEC`
  - `PROGRAMDATA`
  - `PROGRAMW6432`
  - `HOMEPATH`
  - `SYSTEMROOT`
  - `TEMP`
  - `HOMEDRIVE`
  - `PROCESSOR_IDENTIFIER`
  - `USERPROFILE`
  - `TMP`
  - `COMMONPROGRAMFILES(X86)`
  - `PROGRAMFILES`
  - `PUBLIC`
  - `NUMBER_OF_PROCESSORS`
  - `VIRTUAL_ENV`
  - `WINDIR`
  - `_OLD_VIRTUAL_PATH`
  - `_OLD_VIRTUAL_PROMPT`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenvûspecific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`

Debugûspecific environment variables:

  - `PATH`: `C:\Program Files\ImageMagick-6.9.10-Q16;C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Users\jscfe\AppData\Roaming\Python\Python37\Scripts;C:\Users\jscfe\AppData\Local\Microsoft\WindowsApps;C:\Users\jscfe\AppData\Roaming\Python\Python37\Scripts;`
  - `VIRTUAL_ENV`: `C:\Users\jscfe\OneDrive\Documents\.venv`

---------------------------

Contents of `Pipfile` ('C:\\Users\\jscfe\\OneDrive\\Documents\\Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"e25cbd6" = {file = "https://github.com/pricez/Flask-User/archive/0.6-pt_BR.zip"}

[dev-packages]

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('C:\\Users\\jscfe\\OneDrive\\Documents\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "753b2bf179dbc4d1edbfd27ed98e0bfdeda2a717a99f8e4c1c64bf7ce49adcd4"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "e25cbd6": {
            "file": "https://github.com/pricez/Flask-User/archive/0.6-pt_BR.zip"
        }
    },
    "develop": {}
}

```
</details>

**Comment by techalchemy** [comment]
I can't replicate this. Can you please fill out the issue template so that we can help you more effectively?

It would also help if you provided the command you are using, not just the output you're seeing

**Comment by ferrarijessie** [comment]
Just edited the issue with the commands I'm using :)

**Comment by techalchemy** [comment]
Ah because you’re installing the zip directly pipenv doesn’t have a good way to know it’s name. Try `pipenv install https://github.com/pricez/Flask-User/archive/0.6-pt_BR.zip#egg=Flask-User` or change the name in your pipfile from `e25cbd6` to `Flask-User`

**Comment by ferrarijessie** [comment]
Yep, tt worked just fine! Thank you very much :)
