### ISSUE TITLE
Can't indicate minimum python version in pipenv file

### ISSUE THREAD

**Issue by thomwiggers** [pypa/pipenv#2694]
I'm trying to indicate the minimum python version in my Pipfile. I've got
```
[requires]
python_version = "3.5"
```
but if you run that on Python 3.6, `pipenv check` will fail. I've tried specifying ` python_version = ">=3.5"`, or `>3.5`, but both also fail.

How do I do this, or am I missing something?

**Comment by techalchemy** [comment]
You can only specify exact versions currently. Delete the whole section if you want it to work on multiple versions, it’s just for pinning.

**Comment by gpakosz** [comment]
Hello @techalchemy 👋

Will you ever reconsider closing this?

**Comment by techalchemy** [comment]
@gpakosz yes I would, reopening

**Comment by alesanchezr** [comment]
IMG Finally! :)

**Comment by gpakosz** [comment]
Hello. I'm a bit lost on what needs to be done to make this issue progress 🤔
What's the next step that would help?

**Comment by blakjak44** [comment]
This feature would be great. Any progress?

**Comment by matteius** [comment]
Link issue:  https://github.com/pypa/pipenv/issues/5195
