### ISSUE TITLE
`pipenv lock` does not use `extra-index-url` from pip.conf

### ISSUE THREAD

**Issue by kuzmiigo** [pypa/pipenv#2695]
I have checked existing issues and could not find this specific problem.

##### Issue description

`pipenv lock` does not seem to use `extra-index-url` from `pip.conf`, so the generated `pip` commands do not include `--extra-index-url` and resolution fails for packages from a private PyPI repo. At the same time, `pipenv install --skip-lock` works fine.

It seems that lock generation and installation of packages work differently in regards to `extra-index-url` setting from `pip.conf`.

##### Expected result

Considering that `pipenv install --skip-lock` uses `extra-index-url` from `pip.conf` and finds packages from a private repo specified there, it is reasonable to expect that `pipenv lock` would do the same and generate the lock file successfully.

##### Actual result

```
$ rm -rf ~/.local/share/virtualenvs/test-* ~/Library/Caches/pip ~/Library/Caches/pipenv
$ pipenv lock -v
Creating a virtualenv for this project...
Pipfile: /Users/igor/dev/test/Pipfile
Using /Users/igor/.pyenv/versions/3.6.6/bin/python3.6m (3.6.6) to create virtualenv...
Running virtualenv with interpreter /Users/igor/.pyenv/versions/3.6.6/bin/python3.6m
Using base prefix '/Users/igor/.pyenv/versions/3.6.6'
New python executable in /Users/igor/.local/share/virtualenvs/test-zhjSazsP/bin/python3.6m
Also creating executable in /Users/igor/.local/share/virtualenvs/test-zhjSazsP/bin/python
Installing setuptools, pip, wheel...done.
Setting project for test-zhjSazsP to /Users/igor/dev/test

Virtualenv location: /Users/igor/.local/share/virtualenvs/test-zhjSazsP
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
using sources: [{'url': 'https://pypi.org/simple', 'verify_ssl': True, 'name': 'pypi'}]
Using pip: -i https://pypi.org/simple

                          ROUND 1
Current constraints:
  clipper-admin (from -r /var/folders/5c/3n6h99cn0fb_1n1s5lm6klj00000gp/T/pipenv-slcmj1td-requirements/pipenv-hop18nyp-constraints.txt (line 2))
  statlib-core (from -r /var/folders/5c/3n6h99cn0fb_1n1s5lm6klj00000gp/T/pipenv-slcmj1td-requirements/pipenv-hop18nyp-constraints.txt (line 3))

Finding the best candidates:
  found candidate clipper-admin==0.3.0 (constraint was <any>)
Using pip: -i https://pypi.org/simple

                          ROUND 1
Current constraints:
  clipper-admin (from -r /var/folders/5c/3n6h99cn0fb_1n1s5lm6klj00000gp/T/pipenv-slcmj1td-requirements/pipenv-jyp_cgb3-constraints.txt (line 2))
  statlib-core (from -r /var/folders/5c/3n6h99cn0fb_1n1s5lm6klj00000gp/T/pipenv-slcmj1td-requirements/pipenv-jyp_cgb3-constraints.txt (line 3))

Finding the best candidates:
  found candidate clipper-admin==0.3.0 (constraint was <any>)

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches statlib-core (from -r /var/folders/5c/3n6h99cn0fb_1n1s5lm6klj00000gp/T/pipenv-slcmj1td-requirements/pipenv-hop18nyp-constraints.txt (line 3))
No versions found
Was https://pypi.org/simple reachable?
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches statlib-core (from -r /var/folders/5c/3n6h99cn0fb_1n1s5lm6klj00000gp/T/pipenv-slcmj1td-requirements/pipenv-jyp_cgb3-constraints.txt (line 3))
No versions found
Was https://pypi.org/simple reachable?
```

##### Steps to replicate

1. Include a dependency (`statlib-core`) from a private repo in `Pipfile` (see below).
2. Add URL to the private repo as `extra-index-url` in `~/.pip/pip.conf` (not shown here as it contains credentials).
3. Clear Pipenv cache (`rm -rf ~/.local/share/virtualenvs/test-* ~/Library/Caches/pip ~/Library/Caches/pipenv`).
4. Run `pipenv lock` or `pipenv install`.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.7.1/libexec/bin/python3.7'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/Users/igor/.pyenv/shims/python3.5`
  - `3.6`: `/Users/igor/.pyenv/shims/python3.6m`
  - `3.6`: `/Users/igor/.pyenv/shims/python3.6`
  - `3.7`: `/usr/local/bin/python3.7m`
  - `3.7`: `/usr/local/bin/python3.7`

  - `3.6.6`: `/Users/igor/.pyenv/shims/python`
  - `2.7.10`: `/usr/bin/python`
  - `3.6.6`: `/Users/igor/.pyenv/shims/python3`
  - `3.7.0`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT '
                     '2018; root:xnu-4570.71.2~1/RELEASE_X86_64',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `__GIT_PROMPT_IGNORE_STASH`
  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `NVM_CD_FLAGS`
  - `SHELL`
  - `TERM`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `__GIT_PROMPT_SHOW_UPSTREAM`
  - `USER`
  - `NVM_DIR`
  - `__GIT_PROMPT_SHOW_UNTRACKED_FILES`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `_`
  - `PWD`
  - `JAVA_HOME`
  - `LANG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `COLORFGBG`
  - `HOME`
  - `SHLVL`
  - `PYENV_SHELL`
  - `__GIT_PROMPT_SHOW_CHANGED_FILES_COUNT`
  - `ITERM_SESSION_ID`
  - `__GIT_PROMPT_IGNORE_SUBMODULES`
  - `LOGNAME`
  - `GOPATH`
  - `NVM_BIN`
  - `COLORTERM`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.7.1/libexec/tools:/Users/igor/.pyenv/shims:/Users/igor/.nvm/versions/node/v8.11.2/bin:/Users/igor/opt/google-cloud-sdk/bin:/Users/igor/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/igor/dev/go/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/igor/dev/test`

---------------------------

Contents of `Pipfile` ('/Users/igor/dev/test/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
clipper-admin = "*"
statlib-core = "*"

[dev-packages]

[requires]
python_version = "3.6"

```

</details>

**Comment by aaj5956** [comment]
Just started with pipenv and pip so I might be doing a newbie mistake.

@techalchemy I have an internal pypi server on which I have hosted a package called `ll-parser`.
I have mentioned the source in my Pipfile as well. `pipenv lock` fails even though the source is mentioned. I am guessing it only looks in the public pypi server.

```
(sample-I-2dLI3V) atharva:sample atharva$ pipenv install ll-parser
Installing ll-parser…
Looking in indexes: https://pypi.org/simple, http://localhost/simple
Collecting ll-parser
Collecting nose (from ll-parser)
  Using cached https://files.pythonhosted.org/packages/15/d8/dd071918c040f50fa1cf80da16423af51ff8ce4a0f2399b7bf8de45ac3d9/nose-1.3.7-py3-none-any.whl
Collecting xtermcolor (from ll-parser)
Collecting pygments (from ll-parser)
  Using cached https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl
Collecting hermes-pygments (from ll-parser)
Collecting moody-templates (from ll-parser)
Installing collected packages: nose, xtermcolor, pygments, hermes-pygments, moody-templates, ll-parser
Successfully installed hermes-pygments-0.1 ll-parser-2.0rc6 moody-templates-0.9.1 nose-1.3.7 pygments-2.2.0 xtermcolor-1.3

Adding ll-parser to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches ll-parser
Tried: 2.0rc6
There are incompatible versions in the resolved dependencies.

/usr/local/lib/python2.7/site-packages/pipenv/_compat.py:86: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/var/folders/ln/grnjhvzj7v5gbpwf81prtpj80000gq/T/pipenv-GSU6a8-requirements'>
  warnings.warn(warn_message, ResourceWarning)
(sample-I-2dLI3V) atharva:sample atharva$
```

My Pipfile:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "http://localhost/simple"
verify_ssl = false
name = "internal"

[dev-packages]
"flake8" = {version="*", index="pypi"}
pylint = {version="*", index="pypi"}
pytest = {version="*", index="pypi"}
pytest-mock = {version="*", index="pypi"}
pytest-env = {version="*", index="pypi"}
pytest-cov = {version="*", index="pypi"}

[packages]
sql-parser = "*"

[requires]
python_version = "3.6"
```

Am I doing something wrong here?
