### ISSUE TITLE
client-cert and cert for private pypi

### ISSUE THREAD

**Issue by zwopir** [pypa/pipenv#2698]
Thanks for the great work!

I'd like to use a private pypi repo as described in  https://docs.pipenv.org/advanced/#specifying-package-indexes. Is there a way to specify a `client-cert` and CA for this pypi repo? The corresponding pip call would be `pip install --cert <path> --client-cert <path> package`.

Is this possible? if not, would you be interested in a PR?

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.7.1/libexec/bin/python3.7'`

Other Python installations in `PATH`:

  - `2.6`: `/usr/bin/python2.6`
  - `2.6`: `/usr/bin/python2.6`
  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m`
  - `3.6`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `2.7.10`: `/usr/bin/python`
  - `3.6.2`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3`
  - `3.6.2`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '16.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT '
                     '2017; root:xnu-3789.70.16~2/RELEASE_X86_64',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `EXTRA_INDEX_URL`
  - `TERM_PROGRAM`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `ZSH`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `PAGER`
  - `LSCOLORS`
  - `_`
  - `K8S_REPO`
  - `PWD`
  - `EDITOR`
  - `LANG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `CFSSL_HOST`
  - `XPC_SERVICE_NAME`
  - `GPG_TTY`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `INDEX_URL`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `LC_CTYPE`
  - `GOPATH`
  - `COLORTERM`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.7.1/libexec/tools:/Users/coelmueller/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/coelmueller/gocode/bin:/Users/coelmueller/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `vim`
  - `LANG`: `de_DE.UTF-8`
  - `PWD`: `/Users/coelmueller/tmp/python_env`

---------------------------

Contents of `Pipfile` ('/Users/coelmueller/tmp/python_env/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/Users/coelmueller/tmp/python_env/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "415dfdcb118dd9bdfef17671cb7dcd78dbd69b6ae7d4f39e8b44e71d60ca72e7"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

**Comment by techalchemy** [comment]
The current way we are handling most pip options is via the environment -- so you can just set `PIP_CERT` and `PIP_CLIENT_CERT` as environment variables and that should take care of it

closing for now but let us know if you have more issues with that -- I don't think we are looking to change the API just now

**Comment by zwopir** [comment]
thanks for your help!

**Comment by umrashrf** [comment]
> The current way we are handling most pip options is via the environment -- so you can just set `PIP_CERT` and `PIP_CLIENT_CERT` as environment variables and that should take care of it
> 
> closing for now but let us know if you have more issues with that -- I don't think we are looking to change the API just now

Why is this not documented at https://docs.pipenv.org/search/?q=PIP_CERT

**Comment by uranusjr** [comment]
@umrashrf Feel free to submit a pull request to add a section.
