### ISSUE TITLE
pipenv shell should have an option to stay in the same directory

### ISSUE THREAD

**Issue by Alexgmin** [pypa/pipenv#2701]
##### Is your feature request related to a problem? Please describe.

In my django projects, the manage.py isn't in the root of the virtualenv, so a common pattern before  I used pipenv was this:
```
cd /project/django
source ../.venv/bin/activate
```
Which meant I stayed in `/project/django`
However, with `pipenv shell`:
```
cd /project/django
pipenv shell
```
The new directory is `/project`

##### Describe the solution you'd like

Either pipenv shell should stay in the same directory after using pipenv shell to enter a virtualenv by default or the command should have an option to indicate this behavior.

##### Describe alternatives you've considered

Changing the project root or just using the `source` command.

**Comment by uranusjr** [comment]
May I also suggest using `run` instead. I’ve always found it fit with my workflow more than `shell`. (Only a suggestion; this is still a valid suggestion and will be reviewed on its own.)

**Comment by techalchemy** [comment]
This has definitely been discussed in the past and the current behavior was intentional, Kenneth was quite adamant.  Closing this one for the moment but I'm sure it will come up again
