### ISSUE TITLE
How to generate a zip file with deps for AWS Lambda

### ISSUE THREAD

**Issue by juank11memphis** [pypa/pipenv#2705]
Hello, 

I have a python project using pipenv and I have several external libraries on it. 

I would like to generate a zip file for uploading to AWS Lambda that contains all the dependencies but I can't find the way to do this? Sorry if this is a dumb question but I am quite new to Python and pipenv.

Thanks.

**Comment by uranusjr** [comment]
Pipenv does not have a vendoring command, and it is unlikely to be added in near future (see #1143). I personally don’t think it fits well in Pipenv either.

Something like this would probably suit your need (modified from https://github.com/pypa/pipenv/issues/1143#issuecomment-352535697):

```
pipenv lock -r > foo.txt
pipenv run pip download -d ./vendor -r foo.txt
pipenv run python -m zipfile -c vendor.zip ./vendor/
```

**Comment by jtratner** [comment]
I currently do this without pip download, in this fashion:

```
mkdir output
pipenv lock -r > requirements.txt
pip install -r requirements.txt --no-deps -t output
zip -r output.zip output
```

Not sure if it'd be in-scope for `pipenv` to support a `-t` flag. It's not that complicated to do this for AWS Lambda :)

**Comment by juank11memphis** [comment]
Hi @uranusjr, @jtratner, Thanks for your help, this is what I needed :) 
Maybe it would just worth to include these in the docs
Thanks

**Comment by YahyaAbraheem** [comment]
I can't install scikit-learn using pipenv install scikit-learn

**Comment by YahyaAbraheem** [comment]
Hello Everyone,

I have an issue with deploying libraries to AWS lambda layer. When I import the libraries from my lambda function, which I wrote manually using an existing role, It says that pandas, numpy, sklearn are not modules or no modules defined in those names.
Unlike how you did it with zipping files, I zipped files using the following commands:
# Creates foo.txt that lists all your dependencies.
pipenv lock -r > foo.txt

# Download libraries into "./vendor".
pipenv run pip download -d ./vendor -r foo.txt

# Archive (with zip) the "./vendor" directory into "vendor.zip".
pipenv run python -m zipfile -c vendor.zip ./vendor/

Then I uploaded the zipped files of libraries wheels (all zipped libraries for numpy, sklearn, etc.) are in .whl format to AWS. Still have the same problem when I try to import it to my lambda function, any suggestion?

**Comment by Lepozepo** [comment]
You'll find improved consistency if you use a docker image to build your dependency layer.

First: `pipenv lock --requirements --keep-outdated > ./python/requirements.txt`
Then: `docker run --rm -v /your/path/to/deps/python/requirements\:/var/task\:z -u 0 lambci/lambda\:build-python3.7 python3.7 -m pip install -t /var/task/ -r /var/task/requirements.txt`

This ensures you use the lambda's environment so that python can do it's funky environment-dependent dependency magic

**Comment by GeekEast** [comment]
AWS has provided the docker approach, you can simply do this in the root of your repo.
```sh
pipenv lock -r >requirements.txt

docker run -v "$PWD":/var/task "lambci/lambda:build-python3.8" /bin/sh -c "pip install -r requirements.txt -t python/lib/python3.8/site-packages/; exit"

zip -r deps.zip python >/dev/null
```
then you can upload deps.zip to lambda either using the aws console or the aws cli.

**Comment by r8or0pz** [comment]
> AWS has provided the docker approach, you can simply do this in the root of your repo.
> 
> ```shell
> pipenv lock -r >requirements.txt
> 
> docker run -v "$PWD":/var/task "lambci/lambda:build-python3.8" /bin/sh -c "pip install -r requirements.txt -t python/lib/python3.8/site-packages/; exit"
> 
> zip -r deps.zip python >/dev/null
> ```
> 
> then you can upload deps.zip to lambda either using the aws console or the aws cli.

It doesn't add lambda function to the archive though

**Comment by iggyzap** [comment]
By the way, code shown above no longer works, since `-r` was removed in favour of `pipenv requirements` subcommand.

There is additional hurdle, if you are using library that transitively references library already included in lambda scope(i.e. botocore) then it still will be install from lockfile.

Full snippet to generate complete `requirements.txt`:
```
pipenv requirements > ./requirements.txt
```
