### ISSUE TITLE
`pipenv update --outdated` transposed info

### ISSUE THREAD

**Issue by mikob** [pypa/pipenv#2711]
##### Issue description
`$ pipenv update --outdated`

Shows transposed installed and what's available. Seems like an easy one to fix, I would like to do the PR if this is confirmed. Thanks.

##### Expected result
```
Package 'lxml' out-of-date: '==4.2.4' available, '==3.5.0' installed.
Package 'requests' out-of-date: '==2.19.1' available, '==2.9.1' installed.
```
##### Actual result
```
Package 'lxml' out-of-date: '==4.2.4' installed, '==3.5.0' available.
Package 'requests' out-of-date: '==2.19.1' installed, '==2.9.1' available.
```

##### Steps to replicate
Pipfile:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
coloredlogs = "==5.0"
argparse = "==1.2.1"
cachetools = "==1.1.6"
dj-database-url = "==0.3.0"
elasticsearch = "==1.6.0"
ijson = "==2.2"
ipaddress = "==1.0.14"
pilkit = "==1.1.13"
"psycopg2" = "==2.6.1"
statsd = "==3.1"
ua-parser = "==0.3.6"
user-agents = "==0.3.2"
ipdb = "==0.10.0"
ipython = "==4.2.0"
lxml = "==3.5.0"
requests = "==2.9.1"
six = "==1.10.0"
"Jinja2" = "==2.8"
Pillow = "==2.9.0"
Scrapy = "==1.5.1"
Twisted = "==15.3.0"
ipython_genutils = "==0.1.0"
SQLAlchemy = "==1.0.13"
"psycopg2cffi" = "*"
"progressbar2" = "*"
cssselect = "*"
cffi = "*"
cryptography = "*"

[requires]
python_version = "2.7"
```

-------------------------------------------------------------------------------

`$ pipenv --support`
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/opt/anaconda3/lib/python3.6/site-packages/pipenv'`

Python location: `'/opt/anaconda3/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/opt/anaconda3/bin/python3.6m`
  - `3.6`: `/opt/anaconda3/bin/python3.6`
  - `3.6`: `/usr/bin/python3.6`
  - `3.6`: `/usr/bin/python3.6`
  - `3.7`: `/home/mikob/.pyenv/shims/python3.7m`
  - `3.7`: `/home/mikob/.pyenv/shims/python3.7`
  - `3.7`: `/home/mikob/.pyenv/shims/python3.7`

  - `3.6.5`: `/opt/anaconda3/bin/python`
  - `2.7.15`: `/usr/bin/python`
  - `3.7.0`: `/home/mikob/.pyenv/shims/python`
  - `3.7.0`: `/home/mikob/.pyenv/shims/python`
  - `2.7.15`: `/usr/bin/python`
  - `2.7.15`: `/usr/bin/python2`
  - `2.7.15`: `/usr/bin/python2`
  - `3.6.5`: `/opt/anaconda3/bin/python3`
  - `3.6.5`: `/usr/bin/python3`
  - `3.7.0`: `/home/mikob/.pyenv/shims/python3`
  - `3.7.0`: `/home/mikob/.pyenv/shims/python3`
  - `3.6.5`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-29-generic',
 'platform_system': 'Linux',
 'platform_version': '#31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `XDG_SEAT_PATH`
  - `XDG_CONFIG_DIRS`
  - `LC_TELEPHONE`
  - `DISPLAY`
  - `SHLVL`
  - `LOGNAME`
  - `LANGUAGE`
  - `MANDATORY_PATH`
  - `LC_NAME`
  - `XDG_VTNR`
  - `USER`
  - `XAUTHORITY`
  - `XDG_GREETER_DATA_DIR`
  - `QT_QPA_PLATFORMTHEME`
  - `GTK_IM_MODULE`
  - `COLORTERM`
  - `XDG_SESSION_ID`
  - `DESKTOP_AUTOSTART_ID`
  - `GNOME_TERMINAL_SCREEN`
  - `DESKTOP_SESSION`
  - `XDG_SESSION_DESKTOP`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `DEFAULTS_PATH`
  - `LC_NUMERIC`
  - `LC_IDENTIFICATION`
  - `LC_PAPER`
  - `LC_MONETARY`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `LC_MEASUREMENT`
  - `VTE_VERSION`
  - `CLUTTER_IM_MODULE`
  - `XDG_DATA_DIRS`
  - `PAPERSIZE`
  - `QT4_IM_MODULE`
  - `GNOME_TERMINAL_SERVICE`
  - `PWD`
  - `GTK_OVERLAY_SCROLLING`
  - `QT_ACCESSIBILITY`
  - `GDM_LANG`
  - `XDG_SESSION_TYPE`
  - `SHELL`
  - `LC_TIME`
  - `TERM`
  - `SESSION_MANAGER`
  - `GTK_MODULES`
  - `SSH_AGENT_PID`
  - `PATH`
  - `SSH_AUTH_SOCK`
  - `HOME`
  - `XDG_CURRENT_DESKTOP`
  - `QT_IM_MODULE`
  - `LC_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XMODIFIERS`
  - `XDG_SEAT`
  - `XDG_SESSION_PATH`
  - `GPG_AGENT_INFO`
  - `OLDPWD`
  - `PYENV_ROOT`
  - `PYENV_SHELL`
  - `NVM_DIR`
  - `NVM_CD_FLAGS`
  - `NVM_BIN`
  - `TMUXIFIER`
  - `WORKON_HOME`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `KEYTIMEOUT`
  - `PKG_CONFIG_PATH`
  - `JAVA_HOME`
  - `EDITOR`
  - `INPUTRC`
  - `DEV_ENV`
  - `NODE_ENV`
  - `FZF_DEFAULT_COMMAND`
  - `MANPATH`
  - `FFX_PROFILE`
  - `DOCKER_IP`
  - `TSOCKS_CONF_FILE`
  - `PYTHONPATH`
  - `PGUSER`
  - `LANG`
  - `LC_ALL`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/opt/anaconda3/bin:/home/mikob/tools/google_appengine/:/usr/bin:/home/mikob/.pyenv/shims:/home/mikob/.pyenv/bin:/home/mikob/.tmuxifier/bin:/home/mikob/.nvm/versions/node/v10.5.0/bin:/home/mikob/.pyenv/shims:/home/mikob/.pyenv/bin:/home/mikob/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/mikob/.rvm/bin:/home/mikob/.zgen/jimeh/tmuxifier-master/bin:/home/mikob/.local/bin:/home/mikob/.fzf/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/mikob`

---------------------------

</details>

**Comment by uranusjr** [comment]
I don’t seem to have the described issue

```
$ pipenv update --outdated
Package 'alabaster' out-of-date: '==0.7.10' installed, '==0.7.11' available.
Package 'black' out-of-date: '==18.6b2' installed, '==18.6b4' available.
Package 'idna' out-of-date: '==2.6' installed, '==2.7' available.
Package 'invoke' out-of-date: '==1.0.0' installed, '==1.1.1' available.
Package 'more-itertools' out-of-date: '==4.2.0' installed, '==4.3.0' available.
Package 'pluggy' out-of-date: '==0.6.0' installed, '==0.7.1' available.
Package 'py' out-of-date: '==1.5.3' installed, '==1.5.4' available.
Package 'pytest' out-of-date: '==3.6.1' installed, '==3.7.1' available.
Package 'pytz' out-of-date: '==2018.4' installed, '==2018.5' available.
Package 'requests' out-of-date: '==2.18.4' installed, '==2.19.1' available.
Package 'Sphinx' out-of-date: '==1.7.5' installed, '==1.7.6' available.
Package 'sphinx-rtd-theme' out-of-date: '==0.4.0' installed, '==0.4.1' available.
Package 'towncrier' out-of-date: '==18.5.0' installed, '==18.6.0' available.
Package 'tqdm' out-of-date: '==4.23.4' installed, '==4.24.0' available.
Package 'urllib3' out-of-date: '==1.22' installed, '==1.23' available.
```

```
$ pipenv run pip list  # partial result.
Package                  Version     Location
------------------------ ----------- -----------------------------------------------------------
alabaster                0.7.10
black                    18.6b2
idna                     2.6
invoke                   1.0.0
more-itertools           4.2.0
pluggy                   0.6.0
py                       1.5.3
pytest                   3.6.1
pytz                     2018.4
requests                 2.18.4
Sphinx                   1.7.5
sphinx-rtd-theme         0.4.0
towncrier                18.5.0
tqdm                     4.23.4
urllib3                  1.22
```

Is this fixed in master, or is there a deeper issue than simply the version output being reversed?

**Comment by mikob** [comment]
@uranusjr I didn't think something so obvious would not have an issue already open for it... hmm I will try running pipenv from master.

**Comment by techalchemy** [comment]
@mikob what was the result of the check? is this actually broken for you still?

**Comment by mikob** [comment]
@techalchemy @uranusjr I can't reproduce the issue. My python environment somehow got in a funky state and blowing away the lock file (among other things?) seems to have solved it. I will close this for now, unlikely I can reproduce it.
