### ISSUE TITLE
pipenv is not usable for projects with production-only dependencies

### ISSUE THREAD

**Issue by maclauss** [pypa/pipenv#2729]
Hi, we're running into some issues that make pipenv (which I really like by the way), unfortunately unusable for us.

The current "dev-packages" and "packages" mechanism, while enough for many simple use cases, does not allow to express dependencies that are only available in production, be it because of system dependencies (e.g. picamera can't be installed on a mac or windows), hardware dependencies (GPU dependencies on a laptop without a GPU), or simply because we do not want that dependency in dev.

I know there are a number of closed issues that relate to this very problem, however I don't think any of them mention packages that are production-only by design. This is a major hurdle and having a separate workflow for production seems to defeat the purpose of a package manager, at least for us.

Any chance a solution might be implemented in the short-term @kennethreitz ?

**Comment by maclauss** [comment]
Thanks @techalchemy for the prompt and very detailed reply.

1. I'll give a try to the markers right away but it assumes the OS is different between prod and dev (which is luckily almost always the case for us). For the GPU issue, I could see this happening with "tensorflow" and "tensorflow-gpu". We're not having this issue at the moment because we need to build tensorflow tailored to the machine anyway (CPU, GPU, CUDA / cuDNN versions, etc...), but I could see that someone who simply wants to use the prebuilt "tensorflow-gpu" on their inference / training machines and "tensorflow" on their laptop could run into these problems. I'm not looking for a specific answer but that could be helpful if someone finds that post.

2. A google search redirected me to solutions that were not satisfying. I have no excuse for not seeing the marker example in this page https://docs.pipenv.org/advanced/#specifying-basically-anything

**Comment by maclauss** [comment]
The marker that worked for me was: `picamera = { version = "*", markers = "platform_system=='Linux'" }`

Closing this ticket, thanks @techalchemy

**Comment by dmillard** [comment]
I am also using tensorflow. Unfortunately, my dev and prod setups both run linux and are separated effectively only by the presence of GPUs. Having read [PEP 508](https://www.python.org/dev/peps/pep-0508/), I don't believe there is enough information in the markers language to distinguish these systems.  Is there some other way that future versions of pipenv can select dependencies? Perhaps through a prod-only section, or similar.

e.g.

```
...
[packages]
foo = "*"

[prod-packages]
tensorflow-gpu = "*"

[dev-packages]
tensorflow = "*"
...
```

where `[prod-packages]` are only installed if `--dev` is missing?
