### ISSUE TITLE
Pipenv updates all packages in Pipenv.lock after installing new package

### ISSUE THREAD

**Issue by vovkd** [pypa/pipenv#2749]
Not sure is it a bug or a feature. So correct me if this is a feature.
I have a Pipfile and Pipfile.lock,  then i do _pipenv install uwsgi_, pipenv installs uwsgi, add it to Pipfile and then updates Pipfile.lock. I expect that only uwsgi wil be added to Pipfile.lock. But pipenv add uwsgi and then updates whole Pipfile.lock, updating all packages to a newer versions. Is it expected behavior? 
This happens on:
pipenv, version 2018.7.1
pipenv, version 9.0.1

**Comment by techalchemy** [comment]
Wow that version of pipenv is quite out of date and quite broken as I recall :) it’s a necessary functionality right now unfortunately, we will be releasing a more sophisticated resolver soon

**Comment by techalchemy** [comment]
To offer a touch more clarification we currently re-resolve deendencies when you install to make sure there are no conflicts. This performs an aggressive upgrade right now as a a side effect as it re-pins the latest versions of everything

**Comment by vovkd** [comment]
I see, thank you So if i install one package pipenv upgrade all installed packages? Damn, and here i thought that i have done something wrong O_O

**Comment by vovkd** [comment]
What if i need install exactly locked dependecies, without updating Pipfile.lock
![image](https://user-images.githubusercontent.com/1261144/44704573-0772a300-aac6-11e8-9748-3a6e61462ff4.png)

**Comment by uranusjr** [comment]
@vovkd `pipenv run pip install foo==version`.

**Comment by vovkd** [comment]
@uranusjr Thank you. Also came to this.
