### ISSUE TITLE
pipenv has matured, please make PIPENV_VENV_IN_PROJECT default to true

### ISSUE THREAD

**Issue by maximveksler** [pypa/pipenv#2759]
`pipenv` is reaching a point where it can set standards.

storage is cheap

Let now make life simple for developers by making it be the default going forward. The eco system could benefit greatly from any encapsulation and standardisation of the `.venv`.

**Comment by techalchemy** [comment]
This decision was made a long time ago and is a matter of preference, we aren't making a major breaking change on a default which is just a preference which is going to wind up causing beginners to accidentally commit python environments to VCS -- there is a reason underlying most decisions and while I do understand it is your preference to keep the environment local, professional development teams are not the only users we have in mind

For the record I think everyone working on pipenv sets this by default, this really is a user-oriented decision -- closing for now
