### ISSUE TITLE
Pipenv does not resolve dependencies between wheels packages provided in Pipfile

### ISSUE THREAD

**Issue by foxlegend** [pypa/pipenv#2771]
Hello,

##### Issue description

When specifying two wheel packages in a Pipfile, where one is a dependency of the other, pipenv does not generate the lock file, and raises a CRITICAL error saying that it could not find a version that satisfies the requirement.

My Pipfile:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
vapi-runtime = {path = "./lib/vapi-runtime/vapi_runtime-2.9.0-py2.py3-none-any.whl"}
vapi-common-client = {path = "./lib/vapi-common-client/vapi_common_client-2.9.0-py2.py3-none-any.whl"}

[dev-packages]

[requires]
python_version = "3.6"
``` 

In this example, `vapi-common-client` requires `vapi-runtime==2.9.0` as subdependency.

##### Expected result

pipenv should  handle dependencies between wheels packages, and let the lock file being created.

##### Actual result

```
pipenv install --verbose                                                                                                                                                                                                 [14:30:31]
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
using sources: [{'url': 'https://pypi.org/simple', 'verify_ssl': True, 'name': 'pypi'}]
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  vapi-common-client==2.9.0 from file:///home/fox/Repositories/GitHub/pipenv-wheels-example/lib/vapi-common-client/vapi_common_client-2.9.0-py2.py3-none-any.whl (from -r /tmp/pipenv-wmz87d5q-requirements/pipenv-rh0mk4rl-constraints.txt (line 3))
  vapi-runtime==2.9.0 from file:///home/fox/Repositories/GitHub/pipenv-wheels-example/lib/vapi-runtime/vapi_runtime-2.9.0-py2.py3-none-any.whl (from -r /tmp/pipenv-wmz87d5q-requirements/pipenv-rh0mk4rl-constraints.txt (line 2))

Finding the best candidates:
  found candidate vapi-common-client==2.9.0 (constraint was ==2.9.0)
  found candidate vapi-runtime==2.9.0 (constraint was ==2.9.0)

Finding secondary dependencies:
  vapi-common-client==2.9.0 not in cache, need to check index
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  vapi-common-client==2.9.0 from file:///home/fox/Repositories/GitHub/pipenv-wheels-example/lib/vapi-common-client/vapi_common_client-2.9.0-py2.py3-none-any.whl (from -r /tmp/pipenv-wmz87d5q-requirements/pipenv-vg4rvh9a-constraints.txt (line 3))
  vapi-runtime==2.9.0 from file:///home/fox/Repositories/GitHub/pipenv-wheels-example/lib/vapi-runtime/vapi_runtime-2.9.0-py2.py3-none-any.whl (from -r /tmp/pipenv-wmz87d5q-requirements/pipenv-vg4rvh9a-constraints.txt (line 2))

Finding the best candidates:
  found candidate vapi-common-client==2.9.0 (constraint was ==2.9.0)
  found candidate vapi-runtime==2.9.0 (constraint was ==2.9.0)

Finding secondary dependencies:
  vapi-runtime==2.9.0       requires asn1crypto>=0.21.0, attrs, automat>=0.3.0, certifi>=2017.4.17, cffi!=1.11.3,>=1.7, chardet<3.1.0,>=3.0.2, constantly>=15.1, cryptography>=2.2.1, hyperlink>=17.1.1, idna<2.8,>=2.5, incremental>=16.10.1, lxml>=3.4.1, pyasn1, pyasn1-modules, pycparser, pyhamcrest>=1.9.0, pyopenssl>=0.15.1, requests>=2.6.0, service-identity>=16.0.0, setuptools, simplejson>=3.6.5, six>=1.9, twisted>=16.0.0, urllib3<1.24,>=1.21.1, vapi-runtime==2.9.0, werkzeug>=0.10.4, zope.interface>=4.4.2
  vapi-common-client==2.9.0 not in cache, need to check index

CRITICAL:notpip._internal.index:Could not find a version that satisfies the requirement vapi-runtime==2.9.0 (from vapi-common-client==2.9.0->-r /tmp/pipenv-wmz87d5q-requirements/pipenv-rh0mk4rl-constraints.txt (line 3)) (from versions: 2.5.0)
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
No matching distribution found for vapi-runtime==2.9.0 (from vapi-common-client==2.9.0->-r /tmp/pipenv-wmz87d5q-requirements/pipenv-rh0mk4rl-constraints.txt (line 3))
CRITICAL:notpip._internal.index:Could not find a version that satisfies the requirement vapi-runtime==2.9.0 (from vapi-common-client==2.9.0->-r /tmp/pipenv-wmz87d5q-requirements/pipenv-vg4rvh9a-constraints.txt (line 3)) (from versions: 2.5.0)
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
No matching distribution found for vapi-runtime==2.9.0 (from vapi-common-client==2.9.0->-r /tmp/pipenv-wmz87d5q-requirements/pipenv-vg4rvh9a-constraints.txt (line 3))
```

##### Steps to replicate

Use `pipenv install` or `pipenv lock` on a Pipfile where a wheel package is dependent of another.

I created a sample repository where this issue occurs: [foxlegend/pipenv-wheels-example](https://github.com/foxlegend/pipenv-wheels-example). You may clone this project and execute a
`pipenv install` command to replicate the problem.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/home/fox/.local/lib64/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `3.6.5`: `/usr/bin/python`
  - `2.7.14`: `/usr/bin/python2`
  - `3.6.5`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.14.12-2',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Thu Jul 19 12:52:41 CEST 2018',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `rvm_version`
  - `RUBY_VERSION`
  - `_system_version`
  - `NO_PROXY`
  - `DISPLAY`
  - `LC_COLLATE`
  - `MANPAGER`
  - `IRBRC`
  - `rvm_path`
  - `COLORTERM`
  - `HTTPS_PROXY`
  - `WORKON_HOME`
  - `LOGNAME`
  - `ANT_HOME`
  - `JDK_HOME`
  - `VISUAL`
  - `JAVA_HOME`
  - `SHELL`
  - `rvm_loaded_flag`
  - `TERMINAL`
  - `PATH`
  - `_system_type`
  - `ftp_proxy`
  - `OPENGL_PROFILE`
  - `rvm_prefix`
  - `GSETTINGS_BACKEND`
  - `rvm_user_install_flag`
  - `MY_RUBY_HOME`
  - `XAUTHORITY`
  - `LESSOPEN`
  - `OLDPWD`
  - `GEM_PATH`
  - `XDG_CONFIG_DIRS`
  - `FTP_PROXY`
  - `_system_arch`
  - `XDG_SESSION_COOKIE`
  - `LESS`
  - `GCC_SPECS`
  - `MAIL`
  - `no_proxy`
  - `https_proxy`
  - `USER`
  - `PWD`
  - `JAVAC`
  - `TERMINATOR_UUID`
  - `CVS_RSH`
  - `VTE_VERSION`
  - `HOME`
  - `CONFIG_PROTECT`
  - `rvm_bin_path`
  - `HTTP_PROXY`
  - `CONFIG_PROTECT_MASK`
  - `XDG_DATA_DIRS`
  - `LANG`
  - `rvm_stored_umask`
  - `SHLVL`
  - `_system_name`
  - `INFOPATH`
  - `GEM_HOME`
  - `EDITOR`
  - `TERM`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `http_proxy`
  - `VIRTUALENVWRAPPER_VIRTUALENV_ARGS`
  - `MANPATH`
  - `PAGER`
  - `LESS_TERMCAP_mb`
  - `LESS_TERMCAP_md`
  - `LESS_TERMCAP_me`
  - `LESS_TERMCAP_se`
  - `LESS_TERMCAP_so`
  - `LESS_TERMCAP_ue`
  - `LESS_TERMCAP_us`
  - `LS_COLORS`
  - `GREP_COLOR`
  - `GREP_COLORS`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `_VIRTUALENVWRAPPER_API`
  - `VIRTUALENVWRAPPER_SCRIPT`
  - `SSH_AUTH_SOCK`
  - `SSH_AGENT_PID`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/fox/.local/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.1:/home/fox/.rvm/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `emacsclient -t`
  - `LANG`: `en_US.utf8`
  - `PWD`: `/home/fox/Repositories/GitHub/pipenv-wheels-example`

---------------------------

Contents of `Pipfile` ('/home/fox/Repositories/GitHub/pipenv-wheels-example/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
vapi-runtime = {path = "./lib/vapi-runtime/vapi_runtime-2.9.0-py2.py3-none-any.whl"}
vapi-common-client = {path = "./lib/vapi-common-client/vapi_common_client-2.9.0-py2.py3-none-any.whl"}

[dev-packages]

[requires]
python_version = "3.6"

```

</details>

**Comment by uranusjr** [comment]
I don’t think this is a setup supported by Python packaging at the current time. See PEP 508 and pypi/pip#5566 for related information and discussion on alternatives.
