### ISSUE TITLE
'InvalidMarker' is not defined.

### ISSUE THREAD

**Issue by PetterS** [pypa/pipenv#2772]
https://github.com/pypa/pipenv/blob/master/pipenv/vendor/requirementslib/models/utils.py#L150 
On this line, InvalidMarker is not defined.

This results in bad error messages for invalid Pipenv files.

```
File "d:\python37\lib\site-packages\pipenv\vendor\requirementslib\models\utils.py", line 140, in validate_specifiers
    except (InvalidMarker, InvalidSpecifier):
NameError: name 'InvalidMarker' is not defined
```

**Comment by reinout** [comment]
I clicked your link and noticed there have been some changes to that file in the last few days. In any case, `InvalidMarker` is now imported, so I assume the next release will fix your problem.

See https://github.com/pypa/pipenv/blob/master/pipenv/vendor/requirementslib/models/utils.py#L15

**Comment by PetterS** [comment]
Yes, commit https://github.com/pypa/pipenv/commit/b626a111502e73d34b4bef022d439a9061eaa7a7 fixed it.

**Comment by uranusjr** [comment]
One advantage of using calendar-based versioning is we can clearly see whether a version contains a particular issue. This is reported in August, so yes, 2018.07.01 (released on month 7 i.e. July) is affected.

**Comment by dccrazyboy** [comment]
Is there a schedule for a new release?The current version(2018.07.01) is still unavailable on my MAC installed by brew. Or is there some way to solve this problem through brew?
