### ISSUE TITLE
pipenv discovers mystery dependency that pip does not (for ruamel.yaml)

### ISSUE THREAD

**Issue by davidfstr** [pypa/pipenv#2779]
##### Issue description

If I run `pip3 install ruamel.yaml==0.10.11` (A) in a clean virtual environment, it installs successfully, pulling in its one additional dependency `ruamel.base` (B).

If I do the similar `pipenv install ruamel.yaml==0.10.11` (A) in an empty directory, it generates a Pipfile.lock with both the expected `ruamel.base` (B) dependency but also an unexpected `ruamel.ordereddict` (C), and attempts to install all 3.

I don't know why pipenv has decided to attempt to install `ruamel.ordereddict` (C). It does not show up in pipenv's computed graph:

```
$ pipenv graph
ruamel.yaml==0.10.11
  - ruamel.base [required: >=1.0.0, installed: 1.0.0]
```

Unfortunately the install of the mystery `ruamel.ordereddict` (C) fails, so I am unable to migrate ruamel.yaml==0.10.11 (A) from my requirements.txt setup to a new pipenv setup.

##### Expected result

The command `pip3 install ruamel.yaml==0.10.11` should generate a Pipenv.lock file containing only the 2 packages {ruamel.yaml, ruamel.base} and attempt to install them.

##### Actual result

The command `pip3 install ruamel.yaml==0.10.11` actually generates a Pipenv.lock file containing the 3 packages {ruamel.yaml, ruamel.base, ruamel.ordereddict} and attempts to install them.

If I look at the [output of `pipenv lock --verbose`](https://gist.github.com/davidfstr/8e1636aa3e7e000294652439dc74c8b3) I notice that pipenv thinks that `ruamel.yaml` (A) depends directly on `ruamel.ordereddict` (C). Strange.

##### Steps to replicate

* Install the latest pipenv, currently 2018.7.1.
* Create the following Pipfile in an empty directory.

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"ruamel.yaml" = "==0.10.11"

[dev-packages]

[requires]
python_version = "3.6"
```

* Run command `pipenv lock`. Notice that the Pipfile.lock it generates has the 3 packages mentioned instead of the expected 2.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv'`

Python location: `'/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.7`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7`
  - `2.7`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.4`: `/Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4m`
  - `3.4`: `/Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4`
  - `3.4`: `/usr/local/bin/python3.4`
  - `3.4`: `/Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4`
  - `3.4`: `/usr/local/bin/python3.4`
  - `3.6`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m`
  - `3.6`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.7`: `/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m`
  - `3.7`: `/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7`
  - `3.7`: `/usr/local/bin/python3.7`
  - `3.7`: `/usr/local/bin/python3.7`

  - `2.7.1`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.1`: `/Users/davidf/bin/python2`
  - `2.7.1`: `/Users/davidf/bin/python2`
  - `3.7.0`: `/Library/Frameworks/Python.framework/Versions/3.7/bin/python3`
  - `3.6.4`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3`
  - `3.4.4`: `/Library/Frameworks/Python.framework/Versions/3.4/bin/python3`
  - `3.7.0`: `/usr/local/bin/python3`
  - `3.4.4`: `/Library/Frameworks/Python.framework/Versions/3.4/bin/python3`
  - `3.7.0`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST '
                     '2018; root:xnu-4570.51.1~1/RELEASE_X86_64',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `CAML_LD_LIBRARY_PATH`
  - `MANPATH`
  - `rvm_bin_path`
  - `TERM_PROGRAM`
  - `GEM_HOME`
  - `SHELL`
  - `TERM`
  - `IRBRC`
  - `TMPDIR`
  - `PERL5LIB`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `SELENIUM_SERVER_JAR`
  - `OLDPWD`
  - `MY_RUBY_HOME`
  - `TERM_SESSION_ID`
  - `OCAML_TOPLEVEL_PATH`
  - `GIT_EDITOR`
  - `USER`
  - `_system_type`
  - `rvm_path`
  - `SSH_AUTH_SOCK`
  - `OPAMUTF8MSGS`
  - `rvm_prefix`
  - `PATH`
  - `PWD`
  - `JAVA_HOME`
  - `LANG`
  - `_system_arch`
  - `XPC_FLAGS`
  - `_system_version`
  - `XPC_SERVICE_NAME`
  - `rvm_version`
  - `SHLVL`
  - `HOME`
  - `PYTHONPATH`
  - `LOGNAME`
  - `GEM_PATH`
  - `CLASSPATH`
  - `PROMPT_COMMAND`
  - `DISPLAY`
  - `RUBY_VERSION`
  - `SECURITYSESSIONID`
  - `_system_name`
  - `GATLING_HOME`
  - `_`
  - `__CF_USER_TEXT_ENCODING`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/davidf/.cargo/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/sbin:/usr/local/bin:/Users/davidf/.opam/system/bin:/Users/davidf/.rvm/gems/ruby-2.3.0/bin:/Users/davidf/.rvm/gems/ruby-2.3.0@global/bin:/Users/davidf/.rvm/rubies/ruby-2.3.0/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/heroku/bin:/Users/davidf/Library/Haskell/bin:/opt/gcc-4.4.0-mingw32/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/bin:/sbin:/usr/bin:/usr/local/bin:/usr/sbin:/Users/davidf/bin:/Users/davidf/.dotfiles/bin:/Users/davidf/bin:/lib/apache-ant-1.6.5/bin:/Users/davidf/pkgs/gwt-mac-1.5M2:/opt/local/bin:/Applications/Doxygen.app/Contents/Resources:/Users/davidf/pkgs/scala-2.7.7.final/bin:/Users/davidf/pkgs/fmscripts-20100225:/Users/davidf/pkgs/valgrind-3.5.0/inst64/bin:/Users/davidf/pkgs/mongodb-osx-x86_64-1.8.3/bin:/Users/davidf/pkgs/hadoop-0.20.203.0/bin:/Users/davidf/pkgs/redis-2.4.4/src:/Users/davidf/Projects/Classic Package Manager/PUBLIC:/Users/davidf/Projects/Classic Package Manager/PUBLIC/tools/hfsutils-3.2.6:/Users/davidf/Projects/Classic Package Manager/PUBLIC/tools/unar1.3:/Users/davidf/pkgs/ffmpeg:/Users/davidf/bin/renameregex:/Users/davidf/Library/Haskell/ghc-7.6.3/lib/Elm-0.10.1/bin:/Users/davidf/Library/Haskell/ghc-7.6.3/lib/elm-server-0.10.1/bin:/Users/davidf/.rvm/bin:/usr/local/go/bin:/Users/davidf/bin/s3cmd:/Users/davidf/pkgs/apache-maven-3.5.0/bin:/Users/davidf/pkgs/phantomjs-2.1.1-macosx/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/davidf/Projects/pipenv-dependency-debug`

---------------------------

Contents of `Pipfile` ('/Users/davidf/Projects/pipenv-dependency-debug/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"ruamel.yaml" = "==0.10.11"

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/Users/davidf/Projects/pipenv-dependency-debug/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "e9274aa0076371dbd518e4f97ac601de0e621600c80ae80e8c4b95299a78f8b5"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "ruamel.base": {
            "hashes": [
                "sha256:3613a90afcf0735540804af2a693f630a0bccebefec9b4023a39e88950bb294e",
                "sha256:c041333a0f0f00cd6593eb36aa83abb1a9e7544e83ba7a42aa7ac7476cee5cf3",
                "sha256:ff7fe471b3d715fe4f2c4663d9e6d82efbeb3cea8e72accb99fd4fa90df7e5f9"
            ],
            "version": "==1.0.0"
        },
        "ruamel.ordereddict": {
            "hashes": [
                "sha256:08b4b19fe518d32251a5338e039c4dc9eb0876f2919f94c9b8d2f9446ea80806",
                "sha256:150ce8e6c514a2a2b62753622a75874962561f8e5eeec81a3172ab952807bf0b",
                "sha256:45541836cbfdde630033cae7bbbe35acbac87a0ceec79f944b7a3bedd940fe78",
                "sha256:854dd4a524811b16111b1107d8a751e4ca064d2bb103d3d91deab75de36b6620",
                "sha256:aee2fa23e884249b4284b728888c553d551e5bfd4de2731f10153fd7813ec55f",
                "sha256:bf0a198c8ce5d973c24e5dba12d3abc254996788ca6ad8448eabc6aa710db149"
            ],
            "version": "==0.4.13"
        },
        "ruamel.yaml": {
            "hashes": [
                "sha256:0f0a826ecc1d93282baeacf3c02627016932d5bd27e4af93dc328f665266d46c",
                "sha256:46b1cf966c87fca4c67d5c441ff5c9bd28510e551097d6ae083ef04b6e160dc0",
                "sha256:5b723f79b8042d73b86f94be8560477b868d1bdcc90a780b3744412d01817242",
                "sha256:5e32a36eaf1f9a3ce620209fe82bb8d78ac687ae015bbb7085b8e51874cb789b",
                "sha256:d27f8e9db46d10c40c3ee939d0ec6e316067e7516fde78bf55fd772e15efa683",
                "sha256:d29eb8132f8011f0b279bf248a6a51261ca2ad601579faa849680b0b7d29153f",
                "sha256:da2278c945d2fe68ac56301cb4d0b4fcca3d178fce29003894cabd49436032e1",
                "sha256:da642f5e8c932db3e3a1ba54a1b6f7f20d1ddaac01936fdc200ae74cb1d51791",
                "sha256:f707596a9a83545c93f6930927dc6d6305842af8ad17d0eaaa79b213d78c9773"
            ],
            "index": "pypi",
            "version": "==0.10.11"
        }
    },
    "develop": {}
}

```
</details>

**Comment by kennethreitz** [comment]
this is intentional.

**Comment by davidfstr** [comment]
Thank you for the explanation @uranusjr .

So it is valid that `pipenv install X==Y` and `pip3 install X==Y` could install different sets of packages for the same X and Y?

**Comment by uranusjr** [comment]
Essentially, yes. A lot of problems in Pipenv ultimately boil down to the (under-realised) fact that pip does not resolve dependencies as well as many tend to believe (including most maintainers before we dug deep into the topic). Pipenv’s current resolution logic is far from perfect, of course (it installing colorama is obvious a problem—it does not make sense to do so), but it is a process of we trying to amend pip’s resolution issues. Hopefully we’re getting there closer every day, and would eventually reach the goal.
