### ISSUE TITLE
export requirement packages with source tar.gz

### ISSUE THREAD

**Issue by mapleflow** [pypa/pipenv#2782]
hello, in development environment network is available, but many production environment offline. I want export all requirements to directory `packages` include like `requests-2.19.1.tar.gz`, so i can `python setup.py install` in any case.

**Comment by uranusjr** [comment]
Requirement export is available with `pipenv lock -r`. Once you have a requirements.txt, `pip download` can be used to download the packages.

See also: https://stackoverflow.com/questions/46185726

**Comment by mapleflow** [comment]
thanks.
