### ISSUE TITLE
vim command :!python main.py doesn't run on virtual environment

### ISSUE THREAD

**Issue by ab12gu** [pypa/pipenv#2789]
Sorry if this inconsistent with other complaints (this is my first gihub comment/question/request). Using python execution directly from vim :!python3, the execution occurs outside the virtual environment.

I noticed this because it didn't give me "no module installed" error. I got the "no module installed" error using :term.

**Comment by uranusjr** [comment]
What is the command you used to run vim? It is not possible to understand the problem you have with the current (scarce) information available. Please provide a way for the maintainers to reproduce the behaviour from a clean environment.

I suspect this is the same problem as #2747.

**Comment by frostming** [comment]
No new updates, close this now, feel free to reopen when you get more information about the bug.
