### ISSUE TITLE
Indeterminate order generates unneccessary diffs in Pipfile.lock when upgrading.

### ISSUE THREAD

**Issue by PetterS** [pypa/pipenv#2799]
My `Pipfile.lock` contains many lines of the following form:

    "markers": "python_version != '3.2.*' and python_version != '3.0.*' and python_version != '3.1.*' and python_version >= '2.7' and python_version != '3.3.*'",

and after an unrelated change, this line is changed into

    "markers": "python_version != '3.0.*' and python_version != '3.2.*' and python_version != '3.3.*' and python_version != '3.1.*' and python_version >= '2.7'",

i.e. the same content but different order. It would be great to keep the order deterministic in order to keep the diffs small when updating.

**Comment by uranusjr** [comment]
This is essentially #2760. Closing in favour of that since it came first, and has a more descriptive title.
