### ISSUE TITLE
pipenv run and pipenv shell do not exit properly in Windows gitbash 2.14.2 (which is based on mintty 2.7.9)

### ISSUE THREAD

**Issue by srse** [pypa/pipenv#2803]
I checked:
- [ x ] existing open and closed issues for duplicates and found no duplicates or similar issues
- [ x ] checked https://docs.pipenv.org/diagnose for common, similar issues before posting and found no similar issues

##### Issue description

in Windows gitbash: 
running pipenv shell
starting a python app inside pipenv shell (I used a simple http app) 
terminating the app with Crtl + C
typing exit + return to exit pipenv shell
>> results in a zombie python process

in Windows gitbash: 
running pipenv run python myapp (I used a simple http app) 
terminating the app and the pipenv run together with Crtl + C
>> results in a zombie python process

performing the same two workflows in a normal windows cmd:
>> does not result in a zombie python process

performed the same two workflows with a different simple python flask app generates the exact same result/ behaviour - so, I the problem is probably not what python app is run, but from which shell (gitbash or win cmd). 

##### Expected result

pipenv running in gitbash to not miss to quit python processes, which it started

##### Actual result

see Issue description

##### Steps to replicate

see Issue description

`$ pipenv --support` output:

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'C:\\Users\\user1\\AppData\\Roaming\\Python\\Python37\\site-packages\\pipenv'`

Python location: `'c:\\tools\\python\\python-3.7\\python.exe'`

Other Python installations in `PATH`:

  - `3.7`: `C:\tools\python\python-3.7\python.exe`

  - `3.7.0`: `C:\tools\python\python-3.7\python.exe`
  - `3.7.0`: `C:\Users\user1\AppData\Local\Programs\Python\Launcher\py.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '7',
 'platform_system': 'Windows',
 'platform_version': '6.1.7601',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ACLOCAL_PATH`
  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `CLICKSHARE_CAPTUREMOREBYDEFAULT`
  - `COMMONPROGRAMFILES`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `CONFIG_SITE`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `DISPLAY`
  - `EXEPATH`
  - `EMPIRUMSERVER`
  - `EMPIRUMSERVICEPARTITION`
  - `FP_NO_HOST_CHECK`
  - `HOME`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `HOSTNAME`
  - `INFOPATH`
  - `LANG`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `MANPATH`
  - `MINGW_CHOST`
  - `MINGW_PACKAGE_PREFIX`
  - `MINGW_PREFIX`
  - `MSYSTEM`
  - `MSYSTEM_CARCH`
  - `MSYSTEM_CHOST`
  - `MSYSTEM_PREFIX`
  - `NUMBER_OF_PROCESSORS`
  - `OLDPWD`
  - `ORIGINAL_PATH`
  - `ORIGINAL_TEMP`
  - `ORIGINAL_TMP`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PKG_CONFIG_PATH`
  - `PLINK_PROTOCOL`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMFILES`
  - `PS1`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `PWD`
  - `PROGRAMDATA`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `SESSIONNAME`
  - `SHELL`
  - `SHLVL`
  - `SNC_LIB`
  - `SSH_ASKPASS`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TERM`
  - `TMP`
  - `TMPDIR`
  - `TNS_ADMIN`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VBOX_MSI_INSTALL_PATH`
  - `WINDIR`
  - `_`
  - `WINDOWS_TRACING_FLAGS`
  - `WINDOWS_TRACING_LOGFILE`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv▒specific environment variables:

Debug▒specific environment variables:

  - `PATH`: `C:\tools\python\python-3.7\;\\c\tools\python\python-3.7\Scripts;C:\Users\user1\AppData\Roaming\Python\Python37\Scripts\;C:\Users\user1\bin;C:\Users\user1\AppData\Local\Programs\Git\mingw64\bin;C:\Users\user1\AppData\Local\Programs\Git\usr\local\bin;C:\Users\user1\AppData\Local\Programs\Git\usr\bin;C:\Users\user1\AppData\Local\Programs\Git\usr\bin;C:\Users\user1\AppData\Local\Programs\Git\mingw64\bin;C:\Users\user1\AppData\Local\Programs\Git\usr\bin;C:\Users\user1\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\SysWOW64\Empirum;C:\Users\user1\AppData\Local\Programs\Python\Launcher;C:\Users\user1\AppData\Local\Google\Chrome\Application;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\SysWOW64\Empirum;C:\Users\user1\AppData\Local\atom\bin;C:\Users\user1\AppData\Local\Programs\Git\cmd;C:\Users\user1\selenium;C:\Program Files (x86)\Google\Chrome\Application;C:\Users\user1\AppData\Local\Programs\Git\usr\bin\vendor_perl;C:\Users\user1\AppData\Local\Programs\Git\usr\bin\core_perl`
  - `SHELL`: `C:\Users\user1\AppData\Local\Programs\Git\usr\bin\bash.exe`
  - `LANG`: `de_DE.UTF-8`
  - `PWD`: `C:/tools/automation/testonik`

---------------------------

Contents of `Pipfile` ('C:\\tools\\automation\\testonik\\Pipfile'):

```toml
[[source]]

url = "http://nexus.es.biotronik.int:8181/nexus/repository/pypi.python.org/simple"
verify_ssl = false
name = "pypi"


[packages]

flask = "*"
gitpython = "*"


[dev-packages]



[requires]

python_version = "3.7"

```

Contents of `Pipfile.lock` ('C:\\tools\\automation\\testonik\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "840b8f1a9447bb37e29470aba0e8c03d2d1467ac5a0236294a3e1d0fae4e8e8f"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "http://nexus.es.biotronik.int:8181/nexus/repository/pypi.python.org/simple",
                "verify_ssl": false
            }
        ]
    },
    "default": {
        "click": {
            "hashes": [
                "sha256:29f99fc6125fbc931b758dc053b3114e55c77a6e4c6c3a2674a2dc986016381d",
                "sha256:f15516df478d5a56180fbf80e68f206010e6d160fc39fa508b65e035fd75130b"
            ],
            "version": "==6.7"
        },
        "flask": {
            "hashes": [
                "sha256:2271c0070dbcb5275fad4a82e29f23ab92682dc45f9dfbc22c02ba9b9322ce48",
                "sha256:a080b744b7e345ccfcbc77954861cb05b3c63786e93f2b3875e0913d44b43f05"
            ],
            "index": "pypi",
            "version": "==1.0.2"
        },
        "gitdb2": {
            "hashes": [
                "sha256:87783b7f4a8f6b71c7fe81d32179b3c8781c1a7d6fa0c69bff2f315b00aff4f8",
                "sha256:bb4c85b8a58531c51373c89f92163b92f30f81369605a67cd52d1fc21246c044"
            ],
            "version": "==2.0.4"
        },
        "gitpython": {
            "hashes": [
                "sha256:563221e5a44369c6b79172f455584c9ebbb122a13368cc82cb4b5addff788f82",
                "sha256:8237dc5bfd6f1366abeee5624111b9d6879393d84745a507de0fda86043b65a8"
            ],
            "index": "pypi",
            "version": "==2.1.11"
        },
        "itsdangerous": {
            "hashes": [
                "sha256:cbb3fcf8d3e33df861709ecaf89d9e6629cff0a217bc2848f1b41cd30d360519"
            ],
            "version": "==0.24"
        },
        "jinja2": {
            "hashes": [
                "sha256:74c935a1b8bb9a3947c50a54766a969d4846290e1e788ea44c1392163723c3bd",
                "sha256:f84be1bb0040caca4cea721fcbbbbd61f9be9464ca236387158b0feea01914a4"
            ],
            "version": "==2.10"
        },
        "markupsafe": {
            "hashes": [
                "sha256:a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665"
            ],
            "version": "==1.0"
        },
        "smmap2": {
            "hashes": [
                "sha256:0dd53d991af487f9b22774fa89451358da3607c02b9b886a54736c6a313ece0b",
                "sha256:dc216005e529d57007ace27048eb336dcecb7fc413cfb3b2f402bb25972b69c6"
            ],
            "version": "==2.0.4"
        },
        "werkzeug": {
            "hashes": [
                "sha256:c3fd7a7d41976d9f44db327260e263132466836cef6f91512889ed60ad26557c",
                "sha256:d5da73735293558eb1651ee2fddc4d0dedcfa06538b8813a2e20011583c9e49b"
            ],
            "version": "==0.14.1"
        }
    },
    "develop": {}
}

```
</details>

**Comment by uranusjr** [comment]
Unfortunately this is a MinTTY big, and there is nothing we can do. You’ll need to upgrade Got for Windows (or at least MinTTY? I’m not vey familiar with Git for Windows.)

See also https://github.com/git-for-windows/git/issues/1219

**Comment by srse** [comment]
@uranusjr thanks for the pointer! for others for future reference: upgrading to Git for Windows 2.18 solved the issue.
