### ISSUE TITLE
Deployment to pypi?

### ISSUE THREAD

**Issue by b3ross** [pypa/pipenv#2805]
Sorry for the possibly stupid question, but is there a supported workflow in pipenv for deploying a package to a pypi repository?  I'm surprised I couldn't find any documentation on this but perhaps I'm missing something.  This is a typical workflow in other package managers (maven, yarn, etc...).  What's the correct way to do this?

**Comment by b3ross** [comment]
Found the way to do things here:  https://realpython.com/pipenv-guide/#yes-i-need-to-distribute-my-code-as-a-package

Would be great if there was an opinionated `pipenv deploy` command that deployed things to a package repo.

**Comment by gsemet** [comment]
I usually does
```python
pipenv run python setup.py sdist bdist bdist_wheel
twine upload dist/*
```

**Comment by b3ross** [comment]
@gsemet the whole point is that I want to avoid having a `setup.py` file... but thanks.

**Comment by gsemet** [comment]
sadly you cannot skip this part. You can look at pyproject.toml and alike. I personnally use [PBR](https://docs.openstack.org/pbr/latest/). See this ticket #1851

**Comment by Owez** [comment]
I feel this should be reopened as poetry has a mechanism to deploy and seems to be the only real missing feature of pipenv in my eyes

**Comment by frostming** [comment]
Pipenv and Pipfile are never to define the dependencies of a library, it can't play the role of `setup.py`
https://pipenv.pypa.io/en/latest/advanced/#pipfile-vs-setuppy
