### ISSUE TITLE
Documentation for major version locking

### ISSUE THREAD

**Issue by trondhindenes** [pypa/pipenv#2816]
We're trying to figure out a way to lock packages using major/minor versions.

I've tried multiple formats, but the documentation doesn't really go into detail on how to lock versions, and more specifically lock major versions of a package. It would be awesome to see a topic on this in the documentation.

**Comment by uranusjr** [comment]
Pipenv uses the same specifier format as pip; it is outlined in [PEP 440](https://www.python.org/dev/peps/pep-0440/#version-specifiers). Contribution on bridging the gap between Pipenv’s documentation and this standard document is very much welcomed.

**Comment by trallard** [comment]
Hi @uranusjr I just created a PR on this, let me know if you find this suitable

**Comment by trondhindenes** [comment]
Thanks @trallard, sorry I should have specified better:
We're looking to version-lock existing packages, which means that we're trying to figure out the toml format and the available options. Essentially we're looking for the easiest way to change a package from '=*' to a locked major-version.

**Comment by trallard** [comment]
@trondhindenes I think if you use `pipenv update <package>` should allow you to update a package version 
Similarly `--selective-upgrade` should do and then pin the version on both your Pipfile and Profile.lock (I might need to do some digging around to provide more accurate feedback) 

On the other hand the PR tackles the point raised by @uranusjr of bridging the gap in the docs (perhaps I should have opened a new issue for this)

**Comment by trallard** [comment]
hey @trondhindenes I just checked this over,  even if you already have a given package installed you can use `pipenv install "package~=x.y.*`  or (`==` although this will definitely prevent you from getting any updates) 

This will then install the specified version, lock it and modify your Pipfile. Hope this helps

**Comment by GilbertoCS** [comment]
Hi @trallard, @uranusjr and @trondhindenes I made some changes on this issue, but for some reason I can not see the update on GitHub. Well, I take another approach for this issue, It is possible to merge both solutions?

**Comment by uranusjr** [comment]
@GilbertoCS Can you submit a pull request with your changes on this issue so I can compare them with @trallard’s side by side and try to merge them? (Apologies if you already did; please mention the PR #.)

**Comment by GilbertoCS** [comment]
Hi @uranusjr as you request I create an PR #3046.
