### ISSUE TITLE
Add a comment to the top of generated requirements.txt files

### ISSUE THREAD

**Issue by greysteil** [pypa/pipenv#2818]
##### Is your feature request related to a problem? Please describe.

My automation tool (Dependabot) updates Pipfile, Pipfile.lock and requirement files. It sometimes finds it tricky to figure out whether a `requirements.txt` file was generated by running `pipenv lock -r` or written manually. (It needs to take a different approach, depending on the above.)

##### Describe the solution you'd like

I'd like `pipenv lock -r` to add a comment line to the top of its output, similar to that added by pip-tools by default. Something like:

```
# This file is autogenerated by Pipenv.
# To update, run `pipenv lock -r`
#
```

##### Additional info

I'm happy to do the implementation!

**Comment by techalchemy** [comment]
Seems ok to me, I’d suggest holding off until I sort out the PR I have opened which modifies this section of the code a bit

**Comment by greysteil** [comment]
👍 - will wait and then put in a PR.

**Comment by techalchemy** [comment]
I think that is sorted out btw so you are set to PR this one

**Comment by matteius** [comment]
@greysteil `pipenv==2022.4.8` has a new requirements command for generating requirements.txt from the Pipfile.lock

It outputs to stdout, which can be piped to a file, and any prefix that is needed ahead of that can be also piped to the file in the command you choose to run.  If there are further enhancements to requirements command that should be considered, please open a new issue.  We are considering deprecating/removing the `pipenv lock -r` option in favor of this new `requirements` command in future releases.
