### ISSUE TITLE
Auto add newly installed packages to pipfile

### ISSUE THREAD

**Issue by yunti** [pypa/pipenv#2821]
Similarly to yarn auto add installed packages to the pipfile.

Currently installed packages appear to only be added to the venv but not the pipfile. `pipenv graph` also doesn't graph what is installed by instead what is in the pipfile.  So to get a list of the packages that are installed in the virtualenv we have to drop down to `pip list` instead. 

I thought this may have been discussed before but couldn't find an issue if it has (nor see this is the docs).

**Comment by uranusjr** [comment]
`pipenv install` already does that? Like `npm install` (to make a rough analogy).
