### ISSUE TITLE
CLI flag for setting a custom venv location without needing to export WORKON_HOME

### ISSUE THREAD

**Issue by e-ht** [pypa/pipenv#2827]
Would you be open a PR to allow a CLI flag for setting a custom venv location without needing to `export WORKON_HOME` as referenced [here](https://github.com/pypa/pipenv/blob/master/docs/advanced.rst#-custom-virtual-environment-location)?  I would prefer to not need to invoke new variables into the shell.

**Comment by techalchemy** [comment]
This issue will need to go through the new enhancement proposal process -- nothing too fancy, just an organized way for triaging stuff with Kenneth

See here for the initial description and then you can simply just create a PR with a markdown description for review

Thanks!

**Comment by uranusjr** [comment]
I’ll add this is now possible after the `.venv` text file is supported. There are still a lot of implementation details to be sorted out, however, and a PEEP will be required to clarify those.

**Comment by matteius** [comment]
This was solved by https://pipenv.pypa.io/en/latest/advanced/#pipenv.environments.Setting.PIPENV_CUSTOM_VENV_NAME

Most users that wish to change the behavior will want to set this in their `.env` file for the project.
