### ISSUE TITLE
Accessing executables in virtualenv path on pipenv shell

### ISSUE THREAD

**Issue by simonklb** [pypa/pipenv#2829]
Is there currently any way of running an executable in `[virtualenv-path]/bin/` automatically after pipenv forks to the subshell? For example, I'm installing `awscli` in a virtual environment and I'd like to setup auto-completion with `aws_completer` which is installed with it.

Right now it seems like PATH is being set after .bashrc is sourced. Would it be a bad idea to do the opposite? If not, I could add something like this to my .bashrc:
`hash aws_completer 2>/dev/null && complete -C $(which aws_completer) aws`

**Comment by uranusjr** [comment]
Setting PATH before bashrc would indeed be a bad idea. If the user has PATH manipulation in bashrc, it would override our PATH modification. This is extremely common for e.g. pyenv users, where shims are added at the very front of PATH

```
export PATH=~/.pyenv/shims:$PATH
```

If we add to PATH before bashrc, executables in virtualenv (e.g. `python`) would be shadowed by shims (e.g. `~/.local/shims/python`), breaking the shell.
