### ISSUE TITLE
Illegal command name “_pipenv_completion()”

### ISSUE THREAD

**Issue by yohanboniface** [pypa/pipenv#2832]
##### Issue description

Error while autocompleting `pipenv install requests` under fish shell on a brand new directory.

##### Expected result

I can type the command `pipenv install requests` without error.

##### Actual result

```
$ mkdir hello
$ cd hello
$ pipenv install re/usr/share/fish/vendor_completions.d/pipenv.fish (line 1): Illegal command name “_pipenv_completion()”                                              16ms
_pipenv_completion() {
^
from sourcing file /usr/share/fish/vendor_completions.d/pipenv.fish
	called on standard input

in command substitution
	called on standard input

source: Error while reading file “/usr/share/fish/vendor_completions.d/pipenv.fish”
q
```

##### Steps to replicate

Issue only happen first time a I run a command in a new shell.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/usr/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`
  - `3.7`: `/usr/bin/python3.7m`
  - `3.7`: `/usr/bin/python3.7`

  - `3.7.0`: `/usr/bin/python`
  - `2.7.15`: `/usr/bin/python2`
  - `3.7.0`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.18.5-arch1-1-ARCH',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Fri Aug 24 12:48:58 UTC 2018',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `COLORTERM`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DESKTOP_AUTOSTART_ID`
  - `DESKTOP_SESSION`
  - `DISPLAY`
  - `GDMSESSION`
  - `GDM_LANG`
  - `GNOME_DESKTOP_SESSION_ID`
  - `GNOME_TERMINAL_SCREEN`
  - `GNOME_TERMINAL_SERVICE`
  - `GOPATH`
  - `HG`
  - `HOME`
  - `LANG`
  - `LC_MEASUREMENT`
  - `LC_MONETARY`
  - `LC_NUMERIC`
  - `LC_PAPER`
  - `LC_TIME`
  - `LOGNAME`
  - `MAIL`
  - `MOZ_PLUGIN_PATH`
  - `NPM_CONFIG_PREFIX`
  - `PATH`
  - `PIP_DOWNLOAD_CACHE`
  - `PWD`
  - `QT_IM_MODULE`
  - `RBENV_ROOT`
  - `RBENV_SHELL`
  - `SESSION_MANAGER`
  - `SHELL`
  - `SHLVL`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `USER`
  - `USERNAME`
  - `VTE_VERSION`
  - `WINDOWPATH`
  - `XAUTHORITY`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_DATA_DIRS`
  - `XDG_MENU_PREFIX`
  - `XDG_RUNTIME_DIR`
  - `XDG_SEAT`
  - `XDG_SESSION_DESKTOP`
  - `XDG_SESSION_ID`
  - `XDG_SESSION_TYPE`
  - `XDG_VTNR`
  - `XMODIFIERS`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/ybon/Code/go/bin:/home/ybon/npm-global/bin:/home/ybon/.gem/ruby/2.3.0/bin:/home/ybon/.rbenv/shims:/home/ybon/.config/fnm/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
  - `SHELL`: `/usr/bin/fish`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/ybon/Work/playground/hello`

---------------------------

</details>

```
$ fish --version
fish, version 2.7.1

$ pacman -Qo /usr/share/fish/vendor_completions.d/pipenv.fish
/usr/share/fish/vendor_completions.d/pipenv.fish is owned by python-pipenv 2018.7.1-2
```

This is what the `python-pipenv` package does:

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/python-pipenv#n69
```
SHELL=fish python -m pipenv --completion | install -Dm644 /dev/stdin "${pkgdir}/usr/share/fish/vendor_completions.d/pipenv.fish"
```

I do have [virtualfish](http://virtualfish.readthedocs.io/en/latest/) installed, but not the fisherman [pipenv](https://github.com/fisherman/pipenv) plugin.

I see BTW that there is also a builtin pipenv completion file in fish: https://github.com/fish-shell/fish-shell/blob/72d80c3d91bbd35bed0aafb5514c9834bb48e256/share/completions/pipenv.fish

So now I'm not sure where in all this chain [pipenv --completion, python-pipenv using it, fish completion…) the failing bit is, or is it some conflict between all those players trying to do their best, or any misconfiguration on my side, or…

Thanks for your hints :)

**Comment by techalchemy** [comment]
I don't see anywhere that this is invoked this way (at least not anymore) and I believe this will have to be raised with the distro package maintainer who bundled it if you do encounter it again, sorry for the trouble!
