### ISSUE TITLE
Confused by use of crayons

### ISSUE THREAD

**Issue by kevindawson** [pypa/pipenv#2836]
I get the pipenv/patched/

but why O why are you patching a module that **This repository has been archived by the owner. It is now read-only.** 

 * This means the version of crayons available to us mere mortals is broken as far as using it with pipenv.
 * Also ask the question why are you using it if it is **archived**.

Q what is pipenv's suggestion for producing coloured text in a terminal.

many thanks

**Comment by uranusjr** [comment]
Because one of our maintainers is the author of crayons. Pipenv does not have suggestions on how you should put colour in your terminal. Ask on StackOverflow, or email Kenneth privately.
