### ISSUE TITLE
`pipenv run --help` crashes

### ISSUE THREAD

**Issue by boustrophedon** [pypa/pipenv#2843]
##### Issue description
Pipenv 2018.7.1

In any directory (either containing an existing Pipfile or not), running `pipenv run --help` crashes.

##### Expected result

The help text for the run command.

##### Actual result

https://gist.github.com/boustrophedon/c396bf9e6c287f818f9b2ddf23ecebc7

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

run the command `pipenv run --help`

-------------------------------------------------------------------------------
pipenv --support: 
https://gist.github.com/boustrophedon/b68b539241d0ac5fd4aa0974eaf39c89

**Comment by frostming** [comment]
Closed via #3844

**Comment by boustrophedon** [comment]
Thank you!
