### ISSUE TITLE
Cannot do: pipenv uninstall --skip-lock despite documentation

### ISSUE THREAD

**Issue by Overdrivr** [pypa/pipenv#2848]
##### Issue description
Using the `--skip-lock` flag with `pipenv uninstall` results in :

```
Error: no such option: --skip-lock
```

Although the documentation [states](https://pipenv.readthedocs.io/en/latest/basics/#pipenv-uninstall) that:

> $ pipenv uninstall supports all of the parameters in pipenv install, [...] 

(therefore including --skip-lock)

Obviously, this can be a simple documentation fix, but it would be more interesting to add the `skip-lock` flag to `pipenv uninstall`. This is interesting for CI environments, where you might want to drop a package temporarily and don't care about locking the dependencies (that takes a significant amount of times, > 7 mins in my env). In one word: speedup.

**Comment by techalchemy** [comment]
Hmmm that is an interesting suggestion. It seems straightforward — if it’s present in your pipfile, we can remove it, if not, it will just be removed from the lockfile.

This makes sense to me simply as an interface over your pipfile from a UX standpoint. However locking should also benefit from speedups we added a long time ago related to caching, so there may be more going on here

**Comment by jkleint** [comment]
As of 2018.10.13, `pipenv uninstall` accepts `--skip-lock` but does not honor it:

```
$ pipenv uninstall csvkit --skip-lock
Un-installing csvkit…
Uninstalling csvkit-1.0.3:
  Successfully uninstalled csvkit-1.0.3

Removing csvkit from Pipfile…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (4c3760)!
```
