### ISSUE TITLE
pipenv --venv return -6, sublime console

### ISSUE THREAD

**Issue by ezeeyahoo** [pypa/pipenv#2856]
```
SublimeLinter: WARNING: Executing `pipenv --venv` failed
  Command '['pipenv', '--venv']' returned non-zero exit status -6
```

**Comment by techalchemy** [comment]
Does this work if you run it from a normal command prompt?

**Comment by techalchemy** [comment]
Closing due to lack of updates, if you continue to experience this please open a _new issue_ and _provide the full details requested in the template_

Thanks for reporting and sorry for the trouble!
