### ISSUE TITLE
Environment Variables for Username and Password are written into the Pipfile and Pipfile.lock as text

### ISSUE THREAD

**Issue by intellineers** [pypa/pipenv#2861]
When using environment variables for private repositories as sources like this:

${my_environ_var}

everything works perfectly, but the environment variable gets substituted into clear text in the Pipfile and Pipfile.lock. If I git push everything, everyone could see my Username and Password of my private pip repository.

I am not sure if this is a bug, or if this is intended, but then I don't understand the use of this.

**Comment by uranusjr** [comment]
What is the command you are using when this happens. If you’re sending them in the shell, e.g.

```
$ pipenv install http://${my_username}:${my_password}@myhost...
```

Then this is expanded by your shell before Pipenv has a chance to see it, and there’s nothing we can do.

**Comment by intellineers** [comment]
I added the remote source in the Pipfile as a source with the variables as:
[[source]]
url = "https://${USERNAME}:${PASSWORD}@pypi.org/simple"
verify_ssl = true
name = "pypi"

When I fetch the packages it substitutes the values in the Pipfile for the ones in my environment.

**Comment by uranusjr** [comment]
OK. In that case, I’ll need you to fill the issue template to continue debugging.

**Comment by intellineers** [comment]
Ok will do.

**Comment by techalchemy** [comment]
closing due to lack of movement
