### ISSUE TITLE
Pipenv removes files from another package after installing a second one

### ISSUE THREAD

**Issue by tonicebrian** [pypa/pipenv#2869]
##### Issue description

When I install `google-cloud-pubsub` package in combination with `ccxt` package, the later removes some files from dependencies required by the former.

##### Expected result

Files from dependencies are kept no matter what. Same behaviour as `pip`

##### Actual result

When using pipenv file in `lib/python3.6/site-packages/google/iam/v1/iam_policy_pb2.py` has been removed.

##### Steps to replicate

From an empty directory:

```
export PIPENV_VENV_IN_PROJECT=true
pipenv install google-cloud-pubsub==0.38.0
ls .venv/lib/python3.6/site-packages/google/iam/v1/iam_policy_pb2.py
pipenv install ccxt==1.17.322 --pre
ls .venv/lib/python3.6/site-packages/google/iam/v1/iam_policy_pb2.py
```
First ls returns the existence of the file while second reports that the file is non existent.

If we do same procedure with Pip, results are as expected. From an empty dir:

```
virtualenv -p python3 .venv
source .venv/bin/activate
pip install google-cloud-pubsub==0.38.0
ls .venv/lib/python3.6/site-packages/google/iam/v1/iam_policy_pb2.py
pip install ccxt==1.17.322
ls .venv/lib/python3.6/site-packages/google/iam/v1/iam_policy_pb2.py
``` 
In both `ls` the file is present with pip.

Hints:

- I cannot install `ccxt==1.17.322` without the `--pre` while pip works flawless.
- The file missing has suffix `_pb2.py` meaning that it is generated after compiling a Protobuf file. Is Pipenv doing some kind of "clean" and then forgetting to compile?

-------------------------------------------------------------------------------

```
$ pipenv --version
pipenv, version 2018.05.18
```

**Comment by uranusjr** [comment]
I can’t replicate this. `grpc-google-iam-v1` does come prebundled with `google/iam/v1/iam_policy_pb2.py`, and there doesn’t seem to be any compiling involved. The `--pre` part is a limitation in the current resolver, just bear with it.

**Comment by tonicebrian** [comment]
Seems like something is wrong in my machine. I run that in a docker image and it works OK, so there is an interaction in my machine that I'm not aware of.
