### ISSUE TITLE
Pipenv uninstall Fails to Update Pipfile When Package Name Exists in Comment

### ISSUE THREAD

**Issue by msopko81** [pypa/pipenv#2885]
##### Issue description

`pipenv uninstall` fails to remove package from Pipfile if a comment with the package name exists before the package.

##### Expected result

The package to be remove from the Pipfile

##### Actual result

The comment is moved up a line, but the package remains in both Pipfile and Pipfile.lock

##### Steps to replicate

1. `pipenv install django-phonenumber-field phonenumberslite`

2. Edit and have Pipfile like this:
```TOML
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django-phonenumber-field = "*"
# django-phonenumber-field requires phonenumberslite, but does not properly record it
phonenumberslite = "*"

[dev-packages]

[requires]
python_version = "3.6"
```

3. `pipenv uninstall phonenumberslite`

Output:
```
Un-installing phonenumberslite...
Uninstalling phonenumberslite-8.9.14:
  Successfully uninstalled phonenumberslite-8.9.14

Removing phonenumberslite from Pipfile...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Updated Pipfile.lock (ebdcbb)!
```
New Pipfile:
```TOML
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django-phonenumber-field = "*"# django-phonenumber-field requires phonenumberslite, but does not properly record it
phonenumberslite = "*"

[dev-packages]

[requires]
python_version = "3.6"
```

The package is removed if checked within pip:
```
pipenv run python -mpip list
Package                  Version
------------------------ -------
Babel                    2.6.0
Django                   2.1.1
django-phonenumber-field 2.0.1
phonenumbers             8.9.14
pip                      18.0
pytz                     2018.5
setuptools               40.4.3
wheel                    0.31.1
```

Since the package is still listed within the Pipfile, it will get installed for the next pipenv operation.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'C:\\Users\\Michael\\AppData\\Roaming\\Python\\Python36\\site-packages\\pipenv'`

Python location: `'c:\\program files\\python36\\python.exe'`

Other Python installations in `PATH`:

  - `3.6`: `C:\Program Files\Python36\python.exe`

  - `3.6.6`: `C:\Program Files\Python36\python.exe`
  - `3.6.6`: `C:\Windows\py.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.6',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17134',
 'python_full_version': '3.6.6',
 'python_version': '3.6',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALIASES`
  - `ALLUSERSPROFILE`
  - `ANSICON`
  - `ANSICON_DEF`
  - `APPDATA`
  - `ARCHITECTURE`
  - `CHOCOLATEYINSTALL`
  - `CHOCOLATEYLASTPATHUPDATE`
  - `CMDER_ROOT`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `CONEMUANSI`
  - `CONEMUANSILOG`
  - `CONEMUARGS`
  - `CONEMUARGS2`
  - `CONEMUBACKHWND`
  - `CONEMUBASEDIR`
  - `CONEMUBASEDIRSHORT`
  - `CONEMUBUILD`
  - `CONEMUCFGDIR`
  - `CONEMUCONFIG`
  - `CONEMUDIR`
  - `CONEMUDRAWHWND`
  - `CONEMUDRIVE`
  - `CONEMUHOOKS`
  - `CONEMUHWND`
  - `CONEMUPALETTE`
  - `CONEMUPID`
  - `CONEMUSERVERPID`
  - `CONEMUTASK`
  - `CONEMUWORKDIR`
  - `CONEMUWORKDRIVE`
  - `CONFIGSETROOT`
  - `DRIVERDATA`
  - `GIT_INSTALL_ROOT`
  - `HOME`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `KDS_LANGUAGE`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PLINK_PROTOCOL`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `SESSIONNAME`
  - `SVN_SSH`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TERM`
  - `TESSDATA_PREFIX`
  - `TMP`
  - `USER-ALIASES`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VERBOSE-OUTPUT`
  - `VS140COMNTOOLS`
  - `WINDIR`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenvûspecific environment variables:

Debugûspecific environment variables:

  - `PATH`: `C:\cmder\bin;C:\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\cmder\vendor\conemu-maximus5;C:\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files\Python35\Scripts\;C:\Program Files\Python35\;C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\OpenVPN\bin;C:\Program Files (x86)\PDFtk Server\bin\;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\SQL Operations Studio\bin;C:\Users\Michael\Miniconda3;C:\Users\Michael\Miniconda3\Library\mingw-w64\bin;C:\Users\Michael\Miniconda3\Library\usr\bin;C:\Users\Michael\Miniconda3\Library\bin;C:\Users\Michael\Miniconda3\Scripts;C:\Users\Michael\cmder\vendor\git-for-windows\usr\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Sublime Text 3;C:\Users\Michael\AppData\Roaming\npm;C:\Program Files\PostgreSQL\9.6\bin;C:\Program Files\gs\gs9.21\bin;C:\Users\Michael\Downloads\geckodriver-v0.19.1-win64;C:\Users\Michael\AppData\Roaming\Python\Python36\Scripts;C:\Users\Michael\AppData\Local\Programs\Git\cmd;C:\Users\Michael\AppData\Local\Programs\Git\mingw64\bin;C:\Users\Michael\AppData\Local\Programs\Git\usr\bin;C:\Users\Michael\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Michael\AppData\Local\hyper\app-2.0.0\resources\bin;C:\Users\Michael\AppData\Local\Programs\Git\usr\bin;C:\Users\Michael\AppData\Local\Programs\Git\usr\share\vim\vim74;C:\cmder\`

---------------------------

Contents of `Pipfile` ('D:\\KML\\git_code\\test\\Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django-phonenumber-field = "*"# django-phonenumber-field requires phonenumberslite, but does not properly record it
phonenumberslite = "*"

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('D:\\KML\\git_code\\test\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "fdeb4ec10155be6b1e8786d82a93cdbf4dcdd692f086fa1e7672c23441ebdcbb"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "babel": {
            "hashes": [
                "sha256:6778d85147d5d85345c14a26aada5e478ab04e39b078b0745ee6870c2b5cf669",
                "sha256:8cba50f48c529ca3fa18cf81fa9403be176d374ac4d60738b839122dfaaa3d23"
            ],
            "version": "==2.6.0"
        },
        "django": {
            "hashes": [
                "sha256:04f2e423f2e60943c02bd2959174b844f7d1bcd19eabb7f8e4282999958021fd",
                "sha256:e1cc1cd6b658aa4e052f5f2b148bfda08091d7c3558529708342e37e4e33f72c"
            ],
            "version": "==2.1.1"
        },
        "django-phonenumber-field": {
            "hashes": [
                "sha256:08257904750d7329b2b11dd9d8d6b7ceb261980db555bb426d9900fa390e2a4c"
            ],
            "index": "pypi",
            "version": "==2.0.1"
        },
        "phonenumbers": {
            "hashes": [
                "sha256:df8625fe51b3b3f188e846a83669d8ffc154c13e9a31005dc2d7ec5da907848c",
                "sha256:e2804ae067cd123211e4edb141f3e4942d9a1e374fee7c6c8827babefaecb042"
            ],
            "version": "==8.9.14"
        },
        "phonenumberslite": {
            "hashes": [
                "sha256:703fc0334724d4abd459348b235963506039f00ab72117d444932f3347d9abe9",
                "sha256:f7eab337b2aa083768d0cc5361a9f6f81a7bdff29cb333c31d81feae28cfe0cc"
            ],
            "index": "pypi",
            "version": "==8.9.14"
        },
        "pytz": {
            "hashes": [
                "sha256:a061aa0a9e06881eb8b3b2b43f05b9439d6583c206d0a6c340ff72a7b6669053",
                "sha256:ffb9ef1de172603304d9d2819af6f5ece76f2e85ec10692a524dd876e72bf277"
            ],
            "version": "==2018.5"
        }
    },
    "develop": {}
}

```
</details>

**Comment by uranusjr** [comment]
Yet another bug in contoml/prettytoml.
