### ISSUE TITLE
Pipenv lock differently based on different virtualenv python version

### ISSUE THREAD

**Issue by jxltom** [pypa/pipenv#2890]
##### Issue description

When ```pipenv --python 3.6``` and ```pipenv install pytest```, ```pipenv lock -r > requirements.txt``` gives following results.

```
-i https://pypi.org/simple
atomicwrites==1.2.1
attrs==18.2.0
more-itertools==4.3.0
pluggy==0.7.1
py==1.6.0
pytest==3.8.1
six==1.11.0
```

When ```pipenv --python 3.5``` and ```pipenv install pytest```, ```pipenv lock -r > requirements.txt``` gives following results.

```
-i https://pypi.org/simple
atomicwrites==1.2.1; python_version != '3.3.*'
attrs==18.2.0
more-itertools==4.3.0
pathlib2==2.3.2; python_version < '3.6'
pluggy==0.7.1; python_version != '3.3.*'
py==1.6.0; python_version != '3.3.*'
pytest==3.8.1
six==1.11.0
```

Obviously, ```pathlib2==2.3.2; python_version < '3.6'``` is only locked when using python 3.5. This makes app can not work in python35 when lock file is generated in python36.

Is that intended, or a bug? Thanks a lot.

If it is intended, how can I make project working in python35 when Pipfile.lock is generated in Python36?

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/home/user/.local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/home/user/.pyenv/shims/python2.7`
  - `2.7`: `/home/user/.pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/home/user/.pyenv/shims/python3.5m`
  - `3.5`: `/home/user/.pyenv/shims/python3.5`
  - `3.5`: `/usr/bin/python3.5`
  - `3.6`: `/home/user/.pyenv/shims/python3.6m`
  - `3.6`: `/home/user/.pyenv/shims/python3.6`

  - `2.7.12`: `/home/user/.pyenv/shims/python`
  - `2.7.12`: `/usr/bin/python`
  - `2.7.12`: `/home/user/.pyenv/shims/python2`
  - `2.7.12`: `/usr/bin/python2`
  - `3.5.2`: `/home/user/.pyenv/shims/python3`
  - `3.5.2`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-34-generic',
 'platform_system': 'Linux',
 'platform_version': '#37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018',
 'python_full_version': '2.7.12',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `LESS`
  - `UPSTART_EVENTS`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_SESSION_TYPE`
  - `LC_PAPER`
  - `SHELL`
  - `PYENV_SHELL`
  - `XDG_DATA_DIRS`
  - `MANDATORY_PATH`
  - `COMPIZ_CONFIG_PROFILE`
  - `UNITY_DEFAULT_PROFILE`
  - `UPSTART_INSTANCE`
  - `JOB`
  - `XMODIFIERS`
  - `JAVA_HOME`
  - `GTK2_MODULES`
  - `XDG_RUNTIME_DIR`
  - `LC_ADDRESS`
  - `LC_CTYPE`
  - `QT_ACCESSIBILITY`
  - `DBUS_STARTER_BUS_TYPE`
  - `XDG_SESSION_ID`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DEFAULTS_PATH`
  - `DESKTOP_SESSION`
  - `GTK_MODULES`
  - `INSTANCE`
  - `LC_NAME`
  - `XDG_MENU_PREFIX`
  - `LS_COLORS`
  - `GOPATH`
  - `DBUS_STARTER_ADDRESS`
  - `GNOME_DESKTOP_SESSION_ID`
  - `XDG_CURRENT_DESKTOP`
  - `USER`
  - `XDG_VTNR`
  - `PYENV_VIRTUALENV_INIT`
  - `XAUTHORITY`
  - `LANGUAGE`
  - `SESSION_MANAGER`
  - `LC_MEASUREMENT`
  - `QT_QPA_PLATFORMTHEME`
  - `CLUTTER_IM_MODULE`
  - `WINDOWID`
  - `GPG_AGENT_INFO`
  - `LANG`
  - `GDMSESSION`
  - `UPSTART_JOB`
  - `XDG_SEAT_PATH`
  - `PIP_PYTHON_PATH`
  - `_`
  - `GTK_IM_MODULE`
  - `XDG_CONFIG_DIRS`
  - `QT_VERSION`
  - `LC_TIME`
  - `PAGER`
  - `XDG_GREETER_DATA_DIR`
  - `QT4_IM_MODULE`
  - `HOME`
  - `DISPLAY`
  - `XDG_SESSION_DESKTOP`
  - `QT_DIR`
  - `CONDA_SHLVL`
  - `LC_MONETARY`
  - `QT_LINUX_ACCESSIBILITY_ALWAYS_ON`
  - `LC_IDENTIFICATION`
  - `VTE_VERSION`
  - `UPSTART_SESSION`
  - `GNOME_KEYRING_PID`
  - `LC_NUMERIC`
  - `UNITY_HAS_3D_SUPPORT`
  - `QT_IM_MODULE`
  - `LOGNAME`
  - `XDG_SEAT`
  - `GNOME_KEYRING_CONTROL`
  - `PATH`
  - `ZSH`
  - `TERM`
  - `XDG_SESSION_PATH`
  - `DBUS_DEBUG_OUTPUT`
  - `SESSIONTYPE`
  - `IM_CONFIG_PHASE`
  - `SSH_AUTH_SOCK`
  - `LSCOLORS`
  - `OLDPWD`
  - `GDM_LANG`
  - `LC_TELEPHONE`
  - `SHLVL`
  - `PWD`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/user/.pyenv/plugins/pyenv-virtualenv/shims:/home/user/.pyenv/shims:/home/user/.pyenv/bin:/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/user/go/bin:/home/user/jdk1.8.0_171/bin:/home/user/apache-maven-3.5.3/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/user/Desktop/Untitled Folder 2`

---------------------------

Contents of `Pipfile` ('/home/user/Desktop/Untitled Folder 2/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
pytest = "*"

[requires]
python_version = "3.5"


```

Contents of `Pipfile.lock` ('/home/user/Desktop/Untitled Folder 2/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "12174041fb4d5fc742d2aeb5ce2bdadcbfa507fb23df7e0aad9beef3202cdf6f"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.5"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "atomicwrites": {
            "hashes": [
                "sha256:0312ad34fcad8fac3704d441f7b317e50af620823353ec657a53e981f92920c0",
                "sha256:ec9ae8adaae229e4f8446952d204a3e4b5fdd2d099f9be3aaf556120135fb3ee"
            ],
            "markers": "python_version != '3.2.*' and python_version >= '2.7' and python_version != '3.0.*' and python_version != '3.1.*' and python_version != '3.3.*'",
            "version": "==1.2.1"
        },
        "attrs": {
            "hashes": [
                "sha256:10cbf6e27dbce8c30807caf056c8eb50917e0eaafe86347671b57254006c3e69",
                "sha256:ca4be454458f9dec299268d472aaa5a11f67a4ff70093396e1ceae9c76cf4bbb"
            ],
            "version": "==18.2.0"
        },
        "more-itertools": {
            "hashes": [
                "sha256:c187a73da93e7a8acc0001572aebc7e3c69daf7bf6881a2cea10650bd4420092",
                "sha256:c476b5d3a34e12d40130bc2f935028b5f636df8f372dc2c1c01dc19681b2039e",
                "sha256:fcbfeaea0be121980e15bc97b3817b5202ca73d0eae185b4550cbfce2a3ebb3d"
            ],
            "version": "==4.3.0"
        },
        "pathlib2": {
            "hashes": [
                "sha256:8eb170f8d0d61825e09a95b38be068299ddeda82f35e96c3301a8a5e7604cb83",
                "sha256:d1aa2a11ba7b8f7b21ab852b1fb5afb277e1bb99d5dfc663380b5015c0d80c5a"
            ],
            "markers": "python_version < '3.6'",
            "version": "==2.3.2"
        },
        "pluggy": {
            "hashes": [
                "sha256:6e3836e39f4d36ae72840833db137f7b7d35105079aee6ec4a62d9f80d594dd1",
                "sha256:95eb8364a4708392bae89035f45341871286a333f749c3141c20573d2b3876e1"
            ],
            "markers": "python_version != '3.2.*' and python_version >= '2.7' and python_version != '3.0.*' and python_version != '3.1.*' and python_version != '3.3.*'",
            "version": "==0.7.1"
        },
        "py": {
            "hashes": [
                "sha256:06a30435d058473046be836d3fc4f27167fd84c45b99704f2fb5509ef61f9af1",
                "sha256:50402e9d1c9005d759426988a492e0edaadb7f4e68bcddfea586bc7432d009c6"
            ],
            "markers": "python_version != '3.2.*' and python_version >= '2.7' and python_version != '3.0.*' and python_version != '3.1.*' and python_version != '3.3.*'",
            "version": "==1.6.0"
        },
        "pytest": {
            "hashes": [
                "sha256:0a72d8a9f559c006ba153e0c9b4838efd7b656cf1f993747ba7128770d6eb12c",
                "sha256:95529588ff4e85114a0b0ad8e9cf0131ca47d46b28230e25366c5aba66b1d854"
            ],
            "index": "pypi",
            "version": "==3.8.1"
        },
        "six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        }
    },
    "develop": {}
}

```
</details>

**Comment by uranusjr** [comment]
what version of setuptools do you have in each environment

**Comment by jxltom** [comment]
For python36 virtualenv,

```
Package    Version
---------- -------
pip        18.0   
setuptools 40.4.3 
wheel      0.31.1 
```

For python36 virtualenv,

```
Package    Version
---------- -------
pip        18.0   
setuptools 40.4.3 
wheel      0.31.1 
```

Totoally same. I'm using pyen by the way.

**Comment by jxltom** [comment]
Thanks for the quick reply.

No, it doesn't work when ```pipenv lock --clear```. And it's not working neither when I changed the index source url.

I'm glad it is not intended. Otherwise Pipfile.lock generated in specific python version may not be used by other different python versions.

**Comment by jxltom** [comment]
It looks like ```isort``` also has this issue.

For ```pipenv --python 2.7```, ```futures==3.2.0; python_version < '3' and python_version >= '2.6'``` will be in lockfiles.

But for ```pipenv --python 3.6```, it doesn't show.

The ```install_requires=['futures; python_version < "3.2"'],``` is ignored by pipenv when not using matched python version. https://github.com/timothycrosley/isort/blob/e59088f76e1684d7cea1a4aa3985113bac649f22/setup.py#L28

**Comment by matteius** [comment]
This should be resolved on the recent versions of pipenv.
