### ISSUE TITLE
Can pipenv add a feature that it can set a default mirror source?

### ISSUE THREAD

**Issue by ToonoW** [pypa/pipenv#2891]
In my country request "https://pypi.org/simple" is very slow.
So I have to modify the Pipfile every time I create a new project.
I hope I can set a default source.

like that 
```bash
pip config set gloabl.index-url https://pypi.tuna.tsinghua.edu.cn/simple
```

**Comment by uranusjr** [comment]
https://pipenv.readthedocs.io/en/latest/advanced/#pipenv.environments.PIPENV_PYPI_MIRROR
