### ISSUE TITLE
URL in "Bug report" template is unavailable

### ISSUE THREAD

**Issue by ocavue** [pypa/pipenv#2893]
##### Issue description

The URL ( https://kenneth-reitz.uservoice.com/forums/913660-general ) in [issue template](
https://github.com/pypa/pipenv/blob/9084792db033ccbe79beead19e655a3561dd8503/.github/ISSUE_TEMPLATE/Bug_report.md
) is unavailable.

##### Expected result

This URL is available.

##### Actual result

Error 404: Account Has Been Deleted

This UserVoice instance is no longer available.

##### Steps to replicate

None

**Comment by uranusjr** [comment]
Thanks for the report. I believe there is already an open issue for this, but I’m not in the mood of digging it out. The resolution was to remove it, but nobody cared enough to do it. Would you mind sending us a pull request?

**Comment by ocavue** [comment]
I'm happy to contribute to this project.

I think such a simple update is not needed for changelog so I didn't add a description in `news/`. It's that ok?

**Comment by uranusjr** [comment]
yeah it’s fine

**Comment by ocavue** [comment]
ok, [here](https://github.com/pypa/pipenv/pulls) is my PR.
