### ISSUE TITLE
pipenv install --ignore-pipfile is slower that pip install -r requirements

### ISSUE THREAD

**Issue by jxltom** [pypa/pipenv#2895]
It looks like ```pipenv install``` will parse toml, download packages and then lock. But the ```pipenv intall --ignore-pipfile``` should install from Pipfile.lock directly without locking anymore. Why it is still slower than ``` pip install -r requirements```?

The  ```pip install -r requirements``` will bypass installed versions. But it looks like  ```pipenv intall --ignore-pipfile``` will still install pacakges again even packages with same version have already been installed.

Is there any way to let pipenv bypass installed pacakges and only install new added ones? Thanks.

**Comment by techalchemy** [comment]
It shouldn't actually install them again, it should only verify that they are installed.  You can try `sync` instead, but I'm curious about the speed difference -- how much slower?

**Comment by techalchemy** [comment]
Does your `requirements.txt` include hashes/force hash checking?

**Comment by jxltom** [comment]
No it is just as followings.

```
-i https://pypi.org/simple
atomicwrites==1.2.1
attrs==18.2.0
more-itertools==4.3.0
pluggy==0.7.1
py==1.6.0
pytest==3.8.1
six==1.11.0
```

Here are the test materials. https://github.com/jxltom/python-package-management-tests/tree/master/pip-vs-pipenv-speed

**Comment by matteius** [comment]
I am closing this out as stale, but going to provide some context.

We have added specifically a `requirements` command that generates requirements.txt from the lock file without relocking.  I suspect any slowness with -r was that it required locking to generate the requirements to use in subsequent operation.   We are removing `lock -r` soon.  This issue made me realize that `install -r` also needs to be reevaluated, but it is unclear how much of the analysis from 2018 still applies to the current code base.   We want to improve things further, it just would be useful if we had fresh discussions from fresh tests of the latest pipenv release (which is 2022.7.4 at the time of writing).
