### ISSUE TITLE
Error on `pipenv shell` - cygwin

### ISSUE THREAD

**Issue by kip-13** [pypa/pipenv#2897]
##### Issue description

When I run `pipenv shell` I got an error related to `shellingham` vendor package exactly `detect_shell` method.

Works fine the commands passed to `pipenv run`

```zsh
> pipenv run which python  
Loading .env environment variables...
/cygdrive/c/Users/kip/.local/share/virtualenvs/testPipenv-NNClQA64/bin/python
>                                                                                     
```

If I install `shellingham` with `pip` (another dir) and run `detect_shell`

```zsh
> source env/bin/activate
(env) env > python
Python 3.6.4 (default, Jan  7 2018, 15:53:53)
[GCC 6.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import shellingham
>>> shellingham.detect_shell()
('zsh', '/bin/zsh')
>>>
```

Maybe is the version that exists in the vendor folder (`'pipenv/vendor/shellingham/'`) with the actual release `pipenv, version 2018.7.1` ?

The commit https://github.com/pypa/pipenv/commit/3cb3f594a1a5780ceabcfb9d0310f786f58e6188 with the upgrade exists.

##### Expected result

Shell with the correct environment

##### Actual result

> pipenv shell
Loading .env environment variables...
ps: unknown option -- w
Try `ps --help' for more information.
Traceback (most recent call last):
  File "/cygdrive/c/Users/kip/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/cygdrive/c/Users/kip/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/cygdrive/c/Users/kip/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/cygdrive/c/Users/kip/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/cygdrive/c/Users/kip/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/cygdrive/c/Users/kip/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/cygdrive/c/Users/kip/.local/lib/python3.6/site-packages/pipenv/cli.py", line 664, in shell
    three=three, python=python, fancy=fancy, shell_args=shell_args, pypi_mirror=pypi_mirror
  File "/cygdrive/c/Users/kip/.local/lib/python3.6/site-packages/pipenv/core.py", line 2149, in do_shell
    shell = choose_shell()
  File "/cygdrive/c/Users/kip/.local/lib/python3.6/site-packages/pipenv/shells.py", line 217, in choose_shell
    type_, command = detect_info()
  File "/cygdrive/c/Users/kip/.local/lib/python3.6/site-packages/pipenv/shells.py", line 25, in detect_info
    return shellingham.detect_shell()
  File "/cygdrive/c/Users/kip/.local/lib/python3.6/site-packages/pipenv/vendor/shellingham/__init__.py", line 24, in detect_shell
    shell = get_shell(pid, max_depth=max_depth)
  File "/cygdrive/c/Users/kip/.local/lib/python3.6/site-packages/pipenv/vendor/shellingham/posix/__init__.py", line 20, in get_shell
    mapping = _get_process_mapping()
  File "/cygdrive/c/Users/kip/.local/lib/python3.6/site-packages/pipenv/vendor/shellingham/posix/__init__.py", line 13, in _get_process_mapping
    return impl.get_process_mapping()
  File "/cygdrive/c/Users/kip/.local/lib/python3.6/site-packages/pipenv/vendor/shellingham/posix/_default.py", line 14, in get_process_mapping
    'ps', '-ww', '-o', 'pid=', '-o', 'ppid=', '-o', 'args=',
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ps', '-ww', '-o', 'pid=', '-o', 'ppid=', '-o', 'args=']' returned non-zero exit status 1.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/cygdrive/c/Users/kip/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.14`: `/usr/bin/python`
  - `2.7.14`: `/usr/bin/python2`
  - `3.6.4`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '2.10.0(0.325/5/3)',
 'platform_system': 'CYGWIN_NT-10.0',
 'platform_version': '2018-02-02 15:16',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'cygwin'}
```

System environment variables:

  - `!::`
  - `ALLUSERSPROFILE`
  - `ANSICON`
  - `ANSICON_DEF`
  - `APPDATA`
  - `CLASSPATH`
  - `CMDER_ROOT`
  - `COMMONPROGRAMFILES`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `ChocolateyInstall`
  - `ChocolateyLastPathUpdate`
  - `CommonProgramFiles(x86)`
  - `CommonProgramW6432`
  - `ConEmuANSI`
  - `ConEmuAnsiLog`
  - `ConEmuArgs`
  - `ConEmuArgs2`
  - `ConEmuBackHWND`
  - `ConEmuBaseDir`
  - `ConEmuBaseDirShort`
  - `ConEmuBuild`
  - `ConEmuCfgDir`
  - `ConEmuConfig`
  - `ConEmuDir`
  - `ConEmuDrawHWND`
  - `ConEmuDrive`
  - `ConEmuHWND`
  - `ConEmuHooks`
  - `ConEmuPID`
  - `ConEmuPalette`
  - `ConEmuServerPID`
  - `ConEmuTask`
  - `ConEmuWorkDir`
  - `ConEmuWorkDrive`
  - `Docker`
  - `ESET_OPTIONS`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `GIT_LFS_PATH`
  - `HOME`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `HOSTNAME`
  - `INFOPATH`
  - `JAVA_HOME`
  - `LANG`
  - `LC_CTYPE`
  - `LESS`
  - `LOCALAPPDATA`
  - `LOGNAME`
  - `LOGONSERVER`
  - `LSCOLORS`
  - `LS_COLORS`
  - `NUMBER_OF_PROCESSORS`
  - `NVM_HOME`
  - `NVM_SYMLINK`
  - `OLDPWD`
  - `ORIGINAL_PATH`
  - `OS`
  - `OneDrive`
  - `PAGER`
  - `PATH`
  - `PATHEXT`
  - `PRINTER`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROFILEREAD`
  - `PROGRAMFILES`
  - `PS1`
  - `PSModulePath`
  - `PUBLIC`
  - `PWD`
  - `ProgramData`
  - `ProgramFiles(x86)`
  - `ProgramW6432`
  - `SESSIONNAME`
  - `SHELL`
  - `SHLVL`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `Sublime`
  - `TEMP`
  - `TERM`
  - `TMP`
  - `TMUX`
  - `TMUX_PANE`
  - `TZ`
  - `USER`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `WINDIR`
  - `ZSH`
  - `_`
  - `tmp`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/bin:/cygdrive/c/cmder/vendor/conemu-maximus5/ConEmu/Scripts:/cygdrive/c/cmder/vendor/conemu-maximus5:/cygdrive/c/cmder/vendor/conemu-maximus5/ConEmu:/cygdrive/c/Python37/Scripts:/cygdrive/c/Python37:/cygdrive/c/Python27:/cygdrive/c/Python27/Scripts:/cygdrive/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/ProgramData/chocolatey/bin:/cygdrive/c/Program Files/Sublime Text 3:/cygdrive/c/Program Files/Docker Toolbox:/cygdrive/c/Program Files/Java/jdk1.8.0_172/bin:/cygdrive/c/Users/kip/AppData/Roaming/nvm:/cygdrive/c/Program Files/nodejs:/cygdrive/c/Program Files/Git LFS:/cygdrive/c/Users/kip/.cargo/bin:/cygdrive/c/Users/kip/AppData/Roaming/nvm:/cygdrive/c/Program Files/nodejs:/cygdrive/c/Users/kip/.local/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/cygdrive/c/Users/kip/repos/testPipenv`

---------------------------

Contents of `Pipfile` ('/cygdrive/c/Users/kip/repos/testPipenv/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "2.7"

```

</details>

**Comment by uranusjr** [comment]
Cygwin is not supported at the current time, unfortunately. I don’t believe any of the devs have much experience with it either (I certainly don’t, and I am the main maintainer of Shellingham right now), so unless we can get help in this area, this will probably keep being broken for a while…

**Comment by alphydan** [comment]
What is a supported shell to use with Windows 10 to avoid these problems?

**Comment by uranusjr** [comment]
There is not. The unsupported part is Cygwin, not the shell you use. We will be more than glad to merge if someone is willing to contribute, but there is no active development from core maintainers at the current time.
