### ISSUE TITLE
Can pipenv freeze requirements file only include packages?

### ISSUE THREAD

**Issue by leisurelicht** [pypa/pipenv#2901]
Can pipenv freeze requirements file only include packages?

I want requirement file don't include dev-packages.

**Comment by techalchemy** [comment]
I believe we would need to modify the API semantics a bit, you should propose this by making a markdown document and submitting it as a pull request to the `peeps` directory proposing the change so that kenneth can review it

**Comment by leisurelicht** [comment]
OK, I will do it.

**Comment by matteius** [comment]
The new `pipenv requirements` command has flags for this.
