### ISSUE TITLE
Cannot install pipenv with pip

### ISSUE THREAD

**Issue by achou11** [pypa/pipenv#2908]
### Issue description

pip fails to install pipenv on OSX

### Expected result

Expected to have pipenv successfully installed after running  `pip3 install pipenv`

### Actual result

pip hangs when making a request to PyPI:

```
Collecting pipenv
  1 location(s) to search for versions of pipenv:
  * https://pypi.org/simple/pipenv/
  Getting page https://pypi.org/simple/pipenv/
  Looking up "https://pypi.org/simple/pipenv/" in the cache
  Current age based on date: 259811
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/pipenv/ HTTP/1.1" 304 0
```

### Steps to replicate

Using pip3 (18.0) on OSX 10.14 (Mojave), run the following:

`pip3 install pipenv`

Let me know if this might be an issue with PyPI and pip, and not pipenv. Thanks!

**Comment by JulienPalard** [comment]
Yes it looks more like a pip issue than a pipenv issue, you should open it here https://github.com/pypa/pip/. When opening the new bug you may try to answer those questions:

- How many time did you waited during the "hang"?
- Can you try to wait longer to try to reach a timeout and get a stacktrace?
- If you kill the process, using a KeyboardInterrupt (C-c), do you have a stacktrace?
- Can you try with -vvv to get more informations?

**Comment by achou11** [comment]
Sorry for the late response. It seemed to be a cache problem. Thanks!
