### ISSUE TITLE
determine if installation is platform-specific

### ISSUE THREAD

**Issue by freddrake** [pypa/pipenv#2915]
I'm interested in determining whether a build required installing any packages with hardware-specific components (extensions, etc.).

Is there a way to get this information from the command line (possibly via **pipenv run pip ...**), or do I need look in the virtual environment's **lib/pythonX.Y/site-packages/*.dist-info/** files to determine this?

I'm interested in this because I want to construct a system package from (parts of) the resulting virtual environment.

**Comment by uranusjr** [comment]
I feel this is out of the scope of Pipenv. It may be a good proposal to [pip](https://github.com/pypa/pip), or you might want to ask on [distutils-sig](https://mail.python.org/mm3/mailman3/lists/distutils-sig.python.org/) (I don’t believe it is already implemented, but I may very well be wrong, distutils-sig is your best shot to get the correct answer).
