### ISSUE TITLE
I can't install Django (or any other package) using pipenv

### ISSUE THREAD

**Issue by kalasni** [pypa/pipenv#2944]
I can't install Django (or any other package) using pipenv. I "think" I have a conflict with the Python versions installed on my system (Ubuntu 18.04), or when installing pipenv with pip. 

How could I solve this problem? Thanks in advance

pipenv installed by:

$ pip install --user pipenv

$ python --version  
Python 2.7.15rc1
(by default, even though I use an alias to run python3 by default.
alias python='/usr/bin/python3.6'  )

$ pipenv --python 3
Creating a virtualenv for this project...
Pipfile: /home/ro/workspace/pyt/django-jwt/Pipfile
Using /usr/bin/python3 (3.6.6) to create virtualenv...
⠋Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/ro/.local/share/virtualenvs/django-jwt-l8_cwxbw/bin/python3
Also creating executable in /home/ro/.local/share/virtualenvs/django-jwt-l8_cwxbw/bin/python
Installing setuptools, pip, wheel...done.
Setting project for django-jwt-l8_cwxbw to /home/ro/workspace/pyt/django-jwt

Virtualenv location: /home/ro/.local/share/virtualenvs/django-jwt-l8_cwxbw
Creating a Pipfile for this project...

$ pipenv install django
Installing django...
Traceback (most recent call last):
  File "/home/ro/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/ro/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ro/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
...
..
File "/home/ro/.local/lib/python2.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
/home/ro/.local/lib/python2.7/site-packages/pipenv/_compat.py:113: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-Bpi57Z-requirements'>
  warnings.warn(warn_message, ResourceWarning)

<details><summary>$ pipenv --support</summary>
pipenv --support
Pipenv version: `'2018.7.1'`

Pipenv location: `'/home/ro/.local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.15`: `/usr/bin/python`
  - `2.7.15`: `/usr/bin/python2`
  - `3.6.6`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-36-generic',
 'platform_system': 'Linux',
 'platform_version': '#39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018',
 'python_full_version': '2.7.15rc1',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `KDE_SESSION_VERSION`
  - `XCURSOR_SIZE`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_SESSION_TYPE`
  - `LOGNAME`
  - `USER`
  - `PATH`
  - `XDG_VTNR`
  - `HOME`
  - `PAM_KWALLET_LOGIN`
  - `DISPLAY`
  - `KDE_FULL_SESSION`
  - `LANG`
  - `PROFILEHOME`
  - `TERM`
  - `SHELL`
  - `COLORFGBG`
  - `XAUTHORITY`
  - `LANGUAGE`
  - `SESSION_MANAGER`
  - `XDG_DATA_DIRS`
  - `GS_LIB`
  - `MANDATORY_PATH`
  - `KONSOLE_PROFILE_NAME`
  - `XCURSOR_THEME`
  - `KONSOLE_DBUS_WINDOW`
  - `RBENV_SHELL`
  - `QT_ACCESSIBILITY`
  - `WINDOWID`
  - `XDG_RUNTIME_DIR`
  - `SSH_AGENT_PID`
  - `__GIT_PROMPT_IGNORE_SUBMODULES`
  - `KONSOLE_DBUS_SESSION`
  - `XDG_SESSION_CLASS`
  - `XDG_SESSION_DESKTOP`
  - `KDE_SESSION_UID`
  - `__GIT_PROMPT_SHOW_CHANGED_FILES_COUNT`
  - `SSH_AUTH_SOCK`
  - `KONSOLE_DBUS_SERVICE`
  - `PAM_KWALLET5_LOGIN`
  - `PIP_PYTHON_PATH`
  - `GTK2_RC_FILES`
  - `XDG_SEAT_PATH`
  - `XDG_SESSION_PATH`
  - `GIT_BRANCH`
  - `LESSOPEN`
  - `XDG_SESSION_ID`
  - `SHELL_SESSION_ID`
  - `_`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `GTK_RC_FILES`
  - `DESKTOP_SESSION`
  - `GPG_AGENT_INFO`
  - `LESSCLOSE`
  - `DEFAULTS_PATH`
  - `XDG_SEAT`
  - `OLDPWD`
  - `__GIT_PROMPT_IGNORE_STASH`
  - `PYTHONDONTWRITEBYTECODE`
  - `__GIT_PROMPT_SHOW_UNTRACKED_FILES`
  - `SHLVL`
  - `PWD`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `COLORTERM`
  - `XDG_CONFIG_DIRS`
  - `LS_COLORS`
  - `__GIT_PROMPT_SHOW_UPSTREAM`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/heroku/bin:/home/ro/.rbenv/plugins/ruby-build/bin:/home/ro/.rbenv/shims:/home/ro/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ro/.local/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `es_ES.UTF-8`
  - `PWD`: `/home/ro/workspace/pyt/django-jwt`

---------------------------

Contents of `Pipfile` ('/home/ro/workspace/pyt/django-jwt/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]

[requires]
python_version = "3.6"

```

</details>

**Comment by browniebroke** [comment]
Due to #2935, fixed on master.

**Comment by ManniCS** [comment]
I have the same problem. Downgrading to pip 18.0, as suggested on https://github.com/pypa/pipenv/pull/2935 did not solve for me

**Comment by browniebroke** [comment]
Actually, it didn't help me either, so in the meantime, I installed from source `pip install git+https://github.com/pypa/pipenv.git@master`. Hopefully, the team find the time to release & should get a new release on PyPI soon.

**Comment by techalchemy** [comment]
new release is out also, good luck!

**Comment by erinrosenbaum** [comment]
Pipenv (19) would not install any of my packages on Ubuntu (16), so I'm going back to using virtualenv
