### ISSUE TITLE
Can't install packages in pipenv

### ISSUE THREAD

**Issue by nielstron** [pypa/pipenv#2946]
### Issue description
When installing any package with pipenv (whether inside or outside environment) it fails with `TypeError: module not callable`

### Expected result

Package is installed correctly

### Actual result
```
user@device:~/python/test> pipenv install --verbose inflect
Installing inflect...
⠋Installing 'inflect'
Traceback (most recent call last):
  File "/home/niels/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/niels/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/niels/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/niels/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/niels/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/niels/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/niels/.local/lib/python3.6/site-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/home/niels/.local/lib/python3.6/site-packages/pipenv/core.py", line 1971, in do_install
    pypi_mirror=pypi_mirror,
  File "/home/niels/.local/lib/python3.6/site-packages/pipenv/core.py", line 1375, in pip_install
    package_name.split('--hash')[0].split('--trusted-host')[0]
  File "/home/niels/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
```

### Steps to replicate

Create a test directory and run `pipenv install ...`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/home/niels/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.4`: `/usr/local/bin/python3.4m`
  - `3.4`: `/usr/local/bin/python3.4`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.15`: `/usr/bin/python`
  - `2.7.15`: `/usr/bin/python2`
  - `3.6.5`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.18.9-1-default',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Thu Sep 20 06:37:04 UTC 2018 (67901ec)',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `GS_LIB`
  - `KDE_FULL_SESSION`
  - `LS_COLORS`
  - `HOSTTYPE`
  - `LC_MEASUREMENT`
  - `M2_HOME`
  - `XAUTHLOCALHOSTNAME`
  - `LESSCLOSE`
  - `LC_MONETARY`
  - `XKEYSYMDB`
  - `LANG`
  - `WINDOWMANAGER`
  - `LESS`
  - `PROFILEHOME`
  - `DISPLAY`
  - `JAVA_ROOT`
  - `HOSTNAME`
  - `SHELL_SESSION_ID`
  - `CONFIG_SITE`
  - `CSHEDIT`
  - `GTK2_MODULES`
  - `GPG_TTY`
  - `AUDIODRIVER`
  - `LESS_ADVANCED_PREPROCESSOR`
  - `COLORTERM`
  - `JAVA_HOME`
  - `ALSA_CONFIG_PATH`
  - `MACHTYPE`
  - `XDG_VTNR`
  - `M2`
  - `GTK3_MODULES`
  - `SSH_AUTH_SOCK`
  - `QEMU_AUDIO_DRV`
  - `MINICOM`
  - `QT_SYSTEM_DIR`
  - `OSTYPE`
  - `XDG_SESSION_ID`
  - `USER`
  - `PAGER`
  - `DESKTOP_SESSION`
  - `LC_COLLATE`
  - `KONSOLE_VERSION`
  - `MORE`
  - `PWD`
  - `SSH_ASKPASS`
  - `HOME`
  - `SSH_AGENT_PID`
  - `HOST`
  - `XNLSPATH`
  - `XDG_SESSION_TYPE`
  - `SDK_HOME`
  - `XDG_DATA_DIRS`
  - `KONSOLE_DBUS_SESSION`
  - `JDK_HOME`
  - `XDG_SESSION_DESKTOP`
  - `PROFILEREAD`
  - `LC_NUMERIC`
  - `KONSOLE_DBUS_WINDOW`
  - `GTK_MODULES`
  - `FROM_HEADER`
  - `MAIL`
  - `UBUNTU_MENUPROXY`
  - `LESSKEY`
  - `TERM`
  - `SHELL`
  - `KONSOLE_DBUS_SERVICE`
  - `XDG_SESSION_CLASS`
  - `XDG_SEAT_PATH`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `LS_OPTIONS`
  - `XCURSOR_THEME`
  - `XDG_CURRENT_DESKTOP`
  - `KONSOLE_PROFILE_NAME`
  - `PYTHONSTARTUP`
  - `XDG_SEAT`
  - `SHLVL`
  - `COLORFGBG`
  - `LANGUAGE`
  - `G_FILENAME_ENCODING`
  - `MANPATH`
  - `WINDOWID`
  - `XSESSION_IS_UP`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `JRE_HOME`
  - `XDG_SESSION_PATH`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `XDG_CONFIG_DIRS`
  - `PATH`
  - `JAVA_BINDIR`
  - `KDE_SESSION_UID`
  - `SDL_AUDIODRIVER`
  - `KDE_SESSION_VERSION`
  - `QT_IM_SWITCHER`
  - `G_BROKEN_FILENAMES`
  - `HISTSIZE`
  - `SESSION_MANAGER`
  - `CPU`
  - `CVS_RSH`
  - `LESSOPEN`
  - `GTK_IM_MODULE`
  - `LC_TIME`
  - `OLDPWD`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/opt/maven//bin:/opt/maven//bin:/home/niels/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/sbin:home/niels/bin/:/home/niels/.local/bin:home/niels/bin/:/home/niels/.local/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/niels/python/testQU3.4`

---------------------------

Contents of `Pipfile` ('/home/niels/python/testQU3.4/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.6"

```

</details>

**Comment by ManniCS** [comment]
I had the same issue @nielstron. Did you find a solution?

**Comment by nielstron** [comment]
It is the same as #2944 which has been solved. The error still occurs though as no new version has been published yet.
