### ISSUE TITLE
pipshims was updated and pipenv didn't work?

### ISSUE THREAD

**Issue by huangxiaohen2738** [pypa/pipenv#2947]
File "/usr/lib/python2.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable

pipenv, version 2018.7.1

**Comment by jxltom** [comment]
This is a known bug which is fixed by https://github.com/pypa/pipenv/pull/2935

For the workaround, ```pip install pip==18.0``` or install the latest pipenv version from the master branch

**Comment by huangxiaohen2738** [comment]
thanks
