### ISSUE TITLE
dockerfile not recognizing requirements.txt

### ISSUE THREAD

**Issue by bgjelstrup** [pypa/pipenv#2969]
when building my dockerfile it keeps telling me there is no directory, I have even tried pointing it directly to path but to no prevail. basically trying to learn my way around docker for my boss but can't even get it to initiate installing the specified apps in my requirements.txt.

Step 6/9 : RUN pip install -r requirements.txt
 ---> Running in 34df017c7b91
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1

**Comment by xolan** [comment]
1. You're using `pip` directly, not `pipenv`.
2. Without seeing the rest (or relevant rest) of your Dockerfile, it's tough to know where the issue lies.
3. I assume you've forgotten to copy or mount the `requirements.txt` in the working directory.

**Comment by techalchemy** [comment]
closing due to lack of info, hope you had some success figuring this out
