### ISSUE TITLE
pipenv graph fails with ModuleNotFoundError

### ISSUE THREAD

**Issue by orn688** [pypa/pipenv#2973]
### Issue description

`pipenv graph` fails with the following output:

```
File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/pipdeptree.py", line 16, in <module>
    from pipenv.vendor.pip_shims import get_installed_distributions, FrozenRequirement
ModuleNotFoundError: No module named 'pipenv'
```

### Expected result

Some dependency graph to be shown.

### Actual result

(see above)

### Steps to replicate

In the official Pipenv Docker image (`docker run -it --rm kennethreitz/pipenv /bin/bash`):
```bash
pipenv --python 3.7
pipenv graph  # fails
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.9'`

Pipenv location: `'/usr/local/lib/python3.7/dist-packages/pipenv'`

Python location: `'/usr/bin/python3.7'`

Python installations found:

  - `3.7.0`: `/usr/bin/python3`
  - `3.7.0`: `/usr/bin/python3.7`
  - `3.7.0`: `/usr/bin/python3.7m`
  - `3.6.6`: `/usr/bin/python3.6m`
  - `3.6.6`: `/usr/bin/python3.6`
  - `2.7.15rc1`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.9.93-linuxkit-aufs',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Wed Jun 6 16:55:56 UTC 2018',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LC_ALL`
  - `LS_COLORS`
  - `LESSCLOSE`
  - `LANG`
  - `HOSTNAME`
  - `PWD`
  - `HOME`
  - `DEBIAN_FRONTEND`
  - `TERM`
  - `SHLVL`
  - `PATH`
  - `LESSOPEN`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/app`

---------------------------

Contents of `Pipfile` ('/app/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.7"

```

</details>

**Comment by techalchemy** [comment]
Please see #2952 and #2970 for discussion

**Comment by orn688** [comment]
Oops, thanks! Sorry for the dupe.
