### ISSUE TITLE
Arguments Error

### ISSUE THREAD

**Issue by KeatingSmith** [pypa/pipenv#2994]
### Issue description

when using `piping install -r requirements`

### Expected result

installing packages

### Actual result

<img width="928" alt="image" src="https://user-images.githubusercontent.com/15377472/46774796-c6151a80-cd36-11e8-9e9b-9d82bdc69e45.png">

#### Env

➜  clw-server git:(develop) ✗ pipenv --support
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.9'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.10.9/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.10.9/libexec/bin/python3.7'`

**Comment by KeatingSmith** [comment]
I think someone has fixed it, who can upgrade release?

**Comment by techalchemy** [comment]
I will upgrade the release when everything is finished and merged inm closing for now
