### ISSUE TITLE
Set PIPENV_ACTIVE when running pipenv run

### ISSUE THREAD

**Issue by maw** [pypa/pipenv#2996]
### Is your feature request related to a problem? Please describe.

I have a script to wrap pyre that ends thus:

```
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ x"$PIPENV_ACTIVE" != x"1" ]] ; then
   echo activate pipenv by running pipenv shell or pipenv run "$DIR"/pyre
   exit 2
fi

exec pyre --search-path "$(pipenv --venv)/lib/python3.6/site-packages" "$@"
```

Unfortunately, the second suggestion doesn't work as things currently are.

### Describe the solution you'd like

`PIPENV_ACTIVE` should be set when you run `pipenv run`, just as it is when you run `pipenv shell`.

### Describe alternatives you've considered

None.

### Additional context

I'm about to submit a pull request. Is running `pipenv --support` really necessary here?

-

**Comment by techalchemy** [comment]
Ah closing this as I think I missed it when I mass merged some prs, thanks for the fix!
