### ISSUE TITLE
pipenv clean doesn't uninstall package not specified in Pipfile.lock

### ISSUE THREAD

**Issue by HuangShaoyan** [pypa/pipenv#2999]
### Issue description

```pipenv clean``` doesn't uninstall package not specified in Pipfile.lock. 

### Expected result

```pipenv clean``` should uninstall all packages not specified in Pipfile.lock only.

### Actual result

```pipenv clean``` doesn't uninstall package that not specify in Pipfile.lock, but always show uninstalling package "pipenv" and "virtualenv".

```shell
$ pipenv clean -v
Ignoring 'pip'.
Ignoring 'setuptools'.
Ignoring 'wheel'.
Uninstalling 'virtualenv'…
Uninstalling 'virtualenv-clone'…
Uninstalling 'pipenv'…
Uninstalling 'certifi'…                                                                                                                                                     
```

### Steps to replicate

1. install package sh
    ```$ pipenv install sh```
1. pip list it
    ```shell
    $ pipenv run pip list
    Package    Version
    ---------- -------
    pip        18.1
    setuptools 40.4.3
    sh         1.12.14
    wheel      0.32.1
    ```
    I can't use pipenv graph to show dependencies. It is still broken. Please refer to #2952 

    Pipfile:
    ```
    [packages]
    sh = "*"
    ```
1. comment package sh in Pipfile
    Pipfile:
    ```
    [packages]
    # sh = "*"
    ```
1. clean
    ```shell
    $ pipenv clean -v
    Ignoring 'pip'.
    Ignoring 'setuptools'.
    Ignoring 'wheel'.
    Uninstalling 'virtualenv'…
    Uninstalling 'virtualenv-clone'…
    Uninstalling 'pipenv'…
    Uninstalling 'certifi'…
    ```

    package "sh" not uninstall
    ```shell
    $ pipenv run pip list
    Package    Version
    ---------- -------
    pip        18.1
    setuptools 40.4.3
    sh         1.12.14
    wheel      0.32.1
    ```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.9'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.10.9/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.10.9/libexec/bin/python3.7'`

Python installations found:

  - `3.7.0`: `/Users/huangshaoyan/.pyenv/versions/3.7.0/bin/python3.7`
  - `3.7.0`: `/Users/huangshaoyan/.pyenv/versions/3.7.0/bin/python3.7m`
  - `3.7.0`: `/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/bin/python3.7`
  - `3.7.0`: `/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/bin/python3.7m`
  - `3.6.5`: `/Users/huangshaoyan/.pyenv/shims/python3`
  - `3.6.5`: `/Users/huangshaoyan/.pyenv/shims/python`
  - `3.6.5`: `/Users/huangshaoyan/.pyenv/shims/python3.6`
  - `3.6.5`: `/Users/huangshaoyan/.pyenv/shims/python3.6m`
  - `3.6.5`: `/Users/huangshaoyan/.pyenv/versions/3.6.5/bin/python3.6`
  - `3.6.5`: `/Users/huangshaoyan/.pyenv/versions/3.6.5/bin/python3.6m`
  - `3.6.4`: `/Users/huangshaoyan/.pyenv/versions/3.6.4/bin/python3.6`
  - `3.6.4`: `/Users/huangshaoyan/.pyenv/versions/3.6.4/bin/python3.6m`
  - `3.6.3`: `/Users/huangshaoyan/.pyenv/versions/3.6.3/bin/python3.6`
  - `3.6.3`: `/Users/huangshaoyan/.pyenv/versions/3.6.3/bin/python3.6m`
  - `3.6.1`: `/Users/huangshaoyan/.pyenv/versions/3.6.1/bin/python3.6`
  - `3.6.1`: `/Users/huangshaoyan/.pyenv/versions/3.6.1/bin/python3.6m`
  - `3.5.2`: `/Users/huangshaoyan/.pyenv/versions/3.5.2/bin/python3.5`
  - `3.5.2`: `/Users/huangshaoyan/.pyenv/versions/3.5.2/bin/python3.5m`
  - `2.7.15`: `/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7`
  - `2.7.14`: `/Users/huangshaoyan/.pyenv/versions/2.7.14/bin/python2.7`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.0.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT '
                     '2018; root:xnu-4903.201.2~1/RELEASE_X86_64',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `MANPATH`
  - `rvm_use_flag`
  - `SSH_AGENT_PID`
  - `rvm_bin_path`
  - `TERM_PROGRAM`
  - `rvm_quiet_flag`
  - `GEM_HOME`
  - `NVM_CD_FLAGS`
  - `PIPENV_PYTHON`
  - `PYENV_ROOT`
  - `ANDROID_HOME`
  - `rvm_gemstone_url`
  - `TERM`
  - `SHELL`
  - `rvm_docs_type`
  - `IRBRC`
  - `TMPDIR`
  - `NVM_PATH`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `SELENIUM_CDNURL`
  - `rvm_hook`
  - `MY_RUBY_HOME`
  - `TERM_SESSION_ID`
  - `SDKMAN_PLATFORM`
  - `ZSH`
  - `NVM_DIR`
  - `USER`
  - `rvm_gemstone_package_file`
  - `_system_type`
  - `SDKMAN_CANDIDATES_API`
  - `rvm_path`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `rvm_proxy`
  - `rvm_ruby_file`
  - `PAGER`
  - `MAVEN_OPTS`
  - `LSCOLORS`
  - `rvm_silent_flag`
  - `rvm_prefix`
  - `rvm_ruby_make`
  - `_`
  - `NVM_NODEJS_ORG_MIRROR`
  - `PWD`
  - `CHROMEDRIVER_CDNURL`
  - `rvm_sdk`
  - `LANG`
  - `SDKMAN_VERSION`
  - `ITERM_PROFILE`
  - `_system_arch`
  - `XPC_FLAGS`
  - `AUTOJUMP_DATA_DIR`
  - `_system_version`
  - `XPC_SERVICE_NAME`
  - `rvm_version`
  - `rvm_script_name`
  - `rvm_pretty_print_flag`
  - `PYENV_SHELL`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `rvm_ruby_mode`
  - `PHANTOMJS_CDNURL`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `rvm_alias_expanded`
  - `GROOVY_HOME`
  - `SDKMAN_DIR`
  - `rvm_wrapper_name`
  - `GEM_PATH`
  - `LC_CTYPE`
  - `NVM_BIN`
  - `rvm_nightly_flag`
  - `NVM_IOJS_ORG_MIRROR`
  - `rvm_ruby_make_install`
  - `SDKMAN_CANDIDATES_DIR`
  - `ANDROID_NDK_HOME`
  - `rvm_niceness`
  - `DISPLAY`
  - `rvm_ruby_bits`
  - `rvm_bin_flag`
  - `rvm_only_path_flag`
  - `RUBY_VERSION`
  - `_system_name`
  - `COLORTERM`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

 - `PIPENV_PYTHON`: `/Users/huangshaoyan/.pyenv/shims/python`

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.10.9/libexec/tools:/Users/huangshaoyan/.rvm/gems/ruby-2.4.1/bin:/Users/huangshaoyan/.rvm/gems/ruby-2.4.1@global/bin:/Users/huangshaoyan/.rvm/rubies/ruby-2.4.1/bin:/Users/huangshaoyan/.pyenv/shims:/Users/huangshaoyan/.sdkman/candidates/groovy/current/bin:/Users/huangshaoyan/.nvm/versions/node/v8.12.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/deployd/bin:/usr/local/go/bin:/usr/local/opt/android-ndk/bin:/Users/huangshaoyan/.rvm/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/huangshaoyan/workspace/pipenvbug`

---------------------------

Contents of `Pipfile` ('/Users/huangshaoyan/workspace/pipenvbug/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
sh = "*"

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/Users/huangshaoyan/workspace/pipenvbug/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "0d85e69ff0ba710b723eeb2afa6eccc783788971ac59f87a764a116203ddb902"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "sh": {
            "hashes": [
                "sha256:ae3258c5249493cebe73cb4e18253a41ed69262484bad36fdb3efcb8ad8870bb",
                "sha256:b52bf5833ed01c7b5c5fb73a7f71b3d98d48e9b9b8764236237bdc7ecae850fc"
            ],
            "index": "pypi",
            "version": "==1.12.14"
        }
    },
    "develop": {}
}

```

Contents of `Pipfile.lock` after comment out package "sh":
```json
{
    "_meta": {
        "hash": {
            "sha256": "415dfdcb118dd9bdfef17671cb7dcd78dbd69b6ae7d4f39e8b44e71d60ca72e7"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}
```

</details>

**Comment by uranusjr** [comment]
I am not sure if it is a good idea to “fix” this. Maybe we need a poll or something to have an idea what users actually expect. Or maybe a PEEP is needed?

**Comment by techalchemy** [comment]
`pipenv clean` is also fixed in master. Sorry for the difficulty, see #2976
