### ISSUE TITLE
"pipenv lock -r": Unable to generate requirements.txt

### ISSUE THREAD

**Issue by neo** [pypa/pipenv#3003]
This is the same as #2932 

### Issue description

`pipenv lock -r` doesn't work

### Expected result

installed packages in `requirement.txt` format

### Actual result

```
-i https://pypi.org/simple

```

### Steps to replicate

`pipenv lock -r`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.9'`

Pipenv location: `'/usr/local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.7'`

Python installations found:

  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.0.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT '
                     '2018; root:xnu-4903.201.2~1/RELEASE_X86_64',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TMPDIR`
  - `__CF_USER_TEXT_ENCODING`
  - `SHELL`
  - `HOME`
  - `Apple_PubSub_Socket_Render`
  - `SSH_AUTH_SOCK`
  - `PATH`
  - `LOGNAME`
  - `XPC_SERVICE_NAME`
  - `USER`
  - `XPC_FLAGS`
  - `LESS`
  - `LSCOLORS`
  - `OLDPWD`
  - `PAGER`
  - `PWD`
  - `SHLVL`
  - `ZSH`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `LANG`
  - `TERM`
  - `LC_CTYPE`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/neo/Desktop/folder/projects/adblitz-2019/prj-3-354-adblitz-2019`

---------------------------

Contents of `Pipfile` ('/Users/neo/Desktop/folder/projects/adblitz-2019/prj-3-354-adblitz-2019/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]
"unittest2" = "*"

[requires]
python_version = "2.7"

```

Contents of `Pipfile.lock` ('/Users/neo/Desktop/folder/projects/adblitz-2019/prj-3-354-adblitz-2019/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "c2e305d1ee51990746430f08ecfb445457982052a5b9e100f0a3a4d3a69e7d58"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "2.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {
        "argparse": {
            "hashes": [
                "sha256:62b089a55be1d8949cd2bc7e0df0bddb9e028faefc8c32038cc84862aefdd6e4",
                "sha256:c31647edb69fd3d465a847ea3157d37bed1f95f19760b11a47aa91c04b666314"
            ],
            "version": "==1.4.0"
        },
        "linecache2": {
            "hashes": [
                "sha256:4b26ff4e7110db76eeb6f5a7b64a82623839d595c2038eeda662f2a2db78e97c",
                "sha256:e78be9c0a0dfcbac712fe04fbf92b96cddae80b1b842f24248214c8496f006ef"
            ],
            "version": "==1.0.0"
        },
        "six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        },
        "traceback2": {
            "hashes": [
                "sha256:05acc67a09980c2ecfedd3423f7ae0104839eccb55fc645773e1caa0951c3030",
                "sha256:8253cebec4b19094d67cc5ed5af99bf1dba1285292226e98a31929f87a5d6b23"
            ],
            "version": "==1.4.0"
        },
        "unittest2": {
            "hashes": [
                "sha256:13f77d0875db6d9b435e1d4f41e74ad4cc2eb6e1d5c824996092b3430f088bb8",
                "sha256:22882a0e418c284e1f718a822b3b022944d53d2d908e1690b319a9d3eb2c0579"
            ],
            "index": "pypi",
            "version": "==1.1.0"
        }
    }
}

```
</details>

**Comment by neo** [comment]
For people landed here with the same issue, the temporary workaround I found is to do the following instead:
```
pipenv run pip freeze > requirements.txt
```

**Comment by frostming** [comment]
You should do `pipenv lock -d -r` instead since you only have dev packages.

**Comment by neo** [comment]
Thanks a lot! 🙏 
Sorry for didn't realize that.
