### ISSUE TITLE
Command-line option "--bare" has no effect in "sync" and "clean" actions

### ISSUE THREAD

**Issue by cubranic** [pypa/pipenv#3041]
### Issue description

The `--bare` flag is supposed to set "minimal output" in `sync` and `clean`, but I don't see any difference with and without it. Looking at the [code](https://github.com/pypa/pipenv/blob/master/pipenv/core.py#L2469) implementing those actions, I see `bare` in the list of parameters for `do_sync` and `do_clean`, but they are not used anywhere in the body of those functions.

### Expected result

No output when `--bare` is used in `pipenv sync`.

**Comment by techalchemy** [comment]
Yep, that's definitely right.  It's been at the back of my mind to do something about this for awhile but there is a pretty sizeable project to tackle around output cleanup in general

**Comment by frostming** [comment]
I think the meaning of 'bare' here is to run the command on itself, instead of called by other commands. So if you run `pipenv sync`, the 'bare' flag should be True by default.

Just to share what is in my head.

**Comment by cubranic** [comment]
@frostming Check the help text for the `--bare` option: that demonstrably is not what it is intended to be.
Then look at any other command where it's actually functional. There are various lines where status is printed wrapped in `if not bare:`.

**Comment by frostming** [comment]
@cubranic ya you are right. I didn't check source code thoroughly.

**Comment by jcrotts** [comment]
Opened a PR for this, I think it addresses the behavior you described @cubranic .

**Comment by techalchemy** [comment]
This was closed in #3126 by way of #3064 and will be in the next release, thanks @jcrotts!
