### ISSUE TITLE
Use command status codes to indicate success of a command

### ISSUE THREAD

**Issue by cubranic** [pypa/pipenv#3042]
### Is your feature request related to a problem? Please describe.

In automated deployments where `pipenv sync` is used, it's useful to know whether any dependencies were actually updated, since it affects subsequent steps (e.g., restarting the service). AFAIK, "pipenv" does not do this: it prints the same message "All dependencies are now up-to-date!" and returns status 0 regardless of whether anything was updated or not.

### Describe the solution you'd like

An easy to process by a script, and documented, way for pipenv to signal whether it changed anything in the virtual environment. I'm not sure if status code is the right way to do it, as "success" is both not having to do anything and updating dependencies to the requested versions.

### Describe alternatives you've considered

I checked the source, and `sync` only returns a non-zero status code if something failed (no lock file, not able to install requested dependency, etc.) I considered parsing the output of `pipenv sync`, but it's both chatty (e.g., the animated progress bar), and does not print anything that would make it easy to distinguish the "updated deps" from "nothing to update" case.

**Comment by cubranic** [comment]
I described the scenario we face: if the dependencies were changed, the service that uses the pipenv needs to be restarted.

Your pseudo-code would address my need, except that the key bit "`pipenv is-everything-up-to-date`" does not exist.

Also, as I said: "nothing changed" does not have to be signalled with the exit status code. Just printing something like "Everything is already up to date!" would be sufficient.

**Comment by uranusjr** [comment]
I was implying that maybe the best way to approach this is to implement `is-everything-up-to-date`. Is `pipenv --outdated` suitable for your usage? If not, how can we tweak it to be useful for you?

**Comment by cubranic** [comment]
It's not quite the right thing for two reasons:

1. because it's for deployment, what I'm looking would be more like `pipenv sync --outdated`, if there were such a thing. (I.e., check if the packages in the environment are exactly versions specified in Pipenv.lock)

2. I need the check for outdated dependencies to function more like "pip upgrade --upgrade-strategy only-if-needed", not "eager".

**Comment by cjerdonek** [comment]
For command-line API's to convey structured information beyond success or failure, the way I would recommend is to log progress information to stderr, and use stdout for information about the result that can be read in machine-readable format (e.g. json). If you want to get fancy, you could have a command-line flag to indicate the format of the stdout (e.g. `--output=json` or `--output=text`, etc).

**Comment by techalchemy** [comment]
@cjerdonek thanks a bunch for taking the time to give input, I think that’s largely reflective of the situation we would like to be in, but aren’t quite there yet. Basically if it is optional and for users, we want to send it to stderr.

One thing that is going to be an obstacle to this is that our output code is scattered all over the place and needs to be organized. It’s not a straightforward task to track everything down to make sure we are suppressing the correct outputs, etc.

**Comment by matteius** [comment]
This has been fixed.
