### ISSUE TITLE
pipfile.lock package hash value always update

### ISSUE THREAD

**Issue by leileigong** [pypa/pipenv#3053]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://docs.pipenv.org/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

I wanna to install an pyscard package from wheel file in my computer.So I write 
`"pyscard" = {path = "wheelhouse/pyscard-1.9.7-cp27-cp27m-win32.whl"}`
into the pipfile. but everytime I run "pipenv install", the pacage hash value update from "34dec91d1187fbe636566704232ae2c8bd569bdb496ac40d32ddf5a1fc9b9c5d" to "412c74c83e7401566e9d3d7b8b5ca965e74582a1f33179b3c1fabf1da73ebf80".
the hash value "412c74c83e7401566e9d3d7b8b5ca965e74582a1f33179b3c1fabf1da73ebf80" refers to an package on PyPI.

```
        "pyscard": {
            "hashes": [
                "sha256:412c74c83e7401566e9d3d7b8b5ca965e74582a1f33179b3c1fabf1da73ebf80"
            ],
            "path": "wheelhouse/pyscard-1.9.7-cp27-cp27m-win32.whl",
            "version": "==1.9.7"
        }, 
```

### Expected result
I expect the hash value 34dec91d1187fbe636566704232ae2c8bd569bdb496ac40d32ddf5a1fc9b9c5d refer to the package in my local computer. 
```
        "pyscard": {
            "hashes": [
                "sha256:34dec91d1187fbe636566704232ae2c8bd569bdb496ac40d32ddf5a1fc9b9c5d"
            ],
            "path": "wheelhouse/pyscard-1.9.7-cp27-cp27m-win32.whl",
            "version": "==1.9.7"
        },
```

### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by techalchemy** [comment]
As of #3298 hashes will be included for local files as well as remote ones if they are available, sorry for the trouble!
