### ISSUE TITLE
pipenv shell --two freezes shell

### ISSUE THREAD

**Issue by superDross** [pypa/pipenv#3067]
### Issue description

The commands `pipenv shell --two`,  `pipenv shell --python 2.7` & `pipenv shell --two --python 2.7` all cause the terminal to freeze. I can't even use CTRL-C to kill the process, I have kill the PID.

It works fine when install a python3 virtual env.

### Expected result

The python2 virtual environment to be installed. 

### Actual result

Frozen terminal.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.13'`

Pipenv location: `'/home/davidr/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

Then it just freezes and I have to kill the PID.

**Comment by techalchemy** [comment]
Passing `--two` completely replaces your environment. Are you saying you can’t even run the support command? When you say ‘freezes’, how long are you waiting?

**Comment by superDross** [comment]
I can't run anything after running it with --two. It freezes indefinitely, I have to kill the process.

**Comment by techalchemy** [comment]
This is resolved in the latest version, sorry for the trouble!

**Comment by crhan** [comment]
when will you release a new version? I'm still suffer this problem
