### ISSUE TITLE
Impossible to hide the "Courtesy Notice" about active virtualenv

### ISSUE THREAD

**Issue by pior** [pypa/pipenv#3068]
### Issue description

When using an existing virtualenv, we get this message:

> Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.

### Expected result

With `export PIPENV_VERBOSITY=-1` the **Courtesy Notice** message should not be shown.

### Actual result

The message still appear with `export PIPENV_VERBOSITY=-1`.

**Comment by techalchemy** [comment]
This was merged so i'll go ahead and close it, thanks for reporting!
