### ISSUE TITLE
[Feature request] Add installed dev package into Pipfile dev package section

### ISSUE THREAD

**Issue by fkromer** [pypa/pipenv#3076]
When installing dev packages via `pipenv install <dev-package>` they are added to the `Pipfile`s `[packages]` section if not present already. My current workaround is to manualy copy & paste added dev paclages from the `[packages]` into the `[dev-packages]` section. It would be great if one could specify the package type via a command line option to pipe new dev package dependencies into the `Pipfile`s `dev-package` section.

**Comment by frostming** [comment]
I think you need `pipenv install --dev <dev-package>`

**Comment by uranusjr** [comment]
@frostming is correct
