### ISSUE TITLE
dotenv configuration

### ISSUE THREAD

**Issue by decaz** [pypa/pipenv#3077]
1. I am using the latest version of Flask which supports .env files when `python-dotenv` package is installed. It conflicts with `dotenv` package vendored within pipenv.

It would be nice to have `dont_load_env` (default `false`) at `pipenv` section within Pipfile so there will be no need to provide `PIPENV_DONT_LOAD_ENV=1` every time running pipenv. It would be useful not only in case of Flask usage but in case I want to use `python-dotenv` on my own.

2. Pipenv loads .env file using `override=True` argument so I cannot overwrite environment from CLI:
`VAR=1 pipenv run ...`.

It would be great to have `dont_override_env` (default `false`) at `pipenv` section within Pipfile (and `PIPENV_DONT_OVERRIDE_ENV` environment variable also).

**Comment by uranusjr** [comment]
I feel it is usually a personal choice whether `.env` should be loaded, so a project-wide setting seems awkward. An environment variable would be more appropriate.

How does the Flask configuration conflict with Pipenv’s dotenv loading, however? I’d think it is generally safe to load the same dotenv file multiple times. Maybe we should fix the incompatibility as well.

**Comment by decaz** [comment]
I agree that using .env is a personal choice and maybe it worth to do something for not to load .env twice when using Flask.

But overriding existing environment variables seems to be unexpected behavior (Flask, for instance, doesn't override existing variables as `False` is the default value for argument `override` within `python-dotenv` itself). So using for example `PIPENV_DONT_OVERRIDE_ENV` environment variable to not to override existing variables every time would be annoying. For instance:
```PIPENV_DONT_OVERRIDE_ENV=1 SOME_VAR="some value" pipenv run some_cmd```

How can it be configured if not by project setting (for example `dont_override_env`) within Pipfile?

**Comment by uranusjr** [comment]
`override=False` is probably not an option either because it would then be impossible to, well, override things. It is unfortunately quite common for people to have a value globally, and override it in a project’s `.env`. IIRC there was even a debate a while back, and we decided to keep the current implementation. This is quite tricky :(

**Comment by decaz** [comment]
Hmm.. So if I want to override some environment variable once for a single command run then I should add or replace its value within my .env?

**Comment by techalchemy** [comment]
I am definitely not accepting a PR that adds a project setting to the pipfile without Kenneth signing off on it, you need to submit a PEEP if you want that.
