### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split' (when run without using fish)

### ISSUE THREAD

**Issue by adihat** [pypa/pipenv#3078]
**Environment:**

OS: `mac os mojave`
xcode version: `10.0`
pipenv version: `2018.10.13`
python3 version: `Python 3.6.4 Anaconda custom (64-bit)`
shell: `bash`

**Installation steps:**
1. Installed pipenv via homebrew
    `$ brew install pipenv`

2. created a directory in home directory
     `$ mkdir pipenv_test`

3. created a directory .venv inside of pipenv_test
     `$ mkdir .venv`

4. Ran the following command:
     `$ pipenv --three`

Got the following:
![screenshot 2018-10-22 at 8 48 00 pm](https://user-images.githubusercontent.com/30288808/47301127-cf0dc200-d63b-11e8-882f-50804972b1fb.png)

what could be the error?

**Comment by adihat** [comment]
The following errors aren't seen if run using fish. Any thing to be noted here?? Is pipenv mean't to be run under fish alone?

**Comment by adihat** [comment]
Ok its working now. Have no idea how this error happened. I just uninstall pipenv and installed it back again and all seems to work fine.

**Comment by techalchemy** [comment]
I use fish as my primary shell and I haven't seen this one, i'll close for now and we can see if others run into it.  Thanks for reporting!
