### ISSUE TITLE
Performance Bottlenecks

### ISSUE THREAD

**Issue by devkral** [pypa/pipenv#3082]
Pipenv performance is bad. I mentioned some bottlenecks here:
https://github.com/pypa/pipenv/issues/2873
But maybe the wrong place. Here a list of bottlenecks (will grow):

* missing namespace packages. vendor and patched are great candidates for namespace packages
* patching loads vendored libraries. Use a custom Import_loader or better a cache solution like in django-payments (\_\_init\_\_)
* huge bloat: it would be nice to reduce (hard) dependencies as pipenv is supposed to be a core component. Here would be lazy loading a great help.

**Comment by devkral** [comment]
* double hashing (not sure): I think intern pip is used. So why duplicating hash functionality?
* use package hashes: If a package provides hashes, it is safe to use them because pip will check them. 
* caching: I think a dirty fix for the several downloads would be to use lru_cache for small downloads.

**Comment by uranusjr** [comment]
thanks for the patches

**Comment by babaMar** [comment]
I'm experiencing some very slow performances especially while locking, is there any intention to improve on this side of things?

**Comment by uranusjr** [comment]
Locking will always be slow, this is fundamental to Python packaging. The enhancements proposed here will improve it slightly, but the bulk of the improvements need to be handled by *how* Python packaging works (i.e. with more performant API in PyPI.org) and is out of the control of Pipenv.

**Comment by matteius** [comment]
Please open any new specific actionable issues as they pertain to the latest `pipenv==2022.1.8` and be sure to follow the template for opening issues.  I am closing this thread as being dated==it references multiple ideas, but some of the underlying pipenv implementation has changed since the issue was opened and the assumptions should be rechecked.
