### ISSUE TITLE
uwsgi can't be locked on windows by version 2018.10.13

### ISSUE THREAD

**Issue by hulucc** [pypa/pipenv#3084]
### Issue description

It works on version 2018.7.1, but fails after update.

### Expected result

Lock success.

### Actual result

```
ptools\repositories\pypi.py", line 415, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "c:\users\hulucc\appdata\local\programs\python\python36\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "c:\users\hulucc\appdata\local\programs\python\python36\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 263, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\hulucc\appdata\local\programs\python\python36\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "c:\users\hulucc\appdata\local\programs\python\python36\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "c:\users\hulucc\appdata\local\programs\python\python36\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "c:\users\hulucc\appdata\local\programs\python\python36\lib\site-packages\pipenv\patched\notpip\_internal\req\req_install.py", line 636, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\users\hulucc\appdata\local\programs\python\python36\lib\site-packages\pipenv\patched\notpip\_internal\utils\misc.py", line 701, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\hulucc\AppData\Local\Temp\tmpxls4tv_cbuild\uwsgi\
```

### Steps to replicate

```
uwsgi = { version = "==2.0.15", sys_platform = "!= 'win32'" }
```
```
pipenv lock
```
-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.13'`

Pipenv location: `'c:\\users\\hulucc\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\pipenv'`

Python location: `'c:\\users\\hulucc\\appdata\\local\\programs\\python\\python36\\python.exe'`

Python installations found:

  - `3.7.0`: `C:\Users\hulucc\AppData\Local\Programs\Python\Python37\python.exe`
  - `3.6.6`: `C:\Users\hulucc\AppData\Local\Programs\Python\Python36\python.exe`
  - `3.5`: `C:\Users\hulucc\AppData\Local\Programs\Python\Python35\python.exe`
  - `3.5`: `C:\Users\hulucc\AppData\Local\Programs\Python\Python35-32\python.exe`
  - `2.7`: `C:\Python27\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.6',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17134',
 'python_full_version': '3.6.6',
 'python_version': '3.6',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALIASES`
  - `ALIYUN_ACCESS_KEY`
  - `ALIYUN_ACCESS_SECRET`
  - `ALLUSERSPROFILE`
  - `ANSICON`
  - `ANSICON_DEF`
  - `APPDATA`
  - `ARCHITECTURE`
  - `ARCHITECTURE_BITS`
  - `AWS_ACCESS_KEY`
  - `AWS_ACCESS_SECRET`
  - `CMDER_INSTALL_DIR`
  - `CMDER_ROOT`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPOSE_CONVERT_WINDOWS_PATHS`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `CONEMUANSI`
  - `CONEMUANSILOG`
  - `CONEMUARGS`
  - `CONEMUARGS2`
  - `CONEMUBACKHWND`
  - `CONEMUBASEDIR`
  - `CONEMUBASEDIRSHORT`
  - `CONEMUBUILD`
  - `CONEMUCFGDIR`
  - `CONEMUCONFIG`
  - `CONEMUDIR`
  - `CONEMUDRAWHWND`
  - `CONEMUDRIVE`
  - `CONEMUHOOKS`
  - `CONEMUHWND`
  - `CONEMUISADMIN`
  - `CONEMUPALETTE`
  - `CONEMUPID`
  - `CONEMUSERVERPID`
  - `CONEMUTASK`
  - `CONEMUWORKDIR`
  - `CONEMUWORKDRIVE`
  - `DEBUG-OUTPUT`
  - `DNX_HOME`
  - `DOCKER`
  - `DOCKER_CERT_PATH`
  - `DOCKER_HOST`
  - `DOCKER_MACHINE_NAME`
  - `DOCKER_TLS_VERIFY`
  - `DOCKER_TOOLBOX_INSTALL_PATH`
  - `DRIVERDATA`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `GIT_INSTALL_ROOT`
  - `HOME`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `LANG`
  - `LC_ALL`
  - `LIB_BASE`
  - `LIB_CONSOLE`
  - `LIB_GIT`
  - `LIB_PATH`
  - `LIB_PROFILE`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `MAX_DEPTH`
  - `MSBUILDDISABLENODEREUSE`
  - `NGINX_HOME`
  - `NO_PROXY`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PLINK_PROTOCOL`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `PYTHON27`
  - `PYTHON35`
  - `PYTHON36`
  - `PYTHON37`
  - `PYTHONIOENCODING`
  - `STARTUPDIR`
  - `SVN_SSH`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TERM`
  - `TMP`
  - `USER-ALIASES`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VBOX_MSI_INSTALL_PATH`
  - `VBOX_USER_HOME`
  - `VERBOSE-OUTPUT`
  - `VS140COMNTOOLS`
  - `VSSDK140INSTALL`
  - `WINDIR`
  - `WIX`
  - `__COMPAT_LAYER`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `D:\cmder\bin;D:\cmder\vendor\conemu-maximus5\ConEmu\Scripts;D:\cmder\vendor\conemu-maximus5;D:\cmder\vendor\conemu-maximus5\ConEmu;C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\ProgramData\chocolatey\bin;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Bitvise SSH Client;C:\Windows\SysWOW64\WindowsPowerShell\v1.0\Modules\TShell\TShell\;C:\Program Files\Oracle\VirtualBox;C:\Users\hulucc\scoop\apps\nmap\current\bin;C:\Users\hulucc\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\hulucc\AppData\Local\Programs\Python\Python36\;C:\Users\hulucc\scoop\apps\gcc\current\bin;C:\Users\hulucc\AppData\Local\Programs\Python\Launcher\;C:\Users\hulucc\scoop\apps\nodejs\current\bin;C:\Users\hulucc\scoop\apps\nodejs\current;C:\Users\hulucc\scoop\shims;C:\Users\hulucc\scoop\apps\llvm\current\bin;C:\Users\hulucc\.dnx\bin;C:\Users\hulucc\AppData\Local\Programs\Fiddler;C:\Users\hulucc\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Docker Toolbox;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files (x86)\WiX Toolset v3.11\bin;C:\Program Files (x86)\GnuWin32\bin;c:\Program Files (x86)\Java\jdk1.8.0_121\bin;D:\platform-tools;c:\Users\hulucc\scoop\apps\python\current;D:\cmder\vendor\conemu-maximus5\..\git-for-windows\usr\bin;C:\Users\hulucc\scoop\apps\git\current\cmd;C:\Users\hulucc\scoop\apps\git\current\mingw64;C:\Users\hulucc\scoop\apps\git\current\usr\bin;D:\cmder`
  - `LANG`: `en_US.UTF-8`

---------------------------

Contents of `Pipfile` ('D:\\project\\play3\\Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
uwsgi = { version = "==2.0.15", sys_platform = "!= 'win32'" }


[dev-packages]

[requires]
python_version = "3.6"

```

</details>

**Comment by uranusjr** [comment]
Pipenv needs to run setup.py to inspect dependencies from a source distribution. You will need to as uWSGI folks to release a wheel, or at least make `setup.py egg_info` work on Windows (the library itself does not need to work, only setup.py).

**Comment by hulucc** [comment]
For anyone may be interested about the workaround,
Just put the [code](https://gist.github.com/hulucc/669b3f9cc379f017840285fb2bed3387) in the os.py of your virtualenv to make uwsgi can be locked on windows
