### ISSUE TITLE
Pipenv not recognized

### ISSUE THREAD

**Issue by KayJay89** [pypa/pipenv#3101]
### Issue description

Pipenv works when you just install it. However, after rebooting PC (I'm on Windows), it no longer works.

### Expected result

I expect the **python shell** command to work every time.

### Actual result

`pipenv shell
'pipenv' is not recognized as an internal or external command,
operable program or batch file.`

### Steps to replicate

1/CD to folder with pipfile
2/In CMD: pip install pipenv (installs fine)
3/In CMD: pipenv shell (works fine)

*RESTART COMPUTER*

1/Go to same directory
2/pipenv shell --> FAILS with message I pasted in "Actual Result"

Content Pipfile:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.7"

```

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

**I can not. It says:**
```
'pipenv' is not recognized as an internal or external command,
operable program or batch file.
```

I checked the PATH and I have both Python as the Scripts location added there. When I run pipenv install after the above, it says it is already installed:

`Requirement already satisfied: pipenv in c:\users\kevin\appdata\local\programs\python\python37-32\lib\site-packages (2018.10.13)
Requirement already satisfied: certifi in c:\users\kevin\appdata\local\programs\python\python37-32\lib\site-packages (from pipenv) (2018.8.24)
Requirement already satisfied: setuptools>=36.2.1 in c:\users\kevin\appdata\local\programs\python\python37-32\lib\site-packages (from pipenv) (39.0.1)
Requirement already satisfied: virtualenv in c:\users\kevin\appdata\local\programs\python\python37-32\lib\site-packages (from pipenv) (16.0.0)
Requirement already satisfied: virtualenv-clone>=0.2.5 in c:\users\kevin\appdata\local\programs\python\python37-32\lib\site-packages (from pipenv) (0.3.0)
Requirement already satisfied: pip>=9.0.1 in c:\users\kevin\appdata\local\programs\python\python37-32\lib\site-packages (from pipenv) (18.1)`

When I remove virtualenv & pipenv and then reinstall pipenv, it works again until the next time I reboot my computer.

**Comment by susanqiao** [comment]
@ KayJay89  the solution worked for me. Thank you!

**Comment by LightningRpper** [comment]
@KayJay89 This did not help me. I uninstalled and reinstalled, but nothing changed.

**Comment by delLetran** [comment]
@LightningRpper
-> add to path 
-> restart to update installation

**Comment by chilledblitz** [comment]
Refer 
https://stackoverflow.com/questions/46041719/windows-reports-error-when-trying-to-install-package-using-pipenv/46041892#46041892
Solution with highest upvotes
1. First, remove your current version of virtualenv: pip uninstall virtualenv
2. Then, remove your current version of pipenv: pip uninstall pipenv
3. When you are asked Proceed (y/n)? just enter y. This will give you a clean slate.
4. Finally, you can once again install pipenv and its dependencies: pip install pipenv
5. Check installation with pipenv --version
