### ISSUE TITLE
`TypeError: can only concatenate str (not "type") to str` instead of actual error

### ISSUE THREAD

**Issue by aidin36** [pypa/pipenv#3102]
### Issue description

In some cases, `pipenv` outputs `TypeError: can only concatenate str (not "type") to str` instead of the actual error (or after printing out the actual error). It faces an error while handling the actual error.

### Steps to replicate

Set WORKON_HOME to somewhere that current user doesn't have permission for writing to. Example:

`WORKON_HOME=/opt/  pipenv install`

-------------------------------------------------------------------------------
I encountered the issue on the latest source code from the Github.

**Comment by equaliser0** [comment]
I get this error by starting `pipenv shell`. There actually two errors I found:

```
ModuleNotFoundError: No module named 'pkgutil'
```
and

```
TypeError: can only concatenate str (not "type") to str
```

directly after running  `pipenv shell`

I am not sure, what I can do

**Comment by techalchemy** [comment]
The issue is a problem with a dependency in pipenv. You can fix this by installing from the working update until the release is out: `pip install git+https://github.com/pypa/pipenv.git@update-vendor#egg=pipenv`

**Comment by jxltom** [comment]
Hi @techalchemy Could you look at this issue again? I still get this issue when I installed latest master branch with commit e3ee806. Thanks.

**Comment by techalchemy** [comment]
Yikes. Any chance you can print or log the type? I’m guessing it’s an EOF still?

**Comment by jxltom** [comment]
@techalchemy Hi, I found it is ```TIMEOUT```. I made a PR https://github.com/pypa/pipenv/pull/3159 for that.

**Comment by namanipradeep** [comment]
Hi ,

When I am trying to build pypika query for casting I am also getting same error, The code snippet will be(TypeError: can only concatenate str (not "type") to str)

col_name = 'fn.Cast(' + aliasName + '.' + columnNamevalue + ','+ SqlTypes +'.'+ castTypevalue+')'

Can any one help on this
