### ISSUE TITLE
Question: generate requirements.txt without locking all package versions

### ISSUE THREAD

**Issue by RafalSkolasinski** [pypa/pipenv#3107]
General question: how can I generate requirements.txt that specifies only the minimal versions as in the Pipfile lock? It is, if Pipfile contains ``"*"`` I'd like requirements.txt to allow any version of a package.

**Comment by uranusjr** [comment]
So basically a Pipfile -> requirements.txt converter (no locking involved, just map everything literally)? I feel it is out of scope of Pipenv, but you should be able to put together something ralatively easily with RequirementsLib.

**Comment by techalchemy** [comment]
I was considering adding a CLI for this, but am literally maintaining like 40 libraries trying to coordinate releases of pipenv so I don't have time

**Comment by RafalSkolasinski** [comment]
I believe it is completely in range of Pipenv. It is just export of ``Pipfile``, not ``Pipfile.lock``.
After posting this issue, I found an existing project on PyPi: [pipenv-to-requirements](https://pypi.org/project/pipenv-to-requirements/).

I still think, though, that pipenv would be more complete with this functionality as a built in.

**Comment by techalchemy** [comment]
Pipenv is a dependency and environment management tool, it would be nice to have a plug-in system but honestly like I said above when you are asking us to trade between making actual functionality or just printing your file when there’s already a workaround, the first thing is always going to take priority. 

Neither myself nor @uranusjr even uses requirements files anymore so I doubt we are in a hurry to build this for you. Basically I get what you’re asking for, but there are options already. You can even make your own script:

```python
$ pip install requirementslib
$ python -c 'from requirementslib.models.pipfile import Pipfile; pf = Pipfile.load("."); pkgs = [pf.dev_requirements, pf.requirements]; print("\n".join([pkg.as_line() for pkg in pkgs]))'
```

**Comment by uranusjr** [comment]
I thought a bit about how this would be implemented, and it occurs to me that you probably need to come up with a verb for this operation. This would involve some design decisions and probably needs to be approved by Kenneth, maybe via a PEEP?

**Comment by techalchemy** [comment]
yeah this would definitely be an API change  for pipenv and would need to be outlined in an enhancement proposal, feel free to submit one -- the implementation isn't particularly hard, but I'm not sold on adding the additional switch to the api from a UX standpoint

**Comment by matteius** [comment]
This is accomplished by the new `pipenv requirements` command.
