### ISSUE TITLE
Customized dependency resolution / full required graph

### ISSUE THREAD

**Issue by chnlior** [pypa/pipenv#3118]
Note - This is following a quesiton I've asked in SO [here](https://stackoverflow.com/q/52966126/3700626) and [here](https://stackoverflow.com/q/52818381/3700626).

As we all know, the dependency resolution in the python world is far from being easy.

**The Problem**
User can not make a customized conflict resolution (like, for example gradle [has](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html)).
Current situation is that pip resolves to the first installed and pipenv is failing if the conflict can not be resolved. 

In addition, user can not see the full conflicts picture to decide how he wants to solve it. User can manually solve one conflict and then get new one, etc ...
Tools like **pipenv graph** shows what is installed and not the sum of all requirements (regrdless conflicts). pip-compile tool, resolves like pip does (first wins).

**Suggests Solutions**

1. A tool that can "dig" and build the full **required** (not installed) dependencies tree and report all the union of all requirements (regardless conflicts) . This information will:
a. Enable one to see the full conflicts picture.
b. Enable one to decide (manually or automatically) how to solve the conflicts and produce a resolved pip file / requirements.txt. 

2. A predefined special conflict resolutions like: take highest minor, highest release number etc.
and / or a plugin hook to write one by myself according to some api.

For example in my organization, the Java programmers build a custom dependency resolution using Gradle to prefer the release highest version required (not the latest but the highest required by all the consuming packages). If there is such it is installed, if not it is failing.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.13'`

Pipenv location: `'d:\\miniconda3\\lib\\site-packages\\pipenv'`

Python location: `'d:\\miniconda3\\python.exe'`

Python installations found:

  - `4.5.4`: `D:\Miniconda3\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '7',
 'platform_system': 'Windows',
 'platform_version': '6.1.7601',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `AMDAPPSDKROOT`
  - `APPDATA`
  - `ASL.LOG`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `CONDA_DEFAULT_ENV`
  - `CONDA_EXE`
  - `CONDA_PREFIX`
  - `CONDA_PROMPT_MODIFIER`
  - `CONDA_PYTHON_EXE`
  - `CONDA_SHLVL`
  - `FP_NO_HOST_CHECK`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `PYTHONIOENCODING`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDOMAIN`
  - `USERNAME`
  - `USERPROFILE`
  - `VS120COMNTOOLS`
  - `WINDIR`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `d:\miniconda3\Library\bin;D:\Miniconda3;D:\Miniconda3\Library\mingw-w64\bin;D:\Miniconda3\Library\usr\bin;D:\Miniconda3\Library\bin;D:\Miniconda3\Scripts;D:\Miniconda3\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;D:\cygwin64\bin;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;D:\cygwin64\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Windows Live\Shared`

---------------------------

</details>

**Comment by chnlior** [comment]
@techalchemy, thanks for your prompt response.
I agree the implementation is challenging, but I believe there is one representation that sums the union of the requirements regardless the repos order.
In "hand waving" algorithm, suppose that you start like pip but every time you have a conflict you split to two new independent fresh problems and collect continue to collect the requirements.
In the end (assuming no cyclic deps, that in any solution is end of game) you will have an aggregated (big) list of all the options. Now you can start to resolve the conflicts according to some policy. I know this can become exponential combinatoric problem, but I think in most project it is small number of option. We can also solve conflicts on the fly and decrease the number of options.

The approximate version will not work as it will not solves conflicts, but just will reduce the chances they will happen.

**Simple Example of my use case**

A0.1 -> B3.0
A0.1 -> D4.1.0
A0.1 -> C2.x

B3.0 -> D4.1.1

D4.1.0 -> C1.9
D4.1.1 -> C2.3

C1.9 -> E0.1
C2.3 -> E0.3

In the global reoi (pypi)  the latest C is C2.8
C2.8 -> E1.0


I would like to get this info:
B3.0 from A.01
Conflict: D4.1.0 from A0.1,  D4.1.1 from B3.0
Conflict: C2.3 from D4.1.1, C1.9 from D4.1.0, C2.x from A0.1
Conflict: E.01 from C1.9, E0.3 from C2.3, E1.0 from C2.8

With this information I have all the info to resolve (or decide to fail) and I can choose the right path on the big tree.
For example, if I have a policy of **highest required minor**
i will end with **{B3.0, D4.1.1, C2.3, E0.3}**

pip will give me (depend on the order) -  {B3.0, D4.1.0, C2.8, E1.0} and report about the conflicts that were not resolved. You can see **how far** what pip install from what I really wanted.
pipenv (currently) will give me conflict error and **fail**.

**Comment by techalchemy** [comment]
Note that currently you should probably raise this in https://github.com/sarugaku/passa as we plan to move in that direction for resolution and you have almost exactly described how we are handling things. Currently I am stuck on merging markers so if you are good at set math implementations I would be glad for extra eyes :p

Basically for this we need to identify what, as a user, you expect to provide as inputs, and how that will map to different behaviors in the system. But no matter what it’s not possible with the current resolver. We custom-wrote passa specifically with pipenv in mind and it has a constant state representation of all packages and all valid candidates for each one

**Comment by chnlior** [comment]
Tx, @techalchemy .
I will take a look on passa.
