### ISSUE TITLE
Remove easter eggs

### ISSUE THREAD

**Issue by tiran** [pypa/pipenv#3128]
I just noticed the tweet https://twitter.com/KumarVimal/status/1057149022346137600 . Apparently pipenv has an easter egg that shows a pumpkin around Halloween, see https://github.com/pypa/pipenv/blob/d069dff844c04babe4827eb33e443c180e83c5bb/pipenv/core.py#L73-L93 . I'm really worried about this.

I'm aware that some people find easter eggs an amusing gimmick in software. However easter-eggs make software unpredictable and are a even potential security. This is especially true for easter eggs that are triggered by default. CPython has some easter eggs like ``import this``, however they are never triggered either time, environment, or default. Pipenv strives to become a defacto tool for Python's packaging infrastructure. Please be more responsible and serious.

Bugs like [Gimme Gimme Gimme](https://www.theregister.co.uk/2017/11/22/gimme_gimme_gimme_in_linux_breaks_automated_tests/) have been caused by easter eggs.

**Comment by Conan-Kudo** [comment]
This is a huge overreaction. All it does is literally change which emoji is used during what time of year if emoji can be used.

It's a pretty safe alteration, and it's not worth killing an easter egg like this over it. VLC is another example of an application who does something like this. It just swaps out the icon for Christmas time with one that has Santa's hat on top.

> Please be more responsible and serious.

Please understand that levity is important for people to enjoy what they do. Sucking the personality and life out of applications just means it's not worth developing them anymore.

**Comment by tiran** [comment]
You can't seriously compare pipenv to VLC. VLC is a user-facing application and dedicated to entertainment. Also VLC is never executed as privileged root user, too. On the other hand, pipenv also aims to be used in automated tasks and executed as root.

Do you want pipenv to be a fun, cute toy or a professional, serious, reliable application?

And no, I'm not asking for all easter eggs to die. It's depends on the circumstances. For some software, it can be ok. However time based easter eggs, easter eggs in automation tools, and **especially** easter eggs in software that runs as root, are a no-go. Just don't.

**Comment by Conan-Kudo** [comment]
Pipenv is not supposed to run as root either. If people are doing that, they're using it wrong.

> Do you want pipenv to be a fun, cute toy or a professional, serious, reliable application?

I want my fun and cuteness along with reliability. This idea that professionalism implies killing all the fun out of these things has been ridiculous from day one.

> VLC is a user-facing application and dedicated to entertainment.

VLC can be used for Serious Business(TM) too. It's often used for live transcoding and streaming, since it has an engine for it built-in. But that's beside the point.

**Comment by kennethreitz** [comment]
The easter eggs stay.

**Comment by tiran** [comment]
@kennethreitz That's one way to kill a discussion. Not necessarily a polite way, though.

**Comment by kennethreitz** [comment]
The discussion can continue.

**Comment by tiran** [comment]
Then keep the ticket open until the discussion has come to a conclusion.

**Comment by vstinner** [comment]
I wanted to check if the easter egg can cause Unicode encode errors at Halloween, but in fact, it doesn't work all days :-) See my bug report #3131.
