### ISSUE TITLE
How do I tell pipenv which version of pip to use?

### ISSUE THREAD

**Issue by Pomax** [pypa/pipenv#3142]
Pip 18.1 is quite buggy, constantly throwing up `TypeError: 'module' object is not callable` and breaking installs on Windows machines, so I'd like to tell pipenv to only ever use 18.0 until pip gets a fix in some next version. However, while there is a `pipenv --python ...` command, there does not appear to be a `pipenv --pip 18.0` that I can set to ensure pipenv doesn't use the wrong pip version.

I can't find any mention about this in the docs, so: how do I make pipenv use an explicit version of pip when invoking it? Or even better, how do I configure pipenv so that it picks my preferred version of pip by default, unless I tell it not to using a flag?

**Comment by Pomax** [comment]
Note that I did try to tell pipenv to replace pip 18.1 with 18,0 but that fails spectacularly:
```
>pipenv run pip install pip==18.0
Creating a virtualenv for this project...
Pipfile: C:\Users\Pomax\Documents\Git\piptest\Pipfile
Using C:\Program Files (x86)\Python36\python.exe (3.6.6) to create virtualenv...
Running virtualenv with interpreter C:\Program Files (x86)\Python36\python.exe
Using base prefix 'C:\\Program Files (x86)\\Python36'
New python executable in C:\Users\Pomax\.virtualenvs\piptest-4aDC7Y6j\Scripts\python.exe
Installing setuptools, pip, wheel...done.
Setting project for piptest-4aDC7Y6j to C:\Users\Pomax\Documents\Git\piptest

Virtualenv location: C:\Users\Pomax\.virtualenvs\piptest-4aDC7Y6j
Loading .env environment variables...
Collecting pip==18.0
  Using cached https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
      
Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\Mike\\AppData\\Local\\Temp\\pip-uninstall-iyhodf03\\users\\mike\\.virtualenvs\\piptest-4adc7y6j\\scripts\\pip.exe'
Consider using the `--user` option or check the permissions.
```
Apparently the pip files get locked (either by itself, or by pipenv) when running in Windows, making it impossible to properly change pip versions from within pipenv.

**Comment by Pomax** [comment]
I've managed to make this work by using `pipenv run python -m pip install pip==18.0` but that's kind of a crazy amount of indirection just to make pipenv use a specific version of pip =)

**Comment by techalchemy** [comment]
Ah yes, this is actually a good catch to fix before the next release.  Thanks for letting us know!

FYI whenever this happens on windows (it happens with pip itself also) you can fix it by just using `python -m <blah>`

**Comment by techalchemy** [comment]
hrm, this _is_ an issue but I don't think it's one we can solve other than by re-vendoring pip (which I did already and will release shortly)

thanks for the report!

**Comment by Pomax** [comment]
I'll be happy to check whether the error still exists after release if you like.

**Comment by juanitosvq** [comment]
Hey I came across this issue while trying to get my environment to run with the latest version of pip `v21.1.1`.

> I've managed to make this work by using `pipenv run python -m pip install pip==18.0` but that's kind of a crazy amount of indirection just to make pipenv use a specific version of pip =)

Is this the only way we can specify which version of pip to run in the environment?
Thanks in advance.

**Comment by veikman** [comment]
There is a use case for this potential feature in https://github.com/PyO3/maturin/issues/589. It is easy to install the latest versions of `pip` and `pipenv` on Alpine, but they do not spontaneously work together. `pipenv` prefers the system version of `pip`, making recent features of `pip` (in this case `musl` support) unavailable.

**Comment by judilsteve** [comment]
This is affecting me at the moment. I'm trying to use pipenv to set up a venv for a python 3.6.8 project and it is using pip 22 (which requires python >= 3.7) and then every single dependency install fails. None of the workarounds posted here seem to work:

```
python3 -m pipenv sync --dev
Creating a virtualenv for this project...
Pipfile: /<redacted>/Pipfile
Using /<redacted>/.pyenv/versions/3.6.8/bin/python3.6m (3.6.8) to create virtualenv...
⠴ Creating virtual environment...created virtual environment CPython3.6.8.final.0-64 in 269ms
  creator CPython3Posix(dest=/<redacted>/.local/share/virtualenvs/<redacted>, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=20.0.1, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/<redacted>/.local/share/virtualenv)
    added seed packages: pip==22.0.3, setuptools==60.7.1, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /<redacted>/.local/share/virtualenvs/<redacted>
Installing dependencies from Pipfile.lock (b017cf)...
An error occurred while installing attrs==21.4.0 --hash=sha256:2d27e3784d7a565d36ab851fe94887c5eccd6a463168875832a1be79c82828b4 --hash=sha256:626ba8234211db98e869df76230a137c4c40a12d72445c45d5f5b716f076e2fd! Will try again.
```

Is there a definitive way to force a particular version of the seed packages in pipenv in 2022?
