### ISSUE TITLE
Version specifier ignored when using --skip-lock

### ISSUE THREAD

**Issue by davehunt** [pypa/pipenv#3149]
### Issue description

When using `--skip-lock` exact version specifiers in `Pipfile` can be ignored.

### Expected result

flake8 v3.5.0 to be installed.

### Actual result

flake8 v3.6.0 (latest) is installed.

### Steps to replicate

1. Install flake8 v3.5.0 and flake8-isort v2.5 and verify the correct versions are installed:

```
$ pipenv install flake8==3.5.0 flake8-isort==2.5
$ pipenv graph
flake8-isort==2.5
  - flake8 [required: >=3.2.1, installed: 3.5.0]
    - mccabe [required: >=0.6.0,<0.7.0, installed: 0.6.1]
    - pycodestyle [required: >=2.0.0,<2.4.0, installed: 2.3.1]
    - pyflakes [required: >=1.5.0,<1.7.0, installed: 1.6.0]
  - isort [required: >=4.3.0, installed: 4.3.4]
  - testfixtures [required: Any, installed: 6.3.0]
```

2. Remove the virtual environment and install with `--skip-lock`:

```
$ pipenv --rm
$ pipenv install --skip-lock
```

3. Wrong version of flake8 is installed:

```
$ pipenv graph
flake8-isort==2.5
  - flake8 [required: >=3.2.1, installed: 3.6.0]
    - mccabe [required: >=0.6.0,<0.7.0, installed: 0.6.1]
    - pycodestyle [required: >=2.4.0,<2.5.0, installed: 2.4.0]
    - pyflakes [required: >=2.0.0,<2.1.0, installed: 2.0.0]
    - setuptools [required: >=30, installed: 40.5.0]
  - isort [required: >=4.3.0, installed: 4.3.4]
  - testfixtures [required: Any, installed: 6.3.0]
```

Pipfile:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"flake8" = "==3.5.0"
"flake8-isort" = "==2.5"

[dev-packages]

[requires]
python_version = "3.7"
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.13'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.10.13/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.10.13/libexec/bin/python3.7'`

Python installations found:

  - `3.7.0`: `/Users/dhunt/.pyenv/shims/python3`
  - `3.7.0`: `/Users/dhunt/.pyenv/shims/python`
  - `3.7.0`: `/Users/dhunt/.pyenv/shims/python3.7m`
  - `3.7.0`: `/Users/dhunt/.pyenv/shims/python3.7`
  - `3.7.0`: `/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/bin/python3.7`
  - `3.7.0`: `/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/bin/python3.7m`
  - `3.6.5`: `/Users/dhunt/.pyenv/shims/python3.6`
  - `3.6.5`: `/Users/dhunt/.pyenv/shims/python3.6m`
  - `3.5.5`: `/Users/dhunt/.pyenv/shims/python3.5m`
  - `3.5.5`: `/Users/dhunt/.pyenv/shims/python3.5`
  - `3.4.8`: `/Users/dhunt/.pyenv/shims/python3.4m`
  - `3.4.8`: `/Users/dhunt/.pyenv/shims/python3.4`
  - `2.7.15`: `/Users/dhunt/.pyenv/shims/python2`
  - `2.7.15`: `/Users/dhunt/.pyenv/shims/python2.7`
  - `2.7.15`: `/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7`
  - `2.7.13`: `/Users/dhunt/.pyenv/shims/pypy`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.0.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT '
                     '2018; root:xnu-4903.201.2~1/RELEASE_X86_64',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `SPACESHIP_VERSION`
  - `TERM_PROGRAM`
  - `NVM_CD_FLAGS`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `NVM_DIR`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `PYENV_VIRTUALENV_INIT`
  - `PAGER`
  - `LSCOLORS`
  - `_`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `SPACESHIP_ROOT`
  - `XPC_SERVICE_NAME`
  - `PYENV_SHELL`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `LC_CTYPE`
  - `NVM_BIN`
  - `DISPLAY`
  - `COLORTERM`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.10.13/libexec/tools:/Users/dhunt/.local/bin:/Users/dhunt/.nvm/versions/node/v6.11.1/bin:/Users/dhunt/.cargo/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.3/shims:/Users/dhunt/.pyenv/shims:/Users/dhunt/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin::/Users/dhunt/workspace/arcanist/bin/`
  - `SHELL`: `/usr/local/bin/zsh`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/dhunt/workspace/pipenv-scratchpad`

---------------------------

Contents of `Pipfile` ('/Users/dhunt/workspace/pipenv-scratchpad/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"flake8" = "==3.5.0"
"flake8-isort" = "==2.5"

[dev-packages]

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/Users/dhunt/workspace/pipenv-scratchpad/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "b25a6b58721193cd6d46cd7964a3b4ffaf06a8d3cee21cd48393225b3af882d2"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "flake8": {
            "hashes": [
                "sha256:7253265f7abd8b313e3892944044a365e3f4ac3fcdcfb4298f55ee9ddf188ba0",
                "sha256:c7841163e2b576d435799169b78703ad6ac1bbb0f199994fc05f700b2a90ea37"
            ],
            "index": "pypi",
            "version": "==3.5.0"
        },
        "flake8-isort": {
            "hashes": [
                "sha256:298d7904ac3a46274edf4ce66fd7e272c2a60c34c3cc999dea000608d64e5e6e",
                "sha256:5992850626ce96547b1f1c7e8a7f0ef49ab2be44eca2177934566437b636fa3c"
            ],
            "index": "pypi",
            "version": "==2.5"
        },
        "isort": {
            "hashes": [
                "sha256:1153601da39a25b14ddc54955dbbacbb6b2d19135386699e2ad58517953b34af",
                "sha256:b9c40e9750f3d77e6e4d441d8b0266cf555e7cdabdcff33c4fd06366ca761ef8",
                "sha256:ec9ef8f4a9bc6f71eec99e1806bfa2de401650d996c59330782b89a5555c1497"
            ],
            "version": "==4.3.4"
        },
        "mccabe": {
            "hashes": [
                "sha256:ab8a6258860da4b6677da4bd2fe5dc2c659cff31b3ee4f7f5d64e79735b80d42",
                "sha256:dd8d182285a0fe56bace7f45b5e7d1a6ebcbf524e8f3bd87eb0f125271b8831f"
            ],
            "version": "==0.6.1"
        },
        "pycodestyle": {
            "hashes": [
                "sha256:682256a5b318149ca0d2a9185d365d8864a768a28db66a84a2ea946bcc426766",
                "sha256:6c4245ade1edfad79c3446fadfc96b0de2759662dc29d07d80a6f27ad1ca6ba9"
            ],
            "version": "==2.3.1"
        },
        "pyflakes": {
            "hashes": [
                "sha256:08bd6a50edf8cffa9fa09a463063c425ecaaf10d1eb0335a7e8b1401aef89e6f",
                "sha256:8d616a382f243dbf19b54743f280b80198be0bca3a5396f1d2e1fca6223e8805"
            ],
            "version": "==1.6.0"
        },
        "testfixtures": {
            "hashes": [
                "sha256:334497d26344e8c0c5d01b4d785a1c83464573151e6a5f7ab250eb7981d452ec",
                "sha256:53c06c1feb0bf378d63c54d1d96858978422d5a34793b39f0dcb0e44f8ec26f4"
            ],
            "version": "==6.3.0"
        }
    },
    "develop": {}
}

```
</details>

**Comment by techalchemy** [comment]
Can you try the latest master branch and let us know if this still occurs?

**Comment by techalchemy** [comment]
This appears to be fixed, closing for now (feel free to reopen if you continue to experience it)

Thanks for the report!

**Comment by sethmlarson** [comment]
Having this problem again with the latest Pipenv when specifying and upper and lower bound to a dependency version.

`Pipfile` contains `pytest>2.8.0,<4.1` yet `pytest==4.1.1` gets installed when using `--skip-lock`.
https://travis-ci.org/requests/requests/jobs/481796912

**Comment by wlievens** [comment]
I'm having this issue too, making pipenv basically useless for me.
