### ISSUE TITLE
A few issues related with respect --skip-lock option for uninstall

### ISSUE THREAD

**Issue by jxltom** [pypa/pipenv#3174]
### Issue description

In https://github.com/pypa/pipenv/commit/714ff657ca6d0888b932cdffc6fc768e7c9cb6ca commit, I got confused in several places.

1.  For now, even ```pipenv lock``` have ```--skip-lock``` option? This option does not exist for any released pipenv versions. It is introduced in https://github.com/pypa/pipenv/blob/3ce8d7c6bb8007f93f011bd0a7c32b3e977d379f/pipenv/cli/options.py#L356.

2. According to the doc, ```pipenv uninstall --all``` will purge all files from the virtual environment, but **leave the Pipfile untouched**. But for now, from this code https://github.com/pypa/pipenv/blob/master/pipenv/core.py#L2115-L2133, the pipfile and pipfile.lock will be updated anyway.

3. A ```@option("--skip-lock/--lock", is_flag=True, default=False, help="Lock afterwards.")``` is introduced in https://github.com/pypa/pipenv/blob/3ce8d7c6bb8007f93f011bd0a7c32b3e977d379f/pipenv/cli/command.py#L256 which confused me. A ```skip-lock``` option is already added by ```@uninstall_options```. Besides, it looks like this option is not passed into ```do_uninstall``` which means it does not work at all.

Let me know if I'm wrong. :smile: :handshake: 

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by techalchemy** [comment]
> For now, even pipenv lock have --skip-lock option

This was added and not removed as an oversight while I was experimenting with exporting pipfile entries to `requirements.txt` format (currently done via `pipenv lock`, so avoiding the lock operation during export would be quite odd) -- definitely want this removed

> According to the doc, pipenv uninstall --all will purge all files from the virtual environment, but leave the Pipfile untouched.

When was that added to the documentation? That makes no sense, `uninstall` removes things from the pipfile in every other case...

> A skip-lock option is already added by @uninstall_options. 

Right, but it doesn't work, and I wanted an explicit flag to toggle

> Besides, it looks like this option is not passed into do_uninstall which means it does not work at all.

Right, but I want to always accept `--skip-lock` or `lock` and have it operationally used on [line 289](https://github.com/pypa/pipenv/blob/3ce8d7c6/pipenv/cli/command.py#L289):

```python
 lock=not skip_lock,
```

which is in fact used [here](https://github.com/pypa/pipenv/blob/master/pipenv/core.py#L2102)

```python
        removed = package_names - bad_pkgs
        if pipfile_remove:
            project.remove_packages_from_pipfile(removed)
            if lock:
                do_lock(system=system, keep_outdated=keep_outdated, pypi_mirror=pypi_mirror)
            else:
                lockfile = project.get_or_create_lockfile()
                for key in lockfile.default.keys():
                    del lockfile.default[key]
                for key in lockfile.develop.keys():
                    del lockfile.develop[key]
                lockfile.write()
```

**Comment by jxltom** [comment]
Thanks a lot for the explanation. So these issues are just because they're still in development.

Only the ```pipenv uninstall --all``` looks a little bit serious. Check doc here https://github.com/pypa/pipenv/blob/19609340b9425eb73b4b814a857dd7920ead4acb/docs/basics.rst, it said ```--all — This parameter will purge all files from the virtual environment, but leave the Pipfile untouched.```

**Comment by techalchemy** [comment]
@jxltom yeah this is a really important issue and I want to make sure we get this right, I feel like the API is a little awkward here though.  I want to track down the discussion we must have had before we made these decisions though

**Comment by techalchemy** [comment]
Hmm seems like that was Kenneth's call.  I don't want to make breaking changes for no reason so lets make sure we don't screw that up.  Thanks for catching it.

**Comment by jxltom** [comment]
The APIs do look a littile bit strange here. But the functionability makes sense. 

```pipenv uninstall somepackage``` will uninstall package and update the lockfiles. ```pipenv uninstall --all-dev``` will uninstall all dev pacakges and update lockfiles. ```pipenv uninstall --all``` will uninstall all but leave pipfiles untouched.

I believe this design is just to let users re-have a clean virtualenv without changing the pipfiles. It makes sense to having this ability.
