### ISSUE TITLE
Additional output of success when editable packages in Pipfile

### ISSUE THREAD

**Issue by jxltom** [pypa/pipenv#3183]
### Issue description

If editable packages are in Pipfile such as the following simple Pipfile, the ```pipenv lock``` will lock twice and output two ```success!``` info.

```
[packages]
requests = {git = "https://github.com/requests/requests", editable = true}
```

Here is the output.

```
➜  pipenv lock
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
✔ Success! 
✔ Success! 
```

It is because there are two seprate ```venv_resolve_deps``` process (one for normal packages https://github.com/pypa/pipenv/blob/707cca969370b4f9fcb399af5a8f42d0cfe22b2a/pipenv/core.py#L1031, one for editable packages in https://github.com/pypa/pipenv/blob/707cca969370b4f9fcb399af5a8f42d0cfe22b2a/pipenv/core.py#L1059) which will both calling spinner and finally output the ```success!``` message.

Besides, It also takes a while for ```get_vcs_deps``` to process. But there is no spinner for this method and this makes gap which has not status in shell at all between two ```get_vcs_deps``` processes

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.14.dev0'`

Pipenv location: `'/home/user/Documents/dev/pipenv/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.6.5`: `/home/user/.pyenv/versions/3.6.5/bin/python3.6m`
  - `3.6.6`: `/home/user/.pyenv/versions/3.6.6/bin/python3`
  - `2.7.15`: `/home/user/.pyenv/versions/2.7.15/bin/python2.7`
  - `3.6.4`: `/home/user/.pyenv/versions/3.6.4/bin/python3.6m`
  - `3.6.5`: `/home/user/.pyenv/versions/3.6.5/bin/python3.6`
  - `3.6.6`: `/home/user/.pyenv/versions/3.6.6/bin/python3.6m`
  - `3.5.2`: `/usr/bin/python3.5m`
  - `3.5.5`: `/home/user/.pyenv/versions/3.5.5/bin/python3.5m`
  - `3.6.4`: `/home/user/.pyenv/versions/3.6.4/bin/python3.6`
  - `2.7.14`: `/home/user/.pyenv/versions/2.7.14/bin/python2.7`
  - `3.6.3`: `/home/user/.pyenv/versions/3.6.3/bin/python3`
  - `3.5.5`: `/home/user/.pyenv/versions/3.5.5/bin/python`
  - `2.7.12`: `/usr/bin/python`
  - `3.6.3`: `/home/user/.pyenv/versions/3.6.3/bin/python3.6m`
  - `3.5.2`: `/usr/bin/python3.5`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-38-generic',
 'platform_system': 'Linux',
 'platform_version': '#41~16.04.1-Ubuntu SMP Wed Oct 10 20:16:04 UTC 2018',
 'python_full_version': '2.7.12',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `LESS`
  - `UPSTART_EVENTS`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_SESSION_TYPE`
  - `LC_PAPER`
  - `SHELL`
  - `PYENV_SHELL`
  - `XDG_DATA_DIRS`
  - `MANDATORY_PATH`
  - `COMPIZ_CONFIG_PROFILE`
  - `UNITY_DEFAULT_PROFILE`
  - `NVM_BIN`
  - `UPSTART_INSTANCE`
  - `JOB`
  - `XMODIFIERS`
  - `JAVA_HOME`
  - `GTK2_MODULES`
  - `XDG_RUNTIME_DIR`
  - `LC_ADDRESS`
  - `LC_CTYPE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `QT_ACCESSIBILITY`
  - `DBUS_STARTER_BUS_TYPE`
  - `XDG_SESSION_ID`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DEFAULTS_PATH`
  - `DESKTOP_SESSION`
  - `GTK_MODULES`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `INSTANCE`
  - `LC_NAME`
  - `XDG_MENU_PREFIX`
  - `LS_COLORS`
  - `GOPATH`
  - `DBUS_STARTER_ADDRESS`
  - `GNOME_DESKTOP_SESSION_ID`
  - `XDG_CURRENT_DESKTOP`
  - `USER`
  - `XDG_VTNR`
  - `PYENV_VIRTUALENV_INIT`
  - `XAUTHORITY`
  - `LANGUAGE`
  - `SESSION_MANAGER`
  - `LC_MEASUREMENT`
  - `QT_QPA_PLATFORMTHEME`
  - `CLUTTER_IM_MODULE`
  - `WINDOWID`
  - `GPG_AGENT_INFO`
  - `LANG`
  - `GDMSESSION`
  - `UPSTART_JOB`
  - `XDG_SEAT_PATH`
  - `PIP_PYTHON_PATH`
  - `_`
  - `GTK_IM_MODULE`
  - `XDG_CONFIG_DIRS`
  - `QT_VERSION`
  - `PIP_SHIMS_BASE_MODULE`
  - `LC_TIME`
  - `PAGER`
  - `XDG_GREETER_DATA_DIR`
  - `QT4_IM_MODULE`
  - `NVM_DIR`
  - `HOME`
  - `DISPLAY`
  - `XDG_SESSION_DESKTOP`
  - `QT_DIR`
  - `CONDA_SHLVL`
  - `LC_MONETARY`
  - `QT_LINUX_ACCESSIBILITY_ALWAYS_ON`
  - `LC_IDENTIFICATION`
  - `VTE_VERSION`
  - `UPSTART_SESSION`
  - `GNOME_KEYRING_PID`
  - `LC_NUMERIC`
  - `NVM_CD_FLAGS`
  - `UNITY_HAS_3D_SUPPORT`
  - `QT_IM_MODULE`
  - `LOGNAME`
  - `XDG_SEAT`
  - `GNOME_KEYRING_CONTROL`
  - `PATH`
  - `ZSH`
  - `TERM`
  - `XDG_SESSION_PATH`
  - `DBUS_DEBUG_OUTPUT`
  - `SESSIONTYPE`
  - `IM_CONFIG_PHASE`
  - `SSH_AUTH_SOCK`
  - `LSCOLORS`
  - `OLDPWD`
  - `GDM_LANG`
  - `LC_TELEPHONE`
  - `SHLVL`
  - `PWD`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/user/.nvm/versions/node/v10.11.0/bin:/home/user/.pyenv/plugins/pyenv-virtualenv/shims:/home/user/.pyenv/shims:/home/user/.pyenv/bin:/home/user/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/user/go/bin:/home/user/jdk1.8.0_171/bin:/home/user/apache-maven-3.5.3/bin:/home/user/flutter/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/user/Desktop/Untitled Folder 3`

---------------------------

Contents of `Pipfile` ('/home/user/Desktop/Untitled Folder 3/Pipfile'):

```toml
[packages]
requests = {git = "https://github.com/requests/requests", editable = true}


```

Contents of `Pipfile.lock` ('/home/user/Desktop/Untitled Folder 3/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "0219fdc968ac7ad92d35f4030d15cd01cc74163f7b0f4dea98d38c52a8d65c75"
        },
        "pipfile-spec": 6,
        "requires": {},
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "certifi": {
            "hashes": [
                "sha256:339dc09518b07e2fa7eda5450740925974815557727d6bd35d319c1524a04a4c",
                "sha256:6d58c986d22b038c8c0df30d639f23a3e6d172a05c3583e766f4c0b785c0986a"
            ],
            "version": "==2018.10.15"
        },
        "chardet": {
            "hashes": [
                "sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae",
                "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691"
            ],
            "version": "==3.0.4"
        },
        "idna": {
            "hashes": [
                "sha256:156a6814fb5ac1fc6850fb002e0852d56c0c8d2531923a51032d1b70760e186e",
                "sha256:684a38a6f903c1d71d6d5fac066b58d7768af4de2b832e426ec79c30daa94a16"
            ],
            "version": "==2.7"
        },
        "requests": {
            "editable": true,
            "git": "https://github.com/requests/requests",
            "ref": "c501ec986daa4961cd9dee370b5d45ff2e524b37"
        },
        "urllib3": {
            "hashes": [
                "sha256:61bf29cada3fc2fbefad4fdf059ea4bd1b4a86d2b6d15e1c7c0b582b9752fe39",
                "sha256:de9529817c93f27c8ccbfead6985011db27bd0ddfcdb2d86f3f663385c6a9c22"
            ],
            "version": "==1.24.1"
        }
    },
    "develop": {}
}

```
</details>

**Comment by techalchemy** [comment]
Nice, I’ve been wondering about that! Thanks for tracking it down.
