### ISSUE TITLE
transitive dependencies don't honor conditionals of required package

### ISSUE THREAD

**Issue by belm0** [pypa/pipenv#3193]
### Issue description

I have a package with an `os_name` condition in my Pipfile:
```
cffi = {version = "*", os_name = "=='nt'"}
```
pipenv adds the package to Pipfile.lock, which is expected.  When installing (e.g. `pipenv sync`), there is a message about skipping install of the package which doesn't match:
```
Ignoring cffi: markers 'os_name == "nt"' don't match your environment
```
Fine so far.  However, the conditional package has a dependency (pycparser).  `pipenv sync` installs the dependency despite the required package not matching my environment.

### Expected result

pipenv should not install transitive dependencies of packages which don't match the environment

### Actual result

pipenv is installing transitive dependencies (pycparser in this case)

**Comment by belm0** [comment]
Pipfile diff:
```
+cffi = {version = "*", os_name = "=='nt'"}
```
Pipfile.lock diff:
```
         },
+        "cffi": {
+            "hashes": [
+                "sha256:151b7eefd035c56b2b2e1eb9963c90c6302dc15fbd8c1c0a83a163ff2c7d7743",
...
+            ],
+            "index": "pypi",
+            "markers": "os_name == 'nt'",
+            "version": "==1.11.5"
+        },
...
+        "pycparser": {
+            "hashes": [
+                "sha256:a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3"
+            ],
+            "version": "==2.19"
+        },

**Comment by techalchemy** [comment]
I agree with you, but what version of pipenv is this

**Comment by belm0** [comment]
Pipenv version: `'2018.10.13'`

**Comment by MatthewWilkes** [comment]
I'm having the same issue with declaring a conditional dependency on https://github.com/adafruit/Adafruit_circuitpython_dht

That has an indirect dependency on a package that involves building C modules that does not work on Windows. I've reported that should be a conditional dependency, but I do feel that the condition applied to a package should apply to any dependencies that aren't otherwise declared.

**Comment by andreparames** [comment]
Hi, we're hitting the same bug (trying to import `pyobjc` only on macOS). Has there been any movement in this ticket? If not, I may have a crack at it this weekend.

**Comment by matteius** [comment]
Could this be rechecked with `pipenv==2022.8.19`?  There is a fair chance it is still an issue, but I am trying to hone in on which old issue reports are still relevant.
