### ISSUE TITLE
What is the meaning of colors?

### ISSUE THREAD

**Issue by akiross** [pypa/pipenv#3195]
Colors are so nice, but what is their meaning?

Running `pipenv -h` I can see that some commands are in red, some are in green, or yellow or purple, but I [could](https://pipenv.readthedocs.io/en/latest/advanced/) [not](https://pipenv.readthedocs.io/en/latest/basics/) [find](https://pipenv.readthedocs.io/en/latest/search/?q=color) anywhere in the doc a description about what each color means (sorry if I missed it!).

I suspect the color is associated with the effects of the commands (e.g. in red they do not modify Pipenv or Pipenv.lock, in green they will edit both, in purple they will modify only Pipenv), but this is not obvious as it should be.

Is it possible to clarify this and include it clearly in the docs?

**Comment by techalchemy** [comment]
The colors in the help text are for flavor. There is no meaning behind them.

**Comment by akiross** [comment]
Well, that's not optimal!
I propose to make them meaningful. What about the idea I got of having them colored depending on how they affect Pipfile and Pipfile.lock?
