### ISSUE TITLE
Options to support running in a fully automated mode

### ISSUE THREAD

**Issue by ernstp** [pypa/pipenv#3219]
Scenario: You want to run python code with Pipfiles on a random build agent (i.e. Jenkins agent) with unknown state. You also want to use pipenv's caching features to speed up setup.

My idea was to do "pipenv sync && pipenv run python main.py".

This gets you quite far, however you will get errors like this when your Pipfile has changed:
Warning: Your Pipfile requires python_version 3.6, but you are using 3.4.9 (/home/ernsjo/.local/share/v/p/bin/python).

pipenv install --deploy doesn't help either.

So if you want to automate something with pipenv today, you basically have to run
`pipenv --rm`
every single time, which seems to defeat a big part of the features of the project.

I guess what I'm looking for is "pipenv sync --recreate-venv-if-python-version-mismatch".

(The "--three / --two / --python" options are interesting, their documentation is actually a bit off. They are actually "force recreation of the virtualenv with this python version".)

**Comment by ernstp** [comment]
I guess this works but it's not very pretty:
`pipenv install --deploy || (pipenv --rm && pipenv install --deploy) && pipenv run python main.py`

**Comment by matteius** [comment]
Not currently planned.
