### ISSUE TITLE
2018.11.14 regression: pipenv install --system ignore PIPENV_PIPFILE

### ISSUE THREAD

**Issue by abusque** [pypa/pipenv#3234]
### Issue description

When using the `--system` flag, `pipenv install` will ignore any value of `PIPENV_PIPFILE` and try to install from `Pipfile` or `Pipfile.lock`.

### Expected result

The expected result (and behaviour up to and including 2018.10.13) is for `PIPENV_PIPFILE=Pipfile-foo pipenv install --system` to install from `Pipfile-foo`, and not `Pipfile`, which may or may not exist.

### Actual result

Running `PIPENV_PIPFILE=Pipfile-foo pipenv install --system` will install from `Pipfile` instead of `Pipfile-foo`.

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------
 
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.14'`

Pipenv location: `'/usr/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.7.1`: `/usr/bin/python3.7m`
  - `3.7.1`: `/usr/bin/python`
  - `3.6.6`: `/home/abusque/.pyenv/versions/3.6.6/bin/python3.6m`
  - `3.6.6`: `/home/abusque/.pyenv/versions/3.6.6/bin/python`
  - `2.7.15`: `/usr/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.1',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.19.1-arch1-1-ARCH',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Sun Nov 4 16:49:26 UTC 2018',
 'python_full_version': '3.7.1',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LANG`
  - `DISPLAY`
  - `PYENV_ROOT`
  - `OLDPWD`
  - `INVOCATION_ID`
  - `EDITOR`
  - `GPG_TTY`
  - `COLORTERM`
  - `PYENV_VIRTUALENV_INIT`
  - `PYENV_HOOK_PATH`
  - `XDG_VTNR`
  - `SSH_AUTH_SOCK`
  - `XDG_SESSION_ID`
  - `USER`
  - `PYENV_DIR`
  - `PWD`
  - `HOME`
  - `JOURNAL_STREAM`
  - `BROWSER`
  - `PYENV_VERSION`
  - `MAIL`
  - `WINDOWPATH`
  - `TERM`
  - `SHELL`
  - `COLORFGBG`
  - `XDG_SEAT`
  - `SHLVL`
  - `PYENV_SHELL`
  - `WINDOWID`
  - `wspc`
  - `wspl`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `PATH`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/bin:/home/abusque/.pyenv/libexec:/home/abusque/.pyenv/plugins/python-build/bin:/home/abusque/.pyenv/plugins/pyenv-virtualenv/bin:/home/abusque/.pyenv/plugins/pyenv-update/bin:/home/abusque/.pyenv/plugins/pyenv-installer/bin:/home/abusque/.pyenv/plugins/pyenv-doctor/bin:/home/abusque/.pyenv/plugins/pyenv-virtualenv/shims:/home/abusque/.pyenv/shims:/home/abusque/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/abusque/.config/composer/vendor/bin:/home/abusque/.local/bin/:/home/abusque/.config/composer/vendor/bin:/home/abusque/.local/bin/`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `emacs`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/abusque`

---------------------------

</details>

**Comment by jxltom** [comment]
Similar with https://github.com/pypa/pipenv/issues/3228

**Comment by abusque** [comment]
One thing I should perhaps make more explicit is that `PIPENV_PIPFILE=Pipfile-foo pipenv install` worked fine in my testing, only the addition of `--system` triggered the issue.
