### ISSUE TITLE
2018.11.14 regression: Installing Multiple local editable packages leaves some unusable

### ISSUE THREAD

**Issue by christek91** [pypa/pipenv#3236]
### Issue description

We use pipenv to install five packages from local directories as 'editable' packages. In the most recent version of pipenv we see that when we do a `pipenv install` of those packages they report success and appear to succeed in the logs. However, we are unable to import them due to `ModuleNotFoundError: No module named XXX`. 

### Expected result

We are used to being able to install all five local editable packages, and then being able to import them in code that uses the virtualenv.

### Actual result

Pipenv installs and reports exit code 0. However, importing modules gives a `ModuleNotFoundError`.

The logs report no errors, and verbose logs show the same actions being performed in the older and newer versions of pipenv. 

### Steps to replicate

Create a Pipfile that has 3 or more entries of the form:
```
"my_module" = {path = "./path/to/module", editable = true}
```

Then run `pipenv install` and try to import all those modules. You will likely get the import error.

-------------------------------------------------------------------------------

Rather than paste the `pipenv --support output`, I've actually already got a fix and a test for it ready to go. 

I spent enough time going down the rabbit hole today that I figured I'd take a pass at fixing it. I'll update the issue w/ the PR in a second.

**Comment by frostming** [comment]
Close in honor of #3237
