### ISSUE TITLE
Unable to lock from private PyPI

### ISSUE THREAD

**Issue by amancevice** [pypa/pipenv#3244]
I am currently unable to lock my Pipfile when using our private PyPI sources on `2018.11.14`. This issue hadn't appeared on prior versions of pipenv. I suppose it's possible that our private PyPI sources are the problem, but I'm not sure what could be happening.

This is an example `Pipfile` that causes the error:

```
[[source]]
url = "http://<private-pypi-host>/simple/"
verify_ssl = false
name = "private-pypi"

[packages]
moto = "==1.3.6"

[dev-packages]

[requires]
```

Running `pipenv install` yields the following logs:

```
Creating a virtualenv for this project…
Pipfile: /Pipfile
Using /usr/local/bin/python (3.7.1) to create virtualenv…
✔ Complete 
Already using interpreter /usr/local/bin/python
Using base prefix '/usr/local'
New python executable in /root/.local/share/virtualenvs/-x-v5uFv0/bin/python
Installing setuptools, pip, wheel...
done.
Virtualenv location: /root/.local/share/virtualenvs/-x-v5uFv0
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/pexpect/expect.py", line 109, in expect_loop
    return self.timeout()
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f85959d7f98>
searcher: searcher_re:
    0: re.compile('\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/cli/command.py", line 249, in install
    editable_packages=state.installstate.editables,
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1872, in do_install
    keep_outdated=keep_outdated
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1223, in do_init
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1047, in do_lock
    lockfile=lockfile
  File "/usr/local/lib/python3.7/site-packages/pipenv/utils.py", line 620, in venv_resolve_deps
    c = resolve(cmd, sp)
  File "/usr/local/lib/python3.7/site-packages/pipenv/utils.py", line 503, in resolve
    result = c.expect(u"\n", timeout=environments.PIPENV_TIMEOUT)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/delegator.py", line 215, in expect
    self.subprocess.expect(pattern=pattern, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f85959d7f98>
searcher: searcher_re:
    0: re.compile('\n')
<pexpect.popen_spawn.PopenSpawn object at 0x7f85959d7f98>
searcher: searcher_re:
    0: re.compile('\n')
```

Replacing the `[[source]]` section with the default appears to resolve the issue, but then I'm unable to install private pips.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.14'`

Pipenv location: `'/usr/local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Python installations found:

  - `3.7.1`: `/usr/local/bin/python`
  - `3.7.1`: `/usr/local/bin/python3.7m`
  - `3.5.3`: `/usr/bin/python3.5`
  - `3.5.3`: `/usr/bin/python3.5m`
  - `2.7.13`: `/usr/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.1',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.9.93-linuxkit-aufs',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Wed Jun 6 16:55:56 UTC 2018',
 'python_full_version': '3.7.1',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `PATH`
  - `HOSTNAME`
  - `TERM`
  - `LANG`
  - `GPG_KEY`
  - `PYTHON_VERSION`
  - `PYTHON_PIP_VERSION`
  - `HOME`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`

---------------------------

Contents of `Pipfile` ('/Pipfile'):

```toml
[[source]]
url = "http://public-pypi.service.dc1.consul/simple/"
verify_ssl = false
name = "public-pypi"

[packages]
moto = "==1.3.6"

[dev-packages]

[requires]

```

</details>

**Comment by persiyanov** [comment]
Having the same error, but when doing:
```
brew install pipenv
pipenv --three
pipenv install flask
```

**Comment by frostming** [comment]
Can you do `pipenv-resolver -v "moto==1.3.6"` and give the output?
Thanks

**Comment by amancevice** [comment]
```
$ pipenv-resolver -v "moto==1.3.6"
-bash: pipenv-resolver: command not found
```

**Comment by frostming** [comment]
Oh, that is probably because you install `pipenv` via `brew` or other isolated methods. It lies in the same location where the pipenv executable is.

**Comment by techalchemy** [comment]
I believe there is some subtlety here around private indexes -- if you remove pypi from the list of sources, you won't ever look in pypi during resolution.  This was always intended to be the behavior and if there isn't a changelog entry for it that was a big oversight and is probably my fault.

We don't assume you want to use pypi at all, so if you get rid of it we aren't going to check there.  All of your dependencies need to be in the sources you provide us.  If you want to include pypi in your resolution order, you need to include it in your pipfile below the private index you want to prioritize:

```
[[source]]
url = "http://<private-pypi-host>/simple/"
verify_ssl = false
name = "private-pypi"

[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"
```

Let me know if this solves your issue

**Comment by amancevice** [comment]
@techalchemy thanks I've omitted some info for brevity's sake that I realize now is confusing. I actually have two `[[source]]` entries in my `Pipfile`: Both are "private" in that they are deployed on our hardware, but one serves up a mirror of the public PyPI. So it looks like this:

```
[[source]]
url = "http://<private-pypi>/simple/"
verify_ssl = false
name = "private-pypi"

[[source]]
url = "http://<public-pypi>/simple/"
verify_ssl = false
name = "public-pypi"

[packages]
moto = "==1.3.6"

[dev-packages]

[requires]
```

**Comment by frostming** [comment]
> Here's the output of the `pipenv-resolver` command:
> 
> ```
> RESULTS:
> [{"version": "3.0.4", "hashes": ["sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae", "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691"], "name": "chardet"}, {"version": "2.2.1", "hashes": ["sha256:15bee753002dff684987b8df8c235288eb8d45f8191ae056254812dfd42c81d3", "sha256:d6b698788cae4cfa4e62ef8643a9ca332b79bd96cb314294b864ae8d7eb3ee8e"], "name": "cookies"}, {"version": "2.0.2", "hashes": ["sha256:391f860dbe274223d73dd87de25e4117bf09e8fe5f93a417663b1f2d7b591165", "sha256:3b35cdb0e55a88581ff6d3f12de753aa459e940b50fe7ca5aa25149bc94cb37b"], "name": "python-jose"}, {"version": "2018.7", "hashes": ["sha256:31cb35c89bd7d333cd32c5f278fca91b523b0834369e757f4c5641ea252236ca", "sha256:8e0f8568c118d3077b46be7d654cc8167fa916092e28320cde048e54bfc9f1e6"], "name": "pytz"}, {"version": "1.10.84", "hashes": ["sha256:380852e1adb9ba4ba9ff096af61f88a6888197b86e580e1bd786f04ebe6f9c0c", "sha256:d3e4b5a2c903ea30d19d41ea2f65d0e51dce54f4f4c4dfd6ecd7b04f240844a8"], "name": "botocore"}, {"version": "4.1", "hashes": ["sha256:a9b322285f419429402d5ce15e8f6d5c7a64f659eb87251af8b35c106f00a8e3"], "name": "pyyaml"}, {"version": "2.4.1", "hashes": ["sha256:03cc8bc5a69ae3d44acf1a03facdb7c10a94c67907862c563e10efe72b737977", "sha256:07f76bde6815c55195f3b3812d35769cc7c765144c0bb71ae45e02535d078591", "sha256:179bfb585c5efc87ae0e665770e4896727b92dbc1f810c761b1ebf8363e2fec8", "sha256:414af0ba308e74c1f8bc5b11befc86cb66b10be8959547786f64258830d2096f", "sha256:54947eb98bc4eef99ddf49f45d2694ea5a3929ab3edc9806ad01967368594d82", "sha256:5bac7a2abda07d0c3c8429210349bb54149ad8940dc7bcffedcd56519b410a3c", "sha256:7f41af8c586bed9f59cfe8832d818b3b75c860d7025da9cd2db76875a72ff785", "sha256:8004fae1b3cb2dbd90a011ad972e49a7e78a871b89c70cc7213cf4ebd2532bcb", "sha256:8e0eccadc3b465e12c50a5b8fb4d39cf401b44d7bb9936c70fddb5e5aaf740d5", "sha256:95b4741722269cfdc134fec23b7ae6503ee2aea83d0924cfee6d6ec54cd42d8e", "sha256:b0833d27c7eb536bc27323a1e8e22cb39ebac78c4ef3be0167ba40f447344808", "sha256:c800ddc23b5206ce025f23225fdde89cdc0e64016ad914d5be32d1f602ce9495", "sha256:c980c8c313a5e014ae12e2245e89e7b30427e5a98cbb88afe478ecae85f3abaa", "sha256:e85b410885addaeb31a867eabcefc9ef4a7e904ad45eac9e60a763a54b244626"], "name": "cryptography"}, {"version": "0.1.13", "hashes": ["sha256:90dc18e028989c609146e241ea153250be451e05ecc0c2832565231dacdf59c1", "sha256:c7a9ec356982d5e9ab2d4b46391a7d6a950e2b04c472419f5fdec70cc0ada72f"], "name": "s3transfer"}, {"version": "0.3.0", "hashes": ["sha256:0a941b290764ea7286bd77f54c0ace43b86a8acd6eb9ead3de9840af52384079", "sha256:8b0e956c8d206f832b06aa93a710ba2c3bcbacb5a314449c040b0b814355bbff"], "name": "docker-pycreds"}, {"version": "1.11.0", "hashes": ["sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9", "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"], "name": "six"}, {"version": "1.7.84", "hashes": ["sha256:0ed4b107c3b4550547aaec3c9bb17df068ff92d1f6f4781205800e2cb8a66de5", "sha256:64496f2c814e454e26c024df86bd08fb4643770d0e2b7a8fd70055fc6683eb9d"], "name": "boto3"}, {"version": "0.14", "hashes": ["sha256:02aec4bd92ab067f6ff27a38a38a41173bf01bed8f89157768c1573f53e474a6", "sha256:51e64ef2ebfb29cae1faa133b3710143496eca21c530f3f71424d77687764274", "sha256:7a4bd47eaf6596e1295ecb11361139febe29b084a87bf005bf899f9a42edc3c6"], "name": "docutils"}, {"version": "2.0.0", "hashes": ["sha256:5ce3c71c5545b472da17b72268978914d0252980348636840bd34a00b5cc96c1", "sha256:b158b6df76edd239b8208d481dc46b6afd45a846b7812ff0ce58971cf5bc8bba"], "name": "mock"}, {"version": "2.10", "hashes": ["sha256:74c935a1b8bb9a3947c50a54766a969d4846290e1e788ea44c1392163723c3bd", "sha256:f84be1bb0040caca4cea721fcbbbbd61f9be9464ca236387158b0feea01914a4"], "name": "jinja2"}, {"version": "0.11.0", "hashes": ["sha256:8f8d7d40aa28d83f4109a7e8aa86e67a4df202d9538be40c0cb1d70da527b0df", "sha256:add07d92089ff611badec526912747cf87afd4f9447af6661aca074eeaf32615"], "name": "xmltodict"}, {"version": "0.24.0", "hashes": ["sha256:2f1adbb7546ed199e3c90ef23ec95c5cf3585bac7d11fb7eb562a3fe89c64e87", "sha256:9d5c20441baf0cb60a4ac34cc447c6c189024b6b4c6cd7877034f4965c464e49"], "name": "asn1crypto"}, {"version": "3.7.0", "hashes": ["sha256:04eda25b5260562dc67557758bcded8693e68d2960063de5645565e633d8aa80", "sha256:1fead738aab86a427826dd63e5f95dac59c7a94bf3e68329461b903450248736", "sha256:36e89ed59cbaca1e74aedfa844859f5181809eb3983de0b66860980a8596dcd3", "sha256:4444a26fc3830c0d438bca6975ff10d1eb9c0b88f747fdc25b5ab81fb46713d7", "sha256:54789e4f2c60f5c37f9e43b688d51965fab65ce3e9e352ff8ee03543ec7eef58", "sha256:70b8757a7df5a993c778bebf29583b7cb77fa80975ab383381d1fb89717f4e46", "sha256:7e4554a2248773477ff61bae461ab301cbf1e1c21efeda0368ac410a0ff2fb68", "sha256:820dd2404241ef14134f28a1f8f47ea7e323c32763890f463412fe76175d1897", "sha256:86c82278471431deba734f439555ef260f7d84072568268eea654c2beb7568dd", "sha256:881f88bf088985dce9cd9eff9c926deba2ff1fe0ae206d58acfb7059c00fb913", "sha256:8c71bdfae281a741d369a6203d63eba99cf9ee96cf64cd02b40b44db8b8253bd", "sha256:8fe36931e7c5cb5483e97e5f68f34bc4f4be6e976d1fbb2ff502f763874e7919", "sha256:93390e353d6f557dc383c4c907d7b5009b92d6adcbdc2c1d89dcb7e2cb4cbb8e", "sha256:9e6b94f2ee0aa6613157fc22c6fb71f7f11c6c895df35d9e7f8977d0d29da57c", "sha256:acd75781622231fd00aecbd60494aacae54e7afee67ad89e8e22a04a411c07e1", "sha256:b68975f6f88cba021b4286f2c2f8ae863a3b831490964f2a4771193fad1f6fcf", "sha256:b6a574d71988ed01c36150ca7a54904eb93be8c3fa0aac6c646fc01bdeaee9ca", "sha256:bbbc5803c5c7a63e560672ff8f292e1ecc63477983fc9b705aaefdd0b12f29f4", "sha256:da6527b8b3ec022fb9d142652126fdeb9ce8521ef6cadbb1e762d1ef75be6f35", "sha256:dca327ec8750b5cb08bc2c3eecf629f46e4ec18a8ba318d0c6faf16ae53da0a6", "sha256:e37d42dad62fd75db3eb2af6236a234a177e0aca2b73fafa5d54aa1ebd74e936", "sha256:eb9b668dd9dddaa8f1bcd8052a80dea38c0c55a917c3dbe10f34b9882e6310f1", "sha256:f35b2aa23644a0b8b842b5237abee66dd225888dd4112613469ddcfe870da6dd"], "name": "pycryptodome"}, {"version": "2.7", "hashes": ["sha256:156a6814fb5ac1fc6850fb002e0852d56c0c8d2531923a51032d1b70760e186e", "sha256:684a38a6f903c1d71d6d5fac066b58d7768af4de2b832e426ec79c30daa94a16"], "name": "idna"}, {"version": "5.1.1", "hashes": ["sha256:f59d71442f9ece3dffc17bc36575768e1ee9967756e6b6535f0ee1f0054c3d68", "sha256:f6d5b23f226a2ba58e14e49aa3b1bfaf814d0199144b95d78458212444de1387"], "name": "pbr"}, {"version": "2018.10.15", "hashes": ["sha256:339dc09518b07e2fa7eda5450740925974815557727d6bd35d319c1524a04a4c", "sha256:6d58c986d22b038c8c0df30d639f23a3e6d172a05c3583e766f4c0b785c0986a"], "name": "certifi"}, {"version": "1.1.1", "hashes": ["sha256:2d0437782de9418efa34e694aa59f43d7adb1899bd9a793f063867ddba8f7893"], "name": "jsondiff"}, {"version": "1.3.6", "hashes": ["sha256:58fe0a0d55cbd9a001c02c146c15790cfcebf010c6648cb9990e6c3204709cbb", "sha256:a465b73d907531cd5bf4e550b71a2e22b718d646ed201852046ce0bfa7962c79"], "name": "moto"}, {"version": "2.20.1", "hashes": ["sha256:65b3a120e4329e33c9889db89c80976c5272f56ea92d3e74da8a463992e3ff54", "sha256:ea881206e59f41dbd0bd445437d792e43906703fff75ca8ff43ccdb11f33f263"], "name": "requests"}, {"version": "1.0", "hashes": ["sha256:8b6212f1155f43ce67fa945efae6d010ed059f3ca5ed377aa070e5903d45b722", "sha256:d43ede55b3d9b5524a8e11566ea0b11c9c8109116ef6a509a1b619d2041e7397", "sha256:ed4adf0d14564c56023862eabfac211cf01211a20c5271896c8ab6f80c68086c"], "name": "jsonpickle"}, {"version": "1.11.5", "hashes": ["sha256:11d30fc490bbe4d110fb7bfead0f10208275978ced3bce77f202224a0a9b448c", "sha256:151b7eefd035c56b2b2e1eb9963c90c6302dc15fbd8c1c0a83a163ff2c7d7743", "sha256:1553d1e99f035ace1c0544050622b7bc963374a00c467edafac50ad7bd276aef", "sha256:1b0493c091a1898f1136e3f4f991a784437fac3673780ff9de3bcf46c80b6b50", "sha256:2ba8a45822b7aee805ab49abfe7eec16b90587f7f26df20c71dd89e45a97076f", "sha256:3bb6bd7266598f318063e584378b8e27c67de998a43362e8fce664c54ee52d30", "sha256:3c85641778460581c42924384f5e68076d724ceac0f267d66c757f7535069c93", "sha256:3eb6434197633b7748cea30bf0ba9f66727cdce45117a712b29a443943733257", "sha256:495c5c2d43bf6cebe0178eb3e88f9c4aa48d8934aa6e3cddb865c058da76756b", "sha256:4b3d70782d55aa38949e4b66d51c461c053b729baa53d94bb8a3a92c1d1d5b88", "sha256:4c91af6e967c2015729d3e69c2e51d92f9898c330d6a851bf8f121236f3defd3", "sha256:770f3782b31f50b68627e22f91cb182c48c47c02eb405fd689472aa7b7aa16dc", "sha256:79f9b6f7c46ae1f8ded75f68cf8ad50e5729ed4d590c74840471fc2823457d04", "sha256:857959354ae3a6fa3da6651b966d13b0a8bed6bbc87a0de7b38a549db1d2a359", "sha256:87f37fe5130574ff76c17cab61e7d2538a16f843bb7bca8ebbc4b12de3078596", "sha256:95d5251e4b5ca00061f9d9f3d6fe537247e145a8524ae9fd30a2f8fbce993b5b", "sha256:a6a5cb8809091ec9ac03edde9304b3ad82ad4466333432b16d78ef40e0cce0d5", "sha256:ae5e35a2c189d397b91034642cb0eab0e346f776ec2eb44a49a459e6615d6e2e", "sha256:b0f7d4a3df8f06cf49f9f121bead236e328074de6449866515cea4907bbc63d6", "sha256:b75110fb114fa366b29a027d0c9be3709579602ae111ff61674d28c93606acca", "sha256:be2a9b390f77fd7676d80bc3cdc4f8edb940d8c198ed2d8c0be1319018c778e1", "sha256:ca1bd81f40adc59011f58159e4aa6445fc585a32bb8ac9badf7a2c1aa23822f2", "sha256:e55e22ac0a30023426564b1059b035973ec82186ddddbac867078435801c7801", "sha256:e90f17980e6ab0f3c2f3730e56d1fe9bcba1891eeea58966e89d352492cc74f4", "sha256:ecbb7b01409e9b782df5ded849c178a0aa7c906cf8c5a67368047daab282b184", "sha256:ed01918d545a38998bfa5902c7c00e0fee90e957ce036a4000a88e3fe2264917", "sha256:edabd457cd23a02965166026fd9bfd196f4324fe6032e866d0f3bd0301cd486f", "sha256:facc52ea162864a51556925bfa09d8c8c131349aeabfce2da4a43198e36fba5c", "sha256:fdf1c1dc5bafc32bc5d08b054f94d659422b05aba244d6be4ddc1c72d9aa70fb"], "name": "cffi"}, {"version": "3.5.1", "hashes": ["sha256:31421f16c01ffbd1ea7353c7e7cd7540bf2e5906d6173eb51c8fea4e0ea38b19", "sha256:fbe82af9b94ccced752527c8de07fa20267f9634b48674ba478a0bb4000a0b1e"], "name": "docker"}, {"version": "1.1.0", "hashes": ["sha256:048ef924c1623740e70204aa7143ec592504045ae4429b59c30054cb31e3c432", "sha256:19f637c2ac5ae9da8bfd98cef74d64b7e1bb8a63038a3505cd182c3fac5eb4d9", "sha256:1b8a7a87ad1b92bd887568ce54b23565f3fd7018c4180136e1cf412b405a47af", "sha256:1f19ef5d3908110e1e891deefb5586aae1b49a7440db952454b4e281b41620cd", "sha256:3e835d8841ae7863f64e40e19477f7eb398674da6a47f09871673742531e6f4b", "sha256:4e97332c9ce444b0c2c38dd22ddc61c743eb208d916e4265a2a3b575bdccb1d3", "sha256:525396ee324ee2da82919f2ee9c9e73b012f23e7640131dd1b53a90206a0f09c", "sha256:52b07fbc32032c21ad4ab060fec137b76eb804c4b9a1c7c7dc562549306afad2", "sha256:52ccb45e77a1085ec5461cde794e1aa037df79f473cbc69b974e73940655c8d7", "sha256:5c3fbebd7de20ce93103cb3183b47671f2885307df4a17a0ad56a1dd51273d36", "sha256:5e5851969aea17660e55f6a3be00037a25b96a9b44d2083651812c99d53b14d1", "sha256:7d263e5770efddf465a9e31b78362d84d015cc894ca2c131901a4445eaa61ee1", "sha256:83381342bfc22b3c8c06f2dd93a505413888694302de25add756254beee8449c", "sha256:857eebb2c1dc60e4219ec8e98dfa19553dae33608237e107db9c6078b1167856", "sha256:98e439297f78fca3a6169fd330fbe88d78b3bb72f967ad9961bcac0d7fdd1550", "sha256:bf54103892a83c64db58125b3f2a43df6d2cb2d28889f14c78519394feb41492", "sha256:d9ac82be533394d341b41d78aca7ed0e0f4ba5a2231602e2f05aa87f25c51672", "sha256:e982fe07ede9fada6ff6705af70514a52beb1b2c3d25d4e873e82114cf3c5401", "sha256:edce2ea7f3dfc981c4ddc97add8a61381d9642dc3273737e756517cc03e84dd6", "sha256:efdc45ef1afc238db84cb4963aa689c0408912a0239b0721cb172b4016eb31d6", "sha256:f137c02498f8b935892d5c0172560d7ab54bc45039de8805075e19079c639a9c", "sha256:f82e347a72f955b7017a39708a3667f106e6ad4d10b25f237396a7115d8ed5fd", "sha256:fb7c206e01ad85ce57feeaaa0bf784b97fa3cad0d4a5737bc5295785f5c613a1"], "name": "markupsafe"}, {"version": "0.9.3", "hashes": ["sha256:6a81d4c9aa62caf061cb517b4d9ad1dd300374cd4706997aff9cd6aedd61fc64", "sha256:f11b4461f425740a1d908e9a3f7365c3d2e569f6ca68a2ff8bc5bcd9676edd63"], "name": "jmespath"}, {"version": "0.95", "hashes": ["sha256:72791618feb22eaff2e628462b0d58f398ce8c1bacfa989b7679817ab1fad60c", "sha256:9e7ba8dd08fd2939376c21423376206bff01d0deaea7d7721c6b35921fed1943"], "name": "aws-xray-sdk"}, {"version": "0.17.1", "hashes": ["sha256:67045236dcfd6816dc439556d009594abf643e5eb48992e36beac09c2ca659b8"], "name": "future"}, {"version": "17.12.1", "hashes": ["sha256:66623c52f34d83a2c0fc963e08e8b9d0c13d88404e3b43b1852ef71eda19afa3", "sha256:f83fc302c52c6b83a15345792693ae0b5bc07ad19f59e318b7617d7123d62990"], "name": "pyaml"}, {"version": "2.49.0", "hashes": ["sha256:147758d41ae7240dc989f0039f27da8ca0d53734be0eb869ef16e3adcfa462e8", "sha256:ea0d3b40a2d852767be77ca343b58a9e3a4b00d9db440efb8da74b4e58025e5a"], "name": "boto"}, {"version": "0.14.1", "hashes": ["sha256:c3fd7a7d41976d9f44db327260e263132466836cef6f91512889ed60ad26557c", "sha256:d5da73735293558eb1651ee2fddc4d0dedcfa06538b8813a2e20011583c9e49b"], "name": "werkzeug"}, {"version": "0.13", "hashes": ["sha256:40d002cf360d0e035cf2cb985e1308d41aaa087cbfc135b2dc2d844296ea546c", "sha256:64cf1ee26d1cde3c73c6d7d107f835fed7c6a2904aef9eac223d57ad800c43fa"], "name": "ecdsa"}, {"version": "2.7.5", "hashes": ["sha256:063df5763652e21de43de7d9e00ccf239f953a832941e37be541614732cdfc93", "sha256:88f9287c0174266bb0d8cedd395cfba9c58e87e5ad86b2ce58859bc11be3cf02"], "name": "python-dateutil", "markers": "python_version >= '2.7'"}, {"version": "0.10.4", "hashes": ["sha256:16ad4a7a914f20792111157adf09c63a8dc37699c57d1ad20dbc281a4f5743fb", "sha256:b9b31d9b1fcf6d48aea044c9fdd3d04199f6d227b0650c15d2566b0135bc1ed7"], "name": "responses"}, {"version": "1.24.1", "hashes": ["sha256:61bf29cada3fc2fbefad4fdf059ea4bd1b4a86d2b6d15e1c7c0b582b9752fe39", "sha256:de9529817c93f27c8ccbfead6985011db27bd0ddfcdb2d86f3f663385c6a9c22"], "name": "urllib3"}, {"version": "2.19", "hashes": ["sha256:a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3"], "name": "pycparser"}, {"version": "0.54.0", "hashes": ["sha256:8c8bf2d4f800c3ed952df206b18c28f7070d9e3dcbd6ca6291127574f57ee786", "sha256:e51562c91ddb8148e791f0155fdb01325d99bb52c4cdbb291aee7a3563fd0849"], "name": "websocket-client"}, {"version": "1.10.11", "hashes": ["sha256:d4d560d479f2c21e1b5443bbd15fe7ec4b37fe7e53d335d3b9b0a7b1226fe3c6"], "name": "wrapt"}]
> ```

No way, it turns out to work!

**Comment by amancevice** [comment]
The pipenv-resolver works, but I'm still getting the above stacktrace on `pipenv install` or `pipenv lock`.

**Comment by bbbart** [comment]
I'm having the same problem without private sources. I created a new pipenv virtual environment, and started installing some packages: inflection, matplotlib, pandas, pendulum, jinja2, .. no problem. Until I did a `pipenv install scipy`, which resulted in the stack trace above upon locking (`scipy` got installed however, but is not present in the lockfile).

Manual runs of `pipenv lock` result in the same error (after a long wait). Additional package installations (tried pyowm and BeautifulSoup) are now timing out or failing.

`pipenv-resolver -v scipy` has been running for over two minutes now at the time of writing this comment without any noticeable activity.

I'm using pipenv 2018.11.14-1 and never had any issues with previous versions (starting at 2018.7.1-2).

Hope this bug report helps in getting the issue resolved. I'd be happy to provide more info when needed.

**Comment by bbbart** [comment]
Aha! After almost seven minutes, `pipenv-resolver` did result in some output, and since then I can `pipenv lock` and `pipenv install` again. Sorry to have bothered you...

**Comment by techalchemy** [comment]
Seems like a caching issue in that case. I think there may still be a real issue here

**Comment by techalchemy** [comment]
With this pipfile, I can't replicate the issue:

```
[[source]]
url = "http://localhost:3141/testuser/dev/+simple/"
verify_ssl = false
name = "public-pypi"

[packages]
moto = "==1.3.6"

[dev-packages]

[requires]
python_version = "3.7"
```

Locking is working just fine for me against master so I'll need an example that reproduces teh issue against teh master branch otherwise I'm afraid there isn't much we can do.  Try `pipenv lock --clear` and see if that helps

**Comment by amancevice** [comment]
Yeah I totally get that this is a weird one. I'm hoping someone else out there can replicate it and shed some more light on it. I've tried the `pipenv lock --clear` trick a few times but it doesn't seem to take. My bandaid solution is to downgrade to pipenv `2018.10.13` for the time being.

**Comment by amancevice** [comment]
aha, setting `PIPENV_TIMEOUT=3600` seems to resolve the issue!

So if it's timing out, perhaps a better error message could be printed to let the user know that's what is happening?

**Comment by techalchemy** [comment]
What's super weird is we didn't change the timeouts at all... how long does it actually take to lock?

**Comment by Juanlu001** [comment]
I had this same traceback with a plain `pipenv install ipyleaflet` (first usage) and, when I ran again the command using `PIPENV_TIMEOUT=3600`, it worked. Just in case it's useful for anybody else.

**Comment by techalchemy** [comment]
I’ll try bumping the timeout a bit for individual lock operations in this release. I think this might be impacting timeouts of subprocess runtimes in a new way

**Comment by techalchemy** [comment]
Thanks for your patience and for the helpful debugging information— hopefully the changes are actually improving the UX overall

**Comment by massenz** [comment]
Encountered the same issue, definitely a timeout (although, not clear at all what takes so long - is there a way to get a sense of where pipenv spends so much time locking the deps?): I was about to give up on pipenv while building my container, then I swapped it for the `2018.10.13` release, and it succeeded.

The failure needs to be caught and a better error message (maybe with the hint to tweak the `PIPENV_TIMEOUT`) would be great.

This:
```
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7fedef12ed68>
```
is a good hint that there's a timeout there (especially as it happens after waiting forever) but then this throws everyone off the scent:
```
searcher: searcher_re:
    0: re.compile('\n')
<pexpect.popen_spawn.PopenSpawn object at 0x7fedef12ed68>
searcher: searcher_re:
    0: re.compile('\n')
```

**Comment by micahjsmith** [comment]
For anyone who comes across this thread, the following can also result in the original error:

- source url for private index does not have `/simple` at the end
- connection errors to the wrong url result in timeout being exceeded
- strange `re.compile` error is raised

Resolution:
- add `/simple` to the end of the private index url or otherwise fix the url
