### ISSUE TITLE
Installing from git and specifying the platform or os raises an InvalidMarker error

### ISSUE THREAD

**Issue by samfrench** [pypa/pipenv#3249]
### Issue description

When running `pipenv install` using Python3 and pipenv version 2018.11.14, if I specify a platform for a package from GitHub I get an InvalidMarker error.

```
python3.7/site-packages/pip/_vendor/packaging/markers.py", line 280, in __init__', '    raise InvalidMarker(err_str)', 'pip._vendor.packaging.markers.InvalidMarker: Invalid marker: \'sys_platform == \\\'linux\\\'"\', parse error at \'"\'']
```

The platform specifications work fine on other modules when not using a git repo.

### Expected result

The packages to be able to be installed or ignored from GitHub depending if the platform matched. The same installation behaviour as the packages that are not from GitHub.

### Steps to replicate

Pipfile with the platform matchers.

```
[[source]]
name = "pypi"
verify_ssl = true
url = "https://pypi.org/simple"

[requires]
python_version = "3"

[packages]
tweepy = { git = "https://github.com/tweepy/tweepy", markers="sys_platform == 'linux'" }
picamera = { version = "*", sys_platform = "== 'linux'" }
```

Using this without "markers" produced the same issue.

```
tweepy = { git = "https://github.com/tweepy/tweepy", sys_platform = "== 'linux'" }
```

I am on a Mac and using python 3.7.

**Comment by techalchemy** [comment]
Ah, technically VCS repos don't really have this capability when they aren't editable I guess.  I can just turn the validation aspect of this off to fix it I believe
