### ISSUE TITLE
emit warning when using VCS dependency without editable flag

### ISSUE THREAD

**Issue by belm0** [pypa/pipenv#3270]
As a user, it took me a long time to figure out why transitive dependencies of a VCS dependency weren't appearing in my lockfile.  The symptom is subtle, and the correction is obscure (i.e. not intuitive why a VCS dependency needs to be declared `editable`, and it took me 20 minutes of searching old issues to find the hint).

pipenv seems to be aware of the specific dependencies of the the VCS dependency, and that they won't be added to the lockfile when the VCS dependency is not editable.  Could it offer a warning to the user?

**Comment by techalchemy** [comment]
I thought we did this already... :|

**Comment by belm0** [comment]
Perhaps I missed the warning, but I'd expect it during the lock operation:
```
[packages]
trio-websocket = { git = "https://github.com/HyperionGray/trio-websocket" }
```
```
$ pipenv --version
pipenv, version 2018.11.14

$ pipenv lock
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (465138)!
```

**Comment by techalchemy** [comment]
well darn, we used to warn people about this! I agree with you
