### ISSUE TITLE
Pipe/redirection in scripts section

### ISSUE THREAD

**Issue by pj** [pypa/pipenv#3277]
### Is your feature request related to a problem? Please describe.

Is it possible to use pipe/redirect in the scripts section of the Pipfile? e.g.:

     [scripts]
     generate-requirements = ""pipenv lock -r > requirements.txt"

I guess this might not be windows friendly...

### Describe the solution you'd like

I would like to be able to use pipes and redirects.

### Describe alternatives you've considered

A workaround is to use bash -c:

     [scripts]
     generate-requirements = "bash -c \"pipenv lock -r > requirements.txt\""

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.14'`

Pipenv location: `'/Users/pauljohnson/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv'`

Python location: `'/Users/pauljohnson/.pyenv/versions/3.6.4/bin/python3.6'`

Python installations found:

  - `3.7.1`: `/usr/local/bin/python3`
  - `3.7.1`: `/usr/local/bin/python3.7m`
  - `3.6.7`: `/Users/pauljohnson/.pyenv/versions/3.6.7/bin/python3`
  - `3.6.7`: `/Users/pauljohnson/.pyenv/versions/3.6.7/bin/python3.6m`
  - `3.6.4`: `/Users/pauljohnson/.pyenv/versions/3.6.4/bin/python3`
  - `3.6.4`: `/Users/pauljohnson/.pyenv/versions/3.6.4/bin/python3.6m`
  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.15`: `/usr/local/bin/pythonw`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT '
                     '2018; root:xnu-4570.71.13~1/RELEASE_X86_64',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `AUTOJUMP_ERROR_PATH`
  - `TERM_PROGRAM`
  - `AUTOJUMP_SOURCED`
  - `PYENV_ROOT`
  - `PIP_PYTHON_PATH`
  - `SHELL`
  - `TERM`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `GAE`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `ZSH`
  - `PYENV_VERSION`
  - `USER`
  - `COMMAND_MODE`
  - `PYENV_DIR`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `PAGER`
  - `TMUX`
  - `LSCOLORS`
  - `PIPENV_ACTIVE`
  - `PATH`
  - `PWD`
  - `JAVA_HOME`
  - `EDITOR`
  - `GAE_ROOT`
  - `LANG`
  - `ITERM_PROFILE`
  - `PYENV_HOOK_PATH`
  - `TMUX_PANE`
  - `XPC_FLAGS`
  - `PYTHONDONTWRITEBYTECODE`
  - `BACKEND_SERVER_ROOT`
  - `XPC_SERVICE_NAME`
  - `COLORFGBG`
  - `HOME`
  - `SHLVL`
  - `PYENV_SHELL`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `PYTHONPATH`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `LC_CTYPE`
  - `SECURITYSESSIONID`
  - `COLORTERM`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/pauljohnson/.pyenv/versions/3.6.4/bin:/usr/local/Cellar/pyenv/1.2.8/libexec:/Users/pauljohnson/Work/google-cloud-sdk/bin:/usr/local/sbin:/Users/pauljohnson/.pyenv/shims:/Users/pauljohnson/.pyenv/versions/3.6.4/bin:/usr/local/Cellar/pyenv/1.2.8/libexec:/Users/pauljohnson/Work/google-cloud-sdk/bin:/usr/local/sbin:/Users/pauljohnson/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pauljohnson/Work/google-cloud-sdk/bin:/usr/local/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Applications/Postgres.app/Contents/Versions/latest/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/pauljohnson/Work/creator_service`

---------------------------

Contents of `Pipfile` ('/Users/pauljohnson/Work/creator_service/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
flask = "*"

[scripts]
# FIXME: This isn't ideal, it looks like pipenv doesn't support redirects/pipes
# in script commands.
generate-requirements = "bash -c \"pipenv lock -r > requirements.txt\""
start = "pipenv run python main.py"
start = "pipenv run python main.py"

[requires]
# As of 2018-11-20 3.6.4 is the python 3 version supported by GAE.
python_version = "3.6.4"

```

Contents of `Pipfile.lock` ('/Users/pauljohnson/Work/creator_service/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "b3fee6162083d151a8f7e17b1461e3958a23b14986771f96a902ed4ffed408af"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6.4"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "click": {
            "hashes": [
                "sha256:2335065e6395b9e67ca716de5f7526736bfa6ceead690adf616d925bdc622b13",
                "sha256:5b94b49521f6456670fdb30cd82a4eca9412788a93fa6dd6df72c94d5a8ff2d7"
            ],
            "version": "==7.0"
        },
        "flask": {
            "hashes": [
                "sha256:2271c0070dbcb5275fad4a82e29f23ab92682dc45f9dfbc22c02ba9b9322ce48",
                "sha256:a080b744b7e345ccfcbc77954861cb05b3c63786e93f2b3875e0913d44b43f05"
            ],
            "index": "pypi",
            "version": "==1.0.2"
        },
        "itsdangerous": {
            "hashes": [
                "sha256:321b033d07f2a4136d3ec762eac9f16a10ccd60f53c0c91af90217ace7ba1f19",
                "sha256:b12271b2047cb23eeb98c8b5622e2e5c5e9abd9784a153e9d8ef9cb4dd09d749"
            ],
            "version": "==1.1.0"
        },
        "jinja2": {
            "hashes": [
                "sha256:74c935a1b8bb9a3947c50a54766a969d4846290e1e788ea44c1392163723c3bd",
                "sha256:f84be1bb0040caca4cea721fcbbbbd61f9be9464ca236387158b0feea01914a4"
            ],
            "version": "==2.10"
        },
        "markupsafe": {
            "hashes": [
                "sha256:bf54103892a83c64db58125b3f2a43df6d2cb2d28889f14c78519394feb41492"
            ],
            "version": "==1.1.0"
        },
        "werkzeug": {
            "hashes": [
                "sha256:c3fd7a7d41976d9f44db327260e263132466836cef6f91512889ed60ad26557c",
                "sha256:d5da73735293558eb1651ee2fddc4d0dedcfa06538b8813a2e20011583c9e49b"
            ],
            "version": "==0.14.1"
        }
    },
    "develop": {}
}

```
</details>

**Comment by frostming** [comment]
Redirects and pipelines should always be wrapped in a call of `bash -c` to get the expected behavior. Pipenv doesn't wrap it for you.
