### ISSUE TITLE
PEEP new project creation

### ISSUE THREAD

**Issue by AntoinePrv** [pypa/pipenv#3291]
Hello,

First of all I'd like to thank you for the great work done with Pipenv.

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Similar to [Rust's Cargo](https://doc.rust-lang.org/cargo/guide/creating-a-new-project.html), I suggest Pipenv could have a `pipenv new name` command (with additional options) to create a new empty python project (for instance using [kennethreitz/setup.py
](https://github.com/kennethreitz/setup.py)), along with initializing some VCS (git default).

### Describe alternatives you've considered

Alternative are doing it manually, or writing a third party script to do it.

### Additional context

No

**Comment by jxltom** [comment]
So basically you would like to have ```pipenv new projectname``` == ```pipenv --two/three``` + ```setup.py``` + git initialized?

I think this requires a PEEP. Here is a template for PEEP, https://github.com/pypa/pipenv/blob/master/peeps/PEEP-TEMPLATE.md. And this https://github.com/pypa/pipenv/blob/master/peeps/PEEP-002.md is a good example.

**Comment by haizaar** [comment]
I'm curious why [cookiecutter](https://github.com/Kaminario/healthshield/blob/master/docs/howtos/modularity.rst#template) does not fill the bill? You can create a template that does the required initialization in post- hook.
