### ISSUE TITLE
pytest-pypi has pytest-httpbin README, nonexisitng website

### ISSUE THREAD

**Issue by hroncok** [pypa/pipenv#3292]
I was looking at pytest-pypi at https://pypi.org/project/pytest-pypi/

The website points to https://github.com/kennethreitz/pytest-pypi and that is 404

The README looks like copy paste from pytest-httpbin.

Is the upstream of this PyPI project at https://github.com/pypa/pipenv/tree/master/tests/pytest-pypi ?

Can the README, DESCRIPTION.rst (= long description on PyPI) and URL by updated?

Thanks

**Comment by frostming** [comment]
Would you like to send a PR for this? I will be glad to review.

**Comment by hroncok** [comment]
Yes but no promises on when. I will try to get it done this week, but there other things piling up.
