### ISSUE TITLE
phusion: Failed to safefile.OpenRelative failed in Win32

### ISSUE THREAD

**Issue by eltonG** [pypa/pipenv#3302]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://docs.pipenv.org/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

$ docker pull phusion/baseimage
Using default tag: latest
latest: Pulling from phusion/baseimage
281a73dee007: Extracting  41.94MB/41.94MB
2aea1b77cff7: Download complete
59a714b7d8bf: Download complete
0218064da0a9: Download complete
ebac621dcea3: Download complete
a3ed95caeb02: Download complete
b580731643cc: Download complete
faa5fbdba239: Download complete
failed to register layer: re-exec error: exit status 1: output: Failed to safefile.OpenRelative failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\b8ff9c145b7793d60e394d20fa5aaffc420c6062377f930d40d68af06449d223\usr\share\man\man7\pam.7.gz: Cannot create a file when that file already exists. (0x1f) usr\share\man\man7\pam.7.gz

### Expected result

nnnnnnn: Extracting  xMB/yMB

### Actual result

$ docker pull phusion/baseimage
Using default tag: latest
latest: Pulling from phusion/baseimage
281a73dee007: Extracting  41.94MB/41.94MB
2aea1b77cff7: Download complete
59a714b7d8bf: Download complete
0218064da0a9: Download complete
ebac621dcea3: Download complete
a3ed95caeb02: Download complete
b580731643cc: Download complete
faa5fbdba239: Download complete
failed to register layer: re-exec error: exit status 1: output: Failed to safefile.OpenRelative failed in Win32: open \\?\C:\ProgramData\Docker\windowsfilter\b8ff9c145b7793d60e394d20fa5aaffc420c6062377f930d40d68af06449d223\usr\share\man\man7\pam.7.gz: Cannot create a file when that file already exists. (0x1f) usr\share\man\man7\pam.7.gz

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip
[]$ pipenv --support | clip
bash: pipenv: command not found[/]

**Comment by frostming** [comment]
From the failing log i see nothing pipenv can help. Can you restate your issue what situation you confronted with Pipenv?

Thanks

**Comment by techalchemy** [comment]
The failure appears to relate to docker and/or phusion (not sure what that is but it probably isn't pipenv)

In any case, please report your bug to the appropriate place, thanks!
