### ISSUE TITLE
When creating a virtual environment no `pyvenv.cfg` file is created.

### ISSUE THREAD

**Issue by halloleo** [pypa/pipenv#3303]
### Issue description

When creating a virtual environment no `pyvenv.cfg` file is created.

### Expected result

When creating a virtual environment a `pyvenv.cfg` file is created in the root of the virtual environment. This is expected, becasue python3's own venv moduel generates it at least since some 3.5 version.

### Actual result

See description: No `pyvenv.cfg` file is created.

### Steps to replicate

1. Create a new directory.
2. Issue the command

        pipenv install

3. Check the virtual environment directory for the `pyvenv.cfg` file.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.14'`

Pipenv location: `'/usr/local/lib/python3.5/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.6.4`: `/working/software/venv/xonsh/bin/python3.6`
  - `3.6.4`: `/usr/local/bin/python3.6m`
  - `3.5.2`: `/usr/local/bin/python3.5m`
  - `2.7.13`: `/usr/local/bin/python2.7`
  - `3.4.4`: `/usr/local/bin/python3.4m`
  - `2.6.6`: `/usr/bin/python2.6`
  - `3.4.4`: `/usr/local/bin/python3.4`
  - `2.6.6`: `/usr/bin/python`
  - `3.5.2`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.5.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.1.12-124.17.2.el6uek.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#2 SMP Tue Jul 17 20:31:11 PDT 2018',
 'python_full_version': '3.5.2',
 'python_version': '3.5',
 'sys_platform': 'linux'}
```

System environment variables:

  - `_`
  - `PWD`
  - `BROWSER`
  - `JAVA_HOME`
  - `CAML_LD_LIBRARY_PATH`
  - `SSH_CLIENT`
  - `EMACSEXE`
  - `XONSH_TRACEBACK_LOGFILE`
  - `PIP_PYTHON_PATH`
  - `SHLVL`
  - `HISTTIMEFORMAT`
  - `MY_XONSHRC_LOCAL`
  - `G_BROKEN_FILENAMES`
  - `XONSH_SHOW_TRACEBACK`
  - `XONSH_INTERACTIVE`
  - `PIP_SHIMS_BASE_MODULE`
  - `MYCMDSPATH`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PERL5LIB`
  - `SHELL_TYPE`
  - `READLINK_EXE`
  - `PIPENV_CACHE_DIR`
  - `PATH`
  - `USER`
  - `VENV`
  - `DISPLAY`
  - `OCAML_TOPLEVEL_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `TERM`
  - `LANG`
  - `PEX_ROOT`
  - `XONSH_VERSION`
  - `SSH_CONNECTION`
  - `PROMPT`
  - `GIT_EDITOR`
  - `HISTSIZE`
  - `OPAMROOT`
  - `SHELL`
  - `HOSTNAME`
  - `HOME`
  - `MANPATH`
  - `LESSHISTFILE`
  - `TERMCAP`
  - `PROMPT_COMMAND`
  - `OLDPWD`
  - `NEO4J_HOME`
  - `PIPENV_IGNORE_VIRTUALENVS`
  - `PIPENV_DEFAULT_PYTHON_VERSION`
  - `PS_FORMAT`
  - `XONSHRC`
  - `QTLIB`
  - `LOGNAME`
  - `INSIDE_EMACS`
  - `BASH_COMPLETIONS`
  - `VIRTUALENV_HOME`
  - `HISTCONTROL`
  - `MAIL`
  - `LD_LIBRARY_PATH`
  - `TMUX_PANE`
  - `LOADED_RC_FILES`
  - `LS_COLORS`
  - `XONSH_LOGIN`
  - `SSH_TTY`
  - `PYTHONDONTWRITEBYTECODE`
  - `WORKON_HOME`
  - `WHICH_EXE`
  - `TMUX`

Pipenv–specific environment variables:

 - `PIPENV_CACHE_DIR`: `/home/halloleo/.cache/pipenv`
 - `PIPENV_IGNORE_VIRTUALENVS`: `1`
 - `PIPENV_DEFAULT_PYTHON_VERSION`: `3.6`

Debug–specific environment variables:

  - `PATH`: `/working/software/venv/xonsh/bin::/working/software/halloleo/ocaml/opam/system/bin:/home/halloleo/bin:/working/software/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/working/software/JetBrains/idea-IC-181.5281.24/plugins/maven/lib/maven3/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/halloleo/tmp`

---------------------------

</details>

**Comment by techalchemy** [comment]
We don't use venv, we use virtualenv, so yes, this is expected

**Comment by halloleo** [comment]
Mmmh,is there any way to tell pipenv to use the Python3 default way to create venvs? Or wouldn't be sensible to _generally_ move over to the Python3 default way? Not sure if that is feasible with the current architecture...

**Comment by techalchemy** [comment]
Here is the main issue you need to know about: https://github.com/pypa/pipenv/issues/15

**Comment by halloleo** [comment]
Thanks for the link to Issue 15. I can see this is a bigger problem.
