### ISSUE TITLE
`pipenv sync` doesn't work without Pipfile

### ISSUE THREAD

**Issue by konstantinmiller** [pypa/pipenv#3308]
I'm trying to initialize a production environment from Pipfile.lock. I have an empty directory with a Pipfile.lock and run `pipenv sync`. It fails with the following message:

Error: Pipfile.lock is missing! You need to run $ pipenv lock first.
Aborted!

Note that Pipfile.lock is there. It's rather the Pipfile that is missing but my understanding is that you don't need it when you do `pipenv sync`.

**Comment by frostming** [comment]
This issue is well discussed in #2834 and is definitely a direction to improve, thanks for report, close this issue now.
