### ISSUE TITLE
2018.11.26 tagged at 2018.11.15.dev0

### ISSUE THREAD

**Issue by hroncok** [pypa/pipenv#3326]
As a Fedora packager, I take the tagged tarball from GitHub and want to package it, however the tagged version 2018.11.26 still has 2018.11.15.dev0 at https://github.com/pypa/pipenv/blob/742ae1b99b335ffb6d83a2240035af739cacafff/pipenv/__version__.py

Not sure if you are aware, probably not worth rereleasing.

**Comment by frostming** [comment]
Thanks for the kind notice. /cc @techalchemy

**Comment by techalchemy** [comment]
Yeah I saw this and forgot to reply -_- sorry! I replied in my head if that counts...

Yeah this is an annoying workflow issue and I need to sort out where in my release tooling it’s misbehaving. I obviously don’t check that during the release process...

**Comment by Kerybas** [comment]
The archive for 2018.11.26 still show __version__ = "2018.11.15.dev0".
(The Arch package uses the archive link)

I'm wondering if that is just a tag issue or the actual version is indeed 2018.11.15.dev0.  
The thing is, I have this exact bug, supposed to be closed: https://github.com/pypa/pipenv/pull/3287

**Comment by homocomputeris** [comment]
https://github.com/pypa/pipenv/issues/3098 seems to be more or less the same
