### ISSUE TITLE
Environment variables PIPENV_SKIP_LOCK does not work.

### ISSUE THREAD

**Issue by mimizhang** [pypa/pipenv#3332]
I don't know if it is bug or my misunderstanding of document.

### Issue description

Environment variables PIPENV_SKIP_LOCK does not work.

### Expected result

As the document described, if PIPENV_SKIP_LOCK is setted  to true, it will skip locking mechanisms.

### Actual result

when my OS Environment variables PIPENV_SKIP_LOCK is  true , pipenv still excute locking.

### Steps to replicate
```shell
$ echo $PIPENV_SKIP_LOCK
true
$ pipenv uninstall autopep8
Un-installing autopep8…
Uninstalling autopep8-1.4.3:
  Successfully uninstalled autopep8-1.4.3

Removing autopep8 from Pipfile…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (1402f9)!
```

**Comment by frostming** [comment]
What version of pipenv are you running?

It works well on `2018.11.26`

**Comment by mimizhang** [comment]
> What version of pipenv are you running?
> 
> It works well on `2018.11.26`
it is on 2018.10.13. So Which version starts to support this feature?

**Comment by mimizhang** [comment]
@frostming  Thanks for your help!

**Comment by BeyondEvil** [comment]
This (still?) doesn't work with the latest version of pipenv. @frostming 

```
$ echo $PIPENV_SKIP_LOCK
true

$ pipenv install pytest
Installing pytest…
Adding pytest to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success! 
Updated Pipfile.lock (1c4d3d)!
Installing dependencies from Pipfile.lock (1c4d3d)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 12/12 — 00:00:02
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

$ pipenv --version
pipenv, version 2018.11.26

$ python3 --version
Python 3.7.3

$ uname -a
Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.4
BuildVersion:   18E226
```

I also tried adding `PIPENV_SKIP_LOCK=true` to the project `.env`-file with same result.

**Comment by frostming** [comment]
@BeyondEvil Weird that I can't reproduce, maybe try master branch.

**Comment by BeyondEvil** [comment]
@frostming 

Could it be because I have installed pipenv using `brew`?

Also, how can I try master when it is installed using `brew`? 😊

**Comment by pirate** [comment]
Also not working for me when pipenv is installed with pip.

```bash
$ echo $PIPENV_SKIP_LOCK
1

$ pipenv --version
2018.11.26

$ cd myproject/; pipenv install
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
...
```

**Comment by frostming** [comment]
@BeyondEvil you can install by `brew install pipenv --HEAD`

@pirate Please try the master branch.

**Comment by BeyondEvil** [comment]
@frostming 

Tried master both with brew and the pragmatic approach. No dice. It still creates the lock-file.

**Comment by alejandrobalderas** [comment]
I was just having the same exact issue when trying to install pipenv in a docker container via the apt package manager. I switched to installing pipenv via pip and now it works as expected. 

``` diff
FROM python:3.8-slim
ENV PIPENV_SKIP_LOCK=1
- RUN apt update && apt -y install pipenv
+ RUN pip3 install pipenv
WORKDIR /app
COPY . .
RUN pipenv install
```

**Comment by spookyuser** [comment]
Still not working for me :(
