### ISSUE TITLE
Installing from private git repository does not prompt for username and password. (v2018.11.26)

### ISSUE THREAD

**Issue by mab4058** [pypa/pipenv#3333]
Pipenv version 2018.11.26 on Windows 10.

### Issue description

When installing from a private git repository the prompts for entering username and password appear to be hidden due to the "Installing" animation.

[Edit] I am able to enter username and password by assuming when it is asking me, pasting in the values, and hitting enter.  The same animation overwrite behavior is then seen at the "Pinning VCS Packages..." animation.

### Expected result

When running,
`pipenv install -e git+https://git-private-repo@v0.2.0#egg=private-project`

I expect to be prompted for my username and password.

### Actual result

There are no visible prompts.

Console output:
``` console
$ pipenv install -e git+https://git-private-repo@v0.2.0#egg=private-project --verbose
Installing -e git+https://git-private-repo@v0.2.0#egg=private-project… 
[    ] Installing...Installing 'private-project'
$ ['C:\\Users\\user\\.virtualenvs\\env-l1hpaNfS\\Scripts\\pip.exe', 'install', '--src', 'C:\\Users\\user\\.virtualenvs\\env-l1hpaNfS\\src', '--verbose', '--upgrade', '-e', 'git+https://git-private-repo@v0.2.0#egg=private-project', '-i', 'https://pypi.org/simple']
[=== ] Installing...
```

At this point the prompts for entering my username and password are being overwritten by the installing animation.  If I hit enter at this point I can see the enter username/password prompts flash onto the screen, so they are there, just hidden.

### Steps to replicate

Install from a private repo without using environment variables for username/password.

**Comment by techalchemy** [comment]
pipenv is not interactive at this point, you need to configure authentication via environment variable expansion:

https://pipenv.readthedocs.io/en/latest/advanced/#injecting-credentials-into-pipfiles-via-environment-variables

closing for now, thanks for the report!

**Comment by mtdeguzis** [comment]
I believe this is what I am getting for #3412 and didn't see this issue. If the animation was obscuring such prompts, why was it ever added? I know there is a nice assortment of little animations for pipenv, but if they are going to hinder such core interaction with git, why have them? 

Workarounds can still be a bit cumbersome: https://stackoverflow.com/a/10056098.

**Comment by giantas** [comment]
I agree with @mtdeguzis. Installing from git is core functionality and the prompt for username/password is being obscured. Where it would have taken seconds to install a package, it is taking years just because someone has to consistently assume that a password is being requested. One can't just input a password in the Pipfile. This is all I keep seeing

```
Installing git+https://bitbucket.org/someuser/somepackage.git@v0.2.1#egg=somepackage…                                                                                                            
⠹ Installing...                                                                                                                                                                                 
⠧ Installing...                                                                                                                                                                                 
⠦ Installing...                                                                                                                                                                                 
⠴ Installing... 
```

**Comment by mtdeguzis** [comment]
Honestly, I don't see the real need for fancy animations. There's no need for some rotating animation or special characters if that hurts overall compatibility.
