### ISSUE TITLE
pipenv --clear is not working

### ISSUE THREAD

**Issue by jxltom** [pypa/pipenv#3353]
### Issue description

```pipenv --clear``` is not working.

### Actual result

```
➜  Untitled Folder pipenv --clear
Clearing caches...
```

**Comment by clafoutis42** [comment]
Do we have any update on this issue ?

I confronted it today, had to clear caches manually.

**Comment by jxltom** [comment]
https://github.com/pypa/pipenv/pull/3354 should sovles this, I will try to add tests to that PR this weekend. Sorry for the delay.
