### ISSUE TITLE
pipenv alters PATH env var in an unexpected way

### ISSUE THREAD

**Issue by sscullen** [pypa/pipenv#3358]
### Issue description

$ pipenv shell alters the PATH env var by remove /usr/local/bin 

### Expected result

$ pipenv shell

$ echo $PATH

PATH should be the same as outside of the pipenv shell, with the virtualenv path added to the front.

### Actual result

$ pipenv shell

$ echo $PATH

/usr/local/bin is missing from the PATH, despite being present in the PATH before the shell is activated.

### Steps to replicate

Running Ubuntu 18.04, using FISH shell.

**Comment by frostming** [comment]
Can you confirm where `/usr/local/bin` is configured and what the shell is after `pipenv shell`?

**Comment by sscullen** [comment]
I started a clean Ubuntu 18.04 docker image, with Python 3.7, fish, and pipenv, and the issue is not happening. So it has something to do with how my fish shell is set up, nothing to do with pipenv, sorry for creating an issue un-necessarily.

I will check the offending machine on Monday for problems with how the fish shell is set up and the PATH is being altered compared to a fresh install.

**Comment by techalchemy** [comment]
Just to get you something to work with, check how you are setting things up. `pipenv shell` doesn’t spawn login shells so it won’t get the same manipulation you give in your config for checking `if status --is-login`. Beyond that I’m glad it’s working :) closing for now!
