### ISSUE TITLE
Version 2018.11.26 install in docker-compose build process fails the first try, then succeeds

### ISSUE THREAD

**Issue by mikelane** [pypa/pipenv#3359]
### Issue description

Our Dockerfile has the following line:

```RUN pip install --upgrade \
    pip \
    setuptools \
    wheel \
    pipenv
```

And this:

```RUN if [ $DJANGO_ENV = "development" ] ; \
    then set -ex && pipenv install --dev --system ; \
    else set -ex && pipenv install --deploy --system --ignore-pipfile ; \
    fi
```

Up through pipenv version 2018.11.14, there was no issue. However, in the latest version (2018.11.26), all (or perhaps most) of the libraries specified in the Pipfile fail to install the first time and then are installed successfully at the end.

### Expected result

I expect the libraries to install correctly the first time as they do with pipenv versions less than 2018.11.26.

### Actual result

```An error occurred while installing pytest-django==3.4.3 --hash=sha256:49e9ffc856bc6a1bec1c26c5c7b7213dff7cc8bc6b64d624c4d143d04aff0bcf --hash=sha256:b379282feaf89069cb790775ab6bbbd2bd2038a68c7ef9b84a41898e0b551081! Will try again.
An error occurred while installing pytest-factoryboy==2.0.1 --hash=sha256:ad438d191d2b2a0f26956d437c1963875db573147a84ffd85d7bbeaefae22458! Will try again.
An error occurred while installing pytest-socket==0.3.1 --hash=sha256:bb0857c4a459b7ed4586c51b48ad99920ca82f3314c95ed6de84847c2a8b6eef! Will try again.
An error occurred while installing pytz==2017.2 --hash=sha256:d1d6729c85acea5423671382868627129432fba9a89ecbb248d8d1c7a9f01c67 --hash=sha256:f5c056e8f62d45ba8215e5cb8f50dfccb198b4b9fbea8500674f3443e4689589 --hash=sha256:d1d6729c85acea5423671382868627129432fba9a89ecbb248d8d1c7a9f01c67 --hash=sha256:f5c056e8f62d45ba8215e5cb8f50dfccb198b4b9fbea8500674f3443e4689589! Will try again.
...
[many other dependency installation errors skipped]
...
Installing initially failed dependencies…
```

**Comment by techalchemy** [comment]
i've seen this a bunch recently -- can you run this with `--verbose` and provide the output (in full if possible)? I haven't sorted out whats going on here but I'd like to...

**Comment by techalchemy** [comment]
This is fixed in #3298 I believe, do feel free to test out the master branch and let me know if you have any issues

closing for now, thanks for your patience

**Comment by pcraciunoiu** [comment]
Seeing one issue, for `django-watchman`. Upgrading from the latest pipenv release, to the current sha on master, results in the package not getting installed from git.

This is what I have in Pipfile for that package:

```
django-watchman = {git = "git://github.com/mwarkentin/django-watchman.git",ref = "master"}
```

This works on `2018.11.26`, but not with this version `python3 -m pip install git+https://github.com/pypa/pipenv.git@12572dd6b5b08e7beedeaa2329988a353b802003`

`django-watchman` is just nowhere to be found. But works before the upgrade.

```
>>> import watchman
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'watchman'
```

**Comment by techalchemy** [comment]
@pcraciunoiu are you using docker? Can you provide the relevant file(s)?

**Comment by pcraciunoiu** [comment]
Yes, it's inside docker. I cannot provide the entire thing, but what relevant files are you looking for?

* Docker version 18.09.3, build 774a1f4
* docker-compose version 1.21.2, build a133471 (although I'd guess that doesn't matter)

This is the start of the image:

```
FROM python:3.6.6 as test-container

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
    sudo && apt-get install -y \
    git \
    nginx \
    mysql-client \
    supervisor
RUN python3 -m pip install pipenv

# Install python requirements
RUN pipenv install --system --deploy --ignore-pipfile
```

However, ssh into the container and running `pipenv install` creates a virtualenv and `watchman` is missing there too:

```
pipenv shell
python3
>>> import watchman
```

Sample Pipfile:

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[requires]
python_version = "3.6"

[packages]
django = "==2.1.7"
django-watchman = {git = "git://github.com/mwarkentin/django-watchman.git",ref = "master"}

[pipenv]
allow_prereleases = true
```

Hope that helps. Let me know what else you need.

**Comment by techalchemy** [comment]
That’s perfect thank you. Just want enough to reproduce / test with

**Comment by techalchemy** [comment]
Reopening until I can re-test

**Comment by techalchemy** [comment]
Using the above pipfile and dockerfile and a wheel built from the master branch, this is now working without any issue for me.  Thanks for the reproducible test case
