### ISSUE TITLE
How to debug pipenv?

### ISSUE THREAD

**Issue by dimaqq** [pypa/pipenv#3364]
The problem I'm facing is that on the given project (many deps, private pypi server), pipenv operations that may update the lock file take really long...

```
> pipenv lock -v
Locking [dev-packages] dependencies…
⠼ Locking...
# -- couple minutes before to first line of output -- #

# [output snipped]
------------------------------------------------------------
Result of round 4: stable, done


Locking [packages] dependencies…
⠦ Locking...
# -- some five minutes to next output chunk -- #
```

This means that "trivial" changes like `pipenv install --dev pytest-xdist` take prohibitively long to try.

I'm pretty sure it's because of this specific project (either specific deps or private pypi), for example, another project that only has public dependencies is notably faster.

How can I see what's really taking so long?
I've tried the basics -- pstree, profiler, and I can see that pipenv spawned `resolver`, which spends its time in `do_poll`. What do I do next?

**Comment by techalchemy** [comment]
@dimaqq sorry for being slow responding, we had a few big issues at work so I was particularly unhelpful!  If I noticed this was your comment I would have tried to get back with you quicker -- FYI you can ping me on slack (we are in https://pyslackers.com/) or IRC in #pypa or #pipenv with some success

`pipenv-resolver` is a good way to debug, and to be perfectly honest a big motivation for adding t he resolver class is to make debugging a bit easier, you might have success working backwards from there

**Comment by techalchemy** [comment]
(I meant to say more on this but I ran out of time / had too many tabs open!)

**Comment by frostming** [comment]
No further discussion on this question ticket, close it now.
