### ISSUE TITLE
`pipenv sync` doesn't remove packages

### ISSUE THREAD

**Issue by konstantinmiller** [pypa/pipenv#3365]
If I remove a package from Pipfile.lock and perform `pipenv sync`, I expect that the removed packaged is removed from the virtual environment. This, however, doesn't happen. it's still present in `.venv/lib/Python3.7/site-packages`.

**Comment by frostming** [comment]
This is an API change, you may need to submit a PEEP to the `peeps` dir via a normal PR.

**Comment by konstantinmiller** [comment]
So, you mean `pipenv sync` is not supposed to `sync` the removed packages? :)
In this case, the workflow should always be `pipenv clean` plus `pipenv sync` in case you don't know if some packages have been removed or only added, right?

**Comment by frostming** [comment]
Right

**Comment by techalchemy** [comment]
Pipenv sync installs packages, it is not a destructive operation (if you want, it might be reasonable to propose a flag for this via a `PEEP`)

Closing for now, thanks for the report!
