### ISSUE TITLE
Odd decision where to place Pipfile

### ISSUE THREAD

**Issue by dimaqq** [pypa/pipenv#3370]
How this works for me, MWE:

```
cd ~
mkdir -p foo/bar/baz
touch foo/bar/baz/__init__.py

cd ~/foo/bar/baz
pipenv --three  # -> Pipfile: ~/foo/bar/baz/Pipfile

cd ~/foo/bar
pipenv --three  # -> Pipfile: ~/Pipfile
```

Why would the latter be the case?

The actual project I ran into had this structure:

```
~> tree proj
proj
├── LICENSE
├── README.md
├── docs
│   └── [...]
├── pytest.ini
├── setup.cfg
├── setup.py
├── src
│   └── proj
│       ├── __init__.py
│       └── foo.py
└── tests
    ├── __init__.py
    ├── conftest.py
    └── test_foo.py
```

I was able to work around the autodetection with:

```
cd proj
touch Pipfile
pipenv --three
```

**Comment by frostming** [comment]
This gives pipenv capability to use the project's Pipfile when in sub directory. So this is not a bug.

**Comment by dimaqq** [comment]
OK, but my `~` didn't have a `Pipfile` -- pipenv wants to create that file there.
And in that case, why not go further, why not `/home/` or even `/`?

**Comment by dimaqq** [comment]
@frostming your comment doesn't explain why pipenv "likes" a directory `~/foo/bar/baz/` either.

**Comment by frostming** [comment]
@dimaqq Sorry for not clarifying it, Pipenv will look for Pipfile in current path and parent directories recursively.
```
cd ~/foo/bar
pipenv --three  # -> Pipfile: ~/Pipfile
```
There must be a Pipfile in `~/Pipfile`. If not, this should be a bug.

**Comment by dimaqq** [comment]
I can no longer reproduce the original case (perhaps I was confused?), but I can reproduce the following:

```
# starting from $HOME
… ~> mkdir foo
… ~> mkdir foo/bar/
… ~> mkdir foo/bar/baz
… ~> touch Pipfile

… ~> cd ~/foo/bar/baz/; pipenv --three
[snip]
Pipfile: /Users/user.name/foo/bar/baz/Pipfile
[snip]

… ~/f/b/baz> cd ~/foo/bar/; pipenv --three
[snip]
Pipfile: /Users/user.name/Pipfile
[snip]
```

So:
* `~/foo/bar/baz` without Pipfile gets own Pipfile
* `~/foo/bar` without Pipfile does not get own PIpfile

It's as if `pipenv` searches upwards from current directory but at most 2 steps.

`pipenv, version 2018.11.26`

**Comment by frostming** [comment]
> * ~/foo/bar/baz without Pipfile gets own Pipfile
> * ~/foo/bar without Pipfile does not get own PIpfile
> It's as if pipenv searches upwards from current directory but at most 2 steps.

Please make sure there is no `Pipfile` under `/Users/user.name` and retry above steps

**Comment by dimaqq** [comment]
If there's no `Pipfile` anywhere, then pipenv works correctly -- each sub-sub-[sub]-directory gets own Pipfile.

**Comment by dimaqq** [comment]
Let me try to explain this again:

`~/Pipfile` + empty `~/foo/bar/baz` => `~/foo/bar/baz/Pipfile`
`~/Pipfile` + empty `~/foo/bar` => `~/Pipfile`

Seems inconsistent, doesn't it?

**Comment by frostming** [comment]
> If there's no `Pipfile` anywhere, then pipenv works correctly -- each sub-sub-[sub]-directory gets own Pipfile.

@dimaqq yes it is how pipenv works. If Pipfile exists in parent directory it is used.

**Comment by frostming** [comment]
> Let me try to explain this again:
> 
> `~/Pipfile` + empty `~/foo/bar/baz` => `~/foo/bar/baz/Pipfile`
> `~/Pipfile` + empty `~/foo/bar` => `~/Pipfile`
> 
> Seems inconsistent, doesn't it?

It is defined by `PIPENV_MAX_DEPTH` and can be changed via env var.
https://pipenv.readthedocs.io/en/latest/advanced/#pipenv.environments.PIPENV_MAX_DEPTH

**Comment by dimaqq** [comment]
Ohhh! yeah, that makes sense! I wish this was more prominent in the docs, would've saved us both quite a bit of time!
So sorry~~~
