### ISSUE TITLE
pipenv to manage setup.py

### ISSUE THREAD

**Issue by ekhaydarov** [pypa/pipenv#3377]
i have a project a that has a dependency on project b. project b requires project c. project b is managed by pipenv. i need to import project c github tag. I accomplish this fine in pipfile. When trying to install dependencies in project a I now have to create a setup file. I have to duplicate my efforts to create and manually maintain a pipfile, a requirements txt and setup.py?

Is this desired behaviour? whats the point of a requirements.txt intermediary that feeds setup py? 

*I have read the distinctions between a library and dependency setup* is duplication the way forward here?

**Comment by frostming** [comment]
The deps of project a is defined in project a's Pipfile and all sub-dependencies project b, c, d need a setup.py

**Comment by frostming** [comment]
Close it for now, if you have further questions please feel free to reopen it
