### ISSUE TITLE
--pypi-mirror not respected during virtualenv creation after 2018.10.13

### ISSUE THREAD

**Issue by JacobHenner** [pypa/pipenv#3378]
On Windows, versions of Pipenv > 2018.10.13 attempt to connect to https://pypi.org during virtualenv creation, even if --pypi-mirror is specified. This is a regression from 2018.10.13.

I've compared the network activity of 2018.10.13 and 11.14/11.26. For the latter two, connection attempts to pypi.org are made regardless of whether --pypi-mirror is specified. With 10.13, no such attempts are made.

This issue causes inconsistent timeouts and failures when a user is behind a firewall with a drop rule affecting pypi.org.

**Comment by JacobHenner** [comment]
I've tracked down the issue to a bug in vistir, which is preventing PIP_INDEX_URL from being set correctly before virtualenv is run. I'll resolve and submit a PR shortly.

**Comment by JacobHenner** [comment]
Caused by https://github.com/sarugaku/vistir/issues/55, which likely affects all instances of vistir.misc.run() which depend upon environment variables being specified as a parameter.

**Comment by jxltom** [comment]
👍
