### ISSUE TITLE
Deploy my application using pipenv on AWS

### ISSUE THREAD

**Issue by Storm75** [pypa/pipenv#3381]
What is the purpose of this repo if you can not use it to deploy and scale your Python application ?

Also stop the propaganda, this package is crap and does not allow to install dependencies easily for production and AWS auto-scaling. I just did not find a way to do :  cd  /your/project && pipenv run  uwsgi --ini blabla.ini.

This may be useful for beginner developpers that must handle multiple environments, but that's all.When you need to do more serious things that should be simple, pipenv is totally useless.

By the way your documentation is shit.

**Comment by Storm75** [comment]
I would be cordial if this WAS NOT OFFICIALY RECOMMENDED TOOL.

You encourage the death of Python.

Is this cordial enough ?
https://chriswarrick.com/blog/2018/07/17/pipenv-promises-a-lot-delivers-very-little/#officially-recommended-tool-or-how-we-got-here

**Comment by ksmorano** [comment]
[Amazon says](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/python-configuration-requirements.html)
`pipenv lock -r > requirements.txt`
