### ISSUE TITLE
The pipenv uninstall --dev is not working

### ISSUE THREAD

**Issue by jxltom** [pypa/pipenv#3385]
### Issue description

The ```pipenv uninstall --dev``` is not working. The ```--dev``` flag is saved as ```state.installstate.dev```, but it is not passed into ```uninstall``` method as shown in https://github.com/pypa/pipenv/blob/4e476ced063b9266ab046cd244bac46ef5e67b5a/pipenv/cli/command.py#L287-L300. Found this issue in https://github.com/pypa/pipenv/pull/3345.

### Expected result

The ```pipenv uninstall --dev``` should only uninstall and remove packages from dev packages section.

**Comment by sinscary** [comment]
@jxltom if no one is working on this, can I take this up ?

**Comment by jxltom** [comment]
@sinscary That's will be great! Thanks!

**Comment by matteius** [comment]
Is this actually still broken?
