### ISSUE TITLE
Pipfile.lock | Pipfile disappears when changing git branch

### ISSUE THREAD

**Issue by maxglaida** [pypa/pipenv#3400]
Hey,
We have a problem understanding the concept of git and pipenv together.
We have followed the installation to get a functional venv using pipenv.

Added the lock and pipfile to Git.
The problem we are facing is that when we switch from the master branch to the dev branch the lock file and pipfile disappear and we have a problem installing packages that are relevant for our dev branch.

maybe someone here can help on how to work with branching and pipenv or explain the concepts that we just dont understand.

**Comment by frostming** [comment]
It is more related to Git usage rather than pipenv.

**Comment by frostming** [comment]
To elaborate, make sure you have Pipfile and Pipfile.lock in both branches. If you create and commit them after the branch is created, you will not expect this two files in the old branch.
