### ISSUE TITLE
Question:  Should .env file be loaded by pipenv install?

### ISSUE THREAD

**Issue by DanAtShenTech** [pypa/pipenv#3403]
In my development .env file I have set `WORKON_HOME` to a directory other than my user's home directory (and not the project directory).  The docs [say that .env files are automatically loaded](https://pipenv.readthedocs.io/en/latest/advanced/#automatic-loading-of-env) by the `shell` and `run` commands.  If I want to create a new venv (for instance, if I'm upgrading the Python version), then I remove the old venv and the old Pipfile.lock.  I would like to create the new venv and have all dependencies installed with one command (`pipenv install`), but I can't.  `pipenv install`, when run by itself, does create a venv from the Pipfile, but it does not load .env and so does not create the venv where I wanted it to go.  In the event that `pipenv install` is run by itself, would it make sense to have it load the .env file?  And as a follow on question, would it make sense to always have `'install` load the .env file?

**Comment by frostming** [comment]
This was discussed in #3398 , close it for now.
