### ISSUE TITLE
Cannot see text being typed for private repos requiring username/password

### ISSUE THREAD

**Issue by mtdeguzis** [pypa/pipenv#3412]
### Issue description

Newer versions of pipenv do not show text being typed into input fields. Often, just one letter will flash, but you do not know if it is a github user/password prompt or not

### Expected result

Describe what you expected.

### Actual result

```
pipenv install --two --dev git+https://github.com/org/repo.git@ldap3-conversion#egg=opstools

Virtualenv location: /home/mtdeguzis/.local/share/virtualenvs/ranger-resource-manager-xtDlUHoq
Installing git+https://github.com/org/repo@ldap3-conversion#egg=opstools...
⠙ Installing...
⠹ Installing...
⠼ Installing...Warning: You installed a VCS dependency in non-editable mode. This will work fine, but sub-dependencies will not be resolved by $ pipenv lock.
  To enable this sub-dependency functionality, specify that this dependency is editable.

Adding opstools to Pipfile's [dev-packages]...
✔ Installation Succeeded 
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
⠸ Pinning VCS Packages...
⠸ Pinning VCS Packages...
⠹ Pinning VCS Packages...Branch ldap3-conversion set up to track remote branch ldap3-conversion from origin.
Switched to a new branch 'ldap3-conversion'
✔ Success! 
Locking [packages] dependencies...
Updated Pipfile.lock (0dbce1)!
```
### Steps to replicate

1. Start Terminal.app on OS X
2. Try to install a git SCM source from a private repo
3. Prompt should sit at "installing" where it expects the username and password, but a typical end-user will not know to blindly type in username/password, nor can you see what you type for the username.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/Library/Python/2.7/site-packages/pipenv'`

Python location: `'/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python'`

Python installations found:

  - `2.7.10`: `/usr/bin/python`
  - `3.7.0`: `/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m`
  - `3.7.0`: `/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.2.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64',
 'python_full_version': '2.7.10',
 'python_version': '2.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `VERSIONER_PYTHON_PREFER_32_BIT`
  - `TERM_PROGRAM_VERSION`
  - `LOGNAME`
  - `USER`
  - `PATH`
  - `HOME`
  - `TERM_PROGRAM`
  - `LANG`
  - `TERM`
  - `Apple_PubSub_Socket_Render`
  - `VERSIONER_PYTHON_VERSION`
  - `SHLVL`
  - `SECURITYSESSIONID`
  - `XPC_FLAGS`
  - `TMPDIR`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `TERM_SESSION_ID`
  - `XPC_SERVICE_NAME`
  - `SSH_AUTH_SOCK`
  - `SHELL`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `__CF_USER_TEXT_ENCODING`
  - `PWD`
  - `PIP_SHIMS_BASE_MODULE`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/mtdeguzis`

---------------------------

Contents of `Pipfile` ('/Users/mtdeguzis/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "2.7"

```

</details>

**Comment by jxltom** [comment]
Similar with https://github.com/pypa/pipenv/issues/3399

**Comment by matteius** [comment]
We dropped the progress bar a while ago -- is this still an issue?

**Comment by flipcc** [comment]
It is still an issue. Just used `pipenv lock` on version 2023.11.15 on MacOS and entered my password+enter while the spinner was visible, see result:

```sh
⠇ Locking...
⠇ Locking...
⠇ Locking...
⠋ Locking...
INFO:pipenv.patched.pip._internal.vcs.git:Resolved ssh://****@github.com/...
```

and ta-da it worked. That is unusable, if one is not lucky enough to know about this problem. The issue does not arise when executing `pipenv install` after the locking is done, as this subscommand does not show the spinner:

```sh
Installing dependencies from Pipfile.lock (2defd8)...
Enter passphrase for key '/Users/my.name/.ssh/id_rsa': 
Enter passphrase for key '/Users/my.name/.ssh/id_rsa': 
Enter passphrase for key '/Users/my.name/.ssh/id_rsa':
```

Hope this issue gets reopened.

**Comment by matteius** [comment]
@flipcc would be better if you could open a new issue for this.
