### ISSUE TITLE
Pipfile package version, remove "==version"

### ISSUE THREAD

**Issue by perfecto25** [pypa/pipenv#3413]
Hello, currently if I need to specify a version of pkg in pipfile, I need to use the == 

```
[packages]
Quart = "*"
Flask = "*"
Flask-Bootstrap = "*"
PyYAML = "*"
dictor = "*"
loguru = "*"
salt = "==2018.3.3"
tinydb = "*"
```

this messes up a lot of syntax coloring in IDEs and is generally confusing since theres already a "=" char prior to the double ==

why not have it be specified like this, w/o the use of double ==
salt = "2018.3.3"

Is there a reason to use the double ==

**Comment by nijave** [comment]
I think this gets extrapolated so you could put other operators in there as well (basically anything pip understands)
i.e. `>=0.2,<0.3`

So there are other options besides just ==
