### ISSUE TITLE
fish 3.0 breaks how pipenv shell prepends python path

### ISSUE THREAD

**Issue by grahamannett** [pypa/pipenv#3414]
### Issue description

I think this is new since I just updated fish shell and it was the first thing I noticed that was broken.  The $PATH upon using pipenv shell seems to put previous $PATH then virtualenv path then $PATH again, but I am not entirely sure.   I believe it used to be work fine out of the box with just prepending the virtualenv PATH to my $PATH but after my fish_user_path (which also was not preferable)

### Expected result

Have pipenv prepend virtualenv to path in fish shell

### Actual result

Has virtualenv python path in between two copies of $PATH for some reason

### Steps to replicate

Update to fish 3.0

Other:

Yeah I rolled back fish to 2.7.1 (if anyone has this issue, try `brew switch fish 2.7.1`) and seems to work.  Think its specific to pipenv prepending to path.  Also have issues with pipenv prepending to $PATH after $PATH but before the $fish_user_paths stuff so maybe could be done as one fix?

**Comment by ryoppippi** [comment]
I spent a lot of time on this problem and my conclusion is the same as @grahamannett .
Yeah on Fish 3.0 it does not work......
On bash and fish 2, it works fine!
I'm using macOS Mojave with fish

**Comment by thepreacher** [comment]
Currently facing the same issue. I actually posted to [https://superuser.com/questions/1396889/fish-shell-virtualenv-path-not-prepended-to-path](Superuser) with details of the problems before discovering this issue.

**Comment by grahamannett** [comment]
I think I may have created a patch but Im not sure if it will break previous fish versions at this point.

**Comment by thepreacher** [comment]
I've just come across the [https://github.com/fish-shell/fish-shell/issues/5456](url) which seems to me to be causing this issue with pipenv. There are a couple of workarounds there but not fix yet.

**Comment by erinxocon** [comment]
For anyone that finds this issue.  

```
brew unlink fish
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/2827b020c3366ea93566a344167ba62388c16c7d/Formula/fish.rb
```
This will install version 2.7.1 of fish.

**Comment by techalchemy** [comment]
from https://github.com/fish-shell/fish-shell/issues/5456#issuecomment-451697811:

> The problem is that you are directly manipulating PATH, which makes it hard for fish to know what's the originally exported PATH, what is fish's customized view of PATH, and what the correct order of PATH entries is.

i.e. using `set -gx PATH` and expecting it to be inherited in the correct order is not going to work, and you should look at using a workaround like the ones proposed.  

So, if you are using fish as a login shell, you can resolve this (or at least have fish prepend pyenv's paths) by using the following:

```fish
if status --is-login
    set -g fish_user_paths ~/.pyenv/shims fish_user_paths
end
```

And if you only use fish as an interactive shell, you can use this fix in your fish config:

```fish
if not contains ~/.pyenv/shims $fish_user_paths
    set -g fish_user_paths ~/.pyenv/shims $fish_user_paths
end
```


I'm going to close this as it's a fish issue and there are several workarounds plus a fix lined up for the next minor release of fish. Thanks for the report!

**Comment by grahamannett** [comment]
i know this is closed but it still seems quite broken for me at the least and only related to `pipenv shell` with fish 3.0.  

Using `source /Users/graham/.local/share/virtualenvs/example_virtual_env/bin/activate.fish` works (it places the virtualenv python path in front of everything for my path where as using `pipenv shell` places the virtualenv python path after everything but before $fish_user_paths

I don't think this is a fish problem as I am using a fresh install and have nothing impacting my path besides stuff in /etc/paths

**Comment by ElijahLynn** [comment]
Using latest everything right now, and I had to do a:

`fish_add_path /Users/user/.local/bin` after I ran `pipx install pipenv` to get `pipenv` to show up as a command from PATH.
