### ISSUE TITLE
before install package to project, should run pipenv shell

### ISSUE THREAD

**Issue by netroby** [pypa/pipenv#3419]
The official document not tips the right way to install package .

You must switch to virtual env first `pipenv shell`

Then you can install requests `pipenv install requests`

Or you will failed , `pipenv run python ` will show you : no module requests found.

**Comment by frostming** [comment]
> You must switch to virtual env first pipenv shell
No it's not.

What did you observe if you do `pipenv install requests` and `python run python` then import requests inside?

**Comment by netroby** [comment]
![Uploading image.png…]()
