### ISSUE TITLE
How to prevent or recover from accidental use of pip install?

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [pypa/pipenv#3420]
Please bear with me, I'm new to pipenv so my question might be quite silly.

**Once pipenv is installed is there a way to prevent users from accidentally (un)installing packages with "pip install"?**

If my understanding is correct "pip install" works at a lower level than pipenv and will therefore bypass the Pipfile and Pipfile.lock. So if someone installs a new package in their local environment using pip this will go unnoticed by our deployment script (which calls pipenv sync) and will cause errors on our server.

Now of course you could say that it's the user's fault for not using the right command. But my team works on a very large number python projects and the migration to pipenv will happen progressively. Inevitably people will mistakenly use pip from time to time.

**What would you recommend to either avoid, warn about or recover from bypassing pipenv?** Ideally I'd like a way to prevent direct call to "pip install", although should not be the default behaviour. **But at the very least I'd like to have a pipenv command to detect discrepancies** between installed packages and Pipfile.lock. I can get some of these discrepancies by running "pipenv clean --dry-run" but I can't find a way to detect removed packages still in Pipfile.

My plan would be to add a git hook in my projects to report such discrepancies on commit so there's no way they would propagate from one team member's local environment to the rest of the team or the application server.

**Comment by jxltom** [comment]
How is your production server getting deployed? Install/uninstall packages in local dev and copy them to deploy server? I try to understand why you have to take the packages in local development machine as the final deployed environment.

If so, how about setup CI/CD? In that, you install packages with pipenv in virtualenv and run some tests to make sure your packages are not missing

**Comment by frostming** [comment]
To recover as you said, `pipenv sync` can sync the working set to the content of Pipfile.lock. Then you can use Pipenv to install/uninstall packages.

`pipenv clean`, OTOH, can purge packages not specified in Pipfile.lock.

**Comment by geoffroy-noel-ddh** [comment]
Thank you both for the replies. Frostming, you're right, pipenv sync && pipenv clean will restore the working set exactly as it is in Pipfile.lock, thanks for the tip.

(@jxltom currently we have requirements.txt in our github repos and we use 'fabric' and git to deploy automatically to the servers and install packages with something like git pull && pip install -U -r requirements.txt. My concern here is that if we start using pipenv, people can still use pip/requirements.txt by mistake and pip doesn't update the lockfiles so we have two disconnected states)

**Would it be useful to have a pipenv command to tell the difference between installed packaged and Pipfile.lock?**

Here's a simple use case:
```
virtualenv env
env/bin/pip install pipenv
. env/bin/activate
pipenv install six 
pip install ujson
pip uninstall -y six 
# (1)
pipenv sync
=> reinstall six but ujson is still there
pipenv clean
=> removes ujson but also pipenv, virtualenv, ...! I believe this is because the virtualenv wasn't created by pipenv?
```

In (1), I wish I could use a command like this to show differences between Pipfile.lock and the installed packages:
```pipenv graph --diff```

```
+ujson==1.35
-six==1.12.0
```

Would such command be useful?

**Comment by frostming** [comment]
> removes ujson but also pipenv, virtualenv, ...! I believe this is because the virtualenv wasn't created by pipenv?

Yeah, that is a problem. Maybe we should filter out pipenv and dependencies when cleaning.

> I wish I could use a command like this to show differences between Pipfile.lock and the installed packages

That's worth considering, I'm +1 on this, except I prefer `pipenv sync --dry-run`. Would you like to submit a PEEP for it?

**Comment by jxltom** [comment]
A workaround is to comparing ```pipenv run pip freeze``` and ```pipenv lock -r -d``` but you need to write a simple script for comparing that, and then you could use it in git hooks.

**Comment by techalchemy** [comment]
thanks for the issue, the real way to 'recover' is just to re-install with pipenv which will resolve it properly

closing for now, good luck!
