### ISSUE TITLE
Specify Alternate Index for dev

### ISSUE THREAD

**Issue by kylecribbs** [pypa/pipenv#3421]
Allow a [[source]] to be tied to --dev not jut a single package..

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[[source]]
name = "home"
url = "https://someurl.org/simple"
verify_ssl = true
**use_with = "dev"**

[dev-packages] 
pylint = "*"

[packages]

[requires]
python_version = "3.7"
```

When you pipenv install --dev it would install the dev packages with someurl.org/simple/ and the regular packages would install with pypi.org/simple/.

**Comment by frostming** [comment]
A PEEP is required for such a behavioral change. You can submit it under `peeps` folder via a PR.

**Comment by kylecribbs** [comment]
Do you mind explaining what a PEEP is?

**Comment by frostming** [comment]
@kylecribbs It's a proposal document inside `peeps` folder:

https://github.com/pypa/pipenv/blob/master/peeps/PEEP-000.md

**Comment by kylecribbs** [comment]
It was submitted btw

**Comment by matteius** [comment]
@kylecribbs Sorry this issue has languished since you did try to open a PEEP.  Can you comment on if there is still a need to consider this?
