### ISSUE TITLE
pipenv shell session does not use Python found in venv - VIRTUAL_ENV does not appear to be set correctly

### ISSUE THREAD

**Issue by DanAtShenTech** [pypa/pipenv#3429]
### Issue description
When I create a venv with `pipenv --python 3.6`, it puts the venv in ~/.virtualenvs, which is fine.  However, I want to mirror the production machine, which has venv's located at /opt/virtualenvs/, so I created a .env file that contains only:
`WORKON_HOME=/opt/virtualenvs`

When I activate the shell, it seems to activate correctly but does not use the correct Python version, even though the venv contains the correct version (3.6) and shows as being activated.

> **FIRST** skip down and read _NOTE:  The following `pipenv --support` output . . ._ before reviewing the following Steps to Re-create

### Steps to Re-create:
_**Note:** The annotated series of commands shown below was executed after first creating a venv in ~/.virtualenvs using `sudo pipenv --python 3.6` and creating a .env file as described above._

**Disable the previously created .env file by renaming it:**
_vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ mv .env .envTEMP_

**Then activate the venv found at ~/.virtualenvs via `pipenv shell`:**
_vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ pipenv shell
Launching subshell in virtual environment…
 . /home/vagrant/.local/share/virtualenvs/GR_BH-DzdKWSvX/bin/activate
vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$  . /home/vagrant/.local/share/virtualenvs/GR_BH-DzdKWSvX/bin/activate_

**Check which Python and Python version:**
_(GR BH) vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ which python
/home/vagrant/.local/share/virtualenvs/GR_BH-DzdKWSvX/bin/python
(GR BH) vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ python --version
Python 3.6.8_

**Exit the shell:**
_(GR BH) vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ exit
exit_

**Reenable the .env file by renaming it back to .env:**
_vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ mv .envTEMP .env_

**Now move the venv from ~/.virtualenvs to /opt/virtualenvs and activate the venv now found at 
 /opt/virtualenvs via `pipenv shell`:**
vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ sudo mv ~/.virtualenvs/GR_BH-DzdKWSvX/ /opt/virtualenvs/
vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ pipenv shell
Loading .env environment variables…
Launching subshell in virtual environment…
 . /opt/virtualenvs/GR_BH-DzdKWSvX/bin/activate
vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$  . /opt/virtualenvs/GR_BH-DzdKWSvX/bin/activate_

**Check `which Python` and Python version:**
_(GR BH) vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ which python
/usr/bin/python
(GR BH) vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ python --version
Python 2.7.12_

**Exit the shell:**
_(GR BH) vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ exit
exit_

**Again create the venv in ~/.virtualenvs:**
_vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ pipenv --python 3.6
Creating a virtualenv for this project…
Pipfile: /vagrant/GR BH/Pipfile
Using /usr/bin/python3.6m (3.6.8) to create virtualenv…
⠼ Creating virtual environment...Using base prefix '/usr'
New python executable in /home/vagrant/.local/share/virtualenvs/GR_BH-DzdKWSvX/bin/python3.6m
Also creating executable in /home/vagrant/.local/share/virtualenvs/GR_BH-DzdKWSvX/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/bin/python3.6m
✔ Successfully created virtual environment!
Virtualenv location: /home/vagrant/.local/share/virtualenvs/GR_BH-DzdKWSvX_

**Execute `pipenv shell` with .env file still in place but with duplicate venvs - one at ~/.virtualenvs and one at /opt/virtualenvs:**
_vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ pipenv shell
Loading .env environment variables…
Launching subshell in virtual environment…
 . /opt/virtualenvs/GR_BH-DzdKWSvX/bin/activate
vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$  . /opt/virtualenvs/GR_BH-DzdKWSvX/bin/activate

**Check `which python` and Python version:**
(GR BH) vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ which python
/home/vagrant/.local/share/virtualenvs/GR_BH-DzdKWSvX/bin/python
(GR BH) vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ python --version
Python 3.6.8_

**Exit shell:**
_(GR BH) vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ exit
exit_

**Remove venv from ~/.virtualenvs and run `pipenv shell` again:**
_vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ sudo rm -r ~/.virtualenvs/GR_BH-DzdKWSvX/
vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ pipenv shell
Loading .env environment variables…
Launching subshell in virtual environment…
 . /opt/virtualenvs/GR_BH-DzdKWSvX/bin/activate
vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$  . /opt/virtualenvs/GR_BH-DzdKWSvX/bin/activate_

**Check `which python` and Python version again:**
_(GR BH) vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ which python
/usr/bin/python
(GR BH) vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ python --version
Python 2.7.12_

### System:
- Running Ubuntu 16.04.5 LTS in VirtualBox within Vagrant
- Python versions installed:  2.7, 3.5 and 3.6

### Some system commands and what they return:
- python --version returns:  Python 2.7.12
- python3 --version returns:  Python 3.5.2
- pip --version returns:  pip 18.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
- pip3 --version returns:  pip 18.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
- pip show pipenv returns:
Name: pipenv
Version: 2018.11.26
Summary: Python Development Workflow for Humans.
Home-page: https://github.com/pypa/pipenv
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: MIT
Location: /usr/local/lib/python3.6/dist-packages
Requires: certifi, virtualenv-clone, virtualenv, pip, setuptools
Required-by:

### NOTE:  The following `pipenv --support` output was obtained IMMEDIATELY AFTER executing the following at the command line:
**(Notice that the venv is activated from /opt/virtualenvs, but that the `VIRTUAL_ENV` variable in the following still contains: `/home/vagrant/.local/share/virtualenvs/GR_BH-DzdKWSvX`)**

_vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ pipenv shell
Loading .env environment variables…
Launching subshell in virtual environment…
 . /opt/virtualenvs/GR_BH-DzdKWSvX/bin/activate
vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$  . /opt/virtualenvs/GR_BH-DzdKWSvX/bin/activate
_(GR_BH) vagrant@vagrant-ubuntu-trusty-64:/var/sites/gr_bh$ python --version_
_Python 2.7.12_

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.6/dist-packages/pipenv'`

Python location: `'/usr/bin/python3.6'`

Python installations found:

  - `3.6.8`: `/usr/bin/python3.6m`
  - `3.6.8`: `/usr/bin/python3.6`
  - `3.5.2`: `/usr/bin/python3.5`
  - `3.5.2`: `/usr/bin/python3.5m`
  - `2.7.12`: `/usr/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.8',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.4.0-141-generic',
 'platform_system': 'Linux',
 'platform_version': '#167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018',
 'python_full_version': '3.6.8',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `XDG_SESSION_ID`
  - `PIP_PYTHON_PATH`
  - `SHELL`
  - `TERM`
  - `SSH_CLIENT`
  - `SSH_TTY`
  - `USER`
  - `LS_COLORS`
  - `VIRTUAL_ENV`
  - `WORKON_HOME`
  - `PIPENV_ACTIVE`
  - `PATH`
  - `MAIL`
  - `PWD`
  - `LANG`
  - `PS1`
  - `PYTHONDONTWRITEBYTECODE`
  - `HOME`
  - `SHLVL`
  - `LOGNAME`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `SSH_CONNECTION`
  - `LESSOPEN`
  - `XDG_RUNTIME_DIR`
  - `DISPLAY`
  - `LESSCLOSE`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/vagrant/.local/share/virtualenvs/GR_BH-DzdKWSvX/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/var/sites/gr_bh`
  - `VIRTUAL_ENV`: `/home/vagrant/.local/share/virtualenvs/GR_BH-DzdKWSvX`
---------------------------

Contents of `Pipfile` ('/vagrant/GR BH/Pipfile'):

```toml
[[source]]

name = "pypi"
url = "https://pypi.python.org/simple"
verify_ssl = true

[requires]

python_version = "3.6"

[dev-packages]

[packages]
```

### Output from `pipenv --support` WITHOUT venv activated:
Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.6/dist-packages/pipenv'`

Python location: `'/usr/bin/python3.6'`

Python installations found:

  - `3.6.8`: `/usr/bin/python3.6m`
  - `3.6.8`: `/usr/bin/python3.6`
  - `3.5.2`: `/usr/bin/python3.5`
  - `3.5.2`: `/usr/bin/python3.5m`
  - `2.7.12`: `/usr/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.8',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.4.0-141-generic',
 'platform_system': 'Linux',
 'platform_version': '#167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018',
 'python_full_version': '3.6.8',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `XDG_SESSION_ID`
  - `TERM`
  - `SHELL`
  - `SSH_CLIENT`
  - `OLDPWD`
  - `SSH_TTY`
  - `USER`
  - `LS_COLORS`
  - `MAIL`
  - `PATH`
  - `PWD`
  - `LANG`
  - `SHLVL`
  - `HOME`
  - `LOGNAME`
  - `SSH_CONNECTION`
  - `LESSOPEN`
  - `DISPLAY`
  - `XDG_RUNTIME_DIR`
  - `LESSCLOSE`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:
  - `PATH`: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/vagrant/.virtualenvs`
---------------------------

**Comment by frostming** [comment]
This is an issue with virtualenv: the activate script is bound to the python in the old location. You can run following commands to see what it prints:
```
source /opt/virtualenvs/GR_BH-DzdKWSvX/bin/activate
which python
echo $PATH
```
You will see the old path is prepended to $PATH. Pipenv just wraps virtualenv and can't help here. Thanks.

**Comment by DanAtShenTech** [comment]
Thank you.  I would ask for some clarification, though:
pipenv currently only creates virtualenvs in either a global location or the project directory while [virtualenv allows you to specify the directory where the venv is created](https://virtualenv.pypa.io/en/stable/userguide/#usage).
 It seems like, since virtualenv allows you to specify ANY location for a new venv, then pipenv should provide the same capability.  As an example, I was simply trying to duplicate a production server setup on my dev/test machine.  Production has virtualenvs stored at /opt/virtualenvs.  I thought I was doing things right by creating the venv with pipenv and moving it to /opt/virtualenvs on the dev/test machine - I didn't realize that the path to the venv was stored inside the venv activation script, so when I activated the venv to do some further development after moving it to /opt/virtualenvs, I was encountering the above problem.  The [pipenv docs SEEM to indicate](https://pipenv.readthedocs.io/en/latest/advanced/#custom-virtual-environment-location) that you can have pipenv place virtualenvs wherever you want when they are created:

> Pipenv automatically honors the WORKON_HOME environment variable, if you have it set — so you can tell pipenv to store your virtual environments wherever you want, e.g.:

But you CAN'T place the venv wherever you want when creating it with pipenv (I also recently posted [another question ](https://github.com/pypa/pipenv/issues/3403) related to this concern).  At a minimum, it seems like the above should be reworded to something like this:

> Pipenv automatically honors the WORKON_HOME environment variable (if you have it set) to locate your virtual environment (note, however, that the value is not used when creating a new virtual environment with pipenv).

Things seem to work OK in production (specifying the venv location via WORKON_HOME) because (as I think I've just learned) there is a difference between ACTIVATING a venv (for development purposes) and USING a venv (for deployment purposes).  It seems that venvs can safely be placed where needed for deployment.  My use case of having a development server set up exactly like a production server might not be the norm, but I would still request consideration of providing a parameter to pipenv in order to allow creation of the venv wherever desired.  And I would also request a change to the documentation similar to the above suggestion to state clearly that WORKON_HOME is only honored when accessing a venv, not when creating a new venv.  Thank you.

**Comment by frostming** [comment]
@DanAtShenTech 
> But you CAN'T place the venv wherever you want when creating it with pipenv

Just set the environment variable in your shell, not in .env file

**Comment by DanAtShenTech** [comment]
One follow up comment in case it might of use to others:  If I do `export WORKON_HOME=/opt/virtualenvs` as a non-root user and then `pipenv install some_package`, then I understandably get a permissions error.  If I then do `sudo pipenv install some_package`, it creates a new venv in root's home/.virtualenvs folder.  I'm pretty new to Linux, so it wasn't apparent that WORKON_HOME, though set as the non-root user, would NOT be honored when doing `sudo pipenv install some_package`.  I'm remedying this by just switching to root when I need to install a new package, setting WORKON_HOME as the root user, and then doing `pipenv install some_package`.
