### ISSUE TITLE
Suppress 'Creating a virtualenv for this project…' warning

### ISSUE THREAD

**Issue by AlexOQ** [pypa/pipenv#3433]
When running any '$ pipenv [command]' that creates a new virtual environment the following output is WARN level logging:
`Creating a virtualenv for this project…`
`Pipfile: [path]/Pipfile`
`Using /usr/bin/python3.6 (3.6.6) to create virtualenv…`
I am using build agents, and would like to treat WARN logging as 'there's something I might do to avoid some issue I am warned about'. Is there a possibility either to:
a) lower the log level - INFO or DEBUG, or
b) flag to suppress those warnings

**Comment by frostming** [comment]
Not only this message, as you may have noticed, other hints are also printed to stderr, in order that people will get clean output when redirecting stdout to some file.

**Comment by AlexOQ** [comment]
You are correct. But this specific action should be togglable, since I know what's the expected outcome when I run say `pipenv sync` on a clean agent. And I'd like this message to be INFO, for cleanliness sake.
If anyone would point me out to an example of additional flag implementation, I can do that myself.

**Comment by MaxLitvak** [comment]
I also ran into this problem which was pretty annoying. I fixed by changing the **core.py** file in the pipenv folder in **python site packages**. Just comment out this part of the file `click.echo(
            "{0}: Pipenv found itself running within a virtual environment, "
            "so it will automatically use that environment, instead of "
            "creating its own for any project. You can set "
            "{1} to force pipenv to ignore that environment and create "
            "its own instead. You can set {2} to suppress this "
            "warning.".format(
                crayons.green("Courtesy Notice"),
                crayons.normal("PIPENV_IGNORE_VIRTUALENVS=1", bold=True),
                crayons.normal("PIPENV_VERBOSITY=-1", bold=True),
            ),
            err=True,
        )`
