### ISSUE TITLE
pipenv check --db?

### ISSUE THREAD

**Issue by kylecribbs** [pypa/pipenv#3440]
I read somewhere that you can pass flags to pipenv check as it were safety; however, when i try pipenv check --db it is invalid. I live in an isolated environment with no access to the internet so the --db flag is highly used.

**Comment by frostming** [comment]
There's no such option in `clean` command.
https://pipenv.readthedocs.io/en/latest/#pipenv-check

**Comment by kylecribbs** [comment]
I am not sure how this relates to the clean command.

I was more wondering if you can use safety-db with pipenv check?

**Comment by frostming** [comment]
@kylecribbs That was a typo..I meant `check`. Do you mean using the offline safety-db? We don't support this yet.

**Comment by kylecribbs** [comment]
@frostming Yes that is what I was referring to. Do you plan on implementing this or is it still being looked into?

**Comment by kylecribbs** [comment]
@frostming Would you accept a pull-request if i added this in?

**Comment by frostming** [comment]
@kylecribbs yes it would be great and i am glad to review. Also, a PEEP is required for a new feature, I am +1 for this feature.

**Comment by kylecribbs** [comment]
Done and tested.. Do I submit a PEEP with the pull request? What is the general method of doing a pull request? Create a new branch with the updates, etc?

**Comment by frostming** [comment]
@kylecribbs fork the repo to your own and submit the updates to a new branch.

**Comment by kylecribbs** [comment]
@frostming I did three updates.. Wanted to see what you thought.. I added a --squelch to pipenv to ignore the stdout messages. I added an --output to allow users to specify json, full-report, bare, or default.. Default is how you were writing the vulnerabilities.. I wanted to give the users the option to do other options from safety.. A really good use case fo this is --squelch and --output json.. then users can use pipenv check in their CI and do a count of vulnerabilities or whatever from the json to determine if it should go through their pipeline.. Lastly, i added the --db flag so users can specify a path to their local database json file instead of reaching out to the internet.. Watch out for the pull request!

**Comment by frostming** [comment]
@kylecribbs Tons of behavioral changes, we need to fully discuss on it. A PEEP is definitely required.

**Comment by kylecribbs** [comment]
@frostming I will draft it up. At least they are all optional.

**Comment by kylecribbs** [comment]
@frostming no rush just curious how long the PEEP approval process is?
