### ISSUE TITLE
Documentation does not include enough useful Pipfile examples

### ISSUE THREAD

**Issue by charlesreid1** [pypa/pipenv#3450]
### Issue description

The documentation is extensive but is missing information for folks who want to include a Pipfile instead of a requirements.txt with their packages/projects (that was the original motivation for pipenv to be created). There are not enough useful examples and no explanation of how to write Pipfiles in the documentation. I only found two Pipfile examples that showed how software should be installed, both in the "Advanced usage" section (which itself was hard to find, as it does not show up on the side navigation bar until you are on a page in the advanced usage section). Only one example has an explanation: <https://pipenv.readthedocs.io/en/latest/advanced/#specifying-basically-anything> (the title of the section, "Specifying Basically Anything," also does not indicate it contains Pipfile examples).

### Expected result

I expected the documentation (basic documentation, not advanced usage documentation) to contain a few paragraphs explaining how to write a Pipfile, so users can write their own Pipfile to include with their projects.

### Actual result

None found

### Steps to replicate

N/A - documentation-related

**Comment by tapaswenipathak** [comment]
Hi folks: Writing a PR.
