### ISSUE TITLE
pipenv graph --json-tree issues Courtesy warning

### ISSUE THREAD

**Issue by thernstig** [pypa/pipenv#3459]
### Issue description

`pipenv graph --json-tree` issues the warning `Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.`

`pipenv graph` (wihtout --json-tree) does not issue a warning.

### Expected result

`pipenv graph --json-tree` should never issue a warning, no matter if inside a pipenv shell or not. This is have consistency between `pipenv graph` and `pipenv graph --json-tree`.

The command "graph" is natural to execute both without and with the pipenv environment activated.

### Steps to replicate

1. Activate a pipenv shell with `pipenv shell`
2. Run `pipenv graph --json-tree`

**Note**: This happens on Windows 10 Pro, inside VS Code when the terminal is set to use PowerShell. It does not happen in PowerShell opened outside of VS Code nor in other shells I tried..

I'd be humble to say that this is definitely not a huge issue. But for consistency it'd be nice to not show this warning. The reason is that one have to programmatically remove this warning in some scenarios, since it only happens sometimes and in some environments. Also the project is shared so I do not have the power to always set `PIPENV_VERBOSITY=-1` environments. I want to parse the JSON output in Python, so the only workaround has been to programmatically remove the first line in the scenario the warning is shown.

-------------------------------------------------------------------------------

Not able to add `$ pipenv --support` due to reasons.

**Comment by frostming** [comment]
@thernstig VSCode terminal actually uses **activated virtualenv** directly rather than `pipenv shell`, which makes the difference. Can you confirm by printing the value of `PIPENV_ACTIVE` in the terminal?

**Comment by uranusjr** [comment]
Not in Shellingham, but https://github.com/pypa/pipenv/blob/8212a211aa417ae5e1d6402485dd82937bf3eef0/pipenv/patched/crayons.py#L40

**Comment by matteius** [comment]
I believe this is resolved now, but let us know if it isn't.
