### ISSUE TITLE
ERROR: ERROR: Package installation failed...

### ISSUE THREAD

**Issue by tempegarit** [pypa/pipenv#3464]
I've never met this error before. I don't know what to do. 
I installed pyaudio and speechrecognition
![image](https://user-images.githubusercontent.com/44483328/51438441-c8e0bd80-1cde-11e9-8132-6f1011eedb04.png)
Then this error occurs
![image](https://user-images.githubusercontent.com/44483328/51438461-12310d00-1cdf-11e9-9500-4fbaf6d44011.png)
![image](https://user-images.githubusercontent.com/44483328/51438476-49072300-1cdf-11e9-9571-5fdeb82a0ba5.png)
Then i ran this:
`'pipenv lock --clear'` and install pyaudio and speechrecognition again. Same error occur again.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'c:\\users\\asus\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pipenv'`

Python location: `'c:\\users\\asus\\appdata\\local\\programs\\python\\python37\\python.exe'`

Python installations found:

  - `4.5.11`: `C:\Users\asus\Miniconda3\python.exe`
  - `3.7.2`: `C:\Users\asus\AppData\Local\Programs\Python\Python37\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.2',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17134',
 'python_full_version': '3.7.2',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `CM2013DIR`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DRIVERDATA`
  - `GOOGLE_API_KEY`
  - `GOOGLE_DEFAULT_CLIENT_ID`
  - `GOOGLE_DEFAULT_CLIENT_SECRET`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `ILBDIR`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `WINDIR`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenvûspecific environment variables:

Debugûspecific environment variables:

  - `PATH`: `C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\Microsoft VS Code\bin;C:\Users\asus\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\asus\AppData\Roaming\npm;C:\Users\asus\AppData\Local\Programs\Python\Python37;C:\Users\asus\AppData\Local\Programs\Python\Python37\Scripts;C:\Users\asus\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\;C:\Users\asus\.poetry\bin;`

---------------------------

Contents of `Pipfile` ('D:\\Code\\my code\\speech text\\Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
pyaudio = "*"
speechrecognition = "*"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('D:\\Code\\my code\\speech text\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "3909f3dcce81ff54bb36d2539b16d09d47149b5c33fafd3334daeccde72f126f"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "pyaudio": {
            "hashes": [
                "sha256:0d92f6a294565260a282f7c9a0b0d309fc8cc988b5ee5b50645634ab9e2da7f7",
                "sha256:259bb9c1363be895b4f9a97e320a6017dd06bc540728c1a04eb4a7b6fe75035b",
                "sha256:2a19bdb8ec1445b4f3e4b7b109e0e4cec1fd1f1ce588592aeb6db0b58d4fb3b0",
                "sha256:51b558d1b28c68437b53218279110db44f69f3f5dd3d81859f569a4a96962bdc",
                "sha256:589bfad2c615dd4b5d3757e763019c42ab82f06fba5cae64ec02fd7f5ae407ed",
                "sha256:8f89075b4844ea94dde0c951c2937581c989fabd4df09bfd3f075035f50955df",
                "sha256:93bfde30e0b64e63a46f2fd77e85c41fd51182a4a3413d9edfaf9ffaa26efb74",
                "sha256:cf1543ba50bd44ac0d0ab5c035bb9c3127eb76047ff12235149d9adf86f532b6",
                "sha256:f78d543a98b730e64621ebf7f3e2868a79ade0a373882ef51c0293455ffa8e6e"
            ],
            "index": "pypi",
            "version": "==0.2.11"
        },
        "speechrecognition": {
            "hashes": [
                "sha256:4d8f73a0c05ec70331c3bacaa89ecc06dfa8d9aba0899276664cda06ab597e8e"
            ],
            "index": "pypi",
            "version": "==3.8.1"
        }
    },
    "develop": {}
}

```
</details>

**Comment by tempegarit** [comment]
Oh, i miss the message. Thanks mate

**Comment by GustavoMSevero** [comment]
Some solution to this problem?

**Comment by haseebi** [comment]
i am still looking for .  i am  come across  the same issue !

**Comment by ronaldsantos63** [comment]
Some solution to this problem?
