### ISSUE TITLE
Current Directory not in PYTHONPATH

### ISSUE THREAD

**Issue by IvanAtanasov89** [pypa/pipenv#3465]
### Issue description

PYTHONPATH does not contain the current directory when using ```pipenv run```

### Expected result

When running something using run, for example tests

```shell
pipenv run pytest tests/
```

The PYTHONPATH / sys.path should contain the current directory so that packages containing modules to be tested can be found.

### Actual result

I get errors like

> E   ModuleNotFoundError: No module named 'hello'

And doing

```shell
pipenv run python
import sys
print(sys.path)
```

Shows that the directory the command was executed from is not in the path.

### Steps to replicate

Execute these commands in the root dir of a project using pipenv:

```shell
pipenv run python
import sys
print(sys.path)
```

**Comment by frostming** [comment]
```bash
λ pipenv run python -c "import sys;print(sys.path)"
['', 'D:\\Programs\\Python\\Python37-32\\python37.zip', 'D:\\Programs\\Python\\Python37-32\\DLLs', 'D:\\Programs\\Python\\Python37-32\\lib', 'D:\\Programs\\Python\\Python37-32', 'C:\\Users\\frostming\\.virtualenvs\\mynew-Cn1cpy9p', 'C:\\Users\\frostming\\.virtualenvs\\mynew-Cn1cpy9p\\lib\\site-packages']

D:\Workspace\mynew
λ python -c "import sys;print(sys.path)"
['', 'D:\\Programs\\Python\\Python37-32\\python37.zip', 'D:\\Programs\\Python\\Python37-32\\DLLs', 'D:\\Programs\\Python\\Python37-32\\lib', 'D:\\Programs\\Python\\Python37-32', 'D:\\Programs\\Python\\Python37-32\\lib\\site-packages']

λ pipenv run python -c "import my_module"
Hello world
```
Can you confirm the cause?

**Comment by IvanAtanasov89** [comment]
Thanks for the response @frostming 

It turns out that executing ```pytest tests/``` instead of ```python -m pytest tests/``` does not add the current directory to the path and that was my issue. https://docs.pytest.org/en/latest/pythonpath.html

Checking sys.path again now and I can see that '' is present so I think this can be closed.
