### ISSUE TITLE
Bug fix releases

### ISSUE THREAD

**Issue by Diggsey** [pypa/pipenv#3467]
I'm still stuck on `pipenv==2018.7.1`:

> 2018.11.26 - broken ([access denied](https://github.com/pypa/pipenv/issues/3391))
2018.11.14 - broken ([access denied](https://github.com/pypa/pipenv/issues/3391))
2018.10.13 - broken ([Mercurial get_revision_sha](https://github.com/pypa/pipenv/issues/3090))
2018.10.9 - broken ([Mercurial get_revision_sha](https://github.com/pypa/pipenv/issues/3090))
2018.7.1 - works

Prior to 2018.7.1, the last working version for me was on the old versioning scheme.

The problem is that whilst these issues are fixed fairly promptly, there is often no bug fix release, and by the time the next release occurs, new features have been added or a refactor has happened and one of them causes another show-stopping bug.

Having separate branches for new features/bug fixes, or even just more frequent releases would avoid a lot of the frustration.

Also, it wouldn't be such a problem being on an old version, if the format of the lockfile didn't change so often: this makes it hard to collaborate because everyone wants to be on roughly the same version so that the lockfile doesn't get completely trashed every time someone generates it from a different pipenv, and yet we can't be on the same or even similar pipenv versions because everyone has maybe one or two specific versions that work on their particular OS, and they're forced to stick with that.

**Comment by frostming** [comment]
Redirect to #3742
