### ISSUE TITLE
pipenv tutorial helloworld from dev to production

### ISSUE THREAD

**Issue by elfelround** [pypa/pipenv#3484]
hello, i would like to recommend a video/blog of a helloworld development to production tutorial

i have been trying to achieve this with django using pipenv instead of virtualenv with a few issues

**Comment by tapaswenipathak** [comment]
Hi folks: Writing a PR.

**Comment by ShivanS93** [comment]
What are your issues?

Taking a Django project to production in itself can be tricky.

```
pip install pipenv

mkdir project
cd project

pipenv lock # creates a Pipfile and Pipfile.lock

pipenv install django
# django stuff

pipenv install gunicorn #wsgi service used to for django deployment

#deploy django steps here
```

This would be a starting point. Hope it helps.

**Comment by matteius** [comment]
We have improved the documentation to have example Dockerfile as well as complex lock file examples with multiple indexes support -- not sure that we need this ticket open anymore.  There are enough more tangible documentation requests in the backlog that anyone can open PRs to help improve; for me this request feels like something anyone could write blog posts or other articles about outside of pipenv's documentation.
