### ISSUE TITLE
Pipenv cannot 'run' commands in quotes with flags

### ISSUE THREAD

**Issue by crablab** [pypa/pipenv#3486]
### Issue description

When using `run` to run a command, pipenv is unable to run commands that includes flags when they are in quotes, rather than using `--` 

` pipenv run "python -m pytest" `

### Expected result

Python to run pytest. 

### Actual result

`Error: the command python -m pytest could not be found within PATH or Pipfile's [scripts].`

### Steps to replicate

`pipenv run "python" ` - runs fine 
`pipenv run "python -m"` - error
`pipenv run -- python` - runs fine
`pipenv run -- python -m` -runs fine

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.6/dist-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.6.3`: `/usr/bin/python3.6`
  - `3.6.3`: `/usr/bin/python3.6m`
  - `2.7.14`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.13.0-46-generic',
 'platform_system': 'Linux',
 'platform_version': '#51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018',
 'python_full_version': '3.6.3',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `XDG_CONFIG_DIRS`
  - `LANG`
  - `DISPLAY`
  - `SHLVL`
  - `LOGNAME`
  - `LANGUAGE`
  - `MANDATORY_PATH`
  - `XDG_VTNR`
  - `J2REDIR`
  - `J2SDKDIR`
  - `XAUTHORITY`
  - `JOURNAL_STREAM`
  - `COLORTERM`
  - `XDG_SESSION_ID`
  - `JAVA_HOME`
  - `NXJ_HOME`
  - `DESKTOP_SESSION`
  - `XDG_SESSION_DESKTOP`
  - `GDMSESSION`
  - `USERNAME`
  - `DEFAULTS_PATH`
  - `WINDOWPATH`
  - `DERBY_HOME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `VTE_VERSION`
  - `XDG_DATA_DIRS`
  - `PWD`
  - `QT_ACCESSIBILITY`
  - `SHELL`
  - `LEJOS_NXT_JAVA_HOME`
  - `XDG_SESSION_TYPE`
  - `WINDOWID`
  - `TERM`
  - `SSH_AGENT_PID`
  - `GTK_MODULES`
  - `XDG_CURRENT_DESKTOP`
  - `PATH`
  - `SSH_AUTH_SOCK`
  - `HOME`
  - `XDG_SEAT`
  - `XDG_RUNTIME_DIR`
  - `USER`
  - `OLDPWD`
  - `GPGKEY`
  - `ZSH`
  - `GOPATH`
  - `PAGER`
  - `LESS`
  - `LC_CTYPE`
  - `LSCOLORS`
  - `LS_COLORS`
  - `NVM_DIR`
  - `NVM_CD_FLAGS`
  - `NVM_BIN`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/crablab/.nvm/versions/node/v9.7.1/bin:/home/crablab/.cargo/bin:/home/crablab/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/crablab/android-studio/bin/studio.sh:/opt/lejos/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/crablab/Documents/TeamProject2019_02`

---------------------------

Contents of `Pipfile` ('/home/crablab/Documents/TeamProject2019_02/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "3.6"

```

</details>

**Comment by frostming** [comment]
The command shouldn't be wrapped in quotes, just use the run command as if it wasn't there.

**Comment by zacharylawrence** [comment]
> 
> 
> The command shouldn't be wrapped in quotes, just use the run command as if it wasn't there.

Are there any ways around this restriction? Just noticed that it conflicts with AWS ECS: https://docs.aws.amazon.com/AmazonECS/latest/userguide/ecs_run_task_fargate.html

>If your container definition does specify an ENTRYPOINT (such as sh,-c), the format should be an unquoted string, which is surrounded with double quotes and passed as an argument to the ENTRYPOINT command.

This makes it seem like I can't set `pipenv run` as the ENTRYPOINT in my docker image.
