### ISSUE TITLE
Pipenv seems to download binary wheels for other platforms and Python versions

### ISSUE THREAD

**Issue by dodumosu** [pypa/pipenv#3487]
thanks for all the hard work! i'm running devpi locally to speed up locking by using it as a PyPI mirror. while following the devpi server log, I noticed that requests are made for wheels for platforms and Python versions other than the version that I'm using. using the same mirror for pip without pipenv doesn't do the same thing, it just downloads the specific wheel for the platform and Python version I'm using.

**Comment by frostming** [comment]
Those artifacts are downloaded and needed by locking process, you can find more discussion details in #3830 
Close it now.
