### ISSUE TITLE
pipenv shell --fancy

### ISSUE THREAD

**Issue by feigaoxyz** [pypa/pipenv#3491]
I would really like to know that does `--fancy` do behind the scene so that user could understand when or who should invoke it.

As the [current documentation](https://pipenv.readthedocs.io/en/latest/#cmdoption-pipenv-shell-fancy) explains nothing for the usage:

> --fancy
>     Run in shell in fancy mode (for elegantly configured shells).

- What does `fancy mode` really mean? Is this somewhat common phrase that I missed?
- What is an `elegantly configured shell` with respect to bash, zsh, fish, etc.?

**Comment by techalchemy** [comment]
Agreed, the primary difference is that `--fancy` doesn't follow up with `source <activatescript>` & instead relies on the user having a shell that doesn't call path-manipulating scripts in every interactive shell session (pyenv, for example, manipulates your path when you load it and is often loaded in the wrong place, thus leaving it at the top of your `$PATH` no matter what after a new interactive session is started).

If the path is manipulated the user may accidentally install things globally without meaning to, which is obviously bad.

**Comment by frostming** [comment]
@feigaoxyz You can read more in https://docs.pipenv.org/en/latest/basics/#about-shell-configuration

Feel free to improve it via a PR if it is not clear enough.

**Comment by jamesstidard** [comment]
I was also curious about this flag. Assumed it was going to be something about colours and UTF-8.

Can I ask what the advantage of this flag is? I didn't see a noticeable speed increase in activating the shell (which was my guess). Though I wasn't able to use `time` to benchmark it as I wasn't should how to use that with a command that creates a subshell.

**Comment by ndim** [comment]
The above link is out of date and appears to have moved to https://docs.pipenv.org/basics/#about-shell-configuration
