### ISSUE TITLE
Pipfile.lock has incorrect index written for installed packages when using multiple index sources

### ISSUE THREAD

**Issue by ipstech** [pypa/pipenv#3495]
### Issue description

My Pipfile contains listings for three private PyPI servers (pypi_release, pypi_test, pypi_cache in that order) before the normal entry for the main PyPI index. When installing a package that exists on the pypi_cache index, the entry written in the Pipfile.lock lists "pypi_release" as the index instead of "pypi_cache." The "pypi_release" index does not contain this package, and all of the private PyPI servers have fallback to the main PyPI index disabled.

### Expected result

I would expect the actual index that the package was installed from to be written to the Pipfile.lock ("pypi_cache" in this case).

### Actual result

The entry for PySide2 lists "pypi_release" as the index instead of "pypi_cache."

### Steps to replicate

For testing I added PySide2 and its dependency to our pypi_cache server (I am able to successfully install when the only source in the Pipfile is just pypi_cache). Then I used `pipenv install PySide2` to install into the virtualenv successfully.

-------------------------------------------------------------------------------

*I had to redact some information related to paths and environment variables.*

*The pipenv that I am using was built locally using the setup.py and was installed into a brew installed version of Python with pip.*

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.27.dev0'`

Pipenv location: 

Python location: 

Python installations found:

  - `2.7.10`: `/usr/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '16.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64',
 'python_full_version': '2.7.10',
 'python_version': '2.7',
 'sys_platform': 'darwin'}
```

System environment variables:

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`

Debug–specific environment variables:

  - `SHELL`: `/usr/local/bin/bash`
  - `EDITOR`: `nvim`
  - `LANG`: `en_US.UTF-8`

---------------------------

Contents of `Pipfile`

```toml
[[source]]
url = "http://----.----.----.----:8081"
verify_ssl = false
name = "pypi_release"

[[source]]
url = "http://----.----.----.----:8082"
verify_ssl = false
name = "pypi_test"

[[source]]
url = "http://----.----.----.----:8080"
verify_ssl = false
name = "pypi_cache"

[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
pyside2 = "*"

[requires]
python_version = "2.7"
# vim: set filetype=config:

```

Contents of `Pipfile.lock`

```json
{
    "_meta": {
        "hash": {
            "sha256": "85b6e99cd7824509b0472a200460c3d1e08d45091ab7d36380de0d2caabab9d5"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "2.7"
        },
        "sources": [
            {
                "name": "pypi_release",
                "url": "http://----.----.----.----:8081",
                "verify_ssl": false
            },
            {
                "name": "pypi_test",
                "url": "http://----.----.----.----:8082",
                "verify_ssl": false
            },
            {
                "name": "pypi_cache",
                "url": "http://----.----.----.----:8080",
                "verify_ssl": false
            },
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "pyside2": {
            "hashes": [
                "sha256:171d0e43bb241a12c98ab7ae46706af8e7929c973225d1c9abaf18a73dc3dbf0",
                "sha256:31ca082427d2104b9ab61520c0a1435ce23073e54734f3bd671b37be471da9c1",
                "sha256:4d948c441d609868b77bdd8cdab7ac6e595a6f15ca82dde3fd700f73445da821",
                "sha256:4f7518cfa049272ce64e43ce06cf151bdd648c6884272d480ee4b188dbffc7f2",
                "sha256:d5e39cc5868e0b1415846df185a22940219bf1a5ec38a7d9be6c0cd15f413336",
                "sha256:dba738ae3cbe7f90360e0729832d741c6f74698da44614b18d44393f72745022"
            ],
            "index": "pypi_release",
            "version": "==5.12.1"
        },
        "shiboken2": {
            "hashes": [
                "sha256:034ea9104506dcf1c77308a73a7840f1715054b3aaeb86c7ae8b260e6572e410",
                "sha256:479a44f3b11c5d0ba3d581470db28b0788214526b2a26e173890aef47328d945",
                "sha256:49cb68fddd8bd302c0a9eb09554a99cad1b63bfc9440dd016b4fcd300af5612a",
                "sha256:c2a2261c906065b4fb1725bb075a841c72e44e28ca642adb06663d8299d0d9fc",
                "sha256:cf10631e1970ce22b3bc40673288afd55ba9b8a0d803ab0e4ed525b4a68ef6b0",
                "sha256:f4038e97eeffea96bcae932f005a3f7772734b38928e0d44e48af654525c38e3"
            ],
            "version": "==5.12.1"
        }
    },
    "develop": {}
}

```
</details>

**Comment by matteius** [comment]
I believe this was solved with my work on index restricted packages back in April/May.   @ipstech  Could you try with `2022.9.4` and we can revisit if you find there is still an issue?
