### ISSUE TITLE
Pipenv run is not finding binary in PATH (despite it being there)

### ISSUE THREAD

**Issue by 4thel00z** [pypa/pipenv#3496]
### Issue description

I tried to invoke `pipenv run pyo3-pack` which is installed on my system and retrievable by means of `where` and `which -a`, hence in my `PATH` variable etc.

### Expected result
My global pyo3-pack installation is called

### Actual result

```
pipenv run pyo3-pack develop
Error: the command pyo3-pack could not be found within PATH or Pipfile's [scripts].
```

### Steps to replicate
`pip3 install pyo3-pack`
Try to `make install ` the hyperjson package: https://github.com/mre/hyperjson

### Additional notes

I found out that the system_which implementation used in do_run_posix is buggy.
Switched it out with shutil.which which solved my problem.

core.py line 2271+:

```
 do_run_posix(script, command):
    command_path = shutil.which(script.command)
    if not command_path:
```

**Comment by noelmcloughlin** [comment]
This might be fixed, see https://github.com/pypa/pipenv/blob/main/pipenv/core.py#L1567-1571
