### ISSUE TITLE
docs: Main page references video that no longer exists

### ISSUE THREAD

**Issue by salty-horse** [pypa/pipenv#3499]
The file `docs/index.rst`, hosted at https://pipenv.readthedocs.io/en/latest/, embeds a Vimeo video ("Pipenv screencast") that no longer exists:

https://player.vimeo.com/video/233134524

If there is no intention to restore it, perhaps it should be replaced with the gif from the README:

https://s3.amazonaws.com/media.kennethreitz.com/pipenv.gif

**Comment by nachiketdhamankar** [comment]
Unable to get access to the gif.

https://s3.amazonaws.com/media.kennethreitz.com/pipenv.gif

**Comment by frostming** [comment]
Need another store for the image file, any recommendations?
