### ISSUE TITLE
Pipenv shell does not work in Travis CI

### ISSUE THREAD

**Issue by arnavb** [pypa/pipenv#3500]
### Issue description

`pipenv shell` is unable to activate the virtualenv in Travis CI.

### Expected result

`pipenv shell` should spawn a new virtualenv so I can run the commands that have been installed (pytest, mypy, etc.)

### Actual result

I get this output in the log:

```
$ pipenv shell
Launching subshell in virtual environment…
 . /home/travis/.local/share/virtualenvs/pypokedex-308VNbI2/bin/activate
  . /home/travis/.local/share/virtualenvs/pypokedex-308VNbI2/bin/activate
bash: /home/travis/.local/share/virtualenvs/pypokedex-308VNbI2/bin/activate: No such file or directory
```

When this happens, the command doesn't end but no further output is seen. Eventually Travis times out because of a lack of output.

The example that can replicate this is [this PR build](https://travis-ci.org/arnavb/pypokedex/jobs/488257079). The build times out after 10 minutes.

### Steps to replicate

Try using `pipenv shell` in Travis CI.

**Comment by AnderEnder** [comment]
`pipenv shell` spawns a new shell, which can not be used in shell scripts anyway.

`pipenv run` should be used in travis-ci to spawn a command installed into the virtualenv.

**Comment by arnavb** [comment]
Oh, ok. Thanks for clarifying.
