### ISSUE TITLE
Using old pip

### ISSUE THREAD

**Issue by jamesstidard** [pypa/pipenv#3501]
Hi,

`pip==19` current contains [a bug](pypa/pip/issues/6163) that is preventing a majority of my Python projects from building (those with a pandas dependency - it appears.

It is currently recommended to build virtual environments with `pip<19`. However, pipenv doesn't appear to allow you to easily specify the version of `pip` to use, honour the `pip` version installed by the base interpreter (provided by `--python`) or a pip requirement set in the `Pipfile`.

I understand that this is because `pipenv` wants to know the environment tools it's using to it can consistently build environments without the user being able to mess it up. However, would it be reasonable for `pipenv` to support a minimum version to allow the user to at least jump back a major version when issues like this come up. i.e. `pipenv install --python 3.7.2 --pip 18.1`.

Unless there is actually a way of currently handling this situation I was unable to find. I've tried changing the `pip` in the `pipenv` environment, the base interpreter's environment, the global system `pip`, and the `Pipfile`. 

However, I did find that doing `pipenv install pip==18.1 --dev --python 3.7.2` appeared to work. I think that would actually be considered a bug as following that with `pipenv install --dev` does not then use that 18.1 for subsequent installs - unless explicitly handed to `pipenv install` again.

Thanks

**Comment by AlmogCohen** [comment]
+1 I need this following [this bug](https://github.com/pypa/pip/issues/6163). I was unable to freeze pip to a specific version using the Pipfile. My projects with Pyinstaller fail to install.

The hacky solution I use for now is to run `pipenv run pip install pip==18.1` then simply running `pipenv update --dev` as I needed

**Comment by AlmogCohen** [comment]
Anyway it still blocks me as PyCharm is recreating the pipenv from scratch when a new interpreter is set. Then it keeps failing as it uses `19.1` again and again with no seeming way to override this behavior.

**Comment by sh-tech** [comment]
I'm facing the same issue.

**Comment by frostming** [comment]
The pip used in virtualenv is an offline packaged bundled with virtualenv. Not much Pipenv can do.
