### ISSUE TITLE
pipenv shell --fancy doesn't see any of the packages installed

### ISSUE THREAD

**Issue by danechitoaie** [pypa/pipenv#3509]
If I run `pipenv shell --fancy` then when I run my script it complains that none of the packages installed with `pipenv install` are available.

IfI run just `pipenv shell` it works and packages are recognized and script works but it messes up the shell (oh-my-zsh/prezto/fish).

`pipenv, version 2018.10.13`

`Python 3.7.2`

**Comment by heyoni** [comment]
I'm running into the same issue. It seems like the answer to our issue is discussed [here](https://github.com/pypa/pipenv/blob/ab09a3d7e42a7a97f76a5547384299d15e9be558/docs/basics.rst#-about-shell-configuration) however, I haven't been able to fix it.

The way I'm interpreting those instructions, is that I need to go into my shell config file and wrap everything in an `if status --is-login` block. Tried that but it doesn't resolve the issue but can confirm that nothing in the `if` block runs when using `pipenv shell --fancy`.

The only difference between using fancy and not using it is the `source ...` line appears in the latter. Other than that, I'm stuck. Sorry, wish I could be more helpful.

PS: Beware, changes you make when `--fancy` fails to enter your virtual environment can affect your system-wide packages. I learned that the hard way.

**Comment by danechitoaie** [comment]
I'm fine with `pipenv shell` also, all I want is for it to stop adding that `(scripts) ┏ daniels@` and messing with the prompt.

It adds the current venv name as prefix to my prompt and it messes it if you have custom themes for oh-my-zsh, or fish, etc.

**Comment by heyoni** [comment]
I figured out the issue but haven't got a good fix for it just yet. When using `pipenv shell` the `$PATH` variable looks good and has my virtualenv listed first. When using `--fancy` however, the path variable would be `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` + virtualenv + the rest...so something was adding those default folders, and it wasn't any config file of mine.

I google'd around a bit and found that `/etc/shells` on macos has all of those folders listed once per line, and moving the shells file to my desktop, where terminal can't find it solved the issue but ONLY for that terminal session. Restarting the terminal without `/etc/shells` causes other issues.

**Comment by techalchemy** [comment]
would need to see the output of `pipenv --support` to help more (issue template folks!) as I can't really see your paths or shell configs, but in general if you are using pyenv a lot of the time you will have that configured to run in every _interactive_ session and it will modify your path dynamically, so `pipenv shell --fancy` will still wind up with pyenv ahead of the virtualenv.

hope this helps, closing this one for now as the shell situation has been beaten to death a bit.

Also, please upgrade to the latest version

**Comment by heyoni** [comment]
Hey @techalchemy, no need to reopen the issue or anything but I ran `--support` and just thought I'd post it here in case you see anything obvious. My workaround at the moment is not to use the `--fancy` option and to avoid having the repo name show up twice, I set `theme_display_virtualenv` to no, so that's been working well enough for me so far :)

```
 ~  pipenv --support                                                                                          Thu Mar 21 10:26:05 2019
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv'`

Python location: `'/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7'`

Python installations found:

  - `3.7.1`: `/Library/Frameworks/Python.framework/Versions/3.7/bin/python3`
  - `3.7.1`: `/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m`
  - `2.7.15`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python`
  - `2.7.15`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

{'implementation_name': 'cpython',
 'implementation_version': '3.7.1',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.2.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST '
                     '2018; root:xnu-4903.241.1~1/RELEASE_X86_64',
 'python_full_version': '3.7.1',
 'python_version': '3.7',
 'sys_platform': 'darwin'}

System environment variables:

  - `Apple_PubSub_Socket_Render`
  - `CPPFLAGS`
  - `GOPATH`
  - `HOME`
  - `JAVA_HOME`
  - `LANG`
  - `LDFLAGS`
  - `LOGNAME`
  - `OMF_CONFIG`
  - `OMF_PATH`
  - `PATH`
  - `PWD`
  - `PYTHONDONTWRITEBYTECODE`
  - `SHELL`
  - `SHLVL`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `TMPDIR`
  - `USER`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `fish_prompt_pwd_dir_length`
  - `theme_display_virtualenv`
  - `__CF_USER_TEXT_ENCODING`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:


Debug–specific environment variables:

  - `PATH`: `/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/2.6.0/bin:/usr/local/java_home:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/grep/libexec/gnubin:/Users/jrevah/Library/Python/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/opt/freetds@0.91/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jrevah/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS`
  - `SHELL`: `/usr/local/bin/fish`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/jrevah`


---------------------------

</details>
```
