### ISSUE TITLE
How can I force pipenv create a virtualenv in a specific directory (creating .env file inside dir doesn't help, it anyway creates .venv folder in user home)? Why it has no command to create venv explicitely???

### ISSUE THREAD

**Issue by Ratak** [pypa/pipenv#3510]
**AVOID POSTING ISSUES UNDER THIS CATEGORY.**

If Pipenv is not functioning as you would like it to, consider filing either a bug report, or a feature request instead.

Please refer to [StackOverflow tag](https://stackoverflow.com/questions/tagged/pipenv) for more information.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by yawpitch** [comment]
Set a value for PIPENV_VENV_IN_PROJECT in your [environment](https://pipenv.readthedocs.io/en/latest/advanced/#configuration-with-environment-variables).

If set, pipenv will create .venv in the directory in which it is run, rather than in the global cache.

Read the note about **direnv** if you need to do this on a per-project basis.

**Comment by techalchemy** [comment]
Thanks for the response @yawpitch that is essentially spot on.  

@ratak Pipenv is not a tool for managing your virtualenvs, if you are looking for something to do that you would likely be better served just using a `virtualenv` or `venv` call directly.  The use of virtualenvs is an incidental need of the tool and the fact that you don't get to do fine-grain management is a design choice to limit  the number of switches

Thanks for the feedback, hope this clarifies things!
