### ISSUE TITLE
Generating requirements.txt ignores PyPI mirror

### ISSUE THREAD

**Issue by decaz** [pypa/pipenv#3518]
Pipenv does not consider `--pypi-mirror` option when generating requirements.txt file. It's always `-i https://pypi.org/simple` at the first line before any dependencies:
```
$ pipenv lock --pypi-mirror http://my.pypi.host -r
-i https://pypi.org/simple
...
```

**Comment by frostming** [comment]
`PIPENV_PYPI_MIRROR`, or the `--pypi-mirror` option, exist to **replace** the official index defined in Pipfile. The mirror URL varies in different platforms and servers and is not meant to be solidated in any kind of config files. It is an environment-dependant value.

If you do want your packages to be installed from another index source, specify it in the Pipfile and then `pipenv lock -r` will freeze it.
