### ISSUE TITLE
What's the --code-base option used for

### ISSUE THREAD

**Issue by jamesstidard** [pypa/pipenv#3525]
Hi,

I've been wondering what the `--code-base` option in the `pipenv install` command does. Does it mean to install a project that is local on that machine?

Sorry if this is documented, I wasn't able to find it in my searching.

Thanks.

**Comment by frostming** [comment]
As the [documentation](https://pipenv.readthedocs.io/en/latest/#pipenv-install) indicates, if `--code` is turned on, pipenv will discover dependencies from `import` statements in the codebase.

Feel free to send a PR to improve the hint.

**Comment by jamesstidard** [comment]
Great, Thanks @frostming.

Yeah, I did read that part of the documentation but I didn't quite put that together. My guess of what it might be used for was quite far off :) Maybe just because I've not come across other package managers with that feature before.

Would something like "auto-detect and install packages found in the code base's import statements" read OK? Unless that's is too clumsy of a sentence.

**Comment by frostming** [comment]
Closed via #3532
