### ISSUE TITLE
Problem installing tables (pytables / HDF5)

### ISSUE THREAD

**Issue by ricodude** [pypa/pipenv#3526]
### Issue description

I cannot install tables via pipenv.

### Expected result

Successful install.

### Actual result

Ends up with "ERROR: ERROR: Package installation failed..."

### Steps to replicate

1. Start with a completely new directory.

2. Run pipenv to install tables:
$ pipenv install tables

3. Output below - fails:
Creating a virtualenv for this project…
Pipfile: /Users/richard/Dropbox/Developer/Python-projects/tables_test/Pipfile
Using /Users/richard/.pyenv/versions/3.7.1/bin/python3.7 (3.7.1) to create virtualenv…
⠴ Creating virtual environment...Already using interpreter /Users/richard/.pyenv/versions/3.7.1/bin/python3.7
Using base prefix '/Users/richard/.pyenv/versions/3.7.1'
New python executable in /Users/richard/.local/share/virtualenvs/tables_test-LLkngvaS/bin/python3.7
Also creating executable in /Users/richard/.local/share/virtualenvs/tables_test-LLkngvaS/bin/python
Installing setuptools, pip, wheel...
done.

✔ Successfully created virtual environment! 
Virtualenv location: /Users/richard/.local/share/virtualenvs/tables_test-LLkngvaS
Creating a Pipfile for this project…
Installing tables…
Adding tables to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success! 
Updated Pipfile.lock (e5545a)!
Installing dependencies from Pipfile.lock (e5545a)…
An error occurred while installing tables==3.4.4 --hash=sha256:07bb9e96b762874e239ad8cec2cab2c4129abf576fffcdd4e961482dc7d5a0a6 --hash=sha256:09eed21e12a1286ac2e8c5e67a75d9c7a7f262883535a31ac0b985540135d8d6 --hash=sha256:0bd7e5d7ff90df3751bfb2494d41858b96118965edd8cc03758bbc638e2e2f2c --hash=sha256:2379bc98dd8caa6f5824daae4b3b1e53008af32c7b684c67deaeebc1a89a929e --hash=sha256:2cd49a98e750fe78b7a2b8e0efd69be608c8358f664f3705c98cc6f04da18a53 --hash=sha256:415731ae46dfdef7fbe305399a700a54b06a82c4331ba20cc64004fb40e79069 --hash=sha256:44289caf89efac435f49fa4bd298eb48969c026dec25d3a76e7955f1281d1bdf --hash=sha256:714f7162ffa4d470da8c9a067935520e5925384445bdb23989351b48d236345c --hash=sha256:82d98123cf67c012d6c7cb69c6733b51eb10d17fc40547bbb71ffedae8da4f90 --hash=sha256:b625fc71f082011806a60d3b7370f75e34b141dab549ed65957aed54d1f12f63 --hash=sha256:bc1621bd84769ff3f84cfd1481f93ed0c537db4b3355576270bdbb79bb390b1f --hash=sha256:bdc5c073712af2a43babd139c4855fc99496bb2c3f3f5d1b4770a985e6f9ce29 --hash=sha256:bed4f423dd33600907f1c3b88f994920f2b879b12bf83d4372f861ef4085e085 --hash=sha256:c3ac22e3391f67a381d9a3018fd7e0a1ccfcc88b5f61b0d051fe5eba8196388f --hash=sha256:d263f4380a5dad862efac774428bacb04c2339c4f165f2efdd228867abaffcf6 --hash=sha256:da98c8abfeefefad40110b994d5d06ac28d89b00d085530d377376b201566ebf --hash=sha256:e2e4e40d010a6aa0464e5e281d4aa15f64acd99fd881c0e1e4c1c567b7167dba --hash=sha256:e3bd7084dbf80ef347ad5d33645584e0fe7f8353cf2c33d8922a4c00034fa015 --hash=sha256:e8f9b20b9623c900e7007b89a9d3e315280b666ac70b38b0c191345f7d4d8585 --hash=sha256:f786d310cf954eaf52340680dfbc5c1190afc276093f5c454fab605a11488306 --hash=sha256:f97c8b5ebec23894fc56af25c6e73bc86b463cbccb1f9b9887def24cd7811e2c --hash=sha256:fd3e774ff048de838df39b018c171bff3ecd9f34a908395a475ba07ac270a34a! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/4 — 00:00:05
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/Users/richard/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipenv/core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "/Users/richard/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/Users/richard/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/Users/richard/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/Users/richard/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting tables==3.4.4 (from -r /var/folders/h2/x_t3tq6x2lqf_58yh1syy8w40000gn/T/pipenv-k4a888sn-requirements/pipenv-wmentora-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/4d/53/8f34ce887c2a2ad80518980419a5f6f41defc85a287a355987e559ce9385/tables-3.4.4.tar.gz', '    Complete output from command python setup.py egg_info:', "    /var/folders/h2/x_t3tq6x2lqf_58yh1syy8w40000gn/T/H5closeryxpk8x2.c:1:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]", '    main (int argc, char **argv) {', '    ^', "    /var/folders/h2/x_t3tq6x2lqf_58yh1syy8w40000gn/T/H5closeryxpk8x2.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]", '        H5close();', '        ^', '    2 warnings generated.', '    ld: library not found for -lhdf5', '    clang: error: linker command failed with exit code 1 (use -v to see invocation)', '    * Using Python 3.7.1 (default, Dec 28 2018, 22:42:29)', '    * USE_PKGCONFIG: True', '    .. ERROR:: Could not find a local HDF5 installation.', '       You may need to explicitly state where your local HDF5 headers and', '       library can be found by setting the ``HDF5_DIR`` environment', '       variable or by using the ``--hdf5`` command-line option.', '    ', '    ----------------------------------------']
[pipenv.exceptions.InstallError]: ['Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/h2/x_t3tq6x2lqf_58yh1syy8w40000gn/T/pip-install-zexnlhoy/tables/']
ERROR: ERROR: Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:02

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/Users/richard/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipenv'`

Python location: `'/Users/richard/.pyenv/versions/3.7.1/bin/python3.7'`

Python installations found:

  - `3.7.1`: `/Users/richard/.pyenv/versions/3.7.1/bin/python3`
  - `3.7.1`: `/Users/richard/.pyenv/versions/3.7.1/bin/python3.7m`
  - `3.4.0`: `/Users/richard/.pyenv/versions/3.4.0/bin/python3`
  - `3.4.0`: `/Users/richard/.pyenv/versions/3.4.0/bin/python3.4m`
  - `2.7.15`: `/Users/richard/.pyenv/versions/2.7.15/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.1',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.2.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST '
                     '2018; root:xnu-4903.231.4~2/RELEASE_X86_64',
 'python_full_version': '3.7.1',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `LDFLAGS`
  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `CPPFLAGS`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `PYENV_VERSION`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `PYENV_DIR`
  - `PATH`
  - `PWD`
  - `LANG`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `HOME`
  - `SHLVL`
  - `PYENV_SHELL`
  - `LOGNAME`
  - `PKG_CONFIG_PATH`
  - `__CF_USER_TEXT_ENCODING`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/richard/.pyenv/versions/3.7.1/bin:/usr/local/Cellar/pyenv/1.2.8_1/libexec:/Users/richard/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/richard/Dropbox/Developer/Python-projects/tables_test`

---------------------------

Contents of `Pipfile` ('/Users/richard/Dropbox/Developer/Python-projects/tables_test/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
tables = "*"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/Users/richard/Dropbox/Developer/Python-projects/tables_test/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "933d75c09dbfa93a7d44f5e87dc114c04d1b3997423d83dff1ec944920e5545a"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "numexpr": {
            "hashes": [
                "sha256:066d7202d3374d42203ce8ba2b007f14397fd083946abafebbc962215ead1759",
                "sha256:08196ac987324dc02147abcf1883b192aa5cd1a56a07c725310f1d0d703d5301",
                "sha256:37b04292cbb1e20bfb3428d5aeebe2bdd13368d458e508998087e40b68d8cc95",
                "sha256:426053be016a3584a10cae13f18692938ff7314988f69edd367b4ff60b370b5b",
                "sha256:47c205a2bca8477eaaa766ca2b86001ca0df4b61ae407196a3ba2420932b5dca",
                "sha256:4b65fe1b4565ccaab7a3617da1bd046987fb7dbc0bbe34e56aa08b05857259d1",
                "sha256:5839cd5f95b4088659cc5f6d25936c6a03a75c23be37f94a2885db0f6f234531",
                "sha256:5fe05f123e00170370c759734c395e5a4ae0ad4e6a3d370fd73e0dcd6669e665",
                "sha256:62d2853df0233fc04374679de20f39b93fdb7a664a0ee403fdb8e722328c5d4d",
                "sha256:688a25cfcd7be6fcce3f6d59fffca6105541e7a1598144b545b633a266e94113",
                "sha256:6a0470a6c07eaa6aa27affb9ee89ce91070747e44172870b020fd3ebe318950a",
                "sha256:6b70a0c372bb567ddb3039d046cccede284cee2a43688010a4110f6b2fe59421",
                "sha256:7f4e121bd59f3b5f7bbd9ca8873c815277c4994b22cfff8a7d57bdef9d00e939",
                "sha256:8213a3e84f3afadc0a4ab1fc0dab383482297f36dbf84b690bbe698b9b8c2ece",
                "sha256:97920e6c37553571ce55f951080d9e2b28589c1337c3788b5ae66dae3a0131d2",
                "sha256:9992ef8b9598a62364d46d4cb2f0f6285f4c77115f023dca821a50550044d8fc",
                "sha256:9c6b4dfcc978ad50a72f83fbaf0fe4706088f3b2623e365bc05036db4948e15d",
                "sha256:9ef58b5f8debcf0c573968f44709866210696aa476b0d22d9afe88da2bd70add",
                "sha256:a64bfd49359df8f87c34ed601ce857213d8678e314d8c99b972b36e35ff8f98f",
                "sha256:aa5b238af8f2915b39374d764ec0daa3d0a975a798f162c3ca30f1cd9fa9a274",
                "sha256:ae5c73f7412b7e70c88f6b384ad61e123d909b0c81a8d5edd33239eb9b5b3111",
                "sha256:c3850466765b9b374ff2ff40974a7b4b278b875f94314e038043f534aff8e139",
                "sha256:e99213c7fa5ffd5572afe065bab7a8507d750221e3fbba43fc15151056d108a1",
                "sha256:eac513cd2424c5f1b2c75bcb06402da407d74bb6f72584d599218228060c2468",
                "sha256:ecb0d0a1ac843f2b8c7afdc0c3ec4fcfcc275bbd0750065cc4112fcd14904c90",
                "sha256:ed96bc38a37fc34406ef76595235e5966d7d3a4123018e9a91d1b7307b4af425",
                "sha256:ee4c526517d89f92c9b9f9c1937ab15c9e3d33864213b4488e1dd30fbc43c87f",
                "sha256:fc218b777cdbb14fa8cff8f28175ee631bacabbdd41ca34e061325b6c44a6fa6"
            ],
            "version": "==2.6.9"
        },
        "numpy": {
            "hashes": [
                "sha256:0cdbbaa30ae69281b18dd995d3079c4e552ad6d5426977f66b9a2a95f11f552a",
                "sha256:2b0cca1049bd39d1879fa4d598624cafe82d35529c72de1b3d528d68031cdd95",
                "sha256:31d3fe5b673e99d33d70cfee2ea8fe8dccd60f265c3ed990873a88647e3dd288",
                "sha256:34dd4922aab246c39bf5df03ca653d6265e65971deca6784c956bf356bca6197",
                "sha256:384e2dfa03da7c8d54f8f934f61b6a5e4e1ebb56a65b287567629d6c14578003",
                "sha256:392e2ea22b41a22c0289a88053204b616181288162ba78e6823e1760309d5277",
                "sha256:4341a39fc085f31a583be505eabf00e17c619b469fef78dc7e8241385bfddaa4",
                "sha256:45080f065dcaa573ebecbfe13cdd86e8c0a68c4e999aa06bd365374ea7137706",
                "sha256:485cb1eb4c9962f4cd042fed9424482ec1d83fee5dc2ef3f2552ac47852cb259",
                "sha256:575cefd28d3e0da85b0864506ae26b06483ee4a906e308be5a7ad11083f9d757",
                "sha256:62784b35df7de7ca4d0d81c5b6af5983f48c5cdef32fc3635b445674e56e3266",
                "sha256:69c152f7c11bf3b4fc11bc4cc62eb0334371c0db6844ebace43b7c815b602805",
                "sha256:6ccfdcefd287f252cf1ea7a3f1656070da330c4a5658e43ad223269165cdf977",
                "sha256:7298fbd73c0b3eff1d53dc9b9bdb7add8797bb55eeee38c8ccd7906755ba28af",
                "sha256:79463d918d1bf3aeb9186e3df17ddb0baca443f41371df422f99ee94f4f2bbfe",
                "sha256:8bbee788d82c0ac656536de70e817af09b7694f5326b0ef08e5c1014fcb96bb3",
                "sha256:a863957192855c4c57f60a75a1ac06ce5362ad18506d362dd807e194b4baf3ce",
                "sha256:ae602ba425fb2b074e16d125cdce4f0194903da935b2e7fe284ebecca6d92e76",
                "sha256:b13faa258b20fa66d29011f99fdf498641ca74a0a6d9266bc27d83c70fea4a6a",
                "sha256:c2c39d69266621dd7464e2bb740d6eb5abc64ddc339cc97aa669f3bb4d75c103",
                "sha256:e9c88f173d31909d881a60f08a8494e63f1aff2a4052476b24d4f50e82c47e24",
                "sha256:f1a29267ac29fff0913de0f11f3a9edfcd3f39595f467026c29376fad243ebe3",
                "sha256:f69dde0c5a137d887676a8129373e44366055cf19d1b434e853310c7a1e68f93"
            ],
            "version": "==1.16.1"
        },
        "six": {
            "hashes": [
                "sha256:3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c",
                "sha256:d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73"
            ],
            "version": "==1.12.0"
        },
        "tables": {
            "hashes": [
                "sha256:07bb9e96b762874e239ad8cec2cab2c4129abf576fffcdd4e961482dc7d5a0a6",
                "sha256:09eed21e12a1286ac2e8c5e67a75d9c7a7f262883535a31ac0b985540135d8d6",
                "sha256:0bd7e5d7ff90df3751bfb2494d41858b96118965edd8cc03758bbc638e2e2f2c",
                "sha256:2379bc98dd8caa6f5824daae4b3b1e53008af32c7b684c67deaeebc1a89a929e",
                "sha256:2cd49a98e750fe78b7a2b8e0efd69be608c8358f664f3705c98cc6f04da18a53",
                "sha256:415731ae46dfdef7fbe305399a700a54b06a82c4331ba20cc64004fb40e79069",
                "sha256:44289caf89efac435f49fa4bd298eb48969c026dec25d3a76e7955f1281d1bdf",
                "sha256:714f7162ffa4d470da8c9a067935520e5925384445bdb23989351b48d236345c",
                "sha256:82d98123cf67c012d6c7cb69c6733b51eb10d17fc40547bbb71ffedae8da4f90",
                "sha256:b625fc71f082011806a60d3b7370f75e34b141dab549ed65957aed54d1f12f63",
                "sha256:bc1621bd84769ff3f84cfd1481f93ed0c537db4b3355576270bdbb79bb390b1f",
                "sha256:bdc5c073712af2a43babd139c4855fc99496bb2c3f3f5d1b4770a985e6f9ce29",
                "sha256:bed4f423dd33600907f1c3b88f994920f2b879b12bf83d4372f861ef4085e085",
                "sha256:c3ac22e3391f67a381d9a3018fd7e0a1ccfcc88b5f61b0d051fe5eba8196388f",
                "sha256:d263f4380a5dad862efac774428bacb04c2339c4f165f2efdd228867abaffcf6",
                "sha256:da98c8abfeefefad40110b994d5d06ac28d89b00d085530d377376b201566ebf",
                "sha256:e2e4e40d010a6aa0464e5e281d4aa15f64acd99fd881c0e1e4c1c567b7167dba",
                "sha256:e3bd7084dbf80ef347ad5d33645584e0fe7f8353cf2c33d8922a4c00034fa015",
                "sha256:e8f9b20b9623c900e7007b89a9d3e315280b666ac70b38b0c191345f7d4d8585",
                "sha256:f786d310cf954eaf52340680dfbc5c1190afc276093f5c454fab605a11488306",
                "sha256:f97c8b5ebec23894fc56af25c6e73bc86b463cbccb1f9b9887def24cd7811e2c",
                "sha256:fd3e774ff048de838df39b018c171bff3ecd9f34a908395a475ba07ac270a34a"
            ],
            "index": "pypi",
            "version": "==3.4.4"
        }
    },
    "develop": {}
}

```
</details>

**Comment by frostming** [comment]
According to the [file list](https://pypi.org/project/tables/#files), tables isn't providing a wheel nor source dist for Python3.7 on macos.

**Comment by ricodude** [comment]
Thx frostming - I installed HDF5 headers & the tables install now works fine.
