### ISSUE TITLE
"Pipenv --three" (or any other) command hangs on "creating virtual environment..." for fresh Virtual Environment

### ISSUE THREAD

**Issue by Toruitas** [pypa/pipenv#3533]
### Issue description

I've been using pipenv on Ubuntu 18 for a while now, installed with `pip install --user pipenv`. Have a concurrent installation of Anaconda. Both have worked fine until today, and haven't updated either of them. Rebooting is of no help.

`pipenv --python 3.7` or any other version of Python hangs at  "Creating virtual environment..." and while it creates a .venv folder and a Pipfile, however the Pipfile is empty. 

There is no error, it just keeps going and going without doing anything. The `--verbose` flag doesn't give any additional output. Let it go for 12 hours and it didn't get beyond this, or throw an error.

Conda's virtual environment functionality, as well as running `python -m venv venv` both work to create virtual environments still, so it doesn't appear to be a problem with any system packages.

### Expected result

A virtual environment to be created.

### Actual result

Hangs on "Creating virtual environment..." with no error or result.

### Steps to replicate

`pipenv --python <any version>`

--------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/toruitas/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.7.1`: `/usr/bin/python3.7`
  - `3.7.1`: `/usr/bin/python3.7m`
  - `3.6.7`: `/usr/bin/python3.6m`
  - `3.6.7`: `/usr/bin/python3.6`
  - `2.7.15rc1`: `/usr/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-45-generic',
 'platform_system': 'Linux',
 'platform_version': '#48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019',
 'python_full_version': '3.6.7',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `CLUTTER_IM_MODULE`
  - `PIPENV_VENV_IN_PROJECT`
  - `CONDA_SHLVL`
  - `LS_COLORS`
  - `LESSCLOSE`
  - `TERMINATOR_UUID`
  - `XDG_MENU_PREFIX`
  - `LANG`
  - `DISPLAY`
  - `GNOME_SHELL_SESSION_MODE`
  - `GTK2_MODULES`
  - `COLORTERM`
  - `USERNAME`
  - `XDG_VTNR`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `SSH_AUTH_SOCK`
  - `MANDATORY_PATH`
  - `S_COLORS`
  - `XDG_SESSION_ID`
  - `USER`
  - `DESKTOP_SESSION`
  - `QT4_IM_MODULE`
  - `TEXTDOMAINDIR`
  - `DEFAULTS_PATH`
  - `QT_QPA_PLATFORMTHEME`
  - `PWD`
  - `HOME`
  - `TEXTDOMAIN`
  - `SSH_AGENT_PID`
  - `QT_ACCESSIBILITY`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `TERMINATOR_DBUS_NAME`
  - `XDG_SESSION_DESKTOP`
  - `GJS_DEBUG_OUTPUT`
  - `GTK_MODULES`
  - `TERMINATOR_DBUS_PATH`
  - `WINDOWPATH`
  - `VTE_VERSION`
  - `TERM`
  - `SHELL`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `IM_CONFIG_PHASE`
  - `XDG_CURRENT_DESKTOP`
  - `GPG_AGENT_INFO`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `XDG_SEAT`
  - `SHLVL`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `XDG_CONFIG_DIRS`
  - `PATH`
  - `GJS_DEBUG_TOPICS`
  - `SESSION_MANAGER`
  - `LESSOPEN`
  - `GTK_IM_MODULE`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/toruitas/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/toruitas/bin:`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/toruitas/Documents/GitHub/ai/CreativeAI/test`

---------------------------

</details>

**Comment by con-f-use** [comment]
I have the same issue. Even `pipenv --support` hangs after displaying "Python installations found:"

```
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
$ uname -a
Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ python --version
Python 2.7.15rc1
$ pipenv --version
pipenv, version 2018.11.26
```

**Comment by con-f-use** [comment]
Interestingly enough, pressing Ctrl+D (End of File in Unix Shells) seems to cause pipenv do continue.
It might erroneously expect some input from `stdin` in my case.

**Comment by techalchemy** [comment]
can you provide the output of `python --version` and `which python` as well as `which pip` and `pip --version`? Was conda responsible for installing pipenv?

**Comment by jnns** [comment]
Initializing a new virtualenv using `pipenv --three` only works for me if I send <kbd>CTRL</kbd>+ <kbd>d</kbd> while waiting for it to do something. It seems that there's a process spawned that needs to be exited before pipenv actually starts working. This happened in Bash as well as Fish shell.

Interestringly enough `pipenv --support` also suffers from this syndrome: output following *Python installations found:* is only printed after pressing <kbd>CTRL</kbd>+<kbd>D</kbd>.


Let me know if you need further infos, other than the ones below.


```
$ python --version
Python 2.7.15+

$ which python
/usr/bin/python

$ which pip
/home/jnns/.local/bin/pip

$ pip --version
pip 19.0.3 from /home/jnns/.local/lib/python3.6/site-packages/pip (python 3.6)
```




<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/jnns/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.6.7`: `/usr/bin/python3.6m`
  - `3.6.7`: `/usr/bin/python3.6`
  - `2.7.15`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.18.0-15-generic',
 'platform_system': 'Linux',
 'platform_version': '#16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019',
 'python_full_version': '3.6.7',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `CLUTTER_VBLANK`
  - `COLORTERM`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DESKTOP_AUTOSTART_ID`
  - `DESKTOP_SESSION`
  - `DISPLAY`
  - `EDITOR`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `GNOME_TERMINAL_SCREEN`
  - `GNOME_TERMINAL_SERVICE`
  - `HOME`
  - `LANG`
  - `LOGNAME`
  - `LS_COLORS`
  - `OMF_CONFIG`
  - `OMF_PATH`
  - `PATH`
  - `PWD`
  - `QT_IM_MODULE`
  - `SESSION_MANAGER`
  - `SHELL`
  - `SHLVL`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `USER`
  - `USERNAME`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `VTE_VERSION`
  - `WAYLAND_DISPLAY`
  - `WORKON_HOME`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_DATA_DIRS`
  - `XDG_MENU_PREFIX`
  - `XDG_RUNTIME_DIR`
  - `XDG_SEAT`
  - `XDG_SESSION_DESKTOP`
  - `XDG_SESSION_ID`
  - `XDG_SESSION_TYPE`
  - `XDG_VTNR`
  - `XMODIFIERS`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:


Debug–specific environment variables:

  - `PATH`: `/home/jnns/.local/bin:/home/jnns/.poetry/bin:/home/jnns/.local/bin:/home/jnns/.poetry/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
  - `SHELL`: `/usr/bin/fish`
  - `EDITOR`: `vim`
  - `LANG`: `de_DE.UTF-8`


---------------------------

Contents of `Pipfile`:

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "3.6"

```

</details>

**Comment by Toruitas** [comment]
I was not able to confirm that CTRL+D gets Pipenv to work. Here are my details as well. Pipenv is not installed through Conda. 

`
uname -a
Machine 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

python --version
Python 2.7.15rc1

python3 --version
Python 3.6.7

which pip
/home/toruitas/.local/bin/pip

pip --version
pip 18.1 from /home/toruitas/.local/lib/python3.6/site-packages/pip (python 3.6)
`

**Comment by techalchemy** [comment]
ah I see, I think this is related to `pythonfinder` not being able to parse the python version from ubuntu there -- this _should_ be fixed on the master branch if you can give that a try?

`pip install -e git+https://github.com/pypa/pipenv.git@master#egg=pipenv`

**Comment by Toruitas** [comment]
Unfortunately, I haven't been able to install from the master branch to test, it hangs on "Installing build dependencies" but I reckon that's a different issue.
