### ISSUE TITLE
Generate graph in Dot graph format

### ISSUE THREAD

**Issue by ghost** [pypa/pipenv#3543]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

`pipenv graph --dot` should generate a Dot file syntax representation of the dependency graph, ideally with the entries listed in the Pipfile highlighted in some way.

### Describe alternatives you've considered

This ugly command group converts a flat JSON representation from Pipenv to Dot:

```
{ \
    echo 'digraph "Pipenv dependency graph" {' \
    && pipenv graph --json | jq --raw-output '.[] | "\"" + .package.package_name + "\";", "\"" + .package.package_name + "\" -> \"" + .dependencies[].package_name + "\";"' \
    && echo "}"; \
}
```

This can be piped to for example `dot -Tsvg` to create an SVG representation of the graph.

The package names on separate lines is necessary to list packages without any dependencies or reverse dependencies.

**Comment by techalchemy** [comment]
I'm not totally convinced about implementing this, but i think `pipdeptree` might already support it so we may be able to leverage that

**Comment by cmatsuoka** [comment]
I just tested it with `pipdeptree.py --graph-output dot` and it worked quite well.

**Comment by matteius** [comment]
Someone could add a `--dot` flag to the graph command if its important to have.

**Comment by matteius** [comment]
We recently extended the pipdeptree to have `--reverse --json` and `--reverse --nested-json` output -- if this is still something that is needed, please open or ping this ticket and we can revisit.
