### ISSUE TITLE
Show the change logs of updated package

### ISSUE THREAD

**Issue by northtree** [pypa/pipenv#3545]
I wonder if it's possible to grab the change logs of updated packages after running

```pipenv update```

Most of packages will have change logs in their repo. e.g

- https://github.com/kennethreitz/requests-html/releases
- https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst
- https://github.com/urllib3/urllib3/blob/master/CHANGES.rst

It will be more productive if I could have the latest updates via CLI.

**Comment by techalchemy** [comment]
I like the idea a whole lot, although I have to say it's definitely awhile off for implementation -- we have a bunch of work to do on some core functionality before we are on this type of thing

could be something someone might be able to get together or find a library for, not totally sure what's out there

**Comment by matteius** [comment]
Big c
