### ISSUE TITLE
Configure file for user defined alias like .gitconfig

### ISSUE THREAD

**Issue by tamuhey** [pypa/pipenv#3546]
Thanks  for this great tool!
I want to configure user defined alias, e.g.
```bash
$pipenv i # equals pipenv install
```
I think different people have different preference on this abbreviation, so it would be great if there was a configure feature like .gitconfig.

**Comment by frostming** [comment]
Pipenv team are against involving more config files other than `Pipfile` itself.
Anyway you can achieve this by aliases.
