### ISSUE TITLE
python37:AttributeError: '_shims' object has no attribute 'InstallRequirement'

### ISSUE THREAD

**Issue by DachuanZhao** [pypa/pipenv#3547]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://docs.pipenv.org/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

pipenv install tornado failed

### Expected result

Describe what you expected.

### Actual result

```
Installing tornado…
Adding tornado to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✘ Locking Failed! 
Traceback (most recent call last):
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/utils.py", line 477, in actually_resolve_deps
    deps, index_lookup, markers_lookup, project, sources,
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/utils.py", line 224, in get_resolver_metadata
    req = Requirement.from_line(dep)
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1068, in from_line
    if isinstance(line, pip_shims.shims.InstallRequirement):
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/vendor/pip_shims/shims.py", line 254, in __getattr__
    return super(_shims, self).__getattribute__(*args, **kwargs)
AttributeError: '_shims' object has no attribute 'InstallRequirement'
File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/utils.py", line 477, in actually_resolve_deps
    deps, index_lookup, markers_lookup, project, sources,
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/utils.py", line 224, in get_resolver_metadata
    req = Requirement.from_line(dep)
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1068, in from_line
    if isinstance(line, pip_shims.shims.InstallRequirement):
  File "/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv/vendor/pip_shims/shims.py", line 254, in __getattr__
    return super(_shims, self).__getattribute__(*args, **kwargs)
AttributeError: '_shims' object has no attribute 'InstallRequirement'
```

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/zhaodachuan/zhaodachuan/anaconda3/lib/python3.7/site-packages/pipenv'`

Python location: `'/home/zhaodachuan/zhaodachuan/anaconda3/bin/python'`

Python installations found:

  - `3.7.1`: `/home/zhaodachuan/.local/share/virtualenvs/back-end-9PQNjTVn/bin/python`
  - `3.7.1`: `/home/zhaodachuan/zhaodachuan/anaconda3/bin/python`
  - `2.7.5`: `/usr/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.1',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '3.10.0-693.2.2.el7.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Tue Sep 12 22:26:13 UTC 2017',
 'python_full_version': '3.7.1',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `XDG_SESSION_ID`
  - `HOSTNAME`
  - `PIP_PYTHON_PATH`
  - `SHELL`
  - `TERM`
  - `HISTSIZE`
  - `SSH_CLIENT`
  - `CONDA_SHLVL`
  - `CONDA_PROMPT_MODIFIER`
  - `SSH_TTY`
  - `USER`
  - `LS_COLORS`
  - `CONDA_EXE`
  - `VIRTUAL_ENV`
  - `PIPENV_ACTIVE`
  - `PATH`
  - `MAIL`
  - `CONDA_PREFIX`
  - `PWD`
  - `LANG`
  - `PS1`
  - `PYTHONDONTWRITEBYTECODE`
  - `HISTCONTROL`
  - `HOME`
  - `SHLVL`
  - `CONDA_PYTHON_EXE`
  - `LOGNAME`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `SSH_CONNECTION`
  - `CONDA_DEFAULT_ENV`
  - `LESSOPEN`
  - `XDG_RUNTIME_DIR`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/zhaodachuan/.local/share/virtualenvs/back-end-9PQNjTVn/bin:/home/zhaodachuan/zhaodachuan/anaconda3/bin:/mnt/data/zhaodachuan/anaconda3/bin:/home/zhaodachuan/zhaodachuan/anaconda3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `zh_CN.UTF-8`
  - `PWD`: `/home/zhaodachuan/zhaodachuan/code/data_show_proj/back-end`
  - `VIRTUAL_ENV`: `/home/zhaodachuan/.local/share/virtualenvs/back-end-9PQNjTVn`

---------------------------

Contents of `Pipfile` ('/mnt/data/zhaodachuan/code/data_show_proj/back-end/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
tornado = "*"

[requires]
python_version = "3.7"

```

</details>

**Comment by ywllyht** [comment]
**(1) I meet the same problem.  My environment is**
python:   3.6.8
anaconda: 4.6.2

Maybe there is some conflict between anaconda_python and pipenv

**(2) If I install pipenv with "--user" argument, then "pipenv install numpy" will report another error**

liangjie@hb1:~/myproject/python/flask/pipenv_flask$ pipenv install
Creating a virtualenv for this project…
Pipfile: /home/liangjie/myproject/python/flask/pipenv_flask/Pipfile
Using /home/liangjie/anaconda3/bin/python3 (3.6.8) to create virtualenv…
⠴ Creating virtual environment...Using base prefix '/home/liangjie/anaconda3'
New python executable in /home/liangjie/.local/share/virtualenvs/pipenv_flask-88yYFRdh/bin/python3
Also creating executable in /home/liangjie/.local/share/virtualenvs/pipenv_flask-88yYFRdh/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /home/liangjie/anaconda3/bin/python3

✔ Successfully created virtual environment!
Virtualenv location: /home/liangjie/.local/share/virtualenvs/pipenv_flask-88yYFRdh
Pipfile.lock (4fccdf) out of date, updating to (ca72e7)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✘ Locking Failed!
[pipenv.exceptions.ResolutionFailure]:   File "/home/liangjie/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 69, in resolve
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "/home/liangjie/.local/lib/python3.6/site-packages/pipenv/utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "/home/liangjie/.local/lib/python3.6/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/home/liangjie/.local/lib/python3.6/site-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches numpy
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches numpy
No versions found
Was https://pypi.org/simple reachable?
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "/home/liangjie/.local/lib/python3.6/site-packages/pipenv/utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "/home/liangjie/.local/lib/python3.6/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/home/liangjie/.local/lib/python3.6/site-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches numpy
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches numpy
No versions found
Was https://pypi.org/simple reachable?

**Comment by ywllyht** [comment]
I test several releases of pipenv, and none of them could work with conda-python.

version 2018.11.14  reports error:  AttributeError: '_shims' object has no attribute 'InstallRequirement'
version 2018.10.13  reports error:  ImportError: cannot import name 'InstallRequirement'
version 2018.10.9  reports error:  ImportError: cannot import name 'InstallRequirement'
version 2018.7.1  reports error:  ImportError: cannot import name 'HTTPSHandler'
version 2018.6.25  reports error:  ModuleNotFoundError: No module named 'pip.basecommand'
version 2018.5.18  reports error:  ImportError: cannot import name 'HTTPSHandler'

from the python 2018 report(https://www.jetbrains.com/research/python-developers-survey-2018/),  there are 22% pythoners are using conda-python.    We hope admins could add this support.

**Comment by etele** [comment]
I dont realy know what is causing this but came up with a workaround:
https://gist.github.com/etele/599828d3a446532dd194b88d175f972a (it deletes the lib-dynload dir and recreates it as a symlink)

the problem what is causing it, is the that the lib-dynload is now as a directory and the files within are symlinked and it somehow matters.

**Comment by ywllyht** [comment]
Thanks for @etele workaround.   It solves my issue.

**Comment by etele** [comment]
with a little typo we noticed that without creating the link on the directory it worked too.
and it would be good to know what is the real problem

**Comment by techalchemy** [comment]
it appears that creating virtualenvs with anaconda is causing substantial problems, i'll try to triage this for the next release

thanks for the report!

**Comment by techalchemy** [comment]
It looks like this was a bug in virtualenv, one of these two: pypa/virtualenv#1327 pypa/virtualenv#1282 and it should be fixed now.  Let me know if you continue to experience issues
