### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by noblerabbit** [pypa/pipenv#3548]
Hi,

I am having problems if I want to use pipenv to install tensorflow-gpu.

If I create virtual env in conda, and do "pip install tensoflow-gpu", works like a charm.

However if I do "pipenv install tensoflow-gpu", after I try to import it in python I get
"ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory"

I have CUDA Version 10.0.130.
/usr/local/ folders: bin  cuda  cuda-10.0  etc  games  include  lib  man  sbin  share  src

I read online that I should install cuda 9 instead of 10, however, tensorflow-gpu in conda works just fine, so if possible I'd like to avoid downgrading.

What is the "goto" way to fix this? How can I set up the same configuration as conda?

Thanks!

**Comment by uranusjr** [comment]
Cuda 9.0 is an external dependency expected by Tensorflow, and Pipenv has not way to manage it if Tensorflow does not manage it. You’ll need to ask the Tensorflow team for help.

**Comment by uranusjr** [comment]
Similar situation: tensorflow/tensorflow#15604.

**Comment by noblerabbit** [comment]
To give some update. 
Conda env has the option to export path (ie to the cuda library) during activation. Once I deactivate the env the path goes back to what it was before.  This is how I handle different envs with different cuda libraries.
Here is the info how to do that: https://stackoverflow.com/questions/46826497/conda-set-ld-library-path-for-env-only

I stopped using pipenv because I could not find at the time how to do that. It should be possible...
