### ISSUE TITLE
`pipenv shell` ignores `VIRTUAL_ENV` environment var

### ISSUE THREAD

**Issue by codeinvain** [pypa/pipenv#3563]
`pipenv shell` do not respect `VIRTUAL_ENV` env var because `PIPENV_ACTIVE` is set before accessing `project.virtualenv_location` method

https://github.com/pypa/pipenv/blob/master/pipenv/project.py#L418

it causes pipenv shell to create a new virtual env folder instead of using the existing one set in `VIRTUAL_ENV`

**Comment by frostming** [comment]
@codeinvain Yes it is working this way so that we can test pipenv inside a virtualenv. Anyway, if you are already in an activated virtualenv, `pipenv shell` makes no sense.

**Comment by codeinvain** [comment]
@frostming  thanks for the quick reply.
maybe i didn't explain myself correctly. 
I have an existing setup using pipenv using custom  virtual env folder path (non default ~/.local/share/virtualenvs/) .
i'm directing pipenv to use my custom virtual env using  `VIRTUAL_ENV`  environment before invoking pipenv commands . 
this works well for *all* pipenv commands (pipenv run / pipenv --venv/ etc') *but* `pipenv shell` which tries to create a new virtualenv under `~/.local/share/virtualenvs/` once executed.

**Comment by codeinvain** [comment]
maybe the solution  is to memoize `os.getenv("VIRTUAL_ENV")` in https://github.com/pypa/pipenv/blob/847b8ae28da5bc9c301ae9689f8429ce394cfaec/pipenv/project.py#L420
```
        if ("PIPENV_ACTIVE" not in os.environ and
                not PIPENV_IGNORE_VIRTUALENVS and virtualenv_env):
            self._virtualenv_location = virtualenv_env
            return self._virtualenv_location
```

since it does not make any sense that you call the same method (project.virtualenv_location ) and get two different results depending on when it was called

**Comment by frostming** [comment]
@codeinvain I see, in master branch the `PIPENV_ACTIVE` is postponed so that it can work rightly now.
https://github.com/pypa/pipenv/blob/44db5dd87dbeb34e94bf42f178c13b70e9405e8c/pipenv/core.py#L2151-L2160

Can you try against master branch and see if it fit your case?

**Comment by codeinvain** [comment]
@frostming thanks! 
Unfortunately this implementation does not work. it fixes the prompt message on `pipenv shell` but ignores this path beside that.
it still have issues with `pipenv install` inside or outside the virtual env 
when using `VIRTUAL_ENV` and inside the pipenv shell its trying to resolve bins from `~/.local/share/virtualenvs/<PIPENV_DEFAULT_ENV_NAME>/` and not from `VIRTUAL_ENV` path.

It all leads me back to my proposals either to 
1. [memoize _virtualenv_env](https://github.com/pypa/pipenv/issues/3563#issuecomment-467459341)
or 
2. [ignore PIPENV_ACTIVE](https://github.com/pypa/pipenv/pull/3561)

*memoization* will work if we have only one Project instance (if we have multiple instances that instances that are created after ` os.environ["PIPENV_ACTIVE"] = vistir.misc.fs_str("1")` will be invalid 

*ignoring PIPENV_ACTIVE in `Project.virtualenv_env`* IMHO  is more predictable and is easier to reason about when maintaining the code. would be nice to understand what are the scenarios that you want  ignore `VIRTUAL_ENV` once inside a pipenv session (i assume marked as `PIPENV_ACTIVE`)   


That's i did to check:
```
$ mkdir -p  /tmp/example && cd /tmp/example
$ pip install git+https://github.com/pypa/pipenv.git --user
Collecting git+https://github.com/pypa/pipenv.git
  Cloning https://github.com/pypa/pipenv.git to /private/var/folders/db/wy74wjzd0n59f__0jrkk1f3c0000gn/T/pip-req-build-e4l36ujl
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied (use --upgrade to upgrade): pipenv==2018.11.27.dev0 from git+https://github.com/pypa/pipenv.git in /Users/danielc/Library/Python/3.6/lib/python/site-packages
Requirement already satisfied: pip>=9.0.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pipenv==2018.11.27.dev0) (19.0.2)
Requirement already satisfied: setuptools>=36.2.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pipenv==2018.11.27.dev0) (40.2.0)
Requirement already satisfied: virtualenv in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pipenv==2018.11.27.dev0) (16.0.0)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pipenv==2018.11.27.dev0) (2018.8.24)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pipenv==2018.11.27.dev0) (0.3.0)
Building wheels for collected packages: pipenv
  Building wheel for pipenv (PEP 517) ... done
  Stored in directory: /private/var/folders/db/wy74wjzd0n59f__0jrkk1f3c0000gn/T/pip-ephem-wheel-cache-5onz5iv6/wheels/0a/02/1f/d42a34feec5f69f4960928f5efa3e149adfde2ce317f1ba69e
Successfully built pipenv
$ pipenv --version
pipenv, version 2018.11.27.dev0
$pipenv install ujson
Creating a virtualenv for this project…
Pipfile: /private/tmp/example/Pipfile
Using /Users/danielc/.pyenv/versions/3.7.2/bin/python3 (3.7.2) to create virtualenv…
⠹ Creating virtual environment...Using base prefix '/Users/danielc/.pyenv/versions/3.7.2'
New python executable in /Users/danielc/.local/share/virtualenvs/example-KJM9Zk2R/bin/python3
Also creating executable in /Users/danielc/.local/share/virtualenvs/example-KJM9Zk2R/bin/python
Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /Users/danielc/.pyenv/versions/3.7.2/bin/python3

✔ Successfully created virtual environment!
Virtualenv location: /Users/danielc/.local/share/virtualenvs/example-KJM9Zk2R
Installing ujson…
Adding ujson to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (326af2)!
Installing dependencies from Pipfile.lock (326af2)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
$ # ^^ you can see that it works as expected without virtual env set ^^
$
$
$ export VIRTUAL_ENV=/Users/danielc/.local/share/virtualenvs/example-KJM9Zk2R0-custom-venv
$ pipenv install ujson
Installing ujson…
WARNING: location not created nor specified
✘ Installation Failed
```

**Comment by frostming** [comment]
@codeinvain 
1. When inside `pipenv shell`, pipenv takes control over the virtualenv paths. If you run `pipenv --venv` inside the `pipenv shell` subshell, it will gives you the **pipenv owned** virtualenv path.
2. To use a custom virtualenv location, the recommended way is to write the path in a `.venv` file under the project directory. We don't manually set `VIRTUAL_ENV` value which is owned by virtualenv tools.

**Comment by frostming** [comment]
I repeat your steps in the previous comment, works fine.

**Comment by codeinvain** [comment]
@frostming per your advise moved to .venv file instead of setting `VIRTUAL_ENV` and it looks fine both on dev and 2018.11.26 release 

thanks!
