### ISSUE TITLE
Fatal error in launcher: Unable to create process

### ISSUE THREAD

**Issue by Drtrider** [pypa/pipenv#3570]
### Issue description

I am a first time user of pip and pipenv. pipenv is failing to launch when trying to install a library. I have fully installed and updated pip, and python 3.

### Expected result

Expected to have pipenv install the "requests" library. When using the `pipenv install requests` command. Note: I am able to get it to run when using the following command: `python -m pipenv install requests` 

### Actual result

The following is returned when attempting to run pipenv: 
`Fatal error in launcher: Unable to create process using '"c:\python37\python.exe"  "C:\Users\drtri\AppData\Roaming\Python\Python37\Scripts\pipenv.exe" install requests --verbose`

### Steps to replicate

Run the following within cmd on windows: `pipenv install requests --verbose`

-------------------------------------------------------------------------------

Support request:

Fatal error in launcher: Unable to create process using '"c:\python37\python.exe"  "C:\Users\drtri\AppData\Roaming\Python\Python37\Scripts\pipenv.exe" --support'

#### Additional notes
I noticed that using `python -m pipenv install requests` seems to work. However, once I try and use `import requests` within a python script, I get a "No module names 'requests' found" error.

**Comment by frostming** [comment]
@Drtrider Can you still reproduce the issue after you uninstall and reinstall pipenv?

> However, once I try and use `import requests` within a python script, I get a "No module names 'requests' found" error.

The script should be run in virtualenv. or `pipenv run python script.py`

**Comment by Drtrider** [comment]
@frostming Looks like uninstalling it, and re-installing it did the trick. Very odd behavior. Thank you.

**Comment by newlinuxhelper** [comment]
I solved this issues of [Unable to create process using in venv](https://webmatrices.com/d/503-unable-to-create-process-using-virtualenv) with this forum answers. This will surely help you and fix your issues.
