### ISSUE TITLE
Pipenv fails to install package that pip can install

### ISSUE THREAD

**Issue by mbhall88** [pypa/pipenv#3572]
### Issue description

Cannot install the package [`pysam`](https://github.com/pysam-developers/pysam) with `pipenv, version 2018.11.26` on python3.7.2 but can install with `pip` without any problems.

### Expected result

When installing the same package with `pip` (`pip3 install pysam`) it installs without any problems.

### Actual result

The crux of the problem, I believe, is

```
    htslib/cram/cram_io.c:61:10: fatal error: 'lzma.h' file not found
    #include <lzma.h>
             ^~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    Running setup.py install for pysam: finished with status 'error'
```

The full log is below. 

[pysam.txt](https://github.com/pypa/pipenv/files/2920788/pysam.txt)

### Steps to replicate

```sh
pipenv --verbose install pysam
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.11.26_1/libexec/bin/python3.7'`

Python installations found:

  - `3.7.2`: `/usr/local/bin/python3`
  - `3.7.2`: `/usr/local/bin/python3.7m`
  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.15`: `/usr/local/bin/pythonw`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.2.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST '
                     '2018; root:xnu-4903.241.1~1/RELEASE_X86_64',
 'python_full_version': '3.7.2',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `TERM_PROGRAM`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `ZSH`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `PAGER`
  - `LSCOLORS`
  - `_`
  - `PWD`
  - `LANG`
  - `PIPENV_COLORBLIND`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `LC_CTYPE`
  - `PROMPT_EOL_MARK`
  - `DISPLAY`
  - `COLORTERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_COLORBLIND`: `1`

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.11.26_1/libexec/tools:/Users/mbhall88/.cargo/bin:/Users/mbhall88/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/ncbi/blast/bin:/Library/TeX/texbin:/usr/local/munki:/opt/X11/bin`
  - `SHELL`: `/usr/local/bin/zsh`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/mbhall88/Downloads/tmp`

---------------------------

Contents of `Pipfile` ('/Users/mbhall88/Downloads/tmp/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
pysam = "*"

```

Contents of `Pipfile.lock` ('/Users/mbhall88/Downloads/tmp/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "b3ecc54460a270b517b6807dc9ef7164d78debc74320cb4acfa0abf496810d58"
        },
        "pipfile-spec": 6,
        "requires": {},
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "pysam": {
            "hashes": [
                "sha256:0f063380ebd727f58483b256fe21d90358527fbdf48b925ae2680cc1f2c553ae",
                "sha256:1e0a6abf4fe0d3934fee8d662f6fda28e466b60209b5b1fd41070e1ccfbe87f2",
                "sha256:236ae950c0194037ac3e8a11fa7bda6b46db17ee3f86e1111775ed4b9cdaf95b",
                "sha256:34dd4cf08cbdea1329a140f5446c319992460d400b9851c0cb5607f3c58ad256",
                "sha256:975fbd395b5c4d360be5fde2e34d418c64718ba732ae5b2bfb712e6cefa750d5",
                "sha256:d049efd91ed5b1af515aa30280bc9cb46a92ddd15d546c9b21ee68a6ed4055d9",
                "sha256:e8166058e01d5b7fd2d82c5fee29f9c22e6016091b8c397cc029f7cc2f2f61ff"
            ],
            "index": "pypi",
            "version": "==0.15.2"
        }
    },
    "develop": {}
}

```
</details>

**Comment by frostming** [comment]
So where are the header files located? Pipenv doesn't respect some config files(`pip.conf`) that are used to change pip's behavior?

**Comment by mbhall88** [comment]
This seems to be related to https://github.com/pysam-developers/pysam/issues/645
I have followed the instructions from that issue and the header can be found at `usr/local/Cellar/xz/5.2.4/include/lzma.h`

**Comment by matteius** [comment]
I doubt this is still an issue but we can revisit if it is.
