### ISSUE TITLE
Pipenv gets blocked while running with Docker in Gitlab

### ISSUE THREAD

**Issue by Peque** [pypa/pipenv#3575]
I created this simple project in Gitlab:

https://gitlab.com/PequeX/deleteme

With a Pipfile that installs only a couple of packages:

    [[source]]
    name = "pypi"
    url = "https://pypi.org/simple"
    verify_ssl = true
    
    [dev-packages]
    pytest = "*"
    
    [packages]
    requests = "*"
    
    [requires]
    python_version = "3.7"

And a very simple `.gitlab-ci.yml` file:

    image: peque/python-devel
    
    before_script:
      - pipenv sync --dev
    
    python36:
      script:
        - pipenv run pytest

There is also the [autogenerated Pipfile.lock file](https://gitlab.com/PequeX/deleteme/blob/master/Pipfile.lock). Which I will not paste here as it is not very interesting.

Now, the problem is Gitlab seems to get blocked when calling `pipenv sync`:

https://gitlab.com/PequeX/deleteme/-/jobs/171273142

There is no output printed on the log and no error. It just gets blocked forever. And then, eventually, it timeouts (because Gitlab would not let you run a pipeline forever).

**Comment by Peque** [comment]
Maybe related: https://github.com/pypa/pipenv/issues/3534

Will try that workaround.

**Comment by Peque** [comment]
It seems the workaround in #3534 does avoid the block at `pipenv sync`, but then `pipenv run` [fails to find the installed packages](https://gitlab.com/PequeX/deleteme/-/jobs/171370179) (?).

**Comment by techalchemy** [comment]
Closing -- see #3534 for more info
