### ISSUE TITLE
Difference between pipenv sync and pipenv install --deploy

### ISSUE THREAD

**Issue by haizaar** [pypa/pipenv#3582]
What is the difference between `pipenv install --deploy` and `pipenv sync` - both seem to install whatever is specified in `Pipfile.lock`. What am I missing?

pipenv version 2018.11.26

**Comment by frostming** [comment]
@haizaar Yeah they are nearly equivalent except that `pipenv sync` will never try to relock your dependencies while `pipenv install --deploy` will first check the consistency between `Pipfile` and `Pipfile.lock` and abort if they don't match.

**Comment by haizaar** [comment]
Thanks you!
Reading docs again it looks like `pipenv install --deploy` will also check Python version actual vs requested in `Pipfile.lock`.
