### ISSUE TITLE
install local wheel file will generate two records in lock file

### ISSUE THREAD

**Issue by leileigong** [pypa/pipenv#3583]
### I wanna to install pyscard from wheel on my local disk.
so i write an item into my Pipfile.
`cp36-win32-p_y_scard = {path = "wheelhouse/pyscard-1.9.7-cp36-cp36m-win_amd64.whl",sys_platform = "== 'win32'"}`

then i type "pipenv install" installing pyscard package.

this package install success.
but it seems two records is generated in lock file.
the first is:
`
        "cp36-win32-p-y-scard": {
            "path": "wheelhouse/pyscard-1.9.7-cp36-cp36m-win_amd64.whl",
            "sys_platform": "== 'win32'"
        },
` 
the second is:
`
        "pyscard": {
            "hashes": [
                "sha256:412c74c83e7401566e9d3d7b8b5ca965e74582a1f33179b3c1fabf1da73ebf80",
                "sha256:c804cd6891172e172ac404cd40bc9187c1f610a8011ddd9ec3a3a00f6c9ad6ea"
            ],
            "markers": "sys_platform == 'win32'",
            "version": "==1.9.7"
        },
`
From the two hash values listed in  "pyscard".
I can find the SHA256 hash of file from pypi  is "412c74c8...", the SHA256 hash of file from my local disk is " c804cd68...".

So should i get the first record in my Pipfile.lock? or is this a bug?

**Comment by techalchemy** [comment]
This is because you named the wheel in your Pipfile with a name different from the actual package name. The package name was still picked up during resolution. It is definitely a bug, but you can work around it by renaming your Pipfile entry.

**Comment by hartror** [comment]
@techalchemy I've replicated the issue in #3882 but not sure what the desired behaviour is?

**Comment by frostming** [comment]
@hartror Should only lock local wheel and its hash, no pypi alternatives.

**Comment by hartror** [comment]
So the OP's lockfile should be this?

```
"cp36-win32-p-y-scard": { "hashes": [ "sha256:c804cd6891172e172ac404cd40bc9187c1f610a8011ddd9ec3a3a00f6c9ad6ea" ], "markers": "sys_platform == 'win32'" },
```

**Comment by frostming** [comment]
@hartror 
```json
"cp36-win32-p-y-scard": { "hashes": [ "sha256:c804cd6891172e172ac404cd40bc9187c1f610a8011ddd9ec3a3a00f6c9ad6ea" ], path="path_to_wheel.whl", "markers": "sys_platform == 'win32'" },
```
