### ISSUE TITLE
pipenv update and pipenv update --outdated don't work for packages installed from private index

### ISSUE THREAD

**Issue by ipstech** [pypa/pipenv#3587]
### Issue description

I have several private pypi servers that are used to distribute packages internally. I have a meta-package that depends on several other packages that are also internal. When new versions of those packages are pushed up to our development package pypi server, I am unable to use pipenv update to pull down the new packages (I have prereleases enabled in the Pipfile). I am able to directly install the updated packages and then remove the entry from the Pipfile, but this is tedious.

### Expected result

I would expect to be able to use `pipenv update --outdated` to see the list of packages (including dependencies) that are outdated, and also be able to use `pipenv update` to update all outdated packages.

### Actual result

The dependencies are not updated. Only the packages listed in the Pipfile get updated.

#### Example package structure with dependencies:
```
company.meta_package_A
  - company.package_B
    - company.package_C
```

#### Example Pipfile:
```
[[source]]
url = "http://----.----.----.----:8082"
verify_ssl = false
name = "pypi_test"

[[source]]
url = "http://----.----.----.----:8081"
verify_ssl = false
name = "pypi_release"

[[source]]
url = "http://----.----.----.----:8080"
verify_ssl = false
name = "pypi_cache"

[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
“company.meta_pacakge_A" = {path = “/local/path/to/project/with/setup.py"}

[requires]
python_version = "2.7"

[pipenv]
allow_prereleases = true
```

#### Example `pipenv graph` output:
```
company.meta_package_A==1.0.0+local.#######
  - company.package_B [required: >=1.0.0.dev0, installed: 1.0.0.dev0+#######]
    - company.package_C [required: >=1.0.0, installed: 1.0.0]
```

#### Commands:
```
# A new version of company.package_B is available (version: 1.0.0.dev3+#######)

pipenv update

# The previous command runs normally and reports that it installed the single dependency from the
# Pipfile.lock (company.meta_package_A) successfully, however, the company.package_B was not
# updated to the newest available version

pipenv update --oudated

# The previous command reports that all packages are up to date

pipenv run pip list --outdated --pre -i [pypi_test] --trusted-host [pypi servers host]

# pip correctly lists the outdated packages and the newer versions that are available

pipenv run pip uninstall --yes company.package_B && pipenv update

# The package is now updated to the latest available version
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.27.dev0'`

Pipenv location: `'/usr/local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/local/opt/python@2/bin/python2.7'`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '16.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64',
 'python_full_version': '2.7.15',
 'python_version': '2.7',
 'sys_platform': 'darwin'}
```

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`

Debug–specific environment variables:

  - `SHELL`: `/usr/local/bin/bash`
  - `EDITOR`: `nvim`
  - `LANG`: `en_US.UTF-8`

**Comment by ipstech** [comment]
It looks like this was due to having prerelease versions as dependencies (and as dependencies of dependencies).

**Comment by techalchemy** [comment]
Hm that’s fixable. Thanks for troubleshooting!
