### ISSUE TITLE
Call "pipenv freeze - r > requirements.txt" fails in subprocess (automation)

### ISSUE THREAD

**Issue by gotexis** [pypa/pipenv#3590]
to reproduce:

```python
subprocess.run('pipenv freeze - r > requirements.txt')
```

This will fail as it doesnt recognise the '> requirements.txt'

**Comment by frostming** [comment]
@gotexis 

1. There is no `pipenv freeze` command, this will surely fail.
2. To use redirecting in subprocess command, you should add `shell=True` option.

Close as the issue isn't related to pipenv
