### ISSUE TITLE
pipenv shell (how does it know which virtualenv to be used from /home/user/.local/share/virtualenvs

### ISSUE THREAD

**Issue by sant527** [pypa/pipenv#3596]
First i do 

```
$ mkdir /home/user/test1 && ch /home/user/test1

$ pipenv install

```
-- it creates a virtualenv eg:  `/home/user/.local/share/virtualenvs/app-TBa3bLVu/`

Second i do
```
$ mkdir /home/user/test2 && ch /home/user/test2

$ pipenv install
```

-- it creates a virtualenv eg: ` /home/user/.local/share/virtualenvs/app-JhkjhsL/`

Now  how does `pipenv shell` know which virtual env to be used. Where from it gets that information.

**Comment by frostming** [comment]
@sant527 It will use the parent path of the found Pipfile(aka project path), to get a hashed string, which is what you see in `app-JhkjhsL`. The part after the dash is the hash of the project path.

**Comment by sant527** [comment]
can you show more explicityly which file stores the verification hash and how the hash of the project path is compared with that.

**Comment by frostming** [comment]
@sant527 the hash isn't stored somewhere, it forms the path of venv. So whenever Pipenv tries to find the venv, it uses the project path to calculate the hash. As long as the project isn't moved, the venv path is well determined.

```bash
$ mkdir /home/user/test1 && cd /home/user/test1
$ pipenv install
# Pipfile is created under /home/user/test1, project path is /home/user/test1
# Calculate the hash with the path: TBa3bLVu
# Then form the venv path using <project base name>-<hash>: test1-TBa3bLVu
```

**Comment by techalchemy** [comment]
Closing this out as I think we have provided as much as we can here
