### ISSUE TITLE
Unspecified vendored pep514tools

### ISSUE THREAD

**Issue by hroncok** [pypa/pipenv#3597]
pipenv bundles pythonfinder==1.2.0 as declared in https://github.com/pypa/pipenv/blob/d4c8d17024c7c18311de81d878530c1923f491c5/pipenv/vendor/vendor.txt#L24

yet there is vendored [pep514tools](https://github.com/zooba/pep514tools) in pythonfinder as specified in https://github.com/pypa/pipenv/blob/d4c8d17024c7c18311de81d878530c1923f491c5/pipenv/vendor/pythonfinder/_vendor/vendor.txt#L1

I think the top level vendor.txt should either include pep514tools or is should be deleted, as it is only used for mypy runs. Thoughts?

**Comment by hroncok** [comment]
Also, https://github.com/zooba/pep514tools/blob/master/LICENSE is missing from pipenv entirely.

**Comment by techalchemy** [comment]
it should be included, the license will be picked up just by including and vendoring it

also, it is used for windows to find python locations-- pep514 is the windows python registry specification.  See [PEP 514](https://www.python.org/dev/peps/pep-0514/)

**Comment by techalchemy** [comment]
Additionally PythonFinder vendors this because it (at least was) necessary to modify this at one point.  I believe I pr'ed a fix upstream and it's been merged so that might not be the case anymore so it may be fine to vendor it in pipenv

**Comment by oz123** [comment]
KK hookup umukkküjmpopp

**Comment by oz123** [comment]
Closing as this is not a real bug.
