### ISSUE TITLE
how pipenv know Pipfile.lock is outdated

### ISSUE THREAD

**Issue by sant527** [pypa/pipenv#3598]
$ pipenv install

-- creates a virtualenv and created Pipfile and Pipfile.lock

$ pipenv install django

Q: It places the django in the Pipfile and also regenerated the Pipfile.lock with all the dependecies.

So whenever i install any package using pipenv, Pipfile.lock is also updated.

HOw does the hash comparision works so that form the hash of Pipfile it comes to know whether Pipfile.lock is outdated or not.

**Comment by frostming** [comment]
@sant527 The hash is calculated from the Pipfile content, and stored in Pipfile.lock. When the Pipfile content is changed, Pipenv will calculate the hash again and compare it with that stored in Pipfile.lock to see if it needs to be updated.

**Comment by frostming** [comment]
@sant527 Thanks for your curiosity about the implementing details, you can always refer to the source code to find the answer.

**Comment by sant527** [comment]
is there a way using pipenv command to know whether my Pipenv.lock is outdated or not

**Comment by frostming** [comment]
`pipenv update --outdated` 

why not go through all commands and find out what they do?

you should find answer yourself that are included in docs

**Comment by techalchemy** [comment]
Hopefully this is cleared up. Closing this out, thanks for submitting the issue

**Comment by hq9000** [comment]
> `pipenv update --outdated`
> 
> why not go through all commands and find out what they do?
> 
> you should find answer yourself that are included in docs

Sorry for being 3 years late to the party, but I have to point out that above reply doesn't actually answer the question.

what the OP meant, I think, is a way to tell, in advance, whether .lock is older than the Pipfile itself (for example, to fail the build as this would silently make the build non-determinstic).

The closest solution I found is to use `pipenv install --deploy`, this will fail if the "Pipfile.lock out of date" situation is encountered.
