### ISSUE TITLE
pipenv --system and --deploy for docker

### ISSUE THREAD

**Issue by sant527** [pypa/pipenv#3599]
I use `pipenv` for my `django` app.

```
$ mkdir djangoapp && cd djangoapp
$ pipenv install django==2.1
$ pipenv shell
(djangoapp) $ django-admin startproject example_project .
(djangoapp) $ python manage.py runserver
```

Now i am shifting to docker environment.

As per my understanding `pipenv` only installs packages inside a `virtualenv`

You don't need a virtual env inside a container, docket container IS a virtual environment in itself. 

Later after going through many Dockerfile 's i found `--system` option to install in the system.

For example the following i found:

https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
```
COPY ./Pipfile /usr/src/app/Pipfile
RUN pipenv install --skip-lock --system --dev
```

https://hub.docker.com/r/kennethreitz/pipenv/dockerfile
```
# -- Install dependencies:
ONBUILD RUN set -ex && pipenv install --deploy --system
```

https://wsvincent.com/beginners-guide-to-docker/
```
# Set work directory
WORKDIR /code

# Copy Pipfile
COPY Pipfile /code

# Install dependencies
RUN pip install pipenv
RUN pipenv install --system
```
So `--system` is only sufficient or `--deploy --system` is better way. And ` --skip-lock --system --dev` which is different again.

So can some one guide how to get my environment back in my Docker

**Comment by frostming** [comment]
@sant527 When you want to duplicate the environment from existing `Pipfile/Pipfile.lock`, `--deploy` is always recommended. 
`--skip-lock` will skip the locking stage so it isn't so recommended when you are **deploying** things, which should install from `Pipfile.lock`.
Find more explanations in [Pipenv's doc](https://docs.pipenv.org).

**Comment by sant527** [comment]
Then what about --system. Is --system option mainly used only in docker or vagrant or its used on the developement also

**Comment by frostming** [comment]
@sant527 Pipenv will install deps to system-wide python site packages instead of virtualenv. Whether or not to use it in your case depends. The option doesn't suggest a use pattern itself, but from my personal preference, I would recommend you use it only when deploying in an isolated environment, such as a docker container.

Closing it for now, hope that is clear enough.
