### ISSUE TITLE
Pipfile is not recognized from directories deeper than grandchild

### ISSUE THREAD

**Issue by mukuge** [pypa/pipenv#3617]
### Issue description

Pipfile is not recognized by the pipenv command when the current directory is deeper than grandchild directories from its Pipenv project root.

```
% mkdir -p pipenv-test-project/1/2/3
% cd pipenv-test-project
% pipenv install
Creating a virtualenv for this project…
...
Alternatively, run a command inside the virtualenv with pipenv run.
% pipenv --where
/private/tmp/pipenv-test-project
% cd 1
% pipenv --where
/private/tmp/pipenv-test-project
% cd 2
% pipenv --where
/private/tmp/pipenv-test-project
% cd 3
% pipenv --where
No Pipfile present at project home. Consider running `pipenv install` first to automatically generate a Pipfile for you.
% pipenv --venv
No virtualenv has been created for this project yet!
Aborted!
%
```

### Expected result

The Pipfile should be recognized by the pipenv command even when the current directory is deeper than grandchild directories from its Pipenv project root.

### Actual result

As shown in the issue description.

### Steps to replicate

As shown in the issue description.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/Users/mukuge/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipenv'`

Python location: `'/Users/mukuge/.pyenv/versions/3.7.1/bin/python3.7'`

Python installations found:

- `3.7.1`: `/Users/mukuge/.pyenv/versions/3.7.1/bin/python3`
- `3.7.1`: `/Users/mukuge/.pyenv/versions/3.7.1/bin/python3.7m`
- `3.7.1`: `/Users/mukuge/.pyenv/versions/3.7.1-debug/bin/python3`
- `2.7.10`: `/usr/bin/python`
- `2.7.10`: `/usr/bin/pythonw`
- `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
'implementation_version': '3.7.1',
'os_name': 'posix',
'platform_machine': 'x86_64',
'platform_python_implementation': 'CPython',
'platform_release': '18.2.0',
'platform_system': 'Darwin',
'platform_version': 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST '
'2018; root:xnu-4903.241.1~1/RELEASE_X86_64',
'python_full_version': '3.7.1',
'python_version': '3.7',
'sys_platform': 'darwin'}
```

System environment variables:

- `MANPATH`
- `LESS_TERMCAP_mb`
- `TERM_PROGRAM`
- `LESS_TERMCAP_md`
- `LESS_TERMCAP_me`
- `PYENV_ROOT`
- `SHELL`
- `TERM`
- `ZPLUG_LOADFILE`
- `CLICOLOR`
- `SAVEHIST`
- `HISTSIZE`
- `TMPDIR`
- `Apple_PubSub_Socket_Render`
- `TERM_PROGRAM_VERSION`
- `FPATH`
- `BOOKMARKS_FILE`
- `ENHANCD_AWK`
- `LESS_TERMCAP_ue`
- `TERM_SESSION_ID`
- `PYENV_VERSION`
- `LC_ALL`
- `ZSH`
- `ZSH_TMUX_TERM`
- `ZPLUG_USE_CACHE`
- `GROFF_NO_SGR`
- `USER`
- `ENHANCD_DOT_ARG`
- `LS_COLORS`
- `ZPLUG_ERROR_LOG`
- `_ZSH_TMUX_FIXED_CONFIG`
- `ZPLUG_PROTOCOL`
- `ENHANCD_ROOT`
- `SSH_AUTH_SOCK`
- `TERMCAP`
- `PYENV_DIR`
- `__CF_USER_TEXT_ENCODING`
- `FZF_DEFAULT_OPTS`
- `COLUMNS`
- `_ZPLUG_PREZTO`
- `_ZPLUG_VERSION`
- `PERIOD`
- `LSCOLORS`
- `LESS_TERMCAP_us`
- `_ZPLUG_AWKPATH`
- `PATH`
- `ENHANCD_DIR`
- `ENHANCD_DISABLE_HOME`
- `PWD`
- `JAVA_HOME`
- `DBUS_LAUNCHD_SESSION_BUS_SOCKET`
- `LANG`
- `ITERM_PROFILE`
- `ENHANCD_HOME_ARG`
- `PYENV_HOOK_PATH`
- `_ZPLUG_CONFIG_SUBSHELL`
- `XPC_FLAGS`
- `_ZPLUG_OHMYZSH`
- `ZPLUG_BIN`
- `_ZPLUG_URL`
- `ENHANCD_HYPHEN_NUM`
- `XPC_SERVICE_NAME`
- `GPG_TTY`
- `ENHANCD_COMMAND`
- `ZPLUG_CACHE_DIR`
- `MANPAGER`
- `PYENV_SHELL`
- `SHLVL`
- `HOME`
- `COLORFGBG`
- `ENHANCD_FILTER`
- `ZSH_CACHE_DIR`
- `ZPLUG_REPOS`
- `ZPLUG_THREADS`
- `ENHANCD_DISABLE_HYPHEN`
- `ITERM_SESSION_ID`
- `LOGNAME`
- `LC_CTYPE`
- `LESS_TERMCAP_so`
- `ZPLUG_FILTER`
- `ZPLUG_HOME`
- `ENHANCD_DISABLE_DOT`
- `DISPLAY`
- `ENHANCD_HYPHEN_ARG`
- `ENHANCD_USE_FUZZY_MATCH`
- `INSIDE_EMACS`
- `ZPLUG_ROOT`
- `ENHANCD_DOT_SHOW_FULLPATH`
- `HISTFILE`
- `LESS_TERMCAP_se`
- `COLORTERM`
- `PIP_DISABLE_PIP_VERSION_CHECK`
- `PYTHONDONTWRITEBYTECODE`
- `PIP_SHIMS_BASE_MODULE`
- `PIP_PYTHON_PATH`
- `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

- `PATH`: `/Users/mukuge/.pyenv/versions/3.7.1/bin:/Users/mukuge/.pyenv/libexec:/Users/mukuge/.pyenv/plugins/python-build/bin:/Users/mukuge/.pyenv/shims:/Users/mukuge/dev/apache-maven-3.6.0/bin:/Users/mukuge/.pyenv/shims:/Users/mukuge/.pyenv/bin:/usr/local/bin:/usr/local/sbin/:/Users/mukuge/.cargo/bin:/usr/local/Cellar/zplug/2.4.2/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin`
- `SHELL`: `/usr/local/bin/zsh`
- `LANG`: `en_US.UTF-8`
- `PWD`: `/tmp/pipenv-test-project/1/2/3`

---------------------------

</details>

**Comment by frostming** [comment]
@mukuge Yes it is controlled by `PIPENV_MAX_DEPTH` env. https://pipenv.readthedocs.io/en/latest/advanced/#pipenv.environments.PIPENV_MAX_DEPTH

Closing for it isn't a bug.
