### ISSUE TITLE
Calculate the hashes on the gpu

### ISSUE THREAD

**Issue by Euphorbium** [pypa/pipenv#3618]
It is a common knowledge that `pipenv lock` takes FOREVER to complete on large projects with hundreds of dependancies. I am not sure which step is the bottleneck, but if it is hash calculation of thousands of files, maybe it would be a good idea to utilise the gpu for that? It would be amazing if it was possible to reuse some bitcoin miners for pipfile locking.

**Comment by techalchemy** [comment]
This is definitely a good idea, but unfortunately is going to have to be out of scope until we implement some kind of plugin system which isn't even on the roadmap yet.  I don't fancy supporting the implementation for offloading processing to an optional GPU abstraction layer, packaging in python doesn't even support detection of this in environment markers yet :(

if you have implementation ideas I'd suggest submitting a `PEEP` for that (probably need one for a plugin system first with some sample use cases) but I'm super curious about how the actual GPU aspect would be managed so if there is a cogent proposal here it could expedite the plugin system aspect

closing this specific issue for now until we have something more concrete to act on, but we are doing too much directly in pipenv already so I am thinking this would need to be implemented somewhere else as an extension

**Comment by encrypromaniac** [comment]
Noong Biy, Mar 15, 2019, 2:16 AM, isinulat ni Juozas Masiulis <
notifications@github.com> ang:
