### ISSUE TITLE
possible rendundant vendor

### ISSUE THREAD

**Issue by PatrikKopkan** [pypa/pipenv#3621]
Hi, I ' ve noticed that shutilwhich is for importing which function. At description at pypi is said that it is not needed in pythons 3.3 and above. From setup.py I asume you don't support versions below 3.3. https://github.com/pypa/pipenv/blob/d5e446ee7bd0e769c385331714c8616c6b6738b8/setup.py#L130
And it seems you dont import this vendor in your project.
https://github.com/pypa/pipenv/search?q=shutilwhich&unscoped_q=shutilwhich

Hope that the issue is meaningful

**Comment by frostming** [comment]
@PatrikKopkan Thanks for reporting.

> I asume you don't support versions below 3.3.

But we need to support Python 2.7, don't we? I think it is there for Python 2.7.

**Comment by PatrikKopkan** [comment]
Thank you for your response.

From reading your code I still have feeling that it is not actually used. Could you point me to where it is needed?

**Comment by jayvdb** [comment]
No, it isnt needed for Python 2.7.

It is unused.  It was vendored due to pew, but that has been removed/unvendored by @uranusjr  in a5a9583 .  It was used by `pipenv/patched/pew/_utils.py` .

c.f. also https://github.com/pypa/pipenv/issues/3640

**Comment by uranusjr** [comment]
I believe Pipenv still has a few places relying on the system `which` command (or `where` on Windows). We should convert those to `shutil.which` instead. cc @techalchemy

**Comment by jayvdb** [comment]
There are a lot of `which` ... `system_which` should like the one you are referring to.  It falls back to [`pythonfinder`](https://github.com/sarugaku/pythonfinder)`.Finder` , which appears to do the job of `shutil.which`

```
grep -r def.*which pipenv-2018.11.26.1543215385.742ae1b9/pipenv/*.py
pipenv-2018.11.26.1543215385.742ae1b9/pipenv/core.py:def which(command, location=None, allow_global=False):
pipenv-2018.11.26.1543215385.742ae1b9/pipenv/core.py:def which_pip(allow_global=False):
pipenv-2018.11.26.1543215385.742ae1b9/pipenv/core.py:def system_which(command, mult=False):
pipenv-2018.11.26.1543215385.742ae1b9/pipenv/environment.py:    def which(self, search, as_path=True):
pipenv-2018.11.26.1543215385.742ae1b9/pipenv/project.py:    def __init__(self, which=None, python_version=None, chdir=True):
pipenv-2018.11.26.1543215385.742ae1b9/pipenv/project.py:    def which(self, search, as_path=True):
pipenv-2018.11.26.1543215385.742ae1b9/pipenv/resolver.py:def which(*args, **kwargs):
```

If this packport is going to be used again , please also provide some consistency/direction on whether all backports should be in pipenv/vendor/backports/ , because it is quite confusing to have `enum` in there, but `scandir` not in there, etc.

**Comment by uranusjr** [comment]
`backports.*` is the namespace used by a series of libraries. Whether a vendor ed package live inside it depends on how the upstream package does it, not how Pipenv organises it’s vendoring process.

**Comment by jayvdb** [comment]
@uranusjr , `pipenv/vendor/backports/enum` is enum34, and is not in the `backports` namespace.

**Comment by jayvdb** [comment]
https://github.com/pypa/pipenv/pull/3676 opened to check if this really is unused.

I note that `shutilwhich` monkey patches the real stdlib `shutil.which`, and so should only be used if that really is necessary.  It should be removed if possible.

The less intrusive `backports.shutil_which` should be used, as it doesnt modify the stdlib, and it has a much better test suite.  `shutilwhich` tests only test that its monkey patching works, while `backports.shutil_which` verifies its function works correctly.

**Comment by PatrikKopkan** [comment]
Thank you all for hearing me out.
