### ISSUE TITLE
pipenv hangs if there is a interactive pythoni script 

### ISSUE THREAD

**Issue by blueyed** [pypa/pipenv#3625]
Running `pipenv --python 2` hangs for me, if I have pyrepl installed, which ships a `pythoni` script - apparently a custom, always interactive `python` wrapper.

`Ctrl-C`ing there does not help, but pipenv needs to be killed.

I could reproduce it with a custom script in $PATH:

```sh
#!/bin/sh

echo "$@" >&2
echo "$@" >/tmp/t1

cat -
```

Then `pipenv` can be canceled and shows:
```

Traceback (most recent call last):
   File "/usr/lib/python3.7/site-packages/pipenv/vendor/vistir/contextmanagers.py", line 150, in spinner
    yield _spinner
   File "/usr/lib/python3.7/site-packages/pipenv/vendor/vistir/misc.py", line 314, in run
    write_to_stdout=True
   File "/usr/lib/python3.7/site-packages/pipenv/vendor/vistir/misc.py", line 236, in _create_subprocess
    c.out, c.err = c.communicate()
   File "/usr/lib/python3.7/subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
   File "/usr/lib/python3.7/subprocess.py", line 1681, in _communicate
    ready = selector.select(timeout)
   File "/usr/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
 KeyboardInterrupt
```

(This is displayed as a list though:
```
% pipenv --python 2
['Traceback (most recent call last):\n', …, , 'KeyboardInterrupt\n']
Environment creation aborted.
```

The output from the `pythoni` shell script is displayed nowhere, but `/tmp/t1` shows what pipenv called it with: `-c import sys; print(sys.version.split()[0])`.

So it looks like pipenv calls `python*` from the path to get all the versions, or something similar?!

1. Why doesn't it just use `python2`, without even calling it?
2. Why is it not possible to Ctrl-C it with `pythoni` from pyrepl?  (that might be pyrepl's fault though, but I think pipenv should ensure to always get notified of SIGINT, especially in this case).
3. Even `pipenv -vv --python 2` does not display anything?!

This was with pipenv, version 2018.11.15.dev0.

I've then tried master, which shows more on `Ctrl-C`:

```
Traceback (most recent call last):
  File "/tmp/foo/.pyenv/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/python.py", line 565, in from_path
    instance_dict = cls.parse(path_name)
  File "/tmp/foo/.pyenv/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/python.py", line 517, in parse
    version_dict = parse_python_version(str(version))
  File "/tmp/foo/.pyenv/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/utils.py", line 118, in parse_python_version
    raise InvalidPythonVersion("%s is not a python version" % version_str)
pipenv.vendor.pythonfinder.exceptions.InvalidPythonVersion: pythoni is not a python version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/foo/.pyenv/lib/python3.7/site-packages/pipenv/vendor/vistir/contextmanagers.py", line 162, in spinner
    yield _spinner
  File "/tmp/foo/.pyenv/lib/python3.7/site-packages/pipenv/vendor/vistir/misc.py", line 334, in run
    write_to_stdout=True,
  File "/tmp/foo/.pyenv/lib/python3.7/site-packages/pipenv/vendor/vistir/misc.py", line 255, in _create_subprocess
    c.out, c.err = c.communicate()
  File "/usr/lib/python3.7/subprocess.py", line 939, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1681, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```

I.e. it shows the traceback correctly, and it appears to actually get
`pythonfinder.exceptions.InvalidPythonVersion` internally, but still hangs.
Using `pythoni` from pyrepl still hangs it.

`pipenv --support` also hangs.. :/

Without `pythoni` it shows (this should be master, but the version does not reflect it?!)

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.27.dev0'`

Pipenv location: `'/tmp/foo/.pyenv/lib/python3.7/site-packages/pipenv'`

Python location: `'/tmp/foo/.pyenv/bin/python'`

Python installations found:

  - `3.8.0a2`: `/home/user/bin/python3.8`
  - `3.7.2`: `…/pyenv/3.7.2/bin/python3`
  - `3.7.2`: `/usr/bin/python3`
  - `3.7.2`: `/usr/bin/python3.7m`
  - `3.6.8`: `/home/user/bin/python3.6`
  - `3.6.1`: `/usr/bin/pypy3`
  - `3.5.6`: `…/pyenv/3.5.6/bin/python3`
  - `3.4.4`: `/home/user/bin/python3.4`
  - `3.3.7`: `/usr/bin/python3.3m`
  - `3.3.7`: `/usr/bin/python3.3`
  - `2.7.16`: `…/pyenv/mopidy/bin/python2.7`
  - `2.7.16`: `…/pyenv/2.7.16/bin/python2.7`
  - `2.7.16`: `/usr/bin/python2.7`
  - `2.7.15`: `…/pyenv/2.7.15/bin/python2.7`
  - `2.6.9`: `…/pyenv/2.6.9/bin/python2.6`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.0.0-arch1-1-ARCH',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Mon Mar 4 14:11:43 UTC 2019',
 'python_full_version': '3.7.2',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `DIRCOLORS_SETUP`
  - `SSH_AUTH_SOCK`
  - `MY_SESSION_RUN_PID`
  - `MY_X_THEME_VARIANT`
  - `_MY_X_THEME_VARIANT_TTY`
  - `DESKTOP_SESSION`
  - `GPG_TTY`
  - `CLOUDSDK_PYTHON_ARGS`
  - `XDG_SEAT`
  - `PWD`
  - `LOGNAME`
  - `XDG_SESSION_TYPE`
  - `NVIM_TUI_ENABLE_CURSOR_SHAPE`
  - `XAUTHORITY`
  - `WINDOWPATH`
  - `HOME`
  - `LANG`
  - `LS_COLORS`
  - `XDG_CURRENT_DESKTOP`
  - `PYTHONSTARTUP`
  - `CLOUDSDK_ROOT_DIR`
  - `_ZSH_MY_BASE_SHLVL`
  - `INVOCATION_ID`
  - `CLOUDSDK_PYTHON`
  - `GEM_HOME`
  - `XDG_SESSION_CLASS`
  - `LESSOPEN`
  - `GOOGLE_CLOUD_SDK_HOME`
  - `USER`
  - `DISPLAY`
  - `SHLVL`
  - `XDG_VTNR`
  - `MY_X_SESSION_NAME`
  - `DBUS_SESSION_BUS_PID`
  - `XDG_SESSION_ID`
  - `GPGKEY`
  - `PYTHONDOCS`
  - `MOZ_PLUGIN_PATH`
  - `XDG_RUNTIME_DIR`
  - `PYENV_ROOT`
  - `EMAIL`
  - `DIRCOLORS_SETUP_FOR_PID`
  - `JOURNAL_STREAM`
  - `PATH`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `HG`
  - `MAIL`
  - `OLDPWD`
  - `_`
  - `DESKTOP_STARTUP_ID`
  - `WINDOWID`
  - `COLORFGBG`
  - `COLORTERM`
  - `TERM`
  - `BASE16_THEME`
  - `ZSH`
  - `ZSH_THEME`
  - `FZF_DEFAULT_OPTS`
  - `FZF_DEFAULT_COMMAND`
  - `FZF_CTRL_T_COMMAND`
  - `VB`
  - `VP`
  - `LSCOLORS`
  - `_USE_XTERM_CURSOR_CODES`
  - `_ZSH_DID_CD_DASH`
  - `RI`
  - `LESSQUIET`
  - `LESS`
  - `EDITOR`
  - `VIRSH_DEFAULT_CONNECT_URI`
  - `PAGER`
  - `LC_CTYPE`
  - `DEBFULLNAME`
  - `DEBEMAIL`
  - `pacman_program`
  - `MP_FULLNAME`
  - `GOPATH`
  - `PIPENV_VENV_IN_PROJECT`
  - `_ZSH_LAST_CMD_TITLE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/user/.pyenv/libexec:/home/user/bin:/home/user/bin/go1.x/bin:/home/user/.local/opt/neovim/bin:/home/user/.pyenv/shims/system:/home/user/.pyenv/bin:/home/user/bin:…/usr/bin:/home/user/.luarocks/bin:/home/user/.npm-packages/bin:/home/user/.local/bin:/home/user/.gem/ruby/2.6.0/bin:/opt/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
  - `SHELL`: `/usr/bin/zsh`
  - `EDITOR`: `nvim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/tmp/foo`

---------------------------

Contents of `Pipfile` ('/tmp/foo/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "2.7"

```

</details>

`pyrepli` from pyrepl can be seen here: https://github.com/blueyed/pyrepl/blob/master/pythoni (I am trying to fix pyrepl maintenance in that repo).

**Comment by frostming** [comment]
Duplicates:
#3399 
#3412

**Comment by blueyed** [comment]
Not really - one of the main issues here also is that it should not just start anything "python*" in the PATH.
But anyway, I am not using pipenv for reasons like this anyway, and will stop reporting issue I find when helping others / have to use it I guess.. ;)

**Comment by frostming** [comment]
@blueyed Oh yes, `pythonfinder` uses some manner to find the python interpreter in your system.

**Comment by tkcranny** [comment]
I too am having bad issues with `pipenv install` hanging indefinitely and silently for a similar looking reason. The culprit seems to be a hanging `pythoni` process.

This ignores `CTRL`+`C` signals too, and never resolves after even an hour.

A simple but ugly work around is to kill the `pythoni` child process, which seems to let pipenv proceed more or less normally. This does however leave the terminal session in a corrupted state; [new] lines and colours are usually incorrect (although a `reset` fixes this):

![image](https://user-images.githubusercontent.com/4208581/55201921-ebc4ac00-5210-11e9-9e85-f8b29e9bf09a.png)

---

This only has the effect in directories with an existing lockfile, so my steps to replicate are:

```bash
$ mkdir /tmp/foo
$ cd /tmp/foo
$ pipenv install
$ pipenv install ipython
$ pipenv --rm
$ ls
# => Pipfile  Pipfile.lock
$ pipenv install
# => Indefinte hang.
```

**Version Information**
- `pipenv --version`: `pipenv, version 2018.11.26`
- `pipenv --py`: `/Users/tkc/.local/share/virtualenvs/foo-mzLZXOua/bin/python`
- `$(pipenv --py) --version`: `Python 3.7.3`

**Comment by matteius** [comment]
Is this still an issue on latest versions of `pipenv`?
