### ISSUE TITLE
pipenv install -r requirements.txt fails with functool32

### ISSUE THREAD

**Issue by roadie-james** [pypa/pipenv#3628]
Environment:

Mac OS Mojave
pipenv, version 2018.11.26
python 3.7.2
[pipenv_support.out.TXT](https://github.com/pypa/pipenv/files/2985731/pipenv_support.out.TXT)

### Issue description

pipenv install -r requirements.txt fails with 
"pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/t3/_dlmb0rj27g993l6myf7rzrw0000gn/T/tmp0kt0g7tgbuild/functools32/"

### Expected result

No error.

### Actual result

see execution_out
[execution_out.TXT](https://github.com/pypa/pipenv/files/2985733/execution_out.TXT)

### Steps to replicate

1.  Go to folder
2. pipenv shell  (succeeds)
3. pipenv install -r requirements.txt  (fails)

See attached Pipfile, requirements.txt

[requirements.txt](https://github.com/pypa/pipenv/files/2985729/requirements.txt)

[Pipfile.TXT](https://github.com/pypa/pipenv/files/2985730/Pipfile.TXT)

**Comment by frostming** [comment]
`functools32` has some validation codes in `setup.py` and will fail on Python 3. Please specify another `functools` link in your Pipfile. You can take https://github.com/sarugaku/passa/pull/65 for example.

**Comment by roadie-james** [comment]
@frostming thanks!  your solution worked for me.   this would be helpful to add to https://pipenv.readthedocs.io/en/latest/diagnose/
