### ISSUE TITLE
Cannot find in doco how comments are marked in the Pipfile

### ISSUE THREAD

**Issue by halloleo** [pypa/pipenv#3629]
I'm having a hard time to find in the [documentation](https://pipenv.readthedocs.io/en/latest/) how comments are marked in the Pipfile. 

I think `#` does the job, but I'm not sure. As said, I couldn't find anything about it. I looked at the documentation of v2018.11.26

**Comment by frostming** [comment]
> I think # does the job, but I'm not sure.

Correct.

Pipfile uses [TOML](https://github.com/toml-lang/toml) format, and I believe it is referred to in the documentation. A reference link to the TOML spec would be great.

**Comment by NicholasSurmava** [comment]
Hey all. I submitted a PR for this. My first PR so hopefully I did everything correctly :)

https://github.com/pypa/pipenv/pull/3643
