### ISSUE TITLE
Add an option to automatically `conda install xxx`  if occur error .

### ISSUE THREAD

**Issue by eromoe** [pypa/pipenv#3636]
### Is your feature request related to a problem? Please describe.

Windows usually would encounter some build problem, which would make pipenv install failed. 
 it would be easily to solve by 

1. `conda install xxx` 
2. `conda install -c conda-forge xxx`

### Describe the solution you'd like

Provide an option:

when  `pip install xxx` failed automatically call 

1. `conda install xxx` 
2. `conda install -c conda-forge xxx`

Or without option, if detect environment have conda ,  automatically call above command.

**Comment by uranusjr** [comment]
I am -1 to this. Conda packaging is fundamentally too different from pip that mixing those two would cases more trouble down the road. Also the name Pipenv contains *pip* for a reason 😛 

It is possible to make Conda and pip work together in theory, and there has been [speculations](https://discuss.python.org/t/structured-exchangeable-lock-file-format-requirements-txt-2-0/876/34) on how that would work. But it is not a goal that can be reasonably pursued at the current time.

**Comment by eromoe** [comment]
My suggestion is just for convenience .  Pipenv no need to care what's go wrong when install package , if one  `xxx==version` doesn't exist on conda, just raise Exception.

As my opinion, pipenv is mainly focus on below features . 

## Features
* Enables truly deterministic builds, while easily specifying only what you want.
* Generates and checks file hashes for locked dependencies.
* Automatically install required Pythons, if pyenv is available.
* Automatically finds your project home, recursively, by looking for a Pipfile.
* Automatically generates a Pipfile, if one doesn't exist.
* Automatically creates a virtualenv in a standard location.
* Automatically adds/removes packages to a Pipfile when they are un/installed.
* Automatically loads .env files, if they exist.

Add the feature I suggest would not break any parts of current , I think it is a ideal solution for now , since  building problem happens very usual.
