### ISSUE TITLE
Option to skip updating the dependencies

### ISSUE THREAD

**Issue by Euphorbium** [pypa/pipenv#3638]
Currently, when you do `pipenv install somepackage` all of the dependancies and the subdependancies get updated to the latest compatible version. Please provide an option to skip this update. Installing just one package takes seconds. Downloading and calculating hashes for hundreds of files take more than half an hour. I would like to do this update on my own schedule, separate from installing a package.

**Comment by frostming** [comment]
https://pipenv.readthedocs.io/en/latest/#cmdoption-pipenv-install-skip-lock

**Comment by Euphorbium** [comment]
@frostming this is not the same. I need a new lock file, including the new package, just without the update of the old.

**Comment by frostming** [comment]
>I need a new lock file, including the new package, just without the update of the old.

I can't conclude from the issue description.
I put the link without a word in the last comment is to remind you to read the doc carefully -- it is there for a reason.

Per your update, --keep-outdated is what you want.
