### ISSUE TITLE
Please Do a Bugfix Release

### ISSUE THREAD

**Issue by adonig** [pypa/pipenv#3639]
Sadly the current version of pipenv available in homebrew has [broken support for pyenv](https://github.com/pypa/pipenv/issues/3551). While it's possible to install pipenv from master, it would still be a good idea to release a new version as soon as possible. Otherwise you risk that people who try pipenv for the first time might get a misleading first impression. Additionally even seasoned pipenv users suffer from having to do a web search to find a workaround to fix their work environment.

**Comment by whyboris** [comment]
It also seems it's time to have a proper regular *Next Release* according to the _Project Board_:

https://github.com/pypa/pipenv/projects/8

The only issue in the project board not in the _Done_ column has already been closed: https://github.com/pypa/pipenv/issues/2359

We've not had a release since _Nov 26, 2018_ and it's end of March 2019 (4 months). I suspect enough things have been improved/fixed since then that many people are still running into trouble they could be avoiding with just the latest release 🤔 

Thank you for your work 🙇

**Comment by techalchemy** [comment]
To be fair, I have no idea what that project is -- apologies for the delay on this but we had significant delays getting CI builds passing with updates to pip, piptools, and other resolver issues.  Each delay has added up to over a week at a time and this is a project that happens in our free time -- and it is super complicated to push a release with so many moving parts coming together.  I _will_ get one out this week, which is about a week or two behind when I _actually_ planned to cut a release.

**Comment by AlJohri** [comment]
Thanks for the hard work @techalchemy. Also looking forward to restoring pyenv support. ❤️

**Comment by miketheman** [comment]
Hi wonderful contributors! Is there any chance this is in the works, or could use some help getting things ready for release?

**Comment by AlJohri** [comment]
Related: https://github.com/pypa/pipenv/issues/3742

**Comment by amir-barkal** [comment]
why you no?
<a href="https://user-images.githubusercontent.com/30290948/58579912-aa726c00-8254-11e9-82ed-7c760d8dc311.jpg"><img src="https://user-images.githubusercontent.com/30290948/58579912-aa726c00-8254-11e9-82ed-7c760d8dc311.jpg" width="150"/></a>

**Comment by whyboris** [comment]
@amir-barkal -- it's very likely you meant the image in a jovial fashion (it's a funny meme, I like it too), but it's easy to misread people on the internet, and the maintainers of the repository might feel as if you're _demanding_ they do something (which isn't pleasant). 

In the future, a comment like this accompanying with a comment below saying something like "thank you for your hard work 🙇‍♂️" would remove the ambiguity 😉

**Comment by amir-barkal** [comment]
Apologies to anyone if I have offended them, that was never my intention. 

@whyboris I’ve edited the comment as per your kind advice. Thank you.

**Comment by frostming** [comment]
Redirect #3742
