### ISSUE TITLE
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpaf9s7qtwbuild/form/

### ISSUE THREAD

**Issue by LokiSharp** [pypa/pipenv#3641]
I am getting error message below when trying to install libsass django-compressor and django-sass-processor

### Issue description

<pre>✔ Installation Succeeded 
<b>Pipfile.lock not found, creating…</b>
Locking <font color="#CC0000">[dev-packages]</font> dependencies…
Locking <font color="#CC0000">[packages]</font> dependencies…
<font color="#CC0000">✘ Locking Failed!</font> 
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py&quot;, line 126, in &lt;module&gt;
    main()
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py&quot;, line 119, in main
    parsed.requirements_dir, parsed.packages)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py&quot;, line 85, in _main
    requirements_dir=requirements_dir,
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py&quot;, line 69, in resolve
    req_dir=requirements_dir
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/utils.py&quot;, line 726, in resolve_deps
    req_dir=req_dir,
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/utils.py&quot;, line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/utils.py&quot;, line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/resolver.py&quot;, line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/resolver.py&quot;, line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/resolver.py&quot;, line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/repositories/pypi.py&quot;, line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/repositories/pypi.py&quot;, line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/repositories/pypi.py&quot;, line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/notpip/_internal/resolve.py&quot;, line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/notpip/_internal/resolve.py&quot;, line 213, in _get_abstract_dist_for
    self.require_hashes
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/notpip/_internal/operations/prepare.py&quot;, line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/notpip/_internal/operations/prepare.py&quot;, line 127, in prep_for_dist
    self.req.run_egg_info()
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/notpip/_internal/req/req_install.py&quot;, line 474, in run_egg_info
    command_desc=&apos;python setup.py egg_info&apos;)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/notpip/_internal/utils/misc.py&quot;, line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command &quot;python setup.py egg_info&quot; failed with error code 1 in /tmp/tmpaf9s7qtwbuild/form/
File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py&quot;, line 126, in &lt;module&gt;
    main()
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py&quot;, line 119, in main
    parsed.requirements_dir, parsed.packages)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py&quot;, line 85, in _main
    requirements_dir=requirements_dir,
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py&quot;, line 69, in resolve
    req_dir=requirements_dir
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/utils.py&quot;, line 726, in resolve_deps
    req_dir=req_dir,
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/utils.py&quot;, line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/utils.py&quot;, line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/resolver.py&quot;, line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/resolver.py&quot;, line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/resolver.py&quot;, line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/repositories/pypi.py&quot;, line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/repositories/pypi.py&quot;, line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/repositories/pypi.py&quot;, line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/notpip/_internal/resolve.py&quot;, line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/notpip/_internal/resolve.py&quot;, line 213, in _get_abstract_dist_for
    self.require_hashes
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/notpip/_internal/operations/prepare.py&quot;, line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/notpip/_internal/operations/prepare.py&quot;, line 127, in prep_for_dist
    self.req.run_egg_info()
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/notpip/_internal/req/req_install.py&quot;, line 474, in run_egg_info
    command_desc=&apos;python setup.py egg_info&apos;)
  File &quot;/usr/local/lib/python3.6/dist-packages/pipenv/patched/notpip/_internal/utils/misc.py&quot;, line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command &quot;python setup.py egg_info&quot; failed with error code 1 in /tmp/tmpaf9s7qtwbuild/form/
</pre>

### Expected result

Describe what you expected.

### Actual result

Error message above

### Steps to replicate

pipenv install libsass django-compressor django-sass-processor

Below is output of pipenv --support

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.6/dist-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.6.7`: `/usr/bin/python3`
  - `3.6.7`: `/usr/bin/python3.6m`
  - `2.7.15rc1`: `/usr/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.18.0-16-generic',
 'platform_system': 'Linux',
 'platform_version': '#17~18.04.1-Ubuntu SMP Tue Feb 12 13:35:51 UTC 2019',
 'python_full_version': '3.6.7',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `CLUTTER_IM_MODULE`
  - `LS_COLORS`
  - `LC_MEASUREMENT`
  - `LESSCLOSE`
  - `LC_PAPER`
  - `LC_MONETARY`
  - `XDG_MENU_PREFIX`
  - `LANG`
  - `DISPLAY`
  - `GNOME_SHELL_SESSION_MODE`
  - `COLORTERM`
  - `DESKTOP_AUTOSTART_ID`
  - `USERNAME`
  - `XDG_VTNR`
  - `SSH_AUTH_SOCK`
  - `MANDATORY_PATH`
  - `LC_NAME`
  - `XDG_SESSION_ID`
  - `USER`
  - `DESKTOP_SESSION`
  - `QT4_IM_MODULE`
  - `TEXTDOMAINDIR`
  - `GNOME_TERMINAL_SCREEN`
  - `DEFAULTS_PATH`
  - `PWD`
  - `HOME`
  - `TEXTDOMAIN`
  - `SSH_AGENT_PID`
  - `QT_ACCESSIBILITY`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `XDG_SESSION_DESKTOP`
  - `LC_ADDRESS`
  - `LC_NUMERIC`
  - `GTK_MODULES`
  - `PAPERSIZE`
  - `WINDOWPATH`
  - `VTE_VERSION`
  - `TERM`
  - `SHELL`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `IM_CONFIG_PHASE`
  - `XDG_CURRENT_DESKTOP`
  - `GPG_AGENT_INFO`
  - `GNOME_TERMINAL_SERVICE`
  - `XDG_SEAT`
  - `SHLVL`
  - `LANGUAGE`
  - `LC_TELEPHONE`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `XDG_CONFIG_DIRS`
  - `PATH`
  - `LC_IDENTIFICATION`
  - `SESSION_MANAGER`
  - `LESSOPEN`
  - `GTK_IM_MODULE`
  - `LC_TIME`
  - `_`
  - `OLDPWD`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `zh_CN.UTF-8`
  - `PWD`: `/home/loki-sharp/PycharmProjects/DSharp`

---------------------------

Contents of `Pipfile` ('/home/loki-sharp/PycharmProjects/DSharp/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
verify_ssl = true

[dev-packages]

[packages]
django = "*"
django-allauth = "*"
django-debug-toolbar = "*"
django-jinja = "*"
form = "*"
libsass = "*"
django-compressor = "*"
django-sass-processor = "*"

[requires]
python_version = "3.6"

```

</details>

**Comment by Jison** [comment]
how you fix it?

**Comment by LokiSharp** [comment]
Use Linux to lock dependencies

**Comment by Jacksole** [comment]
How do you use Linux to lock it?

**Comment by LokiSharp** [comment]
I think this error is the WSL has something different to real Linux. So I try to create a dev env in a real Linux with VMware.
