### ISSUE TITLE
Is there a way to explicitly forbid a package in the Pipfile?

### ISSUE THREAD

**Issue by murrple-1** [pypa/pipenv#3649]
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3.6'`

Python installations found:

  - `3.6.8`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.8',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '3.0.4(0.338/5/3)',
 'platform_system': 'CYGWIN_NT-10.0',
 'platform_version': '2019-03-16 09:50',
 'python_full_version': '3.6.8',
 'python_version': '3.6',
 'sys_platform': 'cygwin'}
```

System environment variables:

  - `USERDOMAIN`
  - `OS`
  - `COMMONPROGRAMFILES`
  - `PROCESSOR_LEVEL`
  - `PSModulePath`
  - `CommonProgramW6432`
  - `CommonProgramFiles(x86)`
  - `LANG`
  - `TZ`
  - `HOSTNAME`
  - `PUBLIC`
  - `OLDPWD`
  - `USERNAME`
  - `LOGONSERVER`
  - `PROCESSOR_ARCHITECTURE`
  - `LOCALAPPDATA`
  - `COMPUTERNAME`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `USER`
  - `!::`
  - `SYSTEMDRIVE`
  - `USERPROFILE`
  - `PATHEXT`
  - `SYSTEMROOT`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `PROCESSOR_IDENTIFIER`
  - `OneDriveConsumer`
  - `PWD`
  - `HOME`
  - `TMP`
  - `OneDrive`
  - `PROCESSOR_REVISION`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `PROFILEREAD`
  - `NUMBER_OF_PROCESSORS`
  - `ProgramW6432`
  - `COMSPEC`
  - `APPDATA`
  - `SHELL`
  - `TERM`
  - `WINDIR`
  - `ProgramData`
  - `SHLVL`
  - `MINTTY_SHORTCUT`
  - `PRINTER`
  - `PROGRAMFILES`
  - `ALLUSERSPROFILE`
  - `TEMP`
  - `DriverData`
  - `SESSIONNAME`
  - `DASHLANE_DLL_DIR`
  - `ProgramFiles(x86)`
  - `PATH`
  - `PS1`
  - `HOMEDRIVE`
  - `INFOPATH`
  - `HOMEPATH`
  - `ORIGINAL_PATH`
  - `EXECIGNORE`
  - `VBOX_MSI_INSTALL_PATH`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/bin:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/WINDOWS/System32/OpenSSH:/cygdrive/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Program Files/nodejs:/cygdrive/c/Program Files (x86)/Yarn/bin:/cygdrive/c/Users/murrp/AppData/Local/Microsoft/WindowsApps:/cygdrive/c/Users/murrp/AppData/Local/Programs/Microsoft VS Code/bin:%DASHLANE_DLL_DIR%:/cygdrive/c/Users/murrp/AppData/Roaming/npm:/cygdrive/c/Users/murrp/AppData/Local/Yarn/bin:/home/murrp/bin/`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/cygdrive/d`

---------------------------

</details>

This is in direct reference to the issues raised in https://github.com/pypa/pipenv/issues/924.

Is there currently a way to explicity forbid installation of a package via the `Pipfile`?

I am currently have trouble installing the package `argon2-cffi` via `pipenv` because the lockfile is being generated with all subpackages, despite them being expressly forbid by the `setup.py` (https://github.com/hynek/argon2_cffi/blob/master/setup.py#L98). I realize via discussion on issue #924 that supporting `version_info` "hacks" are a quagmire, but I was wondering if there was a way to forbid the package in the `Pipfile` instead? Alternatively, would this be a good extension request?

I have a minimum reproducible Travis CI job that shows where the issue comes in for this: https://travis-ci.org/murrple-1/pipenv-issue-3 - you'll notice that `enum34` is being installed, and is overriding the API of the standard-library `enum.py`

**Comment by frostming** [comment]
IMO adding `enum34 = {version = "*", python_version = "<'3.4'"}` to Pipfile does forbid the installation and isn't a hack at all.

**Comment by frostming** [comment]
@murrple-1 It is likely that the dependencies are locked on Python < 3.4 but you want to deploy on Python >=3.4.

**Comment by murrple-1** [comment]
@frostming Yes, that seems to work. Thank you!
