### ISSUE TITLE
Skipped pre-versions reported multiple times

### ISSUE THREAD

**Issue by washeck** [pypa/pipenv#3654]
### Issue description

I added `django==2.2rc1` to Pipfile and ran `pipenv install` forgotting to add `--pre` argument

### Actual result

Pipenv reported the skipped pre-versions but they are printed many times:

`Skipped pre-versions: 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.10a1, 1.10a1, 1.10b1, 1.10b1, 1.10rc1, 1.10rc1, 1.11a1, 1.11b1, 1.11rc1, 1.11rc1, 2.0a1, 2.0b1, 2.0rc1, 2.1a1, 2.1b1, 2.1rc1, 2.2a1, 2.2a1, 2.2b1, 2.2b1, 2.2rc1, 2.2rc1`

### Expected result

Each skipped version should be printed only once.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/vaclav/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.7.1`: `/usr/bin/python3.7m`
  - `3.7.1`: `/usr/bin/python3.7`
  - `3.6.7`: `/usr/bin/python3`
  - `3.6.7`: `/usr/bin/python3.6m`
  - `2.7.15rc1`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-46-generic',
 'platform_system': 'Linux',
 'platform_version': '#49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019',
 'python_full_version': '3.6.7',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `CLUTTER_IM_MODULE`
  - `NVM_DIR`
  - `LS_COLORS`
  - `LC_MEASUREMENT`
  - `LESSCLOSE`
  - `LC_PAPER`
  - `LC_MONETARY`
  - `XDG_MENU_PREFIX`
  - `LANG`
  - `MANAGERPID`
  - `DISPLAY`
  - `INVOCATION_ID`
  - `UNITY_DEFAULT_PROFILE`
  - `AWS_SECRET_ACCESS_KEY`
  - `COMPIZ_CONFIG_PROFILE`
  - `GTK2_MODULES`
  - `GTK_CSD`
  - `COLORTERM`
  - `NVM_CD_FLAGS`
  - `USERNAME`
  - `SSH_AUTH_SOCK`
  - `MANDATORY_PATH`
  - `LC_NAME`
  - `USER`
  - `DESKTOP_SESSION`
  - `QT4_IM_MODULE`
  - `TEXTDOMAINDIR`
  - `GNOME_TERMINAL_SCREEN`
  - `DEFAULTS_PATH`
  - `PWD`
  - `HOME`
  - `JOURNAL_STREAM`
  - `TEXTDOMAIN`
  - `QT_ACCESSIBILITY`
  - `XDG_SESSION_TYPE`
  - `COMPIZ_BIN_PATH`
  - `XDG_DATA_DIRS`
  - `XDG_SESSION_DESKTOP`
  - `LC_ADDRESS`
  - `AWS_EC2_REGION`
  - `SSH_AGENT_LAUNCHER`
  - `LC_NUMERIC`
  - `GTK_MODULES`
  - `WINDOWPATH`
  - `GNOME_SESSION_XDG_SESSION_PATH`
  - `TERM`
  - `VTE_VERSION`
  - `SHELL`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `IM_CONFIG_PHASE`
  - `NVM_BIN`
  - `XDG_CURRENT_DESKTOP`
  - `GPG_AGENT_INFO`
  - `GNOME_TERMINAL_SERVICE`
  - `UNITY_HAS_3D_SUPPORT`
  - `AWS_ACCESS_KEY_ID`
  - `SHLVL`
  - `LC_TELEPHONE`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `XDG_CONFIG_DIRS`
  - `PATH`
  - `LC_IDENTIFICATION`
  - `LD_PRELOAD`
  - `SESSION_MANAGER`
  - `LESSOPEN`
  - `GTK_IM_MODULE`
  - `LC_TIME`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
```
</details>

**Comment by uranusjr** [comment]
You’d probably want to file this to [pip-tools](https://github.com/jazzband/pip-tools).
