### ISSUE TITLE
Pipenv unlimited cache size 

### ISSUE THREAD

**Issue by abdelrahman-t** [pypa/pipenv#3655]
### Issue description

Huge cache size (at ~/.cache/pipenv)

### Expected result

Cache to contain only the most recently used packages.

### Actual result

Cache seems to keep growing in size with no restrictions (16 GB), while Pip cache on the other hand is < 2GB

### Steps to replicate

du -ah ~/.cache/pipenv --max-depth=1 | sort -hr
16G	/home/pc/.cache/pipenv/http
16G	/home/pc/.cache/pipenv
185M	/home/pc/.cache/pipenv/wheels
74M	/home/pc/.cache/pipenv/hash-cache
12M	/home/pc/.cache/pipenv/pkgs
16K	/home/pc/.cache/pipenv/selfcheck.json
16K	/home/pc/.cache/pipenv/depcache-py3.6.json
16K	/home/pc/.cache/pipenv/depcache-py3.5.json
12K	/home/pc/.cache/pipenv/depcache-py3.7.json

du -ah ~/.cache/pip --max-depth=1 | sort -hr
1.9G	/home/pc/.cache/pip
1.8G	/home/pc/.cache/pip/http
124M	/home/pc/.cache/pip/wheels
16K	/home/pc/.cache/pip/selfcheck.json

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/pc/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3.6'`

Python installations found:

  - `3.7.0`: `/usr/local/bin/python3.7m`
  - `3.7.0`: `/usr/local/bin/python3.7`
  - `3.6.6`: `/usr/bin/python3.6m`
  - `3.6.6`: `/usr/bin/python3.6`
  - `3.5.2`: `/usr/bin/python3.5m`
  - `3.5.2`: `/usr/bin/python3.5`
  - `2.7.12`: `/usr/bin/python2.7`
  - `2.5.6`: `/usr/bin/python2.5`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-46-generic',
 'platform_system': 'Linux',
 'platform_version': '#49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019',
 'python_full_version': '3.6.6',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `XDG_SEAT`
  - `XDG_SESSION_ID`
  - `DISPLAY`
  - `UPSTART_JOB`
  - `JOB`
  - `COLORTERM`
  - `GNOME_KEYRING_CONTROL`
  - `GNOME_DESKTOP_SESSION_ID`
  - `DEFAULTS_PATH`
  - `QT_QPA_PLATFORMTHEME`
  - `LOGNAME`
  - `INSTANCE`
  - `JAVA_HOME`
  - `SHELL`
  - `PATH`
  - `IM_CONFIG_PHASE`
  - `QT4_IM_MODULE`
  - `CLUTTER_IM_MODULE`
  - `XMODIFIERS`
  - `XDG_SESSION_PATH`
  - `J2REDIR`
  - `SSH_AUTH_SOCK`
  - `UPSTART_EVENTS`
  - `XDG_SESSION_DESKTOP`
  - `GDMSESSION`
  - `XAUTHORITY`
  - `QT_IM_MODULE`
  - `XDG_CONFIG_DIRS`
  - `MANDATORY_PATH`
  - `UPSTART_SESSION`
  - `DESKTOP_SESSION`
  - `XDG_RUNTIME_DIR`
  - `GTK_IM_MODULE`
  - `IBUS_DISABLE_SNOOPER`
  - `GTK_MODULES`
  - `PWD`
  - `USER`
  - `DERBY_HOME`
  - `UPSTART_INSTANCE`
  - `TERMINATOR_UUID`
  - `HOME`
  - `QT_ACCESSIBILITY`
  - `ORBIT_SOCKETDIR`
  - `XDG_SEAT_PATH`
  - `XDG_DATA_DIRS`
  - `LANGUAGE`
  - `COMPIZ_CONFIG_PROFILE`
  - `XDG_GREETER_DATA_DIR`
  - `LANG`
  - `GTK2_MODULES`
  - `GPG_AGENT_INFO`
  - `SHLVL`
  - `WINDOWID`
  - `J2SDKDIR`
  - `XDG_VTNR`
  - `GDM_LANG`
  - `SESSIONTYPE`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_SESSION_TYPE`
  - `GNOME_KEYRING_PID`
  - `QT_LINUX_ACCESSIBILITY_ALWAYS_ON`
  - `TERM`
  - `OLDPWD`
  - `ZSH`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `LS_COLORS`
  - `LC_CTYPE`
  - `ANDROID_HOME`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/pc/bin:/home/pc/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/pc/Android/Sdk/platform-tools:/home/pc/Android/Sdk/tools:/home/pc/Android/Sdk/build-tools/23.0.2/:/home/pc/Downloads/android-sdk-linux/platform-tools:/home/pc/Downloads/android-sdk-linux/tools`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/pc`

**Comment by jerr0328** [comment]
I just ran into this issue as well, except my cache size was somehow 172GB (almost all of it the `http` directory). I wonder if pip is using some cache management (https://pip.pypa.io/en/stable/reference/pip_install/#caching seems to imply some expiration of the cache).

**Comment by abdelrahman-t** [comment]
I would like to point out that my pip cache at ~/.cache/pip was significantly smaller at 1.9GB vs 16G (Pipenv cache)

**Comment by leonelgalan** [comment]
Since this a is a cache, I assume we can safely clean it periodically, In exchange for slower installs? Having a workaround would be great, before it consumes our entire drives.

**Comment by mstrofbass** [comment]
Just came across this on my Mac. Had a 7 gig cache size, which seems pretty insane.

I feel like this should be pretty simple to take care of and should be a higher priority for something with the tagline "for humans".

**Comment by abdelrahman-t** [comment]
I use these three lines as a replacement for pipenv using [pip-tools](https://github.com/jazzband/pip-tools)

### create virtual environment
python -m venv venv && source venv/bin/activate

### pin requirments
pip-compile requirements.in --generate-hashes

### install pinned requirements
pip install -r requirements.txt

project seems to be dead, why this project is recomended at https://packaging.python.org/guides/tool-recommendations/ is truely beyond me!

**Comment by m-spyratos** [comment]
@uranusjr Why would this be a low priority enhancement? I'm new to Python here and I decided to use pipenv. Next day my hard drive was gone with 15GB of it occupied by these cache files.

If this is not going to be fixed any time soon, then a big warning in red on the top of the README file ought to be placed.

**Comment by januszm** [comment]
Mac OS X ~/Library/Caches/pipenv - 11GB

**Comment by aukeschaap** [comment]
Same issue here, 19 GB cache. I think this should be a higher priority than 'low', I might stop using pipenv altogether this way.

**Comment by binh-vu** [comment]
Encounter same issue. I just discover it uses 34GB of cache on my machine. There is no limit!

**Comment by frostming** [comment]
Neither does pip: https://github.com/pypa/pip/issues/3138

One should clean the cache manually or by some periodic cron jobs: `pipenv --clear`

**Comment by januszm** [comment]
Perhaps `pipenv` could use a mechanism similar to that used by `git` garbage collector.

Git `gc` is run automatically on several commonly used commands: `git pull`,  `merge`, `rebase` ... Pipenv can run the action `--clear` when its cache size exceeds the configured value or after X days.

**Comment by matteius** [comment]
`pipenv --clear` is the command to run for clearing your pipenv cache.
