### ISSUE TITLE
ubuntu 18.08 reuninstall pipenv

### ISSUE THREAD

**Issue by wangjiancn** [pypa/pipenv#3658]
Q1:I install python3.7.3 from source code,now i can use pipenv --python 3.7.3 to create a new virtualenv, but it can't install any moudle.

<details><summary>error message</summary>

Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✘ Locking Failed! 
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.6/dist-packages/pipenv/resolver.py", line 69, in resolve
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.6/dist-packages/pipenv/utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.6/dist-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.6/dist-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches django
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches django
No versions found
</details>

I use same command in python3.6.7, it work no problem.

Q2:I use `sudo -H pip3 install pipenv`,when i use `sudo -H pip3 uninstall pipenv` ,it warn Skipping pipenv as it is not installed.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.6/dist-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.7.3`: `/usr/local/bin/python3.7`
  - `3.7.3`: `/usr/local/bin/python3.7m`
  - `3.6.7`: `/usr/bin/python3`
  - `3.6.7`: `/usr/bin/python3.6m`
  - `2.7.15rc1`: `/usr/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-46-generic',
 'platform_system': 'Linux',
 'platform_version': '#49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019',
 'python_full_version': '3.6.7',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LC_ADDRESS`
  - `XDG_CONFIG_DIRS`
  - `LC_TELEPHONE`
  - `QT_ACCESSIBILITY`
  - `LANG`
  - `DISPLAY`
  - `SHLVL`
  - `LOGNAME`
  - `LANGUAGE`
  - `MANDATORY_PATH`
  - `LC_NAME`
  - `XDG_VTNR`
  - `USER`
  - `XAUTHORITY`
  - `DESKTOP_AUTOSTART_ID`
  - `GTK_IM_MODULE`
  - `COLORTERM`
  - `XDG_SESSION_ID`
  - `PWD`
  - `GNOME_TERMINAL_SCREEN`
  - `IM_CONFIG_PHASE`
  - `XDG_SESSION_DESKTOP`
  - `GDMSESSION`
  - `USERNAME`
  - `DEFAULTS_PATH`
  - `WINDOWPATH`
  - `PAPERSIZE`
  - `LC_PAPER`
  - `LC_NUMERIC`
  - `LC_MONETARY`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `LC_MEASUREMENT`
  - `TEXTDOMAINDIR`
  - `DESKTOP_SESSION`
  - `CLUTTER_IM_MODULE`
  - `TEXTDOMAIN`
  - `GNOME_DESKTOP_SESSION_ID`
  - `XDG_MENU_PREFIX`
  - `QT4_IM_MODULE`
  - `LC_IDENTIFICATION`
  - `GNOME_SHELL_SESSION_MODE`
  - `SHELL`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `LC_TIME`
  - `TERM`
  - `SESSION_MANAGER`
  - `GTK_MODULES`
  - `SSH_AGENT_PID`
  - `GNOME_TERMINAL_SERVICE`
  - `QT_IM_MODULE`
  - `PATH`
  - `XDG_CURRENT_DESKTOP`
  - `XMODIFIERS`
  - `HOME`
  - `XDG_RUNTIME_DIR`
  - `SSH_AUTH_SOCK`
  - `XDG_SEAT`
  - `VTE_VERSION`
  - `GPG_AGENT_INFO`
  - `OLDPWD`
  - `ZSH`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `LS_COLORS`
  - `LC_CTYPE`
  - `AUTOJUMP_SOURCED`
  - `AUTOJUMP_ERROR_PATH`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/wangj/.autojump/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/yarn-[version]/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/wangj`

---------------------------

</details>

**Comment by frostming** [comment]
1. Do you have a `python3.6` in `/usr/local/bin`, I don't find it in diagnostic information?
2. What is the output of `sudo -H pip3 list`?
3. What is the output of `sudo -H pip3 --version`?

**Comment by frostming** [comment]
Wrong button

**Comment by wangjiancn** [comment]
install a wrong python version,the ssl doesn't work.
