### ISSUE TITLE
Unable to install local package when using --pypi-mirror behind firewall

### ISSUE THREAD

**Issue by adgoudz** [pypa/pipenv#3665]
### Issue description

I'm running pipenv in a corporate environment where we use an internal Nexus mirror for PyPI, and I can't seem to keep pipenv from going out to pythonhosted.org when 1) installing a local package, and 2) specifying `--pypi-mirror`. Many python websites are blocked by our firewall.

As a test, I tried installing `six` with `--index` and `--pypi-mirror` together (both pointing to my mirror), and I still see proxy-related issues. 

### Expected result

Specifying `--pypi-mirror` should prevent pipenv from calling out to pypi.org always. I should need `--index` to install a mirrored package, and no index should be provided (to neither pipenv nor pip) in order to install a local package.

### Actual result

Creating the venv fails when installing 1) a local package, and 2) `six`, both because setuptools can't be installed:

```
Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/d1/6a/4b2fcefd2ea0868810e92d519dacac1ddc64a2e53ba9e3422c3b62b378a6/setuptools-40.8.0-py2.py3-none-any.whl (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
```

### Steps to replicate

```bash
pipenv install --verbose \
    --index http://<obfuscated>:8081/repository/pypi-all/simple/ \
    --pypi-mirror http://<obfuscated>:8081/repository/pypi-all/simple/ \
    six
```

Interestingly enough, I'm able to install `six` by doing this:
```bash
PIP_INDEX_URL=http://<obfuscated>:8081/repository/pypi-all/simple/ \
pipenv install --verbose \
    --index http://<obfuscated>:8081/repository/pypi-all/simple/ \
    --pypi-mirror http://<obfuscated>:8081/repository/pypi-all/simple/ \
    six
```

However, I can't do either of the above when installing a local source. The venv is created successfully, but locking fails:

```bash
PIP_INDEX_URL=http://<obfuscated>:8081/repository/pypi-all/simple/ \
pipenv install --verbose \
    --pypi-mirror http://<obfuscated>:8081/repository/pypi-all/simple/ \ 
    /path/to/some/package.tar.gz
```

Result:
```
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (dbf91a)!
Installing dependencies from Pipfile.lock (dbf91a)…
Traceback (most recent call last):▉▉▉▉ 0/1 — 00:00:00
  File "/<obfuscated>/pipenv/2018.11.26_2/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==2018.11.26', 'console_scripts', 'pipenv')()
  ...
  File "/<obfuscated>/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/project.py", line 901, in get_source
    raise SourceNotFound(name or url)
pipenv.project.SourceNotFound: 'http://<obfuscated>:8081/repository/pypi-all/simple/'
```

If I specify `PIP_NO_INDEX`, the result is similar – the venv will be successfully be created, but locking will fail because pip ignores pipenv's provided `--index-url`:

```
Installing 'six'▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:00
$ ['/<obfuscated>/.local/share/venvs/<obfuscated>/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-407mab56-requirements/pipenv-zos6wo2j-requirement.txt', '-i', 'http://<obfuscated>:8081/repository/pypi-all/simple/', '--trusted-host', '<obfuscated>', '--require-hashes']
Ignoring indexes: http://<obfuscated>:8081/repository/pypi-all/simple/
Created temporary directory: /tmp/pip-ephem-wheel-cache-xdb5_xri
Created temporary directory: /tmp/pip-req-tracker-jf5sh1f2
Created requirements tracker '/tmp/pip-req-tracker-jf5sh1f2'
Created temporary directory: /tmp/pip-install-l4gp54it
Collecting six==1.12.0 (from -r /tmp/pipenv-407mab56-requirements/pipenv-zos6wo2j-requirement.txt (line 1))
  0 location(s) to search for versions of six:
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-jf5sh1f2'
Exception information:
Traceback (most recent call last):
  File "/<obfuscated>/.local/share/venvs/<obfuscated>/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  ...
pip._internal.exceptions.DistributionNotFound: No matching distribution found for six==1.12.0 (from -r /tmp/pipenv-407mab56-requirements/pipenv-zos6wo2j-requirement.txt (line 1))
Traceback (most recent call last):
  File "/<obfuscated>/pipenv/2018.11.26_2/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==2018.11.26', 'console_scripts', 'pipenv')()
  ...
  File "/<obfuscated>/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
    raise exceptions.InstallError(c.dep.name, extra=err_lines)
```

For what it's worth, I manually removed any generated Pipfiles, and also my cache and user site package directories prior to running each command above

I've verified the following:
* `pip3 install --user six` works when I specify `--index-url`
* Pip has no custom configuration (e.g. `~/.config/pip/...`)
* No environment variables are set for either pip or pipenv (unless specified above)

I also came across https://pip.pypa.io/en/latest/reference/pip_install/#controlling-setup-requires, which seemed to be necessary in order for me to successfully install my local package with pip directly. This package specifies `setup_requires` in its `setup.py`. However, I can't tell if `~/.pydistutils.cfg` has any influence here.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/<obfuscated>/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/<obfuscated>/pipenv/2018.11.26_2/libexec/bin/python3.7'`

Python installations found:

  - `3.7.2`: `/<obfuscated>/bin/python3.7m`
  - `3.7.2`: `/<obfuscated>/bin/python3`
  - `2.7.16`: `/<obfuscated>/bin/python`
  - `2.6.6`: `/usr/bin/python2`
  - `2.6.6`: `/usr/bin/python2.6`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '2.6.32-754.10.1.el6.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Thu Nov 29 15:44:01 EST 2018',
 'python_full_version': '3.7.2',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

*Irrelevant variables have been removed.*

  - `USER`
  - `HOME`
  - `NO_PROXY`
  - `http_proxy`
  - `all_proxy`
  - `ALL_PROXY`
  - `HTTPS_PROXY`
  - `https_proxy`
  - `no_proxy`
  - `HTTP_PROXY`
  - `WORKON_HOME`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

**Comment by con-f-use** [comment]
How does your Pipfile look like?

For me something like this works:
```
[[source]]
name = "Company Index"
url = "http://10.10.100.1/root/devel/+simple"
verify_ssl = false

[packages]
requests = "*"
company_package = "7.2.4"
...
```

**Comment by matteius** [comment]
@adgoudz Please recheck behavior with `pipenv==2022.1.8` and let me know if I closed this in error.
