### ISSUE TITLE
Accessing venv from subdirectories

### ISSUE THREAD

**Issue by jimmyorourke** [pypa/pipenv#3668]
When I create a venv in a directory, I can access it (through any pipenv command) from that directory, from the directory below it, and from the directory 2 below it. When I go down 3 directories I run into `No virtualenv has been created for this project yet!`.
Is there any way to set how many directories up pipenv will search for a venv activation site?
`PIPENV_MAX_DEPTH` doesn't do it.
Or can someone point in the code to where it searches up 2 directories and no more? I can't seem to find that.

**Comment by frostming** [comment]
https://pipenv.readthedocs.io/en/latest/advanced/#pipenv.environments.PIPENV_MAX_DEPTH

**Comment by jimmyorourke** [comment]
@frostming 
>PIPENV_MAX_DEPTH doesn't do it.

**Comment by frostming** [comment]
@jimmyorourke Really? Please provide an example with steps to express the issue.

It is supposed to control this behavior and if not you can search it in the codebase to see if any bugs lying there.

**Comment by jimmyorourke** [comment]
hmmmm I  was putting together a toy example and I set and unset `PIPENV_VENV_IN_PROJECT` and then `PIPENV_MAX_DEPTH` started having the desired effect.
Doesn't make any sense but maybe my configuration got super bungled somehow. All is good.
