### ISSUE TITLE
check_github_ssh invoked for every test

### ISSUE THREAD

**Issue by jayvdb** [pypa/pipenv#3677]
As part of 2b90c89d1, `check_github_ssh()` was invoked in conftest fixture `isolate`.

```
 172   │ 2b90c89d1 tests/integration/conftest.py (Dan Ryan           2018-11-11 16:30:42 -0500 172)     global WE_HAVE_GITHUB_SSH_KEYS
 173   │ 2b90c89d1 tests/integration/conftest.py (Dan Ryan           2018-11-11 16:30:42 -0500 173)     WE_HAVE_GITHUB_SSH_KEYS = check_github_ssh()
 174   │ 4dac16765 tests/integration/conftest.py (Dan Ryan           2018-10-22 10:16:04 -0400 174)
 175   │ 4dac16765 tests/integration/conftest.py (Dan Ryan           2018-10-22 10:16:04 -0400 175)
 176   │ d069dff84 tests/integration/conftest.py (Dan Ryan           2018-10-27 21:46:11 -0400 176) WE_HAVE_INTERNET = check_internet()
 177   │ d069dff84 tests/integration/conftest.py (Dan Ryan           2018-10-27 21:46:11 -0400 177) WE_HAVE_GITHUB_SSH_KEYS = check_github_ssh()
```

The global was already being set once at module load.

I cant see how it is useful to re-run `check_github_ssh()` during the test suite, as it is checking something external to the test suite.

Fixing this is closely related to https://github.com/pypa/pipenv/pull/3669 , as the user needs to ctl-c the ssh password for every test because of that.

**Comment by jayvdb** [comment]
Ping @techalchemy in case you remember why you did this.

**Comment by techalchemy** [comment]
Sorry it's decidedly _not_ useful to run it for every test, nor is it actually doing that (or it wasn't) -- but by default we run tests with `pytest-xdist` and 8 worker processes so it does 8 independent checks, no idea how to get around that...


But also it shouldn't be necessary to get an authorization from the user for the test suite, is there an equivalent of `ssh-keyscan` in windows?

**Comment by jayvdb** [comment]
Ah, yes, pytest-xdist is a good reason.  I'll see if I can find a solution for that.  It is doing it btw, for every test operating under fixture `isolate`.  I usually operate without my keys available so I dont accidentally commit to master, so I see the passphase prompts at the beginning, and then for almost every integration test.  It is my itch ;-)
