### ISSUE TITLE
"Pipenv sync" on travis does not install version specified in pipfile.lock

### ISSUE THREAD

**Issue by ramusus** [pypa/pipenv#3678]
Hey, guys!

I see here https://travis-ci.org/cinemanio/backend/builds/509021532#L536 Django version 2.2 was installed, however in `Pipfile.lock` clearly specified version 2.1.7 https://github.com/cinemanio/backend/blob/master/Pipfile.lock#L141

Why is it so? 

It was working a few months ago. Now, if I rebuild previously successful builds they failed because of an inappropriate version of Django.

**Comment by arielnmz** [comment]
I see you're installing some vcs dependencies 

> 
>         "graphene-django": {
>             "editable": true,
>             "git": "https://github.com/graphql-python/graphene-django"
>         },

This is related:

https://github.com/pypa/pipenv/issues/3613

**Comment by matteius** [comment]
Can this be rechecked on `pipenv==2022.8.19`?
