### ISSUE TITLE
"a short animation of pipenv at work" does not exist

### ISSUE THREAD

**Issue by ryan-ccn** [pypa/pipenv#3681]
The GIF in [the pipenv documentation](https://pipenv.readthedocs.io/en/latest/) about pipenv at work does not work.

```xml
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>A5E6E724B6F514F3</RequestId>
<HostId>
U3ok1jWz/kpdNOruEE/34B/Uyhx9BA2OecWAtm7qm0lPu1c9/+nXd9O9Fgq7YSNfPtoEuBaJkZs=
</HostId>
</Error>
```
The s3 url is at [https://s3.amazonaws.com/media.kennethreitz.com/pipenv.gif](https://s3.amazonaws.com/media.kennethreitz.com/pipenv.gif).

**Comment by frostming** [comment]
Redirect to #3666 , close this one. Thanks.

**Comment by ryan-ccn** [comment]
Thanks guys
