### ISSUE TITLE
pipenv hangs only for one user, and when not in home directory

### ISSUE THREAD

**Issue by mtdeguzis** [pypa/pipenv#3683]
### Issue description

pipenv hangs only for one user, and when not in home directory

### Expected result

~/.local/bin/pipenv returns help function

### Actual result

Program hangs indefinitely.

### Steps to replicate

A few observations:
* ~/.local/bin/pipenv runs from the user home directory
* ~/.local/bin/pipenv does not run from /opt/jenkins/workspace/operations/database-creator/utilities
* Went through https://pipenv.readthedocs.io/en/latest/diagnose/
* https://fedoramagazine.org/getting-started-python-debugger/

Things tried so far:
* Reinstalled pipenv for my_user on gdchdpmn04prlx

Ran debugger from home directory:
```
[my_user@HOST ~]$ python2 -m pdb ~/.local/bin/pipenv
[my_user@HOST ~]$ python2 -m pdb ~/.local/bin/pipenv
> /home/my_user/.local/bin/pipenv(4)<module>()
-> import re
(Pdb) n
> /home/my_user/.local/bin/pipenv(5)<module>()
-> import sys
(Pdb) n
> /home/my_user/.local/bin/pipenv(7)<module>()
-> from pipenv import cli
(Pdb) n
> /home/my_user/.local/bin/pipenv(9)<module>()
-> if __name__ == '__main__':
(Pdb) n
> /home/my_user/.local/bin/pipenv(10)<module>()
-> sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
(Pdb) n
> /home/my_user/.local/bin/pipenv(11)<module>()
-> sys.exit(cli())
(Pdb) n
Usage: pipenv [OPTIONS] COMMAND [ARGS]...

Options:
  --where             Output project home information.
  --venv              Output virtualenv information.
```

From any other directory (even /tmp):
```
[my_user@HOST tmp]$ python2 -m pdb ~/.local/bin/pipenv
> /home/my_user/.local/bin/pipenv(4)<module>()
-> import re
(Pdb) n
> /home/my_user/.local/bin/pipenv(5)<module>()
-> import sys
(Pdb) 
> /home/my_user/.local/bin/pipenv(7)<module>()
-> from pipenv import cli
(Pdb) 
> /home/my_user/.local/bin/pipenv(9)<module>()
-> if __name__ == '__main__':
(Pdb) 
> /home/my_user/.local/bin/pipenv(10)<module>()
-> sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
(Pdb) 
> /home/my_user/.local/bin/pipenv(11)<module>()
-> sys.exit(cli())
(Pdb) 

<HANGS>
```

So the command exits on this sys call. When stepping through the sys.exit call instead of going by function, I see:
```
<TRUNCATED>

(Pdb) 
> /home/my_user/.local/lib/python2.7/site-packages/pipenv/core.py(97)<module>()
-> if PIPENV_COLORBLIND:
(Pdb) 
> /home/my_user/.local/lib/python2.7/site-packages/pipenv/core.py(101)<module>()
-> def which(command, location=None, allow_global=False):
(Pdb) 
> /home/my_user/.local/lib/python2.7/site-packages/pipenv/core.py(125)<module>()
-> project = Project(which=which)
(Pdb) 
```

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/my_user/.local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/bin/python2'`

Python installations found:

  - `2.7.5`: `/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '3.10.0-862.11.6.el7.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Fri Aug 10 16:55:11 UTC 2018',
 'python_full_version': '2.7.5',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `PYTHONDONTWRITEBYTECODE`
  - `LESSOPEN`
  - `LOGNAME`
  - `USER`
  - `QTDIR`
  - `PATH`
  - `LANG`
  - `TERM`
  - `SHELL`
  - `SHLVL`
  - `HISTSIZE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `SUDO_USER`
  - `HOME`
  - `USERNAME`
  - `SUDO_UID`
  - `QT_GRAPHICSSYSTEM_CHECKED`
  - `PIP_PYTHON_PATH`
  - `_`
  - `SUDO_COMMAND`
  - `SUDO_GID`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `OLDPWD`
  - `HOSTNAME`
  - `HISTCONTROL`
  - `PWD`
  - `PIP_SHIMS_BASE_MODULE`
  - `MAIL`
  - `LS_COLORS`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin:/home/my_user/.local/bin:/home/my_user/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/my_user`

---------------------------

Contents of `Pipfile` ('/home/my_user/Pipfile'):

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[dev-packages]



[packages]


```

</details>

**Comment by matteius** [comment]
@mtdeguzis Please recheck with latest version if this is still an issue.
