### ISSUE TITLE
`pipenv --two` throws AssertionError

### ISSUE THREAD

**Issue by rmeyer-taos** [pypa/pipenv#3685]
### Issue description

Using `pipenv` in a fresh docker image,
Built with 
```Dockerfile
FROM python:2.7

ENV PIPENV_VENV_IN_PROJECT=1

RUN pip install --upgrade pip --no-cache-dir
RUN pip install --upgrade pipenv

ENTRYPOINT ["pipenv"]
```

Execution of `pipenv --two` or `pipenv --python=/usr/bin/python2.7` fails to complete.
Stack trace provided in `Actual result`

### Expected result

Pipenv to complete without errors and provide a path to the new Python2.7 environment.

### Actual result
```
Creating a virtualenv for this project...
Pipfile: /Pipfile
Using /usr/local/bin/python (2.7.16) to create virtualenv...
⠦ Creating virtual environment...Already using interpreter /usr/local/bin/python
New python executable in /root/.local/share/virtualenvs/-x-v5uFv0/bin/python
Installing setuptools, pip, wheel...
done.

✔ Successfully created virtual environment!
Virtualenv location: /root/.local/share/virtualenvs/-x-v5uFv0
Creating a Pipfile for this project...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli/command.py", line 208, in cli
    clear=state.clear,
  File "/usr/local/lib/python2.7/site-packages/pipenv/core.py", line 609, in ensure_project
    validate=validate, skip_requirements=skip_requirements, system=system
  File "/usr/local/lib/python2.7/site-packages/pipenv/core.py", line 320, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/usr/local/lib/python2.7/site-packages/pipenv/project.py", line 697, in create_pipfile
    config_parser = ConfigOptionParser(name=self.name)
  File "/usr/local/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/cli/parser.py", line 142, in __init__
    assert self.name
AssertionError
```

#### Manual Steps
```
docker --version                                                          
Docker version 18.09.4, build d14af54266
```

- Install docker
- Create Docker file with 
```Dockerfile
FROM python:2.7

ENV PIPENV_VENV_IN_PROJECT=1

RUN pip install --upgrade pip --no-cache-dir
RUN pip install --upgrade pipenv

ENTRYPOINT ["pipenv"]
```
- `docker build . --tag=python2-pipenv`
- `docker run python2-pipenv install --two`
- :boom: 

#### Automaed Failure
```
docker --version                                                          
Docker version 18.09.4, build d14af54266
```

- Install docker
- Create Docker file with 
```Dockerfile
FROM python:2.7

ENV PIPENV_VENV_IN_PROJECT=1

RUN pip install --upgrade pip --no-cache-dir

RUN pip install pipenv --no-cache-dir
RUN pipenv install --two
RUN pipenv shell

ENTRYPOINT ["pipenv"]
```
- `docker build . --tag=python2-pipenv`

### Additional information about approaches

- No Pipfile is required to get this error
- I have tried with and without setting `PIPENV_VENV_IN_PROJECT`
- I have tried using `--no-cache-dir` on *all* commands
- I have tried using `--no-cache-dir` on *none of* commands
- I have tried `pipenv --python=/usr/bin/python2.7`
- I have tried `pipenv --python=/usr/bin/python` < System Python 2>

### Pipenv Support
-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Python installations found:

  - `3.5.3`: `/usr/bin/python3.5`
  - `3.5.3`: `/usr/bin/python3.5m`
  - `2.7.16`: `/usr/local/bin/python2.7`
  - `2.7.13`: `/usr/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-46-generic',
 'platform_system': 'Linux',
 'platform_version': '#49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019',
 'python_full_version': '2.7.16',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `LANG`
  - `PYTHONIOENCODING`
  - `GPG_KEY`
  - `PYTHON_VERSION`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHON_PIP_VERSION`
  - `HOSTNAME`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `HOME`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `PATH`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`

---------------------------

**Comment by frostming** [comment]
@rmeyer-taos Please do not initialize Pipenv under `/` directory, and if you are using master branch there will be a friendly message to tell you to do so.

**Comment by rmeyer-taos** [comment]
@frostming 

Thanks for the response. Setting `WORKDIR` in the Dockerfile sorted this out. 

Working Dockerfile for anyone that comes across this issue. 

```Dockerfile
FROM python:2.7

ENV PIPENV_VENV_IN_PROJECT=1

WORKDIR "/workspace"

RUN pip install pipenv --no-cache-dir
RUN pipenv install --two

```
