### ISSUE TITLE
Command to list [scripts] entries

### ISSUE THREAD

**Issue by uranusjr** [pypa/pipenv#3686]
### Is your feature request related to a problem? Please describe.

I sometimes would start typing `pipenv run` and cannot recall what the command I want is named (`release`? `push`? ehh…), and have to ^U and `cat <path to Pipfile>` and look for the `[scripts]` section. It’d be very helpful if I could quickly do this inside my terminal.

### Describe the solution you'd like

Something like

```console
$ pipenv list-scripts
release     python release
test        pytest
format      black src tests
```

**Comment by techalchemy** [comment]
`list-scripts` is a bit verbose, my first instinct was `pipenv scripts` -- thoughts? Either way it seems odd to add a full command for just this -- would we want other functionality with it?

Invoke uses `--list` as well, we can consider `pipenv run --list` as an option (but I don't particularly like it)

**Comment by uranusjr** [comment]
I don’t really have any preferences, all of the mentioned options would work fine for me.

**Comment by brendanator** [comment]
I think this should be rolled into the `pipenv run` command when no command is provided.
When I run `npm run` with no arguments I get:
```
Lifecycle scripts included in example-project:
  start
    npm run develop
  test
    echo "Write tests! -> https://gatsby.dev/unit-testing"

available via `npm run-script`:
  build
    gatsby build
  clean
    gatsby clean
  develop
    gatsby develop
```
I assume this would no longer need a PEEP

As an additional point I think `pipenv run script_command` should print out the command it is running. npm does this and it is useful, especially when passing additional parameters

**Comment by GlenRSmith** [comment]
A quick hack to accomplish this:

Install pipenv as a dev requirement:

>pipenv install -d pipenv

Add a `script` to your Pipfile:

```
[scripts]
list = "./pipenv_list_scripts.py"
```

Add `pipenv_list_scripts.py`:

```
#!/usr/bin/env python
"""
Utility to allow pipenv command listing `scripts` from Pipfile
"""
try:
    import pipenv.core
except ModuleNotFoundError:
    print("This script is only for use in a development environment")
    exit(1)


def main():
    proj = pipenv.core.project
    if not proj:
        print("project not found")
        exit(1)
    scripts = proj.parsed_pipfile.get('scripts', [])
    print("command\tscript")
    for k, v in scripts.items():
        print(f"{k}\t{v}")
    return


if __name__ == '__main__':
    main()
```

**Comment by uranusjr** [comment]
@GlenRSmith Rewrite that to be invoked as `pipenv script` and submit a PR, and I’ll approve it 🙂

**Comment by GlenRSmith** [comment]
@uranusjr Thanks, done. LMK if you have any feedback.
