### ISSUE TITLE
pipenv --py crashes

### ISSUE THREAD

**Issue by dlech** [pypa/pipenv#3694]
### Issue description

Running `pipenv --py` in a project with no venv setup crashes.

### Expected result

No stack trace, just an error message.

### Actual result

```
$ pipenv --py
Traceback (most recent call last):
  File "/home/david/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/david/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/david/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/david/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/david/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/david/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/david/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/david/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/david/.local/lib/python3.6/site-packages/pipenv/cli/command.py", line 140, in cli
    do_py()
  File "/home/david/.local/lib/python3.6/site-packages/pipenv/core.py", line 1635, in do_py
    click.echo(which("python", allow_global=system))
  File "/home/david/.local/lib/python3.6/site-packages/pipenv/core.py", line 108, in which
    raise RuntimeError("location not created nor specified")
RuntimeError: location not created nor specified
```

### Steps to replicate

Using Ubuntu 18.04:
```
sudo apt update
sudo apt install python3-pip
pip3 install pipenv  # --user is implied so pipenv executable gets installed in /home/$USER/.local/bin/
git clone https://github.com/dlech/vscode-python-issue4866.git
cd vscode-python-issue4866
pipenv --py
```

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. 
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/david/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.6.7`: `/usr/bin/python3`
  - `3.6.7`: `/usr/bin/python3.6m`
  - `2.7.15rc1`: `/usr/bin/python2`
  - `2.7.1`: `/usr/bin/jython`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.18.0-16-generic',
 'platform_system': 'Linux',
 'platform_version': '#17~18.04.1-Ubuntu SMP Tue Feb 12 13:35:51 UTC 2019',
 'python_full_version': '3.6.7',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `CLUTTER_IM_MODULE`
  - `NVM_DIR`
  - `LS_COLORS`
  - `LESSCLOSE`
  - `XDG_MENU_PREFIX`
  - `LANG`
  - `DISPLAY`
  - `GTK2_MODULES`
  - `DEBFULLNAME`
  - `GTK_CSD`
  - `NVM_CD_FLAGS`
  - `USERNAME`
  - `CHROME_DESKTOP`
  - `NO_AT_BRIDGE`
  - `XDG_VTNR`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `SSH_AUTH_SOCK`
  - `PRU_C_DIR`
  - `MANDATORY_PATH`
  - `XDG_SESSION_ID`
  - `USER`
  - `DESKTOP_SESSION`
  - `RBENV_SHELL`
  - `QT4_IM_MODULE`
  - `GOPATH`
  - `TEXTDOMAINDIR`
  - `DROPBOX_USE_LIBAPPINDICATOR`
  - `DEFAULTS_PATH`
  - `QT_QPA_PLATFORMTHEME`
  - `PWD`
  - `HOME`
  - `TEXTDOMAIN`
  - `SSH_AGENT_PID`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `QT_ACCESSIBILITY`
  - `LIBVIRT_DEFAULT_URI`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `GSETTINGS_SCHEMA_DIR`
  - `XDG_SESSION_DESKTOP`
  - `GTK_MODULES`
  - `WINDOWPATH`
  - `TERM`
  - `SHELL`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `IM_CONFIG_PHASE`
  - `NVM_BIN`
  - `XDG_CURRENT_DESKTOP`
  - `GPG_AGENT_INFO`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `XDG_SEAT`
  - `SHLVL`
  - `DEBEMAIL`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `XDG_CONFIG_DIRS`
  - `PATH`
  - `RBENV_VERSION`
  - `SESSION_MANAGER`
  - `LESSOPEN`
  - `GTK_IM_MODULE`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/david/.nvm/versions/node/v10.15.3/bin:/home/david/work/gocode/bin:/home/david/.rbenv/shims:/home/david/bin:/home/david/work/gocode/bin:/home/david/.rbenv/shims:/home/david/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/david/.dotnet/tools:/home/david/.dotnet/tools`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/david/work/junk/vscode-python-issue4866`

---------------------------

Contents of `Pipfile` ('/home/david/work/junk/vscode-python-issue4866/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/home/david/work/junk/vscode-python-issue4866/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "415dfdcb118dd9bdfef17671cb7dcd78dbd69b6ae7d4f39e8b44e71d60ca72e7"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

**Comment by frostming** [comment]
Yes the message `RuntimeError: location not created nor specified` tells what is happening, do you want to improve the message? Welcome

**Comment by dlech** [comment]
It seems that most errors result in a stack trace being printed, so I guess this is normal for pipenv.

**Comment by Cologler** [comment]
@frostming 

maybe `pipenv --venv` and `pipenv --py` should have the same style:

![image](https://user-images.githubusercontent.com/10906962/58013806-012bc780-7b2a-11e9-8a32-239429c4a17b.png)

**Comment by frostming** [comment]
It makes sense to me. Feel free to shoot a PR.
