### ISSUE TITLE
Issues accessing old Django web project

### ISSUE THREAD

**Issue by Theyoungkai** [pypa/pipenv#3695]
(Rebl) kais-MacBook-Air:Rebl kaitopaloglu$ python
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /Users/kaitopaloglu/.local/share/virtualenvs/Rebl-CyPlfddz/bin/python
  Reason: image not found
Abort trap: 6

Whenever i try to do anything python related or launch to heroku the message above always pops up on my terminal. I've done a bit of digging beforehand and a lot of people mentioned that something could be wrong with homebrew. Not completely sure though.Thanks!

**Comment by frostming** [comment]
Yeah, when you upgrade your Python the old venv using the python interpreter becomes stale and can't be accessed anymore, which is a drawback of tools backed byy virtualenv.

You can fix this by refreshing the venv with following commands:
```bash
$ pipenv --python python install --deploy
```
Close this for now, reopen if it doesn't fix things.
