### ISSUE TITLE
How to disable auto `pipenv install` on `pipenv shell`

### ISSUE THREAD

**Issue by qcho** [pypa/pipenv#3697]
Whenever I run `pipenv shell` from outside the root directory of the proyect it procedes to create a `Pipfile`.

Also `pipenv install` should be just install not `init` too.

"Inspiring projects" like `npm` and `composer` work like that.
`XXX init` creates the Pipfile+Piplock
`XXX install` install via Piplock

-------------------------------------------------------------------------------

```
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.7'`

Python installations found:

  - `3.7.3`: `/usr/local/bin/python3`
  - `3.7.3`: `/usr/local/bin/python3.7m`
  - `2.7.16`: `/usr/local/bin/python`
  - `2.7.16`: `/usr/local/bin/pythonw`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT '
                     '2019; root:xnu-4903.251.3~3/RELEASE_X86_64',
 'python_full_version': '3.7.3',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_SESSION_ID`
  - `SSH_AUTH_SOCK`
  - `Apple_PubSub_Socket_Render`
  - `COLORFGBG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `PWD`
  - `SHELL`
  - `SECURITYSESSIONID`
  - `TERM_PROGRAM_VERSION`
  - `TERM_PROGRAM`
  - `PATH`
  - `COLORTERM`
  - `COMMAND_MODE`
  - `TERM`
  - `HOME`
  - `TMPDIR`
  - `USER`
  - `XPC_SERVICE_NAME`
  - `LOGNAME`
  - `__CF_USER_TEXT_ENCODING`
  - `ITERM_SESSION_ID`
  - `SHLVL`
  - `OLDPWD`
  - `LANG`
  - `SDKMAN_DIR`
  - `SDKMAN_PLATFORM`
  - `SDKMAN_VERSION`
  - `SDKMAN_CANDIDATES_API`
  - `SDKMAN_CANDIDATES_DIR`
  - `GRADLE_HOME`
  - `JAVA_HOME`
  - `ZPLUG_ROOT`
  - `PERIOD`
  - `FPATH`
  - `ZPLUG_HOME`
  - `ZPLUG_THREADS`
  - `ZPLUG_PROTOCOL`
  - `ZPLUG_FILTER`
  - `ZPLUG_LOADFILE`
  - `ZPLUG_USE_CACHE`
  - `ZPLUG_ERROR_LOG`
  - `ZPLUG_LOG_LOAD_SUCCESS`
  - `ZPLUG_LOG_LOAD_FAILURE`
  - `ZPLUG_BIN`
  - `ZPLUG_CACHE_DIR`
  - `ZPLUG_REPOS`
  - `_ZPLUG_VERSION`
  - `_ZPLUG_URL`
  - `_ZPLUG_OHMYZSH`
  - `_ZPLUG_PREZTO`
  - `_ZPLUG_AWKPATH`
  - `_ZPLUG_CONFIG_SUBSHELL`
  - `HISTFILE`
  - `SAVEHIST`
  - `HISTSIZE`
  - `LC_ALL`
  - `LC_CTYPE`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:


Debug–specific environment variables:

  - `PATH`: `/Users/qcho/.zplug/bin:/Users/qcho/.sdkman/candidates/java/current/bin:/Users/qcho/.sdkman/candidates/gradle/current/bin:/Applications/MongoDB.app/Contents/Resources/Vendor/mongodb/bin:/Applications/Redis.app/Contents/Resources/Vendor/redis/bin:/Users/qcho/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
  - `SHELL`: `/usr/local/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/qcho`


---------------------------

</details>

```

**Comment by frostming** [comment]
No, `pipenv install` requires Pipfile to be present since there is no separate `init` command for now. In the other hand, `pipenv sync` only respects `Pipfile.lock` and should not touch Pipfile(which is supposed to work like so on the master branch.)

For `pipenv shell` I am not sure if it creates a Pipfile, it is desired to create a new virtualenv, install from Pipfile.lock and activate the venv.

**Comment by qcho** [comment]
@frostming 

On the first question. **For sure** `pipenv shell` is creating a Pipfile with this default content (in my env):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "3.7"
```
It's easy to check.

On the second question It's funny how you put it. `pipenv install` requires a Pipfile. We agree on that. 

Whats odd about these two commands is that requirement does imply remediation by default. It's really worst in the `shell` command where you would *never* expect creation of the Pipfile. On the `install` one, imho it's a bad idea too but since it's not `init` yet... wel... you get away with it ^_^

**Comment by frostming** [comment]
`shell` command, together with many others including `run`, `check`, ensures a virtualenv to be created when it runs, instead of exit with an error. It also allows options like `--python`, `--two/--three` to control the creation of virtualenv. Pipenv is designed as such to make users not worry about whether a virtualenv is created or not, and don't need to run a separate `init` command.

Close it for now.

**Comment by abaldwin88** [comment]
This behavior trips me up regularly. My preference would to to raise an error rather than create a Pipfile. Here's my workaround:

```
# ~/.zshrc

pipenv()
{
  if [ -f "Pipfile" ]; then
    command pipenv "$@"
  else
    echo "Exiting. Pipfile does not exist."
  fi
}
```
