### ISSUE TITLE
install PyQt5 fail on Raspberry

### ISSUE THREAD

**Issue by leileigong** [pypa/pipenv#3698]
on my Raspberry 3B device + python3.6.
**install PyQt5 fail!**

> pipenv install
> Installing dependencies from Pipfile.lock (e9db47)...
> An error occurred while installing pyqt5==5.11.3 --hash=sha256:517e4339135c4874b799af0d484bc2e8c27b54850113a68eec40a0b56534f450 --hash=sha256:ac1eb5a114b6e7788e8be378be41c5e54b17d5158994504e85e43b5fca006a39 --hash=sha256:d2309296a5a79d0a1c0e6c387c30f0398b65523a6dcc8a19cc172e46b949e00d --hash=sha256:e85936bae1581bcb908847d2038e5b34237a5e6acc03130099a78930770e7ead! Will try again.
> Ignoring pyqt5-tools: markers 'sys_platform == "win32"' don't match your environment
> An error occurred while installing pyqt5-sip==4.19.15 --hash=sha256:0aed4266e52f4d11947439d9df8c57d4578e92258ad0d70645f9f69b627b35c7 --hash=sha256:15750a4a3718c68ba662eede7310612aedad70c9727497908bf2eeddd255d16f --hash=sha256:2071265b7a603354b624b6cfae4ea032719e341799fb925961fd192f328fd203 --hash=sha256:31a59f76168df007b480b9382256c20f8898c642e1394df2990559f0f6389f66 --hash=sha256:39ce455bf5be5c1b20db10d840a536f70c3454be3baa7adca22f67ed90507853 --hash=sha256:5d8a4b8e75fa6c9f837ea92793f1aeacbf3929f1d11cdf36f9604c1876182aca --hash=sha256:6bf9bacac776257390dd3f8a703d12c8228e4eb1aa0b191f1550965f44e4c23a --hash=sha256:87a76841e07e6dae5df34dded427708b5ea8d605c017e0bb6e56a7354959271e --hash=sha256:9f0ad4198f2657da9d59a393c266959362c517445cace842051e5ad564fa8fb0 --hash=sha256:cbb0f24e3bfa1403bf3a05f30066d4457509aa411d6c6823d02b0508b787b8ea --hash=sha256:d38d379fa4f5c86a8ea92b8fab42748f37de093d21a25c34b2339eb2764ee5d5 --hash=sha256:f24413d34707525a0fe1448b9574089242b9baa7c604ae5714abef9ad1749839! Will try again.
>   🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 13/13 — 00:00:18
> Installing initially failed dependencies...
>   ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:08
> [pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/cli/command.py", line 254, in install
> [pipenv.exceptions.InstallError]:       editable_packages=state.installstate.editables,
> [pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 1874, in do_install
> [pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
> [pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 1253, in do_init
> [pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
> [pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 862, in do_install_dependencies
> [pipenv.exceptions.InstallError]:       _cleanup_procs(procs, False, failed_deps_queue, retry=False)
> [pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 681, in _cleanup_procs
> [pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
> [pipenv.exceptions.InstallError]: ['Collecting pyqt5==5.11.3 (from -r /tmp/pipenv-0Ir6wG-requirements/pipenv-KX0Vb9-requirement.txt (line 1))']
> [pipenv.exceptions.InstallError]: ['Could not find a version that satisfies the requirement pyqt5==5.11.3 (from -r /tmp/pipenv-0Ir6wG-requirements/pipenv-KX0Vb9-requirement.txt (line 1)) (from versions: )', 'No matching distribution found for pyqt5==5.11.3 (from -r /tmp/pipenv-0Ir6wG-requirements/pipenv-KX0Vb9-requirement.txt (line 1))']
> ERROR: ERROR: Package installation failed...
> 

Here is my Pipfile content:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"pyqt5" = "*"
pyusb = "*"
pycryptodome = {version = "==3.8.0",markers = "python_version >= '2.6' and python_version != '3.0'and python_version != '3.1' and python_version != '3.2' and python_version != '3.3'"}
pycryptodomex = {version = "==3.8.0",markers = "python_version >= '2.6' and python_version != '3.0'and python_version != '3.1' and python_version != '3.2' and python_version != '3.3'"}
#pycrypto = {version = "*",sys_platform = "!= 'win32'"}
#pycrypto-cp27-win32 = {path = "./tools/pycrypto-2.6.1-cp27-cp27m-win32.whl", markers = "python_version == '2.7'", sys_platform = "== 'win32'"}
#pycrypto-cp36-win32 = {path = "./tools/pycrypto-2.6.1-cp36-cp36m-win_amd64.whl", markers = "python_version == '3.6'", sys_platform = "== 'win32'"}
#"2753c28" = {path = "./tools/pyinstaller_7817d3facd34.zip"}
pyinstaller = {version = "*",markers = """python_version >= '2.7' and python_version != '3.0'and python_version != '3.1' and python_version != '3.2' and python_version != '3.3'"""}
pyqt5-tools = {version = "*",sys_platform = "== 'win32'" }

[dev-packages]

[requires]
python_version = "3.6"

```

**Comment by frostming** [comment]
I am not familiar with RasberryPi builds but I think it can't find a compatible wheel from PyPI since it doesn't provide a source tarball for you.
https://pypi.org/project/PyQt5/5.11.3/#files

Also, please confirm that `pip` can install on your machine.

**Comment by leileigong** [comment]
i use `pip
` install PyQt5, but fail too.
```
pi@raspberrypi:~/test$ pip install PyQt5
Collecting PyQt5
  Could not find a version that satisfies the requirement PyQt5 (from versions: )
No matching distribution found for PyQt5
```

Maybe i need to compile PyQt5 source on Raspberry myself.

**Comment by frostming** [comment]
Close this one sine it is not related to Pipenv
