### ISSUE TITLE
Not able to create a virtual environment using pipenv - 

### ISSUE THREAD

**Issue by KaleAM30** [pypa/pipenv#3710]
Dear Team ,

I am new to python virtual environment, While creating a virtual environment i was having one error

"pipenv install --python=python3.7 --skip-lock --dev"

:: Output ->

loading virtual environment veriables
Creating a virtual environment for this project
Using path/to/python3.7 (3.7.0) to create virtualenv...
Creating virtual environment... Already using interpreter path/to/python3.7

New python executable in /home/user/.local/share/myproject/bin/python3.7
Not overwriting existing python script /home/user/.local/share/myproject/bin/python (you must use /home/user/.local/share/myproject/bin/python3.7)
failed to create a virtual environment.

can you please help here

**Comment by KaleAM30** [comment]
Hi Team, 

Any help ? Please

**Comment by frostming** [comment]
@KaleAM30 See this line
> Not overwriting existing python script /home/user/.local/share/myproject/bin/python (you must use /home/user/.local/share/myproject/bin/python3.7)

Do you have a python ready in that location? Remove it and retry.

**Comment by techalchemy** [comment]
or try `pipenv --rm` first

either way it seems like there is already an environment, the error is just that you already have an environment so the command isn't going to create one and overwrite the existing one.

If you want to remove the existing environment you will need to tell pipenv to remove it using `pipenv --rm`.

This usually means you already ran `pipenv install` from this location in the past and have set up a project.  I am going to close this issue for now, but feel free to reach out if you continue to have any issues.  Thanks for using pipenv and thanks for reporting the problem!
