### ISSUE TITLE
Pipenv shell command drops into "$bash 3.2" on mac

### ISSUE THREAD

**Issue by aidataguy** [pypa/pipenv#3717]
### Issue description

I am using mac Mojave, with pipenv  it's a clean install. I am running python version 3.7.3 and pipenv version: pipenv, version 2018.11.26. If I create a new Pipenv environment it keeps dropping to (personalblog) bash-3.2$  instead of staying in actual shell. I always get this 

### Expected result

The pipenv shall show the prompt something like this : 
(personalblog)Himanshus-MacBook-Pro:personalblog himanshupatel

### Actual result

I always get something like:

Launching subshell in virtual environment…
bash-3.2$  . /Users/himanshupatel/personalblog/.venv/bin/activate
(personalblog) bash-3.2$

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

create the pipenv environment with pipenv --python 3.7
-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.11.26_2/libexec/bin/python3.7'`

Python installations found:

  - `3.7.3`: `/Users/himanshupatel/personalblog/.venv/bin/python3`
  - `3.7.3`: `/usr/local/bin/python3`
  - `3.7.3`: `/usr/local/bin/python3.7m`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT '
                     '2019; root:xnu-4903.251.3~3/RELEASE_X86_64',
 'python_full_version': '3.7.3',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `LDFLAGS`
  - `SSH_AGENT_PID`
  - `TERM_PROGRAM`
  - `TERM`
  - `SHELL`
  - `PIP_PYTHON_PATH`
  - `TMPDIR`
  - `CPPFLAGS`
  - `PIPENV_VENV_IN_PROJECT`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `LC_ALL`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `VIRTUAL_ENV`
  - `PIPENV_ACTIVE`
  - `_`
  - `PWD`
  - `LANG`
  - `XPC_FLAGS`
  - `PYTHONDONTWRITEBYTECODE`
  - `XPC_SERVICE_NAME`
  - `HOME`
  - `SHLVL`
  - `LOGNAME`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `LC_CTYPE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `enabled`
 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.11.26_2/libexec/tools:/Users/himanshupatel/personalblog/.venv/bin:/usr/local/Cellar/pipenv/2018.11.26_2/libexec/tools:/usr/local/opt/ruby/bin:/usr/local/opt/ruby/bin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/himanshupatel/personalblog`
  - `VIRTUAL_ENV`: `/Users/himanshupatel/personalblog/.venv`

---------------------------

Contents of `Pipfile` ('/Users/himanshupatel/personalblog/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
django-filebrowser-no-grappelli = "==3.7.7"
django-grappelli = "==2.12.2"
django-tinymce4-lite = "==1.7.4"
jsmin = "==2.2.2"
mysqlclient = "==1.4.2.post1"
pytz = "==2018.9"
Django = "==2.1.7"
Pillow = "==5.4.1"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/Users/himanshupatel/personalblog/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "130b84aaa5f6c1cc3888f0bea3576c30457b0f2c3ed87f17c120060136111c76"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "django": {
            "hashes": [
                "sha256:275bec66fd2588dd517ada59b8bfb23d4a9abc5a362349139ddda3c7ff6f5ade",
                "sha256:939652e9d34d7d53d74d5d8ef82a19e5f8bb2de75618f7e5360691b6e9667963"
            ],
            "index": "pypi",
            "version": "==2.1.7"
        },
        "django-filebrowser-no-grappelli": {
            "hashes": [
                "sha256:651867fe49e3b4bf835ece8ee2d02f43f9fc2092163fcf348e5b01e07b7615f3",
                "sha256:6da51dc7eadd664cdbb4837cad9b14071f253e9244600990702ff26004d6addc"
            ],
            "index": "pypi",
            "version": "==3.7.7"
        },
        "django-grappelli": {
            "hashes": [
                "sha256:c4a98416c41eecaff99e104c18d8d71717305b8466b5de40d3c80d734a9297fb"
            ],
            "index": "pypi",
            "version": "==2.12.2"
        },
        "django-tinymce4-lite": {
            "hashes": [
                "sha256:90bef25a20f43b57040ad631605de3bcccccc7ac760c42640edbf459062af8d2",
                "sha256:cf4a41abc704e56515eb48d9d8fd3c56ceeb9705419bdff2b8a375e2131524f8"
            ],
            "index": "pypi",
            "version": "==1.7.4"
        },
        "jsmin": {
            "hashes": [
                "sha256:b6df99b2cd1c75d9d342e4335b535789b8da9107ec748212706ef7bbe5c2553b"
            ],
            "index": "pypi",
            "version": "==2.2.2"
        },
        "mysqlclient": {
            "hashes": [
                "sha256:425e733b05e359a714d6007c0fc44582be66b63e5a3df0a50949274ae16f4bc6",
                "sha256:62e4770b6a797b9416bcf70488365b7d6b9c9066878108499c559293bb464380",
                "sha256:f257d250f2675d0ef99bd318906f3cfc05cef4a2f385ea695ff32a3f04b9f9a7"
            ],
            "index": "pypi",
            "version": "==1.4.2.post1"
        },
        "pillow": {
            "hashes": [
                "sha256:051de330a06c99d6f84bcf582960487835bcae3fc99365185dc2d4f65a390c0e",
                "sha256:0ae5289948c5e0a16574750021bd8be921c27d4e3527800dc9c2c1d2abc81bf7",
                "sha256:0b1efce03619cdbf8bcc61cfae81fcda59249a469f31c6735ea59badd4a6f58a",
                "sha256:163136e09bd1d6c6c6026b0a662976e86c58b932b964f255ff384ecc8c3cefa3",
                "sha256:18e912a6ccddf28defa196bd2021fe33600cbe5da1aa2f2e2c6df15f720b73d1",
                "sha256:24ec3dea52339a610d34401d2d53d0fb3c7fd08e34b20c95d2ad3973193591f1",
                "sha256:267f8e4c0a1d7e36e97c6a604f5b03ef58e2b81c1becb4fccecddcb37e063cc7",
                "sha256:3273a28734175feebbe4d0a4cde04d4ed20f620b9b506d26f44379d3c72304e1",
                "sha256:4c678e23006798fc8b6f4cef2eaad267d53ff4c1779bd1af8725cc11b72a63f3",
                "sha256:4d4bc2e6bb6861103ea4655d6b6f67af8e5336e7216e20fff3e18ffa95d7a055",
                "sha256:505738076350a337c1740a31646e1de09a164c62c07db3b996abdc0f9d2e50cf",
                "sha256:5233664eadfa342c639b9b9977190d64ad7aca4edc51a966394d7e08e7f38a9f",
                "sha256:5d95cb9f6cced2628f3e4de7e795e98b2659dfcc7176ab4a01a8b48c2c2f488f",
                "sha256:7eda4c737637af74bac4b23aa82ea6fbb19002552be85f0b89bc27e3a762d239",
                "sha256:801ddaa69659b36abf4694fed5aa9f61d1ecf2daaa6c92541bbbbb775d97b9fe",
                "sha256:825aa6d222ce2c2b90d34a0ea31914e141a85edefc07e17342f1d2fdf121c07c",
                "sha256:9c215442ff8249d41ff58700e91ef61d74f47dfd431a50253e1a1ca9436b0697",
                "sha256:a3d90022f2202bbb14da991f26ca7a30b7e4c62bf0f8bf9825603b22d7e87494",
                "sha256:a631fd36a9823638fe700d9225f9698fb59d049c942d322d4c09544dc2115356",
                "sha256:a6523a23a205be0fe664b6b8747a5c86d55da960d9586db039eec9f5c269c0e6",
                "sha256:a756ecf9f4b9b3ed49a680a649af45a8767ad038de39e6c030919c2f443eb000",
                "sha256:b117287a5bdc81f1bac891187275ec7e829e961b8032c9e5ff38b70fd036c78f",
                "sha256:ba04f57d1715ca5ff74bb7f8a818bf929a204b3b3c2c2826d1e1cc3b1c13398c",
                "sha256:cd878195166723f30865e05d87cbaf9421614501a4bd48792c5ed28f90fd36ca",
                "sha256:cee815cc62d136e96cf76771b9d3eb58e0777ec18ea50de5cfcede8a7c429aa8",
                "sha256:d1722b7aa4b40cf93ac3c80d3edd48bf93b9208241d166a14ad8e7a20ee1d4f3",
                "sha256:d7c1c06246b05529f9984435fc4fa5a545ea26606e7f450bdbe00c153f5aeaad",
                "sha256:e9c8066249c040efdda84793a2a669076f92a301ceabe69202446abb4c5c5ef9",
                "sha256:f227d7e574d050ff3996049e086e1f18c7bd2d067ef24131e50a1d3fe5831fbc",
                "sha256:fc9a12aad714af36cf3ad0275a96a733526571e52710319855628f476dcb144e"
            ],
            "index": "pypi",
            "version": "==5.4.1"
        },
        "pytz": {
            "hashes": [
                "sha256:32b0891edff07e28efe91284ed9c31e123d84bea3fd98e1f72be2508f43ef8d9",
                "sha256:d5f05e487007e29e03409f9398d074e158d920d36eb82eaf66fb1136b0c5374c"
            ],
            "index": "pypi",
            "version": "==2018.9"
        }
    },
    "develop": {}
}

```
</details>

**Comment by thedesignable** [comment]
To add, when i manually activate the environment with like :
Himanshus-MacBook-Pro:personalblog himanshupatel$ source .venv/bin/activate

 and then deactivate it and run pipenv shell I get the expected result like this: 

(personalblog) Himanshus-MacBook-Pro:personalblog himanshupatel$ 

It seems like there is a problem with the way it's activating the environment.

My ~/.bash_profile looks like this:

export PATH="/usr/local/opt/ruby/bin:/Users/himanshupatel/Library/Python/3.7/bin:$PATH"
export CPPFLAGS="-I/usr/local/opt/ruby/include"
export LDFLAGS="-I/usr/local/opt/ruby/include"
alias python='python3'

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export PIPENV_VENV_IN_PROJECT="enabled"
