### ISSUE TITLE
How to keep requirements.txt always updated automatically 

### ISSUE THREAD

**Issue by joseph-vedadi** [pypa/pipenv#3723]
I know it is easy to generate requirements.txt from Pipfile.

How am I supposed to keep it updated each time and I install a new package or update the existing one **AUTOMATICALLY**? 
Thanks,

**Comment by jxltom** [comment]
Maybe you could use a pre-commit hook such as by https://pre-commit.com/

**Comment by techalchemy** [comment]
`pipenv lock -r` outputs to requirements.txt but how you generate that is outside of the scope of what pipenv does.  I could see something like this landing in a plugin system someday, but I am not sure when we would implement that.

Thanks for the report, sorry we can't be of more help!
