### ISSUE TITLE
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\\AppData\Local\Temp\pip-install-00z7sx8r\matplotlib\

### ISSUE THREAD

**Issue by davidy96** [pypa/pipenv#3725]
I'm trying to download qstrader through the terminal, but when I type that code 
`pip install -r https://raw.githubusercontent.com/mhallsmoore/qstrader/master/requirements.txt`
I encounter the egg_info error. Could anyone else help?

**Comment by mahmoudhossam** [comment]
This probably failed while building matplotlib, this is not a bug in pipenv.

I think [this stackoverflow question](https://stackoverflow.com/q/8057801/165103) has the solution to your problem.

**Comment by frostming** [comment]
Thanks @mahmoudhossam
