### ISSUE TITLE
Broken link in bug report template

### ISSUE THREAD

**Issue by ppo** [pypa/pipenv#3727]
The link "diagnose documentation" to https://docs.pipenv.org/diagnose/ is not working.
Found in [.github/ISSUE_TEMPLATE/Bug_report.md](https://github.com/pypa/pipenv/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)

The doc seems to exist in [docs/diagnose.rst](https://github.com/pypa/pipenv/blob/master/docs/diagnose.rst)

**Comment by techalchemy** [comment]
thanks for the report and the pr!

**Comment by frostming** [comment]
Closed via #3728
