### ISSUE TITLE
求代理功能啊

### ISSUE THREAD

**Issue by kong5664546498** [pypa/pipenv#3731]
天朝开发
求代理配置方法

**Comment by frostming** [comment]
0. First of all, use English in the open source world.
1. If you have a PyPI mirror deployed in the intranet, use `--pypi-mirror` or replace the `[source]` section in your Pipfile.
2. Otherwise, if you need proxies, `HTTP_PROXY` and `HTTPS_PROXY` env var should just work for you.

**Comment by yuzhujiutian** [comment]
@frostming

while i set HTTP_PROXY and HTTPS_PROXY env var, 
some other soft(e.g. poco service) cannot work (conflict)
so i need pipenv proxy feature like _pip install some_package --proxy=127.0.0.1:port_
