### ISSUE TITLE
Trying to install package editable but no documentation available

### ISSUE THREAD

**Issue by alper** [pypa/pipenv#3733]
I'm trying to install a package in editable mode which I gather is done by passing the `-e` flag to install but the site documentation is so sparse (both here and on the official docs site) that honestly I don't know whether that is the correct option or what it is supposed to do.

**Comment by jxltom** [comment]
You might find some examples in https://docs.pipenv.org/en/latest/basics/#a-note-about-vcs-dependencies.

**Comment by alper** [comment]
Oh, super. Weird how I didn't find this…
https://docs.pipenv.org/en/latest/basics/#editable-dependencies-e-g-e
