### ISSUE TITLE
Option to override pip's --exists-action, or PIP_EXISTS_ACTION

### ISSUE THREAD

**Issue by simion** [pypa/pipenv#3737]
Hello,

I'm trying to find a way to specify `--exists-action` for pip install command, but it seems there's no way to override it.

Here:  https://github.com/pypa/pipenv/blob/master/pipenv/core.py#L1506 you force `"PIP_EXISTS_ACTION": vistir.misc.fs_str("w")`

I need a way to set either `PIP_EXISTS_ACTION=i` or `--exists-action=i` (ignore a package if it's already installed)
This would make installation really really (really) fast, if the virtual environment exists.

We need this because we cache and restore `.venv`, and this option would make CI much faster :) 

Thanks

**Comment by techalchemy** [comment]
Thanks for the suggestion and for the accompanying PR, I will toggle this a bit myself but I don't really see why we shouldn't do this... /cc @uranusjr @frostming
