### ISSUE TITLE
Remove crayons from pipenv in favor of click.styles

### ISSUE THREAD

**Issue by PatrikKopkan** [pypa/pipenv#3741]
Hi, I am trying to devendor packaged pipenv in Fedora. The reason is that it would be easier for us track and solve bugs, CVEs... etc.

I'm working on the pythonfinder package (not patched). It apparently uses the patched version of crayons in pipenv.

I want to ask if you are planning to move from patched crayons to upstream crayons, upstreaming your changes.

I see that the creator of crayons is also the pipenv's BDFL and pipenv uses 7 months old patched version of it.
The rationale listed is very vague: "Crayons is upgraded".

**Comment by techalchemy** [comment]
Hi, someone could upstream patches to crayons but it is definitely not very high priority.  I also am not sure if they would be accepted.  Kenneth also has mostly stepped back from the BDFL role.  We could consider other options besides patching here, but it just isn't on the priority list right now so it would have to be done by someone in the community

**Comment by oz123** [comment]
The patches seem like issues fixes, but also black formatting.
I would vote for completely removing crayons since everything that can be done with crayons can be done with click.
