### ISSUE TITLE
pipenv check --unused incorrectly marks the 'asyncio' package as unused

### ISSUE THREAD

**Issue by mcallaghan-bsm** [pypa/pipenv#3744]
### Issue description

Using `pipenv check --unused" in our project directory.  We use the `asyncio` package, but pipenv unused check is claiming it is not used.

### Expected result

We do not expect `asyncio` to appear in pipenv's output check.
`pipenv check --unused .`

### Actual result

```
pipenv check --unused .
The following dependencies appear unused, and may be safe for removal:
  - asyncio
(snip)
```

Without leaking specific implementation details, here is roughly where it might be within our project
```
$ grep -rins asyncio *
foo_bootstrap.py:10:import asyncio
foo_bootstrap.py:54:        self.loop = asyncio.get_event_loop()
Pipfile:7:asyncio = "*"
Pipfile.lock:61:        "asyncio": {
```
, where self.loop is used throughout such as:
```
self.loop.run_until_complete(python_code_stuff)
```

### Steps to replicate

I would hope it is:
 1. import asyncio in a python file
 2. use it in a function (there may be details here pertinent to reproduction which we have not specifically shared)
 3. run `pipenv check --unused .` in the root project python dir

-------------------------------------------------------------------------------

Some items (SNIPPED for privacy reasons)

+ pipenv --support
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Python installations found:

  - `3.7.3`: `/usr/local/bin/python`
  - `3.7.3`: `/usr/local/bin/python3.7m`
  - `3.5.3`: `/usr/bin/python3.5m`
  - `3.5.3`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-47-generic',
 'platform_system': 'Linux',
 'platform_version': '#50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019',
 'python_full_version': '3.7.3',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `HOSTNAME`
  - `PYTHON_PIP_VERSION`
  - `HOME`
  - `GPG_KEY`
  - `TERM`
  - `PATH`
  - `LANG`
  - `PYTHON_VERSION`
  - `PWD`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/app`

---------------------------

Contents of `Pipfile` ('/app/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
asyncio = "*"
(snip)

[dev-packages]
(snip)

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/app/Pipfile.lock'):
(SNIPPED for privacy reasons)

**Comment by frostming** [comment]
If you are using Python > 3.4 you should put 'asyncio' in Pipfile. In fact, std libraries are filtered out when detecting used libraries.

I am not replying to say there is nothing wrong here but try to explain how things are going under the hood and what we can do at the best. Closing it now, thanks for understanding.

**Comment by mcallaghan-bsm** [comment]
@frostming  - did I not already show that `asyncio` is in the Pipfile?
```
$ grep -rins asyncio *
foo_bootstrap.py:10:import asyncio
foo_bootstrap.py:54:        self.loop = asyncio.get_event_loop()
Pipfile:7:asyncio = "*"                                                                      <<<<<< here
Pipfile.lock:61:        "asyncio": {
```

**Comment by frostming** [comment]
oh sorrys/should/shouldn't/g

**Comment by mcallaghan-bsm** [comment]
ah! _shouldn't_ - thank you;
this is as per: https://docs.python.org/3.4/library/asyncio.html
(`asyncio` is actually part of standard lib as of Python3.4 - this explains it!)
