### ISSUE TITLE
Run commands on new subshell

### ISSUE THREAD

**Issue by jamesshannon** [pypa/pipenv#3747]
I'd like to run some commands within a new shell to further set up the environment. Two specific examples:

* execute the argparse autocompleter for some scripts within the environment
* set a Mac environment variable which causes exceptions when forking processes

I can't seem to find a way to run a specific command(s) after shell is spawned. This should be part of the Pipfile 

A not-nearly-as-good option would be to have a specific section of my `.bashrc` which runs commands per environment, but that's a bit hacky, and it looks like the best variable to use would be the `VIRTUAL_ENV`, which points to the unique hidden environment directory.

Any other ways to solve this?

**Comment by frostming** [comment]
Besides `VIRTUAL_ENV` you can use `PIPENV_ACTIVE` when a pipenv shell is spawned.

**Comment by frostming** [comment]
Closing it for no further actions.
