### ISSUE TITLE
Option in `pipenv lock` to constrain to dev group packages

### ISSUE THREAD

**Issue by jeffb4** [pypa/pipenv#3755]
### Is your feature request related to a problem? Please describe.

Yes. I have an in-house project with `awscli` as a development dependency. `kubernetes` is a runtime dependency. `kubernetes` requires `rsa < 4.0`, `awscli` requires `rsa <=3.5.0`. A Pipfile specifying `awscli *` in dev and `kubernetes *` in default would result in a Pipfile.lock with `rsa = 4.0`

### Describe the solution you'd like

I would like to add a command line option to `pipenv lock` to have `default` take into account `develop` constraints while establishing a resolution lockfile. I'd propose `--constrain-to-dev`

### Describe alternatives you've considered

An alternate solution would be to constrain in `Pipfile/default` these common dependencies such as `rsa`. The disadvantage is lack of automatic upgrades if/when `awscli` bumps its dependency requirement past the constraint.

### Additional context

I'm seeing this on MacOS/python 3.6, but it's a well-known-enough problem

I have done a quick review of previously opened issues around this. I'm not requesting a change in the `Pipfile.lock` format. I'm not requesting a change in the default behavior. I'm not even requesting someone else implement this for me, however I'd like some indication that this approach to solve the UX problem would be accepted. If the scope of this feature is such that a PEEP would need to be created, I can do that.

**Comment by uranusjr** [comment]
I’d say this should be the default behaviour (no flags needed), and the current behaviour is a bug. (It’s a known bug.)

**Comment by jeffb4** [comment]
> I’d say this should be the default behaviour (no flags needed), and the current behaviour is a bug. (It’s a known bug.)

There is previous discussion that due to the desire to decouple dev and default groups (allowing independent updates) the behavior I describe in this option would not be desired by the pipenv team as default. Hence implementation as an option to `lock`

**Comment by matteius** [comment]
Can this be rechecked on `pipenv==2022.8.19`?  I believe work @dqkqd did on constraint files would have resolved it.

**Comment by jeffb4** [comment]
I'm sure you're right. I no longer use pipenv and am not able to test, would it be ok if I closed the issue?
