### ISSUE TITLE
ERROR: No matching distribution found for grpcio==1.21.0

### ISSUE THREAD

**Issue by ryo12882** [pypa/pipenv#3756]
I got above error.
But PyPi has 1.21.0 version of this package.
https://pypi.org/project/grpcio/1.21.0/

How do I solve it?

Thanks,

**Comment by frostming** [comment]
You must be using Windows but `grpcio==1.21.0` doesn't provide a wheel for Windows platform. 
https://pypi.org/project/grpcio/1.21.0/#files

Not related to pipenv
