### ISSUE TITLE
Support cli running from console_scripts

### ISSUE THREAD

**Issue by yssource** [pypa/pipenv#3767]
### Is your feature request related to a problem? Please describe.

1. Project tree
``` bash
.
├── hello
│   ├── __init__.py
│   └── main.py
├── hello.egg-info
│   ├── dependency_links.txt
│   ├── entry_points.txt
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   └── top_level.txt
├── Pipfile
├── Pipfile.lock
├── requirements-dev.txt
└── setup.py
```

2. setup.py
``` python
from setuptools import setup

setup(
    name="hello",
    packages=["hello"],
    entry_points = {
        "console_scripts": [
            "myscript = hello.main:main",
        ]
    }
)
```
3. ./hello/main.py
``` python
def main():
    print("Hello world!")

if __name__ == "__main__":
    main()
```

### Describe the solution you'd like

`pipenv install -e . --dev`
or
`pipenv run pip install -e .`

`hello` is expected installed and executable, but so far it's not available.

I'd like hello bin can be executed from command line.

`hello` should be installed under `./.venv/bin/hello`

May be `pipenv run hello` is available to the user.

**Comment by frostming** [comment]
> hello is expected installed and executable, but so far it's not available.

No, it isn't, according to your `setup.py`, the executable name should be `myscript` and it is available with `pipenv run myscript`.

**Comment by yssource** [comment]
Thanks, it is my fault.
It's OK to run `pipenv run myscript`.
