### ISSUE TITLE
What's the intended deployment strategy? (Pipenv hard-codes absolute path to virtualenv)

### ISSUE THREAD

**Issue by pbudzon** [pypa/pipenv#3771]
Hi everyone.

I'm attempting to create a deployment process for a new project using pipenv. The process is meant to use Jenkins, which will build a deployment package (code + dependecies) that can be deployed onto running servers.
The process would look somewhat like this:
1. Jenkins: Checkout code from repo
2. Jenkins: Run `PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy`
3. Jenkins: Package the whole dir.
4. Jenkins: Upload the package to servers.
5. Restart web server on the servers to make sure code changes are seen.

The main issue I'm encountering with pipenv is the fact that the path to the virtualenv created on Jenkins is hardcoded in various files inside .venv (for example, setting `VIRTUAL_ENV` in bin/activate). This is an issue, since the path in which the project is built in Jenkins (`/var/lib/jenkins/workspace/project/.venv`) is different to the path it sits on the actual application servers (`/var/www/.venv`). I could not find an obvious way to solve this, I thought `PIPENV_NO_INHERIT=1` was meant for this, but it seems to have no effect in this regard.

Hence my question: what is the intended build and deployment strategy with pipenv? Is there a way to pre-build a deployment package (the app code + dependencies) that's ready to be uploaded to the application servers? Or is pipenv expecting that I'll run `pipenv install` on each and every server I want to deploy to?

I'm hoping there's an obvious option I missed somewhere! :)

**Comment by frostming** [comment]
>  Or is pipenv expecting that I'll run pipenv install on each and every server I want to deploy to?

Yes, Pipenv is a tool to **reproduce the environment deterministically**. It is recommended you deploy by `Pipfile` and `Pipfile.lock`, then do `pipenv installl --deploy` on the production server.

Deployment in Python world has been a pain for long days. You can't *easily* deliver prebuilt packages for deployment, like other compiling languages. More specifically, virtualenvs are not created to be **relocatable by default**. However, it is worth trying `virtualenv --relocatable EXISTING_VENV` to make it possible to copy the virtualenv around, though it is not the ultimate solution and may still 
have problems when deploying to another server.
