### ISSUE TITLE
Specifying Package Indexes name

### ISSUE THREAD

**Issue by apiloqbc** [pypa/pipenv#3780]
Is there a way to install using the source name and not the url?
If for example I have my "home" source like this:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "http://pypi.home.org/simple"
verify_ssl = false
name = "home"

[dev-packages]

[packages]
requests = {version="*", index="home"}
maya = {version="*", index="pypi"}
records = "*
```

Without editing by hand the Pipfile, I'm looking for a way to add this:
```
requests = {version="*", index="home"}
```

Thanks in advance
Andrea.

`

**Comment by frostming** [comment]
Pipenv doesn't support this command option now. Such a feature request like this should be landed in a PEEP, you can read `peeps/PEEP-000` for details.

**Comment by oakkitten** [comment]
Won't `pipenv install requests -i home` do just this? Although the index parameter seems to have no effect anyway.

**Comment by matteius** [comment]
This is supported now in latest pipenv versions, for more information read:  https://pipenv.pypa.io/en/latest/advanced/#specifying-package-indexes
