### ISSUE TITLE
Virtualenv source line not removed immediately from zsh history

### ISSUE THREAD

**Issue by nyuszika7h** [pypa/pipenv#3781]
### Issue description

When using zsh, the virtualenv source line executed by `pipenv shell` is not automatically removed from the shell history until a new command is executed. I see that pipenv prefixes the command with a space in an attempt to exclude the line from the history, which works with `HISTCONTROL=ignorespace` in bash, however in zsh it's well-documented behavior that with `setopt histignorespace` the command will linger in the history until the next one is executed.

The solution is to have pipenv send an additional line after the source line, containing only a single space character. This will cause zsh to actually discard the source line from the history immediately (and the empty space line won't stay there either).

### Expected result

The source line should not appear in the zsh history with `setopt histignorespace`.

### Actual result

The source line does appear until the next command is executed, as described above.

### Steps to replicate

```
nyuszika7h@cadoth ~/pipenvtest
% pipenv shell
Launching subshell in virtual environment…
 . /home/nyuszika7h/.local/share/virtualenvs/pipenvtest-SKcwrrwm/bin/activate
nyuszika7h@cadoth ~/pipenvtest
%  . /home/nyuszika7h/.local/share/virtualenvs/pipenvtest-SKcwrrwm/bin/activate
(pipenvtest) nyuszika7h@cadoth ~/pipenvtest
%
[press up arrow]
%  . /home/nyuszika7h/.local/share/virtualenvs/pipenvtest-SKcwrrwm/bin/activate
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/nyuszika7h/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pipenv'`

Python location: `'/home/nyuszika7h/.pyenv/versions/3.7.3/bin/python3.7'`

Python installations found:

  - `3.7.3`: `/home/nyuszika7h/.local/share/virtualenvs/pipenvtest-SKcwrrwm/bin/python3`
  - `3.7.3`: `/home/nyuszika7h/.pyenv/versions/3.7.3/bin/python3`
  - `3.7.3`: `/home/nyuszika7h/.pyenv/versions/3.7.3/bin/python3.7m`
  - `3.5.3`: `/usr/bin/python3`
  - `3.5.3`: `/usr/bin/python3.5m`
  - `2.7.13`: `/usr/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.9.0-9-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13)',
 'python_full_version': '3.7.3',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `NVM_DIR`
  - `SSH_CONNECTION`
  - `LANG`
  - `TZ`
  - `PYENV_ROOT`
  - `OLDPWD`
  - `EDITOR`
  - `NVM_CD_FLAGS`
  - `PYENV_VIRTUALENV_INIT`
  - `PYENV_HOOK_PATH`
  - `VIRTUAL_ENV`
  - `NCURSES_NO_UTF8_ACS`
  - `XDG_SESSION_ID`
  - `USER`
  - `PYENV_DIR`
  - `LC_COLLATE`
  - `PIP_PYTHON_PATH`
  - `PWD`
  - `HOME`
  - `SSH_CLIENT`
  - `PYENV_VERSION`
  - `TMUX`
  - `PIPENV_ACTIVE`
  - `no_proxy`
  - `SSH_TTY`
  - `NO_PROXY`
  - `MAIL`
  - `SHELL`
  - `TERM`
  - `NVM_BIN`
  - `TMUX_PANE`
  - `PYTHONDONTWRITEBYTECODE`
  - `SHLVL`
  - `PYENV_SHELL`
  - `LANGUAGE`
  - `LOGNAME`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `XDG_RUNTIME_DIR`
  - `PATH`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/nyuszika7h/.pyenv/versions/3.7.3/bin:/home/nyuszika7h/.pyenv/libexec:/home/nyuszika7h/.pyenv/plugins/python-build/bin:/home/nyuszika7h/.pyenv/plugins/pyenv-virtualenv/bin:/home/nyuszika7h/.pyenv/plugins/pyenv-update/bin:/home/nyuszika7h/.pyenv/plugins/pyenv-installer/bin:/home/nyuszika7h/.pyenv/plugins/pyenv-doctor/bin:/home/nyuszika7h/.local/share/virtualenvs/pipenvtest-SKcwrrwm/bin:/home/nyuszika7h/.pyenv/plugins/pyenv-virtualenv/shims:/home/nyuszika7h/.pyenv/shims:/home/nyuszika7h/.pyenv/bin:/home/nyuszika7h/.pyenv/versions/3.7.3/bin:/home/nyuszika7h/.pyenv/libexec:/home/nyuszika7h/.pyenv/plugins/python-build/bin:/home/nyuszika7h/.pyenv/plugins/pyenv-virtualenv/bin:/home/nyuszika7h/.pyenv/plugins/pyenv-update/bin:/home/nyuszika7h/.pyenv/plugins/pyenv-installer/bin:/home/nyuszika7h/.pyenv/plugins/pyenv-doctor/bin:/home/nyuszika7h/.nvm/versions/node/v10.15.3/bin:/home/nyuszika7h/.pyenv/plugins/pyenv-virtualenv/shims:/home/nyuszika7h/.pyenv/shims:/home/nyuszika7h/.pyenv/bin:/home/nyuszika7h/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/home/nyuszika7h/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/usr/local/bin:/usr/bin:/bin:/usr/games`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/nyuszika7h/pipenvtest`
  - `VIRTUAL_ENV`: `/home/nyuszika7h/.local/share/virtualenvs/pipenvtest-SKcwrrwm`

---------------------------

Contents of `Pipfile` ('/home/nyuszika7h/pipenvtest/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/home/nyuszika7h/pipenvtest/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "7e7ef69da7248742e869378f8421880cf8f0017f96d94d086813baa518a65489"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

**Comment by frostming** [comment]
@nyuszika7h Did you put the `setopt` line in .zshrc? Also, what about `pipenv shell --fancy`?

**Comment by nyuszika7h** [comment]
Yes, I did. Like I said, this is how zsh works (from `man zshoptions`, emphasis mine):

> HIST_IGNORE_SPACE (-g)
>
> Remove  command  lines from the history list when the first character on the line is  a  space, or when one of the expanded aliases  contains a leading space. Only normal                aliases (not global or suffix aliases) have this behaviour. **Note that the command lingers in the internal history until                the next command is entered before it  vanishes, allowing you to briefly reuse or edit the line. If you want to make it vanish right away without entering another command, type a space and press return.**

`pipenv shell --fancy` doesn't even start the command with a space at all, so it's even worse in this regard. (Also it doesn't even show the virtualenv name, I guess I'm supposed to do that manually in my zshrc in that case.)

**Comment by frostming** [comment]
I finally got a ZSH environment to reproduce this issue. Here is what I observed(ZSH + Oh My ZSH on MacOS):
```bash
$ setopt histignorespace
$  echo foo
$ [UPARROW] echo foo
$ history
...
9981 setopt histignorespace  # echo foo is not in history
$ [UPARROW] setopt histignorespace
```

I believe this is not an issue because it is not saved in history, the last command just preserves for some reason, not sure by Oh My ZSH or ZSH itself.

You can type `history` to check.

**Comment by nyuszika7h** [comment]
Sure, it doesn't get added to the actual history file, but that's not my point. I want to be able to return to the previous command (rather than the pipenv source line) with the up arrow immediately, just like I can in bash.

**Comment by frostming** [comment]
@nyuszika7h You didn't get my point. In my example, I didn't use `pipenv shell` at all. It is a behavior of zsh.
