### ISSUE TITLE
To be truly deterministic, a maintainer of a Pipfile should be able to specify whether to use binary or source

### ISSUE THREAD

**Issue by MrWeeble** [pypa/pipenv#3782]
Currently, if it is necessary to specify source or binary installation of packages it is required for the end user to specify this using pip environment variables, e.g. `PIP_NO_BINARY=psycopg2 pipenv install`

The maintainer of the Pipfile has no way of specifying this directly, so must tell the end user through another channel. This leaves uncertainty as to which variant of the software has been installed

With requirements.txt is is possible for the maintainer to specify in the file the preference with options such as `--no-binary psycopg2`

I believe that adding binary and source options that default to true to the packages specifier would be a sensible way to replicate this behaviour for pipenv e.g.

```
[packages]
psycopg2 = {version = "~=2.7", binary=false}
```

**Comment by immerrr** [comment]
Oh, I would love to be able to do that instead of having a separate wrapper script around `pipenv install` that does
```
PIP_NO_BINARY=psycopg2 pipenv install "$@"
```

**Comment by uranusjr** [comment]
I kind of feel this is a reasonable thing to ask for. The flag should probably not be binary, but tri-state (sdist-only, binary-only, and no preference), but the idea itself is good.

How do you think this should be implemented? I can think of two possibilities:

1. When locking, use the flag to exclude certain types of artifacts from being included into the lock file (i.e. resolve the flag eagerly, on lock time).
2. Simply populate the value to lock file, and use it to pick the desired artifact from the (not filtered) list (i.e. resolve the flag lazily, on install time).

**Comment by immerrr** [comment]
I would suggest the first one, to use the flag when generating the lock file. That way it would also incidentally speed up the download/resolution step somewhat.

**Comment by MrWeeble** [comment]
At lock time makes more sense to me

**Comment by uranusjr** [comment]
Blocking upstream feature required for this to be possible: pypa/pip#6464

**Comment by AlJohri** [comment]
This has been merged https://github.com/pypa/pip/pull/6699
