### ISSUE TITLE
pipenv hashes before expanding environment variables

### ISSUE THREAD

**Issue by andyneff** [pypa/pipenv#3783]
### Issue description

It appears that environment variable expansion is not performed before the hash of a `Pipfile` is calculated. This results in an outdated `Pipfile.lock` being used when environment variables are changed.

### Expected result

A lock happens when versions are changes

### Actual result

A lock does not happen, and the wrong version is installed

### Steps to replicate

`Pipfile`

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
django = "==${DJANGO_VERSION}"
```

Run inside of `docker run -it --rm python:3 bash`

```
DJANGO_VERSION=2.2.1 pipenv install
pipenv run python -c "import django;print(django.__version__)"
pipenv --rm
DJANGO_VERSION=2.2.2 pipenv install
pipenv run python -c "import django;print(django.__version__)"
```

As you will see, 2.2.1 is still installed instead of 2.2.2. You will see on the second install that `Pipfile.lock out of date, updating to…` is not displayed, telling me the hash isn't updated by the environment variable

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Python installations found:

  - `3.7.0`: `/usr/local/bin/python`
  - `3.7.0`: `/usr/local/bin/python3.7m`
  - `3.5.3`: `/usr/bin/python3.5m`
  - `3.5.3`: `/usr/bin/python3`
  - `2.7.13`: `/usr/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.1.5-300.fc30.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Sat May 25 18:00:11 UTC 2019',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LANG`
  - `HOSTNAME`
  - `OLDPWD`
  - `GPG_KEY`
  - `PWD`
  - `HOME`
  - `TERM`
  - `PYTHON_VERSION`
  - `SHLVL`
  - `DJANGO_VERSION`
  - `PATH`
  - `PYTHON_PIP_VERSION`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/tmp`

---------------------------

Contents of `Pipfile` ('/tmp/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
# django = "*"
django = "==${DJANGO_VERSION}"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/tmp/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "ad75608e40aca887f006dca209b3f84b3dfd4f9ec645f2be28b2ffe5b886b0fb"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "django": {
            "hashes": [
                "sha256:753d30d3eb078064d2ddadfea65083c9848074a7f93d7b4dc7fa6b1380d278f5",
                "sha256:7cb67e8b934fab23b6daed7144da52e8a25a47eba7f360ca43d2b448506b01ad"
            ],
            "index": "pypi",
            "version": "==2.2.2"
        },
        "pytz": {
            "hashes": [
                "sha256:303879e36b721603cc54604edcac9d20401bdbe31e1e4fdee5b9f98d5d31dfda",
                "sha256:d747dd3d23d77ef44c6a3526e274af6efeb0a6f1afd5a69ba4d5be4098c8e141"
            ],
            "version": "==2019.1"
        },
        "sqlparse": {
            "hashes": [
                "sha256:40afe6b8d4b1117e7dff5504d7a8ce07d9a1b15aeeade8a2d10f130a834f8177",
                "sha256:7c3dca29c022744e95b547e867cee89f4fce4373f3549ccd8797d8eb52cdb873"
            ],
            "version": "==0.3.0"
        }
    },
    "develop": {}
}

```
</details>

**Comment by frostming** [comment]
This behavior request is different from what is already implemented. The hashes before env injection are there for a reason.

**Comment by vagelim** [comment]
This does not seem to be a feature request but a true bug. The current implementation does not allow for the use of password interpolation [even though the docs state that this is possible](https://docs.pipenv.org/en/latest/advanced/#injecting-credentials-into-pipfiles-via-environment-variables). This seems like a bug given that functionality described in the documentation is not present (locking a Pipfile with interpolated env var results in in the env var being unexpanded in the Pipfile.lock). Tested in `version 2018.11.26`

**Comment by frostming** [comment]
@vagelim Quotes from doc
> Luckily - pipenv will hash your Pipfile before expanding environment variables (and, helpfully, will substitute the environment variables again when you install from the lock file - so no need to commit any secrets! Woo!)

The env vars shouldn't be expanded in either Pipfile or Pipfile.lock, or your secrets may be leaked. Instead, they are substituted when you actually do install or something.

**Comment by vagelim** [comment]
@frostming My apologies my issue was unrelated to this. That totally makes sense.

**Comment by andyneff** [comment]
Are we saying that "the hash contains the secret in hashed form and could be brute forced into leaking it" or something else that I'm missing? (Where a more practical secret would be a password for accessing an https source?)

If that's the case, I see. Is there any obvious future path where we can have things both ways? Maybe a variable prefix that says "This an not a secret, just an env var"? Sounds a little hacky, but I'm spit balling here

**Comment by frostming** [comment]
@andyneff In your example, a package version shouldn't be a variant, because when the package version changed relock must be performed. Pipenv is a tool to generate reproducible dependency setup, it shouldn't depend on some environment variable to produce the environment. The missing fields should have some reason for not being present, which, in most cases, are authentication secrets.
