### ISSUE TITLE
pipenv update does not update package

### ISSUE THREAD

**Issue by apiraino** [pypa/pipenv#3793]
### Issue description

pipenv update does not update package(s)

### Expected result

pipenv should update package(s)

### Steps to replicate

```
$ grep django Pipfile
django-pdb = "==0.5.1"
$ pipenv update --outdated
✔ Success! 
Skipped Update of Package django-pdb: 0.5.1 installed, 0.6.2 available.
All packages are up to date!
$ pipenv update django-pdb
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success! 
Updated Pipfile.lock (8b6857)!
Installing dependencies from Pipfile.lock (8b6857)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
All dependencies are now up-to-date!

... However ... 

$ grep django Pipfile
django-pdb = "==0.5.1"
```

There are a couple of issue closed on the topic, but I can't figure out the right way to use `pipenv update` to update a package to the lastest version.
I've tried setting `django-pdb = "*"` but the package is not updated.

Can you help me on how to use `pipenv update`, pls?

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.7/dist-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.7.3`: `/home/$USER/.local/share/virtualenvs/test-pipenv-hjKnZThl/bin/python3.7`
  - `3.7.3`: `/home/$USER/.pyenv/versions/3.7.3/bin/python3.7`
  - `3.7.3`: `/home/$USER/.pyenv/versions/3.7.3/bin/python3.7m`
  - `3.7.3`: `/usr/bin/python3.7`
  - `3.7.3`: `/usr/bin/python3.7m`
  - `2.7.16`: `/home/$USER/.pyenv/versions/2.7.16/bin/python2.7`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.0.0-16-generic',
 'platform_system': 'Linux',
 'platform_version': '#17-Ubuntu SMP Wed May 15 10:52:21 UTC 2019',
 'python_full_version': '3.7.3',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `QT_ACCESSIBILITY`
  - `COLORTERM`
  - `PYENV_SHELL`
  - `XDG_CONFIG_DIRS`
  - `XDG_SESSION_PATH`
  - `PIPENV_ACTIVE`
  - `LANGUAGE`
  - `LC_ADDRESS`
  - `JAVA_HOME`
  - `LC_NAME`
  - `SSH_AUTH_SOCK`
  - `DESKTOP_SESSION`
  - `LC_MONETARY`
  - `SSH_AGENT_PID`
  - `EDITOR`
  - `GTK_MODULES`
  - `XDG_SEAT`
  - `PWD`
  - `PYENV_VIRTUALENV_INIT`
  - `XDG_SESSION_DESKTOP`
  - `LOGNAME`
  - `XDG_SESSION_TYPE`
  - `GPG_AGENT_INFO`
  - `XAUTHORITY`
  - `XDG_GREETER_DATA_DIR`
  - `GDM_LANG`
  - `PIP_PYTHON_PATH`
  - `HOME`
  - `LANG`
  - `LC_PAPER`
  - `LS_COLORS`
  - `XDG_CURRENT_DESKTOP`
  - `VIRTUAL_ENV`
  - `VTE_VERSION`
  - `XDG_SEAT_PATH`
  - `GNOME_TERMINAL_SCREEN`
  - `LESSCLOSE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `XDG_SESSION_CLASS`
  - `LC_IDENTIFICATION`
  - `TERM`
  - `LESSOPEN`
  - `USER`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `GNOME_TERMINAL_SERVICE`
  - `VISUAL`
  - `DISPLAY`
  - `RUSTC_WRAPPER`
  - `SHLVL`
  - `LC_TELEPHONE`
  - `LC_MEASUREMENT`
  - `XDG_VTNR`
  - `XDG_SESSION_ID`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_RUNTIME_DIR`
  - `PS1`
  - `LC_TIME`
  - `XDG_DATA_DIRS`
  - `ALTERNATE_EDITOR`
  - `PATH`
  - `GDMSESSION`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `LC_NUMERIC`
  - `OLDPWD`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/$USER/.local/share/virtualenvs/test-pipenv-hjKnZThl/bin:/home/$USER/.pyenv/plugins/pyenv-virtualenv/shims:/home/$USER/.pyenv/shims:/home/$USER/.pyenv/bin:/home/$USER/.pyenv/plugins/pyenv-virtualenv/shims:/home/$USER/.pyenv/shims:/home/$USER/.pyenv/bin:/home/$USER/.cargo/bin:/home/$USER/.local/bin:/home/$USER/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:....`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `emacsclient -t`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/$USER/tmp/test-pipenv`
  - `VIRTUAL_ENV`: `/home/$USER/.local/share/virtualenvs/test-pipenv-hjKnZThl`

---------------------------

Contents of `Pipfile` ('/home/$USER/tmp/test-pipenv/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
django-pdb = "==0.5.1"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/home/$USER/tmp/test-pipenv/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "9b6522a11044f8752b200b05671f6c8c94ab8371a5d70e2c0006faa71b8b6857"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "django-pdb": {
            "hashes": [
                "sha256:05d66d986f357e520400d72480db78839698fc013344b4c7024590d05e7dac57"
            ],
            "index": "pypi",
            "version": "==0.5.1"
        }
    },
    "develop": {}
}

```
</details>

**Comment by frostming** [comment]
`pipenv update` only updates Pipfile.lock, not Pipfile. And use the specifier `= "*"` to allow updates.
