### ISSUE TITLE
pipenv --version should work even if doesn't current folder's env doesn't support it

### ISSUE THREAD

**Issue by martinvol** [pypa/pipenv#3796]
### Issue description

pipenv --version should always work, regarding the current folder.

### Expected result

```
$ pipenv --version
pipenv, version 2018.7.1
```

### Actual result

```
$ pipenv --version
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/bin/pipenv", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pipenv==2018.7.1' distribution was not found and is required by the application
```

### Steps to replicate

Try to `pipenv --version` with an env not supported.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipenv'`

Python location: `'/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m`
  - `3.6`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.7`: `/usr/local/bin/python3.7m`
  - `3.7`: `/usr/local/bin/python3.7`

  - `2.7.16`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.16`: `/usr/local/bin/python2`
  - `3.6.4`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3`
  - `3.7.2`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT '
                     '2019; root:xnu-4903.261.4~2/RELEASE_X86_64',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_PROGRAM`
  - `NVM_CD_FLAGS`
  - `ANDROID_HOME`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `GVM_ROOT`
  - `TERM_SESSION_ID`
  - `LC_ALL`
  - `NVM_DIR`
  - `USER`
  - `COMMAND_MODE`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `PATH`
  - `GVM_VERSION`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `PS1`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `ITERM_SESSION_ID`
  - `LOGNAME`
  - `LC_CTYPE`
  - `NVM_BIN`
  - `ANDROID_NDK`
  - `SECURITYSESSIONID`
  - `GVM_PATH_BACKUP`
  - `COLORTERM`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/martinvol/.gvm/bin:/Users/martinvol/.nvm/versions/node/v8.15.1/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/node@8/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/martinvol/Library/Android/sdk/tools:/Users/martinvol/Library/Android/sdk/tools/bin:/Users/martinvol/Library/Android/sdk/platform-tools:/Users/martinvol/go/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/martinvol`

---------------------------

</details>

**Comment by frostming** [comment]
I don't see what the issue title has to do with the error output.

To me, it is more like a broken installation of pipenv. Just remove and re-install it please.
