### ISSUE TITLE
Console output format is out of order

### ISSUE THREAD

**Issue by whg517** [pypa/pipenv#3814]
### ENV
Physics machine: deepin 15.10.1

Remote machine: CentOS 7

Terminal tool: [deepin-terminal](https://www.deepin.org/original/deepin-terminal/)

### Issue description

Terminal execution  `pipenv install --skip-lock` , the output format is out of order

```
(migrate) [tendata@m3 pycharm_project_168]$ cat Pipfile 
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
hdfs = {extras = ["avro", "dataframe", "kerberos"],version = "*"}
avro = "*"
pymongo = "*"

[requires]
pytho   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 3/3 — 00:00:01
(migrate) [tendata@m3 pycharm_project_168]$  — 00:00:00all --skip-lock
  ð   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/3 — 00:00:00irtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to for  ð   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/3 — 00:00:00 instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
  ð   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/3 — 00:00:00
  ð

```
![深度录屏_选择区域_20190627103858](https://user-images.githubusercontent.com/21030747/60229269-e89c9300-98c7-11e9-821a-d32da0c68286.gif)

### Expected result

```
(migrate) kevin@kevin:~/workspaces/develop/python/migrate$ pipenv install --skip-lock
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing dependencies from Pipfile…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 3/3 — 00:00:02

```
### Actual result

```
(migrate) [tendata@m3 pycharm_project_168]$ pipenv install --skip-lock --verbose
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing 'hdfs'▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/3 — 00:00:00
Installing 'avro'▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/3 — 00:00:00ll', '--verbose', '--upgrade', 'hdfs[avro,dataframe,kerberos]', '-i', 'https://pypi.org/simple']
Installing 'pymongo'▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/3 — 00:00:00ll', '--verbose', '--upgrade', 'avro', '-i', 'https://pypi.org/simple']
$ ['/home/tendata/.virtualenvs/migrate/bin/pip', 'install', '--verbose', '--upgrade', 'pymongo', '-i', 'https://pypi.org/simple']
Created temporary directory: /tmp/pip-ephem-wheel-cache-eot4k23v
Created temporary directory: /tmp/pip-req-tracker-3jchdl95
Created requirements tracker '/tmp/pip-req-tracker-3jchdl95'
Created temporary directory: /tmp/pip-install-q8nnv96k
1 location(s) to search for versions of hdfs:
* https://pypi.org/simple/hdfs/
.
.
.

(from https://pypi.org/simple/pymongo/), version: 3.8.0
Installed version (3.8.0) is most up-to-date (past versions: 0.6, 0.7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.9, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.10, 0.10.1, 0.10.2, 0.10.3, 0.11, 0.11.1, 0.11.2, 0.11.3, 0.12, 0.13, 0.14, 0.14.1, 0.14.2, 0.15, 0.15.1, 0.15.2, 0.16, 1.0, 1.1, 1.1.1, 1.1.2, 1.2, 1.2.1, 1.3, 1.4, 1.5, 1.5.1, 1.5.2, 1.6, 1.7, 1.8, 1.8.1, 1.9, 1.10, 1.10.1, 1.11, 2.0, 2.0.1, 2.1, 2.1.1, 2.2, 2.2.1, 2.3, 2.4, 2.4.1, 2.4.2, 2.5, 2.5.1, 2.5.2, 2.6, 2.6.1, 2.6.2, 2.6.3, 2.7, 2.7.1, 2.7.2, 2.8, 2.8.1, 2.9, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 2.9.5, 3.0, 3.0.1, 3.0.2, 3.0.3, 3.1, 3.1.1, 3.2, 3.2.1, 3.2.2, 3.3.0, 3.3.1, 3.4.0, 3.5.0, 3.5.1, 3.6.0, 3.6.1, 3.7.0, 3.7.1, 3.7.2, 3.8.0)
Requirement already up-to-date: pymongo in /home/tendata/.virtualenvs/migrate/lib/python3.6/site-packages (3.8.0)
Clean   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 3/3 — 00:00:02
(migrate) [tendata@m3 pycharm_project_168]$  — 00:00:00
  ð

```

-------------------------------------------------------------------------------

Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/tendata/anaconda3/lib/python3.6/site-packages/pipenv'`

Python location: `'/home/tendata/anaconda3/bin/python'`

Python installations found:

  - `3.6.5`: `/home/tendata/.virtualenvs/migrate/bin/python`
  - `3.6.5`: `/home/tendata/anaconda3/bin/python`
  - `2.7.5`: `/home/tendata/.local/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.20.7-1.el7.elrepo.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Wed Feb 6 13:17:46 EST 2019',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `XDG_SESSION_ID`
  - `VIRTUALENVWRAPPER_SCRIPT`
  - `VIRTUALENVWRAPPER_PROJECT_FILENAME`
  - `HOSTNAME`
  - `SHELL`
  - `TERM`
  - `HISTSIZE`
  - `SSH_CLIENT`
  - `OLDPWD`
  - `QTDIR`
  - `QTINC`
  - `SSH_TTY`
  - `QT_GRAPHICSSYSTEM_CHECKED`
  - `USER`
  - `LS_COLORS`
  - `PYSPARK_DRIVER_PYTHON`
  - `VIRTUAL_ENV`
  - `WORKON_HOME`
  - `PATH`
  - `MAIL`
  - `VIRTUALENVWRAPPER_HOOK_DIR`
  - `PWD`
  - `LANG`
  - `PS1`
  - `HISTCONTROL`
  - `HOME`
  - `SHLVL`
  - `LOGNAME`
  - `QTLIB`
  - `SSH_CONNECTION`
  - `LESSOPEN`
  - `VIRTUALENVWRAPPER_WORKON_CD`
  - `XDG_RUNTIME_DIR`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/tendata/.virtualenvs/migrate/bin:/home/tendata/.local/bin:/home/tendata/anaconda3/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/tendata/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `zh_CN.UTF-8`
  - `PWD`: `/tmp/pycharm_project_168`
  - `VIRTUAL_ENV`: `/home/tendata/.virtualenvs/migrate`

---------------------------

Contents of `Pipfile` ('/tmp/pycharm_project_168/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
hdfs = {extras = ["avro", "dataframe", "kerberos"],version = "*"}
avro = "*"
pymongo = "*"

[requires]
python_version = "3.6"

```

**Comment by frostming** [comment]
It should be an issue with the terminal App because it just looks fine on other terminals
