### ISSUE TITLE
Readme's installation section does not list Windows

### ISSUE THREAD

**Issue by ComFreek** [pypa/pipenv#3815]
### Is your feature request related to a problem? Please describe.

The readme says `Windows is a first-class citizen, in our world.`, but its installation section does not even contain an installation command for Windows. Instead, one is referred to [documentation for instructions](https://docs.pipenv.org/en/latest/install/#installing-pipenv).

### Describe the solution you'd like

List install instruction for Windows in readme, e.g. `pip install pyenv`. Alternatively, create a [Chocolatey package](https://chocolatey.org/) (a Windows package manager) and then write `choco install pyenv`.

**Comment by frostming** [comment]
Because we do not have any package manager installation option on Windows. Just use `pip` for general platforms.

P.S. the package name is `pipenv` not `pyenv`.

**Comment by ComFreek** [comment]
> Just use pip for general platforms.

Yes, why not put this into the readme?
Whenever a project does not list Windows under its installation section, I feel that Windows is *not* a first-class citizen. Further, redirecting Windows installation instructions via links to other sites is a bit negatively connotated for me. Often, projects link to years-old issues which got never resolved.

In any case, feel free to leave it at that & thanks for the project :smile:
