### ISSUE TITLE
"pipenv lock --dev --requirements" doesn't include default packages

### ISSUE THREAD

**Issue by asmaier** [pypa/pipenv#3816]
### Issue description

    pipenv lock --dev --requirements > requirements.txt 

generates a `requirement.txt` that doesn't include the default packages. It only includes the development packages.

### Expected result

According to the documentation the flag `--dev` means

> Install both develop and default packages.

(see https://docs.pipenv.org/en/latest/#pipenv-lock)

So either the documentation should be changed or the behaviour of `pipenv lock --dev` should be fixed.

**Comment by frostming** [comment]
The option's help string is not accurate. Want a PR to fix it.
