### ISSUE TITLE
`pipenv install` tooks almost 1 hour because of `pipenv lock` process

### ISSUE THREAD

**Issue by rnglab** [pypa/pipenv#3829]
Hello everyone,

First of all thanks for this great project.

I'm trying to use `pipenv` for one of our projects. After environment setup i just start to install our dependency packages with :
```
 pipenv install 
```

But the experience is here really unexpected, it tooks almost `1 hour`.

Also when process complete the console says it just takes 4 seconds : 

<img width="404" alt="Screen Shot 2019-07-08 at 15 50 06" src="https://user-images.githubusercontent.com/3276415/60811872-d4467900-a198-11e9-857a-6fb6751b9a41.png">

I guess this message is not related about whole process. There must be another items such as  indexing, caching or something else.

I think these step needs some improvements in console behaviors.

- It could be nice if console output gives correct information about whole process and its current steps.
- It could be nice if install process takes less time.

**Basic Pipfile for just 3 packages:**
```python
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
numpy = "*"
imutils = "*"
opencv-python = "*"

[requires]
python_version = "3.7"
```

**Comment by frostming** [comment]
It is a known issue, which happens when installing packages like `numpy`, `scipy` and `tensorflow`.

See related issues #3827 #2681

**Comment by rnglab** [comment]
@frostming  thanks 👍
