### ISSUE TITLE
When I pipenv install,MemoryError

### ISSUE THREAD

**Issue by mentoorliubin** [pypa/pipenv#3834]
Failed creating virtual environment
[pipenv.exceptions.VirtualenvCreationException]:   File "c:\users\travel\appdata\local\programs\python\python37\lib\site-packages\pipenv\cli\command.py", line 254, in install
[pipenv.exceptions.VirtualenvCreationException]:       editable_packages=state.installstate.editables,
[pipenv.exceptions.VirtualenvCreationException]:   File "c:\users\travel\appdata\local\programs\python\python37\lib\site-packages\pipenv\core.py", line 1741, in do_install
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "c:\users\travel\appdata\local\programs\python\python37\lib\site-packages\pipenv\core.py", line 574, in ensure_project
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "c:\users\travel\appdata\local\programs\python\python37\lib\site-packages\pipenv\core.py", line 506, in ensure_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]:   File "c:\users\travel\appdata\local\programs\python\python37\lib\site-packages\pipenv\core.py", line 935, in do_create_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       extra=[crayons.blue("{0}".format(c.err)),]
[pipenv.exceptions.VirtualenvCreationException]: MemoryError

**Comment by frostming** [comment]
Seems related to #3832 , can you confirm the python version?

**Comment by mentoorliubin** [comment]
> Seems related to #3832 , can you confirm the python version?

solved! thanks a lot!
It's about versions.

**Comment by frostming** [comment]
Thanks, lets awaiting the upstream fix.
