### ISSUE TITLE
Pipenv take longer and instance hangs up

### ISSUE THREAD

**Issue by anuj9196** [pypa/pipenv#3840]
I'm using **Pipenv** for package management and configured Pipeline from Bitbucket to AWS EC2 instance via CodeDeploy.

While running the script 
```
pipenv install
```
It takes longer and instance hangs up at
```
Installing dependencies from Pipfile.lock (a34ea0)…
```
The instance has to be restarted manually by stop-start to get it back to normal.

This is a weird scenario and Pipenv is not performing well.

Even though there is nothing updated in the package, I had to run the `pipenv install` script.

1. Is there any way to optimize this?
2. Is there any way to check if the hash is outdated and only then run the `pipenv install` using bash script?

**Comment by frostming** [comment]
1. If the connection is very slow you probably need to [use a pypi mirror](https://pipenv.readthedocs.io/en/latest/advanced/#using-a-pypi-mirror) that is fast on your server.

2. `pipenv install --deploy` will first check whether the hash is outdated and abort if so. `pipenv sync` will do *installation* only, without checking the hashes.

**Comment by anuj9196** [comment]
I tried with `--deploy` flag but it still wait for installing the libraries even if they are not new.
Is there any faster way to speed up the installation? 

The `pipenv` install is freezing the server and only way is to restart the server. This is really painful.

**Comment by frostming** [comment]
@anuj9196 "outdated" means the content of Pipfile doesn't match the Pipfile.lock, it doesn't mean there are some packages to be upgraded.

Did you try the pypi mirror?

**Comment by anuj9196** [comment]
@frostming what `mirror_url` to use?

**Comment by anuj9196** [comment]
I run the two commands. one with `--deploy` and another without id.
```
user@pc:~/code/project/app$ time pipenv install
Installing dependencies from Pipfile.lock (1e8942)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 103/103 — 00:00:38
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

real    0m43.039s
user    1m39.556s
sys     0m9.872s
user@pc:~/code/project/pc$ time pipenv install --deploy
Installing dependencies from Pipfile.lock (1e8942)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 103/103 — 00:00:28

real    0m31.107s
user    1m40.320s
sys     0m9.540s
```

The time is almost the same for both commands. There is no effect of adding `--deploy`
#2284

**Comment by matteius** [comment]
@anuj9196 There have been some performance enhancements to pipenv since this issue was opened.   Please check the latest pipenv version and report back if there is still an issue to pursue with this report.
