### ISSUE TITLE
pipenv check returns "Unable to load vulnerability database"

### ISSUE THREAD

**Issue by nre-ableton** [pypa/pipenv#3860]
I'm using pipenv version `2018.11.26`, and running `pipenv check` returns the following:

```
Checking PEP 508 requirements…
Passed!
Checking installed package safety…
An error occurred:
Unable to load vulnerability database
```

It seems that this has happened in the past -- I did some googling and stumbled across this old issue: https://github.com/pypa/pipenv/issues/3826

When I first started noticing the error, https://pyup.io/ was returning `HTTP 500` for their homepage. But now it's back up and running, and `pipenv` is still giving errors. `pipenv check --verbose` doesn't show any extra information, so I'm not sure what's wrong.

On another note, might it be possible to add a flag to `pipenv check` to only do the PEP 508 checks and skip the security checks for times like this?

**Comment by mcallaghan-bsm** [comment]
We too are experiencing this consistently today. (could go back in time did not check for how long)

**Comment by mcallaghan-bsm** [comment]
Note pyup.io is intermittently giving `HTTP 500`. (Just tried and it was fine same as OP, but subsequently it returned error)

**Comment by frostming** [comment]
Is the 500 error expected? Any case replacing the pyup key with your own by `PIPENV_PYUP_API_KEY` and try again?

Maybe it is an issue with `safety`

**Comment by Luitame** [comment]
I'm facing the same 

```

**Comment by frostming** [comment]
Yeah, already noticed, maybe it's a good idea to fallback to the open mirror when pyup.io is not available, or provide the ability to override that behavior.

**Comment by Luitame** [comment]
For now, it's working back! Thx @frostming

**Comment by pcraciunoiu** [comment]
Still fails for me consistently and has been most of this week.

**Comment by frostming** [comment]
Seems we can close it now.

**Comment by mcallaghan-bsm** [comment]
Why is the issue closed?  Is there a different ticket to ref for the robustness enhancement?  or what is the plan going forward to protect users from pyup outages?
