### ISSUE TITLE
`MemoryError` while creating a virtual environment

### ISSUE THREAD

**Issue by fuyunekojima** [pypa/pipenv#3863]
Trying to create a virtual environment with `pipenv-python 3.7` will end up with a` MemoryError` after being held for a very long time.
At that time, a large number of logs such as 'Running virtualenv with interpreter C: \ Program Files \ Python37 \ python.exe' appear.
The virtual environment is not created when only 'Pipfile' is created.
The contents of 'Pipfile' are empty.

Looking at the processes in the task manager, you can see that the python processes are constantly increasing while creating the virtual environment.

Python was installed from the official site binary and was installed as `pip install pipinv` after` pip install --upgrade pip`.

The 'PIPENV_VENN_PROJECT' environment variable is 'true'.

System:
     windows 10 pro
     RAM: 16GB
     CPU: i7 3770
     GPU: GTX 680
Python:
     Version: 3.7
Pipenv:
    Version: 2018.11.26

**Comment by frostming** [comment]
You must be using Python 3.7.4 and virtualenv<16.6.2 , you may want #3832 .

**Comment by fuyunekojima** [comment]
I solved it when I raised the version of virtualenv.
