### ISSUE TITLE
Use devicemanager of infi issue

### ISSUE THREAD

**Issue by newperry** [pypa/pipenv#3864]
I want to show device on windows 7 in Python.
My code in below. But it show "RuntimeError: generator raised StopIteration" at dm.all_devices() when I run it.
I use Python 3.7.  I don't know what is wrong.

from infi.devicemanager import DeviceManager
dm = DeviceManager()
all_dev = dm.all_devices()

**Comment by frostming** [comment]
Please report issues related to the Pipenv project.
