### ISSUE TITLE
"Error while finding module specification" after upgrade to v2018.11.26

### ISSUE THREAD

**Issue by reebr** [pypa/pipenv#3872]
### Issue description

I was using a previous version of Pipenv, and used the following command to run my application: 

```sh
set FLASK_APP=app
set FLASK_ENV=development
flask run
 * Serving Flask app "app" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 242-429-215
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

And then the application was run as expected.

I'm not sure if it's a pipenv problem, so I'd like some help solving this. After upgrading to the **2018.11.26** version, I started to have some problems executing the same code. Running the same sequence of commands above results in:

```sh
set FLASK_APP=app
set FLASK_ENV=development
flask run
 * Serving Flask app "app" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Restarting with stat
c:\users\renan\.virtualenvs\pipenv_issue-9cyicfyp\scripts\python.exe: Error while finding module specification for 'C:\\Users\\renan\\.virtualenvs\\pipenv_issue-9cYIcFYP\\Scripts\\flask' (ModuleNotFoundError: No module named 'C:\\Users\\renan\\')
```

However, if I run specifying `py-m ...`, it works:

```sh
py -m flask run
 * Serving Flask app "app" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 242-429-215
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

### Expected result

I expected to run my application without specifying python on the command line. But if this is the new expected behavior of pipenv, all right, I just wish I knew there were changes.

I am using the console in administrator mode (cmd, not PowerShell).

### Steps to replicate

```sh
git clone git@github.com:reebr/pip_env.git

cd ./pip_env
pipenv install
pipenv shell

set FLASK_ENV=development
set FLASK_APP=app
flask run
```

### Environment
- Windows 10 Pro x64 (1809)
- Python 3.7.4
- pipenv 2018.11.26

### Pipenv support
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'c:\\users\\renan\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pipenv'`

Python location: `'c:\\users\\renan\\appdata\\local\\programs\\python\\python37\\python.exe'`

Python installations found:

  - `3.7.4`: `C:\Users\renan\AppData\Local\Programs\Python\Python37\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.4',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17763',
 'python_full_version': '3.7.4',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `CHOCOLATEYINSTALL`
  - `CHOCOLATEYLASTPATHUPDATE`
  - `CHOCOLATEYTOOLSLOCATION`
  - `CLASSPATH`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DRIVERDATA`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `JAVA_HOME`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `ONEDRIVECONSUMER`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PIPENV_ACTIVE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `PYCHARM COMMUNITY EDITION`
  - `PYTHONDONTWRITEBYTECODE`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VIRTUAL_ENV`
  - `WINDIR`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv?specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug?specific environment variables:

  - `PATH`: `C:\Users\renan\.virtualenvs\pipenv_issue-9cYIcFYP\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\ProgramData\chocolatey\bin;C:\Users\renan\AppData\Local\Android\Sdk\platform-tools;D:\Javafx-sdk-12.0.1;C:\Program Files\Java\jre1.8.0_211\bin;C:\Users\renan\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\renan\AppData\Local\Programs\Python\Python37\;C:\Users\renan\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\renan\AppData\Local\Programs\Python\Python38\;C:\Users\renan\AppData\Local\Microsoft\WindowsApps;C:\Users\renan\AppData\Roaming\npm;C:\Users\renan\AppData\Local\Yarn\bin;C:\Users\renan\AppData\Local\Programs\Microsoft VS Code\bin;D:\PyCharm Community Edition 2019.1.1\bin;;C:\tools\dart-sdk\bin;C:\Users\renan\AppData\Roaming\Pub\Cache\bin;C:\Flutter\bin;D:\Javafx-sdk-12.0.1;`
  - `VIRTUAL_ENV`: `C:\Users\renan\.virtualenvs\pipenv_issue-9cYIcFYP`

---------------------------

Contents of `Pipfile` ('C:\\Users\\renan\\Desktop\\pipenv_issue\\Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
flask = "*"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('C:\\Users\\renan\\Desktop\\pipenv_issue\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "a82b674d67d29678775ff6b773de1686a9593749ec14483b0d8e05131b662286"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "click": {
            "hashes": [
                "sha256:2335065e6395b9e67ca716de5f7526736bfa6ceead690adf616d925bdc622b13",
                "sha256:5b94b49521f6456670fdb30cd82a4eca9412788a93fa6dd6df72c94d5a8ff2d7"
            ],
            "version": "==7.0"
        },
        "flask": {
            "hashes": [
                "sha256:13f9f196f330c7c2c5d7a5cf91af894110ca0215ac051b5844701f2bfd934d52",
                "sha256:45eb5a6fd193d6cf7e0cf5d8a5b31f83d5faae0293695626f539a823e93b13f6"
            ],
            "index": "pypi",
            "version": "==1.1.1"
        },
        "itsdangerous": {
            "hashes": [
                "sha256:321b033d07f2a4136d3ec762eac9f16a10ccd60f53c0c91af90217ace7ba1f19",
                "sha256:b12271b2047cb23eeb98c8b5622e2e5c5e9abd9784a153e9d8ef9cb4dd09d749"
            ],
            "version": "==1.1.0"
        },
        "jinja2": {
            "hashes": [
                "sha256:065c4f02ebe7f7cf559e49ee5a95fb800a9e4528727aec6f24402a5374c65013",
                "sha256:14dd6caf1527abb21f08f86c784eac40853ba93edb79552aa1e4b8aef1b61c7b"
            ],
            "version": "==2.10.1"
        },
        "markupsafe": {
            "hashes": [
                "sha256:00bc623926325b26bb9605ae9eae8a215691f33cae5df11ca5424f06f2d1f473",
                "sha256:09027a7803a62ca78792ad89403b1b7a73a01c8cb65909cd876f7fcebd79b161",
                "sha256:09c4b7f37d6c648cb13f9230d847adf22f8171b1ccc4d5682398e77f40309235",
                "sha256:1027c282dad077d0bae18be6794e6b6b8c91d58ed8a8d89a89d59693b9131db5",
                "sha256:24982cc2533820871eba85ba648cd53d8623687ff11cbb805be4ff7b4c971aff",
                "sha256:29872e92839765e546828bb7754a68c418d927cd064fd4708fab9fe9c8bb116b",
                "sha256:43a55c2930bbc139570ac2452adf3d70cdbb3cfe5912c71cdce1c2c6bbd9c5d1",
                "sha256:46c99d2de99945ec5cb54f23c8cd5689f6d7177305ebff350a58ce5f8de1669e",
                "sha256:500d4957e52ddc3351cabf489e79c91c17f6e0899158447047588650b5e69183",
                "sha256:535f6fc4d397c1563d08b88e485c3496cf5784e927af890fb3c3aac7f933ec66",
                "sha256:62fe6c95e3ec8a7fad637b7f3d372c15ec1caa01ab47926cfdf7a75b40e0eac1",
                "sha256:6dd73240d2af64df90aa7c4e7481e23825ea70af4b4922f8ede5b9e35f78a3b1",
                "sha256:717ba8fe3ae9cc0006d7c451f0bb265ee07739daf76355d06366154ee68d221e",
                "sha256:79855e1c5b8da654cf486b830bd42c06e8780cea587384cf6545b7d9ac013a0b",
                "sha256:7c1699dfe0cf8ff607dbdcc1e9b9af1755371f92a68f706051cc8c37d447c905",
                "sha256:88e5fcfb52ee7b911e8bb6d6aa2fd21fbecc674eadd44118a9cc3863f938e735",
                "sha256:8defac2f2ccd6805ebf65f5eeb132adcf2ab57aa11fdf4c0dd5169a004710e7d",
                "sha256:98c7086708b163d425c67c7a91bad6e466bb99d797aa64f965e9d25c12111a5e",
                "sha256:9add70b36c5666a2ed02b43b335fe19002ee5235efd4b8a89bfcf9005bebac0d",
                "sha256:9bf40443012702a1d2070043cb6291650a0841ece432556f784f004937f0f32c",
                "sha256:ade5e387d2ad0d7ebf59146cc00c8044acbd863725f887353a10df825fc8ae21",
                "sha256:b00c1de48212e4cc9603895652c5c410df699856a2853135b3967591e4beebc2",
                "sha256:b1282f8c00509d99fef04d8ba936b156d419be841854fe901d8ae224c59f0be5",
                "sha256:b2051432115498d3562c084a49bba65d97cf251f5a331c64a12ee7e04dacc51b",
                "sha256:ba59edeaa2fc6114428f1637ffff42da1e311e29382d81b339c1817d37ec93c6",
                "sha256:c8716a48d94b06bb3b2524c2b77e055fb313aeb4ea620c8dd03a105574ba704f",
                "sha256:cd5df75523866410809ca100dc9681e301e3c27567cf498077e8551b6d20e42f",
                "sha256:e249096428b3ae81b08327a63a485ad0878de3fb939049038579ac0ef61e17e7"
            ],
            "version": "==1.1.1"
        },
        "werkzeug": {
            "hashes": [
                "sha256:87ae4e5b5366da2347eb3116c0e6c681a0e939a33b2805e2c0cbd282664932c4",
                "sha256:a13b74dd3c45f758d4ebdb224be8f1ab8ef58b3c0ffc1783a8c7d9f4f50227e6"
            ],
            "version": "==0.15.5"
        }
    },
    "develop": {}
}

```
</details>

**Comment by tomwignall** [comment]
I am also experiencing the same issue after reinstall of my machine.

**Comment by frostming** [comment]
No, the issue doesn't occur *after* upgrading pipenv, but after upgrading werkzeug. Though it is not an issue related to Pipenv, I would like to say the workaround is to use werkzeug 0.15.4 or lower.

https://github.com/pallets/werkzeug/issues/1614
https://github.com/pallets/werkzeug/issues/1619

**Comment by reebr** [comment]
@frostming thanks.
