### ISSUE TITLE
fbprophet install(using pip in virtualenv) hangs/freeze

### ISSUE THREAD

**Issue by newbieh4cker** [pypa/pipenv#3874]
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.5/dist-packages/pipenv'`

Python location: `'/usr/bin/python3.5'`

Python installations found:

  - `3.7.4`: `/root/37/bin/python3`
  - `3.6.9`: `/usr/bin/python3.6m`
  - `3.4.10`: `/usr/bin/python3.4m`
  - `3.7.4`: `/usr/bin/python3.7m`
  - `2.7.12`: `/usr/bin/python2.7`
  - `3.7.4`: `/usr/bin/python3.7`
  - `3.5.2`: `/usr/bin/python3`
  - `3.4.10`: `/usr/bin/python3.4`
  - `3.6.9`: `/usr/bin/python3.6`
  - `3.5.2`: `/usr/bin/python3.5m`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.5.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-1037-gcp',
 'platform_system': 'Linux',
 'platform_version': '#39~16.04.1-Ubuntu SMP Thu Jul 4 09:29:23 UTC 2019',
 'python_full_version': '3.5.2',
 'python_version': '3.5',
 'sys_platform': 'linux'}
```

System environment variables:

  - `PS1`
  - `HOSTNAME`
  - `OLDPWD`
  - `TERM`
  - `PIP_SHIMS_BASE_MODULE`
  - `PATH`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `LS_COLORS`
  - `VIRTUAL_ENV`
  - `SHLVL`
  - `HOME`
  - `PIP_PYTHON_PATH`
  - `LANG`
  - `_`
  - `LC_ALL`
  - `PYTHONDONTWRITEBYTECODE`
  - `PWD`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/root/37/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/root`
  - `VIRTUAL_ENV`: `/root/37`

---------------------------

</details>

my env is..
 - host os : ubuntu 16.04 / 8 cpu, 7gb ram, 100gb ssd
 - guest os : docker container / ubuntu 16.04 / 6 cpu, 6gb ram
 - guest os : virtualenv python3.7 and 3.6

problem is...
 - fbprophet does works fine when using python 3.6 virtualenv.
 - fbprophet doesn't work(hangs when install over 30 min) when using python 3.7 virtualenv

![image](https://user-images.githubusercontent.com/23703741/62037615-12323c80-b22f-11e9-80d1-5c27fef14cb0.png)

above htop is host os (which works fine)
below htop is guest os (which doesn't work, Uptime is stopped)

**Comment by frostming** [comment]
Same issue as #3832

**Comment by newbieh4cker** [comment]
@frostming 
downgraded python, but still having issue
 - python 3.7.3
 - virtualenv 16.7.2

**Comment by frostming** [comment]
From your reproducing steps, I see Pipenv is not involved, is it?

**Comment by newbieh4cker** [comment]
@frostming 
sorry, solved issue.
it was pystan problem. 
thank you for help :)
