### ISSUE TITLE
Asdf Support

### ISSUE THREAD

**Issue by jamesstidard** [pypa/pipenv#3875]
Hi,

I'm looking at switching from `pyenv` to `asdf` for managing my python installs, but it would be a shame to miss the QoL integration `pipenv` has with pyenv.

I [forked the repo](https://github.com/jamesstidard/pipenv/commit/8a783deb3b30a2de634ef6294db8bc705d7d2996) and had a look at how easy it would be to add. Seems pretty straight forward. I guess some things to consider are:

- What if pyenv and asdf are both installed?
I would assume pyenv takes priority as it's language specific. Or a user environment var to flag a preference.

- Adding to an already fringe feature
The `pyenv` integration, though I find very convent, is probably not considered that core to the project. Adding this extra python version manager integration is maybe just more to maintain.

If this has a chance of being picked up, I'd happily finish and document the changes.

[link to asdf](https://asdf-vm.com/#/)

Thanks.

**Comment by AlJohri** [comment]
I believe techalchemy added ASDF support already. See: 

- https://github.com/sarugaku/pythonfinder/search?q=asdf&unscoped_q=asdf
- https://github.com/sarugaku/pythonfinder/issues/35
- https://github.com/sarugaku/pythonfinder/pull/36
- https://github.com/sarugaku/pythonfinder/pull/41

I'm not 100% sure if this is already released but the latest version of `pythonfinder` vendored into this repo already ASDF support.

**Comment by frostming** [comment]
If I understand correctly, the ASDF support in `pythonfinder` is about python finding, but the OP is talking about python installation.

In my opinion, it is a reasonable request, just need some refinement for the implementation.

**Comment by jamesstidard** [comment]
> If I understand correctly, the ASDF support in `pythonfinder` is about python finding, but the OP is talking about python installation.

Yeah, sorry I didn't make that too clear in my original post. `pythonfinder` does check for `asdf` installs currently. The hack-job fork I made uses to see if `asdf` is installed - just as `pyenv` installed are currently checked for.

> In my opinion, it is a reasonable request, just need some refinement for the implementation.

I think one of the things that should be checked is if, not just `asdf` is installed, but the python plugin for `asdf` is also installed. I couldn't see how/if this is was handled for `pyenv`'s equivalent `python-build` plugin. You can list installed plugins in `asdf`, whereas I think for `pyenv` the `install` command just doesn't show up unless the plugin is installed.

**Comment by oz123** [comment]
Seems fixed.
