### ISSUE TITLE
Feature request: pipenv graph --out, to have option to output file

### ISSUE THREAD

**Issue by Yobmod** [pypa/pipenv#3881]
Would it be possible to add an --output flag to pipenv graph?
Having a file to search through makes it much easier to find dependancy problems than in the terminal.

I currently bodge this by running pipenv.core.do_graph() and capturing the sdtout (and handling the sys.exit() exception), but a flag would make this a useful feature.

**Comment by frostming** [comment]
It is easy to achieve by `pipenv graph > output.txt`.

**Comment by Yobmod** [comment]
> 
> 
> It is easy to achieve by `pipenv graph > output.txt`.

Ah, great. That's easier, lol.
I can't find that anywhere in the docs, might be worth adding.
Thanks!

**Comment by frostming** [comment]
I dont think so, it is a basic skill of almost all shells.
