### ISSUE TITLE
use .venv no have  module datetime.py

### ISSUE THREAD

**Issue by AlienationX** [pypa/pipenv#3883]
在项目路径创建.venv，启动程序提示如下错误。发现没有.venv/Lib/datetime.py文件，这是什么情况，创建的虚拟环境不完整吗？少了很多系统自带的模块。

In the project path to create. Venv, the launcher prompts the following error.
Found no . venv/Lib/datetime.py file, what is this situation, create virtual environment incomplete? Many of the system's own modules are missing.
------
C:\Users\Admin\Desktop> C:\Users\Admin\Desktop\demo\.venv\Scripts\python.exe C:\Users\Admin\Desktop\demo\case\ex_oracle_to_txt.py
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\demo\case\ex_oracle_to_txt.py", line 4, in <module>
    import pandas as pd
  File "C:\Users\Admin\Desktop\demo\.venv\lib\site-packages\pandas\__init__.py", line 17, in
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy: No module named 'ctypes'
pytz: No module named 'datetime'

**Comment by frostming** [comment]
Please follow the issue template to ask a good question

1. What does the error have to do with Pipenv?
2. What are the necessary steps to replicate the problem?
3. DO use English in the description.

**Comment by frostming** [comment]
No new updates, close this now, feel free to reopen when you get more information about the bug.
