### ISSUE TITLE
pipenv update ERROR in Windows Terminal

### ISSUE THREAD

**Issue by SenWang** [pypa/pipenv#3895]
I like to use pipenv under Windows Terminal App.
Everything is fine except

> pipenv update

command. Error msg as follows:

> ........
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches numpy
No versions found
Was https://pypi.org/simple reachable?

Same command under cmd.exe works.
Please advise how to let it works under Windows Terminal App.

**Comment by frostming** [comment]
Do you have proxy env settings?

**Comment by SenWang** [comment]
There are no env settings.

**Comment by SenWang** [comment]
however, use

> curl https://pypi.org/simple/

command works in both places.

**Comment by frostming** [comment]
Can't reproduce on Windows Terminal here. You might have messed up your terminal settings.

**Comment by SenWang** [comment]
> Can't reproduce on Windows Terminal here. You might have messed up your terminal settings.

OH, I've got some idea from your reply :)
My original setting

> "commandline" : "cmd.exe /K pipenv shell",
not works.
After changing to 
"commandline" : "cmd.exe /K activate.bat & pipenv shell",
it works.

many thanks, and I need to find some way to

**Comment by oz123** [comment]
This is solved.
