### ISSUE TITLE
Feature Git References: Skip LFS

### ISSUE THREAD

**Issue by four43** [pypa/pipenv#3899]
**Feature Request!**

## Use Case
We currently pull some libraries we've created via git+ssh. This allows us to maintain a cheap "repo" of these libraries by leveraging git. We currently use this syntax in our Pipfile:
```
our-private-package = {editable = true,git = "ssh://git@bitbucket.org/our-org/python-our-private-package.git",ref = "v1.2.3"}
```
These repos leverage [Git LFS](https://git-lfs.github.com/) to store large blobs of data for testing. This data is only used for tests and just adds bloat to our project using these libraries.

## Desired Behavior
If we could have a flag to skip LFS download that would be ideal:
```
skip_lfs = true
```
```
our-private-package = {editable = true,git = "ssh://git@bitbucket.org/our-org/python-our-private-package.git",ref = "v1.2.3", skip_lfs = true}
```
Or something like that. That would help take down the package size from several hundred MB to a few KB.

Is there any other interest in this behavior? Am I missing a way to do this already? I did try searching around and didn't find anything quite like this.

Thanks,
-Seth

**Comment by four43** [comment]
A quick hacky work-around I found that works surprisingly well:
```
export GIT_LFS_SKIP_SMUDGE=1
pipenv install --dev
```
Since pipenv seems to respect git settings under the hood, A+ for that.

**Comment by four43** [comment]
So is that a no then @frostming?

**Comment by frostming** [comment]
@four43 Why? The environment variable can do the trick.

Git is not even a dependency of Pipenv.  Pipenv should not take control of its behavior.

**Comment by four43** [comment]
Pipenv is controlling both SSH and Git in this context. I'm looking for more programmatic control, similar to how tags and references are specified.

**Comment by themightyoarfish** [comment]
seconded. Very annoying having to modify the environment instead of ignoring lfs inside Pipfile

**Comment by four43** [comment]
Luckily we've since moved away from pipenv years ago due to flaky behavior and are doing much better with plain pip and bash.
