### ISSUE TITLE
Pipenv picking up wrong version constraint from a newer package version

### ISSUE THREAD

**Issue by six8** [pypa/pipenv#3900]
### Issue description

The following `Pipenv` fails to install:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
springfield = "==0.7.17"
anticipate = "==0.8.0"

[requires]
python_version = "2.7"
```

```
ERROR: Could not find a version that matches anticipate==0.8.0,>=0.9.1
Tried: 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.8.0, 0.9.1, 0.9.1
There are incompatible versions in the resolved dependencies.
```

It seems that even though `springfield==0.7.17` requires `anticipate` without any specific constraint it's picking up a `anticipate>=0.9.1` constraint from `springfield==0.8.0`.

The constraint it gets is:

```
 springfield==0.7.17       requires anticipate>=0.9.1, future==0.17.1
```

This is clearly the `springfield 0.8.0` constraints because `0.17.7` does not specify `future` as a requirement -- only `0.8.0` does.

I've tried `pipenv lock --clear` and it gets the same results.

### Expected result

`anticipate==0.8.0` and `springfield==0.7.17` to be installed.

### Actual result

```
pipenv lock --clear -v
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✘ Locking Failed!
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1
Current constraints:
  anticipate==0.8.0
  springfield==0.7.17

Finding the best candidates:
  found candidate anticipate==0.8.0 (constraint was ==0.8.0)
  found candidate springfield==0.7.17 (constraint was ==0.7.17)

Finding secondary dependencies:
  anticipate==0.8.0 not in cache, need to check index
  anticipate==0.8.0         requires -
  springfield==0.7.17 not in cache, need to check index
  springfield==0.7.17       requires anticipate>=0.9.1, future==0.17.1

New dependencies found in this round:
  adding [u'anticipate', '>=0.9.1', '[]']
  adding [u'future', '==0.17.1', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  anticipate==0.8.0,>=0.9.1
  future==0.17.1
  springfield==0.7.17

Finding the best candidates:
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 395, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches anticipate==0.8.0,>=0.9.1
Tried: 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.8.0, 0.9.1, 0.9.1
There are incompatible versions in the resolved dependencies.
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1
Current constraints:
  anticipate==0.8.0
  springfield==0.7.17

Finding the best candidates:
  found candidate anticipate==0.8.0 (constraint was ==0.8.0)
  found candidate springfield==0.7.17 (constraint was ==0.7.17)

Finding secondary dependencies:
  anticipate==0.8.0 not in cache, need to check index
  anticipate==0.8.0         requires -
  springfield==0.7.17 not in cache, need to check index
  springfield==0.7.17       requires anticipate>=0.9.1, future==0.17.1

New dependencies found in this round:
  adding [u'anticipate', '>=0.9.1', '[]']
  adding [u'future', '==0.17.1', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  anticipate==0.8.0,>=0.9.1
  future==0.17.1
  springfield==0.7.17

Finding the best candidates:
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 395, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches anticipate==0.8.0,>=0.9.1
Tried: 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.8.0, 0.9.1, 0.9.1
There are incompatible versions in the resolved dependencies.
```

### Steps to replicate

Use the `Pepenv` above and `pipenv install --two`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.11.26_2/libexec/bin/python3.7'`

Python installations found:

  - `3.7.4`: `/usr/local/bin/python3`
  - `3.7.4`: `/usr/local/bin/python3.7m`
  - `3.7.3`: `/usr/local/opt/pyenv/versions/3.7.3/bin/python3`
  - `3.7.3`: `/usr/local/opt/pyenv/versions/3.7.3/bin/python3.7m`
  - `2.7.16`: `/usr/local/opt/pyenv/versions/2.7.16/bin/python`
  - `2.7.16`: `/usr/local/opt/pyenv/versions/stashutil/bin/python`
  - `2.7.16`: `/usr/local/opt/pyenv/versions/snakelike/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT '
                     '2019; root:xnu-4903.261.4~2/RELEASE_X86_64',
 'python_full_version': '3.7.4',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `ZSH_DIR`
  - `ZSH`
  - `USER`
  - `COMMAND_MODE`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `PYENV_VIRTUALENV_INIT`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `PAGER`
  - `LSCOLORS`
  - `_`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `PYENV_SHELL`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `LC_CTYPE`
  - `HOMEBREW_CASK_OPTS`
  - `SECURITYSESSIONID`
  - `COLORTERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.11.26_2/libexec/tools:/usr/local/Cellar/pyenv-virtualenv/1.1.3/shims:/usr/local/opt/pyenv/shims:/usr/local/Cellar/pyenv-virtualenv/1.1.3/shims:/usr/local/opt/pyenv/shims:/usr/local/opt/pyenv/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/mthornton/Projects/PulseSecure/pulse-workspace-server`

---------------------------

Contents of `Pipfile` ('/Users/mthornton/Projects/PulseSecure/pulse-workspace-server/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
springfield = "==0.7.17"
anticipate = "==0.8.0"

[requires]
python_version = "2.7"

```

</details>

**Comment by frostming** [comment]
> This is clearly the springfield 0.8.0 constraints because 0.17.7 does not specify future as a requirement -- only 0.8.0 does.

Not the truth, the Github repo may cheat you. Note the universal wheel is uploaded 11 days after the tarball, which is the same date of when 0.8.0 release. So I guess the author might mistake the tag and build the wheel against 0.8.0 requirements.

Not a bug.

**Comment by six8** [comment]
So pipenv is using the py3 wheel on a Python 2 install? Isn't that a problem?

**Comment by six8** [comment]
I checked `pringfield-0.7.17-py3-none-any.whl` and it is definitely the 0.8.0 version but the metadata is mixed

```
Metadata-Version: 2.1
Name: springfield
Version: 0.7.17
...
Requires-Dist: anticipate (>=0.9.1)
Requires-Dist: future (==0.17.1)
...
---------
Changelog
---------

0.8.0
=====

* Added support for Python 3.6+
* Dropped support for Python <2.7
```

Not sure what `bdist_wheel` was doing when it made this. Anyway, I'll remove the broken whl. But I'd still expect the py3 whl would be ignored in a py2 environement.

**Comment by frostming** [comment]
@six8 Oh I didn't notice you are using Python 2. Similar situation of #3865

**Comment by frostming** [comment]
Pipenv always tries to lock *cross-platform and cross-python-version* dependencies. It is based on the assumption that all artifacts belonging to a particular version should be the same except for markers, and a broken release make it not the truth.

Maybe we should ignore the incompatible artifacts when python version is pinned in the Pipfile.

**Comment by six8** [comment]
I see. Yes this does look like #3865.

It seems reasonable to ignore artifacts that don't match a pinned Python version.

The case I'm working on is migrating these packages to Python 3. So I need both py2 and py3 environments to test the compatibility.

**Comment by matteius** [comment]
This issue is a little dated at this point--I believe constraints have been sorted out in recent versions, but we also don't support python 2 anymore, so it would be impossible to triage this.   My suggestion if there is an active issue with the latest pipenv version to open a new issue report and we will respond to that.
