### ISSUE TITLE
environment variables in pipfile scripts are not recognized correctly

### ISSUE THREAD

**Issue by Madoshakalaka** [pypa/pipenv#3901]
When running [scripts from pipfile](https://docs.pipenv.org/en/latest/advanced/#custom-script-shortcuts). Unix style environment variables are wrongly recognized as commands.

### Expected result

`hello=world` is recognized as setting an environment variable 

### Actual result

`Error: the command hello=world (from generic-script) could not be found within PATH.`

### Steps to replicate

- have the following part in `pipfile`
    ```
    [scripts]
    generic-script = 'hello=world python --version'
    ```
- `$ pipenv run generic-script`

**Comment by Madoshakalaka** [comment]
fyi: npm scripts in `package.json` handles this correctly

**Comment by Madoshakalaka** [comment]
a workaround is to use `$ env hello=world <commands>` on unix systems.

**Comment by danieldaeschle** [comment]
What about multiple environment arguments?

**Comment by Hammond95** [comment]
Hello everyone, 
I am trying to contribute to the project trying to solve this issue.

I made a first hackish version that fixes the error of the issue.

Something that is missing, is defining which use cases this feature should cover.
Some examples:
- do we want to solve variables into the command? `${MYVAR} or $MY_VAR`
- do we want to allow the execution of multiple commands if separated by semicolon? `echo "hello"; python --version`
- do we want to allow multiple command execution with `|` or `&&` or `||` operators?

I think that the purpose of this feature was to give an easy tool for a developer to run local script to do tests.

**Comment by matteius** [comment]
@Madoshakalaka Could you check if new version `2022.3.23` which has a fix for something similar to this, solves this ticket?

**Comment by matteius** [comment]
Its `pipenv==2022.3.24` now.

**Comment by piranna** [comment]
Why It got closed?

**Comment by matteius** [comment]
@piranna because of recent improvements to pipenv and a lack of response on this issue.   Should it not be considered closed?

**Comment by piranna** [comment]
> Should it not be considered closed?

If it's still not possible to define an environment variable in the `scripts` field in a similar way to how it can be done in npm `package.json` file, then no, I think it should not be closed. Multiple commands or other advances syntax features can be moved to a script file, but environment variables are needed to exec the commands and falls in the scope of the `scripts` field, if you don't want to add syntax to it at least provide a way to define them, like an `env` dict field or something...

**Comment by matteius** [comment]
> If it's still not possible to define an environment variable in the scripts field in a similar way to how it can be done in npm package.json file, then no, I think it should not be closed.

@piranna There is a new version of pipenv, can you try it and report back?  There are so many things going on that I cannot personally triage everything.   All I know is that you can define whatever variables you want in a `.env` file or your environment and then use those in scripts.  I ever added a test case about it:  https://github.com/pypa/pipenv/pull/4979/files#diff-3fe0ab87ef8fd3ad2eeccf25f9f90375d6013b1a6ff813b883f98aad05db9a8dR214

**Comment by jyotirmay123** [comment]
> > If it's still not possible to define an environment variable in the scripts field in a similar way to how it can be done in npm package.json file, then no, I think it should not be closed.
> 
> @piranna There is a new version of pipenv, can you try it and report back? There are so many things going on that I cannot personally triage everything. All I know is that you can define whatever variables you want in a `.env` file or your environment and then use those in scripts. I ever added a test case about it: https://github.com/pypa/pipenv/pull/4979/files#diff-3fe0ab87ef8fd3ad2eeccf25f9f90375d6013b1a6ff813b883f98aad05db9a8dR214

No, You have tested by defining one env variable and accessing it. It worked for me as well. 
But when you do it to pass to a different command like 
```ini
[scripts]
docker_build="docker build -t $HELLO ."
```

this does not work.

**Comment by jyotirmay123** [comment]
> @Madoshakalaka Could you check if new version `2022.3.23` which has a fix for something similar to this, solves this ticket?

sorry for late response.. I just tested with updated version of pipenv and it works.
For better visibility, this below stuff works:

**.env**
```ini
NOTEBOOK_DIR=path-to-your-notebook-dir
```

**pipfile**
```ini
[scripts]
notebook="jupyter notebook --notebook-dir=$NOTEBOOK_DIR"
```

**terminal**
pipenv run notebook   🥇 

@matteius

**Comment by matteius** [comment]
Wait I just re-opened this and then re-read the comments.  Are you saying @jyotirmay123 it does in fact work `pipenv>=2022-03-24` it works?  That would make sense since the fix got merged to main on March 12th.   I opened this back up to not loose track of it, but if we don't need it to be open, let's close it @piranna

**Comment by jyotirmay123** [comment]
> Wait I just re-opened this and then re-read the comments. Are you saying @jyotirmay123 it does in fact work `pipenv>=2022-03-24` it works? That would make sense since the fix got merged to main on March 12th. I opened this back up to not loose track of it, but if we don't need it to be open, let's close it @piranna

@matteius yes, it does work now with the updated version. Thank you very much for the hard work. Cheers.

**Comment by melyux** [comment]
I think this should be re-opened, because the same syntax that would work in npm's `package.json` and normal shells, like this

```
[scripts]
test = "HELLO=world python myscript.py"
```

doesn't work with Pipfile, even in version 2023.12.1. It says:

```
Error: the command HELLO=world (from test) could not be found within PATH.
```
