### ISSUE TITLE
Failed to install jedi with pipenv

### ISSUE THREAD

**Issue by hongyi-zhao** [pypa/pipenv#3906]
Hi,

See the following:

$ pipenv install jedi
Installing jedi…
Adding jedi to Pipfile's [packages]…
✔ Installation Succeeded 
Installing dependencies from Pipfile.lock (7f1754)…
Traceback (most recent call last):▉▉▉▉▉ 0/4 — 00:00:00
  File "/home/werner/.pyenv/versions/3.7.4/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/core.py", line 1992, in do_install
    skip_lock=skip_lock,
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/core.py", line 1253, in do_init
    pypi_mirror=pypi_mirror,
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/core.py", line 838, in do_install_dependencies
    deps_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/core.py", line 754, in batch_install
    extra_indexes=extra_indexes
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/core.py", line 1421, in pip_install
    c = delegator.run(pip_command, block=block, env=pip_config)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/delegator.py", line 336, in run
    c.run(block=block, binary=binary, cwd=cwd, env=env)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/delegator.py", line 204, in run
    s = PopenSpawn(self._popen_args, **pexpect_kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/pexpect/popen_spawn.py", line 53, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/werner/Desktop/job-transfer/opencv/.venv/bin/pip': '/home/werner/Desktop/job-transfer/opencv/.venv/bin/pip'
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/4 — 00:00:00

    $ pipenv --support

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv'`

Python location: `'/home/werner/.pyenv/versions/3.7.4/bin/python3.7'`

Python installations found:

  - `3.9.0a0`: `/home/werner/.pyenv/versions/3.9-dev/bin/python3.9`
  - `3.8.0b2`: `/home/werner/.pyenv/versions/3.8-dev/bin/python3`
  - `3.7.4`: `/home/werner/.pyenv/versions/3.7.4/bin/python3.7m`
  - `3.7.4`: `/home/werner/.pyenv/versions/3.7.4/bin/python3`
  - `3.7.3`: `/home/werner/.pyenv/versions/3.7.3/bin/python3.7m`
  - `3.7.3`: `/home/werner/.pyenv/versions/3.7.3/bin/python3`
  - `3.7.3`: `/usr/local/bin/python3.7`
  - `3.7.3`: `/usr/local/bin/python3.7m`
  - `3.5.3`: `/usr/bin/python3.5m`
  - `3.5.3`: `/usr/bin/python3.5`
  - `2.7.13`: `/home/werner/.pyenv/versions/2.7.13/bin/python2`
  - `2.7.13`: `/usr/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.9.0-9-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11)',
 'python_full_version': '3.7.4',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `GREP_COLOR`
  - `CLUTTER_IM_MODULE`
  - `PIPENV_VENV_IN_PROJECT`
  - `LS_COLORS`
  - `LD_LIBRARY_PATH`
  - `BASH_IT_THEME`
  - `BASH_IT`
  - `XDG_MENU_PREFIX`
  - `LANG`
  - `GDM_LANG`
  - `HISTCONTROL`
  - `MANAGERPID`
  - `TODO`
  - `DISPLAY`
  - `HISTTIMEFORMAT`
  - `VT_MPI`
  - `PYENV_ROOT`
  - `IPPROOT`
  - `OLDPWD`
  - `INVOCATION_ID`
  - `GDB_CROSS`
  - `VT_ARCH`
  - `COLORTERM`
  - `GDBSERVER_MIC`
  - `VTUNE_AMPLIFIER_XE_2015_DIR`
  - `USERNAME`
  - `PYENV_VIRTUALENV_INIT`
  - `GOPROXY`
  - `PYENV_HOOK_PATH`
  - `MPM_LAUNCHER`
  - `VT_SLIB_DIR`
  - `XDG_VTNR`
  - `GIT_HOSTING`
  - `SSH_AUTH_SOCK`
  - `SCM_CHECK`
  - `PIPENV_PYPI_MIRROR`
  - `INTEL_PYTHONHOME`
  - `CLASSPATH`
  - `XDG_SESSION_ID`
  - `USER`
  - `PYENV_DIR`
  - `GO111MODULE`
  - `LSCOLORS`
  - `DESKTOP_SESSION`
  - `BASH_IT_CUSTOM`
  - `QT4_IM_MODULE`
  - `MIC_LIBRARY_PATH`
  - `QT_QPA_PLATFORMTHEME`
  - `PWD`
  - `HOME`
  - `JOURNAL_STREAM`
  - `SSH_AGENT_PID`
  - `PYENV_VERSION`
  - `QT_ACCESSIBILITY`
  - `CPATH`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `GDB_HOST`
  - `NLSPATH`
  - `XDG_SESSION_DESKTOP`
  - `INSPECTOR_2015_DIR`
  - `DBUS_STARTER_ADDRESS`
  - `LIBRARY_PATH`
  - `VT_LIB_DIR`
  - `INTEL_LICENSE_FILE`
  - `GTK_MODULES`
  - `MIC_LD_LIBRARY_PATH`
  - `VT_ROOT`
  - `WINDOWPATH`
  - `VTE_VERSION`
  - `SHELL`
  - `TERM`
  - `VT_ADD_LIBS`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `ADVISOR_XE_2015_DIR`
  - `IM_CONFIG_PHASE`
  - `DBUS_STARTER_BUS_TYPE`
  - `XDG_CURRENT_DESKTOP`
  - `GPG_AGENT_INFO`
  - `QT_LINUX_ACCESSIBILITY_ALWAYS_ON`
  - `AUTOFEATURE`
  - `SHLVL`
  - `XDG_SEAT`
  - `PYENV_SHELL`
  - `PROMPT_COMMAND`
  - `IRC_CLIENT`
  - `MANPATH`
  - `WINDOWID`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `MKLROOT`
  - `PATH`
  - `TBBROOT`
  - `SYSTEMD_NSS_BYPASS_BUS`
  - `INFOPATH`
  - `I_MPI_ROOT`
  - `HISTSIZE`
  - `HISTFILESIZE`
  - `SESSION_MANAGER`
  - `GTK_IM_MODULE`
  - `history_dir`
  - `BASH_FUNC_run_on_prompt_command%%`
  - `BASH_FUNC_extract%%`
  - `BASH_FUNC_asn2ipset%%`
  - `BASH_FUNC_bhgrep%%`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`
 - `PIPENV_PYPI_MIRROR`: `https://pypi.tuna.tsinghua.edu.cn/simple`

Debug–specific environment variables:

  - `PATH`: `/home/werner/.pyenv/versions/3.7.4/bin:/home/werner/.pyenv/libexec:/home/werner/.pyenv/plugins/python-build/bin:/home/werner/.pyenv/plugins/pyenv-virtualenv/bin:/home/werner/.pyenv/plugins/pyenv-update/bin:/home/werner/.pyenv/plugins/pyenv-installer/bin:/home/werner/.pyenv/plugins/pyenv-doctor/bin:/home/werner/.pyenv/plugins/pyenv-virtualenv/shims:/home/werner/.pyenv/shims:/home/werner/.pyenv/bin:/opt/intel/bin:/opt/intel/advisor_xe_2015.1.10.380555/bin64:/opt/intel/vtune_amplifier_xe_2015.4.1.412820/bin64:/opt/intel/inspector_xe_2015.1.2.379161/bin64:/opt/intel//impi/5.0.3.049/intel64/bin:/opt/intel//itac/9.0.3.051/intel64/bin:/opt/intel/composer_xe_2015.6.233/bin/intel64:/opt/intel/composer_xe_2015.6.233/debugger/gdb/intel64_mic/bin:/opt/openjdk/jdk-12.0.1/bin:/opt/apache-maven/apache-maven-3.6.1/bin:/home/werner/software/golang/go.git/bin:/home/werner/.local/texlive/2016/bin/x86_64-linux:/home/werner/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/usr/local/maui/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/werner/Desktop/job-transfer/opencv`

---------------------------

Contents of `Pipfile` ('/home/werner/Desktop/job-transfer/opencv/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
opencv-python = "*"
jedi = "*"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/home/werner/Desktop/job-transfer/opencv/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "aaa6f7c3eb79c4e2efb757f70a70346fec7d355eecfdd74c43828c6e8a7f1754"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "jedi": {
            "hashes": [
                "sha256:786b6c3d80e2f06fd77162a07fed81b8baa22dde5d62896a790a331d6ac21a27",
                "sha256:ba859c74fa3c966a22f2aeebe1b74ee27e2a462f56d3f5f7ca4a59af61bfe42e"
            ],
            "index": "pypi",
            "version": "==0.15.1"
        },
        "numpy": {
            "hashes": [
                "sha256:03e311b0a4c9f5755da7d52161280c6a78406c7be5c5cc7facfbcebb641efb7e",
                "sha256:0cdd229a53d2720d21175012ab0599665f8c9588b3b8ffa6095dd7b90f0691dd",
                "sha256:312bb18e95218bedc3563f26fcc9c1c6bfaaf9d453d15942c0839acdd7e4c473",
                "sha256:464b1c48baf49e8505b1bb754c47a013d2c305c5b14269b5c85ea0625b6a988a",
                "sha256:5adfde7bd3ee4864536e230bcab1c673f866736698724d5d28c11a4d63672658",
                "sha256:7724e9e31ee72389d522b88c0d4201f24edc34277999701ccd4a5392e7d8af61",
                "sha256:8d36f7c53ae741e23f54793ffefb2912340b800476eb0a831c6eb602e204c5c4",
                "sha256:910d2272403c2ea8a52d9159827dc9f7c27fb4b263749dca884e2e4a8af3b302",
                "sha256:951fefe2fb73f84c620bec4e001e80a80ddaa1b84dce244ded7f1e0cbe0ed34a",
                "sha256:9588c6b4157f493edeb9378788dcd02cb9e6a6aeaa518b511a1c79d06cbd8094",
                "sha256:9ce8300950f2f1d29d0e49c28ebfff0d2f1e2a7444830fbb0b913c7c08f31511",
                "sha256:be39cca66cc6806652da97103605c7b65ee4442c638f04ff064a7efd9a81d50a",
                "sha256:c3ab2d835b95ccb59d11dfcd56eb0480daea57cdf95d686d22eff35584bc4554",
                "sha256:eb0fc4a492cb896346c9e2c7a22eae3e766d407df3eb20f4ce027f23f76e4c54",
                "sha256:ec0c56eae6cee6299f41e780a0280318a93db519bbb2906103c43f3e2be1206c",
                "sha256:f4e4612de60a4f1c4d06c8c2857cdcb2b8b5289189a12053f37d3f41f06c60d0"
            ],
            "version": "==1.17.0"
        },
        "opencv-python": {
            "hashes": [
                "sha256:1703a296a96d3d46615e5053f224867977accb4240bcaa0fcabcb0768bf5ac13",
                "sha256:1777ce7535ee7a1995cae168a107a1320e9df13648b930e72a1a2c2eccd64cda",
                "sha256:1e5520482fb18fbd64d079e7f17ac0018f195fd75f6360a53bb82d7903106b50",
                "sha256:25522dcf2529614750a71112a6659759080b4bdc2323f19d47f4d895960fd796",
                "sha256:2af5f2842ad44c65ae2647377e0ff198719e1a1cfc9c6a19bc0c525c035d4bd8",
                "sha256:31ec48d7eca13fc25c287dea7cecab453976e372cad8f50d55c054a247efda21",
                "sha256:47cf48ff5dbd554e9f58cc9e98cf0b5de3f6a971172612bffa06bc5fb79ce872",
                "sha256:494f98366bb5d6c2ac7e50e6617139f353704fd97a6d12ec9d392e72817d5cb0",
                "sha256:4a9845870739e640e3350a8d98d511c92c087fe3d66090e83be7bf94e0ac64f7",
                "sha256:4ac29cc0847d948a6636899014e84e165c30cc8779d6218394d44363462a01ce",
                "sha256:5857ace03b7854221abf8072462d306c2c2ce4e366190b21d90ee8ee8aaf5bb4",
                "sha256:5b4a23d99d5a2874767034466f5a8fd37b9f93ac14955a01b1a208983c76b9ad",
                "sha256:734d87a5021c037064beb62133e135e66c7128e401a63b8b842b809ae2093749",
                "sha256:78005c1c5d15ef4e32e0f485557bd15b5b6d87f49c19db7fe3e9246a61ebe7e4",
                "sha256:81ae2283225c5c52fc3d72debd4241c30ccff2bb922578bf7867f9851cce3acb",
                "sha256:88dbf900f297fdae0f62b899d6a784d8868ec2135854c5f8a9abbad00a6f0c5b",
                "sha256:8c98ea7b8d327a31cd6028782a06147d0e0329ae8e829e881fb5d02f7ed8aec9",
                "sha256:937d4686fef6967921145290f5b50c01c00c5b5d3542a6519e8a85cd88448723",
                "sha256:a057958c0e362b3c4f03b9af1cbdb6d5af035fd22ecd7fd794eba8fdeb049eb8",
                "sha256:c41eab31fa2c641226c6187caa391a688d064c99f078d604574f1912296b771f",
                "sha256:cf4f7e62d1f80d1fa85a1693a3500def5cde54b2b75212b3609e552e4c25acfb",
                "sha256:d90d60143e18334330c149f293071c9f2f3c79c896f33dc4ec65099e58baaaa7",
                "sha256:db3106b7ca86999a7bd1f2fcc93e49314e5e6e451356774e421a69428df5020b",
                "sha256:dbaf264db56f4771dfac6624f438bc4dc670aa94f61a6138848fcab7e9e77380",
                "sha256:e65206c4cf651dc9cf0829962fae8bec986767c9f123d6a1ad17f9356bf7257e",
                "sha256:eac94ddc78c58e891cff7180274317dad2938a4ddfc6ced1c04846c7f50e77e9",
                "sha256:f2e828711f044a965509c862b3a59b3181e9c56c145a950cb53d43fec54e66d2"
            ],
            "index": "pypi",
            "version": "==4.1.0.25"
        },
        "parso": {
            "hashes": [
                "sha256:63854233e1fadb5da97f2744b6b24346d2750b85965e7e399bec1620232797dc",
                "sha256:666b0ee4a7a1220f65d367617f2cd3ffddff3e205f3f16a0284df30e774c2a9c"
            ],
            "version": "==0.5.1"
        }
    },
    "develop": {}
}

```
</details>

**Comment by frostming** [comment]
You seem to have a broken venv, try removing `/home/werner/Desktop/job-transfer/opencv/.venv/` and run again.

It is not an issue with Pipenv.
