### ISSUE TITLE
Limit repetitive output

### ISSUE THREAD

**Issue by pmlk** [pypa/pipenv#3909]
I'd like to avoid the following in GitLab CI logs:

```
⠋ Creating virtual environment...
⠙ Creating virtual environment...
⠹ Creating virtual environment...
⠸ Creating virtual environment...
⠼ Creating virtual environment...
⠴ Creating virtual environment...
⠦ Creating virtual environment...
⠧ Creating virtual environment...
⠇ Creating virtual environment...
⠏ Creating virtual environment...
⠋ Creating virtual environment...
⠙ Creating virtual environment...
...
⠙ Locking...
⠹ Locking...
⠸ Locking...
⠼ Locking...
⠴ Locking...
⠦ Locking...
⠧ Locking...
⠇ Locking...
⠏ Locking...
⠋ Locking...
⠙ Locking...
⠹ Locking...
⠸ Locking...
...
```

This happens when building a docker image in a GitLab CI pipeline. In a Dockerfile I have the following line which floods the log as shown above:

`RUN PIPENV_QUIET=true PIPENV_YES=true pipenv --bare install`

I have found `PIPENV_QUIET` and `--bare` as possible ways to limit the output `pipenv` generates. However, it doesn't limit it enough as shown above.

### Is your feature request related to a problem? Please describe.

Not a real problem, would just be nice to have a smaller log in the CI.

### Describe the solution you'd like

In situations where the output is supposed to be limited/minimal get rid of the progress indicators and print `Creating virtual environment...`, `Locking...`, etc. just once. Obviously, the progress indicators are super nice when you're actually sitting in front of the terminal.

I am not sure whether or not this behavior should be covered by either `PIPENV_QUIET`, `--bare`, both or if a new option should be introduced.

### Describe alternatives you've considered

None

### Additional context

This happens or shows up in the GitLab CI logs.

Working with `python:3.7` as the docker base image.

**Comment by frostming** [comment]
`PIPENV_NOSPIN=1` can do the trick.
