### ISSUE TITLE
README.md: pipenv.gif 404's

### ISSUE THREAD

**Issue by jasonharrison** [pypa/pipenv#3911]
In README.md

```![image](https://s3.amazonaws.com/media.kennethreitz.com/pipenv.gif)```

https://s3.amazonaws.com/media.kennethreitz.com/pipenv.gif seems to 404.

https://github.com/pypa/pipenv/commit/db3b743a584510092d8a6eeffc2c12965eb5c5f1#diff-04c6e90faac2675aa89e2176d2eec7d8R23

**Comment by frostming** [comment]
Can you see the GIF on Github repo page?

**Comment by frostming** [comment]
We have replaced the GIF on the doc page, would you like to fix it for README? PR welcome.
