### ISSUE TITLE
Pipenv shell fails on PowerShell Core 7 preview 2

### ISSUE THREAD

**Issue by oleo65** [pypa/pipenv#3917]
### Issue description

`pipenv shell` fails on PowerShell Core 7.0.0.-preview.2

Error message is: `The command "pwsh.exe" is either misspelled or could not be found.` (Translated from my German version)

The same machine and environment is working on the build in classic PowerShell

### Expected result

Environment getting activated.

### Actual result

```
Launching subshell in virtual environment…
Der Befehl "pwsh.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```

### Steps to replicate

`pipenv shell`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'c:\\program files\\python37\\lib\\site-packages\\pipenv'`

Python location: `'c:\\program files\\python37\\python.exe'`

Python installations found:

  - `4.2.12`: `C:\Users\odendahl\AppData\Local\Continuum\Miniconda3\python.exe`
  - `4.2.12`: `C:\Program Files\Miniconda3\python.exe`
  - `3.7.4`: `C:\Program Files\Python37\python.exe`
  - `3.5`: `C:\Users\odendahl\AppData\Local\Continuum\Miniconda3\Scripts\python.exe`
  - `3.5`: `C:\Program Files\Miniconda3\Scripts\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.4',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.18362',
 'python_full_version': '3.7.4',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DRIVERDATA`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `JAVA`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `ONEDRIVECONSUMER`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VS140COMNTOOLS`
  - `WINDIR`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv├╗specific environment variables:

Debug├╗specific environment variables:

  - `PATH`: `C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\ProgramData\Oracle\Java\javapath;C:\oracle\product\12.1.0\client_1\BIN;C:\oracle\reports6\BIN;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Windows\System32\OpenSSH\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\dotnet\;C:\Program Files\PowerShell\6\;C:\Program Files (x86)\GnuPG\bin;C:\Program Files\nodejs\;C:\Program Files\PowerShell\7-preview\preview;C:\Users\user\AppData\Local\Programs\Git\cmd;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Local\Programs\Git\cmd;;C:\Program Files\Microsoft VS Code\bin;C:\Users\user\AppData\Roaming\npm`

---------------------------

Contents of `Pipfile` ('C:\\Users\\user\\Documents\\PythonEnvironments\\DataScience\\Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "3.7"

```

</details>

**Comment by frostming** [comment]
So is `pwsh.exe` a valid command that can be executed rightly?

**Comment by oleo65** [comment]
Thank you for your hint. It seems that the preview installer messed up somehow the path environment variable and therefore pwsh.exe could not be found.

Fixing path also resolved pipenv shell.
