### ISSUE TITLE
No PipFile found

### ISSUE THREAD

**Issue by mksoft-systems** [pypa/pipenv#3925]
Hello All , 
My systems is macOSX Ver 10.14.6.
My python 3.7.4

When I run pipenv like "pipenv --python 3.7"  the env is do created but always in the same place.
and NO PipFile and Pipfile.lock is avail on the local dir.

here what I have done...
 
I created dir /home/test1/
run "pipenv --python 3.7"
no Pipfile on the /home/test1 dir to be found.
I try to install django and it did install it fine but not on the pipfile on current dir.

I also created /home/test2
run the same as above and the result are the same.
I try to install flask and it did install it fine but not on the same pipfile as above in main home dir.

Any help please.
Koby Peleg Hen

**Comment by frostming** [comment]
You must have a Pipfile somewhere in the parent directories, type `pipenv --where` to see where it is.

**Comment by mksoft-systems** [comment]
Thank you all , 
I did have at the top dir Pipfile.
I deleted the file , make the test and every thing is perfectly fine now.
