### ISSUE TITLE
pipenv lock --on [date]

### ISSUE THREAD

**Issue by PMLP-novo** [pypa/pipenv#3926]
I want to access a pipenv lock as how it would be generated if would be generate on a speicifc date. For example I want add a new package and this would also update many of the other packages by being able to control not taking newer versions than a given date I would be able to add packages easierly.

### Describe the solution you'd like
If running a `pipenv lock --on 2019/08/22` I expect that the lock file would be generated in same way as if I were to press `pipenv lock` on the 2019/08/22. So just ignoring all versions of packages after the `lock_date` which is set by the --on keyword (I would not be against renaming it to lock_date).

**Comment by PMLP-novo** [comment]
> I want to access a pipenv lock as how it would be generated if would be generate on a speicifc date. For example I want add a new package and this would also update many of the other packages by being able to control not taking newer versions than a given date I would be able to add packages easierly.
> 
> ### Describe the solution you'd like
> If running a `pipenv lock --on 2019/08/22´ I expect that the lock file would be generated in same way as if I were to press `pipenv lock`on the 2019/08/22. So just ignoring all versions of packages after the`lock_date` which is set by the --on keyword (I would not be against renaming it to lock_date).

**Comment by frostming** [comment]
Too complicated to implement, not in the scope now.
