### ISSUE TITLE
Installing serverless-python-requirements issues

### ISSUE THREAD

**Issue by pb321** [pypa/pipenv#3933]
Im trying to install serverless-python-requirements,however, im getting the following error message :

 ERROR: Could not find a version that matches serverless-python-requirements
No versions found
Was https://pypi.org/simple reachable?

ive attempted to clear the cache, uninstalling\reinstalling pipenv etc.. but nothing seems to work.  i can install other packages ok ( serverless framework, numpy etc.. ).  here is the pipenv --support details : 

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'C:\\Users\\TTYY\\AppData\\Roaming\\Python\\Python37\\site-packages\\pipenv'`

Python location: `'c:\\program files (x86)\\python\\python.exe'`

Python installations found:

  - `3.7.4`: `C:\Users\TTYY\git\.virtualenvs\test1-BtSuf0k4\Scripts\python.exe`
  - `3.7.4`: `C:\Users\TTYY\git\.virtualenvs\test1-BtSuf0k4\Scripts\pythonw.exe`
  - `3.7.4`: `C:\Program Files (x86)\Python\python.exe`
  - `3.7.4`: `C:\Program Files (x86)\Python\pythonw.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.4',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17763',
 'python_full_version': '3.7.4',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `COLORTERM`
  - `COMMONPROGRAMFILES`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `DRIVERDATA`
  - `EXEPATH`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `HOME`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `HOMESHARE`
  - `LANG`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `MSYSTEM`
  - `NUMBER_OF_PROCESSORS`
  - `OS`
  - `ONEDRIVE`
  - `ONEDRIVECONSUMER`
  - `ONLINESERVICES`
  - `PATH`
  - `PATHEXT`
  - `PIPENV_ACTIVE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PLINK_PROTOCOL`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_ARCHITEW6432`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMFILES`
  - `PROMPT`
  - `PS1`
  - `PSMODULEPATH`
  - `PTSMINSTALLPATH`
  - `PTSMINSTALLPATH_X86`
  - `PUBLIC`
  - `PWD`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `PROGRAMDATA`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `REGIONCODE`
  - `SESSIONNAME`
  - `SHLVL`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TERM`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `TMP`
  - `UATDATA`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VIRTUAL_ENV`
  - `VS140COMNTOOLS`
  - `WINDIR`
  - `_`
  - `PLATFORMCODE`
  - `PIP_SHIMS_BASE_MODULE`

Pipenv�specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug�specific environment variables:

  - `PATH`: `C:\Users\TTYY\git\.virtualenvs\test1-BtSuf0k4\Scripts;C:\Users\TTYY\AppData\Local\Programs\Git\mingw64\bin;C:\Users\TTYY\AppData\Local\Programs\Git\usr\bin;C:\Users\TTYY\git\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Python\Scripts;C:\Program Files (x86)\Python;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\windows\System32\OpenSSH;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\nodejs;C:\Program Files\Amazon\AWSCLI\bin;C:\Program Files\Amazon\AWSSAMCLI\bin;C:\Users\TTYY\AppData\Local\Microsoft\WindowsApps;C:\Users\TTYY\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\TTYY\AppData\Roaming\Python\Python37\Scripts;C:\Users\TTYY\AppData\Roaming\npm;C:\Users\TTYY\AppData\Local\Programs\Git\cmd;C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `C:/Users/TTYY/Documents/Visual Studio Code/test1`
  - `VIRTUAL_ENV`: `C:\Users\TTYY\git\.virtualenvs\test1-BtSuf0k4`

---------------------------

Contents of `Pipfile` ('C:\\Users\\TTYY\\Documents\\Visual Studio Code\\test1\\Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
serverless-python-requirements = "*"

[requires]
python_version = "3.7"

```

</details>

**Comment by frostming** [comment]
It is not a valid package on pypi.org so you can't installed it by pip or pipenv.

If you are meaning https://github.com/UnitedIncome/serverless-python-requirements, it seems like a plugin of Serverless developed with Javascript.

**Comment by pb321** [comment]
Hi frostming
thanks for your prompt reply.
if its not a valid package, why does it seem to install when using pip ?  its just that when I use pipenv, the problem exists

**Comment by frostming** [comment]
@pb321 No
```
pip3 install serverless-python-requirements
Looking in indexes: https://pypi.org/simple
Collecting serverless-python-requirements
  ERROR: Could not find a version that satisfies the requirement serverless-python-requirements (from versions: none)
ERROR: No matching distribution found for serverless-python-requirements
```

How did you succeed with it?

**Comment by pb321** [comment]
Apologies.  yes, it looks like pip also doesnt install serverless-python-requirements.  so, the only way i can install is via the serverless framework...

thanks for your time, its very much appreciated
