### ISSUE TITLE
Exception while Locking dependencieS

### ISSUE THREAD

**Issue by mian-bilal** [pypa/pipenv#3935]
### Issue description

Exception while installing rasa-x using `pipenv install rasa-x -i https://pypi.rasa.com/simple`

### Expected result
It should change lock file.

### Actual result

Exception 
```
Installing rasa-x…
⠋ Installing...Installing 'rasa-x'
$ ['/home/u/venv/bin/pip', 'install', '--verbose', '--upgrade', 'rasa-x', '-i', 'https://pypi.rasa.com/simple', '--extra-index-url', 'https://pypi.org/simple']
Adding rasa-x to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✘ Locking Failed! 
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  python-dotenv
  rasa-x

Finding the best candidates:
  found candidate python-dotenv==0.10.3 (constraint was <any>)
  found candidate rasa-x==0.0.2 (constraint was <any>)

Finding secondary dependencies:
  python-dotenv==0.10.3     requires -
  rasa-x==0.0.2 not in cache, need to check index
Traceback (most recent call last):
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/u/venv/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmp_7fl0hlkbuild/rasa-x/

```

### Steps to replicate

Try to install rasa-x in your env `pipenv install rasa-x -i https://pypi.rasa.com/simple`

-------------------------------------------------------------------------------

courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/u/venv/lib/python3.6/site-packages/pipenv'`

Python location: `'/home/u/venv/bin/python'`

Python installations found:

  - `3.7.4`: `/home/u/.pyenv/versions/3.7.4/bin/python3.7`
  - `3.7.4`: `/home/u/.pyenv/versions/3.7.4/bin/python3.7m`
  - `3.7.3`: `/usr/bin/python3.7`
  - `3.7.3`: `/usr/bin/python3.7m`
  - `3.6.8`: `/home/u/venv/bin/python3`
  - `3.6.8`: `/usr/bin/python3.6m`
  - `3.6.7`: `/home/u/.pyenv/versions/3.6.7/bin/python3.6m`
  - `3.6.7`: `/home/u/.pyenv/versions/3.6.7/bin/python3`
  - `2.7.15`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.8',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-60-generic',
 'platform_system': 'Linux',
 'platform_version': '#67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019',
 'python_full_version': '3.6.8',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `CLUTTER_IM_MODULE`
  - `NVM_DIR`
  - `LS_COLORS`
  - `_system_type`
  - `LC_MEASUREMENT`
  - `ALGOLIA_APPLIATION_ID`
  - `API_RESPONSE_LOG`
  - `MEMCACHEDCLOUD_PASSWORD`
  - `LESSCLOSE`
  - `SABRE_REST_CLIENT_ID`
  - `LC_PAPER`
  - `LC_MONETARY`
  - `ANDROID_HOME`
  - `XDG_MENU_PREFIX`
  - `VOX_URI`
  - `LANG`
  - `DISPLAY`
  - `rvm_bin_path`
  - `PYENV_ROOT`
  - `OLDPWD`
  - `ALGOLIA_INDEX_PREFIX`
  - `GNOME_SHELL_SESSION_MODE`
  - `APP_ID`
  - `rvm_version`
  - `RUBY_VERSION`
  - `COLORTERM`
  - `MAIL_FROM_ADDRESS`
  - `NVM_CD_FLAGS`
  - `GEM_HOME`
  - `PYENV_VIRTUALENV_INIT`
  - `USERNAME`
  - `CAMPAIGN_MONITOR_API_KEY`
  - `PAPERTRAIL_API_TOKEN`
  - `MAILGUN_API_KEY`
  - `SERVER_URL`
  - `XDG_VTNR`
  - `ALGOLIA_API_KEY`
  - `PUSH_IOS_BUNDLE_ID`
  - `SSH_AUTH_SOCK`
  - `VIRTUAL_ENV`
  - `SABRE_API_URL`
  - `SABRE_API_KEY`
  - `MANDATORY_PATH`
  - `S_COLORS`
  - `MEMCACHED_ENABLED`
  - `MEMCACHED_CONTENT_TTL`
  - `LC_NAME`
  - `XDG_SESSION_ID`
  - `INSTAGRAM_APP_SECRET`
  - `USER`
  - `INSTA_APPIDS`
  - `DESKTOP_SESSION`
  - `S3_BUCKET`
  - `QT4_IM_MODULE`
  - `TEXTDOMAINDIR`
  - `INSTAGRAM_USER_TOKEN`
  - `S3_DIRECT_ACCESS`
  - `TWILIO_NUMBER`
  - `GNOME_TERMINAL_SCREEN`
  - `SABRE_BRIDGE_CARD_EXPIRE_YEAR`
  - `DEFAULTS_PATH`
  - `MAILCHIMP_API_KEY`
  - `JAVASCRIPT_KEY`
  - `PWD`
  - `_system_version`
  - `HOME`
  - `TEXTDOMAIN`
  - `MONGODB_URI`
  - `_system_name`
  - `SSH_AGENT_PID`
  - `STRIPE_API_KEY`
  - `QT_ACCESSIBILITY`
  - `MEMCACHEDCLOUD_SERVERS`
  - `XDG_SESSION_TYPE`
  - `RAILS_SERVE_STATIC_FILES`
  - `XDG_DATA_DIRS`
  - `TWILIO_AUTH_TOKEN`
  - `INSTAGRAM_APP_ID`
  - `_system_arch`
  - `PARSE_MOUNT`
  - `XDG_SESSION_DESKTOP`
  - `GEM_PATH`
  - `MEMCACHEDCLOUD_USERNAME`
  - `S3_SECRET_KEY`
  - `LC_ADDRESS`
  - `S3_ACCESS_KEY`
  - `GJS_DEBUG_OUTPUT`
  - `LC_NUMERIC`
  - `X_Voxiplan_Session_ID`
  - `SABRE_BRIDGE_CARD_EXPIRE_MONTH`
  - `API_REQUEST_LOG`
  - `X_Voxiplan_API_Key`
  - `APP_NAME`
  - `GTK_MODULES`
  - `MAILGUN_DOMAIN`
  - `rvm_path`
  - `WINDOWPATH`
  - `TERM`
  - `VTE_VERSION`
  - `SHELL`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `IM_CONFIG_PHASE`
  - `NVM_BIN`
  - `SPREEDLY_ENV_KEY`
  - `XDG_CURRENT_DESKTOP`
  - `WEBSITE_URL`
  - `GPG_AGENT_INFO`
  - `SABRE_BRIDGE_CARD_NUMBER`
  - `GNOME_TERMINAL_SERVICE`
  - `MASTER_KEY`
  - `REDIS_URL`
  - `rvm_prefix`
  - `SABRE_REST_ENDPOINT`
  - `TWILIO_ACCOUNT_SID`
  - `INSTA_SECRETS`
  - `PYENV_SHELL`
  - `SHLVL`
  - `XDG_SEAT`
  - `SPREEDLY_API_SECRET`
  - `SABRE_REST_SECRET`
  - `LC_TELEPHONE`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `MY_RUBY_HOME`
  - `XDG_CONFIG_DIRS`
  - `GOOGLE_API_KEY`
  - `PATH`
  - `LC_IDENTIFICATION`
  - `PS1`
  - `SABRE_BRIDGE_CARD_HOLDER`
  - `MEMCACHED_PROFILE_TTL`
  - `PUBLIC_URL`
  - `IRBRC`
  - `INSTAGRAM_WEBHOOK_TOKEN`
  - `GJS_DEBUG_TOPICS`
  - `SESSION_MANAGER`
  - `LESSOPEN`
  - `GTK_IM_MODULE`
  - `LC_TIME`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/u/venv/bin:/home/u/.pyenv/plugins/pyenv-virtualenv/shims:/home/u/.pyenv/shims:/home/u/.pyenv/bin:/home/u/.nvm/versions/node/v8.12.0/bin:/home/u/.rvm/gems/ruby-2.4.4/bin:/home/u/.rvm/gems/ruby-2.4.4@global/bin:/home/u/.rvm/rubies/ruby-2.4.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/u/.rvm/bin:/home/u/.rvm/bin:/home/u/.rvm/bin:/home/u/.rvm/bin:/home/u/Android/Sdk/tools:/home/u/Android/Sdk/platform-tools:/home/u/.rvm/bin:/home/u/.rvm/bin:/home/u/.rvm/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/u/voxiplan-ai-bot`
  - `VIRTUAL_ENV`: `/home/u/venv`

---------------------------

Contents of `Pipfile` ('/home/u/voxiplan-ai-bot/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
python-dotenv = "*"
rasa-x = {index = "https://pypi.rasa.com/simple",version = "*"}

[requires]
python_version = "3.6"

```

</details>

**Comment by tapaswenipathak** [comment]
Hi folks: Can I write a doc for the issue?

**Comment by cruzelante098** [comment]
This issue it's still happening with pipenv, version 2020.8.13.

**Comment by matteius** [comment]
Can this be checked with `pipenv==2022.8.19`?
