### ISSUE TITLE
Hangs on "installing" for any package

### ISSUE THREAD

**Issue by waydegg** [pypa/pipenv#3941]
I've tried installing Pipenv with using both Pip and Linuxbrew and haven't made any progress with this. The steps I've taken to get to where I'm at now are:

1. Make a new Pipenv enviornment with ```pipenv --python 3```
2. Go into pipenv shell with ```pipenv shell```
3. Try to install a package with ```pipenv install [package name]```

-------------------------------------------------------------------------------

Here is the output I get from running ```pipenv --suport```:

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/bin/python3.7'`

Python installations found:

  - `3.7.4`: `/home/linuxbrew/.linuxbrew/bin/python3.7m`
  - `3.7.4`: `/home/linuxbrew/.linuxbrew/bin/python3`
  - `3.6.8`: `/usr/bin/python3.6m`
  - `3.6.8`: `/usr/bin/python3`
  - `3.6.5`: `/usr/local/bin/python3.6m`
  - `3.6.5`: `/usr/local/bin/python3`
  - `2.7.15`: `/usr/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.0.0-27-generic',
 'platform_system': 'Linux',
 'platform_version': '#28~18.04.1-Ubuntu SMP Thu Aug 22 03:00:32 UTC 2019',
 'python_full_version': '3.7.4',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `PATH`
  - `SSH_CONNECTION`
  - `_`
  - `LANG`
  - `PYENV_ROOT`
  - `OLDPWD`
  - `XDG_SESSION_ID`
  - `USER`
  - `PWD`
  - `HOME`
  - `SSH_CLIENT`
  - `XDG_DATA_DIRS`
  - `HOMEBREW_REPOSITORY`
  - `SSH_TTY`
  - `MAIL`
  - `SHELL`
  - `TERM`
  - `SHLVL`
  - `PYENV_SHELL`
  - `HOMEBREW_PREFIX`
  - `MANPATH`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `HOMEBREW_CELLAR`
  - `INFOPATH`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/tools:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/waydegg/.pyenv/shims:/home/waydegg/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/waydegg/development/projects/time_series`

---------------------------

Contents of `Pipfile` ('/home/waydegg/development/projects/time_series/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "3.7"

```

</details>

**Comment by frostming** [comment]
Thousands of people are using pipenv installed from pip or linuxbrew, and all work fine. You need to provide more information, such as internet connection conditions, anything that makes the debugging easier otherwise we can't help. You can start with providing verbose output with `pipenv  install -v [package]`

**Comment by waydegg** [comment]
Here's the output for ```pipenv install -v numpy``` (I get the same "hanging" for any package I've tried installing):

```
Installing numpy…
⠋ Installing...Installing 'numpy'
$ ['/home/waydegg/.local/share/virtualenvs/time_series-upgwTY4P/bin/pip', 'install', '--verbose', '--upgrade', 'numpy', '-i', 'https://pypi.org/simple']
⠇ Installing...
```

In terms of internet connection conditions, I'm not sure what you'd like to see.

**Comment by frostming** [comment]
You said "any" so I recommend you test `first` package, also try `pip install -i https://pypi.org/simple first`

**Comment by matteius** [comment]
@waydegg Closing this due to being stale issue.  Please report back any new issues with `pipenv==2022.1.8`
