### ISSUE TITLE
[Proposal] Add troubleshooting instructions  in documentation

### ISSUE THREAD

**Issue by tapaswenipathak** [pypa/pipenv#3944]
Hi folks!

**Visibility Ticket**

An open source contributor and maintainer here, find my work using @tapaswenipathak on web. I saw a lot of tickets where users state that the documentation requires a lot of improvement. Can I take the responsibility of adding troubleshooting instructions and improvement in the documentation in general. I am writing a ticket for more votes than just one maintainer. @frostming opinions of course I respect.  

Samples:
- https://github.com/pypa/pipenv/pull/3940.
- https://github.com/pypa/pipenv/pull/3939#discussion_r322034530.

**Comment by ParthCheulkar** [comment]
what is this project about?

**Comment by matteius** [comment]
@tapaswenipathak If there are documentation improvements you wish to make, feel free to open a PR.   Since this is an old issue I am going to close it out for the time being.
