### ISSUE TITLE
Use environment variable to determine whether to install development dependencies.

### ISSUE THREAD

**Issue by cmackenziek** [pypa/pipenv#3950]
### Problem description.
I'm currently using Docker with Pipenv for a project. Building a container for development requires using the `--dev` flag when running `pipenv sync` or `pipenv install`. Building for production/staging, on the other hand, doesn't.

This means that you currently have to introduce conditionals in a Dockerfile to determine whether or not the flag is needed, or maintain two separate Dockerfiles for the two different builds.

### Proposed solution.
I think the use of an environment variable to determine whether or not to install development dependencies when running `pipenv install` or `pipenv sync` would be a cleaner solution to this problem. Something like `PIPENV_INSTALL_DEV`. I believe npm does something similar with an environment variable called `NODE_ENV`.

If this sounds like a good idea I'd gladly try and submit a PR for this.

**Comment by frostming** [comment]
Yeah, it is already there: `PIPENV_DEV`

**Comment by schuderer** [comment]
Just as a general hint: If you need this kind of flexibility in any command line tool within your pipeline, remember that you can use environment variables within command lines in your pipeline scripts:
```
$ export LSTEST=
$ ls $LSTEST  # just an example command which could be part of your pipeline
a.txt
$ _

vs 

$ export LSTST=-a
$ ls $LSTEST  # exactly same command, different result due to different environment variable
. .. .gitignore a.txt
$ _
```

**Comment by cmackenziek** [comment]
> Yeah, it is already there: `PIPENV_DEV`

This variable doesn't appear to be documented. Shouldn't it be listed in here?: https://pipenv.readthedocs.io/en/latest/advanced/#configuration-with-environment-variables

**Comment by cmackenziek** [comment]
> Just as a general hint: If you need this kind of flexibility in any command line tool within your pipeline, remember that you can use environment variables within pretty much any command line in your scripts:
> 
> ```
> $ export LSTEST=
> $ ls $LSTEST  # just an example command which could be part of your pipeline
> a.txt
> $ _
> 
> vs 
> 
> $ export LSTST=-a
> $ ls $LSTEST  # exactly same command, different result due to different environment variable
> . .. .gitignore a.txt
> $ _
> ```

Thanks! This is actually a very clean way of implementing what I need.
