### ISSUE TITLE
Packages missing from Pipfile.lock if those packages are present in the current working directory

### ISSUE THREAD

**Issue by timthelion** [pypa/pipenv#3953]
### Issue description

If you have specified that a package be installed via the `Pipfile` and the source tree of that package is present in the project directory then `Pipfile.lock` will not contain that package.

### Expected result

Either there should be an error, or pipenv should lock normally.

### Actual result

`Pipfile.lock` simply doesn't contain the requested package.

### Steps to replicate

````
$ mkdir pkpenv-test
$ pipenv install subuser
$ cat Pipfile
$ cat Pipfile.lock # Note that the subuser package is there
$ git clone https://github.com/subuser-security/subuser.git
$ pipenv lock
$ cat Pipfile.lock # Subuser package is missing from lock file.
````

### Version info

    > pipenv --version
    pipenv, version 2018.10.13

**Comment by frostming** [comment]
Can't reproduce with the master branch(https://github.com/pypa/pipenv/commit/7a12dbb5cacc71d1dd2d74d8cce8eb50ce2db121)

**Comment by nuthingman** [comment]
This is what I did. Not sure if this is exactly what you wanted.

`$ mkdir pkpenv-test
$ cd pkpenv-test/
$ pipenv install
$ git clone https://github.com/subuser-security/subuser.git
$ pipenv install -e subuser
$ cat Pipfile
$ cat Pipfile.lock `

**Comment by timthelion** [comment]
@nuthingman thanks :) . As it turns out, I actually came across this bug because I had done exactly as you suggest. I had a package installed for editing and marked as such in the `Pipfile`. Then switched git branches to a branch where the package was not marked for editing in the `Pipfile` and all of a sudden the package was missing from `Pipenv.lock` and I couldn't figure out why.

**Comment by matteius** [comment]
@timthelion I suspect this is closeable at this point, but let us know if still an issue with `2022.1.8`
