### ISSUE TITLE
Add ability to ban a dependency

### ISSUE THREAD

**Issue by timthelion** [pypa/pipenv#3954]
### Is your feature request related to a problem? Please describe.

The packages jsonfield and django-jsonfield both add the same module with the same functionality. Pipenv has no fixed order of installation for dependencies. This means that if you use libraries that depend on both, sometimes you'll end up with one package installed and sometimes you'll end up with the other. [This leads to extremely weird situations](https://github.com/areski/django-admin-tools-stats/pull/49). Currently it seems that the only way to deal with this situation is by using a [version marker to ban one of the packages](https://stackoverflow.com/questions/57959565/how-can-i-ban-a-package-from-being-added-to-pipenv-lock-and-installed-by-pipenv/57982959#57982959).

### Describe the solution you'd like

I'd like

````
django-jsonfield = { markers="False" }
````

To ban that package from being installed.

**Comment by frostming** [comment]
set a non-existing value for marker would do the trick

`os_name="=='foo'"`

**Comment by timthelion** [comment]
@frostming it works, but it is a dirty hack. It is not at all clear from the code `os_name = "foo"` that you want to ban the dependency.

**Comment by matteius** [comment]
With category based installs it will be possible to have orders to install dependencies by creating new categories such as prerequisites.   There is a working prototype branch of this and the plan is to open the PR around October 1st for Hacktoberfest.   You can track that work here:  https://github.com/pypa/pipenv/issues/4745
