### ISSUE TITLE
Error when use pipeline in linux

### ISSUE THREAD

**Issue by nkthanh98** [pypa/pipenv#3957]
### Issue description

pipenv throws BrokenPipelineError when use pipeline for filter output

### Expected result

Don't throw exception

### Actual result

pipenv throws BrokenPipelineError

### Steps to replicate

pipenv run pip search numpy | head -n5 

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.7'`

Python installations found:

  - `3.7.4`: `/usr/local/bin/python3`
  - `3.7.4`: `/usr/local/bin/python3.7m`
  - `3.7.3`: `/Users/nkthanh/.pyenv/versions/3.7.3/bin/python3`
  - `3.7.3`: `/Users/nkthanh/.pyenv/versions/3.7.3/bin/python3.7m`
  - `3.6.8`: `/Users/nkthanh/.pyenv/versions/3.6.8/bin/python3`
  - `3.6.8`: `/Users/nkthanh/.pyenv/versions/3.6.8/bin/python3.6m`
  - `3.6.1`: `/Users/nkthanh/.pyenv/versions/pypy3.6-7.1.1/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`
  - `2.7.9`: `/Users/nkthanh/.pyenv/versions/2.7.9/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT '
                     '2019; root:xnu-4903.271.2~2/RELEASE_X86_64',
 'python_full_version': '3.7.4',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_SESSION_ID`
  - `SSH_AUTH_SOCK`
  - `Apple_PubSub_Socket_Render`
  - `COLORFGBG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `PWD`
  - `SHELL`
  - `LC_CTYPE`
  - `TERM_PROGRAM_VERSION`
  - `TERM_PROGRAM`
  - `PATH`
  - `COLORTERM`
  - `TERM`
  - `HOME`
  - `TMPDIR`
  - `USER`
  - `XPC_SERVICE_NAME`
  - `LOGNAME`
  - `__CF_USER_TEXT_ENCODING`
  - `ITERM_SESSION_ID`
  - `SHLVL`
  - `OLDPWD`
  - `ZSH`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYENV_ROOT`
  - `PIPENV_PYTHON`
  - `JAVA_HOME`
  - `JRE_PATH`
  - `M2_HOME`
  - `M2`
  - `LC_ALL`
  - `LANG`
  - `PYENV_SHELL`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PIPENV_ACTIVE`
  - `VIRTUAL_ENV`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_PYTHON`: `/Users/nkthanh/.pyenv/shims/python`
 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/nkthanh/.local/share/virtualenvs/demo-OzheZQoG-/Users/nkthanh/.pyenv/shims/python/bin:/Users/nkthanh/.pyenv/shims:/Users/nkthanh/.iterm2:/usr/local/opt/apache-maven-3.6.1/bin:/Users/nkthanh/.pyenv/bin:/Users/nkthanh/.pyenv/shims:/Users/nkthanh/.iterm2:/usr/local/opt/apache-maven-3.6.1/bin:/Users/nkthanh/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/tmp/demo`
  - `VIRTUAL_ENV`: `/Users/nkthanh/.local/share/virtualenvs/demo-OzheZQoG-/Users/nkthanh/.pyenv/shims/python`

---------------------------

Contents of `Pipfile` ('/private/tmp/demo/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/private/tmp/demo/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "415dfdcb118dd9bdfef17671cb7dcd78dbd69b6ae7d4f39e8b44e71d60ca72e7"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

**Comment by Sheshtawy** [comment]
I would like to give this a go if that's okay

**Comment by chaps** [comment]
running :
`pip search numpy | head -n5`
returns the following error:

```
pip search numpy | head -n 5
numpy (1.17.2)                         - NumPy is the fundamental package for array computing with Python.
numpy-cloud (0.0.5)                    - Numpy in the cloud
numpy-utils (0.1.6)                    - NumPy utilities.
numpy-sugar (1.5.0)                    - Missing NumPy functionalities
numpy-turtle (0.2)                     - Turtle graphics with NumPy
ERROR: Pipe to stdout was broken
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```
Could this be a `pip` issue instead?

**Comment by josher19** [comment]
I think the error is actually in pip not in pipenv:
`pip search numpy | head -n5`

**Comment by josher19** [comment]
There is a work-around: `pipenv run pip search pipenv | tail -n +1 | head -n5`

**Comment by frostming** [comment]
As shown by @chaps it is an issue with pip and I recommend to raise this in pip instead.
