### ISSUE TITLE
[Gif] not found 

### ISSUE THREAD

**Issue by Sim4n6** [pypa/pipenv#3961]
### Issue description
Gif not found at [location](https://s3.amazonaws.com/media.kennethreitz.com/pipenv.gif)

### Actual result
`<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>media.kennethreitz.com</BucketName><RequestId>32A928CA7C20BCE9</RequestId><HostId>Pl6hW0jkPaLjtvv605DvH4GwfRQFvxxVFklCP2yWi8ET8+bUKCyEHODZfUkRR/4p0l6u1DsSFDk=</HostId></Error>`

### Steps to replicate

1. goto https://pipenv-fork.readthedocs.io/en/latest/
1. click on "Short animation of pipenv at work"

**Comment by frostming** [comment]
The GIF location is already updated in the official site
![image](https://user-images.githubusercontent.com/16336606/65667317-11bcf300-e072-11e9-85ae-58490992939d.png)
