### ISSUE TITLE
pipenv sync shows misleading error when only Pipfile.lock is present

### ISSUE THREAD

**Issue by joekohlsdorf** [pypa/pipenv#3963]
### Issue description

When running `pipenv sync` with only `Pipfile.lock` present an error is shown that `Pipfile.lock` is not present.

### Expected result

An error is shown that `Pipfile` is missing. Or even better `pipenv sync` should work without a `Pipfile` being present.

### Actual result

An error is shown that `Pipfile.lock` is missing but it is present.

### Steps to replicate

```
rm Pipfile
pipenv sync
```

Output:
```
[pipenv.exceptions.LockfileNotFound]:   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
[pipenv.exceptions.LockfileNotFound]:       return ctx.invoke(f, obj, *args, **kwargs)
[pipenv.exceptions.LockfileNotFound]:   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
[pipenv.exceptions.LockfileNotFound]:       return callback(*args, **kwargs)
[pipenv.exceptions.LockfileNotFound]:   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
[pipenv.exceptions.LockfileNotFound]:       return f(get_current_context(), *args, **kwargs)
[pipenv.exceptions.LockfileNotFound]:   File "/usr/local/lib/python3.7/site-packages/pipenv/cli/command.py", line 615, in sync
[pipenv.exceptions.LockfileNotFound]:       pypi_mirror=state.pypi_mirror,
[pipenv.exceptions.LockfileNotFound]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 2589, in do_sync
[pipenv.exceptions.LockfileNotFound]:       raise exceptions.LockfileNotFound("Pipfile.lock")
ERROR: Pipfile.lock not found! You need to run $ pipenv lock before you can continue.
```

**Comment by frostming** [comment]
I believe this is reported somewhere, i am also not sure if it was fixed on master branch, can you have a try?

**Comment by Urhengulas** [comment]
@frostming Yes. It seems solved

**Verification:**
I verified by setting up the dev-env according to [here](https://github.com/pypa/pipenv/blob/master/CONTRIBUTING.md#development-setup-dev-setup) and then running:
```bash
$ pipenv --version
pipenv, version 2018.11.27.dev0
$ pipenv install
...
$ rm Pipfile
$ ls
Pipfile.lock
$ pipenv sync
Creating a Pipfile for this project…
Installing dependencies from Pipfile.lock (a65489)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
All dependencies are now up-to-date!
$ ls
Pipfile  Pipfile.lock
```

**Test Configuration**:
* Pipenv version: 2018.11.27.dev0
* OS: python:3.7 docker container on ubuntu 19.10
* python version: 3.7

I thereby think this issue can be marked as solved.

**Comment by EydenVillanueva** [comment]
So in the end, this issue is already solved? Can we close this issue if it is?

**Comment by Licho59** [comment]
I don't think so. Urhengulas has shown the part-way result in my opinion - it has not been confirmed the content of the Pipfile. My testing also results in creating Pipfile but it has only basic structure with python version and empty [packages] part;
 'check', 'sync', 'install --dev' do not change it.... so if the issue's acceptable solution should be Pipfile as  it was before deleting there is still need for finding it:).
I am a real freshman in programming so few chances to do it myself :) but the pipenv project seems to me really attractive and absolutely worthy of continuation, it is also my first effort in learning how libraries work and how to participate/contribute in open source projects.

**Comment by matteius** [comment]
I believe this error is no longer present.   We are tracking getting pipenv sync to work properly without the sources from the Pipfile in this ticket:  #5353
