### ISSUE TITLE
Meta: github link to docs invalid

### ISSUE THREAD

**Issue by thomas-mc-work** [pypa/pipenv#3974]
### Issue description

The link to the docs next to the project name is broken. It points to a dead end: <https://docs.pipenv.org/>.

### Expected result

Bring me to a valid location of the docs.

### Solution

<https://pipenv.kennethreitz.org/en/latest/>

**Comment by frostming** [comment]
Fixed

**Comment by thomas-mc-work** [comment]
You're welcome.
