### ISSUE TITLE
Pipenv fails to resolve subdependency

### ISSUE THREAD

**Issue by lounis** [pypa/pipenv#3976]
Hi
### Issue description
when i run 
pip3.6 install -r requirements.txt -t _build
every think is ok but if i run PIPENV_VENV_IN_PROJECT=true pipenv --python 3.6 install i have this error ERROR: Could not find a version that matches

**Comment by frostming** [comment]
A reproducible example is greate but you'd better provide the full error output, too.

**Comment by lounis** [comment]
Hi, thanks for your comment
```
git clone https://github.com/lounis/test-pep508.git
 cd test-pep508/
PIPENV_VENV_IN_PROJECT=true pipenv --python 3.6 install
Creating a virtualenv for this project…
Pipfile: /home/lounis/rd00/test-pep508/Pipfile
Using /usr/local/bin/python3.6m (3.6.0) to create virtualenv…
⠦ Creating virtual environment...Using base prefix '/usr/local'
New python executable in /home/lounis/rd00/test-pep508/.venv/bin/python3.6m
Also creating executable in /home/lounis/rd00/test-pep508/.venv/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/local/bin/python3.6m

✔ Successfully created virtual environment! 
Virtualenv location: /home/lounis/rd00/test-pep508/.venv
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✘ Locking Failed! 
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.6/site-packages/pipenv/resolver.py", line 69, in resolve
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches pyfatal_cassandra@ git+https://github.com/lounis/python-test.git@0.0.1#egg=pyfatal_cassandra&subdirectory=src/DB/Cassandra from git+https://github.com/lounis/python-test.git@0.0.1#egg=pyfatal_cassandra&subdirectory=src/DB/Cassandra
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches pyfatal_cassandra@ git+https://github.com/lounis/python-test.git@0.0.1#egg=pyfatal_cassandra&subdirectory=src/DB/Cassandra from git+https://github.com/lounis/python-test.git@0.0.1#egg=pyfatal_cassandra&subdirectory=src/DB/Cassandra
No versions found
Was https://pypi.org/simple reachable?
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches pyfatal_cassandra@ git+https://github.com/lounis/python-test.git@0.0.1#egg=pyfatal_cassandra&subdirectory=src/DB/Cassandra from git+https://github.com/lounis/python-test.git@0.0.1#egg=pyfatal_cassandra&subdirectory=src/DB/Cassandra
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches pyfatal_cassandra@ git+https://github.com/lounis/python-test.git@0.0.1#egg=pyfatal_cassandra&subdirectory=src/DB/Cassandra from git+https://github.com/lounis/python-test.git@0.0.1#egg=pyfatal_cassandra&subdirectory=src/DB/Cassandra
No versions found
Was https://pypi.org/simple reachable
```

But if i use requirements.txt
```
pip3.6 install -r requirements.txt -t _build
Collecting pyfatal_organization from git+https://github.com/lounis/python-test.git@0.0.1#egg=pyfatal_organization&subdirectory=src/Organization (from -r requirements.txt (line 1))
  Cloning https://github.com/lounis/python-test.git (to revision 0.0.1) to /tmp/pip-install-5iybzglz/pyfatal-organization
  Running command git clone -q https://github.com/lounis/python-test.git /tmp/pip-install-5iybzglz/pyfatal-organization
  Running command git checkout -q 01e48ed784185af35ca1fc754c98cbae67383dc7
Collecting pyfatal_cassandra@ git+https://github.com/lounis/python-test.git@0.0.1#egg=pyfatal_cassandra&subdirectory=src/DB/Cassandra from git+https://github.com/lounis/python-test.git@0.0.1#egg=pyfatal_cassandra&subdirectory=src/DB/Cassandra (from pyfatal_organization->-r requirements.txt (line 1))
  Cloning https://github.com/lounis/python-test.git (to revision 0.0.1) to /tmp/pip-install-5iybzglz/pyfatal-cassandra
  Running command git clone -q https://github.com/lounis/python-test.git /tmp/pip-install-5iybzglz/pyfatal-cassandra
  Running command git checkout -q 01e48ed784185af35ca1fc754c98cbae67383dc7
Collecting cassandra-driver>=3.18.0 (from pyfatal_cassandra@ git+https://github.com/lounis/python-test.git@0.0.1#egg=pyfatal_cassandra&subdirectory=src/DB/Cassandra->pyfatal_organization->-r requirements.txt (line 1))
Collecting six>=1.9 (from cassandra-driver>=3.18.0->pyfatal_cassandra@ git+https://github.com/lounis/python-test.git@0.0.1#egg=pyfatal_cassandra&subdirectory=src/DB/Cassandra->pyfatal_organization->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: six, cassandra-driver, pyfatal-cassandra, pyfatal-organization
  Running setup.py install for pyfatal-cassandra ... done
  Running setup.py install for pyfatal-organization ... done
Successfully installed cassandra-driver-3.19.0 pyfatal-cassandra-0.0.1 pyfatal-organization-0.0.1 six-1.12.0
```

Best regards

**Comment by scizzorz** [comment]
I'm also having this problem - it seems to be from the dependency's `setup.py` containing git-ssh URLs in the `install_requires` field.

**Comment by lounis** [comment]
yes it is, but how to include into https://github.com/lounis/python-test/tree/master/src/Organization this dependence https://github.com/lounis/python-test/tree/master/src/DB/Cassandra knowing that dependency_links is deprecated?

**Comment by CharString** [comment]
I bumped into this one too. It's not just git-ssh sources. Dependencies like

    setup(
        ...
        install_requires=['package@https://kallithea.example.com/package/archive/default.zip'],
        ...
    )

show the same problem. Seems like '@' in install_requires doesn't get handled the way pip or running setup.py install handle them.

**Comment by lounis** [comment]
@CharString it is not the same bug, in your use case the solution is to add space before and after @ like this 
```
setup(
    ...
    install_requires=['package @ https://kallithea.example.com/package/archive/default.zip'],
    ...
)
```

**Comment by lounis** [comment]
Hi
@frostming any news?
Best regards

**Comment by zicvic** [comment]
Not sure if this is relevant here but I'm running into a similar issue (I guess...) anyway.

I have three packages with the following dependencies: 

```
package_a
   |__ package_b
            |__ package_c
```

In the different packages I have the following setup
### package_a
`package_a/Pipfile`
```
[packages]
...
package_b = {git = "https://github.com/package-b-repo.git",ref = "master"}
...
```

### package_b

`package_b/setup.py`
```
setup(
...
install_requires=[
        'package_c @ git+https://github.com/package-c-repo.git@master#egg=package_c'
    ]
...
)
```

I have installed this once and all worked fine. But when a make an update to `package_c`, push that to master (no I'm not pushing directly to master, but for simplicity thats what happens), then run `pipenv update` in `package_b` everything seems to work. Committing changes and pushes to master on package-g-repo. Now when I run `pipenv update` in `package_a` the updates from package_b is pulled but any updates from the subdependency in package_c is not propagated up to `package_a`. Any thoughts? 

I know this might be the wrong place to put this but anyhow, it might shine some light on something..

**Comment by netokey** [comment]
I think I have got the same problem
I ran the command `pipenv install xlsxwriter`
got the result below.
![image](https://user-images.githubusercontent.com/8610939/68267633-0d7eef00-008e-11ea-9862-b780759e58f6.png)
notice the yellow frame above, the name is not the same one.
I installed the package named "xlsxwriter", but the error mentioned a package named "xlxswriter".

**Comment by frostming** [comment]
@netokey Because you have a wrong entry in your Pipfile?

**Comment by netokey** [comment]
@frostming yes, I ran a command like 'pipenv install xlxswriter' before. It is not a valid package, but the Pipfile still record the package name.

**Comment by Allan-Nava** [comment]
I got the same error:

 
Installing asgiref…
Adding asgiref to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock (9903ff) out of date, updating to (1b3dc9)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✘ Locking Failed! 
[pipenv.exceptions.ResolutionFailure]:   File "/Users/allan/.local/share/virtualenvs/PasticceriaBesuschio-SFC09LCX/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "/Users/allan/.local/share/virtualenvs/PasticceriaBesuschio-SFC09LCX/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "/Users/allan/.local/share/virtualenvs/PasticceriaBesuschio-SFC09LCX/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/Users/allan/.local/share/virtualenvs/PasticceriaBesuschio-SFC09LCX/lib/python3.7/site-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches asgiref~=2.0.1,~=2.1
[pipenv.exceptions.ResolutionFailure]:       Tried: 0.8, 0.9, 0.9.1, 0.10.0, 0.11.0, 0.11.0, 0.11.0, 0.11.1, 0.11.1, 0.11.2, 0.11.2, 0.12.0, 0.12.0, 0.12.1, 0.12.1, 0.13.0, 0.13.0, 0.13.2, 0.13.2, 0.13.3, 0.14.0, 0.14.0, 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.1.0, 1.1.0, 1.1.1, 1.1.1, 1.1.2, 1.1.2, 2.0.0, 2.0.0, 2.0.1, 2.0.1, 2.1.0, 2.1.0, 2.1.1, 2.1.1, 2.1.2, 2.1.2, 2.1.3, 2.1.3, 2.1.4, 2.1.4, 2.1.5, 2.1.5, 2.1.6, 2.1.6, 2.2.0, 2.2.0, 2.3.0, 2.3.0, 2.3.1, 2.3.1, 2.3.2, 2.3.2, 3.0.0, 3.0.0, 3.1.0, 3.1.0, 3.1.1, 3.1.1, 3.1.2, 3.1.2, 3.1.3, 3.1.3, 3.1.4, 3.1.4, 3.2.0, 3.2.0, 3.2.1, 3.2.1, 3.2.2, 3.2.2, 3.2.3, 3.2.3
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches asgiref~=2.0.1,~=2.1
Tried: 0.8, 0.9, 0.9.1, 0.10.0, 0.11.0, 0.11.0, 0.11.0, 0.11.1, 0.11.1, 0.11.2, 0.11.2, 0.12.0, 0.12.0, 0.12.1, 0.12.1, 0.13.0, 0.13.0, 0.13.2, 0.13.2, 0.13.3, 0.14.0, 0.14.0, 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.1.0, 1.1.0, 1.1.1, 1.1.1, 1.1.2, 1.1.2, 2.0.0, 2.0.0, 2.0.1, 2.0.1, 2.1.0, 2.1.0, 2.1.1, 2.1.1, 2.1.2, 2.1.2, 2.1.3, 2.1.3, 2.1.4, 2.1.4, 2.1.5, 2.1.5, 2.1.6, 2.1.6, 2.2.0, 2.2.0, 2.3.0, 2.3.0, 2.3.1, 2.3.1, 2.3.2, 2.3.2, 3.0.0, 3.0.0, 3.1.0, 3.1.0, 3.1.1, 3.1.1, 3.1.2, 3.1.2, 3.1.3, 3.1.3, 3.1.4, 3.1.4, 3.2.0, 3.2.0, 3.2.1, 3.2.1, 3.2.2, 3.2.2, 3.2.3, 3.2.3
There are incompatible versions in the resolved dependencies.
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "/Users/allan/.local/share/virtualenvs/PasticceriaBesuschio-SFC09LCX/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "/Users/allan/.local/share/virtualenvs/PasticceriaBesuschio-SFC09LCX/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/Users/allan/.local/share/virtualenvs/PasticceriaBesuschio-SFC09LCX/lib/python3.7/site-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches asgiref~=2.0.1,~=2.1
[pipenv.exceptions.ResolutionFailure]:       Tried: 0.8, 0.9, 0.9.1, 0.10.0, 0.11.0, 0.11.0, 0.11.0, 0.11.1, 0.11.1, 0.11.2, 0.11.2, 0.12.0, 0.12.0, 0.12.1, 0.12.1, 0.13.0, 0.13.0, 0.13.2, 0.13.2, 0.13.3, 0.14.0, 0.14.0, 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.1.0, 1.1.0, 1.1.1, 1.1.1, 1.1.2, 1.1.2, 2.0.0, 2.0.0, 2.0.1, 2.0.1, 2.1.0, 2.1.0, 2.1.1, 2.1.1, 2.1.2, 2.1.2, 2.1.3, 2.1.3, 2.1.4, 2.1.4, 2.1.5, 2.1.5, 2.1.6, 2.1.6, 2.2.0, 2.2.0, 2.3.0, 2.3.0, 2.3.1, 2.3.1, 2.3.2, 2.3.2, 3.0.0, 3.0.0, 3.1.0, 3.1.0, 3.1.1, 3.1.1, 3.1.2, 3.1.2, 3.1.3, 3.1.3, 3.1.4, 3.1.4, 3.2.0, 3.2.0, 3.2.1, 3.2.1, 3.2.2, 3.2.2, 3.2.3, 3.2.3
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches asgiref~=2.0.1,~=2.1
Tried: 0.8, 0.9, 0.9.1, 0.10.0, 0.11.0, 0.11.0, 0.11.0, 0.11.1, 0.11.1, 0.11.2, 0.11.2, 0.12.0, 0.12.0, 0.12.1, 0.12.1, 0.13.0, 0.13.0, 0.13.2, 0.13.2, 0.13.3, 0.14.0, 0.14.0, 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.1.0, 1.1.0, 1.1.1, 1.1.1, 1.1.2, 1.1.2, 2.0.0, 2.0.0, 2.0.1, 2.0.1, 2.1.0, 2.1.0, 2.1.1, 2.1.1, 2.1.2, 2.1.2, 2.1.3, 2.1.3, 2.1.4, 2.1.4, 2.1.5, 2.1.5, 2.1.6, 2.1.6, 2.2.0, 2.2.0, 2.3.0, 2.3.0, 2.3.1, 2.3.1, 2.3.2, 2.3.2, 3.0.0, 3.0.0, 3.1.0, 3.1.0, 3.1.1, 3.1.1, 3.1.2, 3.1.2, 3.1.3, 3.1.3, 3.1.4, 3.1.4, 3.2.0, 3.2.0, 3.2.1, 3.2.1, 3.2.2, 3.2.2, 3.2.3, 3.2.3
There are incompatible versions in the resolved dependencies.

**Comment by TouriM** [comment]
I ran into the same problem with xlswriter
Tried to run `pipenv install pandas jupyter xlswriter`
First I believed it to be a python 3.8 problem. But I tried it one 3.7.2.


<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/Users/max/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pipenv'`

Python location: `'/Users/max/.pyenv/versions/3.8.0/bin/python3.8'`

Python installations found:

  - `3.8.0`: `/Users/max/.pyenv/versions/3.8.0/bin/python3`
  - `3.7.5`: `/usr/local/bin/python3`
  - `3.7.5`: `/usr/local/bin/python3.7m`
  - `3.7.2`: `/Users/max/.pyenv/versions/3.7.2/bin/python3`
  - `3.7.2`: `/Users/max/.pyenv/versions/3.7.2/bin/python3.7m`
  - `3.7.1`: `/Users/max/.pyenv/versions/3.7.1/bin/python3`
  - `3.7.1`: `/Users/max/.pyenv/versions/3.7.1/bin/python3.7m`
  - `3.7.0`: `/Users/max/.pyenv/versions/3.7.0/bin/python3`
  - `3.7.0`: `/Users/max/.pyenv/versions/3.7.0/bin/python3.7m`
  - `3.6.6`: `/Users/max/.pyenv/versions/3.6.6/bin/python3`
  - `3.6.6`: `/Users/max/.pyenv/versions/3.6.6/bin/python3.6m`
  - `3.6.5`: `/Users/max/.pyenv/versions/3.6.5/bin/python3`
  - `3.6.5`: `/Users/max/.pyenv/versions/3.6.5/bin/python3.6m`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT '
                     '2019; root:xnu-4903.271.2~2/RELEASE_X86_64',
 'python_full_version': '3.8.0',
 'python_version': '3.8',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_PROGRAM`
  - `LC_MONETARY`
  - `PYENV_ROOT`
  - `PIPENV_PYTHON`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `LC_NUMERIC`
  - `TERM_SESSION_ID`
  - `PYENV_VERSION`
  - `LC_ALL`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `PYENV_DIR`
  - `__CF_USER_TEXT_ENCODING`
  - `LSCOLORS`
  - `PATH`
  - `LC_MESSAGES`
  - `LC_COLLATE`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `PYENV_SHELL`
  - `HOME`
  - `COLORFGBG`
  - `LC_TERMINAL_VERSION`
  - `ITERM_SESSION_ID`
  - `LOGNAME`
  - `LC_CTYPE`
  - `GOPATH`
  - `LC_TERMINAL`
  - `DISPLAY`
  - `SECURITYSESSIONID`
  - `LC_TIME`
  - `COLORTERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_PYTHON`: `/Users/max/.pyenv/shims/python`

Debug–specific environment variables:

  - `PATH`: `/Users/max/.pyenv/versions/3.8.0/bin:/usr/local/Cellar/pyenv/1.2.15/libexec:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/Users/max/.local/bin:/usr/local/bin:/Users/max/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS`
  - `SHELL`: `/usr/local/bin/fish`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/max/Documents/coding/nzp/TPZahlung`


---------------------------

Contents of `Pipfile` ('/Users/max/Documents/coding/nzp/TPZahlung/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
pandas = "*"
jupyter = "*"
xlswriter = "*"

[requires]
python_version = "3.8"

```
</details>

<details> <summary>Error Massage</summary>


 Successfully created virtual environment!
Virtualenv location: /Users/max/.local/share/virtualenvs/TPZahlung-JYwKJGl_-/Users/max/.pyenv/shims/python
Creating a Pipfile for this project…
Installing pandas…
Adding pandas to Pipfile's [packages]…
✔ Installation Succeeded
Installing jupyter…
Adding jupyter to Pipfile's [packages]…
✔ Installation Succeeded
Installing xlswriter…
Adding xlswriter to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✘ Locking Failed!
[pipenv.exceptions.ResolutionFailure]:   File "/Users/max/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pipenv/resolver.py", line 61, in resolve
[pipenv.exceptions.ResolutionFailure]:       return resolve_deps(
[pipenv.exceptions.ResolutionFailure]:   File "/Users/max/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pipenv/utils.py", line 718, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree, hashes, markers_lookup, resolver = actually_resolve_deps(
[pipenv.exceptions.ResolutionFailure]:   File "/Users/max/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/Users/max/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches xlswriter
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches xlswriter
No versions found
Was https://pypi.org/simple reachable?
[pipenv.exceptions.ResolutionFailure]:       return resolve_deps(
[pipenv.exceptions.ResolutionFailure]:   File "/Users/max/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pipenv/utils.py", line 718, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree, hashes, markers_lookup, resolver = actually_resolve_deps(
[pipenv.exceptions.ResolutionFailure]:   File "/Users/max/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/Users/max/.pyenv/versions/3.8.0/lib/python3.8/site-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches xlswriter
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches xlswriter
No versions found
Was https://pypi.org/simple reachable?

</details>
