### ISSUE TITLE
Pipenv not using --pypi-mirror configuration

### ISSUE THREAD

**Issue by Steven-Starnes** [pypa/pipenv#3984]
### Issue description
While using the command:
`pipenv install --pypi-mirror="SOME MIRROR"`

Pipenv would hang on the creating virtual environment spinner. Pressing ctrl-c would cancel the operation and I would see that the ./.venv folder was created but no packages installed. This machine I'm using is not connected to the internet so the mirror must be used. I think the pypi-mirror option isn't being used and so pip is hanging on the installation.

### Expected result

Pipenv installs packages from the pypi mirror.

### Actual result

Stuck on creating virtual environment spinner

### Steps to replicate

Hard to replicate unless you block yourself from the internet only allow connections to a pypi mirror.
Run `pipenv install --pypi-mirror="SOME MIRROR"` in a directory with a Pipfile already made.

### Workaround
Create a pip config file in ~/.pip/pip.conf with
```
[global]
index-url="SOME MIRROR"
```

-------------------------------------------------------------------------------

Python3.7.3
pip3 18.1
Pipenv 2018.11.26
OS Debian 10.0

**Comment by matteius** [comment]
The behavior changed this year to support index restricted packages.  If you want to use pypi mirror, just set that as the default source in your Pipfile or using `--index` when creating the project for the first time.   Note that currently we only query pypi for the json API for prefetching hashes, which means it will be slower to run against a pypi mirror.   I would like to enhance `pipenv` to be able to check if mirrors support the json package data API and use it just like it would from pypi, but that is a separate effort
