### ISSUE TITLE
--find-links for lock subcommand in multi-arch use case

### ISSUE THREAD

**Issue by jbalonso** [pypa/pipenv#3993]
### Is your feature request related to a problem? Please describe.

I'm trying to use `pipenv` to install packages into a docker image that's targeting both amd64 and aarch64 (arm64). I'd like to keep the same `Pipfile` but use different `Pipfile.lock`s. In my case, I need to use a precompiled wheel for `pytorch` that targets aarch64, _but I can and want to rely on pypi for amd64_.

(Lesser use case: I _also_ want to use a precompiled wheel for both amd64 and aarch64 for numpy, but that has to do with the pypi wheel not using performant linear algebra libraries (there's a saga here, perhaps another feature request))

It _seems_ I can do this with `pipenv install --extra-index-url file:///$WHEELHOUSE`, but I need to be able to run `pipenv lock` first.

### Describe the solution you'd like

I would like to be able to tell `pipenv lock` to search a local wheelhouse first when looking to update `Pipfile.lock`, but have it otherwise try to use pypi.

### Describe alternatives you've considered

I'd rather not host a pypi mirror just to graft in one package for one arch.

My current workaround that I'm trying is: `PIP_FIND_LINKS=./wheels/ pipenv lock`. This command takes ten minutes to run in my setup, making for a painfully long test cycle... so it might be the end of day before I can report victory or not.

### Additional context

Prior discussions around `--find-links` have been staggering/overwhelming. The best I can tell, though, prior discussions were focused around populating `Pipfile`, whereas I'm trying to update `Pipfile.lock` without incurring trauma.

**Comment by matteius** [comment]
This should be much easier with the index restricted packages work from earlier this year.  For more information see:  https://pipenv.pypa.io/en/latest/advanced/#specifying-package-indexes
