### ISSUE TITLE
How to create another virtual environment when using an python version

### ISSUE THREAD

**Issue by leileigong** [pypa/pipenv#3998]
For a project, i use command
`pipenv install --python 2` ,  pipenv will create an directory in directory **.virtualenvs**.
But if i use `pipenv install --python 3` , pipenv will delete the previous directory. 
Could pipenv create two virtual environment directory for the same project?

thanks.

**Comment by frostming** [comment]
`PIPENV_PYTHON="2.7" pipenv install`
