### ISSUE TITLE
Pipenv scripts

### ISSUE THREAD

**Issue by hudsonbrendon** [pypa/pipenv#4000]
One thing that exists in the world of nodejs is the npm scripts that are present in package.json. Wouldn't it be a good idea to add something similar to pipenv? A session would be created in Pipfile called "scripts" and below we would put the commands that we would automate, the execution would be something like:

`pipenv run <namescript>`

**Comment by frostming** [comment]
Why not? Isn't it already present in the documentation? https://pipenv.kennethreitz.org/en/latest/advanced/#custom-script-shortcuts
