### ISSUE TITLE
`pipenv install <package>` prints out current and new Pipfile hash values swapped

### ISSUE THREAD

**Issue by ghoubrial** [pypa/pipenv#4002]
### Issue description

When installing a new package using `pipenv install <package>`, it outputs something like this:

>1 Installing \<package-name\>.
>2 Adding <package-name> to Pipfile's [packages].
>3 Installation Succeeded
>4 Pipfile.lock (**1d27c4**) out of date, updating to (**444a6d**).
>5 Locking [dev-packages] dependencies.
>6 Locking [packages] dependencies.
>7 Success!
>8 Updated Pipfile.lock (**1d27c4**)!
>9 Installing dependencies from Pipfile.lock (**1d27c4**).

**Note that**: in line 4 of the output above, the hash value `Pipfile.lock (1d27c4) out of date` is actually the hash value of the new Pipfile as shown in both line 8, and 9 of the output.

### Expected result

Expecting to see this output in line 4 of the above output instead:

`Pipfile.lock (CURRENT_HASH) out of date, updating to (NEW_HASH)`

That is:

> Pipfile.lock (**444a6d**) out of date, updating to (**1d27c4**).

### Actual result

> Pipfile.lock (**1d27c4**) out of date, updating to (**444a6d**).

**Comment by pnowaczyk** [comment]
this has been already fixed in https://github.com/pypa/pipenv/pull/3448

**Comment by frostming** [comment]
Yeah, correct
