### ISSUE TITLE
pip install pipenv breaks pip

### ISSUE THREAD

**Issue by matthaeusheer** [pypa/pipenv#4012]
### Issue description
I have a clean Ubuntu 16.04 installation. All I did so far is to install pyenv. I then install pip and pipenv. Before installing pipenv, pip works fine, after installing pipenv through pip, pip is not usable anymore, see actual result section.

### Expected result
```pip``` should work also after running ```pip install pipenv```.

### Actual result
*Before* running ```pip install pipenv```:
```
matt@matt-xps:~$ pip

Usage:   
  pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  search                      Search PyPI for packages.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --isolated                  Run pip in an isolated mode, ignoring environment variables and user configuration.
  -v, --verbose               Give more output. Option is additive, and can be used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output.
  --log <path>                Path to a verbose appending log.
  --proxy <proxy>             Specify a proxy in the form [user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists: (s)witch, (i)gnore, (w)ipe, (b)ackup.
  --trusted-host <hostname>   Mark this host as trusted, even though it does not have valid or any HTTPS.
  --cert <path>               Path to alternate CA bundle.
  --client-cert <path>        Path to SSL client certificate, a single file containing the private key and the
                              certificate in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine whether a new version of pip is available
                              for download. Implied with --no-index.
```
*After* running ```pip install pipenv```:
```
matt@matt-xps:~$ pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
```

### Steps to replicate
```
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.bashrc
exec "$SHELL"
```
```sudo apt install pip```
```pip install pipenv```

-------------------------------------------------------------------------------

```pipenv --support``` - output  
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/matt/.local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.5.2`: `/usr/bin/python3.5`
  - `3.5.2`: `/usr/bin/python3.5m`
  - `2.7.12`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-66-generic',
 'platform_system': 'Linux',
 'platform_version': '#75~16.04.1-Ubuntu SMP Tue Oct 1 14:01:08 UTC 2019',
 'python_full_version': '2.7.12',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `LC_NUMERIC`
  - `WINDOWID`
  - `MANDATORY_PATH`
  - `XDG_GREETER_DATA_DIR`
  - `GNOME_DESKTOP_SESSION_ID`
  - `UPSTART_EVENTS`
  - `PYTHONDONTWRITEBYTECODE`
  - `LESSOPEN`
  - `UNITY_HAS_3D_SUPPORT`
  - `LC_PAPER`
  - `QT_IM_MODULE`
  - `LOGNAME`
  - `USER`
  - `PATH`
  - `XDG_VTNR`
  - `GNOME_KEYRING_CONTROL`
  - `LANGUAGE`
  - `DISPLAY`
  - `LANG`
  - `TERM`
  - `SHELL`
  - `XDG_SESSION_PATH`
  - `XAUTHORITY`
  - `PYENV_SHELL`
  - `COMPIZ_CONFIG_PROFILE`
  - `LC_MONETARY`
  - `QT_LINUX_ACCESSIBILITY_ALWAYS_ON`
  - `GTK_IM_MODULE`
  - `QT_QPA_PLATFORMTHEME`
  - `QT_ACCESSIBILITY`
  - `UNITY_DEFAULT_PROFILE`
  - `UPSTART_INSTANCE`
  - `CLUTTER_IM_MODULE`
  - `SESSION`
  - `SESSIONTYPE`
  - `XMODIFIERS`
  - `GPG_AGENT_INFO`
  - `HOME`
  - `QT4_IM_MODULE`
  - `GTK2_MODULES`
  - `XDG_SESSION_DESKTOP`
  - `SHLVL`
  - `COMPIZ_BIN_PATH`
  - `XDG_RUNTIME_DIR`
  - `INSTANCE`
  - `LC_ADDRESS`
  - `SSH_AUTH_SOCK`
  - `VTE_VERSION`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `GDMSESSION`
  - `IM_CONFIG_PHASE`
  - `UPSTART_JOB`
  - `GNOME_KEYRING_PID`
  - `XDG_SEAT_PATH`
  - `LESSCLOSE`
  - `PIP_PYTHON_PATH`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_SESSION_ID`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `_`
  - `DEFAULTS_PATH`
  - `LC_IDENTIFICATION`
  - `DESKTOP_SESSION`
  - `UPSTART_SESSION`
  - `XDG_CONFIG_DIRS`
  - `GTK_MODULES`
  - `XDG_SESSION_TYPE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `GDM_LANG`
  - `LC_TELEPHONE`
  - `PYENV_ROOT`
  - `LC_MEASUREMENT`
  - `PWD`
  - `JOB`
  - `PIP_SHIMS_BASE_MODULE`
  - `LC_NAME`
  - `LC_TIME`
  - `LS_COLORS`
  - `XDG_DATA_DIRS`
  - `XDG_SEAT`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/matt/.pyenv/shims:/home/matt/.pyenv/bin:/home/matt/bin:/home/matt/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/matt`

---------------------------

</details>

**Comment by frostming** [comment]
Rule 1: never do `sudo pip install`

Any installation that attempts to upgrade the package manager provided pip will break pip. We recommend installing pipenv in an isolated environment, any of the following approaches is okay:

1. `pipx install pipenv`
2. If you don't have pipx, you can create a virtualenv yourself and install pipenv inside it.
3. Or, install it into your user space: `pip install --user pipenv`

None of the 3 approaches should be done with `sudo`.
To fix the broken pip, you should re-install it with `apt`.

This solution is not only for pipenv, but can apply to all libraries and applications.
