### ISSUE TITLE
Pipenv shell issue on git's bash.exe

### ISSUE THREAD

**Issue by aprather51** [pypa/pipenv#4043]
**Summary:**

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'c:\\python\\38\\lib\\site-packages\\pipenv'`

Python location: `'c:\\python\\38\\python.exe'`

Python installations found:

  - `3.8.0`: `C:\Python\38\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.0',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.18362',
 'python_full_version': '3.8.0',
 'python_version': '3.8',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ADSK_3DSMAX_X64_2020`
  - `ALLUSERSPROFILE`
  - `ANDROID_HOME`
  - `ANDROID_HOME_PLATFORM`
  - `APPDATA`
  - `COLORTERM`
  - `COMMONPROGRAMFILES`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `DRIVERDATA`
  - `EXEPATH`
  - `GTK_BASEPATH`
  - `GYP_MSVS_VERSION`
  - `HOME`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `INTEL_DEV_REDIST`
  - `JAVA_HOME`
  - `LANG`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `MIC_LD_LIBRARY_PATH`
  - `MSYSTEM`
  - `NUMBER_OF_PROCESSORS`
  - `NVM_HOME`
  - `NVM_SYMLINK`
  - `OS`
  - `ONEDRIVE`
  - `ONEDRIVECONSUMER`
  - `PATH`
  - `PATHEXT`
  - `PLINK_PROTOCOL`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMFILES`
  - `PS1`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `PWD`
  - `PROGRAMDATA`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `SESSIONNAME`
  - `SHLVL`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TERM`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `TMP`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VS140COMNTOOLS`
  - `WINDIR`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenvûspecific environment variables:

Debugûspecific environment variables:

  - `PATH`: `C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\A.Prather\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Users\A.Prather\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Microsoft Emulator Manager\1.0;C:\Program Files (x86)\Yarn\bin;C:\WINDOWS\System32\OpenSSH;C:\Android Debug Bridge\platform-tools;C:\Program Files\nodejs;C:\MinGW\bin;C:\Program Files\dotnet;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Common Files\Autodesk Shared;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Python\Python38;C:\Program Files\Git\cmd;C:\PostgreSQL\12\bin;C:\Python\38\Scripts;C:\Python\38\Scripts;C:\Python\38;C:\Python\Python38\Scripts;C:\Python\Python38;C:\Program Files\Java\jdk1.8.0_162;C:\Users\A.Prather\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Microsoft VS Code Insiders\bin;C:\Users\A.Prather\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Heroku\bin;C:\mongoDB\bin;C:\Users\A.Prather\AppData\Local\.meteor;C:\Users\A.Prather\AppData\Local\Android\Sdk;C:\Users\A.Prather\AppData\Local\Android\android-sdk\platform-tools;C:\Users\A.Prather\AppData\Local\Yarn\bin;C:\Users\A.Prather\AppData\Roaming\npm;C:\Users\A.Prather\AppData\Local\Programs\Microsoft VS Code Insiders\bin;C:\Program Files\Bandizip;C:\Users\A.Prather\AppData\Local\Programs\Microsoft VS Code\bin;C:\MinGW\bin;C:\Users\A.Prather\AppData\Local\GitHubDesktop\bin;C:\Users\A.Prather\AppData\Local\Microsoft\WindowsApps;C:\Users\A.Prather\AppData\Local\hyper\app-3.0.2\resources\bin`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `C:/Users/A.Prather/Desktop/cake`

---------------------------

Contents of `Pipfile` ('C:\\Users\\A.Prather\\Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "2.7"

```

</details>

Issue: Trying to initiate dependency management running on bash.exe (git-bash) and end up with some issues...

```
$ pipenv shell                                                                                       
Warning: Python 2.7 was not found on your system…
You can specify specific versions of Python with:
  $ pipenv --python path\to\python
```

Note: `pipenv install django` end up with same error.

**Comment by frostming** [comment]
You can't use a Windows version of Python under bash.exe.

You need to install python and pipenv under bash environment.

**Comment by aprather51** [comment]
> You can't use a Windows version of Python under bash.exe.
Incorrect, I have Python3.8 working on window under bash.exe - it confirm python is working except pipenv. 

> You need to install python and pipenv under bash environment.
python and pipenv is installed! 

It appear you did not look into my problem carefully.

**Comment by frostming** [comment]
> Incorrect, I have Python3.8 working on window under bash.exe - it confirm python is working except pipenv.

> Pipenv location: 'c:\\python\\38\\lib\\site-packages\\pipenv'
Python location: 'c:\\python\\38\\python.exe'

But both Pipenv and Python are installed under **Windows** path not **bash** environment.

So do you know what i am really talking about?

**Comment by frostming** [comment]
According to your Pipfile
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "2.7"
```
Python 2.7 is required but there is no such installation on your system.

**Comment by aprather51** [comment]
Ok, I got Python2.7 installed in system and pipenv seem to be working but not quite.  When I type `pipenv shell`. This should create two new files, Pipfile and Pipfile.lock, in project directory But instead it created virtualenv and launch it from parent directory over local. 

```
A.Prather@Anarchy ~/Desktop/cake ➜
$ pipenv shell
Creating a virtualenv for this project…
Pipfile: C:\Users\A.Prather\Pipfile
Using C:/Python/27/python.exe (2.7.17) to create virtualenv…
[==  ] Creating virtual environment...Already using interpreter C:\Python\27\python.exe
New python executable in C:\Users\A.Prather\.virtualenvs\A.Prather-qxb6yR7Y\Scripts\python.exe
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter C:/Python/27/python.exe

Successfully created virtual environment!
Virtualenv location: C:\Users\A.Prather\.virtualenvs\A.Prather-qxb6yR7Y
Launching subshell in virtual environment…

A.Prather@Anarchy ~ ➜
$
```
I have looked into some other issues #1317 but could not replicate for windows 10. What do you suggest?

By the way deprecation or EOL of Python2.7 is reaching on Jan 1 2020. Does it impair anything on pipenv?

**Comment by frostming** [comment]
> But instead it created virtualenv and launch it from parent directory over local.

Because you have a `Pipfile` there already, pipenv will use that file, and that is what project root is based on. Just delete the file at `C:\Users\A.Prather\Pipfile`

> By the way deprecation or EOL of Python2.7 is reaching on Jan 1 2020. Does it impair anything on pipenv?

No, as long as `virtualenv` still supports Python 2.7, AFAIK it will keep support after the EOL.

**Comment by aprather51** [comment]
> Just delete the file at C:\Users\A.Prather\Pipfile
Got It,  working now,

> No, as long as virtualenv still supports Python 2.7, AFAIK it will keep support after the EOL.
noted,

Thanks for taking your time to reply with help.
