### ISSUE TITLE
How to create two Pipfiles in one project directory?

### ISSUE THREAD

**Issue by leileigong** [pypa/pipenv#4047]
Now i got such demand.

I hava one project, project directory name is **myproject1**
use python36 for x86_64, so i dist an exe for x86_64 os.
But now i want to dist an exe for x86 os.

Now I have to copy my project and rename project  directory name to **myproject1-32**.
then change the file **Pipfile**, and add content as follow:
```
[requires]
python_version = "3.6-32"
```
then run 

> pipenv install

create an new virtual env for **myproject1-32**.

Does it have anthor easy way to do this?
I do not wanna to create two project directorys.

Thanks.

**Comment by frostming** [comment]
Point `PIPENV_PYTHON` to Python 3.6-32 then do `pipenv install`. It will create a venv different from the previous one.

**Comment by leileigong** [comment]
i set an env variable on win10.
`PIPENV_PYTHON = C:\Python36-32\python.exe`

then got this error:

> lei@DESKTOP-AM65SOJ /E/python/Project1
$ pipenv install
Creating a virtualenv for this project…
Pipfile: E:\python\Project1\Pipfile
Using C:\Python36-32\python.exe (3.6.6) to create virtualenv…
[   =] Creating virtual environment...Running virtualenv with interpreter C:\Python36-32\python.exe

Failed creating virtual environment
[pipenv.exceptions.VirtualenvCreationException]:   File "c:\python36\lib\site-packages\pipenv\cli\command.py", line 254, in install
[pipenv.exceptions.VirtualenvCreationException]:       editable_packages=state.installstate.editables,
[pipenv.exceptions.VirtualenvCreationException]:   File "c:\python36\lib\site-packages\pipenv\core.py", line 1741, in do_install
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "c:\python36\lib\site-packages\pipenv\core.py", line 574, in ensure_project
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "c:\python36\lib\site-packages\pipenv\core.py", line 506, in ensure_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]:   File "c:\python36\lib\site-packages\pipenv\core.py", line 935, in do_create_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       extra=[crayons.blue("{0}".format(c.err)),]
[pipenv.exceptions.VirtualenvCreationException]: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\virtualenv.py", line 2462, in <module>
$
  File "c:\python36\lib\site-packages\virtualenv.py", line 762, in main
    symlink=options.symlink,
  File "c:\python36\lib\site-packages\virtualenv.py", line 995, in create_environment
    home_dir, lib_dir, inc_dir, bin_dir = path_locations(home_dir)
  File "c:\python36\lib\site-packages\virtualenv.py", line 1037, in path_locations
    mkdir(home_dir)
  File "c:\python36\lib\site-packages\virtualenv.py", line 378, in mkdir
    os.makedirs(path)
  File "C:\Python36-32\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Python36-32\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Python36-32\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'c:\\Users\\lei\\.virtualenvs\\Project1-H8pChjED-C:'

Failed to create virtual environment.

lei@DESKTOP-AM65SOJ /E/python/Project1
$

**Comment by matteius** [comment]
@leileigong Could this be rechecked on `pipenv==2022.8.19`?

**Comment by matteius** [comment]
Currently there is no way to have two Pipfiles in one project directory and named categories isn't going to solve this use case of desiring two different python versions -- but perhaps the combination of what @frostming said about `PIPENV_PYTHON` combined with explicitly defining what virtualenv name with `PIPENV_CUSTOM_VENV_NAME` on the latest version would be a reasonable solution. https://pipenv.pypa.io/en/latest/advanced/#pipenv.environments.Setting.PIPENV_CUSTOM_VENV_NAME
