### ISSUE TITLE
How to specify optional dependencies

### ISSUE THREAD

**Issue by djmattyg007** [pypa/pipenv#4051]
How do you specify optional dependencies? I've seen other issues where it was explicitly stated that pipenv is largely designed to mimic composer. Composer.json files have a section named `suggests` that allows you to list optional dependencies, but I haven't been able to find an equivalent for pipenv. Would someone be able to point me in the right direction?

**Comment by matteius** [comment]
@djmattyg007 I am not familiar with composer, could you describe more what an optional dependency would be like in the context of pipenv?   Right now there are the default and dev package groups, is it different from a dev dependency?

**Comment by matteius** [comment]
Category based package installs may be what you are looking for:  https://github.com/pypa/pipenv/issues/4745
