### ISSUE TITLE
Environment variables in source url may cause IPv6 error on special characters

### ISSUE THREAD

**Issue by Sprungwunder** [pypa/pipenv#4061]
### Issue description

If special characters in the password or in the username are present a "ValueError: Invalid IPv6 URL" is raised.
I have not tested all special characters, a ")" seem to work, also "@" or some ohters, at least "[" or "]" do not work.
A simple test with the following env vars and the example Pipfile leads to this error.

```
export PYPI_PASSWORD="pw[d"
export PYPI_USERNAME=user
```
Pipfile:
```
[[source]]
url = "https://'$PYPI_USERNAME':'$PYPI_PASSWORD'@example.com/"
verify_ssl = false
name = "pypi_test"

[packages]
pyyaml = {version = "*",index = "pypi_test"}

[requires]
python_version = "3.6"
```

### Expected result

Pipenv will install packages from the given URL, in this case fail with a 
```
pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches pyyaml
No versions found
Was https://user:pwd@example.com/ reachable?
```

### Actual result

Pipenv fails with a ValueError 
```
christian@ubuntu:~/test_pipenv$ export PYPI_USERNAME=user
christian@ubuntu:~/test_pipenv$ export PYPI_PASSWORD="pwd]"
christian@ubuntu:~/test_pipenv$ pipenv install
Pipfile.lock (39f748) out of date, updating to (311704)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/home/christian/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/core.py", line 1874, in do_install
    keep_outdated=keep_outdated
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/core.py", line 1221, in do_init
    pypi_mirror=pypi_mirror,
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/core.py", line 1055, in do_lock
    packages, project, r=False, include_index=True
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/utils.py", line 832, in convert_deps_to_pip
    req = new_dep.as_line(sources=indexes if include_index else None).strip()
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1272, in as_line
    source_list = prepare_pip_source_args(sources)
  File "/home/christian/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/utils.py", line 180, in prepare_pip_source_args
    pip_args.extend(["--trusted-host", urlparse(sources[0]["url"]).hostname])
  File "/usr/lib/python3.6/urllib/parse.py", line 368, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python3.6/urllib/parse.py", line 460, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL

```

### Steps to replicate

Create the Pipfile mentioned above.
Add the environment variables, at least one of them containing for example a "]" or "["
Run: pipenv install

-------------------------------------------------------------------------------
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/christian/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3.6'`

Python installations found:

  - `3.7.5`: `/usr/bin/python3.7m`
  - `3.7.5`: `/usr/bin/python3.7`
  - `3.6.9`: `/usr/bin/python3`
  - `3.6.9`: `/usr/bin/python3.6m`
  - `3.5.2`: `/usr/bin/python3.5`
  - `3.5.2`: `/usr/bin/python3.5m`
  - `2.7.15`: `/usr/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.9',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-72-generic',
 'platform_system': 'Linux',
 'platform_version': '#81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019',
 'python_full_version': '3.6.9',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `CLUTTER_IM_MODULE`
  - `PYPI_PASSWORD`
  - `CONDA_SHLVL`
  - `LS_COLORS`
  - `CONDA_EXE`
  - `LESSCLOSE`
  - `LANG`
  - `GDM_LANG`
  - `DISPLAY`
  - `QT_STYLE_OVERRIDE`
  - `OLDPWD`
  - `COMPIZ_CONFIG_PROFILE`
  - `GTK2_MODULES`
  - `GTK_OVERLAY_SCROLLING`
  - `GTK_CSD`
  - `COLORTERM`
  - `XDG_VTNR`
  - `SSH_AUTH_SOCK`
  - `MANDATORY_PATH`
  - `S_COLORS`
  - `_CE_M`
  - `XDG_SESSION_ID`
  - `XDG_GREETER_DATA_DIR`
  - `USER`
  - `DESKTOP_SESSION`
  - `QT4_IM_MODULE`
  - `TEXTDOMAINDIR`
  - `DEFAULTS_PATH`
  - `QT_QPA_PLATFORMTHEME`
  - `PWD`
  - `HOME`
  - `CONDA_PYTHON_EXE`
  - `TEXTDOMAIN`
  - `SSH_AGENT_PID`
  - `QT_ACCESSIBILITY`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `MATE_DESKTOP_SESSION_ID`
  - `_CE_CONDA`
  - `XDG_SESSION_DESKTOP`
  - `QT_SCALE_FACTOR`
  - `GTK_MODULES`
  - `CLUTTER_BACKEND`
  - `SHELL`
  - `VTE_VERSION`
  - `TERM`
  - `XDG_SEAT_PATH`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `IM_CONFIG_PHASE`
  - `XDG_CURRENT_DESKTOP`
  - `GPG_AGENT_INFO`
  - `XDG_SEAT`
  - `SHLVL`
  - `LANGUAGE`
  - `WINDOWID`
  - `GDMSESSION`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `PYPI_USERNAME`
  - `XDG_SESSION_PATH`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `XDG_CONFIG_DIRS`
  - `PATH`
  - `LD_PRELOAD`
  - `SESSION_MANAGER`
  - `LESSOPEN`
  - `GTK_IM_MODULE`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/christian/anaconda3/condabin:/home/christian/bin:/home/christian/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/christian/test_pipenv`

---------------------------

Contents of `Pipfile` ('/home/christian/test_pipenv/Pipfile'):

```toml
[[source]]
url = "https://'$PYPI_USERNAME':'$PYPI_PASSWORD'@example.com/"
verify_ssl = false
name = "pypi_test"



[packages]
pyyaml = {version = "*",index = "pypi_test"}

[requires]
python_version = "3.6"


```

Contents of `Pipfile.lock` ('/home/christian/test_pipenv/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "cceb38362fc548f369179cd9e2910d9a521551d23d003f928505cd09a0311704"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            },
            {
                "name": "pypi_test",
                "url": "https://$PYPI_USERNAME:'${PYPI_PASSWORD}'@example.com/",
                "verify_ssl": false
            }
        ]
    },
    "default": {
        "pyyaml": {
            "hashes": [
                "sha256:0e7f69397d53155e55d10ff68fdfb2cf630a35e6daf65cf0bdeaf04f127c09dc",
                "sha256:2e9f0b7c5914367b0916c3c104a024bb68f269a486b9d04a2e8ac6f6597b7803",
                "sha256:35ace9b4147848cafac3db142795ee42deebe9d0dad885ce643928e88daebdcc",
                "sha256:38a4f0d114101c58c0f3a88aeaa44d63efd588845c5a2df5290b73db8f246d15",
                "sha256:483eb6a33b671408c8529106df3707270bfacb2447bf8ad856a4b4f57f6e3075",
                "sha256:4b6be5edb9f6bb73680f5bf4ee08ff25416d1400fbd4535fe0069b2994da07cd",
                "sha256:7f38e35c00e160db592091751d385cd7b3046d6d51f578b29943225178257b31",
                "sha256:8100c896ecb361794d8bfdb9c11fce618c7cf83d624d73d5ab38aef3bc82d43f",
                "sha256:c0ee8eca2c582d29c3c2ec6e2c4f703d1b7f1fb10bc72317355a746057e7346c",
                "sha256:e4c015484ff0ff197564917b4b4246ca03f411b9bd7f16e02a2f586eb48b6d04",
                "sha256:ebc4ed52dcc93eeebeae5cf5deb2ae4347b3a81c3fa12b0b8c976544829396a4"
            ],
            "version": "==5.2"
        }
    },
    "develop": {}
}

```
</details>

**Comment by Sprungwunder** [comment]
This seems to be caused by the urllib module.
```
>>> urllib.parse.urlsplit("https://user:pwd[@example.com")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/urllib/parse.py", line 460, in urlsplit
    raise ValueError("Invalid IPv6 URL")

```

**Comment by 20joseph10** [comment]
My very hacky solution now is to encode the special characters in the password using %-encoding mentioned here: https://pip.pypa.io/en/stable/user_guide/#basic-authentication-credentials, but I do hope to see some smart way of doing this.

**Comment by matteius** [comment]
@zz-x404 Can this be rechecked with `pipenv==2022.8.19`?
