### ISSUE TITLE
Find the correct order of install python packages into my project's with pipenv.

### ISSUE THREAD

**Issue by hongyi-zhao** [pypa/pipenv#4066]
Hi,

I want to install the following packages for my project:

```
numpy
scipy
scikit-learn
matplotlib
opencv
jupyter
notebook
pandas
mkl-service
Theano
Keras
```

But install them corroding to the above order always fails.  I'm not sure whether some of these packages are exclusive or must I use specific order to install them?

Any hints?

**Comment by matteius** [comment]
@hongyi-zhao I would just manually add them all to a `Pipfile` rather than try to figure out the ordering, the `pip` resolver will make that determination and build out the `Pipfile.lock` when running `pipenv lock` or `pipenv install`.  Let us know if you need anymore help with this.

**Comment by hongyi-zhao** [comment]
@matteius Thank you for comment and reply. Unfortunately, I haven't used this package for a long time, so I can't do any further testing. Anyway, I would like to thank you for your comments and explanations.
