### ISSUE TITLE
Use the pipenv with anaconda.

### ISSUE THREAD

**Issue by hongyi-zhao** [pypa/pipenv#4067]
Hi,

I installed the anaconda python with:

https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh

In this case, how to let pipenv to use the anaconda python?

**Comment by frostming** [comment]
use `--python` to point to the anaconda Python.

https://pipenv.kennethreitz.org/en/latest/basics/#specifying-versions-of-python
