### ISSUE TITLE
Pipenv doesn't support browser auth flow for Azure artifacts-keyring

### ISSUE THREAD

**Issue by philosophicles** [pypa/pipenv#4074]
### Background

Trying to install a closed-source python package from my company's private package feed hosted on Azure DevOps, following [these instructions](https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-packages?view=azure-devops). 

The instructions, exactly as presented in that link, work fine using `pip install`, within a virtual environment (which I entered via `pipenv shell`). For readers unfamiliar with `artifacts-keyring`, it causes the `pip install` process to produce a message on stdout (well, I _assume_ it's stdout) with a URL to follow and a one-time code to copy, and then wait. The human has to manually browse to the URL, paste the one-time code, then log in to their Microsoft account, then close the browser tab to allow the `pip` installation process to continue.

**But** I want to use `pipenv install` directly if possible! 

Notable here as well is that `artifacts-keyring` is currently in pre-release, which means #3947 is relevant, but I believe I've controlled for it below. 

### Issue description

This would not be directly reproducible for anyone else copy-pasting exactly from below, because the private package feed in question _is private_. You'll have to set up your own Azure DevOps Artifacts package feed if you want to completely replicate, I'm afraid. I have anonymized the organization name, package name etc as a precaution, since it wouldn't work either way. 

Start in a virtual environment, with `artifacts-keyring` already successfully installed by pipenv (using `--pre` switch because it is a pre-release package).

Try to install my private package:

    $ pipenv install mypackage --pre --verbose --skip-lock --pypi-mirror https://pkgs.dev.azure.com/OrgName/Main/_packaging/OrgNamePyPI/pypi/simple/ 

Including `--skip-lock` works around #3947. Without that flag, I am just reproducing #3947. 
I don't think `--pre` is really necessary here but I threw it in just in case.

### Expected result

Successful install. This would have to invoke the browser authentication flow, same as Pip does (provided one uses a totally fresh virtual env for this test; the user access token Pip obtained hangs around within a virtual env, I believe). After doing that I'd expect to get the usual happy messages from `pipenv`, and to see my `Pipfile` updated. (But not `Pipfile.lock` in this case.)

### Actual result

The installation process churns for an unusually long time, mostly staying on the `[==   ]  Installing...` progress monitor. I don't see any authentication prompts. Then eventually it spews a lot more output and ends, all in quick succession. 

The complete output is attached: [pipenv traceback.txt](https://github.com/pypa/pipenv/files/3981042/pipenv.traceback.txt). 

Notably, this output clearly shows that multiple attempts were made to carry out the interactive browser authentication flow. But since I couldn't see them until too late, I couldn't do them, and there is apparently a 90-second timeout.

So pipenv needs to pass the inner output back up to the user's stdout much sooner, instead of presumably caching it? 

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'c:\\python38\\lib\\site-packages\\pipenv'`

Python location: `'c:\\python38\\python.exe'`

Python installations found:

  - `3.8.0`: `C:\Python38\python.exe`
  - `3.7.4`: `C:\Python37\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.0',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.18362',
 'python_full_version': '3.8.0',
 'python_version': '3.8',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `CHOCOLATEYINSTALL`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DRIVERDATA`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `ONEDRIVECOMMERCIAL`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PIPENV_ACTIVE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `PYTHONDONTWRITEBYTECODE`
  - `SESSIONNAME`
  - `SNC_LIB`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `UATDATA`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VIRTUAL_ENV`
  - `WINDIR`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv├╗specific environment variables:

 - `PIPENV_ACTIVE`: `1`

---------------------------

Contents of `Pipfile` ('C:\\src\\python\\testcreds\\Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[[source]]
url = "https://pkgs.dev.azure.com/OrgName/Main/_packaging/OrgNamePyPI/pypi/simple/"
verify_ssl = true
name = "drpypi"

[pipenv]
allow_prereleases = true

[dev-packages]

[packages]
artifacts-keyring = "*"
mypackage = "*"

[requires]
python_version = "3.8"

```

Contents of `Pipfile.lock` ('C:\\src\\python\\testcreds\\Pipfile.lock'):
`Omitted, not relevant, lockfile is outdated due to other issue.`
    
</details>

**Comment by keyz182** [comment]
One potential workaround is to run this beforehand: 
```bash
$ pipenv run keyring get -b artifacts_keyring.ArtifactsKeyringBackend https://pkgs.dev.azure.com/OrgName/Main/_packaging/OrgNamePyPI/pypi/simple/ VssSessionToken
```

It triggers the auth flow manually, and then caches the details so that `pipenv install` can use them later. This does mean requiring the venv to already exist, with `artifacts-keyring` installed unfortunately. 

I'm currently scripting it up to 
```bash
$ pipenv --python 3.7
$ pipenv run keyring get -b artifacts_keyring.ArtifactsKeyringBackend https://pkgs.dev.azure.com/OrgName/Main/_packaging/OrgNamePyPI/pypi/simple/ VssSessionToken
$ pipenv install --dev
```

It at least gets me a step further. Now I'm stuck at pipenv trying to resolve packages and not being able to find/auth to the repo.

```
keyz@mac-mini test % pipenv install --dev --verbose --pre
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✘ Locking Failed!
Using pip: -i https://pkgs.dev.azure.com/OrgName/Main/_packaging/OrgNamePyPI/pypi/simple/
Using pip: -i https://pkgs.dev.azure.com/OrgName/Main/_packaging/OrgNamePyPI/pypi/simple/
Using pip: -i https://pkgs.dev.azure.com/OrgName/Main/_packaging/OrgNamePyPI/pypi/simple/

                          ROUND 1
Current constraints:
  mypackage

Finding the best candidates:
Traceback (most recent call last):
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/patched/piptools/resolver.py", line 198, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/patched/piptools/resolver.py", line 198, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/patched/piptools/resolver.py", line 263, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 175, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches mypackage
No versions found
Was https://pkgs.dev.azure.com/OrgName/Main/_packaging/OrgNamePyPI/pypi/simple/ reachable?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/utils.py", line 395, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches mypackage
No versions found
Was https://pkgs.dev.azure.com/OrgName/Main/_packaging/OrgNamePyPI/pypi/simple/ reachable?
Using pip: -i https://pkgs.dev.azure.com/OrgName/Main/_packaging/OrgNamePyPI/pypi/simple/
Using pip: -i https://pkgs.dev.azure.com/OrgName/Main/_packaging/OrgNamePyPI/pypi/simple/

                          ROUND 1
Current constraints:
  mypackage

Finding the best candidates:
Traceback (most recent call last):
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/patched/piptools/resolver.py", line 198, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/patched/piptools/resolver.py", line 198, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/patched/piptools/resolver.py", line 263, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 175, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches mypackage
No versions found
Was https://pkgs.dev.azure.com/OrgName/Main/_packaging/OrgNamePyPI/pypi/simple/ reachable?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/Users/keyz/Library/Python/3.7/lib/python/site-packages/pipenv/utils.py", line 395, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches mypackage
No versions found
Was https://pkgs.dev.azure.com/OrgName/Main/_packaging/OrgNamePyPI/pypi/simple/ reachable?
```

**Comment by rinman24** [comment]
Have you guys seen this post? https://github.com/microsoft/artifacts-keyring/issues/8

It was working for me until early this week. Perhaps Azure updated the artifacts authentication.

**Comment by philosophicles** [comment]
I wasn't aware that the `artifacts-keyring` project was also tracking this, no. 

From the initial issue description:

> I think it has to do with Pipenv running pip in subprocesses and hiding the stdout/stderr streams. This broke our development workflow.

That sounds about right to me, and I still think this is pipenv's issue to fix, not the responsibility of the artifacts-keyring project. 

@rinman24 Do you mean the workaround described in that issue was working and has stopped? Or do you mean that pipenv was working more generally with artifacts auth for you until last week?

**Comment by rinman24** [comment]
@philosophicles I mean that the workaround described in the issue using the PAT has stopped working. I agree that this is pipenv's issue to fix.

**Comment by ggirard07** [comment]
From what I can understand and see, `pipenv` simply does not support `keyring` by itself.
It cannot proceed with the `Locking...` phase, which means it never moves on to `pip install` which includes keyring support...

Correct me if I am wrong, but I don't see any reference to `keyring` in pipenv code.

**Comment by pataraco** [comment]
combining work around here and in the other related issue, i got this to work:

`# get a TOKEN
$ ADO_ARTIFACTS_TOKEN=$(pipenv run keyring get -b artifacts_keyring.ArtifactsKeyringBackend https://pkgs.dev.azure.com/COMPANY/PROJECT/_packaging/FEED/pypi/simple/ VssSessionToken 2> /dev/null)

# Pipfile: set up the index URL to use the token
[[source]]
name = "pypi-ado"
url = "https://azure:${ADO_ARTIFACTS_TOKEN}@pkgs.dev.azure.com/COMPANY/PROJECT/_packaging/FEED/pypi/simple"
verify_ssl = true

# Install the package
$ pipenv install PACKAGE[==VERSION] -i pypi-ado [--verbose]
`

**Comment by kato-m** [comment]
Just for the record, explicitely specifying the keyring backend didn't work for me with `keyring-artifacts==0.3.1`. I used the deafult.
```
pipenv run keyring get https://pkgs.dev.azure.com/COMPANY/PROJECT/_packaging/FEED/pypi/simple/ VssSessionToken
```
However, pipenv doesn't seem to read the token from the environment. 

Apart from that, storing the token as plain text in an `.env` is IMHO not a good idea. Are there any updates on this issue?

**Comment by cmw278** [comment]
**gentle nudge**

**Comment by Darsstar** [comment]
I managed to get this working today =]

Be sure to replace the url:
```powershelll
#powershell
python -m pip install --user azure_devops_artifacts_helpers artifacts-keyring
[Environment]::SetEnvironmentVariable("VIRTUALENV_SEEDER", "azdo-pip", "Machine")
[Environment]::SetEnvironmentVariable("PIP_INDEX_URL", "https://pkgs.dev.azure.com/XXXXX/_packaging/YYYYY/pypi/simple/", "Machine")
```

Open a new powershell/cmd window so those environment variables get loaded and `pipenv install` should work. It does for me at least, let me now if it doesn't and I'll try to figure out wat else I did during all the trial and error.

**Comment by rgammans** [comment]
The above sort of works for me. I am in  Linux (since you demonstrate Powershell, I'm guessing you are on windows) and have the Index URL directly in the Pipfile, rather than via a envvar.
so 

```
export VIRTUALENV_SEEDER=azdo-pip
pipenv --rm
pipenv sync
```

Works almost , but fails due to authentication, because the stdout is buffered so you never see the prompts for the authentication challenge, however, you should be able to pre-populate the auth with

`
pipenv run pip install -i $MY_INDEX $ANY_DEPENDENCY
`
(given appropriate replacements)

All of my simple tests suggest that all that needs to be done, except it doesn't work. But I don't think that's anything wrong with pipenv, I'm now seen the following  .net exception.

```
Unhandled exception. System.PlatformNotSupportedException: Wait operations on multiple wait handles including a named synchronization primitive are not supported on this platform.
   at System.Threading.WaitHandle.WaitMultipleIgnoringSyncContext(IntPtr* waitHandles, Int32 numHandles, Boolean waitAll, Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitMultiple(ReadOnlySpan`1 waitHandles, Boolean waitAll, Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitMultiple(WaitHandle[] waitHandles, Boolean waitAll, Int32 millisecondsTimeout)
   at System.Threading.WaitHandle.WaitAny(WaitHandle[] waitHandles, Int32 millisecondsTimeout)
   at NuGetCredentialProvider.Util.SessionTokenCache.get_Cache()
   at NuGetCredentialProvider.Util.SessionTokenCache.TryGetValue(Uri key, String& value)
   at NuGetCredentialProvider.RequestHandlers.GetAuthenticationCredentialsRequestHandler.TryCache(GetAuthenticationCredentialsRequest request, String& cachedToken)
   at NuGetCredentialProvider.RequestHandlers.GetAuthenticationCredentialsRequestHandler.HandleRequestAsync(GetAuthenticationCredentialsRequest request)
   at NuGetCredentialProvider.Program.Main(String[] args)
   at NuGetCredentialProvider.Program.<Main>(String[] args)
WARNING: Keyring is skipped due to an exception: Failed to get credentials: process with PID 24315 exited with code -6; additional error message:

```
Because of the timeouts involved and unbuffered verbose logging option would be really helpful as feature in debugging and working with these style of authentication platforms.

**Comment by philosophicles** [comment]
@rgammans 
> Having spend yet more time on this the fix for this exception is to run pipenv {sync,install} with the --sequential switch

This is neat, but I would definitely describe this as a workaround _not_ a fix. This should "just work" without having to do anything different than when installing any old package from PyPi.

**Comment by rgammans** [comment]
@philosophicles , I agree with your characterisation, but the root cause isn't with pipenv, it's the in the .Net component of artifacts-keyring. I've raised the issue with that project here, https://github.com/microsoft/artifacts-credprovider/issues/259

**Comment by philosophicles** [comment]
@rgammans I'm pretty removed from this topic now so please assume a big "I could definitely be wrong or missing something obvious" marker on what I'm about to say :). That said... 

Given that it was all working fine on my Windows system using `pip install` without any involvement from pipenv, doesn't that imply that `artifacts-keyring` cannot be the (only) problem? 

I found this issue on Windows; it's certainly possible that there is _also_ a separate, Linux-specific, race hazard within `artifacts-keyring`. But I'm not sure you've yet proved that pipenv is guilt-free.

**Comment by rgammans** [comment]
Well, @Darsstar did say it now worked for him and given in posted PowerShell as an example, I'm guessing he was on windows. Those instructions worked for me with the exception of the additional linux specific issue I mentioned, and now I think about one other gotcha, which was to authenticate once before running the command, although because pipenv buffers the output you don't see the login code and which is sent to stdout.

**Comment by Darsstar** [comment]
Yes, I am on windows.

**Comment by philosophicles** [comment]
OK - sorry I think I'd misinterpreted @Darsstar 's post on first reading. 

I can't easily experiment with this for myself as I've changed jobs since raising this issue. 

I guess I'm still a little reticent about treating this as fixed, because setting the environment variables @Darsstar demonstrated isn't trivially obvious, isn't documented anywhere official (? I think?), and arguably still shouldn't be necessary. 

You don't need these environment variables to install a private package via pip (according to the MS docs: https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-packages?view=azure-devops) so why should you need to set such environment up to use pipenv?

**Comment by rgammans** [comment]
The problem there is Microsoft's documentation is overly simplistic. Actually setting those variable means you are following the instructions in the docs.
The only actually variable needed is the 'VIRTUALENV_SEEDER=azdo-pip' and the azure_devops_artifacts_helpers package, in the base or outer environment.

What this package and this environment variable do is make sure that the 'artifacts-keyring' package is installed when the new virtual environment is created. The Microsoft docs describe a manual process with pip and virtualenv, but pipenv automates the process so we need the environment variables to provide hints/instructions to virtualenv to do the additional steps required. This should be documented for Pipenv, but nowhere does Microsoft seem to document using Pipenv with Python.

**Comment by philosophicles** [comment]
Fair enough. Note those MS docs (that I linked to above) are open-sourced and hosted on Github, so you can suggest improvements if you want via a PR. I've had a few accepted in the past on other topics. In this case I don't think I'm close enough to the topic any more to be able to make such an edit confidently.

That said, it sounds like there's nothing more that the pipenv project could change to improve this experience, so I'll close this.

**Comment by Adam--** [comment]
I was able to get this to work with https://github.com/djpugh/azure_devops_artifacts_helpers as mentioned above. I think what was key though was to authenticate the devops feed with a pip install command prior to creating the virtual environment, think of it as an extra step to get authenticated on the computer.

Also, it appears that you now have to set disable_pip_input to false in your Pipenv. See https://pipenv.pypa.io/en/latest/advanced/#injecting-credentials-through-keychain-support.
```toml
[pipenv]
disable_pip_input = false
```

Here's how to configure it step by step.

1. Install pipenv, artifacts-keyring, and azure_devops_artifacts_helpers at your "base" interpreter level. It's generally recommended to pip install to the user site using --user so modify this command as appropriate.
```
pip install pipenv artifacts-keyring azure_devops_artifacts_helpers
```

2. Add the following environmental variable to the user scope: 
VIRTUALENV_SEEDER = azdo-pip
On Windows, in PowerShell that's done with
```
[Environment]::SetEnvironmentVariable("VIRTUALENV_SEEDER", "azdo-pip", "User")
```
Restart your shell.

3. Authenticate with your private index by pip installing any package, valid or invalid, from your private azure index. This will trigger authentication and save it to your local keyring. Follow the prompts to sign into https://microsoft.com/devicelogin with the code. This should be the only time you have to login.
```
pip install any-package-valid-or-invalid --index="https://pkgs.dev.azure.com/XXXXX/_packaging/YYYYY/pypi/simple/"
```

4. Configure your Pipenv file
Add your private index
```toml
[[source]]
url = "https://pkgs.dev.azure.com/XXXXX/_packaging/YYYYY/pypi/simple/"
verify_ssl = true
name = "pkgsdevazure"
```

Add your package
```toml
[packages]
YOUR-PACKAGE = {version = "*", index = "pkgsdevazure"}
```

Configure disable_pip_input to false.
```toml
[pipenv]
disable_pip_input = false
```

**Comment by Darsstar** [comment]
Small update: pipenv 2023.4.20 vendored Pip 23.1. keyring can now be used with `--no-input`, the resolver also requires that `--no-input` is used, meaning `disable_pip_input = false` won't work anymore.
[Luckily 23.1 also comes with the `--keyring-provider` flag.](https://pip.pypa.io/en/stable/topics/authentication/#using-keyring-as-a-command-line-application) Be sure to use `VssSessionToken` as the username!

**Comment by al-one-zero** [comment]
If I can add to what @Darsstar said : in the case of Google Artifact Registry, the process is the same but the username might be `oauth2accesstoken` instead of `VssSessionToken` (not documented anywhere, but for some reason `pip` and `poetry` figure this one out on their own).

**Comment by ahdkhalid** [comment]
In case of pipenv 2024.4.0, somehow, It was not picking up PIP_EXTRA_INDEX_URL env variable, 
I had to update index url inside Pipfile with complete URL along with my_azure_username, and my_azure_access_token in plain text in my local to work. 

```
# Pipfile:
[[source]]
name = "azdo"
url = "https://my_azure_username:my_azure_access_token@pkgs.dev.azure.com/COMPANY/PROJECT/_packaging/FEED/pypi/simple"
verify_ssl = true
```

**Comment by matteius** [comment]
We deprecated/removed extra index urls for security reasons -- but you should be a ble to reference your tokens via env vars using ${ENV_VAR} syntax -- if not, that should be a new bug report.
