### ISSUE TITLE
Dead code in core.py

### ISSUE THREAD

**Issue by huornlmj** [pypa/pipenv#4088]
https://github.com/pypa/pipenv/blob/2549656dc09e132d8ba2fa6327c939f5f9a951b7/pipenv/core.py#L1216

Is this line dead code?

**Comment by ftobia** [comment]
Looks like it. Here's the changeset that removes a bunch of similar `sys.exit()` calls, but seems to have missed one. https://github.com/pypa/pipenv/commit/b57240dd45f69859fba3244dc9f642702a700e21
