### ISSUE TITLE
Cant create new virtualenv environment under py2 after setuptools 45.0.0 release yesterday

### ISSUE THREAD

**Issue by littlemo** [pypa/pipenv#4093]
### Issue description

The package `setuptools` release 45.0.0, which is not support `py2` , yesterday(Jan 12, 2020)
Cant create new virtualenv environment under `py2`

### Expected result

Successfully created virtual environment

### Actual result

```
$ pipenv install --two
Creating a virtualenv for this project…
Pipfile: /Volumes/Develop/xx/test/Pipfile
Using /usr/bin/python (2.7.16) to create virtualenv…
⠸ Creating virtual environment...New python executable in /Volumes/Develop/.virtualenvs/test_py2/bin/python
Installing setuptools, pip, wheel...

  Complete output from command /Volumes/Develop/.vi.../test_py2/bin/python - setuptools pip wheel:
  DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Looking in indexes: http://devpi.intra.xx.cn/root/xx/+simple/
Looking in links: /Users/moore/.pyenv/versions/3.6.5/lib/python3.6/site-packages/virtualenv_support
Collecting setuptools
  Downloading http://devpi.intra.xx.cn/root/mirror/%2Bf/616/b116b122e4140/setuptools-45.0.0-py2.py3-none-any.whl (583kB)
ERROR: setuptools requires Python '>=3.5' but the running Python is 2.7.16
----------------------------------------
...Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /usr/bin/python

✘ Failed creating virtual environment
[pipenv.exceptions.VirtualenvCreationException]:   File "/Users/moore/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv/cli/command.py", line 254, in install
[pipenv.exceptions.VirtualenvCreationException]:       editable_packages=state.installstate.editables,
[pipenv.exceptions.VirtualenvCreationException]:   File "/Users/moore/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv/core.py", line 1741, in do_install
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/Users/moore/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv/core.py", line 574, in ensure_project
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/Users/moore/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv/core.py", line 506, in ensure_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]:   File "/Users/moore/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv/core.py", line 935, in do_create_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       extra=[crayons.blue("{0}".format(c.err)),]
[pipenv.exceptions.VirtualenvCreationException]: Traceback (most recent call last):
  File "/Users/moore/.pyenv/versions/3.6.5/lib/python3.6/site-packages/virtualenv.py", line 2580, in <module>
    main()
  File "/Users/moore/.pyenv/versions/3.6.5/lib/python3.6/site-packages/virtualenv.py", line 831, in main
    symlink=options.symlink,
  File "/Users/moore/.pyenv/versions/3.6.5/lib/python3.6/site-packages/virtualenv.py", line 1123, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/Users/moore/.pyenv/versions/3.6.5/lib/python3.6/site-packages/virtualenv.py", line 973, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/Users/moore/.pyenv/versions/3.6.5/lib/python3.6/site-packages/virtualenv.py", line 1060, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/Users/moore/.pyenv/versions/3.6.5/lib/python3.6/site-packages/virtualenv.py", line 924, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /Volumes/Develop/.vi.../test_py2/bin/python - setuptools pip wheel failed with error code 1

Failed to create virtual environment.
```

### Steps to replicate

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/Users/moore/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pipenv'`

Python location: `'/Users/moore/.pyenv/versions/3.6.5/bin/python3.6'`

Python installations found:

  - `3.7.3`: `/usr/bin/python3`
  - `3.6.5`: `/Users/moore/.pyenv/versions/3.6.5/bin/python3`
  - `3.6.5`: `/Users/moore/.pyenv/versions/3.6.5/bin/python3.6m`
  - `3.6.0`: `/Users/moore/.pyenv/versions/3.6.0/bin/python3`
  - `3.6.0`: `/Users/moore/.pyenv/versions/3.6.0/bin/python3.6m`
  - `3.5.3`: `/Users/moore/.pyenv/versions/3.5.3/bin/python3`
  - `3.5.3`: `/Users/moore/.pyenv/versions/3.5.3/bin/python3.5m`
  - `2.7.16`: `/usr/bin/python`
  - `2.7.16`: `/usr/bin/pythonw`
  - `2.7.13`: `/Users/moore/.pyenv/versions/2.7.13/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '19.0.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT '
                     '2019; root:xnu-6153.41.3~29/RELEASE_X86_64',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `LC_ALL`
  - `VIRTUALENVWRAPPER_WORKON_CD`
  - `VIRTUALENVWRAPPER_HOOK_DIR`
  - `LANG`
  - `XPC_FLAGS`
  - `LESS`
  - `PYENV_ROOT`
  - `OLDPWD`
  - `TERM_SESSION_ID`
  - `COMMAND_MODE`
  - `WORKON_HOME`
  - `EDITOR`
  - `GPG_TTY`
  - `COLORTERM`
  - `__CF_USER_TEXT_ENCODING`
  - `LaunchInstanceID`
  - `PYENV_HOOK_PATH`
  - `ITERM_SESSION_ID`
  - `ZSH`
  - `SSH_AUTH_SOCK`
  - `USER`
  - `PYENV_DIR`
  - `PAGER`
  - `LSCOLORS`
  - `GOPATH`
  - `PWD`
  - `HOME`
  - `LC_CTYPE`
  - `LC_TERMINAL`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `PYENV_VERSION`
  - `LC_TERMINAL_VERSION`
  - `ITERM_PROFILE`
  - `HANDFILE_MMD_MODE`
  - `TMPDIR`
  - `VIRTUALENVWRAPPER_PYTHON`
  - `XPC_SERVICE_NAME`
  - `VIRTUALENVWRAPPER_SCRIPT`
  - `TERM`
  - `SHELL`
  - `SECURITYSESSIONID`
  - `PYENV_SHELL`
  - `SHLVL`
  - `COLORFGBG`
  - `MANPATH`
  - `LOGNAME`
  - `VIRTUALENVWRAPPER_PROJECT_FILENAME`
  - `PATH`
  - `HOMEBREW_GITHUB_API_TOKEN`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/moore/.pyenv/versions/3.6.5/bin:/usr/local/Cellar/pyenv/1.2.11/libexec:/usr/local/opt/sqlite/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/Users/moore/.pyenv/shims:/Users/moore/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/usr/local/git/bin:/usr/local/opt/gettext/bin:/Users/moore/.pyenv/shims:/Users/moore/.pyenv/bin:/usr/local/sbin:/opt/X11/bin:/Users/moore/.bin:/usr/local/opt/go/libexec/bin:/Users/moore/Documents/workspace/go/bin:/Users/moore/Downloads/tkg-toolkit-master/mac/bin:/usr/local/opt/fzf/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `nvim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Volumes/Develop`

---------------------------

</details>

**Comment by golf-player** [comment]
Is this a pipenv issue or a problem with your pypi index? What happens if you run `pip install -v setuptools` with the same index url in python2?

**Comment by littlemo** [comment]
Sorry, you are right. it's solved when I modify the `index-url` , thx

**Comment by guysoft** [comment]
Hey, what do you mean when you say modify ``index-url``? What are the workaround steps?

**Comment by littlemo** [comment]
> Hey, what do you mean when you say modify `index-url`? What are the workaround steps?

Just Modify `~/.pip/pip.conf`

```
[list]
format=columns

[global]
#index-url=http://devpi.intra.xx.xx/root/xx/+simple/
#trusted-host=devpi.intra.xx.xx
```

Before I use a pypi from company local
