### ISSUE TITLE
How to install on Windows?

### ISSUE THREAD

**Issue by patrikhuber** [pypa/pipenv#4098]
Hi,

This might be a slightly silly question, but... your readme says at the very top "Windows is a first-class citizen, in our world.". But then in the Installation section https://github.com/pypa/pipenv#installation there are no installation instructions for Windows? "Otherwise, refer to the documentation for instructions.": Even if I click on this docs link https://pipenv.kennethreitz.org/en/latest/#install-pipenv-today I am still unable to read any installation instructions for Windows on that website?

Kind of makes me strongly question the "Windows is a first-class citizen, in our world.", or is there some sarcasm that I fail to see? :-)

Thanks!

**Comment by mikecbone** [comment]
If you follow the documentation, it does tell you that you can install pipenv with `pip install --user pipenv`

**Comment by patrikhuber** [comment]
@mikecbone I must be blind but I can only see instructions for macOS, Debian, Fedora, FreeBSD.
A CTRL+F on the documentation page for the command you gave yields no results. Where is it?

**Comment by mikecbone** [comment]
@patrikhuber 
![image](https://user-images.githubusercontent.com/17406786/72665134-627ba180-39fd-11ea-8e3a-eb2a47af00d5.png)

**Comment by patrikhuber** [comment]
Thanks for the screenshot.

So one needs to follow two links and read three pages until there is some mentioning of a generic install method and/or Windows.

And the instructions on the screenshot are quite convoluted. Nothing that a beginner could make any sense of (I am not a beginner, but I know many people who are and have in fact recently tried to install pipenv (on Windows) and they all came back scratching their heads).

It seems at this point to me that pipenv is primarily meant for macOS and Linux, and Windows is at the very best a second-class citizen.

I would strongly urge you to consider improving the installation instructions for Windows and make it possible for non-expert Windows Python users to know what they have to do to install pipenv.
Just my two cents.

**Comment by danmichaelo** [comment]
Agree. I created a very similar issue a month ago: #4053

**Comment by patrikhuber** [comment]
I am closing this issue in favour of #4053, as it is an exact duplicate.

Two more people in that issue had exactly the same issue as I did, even questioning the "Windows is a first-class citizen, in our world." too ;-).
