### ISSUE TITLE
Use hasvalue from simple repository API as a source for artifact hashes to speed up locking

### ISSUE THREAD

**Issue by fridex** [pypa/pipenv#4102]
### Is your feature request related to a problem? Please describe.

As discussed on Twitter with Kenneth [1], Pipenv could speed up the locking process by not downloading artifacts. Instead, it could use hashvalues exposed by a Python index as described in PEP-503:

> The URL SHOULD include a hash in the form of a URL fragment with the following syntax: #<hashname>=<hashvalue>, where <hashname> is the lowercase name of the hash function (such as sha256) and <hashvalue> is the hex encoded digest.

If hashvalues are not exposed (e.g. private repositories), hashvalues can be computed by downloading artifacts as its donw now (fallback scenario).

[1] https://twitter.com/fridex/status/1216418099580284928

### Describe the solution you'd like

Pipenv could use exposed hashvalues not to download artifacts on each locking.

### Describe alternatives you've considered

The current solution - download and compute hashes of artifacts each time during locking.

**Comment by fridex** [comment]
@kennethreitz mentioned this might be already present in the current master, I haven't check sources, feel free to close this if that's the case.

Also, would you be open to accept a PR for this RFE?

**Comment by fridex** [comment]
@uranusjr ping? any thoughts on this?

**Comment by uranusjr** [comment]
I think this can be filed directly as a PR since it is well-contained and should not affect others parts of the system. Feel free to look into and work on this.

**Comment by fridex** [comment]
> I think this can be filed directly as a PR since it is well-contained and should not affect others parts of the system. Feel free to look into and work on this. (Edit: but remember to still provide a fallback to download artifacts though; the SHOULD means it is still possible for alternative implementstions to not provide a hash in the API.)

Cool, thanks for the reply! :+1:

**Comment by fridex** [comment]
It seems like this behavior is already implemented:

https://github.com/pypa/pipenv/blob/d10b2a216a25623ba9b3e3c4ce4573e0d764c1e4/pipenv/utils.py#L868-L889
