### ISSUE TITLE
Do a release already

### ISSUE THREAD

**Issue by tleonhardt** [pypa/pipenv#4109]
I did a `pip` install of `pipenv` from GitHub using:
```sh
pip3 install -U git+git://github.com/pypa/pipenv
```

I noticed that it fixed a few bugs and also **very noticeably improved the previously crappy performance of pipenv**.  

You folks have done some good work maintaining this project.  I think the Python community would benefit by you doing a release to PyPI.

**Comment by dangelsaurus** [comment]
looks like #1356 is fixed?

**Comment by tleonhardt** [comment]
#4058 has some info in regards to this

**Comment by Flimm** [comment]
This issue seems like a duplicate of https://github.com/pypa/pipenv/issues/3742

**Comment by brainwane** [comment]
Thanks for the note! Am closing as a duplicate of #3742. Thanks again.
