### ISSUE TITLE
Missing % in patched ipaddress.py breaks pipenv

### ISSUE THREAD

**Issue by usta** [pypa/pipenv#4112]
In   https://github.com/pypa/pipenv/blob/21e9e242449b4a1dbf112dbec168744528a14ecc/pipenv/patched/notpip/_vendor/ipaddress.py#L1106
the % is forgotten so it breaks pipenv

raise TypeError("%s and %s are not of the same version" (a, b))
must be
raise TypeError("%s and %s are not of the same version" % (a, b))

**Comment by usta** [comment]
gitblame says that you have added those lines @techalchemy

**Comment by frostming** [comment]
Sorry for the delayed reply.

We are using a complicated vendor process and this bug comes from the vendor `ipaddress` of the vendored `pip 19.0.3`, which is renamed as `notpip`.

`ipaddress` has fixed the bug in the latest release, the correct way is to update the `notpip`.

**Comment by usta** [comment]
With commit 3f9f359c0e563d30a60f0d1e4633eea9f964b610 this already fixed.
