### ISSUE TITLE
Changing index URL in Pipfile does not update it in Pipfile.lock

### ISSUE THREAD

**Issue by andreif** [pypa/pipenv#4116]
### Issue description

Our Pipfile contains source section

```ini
[[source]]
name = "fury"
url = "${GEMFURY_URL}"
verify_ssl = true
```

When we rotate GemFury token, the URL changes in the env var. We run

```sh
GEMFURY_URL=NEW_URL pipenv install --dev
```

### Expected result

Pipfile.lock should contain the new URL.

### Actual result

Pipfile.lock file still has the old URL.

```json
{
    "_meta": {
        "hash": {
            "sha256": "***"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            },
            {
                "name": "fury",
                "url": "OLD_URL",
                "verify_ssl": true
            }
        ]
    },
```

**Comment by jochenparm** [comment]
I think you're supposed to execute a 'pipenv update'?

**Comment by andreif** [comment]
But I don't want to update, I want to install the locked packages using another index URL.

**Comment by jochenparm** [comment]
Afaik, update simply means to create a new lock file. If you've correctly
specified your versions of everything that needs to be pinned in your
pipfile, it won't update anything that shouldn't be updated

**Comment by andreif** [comment]
This means Pipfile is now good old requirements.txt again and sub-dependencies are getting randomly updated.

**Comment by jochenparm** [comment]
Not really true, but I don't see how you expect the lockfile to get updated
by itself.

**Comment by andreif** [comment]
Not true? I thought you meant locking all sub-dependencies in Pipfile as well just to ensure nothing changes when I simply update a URL for one of indexes.

**Comment by andreif** [comment]
So I have to use it as reequirements.txt -- either locking all sub-deps or having a risk of unexpectedly update something and potentially break the system.

**Comment by matteius** [comment]
Can this be rechecked on `pipenv=2022.8.19`?
