### ISSUE TITLE
`pipenv lock` does not add `sys_platform` markers for child dependencies

### ISSUE THREAD

**Issue by mgmarino** [pypa/pipenv#4117]
### Issue description

When locking a Pipfile with [watchdog (0.10.0)](https://pypi.org/project/watchdog/0.10.0/) on Mac OS X, the child dependencies are listed in the lock file without `sys_platform` markers.  These child dependencies are listed correctly with their sys_platform markers in the [setup.py file](https://github.com/gorakhargosh/watchdog/blob/master/setup.py#L76).  Since the lock file does not have the markers, subsequent installation on a linux machine fails.

This seems related to #3063 (and possibly the same underlying issue), but I would argue that the use case is different since we are not listing the markers explicitly in the Pipfile.  I found a set of other issues with _similar_ problems, but all seemed to be related to propagating markers from the Pipfile.  

### Expected result

When created on a mac, the lock file should include any markers on child dependencies.

### Actual result

See below (support output includes the lock file).

### Steps to replicate

Run `pipenv lock` on the following Pipfile on Mac OS X.

Pipfile:
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
watchdog = "==0.10.0"

[requires]
python_version = "3.6"

```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.6'`

Python installations found:

  - `3.6.5`: `/usr/local/bin/python3`
  - `3.6.5`: `/usr/local/bin/python3.6m`
  - `2.7.16`: `/usr/bin/python`
  - `2.7.16`: `/usr/bin/pythonw`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST '
                     '2019; root:xnu-4903.278.19~1/RELEASE_X86_64',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_SESSION_ID`
  - `SSH_AUTH_SOCK`
  - `LC_TERMINAL_VERSION`
  - `Apple_PubSub_Socket_Render`
  - `COLORFGBG`
  - `ITERM_PROFILE`
  - `SQLITE_EXEMPT_PATH_FROM_VNODE_GUARDS`
  - `XPC_FLAGS`
  - `PWD`
  - `SHELL`
  - `SECURITYSESSIONID`
  - `LC_CTYPE`
  - `TERM_PROGRAM_VERSION`
  - `TERM_PROGRAM`
  - `PATH`
  - `DISPLAY`
  - `LC_TERMINAL`
  - `COLORTERM`
  - `COMMAND_MODE`
  - `TERM`
  - `HOME`
  - `TMPDIR`
  - `USER`
  - `XPC_SERVICE_NAME`
  - `LOGNAME`
  - `__CF_USER_TEXT_ENCODING`
  - `ITERM_SESSION_ID`
  - `SHLVL`
  - `OLDPWD`
  - `ZSH`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `JAVA_HOME`
  - `GRAILS_OPTS`
  - `HOMEBREW_GITHUB_API_TOKEN`
  - `SDKMAN_DIR`
  - `SDKMAN_PLATFORM`
  - `SDKMAN_VERSION`
  - `SDKMAN_LEGACY_API`
  - `SDKMAN_CURRENT_API`
  - `SDKMAN_CANDIDATES_DIR`
  - `GRADLE_HOME`
  - `GRAILS_HOME`
  - `GROOVY_HOME`
  - `NVM_DIR`
  - `NVM_CD_FLAGS`
  - `NVM_NODEJS_ORG_MIRROR`
  - `NVM_IOJS_ORG_MIRROR`
  - `MANPATH`
  - `NVM_BIN`
  - `LC_ALL`
  - `LANG`
  - `LIQUIBASE_HOME`
  - `MYSQLXPB_PROTOBUF_INCLUDE_DIR`
  - `MYSQLXPB_PROTOBUF_LIB_DIR`
  - `MYSQLXPB_PROTOC`
  - `PYSPARK_DRIVER_PYTHON`
  - `PYSPARK_PYTHON`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/opt/nvm/versions/node/v6.10.3/bin:/Users/mgmarino/.sdkman/candidates/groovy/current/bin:/Users/mgmarino/.sdkman/candidates/grails/current/bin:/Users/mgmarino/.sdkman/candidates/gradle/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/mgmarino/tmp`

---------------------------

Contents of `Pipfile` ('/Users/mgmarino/tmp/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
watchdog = "==0.10.0"

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/Users/mgmarino/tmp/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "1a32c7af61644383fbfb29e9c3c689237d1141fbca27a319c9b7d68f68ddf2e6"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "pathtools": {
            "hashes": [
                "sha256:7c35c5421a39bb82e58018febd90e3b6e5db34c5443aaaf742b3f33d4655f1c0"
            ],
            "version": "==0.1.2"
        },
        "pyobjc-core": {
            "hashes": [
                "sha256:1a0fbf012fb575e0adf8c18cfd4453e657cc2c0deb2660c529bf524ba4c9149a",
                "sha256:470ccd754efb468a59426942673dfc3c5c59f33a5b8cae8a7fc1be975c2d4128",
                "sha256:751cdeb436cb181af2e2413015b072075590577c410c7f345080a38dd028b8ec",
                "sha256:8ccf44511cbe438fa6562c423c0c5f1dad7cfc0eadd6d8f112840f8845b44fda"
            ],
            "version": "==6.1"
        },
        "pyobjc-framework-cocoa": {
            "hashes": [
                "sha256:1dc428f867d35007ddf9de5b24eff5bfdf65c58b1d610abcb08bebd94c343312",
                "sha256:245e19156739f8068db474ad9561079cc698f08ef525e299b8eedc5531e02801",
                "sha256:32ba4d0ce811e2088bf0fc360c9545c06586934e895f7133655b8f2182e7019a",
                "sha256:c4077d2e6f96e4f3fd9780d66778cf51d27f414822498b24410e9df7a6a4d531"
            ],
            "version": "==6.1"
        },
        "pyobjc-framework-fsevents": {
            "hashes": [
                "sha256:3a403ce5997cc01f23f1a70f8b4c919311b9a6b1fdd3c3d02d19079d711f954c",
                "sha256:7a635c86af744a1d17f0c6c3913bef87b5fd146e0311c03229eba9e512b81520",
                "sha256:94c6953774b6d69e59d9781951f05ef57e352b3c530d4c236f463444852c3a88",
                "sha256:d2ae8748d1791dc9e3d19b41d3873283ac34ed17ff8fca70f1a199336a0477b5"
            ],
            "version": "==6.1"
        },
        "watchdog": {
            "hashes": [
                "sha256:8e800496cdfb921cfdc62b58a11966d0d2203a35dc005b4b5b8e1ab3097b2eb5"
            ],
            "index": "pypi",
            "version": "==0.10.0"
        }
    },
    "develop": {}
}

```
</details>

**Comment by fluffy-critter** [comment]
I'm having the same problem, also with `watchdog`; it's pulling in `pyobjc` via `pyobjc-framework-FSEvents` (and `pyobjc-framework-Cocoa` for some reason?) and this makes my update and deployment process way trickier, since now my lockfile states platform-specific dependencies which don't actually apply to my deployment target.

Per the resolution on #3187 it seems that Pipenv's maintainers' view is that `pyobjc` should no-op its install on unsupported platforms, but pyobjc's maintainers take the view that people shouldn't be installing it if they aren't using it, per https://bitbucket.org/ronaldoussoren/pyobjc/issues/291/install-fails-on-non-macos-platforms. This gridlock doesn't help with getting things working. A short-term workaround is to do `pipenv install watchdog==0.9.0 && pipenv clean` which removes the dependencies entirely, but I'd love to see this issue get fixed properly.

**Comment by techalchemy** [comment]
this _was_ an intentional decision early on in the project history largely because of the challenges involved in merging markers across resolution branches.  It's a bit of technical dependency resolution information but it is also a large part of what has delayed this release -- tons of work has gone into thinking through that problem.

I am fairly convinced at this point that, as long as we can accurately trace all of the parents of a given dependency (i.e. we are sure it doesn't have other parents in the resolution graph), we can propagate markers down to the relevant children.

In the interim you may unfortunately be best served by manually including the markers in your lockfile and/or adding `Pipfile` entries for the packages in question and including the relevant markers there.

**Comment by matteius** [comment]
I think a new(er) issue should be opened or tagged if there is still a request or issue with the markers.
