### ISSUE TITLE
When is the next release ?

### ISSUE THREAD

**Issue by linusguan** [pypa/pipenv#4127]
Hi, 
I recently came across pipenv and really liked the notion pipenv represents. 
However, the infrequent release concerns me. I can see that there is active development going on but have no idea why new release is being withheld for so long. 
Is there any reason for not releasing new versions?
Cheers!

**Comment by shawalli** [comment]
https://github.com/pypa/pipenv/issues/4058

**Comment by sclarson** [comment]
For what it is worth you can also install the latest master as the released version: 
`
python -m pip install -U git+git://github.com/pypa/pipenv@master
`

**Comment by brainwane** [comment]
I spoke with @techalchemy in IRC today and pipenv now has an update in https://github.com/pypa/pipenv/issues/3369#issuecomment-594875477 .

**Comment by Flimm** [comment]
This a duplicate of several other GitHub issues, like #4048 . Can we close this issue?

**Comment by linusguan** [comment]
Closing as we now have a release tracking issue: https://github.com/pypa/pipenv/issues/3369
