### ISSUE TITLE
Improve pipenv roadmap and contributor-maintainer processes

### ISSUE THREAD

**Issue by lucidyan** [pypa/pipenv#4130]
To begin with, I’ll explain: I respect the developers of Pipenv and am very glad that such tools are being developed.

But damn it: for more than a year, no releases, no answers, no roadmaps - nothing. Chat in slack is also empty. And this is with the [officially recommended dependency management tool](https://packaging.python.org/guides/tool-recommendations/)! 

Okay, two months ago we received a response from the maintainer @techalchemy, he promised a rollout soon and hung a critical label on the release task:
https://github.com/pypa/pipenv/issues/4058#issuecomment-565550646
Hurrah?

Not so far. From July last year and to the present moment, he hasn’t done a single commit (correct me, if I'm wrong) in this repo. 

And on the [pulse](https://github.com/pypa/pipenv/graphs/contributors), it generally seems that the project is dead. For comparison, look at the [pulse of poetry](https://github.com/python-poetry/poetry/graphs/contributors)

The [last commit to the master](https://github.com/pypa/pipenv/runs/386366456) was made in November 2019 and breaks the tests, but who cares!

---

Okay, I’ll write again that my goal is not to offend anyone. But at the moment we have the main tool of the language, which is not supported by the maintainer. Which, in turn, do not want to somehow share their plans or solve a problem.

It's time to face the truth, look into your issues: you have failed completely to support the most important project for the python community. Admit this officially, and not in a hidden issue, but on the main page and write about your solution.

As I see the solutions (from the softest to the most radical):
- Write a clear roadmap, make it public domain and attract people to contributing
- Choose a new Maintainer
- Close the project and join forces with @sdispater

**Comment by hartwork** [comment]
355 issues and 32 pull requests seem a bit much for a one or two hobbyist main maintainers. Seems like pipenv needs funding to get somewhere again. I just contacted the Python Software Foundation by mail on this matter.

**Comment by lucidyan** [comment]
@hartwork Please write here when you receive an answer from the PSF, thanks!

**Comment by hartwork** [comment]
> @hartwork Please write here when you receive an answer from the PSF, thanks!

I got one reply now. While feel that it's not appropriate for me to quote that reply verbatim here, it seems fair to say that I was pointed to the [PSF grants program](https://www.python.org/psf/grants/) and to work with the current maintainers of the project. That makes good sense to me.

Based on the Git history on `master` of last 12 months, I obtained this list of people:
```console
# git log --since="1 year ago" master  | fgrep Author | sed -e 's,frostming,Frost Ming,' -e 's,frostming@tencent.com,mianghong@gmail.com,' -e 's, <.*>,,' | sort | uniq -c | sort -n -r | sed -e 's,Author: ,,' | head -n5
    305 Dan Ryan
     89 Frost Ming
     24 Tapasweni Pathak
     11 John Vandenberg
     10 Kenneth Reitz
```

I'll try contact these people now, putting you @lucidyan in CC.

**Comment by svermeulen** [comment]
Is there a way for people to donate to this project?   I couldn't find a link in the docs

**Comment by Flimm** [comment]
https://github.com/pypa/pipenv/issues/4058

**Comment by oteph** [comment]
@hartwork any updates?

**Comment by hartwork** [comment]
> @hartwork any updates?

I got a a first short reply from @techalchemy on 2020-02-22, replied back to him on 2020-02-23 with questions, waiting for a reply since then. No replies from the other four people so far.

**Comment by lucidyan** [comment]
@techalchemy 
@frostming 
@tapaswenipathak 
@jayvdb 
@kennethreitz 

Will you give us any comments on the status of the project?

**Comment by brainwane** [comment]
I spoke with @techalchemy in IRC today and pipenv now has an update in https://github.com/pypa/pipenv/issues/3369#issuecomment-594875477 .

**Comment by brainwane** [comment]
Thanks to everyone who commented in this issue.

Pipenv is working toward a new release -- see #3369 for specific details. The goal is to get that out this month.

I helped @techalchemy write a new update email he's just posted [on distutils-sig](https://mail.python.org/archives/list/distutils-sig@python.org/thread/EY2KKSWVCYBVO2RB6OMD7TFOWO35B2WG/) (mirrored [on the pypa-dev list](https://groups.google.com/forum/#!msg/pypa-dev/qLO8Pd4i_Co/AHUkg-2pBgAJ)). Dan notes:

> As some of you may already know, I recently changed jobs and am now working for Canonical where I have part of my time allocated to open source work in general (and pipenv in particular).

So: thanks, Canonical!

Dan's email also includes a few ways you can help, directly and indirectly, to expedite this release.

----

#3369 is where people can watch the progress towards the next pipenv release. I've retitled this issue to reflect the TODOs that do still need to happen even after this release:

>* Write a clear roadmap, make it public domain and attract people to contributing

And - where you wrote "Choose a new Maintainer" - I'd say:

>* Add new maintainers

**Comment by brainwane** [comment]
As a step towards a clearer future roadmap: @frostming @uranusjr @techalchemy I see that [this milestone was closed in mid-2018](https://github.com/pypa/pipenv/milestone/4) but isn't quite finished. Should those issues go into a milestone for, say, a July release?

**Comment by uranusjr** [comment]
Some of them would be doable, e.g. *Activate PIPENV_VENV_IN_PROJECT with --local*. But both the Pipfile override and lock file metadata issues seem to be very involved and too far from being implementable IMO.

**Comment by brainwane** [comment]
Per [Dan's announcement just now](https://discuss.python.org/t/announcement-pipenv-beta-release/4051/1) the project's going through some process, communication, & related changes. @techalchemy after you get through the next release, I think working with @frostming and @uranusjr on a roadmap would be a good way to organize what would go into the subsequent release.

**Comment by brainwane** [comment]
[Pipenv 2020.5.28 is now out](https://pypi.org/project/pipenv/)!

This roadmap and contribution process issue is, as I understand it, where folks will talk about improving the release cadence in the future. @techalchemy @frostming and @uranusjr are in charge of this, but I think next steps are:

1. Set up a milestone for the next release
2. Assess existing resources (who is committing time & money to Pipenv?)
3. Start a public roadmap
4. Add new maintainers
5. Make a first pass on triaging/responding to all outstanding issues and pull requests
6. Polish new contributor instructions (such as improving [manual testing instructions](https://pad.sfconservancy.org/p/help-test-pipenv-2020-03-26) and moving them into the docs)
7. Start attracting more people to contributing

and I believe this sequence will go faster or slower depending on what Pipenv finds out in Step 2 (how much money and time is available even to do this). Could take a month, could take a year. Personally, I have donated maybe 16 hours to helping shepherd the most recent release and making comments like this one, in case that is a useful data point. (I don't plan to donate more time to Pipenv this year.)

> Is there a way for people to donate to this project? I couldn't find a link in the docs

I'll quote [Dan's post to the Discourse forum](https://discuss.python.org/t/announcement-pipenv-beta-release/4051):

> If your company uses Pipenv, ask them to [sponsor Python packaging via the PSF ](https://pyfound.blogspot.com/2020/04/sponsoring-python-packaging.html) so there’s a stronger fund for packaging work.

**Comment by hugovk** [comment]
Tidelift has an estimated $371.12/month available for the maintainers ("lifters").

https://tidelift.com/lifter/search/pypi/pipenv

**Comment by matteius** [comment]
I am closing this issue out as myself and @oz123 are the current maintainers of the last half year.  

I do have a question for @hugovk  -- I followed that link https://tidelift.com/lifter/search/pypi/pipenv and it says `This project is a part of the Tidelift Subscription. Tidelift is already paying the maintainers of this package for [project maintenance]`  Do you know is there anyway to verify if payments are being made and to who for the `pipenv` mainteance?

**Comment by hugovk** [comment]
I suggest you contact Tidelift directly, they should be able to help out:

https://tidelift.com/lifter/contact-us

**Comment by oz123** [comment]
I would definitely love to see this payment goes for us
