### ISSUE TITLE
No useful information provided with --verbose option when locking

### ISSUE THREAD

**Issue by jo7ueb** [pypa/pipenv#4135]
I'd like to see what `pipenv` is doing during locking because it's tooooooo sloooooow.
I tried to use `--verbose` option to see what's going on, but it shows nothing.

```
[s1830001@vpcc-041 signate_ssd]$ pipenv lock -v
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
? Locking...
        (... waiting for tens of minutes, but nothing happens)
```

I expect some useful information for `--verbose` option.
Is it possible to show something? (e.g. current progress)

Thanks.

**Comment by stardust85** [comment]
+1, it would help to debug https://github.com/pypa/pipenv/issues/2681

**Comment by matteius** [comment]
There is plenty of verbose output these days.  I am closing this out as completed.
