### ISSUE TITLE
Errno 71 protocol error / pipenv failed to create virtual env

### ISSUE THREAD

**Issue by Brettfodor** [pypa/pipenv#4136]
So I have installed a VM via Virtual Box / Vagrant on my Windows machine.  I am attempting to create a virtual environment in one of the directories, and I have tried using venv, virtualenv and now pipenv and I am getting the same error for all.  I have referred to [2084](https://github.com/pypa/pipenv/issues/2084) and the thread preceding that to no avail.  Can anyone help me discern why this error is populating?

`[root@rhel7 jms_ic_cms]# pipenv --three
Creating a virtualenv for this project…
Pipfile: /Smucker_Files/jms_ic_cms/Pipfile
Using /usr/local/bin/python3.7m (3.7.4) to create virtualenv…
⠸ Creating virtual environment...OSError: [Errno 71] Protocol error: '/usr/local/bin/python3.7m' -> '/Smucker_Files/jms_ic_cms/.venv/bin/python'

✘ Failed creating virtual environment
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
[pipenv.exceptions.VirtualenvCreationException]:       return f(get_current_context(), *args, **kwargs)
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/cli/command.py", line 208, in cli
[pipenv.exceptions.VirtualenvCreationException]:       clear=state.clear,
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 574, in ensure_project
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 506, in ensure_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 935, in do_create_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       extra=[crayons.blue("{0}".format(c.err)),]
[pipenv.exceptions.VirtualenvCreationException]:
Failed to create virtual environment.
`

**Comment by zachspar** [comment]
I am getting an issue I think may be related.

```
python pipenv Error: [Errno 71] Protocol error: 'lib' -> /vagrant/home/p1/env/lib64
```
I am trying to create a virtual environment on Ubuntu/bionic64 vagrant machine with the following command:
`python3 -m venv env`

Pip and python virtualenv have been installed.

Has this issue been looked at?

**Comment by JonathanRys** [comment]
I am also getting the following on Windows:
```
Error: [Errno 71] Protocol error: 'lib' -> '/vagrant/venv/lib64'
```
This works fine on my Mac, but when I run it on Windows venv doesn't install

I think this may be related: https://github.com/gratipay/gratipay.com/issues/2327

**Comment by kubac65** [comment]
Windows file system doesn't support symbolic links, so if you're trying to create a virtual environment in a folder shared from the host machine, it's simply not going to work.
