### ISSUE TITLE
Can't upgrade Python subversion

### ISSUE THREAD

**Issue by TensorTom** [pypa/pipenv#4138]
#3539 # Issue description

Can't upgrade Python subversion of a Pipenv environment (3.8 to 3.8.1)

### Expected result

`python --version` should produce 3.8.1

### Actual result

`python --version` still shows 3.8

### Steps to replicate

Change `python_version` from 3.8 to 3.8.1 then run `python update --python 3.8.1`
3.8.1 has already been installed in pyenv and is available on system. I can create new pipenvs with 3.8.1 but I can't upgrade existing project.
-------------------------------------------------------------------------------

not doing that for this. output contains info about my project I don't want to post.

**Comment by TensorTom** [comment]
In desperation, I tried `pipenv --rm` but got: `You are attempting to remove a virtualenv that Pipenv did not create. Aborting.`

**Comment by amhrasmussen** [comment]
Hi @TensorTom, I've found upgrading python versions within pipenv environments slightly tricky. This sequence seems to work for me (having 3.7.7, 3.8.0, 3.8.1 in pyenv, using pipenv master):

> # Create new environment
> touch Pipfile
> pipenv --python 3.7.7
> pipenv run python --version
> # Upgrade by 1. modifying Pipfile 2. running pipenv update 
> sed -i 's/3.7/3.8/g' Pipfile
> pipenv update --python 3.8
> pipenv run python --version

The fact that you cannot --rm the environment, suggests something else is at play. Perhaps manually deleting it will help. Get location with ´pipenv --venv´.

**Comment by frostming** [comment]
Pyenv keeps all legacy installations unless you manually delete it. So install a new subversion of 3.8 **didn't** change the Python version used by venv.

Close it now.
