### ISSUE TITLE
Cannot set setuptools version in Pipfile

### ISSUE THREAD

**Issue by katsar0v** [pypa/pipenv#4149]
### Issue description

I have the following `Pipfile`:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
jupyterhub = "==1.0.0"
jupyterlab = "==0.35.6"
setuptools = "==42.0.0"

[requires]
python_version = "3.6"
```

Unfortunately `pipenv` always installs the latest setuptools (atm is `46.0.0`). Tried `pipenv graph` but setuptools 46.0.0 is not a dependency and choosing a version for this package definitely does not work

### Expected result

I expect to see the proper version using `pip list`.

### Actual result

Output from `pipenv graph | grep setuptools`:

```
- setuptools [required: Any, installed: 46.0.0]
          - setuptools [required: >=18.5, installed: 46.0.0]
            - setuptools [required: Any, installed: 46.0.0]
          - setuptools [required: Any, installed: 46.0.0]
        - setuptools [required: >=18.5, installed: 46.0.0]
          - setuptools [required: Any, installed: 46.0.0]
        - setuptools [required: Any, installed: 46.0.0]
```

### Steps to replicate

Run `pipenv install` using the Pipfile in the description in any `venv` or `virtualenv` environment.
I uploaded a video as well (forgot to update lock file though, but same thing happens with updated lock file): https://drive.google.com/open?id=11b2XTU_lhBW_QTk0SOz1M-yI-atdjPrI

**Comment by amhrasmussen** [comment]
I see the same; with given Pipfile running `pipenv install --python 3.6` gives me setuptools 46.

Contrary to what I would expect, there is no setuptools mentioned in the generated Pipfile.lock.

I can force the specified setuptools 42, with either of

> pipenv install --python 3.6
> pipenv install "setuptools==42"

or
> pipenv install --skip-lock --python 3.6

I'm using https://github.com/pypa/pipenv/commit/d10b2a216a25623ba9b3e3c4ce4573e0d764c1e4.

**Comment by dhallam** [comment]
Same issue as #2364.

**Comment by frostming** [comment]
Close for duplicate
