### ISSUE TITLE
catching pipenv.exceptions.ResolutionFailure

### ISSUE THREAD

**Issue by baddev** [pypa/pipenv#4150]
Is it possible and then, how ? To catch pipenv.exceptions.ResolutionFailure in a script running pipenv install ?

I code a script to update virtual envs automatically but I get this exception as a string. Pipenv is installed in its own directory in my home/bin as a cloned repository.

Thank you.

**Comment by amhrasmussen** [comment]
Hi @baddev 
Just another pipenv user here. I think this is not the right forum for questions about usage of pipenv (https://github.com/pypa/pipenv/blob/master/CONTRIBUTING.md#questions). Perhaps stackoverflow is a better place?

**Comment by baddev** [comment]
Thanks for caring :) I guess you're right : nobody else here seems to be interested to answer anyway.
Nice quarantine to all ! ;)
