### ISSUE TITLE
Error pipenv --python 

### ISSUE THREAD

**Issue by fscosta10** [pypa/pipenv#4153]
I am trying to create a pipenv environment with a specific version of python 3.7.3. 
However, when I try to create with the command  pipenv --python 3.7.3 I am getting this error:

File "/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv/core.py", line 108, in which
    raise RuntimeError("location not created nor specified")
RuntimeError: location not created nor specified

**Comment by amhrasmussen** [comment]
Hi @fscosta10 
I think you need to add some more information to your description. It's not clear to me what is happening from you current description. There's a very nice guide to what a bug report should contain here: https://github.com/pypa/pipenv/blob/master/CONTRIBUTING.md#bug-reports

Also, if you're not sure it's actually a bug in pipenv, then perhaps stackoverflow or similar may have higher probability of getting you somewhere (https://github.com/pypa/pipenv/blob/master/CONTRIBUTING.md#questions).

**Comment by Rukeith** [comment]
I got the same error
