### ISSUE TITLE
pipenv check reports incorrect python-gnupg package version

### ISSUE THREAD

**Issue by yyang-nasuni** [pypa/pipenv#4156]
### Issue description

```bash
# install latest python-gnupg package (version 0.4.5)
# https://pypi.org/project/python-gnupg/
$ pipenv install python-gnupg

# pipenv check was working fine as of 3/16/2020 and starts to reporting following error on 3/17/2020
$ pipenv check
Checking PEP 508 requirements…
Passed!
Checking installed package safety…
37367: python-gnupg <2.2.12 resolved (0.4.5 installed)!
Python-gnupg 2.2.12 - [dirmngr] Avoid possible CSRF attacks via http redirects.  A HTTP query will not anymore follow a 3xx redirect unless the Location header gives the same host.  If the host is different only the host and port is taken from the Location header and the original path and query parts are kept.

```
The required `2.2.12` version is invalid for the python package and looks like reference to actual `gpg` executable version, which is already satisfied on the machine.
```bash
$ gpg --version
gpg (GnuPG) 2.2.19
```

### Expected result

Pass the `pipenv check` as it was before.

### Actual result

The version reported by `pipenv check` is invalid regarding the python package. Would it be possible that some data in the vulnerability DB is changed? Same python package and pipenv worked fine as of 3/16/2020.

### Steps to replicate

1. Install latest `python-gnupg` package.
2. Run `pipenv check`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.7'`

Python installations found:

  - `3.7.7`: `/Users/yyang/.local/share/virtualenvs/demo-qoCfT6nu/bin/python3`
  - `3.7.7`: `/usr/local/bin/python3`
  - `3.7.7`: `/usr/local/bin/python3.7m`
  - `3.7.3`: `/usr/bin/python3`
  - `2.7.16`: `/usr/bin/python`
  - `2.7.16`: `/usr/bin/pythonw`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '19.3.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST '
                     '2020; root:xnu-6153.81.5~1/RELEASE_X86_64',
 'python_full_version': '3.7.7',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TMPDIR`
  - `XPC_FLAGS`
  - `TERM_PROGRAM_VERSION`
  - `LANG`
  - `TERM_PROGRAM`
  - `XPC_SERVICE_NAME`
  - `TERM_SESSION_ID`
  - `TERM`
  - `SSH_AUTH_SOCK`
  - `SHELL`
  - `HOME`
  - `LOGNAME`
  - `USER`
  - `PATH`
  - `SHLVL`
  - `PWD`
  - `OLDPWD`
  - `SAM_CLI_TELEMETRY`
  - `__CF_USER_TEXT_ENCODING`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PIPENV_ACTIVE`
  - `VIRTUAL_ENV`
  - `PS1`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/yyang/.local/share/virtualenvs/demo-qoCfT6nu/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/yyang/Desktop/demo`
  - `VIRTUAL_ENV`: `/Users/yyang/.local/share/virtualenvs/demo-qoCfT6nu`

---------------------------

Contents of `Pipfile` ('/Users/yyang/Desktop/demo/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
python-gnupg = "*"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/Users/yyang/Desktop/demo/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "6a18ebe69cf918a163d78f48cbdddc9fa91f4aabc34a42ebd4feebe86e934d0c"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "python-gnupg": {
            "hashes": [
                "sha256:3353e59949cd2c15efbf1fca45e347d8a22f4bed0d93e9b89b2657bda19cec05",
                "sha256:c095a41f310ad7a4fd393406660ac9bd6c175ccaa0f072f9c18f33be8130a27a"
            ],
            "index": "pypi",
            "version": "==0.4.5"
        }
    },
    "develop": {}
}

```
</details>

**Comment by amhrasmussen** [comment]
Hi @yyang-nasuni 
To me, this looks like an error in the database used for security check (see e.g. #4147). In that case you should report at https://github.com/pyupio/safety-db.

**Comment by yyang-nasuni** [comment]
Thanks @amhrasmussen and I just opened an issue in safety db repo. Yes, we ran in that previous issue a few days ago and this looks similar. Maybe there is some wrong info for the lib in the DB being used by pipenv check.

**Comment by yyang-nasuni** [comment]
Safety DB has been updated and it is all set now.
