### ISSUE TITLE
Not finding Pipfile via PIPENV_PIPFILE with relative location

### ISSUE THREAD

**Issue by n-batalha** [pypa/pipenv#4164]
### Issue description

pipenv is not finding a Pipfile provided with the PIPENV_PIPFILE variable when provided as a relative link, or an absolute link with relative notation e.g. `/Users/REDACTED/Documents/git/wiki/src/somefolder/somefolder/../../../Pipfile`.

It fails with `RuntimeError: Given PIPENV_PIPFILE is not found!`

Running `PIPENV_PIPFILE=/Users/REDACTED/git/wiki/Pipfile pipenv run jupyter --help` works.

### Expected result

It finds the `Pipfile`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/Users/REDACTED/Library/Python/3.7/lib/python/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.7'`

Python installations found:

  - `3.8.1`: `/usr/local/opt/pyenv/versions/3.8.1/bin/python3`
  - `3.7.4`: `/usr/local/bin/python3`
  - `3.7.4`: `/usr/local/bin/python3.7m`
  - `3.7.3`: `/usr/bin/python3`
  - `2.7.16`: `/usr/bin/python`
  - `2.7.16`: `/usr/bin/pythonw`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '19.3.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST '
                     '2020; root:xnu-6153.81.5~1/RELEASE_X86_64',
 'python_full_version': '3.7.4',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `SECURITYSESSIONID`
  - `USER`
  - `COMMAND_MODE`
  - `PATH`
  - `HOME`
  - `SHELL`
  - `LaunchInstanceID`
  - `__CF_USER_TEXT_ENCODING`
  - `XPC_SERVICE_NAME`
  - `SSH_AUTH_SOCK`
  - `XPC_FLAGS`
  - `LOGNAME`
  - `TMPDIR`
  - `CPPFLAGS`
  - `EDITOR`
  - `GIT_SUBREPO_ROOT`
  - `LDFLAGS`
  - `LESS`
  - `LSCOLORS`
  - `MANPATH`
  - `OLDPWD`
  - `PAGER`
  - `PKG_CONFIG_PATH`
  - `PWD`
  - `PYENV_ROOT`
  - `PYENV_SHELL`
  - `RBENV_SHELL`
  - `SHLVL`
  - `ZSH`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `LANG`
  - `COLORTERM`
  - `TERM`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/opt/node@12/bin:/Users/REDACTED/Applications/git-subrepo/lib:/usr/local/opt/openssl/bin:/usr/local/opt/postgresql@10/bin:/usr/local/opt/pyenv/shims:/usr/local/opt/pyenv/bin:/Users/REDACTED/.rbenv/shims:/Users/REDACTED/.rbenv/bin:/Users/REDACTED/bin:/usr/local/bin:/Users/REDACTED/Library/Python/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/Library/TeX/texbin:/usr/local/opt/node@12/bin:/Users/REDACTED/Applications/git-subrepo/lib:/usr/local/opt/openssl/bin:/usr/local/opt/postgresql@10/bin:/usr/local/opt/pyenv/shims:/usr/local/opt/pyenv/bin:/Users/REDACTED/.rbenv/shims:/Users/REDACTED/.rbenv/bin:/Users/REDACTED/REDACTED:/Users/REDACTED/Library/Python/3.7/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `nano`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/REDACTED/git/wiki/src/Data-Engineering/Data-Summary`

---------------------------

</details>

**Comment by n-batalha** [comment]
Strangely, modifying the `Makefile` to do:

```
test:
	printenv
	PIPENV_PIPFILE=${PIPENV_PIPFILE} pipenv run jupytext --help
```

will result in 

```
Creating a virtualenv for this project…
Pipfile: /Users/REDACTED/git/wiki/Pipfile
Using /usr/local/bin/python3 (3.7.4) to create virtualenv…
⠋ Creating virtual environment...Already using interpreter /usr/local/opt/python/bin/python3.7
Using base prefix '/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/REDACTED/.local/share/virtualenvs/wiki-FqT7NnBL/bin/python3.7
Also creating executable in /Users/REDACTED/.local/share/virtualenvs/wiki-FqT7NnBL/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/local/bin/python3

✔ Successfully created virtual environment! 
Virtualenv location: /Users/REDACTED/.local/share/virtualenvs/wiki-FqT7NnBL
```

When strangely that file was already there with all packages installed in an existing environment. This last issue seems related to the mapping it tries to do between a `Pipfile` and the virtualenv?

**Comment by n-batalha** [comment]
I've since updated my issue after further investigation and narrowed down the cause. One was the current issue, and another was https://github.com/pypa/pipenv/issues/4115.

For those looking to address the above, you can [use `realpath`](https://stackoverflow.com/a/14892459) to transform the link into one that `pipenv` understands.

**Comment by matteius** [comment]
Can this be rechecked on `pipenv==2022.8.19`?
