### ISSUE TITLE
The term 'pipenv' is not recognized as the name of a cmdlet, ...

### ISSUE THREAD

**Issue by camador29** [pypa/pipenv#4165]
I've installed pipenv successfully but when i try to run for example 

pipenv django==3.0

i get the error below

pipenv : The term 'pipenv' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.

I've tried to add the folder where the pipenv script is to the path but still get the same error (pipenv is not recognised)

C:\Users\My-set PATH=%PATH%; C:\Users\My-USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts

Actually, when i run the command below it seems to work although then i get an error installing the package. any ideas on how to correct this? I'm very new to all this!

python -m pipenv install django

Installing django…
Adding django to Pipfile's [packages]…
Installation Succeeded
Installing dependencies from Pipfile.lock (a54e8e)…
An error occurred while installing asgiref==3.2.7 --hash=sha256:8036f90603c54e93521e5777b2b9a39ba1bad05773fcf2d208f0299d1df58ce5 --hash=sha256:9ca8b952a0a9afa61d30aa6d3d9b570bb3fd6bafcf7ec9e6bed43b936133db1c! Will try again.
An error occurred while installing django==3.0 --hash=sha256:6f857bd4e574442ba35a7172f1397b303167dae964cf18e53db5e85fe248d000 --hash=sha256:d98c9b6e5eed147bc51f47c014ff6826bd1ab50b166956776ee13db5a58804ae! Will try again.
An error occurred while installing pytz==2019.3 --hash=sha256:1c557d7d0e871de1f5ccd5833f60fb2550652da6be2693c1e02300743d21500d --hash=sha256:b02c06db6cf09c12dd25137e563b31700d3b80fcc4ad23abb7a315f2789819be! Will try again.
An error occurred while installing sqlparse==0.3.1 --hash=sha256:022fb9c87b524d1f7862b3037e541f68597a730a8843245c349fc93e1643dc4e --hash=sha256:e162203737712307dfe78860cc56c8da8a852ab2ee33750e33aeadf38d12c548! Will try again.
  ================================ 4/4 - 00:00:27
Installing initially failed dependencies…
     ================================ 4/4 - 00:00:38
[pipenv.exceptions.InstallError]:   File "C:\Users\amador.c.2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pipenv\cli\command.py", line 235, in install
[pipenv.exceptions.InstallError]:       retcode = do_install(
[pipenv.exceptions.InstallError]:   File "C:\Users\amador.c.2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pipenv\core.py", line 1983, in do_install
[pipenv.exceptions.InstallError]:       do_init(
[pipenv.exceptions.InstallError]:   File "C:\Users\amador.c.2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pipenv\core.py", line 1246, in do_init
[pipenv.exceptions.InstallError]:       do_install_dependencies(
[pipenv.exceptions.InstallError]:   File "C:\Users\amador.c.2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pipenv\core.py", line 862, in do_install_dependencies
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, False, failed_deps_queue, retry=False)
[pipenv.exceptions.InstallError]:   File "C:\Users\amador.c.2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pipenv\core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting asgiref==3.2.7', '  Using cached asgiref-3.2.7-py2.py3-none-any.whl (19 kB)', 'Installing collected packages: asgiref']
[pipenv.exceptions.InstallError]: ["ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\\\Program Files\\\\WindowsApps\\\\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\\\\Lib\\\\site-packages\\\\asgiref'", 'Consider using the `--user` option or check the permissions.']
ERROR: ERROR: Package installation failed...

**Comment by camador29** [comment]
solved

**Comment by tomsfb** [comment]
how did u solve it @camador29 ?
