### ISSUE TITLE
Deprecation process

### ISSUE THREAD

**Issue by brainwane** [pypa/pipenv#4177]
I just spoke with @techalchemy and he mentioned that pipenv does not currently have a process for deprecating a feature/command. This issue is a place for pipenv maintainers and other core contributors to discuss that, and come up with and implement a deprecation process.

**Comment by wadkar** [comment]
@fridex I think the correct question to ask is, which features/commands (or APIs to be precise) are planned for deprecation given that pipenv [doesn't follow semantic versioning](https://pypi.org/project/pipenv/#history)?

**Comment by Darrenmeehan** [comment]
I would assume that Python2.x is already deprecated? Or will be deprecated at some point?
This is something that `pip` has deprecated, but I dont know of any process related to this.
https://pip.pypa.io/en/latest/development/release-process/#python-2-support
