### ISSUE TITLE
Pipenv lock timeout with a pre release dev-package overriding another's dependencies.

### ISSUE THREAD

**Issue by dlamblin** [pypa/pipenv#4178]
### Issue description

Either I'm using pipenv wrong, or it had error cases.
For OS X Mojave the pygame<2.0.0 doesn't draw anything, so trying to do a quick demo with pgzero which relies on pygame I wanted to install pygame==2.0.0.dev6 with pgzero.
(note I also tried putting both packages together without any dev-packages, but that basically didn't trust I knew what I wanted in a pre-release dev package version).

```ini
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = false

[dev-packages]
pygame = ">=2.0.0.dev6"

[packages]
pgzero = "*"

[requires]
python_version = "3.7"

[pipenv]
allow_prereleases = true
```
then
```bash
pipenv shell
rm -rf ~/Library/Caches/pip ~/Library/Caches/pipenv
# This was done because previously it errored out about incompatible versions in the resolved dependencies but recommended I run pipenv clean, but clean didn't seem to do much.
pipenv install --dev
⠧ Locking...  # Ad infinium
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/pexpect/expect.py", line 109, in expect_loop
    return self.timeout()
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x10888c8d0>
searcher: searcher_re:
    0: re.compile('\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
```

### Expected result
At the least fail faster, but preferably do better than 2 single `pip` invocations.
I wanted the same result as:
```bash
pip install pgzero
pip install pygame==2.0.0.dev6
```

### Actual result

I noted the start of the stack trace.

### Steps to replicate

I ran this on a basically fresh Mac too (I used brew to get python 3.7).

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.7'`

Python installations found:

  - `3.7.4`: `/Users/lamblin/VEnvs/sophie-games-Ukt_-U8y/bin/python3`
  - `3.7.4`: `/usr/local/bin/python3`
  - `3.7.4`: `/usr/local/bin/python3.7m`
  - `2.7.16`: `/usr/local/bin/python`
  - `2.7.16`: `/usr/local/bin/pythonw`
  - `2.7.16`: `/usr/bin/python`
  - `2.7.16`: `/usr/bin/pythonw`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST '
                     '2019; root:xnu-4903.278.19~1/RELEASE_X86_64',
 'python_full_version': '3.7.4',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `SHELL`
  - `LSCOLORS`
  - `ITERM_PROFILE`
  - `COLORTERM`
  - `LESS`
  - `XPC_FLAGS`
  - `HISTCONTROL`
  - `TERM_PROGRAM_VERSION`
  - `PIPENV_ACTIVE`
  - `HISTSIZE`
  - `LESS_TERMCAP_se`
  - `LESS_TERMCAP_so`
  - `JAVA_HOME`
  - `SSH_AUTH_SOCK`
  - `HISTTIMEFORMAT`
  - `TERM_SESSION_ID`
  - `ITERM_PREV_PS1`
  - `EDITOR`
  - `ITERM_ORIG_PS1`
  - `PWD`
  - `LOGNAME`
  - `MANPATH`
  - `VIRTUALENVWRAPPER_VIRTUALENV`
  - `CDPATH`
  - `COMMAND_MODE`
  - `VIRTUALENVWRAPPER_SCRIPT`
  - `ITERM_SESSION_ID`
  - `PIP_PYTHON_PATH`
  - `LDFLAGS`
  - `HOME`
  - `LANG`
  - `HADOOP_USER_NAME`
  - `LS_COLORS`
  - `SECURITYSESSIONID`
  - `VIRTUAL_ENV`
  - `AIRFLOW_HOME`
  - `VIRTUALENVWRAPPER_WORKON_CD`
  - `TMPDIR`
  - `LC_TERMINAL`
  - `IT_WIN`
  - `CPPFLAGS`
  - `CLICOLOR`
  - `VIRTUALENVWRAPPER_PYTHON`
  - `VIRTUALENVWRAPPER_VIRTUALENV_ARGS`
  - `WORKON_HOME`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `TERM`
  - `LESS_TERMCAP_mb`
  - `LESS_TERMCAP_me`
  - `LESS_TERMCAP_md`
  - `USER`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `COLORFGBG`
  - `VISUAL`
  - `LC_TERMINAL_VERSION`
  - `VIRTUALENVWRAPPER_PROJECT_FILENAME`
  - `HADOOP_NAMENODE`
  - `SHLVL`
  - `LESS_TERMCAP_ue`
  - `LESS_TERMCAP_us`
  - `PAGER`
  - `IT_PAN`
  - `PYTHONDONTWRITEBYTECODE`
  - `XPC_SERVICE_NAME`
  - `COUSER`
  - `PS1`
  - `LC_ALL`
  - `Apple_PubSub_Socket_Render`
  - `PATH`
  - `VIRTUALENVWRAPPER_HOOK_DIR`
  - `HISTFILESIZE`
  - `PROJECT_HOME`
  - `IT_TAB`
  - `OLDPWD`
  - `GOPATH`
  - `__CF_USER_TEXT_ENCODING`
  - `TERM_PROGRAM`
  - `BASH_FUNC_piptry%%`
  - `BASH_FUNC_knownhosts_delete_line%%`
  - `BASH_FUNC_javaclean%%`
  - `BASH_FUNC_piptry3%%`
  - `BASH_FUNC_iterm_update%%`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/lamblin/VEnvs/sophie-games-Ukt_-U8y/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/openssl/bin:/usr/local/opt/mysql-client/bin:/usr/local/sbin:/usr/local/opt/sqlite/bin:/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/go/libexec/bin:/bin:/Users/lamblin/go/bin:/Users/lamblin/go/bin`
  - `SHELL`: `/usr/local/bin/bash`
  - `EDITOR`: `/usr/bin/vi`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/lamblin/Documents/prj/sophie-games`
  - `VIRTUAL_ENV`: `/Users/lamblin/VEnvs/sophie-games-Ukt_-U8y`

---------------------------

Contents of `Pipfile` ('/Users/lamblin/Documents/prj/sophie-games/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = false

[dev-packages]
pygame = ">=2.0.0.dev6"

[packages]
pgzero = "*"

[requires]
python_version = "3.7"

[pipenv]
allow_prereleases = true

```

</details>

**Comment by matteius** [comment]
Can this be rechecked on `pipenv==2022.8.19`?
