### ISSUE TITLE
Would pip/pip3 work as previously after installing pipenv using `pip3 install --user pipenv`

### ISSUE THREAD

**Issue by gonerodes** [pypa/pipenv#4179]
After installing with `pip3 install --user pipenv` then `pip` and `pip3` will be used from `~/.local/bin` since its path is by default entered at the start of `$PATH` (that's what `~/.profile` does by default on ubuntu18 ). 

This means that from then on when I execute pip3 I will access the `~/.local/bin/pip3` command.

Would the functionality of `pip` and `pip3` that exist inside `~/.local/bin` be the same as using `/usr/bin/pip3` or should I change `.profile` to append the `~/local/bin` at the end of `$PATH`?

**Comment by frostming** [comment]
I think they are not the same, the pip at `.~/.local/bin` should be newer than the system installed `pip`, but after all, newer is better, you should likely get a better experience.

**Comment by frostming** [comment]
Close for not relevant to pipenv
