### ISSUE TITLE
pipenv install never resolves and creates many concurrent python processes

### ISSUE THREAD

**Issue by flaudanum** [pypa/pipenv#4180]
### Issue description
Command `pipenv install <package name>`  starts tens of concurrent python processes. The command never resolves and my machine performance decreases as the number of python processes increases.

### Expected result
If I run the command below in an empty directory:
```
pipenv install six
```
I assume that a virtual environment is created with the package `six`. A `Pipfile` and a `Pipfile.lock` should also be created.

### Actual result

Pipenv gets stuck at the step of creating the virtual environment. The activity bars (`[=== ]`) are still moving. Something like 6 concurrent python processes are created. At some point this number starts increasing dramatically.

### Steps to replicate
Cannot tell for this is very likely caused by a specific state of my machine. I would be interested by having some clues about what to inquiry.

-------------------------------------------------------------------------------
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'c:\\program files\\python37\\lib\\site-packages\\pipenv'`

Python location: `'c:\\program files\\python37\\python.exe'`

Python installations found:

  - `3.7.4`: `C:\Program Files\Python37\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.4',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.18362',
 'python_full_version': '3.7.4',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DEFLOGDIR`
  - `DRIVERDATA`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `HOMESHARE`
  - `INTELLIJ IDEA COMMUNITY EDITION`
  - `JAVA_HOME`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `PYCHARM COMMUNITY EDITION`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VBOX_MSI_INSTALL_PATH`
  - `WINDIR`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\MATLAB\R2019a\bin;C:\Program Files\Java\jdk1.8.0_241\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\f.laudarin\AppData\Local\Microsoft\WindowsApps;C:\Users\f.laudarin\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\f.laudarin\AppData\Roaming\npm;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.1\bin;;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.2\bin;;C:\Program Files (x86)\Launch4j;C:\apache-maven-3.6.3\bin;`

---------------------------

</details>

**Comment by matteius** [comment]
This should not be an issue on `pipenv==2022.8.19`
