### ISSUE TITLE
Pipenv collects a restriction from somewhere and doesn't show it in the graph output

### ISSUE THREAD

**Issue by feakuru** [pypa/pipenv#4182]
Hi! Sorry if this has been discussed before. I tried my best to find a relevant thread.

I have a huge project which I am trying to convert to pipenv. I wrote a Pipfile (specifying most of the dependencies as `"*"`). Now, when I run `$ pipenv install`, I get the error `"Could not find a version that matches django==1.11,>=1.11,>=1.3,>=1.9,>=2.0.1,>=2.2"`, although when I delete the virtual environment, recreate it and run `$ pipenv install --skip-lock && pipenv graph`, I get a graph with no mention of the `">=2.0.1"` or `">=2.2"` restrictions. Is that normal? If so, how can I figure out where those restrictions come from?

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python2.7/dist-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.8.0`: `/usr/bin/python3.8`
  - `3.5.7`: `/usr/local/bin/python3.5m`
  - `3.5.7`: `/usr/local/bin/python3`
  - `3.7.5`: `/usr/bin/python3.7m`
  - `2.7.17`: `/usr/bin/python2.7`
  - `3.7.5`: `/usr/bin/python3.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.3.0-46-generic',
 'platform_system': 'Linux',
 'platform_version': '#38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020',
 'python_full_version': '2.7.17',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `LESS`
  - `QT4_IM_MODULE`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_SESSION_TYPE`
  - `QT_IM_MODULE`
  - `LOGNAME`
  - `USER`
  - `PATH`
  - `PIP_SHIMS_BASE_MODULE`
  - `HOME`
  - `ZSH`
  - `DISPLAY`
  - `SSH_AGENT_PID`
  - `LANG`
  - `MANAGERPID`
  - `SHELL`
  - `XAUTHORITY`
  - `JOURNAL_STREAM`
  - `SESSION_MANAGER`
  - `XDG_DATA_DIRS`
  - `MANDATORY_PATH`
  - `TERM`
  - `GNOME_DESKTOP_SESSION_ID`
  - `CLUTTER_IM_MODULE`
  - `WINDOWPATH`
  - `XMODIFIERS`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `MONITORADO_OAUTH_TOKEN`
  - `GPG_AGENT_INFO`
  - `XDG_SESSION_CLASS`
  - `INVOCATION_ID`
  - `USERNAME`
  - `XDG_SESSION_DESKTOP`
  - `XDG_RUNTIME_DIR`
  - `SSH_AUTH_SOCK`
  - `VTE_VERSION`
  - `GDMSESSION`
  - `IM_CONFIG_PHASE`
  - `GNOME_SHELL_SESSION_MODE`
  - `PIP_PYTHON_PATH`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `_`
  - `GTK_MODULES`
  - `GTK_IM_MODULE`
  - `DESKTOP_SESSION`
  - `LSCOLORS`
  - `XDG_CONFIG_DIRS`
  - `DEFAULTS_PATH`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `OLDPWD`
  - `SHLVL`
  - `PWD`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `DOCKER_TOKEN`
  - `COLORTERM`
  - `XDG_MENU_PREFIX`
  - `LS_COLORS`
  - `PAGER`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/feakuru/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/feakuru`

---------------------------

</details>

**Comment by feakuru** [comment]
UPD: GitHub suggested issues that are alike, and one of them mentions that `pip graph` doesn't show dependencies from extras. I manually checked all extras and it doesn't look like there's any connection.

**Comment by matteius** [comment]
Could this be rechecked on `pipenv==2022.8.19`?
