### ISSUE TITLE
Docs PR/CI enhancement: skip tests for docs-only changes

### ISSUE THREAD

**Issue by ncoghlan** [pypa/pipenv#4185]
At the moment, the full CI is always running, even for docs-only changes like #4175

After #4169 is merged, it would be good to look into adopting CPython's Azure Pipelines prebuild checks, so that docs-only PRs only build the docs, rather than running the full test suite: https://github.com/python/cpython/blob/master/.azure-pipelines/prebuild-checks.yml

**Comment by matteius** [comment]
Closing this issue as outdated -- we have done some work to the CI flows including a pre-linting phase and we are using GitHup actions.
