### ISSUE TITLE
Your API Key is invalid

### ISSUE THREAD

**Issue by tucked** [pypa/pipenv#4188]
```
$ pipenv check
Checking PEP 508 requirements…
Passed!
Checking installed package safety…
An error occurred:
Your API Key '1ab8d58f-5122e025-83674263-bc1e79e0' is invalid. See https://goo.gl/O7Y1rS

2020-04-11T10:08:05-0700 exit 1
```

I can provide `pipenv --support` if necessary.

**Comment by techalchemy** [comment]
Thanks for the report -- We had received the ok from the pyup team to include the API key in pipenv, so I'm not sure why it's been revoked, though I suspect this is going to cause some pain for a lot of users. /cc @pyupio @jayfk (related context: #1651) -- was this intentional? How would you like us to move forward?

**Comment by jayfk** [comment]
@Jwomers is now taking care of pyup.io with the help of @harlekeyn and @rafaelpivato. ccd

**Comment by Ochirgarid** [comment]
The same issue is occurring for me. Looking forward for the fix.

**Comment by alekpikl** [comment]
I have the same issue. Looking forward to the fix! :) 
Thanks!

**Comment by kasioumis** [comment]
Is there a way to temporarily ignore this with `pipenv check --ignore [something]`?

**Comment by joaokrabbe** [comment]
I have the same issue. Looking forward to the fix! :)
Thanks!

**Comment by cemsbr** [comment]
A workaround is to install _safety_ and use `safety check` instead of `pipenv check`.

**Comment by pgagnon** [comment]
> A workaround is to install _safety_ and use `safety check` instead of `pipenv check`.

`pipenv lock --requirements | safety check --stdin`

**Comment by techalchemy** [comment]
After a brief conversation with the new pyup.io management,  (and it seems others have observed this already) we won't need the API key anymore to connect with pyup.io. So we will remove the API key.  In the meantime I believe this can be resolved by simply setting the environment variable `PIPENV_PYUP_API_KEY=""`.

**Comment by kristang** [comment]
I don't want to to tell the maintainers how to handle issues and fixes, but maybe keep issues open until a fix is actually released. This closed issue gives the impression that the problem has been fixed, even though it has only been merged into master, but not yet released.

**Comment by jdobes** [comment]
@kristang pipenv check was actually working in last 2 weeks using the old pipenv version, but here we go again...

**Comment by kristang** [comment]
> @kristang pipenv check was actually working in last 2 weeks using the old pipenv version, but here we go again...

Not sure I understand how it has been working? Did https://pyup.io/ make a change, that has then been reverted now? Or do you mean pipenv has worked withe the work-around with an environment variable?

**Comment by mattnewell** [comment]
I can't speak for @jdobes, but I have a build pipeline, using pipenv 2018.11.26, that runs (at least) nightly. I never applied the environment variable work-around, and have successful runs from April 24 to May 2. On May 2nd it started failing with this issue.

Just wanted to share more information ...

**Comment by kasioumis** [comment]
> but I have a build pipeline, using pipenv 2018.11.26, that runs (at least) nightly. I never applied the environment variable work-around, and have successful runs from April 24 to May 2. On May 2nd it started failing with this issue.

Exact same issue here.

**Comment by kristang** [comment]
It's great that it was working for people,, but my concern is mainly: 1) Has the issue been identified to originate from pipenv? 2) Has a fix then been deployed for pipenv that can be used?

To me it seems like the success for the last two weeks for people have been due to an external change from pypu (possible no longer requiring an API key?), and not an actual solution added to pipenv?

**Comment by frostming** [comment]
@kristang @kasioumis Did you try the latest prerelease version?

**Comment by pietrodn** [comment]
I confirm the issue. We are using pipenv 2018.11.26 in production and are getting this error today in CI.
cc @ralbertazzi

**Comment by kristang** [comment]
> @kristang @kasioumis Did you try the latest prerelease version?

No, but thank you for the suggestion. I'm hesitant to do so, as it concerns our entire production build setup, and we would like to avoid any pre-releases.

**Comment by frostming** [comment]
Yeah, I mean it would be helpful if you can test the prerelease, you should wait for the formal release for your production setup.

**Comment by pietrodn** [comment]
`pipenv check` works correctly for me when using `pipenv-2020.4.1b1`, installed through:

```
pip3 install --upgrade --pre pipenv
```

on a macOS system.

**Comment by mcallaghan-bsm** [comment]
First; tried to update to pipenv latest ... but stable is still:
```
# pip3 list | grep pip
pip                    20.1
pipenv                 2018.11.26

# pip3 install --upgrade pipenv
...
Requirement already up-to-date: pipenv in /root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages (2018.11.26)
...
```
, systems in prod _may not_ want to upgrade to a pre-release ...

Tried workaround to force API key empty, that works
```
# export PIPENV_PYUP_API_KEY=""
# pipenv check
Checking PEP 508 requirements…
Passed!
Checking installed package safety…
.... (no error) ...
```

**Comment by kristang** [comment]
> Yeah, I mean it would be helpful if you can test the prerelease, you should wait for the formal release for your production setup.

Oh, absolutely. I will give it a run. Is there any information you need besides working/not working?

**Comment by kristang** [comment]
2020.4.1b1 works without the environment variable.

Here's some system info:

```
Windows 10 Enterprise
10.0.18363 Build 18363

λ python --version
Python 3.6.8

λ pip list
Package          Version
---------------- ----------
certifi          2019.11.28
pip              18.1
pipenv           2020.4.1b1
setuptools       40.6.2
virtualenv       16.7.8
virtualenv-clone 0.5.3
```

**Comment by wontonst** [comment]
Is there a timeline for when this fix will be released?

**Comment by cemsbr** [comment]
It had been solved for me for days, but I'm having this issue again today.

**Comment by rafaelpivato** [comment]
**WORKAROUND** for those who cannot upgrade:

```console
export PIPENV_PYUP_API_KEY=""
pipenv check
```

**Comment by SPH73** [comment]
If anyone is still struggling I ran:

```pip3 install pipenv```

I already had ```pipenv 2020.6.2-py2.py3``` installed so returned that it was 'already satisfied' but after that, when I launched the environment again and ran
```pipenv check``` Checking PEP508 requirements returned Passed! and Checking installed package safety returned All good!
