### ISSUE TITLE
error no 2

### ISSUE THREAD

**Issue by Rodrigeu** [pypa/pipenv#4190]
when I try to use the command pip install pipenv an error appears.
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or 
directory: 'C:\\Users\\Fam\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\pipenv\\patched\\notpip\\_vendor\\urllib3\\packages\\ssl_match_hostname\\__pycache__\\_implementation.cpython-38.pyc'

If you can help me, thanks

pd: i'm in Windows 10 and i use visual studio code

**Comment by sudopriestmx** [comment]
Additionally to running Windows 10:
What version of python are you running? (You can check this by running `python —version`
What is the exact command you are running to install pipenv?
Are you running the command inside a virtual environment? (venv or virtualenv?)
Try running the command as `python -m pip install —user pipenv` (notice that running this will result in installing pipenv for the current windows 10 user and not on a project basis)

Answering this questions may help us understand your problem better

**Comment by matteius** [comment]
@Rodrigeu do you still require support on the latest version `pipenv==2022.8.17`?
