### ISSUE TITLE
Master CI is broken and no release since 2018?

### ISSUE THREAD

**Issue by bneijt** [pypa/pipenv#4197]
Dear developer,

It seems that the last release is from november 2018 and the continuous integration is broken on master.

I would like to see a new release because we are running into some issues already fixed on master and I'm using pipenv via pip install.

Would it be possible to create a checklist of things to do to get to a new release? Maybe I can help out.

**Comment by brainwane** [comment]
Thanks for the offer, @bneijt! We do already have that kind of issue open: #3369. I suggest you go ahead and look at that issue and follow the suggestions there to help out! (I'm going to close this issue now to direct you and any other folks watching over to #3369.)
