### ISSUE TITLE
Which operating systems, Python versions, etc. does Pipenv officially support?

### ISSUE THREAD

**Issue by brainwane** [pypa/pipenv#4202]
The Pipenv documentation (perhaps in [the installation guide](https://pipenv.pypa.io/en/latest/install/)) should specify which versions of CPython, which operating systems or Linux distributions, etc. Pipenv officially supports. For example, is PyPy supported, or only CPython?

**Comment by Hammond95** [comment]
should be linked to #4096

**Comment by Flimm** [comment]
You can see which Python versions and operating systems Pipenv officially supports by looking at its classifiers on PyPI (left sidebar): https://pypi.org/project/pipenv/

The list of classifiers published for pipenv 2018.11.26 is:

License:

- OSI Approved :: MIT License

Programming Language:

- Python
- Python :: 2.7
- Python :: 3
- Python :: 3.4
- Python :: 3.5
- Python :: 3.6
- Python :: 3.7
- Python :: Implementation :: CPython
- Python :: Implementation :: PyPy

It looks like Pipenv chose not to add classifiers related to supported operating systems, even though those are [potential trove classifiers](https://pypi.org/classifiers/).

**Comment by rajneesh44** [comment]
Can i work on this issue?
I am new to open source and looking forward to contribute.
Thanks in advance if someone can guide me.

**Comment by brainwane** [comment]
@rajneesh44 This isn't a great first issue for you to work on because it requires some skill and knowledge that you don't have yet. Instead I suggest you look at https://github.com/pypa/warehouse/issues/8012 . If you are interested in working on that, read the instructions comment there and comment on THAT thread to say "I am starting to work on this".

**Comment by matteius** [comment]
I don't think we plan to exclude pipenv from a particular operating system, but we can accept issue reports as they might pertain to other systems.
