### ISSUE TITLE
Pipenv installed using Linuxbrew doesn't work anymore

### ISSUE THREAD

**Issue by tsela** [pypa/pipenv#4204]
### Issue description

Since last updating pipenv through Homebrew for Linux, I get the following error each time I try to use it: 

/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_4/libexec/bin/python3.8: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

### Expected result

I would expect pipenv to run normally.

### Actual result

The only thing I get is the error above.

### Steps to replicate

Update pipenv through `$ brew update; brew upgrade`. Next time I try to run pipenv it gives me the error above.

Even `$ pipenv --support` fails so I have nothing to add.

**Comment by tsela** [comment]
The problem seems to have been solved already, pipenv was updated again today and now everything works again. So I'm closing this issue. Thanks to whoever solved it so fast.

**Comment by mlavi** [comment]
This happened again with latest Linuxbrew pipenv when I did a brew update && brew upgrade:
<pre>$ pipenv --support

/home/linuxbrew/.linuxbrew/Cellar/pipenv/2020.5.28/libexec/bin/python3.8: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
</pre>

**Comment by tsela** [comment]
Yes, I've noticed it too when I did a `brew update && brew upgrade` this morning. My experience from last time is that they usually notice such issues at Homebrew within a day, and push an update that solve them quickly. But it's annoying. I think it might make more sense to create an issue over at the Linuxbrew-core repo, but their requirements to fill in an issue are so complex I actually decided to wait it out for now. Feel free to create an issue there if you have the energy!

**Comment by mlavi** [comment]
I have created https://github.com/Homebrew/linuxbrew-core/issues/20474

**Comment by mlavi** [comment]
@tsela Is it possible to reopen this issue? It may be a Linuxbrew issue ultimately, but I came here first looking for answers.

**Comment by tsela** [comment]
OK, reopening the issue. I'll let the Pipenv developers decide whether that's a good move or not. In any case, thanks for opening the Linuxbrew issue.

**Comment by matteius** [comment]
`Homebrew/linuxbrew-core` repository is marked read only.  This issue feels outdated.
