### ISSUE TITLE
"pipenv shell" subshell falls back to system bash, not honouring session bash version

### ISSUE THREAD

**Issue by gigaimage** [pypa/pipenv#4221]
Please see attached screenshot

<img width="1149" alt="Screen Shot 2020-04-30 at 1 16 27 AM" src="https://user-images.githubusercontent.com/1184087/80688979-7ebdbe80-8a81-11ea-87f5-09044b43704f.png">

**Comment by techalchemy** [comment]
Please fill out the issue template in full, including with copying the output of `pipenv --support` as requested -- the shell set by `pipenv shell` is determined by information made available to pipenv. including providing the option for you to override this with the `PIPENV_SHELL` [environment variable](https://pipenv.pypa.io/en/latest/advanced/#pipenv.environments.PIPENV_SHELL)

**Comment by gigaimage** [comment]
Please close this ticket. I no longer see this issue since 2020.6.2 build. I did not set PIPENV_SHELL though. 

Where's Q&A home for pipenv project? 

![Screen Shot 2020-07-02 at 4 33 36 PM](https://user-images.githubusercontent.com/1184087/86419066-0cd34280-bc87-11ea-9809-373ff4952e2a.png)

**Comment by gigaimage** [comment]
see previous post.
