### ISSUE TITLE
Virtualenv name gets botched when PIPENV_PYTHON is a full path and WORKON_HOME is set

### ISSUE THREAD

**Issue by aiguofer** [pypa/pipenv#4225]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

When trying to `pipenv install` using `PIPENV_PYTHON=$HOME/.pyenv/shims/python` and `WORKON_HOME=$HOME/.pyenv/versions`, the `Project.virtualenv_name` property includes slashes. This causes the virtualenv to get botched since it installs within nested directories.

### Expected result

Generated virtualenv name is something that can be a reasonable folder name.

### Actual result

```
❯ WORKON_HOME=$HOME/.pyenv/versions PIPENV_PYTHON=$HOME/.pyenv/shims/python PYENV_VERSION=3.7.7 pipenv install --dev
Creating a virtualenv for this project…
Pipfile: /Users/Diego/work/lucerna/test/Pipfile
Using /Users/Diego/.pyenv/shims/python (3.7.7) to create virtualenv…
⠦ Creating virtual environment...created virtual environment CPython3.7.7.final.0-64 in 691ms
  creator CPython3Posix(dest=/Users/Diego/.pyenv/versions/test-VgJQqnWV-/Users/Diego/.pyenv/shims/python, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/Users/Diego/Library/Application Support/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/Diego/.pyenv/versions/test-VgJQqnWV-/Users/Diego/.pyenv/shims/python
```

**Comment by techalchemy** [comment]
yikes, thanks for the report. I'm not sure what to consider this, it's an input sanitization issue I suppose.  I'm not sure how often anyone is trying this.

Was this something you encountered organically? Was the range of possible values confusing?
