### ISSUE TITLE
pipenv --python 3  finds a requirement.txt from somewhere I can't locate

### ISSUE THREAD

**Issue by melMass** [pypa/pipenv#4228]
- [x] Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

-   [x] Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

### Issue description

When creating a Pipenv from an empty folder it refers to a requirements.txt somewhere, and there is no mention of where it came from.

### Expected result

An "empty" Pipfile 

### Actual result

~~~ruby
Creating a virtualenv for this project…
Pipfile: /Volumes/osx/install_osx/Pipfile
Using /usr/local/bin/python3 (3.7.7) to create virtualenv…
⠧ Creating virtual environment...created virtual environment CPython3.7.7.final.0-64 in 2436ms
  creator CPython3Posix(dest=/Volumes/osx/install_osx/.venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/Users/imac/Library/Application Support/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /Volumes/osx/install_osx/.venv
requirements.txt found, instead of Pipfile! Converting…
✔ Success! 
Warning: Your Pipfile now contains pinned versions, if your requirements.txt did. 
We recommend updating your Pipfile to specify the "*" version, instead.
~~~

### Steps to replicate

~~~bash
pipenv --python 3 --verbose
~~~

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/Users/imac/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv'`

Python location: `'/Users/imac/.pyenv/versions/3.7.4/Python.framework/Versions/3.7/bin/python3.7'`

Python installations found:

  - `3.7.7`: `/usr/local/bin/python3`
  - `3.7.7`: `/usr/local/bin/python3.7m`
  - `3.7.4`: `/Users/imac/.pyenv/versions/3.7.4/bin/python3`
  - `3.7.4`: `/Users/imac/.pyenv/versions/3.7.4/bin/python3.7m`
  - `3.7.2`: `/Users/imac/.pyenv/versions/3.7.2/bin/python3`
  - `3.7.2`: `/Users/imac/.pyenv/versions/3.7.2/bin/python3.7m`
  - `3.6.8`: `/Users/imac/.pyenv/versions/3.6.8/bin/python3`
  - `3.6.8`: `/Users/imac/.pyenv/versions/3.6.8/bin/python3.6m`
  - `2.7.15`: `/Users/imac/.pyenv/versions/2.7.15/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT '
                     '2019; root:xnu-4903.251.3~3/RELEASE_X86_64',
 'python_full_version': '3.7.4',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `SHELL`
  - `CAML_LD_LIBRARY_PATH`
  - `PYENV_HOOK_PATH`
  - `ITERM_PROFILE`
  - `PIPENV_VENV_IN_PROJECT`
  - `NVM_RC_VERSION`
  - `OCAML_TOPLEVEL_PATH`
  - `COLORTERM`
  - `PYENV_SHELL`
  - `CURRENT_OS`
  - `XPC_FLAGS`
  - `TERM_PROGRAM_VERSION`
  - `HISTSIZE`
  - `SSH_AUTH_SOCK`
  - `TERM_SESSION_ID`
  - `MAYA_DEFAULT_SURFACE_SHADER`
  - `ARNOLD_COMMON`
  - `RBENV_SHELL`
  - `OCIO`
  - `EDITOR`
  - `PYENV_VERSION`
  - `PWD`
  - `RMANTREE`
  - `MTB_CLI`
  - `SDKROOT`
  - `LOGNAME`
  - `ARNOLD_ROOT`
  - `OPAM_SWITCH_PREFIX`
  - `ITERM_SESSION_ID`
  - `HOME`
  - `LANG`
  - `HISTFILE`
  - `SECURITYSESSIONID`
  - `GAFFER_ROOT`
  - `TMPDIR`
  - `LC_TERMINAL`
  - `SAVEHIST`
  - `PYENV_DIR`
  - `HOMEBREW_NO_AUTO_UPDATE`
  - `DBUS_LAUNCHD_SESSION_BUS_SOCKET`
  - `NVM_DIR`
  - `MTB_PY`
  - `HOMEBREW_NO_ANALYTICS`
  - `MAYA_DISABLE_CER`
  - `PYTHONPATH`
  - `TERM`
  - `USER`
  - `COLORFGBG`
  - `LC_TERMINAL_VERSION`
  - `DISPLAY`
  - `SHLVL`
  - `NVM_CD_FLAGS`
  - `MTB_ENV`
  - `XPC_SERVICE_NAME`
  - `HOMEBREW_GITHUB_API_TOKEN`
  - `LC_CTYPE`
  - `PYENV_ROOT`
  - `LA_LIBRARY_FILEPATH`
  - `LC_ALL`
  - `TMOUT`
  - `Apple_PubSub_Socket_Render`
  - `PATH`
  - `OPAMNOENVNOTICE`
  - `MTOA_TEMPLATE_PATH`
  - `MTB_ROOT`
  - `ARNOLD_HOME`
  - `MAYA_DISABLE_CLIC_IPM`
  - `OLDPWD`
  - `__CF_USER_TEXT_ENCODING`
  - `MAYA_CUSTOM_TEMPLATE_PATH`
  - `TERM_PROGRAM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/imac/.pyenv/versions/3.7.4/bin:/usr/local/Cellar/pyenv/1.2.18/libexec:/Users/imac/.opam/default/bin:/Applications/Substance\ Automation\ Toolkit:/Users/imac/.cargo/bin:/Users/imac/.rbenv/bin:/Users/imac/.rbenv/shims:/Users/imac/.pyenv/shims:/usr/local/opt/llvm/bin:/Users/imac/bin/neko:/Users/imac/bin:/Users/imac/go/bin/:/Users/imac/.rbenv/versions/2.5.1/bin/:/Users/imac/gits/MINE/dotfiles/home/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/imac/.nimble/bin:/Users/imac/.config/yarn/global/node_modules/.bin/`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `subl -w`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/imac/`

---------------------------

</details>

**Comment by frostming** [comment]
You like have some `requirements.txt` in the **parents** directory.

**Comment by melMass** [comment]
@frostming Will look for that, but I'm pretty sure the isn't in the parent paths.
Can I find more information on that mechanism? 
For instance sometimes while in a subfolder I can call Pipenv and it does rightly pickups the parent's Pipfile, but sometimes it just starts creating a brand new virtual env in this subfolder. I have the feeling that both mechanisms are linked, I might be wrong.

**Comment by frostming** [comment]
No magic but simply searches the current directory and specific levels of parents, which is controlled by the env var `PIPENV_MAX_DEPTH`. When the searching depth exceeds it, a new one will be created.

**Comment by techalchemy** [comment]
@melMass you can run `pipenv --where` to see where it is looking as well I believe. We should probably at least show the path...
