### ISSUE TITLE
Running `pipenv check` returns "Your API Key is invalid"

### ISSUE THREAD

**Issue by den4uk** [pypa/pipenv#4238]
When executing `pipenv check` - the API key is invalid message appears. The command returns a non-zero exit code, thus fails testing pipelines.

```
$ pipenv check --verbose
Checking PEP 508 requirements…
Passed!
Checking installed package safety…
An error occurred:
Your API Key '1ab8d58f-5122e025-83674263-bc1e79e0' is invalid. See https://goo.gl/O7Y1rS
```

Pipenv version: `'2018.11.26'`

**Comment by frostming** [comment]
Duplicate with #4188

**Comment by brainwane** [comment]
@den4uk In case you didn't see: https://github.com/pypa/pipenv/issues/4188#issuecomment-614877929 has a workaround. And there will be a fix in the next pipenv release.

**Comment by den4uk** [comment]
Cheers, much appreciated!
