### ISSUE TITLE
additional path on activation

### ISSUE THREAD

**Issue by iham** [pypa/pipenv#4244]
i like to add a path to my pipenv shell/run on activation.

inside a project with a requirements.txt and setup.py i run ```pipenv --python 2.7 install```

after that i have setuptools and zc.buildout installed, as its an requirement
now i run ```pipenv shell``` and my virtualenv has the buildout command.

then i install additional stuff via buildout which are placed inside <myproject>/bin.
things like i18ndude, zope instance and such.

all those i can't access directly (which worked using virtualenv on its own).

is there a way to add ./bin - which is next to pipfile and piplock - on activation via pipenv shell?

as i run multiple project that way, it would be handy.

thanks for any advice in advanced :)
-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.11.26_4/libexec/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.11.26_4/libexec/bin/python3.8'`

Python installations found:

  - `3.7.7`: `/Users/iham/.pyenv/versions/3.7.7/bin/python3`
  - `3.7.7`: `/Users/iham/.pyenv/versions/3.7.7/bin/python3.7m`
  - `3.7.3`: `/usr/bin/python3`
  - `2.7.17`: `/Users/iham/.local/share/virtualenvs/akbild.deploy-vd4Dj4UK/bin/python`
  - `2.7.17`: `/Users/iham/.pyenv/versions/2.7.17/bin/python`
  - `2.7.16`: `/usr/bin/python`
  - `2.7.16`: `/usr/bin/pythonw`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '19.4.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST '
                     '2020; root:xnu-6153.101.6~15/RELEASE_X86_64',
 'python_full_version': '3.8.2',
 'python_version': '3.8',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `LDFLAGS`
  - `MANPATH`
  - `TERM_PROGRAM`
  - `NVM_CD_FLAGS`
  - `PIP_PYTHON_PATH`
  - `SHELL`
  - `TERM`
  - `TMPDIR`
  - `CPPFLAGS`
  - `NVM_PATH`
  - `TERM_PROGRAM_VERSION`
  - `ZSH`
  - `USER`
  - `NVM_DIR`
  - `COMMAND_MODE`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `VIRTUAL_ENV`
  - `PAGER`
  - `LSCOLORS`
  - `PIPENV_ACTIVE`
  - `_`
  - `NVM_NODEJS_ORG_MIRROR`
  - `PWD`
  - `P9K_SSH`
  - `LANG`
  - `P9K_TTY`
  - `XPC_FLAGS`
  - `PYTHONDONTWRITEBYTECODE`
  - `XPC_SERVICE_NAME`
  - `HOME`
  - `PYENV_SHELL`
  - `SHLVL`
  - `LOGNAME`
  - `LESS`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `NVM_BIN`
  - `PKG_CONFIG_PATH`
  - `NVM_IOJS_ORG_MIRROR`
  - `COLORTERM`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.11.26_4/libexec/tools:/Users/iham/.local/share/virtualenvs/akbild.deploy-vd4Dj4UK/bin:/usr/local/opt/openssl@1.1/bin:/Users/iham/.nvm/versions/node/v13.13.0/bin:/usr/local/sbin:/Users/iham/.pyenv/shims:/usr/local/Cellar/pipenv/2018.11.26_4/libexec/tools:/usr/local/opt/openssl@1.1/bin:/usr/local/sbin:/Users/iham/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/openssl@1.1/bin:/usr/local/sbin:/Users/iham/.pyenv/shims`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/iham/SandBox/AkBild/akbild.deploy`
  - `VIRTUAL_ENV`: `/Users/iham/.local/share/virtualenvs/akbild.deploy-vd4Dj4UK`

---------------------------

Contents of `Pipfile` ('/Users/iham/SandBox/AkBild/akbild.deploy/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
"zc.buildout" = "*"

[requires]
python_version = "2.7"

```

Contents of `Pipfile.lock` ('/Users/iham/SandBox/AkBild/akbild.deploy/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "9eb333ed5fd32e6d71234dbc38797c81a5eec4c948c207159e0defa7e44f52d6"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "2.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "zc.buildout": {
            "hashes": [
                "sha256:0880f131cd5f3c5f6a5e1d17add9d6bead079a4236056c3f896609ebd680c8c1",
                "sha256:d6691a864a7f14b3302ed9a9ab5790f2efc883375033371c1c959fedc72bccb7"
            ],
            "index": "pypi",
            "version": "==2.13.3"
        }
    },
    "develop": {}
}

```
</details>

**Comment by techalchemy** [comment]
Hey there, thanks for filing this issue and opening this discussion!

This is an interesting proposal, I did not know that virtualenv implicitly added `./bin` to the path at runtime!

I'm not sure what could make sense here, but we have a few options:
1. We could implicitly add `./bin` as virtualenv does;
2. We could provide some mechanism in `Pipfile` (or some other config file) for specifying additional paths to include when using `pipenv run` or `pipenv shell`;
3. We could encourage people to use `sitecustomize.py` and/or provide some mechanism for helping to achieve that;
4. We could encourage users to set this in `.env`, e.g. `PATH="${PWD}/bin:${PATH}"` which actually already works fine (I just tested this)

Any substantial changes to how pipenv works will require a `PEEP` or a pipenv enhancement proposal, submitted as a pull request to the `peeps` directory as a markdown document -- so if the first or second option seems right, you should describe how the behavior should work in a short markdown document like one of the existing documents and make a pull request.

If the later options work ok, feel free to close this issue and let us know which one worked for you. Thanks!

**Comment by iham** [comment]
thank you for your quick reply! i rly appreciate that.

> "This is an interesting proposal, I did not know that virtualenv implicitly added ./bin to the path at runtime!"

i might have formulated that a bit "wrong"

when creating a virtualenv i usually do ```virtualenv -p mypython .``` inside my project folder.
that creates the virtualenv there (as i used "." as the target) and includes everything inside. so ./bin is included implicit not explicit.

as pipenv creates virtualenvs in some other place (in the users home), it does not included the current project path on activation.

thats my "problem" i'd like to solve.

or maybe i was plainly to stupid to try that ```.env``` approach you mentioned in 4. shame on me.
(any thoughts about dockers usage of the same .env file?)

i will give it a try in a few hours and close the ticket if that works.

**Comment by iham** [comment]
4. it is! 

thank you @techalchemy - this works like a charm and as i am used to work with virtualenv!

awesome :)

i'll close the issue.
