### ISSUE TITLE
Please change colours when installing package

### ISSUE THREAD

**Issue by vegabook** [pypa/pipenv#4258]
pipenv install colours by default look like errors. Please change orange / red informative messages to something neutral. Red text is generally considered the colour for an outright error and looks wrong on screen when everything is actually working fine. 

![image](https://user-images.githubusercontent.com/3780883/82260448-32192500-9955-11ea-850b-1839ceb545be.png)

**Comment by frostming** [comment]
I'd like to close this issue and track it in #3732
