### ISSUE TITLE
Drop Support for Python2

### ISSUE THREAD

**Issue by r-richmond** [pypa/pipenv#4261]
Python2 was [EOL](https://www.python.org/doc/sunset-python-2/)'ed earlier this year and thus it may be worth considering dropping support for python2. Ideally this would reduce the complexity of the project making it easier to manage, test and release.

Pros:
* Dropping python2 as a requirement would reduce complexity
* Smaller unit test matrix resulting in faster tests and less timeouts
* Python3 represents a significant majority of python users
  * According to Jet Brain's May 2020 [survey](https://blog.jetbrains.com/pycharm/2020/05/5-takeaways-from-the-python-developer-survey-2019/) 90% of python developers use python 3 now
  * According to the same survey Python2 usage is has dropped 40% year-over-year for the last 2 years in a row

Cons:
* Python2 users would not receive any new versions (But they would be able to continue to use version ~~2018.11.26~~ 2020.6.2)

Note: Initially, this was suggested in #3369 under https://github.com/pypa/pipenv/issues/3369#issuecomment-630557465 as it appears that a python2 / cross support issue delayed the 2020 release. I've moved the discussion for dropping python2 here as to avoid further polluting the original ticket.

**Comment by techalchemy** [comment]
This is definitely something we could consider; I suspect we will look to coincide with pip dropping support which I believe is still a few months away. Once we do drop python 2 support we should be able to make some substantial gains in terms of performance and cleanup, so I think we are all excited.

**Comment by hugovk** [comment]
> I suspect we will look to coincide with pip dropping support which I believe is still a few months away.

Pip 20.3 (October 2020) will be the last version to support Python 2.7, and pip 21.0 (January 2021) will be the first version to drop it.

* https://github.com/pypa/pip/issues/6148

**Comment by and-semakin** [comment]
Also we could consider dropping Python 3.4.

**Comment by glensc** [comment]
Before dropping there should be a simple command to switch from python2 printed out each time you run the tool under python2. For example:

> Warning, you are running pipenv under python2, python2 support is to be dropped
> Use python3 -m pipenv install pipenv to switch to use python3 (or whatever the command is)
>
> See for more details at https://github.com/pypa/pipenv/issues/4261
> and at https://www.python.org/doc/sunset-python-2/

**Comment by pytard** [comment]
imagine a python environment manager that only supports some of your environments
this project is completely braindead

**Comment by and-semakin** [comment]
And what about Python 3.5? It reached its EOL recently, and probably could also be dropped.

Sources:
* https://www.python.org/dev/peps/pep-0478/
* https://python-release-cycle.glitch.me/

**Comment by dulmandakh** [comment]
Created a PR to remove Python 2 from CI https://github.com/pypa/pipenv/pull/4605. Once merged I would like to volunteer to remove six from dependency.

**Comment by frostming** [comment]
Here is the current status and plan for dropping Python 2 support:

- [x] #4605
- [ ] #4747 
- [ ] #4751 
- [ ] Upgrade the codebase of Pipenv to 3.6+ syntax
- [ ] Remove py2 only test cases and markers

**Comment by gitpushdashf** [comment]
I see that #4752 was merged. Is there a pull request for removing Python 2 only test cases and markers?

**Comment by frostming** [comment]
2021.11.5 drops support for Python2.7 and 3.5, close this now.
