### ISSUE TITLE
Small bug that happens when you install something that's not available on pypi

### ISSUE THREAD

**Issue by Theodore-Robinson** [pypa/pipenv#4290]
### Issue description

If I do `pipenv install something_that_doesn't_exist`, it shows the failure message but doesn't remove the value `something_that_doesn't_exist` from the pipfile. This is not a big issue but when you have a lot of dependencies installed, its hard to spot the missing dependency and this could result to an unexpected error if someone does `pipenv sync` with wrong dependency list

### Expected result
It is supposed to remove the dependency that was not found/ PyPi was unreachable or give the option to remove that dependency with a yes/no question

### Actual result

It tries to install the dependency then it learns that dependency does not exist on pypi/was unreachable and does not remove it from the pipfile (not pipfile.lock)

### Steps to replicate
```bash
$ pipenv install something_that_does_not_exist_on_pypi
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/human/.local/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.8.2`: `/home/human/Documents/Programming/SomethingDirectory/Something/.venv/bin/python`
  - `2.7.18rc1`: `/usr/bin/python`
  - `2.7.16`: `/usr/local/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.0-33-generic',
 'platform_system': 'Linux',
 'platform_version': '#37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020',
 'python_full_version': '3.8.2',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LANGUAGE`
  - `USER`
  - `LC_TIME`
  - `XDG_SEAT`
  - `XDG_SESSION_TYPE`
  - `SSH_AGENT_PID`
  - `SHLVL`
  - `HOME`
  - `DESKTOP_SESSION`
  - `GTK_MODULES`
  - `LC_MONETARY`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `MANDATORY_PATH`
  - `LOGNAME`
  - `XDG_SESSION_CLASS`
  - `DEFAULTS_PATH`
  - `USERNAME`
  - `XDG_SESSION_ID`
  - `WINDOWPATH`
  - `PATH`
  - `PAPERSIZE`
  - `LC_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `DISPLAY`
  - `LANG`
  - `XDG_CURRENT_DESKTOP`
  - `LC_TELEPHONE`
  - `XDG_SESSION_DESKTOP`
  - `XAUTHORITY`
  - `SSH_AUTH_SOCK`
  - `SHELL`
  - `LC_NAME`
  - `QT_ACCESSIBILITY`
  - `GDMSESSION`
  - `LC_MEASUREMENT`
  - `GPG_AGENT_INFO`
  - `LC_IDENTIFICATION`
  - `XDG_VTNR`
  - `PWD`
  - `XDG_CONFIG_DIRS`
  - `XDG_DATA_DIRS`
  - `LC_NUMERIC`
  - `LC_PAPER`
  - `XCURSOR_THEME`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `KDE_FULL_SESSION`
  - `KDE_SESSION_VERSION`
  - `KDE_SESSION_UID`
  - `SESSION_MANAGER`
  - `CHROME_DESKTOP`
  - `LESS`
  - `LSCOLORS`
  - `OLDPWD`
  - `P9K_SSH`
  - `PAGER`
  - `ZSH`
  - `_`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `COLORTERM`
  - `VSCODE_GIT_IPC_HANDLE`
  - `GIT_ASKPASS`
  - `VSCODE_GIT_ASKPASS_NODE`
  - `VSCODE_GIT_ASKPASS_MAIN`
  - `TERM`
  - `P9K_TTY`
  - `PIPENV_VENV_IN_PROJECT`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `PIPENV_ACTIVE`
  - `VIRTUAL_ENV`
  - `PS1`
  - `PIP_SHIMS_BASE_MODULE`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `true`
 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/human/Documents/Programming/SomethingDirectory/Something/.venv/bin:/home/human/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/human/Documents/Programming/SomethingDirectory/Something`
  - `VIRTUAL_ENV`: `/home/human/Documents/Programming/SomethingDirectory/Something/.venv`

---------------------------

Contents of `Pipfile` ('/home/human/Documents/Programming/SomethingDirectory/Something/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
autopep8 = "*"
flake8 = "*"

[packages]
something-that-does-not-exist = "*"

[requires]
python_version = "3.8"

```

Contents of `Pipfile.lock` ('/home/human/Documents/Programming/SomethingDirectory/Something/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "2ddfd2bd3199396b3860ce6983c238c3cc1948f88ae01a54dbb8540906913cf9"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {
        "autopep8": {
            "hashes": [
                "sha256:152fd8fe47d02082be86e05001ec23d6f420086db56b17fc883f3f965fb34954"
            ],
            "index": "pypi",
            "version": "==1.5.2"
        },
        "flake8": {
            "hashes": [
                "sha256:c69ac1668e434d37a2d2880b3ca9aafd54b3a10a3ac1ab101d22f29e29cf8634",
                "sha256:ccaa799ef9893cebe69fdfefed76865aeaefbb94cb8545617b2298786a4de9a5"
            ],
            "index": "pypi",
            "version": "==3.8.2"
        },
        "mccabe": {
            "hashes": [
                "sha256:ab8a6258860da4b6677da4bd2fe5dc2c659cff31b3ee4f7f5d64e79735b80d42",
                "sha256:dd8d182285a0fe56bace7f45b5e7d1a6ebcbf524e8f3bd87eb0f125271b8831f"
            ],
            "version": "==0.6.1"
        },
        "pycodestyle": {
            "hashes": [
                "sha256:2295e7b2f6b5bd100585ebcb1f616591b652db8a741695b3d8f5d28bdc934367",
                "sha256:c58a7d2815e0e8d7972bf1803331fb0152f867bd89adf8a01dfd55085434192e"
            ],
            "version": "==2.6.0"
        },
        "pyflakes": {
            "hashes": [
                "sha256:0d94e0e05a19e57a99444b6ddcf9a6eb2e5c68d3ca1e98e90707af8152c90a92",
                "sha256:35b2d75ee967ea93b55750aa9edbbf72813e06a66ba54438df2cfac9e3c27fc8"
            ],
            "version": "==2.2.0"
        }
    }
}

```
</details>

**Comment by frostming** [comment]
Please use the latest release, we already abort early if installation fails
