### ISSUE TITLE
Installing a wildcard version does not result in a specific version in the lock file

### ISSUE THREAD

**Issue by ipmb** [pypa/pipenv#4293]
### Issue description

Adding a wildcard version to the Pipfile, e.g. `django = "==2.2.*"` does not pin to a specific version in the lock file. This appears to be a regression in `2020.5.28`

### Expected result

Something like:

```
        "django": {
            "hashes": [
                "sha256:69897097095f336d5aeef45b4103dceae51c00afa6d3ae198a2a18e519791b7a",
                "sha256:6ecd229e1815d4fc5240fc98f1cca78c41e7a8cd3e3f2eefadc4735031077916"
            ],
            "index": "pypi",
            "version": "==2.2.12"
        },
```

### Actual result

```
        "django": {
            "hashes": [
                "sha256:69897097095f336d5aeef45b4103dceae51c00afa6d3ae198a2a18e519791b7a",
                "sha256:6ecd229e1815d4fc5240fc98f1cca78c41e7a8cd3e3f2eefadc4735031077916"
            ],
            "index": "pypi",
            "version": "==2.2.*"
        },
```

### Steps to replicate

```
$ pipenv install 'django==2.2.*'
$ cat Pipfile.lock | jq .default.django.version
"==2.2.*"
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.5.28'`

Pipenv location: `'/home/django/.local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Python installations found:

  - `3.7.7`: `/usr/local/bin/python3.7m`
  - `3.7.7`: `/usr/local/bin/python3.7`
  - `3.7.7`: `/usr/local/bin/python3`
  - `3.7.3`: `/usr/bin/python3.7m`
  - `3.7.3`: `/usr/bin/python3.7`
  - `3.7.3`: `/usr/bin/python3`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.19.76-linuxkit',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Tue May 26 11:42:35 UTC 2020',
 'python_full_version': '3.7.7',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `DATABASE_URL`
  - `SITE_URI`
  - `HOSTNAME`
  - `PYTHON_VERSION`
  - `AWS_DEFAULT_REGION`
  - `PWD`
  - `HOME`
  - `LANG`
  - `LS_COLORS`
  - `GPG_KEY`
  - `TERM`
  - `SHLVL`
  - `PYTHON_PIP_VERSION`
  - `REDIS_CACHE_URL`
  - `PYTHON_GET_PIP_SHA256`
  - `PYTHON_GET_PIP_URL`
  - `PATH`
  - `PIP_NO_CACHE_DIR`
  - `PIP_NO_BINARY`
  - `STATIC_URL`
  - `_`
  - `OLDPWD`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/opt/inklecate:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/home/django`

---------------------------

Contents of `Pipfile` ('/home/django/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
django = "==2.2.*"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/home/django/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "7a778d69a8b843fab393edc4fa605d665505aab45a686b98b9ece084f7b70f3a"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "django": {
            "hashes": [
                "sha256:69897097095f336d5aeef45b4103dceae51c00afa6d3ae198a2a18e519791b7a",
                "sha256:6ecd229e1815d4fc5240fc98f1cca78c41e7a8cd3e3f2eefadc4735031077916"
            ],
            "index": "pypi",
            "version": "==2.2.*"
        },
        "pytz": {
            "hashes": [
                "sha256:a494d53b6d39c3c6e44c3bec237336e14305e4f29bbf800b599253057fbb79ed",
                "sha256:c35965d010ce31b23eeb663ed3cc8c906275d6be1a34393a1d73a41febf4a048"
            ],
            "version": "==2020.1"
        },
        "sqlparse": {
            "hashes": [
                "sha256:022fb9c87b524d1f7862b3037e541f68597a730a8843245c349fc93e1643dc4e",
                "sha256:e162203737712307dfe78860cc56c8da8a852ab2ee33750e33aeadf38d12c548"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "version": "==0.3.1"
        }
    },
    "develop": {}
}

```
</details>

**Comment by frostming** [comment]
It was reported in #4278 , the new release will be out in couple of days
