### ISSUE TITLE
Brew install of pipenv 2020.5.28 does not contain zsh completions

### ISSUE THREAD

**Issue by remidebette** [pypa/pipenv#4300]
### Issue description

The brew installation of pipenv does not set zsh completions
(those completions are broken on both mac and linux)

### Expected result

`$(brew --prefix)/share/zsh/site-functions/../../../Cellar/pipenv/2020.5.28/share/zsh/site-functions/_pipenv`
should contain completions.

### Actual result

The file is empty

### Steps to replicate

Simply install the latest version of pipenv with brew
`brew install pipenv`

To test completions, the system should have zsh installed and the following in .zshrc :
```bash
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi
```

**Comment by frostming** [comment]
We don't officially maintain the brew formula, we may need to raise this issue against https://github.com/Homebrew/homebrew-core

[The formula file](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pipenv.rb) is updated by bot and seems to include zsh completion script with it.

Closing it for now
