### ISSUE TITLE
pipenv no longer installed a version of python that isn't available in the list of pyenv versions

### ISSUE THREAD

**Issue by philjc** [pypa/pipenv#4305]
One of the changes in c23e57b4824e0553ea2e91a2a6c59bff811aac39 introduced a bug in pipenv which prevents pyenv from installing a version that isn't present in pyenv

### Issue description

If the version specified in the Pipfile isn't present in pyenv, it install that version into pyenv, this no longer happens during interactive sessions.

### Expected result

pyenv installs the python version specified in the Pipfile

### Actual result

pipenv doesn't invoke pyenv to install the specified version

### Steps to replicate

run `pipenv install` with a Pipfile that specifies a version of python that isn't present in list of pyenv

**Comment by techalchemy** [comment]
Thanks for the report and for hunting down the fix for this!

**Comment by techalchemy** [comment]
Fixed in c8a29ac5d79c728d294af33c706c2f96c2426f71 - closing -- thanks again!
