### ISSUE TITLE
Cannot use ${VIRTUAL_ENV} in .env file

### ISSUE THREAD

**Issue by bblanchon** [pypa/pipenv#4308]
### Issue description

In my `.env` file, I need to set a path relative to the virtual environment:

```
GDAL_DATA=${VIRTUAL_ENV}\Lib\site-packages\osgeo\data\gda
```

### Expected result

I expect `${VIRTUAL_ENV}` to expand to the location of the virtual environment.

### Actual result

Instead, `${VIRTUAL_ENV}` expands to an empty string.

### Steps to replicate

1. Create the `.env` file as specified above
2. Run `pipenv shell`
3. Run `echo %GDAL_DATA%` (yes, I'm running Windows).
   * It should show `C:\Users\<username>\.virtualenvs\<venv>\Lib\site-packages\osgeo\data\gda`
   * Instead, it shows  `\Lib\site-packages\osgeo\data\gda`

**Comment by techalchemy** [comment]
Thanks for the report and sorry for the confusion, I know it is probably not that clear why things work this way!

The `.env` file loads before you are in the activated environment, so I would not expect this to be successful. The nature of loading environment variables into a shell session means that first, we load the environment variables, then we load the shell session. If we did it the other way around, the environment variables wouldn't be active inside the shell.

Pipenv itself doesn't control the shell session -- it only spawns it. The shell inherits environment variables from the calling process, so I don't think there's a lot we can do here. We aren't manually setting `$VIRTUAL_ENV`, it's being set by the activation script.

You can try a tool like `direnv` (no idea if that works on windows) or recreate the virtualenv with `PIPENV_VENV_IN_PROJECT` set so the path is always the same, but I don't think we can do much else here -- I'll close this issue for now, unless someone can come up with a better solution
