### ISSUE TITLE
Official logo of pipenv?

### ISSUE THREAD

**Issue by torsava** [pypa/pipenv#4313]
Hi,
I have found [this](https://github.com/pypa/pipenv/blob/master/docs/_static/pipenv.png) logo in the GitHub sources, and it's also displayed on the [official website](https://pipenv.pypa.io/en/latest/#).

Is this the official logo of pipenv?

And can I assume that it's available under the MIT license like pipenv itself?

Thank you

**Comment by frostming** [comment]
Yes, you are right
