### ISSUE TITLE
CI/CD: Switch commit author to GitHub Actions bot

### ISSUE THREAD

**Issue by peaceiris** [pypa/pipenv#4328]
### Is your feature request related to a problem? Please describe.

Switch to the commit author to the GitHub Actions bot on the PyPI upload workflow.

### Describe the solution you'd like

About this workflow: 
https://github.com/pypa/pipenv/blob/49f1cb04edb4c53a579f292c56e52b240a4e98c9/.github/workflows/pypi_upload.yml#L65-L66

We can set GitHub Actions bot as a commit author.

```diff
-        git config --local user.name 'Github Action'
-        git config --local user.email action@github.com
+        git config --local user.name 'github-actions[bot]'
+        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
```

### Describe alternatives you've considered

N/A.

### Additional context

We can see an example use here: [peaceiris/actions-gh-pages: GitHub Actions for GitHub Pages](https://github.com/peaceiris/actions-gh-pages)

Commit logs: https://github.com/peaceiris/actions-gh-pages/commits/gh-pages

![Set the GitHub Actions bot as a commit author](https://raw.githubusercontent.com/peaceiris/actions-gh-pages/master/images/committer_github_actions_bot.jpg)

---

I am ready to open my pull-request for this issue.

**Comment by frostming** [comment]
Glad to review the PR!

**Comment by peaceiris** [comment]
Opened https://github.com/pypa/pipenv/pull/4329
