### ISSUE TITLE
Developement Dependencies Won't install from Pipfile or Pipfile.lock

### ISSUE THREAD

**Issue by edkrueger** [pypa/pipenv#4331]
### Issue
When using an already existing Pipfile or Pipfile.lock, development dependencies don't install.

#### Generate the Pipfile and Check for Dev Deps (this works)
Run `pipenv install flask` and `pipenv install --dev pylint` the generate the following Pipfile:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
pylint = "*"

[packages]
flask = "*"

[requires]
python_version = "3.7"
```

Running `pipenv shell` and `pip freeze` shows the following are installed:

```
astroid==2.4.2
click==7.1.2
Flask==1.1.2
isort==4.3.21
itsdangerous==1.1.0
Jinja2==2.11.2
lazy-object-proxy==1.4.3
MarkupSafe==1.1.1
mccabe==0.6.1
pylint==2.5.3
six==1.15.0
toml==0.10.1
typed-ast==1.4.1
Werkzeug==1.0.1
wrapt==1.12.1
```

#### Remove the Environment
Run `exit` and `pipenv --rm`.

#### Reinstall from Pipfile.lock and Check for Dev Deps
Runing `pipenv install`, `pipenv shell` and `pip freeze` shows the following are installed :
```
click==7.1.2
Flask==1.1.2
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
Werkzeug==1.0.1
```
_Notably, pylint, the development dependency is missing._

#### Remove the Environment
`exit` and `pipenv --rm`

#### Reinstall from Pipfile  and Check for Dev Deps
Running `rm Pipfile.lock`, `pipenv install`, `pipenv shell` and `pip freeze` results in:
```
click==7.1.2
Flask==1.1.2
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
Werkzeug==1.0.1
```

_Once again, the pylint, the development dependency is missing._

### Versions
Pipenv: 2018.11.26 and 2020.6.2
OS: macOS 10.15.4
Python: 3.7.5

**Comment by frostming** [comment]
There is some misunderstanding about the development flow.

`pipenv install` **WON'T** include development packages, you need to add `--dev` flag to make it happen. It is expected behavior, I am going to close it now.

**Comment by edkrueger** [comment]
Thanks for clarifying @frostming!
