### ISSUE TITLE
Venv location without environment variables

### ISSUE THREAD

**Issue by espositoandrea** [pypa/pipenv#4332]
Hi! This is not a bug, but a feature request/discussion.

I was thinking about the `PIPENV_VENV_IN_PROJECT` variable: is there any reason why this should be set as an environment var instead of a simple ‘switch‘ option in the CLI (like `--in-project`)? Note that I'm not suggesting to remove the environment variable (it should be kept for both compatibility and CI), but I'm suggesting the addition of a new CLI option for the "human users".

I'm willing to implement this option myself in a PR. But if there's a reason for this design, sorry for the useless request. :)

**Comment by matteius** [comment]
We added an environment variable recently to specify `PIPENV_CUSTOM_VENV_NAME` as well -- the rationale is users can have their own `.env` file per project easily enough.   I am inclined to close this as there are a lot of arguments already and we are trying to cleanup and simplify the interfaces.   If you feel strongly we can revisit but I am also trying to cleanup the backlog of old issues.
