### ISSUE TITLE
apt search/install pipenv not found on Ubuntu

### ISSUE THREAD

**Issue by haroldrandom** [pypa/pipenv#4338]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description
```
$ apt search pipenv
Sorting... Done
Full Text Search... Done
```

pipenv seems doesn't support to install via apt on Ubuntu any more.

### Expected result

Should be indexed and installed.

### Actual result

Not found pipenv

### Steps to replicate

Try `apt search ` and `apt install`

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by frostming** [comment]
Pipenv is not included in `apt`, please consult the distributors.

**Comment by haroldrandom** [comment]
@frostming But the docs are tell user installation using `apt` in Debian. Should it be removed?

**Comment by frostming** [comment]
@haroldrandom Oh I didn't know it, in which section is it mentioned?

**Comment by haroldrandom** [comment]
@frostming My mistake. It's not available in Ubunut but available in Debian. Sorry
