### ISSUE TITLE
Plugin Support

### ISSUE THREAD

**Issue by frog-o** [pypa/pipenv#4340]
I would like to create a plugin(or hook system) library for use with hatch similar to [pep-517](https://www.python.org/dev/peps/pep-0517/) which is doing for pip.

>Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

I have a learning disability, which to me means I think differently then most and find it hard to communicate because of it.  I do a lot of reading but I am much slow at it and **comprehension is difficult for me**. If at any point you think i did not read the relevant documentation please give me a **link** to it so i can read it again or for the first time. **Thanks**. 

 
>Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues and the [PEEP list](https://github.com/pypa/pipenv/blob/master/peeps/) before posting! We may close your issue if it is very similar to one of them. Please be considerate and follow the PEEP process, or be on your way.

I searched the issues for "plugins" and gave a bunch of weird results and made no scenes to me.  

And i apologize in advance if i missing an issue or something.
I have read though all the peeps not that many yet (yeah) and I found some of them relevant to
mine more details bellow.  

>Make sure to mention your debugging experience if the documented solution failed.

this is a feature request does have anything to deal with the documented solutions.
### Is your feature request related to a problem? Please describe.

yes many like 
1.)  [If this project is dead, just tell us](https://github.com/pypa/pipenv/issues/4058)
2.) [PEEP-00 sub-commands]( https://github.com/pypa/pipenv/blob/master/peeps/PEEP-004.md)
3.) [PEEP-005: Do Not Remove Entries from the Lockfile When Using --keep-outdated](https://github.com/pypa/pipenv/blob/master/peeps/PEEP-005.md)
4.) [PEEP-044: safety-db integration, squelch, and output.](https://github.com/pypa/pipenv/blob/master/peeps/PEEP-044.md)
5.) PEEP-TEMPLATE.md
A couple of my issues  but very losely
6.)[better document on cvs support in pip #8317](https://github.com/pypa/pip/issues/8317)(this issus gave me the idea of creating a pip-src tool) 
7.)plugin support for hatch(https://github.com/ofek/hatch/issues/93) now i think it would be better implemented here
8.)logging into Discourse with GitHub #363(https://github.com/pypa/packaging-problems/issues/363)

9.) probably many more.

I often see many thing here like problem **1.** and I feel plugin can help with that.  Releases are often held back to address the many difficult problem that need to be address before Releasing **a side effect of having things in one big code base** Plugin are a well know way to address this problem and IMHO been proven to work. 
 
Things like Problems  **2.** or PEEP-00  IMHO can be better handle with plugins

Problem **3.** can make this problem less by linking pip-freeze to a certain version of pip-env plug-in   

IMHO we can make plugin-tools to help with  
problem like **4** and **5** and a program I am trying to create pip-src **6**
 
  
A clear and concise description of what the problem is. Ex. 

>I'm always frustrated when [...]
I'm always frustrated when dealing with big code.
I always try to read and put things in the correct place but find them keeping being moved like problem **8.**.  I love trying to work on code and the big the project is, the more difficult the problem 
becomes.  By spiting the program up and by using plugins it make comprehension easier.      

### Describe the solution you'd like

>A clear and concise description of what you want to happen.

As I said I love trying to write code and i want to get involved so I would like to see the following 

a.) the acceptance of plugin put in as a peep
b.) A discussion of how to implement such an api (the reason I made request **d.)** 
c.)A plugin to do list (another reason I made request **d.** 
**d.)** A new repository open or branch for pip-env  something like pip-env-plugins  
e.) A list put up of thing I need to do to get plugin for pip-env (maybe put in **d**)  
f.) I would like a way to talk about many issues that cross the bounds of python programs and problem **8** been a barrier.  Even though I don't expect you  to solve this, this is a list of what i would like to see happen :) I would like to cross this barrier.

Thing never go as I suspect and you guy are the experts ,so you probably have better ideas, please tell me i would love to hear them.

### Describe alternatives you've considered
 
>A clear and concise description of any alternative solutions or features you've considered.

I was think about trying to put this in hatch but i wanted it to be under python control where it would be easier to find and maybe git more support.  Before working on any code it tells me I should make an issue first.  Which is the reason i made this post.  I want to talk about this on the dev-list from problem **8** but just find using the list to hard for me to do(but i have not giving up yet) and should not be need for this.  I going to re-look at problem 8.  Someone commented on it and I was not notified i guessing because it was moved.    

### Additional context

>Add any other context or screenshots about the feature request here. It may be a good idea to mention that platform and Python version you are on.

IMHO pep-517 may not be called a plugin but i can not tell the difference and plugin are just so much nicer sounding.

some ideas of plugins 

* tutor                       -gives helpful tips after running command for first time
* file-system             -allow downloading cookie cutters
* licences                 - allow you to choose wich licences you want 
* pip-src                   -tools to help using git and twine work with tutor.
* pipenv-checker     -a tool to check pipenv
* many more 
-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip
-------------------------------------------------------------------------------

I did not do this because it should not be needed.

**Comment by matteius** [comment]
https://github.com/pypa/pipenv/discussions/5158
