### ISSUE TITLE
"pipenv install" failing to install certain dependencies (psycopg2 and rpy2)

### ISSUE THREAD

**Issue by ReuvenBirnbaum** [pypa/pipenv#4348]
To see system/pipenv version: `pipenv_--support` Output: [here](https://gist.github.com/ReuvenBirnbaum/020f8403764ee2e9d71912a86f937425)

### Issue description

Trying to install environment from Pipfile/Pipefile.lock found here https://github.com/CoreyCole/HypDB/tree/master/demo/server

### Expected result

The environment dependencies installs correctly

### Actual result

My first run of  `pipenv install`get this output 
`Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Creating a virtualenv for this project…
Pipfile: /home/reuven/wholetale/HypDB/demo/server/Pipfile
Using /usr/bin/python3.7m (3.7.5) to create virtualenv…
⠧ Creating virtual environment...created virtual environment CPython3.7.5.final.0-64 in 1792ms
  creator CPython3Posix(dest=/home/reuven/.local/share/virtualenvs/server-jfb3rzTr, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/reuven/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/reuven/.local/share/virtualenvs/server-jfb3rzTr
Installing dependencies from Pipfile.lock (8b9d3f)…
An error occurred while installing markupsafe==1.0 --hash=sha256:a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 22/22 — 00:00:19
An error occurred while installing rpy2==2.9.4 --hash=sha256:be57f741d0c284b5d8785ab03dff0e829303e5ac30e548d5ceb46e05b168812e --hash=sha256:a85b95d497815378ad0da79a3b94d1fb9f72614fdd1132dc68bf9ceae5bbb178 --hash=sha256:6d11505999bb1fdb74b0c2e857879b973ff7995bf495d168b01995dbfcae4110! Will try again.
Installing initially failed dependencies…
[InstallError]:   File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/cli/command.py", line 232, in install
[InstallError]:       retcode = do_install(
[InstallError]:   File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/core.py", line 2051, in do_install
[InstallError]:       do_init(
[InstallError]:   File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/core.py", line 1306, in do_init
[InstallError]:       do_install_dependencies(
[InstallError]:   File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/core.py", line 900, in do_install_dependencies
[InstallError]:       batch_install(
[InstallError]:   File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/core.py", line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2020.6.2/libexec/lib/python3.8/site-packages/pipenv/core.py", line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: Collecting markupsafe==1.0
[pipenv.exceptions.InstallError]:   Using cached MarkupSafe-1.0.tar.gz (14 kB)
[pipenv.exceptions.InstallError]:     ERROR: Command errored out with exit status 1:
[pipenv.exceptions.InstallError]:      command: /home/reuven/.local/share/virtualenvs/server-jfb3rzTr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qju0bvdp/markupsafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qju0bvdp/markupsafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-jercma7i
[pipenv.exceptions.InstallError]:          cwd: /tmp/pip-install-qju0bvdp/markupsafe/
[pipenv.exceptions.InstallError]:     Complete output (5 lines):
[pipenv.exceptions.InstallError]:     Traceback (most recent call last):
[pipenv.exceptions.InstallError]:       File "<string>", line 1, in <module>
[pipenv.exceptions.InstallError]:       File "/tmp/pip-install-qju0bvdp/markupsafe/setup.py", line 6, in <module>
[pipenv.exceptions.InstallError]:         from setuptools import setup, Extension, Feature
[pipenv.exceptions.InstallError]:     ImportError: cannot import name 'Feature' from 'setuptools' (/home/reuven/.local/share/virtualenvs/server-jfb3rzTr/lib/python3.7/site-packages/setuptools/__init__.py)
[pipenv.exceptions.InstallError]:     ----------------------------------------
[pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Couldn't install package: markupsafe
 Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/2 — 00:00:02`

I then tried to install markupsafe directly with `pipenv install markupsafe`, which does correctly but it now has issues with psycopg2 and rpy2. Output for `pipenv install markupsafe` given [here](https://gist.github.com/ReuvenBirnbaum/51b6efeb55e74ea87c03ed0c6586c73f), and  `pipenv install markupsafe --verbose given [here](https://gist.github.com/ReuvenBirnbaum/aa74a27699228db5086a9704f3fb18c2). 

I then tried to follow this bug report [here](https://github.com/pypa/pipenv/issues/3991): 
`pipenv --rm`
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Removing virtualenv (/home/reuven/.local/share/virtualenvs/server-jfb3rzTr)…

`pipenv install psycopg2-binary` Output [here](https://gist.github.com/ReuvenBirnbaum/ea18e84f5a942536d68bc6cc64c2ad6b). 

As can be seen, the issue is still not resolved and I'm unsure how to proceed to install psycopg2 or rpy2. 

### Steps to replicate
Download Pipfile/Pipfile.lock in github linked above and run commands given above.

**Comment by mihaelagrigore** [comment]
@ReuvenBirnbaum I have a similar issue. Did you manage to solve this ?

**Comment by matteius** [comment]
I believe this is closeable at this point.
