### ISSUE TITLE
Pipenv install --selective-upgrade

### ISSUE THREAD

**Issue by saisankargochhayat** [pypa/pipenv#4351]
### Issue description
Attempting just to upgrade one package, with out updating other packages. 

### Steps to replicate
Git clone - https://github.com/saisankargochhayat/pipenvTest
Couple of scenarios I tried out just to update one package requests - 
- `pipenv install requests==2.24.0 --keep-outdated`
  Just updates the package version, but not the hashes in the Pipfile.lock, pins down in Pipfile
- `pipenv install --selective-upgrade requests==2.24.0`
   Just updates the package version, but not the hashes in the Pipfile.lock, pins down in Pipfile
- `pipenv install requests==2.24.0` 
   Updates both requests and semver to their latest versions and the hashes. 
- `pipenv update --selective-upgrade requests`
   Updates both requests and semver to their latest versions and the hashes. 

Seems like `pipenv install {dependency}=={package_version} --keep-outdated` earlier did the trick, but now it works, but just misses out on the new hash. Is there a new way to achieve this?

-------------------------------------------------------------------------------
Pipenv support output - https://gist.github.com/saisankargochhayat/a7d09bdc1cea8eeadf902a1bae503b1d

**Comment by saisankargochhayat** [comment]
`pipenv install requests==2.24.0 --keep-outdated` still doesn't seem to be working with Pipenv 2020.8.13 :disappointed: 
![image](https://user-images.githubusercontent.com/9396452/91492329-7afd4580-e883-11ea-8b6a-9710e5dae1ff.png)

**Comment by danstewart** [comment]
I have been having this issue and have found a workaround.

```
# Install the package
# This will update the version number in Pipfile and the Pipfile.lock - but not the package hashes
# I'm not sure if --keep-outdated does anything here, I get the same results without it but I include it to be safe
pipenv install --keep-outdated --selective-upgrade package==0.0.1

# This will update the hashes for the modified package only
pipenv lock --keep-outdated
```

The only downside is that it seems to _add_ the new hashes and keeps the old ones, but that doesn't seem too big of a deal to me.

**Comment by matteius** [comment]
`--keep-outdated` and likely `--selective-upgrade` are deprecated/slated for removal.   I've been working on an alternative command that solves the kind of problems these other flags caused.   Checkout out: https://github.com/pypa/pipenv/pull/5617
