### ISSUE TITLE
[packages.<...>] breaks the installation

### ISSUE THREAD

**Issue by ahmadalli** [pypa/pipenv#4352]
### Issue description

this is my `Pipfile`:

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
Flask = "*"
Flask-RESTful = "*"
Flask-SQLAlchemy = "*"
Flask-Migrate = "*"
celery = "*"
<some other packages>

[dev-packages]
autopep8 = "*"

[requires]
python_version = "3.8"

[packages.dynaconf]
extras = [ "yaml",]

[packages.sentry-sdk]
extras = [ "flask",]
```

`pipenv install` generates this `Pipfile.lock`:

```
{
    "_meta": {
        "hash": {
            "sha256": "4602290511bf3cd794f508985aa0971cbeb846871dac0e9f9b8bb71c31071b85"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "dynaconf": {
            "extras": [
                "yaml"
            ]
        },
        "sentry-sdk": {
            "extras": [
                "flask"
            ]
        }
    },
    "develop": {
        "autopep8": {
            "hashes": [
                "sha256:60fd8c4341bab59963dafd5d2a566e94f547e660b9b396f772afe67d8481dbf0"
            ],
            "index": "pypi",
            "version": "==1.5.3"
        },
        "pycodestyle": {
            "hashes": [
                "sha256:2295e7b2f6b5bd100585ebcb1f616591b652db8a741695b3d8f5d28bdc934367",
                "sha256:c58a7d2815e0e8d7972bf1803331fb0152f867bd89adf8a01dfd55085434192e"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "version": "==2.6.0"
        },
        "toml": {
            "hashes": [
                "sha256:926b612be1e5ce0634a2ca03470f95169cf16f939018233a670519cb4ac58b0f",
                "sha256:bda89d5935c2eac546d648028b9901107a595863cb36bae0c73ac804a9b4ce88"
            ],
            "version": "==0.10.1"
        }
    }
}
```
which doesn't contain the packages I have in the `Pipfile`

if I remove `[packages.dynaconf]` and `[packages.sentry-sdk]` from the `Pipfile` it'd work perfectly

### Expected result

the `Pipfile.lock` should contain all packages

### Actual result

`Pipfile.lock` contains only packages for `[packages.dynaconf]` and `[packages.sentry-sdk]` and dev packages

### Steps to replicate

1. add pipfile
1. `pipenv install`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.6.2'`

Pipenv location: `'/home/ahmadalli/.local/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.8.2`: `/home/ahmadalli/.local/share/virtualenvs/api-U_LJYyFY/bin/python3.8`
  - `3.8.2`: `/home/ahmadalli/.local/share/virtualenvs/api-U_LJYyFY/bin/python3`
  - `3.8.2`: `/home/ahmadalli/.local/share/virtualenvs/api-U_LJYyFY/bin/python3.8`
  - `3.8.2`: `/home/ahmadalli/.local/share/virtualenvs/api-U_LJYyFY/bin/python3`
  - `3.8.2`: `/usr/bin/python3.8`
  - `3.8.2`: `/usr/bin/python3`
  - `3.8.2`: `/bin/python3.8`
  - `3.8.2`: `/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.19.84-microsoft-standard',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Wed Nov 13 11:44:37 UTC 2019',
 'python_full_version': '3.8.2',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `WSL_DISTRO_NAME`
  - `WT_SESSION`
  - `PIPENV_ACTIVE`
  - `NAME`
  - `PWD`
  - `LOGNAME`
  - `PIP_PYTHON_PATH`
  - `HOME`
  - `LANG`
  - `WSL_INTEROP`
  - `LS_COLORS`
  - `VIRTUAL_ENV`
  - `DOCKER_BUILDKIT`
  - `NVM_DIR`
  - `COMPOSE_DOCKER_CLI_BUILD`
  - `LESSCLOSE`
  - `TERM`
  - `LESSOPEN`
  - `USER`
  - `VAULT_ADDR`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `SHLVL`
  - `PYTHONDONTWRITEBYTECODE`
  - `PS1`
  - `WSLENV`
  - `KUBE_EDITOR`
  - `XDG_DATA_DIRS`
  - `PATH`
  - `HOSTTYPE`
  - `WT_PROFILE_ID`
  - `OLDPWD`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

**Comment by ahmadalli** [comment]
I tried installing the packages again and now they're on the Pipfile with different format:
```
sentry-sdk = {extras = ["flask"], version = "*"}
dynaconf = {extras = ["yaml"], version = "*"}
```

this may be some issue of backward compatibility then

**Comment by matteius** [comment]
I think you are right @ahmadalli  -- I am closing this one out.  Let us know if you are still having difficulties.
