### ISSUE TITLE
pipenv install not working if ~/.pip/pipconf file has an extra-index-url 

### ISSUE THREAD

**Issue by dskart** [pypa/pipenv#4353]
### Issue description

I added a private repository to ~/.pip/pipconf with the "extra-index-url". That repository uses https as well as a username/password. 
example of ~/.pip/pipconf
```
[global]
extra-index-url = https://some_pypi_url.com
```

I have set my username and password for the url using keyring.

All of this works perfectly fine when I do a normal
```
pip install my_package
```
But when I go inside a pipenv project and run pipenv install, pipenv hangs on "Installing".
This happens for packages in my private pypi and packages on pypi like numpy.

### Expected result

pipenv install "some_package" should still work for pypi and my private_pypi

### Actual result

when I run:
```
pipenv -v install numpy
```

```
Installing numpy…
Installing package: numpy
Writing supplied requirement line to temporary file: 'numpy'
⠙ Installing numpy...$ ['/home/USER/.local/share/virtualenvs/SOME_PROJECT-AuSfvr89/bin/pip', 'install', '--pre', '--verbose', '--upgrade', '--exists-action=i', '-r', '/tmp/pipenv-5u119_2n-requirements/pipenv-jw4cac4u-requirement.txt', '-i', 'https://pypi.org/simple'
  Installing numpy ....
```
It then hangs for ever

### Steps to replicate

Add a extra-index-url inside your ~/.pip/pipconf:
```
[global]
extra-index-url = https://some_pypi_url.com
```

add the username/password of your private pypi url using keyring

run this inside any project with pipenv
```
pipenv install any_package
```

**Comment by frostming** [comment]
The config is for pip and Pipenv doesn't read it, nor is there any assumption that Pipenv should read it.
