### ISSUE TITLE
Specify dependencies without building

### ISSUE THREAD

**Issue by jobevers** [pypa/pipenv#4362]
I have a library that takes a long time to build. When its listed as a dependency using pipenv, the locking process takes a long time. I believe pipenv builds the library to try to determine the dependencies of the library.

Is there a way that I can specify the dependencies and pipenv will skip the build process?

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.6.2'`

Pipenv location: `'/home/jobevers/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.8.3`: `/home/jobevers/.pyenv/versions/3.8.3/bin/python3.8`
  - `3.8.2`: `/home/jobevers/.pyenv/versions/3.8.2/bin/python3.8`
  - `3.7.7`: `/home/jobevers/.pyenv/versions/3.7.7/bin/python3.7`
  - `3.6.9`: `/usr/bin/python3`
  - `3.6.9`: `/usr/bin/python3.6m`
  - `3.6.9`: `/usr/bin/python3.6`
  - `2.7.17`: `/usr/bin/python2.7`
  - `2.7.17`: `/usr/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.9',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.3.0-1026-gcp',
 'platform_system': 'Linux',
 'platform_version': '#28~18.04.1-Ubuntu SMP Sat Jun 6 00:09:26 UTC 2020',
 'python_full_version': '3.6.9',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SSH_CONNECTION`
  - `LANG`
  - `SSH_AUTH_SOCK`
  - `XDG_SESSION_ID`
  - `USER`
  - `PWD`
  - `HOME`
  - `LC_CTYPE`
  - `LC_TERMINAL`
  - `SSH_CLIENT`
  - `LC_TERMINAL_VERSION`
  - `XDG_DATA_DIRS`
  - `SSH_TTY`
  - `MAIL`
  - `TERM`
  - `SHELL`
  - `SHLVL`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `PATH`
  - `OLDPWD`
  - `ZSH`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `LS_COLORS`
  - `PYENV_ROOT`
  - `PYENV_SHELL`
  - `EDITOR`
  - `SPARK_HOME`
  - `PD_DEPENDENCIES`
  - `PD_PROJECTS`
  - `PIPENV_IGNORE_VIRTUALENVS`
  - `CLOUDSDK_PYTHON`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_IGNORE_VIRTUALENVS`: `1`

Debug–specific environment variables:

  - `PATH`: `/opt/google-cloud-sdk/bin:/home/jobevers/.pyenv/shims:/home/jobevers/.pyenv/bin:/home/jobevers/.local/bin:/opt/gopath/bin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `nano`
  - `LANG`: `C.UTF-8`
</details>

**Comment by jobevers** [comment]
It would be nice to be able to skip this line: https://github.com/pypa/pipenv/blob/d69198c0fb13a0ff92a6d105f2eb07f23ceb70b5/pipenv/vendor/requirementslib/models/setup_info.py#L1784

**Comment by matteius** [comment]
I don't believe there is a way to get the metadata without building the package.   That code has changed a bit since your issue report, but it appears to still build.  Can you confirm if this is still an issue for you @jobevers ?
