### ISSUE TITLE
Pipfile.toml instead of Pipfile

### ISSUE THREAD

**Issue by Theodore-Robinson** [pypa/pipenv#4363]
A small suggestion, vscode and other editors cannot format the pipfile to look beautiful, how about making the pipfile a pipfile.toml?

**Comment by frostming** [comment]
It was taken from a very common naming convention: `<Toolname>file`, e.g. RubyGem's `Gemfile`/`Gemfile.lock`.
So we would like to keep the name as it is. Plus, my VSCode and Pycharm can highlight the file correctly.
