### ISSUE TITLE
Why are projects copied into /tmp?

### ISSUE THREAD

**Issue by jobevers** [pypa/pipenv#4365]
Asking about this line:
https://github.com/pypa/pipenv/blob/master/pipenv/vendor/requirementslib/models/setup_info.py#L1870

I have some internal libraries that have a lot of data files and are a few GB in size. Having to copy the repo into /tmp adds a significant amount of time to the locking process.

**Comment by mjpieters** [comment]
See #4403 for a more detailed bug report on this, and c4a165bce35edf661abaaa68c3cfd427664e5e25 for why it was changed.

**Comment by CharString** [comment]
Also /tmp is not cleaned up if pipenv fails due to an exception.
I can see why this behaviour might be desirable when you're working on pipenv itself. But it shouldn't be the default behaviour.
