### ISSUE TITLE
cannot install wheel from private pypi

### ISSUE THREAD

**Issue by craynic** [pypa/pipenv#4373]
We have built some wheels and uploaded to our private pypi. We can install them with pip, but not with pipenv.
My `Pipfile`:

```toml
[[source]]
url = "https://pypi.doubanio.com/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://user:password@example.com/repository/pypi-internal/simple"
verify_ssl = true
name = "private"

[packages]
sasl = {index = "private"}
```

Got an error in running `pipenv install`:

```
Updated Pipfile.lock (72b261)!
Installing dependencies from Pipfile.lock (72b261)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
An error occurred while installing sasl==0.2.1 --hash=sha256:a86aed371778feee7340f1c504996f2aed3da1747e89005c1f4801c4bc9fa95f --hash=sha256:04f22e17bbebe0cd42471757a48c2c07126773c38741b1dad8d9fe724c16289d! Will try again.
Installing initially failed dependencies…
(sasl build errors)
ERROR: Couldn't install package: sasl
```

Some debug info:

```
Looking in indexes: https://pypi.doubanio.com/simple, https://user:****@example.com/repository/pypi-internal/simple/, https://user:****@example.com/repository/pypi-internal/simple                                                                     
2 location(s) to search for versions of sasl:                                                                                               
* https://pypi.doubanio.com/simple/sasl/                                                                                                    
* https://user:****@example.com/repository/pypi-internal/simple/sasl/                                                       
Fetching project page and analyzing links: https://pypi.doubanio.com/simple/sasl/                                                           
Getting page https://pypi.doubanio.com/simple/sasl/                                                                                         
Found index url https://pypi.doubanio.com/simple                                                                                            
Looking up "https://pypi.doubanio.com/simple/sasl/" in the cache                                                                            
Request header has "max_age" as 0, cache bypassed                                                                                           
Starting new HTTPS connection (1): pypi.doubanio.com:443                                                                                    
https://pypi.doubanio.com:443 "GET /simple/sasl/ HTTP/1.1" 304 0                                                                            
  Found link https://pypi.doubanio.com/packages/9c/77/e2b33cb181d7d8b65e5541cee50d075b88a79456e71d8ebff398852ec19e/sasl-0.1.1.tar.gz#sha256=902e2fc57f0f1d0e40da0f05b20b7bffd7ccc90d9c123fb375581021fc2a7624 (from https://pypi.doubanio.com/simple/sasl/), version: 0.1.1              
  Found link https://pypi.doubanio.com/packages/e2/52/8c1ce738d94654371565403b9c9468f2f0acf423c81a9a73d969f91ff98a/sasl-0.1.2.tar.gz#sha256=07e774f633de1b3cf0e1d0bdc9e02cd2f08fd5d8d9a4c073f33aedab4de9ffd4 (from https://pypi.doubanio.com/simple/sasl/), version: 0.1.2              
  Found link https://pypi.doubanio.com/packages/73/e1/c38a11a2bca79d6857dfcfb539a7b615d06bc60e029980d057be469594e2/sasl-0.1.3.tar.gz#sha256=4f324226e1ee85ac41520579ba9de703294012602e536217fd0e7456e147d886 (from https://pypi.doubanio.com/simple/sasl/), version: 0.1.3              
  Found link https://pypi.doubanio.com/packages/7e/cf/dd5d00ca015b0ab2e9981b0dc37a40054165bbcc83a003fa23b3b558868c/sasl-0.1.tar.gz#sha256=c4262541ec852f620656eac4797984e28cf6d2d7caeff110c64705660538390b (from https://pypi.doubanio.com/simple/sasl/), version: 0.1                  
  Found link https://pypi.doubanio.com/packages/8e/2c/45dae93d666aea8492678499e0999269b4e55f1829b1e4de5b8204706ad9/sasl-0.2.1.tar.gz#sha256=04f22e17bbebe0cd42471757a48c2c07126773c38741b1dad8d9fe724c16289d (from https://pypi.doubanio.com/simple/sasl/), version: 0.2.1              
Fetching project page and analyzing links: https://user:****@example.com/repository/pypi-internal/simple/sasl/              
Getting page https://user:****@example.com/repository/pypi-internal/simple/sasl/                                            
Found credentials in url for example.com                                                                                            
Looking up "https://example.com/repository/pypi-internal/simple/sasl/" in the cache                                                 
Request header has "max_age" as 0, cache bypassed                                                                                           
Starting new HTTPS connection (1): example.com:443                                                                                  
https://example.com:443 "GET /repository/pypi-internal/simple/sasl/ HTTP/1.1" 200 None                                              
Updating cache with response from "https://example.com/repository/pypi-internal/simple/sasl/"                                       
  Found link https://example.com/repository/pypi-internal/packages/sasl/0.2.1/sasl-0.2.1-cp36-cp36m-linux_x86_64.whl#md5=ccb31f06b5526e7c043e781af9f75455 (from https://example.com/repository/pypi-internal/simple/sasl/), version: 0.2.1                              
Checked 2 links for project 'sasl' against 2 hashes (1 matches, 0 no digest): discarding 1 non-matches:                                     
  https://example.com/repository/pypi-internal/packages/sasl/0.2.1/sasl-0.2.1-cp36-cp36m-linux_x86_64.whl#md5=ccb31f06b5526e7c043e781af9f75455 (from https://example.com/repository/pypi-internal/simple/sasl/) 
```

Pipenv found the wheel, but ignored it due to a hash dismatch.
How could I install the wheel?

-------------------------------------------------------------------------------
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.6.2'`

Pipenv location: `'/home/yucheng.cai/knobs/venv/lib/python3.6/site-packages/pipenv'`

Python location: `'/home/yucheng.cai/knobs/venv/bin/python3'`

Python installations found:

  - `3.6.8`: `/home/yucheng.cai/knobs/venv/bin/python3.6`
  - `3.6.8`: `/home/yucheng.cai/knobs/venv/bin/python3`
  - `3.6.8`: `/home/yucheng.cai/knobs/venv/bin/python3.6`
  - `3.6.8`: `/home/yucheng.cai/knobs/venv/bin/python3`
  - `3.6.8`: `/usr/bin/python3`
  - `3.6.8`: `/usr/bin/python3.6m`
  - `3.6.8`: `/usr/bin/python3.6`
  - `2.7.5`: `/usr/bin/python2`
  - `2.7.5`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.8',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '3.10.0-957.1.3.el7.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Thu Nov 29 14:49:43 UTC 2018',
 'python_full_version': '3.6.8',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `XDG_SESSION_ID`
  - `rvm_bin_path`
  - `HOSTNAME`
  - `GEM_HOME`
  - `TERM`
  - `SHELL`
  - `HISTSIZE`
  - `IRBRC`
  - `SSH_CLIENT`
  - `OLDPWD`
  - `MY_RUBY_HOME`
  - `SSH_TTY`
  - `USER`
  - `LS_COLORS`
  - `rvm_path`
  - `VIRTUAL_ENV`
  - `rvm_prefix`
  - `MAIL`
  - `PATH`
  - `PWD`
  - `LANG`
  - `PS1`
  - `HISTCONTROL`
  - `rvm_version`
  - `SHLVL`
  - `HOME`
  - `LOGNAME`
  - `GEM_PATH`
  - `SSH_CONNECTION`
  - `LESSOPEN`
  - `XDG_RUNTIME_DIR`
  - `RUBY_VERSION`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/yucheng.cai/knobs/venv/bin:/usr/local/rvm/gems/ruby-2.4.1/bin:/usr/local/rvm/gems/ruby-2.4.1@global/bin:/usr/local/rvm/rubies/ruby-2.4.1/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/rvm/bin:/opt/cassandra/bin:/home/yucheng.cai//.local/bin:/home/yucheng.cai//bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/yucheng.cai/knobs`
  - `VIRTUAL_ENV`: `/home/yucheng.cai/knobs/venv`

**Comment by GPHemsley** [comment]
I think the problem here is that pipenv is pulling the hashes from pypi.org for some reason. Because your particular private package has a name collision with a public package, it is causing a hash mismatch, because it managed to get the right hash on one side of the equation but not the other.

I am also experiencing this.

@craynic I wonder, does your private package have dependencies that are also private but have name collisions with a public package? Are those getting resolved correctly?

**Comment by craynic** [comment]
There should be no collision. My private package is just a wheel built from the source package on pypi. No other dependencies or modifications.

**Comment by GPHemsley** [comment]
> There should be no collision. My private package is just a wheel built from the source package on pypi. No new dependencies or modifications.

When I say collision, I mean that the name of your private package (which appears to be 'sasl' in this case) is also the name of a package on pypi.org (https://pypi.org/project/sasl/). The hash you are comparing against is the hash available on pypi.org.

As for the dependencies, I was trying to explore whether we could replicate in your environment the problem that I am experiencing. Would it be possible for you to mock up some private repo packages that depend on each other while also depending on public packages from PyPI?

**Comment by craynic** [comment]
> > There should be no collision. My private package is just a wheel built from the source package on pypi. No new dependencies or modifications.
> 
> When I say collision, I mean that the name of your private package (which appears to be 'sasl' in this case) is also the name of a package on pypi.org (https://pypi.org/project/sasl/). The hash you are comparing against is the hash available on pypi.org.
> 
> As for the dependencies, I was trying to explore whether we could replicate in your environment the problem that I am experiencing. Would it be possible for you to mock up some private repo packages that depend on each other while also depending on public packages from PyPI?

It's possible and very common that multi packages have the same name even in one repository. I don't think it's mistake that they exist in two repositories.

And, I don't think it makes sense that two packages depends on each other. You could create a new virtual package depending on all of them.

**Comment by frostming** [comment]
What is the content of your Pipfile.lock?

**Comment by craynic** [comment]
I've lost the lock file.

Well it should had locked with the hash of the wheel package, Because the hash in the log is different from the hash of the source package on pypi.

**Comment by matteius** [comment]
Stale issue -- it is definitely possible to install a wheel from a private pypi on recent pipenv versions.
