### ISSUE TITLE
allow for more then one virtual environment 

### ISSUE THREAD

**Issue by frog-o** [pypa/pipenv#4376]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues and the [PEEP list](https://github.com/pypa/pipenv/blob/master/peeps/) before posting! We may close your issue if it is very similar to one of them. Please be considerate and follow the PEEP process, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Is your feature request related to a problem? Please describe.

yes but not to anything you have posted. 
I'm trying to switching between pypy and cpython virtual environment  to do testing on speed issue and laging in the python programs I am using

A good example of the problem I having is install piipenv ( follow the contributor guide) and running   

> pipenv install --dev

work ok except uses wrong python as already mention in issue  #4339 (pipenv does not use default python version under pyenv) 

but if i want to also install a virtual environment for python 3.6 and run 

> pipenv install --dev --python /usr/local/pyenv/versions/pypy3.6-7.3.1-src/bin/python

it says 

>Virtualenv already exists!
Removing existing virtualenv…

not what I want. I want to have both. 

Right now i don't think there is a way to do this.   

>A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

I'm always frustrated when

* It is creating a pipfile when I don't want one (it demands a specific python, would not be a problem if was not for this) 
* I can't run pipenv shell and drop into the virtual environment shell I want to run    
* I keep running into more problems
* the  --python option does not work well  

### Describe the solution you'd like

I would like to run 

>pipenv --python /usr/bin/pypy

have it create a environment for pypy

then run 

>pipenv --python /usr/bin/python 
 
have it create an environment for python 

then run 

>pipenv shell 

have it print something to the likes of 

>you have more then one python enviorment installed they are
>1 /usr/bin/python
>2 /usr/bin/pypy
>
>please use the --python flag

done above 
 

### Additional context
-------------------------------------------------------------------------------

Like all issues i make I want to look into implement this but not sure if i can( I am not that good of programmer) and want to see if this type of thing is welcomed.  

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on Linux, run the following:

    $ pipenv --support | xclip

return nothing 

but pipenv --support returns
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.6.2'`

Pipenv location: `'/usr/local/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/local/pyenv/versions/3.8.2/bin/python3.8'`

Python installations found:

  - `3.8.2`: `/usr/local/pyenv/versions/3.8.2/bin/python3`
  - `3.8.2`: `/usr/local/pyenv/versions/3.8.2/bin/python3.8`
  - `3.8.2`: `/usr/local/pyenv/versions/3.8.2/bin/python3`
  - `3.7.3`: `/usr/bin/python3`
  - `3.7.3`: `/usr/bin/python3.7m`
  - `3.7.3`: `/usr/bin/python3.7`
  - `2.7.17`: `/usr/local/pyenv/versions/2.7.17/bin/python2`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.2',
 'os_name': 'posix',
 'platform_machine': 'armv7l',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.47-v7l+',
 'platform_system': 'Linux',
 'platform_version': '#1322 SMP Wed Jun 17 17:58:52 BST 2020',
 'python_full_version': '3.8.2',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `SESSION_MANAGER`
  - `WINDOWID`
  - `PYENV_HOOK_PATH`
  - `QT_ACCESSIBILITY`
  - `COLORTERM`
  - `PYENV_SHELL`
  - `XDG_CONFIG_DIRS`
  - `XDG_MENU_PREFIX`
  - `SSH_AUTH_SOCK`
  - `DEBFULLNAME`
  - `DESKTOP_SESSION`
  - `SSH_AGENT_PID`
  - `PYENV_VERSION`
  - `GTK_MODULES`
  - `XDG_SEAT`
  - `PWD`
  - `PIPX_BIN_DIR`
  - `LOGNAME`
  - `XDG_SESSION_TYPE`
  - `CXXFLAGS`
  - `XAUTHORITY`
  - `HOME`
  - `LANG`
  - `LS_COLORS`
  - `XDG_CURRENT_DESKTOP`
  - `VTE_VERSION`
  - `DEBEMAIL`
  - `INVOCATION_ID`
  - `PYENV_DIR`
  - `GLADE_CATALOG_PATH`
  - `XDG_SESSION_CLASS`
  - `TERM`
  - `USER`
  - `PIPX_HOME`
  - `DISPLAY`
  - `SHLVL`
  - `XDG_VTNR`
  - `UBUNTU_MENUPROXY`
  - `XDG_SESSION_ID`
  - `GLADE_MODULE_PATH`
  - `XDG_RUNTIME_DIR`
  - `GLADE_PIXMAP_PATH`
  - `PYENV_ROOT`
  - `JOURNAL_STREAM`
  - `XDG_DATA_DIRS`
  - `PATH`
  - `CFLAGS`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `TEXTDOMAIN`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/pyenv/versions/3.8.2/bin:/usr/local/pyenv/libexec:/usr/local/pyenv/plugins/xxenv-latest/bin:/usr/local/pyenv/plugins/python-build/bin:/usr/local/pyenv/plugins/pyenv-virtualenv/bin:/usr/local/pyenv/plugins/pyenv-update/bin:/usr/local/pyenv/plugins/pyenv-installer/bin:/usr/local/pyenv/plugins/pyenv-doctor/bin:/usr/local/poetry/bin:/home/pi/.local/bin:/home/pi/bin:/usr/local/pyenv/shims:/usr/local/pipx/bin:/usr/local/pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/pi/pip-sources/pyvim-env/src/pyvim`

---------------------------

Contents of `Pipfile` ('/home/pi/pip-sources/pyvim-env/src/pyvim/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
prompt-toolkit = "*"
six = "*"
pyflakes = "*"
pygments = "*"
docopt = "*"
pyvim = {editable = true, path = "."}

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/home/pi/pip-sources/pyvim-env/src/pyvim/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "4709cd6234a8a4ed09266873409dc3a4e1f4e26f93b006a245598e7acc6dee79"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "docopt": {
            "hashes": [
                "sha256:49b3a825280bd66b3aa83585ef59c4a8c82f2c8a522dbe754a8bc8d08c85c491"
            ],
            "index": "pypi",
            "version": "==0.6.2"
        },
        "prompt-toolkit": {
            "hashes": [
                "sha256:563d1a4140b63ff9dd587bda9557cffb2fe73650205ab6f4383092fb882e7dc8",
                "sha256:df7e9e63aea609b1da3a65641ceaf5bc7d05e0a04de5bd45d05dbeffbabf9e04"
            ],
            "index": "pypi",
            "version": "==3.0.5"
        },
        "pyflakes": {
            "hashes": [
                "sha256:0d94e0e05a19e57a99444b6ddcf9a6eb2e5c68d3ca1e98e90707af8152c90a92",
                "sha256:35b2d75ee967ea93b55750aa9edbbf72813e06a66ba54438df2cfac9e3c27fc8"
            ],
            "index": "pypi",
            "version": "==2.2.0"
        },
        "pygments": {
            "hashes": [
                "sha256:647344a061c249a3b74e230c739f434d7ea4d8b1d5f3721bc0f3558049b38f44",
                "sha256:ff7a40b4860b727ab48fad6360eb351cc1b33cbf9b15a0f689ca5353e9463324"
            ],
            "index": "pypi",
            "version": "==2.6.1"
        },
        "pyvim": {
            "editable": true,
            "path": "."
        },
        "six": {
            "hashes": [
                "sha256:30639c035cdb23534cd4aa2dd52c3bf48f06e5f4a941509c8bafd8ce11080259",
                "sha256:8b74bedcbbbaca38ff6d7491d76f2b06b3592611af620f8426e82dddb04a5ced"
            ],
            "index": "pypi",
            "version": "==1.15.0"
        },
        "wcwidth": {
            "hashes": [
                "sha256:beb4802a9cebb9144e99086eff703a642a13d6a0052920003a230f3294bbe784",
                "sha256:c4d647b99872929fdb7bdcaa4fbe7f01413ed3d98077df798530e5b04f116c83"
            ],
            "version": "==0.2.5"
        }
    },
    "develop": {}
}

**Comment by frostming** [comment]
This can be achieved by:
```bash
PIPENV_PYTHON=/path/to/python pipenv install
```

**Comment by frog-o** [comment]
Thankyou 

@frostming 

For you time and  the command bellow.

>PIPENV_PYTHON=/path/to/python pipenv install

I would like to have a better way to do(And wanted to work on) it, since IMHO it is not very user friendly.

For example 

 I want to and a config file for common option that pipenv just does not do the right thing on like [issue](https://github.com/pypa/pipenv/issues/4485)  

Have an options in the config some like    
```
# option to control which python pipenv uses  
#ask on install virtual environment 
VIRENV= ask 
#allows for only one environment deletes the old 
VIRENV=OnlyOne
#to allow it to  create for more than one..
VIRENV=Multiple

DefaultVirPython= /path/to/python 

```

or just when you specify the correct python with the flag have it not delete it.

If I made the changes in pipenv soucecode that allowed for this would it be acceptable or is there some undocumented way to do this.  Adding something in the env file which is unexplained maybe?  

 I apologize That this is getting to close to a stackoverful question and I understand if you don't want to talk about it anymore.
