### ISSUE TITLE
Is there a way I can install packages without creating a f environment?

### ISSUE THREAD

**Issue by ratusratus** [pypa/pipenv#4377]
The github repo I downloaded have dumped all the package information in a pipfile. Hence, I have no other option than to use this package. As frustrating it is to use this package, it is also lacks a good documentation. I have already created an environment and I don't want this stupid package to create another. There isn't anything on the internet regarding this. Is there a way around this or should I have to manually create a requirement.txt file by using Ctrl+C and Ctrl+V?

**Comment by Frame42** [comment]
see here https://pipenv-fork.readthedocs.io/en/latest/advanced.html#generating-a-requirements-txt

**Comment by frostming** [comment]
You can generate a requirements.txt using https://github.com/frostming/pipfile-requirements
