### ISSUE TITLE
Prompt to verify in case of no Pipfile at context

### ISSUE THREAD

**Issue by kobibarhanin** [pypa/pipenv#4382]
I've been using pipenv for a while now, and I've grown accustomed to _deleting unnecessary mistakably created_ Pipfiles.

Whenever running pipenv shell / install / (even) check - in case of no Pipfile at context an empty one will be generated, and in almost every case for me this was a result of simply running the pipenv command in the wrong directory.

I suggest prompting the user in such cases to notify that no Pipfile was found, an empty one will be created, and allowing the user to reject at that stage.

In my opinion it will improve usability.

**Comment by bendem** [comment]
Easy fix, large gain, would love to see this.

**Comment by kobibarhanin** [comment]
@bendem I agree, but when attempting to approach this I've realised that since this is a behavioural type of change it has a wide effect on the entire CI testing schema (which fails due to basing on top of the current convention where a Pipfile is auto generated), so it might require more work then anticipated.
