### ISSUE TITLE
pipenv install with VSC and powershell is taking many minutes

### ISSUE THREAD

**Issue by RahulMR42** [pypa/pipenv#4389]
### Issue description

Really long to get pipenv install completion with windows using visual studio console and powershell 

### Expected result

pipenv install should end with success or failure in a stipulated time 

### Actual result

![image](https://user-images.githubusercontent.com/23480999/87225461-cf6b6500-c3aa-11ea-838c-1e2f06623082.png)

As you  can see its still in locking state with around 3mnts laps and the package indeed installed and i was able to import using another console .
### Steps to replicate

- Python Versin 3.8 
- Window Version # Windows 10
- VSC Version 1.47.0
- pipenv Version # 2020.6.2

Pipfile 

[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
numpy = "*"
sklearn = "*"
jupyter = "*"

[requires]
python_version = "3.8"
-------------------------------------------------------------------------------
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.6.2'`

Pipenv location: `'c:\\users\\mr\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\pipenv'`

Python location: `'c:\\users\\mr\\appdata\\local\\programs\\python\\python38-32\\python.exe'`

Python installations found:

  - `3.8.3`: `C:\Users\mr\AppData\Local\Programs\Python\Python38-32\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.3',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.18362',
 'python_full_version': '3.8.3',
 'python_version': '3.8',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `CHOCOLATEYINSTALL`
  - `CHOCOLATEYLASTPATHUPDATE`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPOSE_CONVERT_WINDOWS_PATHS`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DOCKER_CERT_PATH`
  - `DOCKER_HOST`
  - `DOCKER_MACHINE_NAME`
  - `DOCKER_TLS_VERIFY`
  - `DOCKER_TOOLBOX_INSTALL_PATH`
  - `DRIVERDATA`
  - `GOPATH`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NO_PROXY`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `ONEDRIVECONSUMER`
  - `ONLINESERVICES`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PLATFORMCODE`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_ARCHITEW6432`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `REGIONCODE`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VBOX_MSI_INSTALL_PATH`
  - `WINDIR`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

PipenvΓÇôspecific environment variables:

DebugΓÇôspecific environment variables:

  - `PATH`: `C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Go\bin;C:\ProgramData\chocolatey\bin;C:\Users\mr\AppData\Local\Programs\Python\Python38-32;C:\Users\mr\AppData\Local\Programs\Python\Python38-32\Scripts;C:\Users\mr\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Docker Toolbox;C:\Users\mr\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\mr\go\bin;C:\Users\mr\AppData\Local\Programs\Python\Python38-32;C:\Users\mr\AppData\Local\Programs\Python\Python38-32\Scripts;`

---------------------------

</details>

- No output with clip

**Comment by frostming** [comment]
The performance has gained an improvement on the latest release
