### ISSUE TITLE
Virtualenv created, but can't be found because of 8.3 filename on Windows

### ISSUE THREAD

**Issue by dem1tris** [pypa/pipenv#4395]
### Issue description

I use Kotlin and subprocess to run pipenv on Windows in specified path. In case the pathname contains ["8.3 filename"](https://en.wikipedia.org/wiki/8.3_filename)-part (as user directory), `pipenv install -r requirements.txt` takes this path unchanged to calculate hash for virtualenv name.

Then another subprocess calls `pipenv graph`, which resolves this pathname to canonical path and therefore miss the virtualenv just created.

In case I run `install` from `cmd` manually, resolved path for Pipfile is canonical, whether current directory represented in `cmd` with 8.3 filename or not. Maybe it resolved by `cmd` itself.

### Expected result

Paths are always canonicalized by pipenv, so graph must be printed.

### Actual result

No virtualenv has been created for this project yet!

### Steps to replicate

1. Subprocess from Kotlin calls `pipenv install`
2. Subprocess from Kotlin calls `pipenv graph`
3. No virtualenv has been created for this project yet!

-------------------------------------------------------------------------------

Pipenv version: `2020.6.2`

**Comment by frostming** [comment]
I don't use Kotlin and can follow your steps to reproduce, so I would like to leave this to anyone who is capable to help. Or you may want to pick this up to find out the bug

**Comment by matteius** [comment]
@dem1tris Could you check on `pipenv=2022.1.8` to see if this is still an issue?
