### ISSUE TITLE
Incorrect version comparison

### ISSUE THREAD

**Issue by Dor1s** [pypa/pipenv#4397]
### Issue description

`pipenv lock` as well as `pipenv install` complains that it couldn't find a matching version even though it did try a matching version.

I'm trying to install `tensorflow==2.3.0rc2` and observe the following error:

```
Could not find a version that matches tensorflow-estimator<2.4.0,>=2.3.0rc0
Tried: 1.10.6, 1.10.7, 1.10.8, 1.10.9, 1.10.10, 1.10.11, 1.10.12, 1.13.0rc0, 1.13.0, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0, 1.15.1, 1.15.2, 2.0.0, 2.0.1, 2.1.0rc0, 2.1.0, 2.2.0rc0, 2.2.0, 2.3.0rc0
```

This is blocking https://github.com/google/clusterfuzz/issues/1540

### Expected result

The last version in the list of the versions tried (`2.3.0rc0`) does satisfy the requirements (`<2.4.0,>=2.3.0rc0`):

```
>>> '2.3.0rc0' < '2.4.0'
True
>>> '2.3.0rc0' >= '2.3.0rc0'
True
>>>
```

### Actual result

```
Could not find a version that matches tensorflow-estimator<2.4.0,>=2.3.0rc0
Tried: 1.10.6, 1.10.7, 1.10.8, 1.10.9, 1.10.10, 1.10.11, 1.10.12, 1.13.0rc0, 1.13.0, 1.14.0rc0, 1.14.0rc1, 1.14.0, 1.15.0, 1.15.1, 1.15.2, 2.0.0, 2.0.1, 2.1.0rc0, 2.1.0, 2.2.0rc0, 2.2.0, 2.3.0rc0
```

### Steps to replicate

```
pipenv install --verbose tensorflow==2.3.0rc2
```

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

```
$ pipenv --support
Error: no such option: --support
```

**Comment by frostming** [comment]
Do you have `allow-prereleases` in your Pipfile, otherwise you should pass it explicitly via `--pre` flag.
