### ISSUE TITLE
pipenv location path error (pulls me into different directories)

### ISSUE THREAD

**Issue by peterg121** [pypa/pipenv#4401]
I am having a problem with launching to heroku via my virtual enviorment and i think it is because my virtual enviorment is set up incorrect.

In order to test that i have set it up correctly this is what i have done.

1. uninstalled pipenv by `pip3 uninstall pipenv`
2. reinstalled by `pip3 install pipenv`
3. Cd to desktop and made a directory call called "django2"
4. cd into "django2"
5. tried to install django in "django2" by `pipenv install django`
6. Opened the pipenv shell by doing pipenv shell

No when i opened the pipenv shell in step 6 i thought i would see `(django2) $` in my terminal. Instead i am getting pulled back to my user profile seeing `(my name) $` what is the story here? because in order to launch multiple projects to heroku i will need multiple "pipfles" and "piplock" files. along with each project having its own "Procfile". but the way it seems to currently be set up is that i only have one "pipfles" and "piplock" file located in my user account.

**Comment by frostming** [comment]
What is the full path of `django2`? is it under the user profile directory?

**Comment by frostming** [comment]
Closing due to no further updates
