### ISSUE TITLE
How to manage platform specific sub-dependencies

### ISSUE THREAD

**Issue by nealkruis** [pypa/pipenv#4408]
My example is that I am using [doit](https://pydoit.org/) for task automation, which includes [macfsevents](https://pypi.org/project/MacFSEvents/) as an [extra_requires](https://github.com/pydoit/doit/blob/6bb833d41c82b6fe1b36a1f9bcfeafa6b3c3133c/setup.py#L82) on macOS.

In most cases, platform specific dependencies should be harmless on other operating systems. The real problem is that this particular dependency fails to install on other operating systems. The only way I have found to get around this is to remove the entry in the lock file (things still work fine on macOS without it--though I don't know if this is reliably the case for other sub-dependencies).

There's some related discussion in #3902.

My questions are:

1. Should pipenv be setting a platform specific marker for this sub-dependency and others in the `extra_requires` field?
2. Is there a method in the Pipfile to tell the environment to ignore specific sub-dependencies, or an alternative workaround where I don't have to modify the lock file?

**Comment by frostming** [comment]
If that is the case, you should mark the sub-dependencies in Pipfile as platform-specific, in the following way:

```toml
[packages]
macfsevents = {version="*", sys_platform="=='darwin'"}
```
