### ISSUE TITLE
Pipenv's shebang doesn't use env

### ISSUE THREAD

**Issue by revolter** [pypa/pipenv#4414]
### Steps to replicate

- Use Ubuntu 16
- Install pyenv
- Run `pyenv install 3.8.5`
- Run `pyenv global 3.8.5`
- Run `python -m pip install pipenv`
- Run `pipenv`

### Actual result

The last command throws this error:

```
bash: /home/ubuntu/.local/bin/pipenv: /usr/bin/python3: bad interpreter: No such file or directory
```

### Expected result

The last command should not throw any error.

### Solution

The `~/.local/bin/pipenv` file should be changed like this:

```diff
-#!/usr/bin/python3
+#!/usr/bin/env python3

 # -*- coding: utf-8 -*-
 import re
 import sys

 from pipenv import cli

 if __name__ == '__main__':
     sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
     sys.exit(cli())
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.6.2'`

Pipenv location: `'/home/ubuntu/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv'`

Python location: `'/home/ubuntu/.pyenv/versions/3.8.5/bin/python'`

Python installations found:

  - `3.8.5`: `/home/ubuntu/.pyenv/versions/3.8.5/bin/python3.8`
  - `3.8.5`: `/home/ubuntu/.pyenv/versions/3.8.5/bin/python3`
  - `3.8.5`: `/home/ubuntu/.pyenv/versions/3.8.5/bin/python3.8`
  - `3.8.5`: `/usr/bin/python3.8`
  - `3.7.8`: `/usr/bin/python3.7`
  - `3.7.8`: `/usr/bin/python3.7m`
  - `2.7.12`: `/usr/bin/python2`
  - `2.7.12`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.4.0-184-generic',
 'platform_system': 'Linux',
 'platform_version': '#214-Ubuntu SMP Thu Jun 4 10:14:11 UTC 2020',
 'python_full_version': '3.8.5',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `XDG_SESSION_ID`
  - `PYENV_ROOT`
  - `SHELL`
  - `TERM`
  - `SSH_CLIENT`
  - `SSH_TTY`
  - `PYENV_VERSION`
  - `LC_ALL`
  - `USER`
  - `LS_COLORS`
  - `PYENV_DIR`
  - `PYENV_VIRTUALENV_INIT`
  - `PATH`
  - `MAIL`
  - `PWD`
  - `LANG`
  - `PYENV_HOOK_PATH`
  - `HOME`
  - `SHLVL`
  - `PYENV_SHELL`
  - `LC_TERMINAL_VERSION`
  - `LOGNAME`
  - `LC_CTYPE`
  - `SSH_CONNECTION`
  - `XDG_DATA_DIRS`
  - `LESSOPEN`
  - `LC_TERMINAL`
  - `XDG_RUNTIME_DIR`
  - `LESSCLOSE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/ubuntu/.pyenv/versions/3.8.5/bin:/home/ubuntu/.pyenv/libexec:/home/ubuntu/.pyenv/plugins/python-build/bin:/home/ubuntu/.pyenv/plugins/pyenv-virtualenv/bin:/home/ubuntu/.pyenv/plugins/pyenv-update/bin:/home/ubuntu/.pyenv/plugins/pyenv-installer/bin:/home/ubuntu/.pyenv/plugins/pyenv-doctor/bin:/home/ubuntu/.pyenv/plugins/pyenv-virtualenv/shims:/home/ubuntu/.pyenv/shims:/home/ubuntu/.pyenv/bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/ubuntu`

---------------------------

</details>

**Comment by frostming** [comment]
The script is generated and installed by `setuptools`, not an issue with Pipenv. Thanks
