### ISSUE TITLE
pipenv run echo $VAR_IN_DOTENV doesn't work

### ISSUE THREAD

**Issue by margaro95** [pypa/pipenv#4416]
### Issue description

I run `pipenv run echo $REDIS_HOST` having a .env file in the folder and the variable REDIS_HOST doesn't get loaded.
Nonetheless, if I go
`pipenv run python` and run in the python shell
> import os
> os.environ['REDIS_HOST']

I get the variable located in the .env file

### Expected result

I would expect that, as pipenv says "Loading .env environment variables" they would be available in the command pipenv run echo $REDIS_HOST

**Comment by frostming** [comment]
No, you can't. Shell variables are interpreted and replaced under the current shell, but dotenv is loaded inside the Pipenv process. However you can `echo $VAR_IN_DOTENV` inside the `pipenv shell`
