### ISSUE TITLE
i cant handle the error when i pipenv install

### ISSUE THREAD

**Issue by pmg0738** [pypa/pipenv#4419]
my python , pip and pipenv version is 

$ python -V                                                                                                            Python 3.8.5

$ pip -V                                                                                                               pip 20.2.1 from c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)

$ pipenv --version                                                                                                     pipenv, version 2020.6.2

when i 
` pipenv install requests`

then..

`Traceback (most recent call last):File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                      ipenv\vendor\pythonfinder\models\python.py", line 618, in parse_executable result_version = get_python_version(path)                                                                            File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\vendor\pythonfinder\utils.py", line 105, in get_python_version                                                       c = subprocess.Popen(version_cmd, **subprocess_kwargs)                                                               File "c:\users\coop\appdata\local\programs\python\python38\lib\subprocess.py",                                        line 854, in __init__                                                                                                     self._execute_child(args, executable, preexec_fn, close_fds,                                                         File "c:\users\coop\appdata\local\programs\python\python38\lib\subprocess.py",                                        line 1307, in _execute_child                                                                                              hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
--`

`During handling of the above exception, another exception occurred:                                                                                                                                                                           Traceback (most recent call last):                                                                                       File "c:\users\coop\appdata\local\programs\python\python38\lib\runpy.py", line                                        194, in _run_module_as_main                                                                                               return _run_code(code, main_globals, None,                                                                           File "c:\users\coop\appdata\local\programs\python\python38\lib\runpy.py", line                                        87, in _run_code                                                                                                          exec(code, run_globals)                                                                                              File "C:\Users\coop\AppData\Local\Programs\Python\Python38\Scripts\pipenv.exe\                                       __main__.py", line 7, in                                                                                         File "C:\Users\coop\AppData\Local\Programs\Python\Python38\Lib\site-packages\p                                       ipenv\vendor\click\core.py", line 829, in __call__                                                                         return self.main(*args, **kwargs)                                                                                    File "C:\Users\coop\AppData\Local\Programs\Python\Python38\Lib\site-packages\p                                       ipenv\vendor\click\core.py", line 782, in main                                                                             rv = self.invoke(ctx)                                                                                                File "C:\Users\coop\AppData\Local\Programs\Python\Python38\Lib\site-packages\p                                       ipenv\vendor\click\core.py", line 1259, in invoke                                                                          return _process_result(sub_ctx.command.invoke(sub_ctx))                                                              File "C:\Users\coop\AppData\Local\Programs\Python\Python38\Lib\site-packages\p                                       ipenv\vendor\click\core.py", line 1066, in invoke                                                                          return ctx.invoke(self.callback, **ctx.params)                                                                       File "C:\Users\coop\AppData\Local\Programs\Python\Python38\Lib\site-packages\p                                       ipenv\vendor\click\core.py", line 610, in invoke                                                                           return callback(*args, **kwargs)                                                                                     File "C:\Users\coop\AppData\Local\Programs\Python\Python38\Lib\site-packages\p                                       ipenv\vendor\click\decorators.py", line 73, in new_func                                                                    return ctx.invoke(f, obj, *args, **kwargs)                                                                           File "C:\Users\coop\AppData\Local\Programs\Python\Python38\Lib\site-packages\p                                       ipenv\vendor\click\core.py", line 610, in invoke                                                                           return callback(*args, **kwargs)                                                                                     File "C:\Users\coop\AppData\Local\Programs\Python\Python38\Lib\site-packages\p                                       ipenv\vendor\click\decorators.py", line 21, in new_func                                                                    return f(get_current_context(), *args, **kwargs)                                                                     File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\cli\command.py", line 232, in install                                                                                retcode = do_install(                                                                                                File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\core.py", line 1921, in do_install                                                                                   ensure_project(                                                                                                      File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\core.py", line 576, in ensure_project                                                                                ensure_virtualenv(                                                                                                   File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\core.py", line 498, in ensure_virtualenv                                                                             python = ensure_python(three=three, python=python)                                                                   File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\core.py", line 388, in ensure_python                                                                                 path_to_python = find_a_system_python(python)                                                                        File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\core.py", line 354, in find_a_system_python                                                                          python_entry = find_python(finder, line)                                                                             File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\utils.py", line 2196, in find_python                                                                                 result = finder.find_python_version(line)                                                                            File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\vendor\pythonfinder\pythonfinder.py", line 276, in find_python_version                                               if os.name == "nt" and self.windows_finder is not None:                                                              File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\vendor\pythonfinder\pythonfinder.py", line 129, in windows_finder                                                    self._windows_finder = WindowsFinder()                                                                               File "                                       inder>", line 13, in __init__                                                                                            File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\vendor\pythonfinder\models\windows.py", line 113, in get_versions                                                    versions[py_version.version_tuple[:5]] = base_dir                                                                    File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\vendor\pythonfinder\models\python.py", line 365, in __getattribute__                                                 result = super(PythonVersion, self).__getattribute__(key)                                                            File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\vendor\pythonfinder\models\python.py", line 430, in version_tuple                                                    self.patch,                                                                                                          File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\vendor\pythonfinder\models\python.py", line 375, in __getattribute__                                                 instance_dict = self.parse_executable(executable)                                                                    File "c:\users\coop\appdata\local\programs\python\python38\lib\site-packages\p                                       ipenv\vendor\pythonfinder\models\python.py", line 620, in parse_executable                                                 raise ValueError("Not a valid python path: %r" % path)                                                             ValueError: Not a valid python path: 'C:/Users/coop/Anaconda3/python.exe'
`

**Comment by frostming** [comment]
Did you install a broken python in 'C:/Users/coop/Anaconda3/python.exe'?

**Comment by pmg0738** [comment]
Thanks for reply!
I didn't have Anaconda3 actually
Anyway i couldn't debug the error so i format window10 and i'm using WSL2 in windo10 and i got some new error that i can't handle..

when i hit this comment..
`szmu@DESKTOP-JPNU41L:~/data_ana/opencv$ pipenv install`

i got error like below..
`Pipfile.lock not found, creating…`
`Locking [dev-packages] dependencies…`
`Locking [packages] dependencies…`

`elf.repository.get_dependencies(ireq)`
`File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 174, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)`
 `File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 222, in get_legacy_dependencies
    result = reqset._prepare_file(self.finder, ireq, ignore_requires_python=True)`
 `File "/usr/lib/python3/dist-packages/pipenv/patched/notpip/req/req_set.py", line 644, in _prepare_file
    abstract_dist.prep_for_dist()`
 `File "/usr/lib/python3/dist-packages/pipenv/patched/notpip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()`
 `File "/usr/lib/python3/dist-packages/pipenv/vendor/pip9/req/req_install.py", line 435, in run_egg_info
    call_subprocess(`

 `File "/usr/lib/python3/dist-packages/pipenv/vendor/pip9/utils/__init__.py", line 705, in call_subprocess
    raise InstallationError(`
`pip9.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpwwqn3xh_build/opencv-python/`


Python 3.8.2
pipenv, version 11.9.0

**Comment by frostming** [comment]
You should stick to the latest release of `Pipenv`.

**Comment by soulwawa** [comment]
[Release v2020.8.13](https://github.com/pypa/pipenv/releases/tag/v2020.8.13) solve the issue to me.
