### ISSUE TITLE
ModuleNotFound Error for pika

### ISSUE THREAD

**Issue by addy419** [pypa/pipenv#4420]
Pipenv works perfectly until I have any file that imports pika in the project. When this occurs, I get
```
Using /usr/bin/python3 (3.8.3) to create virtualenv…
⠹ Creating virtual environment...ModuleNotFoundError: No module named 'pika'

✘ Failed creating virtual environment

[pipenv.exceptions.VirtualenvCreationException]:
Failed to create virtual environment.
```
When I remove the import or install pika, only then pipenv creates a virtualenv. It works will all other libraries except pika.

**Comment by frostming** [comment]
What is the project structure? What happens if you create virtualenv with `virtualenv` instead?

**Comment by addy419** [comment]
I have all the files in a single directory, queue.py imports pika. Creating virtual env with virtualenv works flawlessly. Also using virtualenv on another project with same structure works.
Removing queue.py also works.

**Comment by frostming** [comment]
I am afraid you shouldn't use a filename like `queue.py`, which conflicts with Python's standard library.

**Comment by addy419** [comment]
Thank you, It works now, I never thought that would be the issue😅
