### ISSUE TITLE
Unstable version sorting when importing requirements.txt

### ISSUE THREAD

**Issue by fabi125** [pypa/pipenv#4427]
### Issue description

Example requirements.txt:

```
colorama>=0.3,<0.4
```

Importing this via `pipenv install -r requirements.txt` results in either `colorama = ">=0.3,<0.4"` or `colorama = "<0.4,>=0.3"` causing unnecessary churn and unexpected `--deploy` failures.

```
$ pipenv --version
pipenv, version 2020.8.13
```

### Expected result

Repeated import should create a stable Pipfile.

### Actual result

Version sorting varies.

### Steps to replicate

Create `requirements.txt` with content:
```
colorama>=0.3,<0.4
```

Repeatedly run `pipenv install -r requirements.txt` and observe that the Pipfile gets flipped back and forth between `colorama = ">=0.3,<0.4"` and `colorama = "<0.4,>=0.3"`.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.8.13'`

Pipenv location: `'/tmp/pipenv-example/venv/lib/python3.6/site-packages/pipenv'`

Python location: `'/tmp/pipenv-example/venv/bin/python'`

Python installations found:
  - `3.6.5`: `/tmp/pipenv-example/venv/bin/python3`
  - `3.6.5`: `/tmp/pipenv-example/venv/bin/python3.6`
  - `3.6.5`: `/usr/bin/python3.6`
  - `3.6.5`: `/usr/bin/python3.6m`
  - `3.5.3`: `/usr/bin/python3.5`
  - `3.5.3`: `/usr/bin/python3`
  - `3.5.3`: `/usr/bin/python3.5m`
  - `2.7.13`: `/usr/bin/python2`
  - `2.7.13`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.9.0-12-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Thu Jan 2 14:36:58 EST 2020',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `ROSVER`
  - `LC_ALL`
  - `NVM_DIR`
  - `SSH_CONNECTION`
  - `LANG`
  - `TZ`
  - `HISTCONTROL`
  - `OLDPWD`
  - `EDITOR`
  - `NVM_CD_FLAGS`
  - `CONMAN_HOST`
  - `SSH_AUTH_SOCK`
  - `VIRTUAL_ENV`
  - `XDG_SESSION_ID`
  - `USER`
  - `PAGER`
  - `MODULE_VERSION`
  - `LC_COLLATE`
  - `GOPATH`
  - `SVNROOT_NONATL`
  - `PWD`
  - `HOME`
  - `GOROOT`
  - `HUGETLB_NO_PREFAULT`
  - `LC_TERMINAL`
  - `SSH_AGENT_PID`
  - `SSH_CLIENT`
  - `TMUX`
  - `HUGETLB_MORECORE`
  - `LC_TERMINAL_VERSION`
  - `TMPDIR`
  - `LOADEDMODULES`
  - `SSH_TTY`
  - `MAIL`
  - `NVM_RC_VERSION`
  - `TERM`
  - `SHELL`
  - `TMUX_PANE`
  - `SHLVL`
  - `MANPATH`
  - `VALGRIND_OPTS`
  - `BLOCKSIZE`
  - `MODULEPATH`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `MODULE_VERSION_STACK`
  - `PATH`
  - `PS1`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/tmp/pipenv-example/venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/sbin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `vi`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/tmp/pipenv-example`
  - `VIRTUAL_ENV`: `/tmp/pipenv-example/venv`

---------------------------

Contents of `Pipfile` ('/tmp/pipenv-example/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
colorama = "<0.4,>=0.3"

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/tmp/pipenv-example/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "5d287e8624041758e8cf15f04ffe9387fdd2412df13e935f60620640aad2f6dc"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "colorama": {
            "hashes": [
                "sha256:463f8483208e921368c9f306094eb6f725c6ca42b0f97e313cb5d5512459feda",
                "sha256:48eb22f4f8461b1df5734a074b57042430fb06e1d61bd1e11b078c0fe6d7a1f1"
            ],
            "index": "pypi",
            "version": "==0.3.9"
        }
    },
    "develop": {}
}

```
</details>

**Comment by fabi125** [comment]
While doing some debugging for this, I noticed the same behaviour can be observed when using `pipenv install 'colorama>=0.3,<0.4'`, which will sometimes result in `colorama = ">=0.3,<0.4"` and sometimes in `colorama = "<0.4,>=0.3"`.

**Comment by matteius** [comment]
@fabi125 Please recheck with `pipenv==2022.1.8`

**Comment by fabi125** [comment]
Thanks for the nudge.
I just played around with this again using the new pipenv version and was unable to reproduce it. Gonna close this out, thanks!
