### ISSUE TITLE
Pipenv lock still takes way too long to complete

### ISSUE THREAD

**Issue by mjpieters** [pypa/pipenv#4430]
`pipenv lock` is still taking up to 30 minutes to complete for my medium-sized project.

While #4403 was closed as fixed and indeed no full tree copies are made any more, `pipenv lock` is still unworkably slow. What used to take 50 seconds under `2018.11.26`, now takes 30 minutes to figure out that nothing changed:

```
$ export PIPENV_INSTALL_TIMEOUT=10000
$ cp Pipfile.lock Pipfile.lock.before
$ time pipenv lock
Locking [dev-packages] dependencies…
Building requirements...
Resolving dependencies...
✔ Success!
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
✔ Success!
Updated Pipfile.lock (0e1198)!

real	29m19.701s
user	28m39.300s
sys	4m8.222s
$ diff -su Pipfile.lock.old Pipfile.lock
Files Pipfile.lock.old and Pipfile.lock are identical
```

This is making it untenable to keep using Pipenv.

Full [`pipenv lock -v` output in a gist](https://gist.github.com/mjpieters/715b825a5fded073adc2945d802f5177).

Pipfile:

```ini
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
flake8 = "*"
flake8-bugbear = "*"
black = "==19.10b0"
pre-commit = "*"
pytest = "*"
pytest-cov = "*"

[packages]
project-name = {editable = true,path = "."}
"zc.buildout" = "*"

[requires]
python_version = "3.6"
```

where `project-name` (redacted name) lists the following `install-requires` lines:

```ini
install_requires =
    apache-airflow[aws,celery,postgres,redis] >= 1.10.11
    airflow_multi_dagrun
    airflow-prometheus-exporter
```

-----------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.8.13'`

Pipenv location: `'/usr/local/Cellar/pipenv/2020.8.13/libexec/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2020.8.13/libexec/bin/python3.8'`

Python installations found:

  - `3.9.0`: `/Users/mj/bin/python3.9`
  - `3.8.5`: `/usr/local/bin/python3`
  - `3.8.5`: `/usr/local/bin/python3.8`
  - `3.8.3`: `/Users/mj/bin/python3.8`
  - `3.7.7`: `/Users/mj/bin/python3.7`
  - `3.7.6`: `/opt/miniconda3/bin/python3`
  - `3.7.6`: `/opt/miniconda3/bin/python3.7m`
  - `3.7.6`: `/opt/miniconda3/bin/python3.7`
  - `3.7.3`: `/Users/mj/.pyenv/versions/3.7.3/bin/python3`
  - `3.6.10`: `/Users/mj/bin/python3.6`
  - `3.6.1`: `/Users/mj/bin/pypy3`
  - `3.5.9`: `/Users/mj/bin/python3.5`
  - `3.4.10`: `/Users/mj/bin/python3.4`
  - `3.3.7`: `/Users/mj/bin/python3.3`
  - `3.2.6`: `/Users/mj/bin/python3.2`
  - `2.7.18`: `/Users/mj/bin/python2.7`
  - `2.7.16`: `/usr/bin/python2.7`
  - `2.6.9`: `/Users/mj/bin/python2.6`
  - `2.5.6`: `/Users/mj/bin/python2.5`
  - `2.4.6`: `/Users/mj/bin/python2.4`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.7.0: Wed May 27 17:00:02 PDT '
                     '2020; root:xnu-4570.71.80.1~1/RELEASE_X86_64',
 'python_full_version': '3.8.5',
 'python_version': '3.8',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `AUTOJUMP_ERROR_PATH`
  - `NVM_INC`
  - `TERM_PROGRAM`
  - `GIT_PROMPT_END`
  - `rvm_bin_path`
  - `AUTOJUMP_SOURCED`
  - `GEM_HOME`
  - `NVM_CD_FLAGS`
  - `SHELL`
  - `TERM`
  - `HISTSIZE`
  - `TMPDIR`
  - `COPYFILE_DISABLE`
  - `IRBRC`
  - `Apple_PubSub_Socket_Render`
  - `CONDA_SHLVL`
  - `PERL5LIB`
  - `TERM_PROGRAM_VERSION`
  - `CONDA_PROMPT_MODIFIER`
  - `TERM_SESSION_ID`
  - `MY_RUBY_HOME`
  - `PERL_MB_OPT`
  - `LC_ALL`
  - `USER`
  - `HISTFILESIZE`
  - `NVM_DIR`
  - `COMMAND_MODE`
  - `CONDA_EXE`
  - `rvm_path`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `PTPIMG_API_KEY`
  - `_CE_CONDA`
  - `rvm_prefix`
  - `_`
  - `CONDA_PREFIX`
  - `PWD`
  - `HOMEBREW_GITHUB_API_TOKEN`
  - `EDITOR`
  - `LANG`
  - `ITERM_PROFILE`
  - `PYTHONSTARTUP`
  - `XPC_FLAGS`
  - `ITERM_ORIG_PS1`
  - `XPC_SERVICE_NAME`
  - `HISTCONTROL`
  - `_CE_M`
  - `FIGNORE`
  - `rvm_version`
  - `COLORFGBG`
  - `HOME`
  - `SHLVL`
  - `LC_TERMINAL_VERSION`
  - `ITERM_PREV_PS1`
  - `ITERM_SESSION_ID`
  - `PERL_LOCAL_LIB_ROOT`
  - `LOGNAME`
  - `CONDA_PYTHON_EXE`
  - `LC_CTYPE`
  - `GEM_PATH`
  - `GIT_PROMPT_ONLY_IN_REPO`
  - `CONDA_DEFAULT_ENV`
  - `NVM_BIN`
  - `DISPLAY`
  - `LC_TERMINAL`
  - `HGSRC`
  - `SECURITYSESSIONID`
  - `RUBY_VERSION`
  - `PERL_MM_OPT`
  - `COLORTERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2020.8.13/libexec/tools:/usr/local/google-sdks/google-cloud-sdk/bin:/Users/mj/perl5/bin:/Users/mj/.nvm/versions/node/v12.14.1/bin:/Users/mj/.rvm/gems/ruby-2.3.0/bin:/Users/mj/.rvm/gems/ruby-2.3.0@global/bin:/Users/mj/.rvm/rubies/ruby-2.3.0/bin:/opt/miniconda3/bin:/opt/miniconda3/condabin:/Users/mj/bin:/Users/mj/Development/Library/zopatista_setup/bin:/Users/mj/Development/Library/zopatista_setup/audio:/usr/local/Cellar/ruby/2.7.1_2/bin:/Users/mj/.cargo/bin:/Users/mj/.poetry/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/usr/local/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/mj/.local/bin:/Users/mj/.rvm/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `vim`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/mj`

---------------------------

</details>

**Comment by conradg** [comment]
Thanks for raising this @mjpieters, thought we were going crazy. Downgrading to `2018.11.26` speeds things up massively for us too.

**Comment by witsch** [comment]
> Thanks for raising this @mjpieters, thought I was going crazy. Downgrading to `2018.11.26` speeds things up massively for me too

Yes, +1! Thanks for looking into this, Martijn!  We had exactly the same issue (lots of big tmp directories), but sorta gave up for the time being… I couldn't really argue much when `pipenv lock` took 10+ minutes for simply adding another package.

(and hi, btw 👋)

**Comment by mgmarino** [comment]
A "workaround" that may work (and what we have used from time to time) is to remove the lock file and rerun the lock.  This may also hint at the underlying problem, which may have something to do with how pipenv is using the existing lock file during the lock process.

**Comment by Can-Sahin** [comment]
Deleting the `Pipfile.lock` speeds things up for sure. I just install all the packages from scratch and run `pipenv lock` without changing anything and it gets stuck eventhough there is no change at all

**Comment by frostming** [comment]
Can you have a try on the master branch? I recently disabled the copying of the local source tree.

**Comment by mjpieters** [comment]
> Can you have a try on the master branch? I recently disabled the copying of the local source tree.

Do you mean #4421? That's been [part of the 2020.8.13 release](https://github.com/pypa/pipenv/commit/9299ae1f7353bdd523a1829f3c7cad0ee67c2e3b) that I tested with for this issue. I did note that the tree copying no longer takes place.

I also don't see any changes on master since 2020.8.13 was released that look relevant. Did I miss something?

**Comment by frostming** [comment]
If I remember correctly, 2018.11.26 didn't resolve transient dependencies of an editable package. You can compare the lock files generated by both versions.

**Comment by mjpieters** [comment]
> If I remember correctly, 2018.11.26 didn't resolve transient dependencies of an editable package. You can compare the lock files generated by both versions.

I see no differences that look problematic. With `2020.8.13.dev0` (master branch) I see `markers` entries added. The dependencies I see added are ones that were due to other dependencies having been upgraded (I deleted the lock file to see if there was much speed difference).

With the lock file deleted and using `2020.8.13.dev0`, a `pipenv lock` took 10 minutes.

**Comment by frostming** [comment]
I removed all other dependencies except the editable one. It turns out no significant difference is seen in the time costs of 2018.11.26 and 2020.8.13. It will be great if you can narrow down which package brings the performance degrading.

I created a demo repo to showcase the issue, which you can clone and adjust to reproduce the performance issue:
https://github.com/frostming/pipenv-lock-performance

```bash
$ docker build . --build-arg PIPENV_VER=2020.8.13 -t pipenv-bug
$ docker build . --build-arg PIPENV_VER=2018.11.26 -t pipenv-bug
```

**Comment by mjpieters** [comment]
Sorry, I meant to get back to this but current project work is keeping me over-utilised. I do still find Pipenv to be excruciatingly slow, and regularly have to delete the lock file just to get a solution, but that's not really very actionable feedback.

**Comment by alexandrerays** [comment]
I'm having this problem in February 2021. Even deleting lock file, it is still very slow.

**Comment by tombohub** [comment]
Same here, deleting lock file doesn't help

**Comment by GiuseppeLaurenza** [comment]
same here, there are any news?

**Comment by Eortvald** [comment]
same here

**Comment by Real-Gecko** [comment]
Version **2020.11.15**, does not take half an hour for me, but couple of minutes is too much for creating 40 KiB JSON file.

**Comment by bingo4508** [comment]
Why pipenv why so slow? Why?

**Comment by Nytelife26** [comment]
This issue is still present in April of 2021. I have yet to look into why this is, but I know it doesn't *have* to be this way because there are other managers that work better and faster.

For instance, I recommend using Poetry until this is fixed.
I know it seems counter-intuitive and disrespectful to recommend another project, but as of the present moment, the speed of pipenv makes it unusable, and I'd rather put an alternative on the table than leave people to wait.

**Comment by Real-Gecko** [comment]
I did not investigate the code, but I think it happens because on every run `Pipenv` checks for updates even though no one asks for this, thus it makes a lot of queries, calculates a lot of hashes for `Pipfile.lock` etc. So the bigger your `.venv` is the worse things get. For example right now I installed one package, but instead of just installing it and it's dependency `Pipenv` also updated three packages. As I already had **101** packages installed you can imagine the process was quite time consuming.

![image](https://user-images.githubusercontent.com/2231969/115654657-63fbee00-a353-11eb-9755-fdb8f70485dd.png)

**Comment by CharString** [comment]
On 22 April 2021 02:53:29 CEST, Tyler J Russell ***@***.***> wrote:
>This issue is still present in April of 2021. I have yet to look into
>why this is, but I know it doesn't *have* to be this way because there
>are other managers that work better and faster.
>
>For instance, I recommend using Poetry until this is fixed.

Or have a look at pdm. You can make it use venvs instead of __pypackages__, if you want. And it can import your Pipfile.
-- 
Chris Wesseling
Centrum Wiskunde & Informatica (CWI) 
https://www.cwi.nl/people/ccw

**Comment by Nytelife26** [comment]
> Or have a look at pdm. You can make it use venvs instead of
> __pypackages__, if you want. And it can import your Pipfile.

Interesting. I'll take a look later. I like Poetry, though, because it
addresses another issue I noticed with pipenv - it uses a standard from
PEP 518 that's likely to work with other toolchains (`pyproject.toml` as
opposed to `Pipfile`).

**Comment by Nytelife26** [comment]
> ![image](https://user-images.githubusercontent.com/2231969/115654657-63fbee00-a353-11eb-9755-fdb8f70485dd.png)

Interestingly enough, that's actually the same with package managers from other ecosystems, `npm`, `yarn`, etc, all update the lockfile when you install the project unless you specify otherwise. They shouldn't, but it proves a point - it doesn't have to be this painfully slow at all.

**Comment by Real-Gecko** [comment]
The biggest problem IMO is this spinner:
![image](https://user-images.githubusercontent.com/2231969/115702170-6af22300-a38a-11eb-98d9-a94229cc044d.png)
It's not really informative, one cannot tell exactly what's exactly going on right now. What if I have network problems and Pipenv experiences request timeouts? I wouldn't know, because all progress is hidden behind spinner.

**Comment by felix-ht** [comment]
just move to poetry - faster locks overall better performance

**Comment by Nytelife26** [comment]
> just move to poetry

That's not really constructive at all. It's better to work on helping people here. I only suggested it as a temporary solution so people don't have to deal with the hassle while they wait for a fix.

You wouldn't walk into Google's headquarters and tell everyone to "just use DuckDuckGo", would you? It's basic respect.

**Comment by Real-Gecko** [comment]
I bet it'll be network, sending requests to check for updates, checking dependencies for updates, downloading updates etc. Maybe if output would be more verbose we would pinpoint problem quicker.

**Comment by mgmarino** [comment]
> I'll be running tests later. I think the best way to resolve this is to time each stage of the lock and see which ones take the longest so we can determine where the problem comes from and attempt to fix it.

@Nytelife26 A thanks-in-advance for this.  As this issue is closed, I think it'd be helpful to perhaps post the results of your efforts in one or more new issues.  Here's hoping you'll find something actionable that the maintainers (or we in the community) can do to improve the situation.

**Comment by Nytelife26** [comment]
> I bet it'll be network

I do highly doubt that. Other package management software for other
ecosystems do the same thing, but lightyears faster. Unless pipenv uses
a dinosaur of a networking system, it seems unlikely.

> if output would be more verbose we would pinpoint problem quicker
The output alone isn't useful - we need to know the timing. We do
already have a sample of verbose output, though, from earlier on in this
issue.

**Comment by Nytelife26** [comment]
> A thanks-in-advance for this.

That's absolutely fine. Always happy to help.

> post the results [...] in one or more new issues.

Good idea, unless we can attract maintainer attention to get this
reopened.

**Comment by CharString** [comment]
>  but lightyears faster. 

When we report the timing in our verbose output, we should use units of time; lightyears are a unit of distance (as are parsecs Han Solo)

**Comment by Real-Gecko** [comment]
> > but lightyears faster.
> 
> When we report the timing in our verbose output, we should use units of time; lightyears are a unit of distance (as are parsecs Han Solo)

If you have nothing constructive to say, it's better to stay quite.

**Comment by Nytelife26** [comment]
> If you have nothing constructive to say, it's better to stay quite.

No need to be rude. I appreciated the humour honestly - we're engineers,
not lawyers, we're allowed to be funny. You'd love some of the original
UNIX design documents, developers have a real history of messing around.

Anyways, yes, I'll be reporting the timings here in seconds, not
lightyears.

```
requirements.txt found, instead of Pipfile! Converting...
✘ Failed... 
Warning: Your Pipfile now contains pinned versions, if your
requirements.txt did. 
We recommend updating your Pipfile to specify the "*" version, instead.
Pipfile.lock not found, creating...
start - 7.152557373046875e-07
keep outdated - 8.58306884765625e-05
cleanup lockfile - 0.0009396076202392578
inherit dev - 0.009583711624145508
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
resolve deps - 13.933054447174072
Updated Pipfile.lock (ac73fc)!
overwrite dev - 13.93443512916565
Installing dependencies from Pipfile.lock (ac73fc)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 38/38 — 00:00:15
```

For some strange reason it isn't as slow on my machine anymore, only
around 30 seconds. However, the bulk of the time is most definitely
spent resolving and installing dependencies (in my testing, anyone else
should feel free to verify this on a machine where performance is still
poor) - and I'm not sure how easy it'll be to improve that.

**Comment by Real-Gecko** [comment]
Here's the `Pipfile` from my current project:
 
```ini
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
boto3 = "*"
celery = "*"
django = "*"
django-allauth = "*"
django-bootstrap4 = "*"
django-environ = "*"
django-filter = "*"
django-ical = "*"
django-icons = "*"
django-import-export = "*"
django-logentry-admin = "*"
django-menu-generator = "*"
django-modeltranslation = "*"
django-money = "*"
django-pandas = "*"
django-phonenumber-field = "*"
django-redis = "*"
django-rest-auth = "*"
django-reverse-admin = "*"
django-storages = "*"
django-suit = {editable = true, git = "https://github.com/darklow/django-suit.git"}
django-tables2 = "*"
django-vies = "*"
django-widget-tweaks = "*"
djangorestframework = "*"
drf-yasg = "*"
fcm-django = "*"
gunicorn = "*"
monthdelta = "*"
pandas = "*"
phonenumbers = "*"
pillow = "*"
psycopg2-binary = "*"
pymsteams = "*"
redis = "*"
rules = "*"
slack-sdk = "*"
whitenoise = "*"

[dev-packages]
argh = "*"
bpython = "*"
coverage = "*"
django-debug-toolbar = "*"
django-extensions = "*"
flower = {editable = true, git = "https://github.com/mher/flower.git"}
watchdog = "*"

[requires]
python_version = "3.8"
```

In the beginning it was relatively fast too, but as the number of packages grew locking became slower. Currently it's around ~4 minutes.

**Comment by tombohub** [comment]
I am using WSL on windows and it was taking literally half an hour or so to finish with locking

**Comment by Real-Gecko** [comment]
How can I run `Pipenv` with timings?

**Comment by Nytelife26** [comment]
> How can I run `Pipenv` with timings?

You have to modify the `do_lock` function in `core.py` in the root
package directory to print a `time.time()` between calls.

It's a bit of a hacky solution, but as far as I'm aware pipenv has no
built in profiling.

**Comment by mgmarino** [comment]
pipenv spawns a number of subprocesses during the lock, does this take any of that into account?

**Comment by Nytelife26** [comment]
> pipenv spawns a number of subprocesses during the lock, does this take
> any of that into account?

It'll time exactly as long as each step takes to complete. Does it run
the `do_lock` in worker threads, or spawn the worker threads from
`do_lock`? I couldn't tell when I looked.

**Comment by Real-Gecko** [comment]
I've found the way to profile `pipenv install`, take a look at [this repo](https://github.com/Real-Gecko/pipenv-profile) for instructions. The result is `*.calltree` file which can be opened [kcachegrind](https://kcachegrind.github.io/html/Home.html). I' totally do not understand how to interpret this results, but I'm sure someone can figure it out.

![image](https://user-images.githubusercontent.com/2231969/116984891-94497200-aced-11eb-9b25-1edacac08bf9.png)

**Comment by Nytelife26** [comment]
> I've found the way to profile `pipenv install`

Marvellous. Thank you.

I'll investigate later - although, at a glance, the presence of
time.sleep is interesting.

**Comment by mjpieters** [comment]
> I'll investigate later - although, at a glance, the presence of time.sleep is interesting.

I'm pretty sure that those are inside `pexpect`, used to monitor each `pip` process spawned. It just means that there is a lot of waiting around for those processes.

**Comment by mjpieters** [comment]
Yup, it's the vendored pexpect wait loop. `expect_loop()` function definition:

https://github.com/pypa/pipenv/blob/275f7e151eb0aa17702215165a371df7da9ad476/pipenv/vendor/pexpect/expect.py#L153-L184

and `self.spawn.delayafterread` is set to 0.0001 to release the GIL:

https://github.com/pypa/pipenv/blob/275f7e151eb0aa17702215165a371df7da9ad476/pipenv/vendor/pexpect/spawnbase.py#L72-L77

Note that there's no point in setting it to `None` here, as it is not pexpect that is the problem. It's the pip subprocess, which hasn't been profiled.

**Comment by gshpychka** [comment]
Help me understand - is this acknowledged and are there plans to address this?

**Comment by Luca-Terrazzan** [comment]
Same problem for me; locking is so slow that we are currently within the very dangerous situation of avoiding to update the lockfile whenever possible to avoid losing hours of waiting times

**Comment by trallnag** [comment]
To all the people thinking that Poetry is the answer and is perfectly fast in all cases: You are wrong. Both Pipenv and Poetry are having these issues partly due to the nature how dependency management works / does not work in Python.

**Comment by Real-Gecko** [comment]
> To all the people thinking that Poetry is the answer and is perfectly fast in all cases: You are wrong. Both Pipenv and Poetry are having these issues partly due to the nature how dependency management works / does not work in Python.

Totally agree, with lot's of dependencies it's slow too.

**Comment by khimaros** [comment]
anecdotally, switching my medium sized project to poetry solved all of my performance issues.

**Comment by tbrodbeck** [comment]
For some reason locking pandas takes soooo long in my project. I even activated verbose mode, but it does not give me any information what it is doing, still... (found another "closed" issue: https://github.com/pypa/pipenv/issues/1198)
```
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
Reporter.starting()
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.starting()
Reporter.adding_requirement(SpecifierRequirement('rpi.gpio'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('rpi.gpio'), None)
Reporter.adding_requirement(SpecifierRequirement('pytest'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('pytest'), None)
Reporter.adding_requirement(SpecifierRequirement('pyyaml'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('pyyaml'), None)
Reporter.adding_requirement(SpecifierRequirement('pyinstaller'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('pyinstaller'), None)
Reporter.adding_requirement(SpecifierRequirement('pandas'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('pandas'), None)
⠼ Locking...
```
Is the only solution to switch to poetry now?

**Comment by matteius** [comment]
@tbrodbeck What version are you on?  Can you try the branch linked off this issue?  https://github.com/pypa/pipenv/issues/4926

**Comment by CharString** [comment]
@tbrodbeck I thinks it's bad taste to advocate another project here. So try the different branch. But there are alternatives to poetry, like pdm.

**Comment by tbrodbeck** [comment]
@matteius I am on version 2022.1.8 and Python 3.9.2

I tried to switch to the last branch mentioned, but I cannot access it:
```
fatal: invalid reference: issues-4651-infiite-iteration-take4
```

**Comment by matteius** [comment]
@tbrodbeck  I am sorry for I should have been more clear that its this passing branch with the pip 22.0.4 vendoring changes:  https://github.com/pypa/pipenv/pull/4969

**Comment by tbrodbeck** [comment]
I think you would need to provide me some installation instructions. I was not able to install the branch with `python3 setup.py install` or `sudo python3 setup.py install`

**Comment by matteius** [comment]
@tbrodbeck Hmmm, I seem to recall having issues with the install command as well, so I have been installing it using `python3 setup.py develop --user` to install it at user level which is preferred, if you need it at a system level you can drop the --user flag.

**Comment by tbrodbeck** [comment]
Hmm I am still getting permission denied:
```
t@v2:~/pipenv $ python3 setup.py develop --user
running develop
/home/t/.local/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/t/.local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
error: [Errno 13] Permission denied
```

**Comment by matteius** [comment]
@tbrodbeck I'd rather not ping all these people with each update -- perhaps make a new issue report and we can discuss more.   I suspect you need to `pip uninstall pipenv` first if you are getting a permission denied trying to install to `--user` location, like its already installed there.

**Comment by em1208** [comment]
Pipenv unfortunately it is terribly slow in my case. Locking is taking more than 30min and still has not completed. 
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[requires]
python_version = "3.7"

[packages]
Babel = ">=2.5"
bleach = "<3.0"
"boto3" = "<=1.9.183"
Django = ">=1.11,<=2.2.28"
dj_database_url = ">=0.3.0"
dj_email_url = ">=0.0.4"
django-babel = ">=0.6.1"
django-bootstrap4 = ">=0.0.4"
django-cache-url = ">=1.0.0"
django-countries = ">=5.2"
django-filter = ">=2.0"
django-graphql-jwt = ">=0.1.13,<=0.2.1"
pyjwt= "==1.7.1"
django-impersonate = ">=1.3"
django-measurement = "==3.0.0"
django-mptt = ">=0.7.1"
django-phonenumber-field = ">=1.3.0,<3.0"
django-prices = ">=1.0.2, <2.0"
django-prices-openexchangerates = ">=1.0.0"
django-prices-vatlayer = ">=1.0.2"
django-redis = ">=4.0.0"
django-storages = {extras = ["google"],version = "*"}
django-templated-email = ">=2.2.0"
django-versatileimagefield = ">=1.10"
django-webpack-loader = ">=0.3.0,<=0.6.0"
django-elasticsearch-dsl = ">=0.5.0.<0.6.0"
django-recaptcha = "<2.0.0"
django-silk = "==2.0.0"
django-debug-toolbar = "*"
django-debug-toolbar-request-history = "*"
django-extensions = "*"
ipython = "*"
elasticsearch = "==6.3.1"
elasticsearch-dsl = ">=6.0.0,<6.1.0"
faker = ">=0.7.7"
freezegun = ">=0.3.9"
google-measurement-protocol = ">=1.0.0"
"google-i18n-address" = ">=2.3.0"
graphene-django = ">=2.2,<=2.3.2"
Markdown = ">=2.4,<=3.1.1"
maxminddb = "*"
"maxminddb-geolite2" = "*"
phonenumberslite = ">=8.10.10"
prices = ">=1.0.0"
"psycopg2-binary" = ">=2.7,<=2.8.6"
purl = ">=0.4.1"
raven = "==6.9.0"
requests = ">=1.2.0"
social-auth-app-django = ">=2.0.0"
text-unidecode = "*"
uwsgi = {version = ">=2.0.0",platform_system = "!= 'Windows'"}
celery = {version = ">=4.3",extras = ["redis"]}
redis = "<4.0"
kombu = "<5.0.0"
weasyprint = ">=0.42.2"
graphene-django-optimizer = ">=0.4.0,<=0.4.2"
braintree = "==3.49.0"
razorpay = ">=1.1.1"
stripe = "*"
"urllib3" = "*"
dataclasses = {version = "*",markers = "python_version < '3.7'"}
django-contact-form = "*"
whitenoise = {extras = ["brotli"],version = "*"}

[dev-packages]
pytest = "*"
pytest-django = "*"
pytest-django-queries = "*"
pytest-vcr = "*"
pytest-mock = "*"
pytest-xdist = "*"
pylint-django = "*"
coverage = "*"
pytest-cov = "*"
codecov = "*"
tox = "*"
pycodestyle = "*"
pydocstyle = "*"
pylint = "*"
pylint_celery = "*"
isort = "*"
yapf = "*"
pylint-plugin-utils = "*"
transifex-client = "*"
black = "==19.3b0"
pre-commit = "*"
flake8 = "*"
```

I'm using pipenv, version 2022.4.8. Any suggestion how to solve this issue would be much appreciated.

**Comment by leirons** [comment]
I have more than 120 packages and it took about 1 hour, i thought the problem in me, but i was wrong, it's awfull use it in this state

**Comment by matteius** [comment]
@leirons Are you locking against pypi or a private package server?

**Comment by matteius** [comment]
@em1208 I just tried your example from within my Ubuntu VirtualBox VM (which is slower than my native machine) and it took 4.5 minutes.   `pipenv, version 2022.8.5`

```
✔ Success! 
Updated Pipfile.lock (555f96)!

real	4m34.679s
user	3m21.142s
sys	0m8.162s
```

**Comment by matteius** [comment]
I am locking this discussion of this old and closed issue, and I am once again asking that if you are having a new issue that you don't respond to an old closed issue report with minimal details -- please open a new issue report and follow the template.  

It is highly likely that your comment could be missed responding to an old issue as well, because we actively prioritize and tag new issues as they come in.
