### ISSUE TITLE
Pipenv NOT expanding environment variables in [[source]]. Not been able to install a library from private pypi

### ISSUE THREAD

**Issue by bkemmer** [pypa/pipenv#4452]
### Issue description

When I add a source for our private pypi it can't be found:
```
[[source]]
url = "https://$VAR_ID:${VAR_KEY}@my_pypi_path/simple"
verify_ssl = true
name = "some_name"
```
I receive multiple errors like these:
```
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches my_lib (from -r /var/folders.../pipenv...requirements/pipenv-...-constraints.txt (line 5))
No versions found
Were https://pypi.org/simple or https://${VAR_ID}:${VAR_KEY}@my_pypi_path/simple reachable?
```

However, if I add the environments variables in the command it works:
```
env  VAR_ID=my_ID VAR_KEY=my_key pipenv install -v
```

My full Pipfile is like this:
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[[source]]
url = "https://$VAR_ID:${VAR_KEY}@my_pypi_path/simple"
verify_ssl = true
name = "some_name"

[packages]
...list of packages...
a_local_lib = {editable = true, path = "."}
my_lib = {index = "some_name", version = "1.0"}
```

And I have these variables in the .env file. If I run `pipenv run python -c "import os; print(os.environ['VAR_ID'])"` they are printed.

pipenv --version
`pipenv, version 2020.8.13`
python 3.7.8
Macos

### Expected result

I shouldn't be required to set the environment manually as described in the [documentation](https://pipenv-fork.readthedocs.io/en/latest/advanced.html#injecting-credentials-into-pipfiles-via-environment-variables).

**Comment by frostming** [comment]
You can't put env vars of the **setup** stage in `.env` file. It only holds **running** stage variables.

There have been many discussions about the idea of extending the usage of `.env` file already.
