### ISSUE TITLE
dotenv override v2

### ISSUE THREAD

**Issue by eltbus** [pypa/pipenv#4459]
After trying to set some system env vars from using **_.env_**, I believe issue [638](https://github.com/pypa/pipenv/issues/638) decided to remove dotenvs override=True (which was good).

However, working with PySpark, I'd love to be able to point to specific versions of _JAVA_HOME_, _SPARK_HOME_, or even refer to the current virtual python itself.

Currently I have a script do the following:
`JAVA_HOME=/usr/... ; SPARK_HOME=/opt/... ; PYSPARK_HOME=$(which python) ; python`

I feel an option would be more elegant, specially when many system env vars are overriden.

Something that works like this?
`pipenv shell --override-envs=True`
or this
`pipenv shell -o`

**Comment by frostming** [comment]
The default behavior is to override, and there is an env var `PIPENV_DONT_LOAD_ENV` so that when it is set, `.env` won't be loaded

**Comment by eltbus** [comment]
But is this behaviour I'm getting expected?

**.env file:**
```
<user>@<host>:~/<path>$ cat .env
SPARK_HOME=/opt/data/spark-3.0.1-bin-hadoop2.7
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
```
**Current system env vars**
```
<user>@<host>:~/<path>$ printf "$JAVA_HOME\n$SPARK_HOME\n"
/home/<user>/.sdkman/candidates/java/current
/opt/data/spark-2.4.4-bin-hadoop2.7
```
Notice **spark-3.0.1** vs **spark-2.4.4**

**Start pipenv shell:**
```
<user>@<host>:~/<path>$ pipenv shell
Loading .env environment variables…
Launching subshell in virtual environment…
 . /home/<user>/.local/share/virtualenvs/<path>-IaDJX8DR/bin/activate
<user>@<host>:~/<path>$  . /home/<user>/.local/share/virtualenvs/<path>-IaDJX8DR/bin/activate
```
**Pipenv shell vars**
```
(<path>) <user>@<host>:~/<path>$ printf "$JAVA_HOME\n$SPARK_HOME\n"
/home/<user>/.sdkman/candidates/java/current
/opt/data/spark-2.4.4-bin-hadoop2.7
(<path>) <user>@<host>:~/<path>$
```

**Comment by frostming** [comment]
Do you write the env vars in bashrc file? if so, it is expected.

Load dotenv(override=True) -> Launch shell -> execute bashrc

**Comment by eltbus** [comment]
SPARK_HOME is explicitly set, and JAVA_HOME appears to be set from a sourced os a sourced script starting from "/home/<user>/.sdkman/bin/sdkman-init.sh" which came as default for my distribution (Lubuntu).

I'll see if I can safely remove the latter without breaking anything. However, wouldn't it be better for the .env file to be loaded after .bashrc? It would certainly be easier.

Thank you for everything @frostming!  For my part, I consider this closed.
