### ISSUE TITLE
pipenv sync changes Pipfile.lock

### ISSUE THREAD

**Issue by pjboro** [pypa/pipenv#4460]
I checked the issues, but found nothing similar. I used the pipenv included in Ubuntu Eoan

### Issue description
I added 1 dependency to the Pipfile, but left Pipfile.lock untouched. 
`pipenv sync` changes `Pipfile.lock`

### Expected result

`Pipfile.lock` is left untouched when running `pipenv sync`. pipenv installs packages described in Pipfile.lock, as described in the docs. 

### Actual result

`Pipfile.lock` was changed

### Steps to replicate
relevant part of dockerfile:
```
FROM ubuntu:eoan

RUN apt update \
    && apt install -y --no-install-recommends \
      'python3=3.7.5-1' \
      'pipenv=11.9.0-1' \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV APP_DIR=/usr/src/app
RUN mkdir -p ${APP_DIR}
WORKDIR ${APP_DIR}

COPY Pipfile* ${APP_DIR}/

# Pipfile.lock should be present in git repository - it should not be generated in CI/CD
# We generate Pipfile.lock inside the container if PIPENV_LOCK is set to non-empty string
ARG PIPENV_LOCK
RUN md5sum Pipf*
RUN if [ -n "$PIPENV_LOCK" ] ; then pipenv lock --verbose ; fi
RUN chmod a-w ./Pipfile.lock
RUN md5sum Pipf*
RUN pipenv sync --verbose
RUN md5sum Pipf*
RUN pipenv --support

```
commands run in the directory containing the dockerfile
```
docker build -t project . && \
  id=$(docker create project) && \
  docker cp $id:/usr/src/app/Pipfile ./Pipfile && \
  docker cp $id:/usr/src/app/Pipfile.lock ./Pipfile.lock && \
  docker rm -v $id && \
  git add Pipfile Pipfile.lock
```

-------------------------------------------------------------------------------

I'm attaching the output of the commands: 
[pipenv.log](https://github.com/pypa/pipenv/files/5203480/pipenv.log)

I believed pipenv will enable me to be sure I've installed the same packages, with the same hashes. In reality `pipenv sync` changes the file it is supposed to read from. Some parameters described in the docs does not work. Is this production ready? How does this make sure packages' hashes haven't change if the file containing the hashes was changed itself?

**Comment by frostming** [comment]
It seems you are using an old release version (11.9.0)which is 2+ years ago. Please try the latest release.

**Comment by pjboro** [comment]
Yep. After installing the latest stable with pip everything is fine. Sorry to bother you and thank you so much for help!
