### ISSUE TITLE
pipfile is not updating

### ISSUE THREAD

**Issue by myounus96** [pypa/pipenv#4463]
Hi there, I have a use case, I've created a project and did `pipenv shell` in that, then I wanna use this environment for other projects as well, for that I copied the environment path using `pipenv --venv` then in the desired second project I just did `source {pasting the output of last command}/bin/activate` so now I've activated the environment of first project in second project. Now When I am installing anything with `pipenv install {any package}` it creates(pipfile) in second project , but the pipfile in first project is not updated even I go in first project folder and trying using `pipenv install`, `pipenv update`, `pipenv lock`. Is there any solution/workaround for this problem and better if pipfile is not created in second project and just updated in first project whenever I install new package.
Thanks

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.8.13'`

Pipenv location: `'/home/myounus/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.8.4`: `/home/myounus/.pyenv/versions/3.8.4/bin/python3.8`
  - `3.8.3`: `/home/myounus/.pyenv/versions/3.8.3/bin/python3.8`
  - `3.8.2`: `/home/myounus/.pyenv/versions/3.8.2/bin/python3.8`
  - `3.8.1`: `/home/myounus/.pyenv/versions/3.8.1/bin/python3.8`
  - `3.8.0`: `/home/myounus/.pyenv/versions/3.8.0/bin/python3.8`
  - `3.7.4`: `/home/myounus/.pyenv/versions/3.7.4/bin/python3.7`
  - `3.6.9`: `/usr/bin/python3.6`
  - `3.6.9`: `/usr/bin/python3.6m`
  - `3.6.9`: `/usr/bin/python3`
  - `2.7.17`: `/usr/bin/python2`
  - `2.7.17`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.9',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-117-generic',
 'platform_system': 'Linux',
 'platform_version': '#118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020',
 'python_full_version': '3.6.9',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LC_ADDRESS`
  - `XDG_CONFIG_DIRS`
  - `LC_TELEPHONE`
  - `LANG`
  - `DISPLAY`
  - `SHLVL`
  - `LOGNAME`
  - `XDG_VTNR`
  - `MANDATORY_PATH`
  - `LC_NAME`
  - `PWD`
  - `USER`
  - `XAUTHORITY`
  - `GTK_IM_MODULE`
  - `GJS_DEBUG_TOPICS`
  - `XDG_SESSION_ID`
  - `COLORTERM`
  - `GNOME_TERMINAL_SCREEN`
  - `DESKTOP_SESSION`
  - `XDG_SESSION_DESKTOP`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `DEFAULTS_PATH`
  - `WINDOWPATH`
  - `PAPERSIZE`
  - `LC_MEASUREMENT`
  - `LC_NUMERIC`
  - `LC_MONETARY`
  - `IM_CONFIG_PHASE`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `QT_ACCESSIBILITY`
  - `USERNAME`
  - `CLUTTER_IM_MODULE`
  - `GNOME_TERMINAL_SERVICE`
  - `TEXTDOMAIN`
  - `LC_PAPER`
  - `TEXTDOMAINDIR`
  - `QT4_IM_MODULE`
  - `LC_IDENTIFICATION`
  - `XDG_MENU_PREFIX`
  - `SHELL`
  - `GNOME_SHELL_SESSION_MODE`
  - `XDG_DATA_DIRS`
  - `LC_TIME`
  - `TERM`
  - `SESSION_MANAGER`
  - `GJS_DEBUG_OUTPUT`
  - `XDG_SESSION_TYPE`
  - `GTK_MODULES`
  - `QT_IM_MODULE`
  - `SSH_AGENT_PID`
  - `PATH`
  - `XDG_CURRENT_DESKTOP`
  - `XMODIFIERS`
  - `HOME`
  - `XDG_RUNTIME_DIR`
  - `SSH_AUTH_SOCK`
  - `XDG_SEAT`
  - `VTE_VERSION`
  - `GPG_AGENT_INFO`
  - `OLDPWD`
  - `ZSH`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `LS_COLORS`
  - `CONDA_EXE`
  - `_CE_M`
  - `_CE_CONDA`
  - `CONDA_PYTHON_EXE`
  - `CONDA_SHLVL`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/myounus/bin:/usr/local/bin:/home/myounus/anaconda3/condabin:/home/myounus/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/myounus`

---------------------------

</details>

**Comment by frostming** [comment]
Here is a workaround: After you enter the subshell with `pipenv shell`, clear the env var `PIPENV_ACTIVE` (`unset PIPENV_ACTIVE` and everything is as expected).

**Comment by myounus96** [comment]
> Here is a workaround: After you enter the subshell with `pipenv shell`, clear the env var `PIPENV_ACTIVE` (`unset PIPENV_ACTIVE`) and everything is as expected.

But that will create new virtual environment related to second project, right?But I dont wanna do that I just wanna use 1 common environment for multiple projects.

**Comment by frostming** [comment]
> But that will create new virtual environment related to second project, right?

No, do this step before any `pipenv install` operations

**Comment by myounus96** [comment]
> > But that will create new virtual environment related to second project, right?
> 
> No, do this step before any `pipenv install` operations

No difference it still creating `pipfile` in new other project, and `pipfile` in first main project is not updated.

**Comment by frostming** [comment]
You need to check this https://pipenv.pypa.io/en/latest/advanced/#pipenv.environments.PIPENV_PIPFILE

**Comment by myounus96** [comment]
> You need to check this https://pipenv.pypa.io/en/latest/advanced/#pipenv.environments.PIPENV_PIPFILE

Thanks its working.
