### ISSUE TITLE
pipenv with some repos behind proxy others are not

### ISSUE THREAD

**Issue by dcg-csc** [pypa/pipenv#4465]
### Issue description

I am trying to use pipenv in a corporate environment where access to pypi.org requires a proxy, but another internal pip repo must not use a proxy. Also trying to generate `Pipfile.lock` this way.

### Expected result

Able to use both repots in the same Pipfile by setting proxy information per pip repot

### Actual result

Get timeouts trying the access the repot based on environment proxy vars. Use proxy and one repot times out. Don't use proxy and the other repot times out.

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Not sure the following information would give more help, plus some details in Pipfile are corporate internal use only...

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by matteius** [comment]
@dcg-csc based on the limited information in this ticket, I can only speculate that I have a branch that may solve your use of multiple indexes.  Can you check and test with:  https://github.com/pypa/pipenv/pull/4983

**Comment by matteius** [comment]
Please check with `pipenv==2022.4.20` and the updated documentation on index restrictionshttps://pipenv.pypa.io/en/latest/advanced/#specifying-package-indexes:
