### ISSUE TITLE
pipenv install error: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by kychanbp** [pypa/pipenv#4466]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

Pipenv suddenly nor working today. When I try to search Stackoverflow, it seems not only me having the problem. I saw two questions:
https://stackoverflow.com/questions/64008062/pipenv-error-bad-interpreter-no-such-file-or-directory
https://stackoverflow.com/questions/64005389/pipenv-install-error-bad-interpreter-no-such-file-or-directory

### Expected result
No error

### Actual result
```
Installing pandas…
⠋ Installing...Failed to load paths: /bin/sh: /Users/johnchan/.local/share/virtualenvs/src-_ygy3i93/bin/python: No such file or directory

Output: 
⠙ Installing pandas...Failed to load paths: /bin/sh: /Users/johnchan/.local/share/virtualenvs/src-_ygy3i93/bin/python: No such file or directory

Output: 
Failed to load paths: /bin/sh: /Users/johnchan/.local/share/virtualenvs/src-_ygy3i93/bin/python: No such file or directory

Output: 
Error:  An error occurred while installing pandas!
Error text: 
/bin/sh: /Users/johnchan/.local/share/virtualenvs/src-_ygy3i93/bin/pip: /Users/johnchan/.local/share/virtualenvs/src-_ygy3i93/bin/python: bad interpreter: No such file or directory

✘ Installation Failed 
```

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by uranusjr** [comment]
Do you use Homebrew? This is a common problem with Python installed from Homebrew. The only way to fix this is to `pipenv --rm` and rebuild the virtual environment.

**Comment by kychanbp** [comment]
@uranusjr Yes I am using Homebrew. But I have also tried `pipenv --rm` and rebuild by `pipenv install`. The same problem exists.

**Comment by uranusjr** [comment]
Try reinstalling pipenv (from Homebrew if that’s how you installed it initially).

**Comment by kychanbp** [comment]
@uranusjr I tried to reinstall by `brew reinstall pipenv` but the problem still exists.

**Comment by kychanbp** [comment]
`which -a pipenv`: /usr/local/bin/pipenv

`which -a python python3`: 
/usr/local/opt/python/libexec/bin/python
/usr/bin/python
/usr/local/opt/python/libexec/bin/python
/usr/local/bin/python3
/usr/bin/python3

`which -a pip pip3`
/usr/local/opt/python/libexec/bin/pip
/usr/local/bin/pip
/usr/local/opt/python/libexec/bin/pip
/usr/local/bin/pip3
/usr/bin/pip3

**Comment by kychanbp** [comment]
I tried to uninstall python by `brew uninstall python` and `brew uninstall pipenv` and `pip uninstall pipenv`, I still get the same error.

**Comment by kychanbp** [comment]
but when I create a brand new folder. It works..but not the old folder.

**Comment by kychanbp** [comment]
I found the solution. I need to remove the  /Users/johnchan/.local/share/virtualenvs/src-_ygy3i93 file.

In fact all file starting with src-*

**Comment by Mike-Z-DA** [comment]
What helped me was using the "system" option.
`pipenv install --system`

**Comment by dorkamotorka** [comment]
This did it for me:
```
apt-get -y autoremove --purge pipenv
pip uninstall pipenv # If you have it installed with pip
pip install pipenv
```

**Comment by Rohianon** [comment]
> pipenv install --system

Did this and then restarted my system and it worked.
