### ISSUE TITLE
Inconsistency in how to run tests

### ISSUE THREAD

**Issue by normyp** [pypa/pipenv#4468]
The Test section of [Contributing to Pipenv](https://pipenv.kennethreitz.org/en/latest/dev/contributing/) says to use `pytest` to run all the tests. But this fails as follows:
```
D:\Programming\pipenv\pipenv>pytest
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n
  inifile: D:\Programming\pipenv\pipenv\setup.cfg
  rootdir: D:\Programming\pipenv\pipenv
```
However, further down the page provides three different methods which seem more successful.

**Comment by uranusjr** [comment]
`-n` is provided by pytest-xdist, which should be installed with the previous `pipenv install` call. The instructions likely assumed the reader has the knowledge that pytest should be called inside the environment, not globally.

**Comment by normyp** [comment]
Submitted https://github.com/pypa/pipenv/pull/4472 to link to the details for anyone like me who is completely new to the project.
