### ISSUE TITLE
TestDirectDependencies.test_ssh_dependency_links_install fails

### ISSUE THREAD

**Issue by normyp** [pypa/pipenv#4474]
### Issue description
I ran the following command to single out a test which was failing:
```
pytest -k test_ssh_dependency_links_install
```

This occurred at 0032b76de06d4b8b65e4227e66887a0278c914e8 on Windows 10.
 
### Expected result

Test should pass.

### Actual result

https://gist.github.com/normyp/bfc2f408396c886400d425fc83f4ee0f

**Comment by frostming** [comment]
Did you set ssh key on your machine?
