### ISSUE TITLE
test_ssh_vcs_install fails

### ISSUE THREAD

**Issue by normyp** [pypa/pipenv#4475]
### Issue description

When running the following command to single out a test which was failing:
```
pytest -k test_ssh_vcs_install
```
This occured at 0032b76de06d4b8b65e4227e66887a0278c914e8 on Windows 10.

### Expected result

Test should pass.

### Actual result

https://gist.github.com/normyp/c81fbf265676a75fe5d6735f97407117

**Comment by matteius** [comment]
@normyp Is this still an issue for you?

**Comment by matteius** [comment]
Windows test CI is passing, closing down issue.
