### ISSUE TITLE
Usage of '…' (unicode  U+2026) vs '...' (three periods) inconsistent in output strings and generates garbage characters in Jenkins log.

### ISSUE THREAD

**Issue by dcg-csc** [pypa/pipenv#4483]
### Issue description

This is mainly a cosmetic issue.

The presence of three dots ( U+2026 vs three ASCII periods) is inconsistent througout the code base (I would guess due to code editors "helping" developers with automatic punctuation conversion).

Our Jenkins pipeline does not handle this well and outputs messages like this:
Installing dependencies from Pipfile.lock (c4c2a5)���

### Expected result

Three periods instead of the unicode character for consistency in string output messages from pipenv are preferable to avoid garbage characters in Jenkins or other pipline service logging.

### Actual result

Example:

This is what shows up in the console output from a job in our  Jenkins pipeline: 

Installing dependencies from Pipfile.lock (c4c2a5)���

### Steps to replicate

Just run pipenv commands that generate ouput of the problematic strings through a Jenkins job and look at the console output.

-------------------------------------------------------------------------------

$ pipenv --support
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.8.13'`

Pipenv location: `'/usr/local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/bin/python3.6'`

Python installations found:

  - `3.7.3`: `/usr/bin/python3`
  - `3.7.3`: `/usr/bin/python3.7`
  - `3.7.3`: `/usr/bin/python3.7m`
  - `3.6.12`: `/usr/local/bin/python3`
  - `3.6.12`: `/usr/local/bin/python3.6`
  - `3.6.12`: `/usr/local/bin/python3.6m`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.12',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '3.10.0-1127.13.1.el7.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Tue Jun 23 15:46:38 UTC 2020',
 'python_full_version': '3.6.12',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `HOSTNAME`
  - `JAVA_HOME`
  - `PWD`
  - `HOME`
  - `LANG`
  - `LS_COLORS`
  - `ZAP_PATH`
  - `TERM`
  - `DISPLAY`
  - `SHLVL`
  - `GIT_COMMIT`
  - `LC_ALL`
  - `PATH`
  - `DOCKER_API_VERSION`
  - `DEBIAN_FRONTEND`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv?specific environment variables:

Debug?specific environment variables:

  - `PATH`: `/usr/lib/jvm/java-8-openjdk-amd64//bin:/zap/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/cave`

---------------------------

*Pipfile and Pipfile.lock do not matter for this issue*

**Comment by uranusjr** [comment]
The inconsistency is an issue, but the garbage output is a Jenkins configuration problem (you likely have the encoding configured incorrectly somewhere) and should be fixed accordingly.

**Comment by dcg-csc** [comment]
Unfortunately these Jenkins services are managed by our IT department and they don't like to change anything unless it is a system breaking problem.

**Comment by frostming** [comment]
I am OK with the improvement, looking forward to a PR.
