### ISSUE TITLE
Project().parsed_pipfile parse wrong pipfile

### ISSUE THREAD

**Issue by yshovad** [pypa/pipenv#4484]
### Issue description
From v2020.5.28, in case `PIPENV_PIPFILE` env var supplied, and pipenv install package from git, and the package's setup.py use pipenv `Project().parsed_pipfile` for install_requires, it take the install_requires from wrong pipfile.

To be more clear, assuming a git repository named "Library" contains some library code, as well as Pipfile which specify the install requirements for this library. Let's say an application named "app" wants to use "Library" and have the following in its Pipfile:
```
[packages]
library = {editable = true,git = "ssh://git@github.com/<org>/Library.git"}
```
Let Library's setup.py be:
```python3
from pipenv.project import Project
from pipenv.utils import convert_deps_to_pip
from setuptools import setup, find_packages

setup(
    name='library',
    version='0.1',
    packages=find_packages(),
    install_requires=convert_deps_to_pip(Project().parsed_pipfile['packages'], r=False)
)
```
When pipenv clone the repository "Library" and run its setup.py, it will import pipenv. Since PIPENV_PIPFILE exists in os.environ (set to app/Pipfile) the required packages will be taken from it and not from Library's pipfile.

### Expected result

Library's pipfile will be parsed for install_requires

### Actual result

app's pipfile will be parsed for install_requires

### Steps to replicate

For the above example run `PIPENV_PIPFILE=<app/pipfile> pipenv sync`

### Why it's happening

In pipenv v2018.11.26 the relevant code is:

```python3
if PIPENV_PIPFILE:
    if not os.path.isfile(PIPENV_PIPFILE):
        raise RuntimeError("Given PIPENV_PIPFILE is not found!")
    else:
        PIPENV_PIPFILE = _normalized(PIPENV_PIPFILE)
```
In pipenv v2020.5.28 it change to the following:
```python3
if PIPENV_PIPFILE:
    if not os.path.isfile(PIPENV_PIPFILE):
        raise RuntimeError("Given PIPENV_PIPFILE is not found!")
    else:
        PIPENV_PIPFILE = _normalized(PIPENV_PIPFILE)
        # Overwrite environment variable so that subprocesses can get the correct path.
        # See https://github.com/pypa/pipenv/issues/3584
        os.environ['PIPENV_PIPFILE'] = PIPENV_PIPFILE
```
### Optional fix
Add `pipfile_location` kwarg to `pipenv.project.Project.__init__` method. Libraries with pipfile probably will want force specific pipfile to be in use. Preventing the above will be as following:
```python3
from pipenv.project import Project
from pipenv.utils import convert_deps_to_pip
from setuptools import setup, find_packages
from Pathlib import Path

pipfile_location = Path(__file__).parent.joinpath('Pipfile')
required_packages = Project(pipfile_location=pipfile_location).parsed_pipfile['packages']

setup(
    name='library',
    version='0.1',
    packages=find_packages(),
    install_requires=convert_deps_to_pip(required_packages, r=False)
)
```

**Comment by frostming** [comment]
From your description, I can't tell the current behavior is WRONG. It seems more correct though. All you want is a method to convert Pipfile dependencies into a list of PEP 440 requirement strings.

If that is the case, the internal API of pipenv may not be the best way to do it. Instead, you can have a tool like `pipfile_requirements`. Moreover, depending on a heavy library in your setup.py is not a good idea. It makes it impossible to install via `pip install git+<git url>` unless you specify it in `setup_requires` or PEP 517's `build-system` requires section.

**Comment by yshovad** [comment]
`pipfile_requirements` can fix the problem, thanks.

**Comment by yshovad** [comment]
I do expect `parsed_pipfile` to parse the right pipfile, and it behave correctly till version v2020.5.28. From then, since it set PIPENV_PIPFILE it start take wrong pipfile from PIPENV_PIPFILE's content instead of the search for the pipfie in root repository. So, such change should come along with a way for prevent this unwanted behavior, like the way I suggest or any other way which allow users to tell pipenv to use only the root repository search for dictate the pipfile.

**Comment by frostming** [comment]
The env var PIPENV_PIPENV is to tell which Pipfile to use. You can't ignore that var with it existing.
