### ISSUE TITLE
pipenv not update in Docker Hub

### ISSUE THREAD

**Issue by jrisebor** [pypa/pipenv#4490]
### Issue description

The [pipenv image on docker hub](https://hub.docker.com/r/kennethreitz/pipenv) doesn't have any recent releases. I've also looked at the [pypa profile](https://hub.docker.com/u/pypa) for a pipenv docker image and didn't find one there. I found an [older issue](https://github.com/pypa/pipenv/issues/1468) that appears similar, but there aren't many details on how to fix the issue.

### Expected result

I expected the Docker image continue to be updated on pushes to master on this repo or to transition to a new place on Docker hub.

### Actual result

The old images are not updated and the current Dockerfile as on the master branch in this repository is not on Docker hub.

### Steps to replicate

```Dockerfile
FROM kennethreitz/pipfile
```

gives me an outdated version.

**Comment by uranusjr** [comment]
Kenneth is not on the maintenance team anymore. Please contact him personally to update the image.

**Comment by jrisebor** [comment]
Hi @uranusjr, I was expecting an image to be built for `pypa/pipenv`. Is that a possibility?

**Comment by uranusjr** [comment]
I do not know of anyone being interested in investing time to do it now. But PyPA is always open to contributions. Feel free to drop a word at https://dicsuss.python.org if you’re interested in maintaining a recipe for PyPA.
