### ISSUE TITLE
Can black be downgraded to 19.3b0 for use with pypy support for devolper#early-feedback

### ISSUE THREAD

**Issue by frog-o** [pypa/pipenv#4494]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues and the [PEEP list](https://github.com/pypa/pipenv/blob/master/peeps/) before posting! We may close your issue if it is very similar to one of them. Please be considerate and follow the PEEP process, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Is your feature request related to a problem? Please describe.

I like trying to use pypy to help develop pipenv but with black >  19.3b0 it need typed-ast which does not work with the latest (of this writing) pypy aviable from downloads. I doing this on a raspbery 4 pi with 4gb of ram. I have pypy working fine , But since there is no wheel for arm32 it has to a build  typed-ast.

typing 

`pipenv install --dev
`
 which fails to build some header files an is a know issue in typed-ast and thjere sulltion is to wait for a new pypy to support python 3.8 wich they say might take a while.  Looking at black issues the now about it and say  black==19.3b0 works good.

I changed the pipfile.lock to use black==19.3b0 and remove the typed-ast dependency and install fine now..  I was wondering if i make a pull request if this change would be acceptable and if there was reason you black ~> 19.30b  version.  

It is very frustrating right now to have to use python instead of pypy just because black is too new and pipenv does not allow you to use both without deleting the other.

### Describe the solution you'd like

This was explain above, I want black downgraded and typed-ast dependency removed. 

### Describe alternatives you've considered

work on support for more the one virtual enviorments as i already mentioned in [this issue](https://github.com/pypa/pipenv/issues/4376)

### Additional context
the incompatibility with black is 
mentioned in [this issue](https://github.com/psf/black/issues/727)

Add any other context or screenshots about the feature request here. It may be a good idea to mention that platform and Python version you are on.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by frostming** [comment]
19.3b0 is a relatively old release. You can ignore that failure and manually install via `pipenv run pip install black==19.3.b0` if you still require the package. I prefer to keep the lock file unchanged.

**Comment by frog-o** [comment]
Please reconsider reopen this, your work around does not work and does not address the feature  I am requesting which was **Pipenv to support pypy development enviorment)**.
  
**This is my fault with how I worded my feature request** I am sorry about that.  I have a hard time with wording and write in general.  I should of not put the question can black be downgraded in the title(I will rename properly).  

you said 

> 19.3b0 is a relatively old release

I understand you want to use the latest but there are thing you should consider

*  using to new of  release breaks things  **pypy in my case** and black does not want to fix it ,it is not high enough priority (at least that want it sound to me when going thought there issues about it.)

* In some way this is a bug in pipenv I thought it said it support pypy but you can't use it to devlope  pipenv itself.  If you use 

pipenv run pip install black==19.3.b0.  It still fail the pytest (even thought i have not tried to do this, want i have done should do the same thing and fail several imports).
  
I know nothing about pytest though and the document on configuring pytest for pipenv  IMHO is lacking as of right now i was thinking about make a new feature request on that too but  I hate keep opening feature request and want to fix these type of  Issue myself, because I know you don't have much for time.  Who does?


* I came across older packages still be used like( Sphinx and Pytest ) who are worse.  
I think it is for python 2.7 support which is no longer supported  


* I am very frustrated with pipenv not doing the thing I wanted and working with **pypy** is one of them. 

* The whole purpose of a lock file is to keep the development environment the same to avoid breakage,

in generally can use older function but you can't use newer ones.

* I don't want to just complain and  **I was trying to fix the problem myself i just asking for a little support by keeping this open**.  I want a central place to talk about this issue in **case anyone else like me wanted to work on it**. 

 I find it odd , for me  the whole purpose of putting programs on the web is to get people to work together to make a program better, but i just seem to find it to be a big time sync;  Trying to explain want i trying to do.

> I prefer to keep the lock file unchanged

Is there a reason why?  Are you use some important new feature in a new version of black(which is what i was really trying to ask when i posted this ?)

Are you say there no way you will use black version 19 because it to old?

As of right know 

I don't know if it because of pytest(which is relay old which does not help) or I have pytest miss configured.  But i can't 
understand the output it pytest is give me.  I going to keep reading on how to use pytest and How make files are used etc.  I was hoping to try make pipenv better but it's looking to be beyond my abilities.
