### ISSUE TITLE
python executable no longer selectable

### ISSUE THREAD

**Issue by rotten** [pypa/pipenv#4497]
# Issue description

I upgraded to pipenv version 11.9.0 yesterday.  I'm running on Ubuntu 20.04 with multiple versions of Python installed.

After the upgrade, I can no longer get pipenv to use the specific python path I want it to.

`export PIPENV_PYTHON=/usr/bin/python3` doesn't help.
`pipenv install --python=/usr/bin/python3` doesn't help.
`/usr/bin/python3 /usr/bin/pipenv install` doesn't help.

In every case, it reverts to using `/usr/bin/python` which I do not want it to use.  

This was not a problem until I upgraded.

### Expected result

I should be able to specify the path to the python executable on my system that I want pipenv to use.

### Actual result

```
Using /usr/bin/python3 (3.8.5) to create virtualenv…
Warning: Your Pipfile requires python_version 3.8, but you are using 2.7.18 (/bin/python).
```

### Steps to replicate

Upgrade to the latest version and watch it break.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

    $ pipenv --support | xclip

```
Error: no such option: --support
```

**Comment by Mause** [comment]
Version 11.9 is several years out of date, please install pipenv with pip instead

**Comment by rotten** [comment]
Ah.  I did install it with `pip`.  However I still had an old system version running which was getting in the way of the latest version for some reason.  (I'd previously been using a pip installed one as well, and it did not have problems).  Removing the legacy system one seems to have solved this.  Thanks!
