### ISSUE TITLE
Display installed version

### ISSUE THREAD

**Issue by CodeTroopers** [pypa/pipenv#4501]
### Is your feature request related to a problem? Please describe.

When installing a package with `pipenv install "awscli>=1.18.0"`, the version installed is not displayed in the terminal :
```
Installing awscli>=1.18.0…
Adding awscli to Pipfile's [packages]…
✔ Installation Succeeded 
```
So we are unable to know which version is installed unless we look for it in the lock file
  
### Describe the solution you'd like

Add a line in the output with the package version installed

```
Installing awscli>=1.18.0…
Adding awscli to Pipfile's [packages]…
awscli 1.18.165 installed
✔ Installation Succeeded 
```

**Comment by frostming** [comment]
Do you also want installed versions displayed when no package is given to `pipenv install`? Or `pipenv sync` and `pipenv update`

**Comment by CodeTroopers** [comment]
Not necessary for `pipenv install` neither `pipenv sync` because we suppose that the project is healthy. It could be interesting for `pipenv update` since we are in a project upgrade flow

**Comment by frostming** [comment]
How about just displaying the pip command output, like this:
![image](https://user-images.githubusercontent.com/16336606/99018022-1d2fee00-2594-11eb-8793-7c55fcf40828.png)

**Comment by CodeTroopers** [comment]
Too much information kill information so just `Successfully installed {packageName} {packageVersion}` is needed. The rest could be displayed with an option `--verbose`

**Comment by matteius** [comment]
@CodeTroopers Could you check the latest version of pipenv and its level of output?
