### ISSUE TITLE
Creating virtual environment...FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Reevesss** [pypa/pipenv#4507]
I have installed miniconda3, now I'm trying to set up a virtual environment via "pipenv --three". But I'm getting this error:
![image](https://user-images.githubusercontent.com/64840598/97609355-ca8ef780-1a13-11eb-9d47-3136d6599827.png)

I think I set miniconda up wrong and changed the environmental variables, because my PATH is full of miniconda3, it looks the following:
![image](https://user-images.githubusercontent.com/64840598/97609561-0b870c00-1a14-11eb-846e-7c8515aec371.png)
![image](https://user-images.githubusercontent.com/64840598/97609770-4db04d80-1a14-11eb-9e54-0edaaa867d72.png)

Please help me!

**Comment by frostming** [comment]
Can you please try the latest release

**Comment by Reevesss** [comment]
> Can you please try the latest release

Thank you @frostming,
I solved the problem, i think there were some problems with the instalation.
