### ISSUE TITLE
Hard to Read: No `space` between username and command

### ISSUE THREAD

**Issue by Falpangaea** [pypa/pipenv#4509]
Example: 
`pipenv shell`
`(project_name) username`

So when I start typing a command, there isn't a space between `username` and the command:
`(project) usernamecommand`

Everything still works, it's just so hard to read.  Is there a piece of configuration I'm missing?

**Comment by uranusjr** [comment]
pipenv does not control that, it only prepends `(project) ` and the rest is from your shell. You are probably configuring your `PS1` incorrectly.
