### ISSUE TITLE
Virtual environment doesn't appear at head of path when activated with `pipenv shell`

### ISSUE THREAD

**Issue by thepreacher** [pypa/pipenv#4515]
### Issue description

Virtual environment location gets added to path before `.zshenv` is sourced, causing my local path settings to be listed ahead of the current virtual environment. The problem is I use `asdf-vm` for my python installs, so when that happens, the default python is reached before that of the current virtual environment. I'm therefore not able to use any packages from the virtual environment. 

### Expected result

I expect the path to appear as below for the command `pipenv shell` in a virtual environment.

```
/Users/username/.virtualenvs/dataanalysis-S7cc-udF/bin
/usr/local/Cellar/pipenv/2020.8.13_1/libexec/tools
/Users/username/bin
/Users/username/.local/bin
/Users/username/.emacs.d/bin
/Users/username/.asdf/shims
/Users/username/.asdf/bin
/Users/username/.nimble/bin
/Users/username/.cargo/bin
/Users/username/go/bin
/usr/local/opt/sqlite/bin
/Users/username/sdks/flutter/bin
/usr/local/opt/coreutils/libexec/gnubin
/usr/local/opt/findutils/libexec/gnubin
/usr/local/opt/grep/libexec/gnubin
/usr/local/opt/curl/bin
/usr/local/opt/gettext/bin
/Applications/Postgres.app/Contents/Versions/latest/bin
/usr/local/sbin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/share/dotnet
~/.dotnet/tools
/Library/Apple/usr/bin
/usr/local/opt/fzf/bin
```

### Actual result

```
/Users/username/bin
/Users/username/.local/bin
/Users/username/.emacs.d/bin
/Users/username/.asdf/shims
/Users/username/.asdf/bin
/Users/username/.nimble/bin
/Users/username/.cargo/bin
/Users/username/go/bin
/usr/local/opt/sqlite/bin
/Users/username/sdks/flutter/bin
/usr/local/opt/coreutils/libexec/gnubin
/usr/local/opt/findutils/libexec/gnubin
/usr/local/opt/grep/libexec/gnubin
/usr/local/opt/curl/bin
/usr/local/opt/gettext/bin
/Applications/Postgres.app/Contents/Versions/latest/bin
/usr/local/sbin
/Users/username/.virtualenvs/dataanalysis-S7cc-udF/bin
/usr/local/Cellar/pipenv/2020.8.13_1/libexec/tools
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/usr/local/share/dotnet
~/.dotnet/tools
/Library/Apple/usr/bin
/usr/local/opt/fzf/bin
```

The `pipenv` specific entries on the path are:

```
/Users/username/.virtualenvs/dataanalysis-S7cc-udF/bin
/usr/local/Cellar/pipenv/2020.8.13_1/libexec/tools
```
Where `/Users/username/.virtualenvs/dataanalysis-S7cc-udF/bin` is the virtual environment path.

Because 
```
/Users/username/.asdf/shims
/Users/username/.asdf/bin
```
appear earlier, `/Users/username/.virtualenvs/dataanalysis-S7cc-udF/bin` is unreachable for python.

### Steps to replicate

Install `asdf-vm` and us that to install python. 
Set the system python to the version installed by asdf.
Install pipenv and create virtual environment in a chosen folder. 
Activate the virtual environment with `pipenv shell`.
Type `which python` and you'll see the asdf global python is the one that is used instead of the virtual environment's

### Aditional notes
I'm on a mac and use zsh for shell. The work around that I use at the moment is as follows, In my `.zshenv` I only have the following code

```
#!/usr/bin/env zsh

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
```

then in my `.zprofile` I only have

```
#!/usr/bin/env zsh

# Load the envsetting and paths and some:
for file in ~/.{zexports,zpaths}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;
```

My `.zpath` contains

```
#!/usr/bin/env zsh

path=(
  ${HOME}/.nimble/bin   # Nim
  ${HOME}/.cargo/bin  # Rust
  ${GOPATH}/bin   # Golang
  /usr/local/opt/sqlite/bin   # Sqlite3
  ${HOME}/sdks/flutter/bin  # flutter
  /usr/local/opt/coreutils/libexec/gnubin   # coreutils
  /usr/local/opt/findutils/libexec/gnubin   # findutils
  /usr/local/opt/grep/libexec/gnubin  # grep
  /usr/local/opt/curl/bin   # curl
  /usr/local/opt/gettext/bin  # Gettext
  /Applications/Postgres.app/Contents/Versions/latest/bin   # Postgress app
  /usr/local/sbin
  #/usr/local/opt/llvm/bin  # llvm
  $path
)

source ${HOME}/.asdf/asdf.sh

path=(
  ~/bin
  ~/.local/bin
  ${HOME}/.emacs.d/bin
  $path
)

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path
```
If I overwrite the content of `.zprofile` with that of `.zshenv`, the issue rears it's head. The code in the `.zshenv` comes from `prezto`.

**Comment by frostming** [comment]
Did you forced `--fancy` mode? Did you see `Compatibility mode not supported. ` line output when `pipenv shell`?

**Comment by thepreacher** [comment]
@frostming thanks for you questions! That has led me to the answer. It was all my fault. So I had indeed forced `--fancy` with `export PIPENV_SHELL_FANCY=1`. When I commented that out, everything worked as I expected but I didn't like the extra bit of information it printed before the prompt to I read docs againg and found [https://pipenv.pypa.io/en/latest/basics/#about-shell-configuration](url). 

So I moved all my `path and exports` to my `.zshrc` and into an if condition like this
```
if [[ -o login ]]; then
	# Load the env setting and paths and some:
	for file in ~/.{zexports,zpaths}; do
		[ -r "$file" ] && [ -f "$file" ] && source "$file";
	done;
fi
```
and now everything is great. I'll close this issue as it's fixed. Thanks again!
