### ISSUE TITLE
Can you specify a target operating system (installing Linux packages on Windows)?

### ISSUE THREAD

**Issue by kkotowick** [pypa/pipenv#4520]
Is it possible to tell Pipenv what OS to install packages for? I'm building a cross-platform system that bundles code for AWS Lambda functions (Linux OS), so I'd like to be able to run `pipenv install` on a Windows machine and have it install Linux packages.

Currently, running `pipenv install` on Windows and Linux using the exact same Pipfile results in completely different directory structures in the `site-packages` directory.

**Comment by frostming** [comment]
>so I'd like to be able to run pipenv install on a Windows machine and have it install Linux packages.

It can't work this way.
