### ISSUE TITLE
Pipenv not using asdf current python for virtual environment creation

### ISSUE THREAD

**Issue by thepreacher** [pypa/pipenv#4522]
### Issue description
I just upgraded pipenv to **Release v2020.11.4** after which I noticed that creating a virtual environment with `pipenv shell` uses `/usr/local/bin/python3 (3.9.0)` although `which python` gives `/Users/username/.asdf/shims/python` which is python (3.8.6) system default set via `asdf global` command.

### Expected result

I was expecting pipenv to use the default global python as set via asdf since when I type the command `python` or `python3` it displays 

```
Python 3.8.6 (default, Oct 27 2020, 12:32:55)
[Clang 12.0.0 (clang-1200.0.32.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

### Steps to replicate

I have asdf installed and python (3.8.6) installed via asdf and set as the global python via `asdf global python 3.8.6`.
I also installed pipenv via `pipx install pipenv`
Then I create a folder and inside that folder issue the command `pipenv shell`

**Comment by frostming** [comment]
Sorry but pipenv works in this way that it always tries to pick the highest version of Python interpreter if not explicitly specified.

To specify the interpreter:

```bash
# use what `which python` points to
$ pipenv install --python python
# use another python interpreter
$ pipenv install --python /path/to/python
```

**Comment by uranusjr** [comment]
`PIPENV_DEFAULT_PYTHON_VERSION` can also be used to set this permanently.

**Comment by thepreacher** [comment]
@frostming Thanks for your response. What confused me was the slight difference in your answer as compared to the documentation at [Specifying Python Versions](https://pipenv.pypa.io/en/latest/basics/#specifying-versions-of-python) which stated that

`If you don’t specify a Python version on the command–line, either the [requires] python_full_version or python_version will be selected automatically, falling back to whatever your system’s default python installation is, at time of execution.`

which is different from your answer which says `tries to pick the highest version of Python interpreter if not explicitly specified.`. You said `highest version` whereas the docs says `default version`. 

The `default version` might not necessarily be the `highest version` since on mac for eg, other pacakges automatically install specific python versions they need if not already available as happend in my case.

Anyway thanks for helping me.
