### ISSUE TITLE
Pipenv latest version of Django is 3.0.11 rather than 3.1.*

### ISSUE THREAD

**Issue by joweenflores** [pypa/pipenv#4531]
I was creating a new Django App when I encountered a weird error: `return database_name == ':memory:' or 'mode=memory' in database_name TypeError: argument of type 'WindowsPath' is not iterable`  when migrating. I traced back and known that this was an issue in <=3.0.11 so I checked the Django version installed and it was 3.0.11. 

I ran `pipenv updated --outdated` on my previous Django 3.1.3 project and got this:

`Package 'Django' out-of-date: '==3.1.3' installed, '==3.0.11' available.`

Installing django with `pipenv install django` defaults to installing the previous 3.0.11 version.

For now, the workaround installing the specific version older than 3.1 by:

`pipenv install 'django>=3.1.*'`

or with argon-package:

`pipenv install 'django[argon2]>=3.1.*'`

I'm not sure where should I report this so I'm just crossposting it with Django issue tracker, FYI, also posted here: [https://code.djangoproject.com/ticket/32188](https://code.djangoproject.com/ticket/32188)

Thanks!

**Comment by Mause** [comment]
Which version of pipenv are you using?

**Comment by joweenflores** [comment]
> Which version of pipenv are you using?

pipenv, version 2020.8.13

**Comment by joweenflores** [comment]
> > Which version of pipenv are you using?
> 
> pipenv, version 2020.8.13

well, my bad. I was always working with venv so I forgot to update pipenv. Fixed the issue by updating pipenv.
