### ISSUE TITLE
Env variable in pipfile (package section) not working

### ISSUE THREAD

**Issue by julste** [pypa/pipenv#4532]
I'm trying to install a package via Pipfile from a private repo. I have already asked for help on [stackoverflow](https://stackoverflow.com/questions/64784290/pipenv-pipfile-installing-package-from-private-repo).

#3882 # Issue description

Using the following syntax, VScode is asking for a password (in console it is locking forever), although my token is exported to my env variables:
```

[packages]
pack1 = {editable = true, git = "https://${ACCESS_TOKEN}@github.com/.../pack1.git"}
```

Using the ACCESS_TOKEN directly it works like expected:

```
[packages]
pack1 = {editable = true, git = "https://myToken@github.com/.../pack1.git"}
```

Using pipenv install command works also fine with my environment variable (ACCESS_TOKEN):

`pipenv install -e git+https://${ACCESS_TOKEN}@github.com/.../pack1.git`

-------------------------------------------------------------------------------
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.4'`

Pipenv location: `'/home/.../.local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.7.5`: `/usr/bin/python3`
  - `3.7.5`: `/usr/bin/python3.7`
  - `3.7.5`: `/usr/bin/python3.7m`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.3.0-64-generic',
 'platform_system': 'Linux',
 'platform_version': '#58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020',
 'python_full_version': '3.7.5',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

**Comment by frostming** [comment]
Duplicate with #4038 #3516
