### ISSUE TITLE
Creating requirements.txt re-calculates the lock file

### ISSUE THREAD

**Issue by jacobisaliveandwell** [pypa/pipenv#4539]
This is a blatant duplicate of #3975 because @frostming doesn't seem to be responding there.

This is a critical issue that breaks a lot of common workflows. Can this please get some attention?

**Comment by jacobisaliveandwell** [comment]
cc @kennethreitz42

**Comment by frostming** [comment]
This is a behavioral change, but I think OP can be achieved by `pipenv lock -r --skip-lock`.

**Comment by jacobisaliveandwell** [comment]
@frostming Thanks for taking a look. I'll give that a try. For some reason I recall running into a bug with this, but can't recall the details right now.

**Comment by frostming** [comment]
My bad `pipenv lock` doesn't have that option, maybe simply add that flag is okay?

**Comment by jacobisaliveandwell** [comment]
@frostming Found [the issue](https://github.com/pypa/pipenv/issues/3493#issuecomment-614009436) I was thinking of when making my last comment.

> My bad pipenv lock doesn't have that option, maybe simply add that flag is okay?

I think that would be great! I also think there is a growing consensus that `sync` should have the `--requirements' flag added, that way it's very clear nothing is being recalculated, but I understand why it was placed in `lock` since one is creating another representation of state, similar to the lock file.

**Comment by matteius** [comment]
@jacobisaliveandwell new versions of pipenv have a `requirements` command to generate the requirements.txt and this will likely eventually completely replace the `pipenv lock -r` behavior or at least that could lock and then run the requirements command, but the `requirements` command simply introspects the `Pipfile.lock`.
