### ISSUE TITLE
TypeError when attempting to create a new virtual environment

### ISSUE THREAD

**Issue by cjwinchester** [pypa/pipenv#4543]
### Issue description

After updating to OSX Big Sur and updating a homebrew-installed pipenv to version 2020.11.15, attempts to install dependencies into a new project folder with pipenv fail with a TypeError.

### Expected result

I expected pipenv to install the dependencies successfully.

### Actual result
```
pipenv install requests --verbose
Using python: None
Path to python: /usr/local/bin/python3
Creating a virtualenv for this project...
Pipfile: /Users/codywinchester/test/Pipfile
Using /usr/local/bin/python3 (3.9.0) to create virtualenv...
⠹ Creating virtual environment...TypeError: expected str, bytes or os.PathLike object, not list

✘ Failed creating virtual environment
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/cli/command.py", line 233, in install
    retcode = do_install(
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/core.py", line 1920, in do_install
    ensure_project(
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/core.py", line 576, in ensure_project
    ensure_virtualenv(
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/core.py", line 511, in ensure_virtualenv
    do_create_virtualenv(
  File "/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv/core.py", line 979, in do_create_virtualenv
    raise exceptions.VirtualenvCreationException(
pipenv.exceptions.VirtualenvCreationException: Failed to create virtual environment.
```

### Steps to replicate

```
mkdir test
cd test
pipenv install requests --verbose
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'/usr/local/Cellar/pipenv/2020.11.15/libexec/lib/python3.9/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2020.11.15/libexec/bin/python'`

Python installations found:

  - `3.9.0`: `/usr/local/bin/python3`
  - `3.9.0`: `/usr/local/bin/python3.9`
  - `3.7.3`: `/usr/bin/python3`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '20.1.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT '
                     '2020; root:xnu-7195.50.7~2/RELEASE_X86_64',
 'python_full_version': '3.9.0',
 'python_version': '3.9',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `PATHABLE_API_KEY`
  - `PIP_DOWNLOAD_CACHE`
  - `rvm_use_flag`
  - `rvm_bin_path`
  - `VIRTUALENVWRAPPER_SCRIPT`
  - `VIRTUALENVWRAPPER_PROJECT_FILENAME`
  - `TERM_PROGRAM`
  - `PIP_REQUIRE_VIRTUALENV`
  - `rvm_quiet_flag`
  - `GEM_HOME`
  - `rvm_gemstone_url`
  - `TERM`
  - `SHELL`
  - `rvm_docs_type`
  - `IRBRC`
  - `PP_CONGRESS_API_KEY`
  - `TMPDIR`
  - `TERM_PROGRAM_VERSION`
  - `DJANGO_SECRET_KEY`
  - `rvm_hook`
  - `MY_RUBY_HOME`
  - `TERM_SESSION_ID`
  - `ZSH`
  - `USER`
  - `rvm_gemstone_package_file`
  - `_system_type`
  - `NCC_SLACK_WEBHOOK`
  - `COMMAND_MODE`
  - `rvm_path`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `rvm_proxy`
  - `rvm_ruby_file`
  - `PAGER`
  - `WORKON_HOME`
  - `SLACK_WEBHOOK`
  - `PROJECT_HOME`
  - `LSCOLORS`
  - `rvm_silent_flag`
  - `rvm_prefix`
  - `VIRTUALENVWRAPPER_PYTHON`
  - `CENSUS_API_KEY`
  - `rvm_ruby_make`
  - `_`
  - `VIRTUALENVWRAPPER_HOOK_DIR`
  - `__CFBundleIdentifier`
  - `PWD`
  - `EDITOR`
  - `rvm_sdk`
  - `LANG`
  - `ITERM_PROFILE`
  - `_system_arch`
  - `XPC_FLAGS`
  - `_system_version`
  - `XPC_SERVICE_NAME`
  - `rvm_version`
  - `rvm_script_name`
  - `rvm_pretty_print_flag`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `rvm_ruby_mode`
  - `LC_TERMINAL_VERSION`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `rvm_alias_expanded`
  - `rvm_wrapper_name`
  - `GEM_PATH`
  - `NOAA_TOKEN`
  - `LC_CTYPE`
  - `VIRTUALENV_PYTHON`
  - `rvm_nightly_flag`
  - `VIRTUALENVWRAPPER_WORKON_CD`
  - `rvm_ruby_make_install`
  - `rvm_niceness`
  - `LC_TERMINAL`
  - `rvm_ruby_bits`
  - `rvm_bin_flag`
  - `rvm_only_path_flag`
  - `RUBY_VERSION`
  - `_system_name`
  - `COLORTERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2020.11.15/libexec/tools:/Users/codywinchester/.rvm/gems/ruby-2.4.2/bin:/Users/codywinchester/.rvm/gems/ruby-2.4.2@global/bin:/Users/codywinchester/.rvm/rubies/ruby-2.4.2/bin:/usr/local/sbin:/Users/codywinchester/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/codywinchester/.rvm/bin:/Users/codywinchester/webdrivers/`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `subl`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/codywinchester/test`

---------------------------

</details>

**Comment by frostming** [comment]
It is hard to reproduce your case since it highly depends on your environment. Can you please try some digging yourself and provide more information about the case?

Things you can try not limited to:
1. Try creating virtualenv via `virtualenv --python /usr/local/bin/python3 venv`
2. Set `PIPENV_NOSPIN` to expose the full traceback

**Comment by cjwinchester** [comment]
Thank you for your response. I'm not sure what the problem was initially -- virtualenv by itself was working fine -- but I was eventually able to resolve by uninstalling the brew-installed version of pipenv and reinstalling via pip3.
