### ISSUE TITLE
`PIPENV_ACTIVE` gets set when starting tmux

### ISSUE THREAD

**Issue by naterichman** [pypa/pipenv#4544]
### Issue description

When I activate tmux, everytime I try `pipenv shell` I get `Shell for UNKNOWN_VIRTUAL_ENVIRONMENT already activated.  No action taken to avoid nested environments.` And the environmental variable `PIPENV_ACTIVE` gets set

### Expected result

`pipenv shell` completes successfully, `PIPENV_ACTIVE` not set

### Actual result

Before entering tmux, the environmental variable `PIPENV_ACTIVE` is not set, after starting tmux, and when creating new tmux windows, `PIPENV_ACTIVE` gets set to `1`.  I tried setting `PIPENV_ACTIVE=0` and I still can't run `pipenv shell`, however when I `unset PIPENV_ACTIVE` then I can run `pipenv shell`

### Steps to replicate
 (Not exactly sure)
Run tmux on Mac OS Catalina (10.15.16) with pipenv

tmux config:
```
setw -g mode-keys vi
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"

bind r source-file ~/.tmux.conf

set -g mouse on
```

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.6.2'`

Pipenv location: `'/Users/naterichman/Library/Python/3.8/lib/python/site-packages/pipenv'`

Python location: `'/usr/local/bin/python3'`

Python installations found:

  - `3.8.4`: `/usr/local/bin/python3`
  - `3.8.4`: `/usr/local/bin/python3.8`
  - `3.8.4`: `/Library/Frameworks/Python.framework/Versions/3.8/bin/python3`
  - `3.8.4`: `/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8`
  - `3.7.3`: `/usr/bin/python3`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '19.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT '
                     '2020; root:xnu-6153.141.1~1/RELEASE_X86_64',
 'python_full_version': '3.8.4',
 'python_version': '3.8',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `COLORFGBG`
  - `COLORTERM`
  - `COMMAND_MODE`
  - `HOME`
  - `ITERM_PROFILE`
  - `ITERM_SESSION_ID`
  - `LANG`
  - `LC_TERMINAL`
  - `LC_TERMINAL_VERSION`
  - `LESS`
  - `LOGNAME`
  - `LSCOLORS`
  - `LaunchInstanceID`
  - `OLDPWD`
  - `PAGER`
  - `PATH`
  - `PIPENV_ACTIVE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PWD`
  - `PYTHONDONTWRITEBYTECODE`
  - `SECURITYSESSIONID`
  - `SHELL`
  - `SHLVL`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `TMPDIR`
  - `TMUX`
  - `TMUX_PANE`
  - `USER`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `ZSH`
  - `__CF_USER_TEXT_ENCODING`
  - `LC_ALL`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/naterichman/.local/bin:/Users/naterichman/Library/Python/3.8/bin:/Users/naterichman/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/naterichman/.local/bin:/Users/naterichman/Library/Python/3.8/bin:/Users/naterichman/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/naterichman`

---------------------------

Contents of `Pipfile` ('/Users/naterichman/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "3.8"

```

</details>

**Comment by Mause** [comment]
Can you confirm it isn't being set in your shell config?

**Comment by naterichman** [comment]
Yes it wasn't being set in my shell config, however I apparently had some zombie tmux sessions in the background, a restart of my computer seemed to fix the issue.

**Comment by awooTim** [comment]
I have the same problem. I use `tmux kill-session -a` to kill all session and solve the problem

**Comment by brennenhuang** [comment]
I have the same problem. I use `tmux kill-session -a` to kill all session and solve the problem
