### ISSUE TITLE
Problem for pipenv with conda

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [pypa/pipenv#4545]
In your documentation it said that it is possible to use Pipenv with conda:

https://pipenv.pypa.io/en/latest/advanced/#pipenv-and-other-python-distributions

But it does not work even on a freshly created project:

Expected result - Pipenv would install packages inside Conda envirment and would use conda python interpreter.

Actual result - error during Pipenv initializations 

# python console
```
import sys
sys.executable
'C:\\ProgramData\\Miniconda3\\envs\\new_project\\python.exe'
```
# terminal
```
pipenv install --python=C:\\ProgramData\\Miniconda3\\envs\\new_project\\python.exe

# result

Creating a virtualenv for this project...
Pipfile: C:\Users\hardcase1\PycharmProjects\new_project\Pipfile
Using c:/programdata/miniconda3/envs/new_project/python.exe (3.7.9) to create virtualenv...
[=== ] Creating virtual environment...FileNotFoundError: [Errno 2] No such file or directory: 'c:\\programdata\\miniconda3\\envs\\new_pr
oject\\Lib\\venv\\scripts\\nt\\python.exe'

Failed creating virtual environment

[pipenv.exceptions.VirtualenvCreationException]:
Failed to create virtual environment.
```

pipenv, version 2020.11.15
conda 4.8.5
Windows 10
python 3.7.9

Would be glad to have this possible bug fixed or point me out what i did wrong if so.

I use Pipenv over 2 years already. Great tool.

Thank you

**Comment by Mause** [comment]
Have you tried directing pipenv to use a python.exe that isn't part of an existing virtual environment?

**Comment by AlekseiKhatkevich** [comment]
Yes. This way it works correctly.

**Comment by drewgilliam** [comment]
FYI - conda and virtualenv 20.0.34+ don't play well together, see ContinuumIO/anaconda-issues#12094 and pypa/virtualenv#1986.  The current suggested workaround is to downgrade to virtualenv 20.0.33.
