### ISSUE TITLE
python_version is different from the version I use and  the requirement.txt generated different from the original?

### ISSUE THREAD

**Issue by qiulang** [pypa/pipenv#4546]
### Issue description
The following output said my issue. I use python 3.9 while python_version = 3.8. I did use 3.8 before but I installed pipenv by `pip install pipenv `using python 3.9 and I am using 3.9 now.

```
pyenv_test ➤ cat requirements.txt                                
pexpect==4.8.0
termcolor==1.1.0
pyenv_test ➤ pipenv install                            
requirements.txt found, instead of Pipfile! Converting...
✔ Success!
Warning: Your Pipfile now contains pinned versions, if your requirements.txt did.
We recommend updating your Pipfile to specify the "*" version, instead.
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Updated Pipfile.lock (a46966)!
Installing dependencies from Pipfile.lock (a46966)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
pyenv_test ➤ cat Pipfile                     
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
pexpect = "==4.8.0"
termcolor = "==1.1.0"

[dev-packages]

[requires]
python_version = "3.8"
pyenv_test ➤ which python3              
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3
```

The 2nd issue is the requirement.txt that Pipefile generated is different from my original requirement.txt,  ptyprocess is the package used by pexpect. I really don't think it should be list in requiremnt.txt. 

```
pyenv_test ➤ pipenv lock -r   
#
# These requirements were autogenerated by pipenv
# To regenerate from the project's Pipfile, run:
#
#    pipenv lock --requirements
#

-i https://pypi.org/simple
pexpect==4.8.0
ptyprocess==0.6.0
termcolor==1.1.0
```

-------------------------------------------------------------------------------
 
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv'`

Python location: `'/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9'`

Python installations found:

  - `3.9.0`: `/Library/Frameworks/Python.framework/Versions/3.9/bin/python3`
  - `3.9.0`: `/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9`
  - `3.9.0`: `/usr/local/bin/python3`
  - `3.9.0`: `/usr/local/bin/python3.9`
  - `3.8.6`: `/Library/Frameworks/Python.framework/Versions/3.8/bin/python3`
  - `3.8.6`: `/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8`
  - `3.8.6`: `/usr/local/bin/python3.8`
  - `3.8.2`: `/usr/bin/python3`
  - `3.6.10`: `/Users/qiulang/.pyenv/versions/3.6.10/bin/python3`
  - `3.5.3`: `/Users/qiulang/.pyenv/versions/3.5.3/bin/python3`
  - `3.4.0`: `/Users/qiulang/.pyenv/versions/3.4.0/bin/python3`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '20.1.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT '
                     '2020; root:xnu-7195.50.7~2/RELEASE_X86_64',
 'python_full_version': '3.9.0',
 'python_version': '3.9',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_SESSION_ID`
  - `SSH_AUTH_SOCK`
  - `LC_TERMINAL_VERSION`
  - `COLORFGBG`
  - `ITERM_PROFILE`
  - `SQLITE_EXEMPT_PATH_FROM_VNODE_GUARDS`
  - `XPC_FLAGS`
  - `LANG`
  - `PWD`
  - `SHELL`
  - `__CFBundleIdentifier`
  - `TERM_PROGRAM_VERSION`
  - `TERM_PROGRAM`
  - `PATH`
  - `LC_TERMINAL`
  - `COLORTERM`
  - `COMMAND_MODE`
  - `TERM`
  - `HOME`
  - `TMPDIR`
  - `USER`
  - `XPC_SERVICE_NAME`
  - `LOGNAME`
  - `ITERM_SESSION_ID`
  - `__CF_USER_TEXT_ENCODING`
  - `SHLVL`
  - `OLDPWD`
  - `ZSH`
  - `PAGER`
  - `LESS`
  - `LC_CTYPE`
  - `LSCOLORS`
  - `LS_COLORS`
  - `NODENV_SHELL`
  - `rvm_prefix`
  - `rvm_path`
  - `rvm_bin_path`
  - `_system_type`
  - `_system_name`
  - `_system_version`
  - `_system_arch`
  - `rvm_version`
  - `GEM_HOME`
  - `GEM_PATH`
  - `MY_RUBY_HOME`
  - `IRBRC`
  - `RUBY_VERSION`
  - `rvm_alias_expanded`
  - `rvm_bin_flag`
  - `rvm_docs_type`
  - `rvm_gemstone_package_file`
  - `rvm_gemstone_url`
  - `rvm_niceness`
  - `rvm_nightly_flag`
  - `rvm_only_path_flag`
  - `rvm_pretty_print_flag`
  - `rvm_proxy`
  - `rvm_quiet_flag`
  - `rvm_ruby_bits`
  - `rvm_ruby_file`
  - `rvm_ruby_make`
  - `rvm_ruby_make_install`
  - `rvm_ruby_mode`
  - `rvm_script_name`
  - `rvm_sdk`
  - `rvm_silent_flag`
  - `rvm_use_flag`
  - `rvm_hook`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/qiulang/.rvm/gems/ruby-2.5.1/bin:/Users/qiulang/.rvm/gems/ruby-2.5.1@global/bin:/Users/qiulang/.rvm/rubies/ruby-2.5.1/bin:/Users/qiulang/.nodenv/shims:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/qiulang/.rvm/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `zh_CN.UTF-8`
  - `PWD`: `/Users/qiulang/Dev/t2/pyenv_test`

---------------------------

Contents of `Pipfile` ('/Users/qiulang/Dev/t2/pyenv_test/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
pexpect = "==4.8.0"
termcolor = "==1.1.0"

[dev-packages]

[requires]
python_version = "3.8"

```

Contents of `Pipfile.lock` ('/Users/qiulang/Dev/t2/pyenv_test/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "2279312f2ac060eb551621dfdb41beb4078ebad37b55ac553e3e6a7444a46966"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "pexpect": {
            "hashes": [
                "sha256:0b48a55dcb3c05f3329815901ea4fc1537514d6ba867a152b581d69ae3710937",
                "sha256:fc65a43959d153d0114afe13997d439c22823a27cefceb5ff35c2178c6784c0c"
            ],
            "index": "pypi",
            "version": "==4.8.0"
        },
        "ptyprocess": {
            "hashes": [
                "sha256:923f299cc5ad920c68f2bc0bc98b75b9f838b93b599941a6b63ddbc2476394c0",
                "sha256:d7cc528d76e76342423ca640335bd3633420dc1366f258cb31d05e865ef5ca1f"
            ],
            "version": "==0.6.0"
        },
        "termcolor": {
            "hashes": [
                "sha256:1d6d69ce66211143803fbc56652b41d73b4a400a2891d7bf7a1cdf4c02de613b"
            ],
            "index": "pypi",
            "version": "==1.1.0"
        }
    },
    "develop": {}
}

```
</details>

**Comment by frostming** [comment]
I think both issues are invalid.

1. The venv is not recreated, it just reuses the existing one which is python 3.8. You may need to delete `Pipfile`, run `pipenv --rm` and redo the above steps, then Python 3.9 should be chosen.

2. It works this way `pipenv lock -r` lists all dependencies and transient dependencies that are locked in `Pipfile.lock`. There is a significant difference between abstract requirements(your original `requirements.txt`) and concrete requirements.

**Comment by qiulang** [comment]
Thanks for replying my issue. For the second issue I also run [pipreqs](https://pypi.org/project/pipreqs/) to verify that it doesn't list ptyprocess as an requirement. Since ptyprocess is a package used pexpect. Why still list it in requirement.txt. Shouldn't list pexpect==4.8.0 be enough ?

**Comment by frostming** [comment]
`pipreqs` scans py files and analyze import statements to generate requirements. You don't import `ptyprocess` explicitly so it is not listed.

> Why still list it in requirement.txt? Shouldn't list pexpect==4.8.0 be enough ?

Didn't I make it clear? Pipenv will list all dependencies and **sub-dependencies**， assuming they are installed without dependencies.

**Comment by qiulang** [comment]
I will give requirement.txt to others who have not used pipenv (yet).  I really think the requirement.txt with

```
pexpect==4.8.0
termcolor==1.1.0
```

is enough, no need for 

```
pexpect==4.8.0
ptyprocess==0.6.0
termcolor==1.1.0
```

**Comment by frostming** [comment]
But Pipenv works in the second way, clear?

**Comment by qiulang** [comment]
I check pexpect's setup.py   https://github.com/pexpect/pexpect/blob/master/setup.py

`install_requires=['ptyprocess>=0.5'],`

So now I see why pipenv list ptyprocess==0.6.0 as an requirement (for pexpect 4.8.0)

Thanks!

**Comment by qiulang** [comment]
@frostming may I ask another question regarding my 1st issue? 

I am always confused with venv and virtualenv used by pipenv. The pipenv document I read always said pipenv use virtualenv under the hood. If this is the case why did pipenv read my virtual environment setting created by vnenv ?

**Comment by qiulang** [comment]
I hit the first problem again. `pipevn -rm` didn't fix that, it still chose 3.8 and report strange problem.

**Comment by frostming** [comment]
> If this is the case why did pipenv read my virtual environment setting created by vnenv ?

It just reuses the existing one whether it is created by venv or virtualenv.

**Comment by frostming** [comment]
Close this one, leave #4547 open
