### ISSUE TITLE
pipenv install does not use the system python3 and report another python3 version issue.

### ISSUE THREAD

**Issue by qiulang** [pypa/pipenv#4547]
The following screenshot said my issue clearly.  I first run `pipenv --rm` to remove existing venv then `pipenv install `, pipenv chose **3.8** while I use **3.9**. But an error pop up said it hit the error with **3.6**.

<img width="1171" alt="Screen Shot 2020-11-27 at 12 07 10 PM" src="https://user-images.githubusercontent.com/516243/100410582-264baf80-30aa-11eb-830f-63101fcda480.png">

pyenv_test ➤ pipenv --rm                                                                                                  
Removing virtualenv (/Users/qiulang/.local/share/virtualenvs/pyenv_test-8P5GrENk)...
pyenv_test ➤ pipenv install                                                                                               
Creating a virtualenv for this project...
Pipfile: /Users/qiulang/Dev/tmp/pyenv_test/Pipfile
Using /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 (3.8.6) to create virtualenv...
⠧ Creating virtual environment...created virtual environment CPython3.8.6.final.0-64 in 440ms
  creator CPython3Posix(dest=/Users/qiulang/.local/share/virtualenvs/pyenv_test-8P5GrENk, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/qiulang/Library/Application Support/virtualenv)
    added seed packages: pip==20.2.4, setuptools==50.3.2, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/qiulang/.local/share/virtualenvs/pyenv_test-8P5GrENk
Installing dependencies from Pipfile.lock (c9a7fb)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/4 — 00:00:07
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
pyenv_test ➤ pipenv --venv                                                                            
/Users/qiulang/.local/share/virtualenvs/pyenv_test-8P5GrENk
pyenv_test ➤ which python3                                                                               
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3

I opened (closed) an related issue https://github.com/pypa/pipenv/issues/4546

Thanks!

**Comment by frostming** [comment]
You must have `python_version=3.8` in `Pipfile`, which is respected by Pipenv

**Comment by qiulang** [comment]
You were right, I did have python_version=3.8 in Pipfile. After I changed it to 3.9 pipenv chose the system python 3.9

But that "python cannot be opened" warning still exist, only I delete all the venv in `/Users/qiulang/.local/share/virtualenvs/` did that disappear.

**Comment by qiulang** [comment]
If I keep other venv in `/Users/qiulang/.local/share/virtualenvs/ `, sometime it complained 3.5 error

<img width="1073" alt="Screen Shot 2020-11-25 at 4 36 33 PM" src="https://user-images.githubusercontent.com/516243/100423681-59e90280-30c7-11eb-925a-2a4f2592b475.png">

**Comment by frostming** [comment]
Just clear all the invalid installations in the paths shown in the error message

**Comment by qiulang** [comment]
But I don't have python 3.5 & 3.6 in my path now.

echo $PATH     
/Users/qiulang/.rvm/gems/ruby-2.5.1/bin:/Users/qiulang/.rvm/gems/ruby-2.5.1@global/bin:/Users/qiulang/.rvm/rubies/ruby-2.5.1/bin:/Users/qiulang/.nodenv/shims:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/qiulang/.rvm/bin

**Comment by matteius** [comment]
@qiulang Do you still require support with this?

**Comment by qiulang** [comment]
@matteius  thanks for reaching out but that was in 2020.  I have not used pipenv for a while so I will just close it.
