### ISSUE TITLE
pytest pinned to <5 but the tests work fine with the latest version of pytest

### ISSUE THREAD

**Issue by oz123** [pypa/pipenv#4559]
I was able to run the test with the current version of pytest.

The pinning is done [here](https://github.com/pypa/pipenv/blob/48e1f18930aec29d3d8dc1e346a7726f5d324907/setup.py#L45).
I was not able to determine with git blame why this was done.

Also, a small suggestion:

Formatting the list like this:
```
    "tests": ["pytest<5.0", 
                 "pytest-timeout",
                 "pytest-xdist<2.0",
                 "flaky",
                 "mock"],
```
As done with the `dev` requirements will allow committing just the changes in the corresponding version of a library.
Will you accept a PR to break the list to multiple lines and remove the version pinning?

**Comment by matteius** [comment]
Since that line is now pytest>=5.0:  https://github.com/pypa/pipenv/blob/main/setup.py#L41

Closing this issue.
