### ISSUE TITLE
How do I run scripts?

### ISSUE THREAD

**Issue by aprilahijriyan** [pypa/pipenv#4575]
Hi,

I'm currently creating a simple template using pipenv. However, I have a problem running scripts. See here https://github.com/aprilahijriyan/fullstack-zemfrog-nuxtjs for more details.

I've tried the manual method, like this:

```
mkdir zemenv && cd zemenv
pipenv install zemfrog
pipenv shell
zemfrog create backend && cd backend
pip install -r requirements.txt
flask
```

The above works for me, but I don't want the manual method. :(

**Comment by Mause** [comment]
The documentation for creating scripts is here: https://pipenv-fork.readthedocs.io/en/latest/advanced.html#custom-script-shortcuts

**Comment by aprilahijriyan** [comment]
Have you seen the script on my repo?

**Comment by Mause** [comment]
I don't see any issues with the scripts in your repository.

To run scripts, as is documented at that link, you do `pipenv run script_name`

**Comment by aprilahijriyan** [comment]
The issue is I can't run the flask application. You can try to run it by: 

```
pipenv shell
cd backend
flask # the application is not detected by the flask command.
```

To compare, you can do the manual method above.

**Comment by Mause** [comment]
What is the exact error you are getting? And why do you think it's related to pipenv?

**Comment by aprilahijriyan** [comment]
I got this, after I ran the command:

```
pipenv shell
cd backend
flask
```

Output:

```
flask.cli.NoAppException: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
```

Expected output:

```
Usage: flask [OPTIONS] COMMAND [ARGS]...

  A general utility script for Flask applications.

  Provides commands from Flask, extensions, and the application. Loads the
  application defined in the FLASK_APP environment variable, or from a
  wsgi.py file. Setting the FLASK_ENV environment variable to 'development'
  will enable debug mode.

    $ export FLASK_APP=hello.py
    $ export FLASK_ENV=development
    $ flask run

Options:
  --version  Show the flask version
  --help     Show this message and exit.

Commands:
  api         API generator.
  app         App generator.
  blueprint   Blueprint generator.
  command     Command generator.
  db          Perform database migrations.
  extension   Extension generator.
  handler     Error handler generator.
  loader      Loader generator.
  middleware  Middleware generator.
  model       Model generator.
  permission  Role permission manager.
  role        Access role manager.
  routes      Show the routes for the app.
  run         Run a development server.
  shell       Runs a shell in the app context.
  task        Task generator.
  user        User manager.
```

**Comment by aprilahijriyan** [comment]
> I've tried the manual method, like this:
> 
> ```
> mkdir zemenv && cd zemenv
> pipenv install zemfrog
> pipenv shell
> zemfrog create backend && cd backend
> pip install -r requirements.txt
> flask
> ```
> 
> The above works for me, but I don't want the manual method. :(

And I think it's related to Pipenv. Because, I've tried the manual way it works as expected.

**Comment by Mause** [comment]
The reason why it's failing is because when the flask cli tries to load the environment settings, it loads it from the .env file in your repository, and then sets that folder as the current working directory. Then it cannot find your flask app in the current directory.

If you remove this file, or rename it, then it will work as expected. So, nothing to do with pipenv.

**Comment by aprilahijriyan** [comment]
So I can't use `.env` ??

**Comment by aprilahijriyan** [comment]
Ahh, it's solved! by adding the `FLASK_SKIP_DOTENV=1` configuration to `.env`.
So I closed this issue. Thank you in advance.
