### ISSUE TITLE
CI Mode Needed

### ISSUE THREAD

**Issue by caruso-billfire** [pypa/pipenv#4581]
### Is your feature request related to a problem? Please describe.

Hello, when running pipenv commands such as `pipenv install --dev` 
our build logs get full of lines like.  

`⠹ Creating virtual environment...·`
`⠼ Locking...·` 

There are hundreds of these lines because each time the spinner moves it produces a new log entry. 
maybe `PIPENV_QUIET` should quiet this down? 

### Describe the solution you'd like

We need a setting or a ci mode to only print terminal / log friendly lines.

**Comment by frostming** [comment]
That is already supported by setting `PIPENV_NOSPIN=1`

**Comment by caruso-billfire** [comment]
Ah, sorry about that. I failed to find that flag, thanks!
