### ISSUE TITLE
Pipenv not creating virtual environment

### ISSUE THREAD

**Issue by romeopeter** [pypa/pipenv#4589]
I have Pipenv installed but it does not create a virtual environment when I run the `pipenv shell` command. Before this, I use the built-in `VENV`, but decided to switch to Pipenv for a deterministic build. How do I resolve the issue?

OS environment:
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'c:\\users\\romeo\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pipenv'`

Python location: `'c:\\users\\romeo\\appdata\\local\\programs\\python\\python37\\python.exe'`

Python installations found:

  - `3.7.1`: `C:\Users\Romeo\AppData\Local\Programs\Python\Python37\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.1',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.18362',
 'python_full_version': '3.7.1',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DRIVERDATA`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `WINDIR`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

PipenvΓÇôspecific environment variables:

DebugΓÇôspecific environment variables:

  - `PATH`: `C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\xampp\php;C:\composer;C:\Program Files\nodejs\;C:\PostgreSQL\pg11\bin;C:\Program Files\MongoDB\Server\4.2\bin;C:\Program Files\PuTTY\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\xampp\php;C:\composer;C:\Program Files\nodejs\;C:\PostgreSQL\pg11\bin;C:\Program Files\MongoDB\Server\4.2\bin;C:\Program Files\PuTTY\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\Romeo\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\Romeo\AppData\Local\Programs\Python\Python37\;C:\Program Files (x86)\Nmap;C:\Users\Romeo\AppData\Local\Microsoft\WindowsApps;C:\Users\Romeo\AppData\Roaming\Composer\vendor\bin;C:\Users\Romeo\AppData\Roaming\npm;C:\Program Files\Sublime Text 3;C:\projects\automation-projects\download_cleanup;C:\Program Files (x86)\geckodriver-v0.25.0-win64;C:\projects\electrosoft\electrosoft;C:\Program Files\Mozilla Firefox;;C:\Users\Romeo\AppData\Roaming\Python\Python37\Scripts`

---------------------------

</details>

The Error:
```Creating a virtualenv for this project...
Pipfile: C:\projects\shmairfreightbot\Pipfile
Using C:/Users/Romeo/AppData/Local/Programs/Python/Python37/python.exe (3.7.1) to create virtualenv...
[    ] Creating virtual environment...FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\romeo\\appdata\\local\\programs\\python\\python37\\Lib\\venv\\scripts\\nt\\python.exe'

Failed creating virtual environment

[pipenv.exceptions.VirtualenvCreationException]:
Failed to create virtual environment.```

**Comment by frostming** [comment]
Can you show the output of the command with `PIPENV_VERBOSE=1` `PIPENV_NOSPIN=1`

**Comment by romeopeter** [comment]
Could you show me how to implement this? Do pass the verbose commands as a switch to the `pipenv shell` command?
Sorry for the late reply, ...been quite busy.

**Comment by cnrmck** [comment]
@romeopeter you would probably run `PIPENV_VERBOSE=1 PIPENV_NOSPIN=1 pipenv shell`

**Comment by romeopeter** [comment]
> @romeopeter you would probably run `$ PIPENV_VERBOSE=1 PIPENV_NOSPIN=1 pipenv shell`

I ran it just as you said, but it didn't work. 
I got this output error: 
`'PIPENV_VERBOSE' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by Mause** [comment]
Well that's windows for you
