### ISSUE TITLE
Pipenv REQUIRES 3.7 and refuses to run on 3.8

### ISSUE THREAD

**Issue by boxabirds** [pypa/pipenv#4590]
### Issue description

`pipenv install` fails when the only versions of python I have are 2.7 or 3.8.x

### Expected result

That pipenv supports python 3.8+

### Actual result

```
Warning: Python 3.7 was not found on your system…
You can specify specific versions of Python with:
  $ pipenv --python path/to/python
:~/$ python --version
Python 3.8.5
```

This wouldn't be so problematic if it weren't so difficult to specifically instal python 3.7 these days.

**Comment by jakobkogler** [comment]
Can you describe better what you want to accomplish?
Do you have an existing `Pipfile` and `Pipfile.lock` (e.g. from cloning a repository from colleges), or do you execute the command in a fresh empty directory?

---

If you start with a fresh directory, have you tried the suggestion that you got with the warning?
```sh
pipenv --python path/to/python
```

---

If you already have a `Pipfile` / `Pipfile.lock`, I could imagine that you have the line 
```cfg
[requires]
python_version = "3.7"
```
in the `Pipfile`, and corresponding locks in the `Pipfile.lock`.
You can still use a different version, with the same command `pipenv --python path/to/python`, or by changing the line in the Pipfile.
However be warned, it is probably not a good idea as dependencies for 3.7 and 3.8 might differ.
If you want to collaborate on this project with colleges, you should all use the same version.

---

And btw, how difficult is it to install different Python versions today? It's simpler than ever before. Just install them with `pyenv`.

```sh
# installation
pyenv install 3.7.9
# activate it in this directory
# (optional, pipenv should find 3.7 automatically if installed with pyenv)
pyenv local 3.7.9
```

**Comment by boxabirds** [comment]
Firstly, pipenv has been so so useful for me so I want to underscore how
amazing it’s been handling multiple projects. Truly fantastic. Thank you to
all involved!

Can you help me understand why pipenv doesn’t run with recent / default
versions of python out of the box? If I have time I shall try to test it
against 3.8 & 3.9.

The suggestions about installing through pyenv doesn’t make much sense to
me personally: pyenv isn’t included in any distros I’m aware of but maybe
it’s more common than my own limited experience.

At the very least if pipenv is firmly not to support 3.8, 3.9. or future
versions, it’d be great if when it failed that it provided clear
instructions on how to get it going. What do you think? It could be simply
“please install pyenv so you can then install python 3.7…? Though maybe the
install process could be simpler.

**Comment by jakobkogler** [comment]
`pipenv` does support 3.8 and later.

Maybe try answering the questions that I asked and give a more detailed problem description.
And post the output of `pipenv --support`, and the `Pipfile` (if you have any).

---

`pyenv` is included in my distro :grinning: . But even if it's not, you should be able to install it it within one or two minutes. It's just one git clone, and adding a couple of lines to the `.bashrc`. And there's even an automatic installer.

**Comment by boxabirds** [comment]
I tried running it with /usr/bin/python pointing at 3.8 but it would not
run. Only when I installed 3.7 did it work.

**Comment by frostming** [comment]
@boxabirds That is because you have the line in your `Pipfiile`:
```toml
[requires]
python_version = "3.7"
```

**Comment by andreif** [comment]
Pipenv's Python version detection is weird af. When I use 3.8 then it tells me that it does use 3.8 while creating virtualenv and then puts 3.9 in the Pipfile. But when I use 3.9, it tells me that it uses 3.9 but puts 3.8 in Pipfile. The only way to make do what you want is to set it explicitly as argument to first run command.

**Comment by matteius** [comment]
This is an older issue and we know that pipenv definitely runs fine on newer versions of Python, so I am closing this down.
