### ISSUE TITLE
Documentation of `pipfile_dir` environment variable

### ISSUE THREAD

**Issue by smac89** [pypa/pipenv#4592]
### Is your feature request related to a problem? Please describe.

I just wanted to know if this variable is documented anywhere and whether or not I can rely on it to get the location of the virtualenv directory

### Describe the solution you'd like

Would like to see some documentation on this

Thanks for your time!

**Comment by matteius** [comment]
I could not find that environment variable in the code base going back many versions, even to 2018.11.26.     I don't believe it is a supported variable or something we should document.
