### ISSUE TITLE
Cannot get pipenv to work on Windows 10 under PowerShell 5.1

### ISSUE THREAD

**Issue by sockduct** [pypa/pipenv#4601]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.
* I confirmed I am running the latest version of pipenv from PyPI (pip install -U pipenv)

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.
* I do not see my issue listed here.

Make sure to mention your debugging experience if the documented solution failed.
* N/A

### Issue description

Describe the issue briefly here.
* Windows 10, PowerShell v5.1, pipenv install django~=3.1.0 => Creates virtual environment, installs django v3.1, good
* pipenv shell => Creates a second virtual environment, puts me in this new virtual environment which doesn't have django, bad

### Expected result

Describe what you expected.
* When running "pipenv shell", expected it to drop me into the virtual environment just created with django
* Note:  If I go through the above two steps on Ubuntu 20, it works as expected.

### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.
* As described above, running "pipenv shell" creates a new virtual environment (2nd one) and activates it.  This new virtual environment is missing django (pipenv install django~=3.1.0).

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).
* As requested - running commands with --verbose flag:
```
C:\working\champlain\sdev435\testing\django4> pipenv --verbose install django~=3.1.0
Using python: None
Path to python: C:/Program Files (x86)/Python38-32/python.exe
Creating a virtualenv for this project...
Pipfile: C:\working\champlain\sdev435\testing\django4\Pipfile
Using C:/Program Files (x86)/Python38-32/python.exe (3.8.7) to create virtualenv...
[ ===] Creating virtual environment...created virtual environment CPython3.8.7.final.0-32 in 1196ms
  creator CPython3Windows(dest=C:\Users\js646y\.virtualenvs\django4-lyKDhicu, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\js646y\AppData\Local\pypa\virtualenv)
    added seed packages: pip==20.3.3, setuptools==51.1.2, wheel==0.36.2
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Successfully created virtual environment!
Virtualenv location: C:\Users\js646y\.virtualenvs\django4-lyKDhicu
Creating a Pipfile for this project...
Installing django~=3.1.0...
Installing package: django~=3.1.0
Writing supplied requirement line to temporary file: 'django~=3.1.0'
Installing 'django'
[ ===] Installing django...$ ['C:\\Users\\js646y\\.virtualenvs\\django4-lyKDhicu\\Scripts\\pip.exe', 'install', '--verbose', '--upgrade', '--exists-action=i', '-r', 'c:\\users\\js646y\\appdata\\local\\temp\\pipenv-k8v0gj3c-requirements\\pipenv-b_ypbkwe-requirement
.txt', '-i', 'https://pypi.org/simple']
Using source directory: 'C:\\Users\\js646y\\.virtualenvs\\django4-lyKDhicu\\src'
Adding django to Pipfile's [packages]...
Installation Succeeded
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
           Building requirements...
Resolving dependencies...
[    ] Locking...
                          ROUND 1
Current constraints:
  django~=3.1.0 (from -r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))

Finding the best candidates:
[   =] Locking...  found candidate django==3.1.5 (constraint was ~=3.1.0)

Finding secondary dependencies:
  django==3.1.5             requires asgiref<4,>=3.2.10, pytz, sqlparse>=0.2.2

New dependencies found in this round:
  adding ['asgiref', '<4,>=3.2.10', '[]']
  adding ['pytz', '', '[]']
  adding ['sqlparse', '>=0.2.2', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  asgiref<4,>=3.2.10 (from django==3.1.5->-r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))
  django~=3.1.0 (from -r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))
  pytz (from django==3.1.5->-r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))
  sqlparse>=0.2.2 (from django==3.1.5->-r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))

Finding the best candidates:
  found candidate asgiref==3.3.1 (constraint was >=3.2.10,<4)
  found candidate django==3.1.5 (constraint was ~=3.1.0)
  found candidate pytz==2020.5 (constraint was <any>)
  found candidate sqlparse==0.4.1 (constraint was >=0.2.2)

Finding secondary dependencies:
  sqlparse==0.4.1           requires -
  asgiref==3.3.1            requires -
  pytz==2020.5              requires -
  django==3.1.5             requires asgiref<4,>=3.2.10, pytz, sqlparse>=0.2.2
------------------------------------------------------------
Result of round 2: stable, done

Generating hashes:
  asgiref
  sqlparse
  django
  pytz
ROUND 1
Current constraints:
  django~=3.1.0 (from -r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))

Finding the best candidates:
  found candidate django==3.1.5 (constraint was ~=3.1.0)

Finding secondary dependencies:
  django==3.1.5             requires asgiref<4,>=3.2.10, pytz, sqlparse>=0.2.2

New dependencies found in this round:
  adding ['asgiref', '<4,>=3.2.10', '[]']
  adding ['pytz', '', '[]']
  adding ['sqlparse', '>=0.2.2', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  asgiref<4,>=3.2.10 (from django==3.1.5->-r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))
  django~=3.1.0 (from -r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))
  pytz (from django==3.1.5->-r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))
  sqlparse>=0.2.2 (from django==3.1.5->-r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))

Finding the best candidates:
  found candidate asgiref==3.3.1 (constraint was >=3.2.10,<4)
  found candidate django==3.1.5 (constraint was ~=3.1.0)
  found candidate pytz==2020.5 (constraint was <any>)
  found candidate sqlparse==0.4.1 (constraint was >=0.2.2)

Finding secondary dependencies:
  sqlparse==0.4.1           requires -
  asgiref==3.3.1            requires -
  pytz==2020.5              requires -
  django==3.1.5             requires asgiref<4,>=3.2.10, pytz, sqlparse>=0.2.2
------------------------------------------------------------
Result of round 2: stable, done

Generating hashes:
  asgiref
  sqlparse
  django
  pytz
Success!
Warning: ROUND 1
Current constraints:
  django~=3.1.0 (from -r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))

Finding the best candidates:
  found candidate django==3.1.5 (constraint was ~=3.1.0)

Finding secondary dependencies:
  django==3.1.5             requires asgiref<4,>=3.2.10, pytz, sqlparse>=0.2.2

New dependencies found in this round:
  adding ['asgiref', '<4,>=3.2.10', '[]']
  adding ['pytz', '', '[]']
  adding ['sqlparse', '>=0.2.2', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  asgiref<4,>=3.2.10 (from django==3.1.5->-r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))
  django~=3.1.0 (from -r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))
  pytz (from django==3.1.5->-r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))
  sqlparse>=0.2.2 (from django==3.1.5->-r C:\Users\js646y\AppData\Local\Temp\pipenv520j2yelrequirements\pipenv-p71pi8ob-constraints.txt (line 2))

Finding the best candidates:
  found candidate asgiref==3.3.1 (constraint was >=3.2.10,<4)
  found candidate django==3.1.5 (constraint was ~=3.1.0)
  found candidate pytz==2020.5 (constraint was <any>)
  found candidate sqlparse==0.4.1 (constraint was >=0.2.2)

Finding secondary dependencies:
  sqlparse==0.4.1           requires -
  asgiref==3.3.1            requires -
  pytz==2020.5              requires -
  django==3.1.5             requires asgiref<4,>=3.2.10, pytz, sqlparse>=0.2.2
------------------------------------------------------------
Result of round 2: stable, done

Generating hashes:
  asgiref
  sqlparse
  django
  pytz
Updated Pipfile.lock (2f196d)!
Installing dependencies from Pipfile.lock (2f196d)...
  ================================ 0/0 - 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.


C:\working\champlain\sdev435\testing\django4> pipenv --verbose shell
Creating a virtualenv for this project...
Pipfile: C:\Users\js646y\Documents\Projects-NB\Champlain\SDEV435\testing\django4\Pipfile
Using C:/Program Files (x86)/Python38-32/python.exe (3.8.7) to create virtualenv...
[   =] Creating virtual environment...created virtual environment CPython3.8.7.final.0-32 in 1257ms
  creator CPython3Windows(dest=C:\Users\js646y\.virtualenvs\django4-t19PPNhy, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\js646y\AppData\Local\pypa\virtualenv)
    added seed packages: pip==20.3.3, setuptools==51.1.2, wheel==0.36.2
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Successfully created virtual environment!
Virtualenv location: C:\Users\js646y\.virtualenvs\django4-t19PPNhy
Launching subshell in virtual environment...
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Found ssh-agent at 16944
Found ssh-agent socket at /tmp/ssh-sgxWESbC1FxR/agent.889
Loading personal and system profiles took 3501ms.
C:\Users\js646y\Documents\Projects-NB\Champlain\SDEV435\testing\django4>


* Pipfile contents:
C:\Users\js646y\Documents\Projects-NB\Champlain\SDEV435\testing\django4> gc Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "~=3.1.0"

[dev-packages]

[requires]
python_version = "3.8"
```

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip
* Using Windows:
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'c:\\program files (x86)\\python38-32\\lib\\site-packages\\pipenv'`

Python location: `'c:\\program files (x86)\\python38-32\\python.exe'`

Python installations found:

  - `3.8.7`: `C:\Users\js646y\.virtualenvs\django4-t19PPNhy\Scripts\python.exe`
  - `3.8.7`: `C:\Users\js646y\.virtualenvs\django4-t19PPNhy\Scripts\python.exe`
  - `3.8.7`: `C:\Program Files (x86)\Python38-32\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.7',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17763',
 'python_full_version': '3.8.7',
 'python_version': '3.8',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `ANSICON`
  - `ANSICON_DEF`
  - `APPDATA`
  - `ASL.LOG`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `CONEMUANSI`
  - `CONEMUANSILOG`
  - `CONEMUARGS`
  - `CONEMUARGS2`
  - `CONEMUBACKHWND`
  - `CONEMUBASEDIR`
  - `CONEMUBASEDIRSHORT`
  - `CONEMUBUILD`
  - `CONEMUCFGDIR`
  - `CONEMUCONFIG`
  - `CONEMUDIR`
  - `CONEMUDRAWHWND`
  - `CONEMUDRIVE`
  - `CONEMUHOOKS`
  - `CONEMUHWND`
  - `CONEMUPALETTE`
  - `CONEMUPID`
  - `CONEMUSERVERPID`
  - `CONEMUTASK`
  - `CONEMUWORKDIR`
  - `CONEMUWORKDRIVE`
  - `DRIVERDATA`
  - `DRU_APP_DIR`
  - `DRU_BIN_DIR`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `HOME`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `JAVA_HOME`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NEEDSCCMCLIENT`
  - `NUMBER_OF_PROCESSORS`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PIPENV_ACTIVE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_ARCHITEW6432`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `QIP12604`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `UATDATA`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VIRTUAL_ENV`
  - `WINDIR`
  - `PIP_SHIMS_BASE_MODULE`

Pipenv???specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug???specific environment variables:

  - `PATH`: `C:\Users\js646y\.virtualenvs\django4-t19PPNhy\Scripts;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files (x86)\Python38-32\Scripts\;C:\Program Files (x86)\Python38-32\;C:\Program Files (x86)\RSA SecurID Token Common;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Java\jre1.8.0_251\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Enterprise Vault\EVClient\x64\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Webex\Webex\Applications;C:\Program Files\1E\Client\Extensibility\NomadBranch;C:\Program Files\Git\cmd;C:\Users\js646y\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Vim\vim82;C:\Working\Programs;.;C:\Program Files (x86)\LLVM\bin;C:\Program Files\heroku\bin`
  - `VIRTUAL_ENV`: `C:\Users\js646y\.virtualenvs\django4-t19PPNhy`

---------------------------

Contents of `Pipfile` ('C:\\Users\\js646y\\Documents\\Projects-NB\\Champlain\\SDEV435\\testing\\django4\\Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "~=3.1.0"

[dev-packages]

[requires]
python_version = "3.8"

```

Contents of `Pipfile.lock` ('C:\\Users\\js646y\\Documents\\Projects-NB\\Champlain\\SDEV435\\testing\\django4\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "ff6cef0868859afaec16a1b39006f468fa5303495ddaea7d2ce477680d2f196d"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "asgiref": {
            "hashes": [
                "sha256:5ee950735509d04eb673bd7f7120f8fa1c9e2df495394992c73234d526907e17",
                "sha256:7162a3cb30ab0609f1a4c95938fd73e8604f63bdba516a7f7d64b83ff09478f0"
            ],
            "markers": "python_version >= '3.5'",
            "version": "==3.3.1"
        },
        "django": {
            "hashes": [
                "sha256:2d78425ba74c7a1a74b196058b261b9733a8570782f4e2828974777ccca7edf7",
                "sha256:efa2ab96b33b20c2182db93147a0c3cd7769d418926f9e9f140a60dca7c64ca9"
            ],
            "index": "pypi",
            "version": "==3.1.5"
        },
        "pytz": {
            "hashes": [
                "sha256:16962c5fb8db4a8f63a26646d8886e9d769b6c511543557bc84e9569fb9a9cb4",
                "sha256:180befebb1927b16f6b57101720075a984c019ac16b1b7575673bea42c6c3da5"
            ],
            "version": "==2020.5"
        },
        "sqlparse": {
            "hashes": [
                "sha256:017cde379adbd6a1f15a61873f43e8274179378e95ef3fede90b5aa64d304ed0",
                "sha256:0f91fd2e829c44362cbcfab3e9ae12e22badaa8a29ad5ff599f9ec109f0454e8"
            ],
            "markers": "python_version >= '3.5'",
            "version": "==0.4.1"
        }
    },
    "develop": {}
}

```
</details>

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by matteius** [comment]
@sockduct It appears you are using a very outdated version Pipenv version: `2020.11.15`
There are some nice fixes for windows in the master branch, or even the current release probably is a much better experience:  `2022.1.8`

Please try that and also it is recommended that you do a `--user` install of pipenv as opposed the system install you have now.

Try:
`pip uninstall pipenv`
`pip install pipenv --user`
Add the location to your local scripts path where pipenv got installed, for me that was: 
`C:\Users\matte\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts`
