### ISSUE TITLE
Add option to disable venv mention in prompt

### ISSUE THREAD

**Issue by ItsDrike** [pypa/pipenv#4608]
### Is your feature request related to a problem? Please describe.

I'm making my own prompt theme and I designed a function which is using `$VIRTUAL_ENV` variable to check if the user is in virtual environment and printing that to the prompt. It works nicely, but the problem occurs when it comes to pipenv, because it tries to add the venv name in brackets to the beginning of the prompt itself, this is annoying because I have to then disable my feature in prompt, because otherwise, there would be 2 information about venv, 1 made by pipenv, and 1 mine.

![image](https://user-images.githubusercontent.com/20902250/106282787-6281c480-6241-11eb-860f-7b5a6747111e.png)

### Describe the solution you'd like

There should be an environmental variable such as `PIPENV_DISABLE_PROMPT`, which if set, the prompt shouldn't be automatically generated like this.

### Describe alternatives you've considered

I handled it by making an exception if `$PIPENV_ENV` was set, but I'd prefer to have the ability to disable pipenv's prompt so that I can use mine instead.

**Comment by vidhanio** [comment]
For me,
```zsh
export VIRTUAL_ENV_DISABLE_PROMPT=1
```
works to disable it.

**Comment by matteius** [comment]
@ItsDrike is describing a feature of virtualenv and not pipenv so I am closing this issue.  @vidhanio solution should be sufficient.
