### ISSUE TITLE
Latency for pipenv commands

### ISSUE THREAD

**Issue by sampotter** [pypa/pipenv#4617]
After installing pipenv and trying it out, it seems that every command has significant latency. For example:

```sh
sfp@Samuels-MacBook-Pro blah % time pipenv --version
pipenv, version 2020.8.13
pipenv --version  0.57s user 0.14s system 99% cpu 0.713 total
```

No command that I run takes less than ~0.5-0.6s, so presumably there is some operation being run that takes a significant amount of time, regardless of what is being done. E.g., if I run `time pipenv`, it takes about the same amount of time. (Of course, many other commands take significantly longer if they're doing real work!)

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.8.13'`

Pipenv location: `'/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv'`

Python location: `'/opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8'`

Python installations found:

  - `3.8.7`: `/opt/local/bin/python3.8`
  - `3.8.2`: `/usr/bin/python3`
  - `3.7.9`: `/opt/local/bin/python3`
  - `3.7.9`: `/opt/local/bin/python3.7m`
  - `3.7.9`: `/opt/local/bin/python3.7`
  - `2.7.18`: `/opt/local/bin/python2`
  - `2.7.18`: `/opt/local/bin/python2.7`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '19.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST '
                     '2020; root:xnu-6153.141.10~1/RELEASE_X86_64',
 'python_full_version': '3.8.7',
 'python_version': '3.8',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_SESSION_ID`
  - `SSH_AUTH_SOCK`
  - `LC_TERMINAL_VERSION`
  - `COLORFGBG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `LANG`
  - `PWD`
  - `SHELL`
  - `TERM_PROGRAM_VERSION`
  - `TERM_PROGRAM`
  - `PATH`
  - `DISPLAY`
  - `LC_TERMINAL`
  - `COLORTERM`
  - `TERM`
  - `HOME`
  - `TMPDIR`
  - `USER`
  - `XPC_SERVICE_NAME`
  - `LOGNAME`
  - `ITERM_SESSION_ID`
  - `__CF_USER_TEXT_ENCODING`
  - `SHLVL`
  - `OLDPWD`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/sfp/.cabal/bin:/Users/sfp/.ghcup/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Applications/Skim.app/Contents/SharedSupport:/opt/X11/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/sfp/LocalWorkspace/blah`

---------------------------

Contents of `Pipfile` ('/Users/sfp/LocalWorkspace/blah/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "3.8"

```

</details>

**Comment by phaseOne** [comment]
I'm seeing this is well; glad I'm not the only one. It must be a resource-bound operation, as the time increases on lower powered platforms. It makes working on a Raspberry Pi Zero W quite painfully slow.

It's the same delay if I'm in an actual project, or just in an empty folder.

```
pi@raspberrypi:~/emptyenv $ time pipenv --version
pipenv, version 2020.11.15

real    0m14.107s
user    0m13.346s
sys     0m0.702s
```

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'/usr/local/lib/python3.7/dist-packages/pipenv'`

Python location: `'/usr/bin/python3.7'`

Python installations found:

  - `3.7.3`: `/usr/bin/python3.7`
  - `3.7.3`: `/usr/bin/python3`
  - `3.7.3`: `/usr/bin/python3.7m`
  - `3.7.3`: `/bin/python3.7`
  - `3.7.3`: `/bin/python3`
  - `3.7.3`: `/bin/python3.7m`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`
  - `2.7.16`: `/bin/python2`
  - `2.7.16`: `/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.3',
 'os_name': 'posix',
 'platform_machine': 'armv6l',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.83+',
 'platform_system': 'Linux',
 'platform_version': '#1379 Mon Dec 14 13:06:05 GMT 2020',
 'python_full_version': '3.7.3',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `PIPENV_ACTIVE`
  - `NO_AT_BRIDGE`
  - `PWD`
  - `LOGNAME`
  - `XDG_SESSION_TYPE`
  - `PIP_PYTHON_PATH`
  - `HOME`
  - `LANG`
  - `LS_COLORS`
  - `SSH_CONNECTION`
  - `XDG_SESSION_CLASS`
  - `TERM`
  - `USER`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `SHLVL`
  - `XDG_SESSION_ID`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_RUNTIME_DIR`
  - `PS1`
  - `SSH_CLIENT`
  - `PATH`
  - `MAIL`
  - `SSH_TTY`
  - `OLDPWD`
  - `TEXTDOMAIN`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/pi/emptyenv`


---------------------------

</details>

**Comment by phaseOne** [comment]
IDK if I'm using cProfile correctly, so take this with a grain of salt 🧂: It seems the biggest offender is the `click` module. Not sure where to go from here. Maybe profile `click` and look at the source to see what's actually happening, and/or see if there's an update to that module and submit a PR if it helps with the speed?

<details><summary>Expand to see what commands I ran</summary>

I ran this on my RPi Zero.

```shell
python3 -m cProfile -o pipenv.profile /usr/local/bin/pipenv --where
```

And then inspected the results on my main machine in a Jupyter notebook.

```python
import cProfile, pstats, io
from pstats import Stats

Stats("pipenv.profile").sort_stats('cumtime').print_stats(.01)
```

</details>

<details><summary>Expand to see top 1% of calls sorted by cumulative time</summary>

```
         670967 function calls (648539 primitive calls) in 18.317 seconds

   Ordered by: cumulative time
   List reduced from 5293 to 53 due to restriction <0.01>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   1018/1    0.157    0.000   18.434   18.434 {built-in method builtins.exec}
        1    0.000    0.000   18.434   18.434 /usr/local/bin/pipenv:3(<module>)
   1026/2    0.143    0.000   18.387    9.193 <frozen importlib._bootstrap>:978(_find_and_load)
   1015/2    0.100    0.000   18.385    9.193 <frozen importlib._bootstrap>:948(_find_and_load_unlocked)
    959/2    0.113    0.000   18.375    9.188 <frozen importlib._bootstrap>:663(_load_unlocked)
    880/2    0.064    0.000   18.373    9.187 <frozen importlib._bootstrap_external>:722(exec_module)
   1177/2    0.015    0.000   18.360    9.180 <frozen importlib._bootstrap>:211(_call_with_frames_removed)
   311/40    0.020    0.000   14.572    0.364 {built-in method builtins.__import__}
        1    0.000    0.000   12.208   12.208 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py:827(__call__)
        1    0.000    0.000   12.208   12.208 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py:716(main)
        1    0.000    0.000   12.196   12.196 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py:680(make_context)
        1    0.000    0.000   12.195   12.195 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py:1207(parse_args)
        1    0.000    0.000   12.195   12.195 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py:1039(parse_args)
        1    0.000    0.000   12.177   12.177 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py:962(make_parser)
        2    0.000    0.000   12.171    6.086 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py:910(get_params)
        2    0.001    0.000   12.171    6.086 /usr/local/lib/python3.7/dist-packages/pipenv/cli/options.py:26(get_help_option)
        1    0.001    0.001   12.153   12.153 /usr/local/lib/python3.7/dist-packages/pipenv/core.py:2(<module>)
        1    0.001    0.001   11.959   11.959 /usr/local/lib/python3.7/dist-packages/pipenv/project.py:2(<module>)
        1    0.001    0.001    9.587    9.587 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/requirementslib/__init__.py:2(<module>)
        1    0.001    0.001    9.539    9.539 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/requirementslib/models/lockfile.py:2(<module>)
3333/1644    0.057    0.000    8.826    0.005 <frozen importlib._bootstrap>:1009(_handle_fromlist)
        1    0.001    0.001    6.736    6.736 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/requirementslib/utils.py:2(<module>)
        1    0.000    0.000    6.717    6.717 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/pip_shims/__init__.py:21(<module>)
        1    0.000    0.000    6.708    6.708 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/pip_shims/shims.py:4(<module>)
        1    0.006    0.006    6.653    6.653 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/pip_shims/models.py:4(<module>)
    28/16    0.001    0.000    6.497    0.406 /usr/lib/python3.7/importlib/__init__.py:109(import_module)
    31/16    0.001    0.000    6.496    0.406 <frozen importlib._bootstrap>:994(_gcd_import)
        5    0.000    0.000    6.415    1.283 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/pip_shims/models.py:748(shim)
        5    0.000    0.000    6.407    1.281 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/pip_shims/models.py:740(traverse)
        5    0.000    0.000    6.407    1.281 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/pip_shims/models.py:588(shim)
        5    0.000    0.000    6.404    1.281 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/pip_shims/models.py:609(_import)
        1    0.000    0.000    6.396    6.396 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/pip_shims/models.py:701(add_mixin)
        5    0.000    0.000    6.372    1.274 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/pip_shims/models.py:357(_import_module)
        1    0.001    0.001    6.350    6.350 /usr/local/lib/python3.7/dist-packages/pipenv/patched/notpip/_internal/cli/req_command.py:6(<module>)
        1    0.001    0.001    6.207    6.207 /usr/local/lib/python3.7/dist-packages/pipenv/__init__.py:7(<module>)
      752    0.082    0.000    4.207    0.006 /usr/lib/python3.7/re.py:271(_compile)
      471    0.007    0.000    4.183    0.009 /usr/lib/python3.7/re.py:232(compile)
      306    0.047    0.000    4.047    0.013 /usr/lib/python3.7/sre_compile.py:759(compile)
        1    0.000    0.000    3.059    3.059 /usr/local/lib/python3.7/dist-packages/pipenv/cli/__init__.py:2(<module>)
        1    0.004    0.004    3.051    3.051 /usr/local/lib/python3.7/dist-packages/pipenv/cli/command.py:2(<module>)
  989/957    0.212    0.000    2.609    0.003 <frozen importlib._bootstrap>:882(_find_spec)
      306    0.027    0.000    2.572    0.008 /usr/lib/python3.7/sre_parse.py:919(parse)
2340/2293    0.641    0.000    2.526    0.001 {built-in method builtins.__build_class__}
 1156/306    0.102    0.000    2.508    0.008 /usr/lib/python3.7/sre_parse.py:417(_parse_sub)
 1503/319    0.831    0.001    2.473    0.008 /usr/lib/python3.7/sre_parse.py:475(_parse)
      880    0.191    0.000    2.290    0.003 <frozen importlib._bootstrap_external>:793(get_code)
        1    0.001    0.001    2.196    2.196 /usr/local/lib/python3.7/dist-packages/pipenv/vendor/urllib3/__init__.py:3(<module>)
        1    0.001    0.001    2.169    2.169 /usr/local/lib/python3.7/dist-packages/pipenv/patched/notpip/_internal/cli/base_command.py:1(<module>)
        1    0.001    0.001    2.104    2.104 /usr/local/lib/python3.7/dist-packages/pipenv/patched/notpip/_internal/index/package_finder.py:1(<module>)
        1    0.001    0.001    2.057    2.057 /usr/local/lib/python3.7/dist-packages/pipenv/environment.py:2(<module>)
        1    0.001    0.001    2.036    2.036 /usr/local/lib/python3.7/dist-packages/pipenv/patched/notpip/_internal/index/collector.py:3(<module>)
        1    0.001    0.001    2.023    2.023 /usr/local/lib/python3.7/dist-packages/pipenv/cli/options.py:2(<module>)
        1    0.002    0.002    1.979    1.979 /usr/local/lib/python3.7/dist-packages/pipenv/utils.py:2(<module>)
```

</details>

**Comment by matteius** [comment]
Is this still an issue with newer versions such as `pipenv==2021.11.23`?

**Comment by sampotter** [comment]
I am no longer using Pipenv, so I can't comment.
