### ISSUE TITLE
pipenv sync should uninstall packages that have been removed from lockfile

### ISSUE THREAD

**Issue by wosc** [pypa/pipenv#4621]
### Issue description

My mental model for `pipenv sync` is "make the state of the virtualenv be exactly like what's described in Pipfile.lock". Thus, I would expect `pipenv sync` to uninstall any packages that are installed in the virtualenv, but not mentioned in the lockfile. Currently however, those packages simply are left as-is.

### Steps to replicate

```shell
$ pipenv install requests
$ pipenv run python -c 'import requests'  # this works, of course :)
$ sed -i -e '/^requests =/d' Pipfile
$ pipenv lock
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Updated Pipfile.lock (16c839)!
$ pipenv sync
Installing dependencies from Pipfile.lock (fe5a22)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!
$ pipenv run python -c 'import requests'  # expected result: ModuleNotFoundError, actual result: it still works
```

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`
Pipenv location: `'/Users/schnerring/install/tools/lib/python3.9/site-packages/pipenv'`
Python location: `'/Users/schnerring/install/tools/bin/python3'`

Python installations found:

  - `3.9.1`: `/usr/local/bin/python3`
  - `3.9.1`: `/usr/local/bin/python3.9`
  - `3.8.7`: `/usr/local/bin/python3.8`
  - `3.7.9`: `/usr/local/bin/python3.7`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.1',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST '
                     '2021; root:xnu-4903.278.56~1/RELEASE_X86_64',
 'python_full_version': '3.9.1',
 'python_version': '3.9',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `ANDROID_SDK_ROOT`
  - `Apple_PubSub_Socket_Render`
  - `COLORFGBG`
  - `COLORTERM`
  - `COMMAND_MODE`
  - `EDITOR`
  - `HOME`
  - `LANG`
  - `LC_ALL`
  - `LC_CTYPE`
  - `LC_TERMINAL`
  - `LC_TERMINAL_VERSION`
  - `LESS_TERMCAP_md`
  - `LESS_TERMCAP_me`
  - `LESS_TERMCAP_se`
  - `LESS_TERMCAP_ue`
  - `LESS_TERMCAP_us`
  - `LOGNAME`
  - `PATH`
  - `PIPENV_IGNORE_VIRTUALENVS`
  - `PWD`
  - `PYTHONSTARTUP`
  - `SECURITYSESSIONID`
  - `SHELL`
  - `SHLVL`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `TMPDIR`
  - `USER`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_IGNORE_VIRTUALENVS`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/schnerring/bin:/usr/local/bin:/Users/schnerring/.krew/bin:/usr/bin:/bin:/usr/sbin:/sbin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `emacs-minimal`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/schnerring`
---------------------------
</details>

**Comment by januszm** [comment]
Honestly, I wouldn't expect pipenv sync to remove any package. I'd expect it to only make sure that all packages mentioned in Pipfile.lock are available locally in the version specified there. For example, if I want to temporarily use a debugger or just ipython, I can install it with `pip install ...` but not modify Pipfile / Pipfile.lock, since it'd be a temporary attempt.
Perhaps I am wrong, but, it works similarly in the Ruby world (where I spend more time), where the `bundle` command ensures that from among several available package versions, only the one from the .lock file will be used in the runtime.

**Comment by wosc** [comment]
Hmm, I guess that's my "deployment" perspective showing, then (in contrast to "application/library development"). From that point of view, removing unused things is rather important functionality, since that's quite the regular occurrence: you update a library to a new version, now it no longer depends on that other thing -- even more tricky when "other thing" declares setuptools entrypoints or whatnot. In that scenario it's not feasible to manually `pipenv uninstall` the unused thing from 50 production installations. (I _guess_ this gets less relevant when using containers, since those are recreated more or less from scratch, but not everything uses containers, by far.)

**Comment by januszm** [comment]
@wosc on the second thought, I think such an "environment reset" option could be very helpful. Something that works like `git reset --hard`, ie leaves only packages that are checked-in in the lockfile. My only doubt was that this was a destructive action and currently sync is expected to install the necessary packages.

By the way, I think pipenv commands could be simplified considerably to:
```
pipenv install # install packages specified in the lockfile, do not update anything!
pipenv update # re-generate the lockfile using "fresh" versions of packages from Pipfile respecting their coinstraints
pipenv reset # uninstall anything not in lockfile
```
the only remaining question is whether we should install main and "dev" dependencies by default or only main.

**Comment by Mause** [comment]
Is your `pipenv reset` just `pipenv clean`?

> Uninstalls all packages not specified in Pipfile.lock.

**Comment by januszm** [comment]
@Mause you're right! So as for the two, it can be resolved with an alias on the user's end.  So the only thing on my "pipenv wish list" is that pipenv install should behave predictably, i.e. install only what is in .lock, and in the case of specifying the package name (`pipenv install somepackage`), modify the .lock only in the "somepackage" dependency tree - I noticed that installing a new package updates unrelated other packages in .lock. But that's a different story, unrelated to @wosc  issue.

**Comment by frostming** [comment]
It is just a separated command: `pipenv clean`. Combine those commands by `pipenv sync && pipenv clean` should do the trick

**Comment by wosc** [comment]
Oh. Yes. Execellent. Sorry that I didn't look at the docs carefully enough to spot this. Thanks for letting me know!
