### ISSUE TITLE
[Question] Is python 3.8 and 3.9 supported?

### ISSUE THREAD

**Issue by dashsatish** [pypa/pipenv#4624]
**AVOID POSTING ISSUES UNDER THIS CATEGORY.**

Is pipenv execution supported in python 3.8 and 3.9?

If Pipenv is not functioning as you would like it to, consider filing either a bug report, or a feature request instead.

Please refer to [StackOverflow tag](https://stackoverflow.com/questions/tagged/pipenv) for more information.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by matteius** [comment]
@dashsatish Yes at this point in time pipenv is supported in python 3.8, 3.9 and 3.10.  Recommended stable versions are possibly latest `2021.11.23` or `2021.5.29`.
