### ISSUE TITLE
pipenv shell should have envvar option to block bare pip usage

### ISSUE THREAD

**Issue by vaughnkoch** [pypa/pipenv#4634]
### Problem

`pipenv shell` currently allows bare `pip` commands to be executed inside the shell, which means that you can `pip install foo` and have package `foo` available to your Python code, but not have `foo` present in the `Pipfile` or `Pipfile.lock`.

In practice, that means that a developer's tests will pass locally, but not once the code is pushed to a CI test suite.

### Proposed solution

Provide an environment variable to be passed to `pipenv shell` which will block bare `pip` access, or at least output a warning when it's used.

### Describe alternatives you've considered

Another possibility would be for `pipenv shell` to warn the user when it detects packages that are in the virtualenv, but aren't in the Pipfile. However, this would only trigger when new shells are launched.

### Additional context

Versions:

```
Python 3.9.1
pipenv, version 2020.11.15
```

Note: not running `pipenv --support` here because it has nonpublic information and isn't relevant to this feature request.
Apologies if this is a known issue - it's hard to search the issues list for this particular problem.

**Comment by matteius** [comment]
@vaughnkoch I don't believe we want to block pip usage -- for myself, I often want to pip install something for use in my own virtualenv in the project space but not check that in to the project in the Pipfile and Pipfile.lock  and I believe other users do similar.

I believe it is better to just take more time reviewing the command being entered.
