### ISSUE TITLE
Obsolete except condition

### ISSUE THREAD

**Issue by mavriq** [pypa/pipenv#4638]
https://github.com/pypa/pipenv/blob/bf7203148e1e0f57ab86b652d76135f17bf66927/pipenv/patched/yaml2/reader.py#L163

It take me problem when i run
```sh
python3 -m compileall ...
```

**Comment by frostming** [comment]
Yaml2 is the code for Python2 and it should be touched on Python3

**Comment by mavriq** [comment]
this code is required for version python=2.5 and earlier

Are you sure you need support for these versions?

In the [setup.py](/pypa/pipenv/blob/master/setup.py#L156-L161) anonced support for version 2.7 and higher
Also version of python older than 2.7 not supported for a long time 

I propose to replace all
 `except <exception>, exc:`
to
`except <exception> as exc:`
everywhere

If required, I can make pull-request

Why do I need it:
`python -m compileall` helps to additionally check the code for syntax errors
and also slightly speeds up the code

And because `compileall` finds this obsolete code it breaks
