### ISSUE TITLE
How to merge pipenv directory with github repo directory?

### ISSUE THREAD

**Issue by Mahesha999** [pypa/pipenv#4639]
I started by setting pipenv:
   
    > cd project-xyz
    project-xyz> pip install pipenv
    project-xyz> pipenv shell
    (project-xyz-pCe_s2ig) project-xyz> pipenv install package-xyv

Then I created github repo with name `repo-xyz`. Now how can I clone github repo so that it will contain the pipenv's lock file or pipfile created above? I tried to hack it around a bit. I cloned the repo in new folder, which created `repo-xyz`. Then I copied `Pipfile` and `Pipfile.lock` from `project-xyz` to `repo-xyz` and then ran `pipenv shell`. It ended creating clean new virtual environment. it did not use existing `project-xyz` environment. Do I have to reinstall everything from lock file in my repo folder by creating new pipenv? Is there any way to reuse existing pipenv inside new folder? Or I am trying to do something completely weird?

**Update**

I obtained my venv path by running `pipenv --venv`:

    (proj-pCe_s2ig) project-xyz> pipenv -venv
    path-to-venv

Then exited the venv:

    (project-xyz-pCe_s2ig) project-xyz> exit

    project-xyz>

Then I changed directory to folder where I checked out repo:

    repo-xyz>

And explicitly activated vnev from there:

    repo-xyz> path-to-venv\Scripts\activate
    (project-xyz) repo-xyz> 

Notice that, it says `(project-xyz)`, not `(project-xyz-pCe_s2ig)`. So I felt that it only activated internal `virtualenv` and `pipenv` functionality is not going to work. So, I tried to list installed packages using `pipenv`:

    (project-xyz) repo-xyz> pipenv lock -r
    Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can 
    set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.

    -i https://pypi.org/simple
    package-xyz==0.0.0

So, it seems that pipenv is indeed working when we invoke it from venv activated by explicitly invoking `path-to-venv\Scripts\activate`. So, just to make it sure, I tried to install package using `pipenv`:

    (project-xyz) repo-xyz> pipenv install package-abc

    (project-xyz) repo-xyz> pipenv lock -r
    Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can 
    set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.

    -i https://pypi.org/simple
    package-xyz==0.0.0
    package-abc==0.0.0

This also added the entry for `package-abc` in `repo-xyz\Pipfile` (note `repo-xyz`) correctly. So, I guess everything is working fine, only that it shows `(project-xyz)` instead of `(project-xyz-pCe_s2ig)`. Can anyone tell 

**Q1.** if its all fine here?  
**Q2.** why it shows `(project-xyz)` instead of `(project-xyz-pCe_s2ig)`?  
**Q3.** if above has any consequence?

**Comment by frostming** [comment]
> Now how can I clone github repo so that it will contain the pipenv's lock file or pipfile created above?

It is a matter of git skills, you can track an existing project with an **empty** git repo as below:

```bash
cd project-xyz
git init
git remote add origin <your_repo_url>
git fetch origin
git push -u origin master
```

> Q2. why it shows (project-xyz) instead of (project-xyz-pCe_s2ig)?

Yes, Pipenv doesn't take charge when you activate directly by the activate script, which somehow trims the suffix.

> Q3. if above has any consequence?

No, it is fine

**Comment by matteius** [comment]
@Mahesha999 -- Can this be closed or are you looking for any additional support?
