### ISSUE TITLE
How to install packages using -f flag, such as when installing Pytorch?

### ISSUE THREAD

**Issue by DanielPerezJensen** [pypa/pipenv#4641]
I need to install a certain version of Pytorch that I can use with a certain version of Cuda. Normally when using pip I'd install it in the following way:

`pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html`

But when I run that using pipenv, so in the following way:

`pipenv install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html`

I get the following error:

```
Installing torch==1.7.1+cu110...
Error:  An error occurred while installing torch==1.7.1+cu110!
Error text: 
ERROR: Could not find a version that satisfies the requirement torch==1.7.1+cu110
ERROR: No matching distribution found for torch==1.7.1+cu110
```

What is the proper way to handle this using pipenv? Simply to install it using pip anyway, or something else?

These installations instructions come from the [Pytorch getting started guide](https://pytorch.org/get-started/locally/).

**Comment by shamoons** [comment]
I have the same issue. Created [this](https://github.com/pypa/pipenv/issues/4649), but perhaps we can close one as a dupe?

**Comment by DanielPerezJensen** [comment]
Ah yes we can close it then, I'll refer to yours!

**Comment by DanielPerezJensen** [comment]
Ah yes, I'll close this one and refer to yours.

**Comment by DanielPerezJensen** [comment]
Also raised in issue #4649
