### ISSUE TITLE
Pipenv installs inappropriate version of package

### ISSUE THREAD

**Issue by 1beb** [pypa/pipenv#4667]
### Issue description

Pipenv appears to load an older version of a PyPi package than requested. Using the following pipfile only: 

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "*"
django-rest-framework = "*"
django-rest-framework-social-oauth2 = "*"
django-cors-headers = "*"
rest-social-auth = "6.0.0"

[dev-packages]
black = "*"

[requires]
python_version = "3.8"

[pipenv]
allow_prereleases = true
```  

```
$ mkdir test_pipenv
$ cd test_pipenv 
test_pipenv $ nano Pipfile # copy/paste above Pipfile
test_pipenv $ pipenv install
test_pipenv $ pipenv shell
Launching subshell in virtual environment...
 . /home/beb/.local/share/virtualenvs/test_pipenv-SgZtyA2Y/bin/activate
➜  test_pipenv  . /home/beb/.local/share/virtualenvs/test_pipenv-SgZtyA2Y/bin/activate
(test_pipenv) ➜  test_pipenv $ exit
➜  test_pipenv $ cd /home/beb/.local/share/virtualenvs/test_pipenv-SgZtyA2Y/
➜  test_pipenv-SgZtyA2Y $ ls lib/python3.8/site-packages/rest_social_auth
__init__.py  serializers.py  urls_jwt_pair.py  urls_jwt_sliding.py  urls_session.py  views.py
__pycache__  strategy.py     urls_jwt.py       urls_knox.py         urls_token.py
```

The file, `urls_jwt.py` no longer exists in 6.0.0. But it says that it has installed 6.0.0.

```
➜  test_pipenv-SgZtyA2Y $ cd lib/python3.8/site-packages/  
➜  site-packages $ ls | grep rest_social
rest_social_auth
rest_social_auth-6.0.0.dist-info
```
For verification, I downloaded the current gzip from PyPi (https://files.pythonhosted.org/packages/74/22/d65152c1869aaff369034d46d1af5b02ec461a794908de6bfab6a9ba0540/rest_social_auth-6.0.0.tar.gz) and verified that this file (urls_jwt.py) is not included as it shouldn't be.

### Expected result

Expected `rest-social-auth` 6.0.0 to be loaded, however the files that are loaded in the environment are from an earlier 4.X version release that does not match what is on PyPi.  

### Actual result

Installed some other version of the package. Had to manually install with `pip3`.

### Steps to replicate

Provided in description.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.4'`

Pipenv location: `'/usr/local/lib/python3.8/dist-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.8.6`: `/usr/bin/python3`
  - `3.8.6`: `/usr/bin/python3.8`
  - `3.8.6`: `/bin/python3`
  - `3.8.6`: `/bin/python3.8`
  - `2.7.18`: `/usr/bin/python2.7`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/bin/python2.7`
  - `2.7.18`: `/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.11.0-7612-generic',
 'platform_system': 'Linux',
 'platform_version': '#13~1616168001~20.10~cf74746-Ubuntu SMP Mon Mar 29 '
                     '17:37:00 UTC ',
 'python_full_version': '3.8.6',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `GJS_DEBUG_TOPICS`
  - `SSH_AUTH_SOCK`
  - `SESSION_MANAGER`
  - `PAPERSIZE`
  - `GNOME_TERMINAL_SCREEN`
  - `LANGUAGE`
  - `SSH_AGENT_PID`
  - `LC_IDENTIFICATION`
  - `DEFAULTS_PATH`
  - `DISPLAY`
  - `XDG_CURRENT_DESKTOP`
  - `COLORTERM`
  - `LANG`
  - `GPG_AGENT_INFO`
  - `USER`
  - `DESKTOP_SESSION`
  - `XDG_MENU_PREFIX`
  - `HOME`
  - `GJS_DEBUG_OUTPUT`
  - `LC_MEASUREMENT`
  - `QT_IM_MODULE`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `PWD`
  - `LC_NUMERIC`
  - `_`
  - `GTK_MODULES`
  - `WINDOWPATH`
  - `XDG_SESSION_DESKTOP`
  - `XDG_CONFIG_DIRS`
  - `GTK_IM_MODULE`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LC_TIME`
  - `MANDATORY_PATH`
  - `LOGNAME`
  - `QT_ACCESSIBILITY`
  - `GNOME_TERMINAL_SERVICE`
  - `LC_PAPER`
  - `PATH`
  - `XDG_RUNTIME_DIR`
  - `XMODIFIERS`
  - `XDG_SESSION_TYPE`
  - `LC_MONETARY`
  - `GNOME_SHELL_SESSION_MODE`
  - `LC_TELEPHONE`
  - `USERNAME`
  - `SHELL`
  - `VTE_VERSION`
  - `SHLVL`
  - `XAUTHORITY`
  - `XDG_DATA_DIRS`
  - `LC_NAME`
  - `TERM`
  - `LC_ADDRESS`
  - `XDG_SESSION_CLASS`
  - `GDMSESSION`
  - `OLDPWD`
  - `ZSH`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `LS_COLORS`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/beb/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/beb`

---------------------------

</details>

**Comment by frostming** [comment]
This is not the case, indeed the wheel file is the one being used in installed. And it contains that file.
