### ISSUE TITLE
Ability to run a file

### ISSUE THREAD

**Issue by trusktr** [pypa/pipenv#4669]
F.e. something like `pipenv run -f ./path/to/foo.py`.

### Is your feature request related to a problem? Please describe.

It seems the only way to run a file is to use `pipenv shell`, then run the file, but that has downsides when trying to write scripts that run outside the virtual env and need to start the env.

### Describe the solution you'd like

```sh
pipenv run --file any/file.py
```

### Additional context

-------------------------------------------------------------------------------

<details><summary><code>$ pipenv --support</code></summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'/home/trusktr/.local/lib/python3.9/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.9.2`: `/usr/bin/python3.9`
  - `3.9.2`: `/usr/bin/python3`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.105-1-MANJARO',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Thu Mar 11 18:27:58 UTC 2021',
 'python_full_version': '3.9.2',
 'python_version': '3.9',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SSH_AUTH_SOCK`
  - `SESSION_MANAGER`
  - `GNOME_TERMINAL_SCREEN`
  - `LANG`
  - `XDG_CURRENT_DESKTOP`
  - `COLORTERM`
  - `GTK3_MODULES`
  - `LC_IDENTIFICATION`
  - `PWD`
  - `USER`
  - `HOME`
  - `XDG_MENU_PREFIX`
  - `LC_MEASUREMENT`
  - `DESKTOP_SESSION`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `LC_NUMERIC`
  - `XDG_DATA_DIRS`
  - `WINDOWPATH`
  - `XDG_SESSION_DESKTOP`
  - `VTE_VERSION`
  - `LC_TIME`
  - `MAIL`
  - `LOGNAME`
  - `GNOME_TERMINAL_SERVICE`
  - `LC_PAPER`
  - `PATH`
  - `XDG_RUNTIME_DIR`
  - `SHELL`
  - `XDG_SESSION_TYPE`
  - `LC_MONETARY`
  - `LC_TELEPHONE`
  - `EDITOR`
  - `USERNAME`
  - `MOTD_SHOWN`
  - `GDM_LANG`
  - `SHLVL`
  - `XAUTHORITY`
  - `QT_QPA_PLATFORMTHEME`
  - `LC_NAME`
  - `DISPLAY`
  - `TERM`
  - `LC_ADDRESS`
  - `XDG_SESSION_CLASS`
  - `GDMSESSION`
  - `OLDPWD`
  - `ZDOTDIR`
  - `ANTIGEN_DEFAULT_REPO_URL`
  - `ADOTDIR`
  - `_ANTIGEN_LOG_PATH`
  - `ANTIGEN_COMPDUMPFILE`
  - `_ZCACHE_PATH`
  - `_ZCACHE_PAYLOAD_PATH`
  - `_ZCACHE_BUNDLES_PATH`
  - `_ZCACHE_EXTENSION_CLEAN_FUNCTIONS`
  - `_ZCACHE_EXTENSION_BUNDLE`
  - `ZSH`
  - `ZSH_CACHE_DIR`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `LS_COLORS`
  - `_ANTIGEN_BUNDLE_RECORD`
  - `_ZCACHE_CACHE_LOADED`
  - `_ZCACHE_CACHE_VERSION`
  - `NEW_PWD`
  - `NODE_PATH`
  - `N_PREFIX`
  - `VISUAL`
  - `GOPATH`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/trusktr/.npm-packages/bin:/home/linuxbrew/.linuxbrew/bin:/home/trusktr/go/bin:/home/trusktr/.n-node-versions/bin:/home/trusktr/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/trusktr/.local/bin:/home/trusktr/.gem/ruby/1.9.1/bin:/home/trusktr/.gem/ruby/2.2.0/bin:/usr/local/bin:/home/trusktr/.vim/bundle/fzf/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `EDITOR`: `nvim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/trusktr`

---------------------------

</details>

**Comment by uranusjr** [comment]
What's wrong with `pipenv run python ...`?

**Comment by trusktr** [comment]
Ah, I didn't realize it was any command. That indeed works.

I'm new to python in general, and my first guess was to simply try `pipenv run ./foo.py`. It'd be convenient and intuitive if that worked.

**Comment by uranusjr** [comment]
It would if you [`chmod +x`](https://askubuntu.com/a/443799) and add a [shebang](https://stackoverflow.com/a/19305076) to the file.
