### ISSUE TITLE
pipenv installs Django 3.2 instead of the version in the pipfile

### ISSUE THREAD

**Issue by sant527** [pypa/pipenv#4674]
### Issue description

I want to install Django 3.1.2 but it installs 3.2

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
Django = "3.1.2"

[requires]
python_version = "3.7"
```

### Expected result

Expecting Django 3.1.2

### Actual result

Installs Django 3.2

### Steps to replicate

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'/usr/local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Python installations found:

  - `3.7.9`: `/home/simha/app/.venv/bin/python3`
  - `3.7.9`: `/home/simha/app/.venv/bin/python3.7`
  - `3.7.9`: `/home/simha/app/.venv/bin/python3.7m`
  - `3.7.9`: `/home/simha/app/.venv/bin/python3`
  - `3.7.9`: `/home/simha/app/.venv/bin/python3.7`
  - `3.7.9`: `/home/simha/app/.venv/bin/python3.7m`
  - `3.7.9`: `/usr/local/bin/python3.7`
  - `3.7.9`: `/usr/local/bin/python3.7m`
  - `3.7.9`: `/usr/local/bin/python3`
  - `3.7.3`: `/usr/bin/python3.7`
  - `3.7.3`: `/usr/bin/python3.7m`
  - `3.7.3`: `/usr/bin/python3`
  - `2.7.16`: `/usr/bin/python2.7`
  - `2.7.16`: `/usr/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.9',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.0.5-arch1-1-ARCH',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Wed Mar 27 17:53:10 UTC 2019',
 'python_full_version': '3.7.9',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `PIPENV_VENV_IN_PROJECT`
  - `PYTHONUNBUFFERED`
  - `PIPENV_ACTIVE`
  - `HOSTNAME`
  - `PYTHON_VERSION`
  - `PWD`
  - `PIP_PYTHON_PATH`
  - `HOME`
  - `LANG`
  - `LS_COLORS`
  - `VIRTUAL_ENV`
  - `GPG_KEY`
  - `WERKZEUG_DEBUG_PIN`
  - `SQLPRINT`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `TERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `SHLVL`
  - `PYTHON_PIP_VERSION`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHON_GET_PIP_SHA256`
  - `PS1`
  - `PYTHON_GET_PIP_URL`
  - `PATH`
  - `DEBUG`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`
 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/simha/app/.venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/home/simha/app`
  - `VIRTUAL_ENV`: `/home/simha/app/.venv`

---------------------------

Contents of `Pipfile` ('/home/simha/app/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
Django = "3.1.2"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/home/simha/app/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "cb8733cd7cf5db153090ba5a12398959d375d27237ba8d5254d3d1de6bc9e788"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "asgiref": {
            "hashes": [
                "sha256:92906c611ce6c967347bbfea733f13d6313901d54dcca88195eaeb52b2a8e8ee",
                "sha256:d1216dfbdfb63826470995d31caed36225dcaf34f182e0fa257a4dd9e86f1b78"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==3.3.4"
        },
        "django": {
            "hashes": [
                "sha256:0604e84c4fb698a5e53e5857b5aea945b2f19a18f25f10b8748dbdf935788927",
                "sha256:21f0f9643722675976004eb683c55d33c05486f94506672df3d6a141546f389d"
            ],
            "index": "pypi",
            "version": "==3.2"
        },
        "pytz": {
            "hashes": [
                "sha256:83a4a90894bf38e243cf052c8b58f381bfe9a7a483f6a9cab140bc7f702ac4da",
                "sha256:eb10ce3e7736052ed3623d49975ce333bcd712c7bb19a58b9e2089d4057d0798"
            ],
            "version": "==2021.1"
        },
        "sqlparse": {
            "hashes": [
                "sha256:017cde379adbd6a1f15a61873f43e8274179378e95ef3fede90b5aa64d304ed0",
                "sha256:0f91fd2e829c44362cbcfab3e9ae12e22badaa8a29ad5ff599f9ec109f0454e8"
            ],
            "markers": "python_version >= '3.5'",
            "version": "==0.4.1"
        },
        "typing-extensions": {
            "hashes": [
                "sha256:7cb407020f00f7bfc3cb3e7881628838e69d8f3fcab2f64742a5e76b2f841918",
                "sha256:99d4073b617d30288f569d3f13d2bd7548c3a7e4c8de87db09a9d29bb3a4a60c",
                "sha256:dafc7639cde7f1b6e1acc0f457842a83e722ccca8eef5270af2d74792619a89f"
            ],
            "markers": "python_version < '3.8'",
            "version": "==3.7.4.3"
        }
    },
    "develop": {}
}

```
</details>

**Comment by sant527** [comment]
I found the mistake

in pipfile i have to use
```
Django = "==3.1.2"
```
instead of 

```
Django = "3.1.2"
```

**Comment by frostming** [comment]
Yes you got it
