### ISSUE TITLE
Installation of packages

### ISSUE THREAD

**Issue by MITRA-S** [pypa/pipenv#4676]
Hello, I am interested in DIG to use for now sslgraph package. 
I downloaded the codes from github. However, I cannot install the packages  by doing 
pip install git+git://github.com/divelab/DIG.git ,
inside a conda environment.
This immediately gives errors. 
ERROR: Command errored out with exit status1: python setup.py egg_info Check the logs for full command output.

Do you have any suggestion? Is there a setup.py file available? 
Thank you.

**Comment by Mause** [comment]
This repository is for support and bug reports for pipenv, not DIG?

**Comment by MITRA-S** [comment]
Oh. Sorry. I should post in another thread.
Thank you,
Saheli
