### ISSUE TITLE
Pipenv ignores pip version in Pipfile/Pipfile.lock

### ISSUE THREAD

**Issue by AlbertoEAF** [pypa/pipenv#4680]
### Issue description

Pipenv does not install pip in the version specified in the Pipfile/Pipfile.lock.

### Expected/actual result

`pipenv sync` should install the pip version specified in the lock file / Pipfile. It ignores it.

### Steps to replicate

do a `pipenv install pip==X`, lock it if needed and then manually do `pipenv run pip install pip==Y`.

When doing `pipenv sync`, the proper pip version in the pipfile/pipfile.lock is ignored.

-------------------------------------------------------------------------------

My pipenv is the latest release: v2020.11.15.

Thank you

**Comment by frostming** [comment]
pip, setuptools cannot be managed by pipenv, this is a constraint.

**Comment by AlbertoEAF** [comment]
Thank you for the reply.
