### ISSUE TITLE
Pipenv with Fiona on MacOS BigSur 11.1

### ISSUE THREAD

**Issue by GHCamille** [pypa/pipenv#4682]
Hello, 

### Issue description

I'm on a MacBook Air (M1), with MacOS BigSur 11.1.

I've installed Fiona in a pipenv, Python 3.9.1, and when I import Fiona, I get the following : 

```
ImportError: dlopen([path_to_my_pipenv_venv]/lib/python3.9/site-packages/fiona/ogrext.cpython-39-darwin.so, 2): Symbol not found: _CPLCheckForFile
  Referenced from: [path_to_my_pipenv_venv]/lib/python3.9/site-packages/fiona/ogrext.cpython-39-darwin.so
  Expected in: flat namespace
 in [path_to_my_pipenv_venv]/lib/python3.9/site-packages/fiona/ogrext.cpython-39-darwin.so
```

I really don't understand what I should do ... My pipenv looks fine, I've tried uninstalling/reinstalling Fiona with different versions, but I'm always getting the same mistake.

Do you have any idea what the problem is ?

### Expected result

I have another project running just fine with the same version of Fiona (Fiona==1.8.18), but without the pipenv.

This import shouldn't be a problem. 

-------------------------------------------------------------------------------

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

throws nothing ...

**Comment by frostming** [comment]
Check if it works via pip: `pipenv run pip install fiona`

**Comment by GHCamille** [comment]
Thank you for your answer. It throws the exact same error ...

**Comment by frostming** [comment]
It not related to Pipenv, please report it to Fiona
