### ISSUE TITLE
tests parallel running

### ISSUE THREAD

**Issue by odatskiv** [pypa/pipenv#4697]
Hello everyone, 

I'm running the command _**pipenv run pytest**_ and I see that I use only one process. Can I use all the resources of my cpu to speed up the execution of this command.

![image](https://user-images.githubusercontent.com/83705903/118156670-4f76b700-b422-11eb-986d-be4025f18ea3.png)

Thank you all for your help

**Comment by oz123** [comment]
Sure take a look at:

https://pypi.org/project/pytest-xdist/

You can patch `setup.cfg` locally:
```
[tool:pytest]
addopts = -ra -n auto
plugins = xdist
addopts = -ra
```

**Comment by matteius** [comment]
@oz123 I've noticed though that we have `pytest-xdist` in the lock file already somehow, it continues to get added and when adding pytest-cov I had to have the `parallel = True` marker to get the coverage report to assemble properly, so I think somehow it is running in parallel to some extent already.

**Comment by oz123** [comment]
On my machine the tests aren't running in parallel without:
```
diff --git a/setup.cfg b/setup.cfg
index 7f76f1ff..3828db4e 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -45,6 +45,7 @@ mypy_path=typeshed/pyi:typeshed/imports
 
 [tool:pytest]
 addopts = -ra
+plugins = xdist
 testpaths = tests
 ; Add vendor and patched in addition to the default list of ignored dirs
 ; Additionally, ignore tasks, news, test subdirectories and peeps directory
```

The requirements for testing had already `pytest-xdist`, but it wasn't running with `make tests`
