### ISSUE TITLE
Is pulling semver and iso8601 needed?

### ISSUE THREAD

**Issue by befeleme** [pypa/pipenv#4698]
### Issue description

Is pulling semver and iso8601 needed?

I am going through the list of pipenv dependencies for testing purposes in Fedora. 

When looking for ways to invoke functionalities of the vendored libraries I realized, nothing really imports `semver`. 
`pipenv/vendor/distlib` uses some semver matching, but it has no connection to the actual library.

semver is imported in `tests/test_artifacts/git/pinax/check.py` where it seems it's isolated from the production code - alongside with github3 or tabulate which are also not vendored. I guess (as I don't know the codebase that much) that wherever the artifacts are used, they are isolated and pull the needed libraries from the internet resources.

To check the hypothesis I've removed semver and rerun tests with the same good results as before. 
I assume it may be safely removed, but I may have overlooked something. 

Another thing is bundling iso8601 which is not used anywhere. `pyparsing.py` uses `iso8601_date` and `iso8601_datetime`, but they're defined there, not imported from the library. The whole library seems unused and safe to remove.

If this line of thoughts is correct, I can send a PR with the changes.

**Comment by matteius** [comment]
@befeleme Your assessment makes sense to me, please feel free to open a PR for this.
