### ISSUE TITLE
Pipenv install is not adding dependencies to Pipfile.lock

### ISSUE THREAD

**Issue by kdassharma** [pypa/pipenv#4703]
### Issue description

In the process of converting from a requirements.txt style of dependency management to Pipenv. However, the Pipfile.lock does not include information regarding the dependencies and sub-dependencies after installing from requirements.txt. 

### Expected result

The expected result is such that once the Pipfile and Pipfile.lock are pushed to a VCS, ```pipenv install``` will allow one to replicate the environment completely.

### Steps to replicate
```
mkdir testpipenv
cd testpipenv/
mkdir editable_package
cd editable_package/
touch requirements.txt setup.up
```

**requirements.txt as follows:**
```
requests
```
**setup.py as follows:**
```
from __future__ import absolute_import, division, print_function
import os.path
from setuptools import find_packages, setup
LOCAL_DIR = os.path.dirname(os.path.abspath(__file__))

requirements = []

with open(os.path.join(LOCAL_DIR, "requirements.txt"), "r") as infile:
    for line in infile:
        line = line.strip()
        if line and not line[0] == "#":  # ignore comments
                requirements.append(line.strip())
        
print(requirements)

setup(
    name="test_editable_package",
    packages=find_packages("."),
    install_requires=requirements,
    include_package_data=True,
)
```

Steps to replicate error:

1. ```pip install pipenv```
2. ```pipenv --python 3.8 && pipenv shell``` 
3. ```python -m pip install --upgrade pip```
4. ```pipenv install -e editable_package/```
5. ```pipenv lock```
6. Check Pipfile.lock to see if dependecies are visible (subdependencies should not be visible)

NOTE: The expected/ideal behaviour can be observed by doing the same steps as above, but using pipenv==11.8.3 instead of latest.
-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'/home/kaustav/.local/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/bin/python3.8'`

Python installations found:

  - `3.8.0`: `/usr/bin/python3.8`
  - `3.6.9`: `/usr/bin/python3.6m`
  - `3.6.9`: `/usr/bin/python3.6`
  - `3.6.9`: `/usr/bin/python3`
  - `2.7.17`: `/usr/bin/python2`
  - `2.7.17`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.0-73-generic',
 'platform_system': 'Linux',
 'platform_version': '#82~18.04.1-Ubuntu SMP Fri Apr 16 15:10:02 UTC 2021',
 'python_full_version': '3.8.0',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `CLUTTER_IM_MODULE`
  - `LS_COLORS`
  - `LD_LIBRARY_PATH`
  - `LESSCLOSE`
  - `XDG_MENU_PREFIX`
  - `LANG`
  - `DISPLAY`
  - `ORIGINAL_XDG_CURRENT_DESKTOP`
  - `GNOME_SHELL_SESSION_MODE`
  - `COLORTERM`
  - `USERNAME`
  - `CHROME_DESKTOP`
  - `XDG_VTNR`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `SSH_AUTH_SOCK`
  - `MANDATORY_PATH`
  - `XDG_SESSION_ID`
  - `USER`
  - `DESKTOP_SESSION`
  - `QT4_IM_MODULE`
  - `TEXTDOMAINDIR`
  - `DEFAULTS_PATH`
  - `PWD`
  - `HOME`
  - `VSCODE_GIT_ASKPASS_NODE`
  - `TEXTDOMAIN`
  - `SSH_AGENT_PID`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `QT_ACCESSIBILITY`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `XDG_SESSION_DESKTOP`
  - `GJS_DEBUG_OUTPUT`
  - `GTK_MODULES`
  - `VSCODE_GIT_ASKPASS_MAIN`
  - `WINDOWPATH`
  - `TERM`
  - `SHELL`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `IM_CONFIG_PHASE`
  - `XDG_CURRENT_DESKTOP`
  - `GPG_AGENT_INFO`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `SHLVL`
  - `XDG_SEAT`
  - `LANGUAGE`
  - `PYTHONPATH`
  - `VSCODE_GIT_IPC_HANDLE`
  - `GDK_BACKEND`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `GIT_ASKPASS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `XDG_CONFIG_DIRS`
  - `PATH`
  - `GJS_DEBUG_TOPICS`
  - `SESSION_MANAGER`
  - `BREAKPAD_DUMP_LOCATION`
  - `LESSOPEN`
  - `GTK_IM_MODULE`
  - `_`
  - `OLDPWD`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/kaustav/.local/bin:/home/kaustav/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_CA.UTF-8`
  - `PWD`: `/home/kaustav/Documents/test/testpipenv`

---------------------------

Contents of `Pipfile` ('/home/kaustav/Documents/test/testpipenv/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
test-editable-package = {editable = true, path = "./editable_package"}

[dev-packages]

[requires]
python_version = "3.8"

```

Contents of `Pipfile.lock` ('/home/kaustav/Documents/test/testpipenv/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "75f7b48216592e43431f4bdb8efa9252d98c59a2df946bed5aefd0288593d33e"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "test-editable-package": {
            "editable": true,
            "path": "./editable_package"
        }
    },
    "develop": {}
}

```
</details>

**Comment by satyanash** [comment]
probably similar to #4631

**Comment by matteius** [comment]
@kdassharma I made a couple modifications to your report, such as its a setup.py (not setup.up) and installing requests not request.  However once I did that, I got a reproduceable event.  First time it failed and second time it worked, just like I had happen over in https://github.com/pypa/pipenv/issues/4895

It seems the first time it has to generate a directory called reqlib-metadata, and that gets a TextFile busy conflict:
```
davis@matt-VirtualBox:~/shared-projects/pipenv-4703$ pipenv install -e editable_package

Installing -e editable_package...

Adding test_editable_package to Pipfile's [packages]...

✔ Installation Succeeded 

Pipfile.lock not found, creating...

Locking [dev-packages] dependencies...

Locking [packages] dependencies...

Building requirements...

⠹ Locking...['requests']

Resolving dependencies...

✔ Success! 

Updated Pipfile.lock (23ef96)!

Installing dependencies from Pipfile.lock (23ef96)...

  🎅   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00

To activate this project's virtualenv, run pipenv shell.

Alternatively, run a command inside the virtualenv with pipenv run.

Error in atexit._run_exitfuncs:

Traceback (most recent call last):

  File "/home/mdavis/.local/lib/python3.9/site-packages/pipenv/vendor/vistir/path.py", line 433, in rmtree

    shutil.rmtree(directory, ignore_errors=ignore_errors, onerror=onerror)

  File "/usr/lib/python3.9/shutil.py", line 726, in rmtree

    _rmtree_safe_fd(fd, path, onerror)

  File "/usr/lib/python3.9/shutil.py", line 667, in _rmtree_safe_fd

    onerror(os.rmdir, fullname, sys.exc_info())

  File "/home/mdavis/.local/lib/python3.9/site-packages/pipenv/vendor/vistir/path.py", line 528, in handle_remove_readonly

    raise exc_exception

  File "/usr/lib/python3.9/shutil.py", line 665, in _rmtree_safe_fd

    os.rmdir(entry.name, dir_fd=topfd)

OSError: [Errno 26] Text file busy: 'test_editable_package.egg-info'
```

Subsequent retry works:
```
mdavis@matt-VirtualBox:~/shared-projects/pipenv-4703$ pipenv install -e editable_package

Installing -e editable_package...

Adding test-editable-package to Pipfile's [packages]...

✔ Installation Succeeded 

Installing dependencies from Pipfile.lock (23ef96)...

['requests']

  🎅   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00

To activate this project's virtualenv, run pipenv shell.

Alternatively, run a command inside the virtualenv with pipenv run.
```

So I remove only `rm -rf editable_package/reqlib-metadata/` and try again and get the same original error during locking and retry again succeeds.  @frostming this is the most promising reproduction steps of the 'complex setup.py not installable locally' type errors.

**Comment by matteius** [comment]
@kashewnuts  My past comment wasn't accurate, I think I was getting that error from a shared file system on a VirtualBox VM.  Repeating testing tonight this is working on 2022.1.8.

```
matteius@matteius-VirtualBox:~/pipenv-4703$ pipenv install -e ./editable_package
Creating a virtualenv for this project...
Pipfile: /home/matteius/pipenv-4703/Pipfile
Using /home/matteius/.pyenv/versions/3.10.2/bin/python3 (3.10.2) to create virtualenv...
⠇ Creating virtual environment...created virtual environment CPython3.10.2.final.0-64 in 256ms
  creator CPython3Posix(dest=/home/matteius/.virtualenvs/pipenv-4703-VwUZoMut, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/matteius/.local/share/virtualenv)
    added seed packages: pip==22.0.3, setuptools==60.9.3, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/matteius/.virtualenvs/pipenv-4703-VwUZoMut
Creating a Pipfile for this project...
Installing -e ./editable_package...
Adding test-editable-package to Pipfile's [packages]...
✔ Installation Succeeded 
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (747b75)!
Installing dependencies from Pipfile.lock (747b75)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
matteius@matteius-VirtualBox:~/pipenv-4703$ cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
test-editable-package = {editable = true, path = "./editable_package"}

[dev-packages]

[requires]
python_version = "3.10"
matteius@matteius-VirtualBox:~/pipenv-4703$ cat Pipfile.lock 
{
    "_meta": {
        "hash": {
            "sha256": "286ceb27ee6203010927ac1c1fae05272e36f76c48da5869befa675a3c747b75"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.10"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "certifi": {
            "hashes": [
                "sha256:78884e7c1d4b00ce3cea67b44566851c4343c120abd683433ce934a68ea58872",
                "sha256:d62a0163eb4c2344ac042ab2bdf75399a71a2d8c7d47eac2e2ee91b9d6339569"
            ],
            "version": "==2021.10.8"
        },
        "charset-normalizer": {
            "hashes": [
                "sha256:2857e29ff0d34db842cd7ca3230549d1a697f96ee6d3fb071cfa6c7393832597",
                "sha256:6881edbebdb17b39b4eaaa821b438bf6eddffb4468cf344f09f89def34a8b1df"
            ],
            "markers": "python_version >= '3'",
            "version": "==2.0.12"
        },
        "idna": {
            "hashes": [
                "sha256:84d9dd047ffa80596e0f246e2eab0b391788b0503584e8945f2368256d2735ff",
                "sha256:9d643ff0a55b762d5cdb124b8eaa99c66322e2157b69160bc32796e824360e6d"
            ],
            "markers": "python_version >= '3'",
            "version": "==3.3"
        },
        "requests": {
            "hashes": [
                "sha256:68d7c56fd5a8999887728ef304a6d12edc7be74f1cfa47714fc8b414525c9a61",
                "sha256:f22fa1e554c9ddfd16e6e41ac79759e17be9e492b3587efa038054674760e72d"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4, 3.5'",
            "version": "==2.27.1"
        },
        "test-editable-package": {
            "editable": true,
            "path": "./editable_package"
        },
        "urllib3": {
            "hashes": [
                "sha256:000ca7f471a233c2251c6c7023ee85305721bfdf18621ebff4fd17a8653427ed",
                "sha256:0e7c33d9a63e7ddfcb86780aac87befc2fbddf46c58dbb487e0855f7ceec283c"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4' and python_version < '4'",
            "version": "==1.26.8"
        }
    },
    "develop": {}
}
```

Can this be closed?

**Comment by matteius** [comment]
There is a new `requirements` command that generates `requirements.txt` type output from the `Pipfile.lock`
