### ISSUE TITLE
apply .editorconfig indent when creating Pipfile.lock

### ISSUE THREAD

**Issue by tbugfinder** [pypa/pipenv#4718]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues and the [PEEP list](https://github.com/pypa/pipenv/blob/master/peeps/) before posting! We may close your issue if it is very similar to one of them. Please be considerate and follow the PEEP process, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Is your feature request related to a problem? Please describe.

It would be beneficial if pipenv would apply .editorconfig when creating Pipfile.lock, so that additional hooks are not needed or have to run.

### Describe the solution you'd like

pipenv should adhere to .editorconfig settings and create appropriate indents for Pipfile.lock.

### Describe alternatives you've considered

pre-commit hooks or github workflows on pull_request.

### Additional context

Add any other context or screenshots about the feature request here. It may be a good idea to mention that platform and Python version you are on.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by frostming** [comment]
Not in the scope, Pipfile.lock is not designed to be human-writable.
