### ISSUE TITLE
pipenv uses wrong exit code when delegated process is killed

### ISSUE THREAD

**Issue by odormond** [pypa/pipenv#4722]
### Issue description

In memory constrained environment, like a docker container, invoked subprocess can be OOM killed by the kernel but pipenv still exit with status code 0.

### Expected result

Exit code should be different from 0.

### Actual result

Exit code is 0.

### Steps to replicate

I'm afraid I couldn't come up with a simple way to reproduce the memory pressure we got in production and have the OOM trigger at will on the right process. However, you will find below a clear description of why this can happen and how to fix it.

### Origin of the problem

The issue comes from the pexpect delegator that treats positive and negative exit code differently. When the process is OOM killed, the exit code is negative (-15) and so `exitstatus` is set to `None` while `signalstatus` is set to `15` (see https://github.com/pypa/pipenv/blob/72835f142c8010f686ca26af21f3f9079d5bf997/pipenv/vendor/pexpect/popen_spawn.py#L166). As a consequence, when the delegator `return_code` property is checked, it return `None` because it ignore `signalstatus`. This is then passed to `sys.exit(...)` leading to a successful run of pipenv instead of failure.

### Proposed fix

```diff
diff --git a/pipenv/vendor/delegator.py b/pipenv/vendor/delegator.py
index 19f27070..e2fb2a2a 100644
--- a/pipenv/vendor/delegator.py
+++ b/pipenv/vendor/delegator.py
@@ -168,6 +168,8 @@ class Command(object):
     def return_code(self):
         # Support for pexpect's functionality.
         if self._uses_pexpect:
+            if self.subprocess.signalstatus is not None:
+                return -self.subprocess.signalstatus
             return self.subprocess.exitstatus
         # Standard subprocess method.
         return self.subprocess.returncode
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'/usr/local/.pyenv/versions/3.6.13/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/.pyenv/versions/3.6.13/bin/python3.6'`

Python installations found:

  - `3.9.4`: `/usr/local/.pyenv/versions/3.9.4/bin/python3`
  - `3.8.8`: `/usr/local/.pyenv/versions/3.8.8/bin/python3.8`
  - `3.7.10`: `/usr/local/.pyenv/versions/3.7.10/bin/python3.7m`
  - `3.6.13`: `/usr/local/.pyenv/versions/3.6.13/bin/python3.6m`
  - `3.6.9`: `/usr/bin/python3.6m`
  - `3.6.9`: `/usr/bin/python3`
  - `3.6.9`: `/usr/bin/python3.6`
  - `2.7.18`: `/usr/local/.pyenv/versions/2.7.18/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.13',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.0-74-generic',
 'platform_system': 'Linux',
 'platform_version': '#83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021',
 'python_full_version': '3.6.13',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LC_ALL`
  - `LS_COLORS`
  - `LANG`
  - `HOSTNAME`
  - `PYENV_ROOT`
  - `PWD`
  - `HOME`
  - `BUNDLE_PATH`
  - `DEBIAN_FRONTEND`
  - `TERM`
  - `BUNDLE_SILENCE_ROOT_WARNING`
  - `BUNDLE_BIN`
  - `SHLVL`
  - `DEPENDABOT_NATIVE_HELPERS_PATH`
  - `PATH`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `.bundle/binstubs:/usr/local/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/dependabot/.bundle/bin:/opt/python/bin`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/dependabot`

---------------------------

</details>

**Comment by marco-m** [comment]
Hello @frostming, would you have time to review this PR ? Or could you suggest somebody as reviewer ? Thanks!

**Comment by matteius** [comment]
@marco-m or @odormond is there an open PR or is the patch in the issue report the proposal for starting a PR?

**Comment by frostming** [comment]
`delegator` is dropped from the vendors, this issue can be closed
