### ISSUE TITLE
Exported requirements not matching imported requirements.txt

### ISSUE THREAD

**Issue by craigboman** [pypa/pipenv#4731]
When initiating a new virtual environment in an existing python application, I am able to successfully generate a Pipfile from the requirements.txt. All of the explicit Pipfile package version numbers match the explicit package version numbers listed in my initial requirements.txt. But when I generate a new requirements.txt from the Pipfile, the requirements.txt's packages do not match before and after being imported/exported from pipenv. Any idea why that is the case? Why would the Pipfile match the imported requirements, but the exported requirements don't match either one. I would expect that explicit package version numbers would be consistent between all three files. The --keep-outdated flag did not appear to make much of a difference when generating the final requirements.txt. 

I need the generated/exported requirements.txt to match precisely the explicit pipfile package numbers.

**Comment by matteius** [comment]
@craigboman Can you provide an example requirements.txt for us to triage with?
