### ISSUE TITLE
Error finding geos_c.dll when installing dependencies

### ISSUE THREAD

**Issue by bacalfa** [pypa/pipenv#4736]
### Issue description

Installing `keras`, `tensorflow` and a few other packages requires the installation of `shapely`, which comes with binaries (geos.dll and geos_c.dll). These are available under _"C:\Users\username\.virtualenvs\myproj-test-csYg9EO6\Lib\site-packages\shapely\DLLs"_ where _myproj_ is a project folder. However, those DLLs are not copied to the temporary pip-resolver folder during installation, and they can't be found.

```
 Directory of C:\Users\username\AppData\Local\Temp\pip-resolver-4ueqot9z\shapely\shapely

07/13/2021  10:51 PM    <DIR>          .
07/13/2021  10:51 PM    <DIR>          ..
12/13/2019  07:01 PM             8,597 affinity.py
07/13/2021  10:51 PM    <DIR>          algorithms
12/15/2020  06:31 PM             5,831 coords.py
03/01/2021  09:57 PM            18,021 ctypes_declarations.py
12/15/2020  06:31 PM             1,016 errors.py
07/13/2021  10:51 PM    <DIR>          examples
07/13/2021  10:51 PM    <DIR>          geometry
03/03/2021  12:59 PM            27,181 geos.py
03/01/2021  09:57 PM             5,597 impl.py
03/01/2021  09:04 PM             1,355 iterops.py
11/05/2018  06:43 PM               677 linref.py
03/03/2021  12:59 PM            27,643 ops.py
11/05/2018  06:43 PM               626 predicates.py
11/05/2018  06:43 PM             3,046 prepared.py
07/13/2021  10:51 PM    <DIR>          speedups
03/03/2021  05:15 PM             7,290 strtree.py
03/01/2021  09:04 PM             2,283 topology.py
12/15/2020  06:31 PM             1,522 validation.py
07/13/2021  10:51 PM    <DIR>          vectorized
11/05/2018  06:43 PM             1,702 wkb.py
12/15/2020  06:31 PM             1,915 wkt.py
12/15/2020  06:31 PM             8,265 _buildcfg.py
03/04/2020  12:09 PM             3,592 _geos.pxi
03/03/2021  05:16 PM                22 __init__.py
```

### Expected result

Installation should succeed (as it does with `conda install`, for example).

### Actual result

Part of error message:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\username\AppData\Local\Temp\pip-resolver-4ueqot9z\shapely\setup.py", line 74, in <module>
    from shapely._buildcfg import geos_version_string, geos_version, \
  File "C:\Users\username\AppData\Local\Temp\pip-resolver-4ueqot9z\shapely\shapely\_buildcfg.py", line 202, in <module>
    lgeos = CDLL("geos_c.dll")
  File "c:\users\username\miniconda3\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

I haven't deleted Miniconda3 yet, and for some reason, its `ctypes` package is being used as shown above. But I don't think this is the issue here (please comment on it).

### Steps to replicate

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.5.29'`

Pipenv location: `'C:\\Users\\username\\AppData\\Roaming\\Python\\Python39\\site-packages\\pipenv'`

Python location: `'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python39\\python.exe'`

Python installations found:

  - `3.9.6`: `C:\Users\username\AppData\Local\Programs\Python\Python39\python.exe`
  - `3.8.10`: `C:\Users\username\Miniconda3\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.6',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.18363',
 'python_full_version': '3.9.6',
 'python_version': '3.9',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DADIR`
  - `DRIVERDATA`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `HOMESHARE`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `MLM_LICENSE_FILE`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `ONEDRIVECOMMERCIAL`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `PYCHARM COMMUNITY EDITION`
  - `QIP4880`
  - `RTOOLS40_HOME`
  - `R_EXE`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `UATDATA`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VS140COMNTOOLS`
  - `WINDIR`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `C:\WINDOWS\SYSTEM32;C:\WINDOWS;C:\WINDOWS\SYSTEM32\WBEM;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\CheckPoint\Endpoint Security\Endpoint Common\bin;C:\Program Files\1E\Client\Extensibility\NomadBranch;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\MATLAB\R2020b\runtime\win64;C:\Program Files\MATLAB\R2020b\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\TortoiseGit\bin;C:\Users\username;C:\Users\username\Miniconda3;C:\Users\username\Miniconda3\Library\mingw-w64\bin;C:\Users\username\Miniconda3\Library\usr\bin;C:\Users\username\Miniconda3\Library\bin;C:\Users\username\Miniconda3\Scripts;C:\Users\username\AppData\Local\Microsoft\WindowsApps;C:\Users\username\AppData\Local\JetBrains\PyCharm Community Edition 2021.1.1\bin;;C:\Users\username\AppData\Roaming\npm;C:\Users\username\AppData\Local\Yarn\bin;C:\RBuildTools\3.5\bin;`

---------------------------

Contents of `Pipfile` ('C:\\Users\\username\\myproj\\myproj-test\\Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
keras = "*"
tensorflow = "*"
opencv-python = "*"
imgaug = "*"
pycocotools = "*"

[dev-packages]

[requires]
python_version = "3.8"

[pipenv]
allow_prereleases = true

```

</details>

**Comment by bacalfa** [comment]
Actually, the pip-unpack folder contains a zip file (Shapely-1.8a1.tar.gz), which doesn't contain the DLLs. So I'm not sure what the problem is. Everything works fine with `conda install`.

**Comment by matteius** [comment]
@bacalfa Have you tried yet with `pipenv==2022.8.1`?

**Comment by matteius** [comment]
I suspect its a Pathing issue some difference with a path variable between your system that will find the dlls and using pipenv that won't.   I'm not setup to test this however so having your help will be important to seeking resolution.

**Comment by matteius** [comment]
@bacalfa Are you still looking for support on this issue?  If so we can re-visit.
