### ISSUE TITLE
pipenv sync -d doesn't download the dev dependencies when using the WORKON_HOME

### ISSUE THREAD

**Issue by baztian** [pypa/pipenv#4742]
### Issue description

`pipenv sync -d` doesn't download the dev dependencies when using the `WORKON_HOME`.

It actually works when I create a `.venv` folder and unset the `WORKON_HOME`.

### Expected result

I'm expecting pipenv to download the dev dependencies even when working with `WORKON_HOME`.

### Actual result

It does not download additional dev dependencies.

### Steps to replicate

    $ cat Pipfile
    [[source]]
    url = "https://pypi.python.org/simple"
    verify_ssl = true
    name = "pypi"

    [packages]
    bs4 = "*"

    [dev-packages]
    pytest = "*"

    [requires]
    python_version = "3.8"

    $ export WORKON_HOME=$PWD/foo
    $ pipenv install
    ...
    $ ls $(pipenv --venv)/lib/python3.8/site-packages
    beautifulsoup4-4.9.3.dist-info	easy_install.py        setuptools		     _virtualenv.pth
    bs4				pip		       setuptools-51.3.3.dist-info   _virtualenv.py
    bs4-0.0.1.dist-info		pip-20.3.3.dist-info   setuptools-51.3.3.virtualenv  wheel
    _distutils_hack			pip-20.3.3.virtualenv  soupsieve		     wheel-0.36.2.dist-info
    distutils-precedence.pth	pkg_resources	       soupsieve-2.2.1.dist-info     wheel-0.36.2.virtualenv
    $ pipenv sync -d
    ...
    All dependencies are now up-to-date!
    $ ls $(pipenv --venv)/lib/python3.8/site-packages
    beautifulsoup4-4.9.3.dist-info	easy_install.py        setuptools		     _virtualenv.pth
    bs4				pip		       setuptools-51.3.3.dist-info   _virtualenv.py
    bs4-0.0.1.dist-info		pip-20.3.3.dist-info   setuptools-51.3.3.virtualenv  wheel
    _distutils_hack			pip-20.3.3.virtualenv  soupsieve		     wheel-0.36.2.dist-info
    distutils-precedence.pth	pkg_resources	       soupsieve-2.2.1.dist-info     wheel-0.36.2.virtualenv
    $ # no pytest got installed :(

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'/var/lang/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv'`

Python location: `'/var/lang/pipx/venvs/pipenv/bin/python'`

Python installations found:

  - `3.8.6`: `/var/lang/bin/python3.8`
  - `3.8.6`: `/var/lang/bin/python3`
  - `3.7.9`: `/usr/bin/python3.7m`
  - `3.7.9`: `/usr/bin/python3`
  - `3.7.9`: `/usr/bin/python3.7`
  - `3.7.9`: `/bin/python3.7m`
  - `3.7.9`: `/bin/python3`
  - `3.7.9`: `/bin/python3.7`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`
  - `2.7.18`: `/bin/python2`
  - `2.7.18`: `/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.0-80-generic',
 'platform_system': 'Linux',
 'platform_version': '#90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021',
 'python_full_version': '3.8.6',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `HOSTNAME`
  - `_LAMBDA_CONTROL_SOCKET`
  - `TERM`
  - `PIPX_BIN_DIR`
  - `OLDPWD`
  - `LAMBDA_TASK_ROOT`
  - `LD_LIBRARY_PATH`
  - `_LAMBDA_SHARED_MEM_FD`
  - `AWS_EXECUTION_ENV`
  - `WORKON_HOME`
  - `_LAMBDA_RUNTIME_LOAD_TIME`
  - `AWS_XRAY_DAEMON_ADDRESS`
  - `PATH`
  - `_LAMBDA_LOG_FD`
  - `PWD`
  - `LAMBDA_RUNTIME_DIR`
  - `LANG`
  - `TZ`
  - `PIPX_HOME`
  - `SHLVL`
  - `HOME`
  - `_AWS_XRAY_DAEMON_ADDRESS`
  - `_AWS_XRAY_DAEMON_PORT`
  - `_X_AMZN_TRACE_ID`
  - `_LAMBDA_SB_ID`
  - `PKG_CONFIG_PATH`
  - `AWS_XRAY_CONTEXT_MISSING`
  - `_LAMBDA_CONSOLE_SOCKET`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/var/lang/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/var/task`

---------------------------

Contents of `Pipfile` ('/var/task/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
bs4 = "*"

[dev-packages]
pytest = "*"

[requires]
python_version = "3.8"

```

Contents of `Pipfile.lock` ('/var/task/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "1cb50d386c0fb3d21c80978a170308ec8100b7978655ffd53cd86a7cbf9d69cc"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "beautifulsoup4": {
            "hashes": [
                "sha256:4c98143716ef1cb40bf7f39a8e3eec8f8b009509e74904ba3a7b315431577e35",
                "sha256:84729e322ad1d5b4d25f805bfa05b902dd96450f43842c4e99067d5e1369eb25",
                "sha256:fff47e031e34ec82bf17e00da8f592fe7de69aeea38be00523c04623c04fb666"
            ],
            "version": "==4.9.3"
        },
        "bs4": {
            "hashes": [
                "sha256:36ecea1fd7cc5c0c6e4a1ff075df26d50da647b75376626cc186e2212886dd3a"
            ],
            "index": "pypi",
            "version": "==0.0.1"
        },
        "soupsieve": {
            "hashes": [
                "sha256:052774848f448cf19c7e959adf5566904d525f33a3f8b6ba6f6f8f26ec7de0cc",
                "sha256:c2c1c2d44f158cdbddab7824a9af8c4f83c76b1e23e049479aa432feb6c4c23b"
            ],
            "markers": "python_version >= '3.0'",
            "version": "==2.2.1"
        }
    },
    "develop": {
        "attrs": {
            "hashes": [
                "sha256:149e90d6d8ac20db7a955ad60cf0e6881a3f20d37096140088356da6c716b0b1",
                "sha256:ef6aaac3ca6cd92904cdd0d83f629a15f18053ec84e6432106f7a4d04ae4f5fb"
            ],
            "version": "==21.2.0"
        },
        "iniconfig": {
            "hashes": [
                "sha256:011e24c64b7f47f6ebd835bb12a743f2fbe9a26d4cecaa7f53bc4f35ee9da8b3",
                "sha256:bc3af051d7d14b2ee5ef9969666def0cd1a000e121eaea580d4a313df4b37f32"
            ],
            "version": "==1.1.1"
        },
        "packaging": {
            "hashes": [
                "sha256:7dc96269f53a4ccec5c0670940a4281106dd0bb343f47b7471f779df49c2fbe7",
                "sha256:c86254f9220d55e31cc94d69bade760f0847da8000def4dfe1c6b872fd14ff14"
            ],
            "version": "==21.0"
        },
        "pluggy": {
            "hashes": [
                "sha256:15b2acde666561e1298d71b523007ed7364de07029219b604cf808bfa1c765b0",
                "sha256:966c145cd83c96502c3c3868f50408687b38434af77734af1e9ca461a4081d2d"
            ],
            "version": "==0.13.1"
        },
        "py": {
            "hashes": [
                "sha256:21b81bda15b66ef5e1a777a21c4dcd9c20ad3efd0b3f817e7a809035269e1bd3",
                "sha256:3b80836aa6d1feeaa108e046da6423ab8f6ceda6468545ae8d02d9d58d18818a"
            ],
            "version": "==1.10.0"
        },
        "pyparsing": {
            "hashes": [
                "sha256:c203ec8783bf771a155b207279b9bccb8dea02d8f0c9e5f8ead507bc3246ecc1",
                "sha256:ef9d7589ef3c200abe66653d3f1ab1033c3c419ae9b9bdb1240a85b024efc88b"
            ],
            "version": "==2.4.7"
        },
        "pytest": {
            "hashes": [
                "sha256:50bcad0a0b9c5a72c8e4e7c9855a3ad496ca6a881a3641b4260605450772c54b",
                "sha256:91ef2131a9bd6be8f76f1f08eac5c5317221d6ad1e143ae03894b862e8976890"
            ],
            "index": "pypi",
            "version": "==6.2.4"
        },
        "toml": {
            "hashes": [
                "sha256:806143ae5bfb6a3c6e736a764057db0e6a0e05e338b5630894a5f779cabb4f9b",
                "sha256:b3bda1d108d5dd99f4a20d24d9c348e91c4db7ab1b749200bded2f839ccbe68f"
            ],
            "version": "==0.10.2"
        }
    }
}

```
</details>

**Comment by matteius** [comment]
@baztian Please recheck with `2022.1.8` as I have `$WORKON_HOME` set and haven't experienced such an issue.
