### ISSUE TITLE
PIPENV IS NOTHING BUT A HEADACHE FULL OF BUGS@!!!!

### ISSUE THREAD

**Issue by azataiot** [pypa/pipenv#4744]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

Describe the issue briefly here.

### Expected result

Describe what you expected.

### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by SmokinCaterpillar** [comment]
"We Transform Your Data & Ideas Into Intelligent Results", I suppose not, yelling at open source contributors on their github  issue page is far from that....

**Comment by ZelphirKaltstahl** [comment]
> "Azat.ai: We Transform Your Data & Ideas Into Intelligent Results", I suppose not, yelling at open source contributors on their github issue page is far from that....

The whole website is a fake site ^^ Look at the prominent quote :D

> "There have to be reasons that you get up in the morning and you want to live. Why do you want to live? What’s the point? What inspires you? What do you love about the future? The answer is in AzatAI" -- Elon MuskCEO of Tesla

Yeah, I am sure he said that …

And then that fake or at least suggestively implying a non-reality "Coding time" photo.

And the grammar/spelling/language:

> We deliver future knowledges that pro your carrier & life.

What is "to pro sth."?

Maybe the whole page is a spit out of some failed ML model, aiming to make the impression of a human created website or something.

If we look at the github account at "source" type of repos, there is almost no work done there and some repos contains nothing but a single picture. Quite a trash account.

**Comment by frostming** [comment]
Help and contribute, or just leave it. #4746
