### ISSUE TITLE
Improve the testing execution speed

### ISSUE THREAD

**Issue by frostming** [pypa/pipenv#4746]
Now it is a big pain for running tests both locally and on CI. It takes ~1h to run only 270 test cases. This drastically pulls back the development/maintenance of Pipenv and scares potential contributors.

### Current Status

Almost all test cases spawn a subprocess and run Pipenv inside. It has the following disadvantages:

1. The bootstrap overhead is big, slowing down the execution.
2. It makes it difficult to mock and make fixtures, for example, the test PyPI has to be a *real* web service that runs in a separate thread.
3. Impossible to collect coverage.

### Change Plan

While it can be further discussed, the improvement plan is simple -- make the test cases run in the host process. `click` provides a `CliRunner` to run CLI commands in an isolated environment while staying in the host process -- no subprocess is involved.

There is only one blocker that prevents this change. `environments.py` reads some environment variables and stores the states in memory. That means it is impossible to modify the states by case without reloading the whole process. What is worse, the module is imported by many files.

### Participate in helping

Hopefully, after this improvement, the test cases run can speed up by 3-5 times, and makes it easier for contributing. If you have a better approach than the above, comment below. It would be even more appreciated if you volunteer to do the coding.
I personally don't have much time for this project. So I am also seeking a new collaborator. Help to improve Pipenv, instead of [yelling at the open-source contributors](https://github.com/pypa/pipenv/issues/4744) and throwing rubbish words.

**Comment by oz123** [comment]
I was wondering about the need to really start a dummy PyPI server.
What are good are arguments against using mocked responses with https://github.com/getsentry/responses ?

I believe this can not replace all the tests, but can simplify some tests.
Also, many of the integration tests could be run in a docker-compose setup (if pypi server is really needed).
Is this something you would like to have help with?

**Comment by frostming** [comment]
> I was wondering about the need to really start a dummy PyPI server.
What are good are arguments against using mocked responses with https://github.com/getsentry/responses ?

Yeah, there are many ways to mock the response, but not in subprocesses.

**Comment by oz123** [comment]
Can't we use responses without subprocess then? 
The current approach also requires networking to work. Using responses you can make the whole test suite run without networking.

**Comment by matteius** [comment]
We have made recent improvements in this area, currently taking around 20 minutes to run the test suite.
