### ISSUE TITLE
Pipenv fails to install with -r requirements.txt

### ISSUE THREAD

**Issue by ahmetkca** [pypa/pipenv#4748]
### Issue description

i want to import my requirements.txt to pipfile but it just fails

### Expected result

expected result is that pipenv successfully install packages from requirements.txt to Pipfile

### Actual result

Unexpected syntax in /mnt/d/EtsyAPI/backend/requirements.txt. Are you sure this is a requirements.txt style file?
'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

requirements.txt
aiofiles==0.5.0
aiohttp==3.7.4.post0
aniso8601==7.0.0
anyio==3.2.1

pipenv install -r requirements.txt

i also tried without version numbers and equal signs but no luck
i even tried with empty requirements.txt but it still gives the same error

**Comment by ZelphirKaltstahl** [comment]
Is that

```
aiofiles==0.5.0
aiohttp==3.7.4.post0
aniso8601==7.0.0
anyio==3.2.1
```

being the entire `requirements.txt` file?

**Comment by baltazarO** [comment]
Whats the encoding of your requirements.txt file? Try opening it up in a new text editor and save it as utf-8.

**Comment by matteius** [comment]
@ahmetkca please check back and try the solutions in this thread or the issue will close down soon.
