### ISSUE TITLE
pipenv install/lock --dirty to cut locking short

### ISSUE THREAD

**Issue by SmokinCaterpillar** [pypa/pipenv#4749]
Locking takes quite some time for mature projects with dozens of dependencies. And rightly so, checking the dependency tree is time consuming.

However, often in our development workflow, we need to do a micro or minor update in a few or a just a single package (`mypackage 1.3.3` -> `mypackage 1.3.4`, or `mypackage 1.3` -> `mypackage 1.4`) and we do know in advance that the requirements of `mypackage` haven't changed. So locking in this case can be quite a burden, especially if we have to do this update in 5 or more repositories.

So it would be nice if there was an `pipenv install/lock --dirty` command. `--dirty` checks the Pipfile for changes in the package requirements. If `--dirty` finds updates, like `mypackage` is updated from `1.2.3` to `1.3.1`, it will download `1.3.1` and update the entry in the lockfile for this particular package. What it won't do is check all dependencies of `mypackage` or check for conflicts with other packages. In other words, it will only update the hashes and the version of that particular package in the `lockfile` and leave the rest of the lockfile untouched. Note if `--dirty` recognizes that a packages was actually added to the Pipfile it fails, as `--dirty` doesn't work for the addition of new packages. 

So if we know that there's no need to really check the entire dependency tree  (and are aware that we have to take the blame as a user if locking doesn't work), we can tremendously speed up the locking by cutting it short. This is really useful when still developing (i.e. not for production). It's also useful for try and error purposes where we need to switch between package versions quickly, especially if we are talking about inhouse packages as dependencies and we need to install developing releases (and can't use `-e` as we need to install complete setups into docker containers).

**Comment by matteius** [comment]
@SmokinCaterpillar Have you tried the `pipenv install <mypackage> --keep-outdated` flag?  See also:  https://github.com/pypa/pipenv/pull/3304/files

I suspect that basically would do what you are describing of " it will only update the hashes and the version of that particular package in the lockfile and leave the rest of the lockfile untouched." -- the difference in what you are describing is that `--keep-outdated` will still bring in and calculate all of the required sub-dependencies of `mypackage` which makes sense that it would need to for consistency of the lockfile and ensuring that the project doesn't break going from `1.2.3` to `1.3.1` when the version bump introduces a new sub-dependency.
