### ISSUE TITLE
Sub dependency installation in docker fails

### ISSUE THREAD

**Issue by joe42** [pypa/pipenv#4755]
> Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

$ pipenv --version
pipenv, version 2021.5.29

> Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

It might be related to "mixing Pipenv with system packages", but I don't know of a good way to avoid this in my case. I install it via `pip install pipenv` in a docker container and use it to generate a virtual environment with the required dependencies and then remove it.

### Issue description

I try to install a sub dependency from a Pipfile.lock but it is not installed.

Pipfile.lock:

      "typing-extensions": {
                  "hashes": [
                      "sha256:0ac0f89795dd19de6b97debb0c6af1c70987fd80a2d62d1958f7e56fcc31b497",
                      "sha256:50b6f157849174217d0656f99dc82fe932884fb250826c18350e159ec6cdf342",
                      "sha256:779383f6086d90c99ae41cf0ff39aac8a7937a9283ce0a414e5dd782f4c94a84"
                  ],
                  "markers": "python_version < '3.10'",
                  "version": "==3.10.0.0"
              },

After the installation I see it in pipenv graph, but the module is not installed (importing it fails).

      $ pipenv graph|grep typing-extensions
            - typing-extensions [required: >=3.6.4, installed: ?]
            - typing-extensions [required: >=3.6.4, installed: ?]
          - typing-extensions [required: >=3.6.4, installed: ?]
            - typing-extensions [required: >=3.6.4, installed: ?]
            - typing-extensions [required: >=3.6.4, installed: ?]

      $ python
      Python 3.7.2 (default, Mar 27 2019, 08:44:46) 
      [GCC 6.3.0 20170516] on linux
      Type "help", "copyright", "credits" or "license" for more information.
       >>> import typing_extension
      Traceback (most recent call last):
        File "<stdin>", line 1, in <module>
      ModuleNotFoundError: No module named 'typing_extension'

It works fine if I add the module as a primary dependency.

### Expected result

The module is installed and can be imported.

### Actual result

The module is not installed.

### Steps to replicate

Work in progress. I am trying to come up with a smallest reproducible example.

**Comment by matteius** [comment]
@joe42 There is not enough information here to reproduce the issue, no Pipfile and the lock file is just a fragment of one.  At this point the pipenv version is no longer latest, so I am going to close this issue for now and suggest if you can reproduce a problem with the latest version of pipenv to supply a new bug report with steps to reproduce and output from running `pipenv --support`
