### ISSUE TITLE
=Thanks for your concern - The project is not dead; it has been held back by several subdependencies and a complicated release process. This is on me and the next release (which is actually almost finished) seeks to address a large number of these underlying issues including a single point of failure in the maintainership chain.  Unfortunately that requires a substantial amount of documentation which is also currently in progress.

### ISSUE THREAD

**Issue by aserr13** [pypa/pipenv#4756]
Thanks for your concern -- The project is not dead; it has been held back by several subdependencies and a complicated release process. This is on me and the next release (which is actually almost finished) seeks to address a large number of these underlying issues including a single point of failure in the maintainership chain.  Unfortunately that requires a substantial amount of documentation which is also currently in progress.

I recently accepted a role that affords me time to tackle these issues so I have been making progress, albeit slowly.  I apologize for failing to be more communicative but this is incredibly important to everyone, myself included, and updates will be cascading to pipenv shortly.

_Originally posted by @techalchemy in https://github.com/pypa/pipenv/issues/4058#issuecomment-565550646_

')(

**Comment by stewartmiles** [comment]
FYI @aserr13 I recently came across https://github.com/sarugaku/requirementslib/issues/297 which is minimally patched in https://github.com/sarugaku/requirementslib/pull/298 , would be great to merge a new `requirementslib` to fix multiple installations of each editable packages on each `pipenv install`.

**Comment by frostming** [comment]
Hi @aserr13 , Please modify the issue type, I can't read what you desire. Or close this issue.

**Comment by CSharperMantle** [comment]
@frostming I have seen many of these 'originally posted elsewhere' issues and PRs recently, many of which have similar structure. I suspect that they are possibly generated text posted by bots.

E.g.:
mdn/browser-compat-data#11280
mdn/browser-compat-data#11279
mdn/browser-compat-data#11377

**Comment by frostming** [comment]
Thanks, closing it now
