### ISSUE TITLE
pipenv fails to install VCS dependency if no requirements are detected

### ISSUE THREAD

**Issue by mistressofjellyfish** [pypa/pipenv#4763]
### Issue description

pipenv fails to lock, if a package installed from a VCS source has no detectable dependencies.

Specifically, pipenv 2021.5.29 on python 3.9.6 fails on this command:

`pipenv install 'git+https://github.com/fkie-cad/common_helper_files.git#egg=common_helper_files'`

This seems to be caused by pipenv (correctly) not detecting any requirements for this package:
https://github.com/pypa/pipenv/blob/0e7c1fa97c8641d172764dc360bf8bbb0746078f/pipenv/utils.py#L535-L542

`req_list`is, as expected, an empty list. However also causes `req` in line 539 to become an empty list, which is to be expected since the iterator is empty and thus it returns the default element, which is `req_list`. Unsurprisingly, the empty list doesn't have the attribute `normalized_name`.

Now, as far as I understand the code, this makes sure that requirements from dependencies are correctly locked in the lockfile. My simple fix would be to add the following lines after line 538:

```python
if len(req_list) == 0:
    return constraints, locked_deps
```

This should work as both are empty at this point and, as far as I understand the code, if no dependencies are detected, these should remain empty. However, I am entirely new to this codebase and hesitant to consider this the correct fix. It seems to work locally, but I have no idea about the implications or consequences (or the inner workings of pipenv, for that matter).

### Expected result

pipenv locks without problems.

### Actual result

pipenv crashes:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/usr/lib/python3.9/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/usr/lib/python3.9/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/usr/lib/python3.9/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/usr/lib/python3.9/site-packages/pipenv/utils.py", line 1400, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/usr/lib/python3.9/site-packages/pipenv/utils.py", line 1110, in actually_resolve_deps
    resolver = Resolver.create(
  File "/usr/lib/python3.9/site-packages/pipenv/utils.py", line 665, in create
    constraints, skipped, index_lookup, markers_lookup = cls.get_metadata(
  File "/usr/lib/python3.9/site-packages/pipenv/utils.py", line 462, in get_metadata
    constraint_update, lockfile_update = cls.get_deps_from_req(
  File "/usr/lib/python3.9/site-packages/pipenv/utils.py", line 546, in get_deps_from_req
    entry = lockfile[pep423_name(req.normalized_name)]
AttributeError: 'list' object has no attribute 'normalized_name'
```

### Steps to replicate

`pipenv --three`
`pipenv install 'git+https://github.com/fkie-cad/common_helper_files.git#egg=common_helper_files'`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.5.29'`

Pipenv location: `'/usr/lib/python3.9/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.9.6`: `/sbin/python3.9`
  - `3.9.6`: `/sbin/python3`
  - `3.9.6`: `/bin/python3.9`
  - `3.9.6`: `/bin/python3`
  - `3.9.6`: `/usr/bin/python3.9`
  - `3.9.6`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.11.7-arch1-1-debug-kathi',
 'platform_system': 'Linux',
 'platform_version': '#2 SMP PREEMPT Wed, 07 Apr 2021 13:43:41 +0000',
 'python_full_version': '3.9.6',
 'python_version': '3.9',
 'sys_platform': 'linux'}
```

System environment variables:

  - `COLORFGBG`
  - `COLORTERM`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DESKTOP_SESSION`
  - `DISPLAY`
  - `GTK2_RC_FILES`
  - `GTK_RC_FILES`
  - `HOME`
  - `KDE_APPLICATIONS_AS_SCOPE`
  - `KDE_FULL_SESSION`
  - `KDE_SESSION_UID`
  - `KDE_SESSION_VERSION`
  - `KONSOLE_DBUS_SERVICE`
  - `KONSOLE_DBUS_SESSION`
  - `KONSOLE_VERSION`
  - `LANG`
  - `LANGUAGE`
  - `LOGNAME`
  - `MAIL`
  - `MOTD_SHOWN`
  - `PATH`
  - `PROFILEHOME`
  - `PULSE_SCRIPT`
  - `PWD`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `SESSION_MANAGER`
  - `SHELL`
  - `SHELL_SESSION_ID`
  - `SHLVL`
  - `TERM`
  - `UID`
  - `USER`
  - `WINDOWID`
  - `XCURSOR_SIZE`
  - `XCURSOR_THEME`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_RUNTIME_DIR`
  - `XDG_SESSION_CLASS`
  - `XDG_SESSION_ID`
  - `XDG_SESSION_TYPE`
  - `XRDP_PULSE_SINK_SOCKET`
  - `XRDP_PULSE_SOURCE_SOCKET`
  - `XRDP_SESSION`
  - `XRDP_SOCKET_PATH`
  - `OLDPWD`
  - `VISUAL`
  - `EDITOR`
  - `PAGER`
  - `GPSD_UNITS`
  - `CLASSPATH`
  - `LS_COLORS`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/sbin:/bin:/usr/bin:/usr/local/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `vim`
  - `LANG`: `de_AT.UTF-8`
  - `PWD`: `/home/katharina/Dokumente/fact`

---------------------------

Contents of `Pipfile` ('/home/katharina/Dokumente/fact/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
pip = "*"
distro = "*"
python-magic = "*"
requests = "*"
common-helper-files = { git = "https://github.com/fkie-cad/common_helper_files.git"}

[dev-packages]

[requires]
python_version = "3.9"

```

Contents of `Pipfile.lock` ('/home/katharina/Dokumente/fact/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "dcdf99a039cce15584b3fa82f7f4ee40e994a65ad01e373c45c67771e9db0c49"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.9"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "certifi": {
            "hashes": [
                "sha256:2bbf76fd432960138b3ef6dda3dde0544f27cbf8546c458e60baf371917ba9ee",
                "sha256:50b1e4f8446b06f41be7dd6338db18e0990601dce795c2b1686458aa7e8fa7d8"
            ],
            "version": "==2021.5.30"
        },
        "charset-normalizer": {
            "hashes": [
                "sha256:0c8911edd15d19223366a194a513099a302055a962bca2cec0f54b8b63175d8b",
                "sha256:f23667ebe1084be45f6ae0538e4a5a865206544097e4e8bbcacf42cd02a348f3"
            ],
            "markers": "python_version >= '3'",
            "version": "==2.0.4"
        },
        "distro": {
            "hashes": [
                "sha256:83f5e5a09f9c5f68f60173de572930effbcc0287bb84fdc4426cb4168c088424",
                "sha256:c8713330ab31a034623a9515663ed87696700b55f04556b97c39cd261aa70dc7"
            ],
            "index": "pypi",
            "version": "==1.6.0"
        },
        "idna": {
            "hashes": [
                "sha256:14475042e284991034cb48e06f6851428fb14c4dc953acd9be9a5e95c7b6dd7a",
                "sha256:467fbad99067910785144ce333826c71fb0e63a425657295239737f7ecd125f3"
            ],
            "markers": "python_version >= '3'",
            "version": "==3.2"
        },
        "python-magic": {
            "hashes": [
                "sha256:4fec8ee805fea30c07afccd1592c0f17977089895bdfaae5fec870a84e997626",
                "sha256:de800df9fb50f8ec5974761054a708af6e4246b03b4bdaee993f948947b0ebcf"
            ],
            "index": "pypi",
            "version": "==0.4.24"
        },
        "requests": {
            "hashes": [
                "sha256:6c1246513ecd5ecd4528a0906f910e8f0f9c6b8ec72030dc9fd154dc1a6efd24",
                "sha256:b8aa58f8cf793ffd8782d3d8cb19e66ef36f7aba4353eec859e74678b01b07a7"
            ],
            "index": "pypi",
            "version": "==2.26.0"
        },
        "urllib3": {
            "hashes": [
                "sha256:39fb8672126159acb139a7718dd10806104dec1e2f0f6c88aab05d17df10c8d4",
                "sha256:f57b4c16c62fa2760b7e3d97c35b255512fb6b59a259730f36ba32ce9f8e342f"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4' and python_version < '4'",
            "version": "==1.26.6"
        }
    },
    "develop": {}
}

```
</details>

**Comment by matteius** [comment]
@mistressofjellyfish I am closing this issue as it seems to work find on the latest `pipenv==2022.1.8`

```
mdavis@matt-VirtualBox:~/shared-projects/pipenv-4763$ pipenv install 'git+https://github.com/fkie-cad/common_helper_files.git#egg=common_helper_files'

Creating a virtualenv for this project...

Pipfile: /home/mdavis/shared-projects/pipenv-4763/Pipfile

Using /usr/bin/python3 (3.9.7) to create virtualenv...

⠦ Creating virtual environment...created virtual environment CPython3.9.7.final.0-64 in 339ms

  creator CPython3Posix(dest=/home/mdavis/.virtualenvs/pipenv-4763-UhlJ-2S8, clear=False, no_vcs_ignore=False, global=False)

  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/mdavis/.local/share/virtualenv)

    added seed packages: pip==21.3.1, setuptools==59.5.0, wheel==0.37.0

  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator



✔ Successfully created virtual environment! 

Virtualenv location: /home/mdavis/.virtualenvs/pipenv-4763-UhlJ-2S8

Creating a Pipfile for this project...

Installing git+https://github.com/fkie-cad/common_helper_files.git#egg=common_helper_files...

Adding common_helper_files to Pipfile's [packages]...

✔ Installation Succeeded 

Pipfile.lock not found, creating...

Locking [dev-packages] dependencies...

Locking [packages] dependencies...

Building requirements...

Resolving dependencies...

✔ Success! 

Updated Pipfile.lock (51903b)!

Installing dependencies from Pipfile.lock (51903b)...

  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00

mdavis@matt-VirtualBox:~/shared-projects/pipenv-4763$ pipenv --version
pipenv, version 2022.1.8
```
