### ISSUE TITLE
Failed to create virtual environment

### ISSUE THREAD

**Issue by lu5her** [pypa/pipenv#4764]
os: 5.12.19-1-MANJARO
=================================================
Creating a virtualenv for this project...
Pipfile: /home/lu5her/web_dsg/Pipfile
Using /usr/bin/python3.9 (3.9.6) to create virtualenv...
⠹ Creating virtual environment...TypeError: expected string or bytes-like object

✘ Failed creating virtual environment 

[pipenv.exceptions.VirtualenvCreationException]: 
Failed to create virtual environment.
=================================================
pipenv --support
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.5.29'`

Pipenv location: `'/home/lu5her/.local/lib/python3.9/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.9.6`: `/usr/bin/python3.9`
  - `3.9.6`: `/usr/bin/python3`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.12.19-1-MANJARO',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Tue Jul 20 20:57:37 UTC 2021',
 'python_full_version': '3.9.6',
 'python_version': '3.9',
 'sys_platform': 'linux'}
```

System environment variables:

  - `ANDROID_HOME`
  - `BROWSER`
  - `CASROOT`
  - `COLORFGBG`
  - `COLORTERM`
  - `CSF_DrawPluginDefaults`
  - `CSF_EXCEPTION_PROMPT`
  - `CSF_IGESDefaults`
  - `CSF_LANGUAGE`
  - `CSF_MDTVTexturesDirectory`
  - `CSF_MIGRATION_TYPES`
  - `CSF_OCCTResourcePath`
  - `CSF_PluginDefaults`
  - `CSF_SHMessage`
  - `CSF_STEPDefaults`
  - `CSF_ShadersDirectory`
  - `CSF_StandardDefaults`
  - `CSF_StandardLiteDefaults`
  - `CSF_TObjDefaults`
  - `CSF_TObjMessage`
  - `CSF_XCAFDefaults`
  - `CSF_XSMessage`
  - `CSF_XmlOcafResource`
  - `CUDA_PATH`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DESKTOP_SESSION`
  - `DISPLAY`
  - `DRAWDEFAULT`
  - `DRAWHOME`
  - `D_DISABLE_RT_SCREEN_SCALE`
  - `EDITOR`
  - `GTK2_RC_FILES`
  - `GTK3_MODULES`
  - `GTK_MODULES`
  - `GTK_RC_FILES`
  - `HG`
  - `HOME`
  - `KDED_STARTED_BY_KDEINIT`
  - `KDE_APPLICATIONS_AS_SCOPE`
  - `KDE_FULL_SESSION`
  - `KDE_SESSION_UID`
  - `KDE_SESSION_VERSION`
  - `KONSOLE_DBUS_SERVICE`
  - `KONSOLE_DBUS_SESSION`
  - `KONSOLE_DBUS_WINDOW`
  - `KONSOLE_VERSION`
  - `LANG`
  - `LANGUAGE`
  - `LC_ADDRESS`
  - `LC_IDENTIFICATION`
  - `LC_MEASUREMENT`
  - `LC_MONETARY`
  - `LC_NAME`
  - `LC_NUMERIC`
  - `LC_PAPER`
  - `LC_TELEPHONE`
  - `LC_TIME`
  - `LOGNAME`
  - `MAIL`
  - `MMGT_CLEAR`
  - `MOTD_SHOWN`
  - `OLDPWD`
  - `PAM_KWALLET5_LOGIN`
  - `PATH`
  - `PROFILEHOME`
  - `PWD`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `QT_LINUX_ACCESSIBILITY_ALWAYS_ON`
  - `SHELL`
  - `SHELL_SESSION_ID`
  - `SHLVL`
  - `SYSTEMD_EXEC_PID`
  - `TERM`
  - `USER`
  - `WINDOWID`
  - `XAUTHORITY`
  - `XCURSOR_SIZE`
  - `XCURSOR_THEME`
  - `XDG_CONFIG_DIRS`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_DATA_DIRS`
  - `XDG_RUNTIME_DIR`
  - `XDG_SEAT`
  - `XDG_SEAT_PATH`
  - `XDG_SESSION_CLASS`
  - `XDG_SESSION_DESKTOP`
  - `XDG_SESSION_ID`
  - `XDG_SESSION_PATH`
  - `XDG_SESSION_TYPE`
  - `XDG_VTNR`
  - `_`
  - `ZSH`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `LS_COLORS`
  - `PS1`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/lu5her/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:/home/lu5her/.fzf/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `EDITOR`: `/usr/bin/nano`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/lu5her/web_dsg`

---------------------------

**Comment by sharp** [comment]
There are too many issues when I use pipenv。
poor quality

**Comment by matteius** [comment]
@lu5her Definitely an environment issue going on without enough information to support you.   Things to possibly try:
1.) uninstall python versions from pyenv
2.) delete your old virtualenvs
3.) upgrade pip, make sure you're on latest pyenv
4.) make sure virtualenv is installed and working at a system or user level first
5.) try latest version of pipenv `2021.11.23`
