### ISSUE TITLE
--system option should skip virtual environment creation

### ISSUE THREAD

**Issue by Wenzil** [pypa/pipenv#4770]
### Is your feature request related to a problem? Please describe.

In a CI/CD process running in an already isolated environment, there is no need to create a Python virtual environment. It would be nice to have a way to skip creation of one.

### Describe the solution you'd like

Running `pipenv sync --system` should skip the creation of the virtual environment, since it will not be used as part of the command any way.

**Comment by LKI** [comment]
fixed in #4779
