### ISSUE TITLE
No evidence of run when using pipenv run.

### ISSUE THREAD

**Issue by ms-86** [pypa/pipenv#4773]
### Issue description
When running a python script using pipenv run nothing happens - no print output is generated. However, when running same script inside pipenv shell everything seems to be fine.

### Expected result

Both pipenv run main.py and pipenv shell and then python main.py should show the same output/

### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.
![image](https://user-images.githubusercontent.com/52154593/131049146-eb74954b-7ea6-4a1d-bfb7-43a1353b06a5.png)

![image](https://user-images.githubusercontent.com/52154593/131049622-02e0adab-46b4-499f-bf69-2e3809ad03ee.png)

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

main.py:
```
import os, sys

print("PYTHON =", sys.executable)
print("VERSION =", sys.version)
print("HTTP_PROXY =", os.environ.get("HTTP_PROXY"))
print("HTTPS_PROXY =", os.environ.get("HTTPS_PROXY"))
print("REQUESTS_CA_BUNDLE =", os.environ.get("REQUESTS_CA_BUNDLE"))
print("CURL_CA_BUNDLE =", os.environ.get("CURL_CA_BUNDLE "))
```

Pipfile
```[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = "*"
certifi = "*"

[dev-packages]

[requires]
python_version = "3.9"
```

**Comment by SARANYA233** [comment]
Is this issue solved or can I work on this?

**Comment by ms-86** [comment]
It's not solved.

**Comment by SARANYA233** [comment]
can I work on this issue?

**Comment by ms-86** [comment]
Not sure why you ask me.

**Comment by ms-86** [comment]
Hi

It turned out it's not working on one of my computers because something was wrong with file associations in Windows. So every python script had to be prefixed with python. After I fixed this then I could use `pipenv run script.py` with the results just as expected.
