### ISSUE TITLE
CLI docs broken

### ISSUE THREAD

**Issue by Berbe** [pypa/pipenv#4778]
### Issue description
[CLI docs](https://pipenv.pypa.io/en/latest/cli/)
[CLI docs source](https://pipenv.pypa.io/en/latest/_sources/cli.rst.txt)

### Expected result
CLI docs

### Actual result
Empty page

**Comment by matteius** [comment]
The page @Berbe linked to for CLI docs renders the phrase `Pipenv CLI Reference` which is what CLI docs source has in the source.  Otherwise it is just a blank set of documentation checked into the source.  What is the ask here?

**Comment by kdickerson** [comment]
@matteius There used to be actual documentation at that location, [WaybackMachine snapshot from May 8, 2021](http://web.archive.org/web/20210508175543/https://pipenv.pypa.io/en/latest/cli/).  Sometime between May 8, 2021 and [Aug 12, 2021](http://web.archive.org/web/20210812022148/https://pipenv.pypa.io/en/latest/cli/) the documentation disappeared.

Was the documentation intentionally removed?

**Comment by matteius** [comment]
I looked into this today.  I see what is happening, but not yet why it would have changed behavior after 2021.5.29

The sphinx build error is:  `/home/matteius/pipenv/docs/cli.rst:6: ERROR: "<class 'pipenv.cli.options.PipenvGroup'>" of type "pipenv:cli" is not derived from "click.BaseCommand"`

Verified in shell:
```
>>> from pipenv import cli
>>> import click
>>> isinstance(cli, click.BaseCommand)
False
```

For some reason in 2021.5.29 it is:
```
>>> from pipenv import cli
>>> import click
>>> isinstance(cli, click.BaseCommand)
True
```

**Comment by matteius** [comment]
Well I figured out what the change is -- we vendored click into the proejct, and so now in sphinx-click it is not detecting that we sub-class from click, because we are subclassing from pipenv.vendor.click.   Not clear what the easy fix will be, but that is why the docs are blank for CLI currently.

**Comment by matteius** [comment]
I fixed it using the sphinx conf.py and patched the class of click to be our vendored class.   The docs should generate upon the next release.

**Comment by akadouri** [comment]
@matteius the cli docs page (https://pipenv.pypa.io/en/latest/cli/) is still empty.  There was a release a couple days ago so I assume the docs should have been generated?

**Comment by matteius** [comment]
Well that's a bummer.  It was definitely fixed in a recent release, that I verified.   Apparently something about that monkeypatch for the docs build is fragile.  Will look into it at some point.
