### ISSUE TITLE
advanced usage (arguably the most useful part of the) docs is not visible in docs sidebar

### ISSUE THREAD

**Issue by kennethreitz** [pypa/pipenv#4783]

**Comment by matteius** [comment]
I think this may be a non-issue because nothing shows in the side-bar until you click that document section, at which point it does show in the side-bar the contents for that section.  See:
![image](https://user-images.githubusercontent.com/479892/162558167-109f63f0-9f39-424e-a9cf-638fbcd1f05d.png)
