### ISSUE TITLE
Exit With Error Code When pipenv --py Errors Out

### ISSUE THREAD

**Issue by Kurt-von-Laven** [pypa/pipenv#4788]
### Issue description

When `pipenv --py` is run outside of a virtualenv, it prints the following error message to stderr: "No virtualenv has been created for this project (`/path/to/cwd`) yet!"

### Expected result

I expected `pipenv --py` to give an error (non-zero) exit code in this case.

### Actual result

Pipenv exits with code `0`, indicating success and thereby complicating scripting.

### Steps to replicate

1. `cd / && pipenv -py`

**Comment by kobayashi** [comment]
This seems working properly in my environment.

```
bash-3.2$ pipenv --version
pipenv, version 2021.5.29
bash-3.2$ cd / && pipenv --py
No virtualenv has been created for this project (/) yet!
bash-3.2$

```

Which version are you trying and give us the output of the command?

**Comment by Kurt-von-Laven** [comment]
@kobayashi I am using the same version as you. You can use `echo $?` to see that Pipenv incorrectly exits with code `0` indicating success in this case.

**Comment by kobayashi** [comment]
I opened PR to fix. Thanks to let me know.
