### ISSUE TITLE
Infrastructure: pipenv.pypa.io documentation hosting migration

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pipenv#4794]
Hello! The PSF infrastructure currently hosts the pypa.io domain as well as the (soon unsupported) proxy configuration that fronts pipenv.pypa.io via Fastly with ReadTheDocs as the backend.

ReadTheDocs is deprecating support for this configuration, and it requires updating the CNAME record for pipenv.pypa.io to point directly to readthedocs.io.

In order to ensure minimal disruption to pipenv.pypa.io, the change in DNS can be coordinated with RTD via admin, but I need access as an administrator on the RTD project.

Can someone add `ewdurbin` as a Maintainer at https://readthedocs.org/dashboard/pipenv/users/?

**Comment by frostming** [comment]
duplicate #4805

**Comment by ewdurbin** [comment]
@frostming is the intention to stop hosting docs via pypa.io domain? If so I can remove the DNS record.

**Comment by frostming** [comment]
I guess not, I am not owning the RFTD site.

**Comment by bendem** [comment]
Since disruption already happened, it's probably best to update the DNS and once an RFTD admin is found, they can update the config there...
