### ISSUE TITLE
Pipenv docs site becomes unavailable due to invalid certificate

### ISSUE THREAD

**Issue by leogout** [pypa/pipenv#4805]
Hello, the pipenv website returns a 403 error code : 
https://pipenv.pypa.io/en/latest/
![image](https://user-images.githubusercontent.com/9843962/136930740-6956d335-3967-4e5d-ae5e-2997a5fb4d2d.png)

**Comment by pradyunsg** [comment]
This is the fallout of https://github.com/pypa/pipenv/issues/4794, I think.

**Comment by tucked** [comment]
Any updates on this? I cannot load https://docs.pipenv.org/ either.

**Comment by tucked** [comment]
> [Basically only ReadTheDocs project admins can fix this and neither of them (there are two) are responding](https://discord.com/channels/803025117553754132/803025117995073578/907694823186792459)

**Comment by tucked** [comment]
According to https://readthedocs.org/projects/pipenv/, the admins are @kennethreitz and @techalchemy.

**Comment by darkvertex** [comment]
Who controls the DNS on pypa.io though? At some point if none of the admins are responding someone should rebuild a static docs site on Github Pages or whatever, and the PyPA admins can adjust the DNS records so at least pipenv.pypa.io can have a working docs site.

It's been a month now. How much longer must the docs continue broken on this very popular and useful tool? 😐

**Comment by tucked** [comment]
I've emailed Kenneth and Dan, FWIW.

> Who controls the DNS on pypa.io though?

Apparently @ewdurbin

**Comment by abelcheung** [comment]
@darkvertex For now, use https://pipenv-fork.readthedocs.io/en/latest/

**Comment by frostming** [comment]
Latest news: the doc site is back to normal. Thank you all!

**Comment by darkvertex** [comment]
https://pipenv.pypa.io/ is back to normal 🎉
but https://docs.pipenv.org/ still has broken SSL btw.

Maybe it should be replaced with a redirect to the first link perhaps?
