### ISSUE TITLE
pipenv.pypa.io returns 403 error

### ISSUE THREAD

**Issue by mcstafford-git** [pypa/pipenv#4810]
### Issue description

[pipenv.pypa.io](https://pipenv.pypa.io/) currently shows a 403 error.

Is this a cloudflare config issue? I've checked from a couple of "down just for me" sites.

### Expected result

Detailed documentation, as implied by links in [README.md](https://github.com/pypa/pipenv/blob/master/README.md).

### Actual result

```html
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

### Steps to replicate

Open [pipenv.pypa.io](https://pipenv.pypa.io/).

**Comment by sschuberth** [comment]
This duplicates https://github.com/pypa/pipenv/issues/4805.
