### ISSUE TITLE
install_requires setup option doesn't work in some circumstances

### ISSUE THREAD

**Issue by aferguson-cmt** [pypa/pipenv#4814]
### Issue description
```
from setuptools import setup
setup(install_requires=['foo']) # This works
setup(install_requires='foo'.split()) # This doesn't work
```

### Expected result

These two calls to setup are equivalent, generating a Pipfile.lock with a dependency for 'foo'

### Actual result

When creating a list for `install_requires` in this way with split(), `pipenv install -e mypkg` doesn't add dependencies to Pipfile.lock. Specifying the list the other way, Pipfile.lock does get populated with dependencies

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).
This starts with no Pipfile and no Pipfile.lock.

```
$ cat foobar/setup.py
from setuptools import setup

r1 = ['Flask']
r2 = 'Flask'.split()

assert r1 == r2
assert type(r1) is type(r2)

setup(install_requires=r1)

$ cat foobar2/setup.py
from setuptools import setup

r1 = ['Flask']
r2 = 'Flask'.split()

assert r1 == r2
assert type(r1) is type(r2)

setup(install_requires=r2)

$ diff foobar/setup.py foobar2/setup.py 
9c9
< setup(install_requires=r1)
---
> setup(install_requires=r2)

$ ls
foobar	foobar2

$ python --version
Python 3.10.0
$ pipenv --version
pipenv, version 2021.5.29

$ pipenv --verbose install -e foobar > foobar.out 2>&1
$ mv Pipfile.lock foobar-Pipfile.lock
```
[foobar.out.txt](https://github.com/pypa/pipenv/files/7423835/foobar.out.txt)
[foobar-Pipfile.lock.txt](https://github.com/pypa/pipenv/files/7423831/foobar-Pipfile.lock.txt)
```
$ rm -rf Pipfile* foobar{,2}/src/*egg* foobar{,2}/{*egg*,*toml}; pipenv --rm
$ pipenv --verbose install -e foobar2 > foobar2.out 2>&1
$ mv Pipfile.lock foobar2-Pipfile.lock
```
[foobar2.out.txt](https://github.com/pypa/pipenv/files/7423837/foobar2.out.txt)
[foobar2-Pipfile.lock.txt](https://github.com/pypa/pipenv/files/7423832/foobar2-Pipfile.lock.txt)
```

$ ls *lock
foobar-Pipfile.lock	foobar2-Pipfile.lock
```
 **NOTE flask is not in foobar2-Pipfile.lock**
```
$ grep -i flask *lock
foobar-Pipfile.lock:        "flask": {
$ 
```
-------------------------------------------------------------------------------
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.5.29'`

Pipenv location: `'/Users/aferguson/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pipenv'`

Python location: `'/Users/aferguson/.pyenv/versions/3.10.0/bin/python3.10'`

Python installations found:

  - `3.10.0`: `/Users/aferguson/.pyenv/versions/3.10.0/bin/python3`
  - `3.10.0`: `/Users/aferguson/.pyenv/versions/3.10.0/bin/python3`
  - `3.9.7`: `/usr/local/bin/python3`
  - `3.9.7`: `/usr/local/bin/python3.9`
  - `3.9.0`: `/Users/aferguson/.pyenv/versions/3.9.0/bin/python3`
  - `3.8.12`: `/Users/aferguson/.pyenv/versions/init/bin/python3`
  - `3.8.12`: `/Users/aferguson/.pyenv/versions/foo/bin/python3`
  - `3.8.12`: `/Users/aferguson/.pyenv/versions/venv/bin/python3`
  - `3.8.6`: `/Users/aferguson/.pyenv/versions/a/bin/python3`
  - `3.8.6`: `/Users/aferguson/.pyenv/versions/3.8.6/bin/python3`
  - `3.8.2`: `/Users/aferguson/.pyenv/versions/3.8.2/bin/python3`
  - `3.8.2`: `/usr/bin/python3`
  - `3.7.2`: `/Users/aferguson/.pyenv/versions/3.7.2/bin/python3`
  - `2.7.16`: `/usr/local/bin/python2`
  - `2.7.16`: `/usr/local/bin/python2.7`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '20.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT '
                     '2021; root:xnu-7195.121.3~9/RELEASE_X86_64',
 'python_full_version': '3.10.0',
 'python_version': '3.10',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `ANDROID_HOME`
  - `TERM`
  - `SHELL`
  - `CMT_USER`
  - `TMPDIR`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `PYENV_VERSION`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `PYENV_DIR`
  - `PATH`
  - `__CFBundleIdentifier`
  - `PWD`
  - `JAVA_HOME`
  - `LANG`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `HOME`
  - `SHLVL`
  - `PYENV_SHELL`
  - `LOGNAME`
  - `__CF_USER_TEXT_ENCODING`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/aferguson/.pyenv/versions/3.10.0/bin:/usr/local/Cellar/pyenv/2.1.0/libexec:/usr/local/Cellar/pyenv/2.1.0/plugins/python-build/bin:/Users/aferguson/.pyenv/shims:/usr/local/opt/ruby/bin:/Users/aferguson/.fastlane/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/aferguson/.local/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/aferguson/pipenvbug`

---------------------------

Contents of `Pipfile` ('/Users/aferguson/pipenvbug/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
unknown = {editable = true, path = "./foobar2"}

[dev-packages]

[requires]
python_version = "3.8"

```

</details>

**Comment by frostming** [comment]
Fixed on v2021.11.5
