### ISSUE TITLE
Privacy error when visiting https://pipenv.pypa.io/en/latest/

### ISSUE THREAD

**Issue by rossettistone** [pypa/pipenv#4816]
Apologies if this is a duplicate of https://github.com/pypa/pipenv/issues/4805. The behavior is different enough, however, that I thought it worth filing.

### Issue description

Tried to visit https://pipenv.pypa.io/en/latest/ (linked from GitHub docs; available via Google), and was met with a "Privacy error" page in Chrome. 

<img width="923" alt="Screen Shot 2021-10-27 at 7 08 08 PM" src="https://user-images.githubusercontent.com/1834981/139174069-84a82fd7-207b-491a-9f57-ac827334dba5.png">

### Expected result

Expected to see docs website, as normal.

### Actual result

Privacy error (screenshot above).

### Steps to replicate

Visit https://pipenv.pypa.io/en/latest/. I've reproed the issue in an incognito browser, so I don't think any special local state is required.

**Comment by frostming** [comment]
duplicate #4805
