### ISSUE TITLE
Locking uses latest version of package dependency making whole dependency graph incompatible

### ISSUE THREAD

**Issue by HitLuca** [pypa/pipenv#4817]
I hope this is the right place to add the issue, I am having issues with my pipenv locking a set of packages. More specifically, it looks like it forces one particular dependency (`proto-plus`) to be the latest version (`1.19.7`), but the previous one (`1.19.6`) is what is required to get all the locking working.

`Pipfile`

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
mypy = "*"
pylint = "*"
black = "*"
pipenv-setup = "*"
pytest = "*"
pytest-cov = "*"
pip-check-reqs = "*"
pipenv-to-requirements = "*"
pytest-socket = "*"

[packages]
typeguard = "*"
python-dotenv = "*"
env-flag = "*"
boto3 = "*"
google-cloud-logging = "*"
werkzeug = "*"
chardet = "*" # needed until this PR is fixed (https://github.com/sarugaku/requirementslib/issues/296)
opentelemetry-sdk = "!=1.10a0"
opentelemetry-exporter-gcp-trace = "*"
opentelemetry-instrumentation-fastapi = "*"
opentelemetry-instrumentation-flask = "*"
pydantic = "*"
flask = "*"
fastapi = "*"

[requires]
python_version = "3.7"

[pipenv]
allow_prereleases = true
```

This is the output of `pipenv lock`, for the verbose version, see [the full output](https://github.com/pypa/pipenv/files/7433680/output.log)

```text
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 741, in _main
[ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 709, in resolve_packages
[ResolutionFailure]:       requirements_dir=requirements_dir,
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 692, in resolve
[ResolutionFailure]:       req_dir=requirements_dir
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1405, in resolve_deps
[ResolutionFailure]:       req_dir=req_dir,
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1110, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 835, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches protobuf<3.18.0,>=3.12.0,>=3.19.0,>=3.6.0 (from proto-plus==1.19.7->google-cloud-logging==2.6.0->-r /var/folders/v0/h686gzx15k38vm1553k3cfww0000gp/T/pipenv07by1xaxrequirements/pipenv-4lrfu96l-constraints.txt (line 16))
Tried: 2.0.3, 2.3.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 3.0.0, 3.0.0, 3.1.0, 3.1.0.post1, 3.1.0.post1, 3.2.0, 3.2.0, 3.3.0, 3.4.0, 3.4.0, 3.5.0.post1, 3.5.0.post1, 3.5.1, 3.5.1, 3.5.2, 3.5.2, 3.5.2.post1, 3.5.2.post1, 3.6.0, 3.6.0, 3.6.1, 3.6.1, 3.6.1, 3.7.0, 3.7.0, 3.7.0, 3.7.1, 3.7.1, 3.7.1, 3.8.0, 3.8.0, 3.8.0, 3.9.0, 3.9.0, 3.9.0, 3.9.1, 3.9.1, 3.9.1, 3.9.2, 3.9.2, 3.9.2, 3.10.0, 3.10.0, 3.10.0, 3.11.0, 3.11.0, 3.11.0, 3.11.1, 3.11.1, 3.11.1, 3.11.2, 3.11.2, 3.11.2, 3.11.3, 3.11.3, 3.11.3, 3.12.0, 3.12.1, 3.12.2, 3.12.2, 3.12.2, 3.12.4, 3.12.4, 3.12.4, 3.13.0, 3.13.0, 3.13.0, 3.14.0, 3.14.0, 3.14.0, 3.15.0, 3.15.0, 3.15.0, 3.15.1, 3.15.1, 3.15.1, 3.15.2, 3.15.2, 3.15.2, 3.15.3, 3.15.3, 3.15.3, 3.15.4, 3.15.4, 3.15.4, 3.15.5, 3.15.5, 3.15.5, 3.15.6, 3.15.6, 3.15.6, 3.15.7, 3.15.7, 3.15.7, 3.15.8, 3.15.8, 3.15.8, 3.16.0, 3.16.0, 3.16.0, 3.17.0, 3.17.0, 3.17.0, 3.17.1, 3.17.1, 3.17.1, 3.17.2, 3.17.2, 3.17.2, 3.17.3, 3.17.3, 3.17.3, 3.18.0, 3.18.0, 3.18.0, 3.18.1, 3.18.1, 3.18.1, 3.19.0, 3.19.0, 3.19.0
Tried pre-versions: 2.0.0b0, 3.0.0a2, 3.0.0a3, 3.0.0b1, 3.0.0b1.post1, 3.0.0b1.post2, 3.0.0b2, 3.0.0b2, 3.0.0b2.post1, 3.0.0b2.post1, 3.0.0b2.post2, 3.0.0b2.post2, 3.0.0b3, 3.0.0b4, 3.0.0b4, 3.2.0rc1, 3.2.0rc1, 3.2.0rc1.post1, 3.2.0rc1.post1, 3.2.0rc2, 3.2.0rc2, 3.7.0rc2, 3.7.0rc2, 3.7.0rc2, 3.7.0rc3, 3.7.0rc3, 3.7.0rc3, 3.8.0rc1, 3.8.0rc1, 3.8.0rc1, 3.9.0rc1, 3.9.0rc1, 3.9.0rc1, 3.10.0rc1, 3.10.0rc1, 3.10.0rc1, 3.11.0rc1, 3.11.0rc1, 3.11.0rc1, 3.11.0rc2, 3.11.0rc2, 3.11.0rc2, 3.12.0rc1, 3.12.0rc2, 3.13.0rc3, 3.13.0rc3, 3.13.0rc3, 3.14.0rc1, 3.14.0rc1, 3.14.0rc1, 3.14.0rc2, 3.14.0rc2, 3.14.0rc2, 3.14.0rc3, 3.14.0rc3, 3.14.0rc3, 3.15.0rc1, 3.15.0rc1, 3.15.0rc1, 3.15.0rc2, 3.15.0rc2, 3.15.0rc2, 3.16.0rc1, 3.16.0rc1, 3.16.0rc1, 3.16.0rc2, 3.16.0rc2, 3.16.0rc2, 3.17.0rc1, 3.17.0rc1, 3.17.0rc1, 3.17.0rc2, 3.17.0rc2, 3.17.0rc2, 3.18.0rc1, 3.18.0rc1, 3.18.0rc1, 3.18.0rc2, 3.18.0rc2, 3.18.0rc2, 3.19.0rc1, 3.19.0rc1, 3.19.0rc1, 3.19.0rc2, 3.19.0rc2, 3.19.0rc2, 4.0.0rc1, 4.0.0rc1, 4.0.0rc1, 4.0.0rc2, 4.0.0rc2, 4.0.0rc2
There are incompatible versions in the resolved dependencies:
  protobuf<3.18.0,>=3.12.0 (from google-api-core[grpc]==1.31.3->google-cloud-logging==2.6.0->-r /var/folders/v0/h686gzx15k38vm1553k3cfww0000gp/T/pipenv07by1xaxrequirements/pipenv-4lrfu96l-constraints.txt (line 16))
  protobuf>=3.12.0 (from googleapis-common-protos==1.53.0->google-api-core[grpc]==2.2.0->google-cloud-logging==2.6.0->-r /var/folders/v0/h686gzx15k38vm1553k3cfww0000gp/T/pipenv07by1xaxrequirements/pipenv-4lrfu96l-constraints.txt (line 16))
  protobuf>=3.19.0 (from proto-plus==1.19.7->google-cloud-logging==2.6.0->-r /var/folders/v0/h686gzx15k38vm1553k3cfww0000gp/T/pipenv07by1xaxrequirements/pipenv-4lrfu96l-constraints.txt (line 16))
  protobuf>=3.6.0 (from google-cloud-audit-log==0.2.0->google-cloud-logging==2.6.0->-r /var/folders/v0/h686gzx15k38vm1553k3cfww0000gp/T/pipenv07by1xaxrequirements/pipenv-4lrfu96l-constraints.txt (line 16))
  protobuf>=3.6.0 (from grpcio-status==1.41.1->google-api-core[grpc]==2.2.0->google-cloud-logging==2.6.0->-r /var/folders/v0/h686gzx15k38vm1553k3cfww0000gp/T/pipenv07by1xaxrequirements/pipenv-4lrfu96l-constraints.txt (line 16))
```

`google-cloud-logging` is the package that requires `proto-plus`, and `proto-plus` sets a constraint on `protobuf` which makes the whole set of dependencies incompatible (`protobuf<3.18.0,>=3.12.0,>=3.19.0,>=3.6.0` when `proto-plus==1.19.7`).

If I manually add `proto-plus = "==1.19.6"` on my `Pipfile`, the whole locking process completes without errors. What I am finding weird is that there is no particular constraint on `proto-plus` to be of  a specific version, as it is not a pinned package on my `Pipfile`. One detail that may be useful, is that `proto-plus==1.19.7` was released [less than a day ago](https://github.com/googleapis/proto-plus-python/releases/tag/v1.19.7).

Please let me know if you would like to have the `Pipfile.lock` associated with this locking run.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.5.29'`

Pipenv location: `'/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2021.5.29_1/libexec/bin/python3.10'`

Python installations found:

  - `3.9.7`: `/usr/local/bin/python3`
  - `3.9.7`: `/usr/local/bin/python3.9`
  - `3.8.9`: `/usr/bin/python3`
  - `3.8.3`: `/Library/Frameworks/Python.framework/Versions/3.8/bin/python3`
  - `3.8.3`: `/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8`
  - `3.8.3`: `/usr/local/bin/python3.8`
  - `3.7.4`: `/Library/Frameworks/Python.framework/Versions/3.7/bin/python3`
  - `3.7.4`: `/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m`
  - `3.7.4`: `/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7`
  - `3.7.4`: `/usr/local/bin/python3.7m`
  - `3.7.4`: `/usr/local/bin/python3.7`
  - `3.6.5`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3`
  - `3.6.5`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6`
  - `3.6.5`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m`
  - `3.6.5`: `/usr/local/bin/python3.6`
  - `3.6.5`: `/usr/local/bin/python3.6m`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '20.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT '
                     '2021; root:xnu-7195.141.6~3/RELEASE_X86_64',
 'python_full_version': '3.10.0',
 'python_version': '3.10',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `TERM_PROGRAM`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `TERM_PROGRAM_VERSION`
  - `ORIGINAL_XDG_CURRENT_DESKTOP`
  - `ZSH`
  - `USER`
  - `COMMAND_MODE`
  - `KUBECONFIG`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `PAGER`
  - `LSCOLORS`
  - `_`
  - `__CFBundleIdentifier`
  - `PWD`
  - `LANG`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `HOME`
  - `VSCODE_GIT_ASKPASS_MAIN`
  - `LESS`
  - `LOGNAME`
  - `VSCODE_GIT_IPC_HANDLE`
  - `VSCODE_GIT_ASKPASS_NODE`
  - `GIT_ASKPASS`
  - `COLORTERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2021.5.29_1/libexec/tools:/usr/local/sbin:/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon:/Users/lsimonetto/google-cloud-sdk/bin:/Users/lsimonetto/.poetry/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/opt/openssl@1.1/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/Applications/Chia.app/Contents/Resources/app.asar.unpacked/daemon:/Users/lsimonetto/google-cloud-sdk/bin:/Users/lsimonetto/.poetry/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/opt/openssl@1.1/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Users/lsimonetto/.npm-packages/bin:/Users/lsimonetto/.npm-packages/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/lsimonetto/PythonProjects/my-project`

---------------------------

removed `Pipfile` as it's posted above
</details>

**Comment by matteius** [comment]
It appears that version of `proto-plus` requires a higher version of `protobuf` than the prior version did, one that is not compatible with what the version of the parent package you are using `google-cloud-logging==2.6.0`.    See:
```
# from proto-plus = "==1.19.7"
install_requires=("protobuf >= 3.19.0",),

# from proto-plus = "==1.19.6"
install_requires=("protobuf >= 3.12.0",),

# from google-cloud-logging 2.6.0 setup calls out 
"google-api-core[grpc] >= 1.26.0, <3.0.0dev",

# google-api-core[grpc] thus resolved to v1.31.3 in your output, checking that setup.py we see that it requires:
"protobuf >= 3.12.0, < 3.18.0",
```

Hence this is not a pipenv issue, because the new version of `proto-plus` requires `protobuf >= 3.19.0` but the version of `google-cloud-logging==2.6.0` had dependencies on  `protobuf < 3.18.0` hence the tree had become incompatible.   Since you realized the prior version of `proto-plus` worked, you called it out specifically which fixed the issue.  Had `google-cloud-logging==2.6.0` foreseen potential issues with allowing new versions of `proto-plus` to be installed, that project may have wanted the pin the version instead.

It does look like there are newer versions of the packages at play here as well, so I suspect you would get different results today upgrading `google-cloud-logging==2.7.0` which was latest at time of writing.
