### ISSUE TITLE
Documentation site not accessible

### ISSUE THREAD

**Issue by garu57** [pypa/pipenv#4820]
Site pipenv.pypa.io is not accessible with browser. Both Firefox and Chrome return this screen
![security-issue](https://user-images.githubusercontent.com/15155315/139531127-3e4c6728-3a79-433b-b2e1-8282525aead8.png)

This condition cannot be bypassed, but hacking the security settings of the browser which would expose to security issues with possibly forged sites, so the documentation remains de facto not available.

**Comment by nietonfir** [comment]
Apparently a certificate problem, it is only valid for: ssl1036715.cloudflaressl.com, *.readthedocs.io, readthedocs.io

**Comment by frostming** [comment]
Duplicate with #4805

**Comment by tucked** [comment]
> Duplicate with #4805

This is not a 403, though 🤔
