### ISSUE TITLE
Any way to custom or change venv name?

### ISSUE THREAD

**Issue by Bugrakca** [pypa/pipenv#4824]
![resim](https://user-images.githubusercontent.com/23137173/140432777-0c349029-757e-4e8f-bf7a-b12f7b7000de.png)
I want to change the name of the environment. If possible, the short version works too.

Thank you.

**Comment by melvyn-oviavo** [comment]
No. Asked and answered. A lot. Please [look here](https://github.com/pypa/pipenv/issues/1226).
