### ISSUE TITLE
pipenv (2021.11.5) cannot run `pipenv shell`

### ISSUE THREAD

**Issue by mgmarino** [pypa/pipenv#4828]
### Issue description

With the recent new release, we have witnessed a number of issues.  In this case, running `pipenv shell` on an already created venv (with the previous version of `pipenv`) yields:

```python
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/cli/command.py", line 419, in shell
    do_shell(
  File "/usr/local/lib/python3.9/site-packages/pipenv/core.py", line 2309, in do_shell
    shell = choose_shell()
TypeError: choose_shell() missing 1 required positional argument: 'project'
```

This also fails with a newly generated project:

```
new_projectr pipenv --python 3.7
Creating a virtualenv for this project...
Pipfile: /Users/mgmarino/tmp/new_projectr/Pipfile
Using /Users/mgmarino/.pyenv/versions/3.7.9/bin/python3.7m (3.7.9) to create virtualenv...
⠼ Creating virtual environment...created virtual environment CPython3.7.9.final.0-64 in 911ms
  creator CPython3Posix(dest=/Users/mgmarino/tmp/new_projectr/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/mgmarino/Library/Application Support/virtualenv)
    added seed packages: pip==21.2.4, setuptools==58.2.0, wheel==0.37.0
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/mgmarino/tmp/new_projectr/.venv
new_projectr pipenv shell
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/cli/command.py", line 419, in shell
    do_shell(
  File "/usr/local/lib/python3.9/site-packages/pipenv/core.py", line 2309, in do_shell
    shell = choose_shell()
TypeError: choose_shell() missing 1 required positional argument: 'project'
```

### Expected result

Well, it should work as it did previously.  :-) 

### Steps to replicate

Listed above

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.11.5'`

Pipenv location: `'/usr/local/lib/python3.9/site-packages/pipenv'`

Python location: `'/usr/local/opt/python@3.9/bin/python3.9'`

Python installations found:

  - `3.9.6`: `/usr/local/bin/python3`
  - `3.9.6`: `/usr/local/bin/python3.9`
  - `3.8.9`: `/usr/bin/python3`
  - `3.7.9`: `/Users/mgmarino/.pyenv/versions/3.7.9/bin/python3`
  - `3.7.8`: `/Users/mgmarino/.pyenv/versions/3.7.8/bin/python3`
  - `3.6.10`: `/Users/mgmarino/.pyenv/versions/3.6.10/bin/python3`
  - `2.7.17`: `/usr/local/bin/python`
  - `2.7.17`: `/usr/local/bin/python2`
  - `2.7.17`: `/usr/local/bin/pythonw`
  - `2.7.17`: `/usr/local/bin/python2.7`
  - `2.7.16`: `/usr/bin/python`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/pythonw`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '20.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT '
                     '2021; root:xnu-7195.141.6~3/RELEASE_X86_64',
 'python_full_version': '3.9.6',
 'python_version': '3.9',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_SESSION_ID`
  - `SSH_AUTH_SOCK`
  - `LC_TERMINAL_VERSION`
  - `COLORFGBG`
  - `ITERM_PROFILE`
  - `SQLITE_EXEMPT_PATH_FROM_VNODE_GUARDS`
  - `XPC_FLAGS`
  - `PWD`
  - `SHELL`
  - `__CFBundleIdentifier`
  - `SECURITYSESSIONID`
  - `LC_CTYPE`
  - `TERM_PROGRAM_VERSION`
  - `TERM_PROGRAM`
  - `PATH`
  - `DISPLAY`
  - `LC_TERMINAL`
  - `COLORTERM`
  - `COMMAND_MODE`
  - `TERM`
  - `HOME`
  - `TMPDIR`
  - `USER`
  - `XPC_SERVICE_NAME`
  - `LOGNAME`
  - `LaunchInstanceID`
  - `__CF_USER_TEXT_ENCODING`
  - `ITERM_SESSION_ID`
  - `SHLVL`
  - `OLDPWD`
  - `ZSH`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `JAVA_HOME`
  - `GRAILS_OPTS`
  - `HOMEBREW_GITHUB_API_TOKEN`
  - `SDKMAN_DIR`
  - `SDKMAN_PLATFORM`
  - `SDKMAN_VERSION`
  - `SDKMAN_LEGACY_API`
  - `SDKMAN_CURRENT_API`
  - `SDKMAN_CANDIDATES_DIR`
  - `GRADLE_HOME`
  - `GRAILS_HOME`
  - `GROOVY_HOME`
  - `NVM_DIR`
  - `NVM_CD_FLAGS`
  - `NVM_NODEJS_ORG_MIRROR`
  - `NVM_IOJS_ORG_MIRROR`
  - `MANPATH`
  - `NVM_BIN`
  - `LC_ALL`
  - `LANG`
  - `LIQUIBASE_HOME`
  - `MYSQLXPB_PROTOBUF_INCLUDE_DIR`
  - `MYSQLXPB_PROTOBUF_LIB_DIR`
  - `MYSQLXPB_PROTOC`
  - `PYSPARK_DRIVER_PYTHON`
  - `PYSPARK_PYTHON`
  - `PIPENV_VENV_IN_PROJECT`
  - `PYENV_SHELL`
  - `AWSUME_COMMAND`
  - `AWS_ACCESS_KEY_ID`
  - `AWS_SECRET_ACCESS_KEY`
  - `AWS_SESSION_TOKEN`
  - `AWS_REGION`
  - `AWS_DEFAULT_REGION`
  - `AWSUME_PROFILE`
  - `AWSUME_EXPIRATION`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`

Debug–specific environment variables:

  - `PATH`: `/usr/local/opt/nvm/versions/node/v12.13.0/bin:/Users/mgmarino/.sdkman/candidates/groovy/current/bin:/Users/mgmarino/.sdkman/candidates/grails/current/bin:/Users/mgmarino/.sdkman/candidates/gradle/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/mgmarino/tmp/new_projectr`

---------------------------

Contents of `Pipfile` ('/Users/mgmarino/tmp/new_projectr/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.7"

```

</details>

**Comment by mgmarino** [comment]
I would humbly suggest revoking the released version in its current state.

**Comment by Datamined** [comment]
As a temporary fix you can install previous stable release with 
`pip install pipenv==2021.5.29` or
`pipx install pipenv==2021.5.29`

**Comment by mgmarino** [comment]
> As a temporary fix you can install previous stable release with `pip install pipenv==2021.5.29` or `pipx install pipenv==2021.5.29`

We indeed will.  :-)  This was, unfortunately, one of our dependencies that we *have not* locked until now.

**Comment by frostming** [comment]
I am not the pypi admin, but i will release a hotfix quickly
