### ISSUE TITLE
Cannot load the documentation at pipenv.pypa.io

### ISSUE THREAD

**Issue by tucked** [pypa/pipenv#4830]
![image](https://user-images.githubusercontent.com/48501491/140542779-0da9e050-51d5-442a-bce4-e75aeeb9ed87.png)

*edit: For convenience: https://pipenv.pypa.io/*

**Comment by tucked** [comment]
Same as #4820

**Comment by abelcheung** [comment]
But #4820 was errorneously closed as dup of #4805 (which describes a 403 error).

**Comment by tucked** [comment]
@frostming Why was this closed? I'm still seeing the same issue trying to load the docs....
