### ISSUE TITLE
pipenv 2021.11.5 regresses back to issue #2961

### ISSUE THREAD

**Issue by lukaso** [pypa/pipenv#4834]
### Issue description

It appears that issue https://github.com/pypa/pipenv/issues/2961 has returned. This is occurring on a mac.

### Expected result

pipenv should operate without throwing an exception.

### Actual result

```sh
Traceback (most recent call last):
  File "/Users/buildgimp/.new_local/bin/pipenv", line 5, in <module>
    from pipenv import cli
  File "/Users/buildgimp/.new_local/lib/python/site-packages/pipenv/__init__.py", line 22, in <module>
    from pipenv.vendor.vistir.compat import ResourceWarning, fs_str
  File "/Users/buildgimp/.new_local/lib/python/site-packages/pipenv/vendor/vistir/__init__.py", line 4, in <module>
    from .compat import (
  File "/Users/buildgimp/.new_local/lib/python/site-packages/pipenv/vendor/vistir/compat.py", line 13, in <module>
    from .backports.tempfile import NamedTemporaryFile as _NamedTemporaryFile
  File "/Users/buildgimp/.new_local/lib/python/site-packages/pipenv/vendor/vistir/backports/__init__.py", line 6, in <module>
    from .tempfile import NamedTemporaryFile
  File "/Users/buildgimp/.new_local/lib/python/site-packages/pipenv/vendor/vistir/backports/tempfile.py", line 15, in <module>
    from backports.weakref import finalize
ImportError: No module named weakref
``` 

### Steps to replicate

Pipenv is deeply embedded in a jhbuild install, so not able to extract to exactly reproduce. But it appears that pipenv is simply not functioning at all.

### "Workaround"

`pip install --upgrade --user pipenv==2021.5.29`

**Comment by theocodes** [comment]
I can second this. On Monterey (M1 Pro) and python 2.7.17, a simple `pip install -U pipenv` which installs the latest release resulted in the same issue above when running `pipenv`. 

rolling back was the only solution :(

**Comment by Timmeeh** [comment]
Also in Docker image `python:2.7-slim`.

Running `pip install pipenv && pipenv --version` has the same result. Using "workaround" version works.

**Comment by mattbasta** [comment]
I'm also seeing this with the latest release(s) on Github Actions (Ubuntu) on python 3.8

**Comment by jshwi** [comment]
I was also getting this, had to peg installation to `pipenv==2021.5.29`

**Comment by frostming** [comment]
Sorry but 2021.11.5 no longer supports Python 2.7, please stick to the old versions.

I will yank the release of that problematic release after I got the permission of PyPI package.

**Comment by majg0** [comment]
> yank the release of that problematic release

Does this mean that things will start working again during builds without the workaround?

If you could please ping us when it's out, that would be great.

Thank you for your help! 🙏🏼

**Comment by majg0** [comment]
Hi! Do you know whether we can remove the workaround now?

**Comment by lukaso** [comment]
I'm not using the workaround anymore. I think the issue has been fixed (but I'm not quite sure what I did so I'm not certain).
