### ISSUE TITLE
Documentation unreachable due to HTTPS certificate problem

### ISSUE THREAD

**Issue by bartgenuit** [pypa/pipenv#4836]
Hi, it seems the documentation over at
https://pipenv.pypa.io/
is currently unavailable when using Firefox (version 94.0, 64 bit). According to my browser, this is due to HTTP Strict Transport Security (HSTS) being enabled, while there are issues with the certificate. A scan with an [SSL Server Test](https://www.ssllabs.com/ssltest/analyze.html?d=pipenv.pypa.io) reports
> Certificate name mismatch 
> (We were able to retrieve a certificate for this site, but the domain names listed in it do not match the domain name you requested us to inspect.)

**Comment by danmackinlay** [comment]
same as #4820
