### ISSUE TITLE
sync --clear does not work anymore

### ISSUE THREAD

**Issue by Berbe** [pypa/pipenv#4846]
### Issue description
With version `2021.11.5.post0` on Debian, `pipenv sync --clear` does not work anymore.

### Expected result
```
Installing dependencies from Pipfile.lock (***)
[...]
```
like on `2021.5.29`
### Actual result
```
clearing
```
followed by exit code > 0
### Steps to replicate
1. Update to `pipenv` v2021.11.5.post0
2. Run `pipenv sync --clear`

**Comment by frostming** [comment]
The flag has not effect.

**Comment by Berbe** [comment]
@frostming I don't get your answer.
Did you mean you fixed something? If so, could you link to the involved PR/commit? Or a milestone?

Something was definitely fixed: the command, as stated, was working in v`2021.5.29`, has been broken in v`2021.11.5`, and has been working again since v`2121.11.9`, which was released after this bug report... hence this bug report was/is to the point, and valuable.

**Comment by frostming** [comment]
The option's help string is "clear the caches" but no caches were cleared actually. So the latest release changed it to a no-op flag instead of quit directly.

**Comment by Berbe** [comment]
I'm glad you acknowledge this bug report is tied to an actual change. :)

This option was advertised in the command contextual help: there was indeed no reason its use should create any immediate exit with an error status.
If you want to remove it, you'll need to take into account some people might be using it, and plan ahead changes (ie no-op + documentation change clearly indicating the deprecation + clear announcement of point in time when it will be completely removed).

In the meantime, testing commands run whatever set of existing, non-properly deprecated options, are being used, might be an interesting test scenario :)

**Comment by Berbe** [comment]
That option is still listed is v`2021.11.9`, but is *not* described as doing nothing nor marked as deprecated.
