### ISSUE TITLE
Jinja2 in the vendor directory isn't used. Can be dropped.

### ISSUE THREAD

**Issue by oz123** [pypa/pipenv#4858]
The directory contains a copy of jinja2 which isn't used by the user code.
Digging through the history ... This was used to be a requirement for click-completion.
However, this is now dropped, and instead click own completion is used.

Dropping it can reduce the package size.

The tests code uses it, but one can expect developers to be able to install jinja2.

**Comment by frostming** [comment]
Thanks, we need to figure out is there any other unneeded vendors. Can you help?

**Comment by oz123** [comment]
I'm already on it. Tracking this on the rebuild for Gentoo.
Thanks for the quick response!
