### ISSUE TITLE
Shell completion is gone

### ISSUE THREAD

**Issue by diogobaeder** [pypa/pipenv#4864]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

The regular shell completion (`pipenv --completion`) has vanished somehow. The argument just doesn't exist anymore in version 2021.11.9.

### Expected result

I expected it to keep working, as I need it and as it's documented as a supported feature. If this is no longer supported, then it should be taken out of the documentation, and ideally there should be a section stating that it has been removed and why.

### Actual result

```
2021-11-14 12:48:01 master brandindex@us2 diogobaeder@diogobaeder-desktop ~ 
 $ pipenv --version
pipenv, version 2021.11.9
2021-11-14 12:48:05 master brandindex@us2 diogobaeder@diogobaeder-desktop ~ 
 $ pipenv --completion
Usage: pipenv [OPTIONS] COMMAND [ARGS]...
Try 'pipenv -h' for help.

Error: No such option: --completion Did you mean --python?
```

### Steps to replicate

Just run `pipenv --completion` in a terminal.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.11.9'`

Pipenv location: `'/usr/lib/python3.9/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.9.7`: `/usr/bin/python3.9`
  - `3.9.7`: `/usr/bin/python`
  - `3.9.7`: `/usr/bin/python3`
  - `3.8.12`: `/usr/bin/python3.8`
  - `3.7.12`: `/usr/bin/pypy3`
  - `3.6.15`: `/usr/bin/python3.6`
  - `3.6.15`: `/usr/bin/python3.6m`
  - `3.5.10`: `/usr/bin/python3.5`
  - `3.5.10`: `/usr/bin/python3.5m`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.15.2-arch1-1',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Fri, 12 Nov 2021 19:22:10 +0000',
 'python_full_version': '3.9.7',
 'python_version': '3.9',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `SESSION_MANAGER`
  - `COLORTERM`
  - `CSF_MDTVTexturesDirectory`
  - `NVM_INC`
  - `HISTCONTROL`
  - `XDG_MENU_PREFIX`
  - `CSF_DrawPluginDefaults`
  - `TERMINATOR_DBUS_PATH`
  - `PYTHONHASHSEED`
  - `CSF_LANGUAGE`
  - `SSH_AUTH_SOCK`
  - `CSF_MIGRATION_TYPES`
  - `GRADLE_HOME`
  - `MONGO_HOME`
  - `TERMINATOR_UUID`
  - `XMODIFIERS`
  - `DESKTOP_SESSION`
  - `VELOCIRAPTOR_URL`
  - `CSF_OCCTResourcePath`
  - `DISTCC_HOSTS`
  - `CSF_STEPDefaults`
  - `EDITOR`
  - `PWD`
  - `XDG_SESSION_DESKTOP`
  - `LOGNAME`
  - `XDG_SESSION_TYPE`
  - `DRAWHOME`
  - `SYSTEMD_EXEC_PID`
  - `XAUTHORITY`
  - `CSF_StandardLiteDefaults`
  - `MOTD_SHOWN`
  - `GDM_LANG`
  - `VIRTUALENVWRAPPER_SCRIPT`
  - `INSTACLEAN_CLIENT_SECRET`
  - `HOME`
  - `USERNAME`
  - `LANG`
  - `XDG_CURRENT_DESKTOP`
  - `HADOOP_PID_DIR`
  - `VTE_VERSION`
  - `WAYLAND_DISPLAY`
  - `INSTACLEAN_CLIENT_ID`
  - `VIRTUALENVWRAPPER_WORKON_CD`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `FBUSER`
  - `INVOCATION_ID`
  - `TERMINATOR_DBUS_NAME`
  - `FBURL`
  - `MANAGERPID`
  - `GOROOT`
  - `HADOOP_SLAVES`
  - `CSF_ShadersDirectory`
  - `CSF_EXCEPTION_PROMPT`
  - `CSF_XmlOcafResource`
  - `NVM_DIR`
  - `WORKON_HOME`
  - `GNOME_SETUP_DISPLAY`
  - `CSF_SHMessage`
  - `GEM_PATH`
  - `XDG_SESSION_CLASS`
  - `IBUS_DISABLE_SNOOPER`
  - `TERM`
  - `HADOOP_CONF_DIR`
  - `USER`
  - `CSF_StandardDefaults`
  - `CSF_IGESDefaults`
  - `VIRTUALENVWRAPPER_PROJECT_FILENAME`
  - `DISPLAY`
  - `CSF_XCAFDefaults`
  - `SHLVL`
  - `NVM_CD_FLAGS`
  - `VELOCIRAPTOR_AUTH_DOMAIN`
  - `SKIP_JVM_TESTS`
  - `PAGER`
  - `SPARK_HOME`
  - `QT_IM_MODULE`
  - `DESKTOP_AUTOSTART_ID`
  - `CSF_PluginDefaults`
  - `BIXMODEL_TEST_DB`
  - `CSF_TObjMessage`
  - `KUBECONFIG`
  - `CASROOT`
  - `MOZ_PLUGIN_PATH`
  - `XDG_RUNTIME_DIR`
  - `MKLROOT`
  - `KUBE_EDITOR`
  - `SOUP_NTLM_AUTH_DEBUG`
  - `JOURNAL_STREAM`
  - `CSF_XSMessage`
  - `MMGT_CLEAR`
  - `XDG_DATA_DIRS`
  - `FBTOKEN`
  - `PATH`
  - `CARGOPATH`
  - `CSF_TObjDefaults`
  - `__avn_active_file`
  - `VIRTUALENVWRAPPER_HOOK_DIR`
  - `GDMSESSION`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `HG`
  - `NVM_BIN`
  - `MAIL`
  - `SITE_PACKAGES`
  - `DRAWDEFAULT`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `YG_DEV`
  - `HADOOP_LOG_DIR`
  - `GOPATH`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/lib/distcc/bin/:/home/diogobaeder/.nvm/versions/node/v10.15.3/bin:/home/diogobaeder/.config/composer/vendor/bin:/home/diogobaeder/bin:/home/diogobaeder/.avn/bin:/usr/local/bin:/usr/bin:/var/lib/snapd/snap/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/go/bin:/home/diogobaeder/go/bin:/home/diogobaeder/.cargo/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `vim`
  - `LANG`: `pt_BR.utf8`
  - `PWD`: `/home/diogobaeder`

---------------------------

</details>

**Comment by frostming** [comment]
Yeah, README was updated in b61fafe0c0f81a9cb5ee383d779db1a796e47d23. The change was mentioned in the CHANGELOG

**Comment by diogobaeder** [comment]
I tried that other approach with Bash and it fails badly:

```
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 33, in <module>
    sys.exit(load_entry_point('pipenv==2021.11.9', 'console_scripts', 'pipenv')())
  File "/usr/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1057, in main
    self._main_shell_completion(extra, prog_name, complete_var)
  File "/usr/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1132, in _main_shell_completion
    rv = shell_complete(self, ctx_args, prog_name, complete_var, instruction)
  File "/usr/lib/python3.9/site-packages/pipenv/vendor/click/shell_completion.py", line 45, in shell_complete
    echo(comp.source())
  File "/usr/lib/python3.9/site-packages/pipenv/vendor/click/shell_completion.py", line 324, in source
    self._check_version()
  File "/usr/lib/python3.9/site-packages/pipenv/vendor/click/shell_completion.py", line 319, in _check_version
    raise RuntimeError(
RuntimeError: Couldn't detect Bash version, shell completion is not supported.

```

**Comment by matteius** [comment]
@diogobaeder I did a search for that click error and came across this:  https://github.com/pallets/click/issues/1940
