### ISSUE TITLE
Latest pipenv install does not work on travis-ci python instances

### ISSUE THREAD

**Issue by CNDW** [pypa/pipenv#4867]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

The latest release (2021.11.15) started causing failures in our CI after install, our logs look like
```
$ pip install -U pipenv
Collecting pipenv
  Downloading pipenv-2021.11.15-py2.py3-none-any.whl (3.6 MB)
Requirement already satisfied, skipping upgrade: virtualenv-clone>=0.2.5 in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from pipenv) (0.5.3)
Requirement already satisfied, skipping upgrade: certifi in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from pipenv) (2019.3.9)
Requirement already satisfied, skipping upgrade: pip>=18.0 in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from pipenv) (20.1.1)
Requirement already satisfied, skipping upgrade: virtualenv in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from pipenv) (16.6.0)
Requirement already satisfied, skipping upgrade: setuptools>=36.2.1 in /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages (from pipenv) (47.3.1)
Installing collected packages: pipenv
  Attempting uninstall: pipenv
    Found existing installation: pipenv 2018.11.26
    Uninstalling pipenv-2018.11.26:
      Successfully uninstalled pipenv-2018.11.26
Successfully installed pipenv-2021.11.15
0.79s$ ./pipenv.sh
---INSTALLING Pipfile TO VIRTUALENV---
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Removing virtualenv (/home/travis/virtualenv/python3.7.1)...
./pipenv.sh: line 3: /home/travis/virtualenv/python3.7.1/bin/pipenv: No such file or directory
```
line 3 of `pipenv.sh` is the following
```
pipenv --rm && pipenv --python 3.7
```
It appears that the pip install of pipenv is no longer linking itself into the venv `bin` directory

### Expected result

`pip install -U pipenv` should not fail when trying to access the `pipenv` command from ci after install

### Actual result

calling `pipenv` after install raises a `/home/travis/virtualenv/python3.7.1/bin/pipenv: No such file or directory` exception

### Steps to replicate

Using a fresh docker container on ubuntu 16.04, install pipenv using `pip install -U pipenv` and run the `pipenv` command

-------------------------------------------------------------------------------

> Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

Pipenv does not execute, I cannot provide `pipenv --support` logs

**Comment by jcjones1515** [comment]
I suspect that the call to `pipenv --rm` would previously *not* remove the virtualenv because it wasn't created by pipenv, but now it is removing it as of 2021.11.15.

**Comment by CNDW** [comment]
I did test it without the "pipenv --rm" and got the same results
