### ISSUE TITLE
Editable install doesn't work for projects without setup.py - PEP 660 compatibility

### ISSUE THREAD

**Issue by vakker** [pypa/pipenv#4869]
### Issue description

Using the example `Pipfile` from the [docs](https://pipenv.pypa.io/en/latest/basics/) and running `pipenv install -e .` fails. It's also mentioned in other parts, e.g. [here](https://pipenv.pypa.io/en/latest/advanced/#pipfile-vs-setup-py).

Is there a `setup.py` or anything else required? It's not clear from the docs, so I'm not sure if this is an issue of I'm just doing this wrong.

### Expected result

Install the package as editable.

### Actual result

Error (see below).

### Steps to replicate

Pipfile:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = "*"

[dev-packages]
pytest = "*"
```

Command:
```
pipenv install --dev -e .
```

Or:
```
pipenv install -e .
```

<details><summary>Error</summary>

```
Installing -e ....

⠋ Installing...Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3739, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 3400, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 2711, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3103, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 92, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'.'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 966, in _parse_name_from_line
    self._requirement = init_requirement(self.line)
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/utils.py", line 197, in init_requirement
    req = Requirement.parse(name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3150, in parse
    req, = parse_requirements(s)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3096, in parse_requirements
    yield Requirement(line)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3105, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "'.'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vince/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/cli/command.py", line 193, in install
    do_install(
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/core.py", line 2037, in do_install
    pkg_requirement = Requirement.from_line(pkg_line)
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2674, in from_line
    parsed_line = Line(line)
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 171, in __init__
    self.parse()
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1304, in parse
    self.parse_name()
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1027, in parse_name
    name = self._parse_name_from_line()
  File "/home/vince/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 968, in _parse_name_from_line
    raise RequirementError(
pipenv.vendor.requirementslib.exceptions.RequirementError: Failed parsing requirement from '.'
```

</details>

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.11.15'`

Pipenv location: `'/home/vince/.local/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.9.7`: `/home/vince/.pyenv/versions/3.9.7/bin/python3.9`
  - `3.8.12`: `/home/vince/.pyenv/versions/cm2-p1/bin/python3.8`
  - `3.8.12`: `/home/vince/.pyenv/versions/3.8.12/bin/python3.8`
  - `3.8.12`: `/home/vince/.pyenv/versions/spg-3d/bin/python3.8`
  - `3.8.10`: `/usr/bin/python3.8`
  - `3.8.10`: `/usr/bin/python`
  - `3.8.10`: `/usr/bin/python3`
  - `3.8.10`: `/bin/python3.8`
  - `3.8.10`: `/bin/python`
  - `3.8.10`: `/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.10',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.11.0-40-generic',
 'platform_system': 'Linux',
 'platform_version': '#44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021',
 'python_full_version': '3.8.10',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `CLIENT_ID`
  - `CLIENT_SECRET`
  - `COLORTERM`
  - `CPATH`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DEFAULTS_PATH`
  - `DESKTOP_SESSION`
  - `DISPLAY`
  - `FPATH`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `GNOME_SHELL_SESSION_MODE`
  - `GNOME_TERMINAL_SCREEN`
  - `GNOME_TERMINAL_SERVICE`
  - `GOPATH`
  - `GOROOT`
  - `GPG_AGENT_INFO`
  - `GTK_MODULES`
  - `GTK_PATH`
  - `HOME`
  - `IM_CONFIG_PHASE`
  - `INVOCATION_ID`
  - `JOURNAL_STREAM`
  - `KUBEFLOW_SRC`
  - `LANG`
  - `LANGUAGE`
  - `LD_LIBRARY_PATH`
  - `LESS`
  - `LOGNAME`
  - `LSCOLORS`
  - `LS_COLORS`
  - `MANAGERPID`
  - `MANDATORY_PATH`
  - `OLDPWD`
  - `PAGER`
  - `PATH`
  - `PERIOD`
  - `PWD`
  - `PYENV_ROOT`
  - `PYENV_SHELL`
  - `QT_ACCESSIBILITY`
  - `QT_DIR`
  - `QT_IM_MODULE`
  - `SESSION_MANAGER`
  - `SHELL`
  - `SHLVL`
  - `SSH_AGENT_PID`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `TMUX`
  - `TMUX_PANE`
  - `USER`
  - `USERNAME`
  - `VERIFICATION_TOKEN`
  - `VTE_VERSION`
  - `WINDOWPATH`
  - `XAUTHORITY`
  - `XDG_CONFIG_DIRS`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_DATA_DIRS`
  - `XDG_MENU_PREFIX`
  - `XDG_RUNTIME_DIR`
  - `XDG_SESSION_CLASS`
  - `XDG_SESSION_DESKTOP`
  - `XDG_SESSION_TYPE`
  - `XMODIFIERS`
  - `ZPLUG_BIN`
  - `ZPLUG_CACHE_DIR`
  - `ZPLUG_ERROR_LOG`
  - `ZPLUG_FILTER`
  - `ZPLUG_HOME`
  - `ZPLUG_LOADFILE`
  - `ZPLUG_LOG_LOAD_FAILURE`
  - `ZPLUG_LOG_LOAD_SUCCESS`
  - `ZPLUG_PROTOCOL`
  - `ZPLUG_REPOS`
  - `ZPLUG_ROOT`
  - `ZPLUG_USE_CACHE`
  - `ZSH`
  - `_`
  - `_ZPLUG_AWKPATH`
  - `_ZPLUG_CONFIG_SUBSHELL`
  - `_ZPLUG_OHMYZSH`
  - `_ZPLUG_PREZTO`
  - `_ZPLUG_URL`
  - `_ZPLUG_VERSION`
  - `ZPLUG_THREADS`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/vince/.zplug/bin:/home/vince/.pyenv/shims:/home/vince/.pyenv/bin:/home/vince/.npm/bin/:/home/vince/.platformio/penv/bin:/usr/local/cuda/bin:/home/vince/.krew/bin:/home/vince/.emacs.d/bin:/home/vince/.local/bin:/home/vince/local/bin:/home/vince/.cargo/bin:/home/vince/bin:/home/vince/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/vince/.fzf/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/vince/workspace/test2`

---------------------------

Contents of `Pipfile` ('/home/vince/workspace/test2/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = "*"

[dev-packages]
pytest = "*"

```

Contents of `Pipfile.lock` ('/home/vince/workspace/test2/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "8d14434df45e0ef884d6c3f6e8048ba72335637a8631cc44792f52fd20b6f97a"
        },
        "pipfile-spec": 6,
        "requires": {},
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "certifi": {
            "hashes": [
                "sha256:78884e7c1d4b00ce3cea67b44566851c4343c120abd683433ce934a68ea58872",
                "sha256:d62a0163eb4c2344ac042ab2bdf75399a71a2d8c7d47eac2e2ee91b9d6339569"
            ],
            "version": "==2021.10.8"
        },
        "charset-normalizer": {
            "hashes": [
                "sha256:e019de665e2bcf9c2b64e2e5aa025fa991da8720daa3c1138cadd2fd1856aed0",
                "sha256:f7af805c321bfa1ce6714c51f254e0d5bb5e5834039bc17db7ebe3a4cec9492b"
            ],
            "markers": "python_version >= '3'",
            "version": "==2.0.7"
        },
        "idna": {
            "hashes": [
                "sha256:84d9dd047ffa80596e0f246e2eab0b391788b0503584e8945f2368256d2735ff",
                "sha256:9d643ff0a55b762d5cdb124b8eaa99c66322e2157b69160bc32796e824360e6d"
            ],
            "markers": "python_version >= '3'",
            "version": "==3.3"
        },
        "requests": {
            "hashes": [
                "sha256:6c1246513ecd5ecd4528a0906f910e8f0f9c6b8ec72030dc9fd154dc1a6efd24",
                "sha256:b8aa58f8cf793ffd8782d3d8cb19e66ef36f7aba4353eec859e74678b01b07a7"
            ],
            "index": "pypi",
            "version": "==2.26.0"
        },
        "urllib3": {
            "hashes": [
                "sha256:4987c65554f7a2dbf30c18fd48778ef124af6fab771a377103da0585e2336ece",
                "sha256:c4fdf4019605b6e5423637e01bc9fe4daef873709a7973e195ceba0a62bbc844"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4' and python_version < '4'",
            "version": "==1.26.7"
        }
    },
    "develop": {
        "attrs": {
            "hashes": [
                "sha256:149e90d6d8ac20db7a955ad60cf0e6881a3f20d37096140088356da6c716b0b1",
                "sha256:ef6aaac3ca6cd92904cdd0d83f629a15f18053ec84e6432106f7a4d04ae4f5fb"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "version": "==21.2.0"
        },
        "iniconfig": {
            "hashes": [
                "sha256:011e24c64b7f47f6ebd835bb12a743f2fbe9a26d4cecaa7f53bc4f35ee9da8b3",
                "sha256:bc3af051d7d14b2ee5ef9969666def0cd1a000e121eaea580d4a313df4b37f32"
            ],
            "version": "==1.1.1"
        },
        "packaging": {
            "hashes": [
                "sha256:096d689d78ca690e4cd8a89568ba06d07ca097e3306a4381635073ca91479966",
                "sha256:14317396d1e8cdb122989b916fa2c7e9ca8e2be9e8060a6eff75b6b7b4d8a7e0"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==21.2"
        },
        "pluggy": {
            "hashes": [
                "sha256:4224373bacce55f955a878bf9cfa763c1e360858e330072059e10bad68531159",
                "sha256:74134bbf457f031a36d68416e1509f34bd5ccc019f0bcc952c7b909d06b37bd3"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==1.0.0"
        },
        "py": {
            "hashes": [
                "sha256:51c75c4126074b472f746a24399ad32f6053d1b34b68d2fa41e558e6f4a98719",
                "sha256:607c53218732647dff4acdfcd50cb62615cedf612e72d1724fb1a0cc6405b378"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "version": "==1.11.0"
        },
        "pyparsing": {
            "hashes": [
                "sha256:c203ec8783bf771a155b207279b9bccb8dea02d8f0c9e5f8ead507bc3246ecc1",
                "sha256:ef9d7589ef3c200abe66653d3f1ab1033c3c419ae9b9bdb1240a85b024efc88b"
            ],
            "markers": "python_version >= '2.6' and python_version not in '3.0, 3.1, 3.2'",
            "version": "==2.4.7"
        },
        "pytest": {
            "hashes": [
                "sha256:131b36680866a76e6781d13f101efb86cf674ebb9762eb70d3082b6f29889e89",
                "sha256:7310f8d27bc79ced999e760ca304d69f6ba6c6649c0b60fb0e04a4a77cacc134"
            ],
            "index": "pypi",
            "version": "==6.2.5"
        },
        "toml": {
            "hashes": [
                "sha256:806143ae5bfb6a3c6e736a764057db0e6a0e05e338b5630894a5f779cabb4f9b",
                "sha256:b3bda1d108d5dd99f4a20d24d9c348e91c4db7ab1b749200bded2f839ccbe68f"
            ],
            "markers": "python_version >= '2.6' and python_version not in '3.0, 3.1, 3.2'",
            "version": "==0.10.2"
        }
    }
}

```
</details>

**Comment by frostming** [comment]
> Is there a setup.py or anything else required?

Yes, `setup.py` is required.

**Comment by vakker** [comment]
Thanks, so then it's a question of [PEP 660](https://www.python.org/dev/peps/pep-0660/) compatibility? Even though it specifies "pyproject.toml based builds" and pipenv uses Pipfile.

**Comment by jonaslb** [comment]
This appears to be working now as long as a "new enough" pip is installed in the virtualenv.

Virtualenv by default uses system pip, even if a newer pip is installed user locally. This pip is usually too old, so a newer pip needs to be installed. Similarly in venvs created by Pipenv, one can run `pipenv run pip install --upgrade pip` to do that. 

However my `pipenv` is now (pretty sure it didn't just a moment ago) creating prefixes with already upgraded pip in them, so I don't need workarounds any more. I'm not sure if `pipenv` installs `pip` in a newer version for itself now? Or if it copies the one I have in `~/.local`?

**Comment by matteius** [comment]
@jonaslb pipenv vendors in its own pip and AFAIK it always uses that one.   I updated the pip vendoring to latest pip `22.0.4` starting in the `2022.4.20` release.

**Comment by jonaslb** [comment]
@matteius No, Pipenv calls `pip` from inside the venv as a subprocess. The code is here: https://github.com/pypa/pipenv/blob/5ed54193366f8e61dc80d98eb32606685354ed79/pipenv/core.py#L1543

**Comment by matteius** [comment]
@jonaslb That might explain something I've seen but I am still not convinced, on the whole pipenv uses the vendor pip that is included and this is the first inclination of a code path that might not.  Can you open a new issue about that?  It seems problematic and is inconsistent with the expectation that we vendor in pip for this very reason.  It probably is the missing link of why I was unable to completely pin setuptools while testing a unit test that broke when setuptools upgraded recently.

**Comment by matteius** [comment]
@jonaslb This somewhat recent commit from @frostming seems to  change away from the vendor'd pip to the running one, but I don't think it would affect the other code path you mention.  This though is another spot that pip gets invoked and it definitely used to use the vendor one.   I am running the test suite locally in the background to see if changing this back breaks anything.
https://github.com/pypa/pipenv/commit/33cbabe20cfda8cd7c3e62fc9731aa7776db7566

**Comment by jonaslb** [comment]
I don't really think pipenv should be vendoring pip at all to begin with, so don't do this for me, haha. I don't have a problem with using pip as a subprocess, in fact this seems the "most right" way to do it!

**Comment by matteius** [comment]
@jonaslb It is in fact an issue because we have modified pip internals for say index restriction guarantees.  If in some cases it isn't using that correct pip version it is a real issue.

**Comment by jonaslb** [comment]
But this type of restrictions would be specified in the temporary requirements file that is given to pip, no? Probably the patched pip internals are used for "resolution work" before giving this specification to the real pip for installation?
