### ISSUE TITLE
ModuleNotFoundError inside Pipenv environment

### ISSUE THREAD

**Issue by Irfan-Ahmad-byte** [pypa/pipenv#4882]
On Ubuntu I'm trying to install python packages inside Pipenv environment. I do start the Pipenv shell by typing
`pipenv shell`
and the
`pip install <package name>`
But, it is giving this error

> ModuleNotFoundError: No module named 'distutils.cmd'

Pip is working fine with none Error like the above, outside Pipenv.
The error is appearing only inside Pipenv.

## I'm using python3.9.9

**Comment by Irfan-Ahmad-byte** [comment]
I tried reinstalling the python version, pip, pipenv.
But, nothing changed. Even pip3 didn't work.

**Comment by frostming** [comment]
Please print the python version inside the virtualenv and run `python -c "import distutils.cmd`  to see what it outputs

**Comment by Irfan-Ahmad-byte** [comment]
The python version inside Pipenv VENV is python3.9.9 and the error persists.
![bandicam 2021-11-26 12-07-31-133](https://user-images.githubusercontent.com/76489214/143541001-fb6e815f-601d-4afa-b6f4-d67a88ff72b1.jpg)

**Comment by Irfan-Ahmad-byte** [comment]
It is working fine with python3.8.
python3.9 is giving the error.

**Comment by yuzhujiutian** [comment]
The module not found likely means the packages aren't installed.

You can try:
`sudo apt-get install python3-distutils`

Refer to:
https://askubuntu.com/a/1239882
https://askubuntu.com/questions/1239829/modulenotfounderror-no-module-named-distutils-util

**Comment by Irfan-Ahmad-byte** [comment]
trying
`sudo apt install python3-distutils`
did not solve the problem.
Rather
`sudo apt install python3.9-distutils`
solved the problem.

**Comment by Irfan-Ahmad-byte** [comment]
# Error / Bug

With python3.9.9 and 3.10, Pipenv gives the error

>  ModuleNotFoundError: No module named 'distutils.cmd'

while trying to install any python package, leaving pip unworkable.

# Platform/OS

**Ubuntu 20**

# Solution

This issue is resolved by installing ***distutils*** manually with

`sudo apt install python3.9-distutils`

# Exception

It is working fine below python3.9.9, and I don't have to install **distutils** manually.

**Comment by frostming** [comment]
> It is working fine below python3.9.9, and I don't have to install distutils manually.

It is not difficult to find it out. First make sure you can reproduce the bug

On below python3.9.9:

```
python -c "import distutils,sys;print(sys.path);print(distutils.__file__)
```
See where `distutils` is from
On python 3.9.9:

```
python -c "import distutils,sys;print(sys.path)
```
See if `sys.path` doesn't contain `distutils` package.

**Comment by matteius** [comment]
I am compelled to close this issue for now given it appears to be an environment issue, which the original poster confirmed that in the Solution.  Please note @Irfan-Ahmad-byte that including the output from `pipenv --support` would be helpful in future issue reports.   It appears that the codebase (at least the vendor components) in pipenv depend on distutils being present.  There should probably be a separate issue (maybe already is) to track dependence on distutils since:

`Note:  The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives`
