### ISSUE TITLE
Add URLs called and reason they're called when locking and the verbose flag is set; module resolution failures

### ISSUE THREAD

**Issue by Josh-Marshall-FactSet** [pypa/pipenv#4889]
### Is your feature request related to a problem? Please describe.

I need to pull python modules from two servers, my employer's and the public.  I am having persistent difficulties locking.  All modules fail to resolve irrespective of their actual location.  I can manually trace through what should be the URL calls, and everything is there for the public and private servers.

### Describe the solution you'd like

When the verbose flag is set when locking, each outgoing URL is logged as well with the particular action which is pulling that URL.  Currently, I get a stack trace in triplicate instead of what practically failed and how.

### Describe alternatives you've considered

I don't know enough to even suggest.   There could be something which 'just' fixes my problem that I've been unable to find.

### Additional context

Here is an example run:
```bash
jmarshall@jmarshallpc:/mnt/c/Users/jmarshall/Documents/<OMITTED>$ REQUESTS_CA_BUNDLE="" CURL_CA_BUNDLE="" python3.9 -m pipenv lock -v
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
Reporter.starting()
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.starting()
Reporter.adding_requirement(SpecifierRequirement('requests-mock==1.9.3'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('requests-mock==1.9.3'), None)
CRITICAL:pipenv.patched.notpip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement requests-mock==1.9.3 (from versions: none)
Traceback (most recent call last):
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    raise RequirementsConflicted(criterion)
pipenv.patched.notpip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('requests-mock==1.9.3')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 343, in resolve
    raise ResolutionImpossible(e.criterion.information)
pipenv.patched.notpip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('requests-mock==1.9.3'), parent=None)]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/utils.py", line 875, in resolve
    results = resolver.resolve(self.constraints, check_supported_wheels=False)
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/resolver.py", line 103, in resolve
    raise error from e
pipenv.patched.notpip._internal.exceptions.DistributionNotFound: No matching distribution found for requests-mock==1.9.3
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 766, in <module>
    main()
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 760, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 743, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 704, in resolve_packages
    results, resolver = resolve(
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/resolver.py", line 685, in resolve
    return resolve_deps(
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/utils.py", line 1370, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/utils.py", line 1099, in actually_resolve_deps
    resolver.resolve()
  File "/home/jmarshall/.local/lib/python3.9/site-packages/pipenv/utils.py", line 877, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: No matching distribution found for requests-mock==1.9.3
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.11.23'`

Pipenv location: `'/home/jmarshall/.local/lib/python3.9/site-packages/pipenv'`

Python location: `'/usr/bin/python3.9'`

Python installations found:

  - `3.9.5`: `/usr/bin/python3.9`
  - `3.9.5`: `/bin/python3.9`
  - `3.8.10`: `/usr/bin/python3.8`
  - `3.8.10`: `/usr/bin/python3`
  - `3.8.10`: `/usr/bin/python`
  - `3.8.10`: `/bin/python3.8`
  - `3.8.10`: `/bin/python3`
  - `3.8.10`: `/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.72-microsoft-standard-WSL2',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Wed Oct 28 23:40:43 UTC 2020',
 'python_full_version': '3.9.5',
 'python_version': '3.9',
 'sys_platform': 'linux'}
```

System environment variables:

  - `CURL_CA_BUNDLE`
  - `REQUESTS_CA_BUNDLE`
  - `SHELL`
  - `WSL_DISTRO_NAME`
  - `WT_SESSION`
  - `NAME`
  - `PWD`
  - `LOGNAME`
  - `HOME`
  - `LANG`
  - `WSL_INTEROP`
  - `LS_COLORS`
  - `LESSCLOSE`
  - `TERM`
  - `LESSOPEN`
  - `USER`
  - `SHLVL`
  - `WSLENV`
  - `XDG_DATA_DIRS`
  - `PATH`
  - `HOSTTYPE`
  - `WT_PROFILE_ID`
  - `OLDPWD`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/Python38/Scripts/:/mnt/c/Program Files/Python38/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/ccm:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/SysWOW64/~FDSTools/SysinternalsSuite:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Users/jmarshall/AppData/Roaming/nvm:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files (x86)/Yarn/bin/:/mnt/c/Program Files/:/mnt/c/Program Files/MATLAB/R2020a/bin:/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/:/mnt/c/Program Files (x86)/Windows Kits/10/Microsoft Application Virtualization/Sequencer/:/mnt/c/Program Files (x86)/PuTTY/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Git/mingw64/bin:/mnt/c/Program Files/Git/usr/bin:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Users/jmarshall/AppData/Roaming/nvm:/mnt/c/Program Files/nodejs:/mnt/c/Users/jmarshall/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/jmarshall/AppData/Local/Yarn/bin:/mnt/c/Users/jmarshall/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/jmarshall/AppData/Local/Programs/Fiddler:/mnt/c/Users/jmarshall/AppData/Roaming/factsetio/bin/:/mnt/c/Users/jmarshall/AppData/Local/atom/bin:/mnt/c/Users/jmarshall/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/nodejs:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/mnt/c/Users/jmarshall/Documents/cts-formula-api`

---------------------------

Contents of `Pipfile` ('/mnt/c/Users/jmarshall/Documents/cts-formula-api/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = false
name = "pypi"

[[source]]
url = "<OMITTED>"
verify_ssl = false
name = "FactSet"

[requires]
python_version = "3.9"

[packages]
googleapis-common-protos = {version="==1.54.0", index="pypi"}
gunicorn = {version="==20.1.0", index="pypi"}
lightstep = {version="==4.4.8", index="pypi"}
openapi-spec-validator = {version="==0.3.1", index="pypi"}
opentracing = {version="==2.4.0", index="pypi"}
protobuf = {version="==3.19.1", index="pypi"}
python-rapidjson = {version="==1.5", index="pypi"}
requests = {version="==2.26.0", index="pypi"}
requests-mock = {version="==1.9.3", index="pypi"}
coverage = {version="==6.2", index="pypi"}
nox = {version="==2021.10.1", index="pypi"}
"fds.python-logging-clp" = {version="==2.0.1", index="FactSet"}
dictdiffer = {version="==0.9.0", index="pypi"}
"fds.cts-table-service-protos" = {version="==0.3.1", index="FactSet"}
grpcio = {version="==1.42.0", index="pypi"}
grpcio-testing = {version="==1.42.0", index="pypi"}
grpcio-tools = {version="==1.42.0", index="pypi"}
Flask = {version="==2.0.2", index="pypi"}
Flask-Cors = {version="==3.0.10", index="pypi"}
json-stream = {version="==1.3.0", index="pypi"}

[dev-packages]

[pipenv]
allow_prereleases = true

```

</details>

**Comment by matteius** [comment]
@Josh-Marshall-FactSet just a clarifying question: is your issue specifically caused by using a private package repository?  Also, a new version of pipenv was released yesterday, `pipenv==2022.1.8` and in the Changelog has:
* Fix a bug of installation fails when extra index url is given. #4881

Wondering if is related; can you recheck issue with new version?  Thanks!
