### ISSUE TITLE
pipenv lock -r unnecessarily produces dependencies included in install_requires which results in a conflict

### ISSUE THREAD

**Issue by gawdzer** [pypa/pipenv#4891]
### Issue description

Creating a requirements.txt file with `pipenv lock -r > requirements.txt` produces dependencies from imported packages with install_requires

### Expected result

requirements.txt does not contain dependencies from **shared-a  setup.py install-requires**

```
-i https://pypi.org/simple
-e ssh://git@github.com/company/shared_a.git@babfb191416822bc8673bb89d83b720a09a267a9#egg=shared-a
python_full_version >= '3.6.1'
```

### Actual result

requirements.txt contains a dependency from **shared-a  setup.py install-requires**

```
-i https://pypi.org/simple
-e ssh://git@github.com/company/shared_a.git@babfb191416822bc8673bb89d83b720a09a267a9#egg=shared-a
ssh://git@github.com/company/shared_b.git@a1ffa042215360f4a16ea7e38dba93aa656f040f8#egg=shared-b
python_full_version >= '3.6.1'
```

pip install requirements.txt output:

```
ERROR: Cannot install -r reqs.text (line 3) and shared-b 1.0 (from ssh://git@github.com/company/shared_b.git@a1ffa042215360f4a16ea7e38dba93aa656f040f8#egg=shared-b) because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested shared-b 1.0 (from ssh://git@github.com/company/shared_b.git@a1ffa042215360f4a16ea7e38dba93aa656f040f8#egg=shared-b)
    shared-a 1.0 depends on shared-b 1.0 (from ssh://git@github.com/company/shared_b.git#egg=shared-b)
```

### Steps to replicate

project-a - Contains a Pipfile
shared-a - Contains setup.py file
shared-b - a simple python package

**Pipfile in project_a** packages section contains the following entry:

 `shared_a = {editable="true", git = "ssh://git@github.com/company/shared-a.git"}`

**setup.py in shared_a** contains the following:

```
setup(name='shared_a',
      version='1.0',
      description='Test',
      author='Me',
      author_email='me@example.com',
      license='MIT',
      packages=find_packages(),
      install_requires=[
            'shared_b @ git+ssh://git@github.com/company/shared-b.git'
      ])
```

### the WHY
pip is already take care of importing dependencies listed under `install_requires`

-------------------------------------------------------------------------------
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.5.29'`

Pipenv location: `'/usr/local/Cellar/pipenv/2021.5.29/libexec/lib/python3.9/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2021.5.29/libexec/bin/python3.9'`

Python installations found:

  - `3.9.6`: `/Users/ewok/.local/share/virtualenvs/kalamate-shared-model-hW_i7_dZ/bin/python3`
  - `3.9.6`: `/Users/ewok/.local/share/virtualenvs/kalamate-shared-model-hW_i7_dZ/bin/python3.9`
  - `3.9.6`: `/Users/ewok/.local/share/virtualenvs/kalamate-shared-model-hW_i7_dZ/bin/python3`
  - `3.9.6`: `/Users/ewok/.local/share/virtualenvs/kalamate-shared-model-hW_i7_dZ/bin/python3.9`
  - `3.9.6`: `/usr/local/bin/python3`
  - `3.9.6`: `/usr/local/bin/python3.9`
  - `3.7.3`: `/Users/ewok/.pyenv/versions/3.7.3/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '20.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT '
                     '2021; root:xnu-7195.141.8~1/RELEASE_X86_64',
 'python_full_version': '3.9.6',
 'python_version': '3.9',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `LDFLAGS`
  - `TERM`
  - `SHELL`
  - `CPPFLAGS`
  - `TMPDIR`
  - `TERM_SESSION_ID`
  - `ZSH`
  - `__INTELLIJ_COMMAND_HISTFILE__`
  - `USER`
  - `COMMAND_MODE`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `LOGIN_SHELL`
  - `VIRTUAL_ENV`
  - `PAGER`
  - `LSCOLORS`
  - `TERMINAL_EMULATOR`
  - `_`
  - `LaunchInstanceID`
  - `__CFBundleIdentifier`
  - `PWD`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `HOME`
  - `LESS`
  - `LOGNAME`
  - `LC_CTYPE`
  - `SECURITYSESSIONID`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv‚Äìspecific environment variables:

Debug‚Äìspecific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2021.5.29/libexec/tools:/Users/ewok/.local/share/virtualenvs/kalamate-shared-model-hW_i7_dZ/bin:/Users/ewok/.pyenv/shims:/usr/local/bin:/Users/ewok/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands`
  - `SHELL`: `/bin/zsh`
  - `PWD`: `/Users/ewok/Desktop/sources/kalamate-shared-model`
  - `VIRTUAL_ENV`: `/Users/ewok/.local/share/virtualenvs/kalamate-shared-model-hW_i7_dZ`

---------------------------

```
</details>

**Comment by matteius** [comment]
I think the whole point of the lock file, as I understand it, is to lock ALL packages that the project depends on, and snapshot at that point in time their package hashes.  It would be similar to if you took your minimal requirements.txt file that also installed dependent packages through `install_requires` and then ran `pip freeze > requirements.txt` because at that point you are documenting what all requirements are to rebuild that virtual environment, even the ones that came from `install_requires`.  

 I suspect that Pipenv has had this behavior for a long time, as it is the intended behavior.   Another analogy I could make is comparing it to the npm lock file of a node project.  I haven't found anything in the documentation that would suggest this isn't intended behavior, but more importantly how would you guarantee the package hashes of packages your virtualenv depends on, but aren't in the lock file?
