### ISSUE TITLE
Feature: Command to verify hash in Pipfile.lock against packages in Pipfile (out-of-date check)

### ISSUE THREAD

**Issue by den4uk** [pypa/pipenv#4893]
When running `pipenv install --deploy`, it checks the hash in the **Pipfile.lock** file matches with the packages in the **Pipfile**. Upon a mismatch, an exception is raised, else it proceeds to install.

**NEW FEATURE**: It would be very used to have the hash verification step to be a standalone command, which could return an exit code if the hash is verified or not.

**User case.** 
This can come in useful in the CI/CD pipelines, where locking could be performed and committed when the hash is not verified. This could save a significant amount of time to avoid re-locking dependencies, especially when there are many of them.

**Comment by matteius** [comment]
I agree that this would be a useful feature.   Perhaps open a PR and we can push for it?

**Comment by den4uk** [comment]
Thanks for a suggestion, I opened a PR for an initial review. https://github.com/pypa/pipenv/pull/4896
