### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by frostming** [pypa/pipenv#4894]
This project is used by millions of people, but the number of contributions is not on par with the issues number. I am a bit burnt out by the bugs reports with the limited time of my open source as most of it has been devoted to PDM. I have been waiting for someone to pick up those issues but few show up. So I opened this issue to see if anyone is interested in maintaining it, please leave a comment below and I will add you to the members list.

Any contributions, including but not limited to issue triaging, bug fixing, and feature improvements are welcome. I am glad to offer help of any type.

**Comment by henrytseng** [comment]
Wow.  So sorry to hear that issues are building up and that you're getting overwhelmed.

**Comment by matteius** [comment]
Just a month ago I started a new job and we use pipenv.  I like the project and it solves a problem of automating locking package versions and documenting their known hash values for validation at install time, which has major security benefits over your basic requirements files.  We ran into an issue with the new versions published in November basically dropping 75% of the lock file based on the Pipenv file.   I intend to investigate that further as a starting point, and not sure how much time I'll have overall, but would be happy to lend a hand where I can.

**Comment by frostming** [comment]
@matteius Thank you for your effort triaging issues, I've added you as a co-maintainer, feel free to close invalid ones.

**Comment by matteius** [comment]
How exciting!  :-)  Thanks for your trust @frostming, I will do my best and begin slow--looks like is a lot of potential to trim it down over the next months.

**Comment by mattalexx** [comment]
I'm hoping I'll be able to find some time to look into a few bugs too.

**Comment by kobayashi** [comment]
Thanks to your effort to maintain this project @frostming. I like this project and can take a role for maintaining.

**Comment by frostming** [comment]
@mattalexx @kobayashi , thank you. You can just start contributing and I will add you to the maintainers at a suitable time.

**Comment by mattalexx** [comment]
@frostming I maybe have time to fix some bugs during a transition time. I do not have time to be an official maintainer.

**Comment by faizanalhassan** [comment]
Hi @frostming, 
I just saw your issue regarding the needs maintainer for this project. It would be great to contribute to this project. Because I had used it in a couple of projects and It will be a great honor for me to contribute to this open-source project. Please let me know how can I start because it will be my first experience contributing to an open-source community. 
Regards:
Faizan AlHassan

**Comment by frostming** [comment]
Hi, @mattalexx @faizanalhassan Thank you for the interest, you can start by triaging issues and answering questions in the Issues backlog. Fixing bugs would be more appreciated.

**Comment by tchappui** [comment]
I'm using pipenv on a day to day basis and thinks it makes work related to application dependensies easier both for developers and educators. I'm sorry to hear about your availability issues but can understand. While not having the availability to play a role as a maintainer, contributing to bug fixes for pipenv will definitely be one of my goal for the coming year. I quasi daily refer students to https://packaging.python.org/en/latest/tutorials/managing-dependencies/ and would be happy to contribute the stabilisation of the tool.

Kind regards, Thierry

**Comment by oz123** [comment]
Hi, I have been maintaining the Gentoo ebuild for quite a while and I'm familiar with the code base.
IMHO, I can contribute in the following areas:
 * Code clean up.
 * documentation updates
 * testing

**Comment by matteius** [comment]
I'm down to figure out how to make a release next.

**Comment by matteius** [comment]
Also for anyone else looking to help out, the `Documentation` label might be a good place to start for a first PR:  https://github.com/pypa/pipenv/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Documentation+%3Abook%3A%22

**Comment by oz123** [comment]
@pradyunsg unfortunately only he can pin it. But @matteius and myself are already very active.

**Comment by pradyunsg** [comment]
Well, I can do it as well -- so I've done that.

If y'all aren't looking for more maintainers, please say so and I'll unpin this. Let me know if there's folks with the write bit here who aren't members of the PyPA -- I'll add them in with write bit and to pypa-committers so that they get the ability to vote in the PyPA committer votes (see PEP 609). :)

**Comment by oz123** [comment]
Please add myself and @matteius, also we kind of have strange permissions here. We can push and merge, but we can't add new contributors. @frostming isn't always active.
Also, pipenv depends on many projects from https://github.com/sarugaku, but it seems abandoned. My efforts to contact the maintainers haven't been answered. We can fork the repositories, but we still lack permission on PyPI can this somehow be resolved via PyPA?

**Comment by oz123** [comment]
@frostming thanks for the quick response. I'll need to revisit which projects we needed patch.
@matteius is leading this, I'm helping on slack and reviews.

**Comment by matteius** [comment]
@frostming Its `requirementslib` and `pip-shims` that is currently blocking the update to pip 22.0.4 which solves a number of resolver issues for people.   If we could get collaborator to those would be a big help.   

@pradyunsg I would like to by added as a member of pypa and I suspect so would @oz123   -- Thanks for pinning this issue; I have been enjoying taking on a maintenance role for the project, however having more peer reviewers and folks triaging issues would be helpful in general.  As we try to clean some more things up here and always good to have more support rather than less.

**Comment by frostming** [comment]
> @frostming Its requirementslib and pip-shims that is currently blocking the update to pip 22.0.4 which solves a number of resolver issues for people. If we could get collaborator to those would be a big help.

I've sent the invitation

**Comment by uranusjr** [comment]
Please drop a word if you're interested in a sarugaku project. I don't maintain all of them either but we could work out a solution if needed; what exactly needs to be done depends on which one of them you wish to work on.

**Comment by xncbf** [comment]
I have been using pipenv for several months and created several open source projects and have contributed to various projects such as django, pydantic, and mypy stubs. It would be great if i could contribute even a small help.

**Comment by frostming** [comment]
Thanks to all, now we have a very active maintainer @matteius, and @oz123 as a reviewer. I will proceed to unpin this issue now. Anyone who drops in and is interested, welcome to contribute.

**Comment by matteius** [comment]
@uranusjr or @pradyunsg or @frostming  Would it be possible add myself https://pypi.org/user/matteiuspi/ and @oz123 to the maintainers in pypi and if someone could get a review of the current list?  I know that I don't really recognize the name [tuxtimo](https://pypi.org/user/tuxtimo/) or [JetBlackPope](https://pypi.org/user/JetBlackPope/) in my 5 months contributing to the project.

**Comment by uranusjr** [comment]
I don’t have permission to add user on PyPI unfortunately. Both users you mentioned stopped contributing to pipenv for quite a while (one or two years iirc); it’s probably safe to keep them but I wouldn’t object if someone wants to take them off. We should ask them first though.

**Comment by pradyunsg** [comment]
I've finally invited a bunch of the relevant folks to the GitHub organisation. To those that got an invite, please accept it and then remove yourself from https://github.com/pypa/pipenv/settings/access (don't remove pipenv-committers).
