### ISSUE TITLE
Mac air M1 - double parenthesis

### ISSUE THREAD

**Issue by filski95** [pypa/pipenv#4903]
Good morning,

I am using m1 Mac and run across a possible issue with Pipenv recently (like here https://stackoverflow.com/questions/70246087/pipenv-found-itself-venv-is-displayed-with-double-brackets)

I installed Pipenv:
python -m pip install pipenv

Pipenv shell creates an environment but I get two parentheses each time a program is run. Regardless if using IDE or in Terminal.

✔ Successfully created virtual environment! 
Virtualenv location: /Users/xxx.local/share/virtualenvs/pipenv-opVGfhGc
Creating a Pipfile for this project...
Launching subshell in virtual environment...
 . /Users/xxx/.local/share/virtualenvs/pipenv-opVGfhGc/bin/activate          
xxx@Filips-MacBook-Air pipenv %  . /Users/xxx/.local/share/virtualenvs/pipenv-opVGfhGc/bin/activate

does anyone have an idea how to fix this ?

$ pipenv --support

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.11.23'`

Pipenv location: `'/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipenv'`

Python location: `'/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9'`

Python installations found:

  - `3.10.1`: `/usr/local/bin/python3`
  - `3.9.7`: `/Library/Frameworks/Python.framework/Versions/3.9/bin/python3`
  - `3.9.7`: `/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9`
  - `3.9.7`: `/usr/local/bin/python3.9`
  - `3.8.9`: `/usr/bin/python3`
  - `2.7.18`: `/usr/bin/python`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '21.2.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST '
                     '2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101',
 'python_full_version': '3.9.7',
 'python_version': '3.9',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TMPDIR`
  - `__CFBundleIdentifier`
  - `XPC_FLAGS`
  - `TERM`
  - `SSH_AUTH_SOCK`
  - `XPC_SERVICE_NAME`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `SHELL`
  - `HOME`
  - `LOGNAME`
  - `USER`
  - `PATH`
  - `SHLVL`
  - `PWD`
  - `OLDPWD`
  - `__CF_USER_TEXT_ENCODING`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `PIPENV_ACTIVE`
  - `PS1`
  - `LC_CTYPE`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/fafa95/opt/anaconda3/bin:/Users/fafa95/opt/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
  - `SHELL`: `/bin/zsh`
  - `PWD`: `/Users/fafa95`

---------------------------

**Comment by matteius** [comment]
Closing this for now as I think this was fixed in `2021.1.8` that was released yesterday, see the changelog has:

- Remove the extra parentheses around the venv prompt. #4877

Also I see the stackoverflow you link to has a recent new comment from someone regarding something to do with pipx.   Let us know if you think this is still an issue or open question in the latest  `pipenv==2021.1.8` release.  Thanks!
