### ISSUE TITLE
mention TLS verification fix in release notes

### ISSUE THREAD

**Issue by jmhodges** [pypa/pipenv#4916]
It looks like `2022.1.8` was released with a fix to make pipenv [verify the TLS certificates of index hosts](https://github.com/pypa/pipenv/commit/167909839a95ef5aa379fe12d4564b2b829cc175) mentioned in a requirements.txt. Since it could be pretty important fix for folks, it'd be nice for it to be mentioned in the release notes

**Comment by oz123** [comment]
This is mentioned in the form

Fix the index parsing to reject illegal requirements...

**Comment by oz123** [comment]
Also update the release notes in GH: https://github.com/pypa/pipenv/releases/tag/v2022.1.8 with explicit mention of the CVE fix.
