### ISSUE TITLE
$(pipenv --venv)/Scripts/activate returns "No such file or directory" on Windows 10

### ISSUE THREAD

**Issue by johngallino** [pypa/pipenv#4928]
### Issue description

Activating a pipenv environment using `source "$(pipenv --venv)/Scripts/activate"` on Windows 10 returns **/Scripts/activate: No such file or directory** even when the file exists.

### Expected result

The command **$pipenv --venv** returns *C:/Users/johng/.virtualenvs/cashman-flask-project-2vwc8e6G*

Thus `source "$(pipenv --venv)/Scripts/activate"` should activate the above environment. A workaround is to replace the command with `source "C:\\Users\\johng\\.virtualenvs\\cashman-flask-project-2vwc8e6G\\Scripts\\activate"`

### Actual result

Returns: **/Scripts/activate: No such file or directoryualenvs/cashman-flask-project-2vwc8e6G**

Notice the overlapping text

### Steps to replicate

This is in a bash terminal on Windows 10.

I suspect its an issue with the way Windows handles directories. Changing forward slashes to double backslashes does not resolve the issue.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.1.8'`

Pipenv location: `'w:\\anaconda3\\lib\\site-packages\\pipenv'`

Python location: `'w:\\anaconda3\\python.exe'`

Python installations found:

  - `3.8.5`: `W:\Anaconda3\python.exe`
  - `3.8.5`: `W:\Anaconda3\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.5',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.19041',
 'python_full_version': '3.8.5',
 'python_version': '3.8',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ACLOCAL_PATH`
  - `ADSK_3DSMAX_X64_2018`
  - `ADSK_CLM_WPAD_PROXY_CHECK`
  - `ALLUSERSPROFILE`
  - `AMDRMPATH`
  - `APPDATA`
  - `CHROME_CRASHPAD_PIPE_NAME`
  - `COLORTERM`
  - `COMMONPROGRAMFILES`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `CONDA_DEFAULT_ENV`
  - `CONDA_EXE`
  - `CONDA_PREFIX`
  - `CONDA_PROMPT_MODIFIER`
  - `CONDA_PYTHON_EXE`
  - `CONDA_SHLVL`
  - `CONFIG_SITE`
  - `CUDA_PATH`
  - `CUDA_PATH_V10_2`
  - `CHOCOLATEYINSTALL`
  - `CHOCOLATEYLASTPATHUPDATE`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `DISPLAY`
  - `DRIVERDATA`
  - `EXEPATH`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `GDAL_DATA`
  - `GDAL_DRIVER_PATH`
  - `GIT_ASKPASS`
  - `GOOGLE_API_KEY`
  - `GTK_BASEPATH`
  - `HOME`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `HOSTNAME`
  - `INFOPATH`
  - `INTEL_DEV_REDIST`
  - `KEYSHOT7`
  - `LANG`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `MANPATH`
  - `MIC_LD_LIBRARY_PATH`
  - `MINGW_CHOST`
  - `MINGW_PACKAGE_PREFIX`
  - `MINGW_PREFIX`
  - `MOZ_PLUGIN_PATH`
  - `MSYSTEM`
  - `MSYSTEM_CARCH`
  - `MSYSTEM_CHOST`
  - `MSYSTEM_PREFIX`
  - `NUMBER_OF_PROCESSORS`
  - `NVCUDASAMPLES10_2_ROOT`
  - `NVCUDASAMPLES_ROOT`
  - `NVTOOLSEXT_PATH`
  - `OLDPWD`
  - `ORIGINAL_PATH`
  - `ORIGINAL_TEMP`
  - `ORIGINAL_TMP`
  - `ORIGINAL_XDG_CURRENT_DESKTOP`
  - `OS`
  - `OTB_APPLICATION_PATH`
  - `ONEDRIVE`
  - `ONEDRIVECONSUMER`
  - `PATH`
  - `PATHEXT`
  - `PKG_CONFIG_PATH`
  - `PLINK_PROTOCOL`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMFILES`
  - `PS1`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `PVIEW_KEYSHOT7_HOME`
  - `PWD`
  - `PYENV`
  - `PYENV_HOME`
  - `PYTHONPATH`
  - `PROGRAMDATA`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PYCHARM COMMUNITY EDITION WITH ANACONDA PLUGIN`
  - `SESSIONNAME`
  - `SHELL`
  - `SHLVL`
  - `SSH_ASKPASS`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TERM`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `TMP`
  - `TMPDIR`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VIRTUAL_ENV`
  - `VSCODE_GIT_ASKPASS_EXTRA_ARGS`
  - `VSCODE_GIT_ASKPASS_MAIN`
  - `VSCODE_GIT_ASKPASS_NODE`
  - `VSCODE_GIT_IPC_HANDLE`
  - `WINDIR`
  - `_`
  - `_CE_CONDA`
  - `_CE_M`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

PipenvΓÇôspecific environment variables:

DebugΓÇôspecific environment variables:

  - `PATH`: `C:\Users\johng\.virtualenvs\cashman-flask-project-2vwc8e6G\Scripts;W:\Anaconda3;W:\Anaconda3\Library\mingw-w64\bin;W:\Anaconda3\Library\usr\bin;W:\Anaconda3\Library\bin;W:\Anaconda3\Scripts;W:\Anaconda3\bin;W:\Anaconda3\condabin;C:\Users\johng\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\johng\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\PHP\v7.4;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Calibre2;C:\Program Files\Common Files\Autodesk Shared;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\dotnet;C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\ProgramData\chocolatey\bin;C:\ProgramData\ComposerSetup\bin;C:\HashiCorp\Vagrant\bin;C:\Program Files\GDAL;C:\Program Files\Graphviz\bin;C:\Program Files\nodejs;C:\Users\johng\AppData\Roaming\Python\Python38\Scripts;C:\Users\johng\.pyenv\pyenv-win\bin;C:\Users\johng\.pyenv\pyenv-win\shims;W:\Anaconda3\envs\HSIproject\Library\bin;W:\Anaconda3\envs\HSIproject;W:\Hyperspectral\OTB-7.2.0-Win64\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\PHP\v7.4;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Calibre2;C:\Program Files\Common Files\Autodesk Shared;C:\Program Files (x86)\Autodesk\Backburner;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\dotnet;C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\ProgramData\ComposerSetup\bin;C:\HashiCorp\Vagrant\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin;C:\Users\johng\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2020.1\bin;C:\Users\johng\AppData\Local\GitHubDesktop\bin;C:\Users\johng\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\FAHClient;C:\Users\johng\AppData\Roaming\Composer\vendor\bin;C:\Program Files\heroku\bin;W:\msys64\mingw64\bin;C:\Users\johng\AppData\Roaming\npm;C:\users\johng\.pyenv\pyenv-win\versions\3.7.2-win32\Scripts;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl`
  - `SHELL`: `C:\Program Files\Git\usr\bin\bash.exe`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `W:/FlaskProj/cashman-flask-project`
  - `VIRTUAL_ENV`: `C:/Users/johng/.virtualenvs/cashman-flask-project-2vwc8e6G`

---------------------------

Contents of `Pipfile` ('W:\\FlaskProj\\cashman-flask-project\\Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "*"
jsonify = "*"
marshmallow = "*"

[dev-packages]

[requires]
python_version = "3.8"

```

Contents of `Pipfile.lock` ('W:\\FlaskProj\\cashman-flask-project\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "77443b7fe225362f0d258d27ab560e8a4c2de2dc024427a882eb9dbef350fbbc"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "click": {
            "hashes": [
                "sha256:353f466495adaeb40b6b5f592f9f91cb22372351c84caeb068132442a4518ef3",
                "sha256:410e932b050f5eed773c4cda94de75971c89cdb3155a72a0831139a79e5ecb5b"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==8.0.3"
        },
        "colorama": {
            "hashes": [
                "sha256:5941b2b48a20143d2267e95b1c2a7603ce057ee39fd88e7329b0c292aa16869b",
                "sha256:9f47eda37229f68eee03b24b9748937c7dc3868f906e8ba69fbcbdd3bc5dc3e2"
            ],
            "markers": "platform_system == 'Windows'",
            "version": "==0.4.4"
        },
        "flask": {
            "hashes": [
                "sha256:7b2fb8e934ddd50731893bdcdb00fc8c0315916f9fcd50d22c7cc1a95ab634e2",
                "sha256:cb90f62f1d8e4dc4621f52106613488b5ba826b2e1e10a33eac92f723093ab6a"
            ],
            "index": "pypi",
            "version": "==2.0.2"
        },
        "itsdangerous": {
            "hashes": [
                "sha256:5174094b9637652bdb841a3029700391451bd092ba3db90600dea710ba28e97c",
                "sha256:9e724d68fc22902a1435351f84c3fb8623f303fffcc566a4cb952df8c572cff0"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==2.0.1"
        },
        "jinja2": {
            "hashes": [
                "sha256:077ce6014f7b40d03b47d1f1ca4b0fc8328a692bd284016f806ed0eaca390ad8",
                "sha256:611bb273cd68f3b993fabdc4064fc858c5b47a973cb5aa7999ec1ba405c87cd7"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==3.0.3"
        },
        "jsonify": {
            "hashes": [
                "sha256:f340032753577575e9777835809b283fdc9b251867d5d5600389131647f8bfe1"
            ],
            "index": "pypi",
            "version": "==0.5"
        },
        "markupsafe": {
            "hashes": [
                "sha256:01a9b8ea66f1658938f65b93a85ebe8bc016e6769611be228d797c9d998dd298",
                "sha256:023cb26ec21ece8dc3907c0e8320058b2e0cb3c55cf9564da612bc325bed5e64",
                "sha256:0446679737af14f45767963a1a9ef7620189912317d095f2d9ffa183a4d25d2b",
                "sha256:04635854b943835a6ea959e948d19dcd311762c5c0c6e1f0e16ee57022669194",
                "sha256:0717a7390a68be14b8c793ba258e075c6f4ca819f15edfc2a3a027c823718567",
                "sha256:0955295dd5eec6cb6cc2fe1698f4c6d84af2e92de33fbcac4111913cd100a6ff",
                "sha256:0d4b31cc67ab36e3392bbf3862cfbadac3db12bdd8b02a2731f509ed5b829724",
                "sha256:10f82115e21dc0dfec9ab5c0223652f7197feb168c940f3ef61563fc2d6beb74",
                "sha256:168cd0a3642de83558a5153c8bd34f175a9a6e7f6dc6384b9655d2697312a646",
                "sha256:1d609f577dc6e1aa17d746f8bd3c31aa4d258f4070d61b2aa5c4166c1539de35",
                "sha256:1f2ade76b9903f39aa442b4aadd2177decb66525062db244b35d71d0ee8599b6",
                "sha256:20dca64a3ef2d6e4d5d615a3fd418ad3bde77a47ec8a23d984a12b5b4c74491a",
                "sha256:2a7d351cbd8cfeb19ca00de495e224dea7e7d919659c2841bbb7f420ad03e2d6",
                "sha256:2d7d807855b419fc2ed3e631034685db6079889a1f01d5d9dac950f764da3dad",
                "sha256:2ef54abee730b502252bcdf31b10dacb0a416229b72c18b19e24a4509f273d26",
                "sha256:36bc903cbb393720fad60fc28c10de6acf10dc6cc883f3e24ee4012371399a38",
                "sha256:37205cac2a79194e3750b0af2a5720d95f786a55ce7df90c3af697bfa100eaac",
                "sha256:3c112550557578c26af18a1ccc9e090bfe03832ae994343cfdacd287db6a6ae7",
                "sha256:3dd007d54ee88b46be476e293f48c85048603f5f516008bee124ddd891398ed6",
                "sha256:4296f2b1ce8c86a6aea78613c34bb1a672ea0e3de9c6ba08a960efe0b0a09047",
                "sha256:47ab1e7b91c098ab893b828deafa1203de86d0bc6ab587b160f78fe6c4011f75",
                "sha256:49e3ceeabbfb9d66c3aef5af3a60cc43b85c33df25ce03d0031a608b0a8b2e3f",
                "sha256:4dc8f9fb58f7364b63fd9f85013b780ef83c11857ae79f2feda41e270468dd9b",
                "sha256:4efca8f86c54b22348a5467704e3fec767b2db12fc39c6d963168ab1d3fc9135",
                "sha256:53edb4da6925ad13c07b6d26c2a852bd81e364f95301c66e930ab2aef5b5ddd8",
                "sha256:5855f8438a7d1d458206a2466bf82b0f104a3724bf96a1c781ab731e4201731a",
                "sha256:594c67807fb16238b30c44bdf74f36c02cdf22d1c8cda91ef8a0ed8dabf5620a",
                "sha256:5b6d930f030f8ed98e3e6c98ffa0652bdb82601e7a016ec2ab5d7ff23baa78d1",
                "sha256:5bb28c636d87e840583ee3adeb78172efc47c8b26127267f54a9c0ec251d41a9",
                "sha256:60bf42e36abfaf9aff1f50f52644b336d4f0a3fd6d8a60ca0d054ac9f713a864",
                "sha256:611d1ad9a4288cf3e3c16014564df047fe08410e628f89805e475368bd304914",
                "sha256:6300b8454aa6930a24b9618fbb54b5a68135092bc666f7b06901f897fa5c2fee",
                "sha256:63f3268ba69ace99cab4e3e3b5840b03340efed0948ab8f78d2fd87ee5442a4f",
                "sha256:6557b31b5e2c9ddf0de32a691f2312a32f77cd7681d8af66c2692efdbef84c18",
                "sha256:693ce3f9e70a6cf7d2fb9e6c9d8b204b6b39897a2c4a1aa65728d5ac97dcc1d8",
                "sha256:6a7fae0dd14cf60ad5ff42baa2e95727c3d81ded453457771d02b7d2b3f9c0c2",
                "sha256:6c4ca60fa24e85fe25b912b01e62cb969d69a23a5d5867682dd3e80b5b02581d",
                "sha256:6fcf051089389abe060c9cd7caa212c707e58153afa2c649f00346ce6d260f1b",
                "sha256:7d91275b0245b1da4d4cfa07e0faedd5b0812efc15b702576d103293e252af1b",
                "sha256:89c687013cb1cd489a0f0ac24febe8c7a666e6e221b783e53ac50ebf68e45d86",
                "sha256:8d206346619592c6200148b01a2142798c989edcb9c896f9ac9722a99d4e77e6",
                "sha256:905fec760bd2fa1388bb5b489ee8ee5f7291d692638ea5f67982d968366bef9f",
                "sha256:97383d78eb34da7e1fa37dd273c20ad4320929af65d156e35a5e2d89566d9dfb",
                "sha256:984d76483eb32f1bcb536dc27e4ad56bba4baa70be32fa87152832cdd9db0833",
                "sha256:99df47edb6bda1249d3e80fdabb1dab8c08ef3975f69aed437cb69d0a5de1e28",
                "sha256:9f02365d4e99430a12647f09b6cc8bab61a6564363f313126f775eb4f6ef798e",
                "sha256:a30e67a65b53ea0a5e62fe23682cfe22712e01f453b95233b25502f7c61cb415",
                "sha256:ab3ef638ace319fa26553db0624c4699e31a28bb2a835c5faca8f8acf6a5a902",
                "sha256:aca6377c0cb8a8253e493c6b451565ac77e98c2951c45f913e0b52facdcff83f",
                "sha256:add36cb2dbb8b736611303cd3bfcee00afd96471b09cda130da3581cbdc56a6d",
                "sha256:b2f4bf27480f5e5e8ce285a8c8fd176c0b03e93dcc6646477d4630e83440c6a9",
                "sha256:b7f2d075102dc8c794cbde1947378051c4e5180d52d276987b8d28a3bd58c17d",
                "sha256:baa1a4e8f868845af802979fcdbf0bb11f94f1cb7ced4c4b8a351bb60d108145",
                "sha256:be98f628055368795d818ebf93da628541e10b75b41c559fdf36d104c5787066",
                "sha256:bf5d821ffabf0ef3533c39c518f3357b171a1651c1ff6827325e4489b0e46c3c",
                "sha256:c47adbc92fc1bb2b3274c4b3a43ae0e4573d9fbff4f54cd484555edbf030baf1",
                "sha256:cdfba22ea2f0029c9261a4bd07e830a8da012291fbe44dc794e488b6c9bb353a",
                "sha256:d6c7ebd4e944c85e2c3421e612a7057a2f48d478d79e61800d81468a8d842207",
                "sha256:d7f9850398e85aba693bb640262d3611788b1f29a79f0c93c565694658f4071f",
                "sha256:d8446c54dc28c01e5a2dbac5a25f071f6653e6e40f3a8818e8b45d790fe6ef53",
                "sha256:deb993cacb280823246a026e3b2d81c493c53de6acfd5e6bfe31ab3402bb37dd",
                "sha256:e0f138900af21926a02425cf736db95be9f4af72ba1bb21453432a07f6082134",
                "sha256:e9936f0b261d4df76ad22f8fee3ae83b60d7c3e871292cd42f40b81b70afae85",
                "sha256:f0567c4dc99f264f49fe27da5f735f414c4e7e7dd850cfd8e69f0862d7c74ea9",
                "sha256:f5653a225f31e113b152e56f154ccbe59eeb1c7487b39b9d9f9cdb58e6c79dc5",
                "sha256:f826e31d18b516f653fe296d967d700fddad5901ae07c622bb3705955e1faa94",
                "sha256:f8ba0e8349a38d3001fae7eadded3f6606f0da5d748ee53cc1dab1d6527b9509",
                "sha256:f9081981fe268bd86831e5c75f7de206ef275defcb82bc70740ae6dc507aee51",
                "sha256:fa130dd50c57d53368c9d59395cb5526eda596d3ffe36666cd81a44d56e48872"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==2.0.1"
        },
        "marshmallow": {
            "hashes": [
                "sha256:04438610bc6dadbdddb22a4a55bcc7f6f8099e69580b2e67f5a681933a1f4400",
                "sha256:4c05c1684e0e97fe779c62b91878f173b937fe097b356cd82f793464f5bc6138"
            ],
            "index": "pypi",
            "version": "==3.14.1"
        },
        "werkzeug": {
            "hashes": [
                "sha256:63d3dc1cf60e7b7e35e97fa9861f7397283b75d765afcaefd993d6046899de8f",
                "sha256:aa2bb6fc8dee8d6c504c0ac1e7f5f7dc5810a9903e793b6f715a9f015bdadb9a"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==2.0.2"
        }
    },
    "develop": {}
}

```
</details>

**Comment by oz123** [comment]
The syntax `$(...)` is  for UNIX shell.
You should activate the environment with:
```
C:\ pipenv shell
```

(As a side note ... do try WSL for developing software, you will enjoy a capable linux without living the comfort of your windows).

**Comment by matteius** [comment]
@johngallino I second using `pipenv shell` for this purpose or using `pipenv run <cmd>` to get the context of the virtualenv.  Are you using Git bash shell?  I don't see where source is even an option for cmd or power shell.  If so, I think the issue is that the `pipenv --venv` returns the windows style path that git shell doesn't understand.  See:
```
matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/mainegardener (account-registration)
$ pipenv --venv
C:\Users\matte\.virtualenvs\mainegardener-R_3nKGL4

matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/mainegardener (account-registration)
$ source "$(pipenv --venv)/Scripts/activate"
stdout is not a tty
bash: /Scripts/activate: No such file or directory

matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/mainegardener (account-registration)
$ source /C/Users/matte/.virtualenvs/mainegardener-R_3nKGL4
bash: source: /C/Users/matte/.virtualenvs/mainegardener-R_3nKGL4: is a directory

matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/mainegardener (account-registration)
$ source /C/Users/matte/.virtualenvs/mainegardener-R_3nKGL4/Scripts/activate
(mainegardener)
matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/mainegardener (account-registration)
```
