### ISSUE TITLE
compatibility of virtualenvs created with pipenv 11.9.0 and the 2022 branch

### ISSUE THREAD

**Issue by JBPressac** [pypa/pipenv#4931]
Hello,

I tried to upgrade pipenv on Linux from 11.9.0 version to the 2022.1.8 version with pip install --user --upgrade pipenv. However, after the installation, pipenv 2022.1.8 does not recognizes virtualenvs previsously created with the 11.9.0 version as if I run from a folder where resides a virtualenv created with pipenv 11.9.0:

`pipenv run pip list`

pipenv creates a new virtualenv:

```
Creating a virtualenv for this project…
Using /usr/bin/python3.7m (3.7.3) to create virtualenv…
```

Is there a way to upgrade pipenv without recreating the virtualenvs ?

Thanks,

**Comment by frostming** [comment]
Because the name hashing is changed between the two versions. You can try this workaround:

> Place a text file `.venv` under the project root. The content is the path to the existing virtualenv.

**Comment by matteius** [comment]
The workaround should be suitable.
