### ISSUE TITLE
Getting error when trying to activate the enviroment

### ISSUE THREAD

**Issue by kaburelabs** [pypa/pipenv#4932]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

When I try to activate or even create my pipenv shell / pipenv install it doesn't work and raises an error in InvalidHeader

### Expected result

It should activate the environment but it's raising the error

### Actual result

> $ pipenv shellTraceback (most recent call last):
>   File "/home/leonardo/.local/bin/pipenv", line 8, in <module>
>     sys.exit(cli())
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 548, in shell
>     from .import core
>   File "/usr/lib/python3/dist-packages/pipenv/core.py", line 21, in <module>
>     import requests
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/__init__.py", line 67, in <module>
>     from .api import request, get, head, post, patch, put, delete, options
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/api.py", line 13, in <module>
>     from . import sessions
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/sessions.py", line 23, in <module>
>     from .packages.urllib3._collections import RecentlyUsedContainer
>   File "/home/leonardo/.local/lib/python3.10/site-packages/urllib3/_collections.py", line 21, in <module>
>     from .exceptions import InvalidHeader
> ImportError: cannot import name 'InvalidHeader' from 'requests.packages.urllib3.exceptions' (/usr/lib/python3/dist-packages/pipenv/vendor/requests/packages/urllib3/exceptions.py)

### Steps to replicate

I don't know exactly how to replicate it but I think that it started to happen after I did update my python to Python 3.10

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

> $ pipenv --support | xclip
> Traceback (most recent call last):
>   File "/usr/lib/command-not-found", line 28, in <module>
>     from CommandNotFound import CommandNotFound
>   File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
>     from CommandNotFound.db.db import SqliteDatabase
>   File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
>     import apt_pkg
> ModuleNotFoundError: No module named 'apt_pkg'
> Traceback (most recent call last):
>   File "/home/leonardo/.local/bin/pipenv", line 8, in <module>
>     sys.exit(cli())
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 696, in main
>     with self.make_context(prog_name, args, **extra) as ctx:
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 621, in make_context
>     self.parse_args(ctx, args)
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1018, in parse_args
>     rest = Command.parse_args(self, ctx, args)
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 875, in parse_args
>     parser = self.make_parser(ctx)
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 821, in make_parser
>     for param in self.get_params(ctx):
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 774, in get_params
>     help_option = self.get_help_option(ctx)
>   File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 26, in get_help_option
>     from .import core
>   File "/usr/lib/python3/dist-packages/pipenv/core.py", line 21, in <module>
>     import requests
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/__init__.py", line 67, in <module>
>     from .api import request, get, head, post, patch, put, delete, options
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/api.py", line 13, in <module>
>     from . import sessions
>   File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/sessions.py", line 23, in <module>
>     from .packages.urllib3._collections import RecentlyUsedContainer
>   File "/home/leonardo/.local/lib/python3.10/site-packages/urllib3/_collections.py", line 21, in <module>
>     from .exceptions import InvalidHeader
> ImportError: cannot import name 'InvalidHeader' from 'requests.packages.urllib3.exceptions' (/usr/lib/python3/dist-packages/pipenv/vendor/requests/packages/urllib3/exceptions.py)

I'm looking for this answer has more than one week and I can't find any reference about this problem anywhere;

Any help is really appreciated.

**Comment by kaburelabs** [comment]
Hey @oz123, thanks for your answer man. 

You're correct... 

I'm using the following versions:
- Ubuntu 20.04
- Python 3.10
- pipenv 11.9.0

I do not remember exactly how I installed it but probably was through pip install pipenv... The problem started after I set the python 3.10 as the default

**Comment by oz123** [comment]
Is pipenv installed via your package manager? Seems like a very outdated version ...
Plus, it's got a known CVE. I suggest you install the latest version using `get-pipenv.py`.

**Comment by kaburelabs** [comment]
Hey @oz123 Thank you very much, mate... With your questions, I did some new searches on google and it's now working again... 

I have just upgraded my pipenv and virtualenv:
> pip install --user --upgrade pipenv
> pip install --upgrade virtualenv
