### ISSUE TITLE
Userhelp for ERROR: No matching distribution found for imagio / ERROR: Could not find a version that satisfies the requirement imagio (from versions: none)

### ISSUE THREAD

**Issue by PlamAtom** [pypa/pipenv#4939]
Do not use !pip install imagio

Use: 
!git clone https://github.com/imageio/imageio.git  
import imageio

Not working?
Try "pip3 install --upgrade pip" (might break your package manager etc...

No clue tbh... but now it is working

**Comment by oz123** [comment]
Err? What is the issues here? Which OS? Not enough information. Feel free to reopen when you supply the info.
