### ISSUE TITLE
Locking failing with SyntaxError in Python 2 virtualenvs

### ISSUE THREAD

**Issue by OmeGak** [pypa/pipenv#4941]
Locking packages fails with a `SyntaxError` in Python 2 virtualenvs. 

### Expected result

No syntax error.

### Actual result

```console
$ pipenv --python 2.7
Creating a virtualenv for this project...
Pipfile: /Users/ome/Code/tmp/venv-test/Pipfile
Using /usr/bin/python2.7 (2.7.18) to create virtualenv...
⠼ Creating virtual environment...created virtual environment CPython2.7.18.final.0-64 in 223ms
  creator CPython2macOsFramework(dest=/Users/ome/Code/tmp/venv-test/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/ome/Library/Application Support/virtualenv)
    added seed packages: pip==20.3.4, setuptools==44.1.1, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/ome/Code/tmp/venv-test/.venv
Creating a Pipfile for this project...

$ pipenv install click
Installing click...
Adding click to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!

  File "/usr/local/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 25
    path_options = [name, f"{name}.py"]
                                     ^
SyntaxError: invalid syntax
```

### Steps to replicate

```shell
pipenv --python 2.7
pipenv install click
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.1.8'`

Pipenv location: `'/usr/local/Cellar/pipenv/2022.1.8/libexec/lib/python3.10/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2022.1.8/libexec/bin/python3.10'`

Python installations found:

  - `3.9.10`: `/usr/local/opt/python/libexec/bin/python`
  - `3.9.10`: `/usr/local/bin/python3`
  - `3.9.10`: `/usr/local/bin/python3.9`
  - `3.9.5`: `/Users/ome/.pyenv/versions/3.9.5/bin/python3`
  - `3.8.2`: `/usr/bin/python3`
  - `2.7.18`: `/usr/bin/python`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.1',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '21.3.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST '
                     '2022; root:xnu-8019.80.24~20/RELEASE_X86_64',
 'python_full_version': '3.10.1',
 'python_version': '3.10',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `MANPATH`
  - `TERM_PROGRAM`
  - `PIP_REQUIRE_VIRTUALENV`
  - `TERM`
  - `SHELL`
  - `CLICOLOR`
  - `PIPENV_VENV_IN_PROJECT`
  - `TMPDIR`
  - `LIBRARY_PATH`
  - `TERM_PROGRAM_VERSION`
  - `FPATH`
  - `TERM_SESSION_ID`
  - `OS`
  - `LC_ALL`
  - `ZSH`
  - `USER`
  - `LS_COLORS`
  - `LD_LIBRARY_PATH`
  - `COMMAND_MODE`
  - `PROJECTS`
  - `CPATH`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `GIT_AUTHOR_NAME`
  - `GIT_COMMITTER_NAME`
  - `BREWDIR`
  - `WORKON_HOME`
  - `PERIOD`
  - `PIPENV_DEFAULT_PYTHON_VERSION`
  - `_`
  - `GIT_COMMITTER_EMAIL`
  - `__CFBundleIdentifier`
  - `PWD`
  - `EDITOR`
  - `LANG`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `MANPAGER`
  - `PYENV_SHELL`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `GREP_OPTIONS`
  - `QUOTING_STYLE`
  - `LC_TERMINAL_VERSION`
  - `ZSH_CACHE_DIR`
  - `LOGNAME`
  - `LC_CTYPE`
  - `HOMEBREW_CASK_OPTS`
  - `PKG_CONFIG_PATH`
  - `LC_TERMINAL`
  - `GIT_AUTHOR_EMAIL`
  - `COLORTERM`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`
 - `PIPENV_DEFAULT_PYTHON_VERSION`: `3.9`

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2022.1.8/libexec/tools:/usr/local/opt/make/libexec/gnubin:/Users/ome/.pyenv/shims:/usr/local/opt/python/libexec/bin:/Users/ome/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/ome/Code/tmp/venv-test`

---------------------------

Contents of `Pipfile` ('/Users/ome/Code/tmp/venv-test/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
click = "*"

[dev-packages]

[requires]
python_version = "2.7"

```

</details>

**Comment by oz123** [comment]
Python2 is EOL. We can't and won't support it .
Sorry.

**Comment by OmeGak** [comment]
That's very reasonable, no worries. It would still be useful to specify in the docs that Python 2 is no longer supported.

**Comment by oz123** [comment]
It should be kind of obvious right now. I have other priorities, but I might add it.
