### ISSUE TITLE
ERROR:display_layout.cc

### ISSUE THREAD

**Issue by grantwforsythe** [pypa/pipenv#4943]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

I am trying to execute a script with `python -m pipenv run main.py`  but it is throwing a `display_layout.cc` error.

I can't find a solution to this problem anywhere online.

### Expected result

The program to execute without throwing any errors.

### Actual result

Console output after executing the command: `[9464:0203/141858.364:ERROR:display_layout.cc(562)] PlacementList must be sorted by first 8 bits of display_id `

The script's contents:

```python
print('Hello, World!')
```

Pipfile contents:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.10"
```
Locations:
```
Pipenv version: `'2021.11.23'`

Pipenv location: `'C:\\Users\\grantwforsythe\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pipenv'`

Python location: `'C:\\Users\\grantwforsythe\\AppData\\Local\\Programs\\Python\\Python310\\python.exe'`
```

### Steps to replicate

I am unsure of how to replicate the issue since I assume this is a problem with my system.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by oz123** [comment]
Are you using Windows? If so, which terminal are using?

**Comment by grantwforsythe** [comment]
Yes, I am, Windows 10 Pro v10.0.19044 and I currently using the *Powershell Integrated Console* v2021.12.0 in VS Code.

**Comment by oz123** [comment]
Can you please see if this problem occurs on the normal `cmd.exe`? Unfortunately, I don't use Windows and I can't help much here. It seems like there is an issue with the console. Also, I am guessing that your script is invoking some browser? Seems related to chrome?

**Comment by matteius** [comment]
@grantwforsythe I think the issue is the command you are running, it doesn't work on git shell either and tries to open a new window.   Specifically this: `python -m pipenv run main.py`
`pipenv` should be used to run python, not the other way around, so like: `pipenv run python main.py` worked for me:

```
$ pipenv run python main.py
Hello, World!
```

**Comment by grantwforsythe** [comment]
Hi, @matteius

Your comment was a solution to my problem. 

Thanks, @oz123, for your help as well.
