### ISSUE TITLE
Error executing pipenv shell - 'virtualenv.activation.xonsh'

### ISSUE THREAD

**Issue by Tlaloc-Es** [pypa/pipenv#4953]
### Issue description

Error when executing pipenv shell without environment created, over a folder with a pipfile

### Expected result

virtualenv created

### Actual result

```
Loading .env environment variables...
Creating a virtualenv for this project...
Pipfile: /home/user/USB/github/project/Pipfile
Using /usr/bin/python3 (3.9.7) to create virtualenv...
⠋ Creating virtual environment...ModuleNotFoundError: No module named 'virtualenv.activation.xonsh'

✘ Failed creating virtual environment 
[pipenv.exceptions.VirtualenvCreationException]: 
Failed to create virtual environment.
```

### Steps to replicate

install pipenv
launch zsh 
go to folder with pipfile
execute pipenv shell

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.1.8'`

Pipenv location: `'/home/user/.local/lib/python3.9/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.9.7`: `/usr/bin/python3`
  - `3.9.7`: `/usr/bin/python3.9`
  - `3.9.7`: `/bin/python3`
  - `3.9.7`: `/bin/python3.9`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.13.0-28-generic',
 'platform_system': 'Linux',
 'platform_version': '#31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022',
 'python_full_version': '3.9.7',
 'python_version': '3.9',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `LSCOLORS`
  - `SESSION_MANAGER`
  - `QT_ACCESSIBILITY`
  - `COLORTERM`
  - `XDG_CONFIG_DIRS`
  - `SSH_AGENT_LAUNCHER`
  - `LESS`
  - `XDG_MENU_PREFIX`
  - `TERM_PROGRAM_VERSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL`
  - `_P9K_TTY`
  - `LC_ADDRESS`
  - `GNOME_SHELL_SESSION_MODE`
  - `LC_NAME`
  - `SSH_AUTH_SOCK`
  - `P9K_TTY`
  - `XMODIFIERS`
  - `DESKTOP_SESSION`
  - `LC_MONETARY`
  - `BAMF_DESKTOP_FILE_HINT`
  - `GTK_MODULES`
  - `PWD`
  - `GSETTINGS_SCHEMA_DIR`
  - `LOGNAME`
  - `XDG_SESSION_DESKTOP`
  - `XDG_SESSION_TYPE`
  - `GPG_AGENT_INFO`
  - `SYSTEMD_EXEC_PID`
  - `XAUTHORITY`
  - `VSCODE_GIT_ASKPASS_NODE`
  - `GJS_DEBUG_TOPICS`
  - `WINDOWPATH`
  - `HOME`
  - `USERNAME`
  - `IM_CONFIG_PHASE`
  - `LANG`
  - `LC_PAPER`
  - `LS_COLORS`
  - `XDG_CURRENT_DESKTOP`
  - `DISABLE_WAYLAND`
  - `GIT_ASKPASS`
  - `INVOCATION_ID`
  - `MANAGERPID`
  - `CHROME_DESKTOP`
  - `GJS_DEBUG_OUTPUT`
  - `VSCODE_GIT_ASKPASS_EXTRA_ARGS`
  - `LESSCLOSE`
  - `XDG_SESSION_CLASS`
  - `LC_IDENTIFICATION`
  - `TERM`
  - `ZSH`
  - `LESSOPEN`
  - `USER`
  - `VSCODE_GIT_IPC_HANDLE`
  - `DISPLAY`
  - `SHLVL`
  - `PAGER`
  - `LC_TELEPHONE`
  - `QT_IM_MODULE`
  - `LC_MEASUREMENT`
  - `XDG_RUNTIME_DIR`
  - `LC_TIME`
  - `P9K_SSH`
  - `VSCODE_GIT_ASKPASS_MAIN`
  - `JOURNAL_STREAM`
  - `XDG_DATA_DIRS`
  - `GDK_BACKEND`
  - `PATH`
  - `GDMSESSION`
  - `ORIGINAL_XDG_CURRENT_DESKTOP`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `LC_NUMERIC`
  - `OLDPWD`
  - `TERM_PROGRAM`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/user/.fzf/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/user/USB/github/project`

**Comment by kayhayen** [comment]
I have a Debian Bullseye system, and have been plagued by the same issue for a while. I have tried to manually remove all occurrences of xonsh, strangely what helped was to do `apt-get remove python3-virtualenv`. Although the user local install should overload it, apparently that's not successful in my case.

Not sure if it's a bug of Debian, or virtualenv here, or maybe pipenv. Anyway, hope that helps.

**Comment by Tlaloc-Es** [comment]
Thanks, @kayhayen works, perfectly, I don't understand why this error happen suddenly but this works perfectly.

**Comment by ArtemChekunov** [comment]
I believe after the Debian upgrade we have got a conflict between built-in **venv** and module **virtualenv**
