### ISSUE TITLE
docs.pipenv.org (linked to by external sources) is defunct and gives a strong impression that `pipenv` is a dead project

### ISSUE THREAD

**Issue by mmmbogosian** [pypa/pipenv#4954]
This was raised in https://github.com/pypa/pipenv/issues/4805#issuecomment-966394069, but I don't believe another issue was opened to track that. The cert for docs.pipenv.org expired in Aug. of 2021, which is quite awhile ago. The video is also broken on that page. The project link on that page goes to https://github.com/ken/pipenv, which 404s. I arrived at docs.pipenv.org from an external link, and, based on what I saw, assumed (I think reasonably) that pipenv was dead. I eventually found this GH project via an independent search. Had I not done that, I would have drawn the wrong conclusion.

@darkvertex suggested a redirect to https://pipenv.pypa.io/, which sounds reasonable.

**Comment by oz123** [comment]
The owner of docs.pipenv.og is probably Keneth, or not. It doesn't matter. External sources should update their links to pipenv.pypa.org. If you can report this upstream, or at least post here what are these external source I'd be grateful.

**Comment by jdeveloperw** [comment]
> External sources should update their links to pipenv.pypa.org

It appears that the URL is [pipenv.pypa.io](https://pipenv.pypa.io/). Perhaps it may also make sense to do a redirect from docs.pipenv.org to [pipenv.pypa.io](https://pipenv.pypa.io/)?

**Comment by oz123** [comment]
@kennethreitz do you still own docs.pipenv.org?
@frostming can we do something here?

**Comment by kennethreitz** [comment]
I don't own the domains any longer

**Comment by matteius** [comment]
Interesting, do you know who does @kennethreitz ?  The whois information is redacted and just says GoDaddy and California.
