### ISSUE TITLE
Let's Encrypt Certificate out of date since September 1, 2021

### ISSUE THREAD

**Issue by Semnodime** [pypa/pipenv#4956]
Let's Encrypt Certificate out of date since September 1, 2021
https://docs.pipenv.org/basics/

**Comment by matteius** [comment]
Basically this is a duplicate discussion (but from the cert perspective) of:  https://github.com/pypa/pipenv/issues/4954

**Comment by oz123** [comment]
I believe the owner of pipenv.org is @kennethreitz and he has moved on. The only thing we can do is maybe ask the hoster to take down the website, or claim the domain.

**Comment by matteius** [comment]
SSL cert was fixed but docs are way outdated on that domain, see my comment here:  https://github.com/pypa/pipenv/issues/4954#issuecomment-1093679143
