### ISSUE TITLE
Updating an existing lock file on Windows fails

### ISSUE THREAD

**Issue by mardukbp** [pypa/pipenv#4972]
### Issue description

Executing pipenv install on Windows fails with FileNotFoundError while updating an existing Pipfile.lock file.

### Expected result

pipenv install succeeds and outputs "Updated Pipfile.lock!"

### Actual result

```
Locking failed!

Traceback (most recent call last):
    File "C:/Users/mardukb/.local/pipx/venvs/pipenv/lib/site-packages/pipenv/resolver.py", line 766, in <module> main()
    File "C:/Users/mardukb/.local/pipx/venvs/pipenv/lib/site-packages/pipenv/resolver.py", line 762, in main dev=parsed.dev)
    File "C:/Users/mardukb/.local/pipx/venvs/pipenv/lib/site-packages/pipenv/resolver.py", line 743, in _main resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
    File "C:/Users/mardukb/.local/pipx/venvs/pipenv/lib/site-packages/pipenv/resolver.py", line 716, in resolve_packages results = clean_results(results, resolver, project, dev)
    File "C:/Users/mardukb/.local/pipx/venvs/pipenv/lib/site-packages/pipenv/resolver.py", line 593, in clean_results reverse_deps = project.environment.reverse_dependencies()
    File "c:\users\mardukb\.local\pipx\venvs\pipenv\lib\site-packages\pipenv\project.py", line 350, in environment self._environment = self.get_environment(allow_global=allow_global)
    File "c:\users\mardukb\.local\pipx\venvs\pipenv\lib\site-packages\pipenv\project.py", line 336, in get_environment pipfile=self.parsed_pipfile, project=self
    File "c:\users\mardukb\.local\pipx\venvs\pipenv\lib\site-packages\pipenv\environment.py", line 72, in __init__ self._base_paths = self.get_paths()
    File "c:\users\mardukb\.local\pipx\venvs\pipenv\lib\site-packages\pipenv\environment.py", line 360, in get_paths c = subprocess_run(command)
    File "c:\users\mardukb\.local\pipx\venvs\pipenv\lib\site-packages\pipenv\utils.py", line 2328, in subprocess_run encoding=encoding, **other_kwargs
    File "c:\users\mardukb\appdata\local\programs\python\python37\lib\subprocess.py", line 488, in run with Popen(*popenargs, **kwargs) as process:
    File "c:\users\mardukb\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in __init__ restore_signals, start_new_session)
    File "c:\users\mardukb\appdata\local\programs\python\python37\lib\subprocess.py", line 1207, in _execute_child startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
```

### Steps to replicate

1. Open a command line
2. mkdir test-project
3. cd test-project
4. pipenv install --dev pydantic==1.9.0
5. pipenv install JPype1==1.3.0

### Solution

I investigated the problem and [solved it](https://github.com/mardukbp/pipenv/commit/fdbee328fe954424e6dc13904e655e8faa8854e5).

This problem exists since v2021.11.5 when the call to vistir.misc.run was replaced by a call to subprocess_run in the function get_paths in environment.py. On Windows vistir.misc.run executes a process with shell=True, but the new function does not.

A recent [commit](https://github.com/pypa/pipenv/commit/d3df2e2abb16e2b1d1a24acdfc22e1b873e77ec7) fixed a function that failed due to this. Instead of submitting a PR to fix the function get_paths, I suggest that the function subprocess_run is fixed and corresponding tests are written, so that this problem does not arise again after a refactoring.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.1.8'`

Pipenv location: `'C:\\Users\\mardukb\\.local\\pipx\\venvs\\pipenv\\lib\\site-packages\\pipenv'`

Python location: `'C:\\Users\\mardukb\\.local\\pipx\\venvs\\pipenv\\Scripts\\python.exe'`

Python installations found:

  - `3.10.1`: `C:\Users\mardukb\AppData\Local\Programs\Python\Python310\python.exe`
  - `3.7.9`: `C:\Users\mardukb\AppData\Local\Programs\Python\Python37\python.exe`
  - `3.8.10`: `C:\Users\mardukb\AppData\Local\Programs\Miniconda3\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.1',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.19044',
 'python_full_version': '3.10.1',
 'python_version': '3.10',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `CHOCOLATEYLASTPATHUPDATE`
  - `CHOCOLATEYTOOLSLOCATION`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DRIVERDATA`
  - `EMPIRUMSERVER`
  - `HOME`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `JAVA_HOME`
  - `JAVA_HOME_8`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `MINGW_PREFIX`
  - `MOZ_ALLOW_DOWNGRADE`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `POWERSHELL_DISTRIBUTION_CHANNEL`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `QFTEST_HOME`
  - `RUBYOPT`
  - `RUSTFLAGS`
  - `SBT_HOME`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `WINDIR`
  - `ZES_ENABLE_SYSMAN`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv├ö├ç├┤specific environment variables:

Debug├ö├ç├┤specific environment variables:

  - `PATH`: `C:\Users\mardukb\AppData\Local\Programs\PowerShell\7;C:\ProgramData\QFS\QF-Test\qftestpath;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\Users\mardukb\AppData\Local\Programs\Oracle\oracle19c\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Windows\SysWOW64\Empirum;C:\Program Files\OpenVPN\bin;C:\Program Files\Sierra Wireless Inc\Skylight\;C:\Users\mardukb\AppData\Local\Programs\TortoiseHg\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Users\mardukb\AppData\Local\Programs\Vagrant\bin;C:\Users\mardukb\AppData\Local\Programs\Git\cmd;C:\Users\mardukb\AppData\Local\Programs\Git\usr\bin;C:\Users\mardukb\AppData\Local\Programs\Python\Python37\;C:\Users\mardukb\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\mardukb\AppData\Local\Programs\Python\Python310\;C:\Users\mardukb\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\mardukb\AppData\Local\Programs\Miniconda3;C:\Users\mardukb\AppData\Local\Programs\Miniconda3\Scripts;C:\Users\mardukb\.poetry\bin;C:\Users\mardukb\AppData\Local\Programs\Miniconda3\Library\mingw-w64\bin;C:\Users\mardukb\AppData\Local\Programs\Miniconda3\Library\usr\bin;C:\Users\mardukb\AppData\Local\Programs\Miniconda3\Library\bin;C:\Users\mardukb\AppData\Local\Programs\Microsoft Keyboard Layout Creator 1.4\bin\i386;C:\Users\mardukb\.cargo\bin;C:\Users\mardukb\AppData\Local\Programs\Python\Launcher\;C:\Users\mardukb\bin;C:\Users\mardukb\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\mardukb\AppData\Local\Programs\fd;C:\Users\mardukb\AppData\Local\Programs\ripgrep;C:\Users\mardukb\AppData\Local\Programs\micro;C:\Users\mardukb\AppData\Local\Programs\TDM-GCC-64\bin;C:\Users\mardukb\AppData\Roaming\npm;C:\Users\mardukb\AppData\Local\rasjani\WebDriverManager\bin;C:\Users\mardukb\AppData\Local\Programs\PowerShell\7\;C:\Users\mardukb\AppData\Local\Programs\Git\cmd;C:\Users\mardukb\AppData\Local\Programs\Git\usr\bin;C:\Users\mardukb\AppData\Local\Programs\nodejs\;C:\Users\mardukb\AppData\Local\Programs\sbt\bin;C:\Users\mardukb\AppData\Local\Programs\maven\bin;C:\Users\mardukb\AppData\Local\Programs\Docker;C:\Users\mardukb\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Azure Data Studio\bin;C:\Program Files\Eclipse Adoptium\jre-8.0.312.7-hotspot\bin;C:\Program Files\Eclipse Adoptium\jdk-8.0.312.7-hotspot\bin;C:\Users\mardukb\AppData\Local\Programs\jdk8u312-full\bin;C:\Users\mardukb\AppData\Local\Programs\tldr;C:\Users\mardukb\AppData\Local\Programs\QF-Test\qftest-5.4.1\bin;C:\Users\mardukb\.poetry\bin;c:\users\mardukb\.local\bin;;.`

---------------------------

Contents of `Pipfile` ('C:\\Users\\mardukb\\tb2itorx\\Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
jpype1 = "==1.3.0"

[dev-packages]
pydantic = "==1.9.0"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('C:\\Users\\mardukb\\tb2itorx\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "128eea60aadaf79b40a253b5c1d1101f027a4b71ed3ea436d6d0d9b7eb8e907d"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {
        "pydantic": {
            "hashes": [
                "sha256:085ca1de245782e9b46cefcf99deecc67d418737a1fd3f6a4f511344b613a5b3",
                "sha256:086254884d10d3ba16da0588604ffdc5aab3f7f09557b998373e885c690dd398",
                "sha256:0b6037175234850ffd094ca77bf60fb54b08b5b22bc85865331dd3bda7a02fa1",
                "sha256:0fe476769acaa7fcddd17cadd172b156b53546ec3614a4d880e5d29ea5fbce65",
                "sha256:1d5278bd9f0eee04a44c712982343103bba63507480bfd2fc2790fa70cd64cf4",
                "sha256:2cc6a4cb8a118ffec2ca5fcb47afbacb4f16d0ab8b7350ddea5e8ef7bcc53a16",
                "sha256:2ee7e3209db1e468341ef41fe263eb655f67f5c5a76c924044314e139a1103a2",
                "sha256:3011b975c973819883842c5ab925a4e4298dffccf7782c55ec3580ed17dc464c",
                "sha256:3c3b035103bd4e2e4a28da9da7ef2fa47b00ee4a9cf4f1a735214c1bcd05e0f6",
                "sha256:4c68c3bc88dbda2a6805e9a142ce84782d3930f8fdd9655430d8576315ad97ce",
                "sha256:574936363cd4b9eed8acdd6b80d0143162f2eb654d96cb3a8ee91d3e64bf4cf9",
                "sha256:5a79330f8571faf71bf93667d3ee054609816f10a259a109a0738dac983b23c3",
                "sha256:5e48ef4a8b8c066c4a31409d91d7ca372a774d0212da2787c0d32f8045b1e034",
                "sha256:6c5b77947b9e85a54848343928b597b4f74fc364b70926b3c4441ff52620640c",
                "sha256:742645059757a56ecd886faf4ed2441b9c0cd406079c2b4bee51bcc3fbcd510a",
                "sha256:7bdfdadb5994b44bd5579cfa7c9b0e1b0e540c952d56f627eb227851cda9db77",
                "sha256:815ddebb2792efd4bba5488bc8fde09c29e8ca3227d27cf1c6990fc830fd292b",
                "sha256:8b5ac0f1c83d31b324e57a273da59197c83d1bb18171e512908fe5dc7278a1d6",
                "sha256:96f240bce182ca7fe045c76bcebfa0b0534a1bf402ed05914a6f1dadff91877f",
                "sha256:a733965f1a2b4090a5238d40d983dcd78f3ecea221c7af1497b845a9709c1721",
                "sha256:ab624700dc145aa809e6f3ec93fb8e7d0f99d9023b713f6a953637429b437d37",
                "sha256:b2571db88c636d862b35090ccf92bf24004393f85c8870a37f42d9f23d13e032",
                "sha256:bbbc94d0c94dd80b3340fc4f04fd4d701f4b038ebad72c39693c794fd3bc2d9d",
                "sha256:c0727bda6e38144d464daec31dff936a82917f431d9c39c39c60a26567eae3ed",
                "sha256:c556695b699f648c58373b542534308922c46a1cda06ea47bc9ca45ef5b39ae6",
                "sha256:c86229333cabaaa8c51cf971496f10318c4734cf7b641f08af0a6fbf17ca3054",
                "sha256:c8d7da6f1c1049eefb718d43d99ad73100c958a5367d30b9321b092771e96c25",
                "sha256:c8e9dcf1ac499679aceedac7e7ca6d8641f0193c591a2d090282aaf8e9445a46",
                "sha256:cb23bcc093697cdea2708baae4f9ba0e972960a835af22560f6ae4e7e47d33f5",
                "sha256:d1e4c28f30e767fd07f2ddc6f74f41f034d1dd6bc526cd59e63a82fe8bb9ef4c",
                "sha256:d9c9bdb3af48e242838f9f6e6127de9be7063aad17b32215ccc36a09c5cf1070",
                "sha256:dee5ef83a76ac31ab0c78c10bd7d5437bfdb6358c95b91f1ba7ff7b76f9996a1",
                "sha256:e0896200b6a40197405af18828da49f067c2fa1f821491bc8f5bde241ef3f7d7",
                "sha256:f5a64b64ddf4c99fe201ac2724daada8595ada0d102ab96d019c1555c2d6441d",
                "sha256:f947352c3434e8b937e3aa8f96f47bdfe6d92779e44bb3f41e4c213ba6a32145"
            ],
            "index": "pypi",
            "version": "==1.9.0"
        },
        "typing-extensions": {
            "hashes": [
                "sha256:1a9462dcc3347a79b1f1c0271fbe79e844580bb598bafa1ed208b94da3cdcd42",
                "sha256:21c85e0fe4b9a155d0799430b0ad741cdce7e359660ccbd8b530613e8df88ce2"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==4.1.1"
        }
    }
}

```
</details>

**Comment by matteius** [comment]
@mardukbp Can you try the master branch of pipenv?  I feel like this issue was recently solved for with these latest Windows fixes:
https://github.com/pypa/pipenv/pull/4949/files
https://github.com/pypa/pipenv/pull/4955/files

**Comment by matteius** [comment]
@mardukbp Check with `pipenv==2022.3.24` and we can re-open if you find there is still an issue.
