### ISSUE TITLE
Upgrade vendor to PythonFinder 1.2.10

### ISSUE THREAD

**Issue by alago1** [pypa/pipenv#4976]
### Issue description

Pipenv can currently have issues running on WSL2 (#4880).
At the time, the issue was closed once it was found to be an issue with the upstream package PythonFinder.
Recently, PythonFinder fixed the problem on version 1.2.10.
Upgrading to 1.2.10 should therefore address pipenv's problems on WSL2.

**Comment by matteius** [comment]
I can take a stab at this soon, since I've gotten some vendoring experience under my belt in the last few weeks.

**Comment by oz123** [comment]
Fixed.
