### ISSUE TITLE
ModuleNotFoundError: No module named 'poetry'

### ISSUE THREAD

**Issue by AIGeneratedUsername** [pypa/pipenv#4985]
### Steps to replicate
```bash
$ curl -sSL https://install.python-poetry.org | python3 -
Retrieving Poetry metadata

The latest version (1.1.13) is already installed.

$ poetry --version
Traceback (most recent call last):
  File "/home/sam/.poetry/bin/poetry", line 17, in <module>
    from poetry.console import main
ModuleNotFoundError: No module named 'poetry'
```
### Versions

Lubuntu 20.04

**Comment by AIGeneratedUsername** [comment]
It turned out to be very easy. After spending a whole day on investigating the error, I finally installed Poetry. If someone want to install Poetry before the end of the working day, I highly recommend to start at the early morning.

`ModuleNotFoundError: No module named 'poetry'` solution:

1. Remove Poetry
2. Remove Poetry from PATH
3. Reboot your PC (THIS IS THE MOST IMPORTANT STEP!)
4. Install Poetry

**Comment by matteius** [comment]
@AIGeneratedUsername Just wondering ... did your use case have any relation to pipenv?
