### ISSUE TITLE
Add pytest coverage report and Review and remove more unused code

### ISSUE THREAD

**Issue by matteius** [pypa/pipenv#4996]
Place holder ticket to continue work improving the readability of the code base. 

### Issue description

Noticed that `PIPENV_MAX_ROUNDS` is unused and the comments mention pip-tools which appears to be a prior requirement that we have moved away from. 

Going to start reviewing pip-tools comments in the code and go from there.

**Comment by Afsan751** [comment]
#4906 #4775 #4990
