### ISSUE TITLE
Pipenv activate command - activate the virtual environment in the current shell

### ISSUE THREAD

**Issue by ericPrince** [pypa/pipenv#5007]
> Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.
> 
> Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues and the [PEEP list](https://github.com/pypa/pipenv/blob/master/peeps/) before posting! We may close your issue if it is very similar to one of them. Please be considerate and follow the PEEP process, or be on your way.
>
> Make sure to mention your debugging experience if the documented solution failed.

### Is your feature request related to a problem? Please describe.

I'd like to be able to use a pipenv command to activate the virtual environment for a project in the current shell. `pipenv shell` spawns a new shell (and often doesn't work in a containerized environment) and the alternative is to use shell commands, which is fine but less straightforward.

### Describe the solution you'd like

A new command `pipenv activate` that does the equivalent of calling `source activate` for the virtual environment. Then a user can call the exsting virtualenv `deactivate` when they want to deactivate the environment.

### Describe alternatives you've considered

My current workaround on bash is `source $(dirname $(pipenv run which python))/activate`. It's fine but not intuitive for someone not experienced with bash. It also breaks due to things like #5003 modifying stdout.

### Additional context

Add any other context or screenshots about the feature request here. It may be a good idea to mention that platform and Python version you are on.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

(removed because too long for max issue body)

**Comment by ericPrince** [comment]
@oz123 understood, calling shell-specific commands from the existing shell process just might not be possible ([this](https://stackoverflow.com/questions/7040592/calling-the-source-command-from-subprocess-popen)). I could be interested in having it as a bash-completion made available by pipenv. Also ok if the answer is just, you can't source a file in python, keep using `source $(dirname $(pipenv run which python))/activate`.

**Comment by smac89** [comment]
What about `pipenv run $SHELL`?

**Comment by oz123** [comment]
The run subcommand already creatures a subshell.
Only venue's activate avoids it.

**Comment by frostming** [comment]
It is very easy to create an alias or shell function that does the following:

```bash
source $(pipenv --venv)/bin/activate
```

we are not going to implement it in pipenv.

**Comment by matteius** [comment]
> source $(pipenv --venv)/bin/activate

That would be a nice tid-bit to add to the docs at some point.

**Comment by ericPrince** [comment]
Yeah, fine by me. For posterity, that command doesn't work in windows since virtual environment exes are placed in the "Scripts" folder. That's why I've been using `source $(dirname $(pipenv run which python))/activate`, so I can copy/paste the same thing wherever I am.
