### ISSUE TITLE
Need a new option that installs through lock file but does not locking.

### ISSUE THREAD

**Issue by xncbf** [pypa/pipenv#5020]
Thank you for your hard work in making a great product.

I use pipenv in the local environment, but also in the pipeline environment. (CI)

In a pipeline environment, installation through a lock file is required, but after that, it takes a few more seconds to a minute to automatically lock.

I want to save this time.

If you agree with me, I will submit a PR.

Thanks.

**Comment by frostming** [comment]
Locking is not required if `Pipfile.lock` already exists and matches the content of `Pipfile`.

**Comment by matteius** [comment]
@xncbf  Its as frostming said; Have you tried `pipenv install --deploy` or `pipenv sync`?

**Comment by xncbf** [comment]
`pipenv sync` is perfect option what i wanted.
