### ISSUE TITLE
Turn off color via PY_COLORS=0

### ISSUE THREAD

**Issue by starblue** [pypa/pipenv#5057]
Please support a more standard way to turn off colors. It is tedious to turn off color for every tool separately, especially since with PY_COLORS there exists a general way for the Python ecosystem.

Even better would be to respect NO_COLOR=1, which IMHO is the closest thing to a general standard. General support for this would avoid playing whack-a-mole with every new tool that comes along.

Also, there are many valid reasons not to want colors on the command line, so calling the environment variable PIPENV_COLORBLIND is in rather bad taste.

**Comment by oz123** [comment]
I think this is a very good issue to work on. I also added this feature in the past to pip :-).
https://github.com/pypa/pip/pull/4739

This will take quite some time to implement this here. Been talking with @ma about removing all the usage of `crayons`  and only using `click.echo`. If `click.echo` has a global way to disable color that would be easy!

**Comment by oz123** [comment]
In PIPENV the place for this would be:
https://github.com/pypa/pipenv/blob/891486e18040e4fb3ff0eaedd85349a78e214915/pipenv/environments.py#L101

**Comment by matteius** [comment]
https://github.com/tartley/colorama/issues/268

**Comment by matteius** [comment]
I agree with a comment someone left somewhere else recently that the name `PIPENV_COLORBLIND` is in bad taste.   It looks like colorama will maybe one day soon support a `NO_COLOR` environment variable ... that is what click uses, but only for Windows I think.

**Comment by oz123** [comment]
There is another way to disable colors in pipenv which we inherit from `vistir.termcolors`:

DISABLE_COLORS = os.getenv("CI", False) or os.getenv(
    "ANSI_COLORS_DISABLED", os.getenv("VISTIR_DISABLE_COLORS", False)
)
