### ISSUE TITLE
Add concurrency limits, to reduce the GitHub Actions usage

### ISSUE THREAD

**Issue by pradyunsg** [pypa/pipenv#5073]
Currently, pipenv's test suite is consuming a substantial portion of the GitHub Actions workers available to the PyPA as a whole, due to multiple concurrent runs on the same PR / multiple PR merges.

Adding a block like the following, to the top level of the CI pipeline would help alleviate some of this load.

```
concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
```

In a similar vein, it could be beneficial to explore speeding up the test suite/CI runs if that is feasible, through the use of caches and RAM disks. :)

**Comment by oz123** [comment]
The test suite is a real PITA. Hopefully, we can improve it.
