### ISSUE TITLE
"pipenv" fails with AttributeError after upgrading from ubuntu 20.04 to 22.04?

### ISSUE THREAD

**Issue by amod-amatya** [pypa/pipenv#5088]
I recently upgraded my distro version from ubuntu 20.04 to ubuntu 22.04 and now pipenv command does not work. Any solutions to fix this?

```
 > pipenv --help

Traceback (most recent call last):
  File "/usr/bin/pipenv", line 33, in <module>
    sys.exit(load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')())
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1018, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 875, in parse_args
    parser = self.make_parser(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 821, in make_parser
    for param in self.get_params(ctx):
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 774, in get_params
    help_option = self.get_help_option(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 26, in get_help_option
    from .import core
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 21, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/__init__.py", line 65, in <module>
    from . import utils
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/utils.py", line 27, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/usr/lib/python3/dist-packages/pipenv/vendor/requests/cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Comment by matteius** [comment]
@amod-amatya I can only suspect that you are perhaps on a really old version of pipenv, as core.py does not import requests at present time.

**Comment by amod-amatya** [comment]
I am running version 11.9.0-1.1

**Comment by matteius** [comment]
@amod-amatya that is from Released: Mar 21, 2018 and hasn't been supported for some time.  It looks like you may be trying to run with python 3.10.   Either way have a run with a newer version, the newest one being:  `pipenv==2022.4.21`

**Comment by berlotto** [comment]
For me  too using Python 3.10 on PopOS 22.04.

There is a break change in Python 3.10: Remove deprecated aliases to [Collections Abstract Base Classes](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes) from the [collections](https://docs.python.org/3/library/collections.html#module-collections) module. (Contributed by Victor Stinner in [bpo-37324](https://bugs.python.org/issue?@action=redirect&bpo=37324).)

https://docs.python.org/3/whatsnew/3.10.html


```
import collections 
if sys.version_info.major == 3 and sys.version_info.minor >= 10

    from collections.abc import MutableMapping
else 
    from collections import MutableMapping
```

**Comment by amod-amatya** [comment]
@matteius yup I had pipenv installed from apt package manager, removed it and installed the latest one from pip, it works.
`> pip install pipenv`

**Comment by dmtucker** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1012124

**Comment by yosefor** [comment]
> 

it's better to use `sudo pip install pipenv`

**Comment by dmtucker** [comment]
Don't `sudo pip`. It's a security risk, and it can break your system.

https://askubuntu.com/questions/802544/is-sudo-pip-install-still-a-broken-practice

**Comment by Flimm** [comment]
Has someone reported this to Ubuntu through Launchpad?

**Comment by mikehearn** [comment]
Bug report is here:

https://bugs.launchpad.net/ubuntu/+source/pipenv/+bug/1998280

Looks like it's fixed but only in Lunar! Hopefully they'll backport the fix at some point but doesn't seem likely given that the bug is unassigned.

**Comment by rundekugel** [comment]
"Do not install pipenv from apt, it's way too old. Install from pypi." 
source: https://github.com/pypa/pipenv/issues/5469

This solve it for me:

    sudo apt remove pipenv
    pip install pipenv

Unfortunately `pipenv`didn't worked out of the box in this console. I had to use:
    
    python -m pipenv

Or simply start a new terminal session.
