### ISSUE TITLE
pipenv commands yields following error: `.../.local/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release   warnings.warn(`

### ISSUE THREAD

**Issue by DanielPerezJensen** [pypa/pipenv#5098]
### Issue description

I recently updated pyenv and upgraded pipenv to the latest version using the following command:
`pyenv update && pip3 install --upgrade --upgrade-strategy eager --user pipenv`
After this running any pipenv command will yield the error described in the title.

### Expected result

No such error. 

### Actual result

The error in the title.
However the virtual environment does seem to be properly loaded, with packages working and all scripts working. Installing packages seems to also work with no problem, however the error does come up every time which does not seem to be intended behaviour.

### Steps to replicate

1. Update pipenv to latest version:
`pyenv update && pip3 install --upgrade --upgrade-strategy eager --user pipenv`

2. Run
Run pipenv shell (or any other command)

3. See error

### Own steps to fix
I tried to fix it by downgrading my pipenv version back to the previous version, namely pipenv-2022.3.28 using `pip3 --user install pipenv==2022.3.28`. However, this did not fix the issue. Then I tried to downgrade setuptools down to 61.2.0 using `pip3 --user install setuptools==61.2.0`, this did also not fix the issue. I believe perhaps it might have to do with a mistake in pip installation, so I tried to reinstall that using `sudo apt install --reinstall python3-pip`, this did not fix the issue.

I don't really know what else to try. Any help is appreciated.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

I do not get any output besides the warning

.local/lib/python3.8/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(

**Comment by NeroVanbiervliet** [comment]
Apparently it is due a bug in setuptools, see [discussion on stackoverflow](https://askubuntu.com/questions/1406952/what-is-the-meaning-of-this-pkgresourcesdeprecationwarning-warning-from-pipenv)

**Comment by matteius** [comment]
@DanielPerezJensen This is not a pipenv bug.

**Comment by matteius** [comment]
This was fixed in `2022.9.20`
