### ISSUE TITLE
Vendored importlib_resources uses obsolete typing.io import

### ISSUE THREAD

**Issue by srittau** [pypa/pipenv#5106]
### Issue description

The vendored version of importlib_resources uses the `typing.io` namespace, which is deprecated since Python 3.8 and will be removed in Python 3.12 (cf. python/cpython#92871). This was seemingly fixed in importlib_resources v5.2.1 (according to the changelog).

**Comment by oz123** [comment]
I think we can completely drop this vendored library. I don't see it used any where.
