### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'build_location'

### ISSUE THREAD

**Issue by Paul4936** [pypa/pipenv#5108]
Hello everyone.

### Issue description

Before all was fine.
But yesterday i get troubles with celery and pip(both get me to same error right on start) inside virtual environment(Segfault).
There were late hour, so i updated my whole system and go to sleep.

Today after update i found myself unable to create any VENV by pipenv.
I tried to fix it, no result. 
In brief it were:
Reboot(always a good option). No result.
Removing python caches. No result.
Removing whole python dirs and "repopulate" them by installing python packages again via packet manager. No result again.
Also i tried to create another user(in case if thee is something with current one). No result.
And just to try something else - tried pipenv as superuser, and delete all files since no result again.
Removing pipenv with package manager and installing(system wide) with pip - bring no results too.

Of course i tried to rollback my updates(few dates were checked, 2 days ago, five, 2 weeks, 2 months) - no result.
It's looks like something missing, but i cant realize what exactly.
Now i get:
<details><summary>$ pipenv install --dev</summary>
`
Pipfile.lock (f85c49) out of date, updating to (51d269)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed! 

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 857, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 852, in main
    dev=parsed.dev,
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 823, in _main
    pre, clear, verbose, system, write, requirements_dir, packages, dev
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 778, in resolve_packages
    requirements_dir=requirements_dir,
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 759, in resolve
    req_dir=requirements_dir,
  File "/usr/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 1076, in resolve_deps
    req_dir=req_dir,
  File "/usr/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 860, in actually_resolve_deps
    deps, project, index_lookup, markers_lookup, sources, req_dir, clear, pre
  File "/usr/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 407, in create
    clear=clear,
  File "/usr/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 177, in get_metadata
    project=project,
  File "/usr/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 231, in parse_line
    req = Requirement.from_line(line)
  File "/usr/lib/python3.10/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2672, in from_line
    if isinstance(line, pip_shims.shims.InstallRequirement):
  File "/usr/lib/python3.10/site-packages/pipenv/vendor/pip_shims/shims.py", line 61, in __getattr__
    return locations[args[0]].shim()
  File "/usr/lib/python3.10/site-packages/pipenv/vendor/pip_shims/models.py", line 737, in shim
    result = self.traverse(top_path)
  File "/usr/lib/python3.10/site-packages/pipenv/vendor/pip_shims/models.py", line 729, in traverse
    result = shim.shim()
  File "/usr/lib/python3.10/site-packages/pipenv/vendor/pip_shims/models.py", line 577, in shim
    return self.shim_class(imported, self.name_to_import)
  File "/usr/lib/python3.10/site-packages/pipenv/vendor/pip_shims/models.py", line 519, in shim_class
    imported, result = self._shim_parent(imported, attribute_name)
  File "/usr/lib/python3.10/site-packages/pipenv/vendor/pip_shims/models.py", line 503, in _shim_parent
    result = self._shim_base(imported, attribute_name)
  File "/usr/lib/python3.10/site-packages/pipenv/vendor/pip_shims/models.py", line 492, in _shim_base
    return self._apply_aliases(imported, result)
  File "/usr/lib/python3.10/site-packages/pipenv/vendor/pip_shims/models.py", line 497, in _apply_aliases
    target = apply_alias(imported, target, *alias_list)
  File "/usr/lib/python3.10/site-packages/pipenv/vendor/pip_shims/utils.py", line 326, in apply_alias
    setattr(target, alias, alias_value)
AttributeError: 'NoneType' object has no attribute 'build_location'
`
</details>
In brief:

`AttributeError: 'NoneType' object has no attribute 'build_location'`

Looks like it cant properly create python environment, even though i can get inpo pipenv shell and run python 3.6 inside.

### Expected result

Working virtual environment created according to pipfile.

### Steps to replicate

In my case: 
just select any directory with pipfile(not empty) inside and type 
```pipenv install```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.5.2'`

Pipenv location: `'/usr/lib/python3.10/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.10.4`: `/usr/bin/python3`
  - `3.10.4`: `/usr/bin/python`
  - `3.10.4`: `/bin/python3`
  - `3.10.4`: `/bin/python`
  - `3.6.15`: `/home/paul/.pyenv/versions/3.6.15/bin/python`
  - `2.7.18`: `/usr/bin/python2.7`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/bin/python2.7`
  - `2.7.18`: `/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.15.41-1-lts',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Wed, 18 May 2022 13:37:06 +0000',
 'python_full_version': '3.10.4',
 'python_version': '3.10',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `SESSION_MANAGER`
  - `WINDOWID`
  - `COLORTERM`
  - `CSF_MDTVTexturesDirectory`
  - `XDG_SESSION_PATH`
  - `HISTCONTROL`
  - `CONDA_EXE`
  - `_CE_M`
  - `CSF_DrawPluginDefaults`
  - `CSF_LANGUAGE`
  - `DOTNET_ROOT`
  - `SSH_AUTH_SOCK`
  - `CSF_MIGRATION_TYPES`
  - `GRADLE_HOME`
  - `DESKTOP_SESSION`
  - `CSF_OCCTResourcePath`
  - `CSF_STEPDefaults`
  - `CLOUDSDK_PYTHON_ARGS`
  - `GTK_MODULES`
  - `ANDROID_NDK`
  - `XDG_SEAT`
  - `MATE_DESKTOP_SESSION_ID`
  - `PWD`
  - `XDG_SESSION_DESKTOP`
  - `LOGNAME`
  - `XDG_SESSION_TYPE`
  - `DRAWHOME`
  - `XAUTHORITY`
  - `CSF_StandardLiteDefaults`
  - `RAWWAVE_PATH`
  - `XDG_GREETER_DATA_DIR`
  - `MOTD_SHOWN`
  - `WINEARCH`
  - `HOME`
  - `LANG`
  - `WINEPREFIX`
  - `XDG_CURRENT_DESKTOP`
  - `VTE_VERSION`
  - `CLOUDSDK_ROOT_DIR`
  - `XDG_SEAT_PATH`
  - `ANDROID_NDK_HOME`
  - `CSF_ShadersDirectory`
  - `DOTNET_BUNDLE_EXTRACT_BASE_DIR`
  - `CSF_EXCEPTION_PROMPT`
  - `CSF_XmlOcafResource`
  - `CLOUDSDK_PYTHON`
  - `CSF_SHMessage`
  - `OPCODE6DIR`
  - `XDG_SESSION_CLASS`
  - `ANDROID_HOME`
  - `TERM`
  - `_CE_CONDA`
  - `GTK_OVERLAY_SCROLLING`
  - `npm_config_prefix`
  - `GOOGLE_CLOUD_SDK_HOME`
  - `USER`
  - `CUDA_PATH`
  - `CONDA_SHLVL`
  - `CSF_StandardDefaults`
  - `CSF_IGESDefaults`
  - `CSSTRNGS`
  - `DISPLAY`
  - `CSF_XCAFDefaults`
  - `SHLVL`
  - `XDG_VTNR`
  - `CSF_PluginDefaults`
  - `CSF_TObjMessage`
  - `XDG_SESSION_ID`
  - `CASROOT`
  - `CONDA_PYTHON_EXE`
  - `MOZ_PLUGIN_PATH`
  - `XDG_RUNTIME_DIR`
  - `MKLROOT`
  - `DEBUGINFOD_URLS`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `CSF_XSMessage`
  - `MMGT_CLEAR`
  - `PATH`
  - `CSF_TObjDefaults`
  - `GDMSESSION`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `HG`
  - `MAIL`
  - `QT_FONT_DPI`
  - `QT_SCALE_FACTOR`
  - `DRAWDEFAULT`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/paul/anaconda3/condabin:/home/paul/bin:/home/paul/.node_modules/bin:/opt/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/android-sdk/emulator:/opt/android-ndk:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/home/paul/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.utf8`
  - `PWD`: `/mnt/sdd2/Repositories/Python/Coursera`

---------------------------

Contents of `Pipfile` ('/mnt/sdd2/Repositories/Python/Coursera/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
pytest = "*"
pytest-django = "*"
pytest-cov = "*"
factory-boy = "*"
responses = "*"

[packages]
requests = "==2.18.4"
celery = "==4.1.1"
Django = "==2.0"
redis = "==2.10.6"
marshmallow = "==2.15.1"
jsonschema = "==2.6.0"

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/mnt/sdd2/Repositories/Python/Coursera/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "1e5dfbb939020aff3de5b693a9b1228ec1e1afd2174bd18755ad225b20f85c49"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "amqp": {
            "hashes": [
                "sha256:073dd02fdd73041bffc913b767866015147b61f2a9bc104daef172fc1a0066eb",
                "sha256:eed41946890cd43e8dee44a316b85cf6fee5a1a34bb4a562b660a358eb529e1b"
            ],
            "version": "==2.3.2"
        },
        "billiard": {
            "hashes": [
                "sha256:1d7b22bdc47aa52841120fcd22a74ae4fc8c13e9d3935643098184f5788c3ce6",
                "sha256:abd9ce008c9a71ccde2c816f8daa36246e92a21e6a799831b887d88277187ecd"
            ],
            "version": "==3.5.0.3"
        },
        "celery": {
            "hashes": [
                "sha256:6fc4678d1692af97e137b2a9f1c04efd8e7e2fb7134c5c5ad60738cdd927762f",
                "sha256:d1f2a3359bdbdfb344edce98b8e891f5fe64f8a11c5a45538ec20ac237c971f5"
            ],
            "index": "pypi",
            "version": "==4.1.1"
        },
        "certifi": {
            "hashes": [
                "sha256:13e698f54293db9f89122b0581843a782ad0934a4fe0172d2a980ba77fc61bb7",
                "sha256:9fa520c1bacfb634fa7af20a76bcbd3d5fb390481724c597da32c719a7dca4b0"
            ],
            "version": "==2018.4.16"
        },
        "chardet": {
            "hashes": [
                "sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae",
                "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691"
            ],
            "version": "==3.0.4"
        },
        "django": {
            "hashes": [
                "sha256:9614851d4a7ff8cbd32b73c6076441f377c45a5bbff7e771798fb02c43c31f47",
                "sha256:af18618ce3291be5092893d8522fe3919661bf3a1fb60e3858ae74865a4f07c2"
            ],
            "index": "pypi",
            "version": "==2.0"
        },
        "idna": {
            "hashes": [
                "sha256:2c6a5de3089009e3da7c5dde64a141dbc8551d5b7f6cf4ed7c2568d0cc520a8f",
                "sha256:8c7309c718f94b3a625cb648ace320157ad16ff131ae0af362c9f21b80ef6ec4"
            ],
            "version": "==2.6"
        },
        "jsonschema": {
            "hashes": [
                "sha256:000e68abd33c972a5248544925a0cae7d1125f9bf6c58280d37546b946769a08",
                "sha256:6ff5f3180870836cae40f06fa10419f557208175f13ad7bc26caa77beb1f6e02"
            ],
            "index": "pypi",
            "version": "==2.6.0"
        },
        "kombu": {
            "hashes": [
                "sha256:86adec6c60f63124e2082ea8481bbe4ebe04fde8ebed32c177c7f0cd2c1c9082",
                "sha256:b274db3a4eacc4789aeb24e1de3e460586db7c4fc8610f7adcc7a3a1709a60af"
            ],
            "version": "==4.2.1"
        },
        "marshmallow": {
            "hashes": [
                "sha256:a3fe4bc61c4f6902b5cc95bd34cd0803e2a09ae0ea6bf09eb8f491acebe6934c",
                "sha256:b73361eab812af97eaf8e8691333a1096787968450051d132c8b9fb90aa1db5a"
            ],
            "index": "pypi",
            "version": "==2.15.1"
        },
        "pytz": {
            "hashes": [
                "sha256:65ae0c8101309c45772196b21b74c46b2e5d11b6275c45d251b150d5da334555",
                "sha256:c06425302f2cf668f1bba7a0a03f3c1d34d4ebeef2c72003da308b3947c7f749"
            ],
            "version": "==2018.4"
        },
        "redis": {
            "hashes": [
                "sha256:8a1900a9f2a0a44ecf6e8b5eb3e967a9909dfed219ad66df094f27f7d6f330fb",
                "sha256:a22ca993cea2962dbb588f9f30d0015ac4afcc45bee27d3978c0dbe9e97c6c0f"
            ],
            "index": "pypi",
            "version": "==2.10.6"
        },
        "requests": {
            "hashes": [
                "sha256:6a1b267aa90cac58ac3a765d067950e7dbbf75b1da07e895d1f594193a40a38b",
                "sha256:9c443e7324ba5b85070c4a818ade28bfabedf16ea10206da1132edaa6dda237e"
            ],
            "index": "pypi",
            "version": "==2.18.4"
        },
        "urllib3": {
            "hashes": [
                "sha256:06330f386d6e4b195fbfc736b297f58c5a892e4440e54d294d7004e3a9bbea1b",
                "sha256:cc44da8e1145637334317feebd728bd869a35285b93cbb4cca2577da7e62db4f"
            ],
            "version": "==1.22"
        },
        "vine": {
            "hashes": [
                "sha256:52116d59bc45392af9fdd3b75ed98ae48a93e822cee21e5fda249105c59a7a72",
                "sha256:6849544be74ec3638e84d90bc1cf2e1e9224cc10d96cd4383ec3f69e9bce077b"
            ],
            "version": "==1.1.4"
        }
    },
    "develop": {
        "atomicwrites": {
            "hashes": [
                "sha256:240831ea22da9ab882b551b31d4225591e5e447a68c5e188db5b89ca1d487585",
                "sha256:a24da68318b08ac9c9c45029f4a10371ab5b20e4226738e150e6e7c571630ae6"
            ],
            "version": "==1.1.5"
        },
        "attrs": {
            "hashes": [
                "sha256:4b90b09eeeb9b88c35bc642cbac057e45a5fd85367b985bd2809c62b7b939265",
                "sha256:e0d0eb91441a3b53dab4d9b743eafc1ac44476296a2053b6ca3af0b139faf87b"
            ],
            "version": "==18.1.0"
        },
        "certifi": {
            "hashes": [
                "sha256:13e698f54293db9f89122b0581843a782ad0934a4fe0172d2a980ba77fc61bb7",
                "sha256:9fa520c1bacfb634fa7af20a76bcbd3d5fb390481724c597da32c719a7dca4b0"
            ],
            "version": "==2018.4.16"
        },
        "chardet": {
            "hashes": [
                "sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae",
                "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691"
            ],
            "version": "==3.0.4"
        },
        "cookies": {
            "hashes": [
                "sha256:15bee753002dff684987b8df8c235288eb8d45f8191ae056254812dfd42c81d3",
                "sha256:d6b698788cae4cfa4e62ef8643a9ca332b79bd96cb314294b864ae8d7eb3ee8e"
            ],
            "version": "==2.2.1"
        },
        "coverage": {
            "hashes": [
                "sha256:03481e81d558d30d230bc12999e3edffe392d244349a90f4ef9b88425fac74ba",
                "sha256:0b136648de27201056c1869a6c0d4e23f464750fd9a9ba9750b8336a244429ed",
                "sha256:104ab3934abaf5be871a583541e8829d6c19ce7bde2923b2751e0d3ca44db60a",
                "sha256:15b111b6a0f46ee1a485414a52a7ad1d703bdf984e9ed3c288a4414d3871dcbd",
                "sha256:198626739a79b09fa0a2f06e083ffd12eb55449b5f8bfdbeed1df4910b2ca640",
                "sha256:1c383d2ef13ade2acc636556fd544dba6e14fa30755f26812f54300e401f98f2",
                "sha256:28b2191e7283f4f3568962e373b47ef7f0392993bb6660d079c62bd50fe9d162",
                "sha256:2eb564bbf7816a9d68dd3369a510be3327f1c618d2357fa6b1216994c2e3d508",
                "sha256:337ded681dd2ef9ca04ef5d93cfc87e52e09db2594c296b4a0a3662cb1b41249",
                "sha256:3a2184c6d797a125dca8367878d3b9a178b6fdd05fdc2d35d758c3006a1cd694",
                "sha256:3c79a6f7b95751cdebcd9037e4d06f8d5a9b60e4ed0cd231342aa8ad7124882a",
                "sha256:3d72c20bd105022d29b14a7d628462ebdc61de2f303322c0212a054352f3b287",
                "sha256:3eb42bf89a6be7deb64116dd1cc4b08171734d721e7a7e57ad64cc4ef29ed2f1",
                "sha256:4635a184d0bbe537aa185a34193898eee409332a8ccb27eea36f262566585000",
                "sha256:56e448f051a201c5ebbaa86a5efd0ca90d327204d8b059ab25ad0f35fbfd79f1",
                "sha256:5a13ea7911ff5e1796b6d5e4fbbf6952381a611209b736d48e675c2756f3f74e",
                "sha256:69bf008a06b76619d3c3f3b1983f5145c75a305a0fea513aca094cae5c40a8f5",
                "sha256:6bc583dc18d5979dc0f6cec26a8603129de0304d5ae1f17e57a12834e7235062",
                "sha256:701cd6093d63e6b8ad7009d8a92425428bc4d6e7ab8d75efbb665c806c1d79ba",
                "sha256:7608a3dd5d73cb06c531b8925e0ef8d3de31fed2544a7de6c63960a1e73ea4bc",
                "sha256:76ecd006d1d8f739430ec50cc872889af1f9c1b6b8f48e29941814b09b0fd3cc",
                "sha256:7aa36d2b844a3e4a4b356708d79fd2c260281a7390d678a10b91ca595ddc9e99",
                "sha256:7d3f553904b0c5c016d1dad058a7554c7ac4c91a789fca496e7d8347ad040653",
                "sha256:7e1fe19bd6dce69d9fd159d8e4a80a8f52101380d5d3a4d374b6d3eae0e5de9c",
                "sha256:8c3cb8c35ec4d9506979b4cf90ee9918bc2e49f84189d9bf5c36c0c1119c6558",
                "sha256:9d6dd10d49e01571bf6e147d3b505141ffc093a06756c60b053a859cb2128b1f",
                "sha256:9e112fcbe0148a6fa4f0a02e8d58e94470fc6cb82a5481618fea901699bf34c4",
                "sha256:ac4fef68da01116a5c117eba4dd46f2e06847a497de5ed1d64bb99a5fda1ef91",
                "sha256:b8815995e050764c8610dbc82641807d196927c3dbed207f0a079833ffcf588d",
                "sha256:be6cfcd8053d13f5f5eeb284aa8a814220c3da1b0078fa859011c7fffd86dab9",
                "sha256:c1bb572fab8208c400adaf06a8133ac0712179a334c09224fb11393e920abcdd",
                "sha256:de4418dadaa1c01d497e539210cb6baa015965526ff5afc078c57ca69160108d",
                "sha256:e05cb4d9aad6233d67e0541caa7e511fa4047ed7750ec2510d466e806e0255d6",
                "sha256:e4d96c07229f58cb686120f168276e434660e4358cc9cf3b0464210b04913e77",
                "sha256:f3f501f345f24383c0000395b26b726e46758b71393267aeae0bd36f8b3ade80",
                "sha256:f8a923a85cb099422ad5a2e345fe877bbc89a8a8b23235824a93488150e45f6e"
            ],
            "version": "==4.5.1"
        },
        "factory-boy": {
            "hashes": [
                "sha256:6f25cc4761ac109efd503f096e2ad99421b1159f01a29dbb917359dcd68e08ca",
                "sha256:d552cb872b310ae78bd7429bf318e42e1e903b1a109e899a523293dfa762ea4f"
            ],
            "index": "pypi",
            "version": "==2.11.1"
        },
        "faker": {
            "hashes": [
                "sha256:782a58cec0e083df8e3536b0a890fce9bdc1633782c140b64183dcc626fea53e",
                "sha256:a77a1a2223a8e0d32618878350bbd2171040f32b526ba2cddfab8864704bb370"
            ],
            "version": "==0.8.15"
        },
        "idna": {
            "hashes": [
                "sha256:2c6a5de3089009e3da7c5dde64a141dbc8551d5b7f6cf4ed7c2568d0cc520a8f",
                "sha256:8c7309c718f94b3a625cb648ace320157ad16ff131ae0af362c9f21b80ef6ec4"
            ],
            "version": "==2.6"
        },
        "more-itertools": {
            "hashes": [
                "sha256:2b6b9893337bfd9166bee6a62c2b0c9fe7735dcf85948b387ec8cba30e85d8e8",
                "sha256:6703844a52d3588f951883005efcf555e49566a48afd4db4e965d69b883980d3",
                "sha256:a18d870ef2ffca2b8463c0070ad17b5978056f403fb64e3f15fe62a52db21cc0"
            ],
            "version": "==4.2.0"
        },
        "pluggy": {
            "hashes": [
                "sha256:7f8ae7f5bdf75671a718d2daf0a64b7885f74510bcd98b1a0bb420eb9a9d0cff",
                "sha256:d345c8fe681115900d6da8d048ba67c25df42973bda370783cd58826442dcd7c",
                "sha256:e160a7fcf25762bb60efc7e171d4497ff1d8d2d75a3d0df7a21b76821ecbf5c5"
            ],
            "version": "==0.6.0"
        },
        "py": {
            "hashes": [
                "sha256:29c9fab495d7528e80ba1e343b958684f4ace687327e6f789a94bf3d1915f881",
                "sha256:983f77f3331356039fdd792e9220b7b8ee1aa6bd2b25f567a963ff1de5a64f6a"
            ],
            "version": "==1.5.3"
        },
        "pytest": {
            "hashes": [
                "sha256:39555d023af3200d004d09e51b4dd9fdd828baa863cded3fd6ba2f29f757ae2d",
                "sha256:c76e93f3145a44812955e8d46cdd302d8a45fbfc7bf22be24fe231f9d8d8853a"
            ],
            "index": "pypi",
            "version": "==3.6.0"
        },
        "pytest-cov": {
            "hashes": [
                "sha256:03aa752cf11db41d281ea1d807d954c4eda35cfa1b21d6971966cc041bbf6e2d",
                "sha256:890fe5565400902b0c78b5357004aab1c814115894f4f21370e2433256a3eeec"
            ],
            "index": "pypi",
            "version": "==2.5.1"
        },
        "pytest-django": {
            "hashes": [
                "sha256:534505e0261cc566279032d9d887f844235342806fd63a6925689670fa1b29d7",
                "sha256:7501942093db2250a32a4e36826edfc542347bb9b26c78ed0649cdcfd49e5789"
            ],
            "index": "pypi",
            "version": "==3.2.1"
        },
        "python-dateutil": {
            "hashes": [
                "sha256:1adb80e7a782c12e52ef9a8182bebeb73f1d7e24e374397af06fb4956c8dc5c0",
                "sha256:e27001de32f627c22380a688bcc43ce83504a7bc5da472209b4c70f02829f0b8"
            ],
            "version": "==2.7.3"
        },
        "requests": {
            "hashes": [
                "sha256:6a1b267aa90cac58ac3a765d067950e7dbbf75b1da07e895d1f594193a40a38b",
                "sha256:9c443e7324ba5b85070c4a818ade28bfabedf16ea10206da1132edaa6dda237e"
            ],
            "index": "pypi",
            "version": "==2.18.4"
        },
        "responses": {
            "hashes": [
                "sha256:c6082710f4abfb60793899ca5f21e7ceb25aabf321560cc0726f8b59006811c9",
                "sha256:f23a29dca18b815d9d64a516b4a0abb1fbdccff6141d988ad8100facb81cf7b3"
            ],
            "index": "pypi",
            "version": "==0.9.0"
        },
        "six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        },
        "text-unidecode": {
            "hashes": [
                "sha256:5a1375bb2ba7968740508ae38d92e1f889a0832913cb1c447d5e2046061a396d",
                "sha256:801e38bd550b943563660a91de8d4b6fa5df60a542be9093f7abf819f86050cc"
            ],
            "version": "==1.2"
        },
        "urllib3": {
            "hashes": [
                "sha256:06330f386d6e4b195fbfc736b297f58c5a892e4440e54d294d7004e3a9bbea1b",
                "sha256:cc44da8e1145637334317feebd728bd869a35285b93cbb4cca2577da7e62db4f"
            ],
            "version": "==1.22"
        }
    }
}

```
</details>

**Comment by Paul4936** [comment]
Update:
To check if there something with my setup - i downloaded clear Virtualbox image of my distributive(Archlinux), created Pipfile, installed DE(Mate), gcc, make, python pipenv\venv and dependencies. And get same error.

**Comment by Paul4936** [comment]
I dont know if this will help.
But, there is VirtualBox image(3.9 GB):
https://mega.nz/file/Fa4BHTgb#CNSPnKsVeFC-kDxt2s2BHGHywzoGY4_pRFXX9Taugag

Password is:
`archlinux`

**Username the same as password.**

**Comment by matteius** [comment]
I am not sure on this one but I am not going to download that VirtualBox Image due to concerns about downloading any binary image like that.

**Comment by Paul4936** [comment]
> I am not sure on this one but I am not going to download that VirtualBox Image due to concerns about downloading any binary image like that.

Can you please recommend any another way to deliver OS&Software with problem?

**Comment by Paul4936** [comment]
BTW, if python is set to 3.10 or 3.9 or 3.8 - looks like all fine.

**Comment by Paul4936** [comment]
> 1.2.3 2022.4.21 (2022-04-21)
Removals and Deprecations
• Updated setup.py to remove support for python 3.6 from built pipenv packages’ Metadata. #5065

Oh. Well. Many shame on me.
So looks like that is totally not a bug, its just mean 3.6 is too old and deprecated.
If anyone get the same problem - i suggest to use docker, or downgrade whole system.

**Comment by Paul4936** [comment]
> 1.2.3 2022.4.21 (2022-04-21)
Removals and Deprecations
• Updated setup.py to remove support for python 3.6 from built pipenv packages’ Metadata. #5065

Oh. Well. Many shame on me.
So looks like that is totally not a bug, its just mean 3.6 is too old and deprecated.
If anyone get the same problem - i suggest to use docker, or downgrade whole system.
