### ISSUE TITLE
Recursive search for egg-info directories breaks nested projects

### ISSUE THREAD

**Issue by owtaylor** [pypa/pipenv#5118]
### Issue description

During locking, when the resolver subprocess looks for a name for a requirement, and the requirement is a local path, then it ([via requirementslib](https://github.com/pypa/pipenv/blob/main/pipenv/vendor/requirementslib/models/setup_info.py#L763)) will *recursively* search for an .egg-info directory and get the name from there. But the .egg-info directory might be unrelated to the package to install. In particular, a pathological case occurs when:

* A Pipfile lists multiple packages, one nested inside the other
* The inner one is processed first
* Processing the inner one *generates* an .egg-info directory (because `setup.py egg_info` is invoked)

In this case, the resolver process ends up with the same name for the inner and outer package, and things get badly confused. See "Steps to Reproduce" below.

### Expected result

`Pipfile.lock` has the correct path for each project

### Actual result

Pipfile.lock is corrupted and confuses the outer and inner packages

```
    "default": {
        "french-toast": {
            "editable": true,
            "path": "."
        },
        "scrambled-eggs": {
            "editable": "true",
            "path": "."
        }
    },
```

### Steps to replicate

1. Clone the repo https://github.com/owtaylor/scrambled_eggs. It has following structure

```
scrambled_eggs/
   Pipfile
   setup.py
   scrambled_eggs/
      __init__.py
   french_toast/
       setup.py
       french_toast/
            __init__.py
```

and the following Pipfile

``` toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
french_toast = {path = "./french_toast", editable = "true"}
scrambled_eggs = {path = ".", editable = "true"}
```

2. Make sure that there are no existing .egg-info directories from previous runs (`git clean -dxf`)
3. Run `pipenv lock` and observe the Pipfile.lock generated

***NOTE***: the order of requirement processing is arbitrary - it may be necessary to force it by editing https://github.com/pypa/pipenv/blob/main/pipenv/utils/resolver.py#L152

***WORKAROUND**: Run `python setup.py egg_info` at the toplevel before running `pipenv lock`. This will create an egg_info directory for the outer package, which will be found first.

I'm not really sure what the right fix here is - requirementslib could not scan recursively for .egg-info directories and only look for directo subdirectories of the given path - but there's probably some reason that the recursive search was added?

-------------------------------------------------------------------------------

Pipenv version: `'2022.5.2'`

Pipenv location: `'/var/home/otaylor/.local/share/virtualenvs/scrambled_eggs-mbSpAmTK/lib/python3.10/site-packages/pipenv'`

Python location: `'/var/home/otaylor/.local/share/virtualenvs/scrambled_eggs-mbSpAmTK/bin/python'`

Python installations found:

  - `3.10.4`: `/var/home/otaylor/.local/share/virtualenvs/scrambled_eggs-mbSpAmTK/bin/python`
  - `3.10.4`: `/var/home/otaylor/.local/share/virtualenvs/scrambled_eggs-mbSpAmTK/bin/python3`
  - `3.10.4`: `/var/home/otaylor/.local/share/virtualenvs/scrambled_eggs-mbSpAmTK/bin/python`
  - `3.10.4`: `/var/home/otaylor/.local/share/virtualenvs/scrambled_eggs-mbSpAmTK/bin/python3`
  - `3.10.4`: `/usr/bin/python3`
  - `3.10.4`: `/bin/python3`
  - `3.9.12`: `/usr/bin/python3.9`
  - `3.9.12`: `/usr/bin/pypy3.9`
  - `3.9.12`: `/usr/bin/pypy3`
  - `3.9.12`: `/bin/python3.9`
  - `3.9.12`: `/bin/pypy3.9`
  - `3.9.12`: `/bin/pypy3`
  - `3.8.13`: `/usr/bin/python3.8`
  - `3.8.13`: `/usr/bin/pypy3.8`
  - `3.8.13`: `/bin/python3.8`
  - `3.8.13`: `/bin/pypy3.8`
  - `3.7.13`: `/usr/bin/python3.7`
  - `3.7.13`: `/usr/bin/python3.7m`
  - `3.7.13`: `/bin/python3.7`
  - `3.7.13`: `/bin/python3.7m`
  - `3.6.15`: `/usr/bin/python3.6`
  - `3.6.15`: `/usr/bin/python3.6m`
  - `3.6.15`: `/bin/python3.6`
  - `3.6.15`: `/bin/python3.6m`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`
  - `2.7.18`: `/usr/bin/pypy2`
  - `2.7.18`: `/usr/bin/pypy`
  - `2.7.18`: `/usr/bin/pypy2.7`
  - `2.7.18`: `/bin/python2`
  - `2.7.18`: `/bin/python2.7`
  - `2.7.18`: `/bin/pypy2`
  - `2.7.18`: `/bin/pypy`
  - `2.7.18`: `/bin/pypy2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.15.8-200.fc35.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Tue Dec 14 14:26:01 UTC 2021',
 'python_full_version': '3.10.4',
 'python_version': '3.10',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `COLORTERM`
  - `HISTCONTROL`
  - `XDG_MENU_PREFIX`
  - `PIPENV_ACTIVE`
  - `HOSTNAME`
  - `HISTSIZE`
  - `SSH_AUTH_SOCK`
  - `DISTTAG`
  - `DESKTOP_SESSION`
  - `EDITOR`
  - `NAME`
  - `PWD`
  - `XDG_SESSION_DESKTOP`
  - `LOGNAME`
  - `XDG_SESSION_TYPE`
  - `TOOLBOX_PATH`
  - `GNOME_TERMINAL_FEATURES`
  - `XAUTHORITY`
  - `container`
  - `TOOLBOX_CONTAINER`
  - `PIP_PYTHON_PATH`
  - `HOME`
  - `LANG`
  - `LS_COLORS`
  - `XDG_CURRENT_DESKTOP`
  - `FGC`
  - `VIRTUAL_ENV`
  - `VTE_VERSION`
  - `WAYLAND_DISPLAY`
  - `GNOME_TERMINAL_SCREEN`
  - `ANSIBLE_NOCOWS`
  - `TERM`
  - `LESSOPEN`
  - `USER`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `GNOME_TERMINAL_SERVICE`
  - `DISPLAY`
  - `SHLVL`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_RUNTIME_DIR`
  - `PS1`
  - `DEBUGINFOD_URLS`
  - `which_declare`
  - `XDG_DATA_DIRS`
  - `PATH`
  - `VERSION`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `MAIL`
  - `OLDPWD`
  - `BASH_FUNC_which%%`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/var/home/otaylor/.local/share/virtualenvs/scrambled_eggs-mbSpAmTK/bin:/var/home/otaylor/.local/bin:/var/home/otaylor/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `/usr/bin/vim`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/var/home/otaylor/Source/scrambled_eggs`
  - `VIRTUAL_ENV`: `/var/home/otaylor/.local/share/virtualenvs/scrambled_eggs-mbSpAmTK`

**Comment by matteius** [comment]
> I'm not really sure what the right fix here is - requirementslib could not scan recursively for .egg-info directories and only look for directo subdirectories of the given path - but there's probably some reason that the recursive search was added?

The code you linked to in requirementslib has been that way for 3 years.

I tried the example @owtaylor but it seemed to work fine, no errors:

```
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ git clean -dxf
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ pipenv lock
Creating a virtualenv for this project...
Pipfile: /home/matteius/pipenv-triage/pipenv-5118/scrambled_eggs/Pipfile
Using /home/matteius/.pyenv/versions/3.10.2/bin/python3 (3.10.2) to create virtualenv...
⠼ Creating virtual environment...created virtual environment CPython3.10.2.final.0-64 in 557ms
  creator CPython3Posix(dest=/home/matteius/.virtualenvs/scrambled_eggs-tI4FO2ez, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/matteius/.local/share/virtualenv)
    added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/matteius/.virtualenvs/scrambled_eggs-tI4FO2ez
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (c8a99c)!
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ git diff
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ cat Pipfile.lock 
{
    "_meta": {
        "hash": {
            "sha256": "00a46b458d13e0a1bb67bcccae4980309f9e48546306b4a52533e71a7ec8a99c"
        },
        "pipfile-spec": 6,
        "requires": {},
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "french-toast": {
            "editable": true,
            "path": "./french_toast"
        },
        "scrambled-eggs": {
            "editable": true,
            "path": "."
        }
    },
    "develop": {}
}
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ pipenv --version
pipenv, version 2022.5.2
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ pipenv sync
Installing dependencies from Pipfile.lock (c8a99c)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:17
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!
```

**Comment by matteius** [comment]
@owtaylor Ok weird, on take two I see what you mean about it generating a different Pipfile.lock this time.

```
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ git clean -dxf
Removing Pipfile.lock
Removing build/
Removing french_toast/build/
Removing french_toast/french_toast.egg-info/
Removing scrambled_eggs.egg-info/
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ pipenv lock
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (c8a99c)!
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ cat Pipfile.lock 
{
    "_meta": {
        "hash": {
            "sha256": "00a46b458d13e0a1bb67bcccae4980309f9e48546306b4a52533e71a7ec8a99c"
        },
        "pipfile-spec": 6,
        "requires": {},
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "french-toast": {
            "editable": true,
            "path": "."
        },
        "scrambled-eggs": {
            "editable": "true",
            "path": "."
        }
    },
    "develop": {}
}
```

**Comment by owtaylor** [comment]
This isn't entirely a recent regression - with 2021.5.29:

 * The problem occurs if you *manually* run 'python setup.py egg_info'
 * But pipenv / requirementslib doesn't end creating up the egg-info directory itself (not quite sure why), while it is created with current pipenv

As you've seen it's quite a heisenbug - if you look at it wrong it goes away (I expect people have hit it, tried again, and ignored it.) The two sources I know of unreproducibility I know of are:
 
 1. The dependency on what files already exist - you have to *not* have metadata for the out project
 2. The fact that pipenv iterates the packages from the requirements in undefined order (the `constraints = set(deps)` code I linked to above)

But there might be something else going on that makes it tricky as well. I had a Dockerfile that reproduced it and spent a good chunk of yesterday patching pipenv in the build environment to add debug-prints until I figured out what was going on ...

**Comment by matteius** [comment]
> As you've seen it's quite a heisenbug 

As are many pipenv bugs I have been involved with so far--it can be very time consuming to understand the bug, yet alone fixing it.   This is something that I could use help with and I am willing to collaborate on the fix.  Is this something you have bandwidth to take on (it sounds like you've already started working on an understanding of that code)?   If so, I can mark you as assigned and If not I will tag this item with help wanted.   

> But pipenv / requirementslib doesn't end creating up the egg-info directory itself (not quite sure why), while it is created with current pipenv

This maybe has to do with some changes to support newer version of setuptools, though I am only speculating based on what I know so far that setuptools has been evolving in the last 6 months.  I helped release the new version of requirementslib, though my changes wouldn't have been specific to this issue, at least I don't think.

**Comment by matteius** [comment]
@owtaylor Thanks for your excellent analysis.  I may have just figured this out as a logical bug from the outer method that calls `_parse_name_from_path` Check out my PR of requirementslib here:  https://github.com/sarugaku/requirementslib/pull/319/files

Basically there was a logical boolean error where the name may have already been established but it tried to get the name again when `is_remote_url` or `is_path` was true.  

 `elif name is None and self.is_file or self.is_remote_url or self.is_path` should become `elif name is None and (self.is_file or self.is_remote_url or self.is_path):`

I patched it to my local pipenv vendor directory and re-ran your example and it worked to lock and install, so it seemed work.  Here is my output:

```
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ pipenv --rm
Removing virtualenv (/home/matteius/.virtualenvs/scrambled_eggs-tI4FO2ez)...
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ pipenv lock
Creating a virtualenv for this project...
Pipfile: /home/matteius/pipenv-triage/pipenv-5118/scrambled_eggs/Pipfile
Using /home/matteius/.pyenv/versions/3.10.2/bin/python3 (3.10.2) to create virtualenv...
⠼ Creating virtual environment...created virtual environment CPython3.10.2.final.0-64 in 474ms
  creator CPython3Posix(dest=/home/matteius/.virtualenvs/scrambled_eggs-tI4FO2ez, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/matteius/.local/share/virtualenv)
    added seed packages: pip==22.1.2, setuptools==62.3.4, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/matteius/.virtualenvs/scrambled_eggs-tI4FO2ez
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (c8a99c)!
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ cat Pipfile.lock 
{
    "_meta": {
        "hash": {
            "sha256": "00a46b458d13e0a1bb67bcccae4980309f9e48546306b4a52533e71a7ec8a99c"
        },
        "pipfile-spec": 6,
        "requires": {},
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "french-toast": {
            "editable": true,
            "path": "./french_toast"
        },
        "scrambled-eggs": {
            "editable": true,
            "path": "."
        }
    },
    "develop": {}
}
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ ls
build  french_toast  Pipfile  Pipfile.lock  pyproject.toml  README.md  scrambled_eggs  scrambled_eggs.egg-info  setup.py
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ pipenv install
Installing dependencies from Pipfile.lock (c8a99c)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:20
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5118/scrambled_eggs$ pipenv run pip freeze
-e git+https://github.com/owtaylor/scrambled_eggs@eafd1828e402c5709b311499cfaea766f995bf33#egg=french_toast&subdirectory=french_toast
-e git+https://github.com/owtaylor/scrambled_eggs@eafd1828e402c5709b311499cfaea766f995bf33#egg=scrambled_eggs
```

Let me know if that also looks correct to you, and I can try to get another patch release of requirementslib out and vendor'd in soon.  Thanks again!
