### ISSUE TITLE
Switch from type comments to type annotations

### ISSUE THREAD

**Issue by ethanhs** [pypa/pipenv#5119]
### Is your feature request related to a problem? Please describe.

Eventually mypy, pyflakes, and other code checking tools would like to switch away from supporting type comments since type annotations are cleaner, simpler, and easier to parse.

### Describe the solution you'd like

Pipenv should switch to using type annotations instead of type comments.

### Describe alternatives you've considered

Not switching would be an option, no deprecation has been announced (yet). However, type comments will be deprecated at some point I expect.

**Comment by matteius** [comment]
@ethanhs oh wow you even opened a PR already -- this is awesome!  I will try to take a look sometime soon.

**Comment by matteius** [comment]
Has been merged to `main` branch.  Thanks for the PR @ethanhs !
