### ISSUE TITLE
pipenv on windows does not honor PIPENV_PYTHON variable with pyenv-win

### ISSUE THREAD

**Issue by spencerbug** [pypa/pipenv#5125]
### Issue description

I'm trying to set up pipenv with pyenv in Windows 10 for easy version management with project isolation, but I'm not sure how to get pipenv to use the version I have configured with pyenv.

### Expected result

I would expect switching the python version in pyenv would dictate the version pipenv uses in its virtual shell environment.

### Actual result

pipenv with pyenv in windows does not use the version specified in the current pyenv variable, as it does not seem to only default to a fixed python version

### Steps to replicate

1.  Environment: Windows 10, with no prior python installations
2.[ Install pyenv-win with powershell](https://pyenv-win.github.io/pyenv-win/#power-shell): `Invoke-WebRequest -UseBasicParsing -Uri "https://raw.githubusercontent.com/pyenv-win/pyenv-win/master/pyenv-win/install-pyenv-win.ps1" -OutFile "./install-pyenv-win.ps1"; &"./install-pyenv-win.ps1"`
3. Install a version of python via pyenv: `pyenv install 3.11.0b1`
4. Install another version of python via pyenv: `pyenv install 3.9.13`
5. Add PIPENV_PYTHON environment variable to point to the shims in powershell: `[System.Environment]::SetEnvironmentVariable('PIPENV_PYTHON',$env:PYENV_HOME + "\bin\python","User")`
6. close and reopen powershell
7. switch to 3.11 `pyenv global 3.11.0b1`
8. Go to a folder, and run `pipenv install` then `pipenv_shell` 
9. Check the python version. `python --version`
10. I would expect python to be 3.11, but it is instead 3.9
11. Strangely, the Pipfile does show [requires] python_version="3.11" even though it's at 3.9
Any suggestions?

**Comment by matteius** [comment]
@spencerbug I believe I have it working for myself locally, where by it uses the python version specified in the Pipfile and installs it using pyenv-win.   I think part of the solution is how I have my environment setup, I have these included in my .bashrc file (it may be different for powershell where you define these, but that is working for me too -- its just that I mostly use git shell on windows for a terminal):
```
alias python='winpty python.exe'
alias pipenv='winpty pipenv.exe'
export PATH=$PATH:~/.pyenv/pyenv-win/bin/:~/.pyenv/pyenv-win/shims
export PYENV_HOME=~/.pyenv
export PYENV_ROOT=~/.pyenv
export PYENV=~/.pyenv

export PATH=$PATH:~/.local/bin

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Projects
```

**Comment by spencerbug** [comment]
Thanks @matteius I tried that and was able to get it working
