### ISSUE TITLE
PyPi outages:  Too many redirects when updating

### ISSUE THREAD

**Issue by AKJ7** [pypa/pipenv#5126]
### Issue description

`requests.exceptions.TooManyRedirects: Exceeded 30 redirects.` while updating packages that were working fine the day before. 

### Steps to replicate

Just add a bunch of dependencies to a Pipfile and run pipenv update like always.

**Comment by ranvit** [comment]
Or, make no updates to your Pipfile, just run `pipenv clean` and even that results in the error 🥲

**Comment by thunderpowered** [comment]
Same here. Started just today. But i believe this is not a Pipenv fault. Seems like some packages are unavailable, for instance "djangorestframework-simplejwt". When i commented like with this package in Pipenv file and ran 'pipenv lock', everything worked well, but when i uncommented it back the error appeared again.

**Comment by danielwoerner** [comment]
> instance

similar thing here. for me it was the package `PyJWT="*"`.

example:

Pipfile
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
PyJWT = "*"
```
then running `pipenv --verbose lock`
spits out the `requests.exceptions.TooManyRedirects: Exceeded 30 redirects.` Error

**Comment by matteius** [comment]
https://status.python.org/

**Comment by AKJ7** [comment]
As it seems, the servers are down/busy.
Leaving the ticket opened for all new comers.
Closing it as soon as the issue is resolved.

**Comment by tilda** [comment]
could this issue be pinned? there's probably gonna be a lot of people coming to the tracker about this

**Comment by AndBondStyle** [comment]
Quick dirty fix that worked for me: open `<python>/site-packages/pipenv/utils/resolver.py`, search for `_get_hashes_from_pypi` method and change `r = session.get(pkg_url, timeout=10)` to `r = session.get(pkg_url, timeout=10, allow_redirects=False)`. It gives some warnings ("Error generating hash for <package>") during install, but otherwise everything seems to work fine.

**Comment by matteius** [comment]
I wouldn't advise that for anyone running any kind of sensitive transactions to just cobble the code and ignore hash checking errors.

**Comment by matteius** [comment]
This has been resolved according to the status page.
