### ISSUE TITLE
conda-feedstock broken?

### ISSUE THREAD

**Issue by drewgilliam** [pypa/pipenv#5128]
I've haven't gotten any response over at conda-forge, so I'm hoping someone here can help.  The conda-forge feedstock has failed for almost all 2022 pipenv releases (latest pipenv version on conda-forge is 2022.1.8).  Would anyone on the pipenv team be able to help fix the conda-forge feedstock?

https://github.com/conda-forge/pipenv-feedstock/issues/24
https://anaconda.org/conda-forge/pipenv/files

**Comment by matteius** [comment]
@drewgilliam  Can you kick off some new builds over there?  All of the old builds are too old to have the log files still available in Github Actions.

**Comment by drewgilliam** [comment]
Thanks for the quick response!  I don't think I have permissions to do anything in pipenv-feedstock - I'm just a user of conda-forge not an admin of the pipenv-feedstock.  There seem to only be two human contributors in the history of pipenv-feedstock., @roccqqck and @beckermr, maybe they could kick something off?

**Comment by beckermr** [comment]
I don't recall making any non-admin changes to the feedstock. (I did accidentally make commits to most feedstocks on conda forge a while back.)

Feel free to push a fix.

**Comment by matteius** [comment]
@beckermr Well for one, I don't know what the `pipenv-feedstock` project is about, and the actual problem has been lost to the logs being no longer available, so unless you can kick off a run that demonstrates the failure within the logs, then I won't be spending time on it.

**Comment by matteius** [comment]
Sorry for the delay in responding @drewgilliam, yes I believe this is expected that CI should be set to 1 or unset or 0.  However at first glance, that code doesn't look correct.  Shouldn't this line:
`PIPENV_IS_CI = env_to_bool(os.environ.get("CI") or os.environ.get("TF_BUILD") or False)`
Actually be more correct as this:
`PIPENV_IS_CI = env_to_bool(os.environ.get("CI")) or env_to_bool(os.environ.get("TF_BUILD"))`

cc: @oz123

**Comment by matteius** [comment]
@drewgilliam Clarifying question -- does your environment need CI to be set to `azure` for other reasons in the build pipeline besides `pipenv`?

**Comment by drewgilliam** [comment]
I don't know too much about the conda-forge feedstock environment - in my limited understanding, its a fairly automated environment where a lot of stuff is autogenerated for each feedstock package by the "conda smithy".  The `CI` variable appears to be set in one of these auto-generated files, I assume/hope for good reason:
https://github.com/conda-forge/pipenv-feedstock/blob/main/.azure-pipelines/azure-pipelines-linux.yml#L32

Even with the suggested change, `env_to_bool` is going to throw an error if `CI` or `TF_BUILD` are anything but truthy/falsey.
https://github.com/pypa/pipenv/blob/d2365bb3fd921a3326226c4c64339412fac71d88/pipenv/environments.py#L17-L35

Assuming you're just trying to check if you're in a `CI=1` type environment, maybe it would be better if env_to_bool returned false by default?
```
_true_values = ("1", "true", "yes", "on")

def env_to_bool(val):
    """
    Convert **val** to boolean, returning True only if truthy
    :param Any val: The value to convert
    :return: True if truthy, otherwise False
    :rtype: bool
    """
    if isinstance(val, bool):
        return val
    else:
        return val.lower() in _true_values

```

**Comment by matteius** [comment]
@drewgilliam Is it safe to close this ticket at this point seeing as `conda-feedstock` has been fixed?

**Comment by drewgilliam** [comment]
@matteius - before you close this issue, is there an answer to my comment above?  It seems unexpected that pipenv will fail for any user/system that happens to have an environment variable `CI` which does not translate to a boolean variable.

**Comment by matteius** [comment]
@drewgilliam I opened a PR to improve handling of the CI variable:  https://github.com/pypa/pipenv/pull/5222
