### ISSUE TITLE
Reuse libraries in pip own's _vendor

### ISSUE THREAD

**Issue by oz123** [pypa/pipenv#5174]
There are some libraries that we vendor, and are already found in `pip/_vendor`. These are;

```
colorma
tomli
urllib3
pyparsing
packaging
pep517
platformdirs
idna
distlib
six
```

Removing them from our own vendor is going to serve pipenv users with a smaller package and remove duplication.
It is also worth noting that most of these libraries are probably not going to be removed from pip since they are crucial for 
parsing of dependencies.

Those who are not really related like `tomli, colorama` and `urllib3` are crucial for other reasons and I also don't see them
being removed from pip anytime soon.

**Comment by matteius** [comment]
@oz123 Anything left on this one?

**Comment by oz123** [comment]
attrs is still an open issue. It's a large one though.
