### ISSUE TITLE
Pipfile in home directory confuses Pipenv

### ISSUE THREAD

**Issue by ccurvey** [pypa/pipenv#5186]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

If there is a Pipfile in your home directory, pipenv will create a new environment named after your home directory.

### Expected result

I expect pipenv to create the new environment based on the current directory name

### Actual result

Wrong pipenv directory created

### Steps to replicate

A) Start with a user error -- running `pipenv shell` in your home directory

```
$ cd 
$ pwd
/home/chris
$ pipenv shell --python `pyenv which python`
```
Now there's a Pipfile at `/home/chris/Pipfile`

B) Start a new terminal, so everything is clean, and try to create a new environment

```
$ mkdir abcd
$ cd abcd
$ pipenv shell --python `pyenv which python`
Launching subshell in virtual environment...
 . /home/chris/.virtualenvs/chris-305vt3Nc/bin/activate
chris@chi ~ 
$  . /home/chris/.virtualenvs/chris-305vt3Nc/bin/activate
(chris) chris@chi ~ 
```

Note that the virtualenv that was created is for "chris" not for "abcd".  And this is done without warning.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.7.4'`

Pipenv location: `'/home/chris/.local/lib/python3.10/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.10.4`: `/usr/bin/python3`
  - `3.10.4`: `/usr/bin/python`
  - `3.10.4`: `/bin/python3`
  - `3.10.4`: `/bin/python`
  - `3.9.7`: `/home/chris/.pyenv/versions/3.9.7/bin/python3`
  - `3.8.10`: `/home/chris/.virtualenvs/chris-305vt3Nc/bin/python3`
  - `3.8.10`: `/home/chris/.virtualenvs/chris-305vt3Nc/bin/python`
  - `3.8.10`: `/home/chris/.virtualenvs/chris-305vt3Nc/bin/python3.8`
  - `3.8.10`: `/home/chris/.virtualenvs/chris-305vt3Nc/bin/python3`
  - `3.8.10`: `/home/chris/.virtualenvs/chris-305vt3Nc/bin/python`
  - `3.8.10`: `/home/chris/.virtualenvs/chris-305vt3Nc/bin/python3.8`
  - `3.8.10`: `/home/chris/.pyenv/versions/3.8.10/bin/python3`
  - `3.6.8`: `/usr/bin/python3.6m`
  - `3.6.8`: `/usr/bin/python3.6`
  - `3.6.8`: `/bin/python3.6m`
  - `3.6.8`: `/bin/python3.6`
  - `2.7.18`: `/usr/bin/pypy`
  - `2.7.18`: `/usr/bin/python2.7`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/bin/pypy`
  - `2.7.18`: `/bin/python2.7`
  - `2.7.18`: `/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.15.0-41-generic',
 'platform_system': 'Linux',
 'platform_version': '#44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022',
 'python_full_version': '3.10.4',
 'python_version': '3.10',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `SESSION_MANAGER`
  - `QT_ACCESSIBILITY`
  - `COLORTERM`
  - `PYENV_SHELL`
  - `XDG_CONFIG_DIRS`
  - `GTK_IM_MODULE`
  - `PIPENV_ACTIVE`
  - `TERMINATOR_DBUS_PATH`
  - `MANDATORY_PATH`
  - `SSH_AUTH_SOCK`
  - `TERMINATOR_UUID`
  - `XMODIFIERS`
  - `DESKTOP_SESSION`
  - `EDITOR`
  - `GTK_MODULES`
  - `XDG_SEAT`
  - `MATE_DESKTOP_SESSION_ID`
  - `PWD`
  - `XDG_SESSION_DESKTOP`
  - `LOGNAME`
  - `QT_QPA_PLATFORMTHEME`
  - `XDG_SESSION_TYPE`
  - `GPG_AGENT_INFO`
  - `SYSTEMD_EXEC_PID`
  - `XAUTHORITY`
  - `WINDOWPATH`
  - `VIRTUALENVWRAPPER_SCRIPT`
  - `PIP_PYTHON_PATH`
  - `HOME`
  - `USERNAME`
  - `LANG`
  - `LS_COLORS`
  - `_VIRTUALENVWRAPPER_API`
  - `XDG_CURRENT_DESKTOP`
  - `VIRTUAL_ENV`
  - `VTE_VERSION`
  - `TERMINATOR_DBUS_NAME`
  - `CLUTTER_IM_MODULE`
  - `WORKON_HOME`
  - `LESSCLOSE`
  - `XDG_SESSION_CLASS`
  - `IBUS_DISABLE_SNOOPER`
  - `TERM`
  - `GTK_OVERLAY_SCROLLING`
  - `DEFAULTS_PATH`
  - `LESSOPEN`
  - `USER`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `DISPLAY`
  - `SHLVL`
  - `QT_IM_MODULE`
  - `XDG_VTNR`
  - `UBUNTU_MENUPROXY`
  - `XDG_SESSION_ID`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_RUNTIME_DIR`
  - `COMPIZ_CONFIG_PROFILE`
  - `PS1`
  - `PYENV_ROOT`
  - `GTK3_MODULES`
  - `XDG_DATA_DIRS`
  - `PATH`
  - `GDMSESSION`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `QT_FONT_DPI`
  - `QT_SCALE_FACTOR`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `OLDPWD`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/chris/.virtualenvs/chris-305vt3Nc/bin:/home/chris/.pyenv/bin:/home/chris/.pyenv/bin:/home/chris/.cargo/bin:/home/chris/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/chris/mycroft-core/bin:/home/chris/.local/bin:/home/chris/.local/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/chris`
  - `VIRTUAL_ENV`: `/home/chris/.virtualenvs/chris-305vt3Nc`

---------------------------

Contents of `Pipfile` ('/home/chris/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.8"

```

</details>

**Comment by matteius** [comment]
This would essentially happen anytime you try to create a pipenv environment inside a directory that is already made into a pipenv environment.  I am not sure what the desired change would be honestly.  You can run `pipenv --rm` in your home directory to clean up that issue as it currently stands.

**Comment by ccurvey** [comment]
oh well.  I guess I was hoping for the "Principle of Least Surprise".

**Comment by matteius** [comment]
@ccurvey Well I mean the issue doesn't have to be closed -- if you or someone has an idea for how we can improve the experience then let's do it.

**Comment by ccurvey** [comment]
note to self.    If by accident, you create an environment in your home directory, use `pipenv --rm` to get rid of all the files related to that environment.
