### ISSUE TITLE
Convert away from `six` python 2 -> 3 conversion library

### ISSUE THREAD

**Issue by matteius** [pypa/pipenv#5187]
Convert away from `six` python 2 -> 3 conversion library

### Issue description

We no longer support python 2 so including six should no longer be a requirement.

**Comment by oz123** [comment]
We will need to sieve through the vendored packages and slowly bump them up to versions that don't support Python2.

**Comment by oz123** [comment]
I already removed\bumped  a few vendored libs which pulled six.
We now only have plette and pipfile which pull it.
