### ISSUE TITLE
Cosmetic issue with PIPENV_COLORBLIND deprecation warning

### ISSUE THREAD

**Issue by davep** [pypa/pipenv#5192]
### Issue description

The deprecation warning about the use of `PIPENV_COLORBLIND` looks like this:

`PIPENV_COLORBLIND is deprecated, use NO_COLOR insteadPer https://no-color.org/`

It would seem that [this text here](https://github.com/pypa/pipenv/blob/46c13edaf430888ede758b052f0a7a42eda23810/pipenv/cli/command.py#L96-L101) just needs a tweak (sorry, I would have done a PR but I'm not in a position to do that at the moment, just noticed this and thought it worth a mention).

### Expected result

It should probably look something like this:

`PIPENV_COLORBLIND is deprecated, use NO_COLOR instead, per https://no-color.org/`

or perhaps:

```
PIPENV_COLORBLIND is deprecated, use NO_COLOR instead
Per https://no-color.org/
```

Etc. 

### Actual result

`PIPENV_COLORBLIND is deprecated, use NO_COLOR insteadPer https://no-color.org/`

### Steps to replicate

Use the latest `pipenv` version as normal but have `PIPENV_COLORBLIND` set to a positive value in your environment.

**Comment by otherjake** [comment]
doh, fixing this
