### ISSUE TITLE
Documentation doesn't list environment variables available for configuration

### ISSUE THREAD

**Issue by allanlewis** [pypa/pipenv#5201]
### Issue description

The [Configuration With Environment Variables section of the documentation page Advanced Usage of Pipenv](https://pipenv.pypa.io/en/latest/advanced/#configuration-with-environment-variables) doesn't appear to list all the available environment variables

### Expected result

I expect variables such as `PIPENV_SPINNER` to be documented.

### Actual result

Only `PIPENV_HIDE_EMOJIS` is documented, along with some functions.

### Steps to replicate

n/a

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

n/a

**Comment by oz123** [comment]
Yes, that is true. We currently could use help here.

**Comment by Abdullium** [comment]
I can definitely fix this issue, assign it to me

**Comment by Abdullium** [comment]
> ### Issue description
> The [Configuration With Environment Variables section of the documentation page Advanced Usage of Pipenv](https://pipenv.pypa.io/en/latest/advanced/#configuration-with-environment-variables) doesn't appear to list all the available environment variables
> 
> ### Expected result
> I expect variables such as `PIPENV_SPINNER` to be documented.
> 
> ### Actual result
> Only `PIPENV_HIDE_EMOJIS` is documented, along with some functions.
> 
> ### Steps to replicate
> n/a
> 
> Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.
> 
> n/a

**Comment by Abdullium** [comment]
> ### Issue description
> The [Configuration With Environment Variables section of the documentation page Advanced Usage of Pipenv](https://pipenv.pypa.io/en/latest/advanced/#configuration-with-environment-variables) doesn't appear to list all the available environment variables
> 
> ### Expected result
> I expect variables such as `PIPENV_SPINNER` to be documented.
> 
> ### Actual result
> Only `PIPENV_HIDE_EMOJIS` is documented, along with some functions.
> 
> ### Steps to replicate
> n/a
> 
> Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.
> 
> n/a

so you want me to past the result in 
[pipenv](https://github.com/pypa/pipenv)/[docs](https://github.com/pypa/pipenv/tree/main/docs)/advanced.rst  

below or above the  PIPENV_HIDE_EMOJIS section.

**Comment by Abdullium** [comment]
> I can definitely fix this issue, assign it to me

Guys I have submitted the pull request, everything is crisp and clear all system environment are listed
