### ISSUE TITLE
ResourceWarning: unclosed `<ssl.SSLSocket...>`

### ISSUE THREAD

**Issue by smac89** [pypa/pipenv#5202]
### Issue description

Installing requirements from requirements file completes, but errors out briefly with a message

Command:
```
pipenv install --requirements ./requirements/requirements.in
```
## Requirements.in
```
O365
WeasyPrint
boto3
braintree
celery
django
django-allow-cidr
django-cors-headers
django-countries
django-filter
django-health-check
django-import-export ~= 2.8.0
django-object-actions
django-paranoid
django-phonenumber-field[phonenumbers]
django-redis
django-service-objects
django-simple-coupons @ git+https://github.com/vladtischenko/django-simple-coupons.git@ab27e7f90f17c3e3b6a2f9319d36e807710d025b
django-simple-history
django-storages
django-timezone-field
django_replicated
djangorestframework
facturama @ git+https://github.com/Facturama/facturama-python-sdk.git@master
firebase-admin
google-api-python-client
google-auth-httplib2
google-auth-oauthlib
graphene-django ~= 2.15.0
graphene-file-upload
hypercorn
jsonpickle
moto[s3]
paypal-checkout-serversdk @ git+https://github.com/gazi-md-hasnat-zahan/Checkout-Python-SDK.git@fe6102f56e08b492f73f6c5d7c9a5c5321766367
paypalhttp @ git+https://github.com/gazi-md-hasnat-zahan/paypalhttp_python.git@2f73547c888d8231c4dfbf9c8cdef57066841edb
pillow
psycopg2
pydyf @ git+https://github.com/gazi-md-hasnat-zahan/pydyf.git@65a60bdc06116b84b4694b9e8ec3aef1688c948d
python-magic
redis
sentry-sdk
slack_sdk
twilio
```

### Expected result

It worked apart from the warning that was shown

### Actual result

Worked with warnings:

> ResourceWarning: unclosed <ssl.SSLSocket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.16.1.234', 45580), raddr=('151.101.0.223', 443)>
return list(value)
ResourceWarning: Enable tracemalloc to get the object allocation tracebac

### Steps to replicate

Not really sure, I was just installing about 40 dependencies from requirements.txt

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

**Comment by matteius** [comment]
I noticed similar warnings in my tests recently.  I am wondering if you can try this with the `main` branch which as of the last night got some major improvements.  I suspect it may still be an issue though, as I didn't specifically change our usages of context processors.

**Comment by matteius** [comment]
New version of pipenv `2022.8.5` is out -- could this be rechecked against that?

**Comment by smac89** [comment]
@matteius well it seems to have no issues installing this time, but I'm not sure if anything was done in particular to address this issue

**Comment by matteius** [comment]
@smac89 I haven't seen these warnings in over a month -- I think there was something up with one of the prior versions of pip, perhaps `22.1.2`  (we are on latest 22.2.2 now) or maybe something else back in July causing this.   If we see this issue crop up again we can re-open or cut a new ticket, but at this time I am not sure of anything actionable for this.
