### ISSUE TITLE
Invalid version and will not be supported in a future release

### ISSUE THREAD

**Issue by kaykhan** [pypa/pipenv#5208]
When i run `pipenv shell` i get the following warning/error?

**pipenv shell**      
```
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Loading .env environment variables.
```

**python --version**                                                                                                                                  
Python 3.10.4

**OS**
Ubuntu 22.04

**Comment by matteius** [comment]
@kaykhan This issue has been reported from time to time, but unfortunately it is really challenging to figure out where pipenv could be invoking this from.   Could you try the main branch of pipenv  `pip install git+https://github.com/pypa/pipenv.git@main` and see if the error is still present?

**Comment by matteius** [comment]
Downgrading setuptools really should not be the answer.  It's just a warning, you can ignore it for now until it can be figured out.

**Comment by kaykhan** [comment]
> Downgrading setuptools really should not be the answer. It's just a warning, you can ignore it for now until it can be figured out.

Okay thank you, i will check back a later date and if theres anyting else i can do/try to help  let me know!

**Comment by kaykhan** [comment]
@matteius Upgraded pipenv for you, unfortunately i still get these errors/warnings

**1. pipenv --version**     

```
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
pipenv, version 2022.8.15
```

**2. pip install --upgrade pipenv**


**3. pipenv --version**
```

/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
pipenv, version 2022.8.24
```

**Comment by real-yfprojects** [comment]
The warning will show up even when entering the following:
```console
$ pipenv help
/home/yannick/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.13.1-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/home/yannick/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/yannick/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Usage: pipenv [OPTIONS] COMMAND [ARGS]...
Try 'pipenv -h' for help.

Error: No such command 'help'.

Did you mean one of these?
    shell
```

This means that the problem lies before or while parsing the cmd arguments.

**Comment by real-yfprojects** [comment]
The warning will show up even when entering the following:
```console
$ pipenv help
/home/user/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.13.1-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/home/user/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/user/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Usage: pipenv [OPTIONS] COMMAND [ARGS]...
Try 'pipenv -h' for help.

Error: No such command 'help'.

Did you mean one of these?
    shell
```

This means that the problem lies before or while parsing the cmd arguments.

**Comment by sepsallao** [comment]
I am using WSL2 Ubuntu 18.04

By just checking the version, I also get this error:

```
$ pipenv --version
/home/sep/.local/lib/python3.6/site-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: 0.18ubuntu0.18.04.1 is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
pipenv, version 2022.4.20
```

**Comment by matteius** [comment]
`2022.9.20` is released

**Comment by kaykhan** [comment]
Upgrading to this new version (2022.9.20) has resolved the problem for for me. thanks!

![Screenshot from 2022-09-21 12-46-59](https://user-images.githubusercontent.com/5202527/191496058-ef47f658-2282-46cc-91e2-06d35f9c1d50.png)

**Comment by fatraphael95** [comment]
I have just come across this issue mentioned by @kaykhan previously but for me, the issue is appearing on GitHub when I was trying to run a job. 

<img width="1404" alt="Screenshot 2023-01-16 at 3 31 57 AM" src="https://user-images.githubusercontent.com/50533288/212562995-a80d0048-5a28-432c-bf88-49b7af962577.png">

I have also tried including the "pip install git+https://github.com/pypa/pipenv.git@main" on the main branch (suggested by @matteius ) but unfortunately, I still face the same issue 😭

<img width="1077" alt="Screenshot 2023-01-16 at 3 34 24 AM" src="https://user-images.githubusercontent.com/50533288/212563180-73eb8b0f-cef3-4613-9f0b-a92663eb34d5.png">

Hope to know if anyone knows how to resolve this? 🙏🏻

**Comment by matteius** [comment]
@fatraphael95 that fix was released to pypi a while ago.  Is it possible you are invoking `pipenv` from an apt installed version?

**Comment by fatraphael95** [comment]
Hi @matteius, sorry I'm quite new to this and not quite sure what you mean by invoking `pipenv` from an apt installed version. Currently, I have sort of resolved the earlier issue by changing from setuptools==65.x.x to setuptools==66.0.0 and right now this is the current status whereby the "1.1build1" is an invalid version. 

<img width="1395" alt="Screenshot 2023-01-16 at 5 03 57 PM" src="https://user-images.githubusercontent.com/50533288/212639015-8130897f-e33c-4a3c-a269-664580f1f875.png">

**Comment by fatraphael95** [comment]
@matteius ohh i see and yes it was not the latest version. I have updated the requirement.txt file and it is working now. Thanks a lot for your kind help! :)
