### ISSUE TITLE
--no-site-packages argument is in help but not recognized

### ISSUE THREAD

**Issue by NFSpeedy** [pypa/pipenv#5246]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

Describe the issue briefly here.

### Expected result

Describe what you expected.

### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by matteius** [comment]
@NFSpeedy Did you mean to close this?

**Comment by NFSpeedy** [comment]
@matteius Yes, I figured it out. All arguments are accepted after the main command except some that have to be given before the command.
As in my case:
pipenv --no-site-packages sync --dev -v
It confused me, because -v, for example, is a global arg, and --no-site-packages should be the same in my mind.
