### ISSUE TITLE
pipenv lock -r no longer works

### ISSUE THREAD

**Issue by megamayoy** [pypa/pipenv#5253]
### Issue description
I installed Pipenv **2022.8.14**

we run ```pipenv lock -r > requirements.txt``` to generate output of the lockfile as per the documentation.

### Expected result

We expect the creation of requirements.txt file with dependencies information.

### Actual result
```Error: No such option: -r```

**Comment by megamayoy** [comment]
I see that it's replaced by ```pipenv requirements > requirements.txt``` but in this [section](https://pipenv.pypa.io/en/latest/basics/#pipfile-lock-security-features) of the documentation, it says it's working . I think it should be removed from the documentation.

**Comment by rafasimionato** [comment]
Maybe the error message could state something like "replaced/deprecated by **pipenv requirements**"
