### ISSUE TITLE
"The Python interpreter can't be found" error when running `pipenv install --system` with a python3 but no python

### ISSUE THREAD

**Issue by jfly** [pypa/pipenv#5261]
### Issue description

I get a "The Python interpreter can't be found" error when running `pipenv install --system` with a python3 but no python.

Demo:

```
$ docker run $(docker build -q -f Dockerfile.pipenv-2022.8.15 https://github.com/jfly/2022-08-16-pipenv-system-which-issue.git#main)
Installing dependencies from Pipfile.lock (63bec0)...
The Python interpreter can't be found.▉ 0/4 — 00:00:00
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/4 — 00:00:00
```

I'm confident this bug was introduced in https://github.com/pypa/pipenv/commit/f276360dfcef3200908e2c6569567d617919c63d, which removed a usage of `first()`, but broke the "filter None values" behavior that `first()` gave us.

**Comment by schuberttobias** [comment]
Thanks for your report.

I am also running into this problem with python3.8 and pipenv==2022.8.15 .
