### ISSUE TITLE
How can i pin some (or all) packages from --site-packages to not beeing overwritten in user env

### ISSUE THREAD

**Issue by wuxxin** [pypa/pipenv#5264]
use case:

+ install a specific hardware version of a python package from source, eg. 
   + https://aur.archlinux.org/packages/python-jax-rocm
   + this package has wheels for hardware support of amd rocm gpus.

+ make a new environment with pipenv, and parse requirements from other sources into it
+ other sources may depend on a different version of jax, but may work on the system compiled

question:

+ how can i assure that the --site-packages version of jax is used in dependency resolution ?

Currently i try to pin it in Pipfile by using jax="=3.6.1" by looking at the current system version, and hope pipenv does not overwrite it.

Is there another way to pin system packages in an pipenv environment ?

**Comment by matteius** [comment]
pipenv `2022.8.17` is released
