### ISSUE TITLE
--ignore-installed should not be used by default ( at least when --site-packages is used )

### ISSUE THREAD

**Issue by b3nder2016** [pypa/pipenv#5265]
### Issue description

--ignore-installed is used by default in the release 2022.8.15 

### Expected result
--ignore-installed should not be used by default. At least it should not be used together with the flag --site-packages

I tried to use PIP_IGNORE_INSTALLED=0, but it didn't help

here is the log snippet:

```
$HOME/.venv/bin/python /usr/local/lib/python3.8/dist-packages/pipenv/patched/pip/__pip-runner__.py install --ignore-installed --verbose --upgrade --require-hashes --no-deps --exists-action=i -r /tmp/pipenv-vps3t34b-requirements/pipenv-pck_y0xm-requirement.txt -i https://pypi.org/simple
Using source directory: '$HOME/.venv/src'
Writing supplied requirement line to temporary file: "ruamel.yaml==0.17.21; python_version >= '3' --hash=sha256:8b7ce697a2f212752a35c1ac414471dc16c424c9573be4926b56ff3f5d23b7af --hash=sha256:742b35d3d665023981bd6d16b3d24248ce5df75fdb4e2924e93a05c1f8b61ca7"
Installing 'ruamel.yaml'
```

**Comment by matteius** [comment]
Can you explain the problem you have with `--ignore-installed`?  It was applied to fix the case where vendor'd pip was skipping package installations for things that are in the site-packages.   I don't see where `--site-packages` is being used in your example.   Even when `--ignore-installed` is supplied, pipenv doesn't reinstall packages that it has already installed.  Basically I need more context to try and make sense of this issue.

**Comment by b3nder2016** [comment]
I use the following line to install packages from the Pipfile.lock: `pipenv install --site-packages --ignore-pipfile --verbose`
I want to reuse the python packages installed in the system. For example, I want to reuse GDAL library installed on the system in my venv. Basically, when I try to install the dependencies using the command above pipenv ignores GDAL from the system and is trying to recompile it which is very time consuming and needs even more dependencies in the venv such as c++ compiler and libraries.  There might be other use-cases when heavy packages from the system need to be reused.

**Comment by matteius** [comment]
Thanks for the context @b3nder2016  -- I revisited the original issue of why `--ignore-installed` got added as a workaround, and I think I just solved for it in a new PR but I need to rewrite the patch file and add a news fragment, etc yet.

**Comment by matteius** [comment]
pipenv `2022.8.17` is released
