### ISSUE TITLE
Lock file cannot be applied > v2022.08.05

### ISSUE THREAD

**Issue by Berbe** [pypa/pipenv#5269]
### Issue description
A `Pipfile.lock` lock file used to guarantee a deterministic environment started to fail with version `2022.08.13` of ``pipenv``.
It works as expected with `2022.08.05`.

### Expected result
Lock file to work as expected, like it did < v`2022.08.13`

### Actual result
Messages like what follows appear:
```console
An error occurred while installing py==1.11.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4' --hash=sha256:607c53218732647dff4acdfcd50cb62615cedf612e72d1724fb1a0cc6405b378 --hash=sha256:51c75c4126074b472f746a24399ad32f6053d1b34b68d2fa41e558e6f4a98719! Will try again.
```

### Steps to replicate
1. `pipenv sync` based on `Pipfile.lock`

**Comment by matteius** [comment]
Works fine for me, please provide a reproduction example.

**Comment by apamildner** [comment]
Also having this issue. Locked pipenv version to version `2022.08.05` and it worked again. Unable to reproduce a simple example as well, but our build started working again with the only difference was to lock the version of `pipenv`. Running python `3.9` on an `ubuntu 18.04`.

**Comment by matteius** [comment]
Have you tried the new version that was released today `pipenv==2022.8.17`?

One difference is we rely on the vendor'd pip for installations now whereas in `2022.08.05` it invoked the system installed pip.  That shouldn't change the hashes involved though -- are you using a private pypi server at all in your project?

**Comment by matteius** [comment]
@apamildner That syntax error on `pip/__pip-runner__.py` -- doesn't make much sense, that is unmodified pip code.  What is your system `pip --version`?  Pipenv is using `pip=22.2.2`

**Comment by apamildner** [comment]
The pip version is `22.2.2`. We do use a private pypi server though, so maybe that has something to do with it?

**Comment by matteius** [comment]
@apamildner I am not sure because what you shared is a syntax error parsing the same version of pip you say is on the system.  I wonder if despite the path saying python3.9, if pipenv is finding a lower version of python and trying to run with that in the newer version of pipenv.   Could you see if you can make any determination around that?

**Comment by matteius** [comment]
Can this be rechecked with `pipenv==2022.8.24`?

**Comment by Berbe** [comment]
Lock file had to be regenerated.
