### ISSUE TITLE
pipenv-README seems cluttered at "Usage"

### ISSUE THREAD

**Issue by dshah244** [pypa/pipenv#5280]
**Bugfix: Documentation**

I consider this issue as a Bug as nothing needs to be changed within the content of the README file.

### Issue description

There are two stages within the README file where the content seems to be a bit cluttered. These can also be seen within the attached images. It seems that the content is not being rendered properly.

# 1
![image](https://user-images.githubusercontent.com/8057610/185968382-99130ff2-3055-484d-9dcf-581b7b7c2d5e.png)

# 2
![image](https://user-images.githubusercontent.com/8057610/185968468-5d99f39a-447c-42c6-8ac2-16c910f9d9d8.png)

### Expected result

I at least expect the CLI parameters to be mentioned as a list, with each one present in a new line.

### Actual result

Neat and de-cluttered text rendered properly and presenting the various CLI options of pipenv.

### Steps to replicate

It's visible in the "main" branch of the repository.

**Comment by oz123** [comment]
Thanks!
