### ISSUE TITLE
Release 2022.8.31 introduced issues with the install command

### ISSUE THREAD

**Issue by CoburnJoe** [pypa/pipenv#5332]
Hi! I have a large number of codebases using Pipenv, and _some_ (not all) are failing to install dependencies.

**Python version:** 3.8
**Pipenv version:** 2022.8.31, 2022.9.2, 2022.9.4.  
**Pip version:** Latest - 22.2.2

**Error snippet:**

```An error occurred while installing attrs==21.4.0;
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Collecting attrs==21.4.0

× python [setup.py](http://setup.py/) egg_info did not run successfully.
[pipenv.exceptions.InstallError]:   │ exit code: 1
[pipenv.exceptions.InstallError]:   ╰─> [153 lines of output]
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:           No working compiler found, or bogus compiler options passed to
[pipenv.exceptions.InstallError]:           the compiler from Python's standard "distutils" module.  See
[pipenv.exceptions.InstallError]:           the error messages above.  Likely, the problem is not related
[pipenv.exceptions.InstallError]:           to CFFI but generic to the [setup.py](http://setup.py/) of any Python package that
[pipenv.exceptions.InstallError]:           tries to compile C code.  (Hints: on OS/X 10.8, for errors about
[pipenv.exceptions.InstallError]:           -mno-fused-madd see http://stackoverflow.com/questions/22313407/
[pipenv.exceptions.InstallError]:           Otherwise, see https://wiki.python.org/moin/CompLangPython or
[pipenv.exceptions.InstallError]:           the IRC channel #python on irc.libera.chat.)
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:           Trying to continue anyway.  If you are trying to install CFFI from
[pipenv.exceptions.InstallError]:           a build done in a different context, you can ignore this warning.
[pipenv.exceptions.InstallError]:       
[pipenv.exceptions.InstallError]:       warning: build_py: byte-compiling is disabled, skipping.
[pipenv.exceptions.InstallError]:
```

^ this happens for every dependency, but I do know that Pipenv version 2022.8.31 appears to have introduced the issue, and it is still present in all subsequent releases.

I have ran builds with multiple previous versions of Pipenv, all of which work fine: 

- 2022.1.8 works
- 2022.4.8 works
- 2022.7.4 works
- 2022.8.15 works
- 2022.8.17 works
- 2022.8.19 works
- 2022.8.24 works
- 2022.8.30 works

I'm not sure why only some projects have this issue, but I do know the only change to make the builds fail is upgrading Pipenv...

😃

**Comment by matteius** [comment]
@CoburnJoe I have two theories, if they are both wrong I am going to need more information -- one is can you try `2022.9.4` -- the other is that you have a dependency in your install chain that this setup.py depends on, in which case you'll want to run `pipenv run pip install <dependency>` ahead of the `pipenv sync` or `pipenv install --deploy` command--you may have been getting lucky before when dependencies were installed serially that it was available by the time this `setup.py` was invoked.   The error seems to indicate something is missing causing a setup.py invocation to fail.  We saw a different issue where a user needed to pre-install `six` this way as a workaround for when setup.py requires one of the other installed dependencies, because batch install will not get lucky anymore, it installs in typically 1, at most 2 pip invocations in order to cut the install times in half:  #5319   Inspect the setup.py of that project/specifier for what it imports or does to install, to get a better idea of what might be going on.

**Comment by CoburnJoe** [comment]
> @CoburnJoe I have two theories, if they are both wrong I am going to need more information -- one is can you try `2022.9.4` -- the other is that you have a dependency in your install chain that this setup.py depends on, in which case you'll want to run `pipenv run pip install <dependency>` ahead of the `pipenv sync` or `pipenv install --deploy` command--you may have been getting lucky before when dependencies were installed individually, that it was available by the time this `setup.py` was invoked. The error seems to indicate something is missing causing a setup.py invocation to fail. We saw a different issue where a user needed to pre-install `six` this way as a workaround for when setup.py requires one of the other installed dependencies, because batch install will not get lucky anymore, it installs in typically 1, at most 2 pip invocations in order to cut the install times in half: #5319 Inspect the setup.py of that project/specifier for what it imports or does to install, to get a better idea of what might be going on.

Thanks for the reply - I've tried `2022.9.4` (all releases since the "working" release - 2022.8.31, 2022.9.2, 2022.9.4) with no change.

I think your second suggestion is the most likely answer - I'll report back ASAP - but this may take me some time to track down.

**Comment by CoburnJoe** [comment]
@matteius I'm now certain this is as you described, and basically the same as #5319 - i.e. not a problem you need to solve with Pipenv - closing now, thanks so much for your quick reply!
