### ISSUE TITLE
Error running pipenv install with latest pip22.2.2 and pipenv2022.9.8  

### ISSUE THREAD

**Issue by kumarkeshav021** [pypa/pipenv#5358]
Error : `jenkins@dev-7bbcx:~/jenkins-manager$ pipenv install
Installing dependencies from Pipfile.lock (307a86)...
An error occurred while installing -e .! Will try again.
An error occurred while installing -e git+ssh://git@*******/tf-runner.git@d8b9c97b01bfa8a5820d94d5fd66caca7a04ae1d#egg=tf-runner! Will try again.
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Obtaining file:///home/jenkins/agent/jenkins-manager (from -r /tmp/pipenv-pfm6jtf2-requirements/pipenv-cp2i1dqi-reqs.txt (line 1))
[pipenv.exceptions.InstallError]:   Installing build dependencies: started
[pipenv.exceptions.InstallError]:   Installing build dependencies: finished with status 'done'
[pipenv.exceptions.InstallError]:   Checking if build backend supports build_editable: started
[pipenv.exceptions.InstallError]:   Checking if build backend supports build_editable: finished with status 'done'
[pipenv.exceptions.InstallError]:   Getting requirements to build editable: started
[pipenv.exceptions.InstallError]:   Getting requirements to build editable: finished with status 'error'
[pipenv.exceptions.InstallError]: error: subprocess-exited-with-error
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   × Getting requirements to build editable did not run successfully.
[pipenv.exceptions.InstallError]:   │ exit code: 1
[pipenv.exceptions.InstallError]:   ╰─> [23 lines of output]
[pipenv.exceptions.InstallError]:       Traceback (most recent call last):
[pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.9/dist-packages/pipenv/patched/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
[pipenv.exceptions.InstallError]:           main()
[pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.9/dist-packages/pipenv/patched/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
[pipenv.exceptions.InstallError]:           json_out['return_val'] = hook(**hook_input['kwargs'])
[pipenv.exceptions.InstallError]:         File "/usr/local/lib/python3.9/dist-packages/pipenv/patched/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
[pipenv.exceptions.InstallError]:           return hook(config_settings)
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-3la62mdh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 445, in get_requires_for_build_editable
[pipenv.exceptions.InstallError]:           return self.get_requires_for_build_wheel(config_settings)
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-3la62mdh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
[pipenv.exceptions.InstallError]:           return self._get_build_requires(config_settings, requirements=['wheel'])
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-3la62mdh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
[pipenv.exceptions.InstallError]:           self.run_setup()
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-3la62mdh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 482, in run_setup
[pipenv.exceptions.InstallError]:           super(_BuildMetaLegacyBackend,
[pipenv.exceptions.InstallError]:         File "/tmp/pip-build-env-3la62mdh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
[pipenv.exceptions.InstallError]:           exec(code, locals())
[pipenv.exceptions.InstallError]:         File "<string>", line 2, in <module>
[pipenv.exceptions.InstallError]:         File "/home/jenkins/agent/jenkins-manager/jenkins_manager/__init__.py", line 2, in <module>
[pipenv.exceptions.InstallError]:           from .cli import jenkins_manager
[pipenv.exceptions.InstallError]:         File "/home/jenkins/agent/jenkins-manager/jenkins_manager/cli.py", line 1, in <module>
[pipenv.exceptions.InstallError]:           import click
[pipenv.exceptions.InstallError]:       ModuleNotFoundError: No module named 'click'
[pipenv.exceptions.InstallError]:       [end of output]
[pipenv.exceptions.InstallError]:   
[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.
[pipenv.exceptions.InstallError]: error: subprocess-exited-with-error
[pipenv.exceptions.InstallError]: 
[pipenv.exceptions.InstallError]: × Getting requirements to build editable did not run successfully.
[pipenv.exceptions.InstallError]: │ exit code: 1
[pipenv.exceptions.InstallError]: ╰─> See above for output.
[pipenv.exceptions.InstallError]: 
[pipenv.exceptions.InstallError]: note: This error originates from a subprocess, and is likely not a problem with pip.`

pipenv is working fine with pipenv 22.7.24 and pip 22.2.1. 

As i run with --verbose on both side i got different ouput. latest pipenv tries to install editable first and fails
pipenv install --verbose # on pipenv 22.7.24
jenkins@dev-9990d:~/jenkins-manager$ pipenv install --verbose
Using python: None
Path to python: /usr/bin/python3
Creating a virtualenv for this project...
Pipfile: /home/jenkins/agent/jenkins-manager/Pipfile
Using /usr/bin/python3 (3.9.2) to create virtualenv...
⠇ Creating virtual environment...created virtual environment CPython3.9.2.final.0-64 in 547ms
  creator CPython3Posix(dest=/home/jenkins/agent/.local/share/virtualenvs/jenkins-manager-0rarv__h, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/jenkins/agent/.local/share/virtualenv)
    added seed packages: pip==22.2, setuptools==63.2.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/jenkins/agent/.local/share/virtualenvs/jenkins-manager-0rarv__h
Installing dependencies from Pipfile.lock (307a86)...
Writing supplied requirement line to temporary file: 'aiohttp==3.7.4.post0 --hash=sha256:17c073de315745a1510393a96e680d20af8e67e324f70b42accbd4cb3315c9fb --hash=sha256:547da6cacac20666422d4882cfcd51298d45f7ccb60a04ec27424d2f36ba3eaf --hash=sha256:bdb230b4943891321e06fc7def63c7aace16095be7d9cf3b1e01be2f10fba439 --hash=sha256:64322071e046020e8797117b3658b9c2f80e3267daec409b350b6a7a05041213 --hash=sha256:a00bb73540af068ca7390e636c01cbc4f644961896fa9363154ff43fd37af2f5 --hash=sha256:0563c1b3826945eecd62186f3f5c7d31abb7391fedc893b7e2b26303b5a9f3fe --hash=sha256:79ebfc238612123a713a457d92afb4096e2148be17df6c50fb9bf7a81c2f8013 --hash=sha256:4b302b45040890cea949ad092479e01ba25911a15e648429c7c5aae9650c67a8 --hash=sha256:e4b2b334e68b18ac9817d828ba44d8fcb391f6acb398bcc5062b14b2cbeac970 --hash=sha256:f881853d2643a29e643609da57b96d5f9c9b93f62429dcc1cbb413c7d07f0e1a --hash=sha256:fe60131d21b31fd1a14bd43e6bb88256f69dfc3188b3a89d736d6c71ed43ec95 --hash=sha256:932bb1ea39a54e9ea27fc9232163059a0b8855256f4052e776357ad9add6f1c9 --hash=sha256:493d3299ebe5f5a7c66b9819eacdcfbbaaf1a8e84911ddffcdc48888497afecf --hash=sha256:3d78619672183be860b96ed96f533046ec97ca067fd46ac1f6a09cd9b7484287 --hash=sha256:f705e12750171c0ab4ef2a3c76b9a4024a62c4103e3a55dd6f99265b9bc6fcfc --hash=sha256:114b281e4d68302a324dd33abb04778e8557d88947875cbf4e842c2c01a030c5 --hash=sha256:d9e13b33afd39ddeb377eff2c1c4f00544e191e1d1dee5b6c51ddee8ea6f0cf5 --hash=sha256:cffe3ab27871bc3ea47df5d8f7013945712c46a3cc5a95b6bee15887f1675c22 --hash=sha256:7b18b97cf8ee5452fa5f4e3af95d01d84d86d32c5e2bfa260cf041749d66360b --hash=sha256:209b4a8ee987eccc91e2bd3ac36adee0e53a5970b8ac52c273f7f8fd4872c94c --hash=sha256:02f46fc0e3c5ac58b80d4d56eb0a7c7d97fcef69ace9326289fb9f1955e65cfe --hash=sha256:15492a6368d985b76a2a5fdd2166cddfea5d24e69eefed4630cbaae5c81d89bd --hash=sha256:a5ca29ee66f8343ed336816c553e82d6cade48a3ad702b9ffa6125d187e2dedb --hash=sha256:14762875b22d0055f05d12abc7f7d61d5fd4fe4642ce1a249abdf8c700bf1fd8 --hash=sha256:3cf75f7cdc2397ed4442594b935a11ed5569961333d49b7539ea741be2cc79d5 --hash=sha256:2e19413bf84934d651344783c9f5e22dee452e251cfd220ebadbed2d9931dbf0 --hash=sha256:c6e9dcb4cb338d91a73f178d866d051efe7c62a7166653a91e7d9fb18274058f --hash=sha256:e54962802d4b8b18b6207d4a927032826af39395a3bd9196a5af43fc4e60b009 --hash=sha256:bb437315738aa441251214dad17428cafda9cdc9729499f1d6001748e1d432f4 --hash=sha256:5df68496d19f849921f05f14f31bd6ef53ad4b00245da3195048c69934521809 --hash=sha256:7615dab56bb07bff74bc865307aeb89a8bfd9941d2ef9d817b9436da3a0ea54f --hash=sha256:515dfef7f869a0feb2afee66b957cc7bbe9ad0cdee45aec7fdc623f4ecd4fb16 --hash=sha256:393f389841e8f2dfc86f774ad22f00923fdee66d238af89b70ea314c4aefd290 --hash=sha256:af9aa9ef5ba1fd5b8c948bb11f44891968ab30356d65fd0cc6707d989cd521df --hash=sha256:230a8f7e24298dea47659251abc0fd8b3c4e38a664c59d4b89cca7f6c09c9e87 --hash=sha256:d012ad7911653a906425d8473a1465caa9f8dea7fcf07b6d870397b774ea7c0f --hash=sha256:40eced07f07a9e60e825554a31f923e8d3997cfc7fb31dbc1328c70826e04cde'
Installing 'aiohttp'
$ /home/jenkins/agent/.local/share/virtualenvs/jenkins-manager-0rarv__h/bin/python -m pip install --verbose --upgrade --require-hashes --no-deps --exists-action=i -r /tmp/pipenv-owgehjpk-requirements/pipenv-sb7ygo9d-requirement.txt -i https://pypi.org/simple

pipenv install --verbose # pipenv 2022.9.8
jenkins@dev-7bbcx:~/jenkins-manager$ pipenv install --verbose
Installing dependencies from Pipfile.lock (307a86)...
Writing supplied requirement line to temporary file: '-e .'
Writing supplied requirement line to temporary file: '-e git+ssh://git@******.git@d8b9c97b01bfa8a5820d94d5fd66caca7a04ae1d#egg=tf-runner'
Install Phase: Editable Requirements
Preparing Installation of 'jenkins-manager'
Preparing Installation of 'tf-runner'
$ /home/jenkins/agent/.local/share/virtualenvs/jenkins-manager-0rarv__h/bin/python /usr/local/lib/python3.9/dist-packages/pipenv/patched/pip/__pip-runner__.py install -i https://pypi.org/simple --no-input --upgrade --no-deps --exists-action=i -r /tmp/pipenv-87e1gw0m-requirements/pipenv-m3u729j7-reqs.txt
Using source directory: '/home/jenkins/agent/.local/share/virtualenvs/jenkins-manager-0rarv__h/src'
Obtaining file:///home/jenkins/agent/jenkins-manager (from -r /tmp/pipenv-87e1gw0m-requirements/pipenv-m3u729j7-reqs.txt (line 1))

  Installing build dependencies: started

  Installing build dependencies: finished with status 'done'

  Checking if build backend supports build_editable: started

  Checking if build backend supports build_editable: finished with status 'done'

  Getting requirements to build editable: started

  Getting requirements to build editable: finished with status 'error'

error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/dist-packages/pipenv/patched/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/lib/python3.9/dist-packages/pipenv/patched/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.9/dist-packages/pipenv/patched/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-bwz8x1is/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 445, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-bwz8x1is/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-bwz8x1is/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-bwz8x1is/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 482, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-bwz8x1is/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
        File "/home/jenkins/agent/jenkins-manager/jenkins_manager/__init__.py", line 2, in <module>
          from .cli import jenkins_manager
        File "/home/jenkins/agent/jenkins-manager/jenkins_manager/cli.py", line 1, in <module>
          import click
      ModuleNotFoundError: No module named 'click'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by matteius** [comment]
@kumarkeshav021 It looks like one of your setup.py depends on `click` and so it has to be installed ahead of the other install.  This is similar to #5344 #5332 #5319

**Comment by matteius** [comment]
Named package categories feature has been released and, so now it should be possible to `pipenv install click --categories=prereq` and then change your install phase to something like `pipenv install --deploy --categories="prereq packages"`.

Closing this out for now since we haven't heard back from you.
