### ISSUE TITLE
Command Ls pops up pipefile.lock I want to change that but dont know how

### ISSUE THREAD

**Issue by xahver** [pypa/pipenv#5378]
![Screenshot 2022-09-30 063052](https://user-images.githubusercontent.com/102440646/193251393-b79bace7-e781-4abe-8852-792300cc8193.png)
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

Describe the issue briefly here.

### Expected result

Describe what you expected.

### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by xahver** [comment]
Currently in appacademy and where doing basic navigation and I cant seem to use this command without this pipfile.lock coming up anyway anyone can help me with this.

**Comment by matteius** [comment]
@xahver The Pipfile.lock is what actually stores the resolved dependencies.  It is an important file that you'll want to keep around.

**Comment by xahver** [comment]
Oh wait Matt its you again. I was trying to type in ls which was supposed to list my folders and files but it didn't do you know how I can get it to list it because all its popping up is that

**Comment by xahver** [comment]
So like Im still having issues with this pls help :(

**Comment by matteius** [comment]
@xahver `ls` simply lists what files/directories are present in your working directory which can be printed with `pwd`.   If you wanted to print the contents of the file you could `cat` it -- example: `cat Pipfile.lock`.   These are basic linux commands which is outside of the scope of pipenv.   Is there a specific pipenv thing you are trying to accomplish?

**Comment by xahver** [comment]
I was just a little confused because Im watching a tutorial on setting up this system so I can continue with learning code at appacademy and there saying ls supposed to list those files but its not. Its just popping up Pipfile.lock so I didnt know if something went wrong or what

**Comment by xahver** [comment]
If is pops up pipfile.lock does that mean everything is fine? If so why isn't it popping up the directories?

**Comment by matteius** [comment]
@xahver What kind of directories are you expecting? Is there also a `Pipfile` in addition to the `Pipfile.lock`?  If you made a project directory and ran pipenv to create a lock file then what you see may make sense.   Pipenv generally not create directories in the project directory -- so you may have to explain more which directory you are looking for.

**Comment by xahver** [comment]
I was expecting it to look like this 
![Uploading Screenshot 2022-10-04 191527.png…]()

Instead I got something like this 

![Screenshot 2022-10-04 191623](https://user-images.githubusercontent.com/102440646/193947734-c7b91636-031a-4a73-85af-5dda8f28c570.png)

**Comment by xahver** [comment]
I havent explored or done anything with the terminal so far. Oh yeah a pipfile also pops up alongside pipfile.lock

**Comment by xahver** [comment]
All ive done so far is set up the terminal and ran the checker and everything checked out there but then theres this

**Comment by matteius** [comment]
@xahver That screenshot is just showing a listing of that user's files on their Desktop -- nothing to do with pipenv and I would expect your filesystem to look different anyway.   What exactly are you trying to do?

**Comment by xahver** [comment]
No lol Im sorry I don't think I'm being clear. Ok so we type in the panel ls right is it normal for it to popup with just pipfile and pipfil.lock I was just curious because in the presenters video shes showing all these files and directories that my terminal isnt showing.

**Comment by matteius** [comment]
@xahver I think it is fine.  So what is your path when you type `pwd`?   If you change to you home directory using `cd ~` do you see additional files when you do an `ls`?

**Comment by xahver** [comment]
Sorry for the late respond I had a last minute school assignment to do but here I took another screenshot
![Screenshot 2022-10-04 224954](https://user-images.githubusercontent.com/102440646/193970741-5aa10365-8e7c-4867-8697-2d8d785fba7a.png)

**Comment by matteius** [comment]
@xahver So your home directory is empty, probably a fresh install of WSL.  That's fine.   I recommend not having your pipenv project be your home directory though.    run `pipenv --rm` there to be sure, and create a new directory, perhaps call it projects.  `mkdir projects` -- then `cd projects` and create another directory for the project you want to work on -- run pipenv commands in that directory.

**Comment by xahver** [comment]
![Screenshot 2022-10-04 230253](https://user-images.githubusercontent.com/102440646/193972002-9b563842-c5f6-40f4-bd02-550c13166350.png)

**Comment by xahver** [comment]
like this right

**Comment by xahver** [comment]
I think Im getting it now so I just didnt have the libraries because its a fresh install smh jeez I wish they explained that in the video

**Comment by matteius** [comment]
Its ok @xahver  -- you'll figure it out in time, just keep at it.
