### ISSUE TITLE
Add support for multiple categories in exported requirements

### ISSUE THREAD

**Issue by oz123** [pypa/pipenv#5397]
Now that Pipfile supports multiple categories, it would be nice if I could create different requirements files for these categories.
Let's say my Pipfile has categoires: tests, documentation, foo, bar.
I would like to create the following files: requirements-tests.txt, requirements-documentation.txt, requirements-foo.txt and requirements-bar.txt.

I would like to export them with:
```
pipenv requirements --category tests > requirements-tests.txt
```

And so on ...

However, right now only these options are supported:

```
 $ pipenv requirements -h
Usage: pipenv requirements [OPTIONS]

Options:
  --dev              Also add development requirements.
  --dev-only         Only add development requirements.
  --hash             Add package hashes.
  --exclude-markers  Exclude markers.
  -h, --help         Show this message and exit.
```

**Comment by BAllbeeDHI** [comment]
I would find this immensely helpful as well.

**Comment by dojutsu-user** [comment]
HI @oz123,
I would like to take this up. First time here, can you help me on how to start with this?

**Comment by oz123** [comment]
I would start with the following:

Add the command line options.
Look where this leads you inside pipenv. 
You'll bump into a library we maintain called requirementslib that does the real work of parsing Pipfile. Change the code here. 
One your prototype works, you'll need (probably) to open a PR in requirementslib.
It's probably not a good first issue. But you can try 💪

**Comment by dojutsu-user** [comment]
Sure.. would like to give a try.

**Comment by dojutsu-user** [comment]
HI @oz123,
Raised a PR with probable fix. Can you please check it once if the approach looks fine to you.

**Comment by BAllbeeDHI** [comment]
Thank you for taking that on, @dojutsu-user — Looking forward to having that capability as soon as it's released. :-D
