### ISSUE TITLE
pipenv fails to generate lock file for flask 2.0.1 and 2.1.1 even when using tilde operator

### ISSUE THREAD

**Issue by vishal180618** [pypa/pipenv#5428]
### Discussed in https://github.com/pypa/pipenv/discussions/5425

<div type='discussions-op-text'>

<sup>Originally posted by **vishal180618** October 20, 2022</sup>
Problem: even though I've used `~` in dependency and both flask versions are changed in minor versions so it should be able to generate `Pipfile.lock ` using `pipenv lock`.

difference bw the pipfile.lock generated individually for both flask versions: https://www.diffchecker.com/GngEExsR  

Error:
```
CRITICAL:pipenv.patched.notpip._internal.resolution.resolvelib.factory:Cannot install flask~=2.0.1 and flask~=2.1.1 because these package versions have conflicting dependencies.
```

Pipfile:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "~=2.0.1"
abcdef = {ref = "1.1.0", git = "https://***@github.com/abcdef-Utilities.git"}

[dev-packages]


[requires]
python_version = "3.7"
```
abcdef has flask ~=2.1.1 in setup.py

</div>

**Comment by vishal180618** [comment]
the same thing happened today for mock.

`CRITICAL:pipenv.patched.notpip._internal.resolution.resolvelib.factory:Cannot install mock~=1.2.0 and mock~=1.3.0 because these package versions have conflicting dependencies.`
Although their `setup.py` for both versions is exactly the same.

**Comment by matteius** [comment]
@vishal180618 Please see:  https://stackoverflow.com/questions/39590187/in-requirements-txt-what-does-tilde-equals-mean

So what does flask = "~=2.0.1"
It means it will select the latest version of the package, greater than or equal to 2.0.1, but still in the 2.0.* version, so it won't download 2.1.1 for example.  So having `flask = "~=2.1.1"` and flask = "~=2.0.1" together is in fact incompatible and will not resolve, pip is correct.
