### ISSUE TITLE
backup branch when backup not exists

### ISSUE THREAD

**Issue by gils-di** [pypa/pipenv#5439]
I want to move to use github instead of hard coded version, like the example below:
pinax = { git = "https://github.com/pinax/pinax.git", ref = "<branch_name>" }

in there a way to use repo default branch in case the branch on exsits?
if this case failed:
pinax = { git = "https://github.com/pinax/pinax.git", ref = "branch_name" }
i would like to to use:
pinax = { git = "https://github.com/pinax/pinax.git", ref = "main" }

**Comment by matteius** [comment]
There is not currently a way to do this.
