### ISSUE TITLE
Generating metadata for package public-repo produced metadata for project name main.

### ISSUE THREAD

**Issue by cikay** [pypa/pipenv#5445]
I am trying to install directly from GitHub by the following command

```
pipenv install -e git+https://github.com/cikay/public_repo.git@main#egg=public_repo
```

I got 
```
  WARNING: Generating metadata for package public-repo produced metadata for project name main. Fix your #egg=public-repo fragments.
Discarding git+https://github.com/cikay/public_repo.git#egg=public-repo: Requested main from git+https://github.com/cikay/public_repo.git#egg=public-repo has inconsistent name: expected 'public-repo', but metadata has 'main'
ERROR: Could not find a version that satisfies the requirement public-repo (unavailable) (from versions: none)
ERROR: No matching distribution found for public-repo (unavailable)
```

When I specify `egg=main` It installs. Why I have to specify package name as the same with the branch name?

**Comment by matteius** [comment]
@cikay -- when I specify `egg=main` it still fails to install -- I think there may be a lack of definition in your setup.py.

```
Installing git+https://github.com/cikay/public_repo.git@main#egg=main...
Error:  An error occurred while installing git+https://github.com/cikay/public_repo.git@main#egg=main!
Error text: Collecting main
  Cloning https://github.com/cikay/public_repo.git (to revision main) to /tmp/pip-install-h3lj2prs/main_c172edfdf71e40fc8b3841b384504f4d
  Resolved https://github.com/cikay/public_repo.git to commit c4551dea1dff89b6871f08ca0fa983e8edaceebf
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Discarding git+https://github.com/cikay/public_repo.git@main#egg=main: Requested selam from git+https://github.com/cikay/public_repo.git@main#egg=main (from -r /tmp/pipenv-jal8ru1h-requirements/pipenv-lgqqhdqa-requirement.txt (line 1)) has inconsistent name: expected 'main', but metadata has 'selam'

  Running command git clone --filter=blob:none --quiet https://github.com/cikay/public_repo.git /tmp/pip-install-h3lj2prs/main_c172edfdf71e40fc8b3841b384504f4d
  WARNING: Generating metadata for package main produced metadata for project name selam. Fix your #egg=main fragments.
ERROR: Could not find a version that satisfies the requirement main (unavailable) (from versions: none)
ERROR: No matching distribution found for main (unavailable)

✘ Installation Failed 
```

**Comment by cikay** [comment]
> @cikay -- when I specify `egg=main` it still fails to install -- I think there may be a lack of definition in your setup.py.
> 
> ```
> Installing git+https://github.com/cikay/public_repo.git@main#egg=main...
> Error:  An error occurred while installing git+https://github.com/cikay/public_repo.git@main#egg=main!
> Error text: Collecting main
>   Cloning https://github.com/cikay/public_repo.git (to revision main) to /tmp/pip-install-h3lj2prs/main_c172edfdf71e40fc8b3841b384504f4d
>   Resolved https://github.com/cikay/public_repo.git to commit c4551dea1dff89b6871f08ca0fa983e8edaceebf
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'done'
> Discarding git+https://github.com/cikay/public_repo.git@main#egg=main: Requested selam from git+https://github.com/cikay/public_repo.git@main#egg=main (from -r /tmp/pipenv-jal8ru1h-requirements/pipenv-lgqqhdqa-requirement.txt (line 1)) has inconsistent name: expected 'main', but metadata has 'selam'
> 
>   Running command git clone --filter=blob:none --quiet https://github.com/cikay/public_repo.git /tmp/pip-install-h3lj2prs/main_c172edfdf71e40fc8b3841b384504f4d
>   WARNING: Generating metadata for package main produced metadata for project name selam. Fix your #egg=main fragments.
> ERROR: Could not find a version that satisfies the requirement main (unavailable) (from versions: none)
> ERROR: No matching distribution found for main (unavailable)
> 
> ✘ Installation Failed 
> ```

What kind of lack?

**Comment by cikay** [comment]
I renamed repo. Here is current link https://github.com/cikay/publicrepo

**Comment by cikay** [comment]
> @cikay -- when I specify `egg=main` it still fails to install -- I think there may be a lack of definition in your setup.py.
> 
> ```
> Installing git+https://github.com/cikay/public_repo.git@main#egg=main...
> Error:  An error occurred while installing git+https://github.com/cikay/public_repo.git@main#egg=main!
> Error text: Collecting main
>   Cloning https://github.com/cikay/public_repo.git (to revision main) to /tmp/pip-install-h3lj2prs/main_c172edfdf71e40fc8b3841b384504f4d
>   Resolved https://github.com/cikay/public_repo.git to commit c4551dea1dff89b6871f08ca0fa983e8edaceebf
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'done'
> Discarding git+https://github.com/cikay/public_repo.git@main#egg=main: Requested selam from git+https://github.com/cikay/public_repo.git@main#egg=main (from -r /tmp/pipenv-jal8ru1h-requirements/pipenv-lgqqhdqa-requirement.txt (line 1)) has inconsistent name: expected 'main', but metadata has 'selam'
> 
>   Running command git clone --filter=blob:none --quiet https://github.com/cikay/public_repo.git /tmp/pip-install-h3lj2prs/main_c172edfdf71e40fc8b3841b384504f4d
>   WARNING: Generating metadata for package main produced metadata for project name selam. Fix your #egg=main fragments.
> ERROR: Could not find a version that satisfies the requirement main (unavailable) (from versions: none)
> ERROR: No matching distribution found for main (unavailable)
> 
> ✘ Installation Failed 
> ```

I did not specify the name in the setup function. It should be like this `setuptools.setup(name="publicrepo")`

Thanks. I will close the issue.
