### ISSUE TITLE
virtualenv: error: argument --creator: invalid choice: 'venv' (choose from 'builtin', 'cpython2-posix')

### ISSUE THREAD

**Issue by f0o** [pypa/pipenv#5452]
### Issue description

`pipenv check` fails or actually everything fails; it does install the python version correctly however.

### Expected result

it to work, obviously ;)

### Actual result
```
/usr/local/py-utils/venvs/pipenv/lib/python3.11/site-packages/pipenv/vendor/attr/_make.py:876: RuntimeWarning: Running interpreter doesn't sufficiently support code object introspection.  Some features like bare super() or accessing __class__ will not work with slotted classes.
  set_closure_cell(cell, cls)
/usr/local/py-utils/venvs/pipenv/lib/python3.11/site-packages/pipenv/vendor/attr/_make.py:876: RuntimeWarning: Running interpreter doesn't sufficiently support code object introspection.  Some features like bare super() or accessing __class__ will not work with slotted classes.
  set_closure_cell(cell, cls)
/usr/local/py-utils/venvs/pipenv/lib/python3.11/site-packages/pipenv/vendor/attr/_make.py:876: RuntimeWarning: Running interpreter doesn't sufficiently support code object introspection.  Some features like bare super() or accessing __class__ will not work with slotted classes.
  set_closure_cell(cell, cls)
Creating a virtualenv for this project...
Pipfile: /workspaces/backend/Pipfile
Using /home/vscode/.pyenv/versions/2.7.18/bin/python2.7 (2.7.18) to create virtualenv...
⠙ Creating virtual environment...SystemExit: 2

✘ Failed creating virtual environment 
[pipenv.exceptions.VirtualenvCreationException]: usage: virtualenv [--version] [--with-traceback] [-v | -q] [--read-only-app-data] [--app-data APP_DATA] [--reset-app-data] [--upgrade-embed-wheels] [--discovery {builtin}] [-p py] [--try-first-with py_exe]
                  [--creator {builtin,cpython2-posix}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list]
virtualenv: error: argument --creator: invalid choice: 'venv' (choose from 'builtin', 'cpython2-posix')

Failed to create virtual environment.
```

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

Pipfile:
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
```

`pipenv check` already fails

-------------------------------------------------------------------------------

**Comment by f0o** [comment]
https://pastebin.com/USh8htgX

due to size limitations here is the pipenv --support output

**Comment by matteius** [comment]
@f0o We don't have support for python 3.11 yet

**Comment by f0o** [comment]
That explains it; closing

**Comment by matteius** [comment]
@f0o Actually though I am wondering if this has nothing to do with 3.11 -- Did you by chance install virtualenv from apt?   If so, could you uninstall that and try installing it from pypi using pip?  https://stackoverflow.com/questions/70583980/i-am-unable-to-create-a-new-virtualenv-in-ubuntu

**Comment by iamdbychkov** [comment]
May I Bring this up again? 

Having the same issue using 3.10.6.
removing virtualenv installed from apt made no difference.

pipx installations and bare pip installation behave the same.

**Comment by iamdbychkov** [comment]
Hi @matteius ! Thank your for the reply :)

Have installed `2022.11.1.dev0` from `main` branch but no luck, unfortunately

Error read as follows:

![image](https://user-images.githubusercontent.com/53076075/206924453-c9a36f4a-d9ac-4dd3-8d6f-988dea04a1df.png)


Haven't got an opportunity to check pipenv version on work PC which handles such cases without problems.

**Comment by iamdbychkov** [comment]
![image](https://user-images.githubusercontent.com/53076075/207023660-e16c9728-320d-4f7d-ba55-54051b0477d7.png)

Works fine on 2022.6.7
