### ISSUE TITLE
Package installation failed error 

### ISSUE THREAD

**Issue by Raghuveeranagouda** [pypa/pipenv#5465]
In the docker build `pipenv install` is failing with below error.

![image](https://user-images.githubusercontent.com/45602562/201065887-07da2fb1-089a-4f47-81a5-d2cdf85f2842.png)

before new release it was working fine, after the latest release on Nov  5, 2022 it is giving this error.
We get this error only if the Pipfile contains custom packages, otherwise works fine.
And tried with some older pipenv version working fine for custom packages.

may i know the reason why it is failing for latest pipenv.

Dockerfile:
![image](https://user-images.githubusercontent.com/45602562/201066926-08530e1f-7135-49d9-8d8a-5a2d4adcebd8.png)

Pipfile:
![image](https://user-images.githubusercontent.com/45602562/201067599-597f9e43-2831-409d-b368-879f592992ec.png)

**Comment by matteius** [comment]
@Raghuveeranagouda You must specify the indexes of packages in the  pipfile that do not get pulled from the default source (the first source in the file).  Optionally, you may try your luck with this option:  

```
[pipenv]
install_search_all_sources = true
```

https://pipenv.pypa.io/en/latest/advanced/#specifying-package-indexes

**Comment by monkeyman192** [comment]
I'm just going to piggyback on this issue as I think I have a similarly related one I want clarification on.
So I have a Pipfile that looks like the following:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[[source]]
name = "nexus"
url = "<private repo>"
verify_ssl = true


[packages]
my_package = {version = "*", index = "nexus"}

[requires]
python_version = "3.9"
```

where `my_package` is a package uploaded to our private repo which has some dependency which can be found on the usual `pypi` repo (`pika` in this case, but this issue applies to any sub-dependency not on our own repo)

On version 2022.10.25 this would install just fine, no issues whatsoever. However in subsequent versions it will fail when doing `pipenv install --skip-lock` (paths etc removed as this is for work):

```
Installing dependencies from Pipfile...
An error occurred while installing my_package! Will try again.
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]: Looking in indexes: <private repo>, <private repo>
[pipenv.exceptions.InstallError]: Collecting my_package
[pipenv.exceptions.InstallError]:   Using cached <private repo>/my_package/0.7.1/my_package-0.7.1-py3-none-any.whl (15 kB)
[pipenv.exceptions.InstallError]:   Using cached <private repo>/my_package/0.7.0/my_package-0.7.0-py3-none-any.whl (15 kB)
[pipenv.exceptions.InstallError]:   Using cached <private repo>/my_package/0.6.0/my_package-0.6.0-py3-none-any.whl (12 kB)
[pipenv.exceptions.InstallError]:   Using cached <private repo>/my_package/0.5.0/my_package-0.5.0-py3-none-any.whl (12 kB)
[pipenv.exceptions.InstallError]: 
[pipenv.exceptions.InstallError]: The conflict is caused by:
[pipenv.exceptions.InstallError]:     my_package 0.7.1 depends on pika
[pipenv.exceptions.InstallError]:     my_package 0.7.0 depends on pika
[pipenv.exceptions.InstallError]:     my_package 0.6.0 depends on pika
[pipenv.exceptions.InstallError]:     my_package 0.5.0 depends on pika
[pipenv.exceptions.InstallError]: 
[pipenv.exceptions.InstallError]: To fix this you could try to:
[pipenv.exceptions.InstallError]: 1. loosen the range of package versions you've specified
[pipenv.exceptions.InstallError]: 2. remove package versions to allow pip attempt to solve the dependency conflict
[pipenv.exceptions.InstallError]: ERROR: Cannot install -r ~\appdata\local\temp\pipenv-77lf0fhm-requirements\pipenv-7_26ucmn-hashed-reqs.txt (line 1) because these package versions have conflicting dependencies.
[pipenv.exceptions.InstallError]: ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
ERROR: Couldn't install package: [Requirement(_name='my_package', vcs=None, req=NamedRequirement(name='my_package', version='', req=Requirement.parse('my_package'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=my_package, path=None, uri=None, extras=(), markers=None, vcs=None, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=my_package)>), markers=None, _specifiers='', index='nexus', editable=False, hashes=frozenset(), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=my_package, path=None, uri=None, extras=(), markers=None, vcs=None, specifier=None, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=my_package)>, _ireq=None)]
 Package installation failed...
 ```

If however I add the `pika` dependency to the Pipfile before the `my_package` dependency it will create the venv fine.
This I guess is a workaround, however, we have multiple packages, all requiring different dependencies (some of which are nested), so it isn't a sustainable solution to add all the dependencies for each package in each place we require them.

I'm inclined to think that [this](https://github.com/pypa/pipenv/commit/bf289af7e62bc334862efd7e3e2a9bb537238f2c) commit is likely for this change.

**Comment by matteius** [comment]
@monkeyman192 That commit was only first included in `2022.11.11` but you say versions after `2022.10.25` have the issue.  ``2022.10.25`` was the version pipenv to include/use `pip=22.3`.  You can bypass the effect of the change you referenced by adding :
```
[pipenv]
install_search_all_sources = true
```
Since you are using multiple package indexes, I recommend taking a read through:  https://pipenv.pypa.io/en/latest/advanced/#specifying-package-indexes

**Comment by monkeyman192** [comment]
@matteius Ok, I maybe wasn't exhaustive in my determination of the version that this occurred in, sorry.
I thought I had had a good read of that documentation, but upon re-re-read, I see the following:
"When PyPI is omitted, then any public packages required either directly or as sub-dependencies must be mirrored onto your private index or they will not resolve properly"
I guess that clarifies that.
So one final question I have then, is it possible for a sub-dependency to be written in such a way that when the dependency resolution occurs it will pull some packages from the public and some from the private, or is it the case that, once a package is in the private repo, ALL its dependencies must also be there (unless I specify `install_search_all_sources = true`?)

**Comment by matteius** [comment]
@monkeyman192 That part of the documentation about mirroring pypi packages came from pip's recommendation, but it is not a strict requirement.  It is totally possible to use multiple indexes.  It also seems to me that pip used to prefer pypi if it was there, but now their documentation says:

> pip looks for packages in a number of places: on PyPI (if not disabled via --no-index), in the local filesystem, and in any additional repositories specified via --find-links or --index-url. There is no ordering in the locations that are searched. Rather they are all checked, and the “best” match for the requirements (in terms of version number - see [PEP 440](https://peps.python.org/pep-0440/) for details) is selected.

You asked:

> So one final question I have then, is it possible for a sub-dependency to be written in such a way that when the dependency resolution occurs it will pull some packages from the public and some from the private, or is it the case that, once a package is in the private repo, ALL its dependencies must also be there (unless I specify install_search_all_sources = true?)

Well, the way it has been working is that the first index in the Pipfile is the default, and so unless specified it should pull from the default.   Before the change you referenced it really was searching all sources whether or not that setting was defined, which I saw as a bug from when I first worked on index restricted packages for pipenv (to prevent package confusion attacks).  

I think you aren't the first person that has run into the desire to specifying in the sub-dependency what index it should be pulled from.   I am not aware of current support for this, nor am I opposed to it being added.  I think it would require some thought about how its done -- possibly a `pipenv` section of a pyproject.toml could specify this?

The workarounds are basically are:  If the lock phase resolution is working but install phase is not, then `install_search_all_sources = true` is probably a good option for you.  I have to ask though why you are using --skip-lock, it defeats the security benefits of having a lock file with hash verification, which seems especially important when using install_search_all_sources enabled.

Alternatively, as you found, you can specify manually the indexes of packages in the Pipfile that pull from a non default index, which would also solve any resolver issues during the lock phase.   I think that could be improved upon if we could process an index override from the pyproject.toml into the metadata and use that when present.   That would also be a fair amount of work to get going and would require community support to figure out the past paths forward.   That is the current lay of the land.

**Comment by monkeyman192** [comment]
Yeah ok, sounds like it would be a decent amount of work to implement something like specifying dependencies in sub-dependencies. `setuptools` doesn't seem to include functionality to provide an index for some given package, and things like the .toml file isn't included in the package, so there is probably no way to have that info in the package without some extra work.

Regarding using `--skip-lock`, I'm just doing this because it's quicker in this case (ie. to indicate the error occurs when trying to install the packages).
Although, running this without `--skip-lock` throws up a different error...
Running `pipenv install` with a Pipfile which has one dep which is in the private repo, and this dep itself has a dependency which is also in the private repo, when looking at the lock file, this sub-dependency doesn't have the index listed:

```
        "first_dependency": {
            "hashes": [
                "sha256:cac8fce50f1fd3ccd15290e98aeb33dd625abc2e6a9040c9822baae5bf8b52af",
                "sha256:cfd7e1aef870926e9237c3dce304bcf0d1bfd74a287e8a9c9d61169e1685590e"
            ],
            "index": "nexus",
            "markers": null,
            "version": "==1.0.0"
        },
        "sub_dependency": {
            "hashes": [
                "sha256:6573bdd980034f2c449102a0e16061a9f731e2abbc5682bf96af16446ed2a57c"
            ],
            "markers": "python_version >= '2.7'",
            "version": "==21.1.1.dev4+gc5abe93"
```
So when running with a lock causes this issue where it says it can't find this dependency, and running without the lock I get the issue mentioned in my first comment.
Of course adding `install_search_all_sources = true` fixes this issue, but again, figured I'd mention this.

I guess this all amounts to us just needing to use this value in our pipenv files until the possibility of a more precise solution.
Thanks for the help!

**Comment by Raghuveeranagouda** [comment]
> @Raghuveeranagouda You must specify the indexes of packages in the pipfile that do not get pulled from the default source (the first source in the file). Optionally, you may try your luck with this option:
> 
> ```
> [pipenv]
> install_search_all_sources = true
> ```
> 
> https://pipenv.pypa.io/en/latest/advanced/#specifying-package-indexes

Thank you @matteius, now I am able to install packages with indexes.

**Comment by Dans182** [comment]
> @Raghuveeranagouda You must specify the indexes of packages in the pipfile that do not get pulled from the default source (the first source in the file). Optionally, you may try your luck with this option:
> 
> ```
> [pipenv]
> install_search_all_sources = true
> ```
> 
> https://pipenv.pypa.io/en/latest/advanced/#specifying-package-indexes

Thank you bro!! Help me a lot this!
