### ISSUE TITLE
sync Error: No such option: --sequential

### ISSUE THREAD

**Issue by Charles546** [pypa/pipenv#5473]
### Issue description

The latest version doesn't support `pipenv sync --sequential`, which was supported in 2020.6.2. Can't find any document and release notes about removing this feature, so either a documentation an issue or it is broken.

### Expected result

Either make it work again or correct the documents

### Actual result

```
Usage: pipenv sync [OPTIONS]
Try 'pipenv sync -h' for help.

Error: No such option: --sequential
The command '/bin/sh -c pipenv sync --sequential' returned a non-zero code: 2
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @honeyscience/datadog-monitor@0.0.1 docker-build: `docker-build "-y" "staging" "metrics-monitor"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @honeyscience/datadog-monitor@0.0.1 docker-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2022-11-14T18_05_09_669Z-debug.log


Exited with code exit status 2

```

### Steps to replicate

Just run `pipenv sync --sequential`.

**Comment by matteius** [comment]
The implementation changed to always be sequential batches so the option eventually went away in a separate PR.
