### ISSUE TITLE
Followup on skipped test `test_pipenv_check`

### ISSUE THREAD

**Issue by matteius** [pypa/pipenv#5488]
Had to skip this test to get the latest safety work across the line -- ideally @yeisonvargasf can help us look at how to make safety in the unit test look at the virtualenv that the test creates.

### Issue description

Test is marked skipped for now

### Expected result

To have a test of the integration.

**Comment by yeisonvargasf** [comment]
This issue is probably caused by #4819. I'm going to take a look.
