### ISSUE TITLE
Incorrect links in table of contents of README.md

### ISSUE THREAD

**Issue by albert-github** [pypa/pipenv#5494]
### Issue description

In the README.md file we see in the Table of contents constructs like (just 2 examples):
```

- [User Testimonals](#☤-user-testimonials)

- [Features](#☤-features)
```
though these links don't work under GitHubm, but should be like
```

- [User Testimonals](#-user-testimonials)

- [Features](#-features)
```

### Expected result

Correct links, so possibility to jump to the right place

### Actual result

No jump to the right place

**Comment by albert-github** [comment]
Problem is NOT solved, just tried the 2 mentioned links and the don't point to the right place, in fact they have not changed at all.

**Comment by matteius** [comment]
https://github.com/pypa/pipenv/pull/5498#issuecomment-1333560141

**Comment by albert-github** [comment]
I looked at the release v2022.12.17 and the problem is still present (see also my remark:  https://github.com/pypa/pipenv/pull/5498#issuecomment-1333560141)
