### ISSUE TITLE
run `pipenv check`, get VERSION file is not found

### ISSUE THREAD

**Issue by shexiaoheng** [pypa/pipenv#5502]
## Env
windows11 professional edition
python 3.11.0
pip 22.3
pipenv 2022.11.23

## Error message
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\shexi\\AppData\\Roaming\\Python\\Python311\\site-packages\\pipenv\\patched\\safety\\VERSION'

### Run and Install directory
![image](https://user-images.githubusercontent.com/3015681/203848961-cb0a4b13-58a4-42b6-8915-9fe86a350571.png)

### Project source code
![image](https://user-images.githubusercontent.com/3015681/203849073-d58becab-0e53-4984-b296-3b28b23172af.png)

Why did the pipenv I installed using `pip install --user pipenv` lose the VERSION file? In addition, I noticed that the submission of the source code commit c58c371f6b0a8fce59fdfa92f87cb79f58b726f5 did not pass. Is this the reason?

I tried 3.10.x and 3.9.x versions after the 3.11 version failed, and they all reported the error that the VERSION file could not be found

**Comment by matteius** [comment]
@shexiaoheng There was an issue with the sdist wheels build configuration, it has been fixed in `2022.11.24` which was just released.

**Comment by matteius** [comment]
Ok sorry about that -- there was still an issue with the wheel not including the rumael vendoring.   I just verified that new release `2022.11.25` does in fact include the required ruamel.

**Comment by shexiaoheng** [comment]
tanks
