### ISSUE TITLE
Pipenv does not sync indexes to lockfile

### ISSUE THREAD

**Issue by NicoStellwag** [pypa/pipenv#5508]
### Issue description

When specifying an addtitional index as described [here](https://github.com/pypa/pipenv/blob/main/docs/advanced.rst), `pipenv install` does not synchronize the additional index to the lockfile, resulting in the following error:
```
...
Installing dependencies from Pipfile.lock (4204ea)...
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
...
    install_source = next(filter(lambda s: s["name"] == index_name, sources))
StopIteration
```

System:
OS: Windows Server 2019
Python: 3.9.1
Pipenv: 2022.11.25

When updating Pipfile.lock manually, everything works as expected.

### Expected result

Pipfile.lock:
```
...
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            },
            {
                "name": "pytorch",
                "url": "https://download.pytorch.org/whl/cu116",
                "verify_ssl": false
            }
        ]
...
```

### Actual result

Pipfile.lock:
```
...
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
...
```

### Steps to replicate

Minimal Pipfile:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://download.pytorch.org/whl/cu116"
verify_ssl = false
name = "pytorch"

[packages]
torch = {version = "*", index = "pytorch"}

[dev-packages]

[requires]
python_version = "3.9"
python_full_version = "3.9.1"

```

-------------------------------------------------------------------------------

Unfortunately I cannot provide `pipenv --support` from my work PC.

**Comment by matteius** [comment]
If possible, could you help validate the branch for this?  I will work on adding a unit test here if possible, as well.

**Comment by NicoStellwag** [comment]
When I'm back at work I will take a look.

**Comment by matteius** [comment]
new release has been published
