### ISSUE TITLE
`pipenv requirements` outputs some extraneous debug statements making for an invalid requirements.txt file

### ISSUE THREAD

**Issue by b-jazz** [pypa/pipenv#5517]
### Issue description

`pipenv requirements` generates debugging output (on stdout) that makes for an invalid requirements.txt file.

### Expected result

A list of packages and version numbers in the proper format.

### Actual result

```
[b-jazz:/tmp/test06] [test06-tmnPtKti] master* ± pipenv --verbose requirements > requirements.txt
[b-jazz:/tmp/test06] [test06-tmnPtKti] master* 9s ± cat requirements.txt 
-i https://pypi.org/simple
running egg_info
creating /tmp/test06/reqlib-metadata/UNKNOWN.egg-info
writing /tmp/test06/reqlib-metadata/UNKNOWN.egg-info/PKG-INFO
writing dependency_links to /tmp/test06/reqlib-metadata/UNKNOWN.egg-info/dependency_links.txt
writing top-level names to /tmp/test06/reqlib-metadata/UNKNOWN.egg-info/top_level.txt
writing manifest file '/tmp/test06/reqlib-metadata/UNKNOWN.egg-info/SOURCES.txt'
reading manifest file '/tmp/test06/reqlib-metadata/UNKNOWN.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file '/tmp/test06/reqlib-metadata/UNKNOWN.egg-info/SOURCES.txt'
click==8.1.3
-e .
```

### Steps to replicate

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
click = "*"
unknown = {editable = true, path = "."}

[dev-packages]

[requires]
python_version = "3.10"
```

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.11.30'`

Pipenv location: `'/home/b-jazz/.local/lib/python3.10/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

OS Name: `'posix'`

User pip version: `'22.3'`

user Python installations found:

  - `3.10.6`: `/home/b-jazz/.local/share/virtualenvs/test06-tmnPtKti/bin/python`
  - `3.10.6`: `/home/b-jazz/.local/share/virtualenvs/test06-tmnPtKti/bin/python3`
  - `3.10.6`: `/home/b-jazz/.local/share/virtualenvs/test06-tmnPtKti/bin/python`
  - `3.10.6`: `/home/b-jazz/.local/share/virtualenvs/test06-tmnPtKti/bin/python3`
  - `3.10.6`: `/usr/bin/python3`
  - `3.10.6`: `/usr/bin/python`
  - `3.10.6`: `/bin/python3`
  - `3.10.6`: `/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.15.0-47-generic',
 'platform_system': 'Linux',
 'platform_version': '#51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022',
 'python_full_version': '3.10.6',
 'python_version': '3.10',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `SESSION_MANAGER`
  - `WINDOWID`
  - `QT_ACCESSIBILITY`
  - `COLORTERM`
  - `XDG_CONFIG_DIRS`
  - `LESS`
  - `XDG_SESSION_PATH`
  - `TERM_PROGRAM_VERSION`
  - `TMUX`
  - `PIPENV_ACTIVE`
  - `HISTSIZE`
  - `LANGUAGE`
  - `SSH_AUTH_SOCK`
  - `SVN_EDITOR`
  - `SHELL_SESSION_ID`
  - `DESKTOP_SESSION`
  - `SSH_AGENT_PID`
  - `GTK_RC_FILES`
  - `XCURSOR_SIZE`
  - `EDITOR`
  - `XDG_SEAT`
  - `PWD`
  - `XDG_SESSION_DESKTOP`
  - `LOGNAME`
  - `XDG_SESSION_TYPE`
  - `GPG_AGENT_INFO`
  - `SYSTEMD_EXEC_PID`
  - `XAUTHORITY`
  - `GTK2_RC_FILES`
  - `PIP_PYTHON_PATH`
  - `HOME`
  - `IM_CONFIG_PHASE`
  - `LANG`
  - `XDG_CURRENT_DESKTOP`
  - `KONSOLE_DBUS_SERVICE`
  - `VIRTUAL_ENV`
  - `KONSOLE_DBUS_SESSION`
  - `PROFILEHOME`
  - `XDG_SEAT_PATH`
  - `KONSOLE_VERSION`
  - `FIGNORE`
  - `BASH_SILENCE_DEPRECATION_WARNING`
  - `KDE_SESSION_UID`
  - `XDG_SESSION_CLASS`
  - `TERM`
  - `USER`
  - `TMUX_PANE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `COLORFGBG`
  - `KDE_SESSION_VERSION`
  - `PAM_KWALLET5_LOGIN`
  - `DISPLAY`
  - `SHLVL`
  - `XDG_VTNR`
  - `XDG_SESSION_ID`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_RUNTIME_DIR`
  - `PS1`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `XCURSOR_THEME`
  - `XDG_DATA_DIRS`
  - `KDE_FULL_SESSION`
  - `PATH`
  - `HISTORYFILESIZE`
  - `HISTIGNORE`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `KDE_APPLICATIONS_AS_SCOPE`
  - `OLDPWD`
  - `GOPATH`
  - `TERM_PROGRAM`
  - `KONSOLE_DBUS_WINDOW`
  - `_`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/b-jazz/.local/share/virtualenvs/test06-tmnPtKti/bin:/export/apps/xtools/bin:/usr/local/linkedin/bin:/opt/local/bin:/home/b-jazz/bin:/home/b-jazz/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/b-jazz/go:/home/b-jazz/go/bin:/home/b-jazz/.cargo/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `emacs`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/tmp/test06`
  - `VIRTUAL_ENV`: `/home/b-jazz/.local/share/virtualenvs/test06-tmnPtKti`

---------------------------

Contents of `Pipfile` ('/tmp/test06/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
click = "*"
unknown = {editable = true, path = "."}

[dev-packages]

[requires]
python_version = "3.10"

```

Contents of `Pipfile.lock` ('/tmp/test06/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "f85497885b1e8f7947b63eaa52ba015966ec2b3666c6f7c213ad01058683277c"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.10"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "click": {
            "hashes": [
                "sha256:7682dc8afb30297001674575ea00d1814d808d6a36af415a82bd481d37ba7b8e",
                "sha256:bb4d8133cb15a609f44e8213d9b391b0809795062913b383c62be0ee95b1db48"
            ],
            "index": "pypi",
            "version": "==8.1.3"
        },
        "unknown": {
            "editable": true,
            "path": "."
        }
    },
    "develop": {}
}

```
</details>

**Comment by oz123** [comment]
This seems like a variation of https://github.com/pypa/pipenv/issues/5503.
Are you still having this issue without the `--verbose` option?

**Comment by b-jazz** [comment]
>Are you still having this issue without the `--verbose` option?

Yes.

$ pipenv requirements
-i https://pypi.org/simple
running egg_info
creating /tmp/test06/reqlib-metadata/UNKNOWN.egg-info
writing /tmp/test06/reqlib-metadata/UNKNOWN.egg-info/PKG-INFO
writing dependency_links to /tmp/test06/reqlib-metadata/UNKNOWN.egg-info/dependency_links.txt
writing top-level names to /tmp/test06/reqlib-metadata/UNKNOWN.egg-info/top_level.txt
writing manifest file '/tmp/test06/reqlib-metadata/UNKNOWN.egg-info/SOURCES.txt'
reading manifest file '/tmp/test06/reqlib-metadata/UNKNOWN.egg-info/SOURCES.txt'
writing manifest file '/tmp/test06/reqlib-metadata/UNKNOWN.egg-info/SOURCES.txt'
click==8.1.3
setuptools==65.6.3
-e .
$


I think just the existence of the UNKNOWN.egg-info directory is a problem in and of itself. I have no idea why that is being created.

**Comment by b-jazz** [comment]
I have two computers set up. One with python 3.10.6 and the other with 3.10.8. Both have setuptools 65.6.3. Both have pipenv 2022.11.30. Using the same sample code, one of them (the older) creates this UNKNOWN egg info while the newer python version doesn't. 

I'm not sure if there is something with my user (years of customization) on the 3.10.6 python box vs a brand new user on the python 3.10.8 vagrant box (Arch Linux) or if there are some packages in the dependency tree that have different versions. Happy to gather whatever info I can.

I've attached my tar file with a simple python script and project setup in case that helps.
[test06.zip](https://github.com/pypa/pipenv/files/10158875/test06.zip)

**Comment by b-jazz** [comment]
Here is some output of what it takes to repro with my python 3.10.6 environment: https://gist.github.com/b-jazz/731e130a96a7a7edd43124223c43a457

I think this is probably more of a problem with the UNKNOWN.egg-info being created in the first place.

**Comment by oz123** [comment]
I can't reproduce this issue with pipenv 2022.12.19. Using your supplied package.
```
 $ pipenv --verbose requirements > requirements.txt
oznt@dell-gentoo:~/Software/test06 |test06-_HAq06HR|] $ $ cat requirements.txt 
-i https://pypi.org/simple
click==8.1.3
-e .
oznt@dell-gentoo:~/Software/test06 |test06-_HAq06HR|] $ pipenv --version
pipenv, version 2022.12.19
```

Can you confirm that you still have this issue with this version?

**Comment by b-jazz** [comment]
I just checked this on a new system and I no longer have my original problem. This issues can be closed.
