### ISSUE TITLE
Local wheel Installation failure due to path removal in Pipfile.lock

### ISSUE THREAD

**Issue by JGSweets** [pypa/pipenv#5542]
### Issue description

This issue was introduced within the PR #5464
The lines:
```python
if not keep_outdated:
    try:
        del lockfile[category]
    except KeyError:
        pass
```
forces the category to be resolved latter. This strips the `path` key for local packages which does not get reintroduced into the lockfile later. This causes a `cannot resolve package error` during installation despite Pipfile.lock being created.

i.e. the Pipfile.lock for the `<LOCAL_PACKAGE>` loses the path.
```json
"<LOCAL_PACKAGE>": {
    "hashes": [
        "sha256:<VALUE>"
    ],
    "path": "<PATH>"
}
```
becomes
```json
"<LOCAL_PACKAGE>": {
    "hashes": [
        "sha256:<VALUE>"
    ]
}
```

### Expected result

Pipfile.lock should maintain the `path` key for locally installed packages.

### Actual result

```
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement my-package (from versions: none)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for my-package
```

### Steps to replicate

1. Create a Pipfile which contains a path to a local package.
  e.g. 
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
my-package = {path = "./path/to/my-package.whl"}
```
2. Run `pipenv install`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.11.30'` # NOTE: Tested around 2022.11.11 and 2022.11.5 to identify.

Pipenv location: `'/usr/local/lib/python3.10/site-packages/pipenv'`

Python location: `'/usr/local/opt/python@3.10/bin/python3.10'`

OS Name: `'posix'`

User pip version: `'22.3'`

user Python installations found:

  - `3.10.8`: `/usr/local/bin/python3`
  - `3.9.16`: `/usr/local/bin/python3.9`
  - `3.8.16`: `/usr/local/bin/python3.8`
  
Limited output...
</details>

**Comment by matteius** [comment]
Have you tried the main branch?

**Comment by matteius** [comment]
Ok to my surprise, this appears to be an issue even on main.   I thought this would have fixed it:  https://github.com/pypa/pipenv/pull/5523

**Comment by matteius** [comment]
I see the issue -- you named it `my-package` but there is this logic that converts to `pep423_name` which converts dashes to underscores.  If in my example I change `my-package` to `requests` to match the wheel I am installing, then it works on main branch.  Let me know if you can try main branch if your example still has an issue; we plan to do another release soon.

**Comment by JGSweets** [comment]
I can check tomorrow, thanks for the quick responses!

**Comment by matteius** [comment]
New version has been released so you can try it from pypi install.

**Comment by JGSweets** [comment]
> New version has been released so you can try it from pypi install.

Looks resolved on my end!

**Comment by JGSweets** [comment]
Would there be need to add a test for coverage or did the PR that fixed the issue include enough coverage wrt this issue?

**Comment by matteius** [comment]
There was a test scenario added for `file` but not `path` -- we should probably add one for `path` as well:  https://github.com/pypa/pipenv/pull/5523/files

**Comment by matteius** [comment]
Non trivial to add a test for path because path is relative and by the time the test runner invokes and makes temp directories, its impossible to know the relative pathing to the test wheel for install and actually have it resolve via lock, without making an absolute file path which we already have a test for.
