### ISSUE TITLE
Private repo in pipfile not working

### ISSUE THREAD

**Issue by julste** [pypa/pipenv#5545]
I'm trying to install a package from a private repo, using version [2020.11.15] it worked a long time, with the current version 2022.12.17 not anymore.

Example:

```
[packages] 
pack1 = {editable = true, git = "https://myToken@github.com/.../pack1"}
```
It looks forever:

`Locking [packages] dependencies...
`

**Comment by matteius** [comment]
I think this is related:  https://github.com/sarugaku/requirementslib/issues/353

**Comment by julste** [comment]
looks good, thanks a lot!
