### ISSUE TITLE
pipenv `2022.12.17` ate my while loop

### ISSUE THREAD

**Issue by neilferreira** [pypa/pipenv#5546]
### Issue description

I've described this issue in greater detail on https://github.com/neilferreira/pipenv-ate-my-while-loop - but essentially the pipenv release `2022.12.17` that came out this weekend is seemingly impacting a `| while IFS= read -r foo; do` statement in bash, and is ending the while loop as a result.

As per my example, this command works:

```
docker build --build-arg VERSION=2022.11.30 -t foo:latest .
```

Whereas this command fails:

```
docker build --build-arg VERSION=2022.12.17 -t foo:latest .
```

### Expected result

I expect that running `pipenv install -e .` should not impact the bash script that is running it.

### Actual result

Running `pipenv install -e .` is affecting the bash script that is running it.

### Steps to replicate

```
git clone git@github.com:neilferreira/pipenv-ate-my-while-loop.git
cd pipenv-ate-my-while-loop
docker build --build-arg VERSION=2022.11.30 -t foo:latest .
docker build --build-arg VERSION=2022.12.17 -t foo:latest .
```

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

**Comment by matteius** [comment]
I think this is related: https://github.com/sarugaku/requirementslib/issues/353

Specifically, I think the issue is here:
![image](https://user-images.githubusercontent.com/479892/208385805-74214e90-8841-40f6-a800-bf37e4b57d66.png)

**Comment by matteius** [comment]
Actually that part changed to shell=True, but is ok, there is another spot in that file that didn't convert right, but I am thinking its better to avoid using `shell=True` -- I have a PR out to requirementslib to fix this.

**Comment by matteius** [comment]
`2022.12.19` has been released to fix this issue.
