### ISSUE TITLE
Unable to install pipenv - "ERROR: Could not find a version that satisfies the requirement pipenv "

### ISSUE THREAD

**Issue by Bereky** [pypa/pipenv#5551]
I was trying to install pipenv through this command: 

``` pip install --user pipenv ```

But I keep getting this error: 
```
ERROR: Could not find a version that satisfies the requirement pipenv (from versions: none)
ERROR: No matching distribution found for pipenv
```

I'm using Python 3.11.1 and pip 22.3.1

Can you help?

**Comment by oz123** [comment]
Which OS are you using?

**Comment by Bereky** [comment]
> Which OS are you using?

I'm using windows 10. It works fine on my Fedora VM but not on windows(primary os).

**Comment by oz123** [comment]
Does this work for you?
https://raw.githubusercontent.com/pypa/pipenv/main/get-pipenv.py

**Comment by Bereky** [comment]
No, It's not working.

**Comment by matteius** [comment]
Can you pip install something else like requests?

**Comment by Bereky** [comment]
> Can you pip install something else like requests?

I think the problem might be my pip or the network. It is not specifically pipenv that's not working at this point. I get this warning whenever I try to install a pip package and it fails every time.

```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")':
```

Thanks for the help!
