### ISSUE TITLE
Prepare environement with my custom package (install from VCS)

### ISSUE THREAD

**Issue by vsedyshev-intermedia** [pypa/pipenv#5557]
### Issue description

Using custom dependencies `git+ssh` described in local package module `pyproject.toml` well working in `poetry` does not work with `pipenv`.

### Expected result

Clone `git+ssh` private repository and continue working.

### Actual result

Error message:

```
$ pipenv install -e .
Installing -e ....
⠴ Installing ***...[31m[1mError: [0m An error occurred while installing [32m-e .[0m!
Error text: Obtaining file:///*** (from -r /tmp/pipenv-adguwfr_-requirements/pipenv-zhdvnob6-requirement.txt (line 1))
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Collecting ***@ git+git+ssh://...@...@1.3.0

[36mERROR: Could not install packages due to an OSError: No connection adapters were found for 
'git+git+ssh://...'
```

**Comment by vsedyshev-intermedia** [comment]
Please also pay attention with garbage ANSI in output...

**Comment by matteius** [comment]
Have you tried specifying it without the `git+`  It seems in the output that its being added twice.

**Comment by vsedyshev-intermedia** [comment]
> Have you tried specifying it without the git+ It seems in the output that its being added twice.

Thanks. Now works with 'ssh://' prefix. But `poetry` documentation provide "git+ssh" example. See at https://python-poetry.org/docs/cli/. What's difference with here?

![image](https://user-images.githubusercontent.com/121124346/209851934-0dfeb3cc-a712-442f-af7e-c982f2bc5665.png)

> Not sure what you mean by garbage ANSI in output.

```
⠴ Installing ***...[31m[1mError: [0m An error occurred while installing [32m-e .[0m!
-------------------^^^^^^^-------^^^------------------------------------^^^^----^^^
```
![image](https://user-images.githubusercontent.com/121124346/209850812-e5105c79-e3ad-4e69-9802-e735b91e3f06.png)

**Comment by matteius** [comment]
@oz123 I think this another case where the output looks weird since the conversion to use rich for the subprocess streams.

**Comment by oz123** [comment]
This issue has two parts:
The first, is that the protocol `git+ssh` isn't parsed properly. That is very likely a bug with requirememtslib.
The second, something is writing output with colors and isn't detecting it's supposed to trim the ANSI Color chars, because it's not writing to a terminal. This might be  an issue that  caused by rich.

**Comment by oz123** [comment]
OK, I started looking at it, and like I was guessing, the ssh part is a problem with requirementslib. See this:

```
$ pipenv install -v git+ssh://git@github.com/sdispater/pendulum.git
Installing git+ssh://git@github.com/sdispater/pendulum.git...
[31mWARNING[0m: pipenv requires an #egg fragment for version controlled dependencies. Please install remote dependency in the form git+ssh://git@github.com/sdispater/pendulum.git#egg=<package-name>.
✘ Installation Failed
```
The error coms from this line:
```
ValueError: pipenv requires an #egg fragment for version controlled dependencies. Please install remote dependency in the form git+ssh://git@github.com/sdispater/pendulum.git#egg=<package-name>.
> /home/oznt/Software/pypa/pipenv/pipenv/core.py(2335)do_install()
-> pkg_requirement = Requirement.from_line(pkg_line)
```

Can you please show your Pipfile?
This works:

```
$ cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
o3 = {git = "https://gitlab.com/oz123/o3.git"}

[pipenv]
allow_prereleases = true
```

You can install this with:
```
$ pipenv install
```
Which looks at the current or above dirs for the Pipfile.

The command you are using:
```
$ pipenv install .
```
Will only work if you have pyproject\setup.py in that directory, e.g https://github.com/pypa/pipenv/files/10158875/test06.zip

Note, how I specify git sources in Pipfile. Are you using the same format?

**Comment by vsedyshev-intermedia** [comment]
> Can you please show your Pipfile?

I think that no issues in Pipfile. Since I understand error raise up
by cascade dependencies from `pyproject.toml` writen on `poetry` library.

Since I undestand right in poetry module specify dependencies shown below:

```
    {git = "git+ssh://...", tag = "", ... },
```
I assume that "git" and "git+ssh" is concatenate under poetry and provide as result git+git+ssh.

Since issue I now make workaround with using venv+pip instead using pipenv and talk with developer our cascade library and at current moment I have no environmetnt to reproduce issue.

Since we no more poetry using as dependencies I have no issues.

**Comment by oz123** [comment]
So this issue can be closed?

**Comment by vsedyshev-intermedia** [comment]
> So this issue can be closed?

Yep.
