### ISSUE TITLE
Implement PIP_TRUSTED_HOSTS logic from importing requirements to specified --index URL

### ISSUE THREAD

**Issue by kalebmckale** [pypa/pipenv#5572]
### Is your feature request related to a problem? Please describe.

The larger problem I'd ideally like to solve is to have newly created Pipfiles contain the correct source information and not be required to first fail, to have to edit the Pipfile, and then to attempt again.

Specifically, when adding an index via command line, if the index URL begins with https, verify_ssl is automatically set to true. However, if using private indices, this may be neither necessary nor preferred.

### Describe the solution you'd like

The logic currently used when parsing requirements files in core.py that checks environment variable PIP_TRUSTED_HOSTS when determining the value for verify_ssl could also be implemented with index URLs specified at the command line.

### Describe alternatives you've considered

Alternatively, one could pre-generate a blank Pipfile template with the correct sources and not use pipenv to create Pipfile. This would not be preferred.

### Additional context

I'm happy to make the simple changes and create a pull request (see kalebmckale/pipenv@7c5dcde). I've already successfully tested this locally on my system, but I understand it needs to run though the full gamut of possible platforms, etc.

**Comment by matteius** [comment]
@kalebmckale Would you still be interested in taking on any fixes related to this?

**Comment by kalebmckale** [comment]
@matteius I would love to be able to confidently create pull requests, but unfortunately I don't have a good development environment at home. Right now, I really just do programming on my iPad, and `iSH` isn't quite there with its functionality although it's pretty nice to have. I think the latest issue I ran into was the inability to use `pyenv` to install other versions of Python because iSH has yet to figure out (or perhaps just haven't released a fix to) shell redirection, i.e. `<(...)`. tl;dr: I'm happy to do the coding, but I cannot really test it at home.

**Comment by matteius** [comment]
@kalebmckale opening a PR that is editable by the maintainers would be a good way to capture your ideas and possibly allow us to push them across the line.   There is so much going on for me that pipenv is a slice of it, and while I'd love to get the issue reports under 100 in the next year, it will require as much help as possible.

**Comment by kalebmckale** [comment]
@matteius Okay, I think I did it correctly. It's technically my first PR on GitHub. I wasn't sure what extension to use for the news item but decided to go with feature.

**Comment by kalebmckale** [comment]
@matteius @oz123 This can be closed / resolved?

**Comment by kalebmckale** [comment]
@matteius @oz123 I figured out how to close the issue. So embarrassing! 😅
