### ISSUE TITLE
installing package with ~= leads to installing the latest version of that package

### ISSUE THREAD

**Issue by EiJayK** [pypa/pipenv#5594]
### Issue description

pipenv install "tensorflow~=2.9" leads to the installation of the latest version of tensorflow which is 2.11.x I would expect that it would not update the major version

### Expected result

a version of tensorflow equal to 2.9.3 (for example)

### Actual result

tensorflow 2.11.x

### Steps to replicate
python 3.7
run on cli
pipenv install "tensorflow~=2.9"

**Comment by matteius** [comment]
I think this is expected, -- the tilde-equals operator takes the least most significant specified value, in this case .9 and makes it flexible.  If you wanted to restrict further you could do `pipenv install "tensorflow~=2.9.3"` which would upgrade to anything in 2.9 (making the .3 flexible).

**Comment by EiJayK** [comment]
Ok, thanks I will try this
