### ISSUE TITLE
Can no longer specify custom name for wheel based dependencies

### ISSUE THREAD

**Issue by elanou** [pypa/pipenv#5598]
### Issue description

In the Pipfile you used to be able to set a custom name for the dependency you were installing from wheel.

example where you want to have a separate wheel for a different platform:
```
spacy-darwin = {file = "https://files.pythonhosted.org/packages/8a/2a/fe2870e216511ed12b9b5acf89228abc0c76832b9572501e0b895a9e129d/spacy-3.4.3-cp39-cp39-macosx_10_9_x86_64.whl", extras = ["transformers"], sys_platform = "== 'darwin'"}
spacy = {version = ">=3.4.1,<3.5.0", extras = ["transformers","cuda114"], sys_platform = "== 'linux'"}
```
The Pipfile.lock would then contain an entry for each item (spacy, spacy-darwin).

### Expected result

I used to be able to expect the Pipfile.lock to contain an entry for both 'spacy-darwin' and 'spacy' with the sys_platform markers and correct hashes/files.

### Actual result

Now only 'spacy' shows up in the lock file.

If you try having only one line in the Pipfile like this:
```
spacy-darwin = {file = "https://files.pythonhosted.org/packages/8a/2a/fe2870e216511ed12b9b5acf89228abc0c76832b9572501e0b895a9e129d/spacy-3.4.3-cp39-cp39-macosx_10_9_x86_64.whl", extras = ["transformers"], sys_platform = "== 'darwin'"}
```
it doesn't lock as 'spacy-darwin' but rather just 'spacy' it also doesn't include the sys_platform markers. Maybe this is correct behavior and what I'm trying to do isn't supposed to be supported...

### Steps to replicate

Create a Pipfile with the above lines and attempt to create a lock file.

-------------------------------------------------------------------------------

Pipenv version: `'2023.2.4'`

OS Name: `'posix'`

User pip version: `'22.3.1'`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.11.1',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '22.1.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT '
                     '2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103',
 'python_full_version': '3.11.1',
 'python_version': '3.11',
 'sys_platform': 'darwin'}
```

**Comment by matteius** [comment]
@elanou I think this has been the case for a long time, do you recall what version this last "worked" on?  I am not sure we can go back to supporting naming a package different than is expected for the lock file, but I think named package categories can accomplish what you want.   Basically create an alternate category for the other version of `spacy` that you want, maybe this category is called `darwin` ... but then you lock it on a darwin system and install that category on the relevant systems, and you'd probably want to pull the other spacy version out into a different separate category so it wouldn't conflict with the darwin  category.  Let me know if you have any follow-up questions.

**Comment by elanou** [comment]
> if you h

Last know version was probably some time around August 2022 or shortly before. These named categories are a great feature and it seems like it should accomplish what I am trying to do. Thank you!
