### ISSUE TITLE
Pipenv commands hang due to error removing already deleted venv

### ISSUE THREAD

**Issue by ben-briant** [pypa/pipenv#5633]
### Issue description

Running `pipenv install` (or any other `pipenv` command) hangs forever. When killed, prints the following error message:
```
$ pipenv install --verbose
^CEnvironment creation aborted.
Error:  An error occurred while removing /home/ben/.local/share/virtualenvs/backend-izEVafBv!
[Errno 2] No such file or directory: '/home/ben/.local/share/virtualenvs/backend-izEVafBv'
```

The virtualenv directory does not exist, so presumably `pipenv` should just ignore this, and continue with creating a new one?

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2023.2.18'`

Pipenv location: `'/home/ben/.local/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

OS Name: `'posix'`

User pip version: `'23.0.1'`

user Python installations found:

  - `3.9.16`: `/usr/bin/python3.9`
  - `3.9.16`: `/bin/python3.9`
  - `3.8.10`: `/usr/bin/python3.8`
  - `3.8.10`: `/usr/bin/python3`
  - `3.8.10`: `/bin/python3.8`
  - `3.8.10`: `/bin/python3`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python`
  - `2.7.18`: `/usr/bin/python2.7`
  - `2.7.18`: `/bin/python2`
  - `2.7.18`: `/bin/python`
  - `2.7.18`: `/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.10',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.15.90.1-microsoft-standard-WSL2',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Fri Jan 27 02:56:13 UTC 2023',
 'python_full_version': '3.8.10',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `HOSTTYPE`
  - `LANG`
  - `PATH`
  - `TERM`
  - `XDG_RUNTIME_DIR`
  - `DISPLAY`
  - `WAYLAND_DISPLAY`
  - `PULSE_SERVER`
  - `WSL2_GUI_APPS_ENABLED`
  - `WSLENV`
  - `WT_SESSION`
  - `WT_PROFILE_ID`
  - `WSL_INTEROP`
  - `NAME`
  - `HOME`
  - `USER`
  - `LOGNAME`
  - `SHELL`
  - `WSL_DISTRO_NAME`
  - `SHLVL`
  - `PWD`
  - `OLDPWD`
  - `SSH_AUTH_SOCK`
  - `SSH_AGENT_PID`
  - `P9K_TTY`
  - `_P9K_TTY`
  - `ZSH`
  - `EDITOR`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `LS_COLORS`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `FZF_DEFAULT_COMMAND`
  - `P9K_SSH`
  - `NVM_DIR`
  - `NVM_CD_FLAGS`
  - `NVM_BIN`
  - `NVM_INC`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/ben/.nvm/versions/node/v17.7.2/bin:/home/ben/bin:/home/ben/bin:/usr/local/bin:/home/ben/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/dotnet/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Users/bencb/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/bencb/AppData/Local/Programs/Microsoft VS Code/bin:/home/ben/.local/bin:/home/ben/.cabal/bin:/home/ben/.ghcup/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `EDITOR`: `vim`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/home/ben/random/backend`

---------------------------

Contents of `Pipfile` ('/home/ben/random/backend/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
sse-starlette = "*"
asyncio = "*"
fastapi = {extras = ["all"], version = "*"}

[dev-packages]
black = "*"

[requires]
python_version = "3.10"

```

</details>

**Comment by matteius** [comment]
Hmmm, I didn't think pipenv install should be trying to remove the virtualenv anyway, I wonder if something else is going on.  `pipenv --rm` is what removes a virtualenv.  Do you have any more details you could share?

**Comment by matteius** [comment]
@ben-briant did you see my last comment and any additional details you can share?

**Comment by ben-briant** [comment]
Ah, apologies -- I completely forgot about this!
In the end I just reinstalled `pipenv` and it worked, so I think it was just something incorrect about my installation. Thanks for following up though!

**Comment by amirhpd** [comment]
I had the same problem:
https://stackoverflow.com/questions/77366561/pipenv-stucks-while-creating-a-venv
