### ISSUE TITLE
Installation of private subdependencies fails since version 2022.3.23

### ISSUE THREAD

**Issue by mkp-bartsch** [pypa/pipenv#5634]
Hello all, 
We use Pipenv in our company to create our Python environments.

Since the Pipenv version 2022.3.23 the creation of the Pipenv does not work as usual. 

### Basics

We run our own Pypi server, which is configured as [[source]] in the pipfile. The credentials, username and password, are used by pipenv during execution through environment variables. 
We unfortunately have private package names that also exist on the public package server, so it is important that the correct index is resolved per package. 
As Python version we used 3.8.x. The behavior described below is reproducible with all 3.8 versions. PyCharm is used as IDE. But this plays only a minor role, because the behavior occurs with PyCharm and in the terminal. 
As terminal bash is used. The variables unsername and password are in the .bashrc - file. Windows 11 is used as operating system. On MacOS the problem can be reproduced.

### Expected result
Previous behavior, pipenv version <= 2022.3.23:
Repository is cloned and pipenv install is used to install the project interpreter. 
Packages are correctly resolved and installed by the public and private pypi servers. Environment variables with credentials are deployed and resolved correctly. 

1. Go to directory and clone the repo
     > git clone git@github.com:MarxKrontalPartner/my-repo.git 
2. open cloned directory with pycharm. Open a new bash terminal and run:
    > pipenv install
3. pipenv installs the environment. Everything is fine and working as expected. 

### Issue description
Pipenv version >2022.3.23
If I use a newer pipenv version, errors occur in the same process. We have sub-dependencies in our private packages, which are also private packages. Pipenv does not consider that the sub dependencies must also be installed from the private pypi server.

### bash.rc
Username and password are replaced with dummy values.
```
export PYPI_USER=PrivatePypiUser
export PYPI_PASSWORD=PrivatePypiPassword
````

### Pipfile
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[[source]]
name = "Packages"
url = "https://$PYPI_USER:$PYPI_PASSWORD@pypi.myserver.com/"
verify_ssl = true

[dev-packages]
pipenv-setup = "*"
pytest = "*"
vistir = "==0.6.1"

[packages]
numpy = "*"
pandas = "*"
azure-logging = {index = "Packages", version = ">=1"}

[requires]
python_version = "3.8"

```

### pipfile.lock
Here is the generated pipfile.lock. I added the txt file extension to upload the file (.lock is not allowed)

[Pipfile.lock.txt](https://github.com/pypa/pipenv/files/11000534/Pipfile.lock.txt)

Let's focus the package azure-logging: The package azure-logging was resolved correctly, with the latest version and also the index was transferred correctly to the pipfile.lock. 
(You also find this block in the attached pipfile.lock.

```
        "azure-logging": {
            "hashes": [
                "sha256:98b22d0a9bf9371ad1a2973614b5a08c12f736c9e23c02560470cd7cadbfab9c"
            ],
            "index": "Packages",
            "version": "==1.0+20.gc88e586.dirty"
        },
```

The azure-logging package has sub dependencies, which also must get loaded from the private pypi server. In this case for example a package called adx-connector. This sub dependency package is also a pyhton package with a pipfile. This is structured and configured like the private dependencies in the attached pipfile. 
After pipenv created the pipfile.lock file, the setup of the project environment runs into an error. 

As described this dependency is resolved correctly with a previous pypi version (2022.2.23)

### pipenv install logs
The last log entries describe, that the version "None" of package "adx-connector" could not get found. 

```
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement adx-connector==0.2+1.g5eb7a93.dirty (from versions: none)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for adx-connector==0.2+1.g5eb7a93.dirty
```

Here is the complete log:
[pipenv_install_logs.txt](https://github.com/pypa/pipenv/files/11000749/pipenv_install_logs.txt)

It seems that pipenv no longer loads private sub-attachments since version 2022.2.23.

**Comment by matteius** [comment]
@mkp-bartsch I haven't had a chance to really dig in to your report, but assuming its accurate, my guesses would be it could be one of two things:
1.) The change to introspect pip.conf/pip.ini for help in determining desired indexes.
2.) The upgrade to pip 23.x

Does locking work and just install is failing, or is this a resolution issue as well?   If just install is failing, have you tried adding install_search_all_sources = true option to your Pipfile in the pipenv section:
```
[pipenv]
install_search_all_sources = true
```

**Comment by mkp-bartsch** [comment]
@matteius, thanks for the quick reply!

1.) I checked the directories for pip.conf / pip.ini, which get returned by following command, but these files don't exist. They are optional, so that's seems to be okay.
> pip config -v list
2.) The upgrade from pip 21.x to 23.x did not change the behaviour. 

Thats right. The locking works fine but the install process is failing. Resolution is working. 
I added your suggestion to the Pipfile. Same behaviour and same error.

In addition, I compared the pipfile.lock files of version 2022.3.23 (working pipenv version) and current version 2023.2.18 (> 2022.3.23 installing fails). 
The only difference between the two files is that the subdependencies also get hashes added. This looks more correct than before. 
It is noticeable that in both versions the index is not set. adx-connector is a package that should also be installed from the private pypi server. The package listed in the dependencies of the package azure-logging. 
<img width="983" alt="pipfile lock comparison subdependency" src="https://user-images.githubusercontent.com/67417735/226030025-4d2faebf-7294-4c81-86a4-2c14ad82a633.png">


In comparison, the index in both pipfile.lock files for azure-logging, i.e. the package that is the dependency in the example, is set correctly. 
<img width="977" alt="pipfile lock comparison project dependency" src="https://user-images.githubusercontent.com/67417735/226030505-e0c2bfb9-6287-408e-a1fc-a0069700a63f.png">

With this I could understand why adx-connector is not found. the old pipenv version installed these packages anyway. 
This in turn means that the index of subdependencies cannot be read from setup.py?

Thanks in advance

**Comment by matteius** [comment]
Thanks @mkp-bartsch -- we have a blip in the pip env documentation (the new version of which should release this weekend) but its already there, suggests from pip that to do just as you did an mirror all the relevant pypi dependencies.  As you discovered it is not possible yet for pipenv to infer indexes from the setup.py and generally you have to call out the primary index in the file is the default, and any secondary packages need to call out explicitly in the Pipfile for the indexes to work out.  Thanks for your detailed analysis!
