### ISSUE TITLE
`pipenv lock -r` command was not found.

### ISSUE THREAD

**Issue by KANGSangUn** [pypa/pipenv#5640]
I want to Copy package Dependency the requirements.txt
In the past, I used this command to record dependencies, but now not working.
I checked the release notes, but nothing related came up.

```
$ pipenv lock -r -d > requirements.txt
Usage: pipenv lock [OPTIONS]
Try 'pipenv lock -h' for help.

Error: No such option: -r
```

I use pipenv 2023.3.20.
```
$ pipenv --version
pipenv, version 2023.3.20
```

**Comment by KANGSangUn** [comment]
https://github.com/pypa/pipenv/issues/5253
I found solution. Thank you!

**Comment by matteius** [comment]
@KANGSangUn Middle of last year that options was replaced by the `pipenv requirements` command.
