### ISSUE TITLE
`pipenv upgrade` doesn't handle `--index`

### ISSUE THREAD

**Issue by danstewart** [pypa/pipenv#5692]
### Issue description

It doesn't look like `pipenv upgrade` handles the `--index` flag.

### Expected result

It uses the specified index.

### Actual result

The error message isn't clear but I think it's trying to install from PyPI.

### Steps to replicate

To simplify I've made a new directory and only added a single dependency:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "URL TO PRIVATE REGISTRY"
verify_ssl = true
name = "priv"

[packages]
thing = {version = "==4.3.2", index = "priv"}

[requires]
python_version = "3.11"
```

Running `pipenv upgrade --index priv thing` fails but `pipenv install --index priv thing` works

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2023.4.29'`

Pipenv location: `'/home/dan/.local/pipx/venvs/pipenv/lib64/python3.11/site-packages/pipenv'`

Python location: `'/home/dan/.local/pipx/venvs/pipenv/bin/python'`

OS Name: `'posix'`

User pip version: `'23.1.2'`

user Python installations found:

  - `3.11.3`: `/usr/bin/python`
  - `3.11.3`: `/usr/bin/python3`
  - `3.10.10`: `/home/dan/.asdf/installs/python/3.10.10/bin/python3`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.11.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '6.2.15-300.fc38.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT_DYNAMIC Thu May 11 17:37:39 UTC 2023',
 'python_full_version': '3.11.3',
 'python_version': '3.11',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `SESSION_MANAGER`
  - `WINDOWID`
  - `COLORTERM`
  - `LESS`
  - `HISTCONTROL`
  - `XDG_MENU_PREFIX`
  - `FORGIT_INSTALL_DIR`
  - `HOSTNAME`
  - `HISTSIZE`
  - `SSH_AUTH_SOCK`
  - `XMODIFIERS`
  - `DESKTOP_SESSION`
  - `SSH_AGENT_PID`
  - `KITTY_PID`
  - `ERG_PATH`
  - `EDITOR`
  - `PWD`
  - `XDG_SESSION_DESKTOP`
  - `LOGNAME`
  - `XDG_SESSION_TYPE`
  - `MANPATH`
  - `SYSTEMD_EXEC_PID`
  - `BUILDKIT_PROGRESS`
  - `XAUTHORITY`
  - `GEMFURY_TOKEN`
  - `KITTY_PUBLIC_KEY`
  - `FORGIT_GI_TEMPLATES`
  - `GJS_DEBUG_TOPICS`
  - `GDM_LANG`
  - `HOME`
  - `USERNAME`
  - `LANG`
  - `LS_COLORS`
  - `XDG_CURRENT_DESKTOP`
  - `WAYLAND_DISPLAY`
  - `AWS_PAGER`
  - `KITTY_WINDOW_ID`
  - `PROMPT_COMMAND`
  - `INVOCATION_ID`
  - `DOCKER_BUILDKIT`
  - `MANAGERPID`
  - `FORGIT_GI_REPO_REMOTE`
  - `GJS_DEBUG_OUTPUT`
  - `NVM_DIR`
  - `MOZ_GMP_PATH`
  - `GNOME_SETUP_DISPLAY`
  - `COMPOSE_DOCKER_CLI_BUILD`
  - `XDG_SESSION_CLASS`
  - `TERMINFO`
  - `TERM`
  - `BAT_PAGER`
  - `ASDF_DIR`
  - `LESSOPEN`
  - `USER`
  - `SUDO_EDITOR`
  - `VISUAL`
  - `DISPLAY`
  - `SHLVL`
  - `PAGER`
  - `QT_IM_MODULE`
  - `FORGIT_GI_REPO_LOCAL`
  - `XDG_RUNTIME_DIR`
  - `PS1`
  - `DEBUGINFOD_URLS`
  - `JOURNAL_STREAM`
  - `XDG_DATA_DIRS`
  - `PATH`
  - `HISTIGNORE`
  - `GDMSESSION`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `FZF_DEFAULT_OPTS`
  - `MAIL`
  - `KITTY_INSTALLATION_DIR`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `OLDPWD`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/dan/.poetry/bin:/home/dan/.asdf/shims:/home/dan/.asdf/bin:/home/dan/.cargo/bin:/home/dan/bin:/home/dan/.local/bin:/usr/local/go/bin:/home/dan/.cargo/bin/:/usr/local/go/bin/:/home/dan/go/bin/:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/dan/.local/share/JetBrains/Toolbox/scripts`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `nvim`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/dan/tw/x`

</details>

</summary>

**Comment by matteius** [comment]
@danstewart I have attempted a patch:  https://github.com/pypa/pipenv/pull/5693

Update/upgrade were ignoring the index url altogether--if you could help validate if this solves the issue it would be appreciated.

**Comment by matteius** [comment]
New version of pipenv with fix has been released.
