### ISSUE TITLE
Specifying categories when installing from a requirements.txt

### ISSUE THREAD

**Issue by kaine-bruce-dmt** [pypa/pipenv#5722]
I am converting an in-house python project to use pipenv.

We have 9 different requirements.txt depending on what stage of the build/testing we're at, each with a different name.

As such we're looking to use [categories](https://pipenv.pypa.io/en/latest/specifiers/#specifying-package-categories)

I was surprised when the below didn't work (it adds it to [packages])
```
pipenv install -r ./req-test.txt --categories test
```

When this does:

```
pipenv install -r ./req-test.txt --dev
```

### Describe the solution you'd like

```
#req-test.txt
requests
```

```bash
pipenv install -r ./req-test.txt --categories test
```

```
#Pipfile

[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[test]
requests = "*"

[requires]
python_version = "3.10"

```

I realise this might be a strange use case, but I just thought it made sense :)

**Comment by matteius** [comment]
It makes sense, I am just short on time to work on all these enhancement requests, so I am hoping that someone else will pick this one up since it seems straight forward.

**Comment by kaine-bruce-dmt** [comment]
No worries Matt! If I get some free time myself, I might have a looksie.

**Comment by DasaniT** [comment]
Hi, is this still open and if so can I work on this?
if yes, should I add a new option like `--category` or use `--categories`? because giving multiple options here is not really meaningful.

**Comment by kaine-bruce-dmt** [comment]
Yes, fill your boots! `--categories` is probably the way to go. Keeps it in line with what we currently have.

**Comment by DasaniT** [comment]
> Yes, fill your boots! `--categories` is probably the way to go. Keeps it in line with what we currently have. I do see your point, but maybe someone does want to install `requirements.txt` into multiple categories _shrug_.

Sure! One question though, when multiple categories is given, should I add the packages to all of the categories or something else is the desired behavior?
