### ISSUE TITLE
When installing psycopg2 or mysqlclient, the following is displayed:

### ISSUE THREAD

**Issue by waouxiful** [pypa/pipenv#5726]
pipenv install psycopg2
Installing psycopg2...
Resolving psycopg2...
Adding psycopg2 to Pipfile's [packages] ...
✔ Installation Succeeded
Pipfile.lock (e4eef2) out of date, updating to (cc64ce)...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
⠋ Locking...
ERROR:pip.subprocessor:[present-rich] python setup.py egg_info exited with 1
[ResolutionFailure]:   File "/home/sergii/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 811, in _main
[ResolutionFailure]:       resolve_packages(
[ResolutionFailure]:   File "/home/sergii/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 759, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/home/sergii/.local/lib/python3.10/site-packages/pipenv/resolver.py", line 738, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/home/sergii/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 1154, in resolve_deps
[ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
[ResolutionFailure]:   File "/home/sergii/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 953, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/home/sergii/.local/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 700, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: metadata generation failed

**Comment by matteius** [comment]
Please provide additional details, I am not able to reproduce:

```
matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/pipenv-triage/issue-5726
$ pipenv install psycopg2
Creating a virtualenv for this project...
Pipfile: C:\Users\matte\Projects\pipenv-triage\issue-5726\Pipfile
Using default python from C:\Users\matte\AppData\Local\Programs\Python\Python311\python.exe (3.11.2) to create virtualenv...
[====] Creating virtual environment...created virtual environment CPython3.11.2.final.0-64 in 3902ms
  creator CPython3Windows(dest=C:\Users\matte\.virtualenvs\issue-5726-l9kvJmcD, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\matte\AppData\Local\pypa\virtualenv)
    added seed packages: pip==23.1.2, setuptools==67.7.2, wheel==0.40.0
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Successfully created virtual environment!
Virtualenv location: C:\Users\matte\.virtualenvs\issue-5726-l9kvJmcD
Creating a Pipfile for this project...
Installing psycopg2...
Resolving psycopg2...
Adding psycopg2 to Pipfile's [packages] ...
Installation Succeeded
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
Success!
Locking [dev-packages] dependencies...
Updated Pipfile.lock (f97f0e50534e142f05d9d226aa3d30214d87693285b782f7f5565930de3fec13)!
Installing dependencies from Pipfile.lock (3fec13)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/pipenv-triage/issue-5726
$ pipenv --version
pipenv, version 2023.6.3.dev0
```

**Comment by waouxiful** [comment]
Oh, sorry, I already fixed it, I installed a later version pipenv.Thank you for the answer
