### ISSUE TITLE
Documentation Missing  for Importing From Requriements

### ISSUE THREAD

**Issue by txoof** [pypa/pipenv#5758]
The link to "[importing from requirements"](https://pipenv.pypa.io/en/latest/basics/#importing-from-requirements-txt) is broken.

Link from documentation yields 404.

**Comment by matteius** [comment]
I'll be honest, I have no idea what the fix is for this yet -- if someone has some bandwidth to open a PR.

**Comment by IamPreethi-S** [comment]
Hey, would like to know if the issue is still open?
I would like to take it up and contribute.
Thanks:)

**Comment by txoof** [comment]
The link is still busted - I'd certainly appreciate the documentation!

**Comment by oz123** [comment]
> The link is still busted - I'd certainly appreciate the documentation!

How did you reach this link? Is it in your bookmarks? Can you point to what points to this in the docs?

**Comment by txoof** [comment]
@oz123 

It looks like it's been repaired since I last tried to get there. 

Here's how I got there originally:

1. browse to https://pipenv.pypa.io/en/latest/
2. click on "importing from requirements.txt"


I'll consider this fixed and closed.
