### ISSUE TITLE
"pipenv requirements" command doesn't export "extras" since version 2023.7.1

### ISSUE THREAD

**Issue by apolain** [pypa/pipenv#5783]
# Description 
My problem could be linked to [issue 5780](https://github.com/pypa/pipenv/issues/5780).

In one of my projects, I use certain packages with "extras" ([django-storages[azure]](https://django-storages.readthedocs.io/en/latest/backends/azure.html))
Since version 2023.7.1, the *pipenv requirements* command ignores extras. As a result, the version specified in the Pipfile does not correspond to the version exported by *pipenv requirements*.

# How to reproduct

My Pipfile looks like :

```
[packages]
[...]
django-storages = {version = "<1.13", extras = ["azure"]}
[...]
```

Before version 2023.7.1, *pipenv requirements* led me to: 

```
$ pipenv --version 
2023.6.26

$ pipenv requirements
[...]
django-storages[azure]==1.12.3
[...]
```

And now I only have:
```
$ pipenv --version 
2023.7.4

$ pipenv requirements
[...]
django-storages==1.12.3
[...]
```

**Comment by matteius** [comment]
Same as issue #5780

**Comment by matteius** [comment]
Actually this is maybe a different issue.

**Comment by matteius** [comment]
I'm taking a shot a PR now for this issue.

**Comment by matteius** [comment]
I've tagged a PR that I think should fix this, if you could have a try and help determine if it still needs work (even added some test cases).

**Comment by apolain** [comment]
Thank you very much, you've been so quick ! I try in the day and let you know  :)

**Comment by apolain** [comment]
Hi @matteius, I confirm that the bug has been corrected with your changes. I see nothing more to add to this issue. Thank you again ! :)
