### ISSUE TITLE
Platform specific installs are not respected when using file with a url

### ISSUE THREAD

**Issue by kaine-bruce-dmt** [pypa/pipenv#5785]
### Issue description

The below entry in a Pipfile does not seem to be respected on Linux. I believe we have followed the correct syntax.

This is using our in-house package, as such I have redacted some parts.

I can privately share our pipenv support output if needed.

```
$ pipenv --version
pipenv, version 2023.7.9
```

### Expected result

The package should be skipped on operating systems that are not Windows.

### Actual result

On Ubuntu:
![Screenshot 2023-07-10 142419](https://github.com/pypa/pipenv/assets/131783606/ae9c3afb-0c2f-49f5-ba23-fe1847b9d064)

### Steps to replicate

```
#Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
package_name= { sys_platform = "== 'win32'", file = "https://{REDACTED}.whl"}

[requires]
python_version = "3.10"
```

```
# cmd
pipenv install
```

**Comment by matteius** [comment]
@kaine-bruce-dmt I got somewhere with this finally, if you want to take a look/try out the draft PR:  https://github.com/pypa/pipenv/pull/5871

**Comment by matteius** [comment]
@lewiswolf I think the problem from your example is we handle either specifying a git repository without the egg, or we support it with the ref and and the egg, but you appear to not be suppling a ref, but just an egg.  So for example:  `pip install "git+https://github.com/lewiswolf/graphs.git@main#egg=graphs"`

**Comment by lewiswolf** [comment]
so the second example is expected behaviour also, i.e `pipenv install "git+https://github.com/lewiswolf/graphs.git"`
