### ISSUE TITLE
On Windows,  specifying a **relative path** in "pipenv install" command  occurs OSError: Bad Path 

### ISSUE THREAD

**Issue by alumuko** [pypa/pipenv#5789]
### Issue description

On Windows, specifying a **relative path** in "pipenv install" command as shown below will result in "OSError: Bad path: C;\C:".
(The drive letter "C" appears twice)

`pipenv install ./../packages/pyparsing-3.1.0-py3-none-any.whl
`
### Expected result

On Linux, same command is no problem. (Success)

On Windows, "pipenv run pip install" does not cause this problem. (Success)
However, I prefer to use "pipenv install" because "pip install" does not save the installation information into the Pipfile.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2023.7.11'`

Pipenv location: `'C:\\Users\\Main User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pipenv'`

Python location: `'C:\\Users\\Main User\\AppData\\Local\\Programs\\Python\\Python311\\python.exe'`

OS Name: `'nt'`

User pip version: `'23.1.2'`

user Python installations found:

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.11.1',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.19045',
 'python_full_version': '3.11.1',
 'python_version': '3.11',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DRIVERDATA`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PIPENV_VENV_IN_PROJECT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VBOX_MSI_INSTALL_PATH`
  - `WINDIR`
  - `__PSLOCKDOWNPOLICY`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `true`

---------------------------

Contents of `Pipfile` ('D:\\Develop\\pipenv-test\\testapp\\Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
pyparsing = {path = "./../packages/pyparsing-3.1.0-py3-none-any.whl"}

[dev-packages]

[requires]
python_version = "3.11"
python_full_version = "3.11.1"

```

</details>
```[tasklist]
### Tasks
```

**Comment by matteius** [comment]
Hmmm, I spent a bit of time trying to debug this last night and this bug is actually occurring in an internal pip method we call, which is odd seeing as pip handles the same command just fine.

**Comment by matteius** [comment]
@alumuko This appears to also be solved on the branch that drops requirementslib:  https://github.com/pypa/pipenv/pull/5793
```
matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/pipenv-triage/issue-5789
$ pipenv install ./../../pyparsing-3.1.0-py3-none-any.whl
Creating a virtualenv for this project...
Pipfile: C:\Users\matte\Projects\pipenv-triage\issue-5789\Pipfile
Using default python from C:\Users\matte\AppData\Local\Programs\Python\Python311\python.exe (3.11.2) to create virtualenv...
[   =] Creating virtual environment...created virtual environment CPython3.11.2.final.0-64 in 6921ms
  creator CPython3Windows(dest=C:\c\users\matte\.virtualenvs\issue-5789-EmqWSKte, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\matte\AppData\Local\pypa\virtualenv)
    added seed packages: pip==23.1.2, setuptools==68.0.0, wheel==0.40.0
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Successfully created virtual environment!
Virtualenv location: C:\c\Users\matte\.virtualenvs\issue-5789-EmqWSKte
Creating a Pipfile for this project...
Installing ./../../pyparsing-3.1.0-py3-none-any.whl...
Resolving ./../../pyparsing-3.1.0-py3-none-any.whl...
Added pyparsing to Pipfile's [packages] ...
Installation Succeeded
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
Success!
Locking [dev-packages] dependencies...
Updated Pipfile.lock (fa664f03c27244ed293d2222cd14a32c1e8a0f01e4a72589b88b02ef25e4f19a)!
Installing dependencies from Pipfile.lock (e4f19a)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/pipenv-triage/issue-5789
$ cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
pyparsing = {file = "..\\..\\pyparsing-3.1.0-py3-none-any.whl"}

[dev-packages]

[requires]
python_version = "3.9"

matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/pipenv-triage/issue-5789
$ cat Pipfile.lock
{
    "_meta": {
        "hash": {
            "sha256": "fa664f03c27244ed293d2222cd14a32c1e8a0f01e4a72589b88b02ef25e4f19a"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.9"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "pyparsing": {
            "editable": true,
            "file": "..\\..\\pyparsing-3.1.0-py3-none-any.whl",
            "hashes": [
                "sha256:d554a96d1a7d3ddaf7183104485bc19fd80543ad6ac5bdb6426719d766fb06c1"
            ],
            "markers": "python_full_version >= '3.6.8'"
        }
    },
    "develop": {}
}
```

**Comment by ROT-at-OpenEP** [comment]
Has this issue been fixed by now? What needs to be updated? Package pip or pipenv or both?

**Comment by matteius** [comment]
@ROT-at-OpenEP as mentioned in my last comments, there is a forward looking branch that I believe fixes this issue.    https://github.com/pypa/pipenv/pull/5793
