### ISSUE TITLE
Dependency resolver fails for private package registry sub-dependencies (order matters).

### ISSUE THREAD

**Issue by kalebmckale** [pypa/pipenv#5834]
### Issue description

When locking `Pipfile` containing dependencies from private package registry, the dependency resolver fails due to "conflicting dependencies." However, installing without locking succeeds and locking from a requirements file produced from the installed environment by running `pip freeze` also succeeds. The verbose output does reveal though that all of the private package registry dependencies being installed have no version specifications.

### Expected result

The expectation is that dependencies without version specifications would work as they do for those in PyPI, or at least as I intuit they do, instead of showing the shared dependencies as conflicting one another.

### Actual result

Unable to provide exact output but here are the essential details:

- `package-A` in `Pipfile` belongs to `private-pypi`
- `package-A` has dependencies `package-B` and `package-C` also in `private-pypi`.
- all private packages discussed here are specified without version specifications both in `Pipfile` and within their `private-pypi` wheels or source distributions.
- `package-B` and `package-C` share a common `private-pypi` dependency `package-D`.
- There are multiple versions of each of the packages in `private-pypi`.

Sample output (abridged)
```
There is a package conflict.
package-A-1.0.0 has dependency package-B
package-A-1.0.1 has dependency package-B
package-A-1.1.0 has dependency package-B
...
```

- This happens for each `private-pypi` dependency that has no version specification.
### Steps to replicate

`pipenv lock`

```
[[source]]
url = "https://private-pypi.mycompany.com/simple"
verify_ssl = false
name = "mycompany-pypi"

[packages]
package-A = {version = "*", index = "mycompany-pypi"}
```

### Work-around

However, while experimenting I discovered another way to lock the file by looking up the latest version number of the package failing and then adding to `Pipfile`. This included both direct dependencies of my package and all of the `private-pypi` sub-dependencies that showed to be point of failure as the previous one was added, ending up with a `Pipfile` that looked like this:

```
[[source]]
url = "https://private-pypi.mycompany.com/simple"
verify_ssl = false
name = "mycompany-pypi"

[packages]
package-A = {version = ">=1.1.0", index = "mycompany-pypi"}
package-B = {version = ">=0.1.3", index = "mycompany-pypi"}
package-C = {version = ">=2.0.0", index = "mycompany-pypi"}
package-D = {version = ">=2.1.0", index = "mycompany-pypi"}
```

Early in the experimentation, when I attempted to specify a version using `major.minor`, it still failed even if there were only two possible versions available. Essentially, I had to pin the versions of each of the packages manually after which the locking process completed.

-------------------------------------------------------------------------------

Unable to provide output to `pipenv --support`.

### Update after more testing

After some additional testing (using v2023.8.21), here’s what clear: order matters and version specification does not.

It seems that the sub-dependencies of whichever packages come from the index that is the second (or later) source do not get resolved correctly. Here’s what I mean:

When PyPI mirror was listed first in Pipfile, the dependencies and any sub-dependencies of those dependencies that belong to PyPI were resolved and successful while the sub-dependencies belonging to the Private PyPI were apparently unable to be located, causing the dependencies to which the sub-dependencies belonged to fail.

To my surprise, when I merely swapped the order of the two sources in the Pipfile, the situation reversed, that is, common PyPI packages were failing because it was unable to locate sub-dependencies.

I misinterpreted the original verbose output, when it was saying all the various versions had the same dependency (`package-B`), it was saying that this was an unsatisfiable requirement because it couldn’t locate it. This is not presented in any of the verbose output from `pip` no matter how verbose you make it. I ended up doing a lot of `print` statement debugging all the way back to the `RLResolver` to see why the various `candidates` were being rejected.

What seems to be happening (for some reason) is that sub-dependencies of packages, no matter from which PyPI package registry they come, are searched for within the `--index-url`, which is defined by `pipenv` to be `sources[0]`, and not in any of `--extra-index-url`. The verbose output and my `print` debugging showed that both indices were set for `pip`, but what’s happening deep within the bowels of the `Resolver`, I am uncertain as `print` debugging can only take you so far when dealing with a monolith of a package like `pip`. Hopefully, someone else understands all of this much better than I.

**Comment by matteius** [comment]
@kalebmckale can you check this on `2023.8.19`?  I think the issue might have been that for it to work prior you needed `==*` but that is just what I recall.

**Comment by kalebmckale** [comment]
Hey @matteius! I was able to test with `2023.8.21` today and really played around and dug deep into the code. I updated the title and description above to reflect the new discoveries.

**Comment by matteius** [comment]
Ah I see now -- yes we intentionally removed support for `--extra-index-urls` last year in favor of requiring index restricted packages for security reasons (to prevent package confusion attacks).   This means the default index is always used for resolution and transitive dependencies will resolve to the default index unless otherwise specified in the Pipfile.  It is recommended to mirror relevant pypi packages to the private index in cases where specifying them in the Pipfile is problematic because there are too many.

**Comment by kalebmckale** [comment]
The two repositories are separate and cannot mirror the packages. I do see why this could be an issue. Without `pip` adopting the more secure position and/or perhaps Python itself to store both the index and dependency information in `pyproject.toml`, this will always be an issue for multi-index workflows involving sub-dependencies. I suppose that's where `--skip-lock` had a role since, in these cases, one could first skip and then lock after the resolution was completed. Hmmmm...🤔 I need to think about this some more.
