### ISSUE TITLE
pipenv update --outdated became noisy

### ISSUE THREAD

**Issue by BorgPrincess** [pypa/pipenv#5854]
### Issue description

`pipenv update --outdated` writes extensive INFO logs to console.
Flags `--bare` and `--quiet` do not change this.
The new behaviour began in release 2023.8.19 and persists at least through release 2023.8.22.

### Expected result

Console output _without added flags_; possibly less with `--bare` or `--quiet`:

```
Running $ pipenv lock then $ pipenv sync.
Building requirements...
Resolving dependencies...
✔ Success!
Building requirements...
Resolving dependencies...
✔ Success!
Building requirements...
Resolving dependencies...
✔ Success!
Building requirements...
Resolving dependencies...
✔ Success!
All packages are up to date!

```

### Actual result

More than 120k of log output to the console:
[pipenv.log.txt](https://github.com/pypa/pipenv/files/12408204/pipenv.log.txt)

### Steps to replicate

Any one of

`pipenv update --outdated`
`pipenv --bare update --outdated`
`pipenv --quiet update --outdated`

-------------------------------------------------------------------------------

[pipenv.support.txt](https://github.com/pypa/pipenv/files/12408219/pipenv.support.txt)

**Comment by phette23** [comment]
To add to this, even with `PIPENV_QUIET=true` or `--quiet` the command is still noisy, filled with `INFO:pipenv.patched.pip...` messages.

**Comment by matteius** [comment]
We'll want to figure out how to make those flags reduce the output, without breaking verbose again.   The line I removed that caused this was just globally silencing the pip logging which was leading to a lot of reports where folks could not debug why their lock phases were failing.

**Comment by matteius** [comment]
I believe https://github.com/pypa/pipenv/pull/5897 solves for this.

**Comment by BorgPrincess** [comment]
Yes, it does!
Thank you very much! :D
