### ISSUE TITLE
ANSI escape codes display in usage text

### ISSUE THREAD

**Issue by BillSchumacher** [pypa/pipenv#5869]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

The color escape codes display when using a Mac and zsh.

<img width="629" alt="image" src="https://github.com/pypa/pipenv/assets/34168009/630c23b6-437b-4140-8b9b-a615e6c1223a">

### Expected result

The colors to appear and not show color codes.

### Actual result

Only some of the colors are working.

### Steps to replicate

Install latest on a Mac with zsh.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2023.8.23'`

Pipenv location: `'/Users/billschumacher/.local/lib/python3.10/site-packages/pipenv'`

Python location: `'/Users/billschumacher/.pyenv/versions/3.10.6/bin/python3.10'`

OS Name: `'posix'`

User pip version: `'23.2.1'`

user Python installations found:

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.6',
 'os_name': 'posix',
 'platform_machine': 'arm64',
 'platform_python_implementation': 'CPython',
 'platform_release': '22.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT '
                     '2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020',
 'python_full_version': '3.10.6',
 'python_version': '3.10',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `NVM_INC`
  - `MANPATH`
  - `TERM_PROGRAM`
  - `NVM_CD_FLAGS`
  - `PYENV_ROOT`
  - `SHELL`
  - `TERM`
  - `PIPX_BIN_DIR`
  - `PIPENV_VENV_IN_PROJECT`
  - `HOMEBREW_REPOSITORY`
  - `TMPDIR`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `PYENV_VERSION`
  - `NVM_DIR`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `PYENV_DIR`
  - `PYENV_VIRTUALENV_INIT`
  - `PATH`
  - `LaunchInstanceID`
  - `__CFBundleIdentifier`
  - `PWD`
  - `LANG`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `PYENV_SHELL`
  - `SHLVL`
  - `HOME`
  - `HOMEBREW_PREFIX`
  - `LOGNAME`
  - `NVM_BIN`
  - `INFOPATH`
  - `HOMEBREW_CELLAR`
  - `SECURITYSESSIONID`
  - `__CF_USER_TEXT_ENCODING`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/billschumacher/.pyenv/versions/3.10.6/bin:/opt/homebrew/Cellar/pyenv/2.3.22/libexec:/opt/homebrew/Cellar/pyenv/2.3.22/plugins/python-build/bin:/Users/billschumacher/.pyenv/shims:/Users/billschumacher/.local/bin:/Users/billschumacher/.pyenv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/opt/openssl@3/bin:/opt/homebrew/opt/openssl@1.1/bin:/opt/homebrew/opt/libpq/bin:/Users/billschumacher/Library/Python/3.11/bin:/opt/homebrew/Cellar/pyenv-virtualenv/1.2.1/shims:/Users/billschumacher/.nvm/versions/node/v18.15.0/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/billschumacher/Library/Application Support/JetBrains/Toolbox/scripts`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/billschumacher`

---------------------------

</details>

**Comment by matteius** [comment]
Duplicates: #5850
