### ISSUE TITLE
documentation is a mix of markdown and restructuredtext

### ISSUE THREAD

**Issue by deronnax** [pypa/pipenv#5881]
### Issue description

documentation is a mix of markdown and restructuredtext, but the [documentation says the documentation is restructuredtext](https://pipenv.pypa.io/en/latest/dev/contributing/#documentation-contributions). I found out commit 761a03d seemingly did a conversion to markdown which did not go all the way to the end.
I would like to know what is the pursued direction (markdown + restructuredtext or full markdown), and if the direction is full markdown, try to help.

### Expected result

* either the documentation says the documentation is both markdown and restructuredtext
* either we clean out one of them (restructuredtext, I guess)

### Actual result

mix of both

### Steps to replicate

N/A

**Comment by matteius** [comment]
@deronnax Full markdown would be preferred I think; I ran out of time when I was working on that before.   Any help is appreciated.

**Comment by thiagogquinto** [comment]
Hey guys, I am new in open source community, if possible, could I be assigned to this task? Just to be clear, if I be assigned, once I start making the contribution, I converto to fully *md* or gully *rst*?

**Comment by matteius** [comment]
@thiagogquinto I believe @deronnax is offering to help with this, but either way -- the plan is to go fully markdown.  (so .md)

**Comment by thiagogquinto** [comment]
Ok @matteius, thanks for the reply! I will let him work on it then. Will just ask @deronnax that in case he changes of mind, let me know, please.

**Comment by deronnax** [comment]
@thiagogquinto I have not started the work, so you can take it :)

**Comment by thiagogquinto** [comment]
Thanks, I will work on it then.

**Comment by thiagogquinto** [comment]
Hey @matteius, could you help me with the following question: do you know what this reference points to?

```console
No, it does not, intentionally. Pipfile and setup.py serve different purposes,
and should not consider each other by default. See :ref:`pipfile-vs-setuppy`
for more information.
```
The file is [here](https://github.com/thiagogquinto/pipenv/blob/main/docs/diagnose.rst), the line in question is on the line 102 of the file.
