### ISSUE TITLE
Pipenv ignores development dependencies from pyproject.toml

### ISSUE THREAD

**Issue by dustalov** [pypa/pipenv#5915]
### Issue description

In my project, I specify all the dependencies in `pyproject.toml`: mandatory dependencies are in `project.dependencies`, development dependencies are in `project.optional-dependencies.dev`. Then, I define the `packages` and `dev-packages` sections of `Pipfile` accordingly. Before the latest version of Pipenv v2023.9.1, it respected the `--dev` flag and installed the dependencies correctly. Since the latest version, it stopped.

I created a sample minimal Gist to reproduce the issue: https://gist.github.com/dustalov/9abb5c67a6eb0e8fa0e3b93a46299a1a

Contents of `pyproject.toml`:

```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bug"
version = "0"
dependencies = ["urllib3"]

[project.optional-dependencies]
dev = ["mypy"]
```

Contents of Pipfile:

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
bug = {editable = true, path = "."}

[dev-packages]
bug = {editable = true, path = ".", extras = ["dev"]}
```

### Expected result

When I run `pipenv install --dev --system --skip-lock`, it should install both `urllib3` (as specified in `packages`) and `mypy` (as specified in `dev-packages`). Previous versions of Pipenv did this correctly.

### Actual result

Only the `urllib3` package is installed, but `mypy` is not.

<details><summary>pipenv install --dev --system --skip-lock --verbose</summary>

```
The flag --skip-lock has been reintroduced (but is not recommended).  Without the lock resolver it is difficult to manage multiple package indexes, and hash 
checking is not provided.  However it can help manage installs with current deficiencies in locking across platforms.
Installing dependencies from Pipfile...
Writing supplied requirement line to temporary file: '.'
Install Phase: Editable Requirements
Preparing Installation of '.'
$ /usr/local/Caskroom/mambaforge/base/envs/cw/bin/python3 
/usr/local/Caskroom/mambaforge/base/envs/cw/lib/python3.11/site-packages/pipenv/patched/pip/__pip-runner__.py install -i https://pypi.org/simple --no-input 
--upgrade -r /var/folders/d0/ldgxpyt126z62l9976k7nkdh0000gn/T/pipenv-do8nct0e-requirements/pipenv-rzl08zg_-reqs.txt
Processing /Users/dmitry/pipenv-bug

  Installing build dependencies: started

  Installing build dependencies: finished with status 'done'

  Getting requirements to build wheel: started

  Getting requirements to build wheel: finished with status 'done'

  Installing backend dependencies: started

  Installing backend dependencies: finished with status 'done'

  Preparing metadata (pyproject.toml): started

  Preparing metadata (pyproject.toml): finished with status 'done'

Requirement already satisfied: urllib3 in /usr/local/Caskroom/mambaforge/base/envs/cw/lib/python3.11/site-packages (from bug==0->-r 
/var/folders/d0/ldgxpyt126z62l9976k7nkdh0000gn/T/pipenv-do8nct0e-requirements/pipenv-rzl08zg_-reqs.txt (line 1)) (2.0.4)

Building wheels for collected packages: bug

  Building wheel for bug (pyproject.toml): started

  Building wheel for bug (pyproject.toml): finished with status 'done'

  Created wheel for bug: filename=bug-0-py3-none-any.whl size=911 sha256=bf119542182ffd28c93afaaf091ee8149a58257f342ebad4e2c6670c1ae21dea

  Stored in directory: /Users/dmitry/Library/Caches/pipenv/wheels/19/fb/33/bdce74a90bb4ca2b7121362bc3abfe9b279252ceaec986d3ae

Successfully built bug

Installing collected packages: bug

  Attempting uninstall: bug

    Found existing installation: bug 0

    Uninstalling bug-0:

      Successfully uninstalled bug-0

Successfully installed bug-0


Installing dependencies from Pipfile...
Writing supplied requirement line to temporary file: '.'
Install Phase: Editable Requirements
Preparing Installation of '.'
$ /usr/local/Caskroom/mambaforge/base/envs/cw/bin/python3 
/usr/local/Caskroom/mambaforge/base/envs/cw/lib/python3.11/site-packages/pipenv/patched/pip/__pip-runner__.py install -i https://pypi.org/simple --no-input 
--upgrade -r /var/folders/d0/ldgxpyt126z62l9976k7nkdh0000gn/T/pipenv-do8nct0e-requirements/pipenv-804tnd6t-reqs.txt
Processing /Users/dmitry/pipenv-bug

  Installing build dependencies: started

  Installing build dependencies: finished with status 'done'

  Getting requirements to build wheel: started

  Getting requirements to build wheel: finished with status 'done'

  Installing backend dependencies: started

  Installing backend dependencies: finished with status 'done'

  Preparing metadata (pyproject.toml): started

  Preparing metadata (pyproject.toml): finished with status 'done'

Requirement already satisfied: urllib3 in /usr/local/Caskroom/mambaforge/base/envs/cw/lib/python3.11/site-packages (from bug==0->-r 
/var/folders/d0/ldgxpyt126z62l9976k7nkdh0000gn/T/pipenv-do8nct0e-requirements/pipenv-804tnd6t-reqs.txt (line 1)) (2.0.4)

Building wheels for collected packages: bug

  Building wheel for bug (pyproject.toml): started

  Building wheel for bug (pyproject.toml): finished with status 'done'

  Created wheel for bug: filename=bug-0-py3-none-any.whl size=911 sha256=c54995ddc56edf6f6c478736f92d76242f8fa7eb54d9741c956a5891c5d59c38

  Stored in directory: /Users/dmitry/Library/Caches/pipenv/wheels/19/fb/33/bdce74a90bb4ca2b7121362bc3abfe9b279252ceaec986d3ae

Successfully built bug

Installing collected packages: bug

  Attempting uninstall: bug

    Found existing installation: bug 0

    Uninstalling bug-0:

      Successfully uninstalled bug-0

Successfully installed bug-0
```
</details>

### Steps to replicate

Run `pipenv install --dev --system --skip-lock` (I use this command in my CI workflows). Then confirm that `which mypy` could not find `mypy`.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2023.9.1'`

Pipenv location: `'/usr/local/Caskroom/mambaforge/base/envs/cw/lib/python3.11/site-packages/pipenv'`

Python location: `'/usr/local/Caskroom/mambaforge/base/envs/cw/bin/python3.11'`

OS Name: `'posix'`

User pip version: `'23.2.1'`

user Python installations found:

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.11.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '19.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT '
                     '2022; root:xnu-6153.141.66~1/RELEASE_X86_64',
 'python_full_version': '3.11.5',
 'python_version': '3.11',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_PROGRAM`
  - `SHELL`
  - `TERM`
  - `TMPDIR`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `PATH`
  - `PWD`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `HOME`
  - `LOGNAME`
  - `OLDPWD`
  - `BUNDLE_DISABLE_VERSION_CHECK`
  - `BUNDLE_VERSION`
  - `NO_UPDATE_NOTIFIER`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `RUBYOPT`
  - `CLICOLOR`
  - `HOMEBREW_NO_ANALYTICS`
  - `HOMEBREW_NO_ENV_HINTS`
  - `JAVA_HOME`
  - `CONDA_EXE`
  - `_CE_M`
  - `_CE_CONDA`
  - `CONDA_PYTHON_EXE`
  - `CONDA_SHLVL`
  - `CONDA_PREFIX`
  - `CONDA_DEFAULT_ENV`
  - `CONDA_PROMPT_MODIFIER`
  - `LC_CTYPE`
  - `_`
  - `__CF_USER_TEXT_ENCODING`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/Caskroom/mambaforge/base/envs/cw/bin:/usr/local/Caskroom/mambaforge/base/condabin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/usr/local/opt/ruby/bin:/usr/local/opt/python@3.11/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/bin:/Users/dmitry/.dotscripts`
  - `SHELL`: `/bin/zsh`
  - `PWD`: `/Users/dmitry/pipenv-bug`

---------------------------

Contents of `Pipfile` ('/Users/dmitry/pipenv-bug/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
bug = {editable = true, path = "."}

[dev-packages]
bug = {editable = true, path = ".", extras = ["dev"]}

```

</details>

**Comment by matteius** [comment]
Only happening for editable installs?

**Comment by dustalov** [comment]
Unfortunately, I have never tried it outside of this scope. I use this configuration to achieve a uniform dependency definition between `pyproject.toml` and Pipenv by defining them only once.

**Comment by dustalov** [comment]
I suspect the new resolver introduced in August 2023 might cause this issue as freezing the Pipenv version to 2023.7.23 helps.

**Comment by matteius** [comment]
@dustalov I believe this branch will resolve your issue:  https://github.com/pypa/pipenv/pull/5919

Also, its the same pip resolver as before, we just eliminated requirementslib as the interface between it and requirements, it reduced the amount of code by 80% and cleaned up a number of bug reports (while breaking a few things in the process, but those have been much easier to patch than it was on requirementslib).

**Comment by dustalov** [comment]
Removing code with only a minor loss of functionality sounds like a big win!

I am currently traveling and will try out the branch this Saturday. Thank you for a quick fix!

**Comment by dustalov** [comment]
I am happy to confirm that the issue has been fixed.
