### ISSUE TITLE
pipenv 2023.8.26 and 2023.9.1 ignore editable=true for vcs install

### ISSUE THREAD

**Issue by dennisvang** [pypa/pipenv#5923]
### Issue description

Pipfile contains a line as follows, to do a vcs install (git) from bitbucket:

```
...

[packages]
mypackage = {git = "ssh://bitbucket.org/my-username/my-package.git", ref = "2023.8", editable = true}

[requires]
python_version = "3.8"
```
Note the `editable = true`.

Using `pipenv` `2023.7.23` this works as expected: the package is installed as editable, and ends up in my `venv/src` directory.

Using `pipenv` `2023.8.26` (and `2023.9.1`), this does not work as expected: the package is installed normally (i.e. not editable), in `venv/lib/python3.8/site-packages`

### Expected result

I would expect the package to be installed into `venv/src`, as described in the [pip docs][1].

### Actual result

Package is built and ends up in `venv/lib/python3.8/site-packages`

### Steps to replicate

Install a package from vcs, using a pipfile similar to the above.

###  References

Possibly related (?): 
- https://github.com/pypa/pipenv/issues/5913
-  https://github.com/pypa/pipenv/issues/5917

[1]: https://pip.pypa.io/en/stable/topics/vcs-support/#editable-vcs-installs

**Comment by matteius** [comment]
Worth checking if still an issue in `2023.9.7` -- it might be, I was under  the impression you can't have an editable vcs install, just local file installs.

**Comment by dennisvang** [comment]
@matteius Thanks for the quick reply.

I uninstalled `mypackage`, upgraded pipenv to `2023.9.7`, and did a `pipenv update` with the original `Pipfile` described above, but it yields a 

```
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. 
...
ERROR: Getting requirements to build wheel exited with 1
```

**Comment by dennisvang** [comment]
>... I was under the impression you can't have an editable vcs install ...

@matteius there is a section in the pip docs: https://pip.pypa.io/en/stable/topics/vcs-support/#editable-vcs-installs

**Comment by matteius** [comment]
The resolution failure you say is on 2023.9.7 only sounds troubling to me but I'd really need more details around it, since the example Pipfile is just an example format.

**Comment by dennisvang** [comment]
@matteius I can provide more detail about the resolution failure for `2023.9.7`, but it *appears* to be unrelated to the present issue.

I verified this by removing the `mypackage` vcs-install line from the Pipfile (see [OP][1]) and attempting a *fresh* `pipenv install`. 

This is on a different (ubuntu) system. The error I'm seeing now is slightly different (both with and without the vcs-install line):

```
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved.
...
ERROR: metadata generation failed
```

Again, the fresh `pipenv install` ***does*** succeed after rolling back pipenv to `2023.9.1`.

Should I open a separate issue for this?

[1]: https://github.com/pypa/pipenv/issues/5923#issue-1886089576

**Comment by matteius** [comment]
@dennisvang Actually that is probably related to:  https://github.com/pypa/pipenv/issues/5924

There is an associated PR that fixes it.   Also I just opened a VCS editable install -- could use help checking it, but it doesn't include the fix for the resolution (two separate PRs right now).

**Comment by matteius** [comment]
@dennisvang I merged the resolver fix into main and into the editable vcs branch to make it easier to verify.   If you can check out the vcs branch and see if its working for your case, that would be helpful for me including it in a 2023.9.8 release (assuming it passes also CI).

**Comment by dennisvang** [comment]
@matteius After a clean install of `pipenv` from the `issue-editable-vcs` branch, I can confirm that both issues appear to be resolved for my case:

- fresh `pipenv install` succeeds without any resolution failure
- editable install of `mypackage` works as expected, i.e. the package is installed into `venv/src`

**Comment by matteius** [comment]
https://pypi.org/project/pipenv/2023.9.8/
