### ISSUE TITLE
Pipenv lock does not resolve local dev package as editable

### ISSUE THREAD

**Issue by Mykhailo-Leskiv** [pypa/pipenv#5952]
### Issue description
If the same local package is specified in both dev-packages and packages sections, but in dev-packages section editable=true flag is set, `pipenv lock` ignores this flag.

### Expected result

The flag "editable": true is added in Pipenv.lock in develop" section

### Actual result

The flag is missing

### Steps to replicate

Create local package and run `pipenv lock`. "Editable" flag won't be present in Pipenv.lock file.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2023.6.18'`

Pipenv location: `'/home/user/.local/lib/python3.10/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

OS Name: `'posix'`

User pip version: `'22.0.2'`

user Python installations found:

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.12',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '6.2.0-33-generic',
 'platform_system': 'Linux',
 'platform_version': '#33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 '
                     '10:33:52 UTC 2',
 'python_full_version': '3.10.12',
 'python_version': '3.10',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `SESSION_MANAGER`
  - `QT_ACCESSIBILITY`
  - `SNAP_REVISION`
  - `XDG_CONFIG_DIRS`
  - `SSH_AGENT_LAUNCHER`
  - `XDG_MENU_PREFIX`
  - `GNOME_DESKTOP_SESSION_ID`
  - `GTK_IM_MODULE`
  - `SNAP_REAL_HOME`
  - `TERMINAL_EMULATOR`
  - `SNAP_USER_COMMON`
  - `LANGUAGE`
  - `LC_ADDRESS`
  - `GNOME_SHELL_SESSION_MODE`
  - `LC_NAME`
  - `SSH_AUTH_SOCK`
  - `TERM_SESSION_ID`
  - `SNAP_INSTANCE_KEY`
  - `XMODIFIERS`
  - `DESKTOP_SESSION`
  - `LC_MONETARY`
  - `BAMF_DESKTOP_FILE_HINT`
  - `GTK_MODULES`
  - `DBUS_STARTER_BUS_TYPE`
  - `SNAP_EUID`
  - `PWD`
  - `XDG_SESSION_DESKTOP`
  - `LOGNAME`
  - `XDG_SESSION_TYPE`
  - `GPG_AGENT_INFO`
  - `SYSTEMD_EXEC_PID`
  - `XAUTHORITY`
  - `DESKTOP_STARTUP_ID`
  - `SNAP_CONTEXT`
  - `WINDOWPATH`
  - `HOME`
  - `USERNAME`
  - `LANG`
  - `LC_PAPER`
  - `LS_COLORS`
  - `XDG_CURRENT_DESKTOP`
  - `SNAP_ARCH`
  - `SNAP_INSTANCE_NAME`
  - `SNAP_USER_DATA`
  - `INVOCATION_ID`
  - `MANAGERPID`
  - `SNAP_REEXEC`
  - `SNAP_UID`
  - `LESSCLOSE`
  - `XDG_SESSION_CLASS`
  - `TERM`
  - `LC_IDENTIFICATION`
  - `LESSOPEN`
  - `USER`
  - `SNAP`
  - `SNAP_COMMON`
  - `SNAP_VERSION`
  - `DISPLAY`
  - `SHLVL`
  - `SNAP_LIBRARY_PATH`
  - `SNAP_COOKIE`
  - `LC_TELEPHONE`
  - `QT_IM_MODULE`
  - `LC_MEASUREMENT`
  - `DBUS_STARTER_ADDRESS`
  - `PAPERSIZE`
  - `SNAP_DATA`
  - `XDG_RUNTIME_DIR`
  - `PS1`
  - `LC_TIME`
  - `FIG_JETBRAINS_SHELL_INTEGRATION`
  - `SNAP_NAME`
  - `JOURNAL_STREAM`
  - `XDG_DATA_DIRS`
  - `PATH`
  - `GDMSESSION`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `LC_NUMERIC`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/user/.amplify/bin:/home/user/.amplify/bin:/home/user/.local/bin:/home/user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/user/pipfile_issue`

---------------------------

Contents of `Pipfile` ('/home/user/pipfile_issue/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
package = {editable = true, path = "./package"}

[packages]
package = {path = "./package"}

[requires]
python_version = "3.8"
```

Contents of `Pipfile.lock` ('/home/user/pipfile_issue/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "db838749edb73b37e05f55cb0bdc2b41208c764a5d4206f441cd5059601fb95f"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "package": {
            "path": "./package"
        }
    },
    "develop": {
        "package": {
            "path": "./package"
        }
    }
}

```
</details>

**Comment by matteius** [comment]
I think this has been fixed, we can revisit if not.
