### ISSUE TITLE
dependency dependant on python version

### ISSUE THREAD

**Issue by coldcoff** [pypa/pipenv#5955]
I have a project running with Python 3.6 - 3.11.

When installing with Python 3.6 and 3.7 it now fails with "flake8", as flake 8 dropped support for Python < 3.8.

So for these old Pythons to work I need to fixate the flake version to be < 6. Easy.
But: On Python >= 3.8 flake8 could be any version, why not use the latest...

I read about markers and tried to write a `Pipfile` to reflect that:

```text
...
flake8 = {markers="python_version < '3.8'", version = "<6"}
flake8 = {markers="python_version >= '3.8'", version = "*"}
...
``` 

but that fails

```text
...
pipenv.vendor.tomlkit.exceptions.KeyAlreadyPresent: Key "flake8" already exists.
```

How to solve that? Can I specify that in one line somehow?
Is there some syntax to specify package versions per python version?

Or should I play with different Pipfiles per Python version?

`PIPENV_PIPFILE=path/to/pipfile pipenv install `

and duplicate the Pipfile(s) in the project?

What's the best practice here?

**Comment by matteius** [comment]
Possibly helpful for what you are trying to do is this prototype PR that allows specifying which python/system information you want the resolver to operate against with respect to markers:  https://github.com/pypa/pipenv/pull/5931

**Comment by matteius** [comment]
Worth noting there is not support to lock different versions of the same package based on python version or system platform -- you basically get the one resolved version.

**Comment by coldcoff** [comment]
Thank you, that PR looks really interesting!

Meanwhile I was able to avoid that "conditional" and solve that indirectly by specifying constraints for older python versions for the problematic sub-dependency only. The resolver does the right thing, then.

That works.

```text
[dev-packages]

flake8 = "*"

# needed for flake8 for Python 3.6 and Python 3.7
importlib-metadata = { version = ">=1.1.0,<4.3", markers = "python_version < '3.8'"}
```

<closing>.
