### ISSUE TITLE
Feature Request: Sort packages alphabetically inside each category

### ISSUE THREAD

**Issue by daveschaefer** [pypa/pipenv#5964]
Hello - Thank you for creating pipenv. It is really interesting and useful. Thanks for putting all of the package and environment management into one place.

What do you think about the idea of sorting package names alphabetically inside each category?

I tried to collect some examples of where else this is done in the python community:

* I see that pipenv itself added alphabetical sorting for the hashes inside the lock file in March 2018 - https://github.com/pypa/pipenv/issues/1529 .
* Both `pip freeze` and `pip list` output their list of packages in a case-insensitive sorted order, and the help docs for each command specifically mention this.
* Tools like `isort` are built specifically to sort and organize packages - https://pycqa.github.io/isort/
* Tutorials like RealPython mention sorting as a best practice - "I like to sort them alphabetically because that makes it easier to find what I am looking for." - https://realpython.com/lessons/requirements-files-best-practices/

I have encountered many python projects and requirements files where the package list is sorted alphabetically for easier readability.
Personally I find package lists easier to read and diff when the names are sorted. It might be nice if `pipenv` took care of this automatically.

From reading through pipenv code, issues, and discussions - my understanding is that this would be only a cosmetic change, and not have any change on the functionality. It appears that pipenv does smart calculations to figure out the correct package installation sequence, and always installs packages in a good working order. Thus sorting the contents of the Pipfile package list should only affect how humans read and use the Pipfile. It would not affect the tool behaviour in any way. Is this correct?

I have a very small working prototype, which I can send a PR for shortly. Simply to start a discussion. (edit: here - https://github.com/pypa/pipenv/pull/5965 )
I realize this might be a drastic change for existing projects that use pipenv, so I thought I would start by filing this Issue to ask.

Thank you for your time.

..

From the Issue template:

> Existing issues 

* pipenv added alphabetical sorting for the hashes inside the lock file in March 2018 - https://github.com/pypa/pipenv/issues/1529 
* Some discussion on ordering here, but closed in Aug 2022 as "may have improved" - https://github.com/pypa/pipenv/issues/2274

> make sure you are running the latest version of Pipenv.

I just cloned the repo today to write a test PR:

```
$ pipenv --version
pipenv, version 2023.10.4.dev0
```

### Is your feature request related to a problem? Please describe.

I find it faster and easier to read a list of python packages if that list is sorted alphabetically by package name.
This also results in smaller diffs when adding new packages or doing code reviews, because it is clear where any package should be added or removed in the list.

Adding sorting as a feature may cause initial pain when a project sorts their list(s) for the first time.
But hopefully after that it will always result in smaller diffs and easier, faster reading and work.

### Describe the solution you'd like

* `pipenv` creates package lists in sorted alphabetical order
* Whenever a package is added to a category, it is inserted in the correct sorted location

### Describe alternatives you've considered

* **Manually sorting Pipfiles.** This is not ideal because it requires regular manual work, and you have to pay extra attention each time to make sure the package goes into the right spot. It may also results in differences across different people working on the same project, since the behaviour is not being consistently and automatically applied. Some people may sort their files. Others may not.
* **Doing nothing. Just living with unsorted Pipfiles.** Obviously this works and the pipenv community has been living with it so far. However it seems like reading or searching through a package list takes longer than it should - I have to grep or look for longer to check whether a package is already in the Pipfile, and where.

### Additional context

-------------------------------------------------------------------------------

> Please run `$ pipenv --support`, and paste the results here.

I ran this but it seems to contain several pieces of personally identifying information. Is it needed for feature requests? I have left it out for now.

**Comment by ff-sp** [comment]
IMHO if this is only done when running Pipenv commands that modify the Pipfile (e.g. `install`, `uninstall`), this shouldn't be disruptive. Other tools (\*couch\* `npm` \*cough\*) do much more to their package definition files than just sorting the packages alphabetically. If someone really wants to sort their packages differently, they can just add them to Pipfile manually and then run `pipenv install` instead of `pipenv install <package>`.
