### ISSUE TITLE
Cannot import editable dependencies from custom directories starting with pipenv 2023.4.20

### ISSUE THREAD

**Issue by alex-pobeditel-2004** [pypa/pipenv#5998]
### Issue description
Hello! Today I decided to update my pipenv and found a problem - my local editable dependencies which are located in separate directory cannot be imported since **pipenv==2023.4.20**.

Example of Pipfile (fully reproducible code example is located below, in **Steps to replicate**):  
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[requires]
python_version = "3.10"

[packages]
example-lib = {editable = "true", path = "/libs/example_lib"}
```

In `pipenv==2023.3.20` and earlier, path `/libs/example_lib` was appended to `sys.path` automatically. Since `2023.4.20` there is no additional entries in `sys.path`.

I want to understand if this is a bug or I use editable packages in a wrong way and on the contrary 2023.4.20 fixed the bug that allowed this to work correctly before.

### Expected result
`example_lib` is imported correctly from the installation

### Actual result
`ModuleNotFoundError: No module named 'example_lib'`

### Steps to replicate
I prepared the minimal example to reproduce the bug in this repo: https://github.com/alex-pobeditel-2004/pipenv-test  
There is no problem with pipenv 2023.3.20 and earlier, issue is reproduced on all new versions since 2023.4.20.  
Issue is reproducible at least in Docker environment with `python:3.10-slim` image.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2023.4.20'`

Pipenv location: `'/opt/venv/lib/python3.10/site-packages/pipenv'`

Python location: `'/opt/venv/bin/python3'`

OS Name: `'posix'`

User pip version: `'23.1'`

user Python installations found:

  - `3.10.13`: `/opt/venv/bin/python3`
  - `3.10.13`: `/opt/venv/bin/python`
  - `3.10.13`: `/usr/local/bin/python`
  - `3.10.13`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.13',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.72-microsoft-standard-WSL2',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Wed Oct 28 23:40:43 UTC 2020',
 'python_full_version': '3.10.13',
 'python_version': '3.10',
 'sys_platform': 'linux'}
```

System environment variables:

  - `HOSTNAME`
  - `PYTHON_PIP_VERSION`
  - `HOME`
  - `GPG_KEY`
  - `PYTHON_GET_PIP_URL`
  - `TERM`
  - `PATH`
  - `LANG`
  - `PYTHON_VERSION`
  - `PYTHON_SETUPTOOLS_VERSION`
  - `PWD`
  - `PYTHON_GET_PIP_SHA256`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/opt/venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/`

---------------------------

</details>

**Comment by matteius** [comment]
I am unfamiliar with any behaviors' that modified the sys.path when using the `--system` flag 🤔

**Comment by alex-pobeditel-2004** [comment]
@matteius So it looks like old behavior was a bug that was fixed (maybe accidentally) in 2023.4.20?  
I use `--system` because of multi-stage build - I copy all installed packages into resulting image to use it as venv. In this case maybe I just should try to achieve this with "usual" userspace package installation.

Or maybe you know how to use libs from custom directories within a` --system` installation?

**Comment by matteius** [comment]
@alex-pobeditel-2004 the `--system` flag is discouraged and one area of pipenv that @oz123 and myself and not spent a lot of time improving upon.   It has become more complicated by things like the latest ubuntu where installing to system packages requires an extra flag for pip, and I think modern pip has also added restrictions about this.   The community is somewhat divided on this, because technically installing and overwriting system packages can break things.  I've seen this first hand, I managed to break the ubuntu gnome terminal using the `--system` flag before in testing because I removed or upgraded some dependencies that the terminal depend on.   I recommend using virtualenv but admittedly the system flag and related reports are something we need to put more thought into going into next year.

**Comment by alex-pobeditel-2004** [comment]
@matteius great thanks for the explanation! ❤️
@oz123 I don't have this build script right now to do experiments and recall it exactly, but I bet that `--system` flag was used before we moved to multi-stage build and it is just a legacy, so now I think that problem can really be solved with usual venv 👍 Thank you, too!

I think issue can be closed now, if you are OK with it.
