### ISSUE TITLE
The Poetry is installing but the llm_app and dependencies are not installing

### ISSUE THREAD

**Issue by Vedansh-05** [pypa/pipenv#5999]
error: command 'cmake' failed: No such file or directory
  

  at ~/.virtualenvs/djangodev/lib/python3.12/site-packages/poetry/installation/chef.py:147 in _prepare
      143│ 
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│ 
      146│             if error is not None:
    → 147│                 raise error from None
      148│ 
      149│             return path
      150│ 
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pyarrow (13.0.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pyarrow (==13.0.0)"'.

This error is being thrown.

**Comment by matteius** [comment]
This is not the poetry project issue tracker.  This is pipenv.

**Comment by Vedansh-05** [comment]
So where do we start to fix it exactly?
