### ISSUE TITLE
Our github CI is using deprecated feature

### ISSUE THREAD

**Issue by matteius** [pypa/pipenv#6015]
### Issue description

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-[11](https://github.com/pypa/pipenv/actions/runs/6870809974/job/18686423909#step:4:12)-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

https://github.com/pypa/pipenv/actions/runs/6870809974/job/18686423909

### Expected result

I don't want this to break one day when we go to publish a release.

**Comment by stumpylog** [comment]
It's probably all from actions/create-release@v1, which is archived and so not updating to new Node or new output methods.  I've been using ncipollo/release-action@v1 with success so far
