### ISSUE TITLE
Date Flag

### ISSUE THREAD

**Issue by padenmoss** [pypa/pipenv#6041]
I am experiencing an issue with pip: There are modules that are too new which are causing inconsistencies with older scripts. Specifying versions for each module is tedious.

When a particular older script was first written pip got the correct modules. Now it doesn't. I know I can set a version with a flag. I do not want users to have issues when time passes.

The solution I imagine is to check a module's timestamp against a date flag then check the version.

Please consider adding a date flag.

**Comment by matteius** [comment]
Sorry, I don't quite understand the issue -- could you elaborate/provide an example?

**Comment by padenmoss** [comment]
Could you tell me where I lost you so I know where to begin?

**Comment by ZenulAbidin** [comment]
If Electrum dependencies are clashing with other packages then you can try installing Electrum inside a [virtualenv](https://docs.python.org/3/library/venv.html).

**Comment by matteius** [comment]
I wish I could tell you where you lost me, yes I have been using Python for 20 years -- so I have definitely run old scripts.    Feel free to open a PR or provide additional concept for what you are trying to accomplish, but recall we drop support for old EOL python versions.
