### ISSUE TITLE
Error when installing own library dependent on another own library

### ISSUE THREAD

**Issue by jbevi** [pypa/pipenv#6046]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

When trying to install its own library (with pipenv 2023.11.15), which in turn uses (among others) its own library, it fails when installing the latter.
This behavior does not occur with version 2023.4.29. I didn't try it with other versions.

### Expected result

Install all libraries.

### Actual result

No matching distribution found for mylibrary1==2.0.4

### Steps to replicate

1.Create library (mylibrary1). Publish in private index.
2.Create the library (mylibrary2) whose 1 of its dependencies is mylibrary1. Publish to the same private index.
3.In a new project, install mylibrary22: pipenv install mylibrary2

-------------------------------------------------------------------------------

**Comment by matteius** [comment]
What does your Pipfile look like -- is the first and default index your private index?  I suspect its pypi or something else and so everything that relates to a secondary index must be specified in the Pipfile.

**Comment by jbevi** [comment]
If it were the pipfile, then it wouldn't work with version 2023.04.29 either or did you change the way it should be configured?

Pipfile of my project:
[pipenv]
install_search_all_sources = true

[[source]]
url = "https://nexus.cloud.com.ar/nexus/repository/pypi-proxy/simple"
verify_ssl = false
name = "pypi"

[[source]]
url = "https://nexus.cloud.com.ar/nexus/repository/infraestructura-pypi/simple"
verify_ssl = false
name = "infra"

[packages]
uvicorn = "==0.23.2"
mylibrary2 = {version = "==0.0.12", index = "infra"}

[dev-packages]
pytest = "==7.4.0"
httpx = "==0.24.1"
locust = "*"

[requires]
python_version = "3.8"

**Comment by jbevi** [comment]
hello. Any news on this ?

**Comment by jbevi** [comment]
Hello.
I'm not sure I understand the comment correctly.
Currently the mylibrary2 library uses many dependencies (oracledb, fastapi and mylibrary among others).
When I use mylibrary2 in a project, it correctly installs all the libraries (with pipenv==2023.4.29).
With the version of pipenv==2023.11.15, it installs all the libraries correctly, except mylibrary.

In the latest versions, do I have to specify to install mylibrary verbatim? I don't like this very much, since developers will have to know which libraries mylibrary2 uses internally, my idea is to simplify this for them.

Note: In my company, we have an index for all the libraries that exist in pypi (it is like a pypi proxy) since we do not have internet access.
Additionally, other libraries we created have their own internal index, such as mylibrary and mylibrary2. That's why in Pipfile I define the two index sources (pypi-proxy and infraestructura-pypi).

**Comment by matteius** [comment]
> Currently the mylibrary2 library uses many dependencies (oracledb, fastapi and mylibrary among others).

It will default all non-specified indexes to the first index, so as long as they mirror pypi, you shouldn't have to re-specify those, but everything from the secondary indexes needs to be called out explicitly at this point in time.   There are notes in our docs about this regarding the secondary package indexes and the recommendation to mirror relevant pypi packages there so it mitigates the need for a secondary index.

**Comment by matteius** [comment]
https://pipenv.pypa.io/en/latest/indexes.html#index-restricted-packages
