### ISSUE TITLE
No way to force pipenv to not install a dependency

### ISSUE THREAD

**Issue by Brian-Taylor8** [pypa/pipenv#6086]
### Is your feature request related to a problem? Please describe.

I'm experiencing a problem where a claimed dependency for a project is not actually needed, and it's installation screws up execution of existing code. Specifically, I'm installing an ML package that has rt-utils as a dependency. One of the listed dependencies for rt-utils is [dataclasses](https://pypi.org/project/dataclasses/). The dataclasses pip package is a backport for python 3.6; it is included in subsequent python versions. For any python version after 3.6, it is at best an unnecessary installation, and at worst it can screw everything up. Basically, it gives me an issue that is 100% solvable by the deletion of the dataclasses package. See [this SO post](https://stackoverflow.com/questions/71991891/pip-gives-an-attributeerror-module-typing-has-no-attribute-classvar) for people experiencing a similar error. It seems that the existence of the separate dataclasses package can sometimes confuse python on windows machines. 

My problem is, **I can't find a way to tell pipenv: "Under no condition should you install the dataclasses package"**. It seems my only option is to manually delete the package in the venv folder(which works), but things get hairy when I send that to other people, as I'd like everything to be in order when they do `pipenv install`. When you try to pipenv uninstall dataclasses, the pipfile will just relock and reinstall dataclasses, as dataclasses is a listed dependency of rt-utils. I put up a PR on rt-utils about removing the dependency for py > 3.6, but it seems valuable for pipenv to have executive power. Note that with pip, you can successfully uninstall a dependency and get around this problem way more easily. Of course, regular pip doesn't have all the advantages pipenv offers.

### Describe the solution you'd like

Perhaps we can add an `uninstall --force` option, or a new: `never-install` option, that can add that package to a list in the pipfile of packages that should never be installed, and wipe it from pipfile.lock and the venv. `pipenv install [specific package]` could override it from that list if somebody did actually want to regain the banished package. Or maybe we would require `pipenv install [specific package] --force` to install a package that was supposed to be not installed. If this is something the maintainers think is worthwhile, I'm happy to take a crack at creating it myself.

### Describe alternatives you've considered

I've considered other workarounds in my project, like creating scripts around pipenv that gets rid of `dataclasses` in my specific project. But I was thinking it might be useful to have this in pipenv itself. I'm early to using pipenv, and wonder if the problem may crop up again.

### Additional context
If there is a way to already force pipenv to get rid of a dependency, please let me know.

**Comment by matteius** [comment]
It looks like `rt-utils` is an active project -- if they had a marker in the requirement of dataclasses that it was only required for python < 3.x (I forgot when dataclasses was first introduced).   That would be the ideal fix, because the pip resolver will continue to get confused by the presence of that constraint otherwise.

**Comment by Brian-Taylor8** [comment]
As far as the first comment: I opened a PR on rt-utils suggesting exactly that; tweaking requirements to only install dataclasses for python version 3.6 or higher. Haven't heard back from them and it looks like the last thing they merged in was 7 months ago so I didn't want to wait around for months to see if they'd approve it or not, but it's there when they are interested in looking at it!

As far as the second comment: Thanks a bunch! That seems to work for me!
