### ISSUE TITLE
`pipenv install` add spurious `"markers": "python_version == '3'"` for a specific library since v2023.12.1, how to fix the library?

### ISSUE THREAD

**Issue by bakert** [pypa/pipenv#6115]
### Issue description

`pipenv install better-profanity` adds `"markers": "python_version == '3'",` to Pipfile.lock. This started happening with pipenv v2023.12.1. The library has not changed, so this comes from a pipenv change. I would like to understand what to fix in better-profanity to avoid this behavior.

### Expected result

`pipenv install better-profanity` makes an entry in Pipfile.lock that is usable

### Actual result

```
            "markers": "python_version == '3'",
```

appears in Pipfile.lock

### Steps to replicate

```
$ pipenv install better-profanity
$ grep -A8 better-profanity Pipfile.lock
        "better-profanity": {
            "hashes": [
                "sha256:8a6fdc8606d7471e7b5f6801917eca98ec211098262e82f62da4f5de3a73145b",
                "sha256:bd4c529ea6aa2db1aaa50524be1ed14d0fe5c664f1fd88c8bc388c7e9f9f00e8"
            ],
            "index": "pypi",
            "markers": "python_version == '3'", <<<< this is the bad line
            "version": "==0.7.0"
        },

```

**Comment by bakert** [comment]
I did some digging into this to see what version of pipenv changed behavior.

Using:

```
export VERSION=2023.8.25 && git checkout . && yes | pip uninstall pipenv && pip install pipenv==$VERSION && pipenv update && grep -A8 better-profanity Pipfile.lock
```

I got the following results:

2023.9.1 bad
2023.8.28 bad
2023.8.26 bad
2023.8.25 FAIL
2023.8.23 FAIL
2023.8.20 FAIL
2023.8.19 FAIL
2023.7.23 good
2023.7.11 good
2023.7.9 good
2023.6.26 good
2023.4.29 good

where FAIL is an error like this:

```
File "/opt/homebrew/lib/python3.11/site-packages/pipenv/utils/dependencies.py", line 620, in find_package_name_from_directory
    os.listdir(directory),
NotADirectoryError: [Errno 20] Not a directory: '/Users/bakert/pd/pipfile'
```

I wonder if the error is some kind of clue about what is going on here.

**Comment by bakert** [comment]
I ended up investigating this in some detail.

I isolated the problem away from my specific scenario. Now I'm just trying to `pipenv install` the better-profanity library in a new project:

```
[dent ~] mkdir test
[dent ~] cd test
[dent test] python3.12 -m venv .
[dent test] source bin/activate          
(test) [dent test] for VERSION in 2023.12.1 2023.9.7 2023.8.28 2023.8.26 2023.8.25 2023.8.23 2023.8.22 2023.8.21 2023.8.20 2023.8.19 2023.7.23 2023.7.11 2023.7.9 2023.7.4 2023.7.3; do {echo $VERSION && \rm Pipfile*; yes | pip uninstall pipenv && pip install pipenv==$VERSION && pipenv install better-profanity && (grep -A8 better-profanity Pipfile.lock | grep -q "python_version == '3'" && echo "$VERSION bad" || echo "$VERSION good") || echo "$VERSION FAIL"} 2>/dev/null | egrep "(good|bad|FAIL)"; done
```

This gives me:

```
2023.12.1 bad
2023.9.7 FAIL
2023.8.28 FAIL
2023.8.26 FAIL
2023.8.25 FAIL
2023.8.23 FAIL
2023.8.22 FAIL
2023.8.21 FAIL
2023.8.20 FAIL
2023.8.19 FAIL
2023.7.23 good
2023.7.11 good
2023.7.9 good
2023.7.4 good
2023.7.3 good
```

The FAIL cases all give me an error like this:

```
  File "/Users/bakert/test/lib/python3.12/site-packages/pipenv/utils/resolver.py", line 812, in venv_resolve_deps
    return prepare_lockfile(
           ^^^^^^^^^^^^^^^^^
  File "/Users/bakert/test/lib/python3.12/site-packages/pipenv/utils/locking.py", line 143, in prepare_lockfile
    lockfile_entry = get_locked_dep(project, dep, pipfile, current_entry)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bakert/test/lib/python3.12/site-packages/pipenv/utils/locking.py", line 126, in get_locked_dep
    lockfile_entry = clean_resolved_dep(project, dep, is_top_level, current_entry)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bakert/test/lib/python3.12/site-packages/pipenv/utils/dependencies.py", line 300, in clean_resolved_dep
    current_entry.update(lockfile)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'String' object has no attribute 'update'
```

Probably needless to say a library like requests installs fine against any of these versions.

So pipenv's handling of something funky about better-profanity changed in 2023.8.19 to the point of crashing `pipenv install`. And then that was fixed up in some way in 2023.12.1 that meant that the bad line now gets added to Pipfile.lock.

**Comment by bakert** [comment]
My guess is in https://github.com/pypa/pipenv/commit/6ac1451ec86d2949855e557109c2eb92b61930fc by @matteius exposed an issue in whatever faulty metadata better-profanity is issuing. Before it was being swallowed/ignored in some way. That change caused it to instead crash pipenv. And then some change in v2023.12.1 stopped the crash, but now causes the bad line to be added to Pipefile.lock.

What might be the cause on the better-profanity side? I'm not sure as I don't really understand how pipenv works. I am guessing that something in the setup.py is not right:

```
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires="==3.*",
```
https://github.com/snguyenthanh/better_profanity/blob/master/setup.py

Maybe the wildcard isn't allowed. Or maybe a bare "3" with no minor version is causing the issue.

Maybe @matteius would be kind enough to take a quick look at this and help out an ignoramus :)

**Comment by matteius** [comment]
@bakert I greatly appreciate the amount of detail you have put into your analysis.    Here is what I can recall:
* The conversion away from requirementslib was pretty good for the happy path, but then came the edge cases.
* One such edge case involved some weird thing requirementslib was doing to pull in hashes/markers for top level dependencies that don't match the system being resolved on.   
* It was kind of a pickle, if I had more time I'd reference some of those issue reports, but I made some decision where sys_markers would continue to try resolving and if it could it would pull the right package data with markers, but if it couldn't then I'd advise users to move the sys markers to regular markers and then it would skip the package.
* This was a mediocre compromise (as was the original implementation), but it kind of resolved those issues, though we still have some issues about people confused by _that_ change in behavior.
* As it related to this issue, with the markers, one thing I learned is the markers comparison logic that we use which I think is in packaging, is quite limited. 
* Off the top of my head I know for sure packaging is don't basic integer comparison on semver, and anything else kind of breaks it.
* Quick check, look around here:  https://github.com/pypa/pipenv/blob/main/pipenv/patched/pip/_vendor/packaging/markers.py#L222-L244

I wish I could put a bit more time into now, but keep probing and I may be able to provide additional details.   There are other issues as it relates to those marker evaluations and dev dependency versions, so it could use more TLC.   I think my priorities are wrapping up the install refactor and some other things and getting the first pipenv 3000 semver release finalized; and if I had even more time I'd like to look at the pythonfinder bug reports/regressions I helped cause (but a proper solution).    Sorry to steal this post a minute for a general update, but I feel that the code base is finally to a point where we can support more Individual Contributions towards improving things -- there were a lot of hurdle to get over with pip-shims, requirementslib being its own repo that had ballooned into a mess, and not deterministic behavior from referencing the system pip prior--all of that has been resolved, and it should be easier than ever to contribute to pipenv, but I don't have a ton of time as of late to take on "everything".

**Comment by matteius** [comment]
I guess the "good" cases mean something else might have been happening in requirementslib, so looking back on that code base may provide more clues on possible improvements to pipenv.

**Comment by bakert** [comment]
Thanks for your comments @matteius . I think the one question I have now is … "is `==3.*` a valid python version specifier?" What follows is a big discussion of what that matters but if you just know the answer to that question, that would be great!

I am coming around to the idea that this might be a pipenv bug rather than an issue with better-profanity's metadata.`packaging` seems to think `==3.*` is a valid specifier, although that code is pretty permissive and not a strict check of the spec I don't think:

```
>>> from packaging.specifiers import Specifier                                                                                                                                                                              >>> "3.1" in Specifier("==3.*")
True
>>> "3.10" in Specifier("==3.*")
True
>>> "2.7" in Specifier("==3.*")
False
```

I've been debugging with a local copy of pipenv today and I've found that in more than one place during resolving of dependencies we take version specifiers and strip off any trailing `.*`. Notably in `markers.normalize_specifier_set` but also in `markers._tuplize_version` and maybe elsewhere too.

`markers.normalize_specifier_set` actually has this comment:

```
    .. note:: This function exists largely to deal with ``pyzmq`` which handles
        the ``requires_python`` specifier incorrectly, using ``3.7*`` rather than
        the correct form of ``3.7.*``.  This workaround can likely go away if
        we ever introduce enforcement for metadata standards on PyPI.
```

I guess it's much more normal to specify something like `==3.1.*` or (more likely) `>=3.1.*` than it is to specify `==3.*` as better-profanity does. But nothing I read in https://packaging.python.org/en/latest/specifications/version-specifiers/#version-specifiers suggests that `==3.*` is not legal. There is even an example that involves `==2.*`.

If we decide that `==3.*` IS a valid identifier that we want to support I can look at making the necessary changes now that I'm passingly familiar with the code. But I guess we should rule on whether we even want that before I do that :)

**Comment by matteius** [comment]
@bakert I believe the workaround is to override the markers in the Pipfile so that it installs -- please see below:

Otherwise the package publisher would need to update their packages default markers:
```
matte@matteius-proart MINGW64 ~/projects/pipenv-triage/issue-6115
$ pipenv install better-profanity
Creating a virtualenv for this project
Pipfile: C:\Users\matte\projects\pipenv-triage\issue-6115\Pipfile
Using default python from C:\Users\matte\AppData\Local\Programs\Python\Python313\python.exe3.13.0 to create virtualenv...
[  ==] Creating virtual environment...created virtual environment CPython3.13.0.final.0-64 in 8770ms
  creator CPython3Windows(dest=C:\Users\matte\.virtualenvs\issue-6115-P366Bbhg, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=C:\Users\matte\AppData\Local\pypa\virtualenv)
    added seed packages: pip==24.2
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Successfully created virtual environment!
Virtualenv location: C:\Users\matte\.virtualenvs\issue-6115-P366Bbhg
Creating a Pipfile for this project...
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Locking [dev-packages] dependencies...
Updated Pipfile.lock (494d5b4f482f0ef471f49afe28f00ec1a2ff75da2ce65060d8cabaeb3da2f100)!
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing better-profanity...
Installation Succeeded
Building requirements...
Resolving dependencies...
Success!
Building requirements...
Resolving dependencies...
Success!
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing dependencies from Pipfile.lock (f48753)...
All dependencies are now up-to-date!
Installing dependencies from Pipfile.lock (f48753)...

matte@matteius-proart MINGW64 ~/projects/pipenv-triage/issue-6115
$ cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
better-profanity = "*"

[dev-packages]

[requires]
python_version = "3.13"

matte@matteius-proart MINGW64 ~/projects/pipenv-triage/issue-6115
$ cat Pipfile.lock
{
    "_meta": {
        "hash": {
            "sha256": "1f0818c03397cae9ca8d519046ab327ffa3ba7659d3e1336d784aeb2baf48753"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.13"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "better-profanity": {
            "hashes": [
                "sha256:8a6fdc8606d7471e7b5f6801917eca98ec211098262e82f62da4f5de3a73145b",
                "sha256:bd4c529ea6aa2db1aaa50524be1ed14d0fe5c664f1fd88c8bc388c7e9f9f00e8"
            ],
            "index": "pypi",
            "markers": "python_version == '3'",
            "version": "==0.7.0"
        }
    },
    "develop": {}
}

matte@matteius-proart MINGW64 ~/projects/pipenv-triage/issue-6115
$ pipenv run pip freeze

matte@matteius-proart MINGW64 ~/projects/pipenv-triage/issue-6115
$ vim Pipfile

matte@matteius-proart MINGW64 ~/projects/pipenv-triage/issue-6115
$ pipenv lock -v
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting()
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('better-profanity'), None)
INFO:pipenv.patched.pip._internal.operations.prepare:Collecting better-profanity (from -r C:\Users\matte\AppData\Local\Temp\pipenv-7x2zseht-requirements\pipenv-9935e7ew-constraints.txt (line 2))
INFO:pipenv.patched.pip._internal.network.download:Using cached better_profanity-0.7.0-py3-none-any.whl.metadata (7.1 kB)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting_round(0)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.pinning(LinkCandidate('https://files.pythonhosted.org/packages/f3/dd/0b074d89e903cc771721cde2c4bf3d8c9d114b5bd791af5c62bcf5fb9459/better
_profanity-0.7.0-py3-none-any.whl (from https://pypi.org/simple/better-profanity/) (requires-python:==3.*)'))
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.ending_round(0, state)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting_round(1)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.ending(State(mapping=OrderedDict({'better-profanity':
LinkCandidate('https://files.pythonhosted.org/packages/f3/dd/0b074d89e903cc771721cde2c4bf3d8c9d114b5bd791af5c62bcf5fb9459/better_profanity-0.7.0-py3-none-any.whl (from https://pypi.org/simple/better-profanity/)
(requires-python:==3.*)')}), criteria={'better-profanity': Criterion((SpecifierRequirement('better-profanity'), via=None))}, backtrack_causes=[]))
INFO:pipenv.patched.pip._internal.network.download:Using cached better_profanity-0.7.0-py3-none-any.whl (46 kB)
[=== ] Locking packages...
Success!
Locking [dev-packages] dependencies...
Updated Pipfile.lock (68c786741e8dcc039f1e92f264953bbbb678c23f8aa33f14398ab5fe1a17955f)!

matte@matteius-proart MINGW64 ~/projects/pipenv-triage/issue-6115
$ pipenv lock -vc^C

matte@matteius-proart MINGW64 ~/projects/pipenv-triage/issue-6115
$ pipenv sync
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Installing dependencies from Pipfile.lock (17955f)...
All dependencies are now up-to-date!

matte@matteius-proart MINGW64 ~/projects/pipenv-triage/issue-6115
$ pipenv run pip freeze
better-profanity==0.7.0

matte@matteius-proart MINGW64 ~/projects/pipenv-triage/issue-6115
$ cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
better-profanity = {version = "*", markers = "python_version=='3.*'"}

[dev-packages]

[requires]
python_version = "3.13"
```

**Comment by bakert** [comment]
Thanks for the update. I do edit Pipfile.lock every time I pipenv install or similar to remove the bad line.

Are you saying that `==3.*` is a valid version specifier that pipenv does not support? Or are you saying that it is an invalid version specifier and the library should change. If you let me know I'll try to fix it in the right place :)

**Comment by matteius** [comment]
I believe this is fixed by #6282

**Comment by bakert** [comment]
Circling back to this rather late in the day I can confirm that when I install a library in my project the better-profanity entry in my Pipfile.lock no longer gets updated to include `"markers": "python_version == '3'"`. I struggled to test it in the manner I described above some months ago so I can't confirm total success, but practically speaking it seems to have done the trick. Thanks!

**Comment by yurii-merker** [comment]
Still an issue
