### ISSUE TITLE
Updating packages with non canonical names errors out

### ISSUE THREAD

**Issue by Kroppeb** [pypa/pipenv#6116]
Seems related to #6056

Running `pipenv update some_cool_package_name` will error out. When using verbose mode the following error can be found:

```
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Cannot install some_cool_package_name because these package versions have conflicting dependencies.
INFO:pipenv.patched.pip._internal.resolution.resolvelib.factory:
The conflict is caused by:
    The user requested some_cool_package_name
    The user requested (constraint) some_cool_package_name
```

**Comment by Kroppeb** [comment]
I suppose this is also an example for #6091 and #6090

**Comment by matteius** [comment]
I think when I removed requirementslib I broke something with canonical naming, and I could use help figuring out the right patch.   There was this, but apparently its still an issue?   https://github.com/pypa/pipenv/pull/6057

**Comment by matteius** [comment]
@Kroppeb could this be checked against `2024.2.0` or even https://github.com/pypa/pipenv/pull/6282
