### ISSUE TITLE
Should Dependabot manually / explicitly call plette for `Pipfile` validation?

### ISSUE THREAD

**Issue by jeffwidman** [pypa/pipenv#6148]
👋 from :dependabot:.

I see `plette` supports validation of `Pipfile`: https://plette.readthedocs.io/en/latest/validation.html

Does this happen automatically within `pipenv`, or does it need to be explicitly called?

Ie, within Dependabot do we need to somewhere call:
```python
from plette import Pipfile

with open("examples/Pipfile.invalid.list") as f:
    pipfile = Pipfile.load(f)
```

Or will simply calling the CLI command `pipenv <command>` automatically result in throwing the validation error?

**Comment by jeffwidman** [comment]
Actually, on second thought, I'd rather we don't have to manually write python code to do validation... it should be hidden behind `pipenv` internals.

I could _maybe_ be convinced we'd need to call `pipenv validate`, but IMO this should happen automatically as the first step of any `pipenv` command so that the implementation is hidden from the caller and all they see are the resulting errors.

**Comment by jeffwidman** [comment]
> The validation is implicitly called when you first load the file. That means that every pipenv operation will read it and validate it.

Awesome, that's exactly how I hoped it'd work.

**Comment by oz123** [comment]
Let me just add a warning. Plette and Pipenv have evolved separately for a while, and pipenv has "undocumented" features which will not be validated with plette. I am working on improving the situation.
