### ISSUE TITLE
Fedora 40 has dropped pipenv

### ISSUE THREAD

**Issue by ProbstDJakob** [pypa/pipenv#6167]
With the release of Fedora 40 the `pipenv` package has been drop. It seems that it has been dropped because it has been orphaned ([see here](https://src.fedoraproject.org/rpms/pipenv/blob/rawhide/f/dead.package)). This means either someone else has to repackage it for Fedora 40+ or the [installation on Fedora part in the README.md](https://github.com/pypa/pipenv/blob/main/README.md?plain=1#L81-L84) has to be removed.

**Comment by magicgoose** [comment]
https://pipenv.pypa.io/en/latest/installation.html#fedora still implies it can be installed (`sudo dnf install pipenv`, no comment)
