### ISSUE TITLE
how can we create a same folder storage without effect other pipenv

### ISSUE THREAD

**Issue by xalteropsx** [pypa/pipenv#6175]
the problem if i set home env the other library will get broken cause they link with c drive local path  i just want to set some pipenv to same folder

**Comment by oz123** [comment]
This seems like an issue with python-dotenv.  I don't really understand what you are trying to do, but if you override the HOME path in .env, it will have unexpected consequences.

**Comment by oz123** [comment]
If I understood you correctly, you are trying to control the location of the virtualenv created by pipenv in the directory of the project or you can create a custom path by setting PIPENV_CUSTOM_VENV_NAME.
You can change the location of the virtualenv by setting environment variables before invoking pipenv for the first time.
There is no way to move a virtualenv to a new location. Once created it's fixed. You need to remove it and create a new one.

**Comment by oz123** [comment]
Before you run `pipenv shell` you. can set environment variables effecting it's behavior.
Please see here how to do this in windows. 

http://xahlee.info/mswin/env_var.html

**Comment by matteius** [comment]
@xalteropsx you look like a kid when you write like this.   We aren't going to help you when you display such an attitude, bad grammar and cannot explain what you are trying to do.
