### ISSUE TITLE
pipenv 2024.0.1 fails under CI on Linux

### ISSUE THREAD

**Issue by command-tab** [pypa/pipenv#6176]
Yesterday's pipenv 2024.0.1 apparently breaks under Linux CI, though not on my macOS development environment. I'm yet not sure what all is different between the two environments that's causing the difference in behavior, but I'm filing this issue to see if this traceback rings a bell about recent changes.

### Issue description

Running `pipenv install --deploy` under CI raises a `VirtualenvCreationException`. This worked on the previous version of pipenv, and I've made no codebase or `Pipfile`/`Pipfile.lock` changes since then.

### Expected result

I expected dependencies to be successfully installed from the lockfile.

### Actual result

```
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
✘ Failed creating virtual environment
[pipenv.exceptions.VirtualenvCreationException]: Exception ignored in: <function BaseFileLock.__del__ at 0x7f6cf438b060>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.11/site-packages/filelock/_api.py", line 365, in __del__
    self.release(force=True)
  File "/opt/app-root/lib64/python3.11/site-packages/virtualenv/util/lock.py", line 34, in release
    with self.thread_safe:
         ^^^^^^^^^^^^^^^^
AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'
```

### Steps to replicate

Here's my Pipfile:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "==3.0.3"
ldap3 = "==2.9.1"
gunicorn = "==22.0.0"

[dev-packages]
bandit = "==1.7.8"
flake8 = "==7.0.0"
pytest = "==8.0.1"
pytest-cov = "==4.1.0"
flask-testing = "==0.8.1"

[requires]
python_version = "3.11"
```

Run `pipenv install --deploy` to (hopefully) reproduce the failure.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>
Pipenv version: `'2024.0.1'`
Pipenv location: `'/opt/app-root/lib64/python3.11/site-packages/pipenv'`
Python location: `'/opt/app-root/bin/python3.11'`
OS Name: `'posix'`
User pip version: `'24.0'`
user Python installations found:
PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.11.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.14.0-362.24.2.el9_3.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT_DYNAMIC Sat Mar 30 14:11:54 EDT 2024',
 'python_full_version': '3.11.2',
 'python_version': '3.11',
 'sys_platform': 'linux'}
```

System environment variables:
  - `PIPENV_VENV_IN_PROJECT`
  - `PYTHONUNBUFFERED`
  - `PLATFORM`
  - `HOSTNAME`
  - `PYTHON_VERSION`
  - `ENV`
  - `PWD`
  - `CNB_STACK_ID`
  - `CNB_GROUP_ID`
  - `container`
  - `NODEJS_VER`
  - `HOME`
  - `SUMMARY`
  - `LANG`
  - `PROMPT_COMMAND`
  - `STI_SCRIPTS_URL`
  - `PIPENV_IGNORE_VIRTUALENVS`
  - `APP_ROOT`
  - `PYTHONIOENCODING`
  - `SHLVL`
  - `BASH_ENV`
  - `CNB_USER_ID`
  - `CA_BUNDLE`
  - `REQUESTS_CA_BUNDLE`
  - `LC_ALL`
  - `AWS_CA_BUNDLE`
  - `PATH`
  - `DESCRIPTION`
  - `STI_SCRIPTS_PATH`
  - `PIP_NO_CACHE_DIR`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
Pipenv–specific environment variables:
 - `PIPENV_VENV_IN_PROJECT`: `1`
 - `PIPENV_IGNORE_VIRTUALENVS`: `1`
Debug–specific environment variables:
  - `PATH`: `/opt/app-root/src/.local/bin/:/opt/app-root/src/bin:/opt/app-root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/opt/app-root/src`
---------------------------
</details>

**Comment by BillJWatts** [comment]
There was an issue with the latest release of filelock `3.15.0`

https://github.com/tox-dev/filelock/issues/337

The version was yanked in the last hour.

**Comment by command-tab** [comment]
The filelock yank resolved this. All is well again. Thanks!
