### ISSUE TITLE
toxic matteius

### ISSUE THREAD

**Issue by xalteropsx** [pypa/pipenv#6194]
you look like a amature when you didnt write anything. we are also not going to talk to no brain who didnt understand even bots can understand better then u 

u might heard of a story a monkey jump on conservation from nowhere when didnt even answer a single line just their to show some politics i dont need ur funny library i will go use other library or create my own library but not gonna use toxic person library 

![image](https://github.com/pypa/pipenv/assets/140290288/401cbccd-7357-4e9c-b676-9cc930df9e1d)

u want a explaination look urself on mirror found worse then human being first improve ur understand else u keep fix on other people grammer between i am ur senior pay respect to me i have more experience then u even amd google and many company invited me 

first of all behave ur attitude and for kind info i dont need ur library i will block ur repo from my account and dont gonna use ur childish work in my project 

even a 5-6 year old kid can understand what i sayed in question but look to me u guys are worse then bots or kids

**Comment by oz123** [comment]
Well, I didn't understand what you wanted. Obviously, we both are not English native. However, my patience also ran out before my English capabilities. Sorry mate.
