### ISSUE TITLE
Pipenv Fails to Install Packages from Public PyPI When Private PyPI is Listed First as Source

### ISSUE THREAD

**Issue by krishnamandanapu1** [pypa/pipenv#6224]
### Issue description

When using Pipenv to manage dependencies, it has been observed that if a private PyPI repository is listed first in the Pipfile as the source, Pipenv fails to install packages that are only available on the public PyPI repository. However, when the public PyPI repository is listed first and the private repository is listed second, Pipenv successfully installs the packages.

### Expected result

Pipenv should correctly install packages from public PyPI, even if a private PyPI repository is listed first in the Pipfile.

### Actual result

Pipenv fails to install packages that are available on public PyPI when the private PyPI repository is listed first as the source.
```
pipenv install
Pipfile.lock (b7d48b) out of date, updating to (7af745)...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
⠧ Locking...False
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement pandas==1.3.5 (from versions: none)
[ResolutionFailure]:   File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/resolver.py", line 646, in _main
[ResolutionFailure]:       pre, clear, verbose, system, write, requirements_dir, packages, category
[ResolutionFailure]:   File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/resolver.py", line 620, in resolve_packages
[ResolutionFailure]:       requirements_dir=requirements_dir,
[ResolutionFailure]:   File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/resolver.py", line 601, in resolve
[ResolutionFailure]:       req_dir=requirements_dir,
[ResolutionFailure]:   File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/utils/resolver.py", line 901, in resolve_deps
[ResolutionFailure]:       req_dir=req_dir,
[ResolutionFailure]:   File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/utils/resolver.py", line 665, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/utils/resolver.py", line 442, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv run pip install <requirement_name> to bypass this mechanism, then run $ pipenv graph to inspect the versions actually installed in the virtualenv.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: No matching distribution found for pandas==1.3.5

Traceback (most recent call last):
  File "/Users/kman/miniconda3/envs/python376/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/cli/command.py", line 225, in install
    skip_lock=state.installstate.skip_lock,
  File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/routines/install.py", line 176, in do_install
    skip_lock=skip_lock,
  File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/routines/install.py", line 654, in do_init
    categories=categories,
  File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/routines/lock.py", line 76, in do_lock
    old_lock_data=old_lock_data,
  File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/utils/resolver.py", line 833, in venv_resolve_deps
    c = resolve(cmd, st, project=project)
  File "/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv/utils/resolver.py", line 702, in resolve
    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!

```

### Steps to Reproduce

1. Create a Pipfile with the private PyPI repository listed first as the source and the public PyPI repository listed second.
2. Add a dependency that is available only on the public PyPI (e.g., requests).
3. Run pipenv install.
4. Observe that Pipenv fails to install the package, possibly with errors indicating that the package cannot be found.
5. Modify the Pipfile to list the public PyPI repository first and the private one second.
6. Run pipenv install again.
7. Observe that the package is now installed correctly.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2023.10.3'`

Pipenv location: `'/Users/kman/miniconda3/envs/python376/lib/python3.7/site-packages/pipenv'`

Python location: `'/Users/kman/miniconda3/envs/python376/bin/python'`

OS Name: `'posix'`

User pip version: `'23.2.1'`

user Python installations found:

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '23.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT '
                     '2024; root:xnu-10063.141.2~1/RELEASE_X86_64',
 'python_full_version': '3.7.6',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `COLORTERM`
  - `COMMAND_MODE`
  - `HOME`
  - `LANG`
  - `LOGNAME`
  - `LaunchInstanceID`
  - `PATH`
  - `SECURITYSESSIONID`
  - `SHELL`
  - `SSH_AUTH_SOCK`
  - `SSH_SOCKET_DIR`
  - `TERM`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `TMPDIR`
  - `USER`
  - `WARP_COMBINED_PROMPT_COMMAND_GRID`
  - `WARP_HONOR_PS1`
  - `WARP_IS_LOCAL_SHELL_SESSION`
  - `WARP_USE_SSH_WRAPPER`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `__CFBundleIdentifier`
  - `__CF_USER_TEXT_ENCODING`
  - `SHLVL`
  - `PWD`
  - `OLDPWD`
  - `CONDA_EXE`
  - `_CE_M`
  - `_CE_CONDA`
  - `CONDA_PYTHON_EXE`
  - `CONDA_SHLVL`
  - `CONDA_PREFIX`
  - `CONDA_DEFAULT_ENV`
  - `CONDA_PROMPT_MODIFIER`
  - `CONDA_CHANGEPS1`
  - `CONDA_PREFIX_1`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/kman/miniconda3/envs/python376/bin:/Users/kman/miniconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/kman/Library/Application Support/JetBrains/Toolbox/scripts`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/kman/workspace/dummy_repo`

---------------------------

Contents of `Pipfile` ('/Users/kman/workspace/dummy_repo/Pipfile'):

```toml
[[source]]
name = "private-pypi"
url = "http://<IP>:<port>/simple"
verify_ssl = false

[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
pandas = "==1.3.5"
simplepytools = {version = "*", index = "private-pypi"}

[dev-packages]

[requires]
python_version = "3.7"
```

Contents of `Pipfile.lock` ('/Users/kman/workspace/dummy_repo/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "74f80cc210782bb033bb7257ebffc5df57edd494a136991b31cc0429f9f66d29"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_full_version": "3.7.6",
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

**Comment by krishnamandanapu1** [comment]
It worked when I added the index to package
```
[packages] 
simplepytools = {version = "*", index = "private-pypi"}
```

**Comment by matteius** [comment]
This is by design -- to solve security concerns we are index restricting the packages, so when not specified, it uses the first source of the Pipfile as the default, otherwise each package that is to be pulled from an alternative index must be specified.  See also:  https://pipenv.pypa.io/en/latest/indexes.html#index-restricted-packages

**Comment by krishnamandanapu1** [comment]
@matteius Thank you for clarification!
