### ISSUE TITLE
Github Token not added to Piplock file for github repos, which fails installation 

### ISSUE THREAD

**Issue by nakulsingh1299** [pypa/pipenv#6256]
### Issue description

Version 2024.0.3 
I use private Github repos as a utility in my backend service code.

Pipfile 
utility = {ref = "1.0.0", git = "https://${GITHUB_TOKEN}@github.com/org/Utilities"}

where GITHUB_TOKEN is an environment variable
When I lock my Pipfile using the latest version, it does not add the GitHub token in the Piplock file and it is not able to fetch the private packages from GitHub while installing dependencies 

### Expected result
Previous Piplock file
```json
"utility": {
            "git": "https://${GITHUB_TOKEN}@github.com/org/Utilities",
            "ref": "commit-id"
 }
```

### Actual result
```json
"utility": {
            "git": "github.com/org/Utilities",
            "ref": "commit-id"
 }
```

### Steps to replicate
1. Create a pip file with any private Github repo as a package
2. Run below command
pipenv install --dev

### Output
```
Installing dependencies from Pipfile.lock (38058a)...
: ERROR: Invalid requirement: 'utility@ git+github.com/org/Utilities@commit-id' (from line 1 of /tmp/pipenv-dntff654-requirements/pipenv-ig2fc_8d-reqs.txt)
: Hint: It looks like a path. File 'utility@ git+github.com/org/Utilities@commit-id' does not exist.
ERROR: Couldn't install package: [1m{}[0m
```

**Comment by julio-tl** [comment]
+1

**Comment by matteius** [comment]
Could you help check on https://github.com/pypa/pipenv/pull/6257 to see if it resolves the problem?

**Comment by julio-tl** [comment]
Hi @matteius  https://github.com/pypa/pipenv/pull/6257 worked for me, thanks for looking into this
