### ISSUE TITLE
2024.3.0 update regressions

### ISSUE THREAD

**Issue by mcsloe** [pypa/pipenv#6299]
### Issue description

We use pipenv here to manage requirements.

I noticed a few issues with the 2024.3.0 release today.
- pipenv update no longer works if Pipfile.lock is missing, returns error “ERROR: Pipfile.lock not found! You need to run $ pipenv lock before you can continue.”
- pipenv update changes Pipfile, adding a new [[source]] section

### Expected result

pipenv update works if Pipfile.lock is missing.

### Actual result

ERROR: Pipfile.lock not found! You need to run $ pipenv lock before you can continue.

### Steps to replicate

delete Pipfile.lock
run pipenv update

**Comment by GuillermoFarias** [comment]
The same error

**Comment by qnelo** [comment]
with version 2024.2.0 it works fine, with version 2024.2.0 it breaks. I had to fix the version so it doesn't break.

```
25.47 Loading .env environment variables...
 Traceback (most recent call last):
   File "/usr/local/bin/pipenv", line 8, in <module>
     sys.exit(cli())
              ^^^^^
   File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1157, in __call__
     return self.main(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/pipenv/cli/options.py", line 52, in main
     return super().main(*args, **kwargs, windows_expand_args=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1078, in main
     rv = self.invoke(ctx)
          ^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1688, in invoke
     return _process_result(sub_ctx.command.invoke(sub_ctx))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1434, in invoke
     return ctx.invoke(self.callback, **ctx.params)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
     return __callback(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 92, in new_func
     return ctx.invoke(f, obj, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
     return __callback(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/pipenv/cli/command.py", line 207, in install
     do_install(
   File "/usr/local/lib/python3.11/site-packages/pipenv/routines/install.py", line 309, in do_install
     new_packages, _ = handle_new_packages(
                       ^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/pipenv/routines/install.py", line 114, in handle_new_packages
     do_update(
   File "/usr/local/lib/python3.11/site-packages/pipenv/routines/update.py", line 51, in do_update
     ensure_project(
   File "/usr/local/lib/python3.11/site-packages/pipenv/utils/project.py", line 96, in ensure_project
     os.environ["PIP_PYTHON_PATH"] = project.python(system=system)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/pipenv/project.py", line 1418, in python
     return project_python(self, system=system)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/pipenv/utils/shell.py", line 408, in project_python
     python = project._which("python")
              ^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/pipenv/project.py", line 1427, in _which
     raise RuntimeError("location not created nor specified")
 RuntimeError: location not created nor specified
```

**Comment by thisjulio** [comment]
> with version 2024.2.0 it works fine, with version 2024.2.0 it breaks. I had to fix the version so it doesn't break.
> 
> ```
> 25.47 Loading .env environment variables...
>  Traceback (most recent call last):
>    File "/usr/local/bin/pipenv", line 8, in <module>
>      sys.exit(cli())
>               ^^^^^
>    File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1157, in __call__
>      return self.main(*args, **kwargs)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "/usr/local/lib/python3.11/site-packages/pipenv/cli/options.py", line 52, in main
>      return super().main(*args, **kwargs, windows_expand_args=False)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1078, in main
>      rv = self.invoke(ctx)
>           ^^^^^^^^^^^^^^^^
>    File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1688, in invoke
>      return _process_result(sub_ctx.command.invoke(sub_ctx))
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1434, in invoke
>      return ctx.invoke(self.callback, **ctx.params)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
>      return __callback(*args, **kwargs)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 92, in new_func
>      return ctx.invoke(f, obj, *args, **kwargs)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "/usr/local/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
>      return __callback(*args, **kwargs)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "/usr/local/lib/python3.11/site-packages/pipenv/cli/command.py", line 207, in install
>      do_install(
>    File "/usr/local/lib/python3.11/site-packages/pipenv/routines/install.py", line 309, in do_install
>      new_packages, _ = handle_new_packages(
>                        ^^^^^^^^^^^^^^^^^^^^
>    File "/usr/local/lib/python3.11/site-packages/pipenv/routines/install.py", line 114, in handle_new_packages
>      do_update(
>    File "/usr/local/lib/python3.11/site-packages/pipenv/routines/update.py", line 51, in do_update
>      ensure_project(
>    File "/usr/local/lib/python3.11/site-packages/pipenv/utils/project.py", line 96, in ensure_project
>      os.environ["PIP_PYTHON_PATH"] = project.python(system=system)
>                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "/usr/local/lib/python3.11/site-packages/pipenv/project.py", line 1418, in python
>      return project_python(self, system=system)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    File "/usr/local/lib/python3.11/site-packages/pipenv/utils/shell.py", line 408, in project_python
>      python = project._which("python")
>               ^^^^^^^^^^^^^^^^^^^^^^^^
>    File "/usr/local/lib/python3.11/site-packages/pipenv/project.py", line 1427, in _which
>      raise RuntimeError("location not created nor specified")
>  RuntimeError: location not created nor specified
> ```

Same error here.

**Comment by danilodesolesonar** [comment]
hello, we also use `pipenv` to manage our python dependencies. We noticed that `pipenv install --dev --skip-lock` no longer install dependencies. We do not have and use the lock file. Before, up to version `2024.0.1.` the same command resulted in successful dependencies installation.

**Comment by danilodesolesonar** [comment]
> hello, we also use `pipenv` to manage our python dependencies. We noticed that `pipenv install --dev --skip-lock` no longer install dependencies. We do not have and use the lock file. Before, up to version `2024.0.1.` the same command resulted in successful dependencies installation.

I opened a dedicated bug for this https://github.com/pypa/pipenv/issues/6301, please check if this one is related.

**Comment by matteius** [comment]
I believe I have the issue @mcsloe reported resolved by https://github.com/pypa/pipenv/pull/6300 but I could use help beyond the tests I added verifying it meets expectations.

@danilodesolesonar I believe your issue is separate and related to a prior version being installed -- I commented in your ticket, lets follow up there.

**Comment by matteius** [comment]
`2024.3.1` has been released -- it took some fiddling and I think there are some future improvements to upgrade to be able to detect which Pipfile specifiers are actually worth considering being upgraded, but for now should fixe the breakages.   Fwiw, if you actually want to upgrade packages to commit to the lockfile, you are best passing the specifier to the upgrade command for now.
